### ISSUE TITLE
issues installing takana, or any other module

### ISSUE THREAD

**Issue by alexadark** [npm/npm#7533]
```
alexandras-iMac:~ alexadark$ npm install -g takana
npm WARN locking Error: EACCES, open '/Users/alexadark/.npm/_locks/takana-6d627042bd4fa4f7.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/alexadark/.npm/_locks/takana-6d627042bd4fa4f7.lock failed { [Error: EACCES, open '/Users/alexadark/.npm/_locks/takana-6d627042bd4fa4f7.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/alexadark/.npm/_locks/takana-6d627042bd4fa4f7.lock' }
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "takana"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! Attempt to unlock /usr/local/lib/node_modules/takana, which hasn't been locked
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/alexadark/npm-debug.log
alexandras-iMac:~ alexadark$
```
same thing for gulp:
```
alexandras-iMac:~ alexadark$ npm install --save-dev gulp
npm WARN package.json alexadark@1.0.0 No description
npm WARN package.json alexadark@1.0.0 No repository field.
npm WARN package.json alexadark@1.0.0 No README data
npm WARN locking Error: EACCES, open '/Users/alexadark/.npm/_locks/gulp-6053d63b9c3ef9ba.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/alexadark/.npm/_locks/gulp-6053d63b9c3ef9ba.lock failed { [Error: EACCES, open '/Users/alexadark/.npm/_locks/gulp-6053d63b9c3ef9ba.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/alexadark/.npm/_locks/gulp-6053d63b9c3ef9ba.lock' }
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "--save-dev" "gulp"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! Attempt to unlock /Users/alexadark/node_modules/gulp, which hasn't been locked
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/alexadark/npm-debug.log
```

**Comment by KenanY** [comment]
@alexadark Looks like you have lost permissions to modify the contents of `~/.npm`, the cache folder. Could you try taking back ownership?:

``` sh
$ sudo chown -R $(whoami) "$HOME/.npm"
```

**Comment by alexadark** [comment]
Thank you KenanY, but still a mess (i am very bad with command line!)

alexandras-iMac:~ alexadark$ sudo chown -R $(whoami) "$HOME/.npm"
Password:
alexandras-iMac:~ alexadark$ sudo chown -R $(whoami) "$HOME/.npm"
alexandras-iMac:~ alexadark$ npm install -g takana
npm ERR! tar.unpack untar error /Users/alexadark/.npm/takana/0.4.2/package.tgz
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "takana"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! path /usr/local/lib/node_modules/takana
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, mkdir '/usr/local/lib/node_modules/takana'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, mkdir '/usr/local/lib/node_modules/takana']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/takana',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/takana',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack:
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53',
npm ERR!      'FSReqWrap.oncomplete (fs.js:99:15)' ] }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/alexadark/npm-debug.log

**Comment by KenanY** [comment]
@alexadark Since you have it set up so that global modules go to `/usr/local`, you'll need to use `sudo` when you install global modules.

**Comment by alexadark** [comment]
Thanks but continue not working :-(

alexandras-iMac:~ alexadark$ sudo chown -R $(whoami) "$HOME/.npm"
Password:
alexandras-iMac:~ alexadark$ sudo npm install -g takana

> fsevents@0.3.0 install /usr/local/lib/node_modules/takana/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/Users/alexadark/.node-gyp/0.12.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/takana/node_modules/chokidar/node_modules/fsevents/.node-gyp"
child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
In file included from ../node_modules/nan/nan.h:177:
In file included from /usr/local/lib/node_modules/takana/node_modules/chokidar/node_modules/fsevents/.node-gyp/0.12.0/deps/uv/include/uv.h:48:
/usr/local/lib/node_modules/takana/node_modules/chokidar/node_modules/fsevents/.node-gyp/0.12.0/deps/uv/include/uv-errno.h:25:10: fatal error:
      'errno.h' file not found
#include <errno.h>
         ^
1 error generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/takana/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok

> websocket@1.0.17 install /usr/local/lib/node_modules/takana/node_modules/websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
npm WARN optional dep failed, continuing fsevents@0.3.0

> node-sass@1.0.3 install /usr/local/lib/node_modules/takana/node_modules/node-sass
> node build.js

child_process: customFds option is deprecated, use stdio instead.
gyp WARN EACCES user "root" does not have permission to access the dev dir "/Users/alexadark/.node-gyp/0.12.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/takana/node_modules/node-sass/.node-gyp"

**Comment by othiym23** [comment]
@alexadark one more thing you could try is `sudo npm install -g takana --unsafe-perm`. In general, as the name implies, this isn't a safe option to use, but `node-gyp` (the package that npm uses to build native modules that have components written in C and C++) and npm are disagreeing about what permissions they need to do their jobs.

My guess is that this can be fixed by first installing `takana` locally *without* sudo (`npm install takana` in a subdirectory of your home directory, for example), and then trying to install it globally again *with* sudo.  The first time `node-gyp` builds a native module with a given version of Node.js or io.js, it has to download a set of C headers that tell it what the native module API looks like. Because by default npm drops permissions for child processes like `node-gyp` (for safety's sake), it's trying to write to `~/.node-gyp` as the user `nobody` and failing.

Hope this helps, and hang in there! You're making progress!

**Comment by alexadark** [comment]
nothing works, and as i really don't understand how it works, i can just copy and paste instruction
so first i tried to install it locally on my deskto just to see

and then i tried the unsafe perm

With my ex computer (macbook pro, now i have a new imac) the install worked, but don't succeed to use it with wordpress ( i talk about takana)

alexandras-iMac:Desktop alexadark$ npm install takana
npm WARN package.json alexadark@1.0.0 No description
npm WARN package.json alexadark@1.0.0 No repository field.
npm WARN package.json alexadark@1.0.0 No README data

> fsevents@0.3.0 install /Users/alexadark/node_modules/takana/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
In file included from ../node_modules/nan/nan.h:177:
In file included from /Users/alexadark/.node-gyp/0.12.0/deps/uv/include/uv.h:48:
/Users/alexadark/.node-gyp/0.12.0/deps/uv/include/uv-errno.h:25:10: fatal error:
      'errno.h' file not found
#include <errno.h>
         ^
1 error generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/alexadark/node_modules/takana/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok

> websocket@1.0.17 install /Users/alexadark/node_modules/takana/node_modules/websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
npm WARN optional dep failed, continuing fsevents@0.3.0

> node-sass@1.0.3 install /Users/alexadark/node_modules/takana/node_modules/node-sass
> node build.js

child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/binding/binding.o
In file included from ../binding.cpp:1:
In file included from ../node_modules/nan/nan.h:22:
In file included from /Users/alexadark/.node-gyp/0.12.0/deps/uv/include/uv.h:48:
/Users/alexadark/.node-gyp/0.12.0/deps/uv/include/uv-errno.h:25:10: fatal error:
      'errno.h' file not found
#include <errno.h>
         ^
1 error generated.
make: *** [Release/obj.target/binding/binding.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/alexadark/node_modules/takana/node_modules/node-sass
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
Build failed
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "takana"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! node-sass@1.0.3 install: `node build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@1.0.3 install script 'node build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/alexadark/Desktop/npm-debug.log
alexandras-iMac:Desktop alexadark$ sudo npm install -g takana --unsafe-perm
Password:

> fsevents@0.3.0 install /usr/local/lib/node_modules/takana/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
In file included from ../node_modules/nan/nan.h:177:
In file included from /Users/alexadark/.node-gyp/0.12.0/deps/uv/include/uv.h:48:
/Users/alexadark/.node-gyp/0.12.0/deps/uv/include/uv-errno.h:25:10: fatal error:
      'errno.h' file not found
#include <errno.h>
         ^
1 error generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/takana/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok

> websocket@1.0.17 install /usr/local/lib/node_modules/takana/node_modules/websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
npm WARN optional dep failed, continuing fsevents@0.3.0
/
> node-sass@1.0.3 install /usr/local/lib/node_modules/takana/node_modules/node-sass
> node build.js

child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/binding/binding.o
In file included from ../binding.cpp:1:
In file included from ../node_modules/nan/nan.h:22:
In file included from /Users/alexadark/.node-gyp/0.12.0/deps/uv/include/uv.h:48:
/Users/alexadark/.node-gyp/0.12.0/deps/uv/include/uv-errno.h:25:10: fatal error:
      'errno.h' file not found
#include <errno.h>
         ^
1 error generated.
make: *** [Release/obj.target/binding/binding.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/takana/node_modules/node-sass
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
Build failed
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "takana" "--unsafe-perm"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! node-sass@1.0.3 install: `node build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@1.0.3 install script 'node build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/alexadark/Desktop/npm-debug.log
alexandras-iMac:Desktop alexadark$

**Comment by othiym23** [comment]
```
/Users/alexadark/.node-gyp/0.12.0/deps/uv/include/uv-errno.h:25:10: fatal error:
      'errno.h' file not found
#include <errno.h>
         ^
1 error generated.
```

This is the error you get when you try to build npm modules with native dependencies but don't have Xcode or the Apple developer command-line tools installed (it's documented in a few places that you need to have these tools involved, but not anywhere obvious). Can you install Xcode and try again?

**Comment by alexadark** [comment]
Thanks, Xcode was the problem, i was install but bad, si desinstall and reinstall and bow everything works :-)

**Comment by othiym23** [comment]
Great! I'm going to close this issue as resolved now. Good luck getting started with npm and takana!

**Comment by alexadark** [comment]
Well, if that's outside of the scope here, but do you know if takana works with codekit..it don't work for me, do i need to use grunt absolutely ( and i work with wordpress)

**Comment by othiym23** [comment]
I don't know, unfortunately, because I haven't used takana myself. Ask over on their issue tracker, maybe?
