### ISSUE TITLE
Install yeoman behide corporate firewall

### ISSUE THREAD

**Issue by samastshi** [npm/npm#7536]
I cant install anything using npm this is what it says: 

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'grunt-cli' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 silly cache add args [ 'grunt-cli', null ]
6 verbose cache add spec grunt-cli
7 silly cache add parsed spec { raw: 'grunt-cli',
7 silly cache add   scope: null,
7 silly cache add   name: 'grunt-cli',
7 silly cache add   rawSpec: '',
7 silly cache add   spec: '*',
7 silly cache add   type: 'range' }
8 verbose addNamed grunt-cli@*
9 silly addNamed semver.valid null
10 silly addNamed semver.validRange *
11 silly addNameRange { name: 'grunt-cli', range: '*', hasData: false }
12 silly mapToRegistry name grunt-cli
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/grunt-cli
16 verbose addNameRange registry:https://registry.npmjs.org/grunt-cli not in flight; fetching
17 verbose request uri https://registry.npmjs.org/grunt-cli
18 verbose request no auth needed
19 info attempt registry request try #1 at 16:37:52
20 verbose request id ebc2907eccdad5ac
21 http request GET https://registry.npmjs.org/grunt-cli
22 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN
23 info attempt registry request try #2 at 16:38:14
24 http request GET https://registry.npmjs.org/grunt-cli
25 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN
26 info attempt registry request try #3 at 16:39:26
27 http request GET https://registry.npmjs.org/grunt-cli
28 verbose stack Error: getaddrinfo EAI_AGAIN
28 verbose stack     at Object.exports._errnoException (util.js:746:11)
28 verbose stack     at errnoException (dns.js:49:15)
28 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)
29 verbose cwd C:\Users\m.mossadek
30 error Windows_NT 6.1.7601
31 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "grunt-cli"
32 error node v0.12.0
33 error npm  v2.5.1
34 error code EAI_AGAIN
35 error errno EAI_AGAIN
36 error syscall getaddrinfo
```

Thanks

**Comment by smikes** [comment]
Have you told `npm` about your proxy?  Depending on what the corporate proxy is, it may be enough to write

`npm set proxy http://proxy.host.com:3128`

Or you may have to set up a local proxy (e.g., `cntlm`).  See also this issue comment <https://github.com/npm/npm/issues/7156#issuecomment-70252268> for how to see what your proxy settings are from the command line in Windows.

**Comment by samastshi** [comment]
Thank you very much

Le mercredi 4 mars 2015, Sam Mikes <notifications@github.com> a écrit :

> Have you told npm about your proxy? Depending on what the corporate proxy
> is, it may be enough to write
>
> npm set proxy http://proxy.host.com:3128
>
> Or you may have to set up a local proxy (e.g., cntlm). See also this
> issue comment #7156 (comment)
> <https://github.com/npm/npm/issues/7156#issuecomment-70252268> for how to
> see what your proxy settings are from the command line in Windows.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/npm/npm/issues/7536#issuecomment-77199958>.
>


-- 
----
Mosaddeq Mohammed

**Comment by SCWR** [comment]
npm ERR! Linux 2.6.18-194.el5
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "supervisor"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! syscall getaddrinfo

npm ERR! getaddrinfo EAI_AGAIN
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log

It happened in my redhat system,

**Comment by SCWR** [comment]
It happened in my redhat system, @smikes

**Comment by iarna** [comment]
I'm closing this as @samastshi's issue seems to be resolved. @SCWR have you tried the solution @smikes posted? If you're still having problems I encourage you to open a new issue.
