### ISSUE TITLE
socket.io install failing

### ISSUE THREAD

**Issue by skoontz** [npm/npm#7540]
I can't seem to get socket.io installed.  Can you point me in the right direction? thanks

```
npm install socket.io --msvs_version=2013

npm WARN package.json athenaServerHttps@0.0.4 No repository field.
npm http GET http://registry.npmjs.org/socket.io
npm http 200 http://registry.npmjs.org/socket.io
npm ERR! Error: No compatible version found: socket.io@'^1.0.6'
npm ERR! Valid install targets:
npm ERR! ["0.3.8","0.4.0","0.4.1","0.5.1","0.5.3","0.6.0","0.6.1","0.6.3","0.6.4
","0.6.5","0.6.6","0.6.7","0.6.8","0.6.9","0.6.10","0.6.11","0.6.12","0.6.14","0
.6.15","0.6.16","0.6.17","0.6.18","0.7.0","0.7.1","0.7.2","0.7.3","0.7.4","0.7.5
","0.7.6","0.7.7","0.7.8","0.7.9","0.7.10","0.7.11","0.8.0","0.8.1","0.8.2","0.8
.3","0.8.4","0.8.5","0.8.6","0.8.7","0.9.0","0.9.1","0.9.1-1","0.9.2","0.9.3","0
.9.4","0.9.5","0.9.6","0.9.7","0.9.8","0.9.9","0.9.10","0.9.11","0.9.12","0.9.13
","0.9.14","0.9.15","0.9.16","1.0.0-pre","1.0.0-pre2","1.0.0-pre3","1.0.0-pre4",
"1.0.0-pre5","0.9.17","1.0.0","1.0.1","1.0.2","1.0.3","1.0.4","1.0.5","1.0.6","1
.1.0","1.2.0","1.2.1","1.3.0","1.3.1","1.3.2","1.3.3","1.3.4","1.3.5"]
npm ERR!     at installTargetsError (C:\Program Files\StrongLoop Node\node_modul
es\npm\lib\cache.js:719:10)
npm ERR!     at C:\Program Files\StrongLoop Node\node_modules\npm\lib\cache.js:6
38:10
npm ERR!     at saved (C:\Program Files\StrongLoop Node\node_modules\npm\node_mo
dules\npm-registry-client\lib\get.js:142:7)
npm ERR!     at C:\Program Files\StrongLoop Node\node_modules\npm\node_modules\g
raceful-fs\polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\StrongLoop Node\\\\node.exe" "C:\\Program F
iles\\StrongLoop Node\\node_modules\\npm\\bin\\npm-cli.js" "install" "socket.io"
 "--msvs_version=2013"
npm ERR! cwd C:\node\Athena12
npm ERR! node -v v0.10.16
npm ERR! npm -v 1.3.5
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\node\Athena12\npm-debug.log
npm ERR! not ok code 0
```

**Comment by faiq** [comment]
Hey! Sorry to hear you're having this problem. I think you can resolve it fairly easily by upgrading your versions of node and npm

```
npm ERR! cwd C:\node\Athena12
npm ERR! node -v v0.10.16
npm ERR! npm -v 1.3.5
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR! C:\node\Athena12\npm-debug.log
npm ERR! not ok code 0
```

The error logs shows the version of node and npm are really old (I think about 2 years old at this point) 

The easiest way you can upgrade them is to go on nodejs.org and us the installer! 

Let us know if this works for you.

**Comment by skoontz** [comment]
I upgraded now I get this error: (MSB8007)  Do you know what can be wrong?
Thanks

C:\node\Athena12>npm install socket.io --msvs_version=2013
\


> ws@0.5.0 install C:\node\Athena12\node_modules\socket.io
\node_modules\engine.i
o\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

|
C:\node\Athena12\node_modules\socket.io\node_modules\engine.io
\node_modules\ws>n
ode "C:\Program
Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modul
es\node-gyp\bin\node-gyp.js" rebuild
Building the projects in this solution one at a time. To enable parallel
build,
please add the "/m" switch.
C:\Program Files
(x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform
.Targets(23,7): error MSB8007: The Platform for project
'bufferutil.vcxproj' is
 invalid.  Platform='x64'. You may be seeing this message because you are
tryin
g to build a project without a solution file, and have specified a
non-default
Platform that doesn't exist for this project.
[C:\node\Athena12\node_modules\so
cket.io\node_modules\engine.io\node_modules\ws\build\bufferutil.vcxproj]
C:\Program Files
(x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform
.Targets(23,7): error MSB8007: The Platform for project
'validation.vcxproj' is
 invalid.  Platform='x64'. You may be seeing this message because you are
tryin
g to build a project without a solution file, and have specified a
non-default
Platform that doesn't exist for this project.
[C:\node\Athena12\node_modules\so
cket.io\node_modules\engine.io\node_modules\ws\build\validation.vcxproj]

> ws@0.4.31 install C:\node\Athena12\node_modules\socket.io
\node_modules\socket.
io-client\node_modules\engine.io-client\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)


C:\node\Athena12\node_modules\socket.io
\node_modules\socket.io-client\node_modul
es\engine.io-client\node_modules\ws>node "C:\Program
Files\nodejs\node_modules\n
pm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
Building the projects in this solution one at a time. To enable parallel
build,
please add the "/m" switch.
C:\Program Files
(x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform
.Targets(23,7): error MSB8007: The Platform for project
'bufferutil.vcxproj' is
 invalid.  Platform='x64'. You may be seeing this message because you are
tryin
g to build a project without a solution file, and have specified a
non-default
Platform that doesn't exist for this project.
[C:\node\Athena12\node_modules\so
cket.io
\node_modules\socket.io-client\node_modules\engine.io-client\node_module
s\ws\build\bufferutil.vcxproj]
C:\Program Files
(x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform
.Targets(23,7): error MSB8007: The Platform for project
'validation.vcxproj' is
 invalid.  Platform='x64'. You may be seeing this message because you are
tryin
g to build a project without a solution file, and have specified a
non-default
Platform that doesn't exist for this project.
[C:\node\Athena12\node_modules\so
cket.io
\node_modules\socket.io-client\node_modules\engine.io-client\node_module
s\ws\build\validation.vcxproj]
socket.io@1.3.5 node_modules\socket.io
├── debug@2.1.0 (ms@0.6.2)
├── has-binary-data@0.1.3 (isarray@0.0.1)
├── socket.io-adapter@0.3.1 (object-keys@1.0.1, debug@1.0.2,
socket.io-parser@2.
2.2)
├── socket.io-parser@2.2.4 (isarray@0.0.1, debug@0.7.4,
component-emitter@1.1.2,
 benchmark@1.0.0, json3@3.2.6)
├── engine.io@1.5.1 (base64id@0.1.0, debug@1.0.3, engine.io-parser@1.2.1,
ws@0.5
.0)
└── socket.io-client@1.3.5 (to-array@0.1.3, indexof@0.0.1,
component-bind@1.0.0,
 debug@0.7.4, backo2@1.0.2, object-component@0.0.3, component-emitter@1.1.2,
has
-binary@0.1.6, parseuri@0.0.2, engine.io-client@1.5.1)



C:\node\Athena12>where msbuild
C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe

C:\node\Athena12>where python
C:\apps\Python27\python.exe
C:\apps\Python 3.5\python.exe

**Comment by smikes** [comment]
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially involving git dependencies -- since 2.7. Can you try updating your npm installation?

There is a bad interaction between two known bugs — one in `node@>0.11` and `iojs` and the other in `npm@<2.8.2`.  This can cause ECONNRESET and ETIMEDOUT errors.  The full writeup is here: https://github.com/npm/npm/issues/7699  You can fix this problem by updating your `npm` to the latest (see below).

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved / abandoned.
