### ISSUE TITLE
undocumented syntax is the only one that works..

### ISSUE THREAD

**Issue by AlexCppns** [npm/npm#7544]
I fought with my CircleCi setup yesterday to have the npm packages installed where I wanted them to be, I started with something like this from the documentation:
```
dependencies:
  pre:
    - npm config set prefix ~/platform-ui/spec/karma 
    - npm install -g jasmine-core karma karma-coverage karma-jasmine karma-phantomjs-launcher karma-threshold-reporter
    - npm config delete prefix
```

which didnt work. After some extensive search on stackoverflow, I eventually found that I can pass --prefix as a parameter (if this is written in the docs, I would love to see it):

```
- npm install --prefix ./spec/karma jasmine-core karma karma-coverage karma-jasmine karma-phantomjs-launcher karma-threshold-reporter
```

If there is an error in the first syntax, let me know.

**Comment by smikes** [comment]
Hi!  Sorry to hear you had difficulty getting `npm` to do what you wanted.

The command-line parameters are all the same as the config file parameters, and this is documented (for example) here <https://docs.npmjs.com/files/npmrc>

> The npm config files
> npm gets its config settings from the command line, environment variables, and npmrc files.

And also here <https://docs.npmjs.com/cli/config>:

> Manage the npm configuration files
>
> `npm config set <key> <value> [--global]`
> ...
>
> npm gets its config settings from the command line, environment variables, npmrc files, and in some cases, the package.json file.

I'm curious, however, why the instructions you were following wanted you to set `prefix` at all.  Usually this is not necessary, as `npm` installs the dependencies for each package under that package's directory, in the `node_modules` subdirectory.

**Comment by smikes** [comment]
Is this still a problem for you?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as abandoned.

**Comment by AlexCppns** [comment]
@smikes I don't see it as a problem for me since I solved it, It's a problem in the documentation. Also, no it is not documented, I would never have guessed it fromt he links you provided here.

'I'm curious, however, why the instructions you were following wanted you to set prefix at all.'

Well I provided a use case right here.

**Comment by aredridel** [comment]
The normal way to achieve that use-case is to not pass the `-g` flag, and call the executable files installed in `node_modules/.bin/`. npm adds this to the path for any script from package.json it executes, so this almost never needs to be done explicitly.

In fact, if you list these in your `devDependencies`, this is where they are installed anyway. You should end up not needing any special scripts for your CircleCI config at all.

**Comment by AlexCppns** [comment]
@aredridel Sorry for the confusion, I do not have a package.json or node_modules/.bin/ directory. I installed those npm packages to be able to run karma tests on my RoR application. The tests are run via a custom rake task (ruby).
