### ISSUE TITLE
`yo webapp` Errors

### ISSUE THREAD

**Issue by fguillen** [npm/npm#7546]
I'm having issues trying any `yo` command, I have tried to update everything, now I'm using: 

- node v0.12.0
- npm  v2.5.1
- yo v1.4.6

Trying `yo webapp` I get these errors:

    npm WARN package.json panelbookv2-2@ No description
    npm WARN package.json panelbookv2-2@ No repository field.
    npm WARN package.json panelbookv2-2@ No README data
    npm ERR! Darwin 13.3.0
    npm ERR! argv "node" "/usr/local/bin/npm" "install"
    npm ERR! node v0.12.0
    npm ERR! npm  v2.5.1

    npm ERR! null == true
    npm ERR! 
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <http://github.com/npm/npm/issues>
    npm ERR! Darwin 13.3.0
    npm ERR! argv "node" "/usr/local/bin/npm" "install"
    npm ERR! node v0.12.0
    npm ERR! npm  v2.5.1

    npm ERR! null == true
    npm ERR! 
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <http://github.com/npm/npm/issues>

Full console log: http://pastebin.com/HK8Kbhar
Full debug log (npm-debug.log): (too big I can't use pastebin, if necessary I can try other methods)

**Comment by fguillen** [comment]
Tried this: https://gist.github.com/DanHerbert/9520689 .. not working :/

**Comment by KenanY** [comment]
@fguillen This is a node bug https://github.com/npm/npm/issues/7332

**Comment by fguillen** [comment]
@KenanY yep..  I've seen thanks

**Comment by fguillen** [comment]
Downgrading to `node 0.10.30` cleaning caches and installing everything again solved this for me.

**Comment by othiym23** [comment]
See #7349 for further discussion of this, as I'm going to close this issue and use that one as the master issue for tracking this problem, which appears to be in Node.js's HTTPS handling code.
