### ISSUE TITLE
SELF_SIGNED_CERT_IN_CHAIN

### ISSUE THREAD

**Issue by rNemesis** [npm/npm#7547]
Hi, I cannot install npm due to the titled error. Please help.

**Comment by smikes** [comment]
Usually this error would not prevent you from installing `npm`, but from using `npm` to install other packages -- possibly even `npm` itself.

If you install packages with  `npm` and you want to upgrade, on a Unix-like system you can use

````
$ curl -L http://npmjs.org/install.sh | sudo sh
```

There is also a Troubleshooting guide here <https://github.com/npm/npm/wiki/Troubleshooting#ssl-error> with a number of things you can try to work around the "self-signed cert" error.

If you need more help, please upload your npm-debug.log as a gist to <https://gist.github.com> and put the link in this issue.

**Comment by rNemesis** [comment]
Hello @smikes I'm on a windows  box. I can install npm globally but when I try to install in mean-stack-relational it blows up.

**Comment by smikes** [comment]
If you are behind a proxy, have you configured `npm` to use the appropriate proxy settings?  Are you using an SSL-intercepting proxy?

**Comment by rNemesis** [comment]
@smikes  this is the link to the debug file:
https://gist.github.com/rNemesis/98c3798c561d6853c89e

**Comment by rNemesis** [comment]
@smikes I am not behind a proxy, I use openDNS for my IP configuration but that has never been an issue. As for the latter part of your question on SSL-intercepting proxy, I am not familiar with that concept. I am using Kaspersky, I just read a post about the AV being an issue but the writer did not elaborate on how to fix the problem.

**Comment by smikes** [comment]
Try disabling the `https` or `ssl` feature in Kaspersky. If that solves the problem, then you can look into whether the software supports white listing by application or website.

**Comment by smikes** [comment]
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There is a bad interaction between two known bugs — one in `node@>0.11` and `iojs` and the other in `npm@<2.8.2`.  This can cause ECONNRESET and ETIMEDOUT errors.  The full writeup is here: https://github.com/npm/npm/issues/7699  You can fix this problem by updating your `npm` to the latest (see below).

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by smikes** [comment]
In your case, you may need to download a new MSI to get the latest version of `node`, and then manually download `npm-2.8.4.tgz` from http://registry.npmjs.org/npm/-/npm-2.8.4.tgz.  Assuming you download the the tarball to C:\TEMP, you can install it globally like this:

```
> cd C:\Program Files (x86)\nodejs
> npm i C:\tmp\npm-2.8.4.tgz
```

That should give you a functional `npm` that works around the known `http` bugs in node 0.12+earlier `npm`, but it will not necessarily address the SSL issue.  You might need to consult your local IT/networking staff to make sure your `proxy` config setting is correct.

**Comment by othiym23** [comment]
Closing as resolved!
