### ISSUE TITLE
Problem with cordova

### ISSUE THREAD

**Issue by Maverick2786** [npm/npm#7549]
I have these errors, also if I can help as finding the file npm-debug.log

Thanks to all in advance

![screenhunter_142 mar 05 12 48](https://cloud.githubusercontent.com/assets/6043564/6514197/26c3a148-c346-11e4-929b-80254d7cb8be.jpg)

**Comment by KenanY** [comment]
@Maverick2786 Are you behind a proxy by any chance?

**Comment by smikes** [comment]
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There is a bad interaction between two known bugs — one in `node@>0.11` and `iojs` and the other in `npm@<2.8.2`.  This can cause ECONNRESET and ETIMEDOUT errors.  The full writeup is here: https://github.com/npm/npm/issues/7699  You can fix this problem by updating your `npm` to the latest (see below).

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved / abandoned.
