### ISSUE TITLE
unable to install appium using npm v2.6.1

### ISSUE THREAD

**Issue by spatchamatla** [npm/npm#7550]
npm ERR! git clone git://github.com/vojtajina/traceur-compiler Cloning into bare repository '/Users/spatchamatla/.npm/_git-remotes/git-github-com-vojtajina-traceur-compiler-f4c43c65'...
npm ERR! git clone git://github.com/vojtajina/traceur-compiler fatal: read error: Operation timed out
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "-g" "install" "appium"
npm ERR! node v0.12.0
npm ERR! npm  v2.6.1
npm ERR! code 128

ERR! Command failed: git clone --template=/Users/<>/.npm/_git-remotes/_templates --mirror git://github.com/vojtajina/traceur-compiler /Users/s<>/.npm/_git-remotes/git-github-com-vojtajina-traceur-compiler-f4c43c65
npm ERR! Cloning into bare repository '/Users/<>/.npm/_git-remotes/git-github-com-vojtajina-traceur-compiler-f4c43c65'...
npm ERR! fatal: read error: Operation timed out
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/<>/npm-debug.log

**Comment by KenanY** [comment]
@spatchamatla 

```
npm ERR! fatal: read error: Operation timed out
```

Looks like your internet connection timed out trying to connect to `github.com`.

**Comment by spatchamatla** [comment]
Thanks Kenyan, i got the reply from Appium folks, it an issue on appium side. Thank You.
