### ISSUE TITLE
ember-cli install weirdness

### ISSUE THREAD

**Issue by isaacs** [npm/npm#7552]
When you take [the package.json generated by ember-cli's `ember new app`](https://gist.github.com/isaacs/ed86224c4040df1beed6), and then try to `npm install` with it, you get a broken state:

```json
{
  "name": "app",
  "version": "0.0.0",
  "description": "Small description for app goes here",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "start": "ember server",
    "build": "ember build",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.0.0",
    "ember-cli": "0.2.0-beta.1",
    "ember-cli-babel": "^4.0.0",
    "ember-cli-app-version": "0.3.1",
    "ember-cli-content-security-policy": "0.3.0",
    "ember-cli-dependency-checker": "0.0.7",
    "ember-cli-htmlbars": "0.7.4",
    "ember-cli-ic-ajax": "0.1.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-qunit": "0.3.8",
    "ember-cli-uglify": "1.0.1",
    "ember-data": "1.0.0-beta.15",
    "ember-export-application-global": "^1.0.2",
    "express": "^4.8.5",
    "glob": "^4.0.5"
  }
}
```

```
$ npm ls glob rimraf
npm WARN unmet dependency /Users/isaacs/dev/js/x/app/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rimraf requires glob@'^4.4.2' but will load
npm WARN unmet dependency /Users/isaacs/dev/js/x/app/node_modules/ember-cli/node_modules/glob,
npm WARN unmet dependency which is version 4.0.5
npm WARN unmet dependency /Users/isaacs/dev/js/x/app/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/broccoli-caching-writer/node_modules/rimraf requires glob@'^4.4.2' but will load
npm WARN unmet dependency /Users/isaacs/dev/js/x/app/node_modules/ember-cli/node_modules/glob,
npm WARN unmet dependency which is version 4.0.5
npm WARN unmet dependency /Users/isaacs/dev/js/x/app/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/sander/node_modules/rimraf requires glob@'^4.4.2' but will load
npm WARN unmet dependency /Users/isaacs/dev/js/x/app/node_modules/ember-cli/node_modules/glob,
npm WARN unmet dependency which is version 4.0.5
npm WARN unmet dependency /Users/isaacs/dev/js/x/app/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/node_modules/rimraf requires glob@'^4.4.2' but will load
npm WARN unmet dependency /Users/isaacs/dev/js/x/app/node_modules/ember-cli/node_modules/glob,
npm WARN unmet dependency which is version 4.0.5
app@0.0.0 /Users/isaacs/dev/js/x/app
├─┬ broccoli-asset-rev@2.0.1
│ └─┬ broccoli-filter@0.1.11
│   ├─┬ broccoli-kitchen-sink-helpers@0.2.6
│   │ └── glob@4.0.4
│   └─┬ quick-temp@0.1.2
│     └── rimraf@2.2.8
├─┬ ember-cli@0.2.0-beta.1
│ ├─┬ bower@1.3.12
│ │ └── rimraf@2.2.8
│ ├─┬ broccoli@0.13.3
│ │ └─┬ findup-sync@0.1.3
│ │   └── glob@3.2.11
│ ├─┬ broccoli-caching-writer@0.5.1
│ │ ├─┬ broccoli-kitchen-sink-helpers@0.2.6
│ │ │ └── glob@4.0.4
│ │ ├─┬ quick-temp@0.1.2
│ │ │ └── rimraf@2.2.8
│ │ └── rimraf@2.3.1
│ ├─┬ broccoli-es6modules@0.5.1
│ │ ├─┬ broccoli-caching-writer@0.5.3
│ │ │ ├─┬ quick-temp@0.1.2
│ │ │ │ └── rimraf@2.2.8
│ │ │ └── rimraf@2.3.1
│ │ ├─┬ broccoli-kitchen-sink-helpers@0.2.6
│ │ │ └── glob@4.0.4
│ │ └─┬ esperanto@0.6.17
│ │   └─┬ sander@0.2.2
│ │     └── rimraf@2.3.1
│ ├─┬ broccoli-funnel@0.2.2
│ │ └── rimraf@2.2.8
│ ├─┬ broccoli-sourcemap-concat@0.4.3
│ │ ├─┬ broccoli-caching-writer@0.5.3
│ │ │ ├─┬ quick-temp@0.1.2
│ │ │ │ └── rimraf@2.2.8
│ │ │ └── rimraf@2.3.1
│ │ └─┬ broccoli-kitchen-sink-helpers@0.2.6
│ │   └── glob@4.0.4
│ ├─┬ broccoli-writer@0.1.1
│ │ └─┬ quick-temp@0.1.2
│ │   └── rimraf@2.2.8
│ ├─┬ fs-extra@0.12.0
│ │ └── rimraf@2.2.8
│ ├── glob@4.0.5  invalid
│ ├─┬ npm@2.1.8
│ │ ├── glob@4.0.6
│ │ └── rimraf@2.2.8
│ ├─┬ quick-temp@0.1.2
│ │ └── rimraf@2.2.8
│ ├─┬ temp@0.8.1
│ │ └── rimraf@2.2.8
│ ├─┬ testem@0.7.0
│ │ ├─┬ fileset@0.1.5
│ │ │ └── glob@3.2.11
│ │ ├── glob@4.3.5
│ │ └── rimraf@2.2.8
│ └─┬ yam@0.0.17
│   └─┬ fs-extra@0.8.1
│     └── rimraf@2.2.8
├─┬ ember-cli-babel@4.1.0
│ ├─┬ broccoli-babel-transpiler@4.0.1
│ │ └─┬ babel-core@4.6.6
│ │   └─┬ regenerator-babel@0.8.13-1
│ │     └─┬ commoner@0.10.1
│ │       └── glob@4.2.2
│ └─┬ broccoli-filter@0.1.11
│   ├─┬ broccoli-kitchen-sink-helpers@0.2.6
│   │ └── glob@4.0.4
│   └─┬ quick-temp@0.1.2
│     └── rimraf@2.2.8
├─┬ ember-cli-htmlbars@0.7.4
│ └─┬ broccoli-filter@0.1.11
│   ├─┬ broccoli-kitchen-sink-helpers@0.2.6
│   │ └── glob@4.0.4
│   └─┬ quick-temp@0.1.2
│     └── rimraf@2.2.8
├─┬ ember-cli-qunit@0.3.8
│ └─┬ broccoli-jshint@0.5.3
│   ├─┬ broccoli-filter@0.1.11
│   │ ├─┬ broccoli-kitchen-sink-helpers@0.2.6
│   │ │ └── glob@4.0.4
│   │ └─┬ quick-temp@0.1.2
│   │   └── rimraf@2.2.8
│   ├─┬ findup-sync@0.1.3
│   │ └── glob@3.2.11
│   └─┬ jshint@2.5.11
│     └─┬ cli@0.6.5
│       └── glob@3.2.11
├─┬ ember-cli-uglify@1.0.1
│ └─┬ broccoli-uglify-sourcemap@0.2.1
│   └─┬ broccoli-writer@0.1.1
│     └─┬ quick-temp@0.1.2
│       └── rimraf@2.2.8
└── glob@4.4.2
```

I think this might be a bug in how we're calculating the package ancestry while deciding what to install.

Note: `rimraf@2.3.1` depends on `glob@^4.4.2`.  If it gets any other version of `glob`, bad times happen.

At the top level, we have a dep on `glob@^4.0.5`.  This resolves to `4.4.2`, which is good.

Then, `ember-cli` is installed, which has a dep on `glob@4.0.5`, and it is a bundled dependency.

Underneath, `ember-cli`, we get `broccoli-caching-writer@0.5.3`, which depends on `rimraf@^2.2.8`.

I would expect that, since the closest ancestor glob is ember-cli's (bundled) `glob@4.0.5`, it should say, "Oh, this won't work for me".  However, we're *not* getting another copy of `glob@4.4.2` installed underneath rimraf here.

Then, this happens 2 more times, since `broccoli-es6modules@0.5.1` and `broccoli-sourcemap-concat@0.4.3` also depend on `broccoli-caching-writer@0.5.3`.

Is it failing to add the bundled glob to the ancestor set, and thinking that the root's `glob@4.4.2` is the nearest ancestor?

**Comment by mkwallace** [comment]
I'm running into this issue as well.

**Comment by jesuskwice** [comment]
Same here.. (ember-cli@0.1.12)

**Comment by intuitivepixel** [comment]
Same here on `ember-cli@0.2.0-beta.1`

**Comment by mkwallace** [comment]
After searching around, I found https://github.com/npm/npm/issues/1341 which allowed me to figure out the following fix:

For each unmet dependency warning, run `npm install` in the directory of that dependency, e.g. for
npm WARN unmet dependency /Users/isaacs/dev/js/x/app/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rimraf requires glob@'^4.4.2' but will load

Run `npm install` in
/Users/isaacs/dev/js/x/app/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rimraf

In my case, this was because I had a top-level dependency on glob 4.0.5, which was preventing the child modules from receiving a copy of glob 4.4.2 or later.

**Comment by s12chung** [comment]
ember-cli@0.1.12...

**Comment by pivotal-topher-bullock** [comment]
Yeah, @s12chung 's solution worked for me ; specifying a specific version of ``rimraf`` in your root ``package.json`` fixes the whole enchilada **temporarily**. 

Could the problem be that NPM isn't identifying the ``ember-cli`` "middle-child" dependency for a specific static version of ``glob@4.0.5`` as not satisfying ``rimraf``'s  `` glob@^4.4.2 `` requirement because it looks higher up in the ancestry set and finds the root ``glob@^4.0.5``?

NPM knows that it did a bad thing, because ``npm ls`` tells us specifically that ``rimraf`` is going to try and load the invalid ``glob@4.0.5`` from ``ember-cli``. Shouldn't these same checks run on install and confirm/deny that the ancestors provide the proper semver for dependencies their children are asking for?

**Comment by Mithrilhall** [comment]
I had the same issue and the fix for me was updating ember in my package.json:

"ember-cli": "0.2.0"

**Comment by jesuskwice** [comment]
Hi all, FWIW, I found the root of my problem was that I tried updating ember-cli directly in package.json and running npm install, as opposed to the proper clean way of doing it described here:
http://www.ember-cli.com/#upgrading

After following the process outlined in the Project Update section, all the unmet dependency issues were resolved. Posting in case it saves anyone else a bit of headache.

**Comment by miguelmota** [comment]
same issue on ember-cli@0.2.0-beta.1

**Comment by othiym23** [comment]
I'm just going to cut and paste the entire commit message for 051c4738486a826300f205b71590781ce7744f01, which fixes this bug:

> The npm@<3 installer uses an elaborate data tree built in-memory as the install process runs to track which dependencies have already been seen in the tree. This allows the installer to determine whether a parent dependency satisfies the current semver requirement.
> 
> However, if one version of a dependency is specified at one level of the tree, and then a child of that level includes that same dependency bundled at a different version, and one of *that dependency's* children depends on this same dependency at yet another version, it will end up matching against the version _above_ the bundled dependency.  This can lead anyone trying to figure out what's going on into a phantasmagorical wonderland where nothing is real, and can also produce an inconsistent installed tree.
> 
> The solution is to ensure that the bundled dependency versions are added to the tree, but in order to do this, we need to know exactly which version got bundled. This requires a call to readInstalled, because the version that was bundled isn't included anywhere in the package metadata. Since readInstalled is slow, installMany will only call it if it knows there are bundledDependencies for the current package.

**Comment by udfalkso** [comment]
Thanks @mkwallace I'm downgrading to test an old version of my app and your suggestion helped me out.

**Comment by mkwallace** [comment]
@udfalkso I'm glad it was helpful!

**Comment by pivotal-topher-bullock** [comment]
@othiym23 Awesome! :+1:
