### ISSUE TITLE
Q: Tweak CHANGELOG.md?

### ISSUE THREAD

**Issue by Zearin** [npm/npm#7556]
So, I’ve been trying to get people on board with http://keepachangelog.com .  It describes some good common-sense guidelines for changelogs.  It’s explicitly *not* as formal as, say, semver, but it’s got some guidelines I really like.

That said, I just checked out npm’s CHANGELOG.md, and it’s really awesome.  I especially love the humorous writing sprinkled throughout.  It also suggests to me that your changelog is hand-crafted, rather than script-generated. 

If that’s the case, I’d like to ask permission to apply one (*only* one) of [keep a changelog]’s guidelines to your changelog. One of my favorite guidelines is, under each version, the grouping of changes into the most common categories: Added, Changed, Deprecated, Removed, Fixed, and Security.  (I’ll go ahead and assume a Miscellaneous category is sensible, as well.)

Would it be okay if I were to sort your changes into these categories?

-----------

Thanks for all your work on npm.  It’s awesome. :-) 

[keep a changelog]: http://keepachangelog.com

**Comment by othiym23** [comment]
Hmmm..., let me think about it. I do create the log more or less by hand and have a pretty strong editorial voice (I weed out trivial changes and tests, group things by related changes, create themes for related sets of issues on the fly, etc). I see the value of consistency, but maybe not if it makes the CHANGELOG less accessible (which is the point of trying to keep it light / funny).

**Comment by othiym23** [comment]
So, a year later, the CLI team has continued to work on the formatting, style, and tone of our various changelogs, and we've figured out the purpose of the changelog:

1. To communicate to end users, in terms they can understand and relate to, why they should update their version of npm, and how the changes in the new version are going to affect them.
2. To act as a means for the npm CLI team to support and build the community around npm.

If you look at a few of our changelog entries in a row, you'll see that there's a fair amount of consistency between them, and we've developed our own categorization scheme (i.e. dependency updates, document changes contributed by the community, significant bug fixes), and those are categories chosen to optimize for the specific interests of npm users (or, as in the case of dependency updates, lack thereof).

Also, the overall format of the changelog is conversational (without being too informal), and we try to give it at least a little bit of a narrative shape. As such, we've decided that we don't want to move to any of the semantically-oriented potential changelog formats out there. Thanks for opening this, though, and thanks for the offer!

**Comment by Zearin** [comment]
Thank you very much for your thoughtful and articulate response!  

I generally think most changelogs are substandard.  But your changelog is an exemplar counter to the trend (or more precisely, what I *perceive* to be a “trend” :stuck_out_tongue:).  

Thanks to you and all who have created such a wonderful changelog, and I hope it inspires others to make their own changelogs the best that they can.  Cheers!  :D
