### ISSUE TITLE
NPM, TFS, and Windows Authentication

### ISSUE THREAD

**Issue by mikejr83** [npm/npm#7557]
Until recently we were using a local install of Gitorious on our company's intranet to host tools/modules we were building with node. The consumers of the tools would use npm to install from the git repository.

    npm install git://gitorious.corp.local/Project/repo@tag

Life was good. Then everyone decided on one source control system. We went with TFS 2013 because it supports each team's needs. One thing it doesn't do is support git/ssh. No biggie, I thought, we'll just use HTTP.

    npm install http://tfs2013.corp.local:8080/tfs/DefaultCollection/TeamProject/_git/Repo

This causes npm an unhappy situation as well...

    npm ERR! fetch failed http://tfs2013.corp.local:8080/tfs/DefaultCollection/TeamProject/_git/Repo
    npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
    npm ERR! fetch failed http://tfs2013.corp.local:8080/tfs/DefaultCollection/TeamProject/_git/Repo
    npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401

I fired up wireshark to get that response:

    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
    <html xmlns="http://www.w3.org/1999/xhtml">
    	<head>
    		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
    		<title>401 - Unauthorized: Access is denied due to invalid credentials.</title>
    		<style type="text/css">
    			
    		</style>
    	</head>
    	<body>
    		<div id="header">
    			<h1>Server Error</h1>
    		</div>
    		<div id="content">
    			<div class="content-container">
    				<fieldset>
    					<h2>401 - Unauthorized: Access is denied due to invalid credentials.</h2>
    					<h3>You do not have permission to view this directory or page using the credentials that you supplied.</h3>
    				</fieldset>
    			</div>
    		</div>
    	</body>
    </html>

So our TFS git repo uses windows auth / NTLM. How can I get npm pass through my credentials? I already setup git to use wincred? Is there a value I can set in npmrc for credentials? Is this not supported? Can this be supported? :)

**Comment by othiym23** [comment]
Sounds like you need a [`cntlm` proxy](http://cntlm.sourceforge.net)! The best way to get support for NTLM in npm is to bug the request team until they agree to figure it out for all of us. ;) npm doesn't handle details of proxying or tunneling itself.

**Comment by othiym23** [comment]
[Here's](http://stackoverflow.com/questions/18569054/npm-behind-ntlm-proxy) a pretty decent writeup of getting up and running with `cntlm`.
