### ISSUE TITLE
npm should print stack trace to stderr when top frame is not `npm` code

### ISSUE THREAD

**Issue by smikes** [npm/npm#7561]
Identification of the underlying node 0.12 / HTTPS issue in https://github.com/npm/npm/issues/7349 was delayed because at first we didn't see the stack trace, just the exception text.

However, normally we don't need/want the full stack trace when the error being thrown is something `npm` aims to communicate to the user e.g., "Tag must not be a valid SemVer range".

My proposed middle ground is that when there's an exception, if the top frame of `er.stack` does not contain the string `npm`, then all "optional" logging that's currently going out as `verbose` goes out as `error`.

**Comment by othiym23** [comment]
In general, npm's user base skews towards new users over time, and while in this specific circumstance, it might have gotten the stack trace to the maintainers in a form that was actionable sooner, in general printing out the full stacktrace for unknown errors (i.e. errors that aren't already rolled up in `lib/utils/error-handler`) isn't going to be any more useful to the end user. In general, the best thing the CLI team can get is unfiltered `npm-debug.log` files, and we already have pretty clear messaging to that effect. So I'm going to close this, although it prompted a pretty good discussion about how to handle these kinds of errors more gracefully. Thanks for filing it!
