### ISSUE TITLE
(bug) npm self update actually uninstalled npm

### ISSUE THREAD

**Issue by fredgalvao** [npm/npm#7562]
### This is the PROBLEM

I went on to update 2 of my global packages today, [npm 2.6.1 to 2.7.0, ripple-emulator 0.9.24 to 0.9.28] using `npm i -g npm ripple-emulator`, and it ended in tears.

```
$ npm i -g npm ripple-emulator
/home/frederico/local/bin/npm -> /home/frederico/local/lib/node_modules/npm/bin/npm-cli.js
/home/frederico/local/bin/ripple -> /home/frederico/local/lib/node_modules/ripple-emulator/bin/ripple
npm ERR! Linux 3.11.0-26-generic
npm ERR! argv "node" "/home/frederico/local/bin/npm" "i" "-g" "npm" "ripple-emulator"
npm ERR! node v0.10.25
npm ERR! npm  v2.6.1
npm ERR! path ../../../lib/node_modules/npm/man/man7/npm-coding-style.7
npm ERR! code ENOENT
npm ERR! errno 34

npm ERR! enoent ENOENT, symlink '../../../lib/node_modules/npm/man/man7/npm-coding-style.7'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /.../PATH/.../npm-debug.log
```

The end result is that npm was uninstalled from my system. There is no **npm** folder where it's expected to be:

```
$ npm
bash: /home/frederico/local/bin/npm: No such file or directory
```

```
:~/local/bin$ ls -la
total 10924
drwxr-xr-x 2 frederico frederico     4096 Mar  6 16:27 ./
drwxr-xr-x 7 frederico frederico     4096 Fev 25 13:37 ../
lrwxrwxrwx 1 frederico frederico       39 Mar  3 14:05 cordova -> ../lib/node_modules/cordova/bin/cordova*
lrwxrwxrwx 1 frederico frederico       36 Fev 10 15:55 gulp -> ../lib/node_modules/gulp/bin/gulp.js*
-rwxr-xr-x 1 frederico frederico 11174429 Jan 28  2014 node*
lrwxrwxrwx 1 frederico frederico       59 Jan 30 08:16 npm-check-updates -> ../lib/node_modules/npm-check-updates/bin/npm-check-updates*
lrwxrwxrwx 1 frederico frederico       46 Mar  6 16:27 ripple -> ../lib/node_modules/ripple-emulator/bin/ripple*
```

```
:~/local/lib/node_modules$ ls -la
total 24
drwxr-xr-x 6 frederico frederico 4096 Mar  6 16:39 .
drwxr-xr-x 4 frederico frederico 4096 Jan 28  2014 ..
drwxr-xr-x 7 frederico frederico 4096 Mar  3 14:04 cordova
drwxr-xr-x 6 frederico frederico 4096 Fev 10 15:55 gulp
drwxr-xr-x 6 frederico frederico 4096 Jan 30 08:15 npm-check-updates
drwxr-xr-x 8 frederico frederico 4096 Mar  6 16:27 ripple-emulator
```

The mentioned **npm-debug.log** is attached on these 2 pastebins:
http://pastebin.com/RSkB5TM9
http://pastebin.com/UgdRArMn
### This is my ENVIRONMENT

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 13.10
Release:    13.10
Codename:   saucy
```

```
$ uname -a
Linux frederico 3.11.0-26-generic #45-Ubuntu SMP Tue Jul 15 04:02:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

```
node -v
v0.10.25
```
### And this is how I FIXED IT

```
$ curl -L https://www.npmjs.org/install.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    51  100    51    0     0     59      0 --:--:-- --:--:-- --:--:--    59
100  6239  100  6239    0     0   2936      0  0:00:02  0:00:02 --:--:--  5463
tar=/bin/tar
version:
tar (GNU tar) 1.26
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
install npm@latest
fetching: http://registry.npmjs.org/npm/-/npm-2.7.0.tgz

> npm@2.7.0 prepublish /tmp/npm.8264/package
> node bin/npm-cli.js prune --prefix=. --no-global && rm -rf test/*/*/node_modules && make -j8 doc

make: Nothing to be done for `doc'.
/home/frederico/local/bin/npm -> /home/frederico/local/lib/node_modules/npm/bin/npm-cli.js
npm@2.7.0 /home/frederico/local/lib/node_modules/npm
It worked
```

```
$ npm -v
2.7.0
```

PS: My node+npm installation was made from [this gist](https://gist.github.com/fredgalvao/2627656#file-install-sh-L174-L184) I made, which was based on [isaacs](https://gist.github.com/isaacs/579814).

**Comment by KidkArolis** [comment]
This issue is already being discussed here https://github.com/npm/npm/issues/7510

**Comment by fredgalvao** [comment]
This issue only refers to a single scenario of #7510, and while the resolution of **that** issue will *prevent* **this** issue from happening, **this** one is still a bug of it's own IMO.

**Comment by KenanY** [comment]
Just randomly ran into myself, although I am fairly sure this is not the first time (been a while since the last time though). I've uploaded my `npm-debug.log`: https://gist.github.com/KenanY/0e752b46334bf9fb4bc4

**Comment by KenanY** [comment]
`curl` method reinstalled `npm` of course but I got that same error trying to update to `npm@next`. Had to `rm -rf /home/kenan/.npm-packages/share/man/`.

**Comment by banderror** [comment]
Same issue on Windows

$ npm install npm -g
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "npm" "-g"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! path c:\Program Files\nodejs\npm
npm ERR! code EPERM
npm ERR! errno -4048

npm ERR! Error: EPERM, open 'c:\Program Files\nodejs\npm'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM, open 'c:\Program Files\nodejs\npm']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   path: 'c:\\Program Files\\nodejs\\npm' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
npm ERR! error rolling back Error: EPERM, lstat 'c:\Program Files\nodejs\npm'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EPERM, lstat 'c:\Program Files\nodejs\npm']
npm ERR! error rolling back   errno: -4048,
npm ERR! error rolling back   code: 'EPERM',
npm ERR! error rolling back   path: 'c:\\Program Files\\nodejs\\npm' }

npm ERR! Please include the following file with any support request:
npm ERR!     d:\...\src\npm-debug.log
/c/Program Files/nodejs/npm: line 14: 10060 Signal 112              (core dumped) "$basedir/node.exe" "$basedir/node_modules/npm/bin/npm-cli.js" "$@"

[npm-debug.log](https://gist.github.com/banderror/a050582ee4a60e25f9b1)

**Comment by simonbuchan** [comment]
+1 to on windows, and still in npm@3:

```
$ npm -g i npm@3
npm WARN EPACKAGEJSON C:\Users\sbuchan\AppData\Roaming\npm No description
npm WARN EPACKAGEJSON C:\Users\sbuchan\AppData\Roaming\npm No repository field.
npm WARN EPACKAGEJSON C:\Users\sbuchan\AppData\Roaming\npm No README data
npm WARN EPACKAGEJSON C:\Users\sbuchan\AppData\Roaming\npm No license field.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Users\\sbuchan\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "-g" "i" "npm@3"
npm ERR! node v0.12.5
npm ERR! npm  v3.1.0
npm ERR! path C:\Users\sbuchan\AppData\Roaming\npm\npm
npm ERR! code EPERM
npm ERR! errno -4048

npm ERR! Error: EPERM, open 'C:\Users\sbuchan\AppData\Roaming\npm\npm'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM, open 'C:\Users\sbuchan\AppData\Roaming\npm\npm']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   path: 'C:\\Users\\sbuchan\\AppData\\Roaming\\npm\\npm',
npm ERR!   parent: 'npm' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\code\portal\npm-debug.log
/c/Users/sbuchan/AppData/Roaming/npm/npm: line 14:  4276 Signal 112              (core dumped) node "$basedir/node_modules/npm/bin/npm-cli.js" "$@"
```

[npm-debug.log](https://gist.github.com/simonbuchan/9eb7f25d706b48675b33)

**Comment by iarna** [comment]
Yeah, this has been a known bug in npm@2. npm@3 should fix this, but unfortunately you can encounter the bug when you go to upgrade to npm@3. Ironic I know. 😒

@simonbuchan Are you using cygwin? IIRC that has known issues w/ npm and isn't very well supported.

**Comment by simonbuchan** [comment]
@iarna - see `npm v3.1.0` line in the error spew. Nah, msys(git) bash, so the regular windows node.exe. I expect at worst it could have some path translation screwiness? Maybe it's not expecting the `/bin/sh` `npm` script to be the one running, thus not deletable on windows? But I'd expect msys bash to read and close scripts before execution to emulate POSIX semantics?

**Comment by iarna** [comment]
msys is supposed to work fine, afaik

**Comment by legodude17** [comment]
What version of `npm` are you using? (`npm -v`)

**Comment by thany** [comment]
On WLS that's 4.1.2.
On native Windows that's... 4.1.2 as well.

**Comment by legodude17** [comment]
Maybe try updating to the latest version?

**Comment by thany** [comment]
Yeah well, that'll cause npm to return an error like the one above, and effectively uninstall itself.

**Comment by legodude17** [comment]
Try getting it from the homepage, or from a new install of `node.js`.

**Comment by thany** [comment]
That's exactly what `sudo apt-get install --reinstall nodejs` does, having set up the ppa recommended from that very homepage.

**Comment by legodude17** [comment]
You should use `npm install npm@latest -g` instead.

**Comment by thany** [comment]
I'll try that. I'm still going to have to do a `sudo npm update -g` though, to update globally-installed modules. So I guess that comes afterwards.
