### ISSUE TITLE
OSX npm install error "invalid version 0.1"

### ISSUE THREAD

**Issue by PierBover** [npm/npm#7564]
I'm trying to install packages but I get this error on the terminal with most packages I've tried.

```
npm ERR! Darwin 13.2.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "xml2js"
npm ERR! node v1.5.0
npm ERR! npm  v2.7.0

npm ERR! Invalid version: "0.1"
```

I'm on OSX 10.9

**Comment by PierBover** [comment]
These are the contents of the debug.log file

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', 'js-yaml' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose stack Error: Invalid version: "0.1"
4 verbose stack     at Object.module.exports.fixVersionField (/usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/fixer.js:190:13)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/normalize.js:30:38
4 verbose stack     at Array.forEach (native)
4 verbose stack     at normalize (/usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/normalize.js:29:15)
4 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:342:33)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:126:33)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:316:48
4 verbose stack     at evalmachine.<anonymous>:265:20
4 verbose stack     at OpenReq.Req.done (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:141:5)
4 verbose stack     at OpenReq.done (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:61:22)
5 verbose cwd *******************
6 error Darwin 13.2.0
7 error argv "node" "/usr/local/bin/npm" "install" "js-yaml"
8 error node v0.12.0
9 error npm  v2.5.1
10 error Invalid version: "0.1"
11 error If you need help, you may report this error at:
11 error     <http://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@PierBover Is the `"version"` field of your `package.json` `"0.1"` by any chance? That's not a valid version under Semantic Versioning, hence the error. Changing it to `"0.1.0"` should suffice.

The [docs](https://docs.npmjs.com/files/package.json#version) for the `"version"` field describe how the field must be parseable by [`npm/node-semver`](https://github.com/npm/node-semver), which `"0.1"` isn't:

``` bash
$ npm install -g semver
$ semver 1.0
$ echo $?
1
```

(`1` is the exit code for failure)

**Comment by PierBover** [comment]
That's the strange thing, I'm not using any `package.json`

I did the exact same thing on another OSX computer an it didn't throw the error...

**Comment by KenanY** [comment]
@PierBover Oh, hmm, wrong assumption on my part then. Unfortunately I don't think there's any [`loglevel`](https://docs.npmjs.com/misc/config#loglevel) which will show what `package.json` is generating the error (I just tried it myself).

**Comment by KidkArolis** [comment]
Maybe one of the parent dirs of where you are running `npm install xml2js`
has a package.json?

**Comment by PierBover** [comment]
@KidkArolis That's correct!

I'm such a noob with npm, I didn't know it was also reading upper directories.
