### ISSUE TITLE
Npm on Raspberry Pi 2 is broken

### ISSUE THREAD

**Issue by randomite** [npm/npm#7566]
Whenever I try and do anything with npm this error is returned:
```bash
pi@raspberrypi ~ $ npm
/usr/local/bin/node: 1: /usr/local/bin/node: Syntax error: "(" unexpected
```

**Comment by KenanY** [comment]
@randomite Hmm, not much to go on here. Node.js version? `npm` version (if possible at all, of course)?

**Comment by randomite** [comment]
@KenanY:
```bash
pi@raspberrypi ~ $ nodejs -v
v0.10.36
```

**Comment by randomite** [comment]
@KenanY, any updates?

**Comment by KenanY** [comment]
@randomite I'm stumped :( doesn't look like an error that `npm` is generating... does `node -v` work as well?

**Comment by othiym23** [comment]
Something has overwritten `/usr/local/bin/node` with something else. What does `file /usr/local/bin/node` print out? If it says `ASCII text`, what's inside the file?

**Comment by randomite** [comment]
@KenanY , the ````node```` command does not work, but ````nodejs```` does work
````bash 
pi@raspberrypi ~ $ node -v
-bash: /usr/local/bin/node: cannot execute binary file
````

**Comment by randomite** [comment]
@othiym23 
````
pi@raspberrypi / $ file /usr/local/bin/node
/usr/local/bin/node: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.9, not stripped
````

**Comment by othiym23** [comment]
@randomite there's part of your problem -- you've somehow gotten an x86 node binary installed to `/usr/local/bin/node`. That can't work on a RasPi, so you should uninstall it. If you have a working `nodejs`, then after you uninstall whatever installed `/usr/local/bin/node`, you can run `sudo ln -s $(which nodejs) /usr/local/bin/node`, and npm should start working much better.

I'm going to close this now, as this isn't an npm issue. If @KenanY or I have time, we can answer questions, but you'd be better off asking a lot of these questions of other RasPi Node users. Good luck!
