### ISSUE TITLE
Windows configuration errors

### ISSUE THREAD

**Issue by CalebEverett** [npm/npm#7567]
I installed nodesjs on a windows 8 machine using the installer. I followed the [windows troubleshooting](https://github.com/npm/npm/wiki/Troubleshooting) guidelines, but am still getting errors when I run `npm install`. 

Any help would be greatly appreciated.

Here are the errors:

```
223358 silly gunzTarPerm extractEntry package.json
223359 silly gunzTarPerm modified mode [ 'package.json', 420, 438 ]
223360 verbose stack Error: read ECONNRESET
223360 verbose stack     at exports._errnoException (util.js:746:11)
223360 verbose stack     at TCP.onread (net.js:550:26)
223361 verbose cwd c:\Users\caleb.everett\nikoeverett
223362 error Windows_NT 6.3.9600
223363 error argv "c:\\Program Files\\nodejs\\\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
223364 error node v0.12.0
223365 error npm  v2.5.1
223366 error code ECONNRESET
223367 error errno ECONNRESET
223368 error syscall read
223369 error network read ECONNRESET
223369 error network This is most likely not a problem with npm itself
223369 error network and is related to network connectivity.
223369 error network In most cases you are behind a proxy or have bad network settings.
223369 error network
223369 error network If you are behind a proxy, please make sure that the
223369 error network 'proxy' config is set properly.  See: 'npm help config'
223370 verbose exit [ 1, true ]
```
And here is the output from `npm config ls -l`
```
; cli configs
user-agent = "npm/2.5.1 node/v0.12.0 win32 x64"

; userconfig C:\Users\caleb.everett\.npmrc
prefix = "c:\\Users\\caleb.everett\\AppData\\Roaming\\npm"

; builtin config undefined

; node bin location = c:\Program Files\nodejs\node.exe
; cwd = c:\Users\caleb.everett\nikoeverett
; HOME = C:\Users\caleb.everett
; 'npm config ls -l' to show all defaults.

; cli configs
long = true
user-agent = "npm/2.5.1 node/v0.12.0 win32 x64"

; userconfig C:\Users\caleb.everett\.npmrc
prefix = "c:\\Users\\caleb.everett\\AppData\\Roaming\\npm"

; builtin config undefined
; prefix = "C:\\Users\\caleb.everett\\AppData\\Roaming\\npm" (overridden)

; default values
access = null
always-auth = false
bin-links = true
browser = null
ca = null
cache = "C:\\Users\\caleb.everett\\AppData\\Roaming\\npm-cache"
cache-lock-retries = 10
cache-lock-stale = 60000
cache-lock-wait = 10000
cache-max = null
cache-min = 10
cafile = undefined
cert = null
color = true
depth = null
description = true
dev = false
editor = "notepad.exe"
engine-strict = false
fetch-retries = 2
fetch-retry-factor = 10
fetch-retry-maxtimeout = 60000
fetch-retry-mintimeout = 10000
force = false
git = "git"
git-tag-version = true
global = false
globalconfig = "c:\\Users\\caleb.everett\\AppData\\Roaming\\npm\\etc\\npmrc"
globalignorefile = "c:\\Users\\caleb.everett\\AppData\\Roaming\\npm\\etc\\npmignore"
group = 0
heading = "npm"
https-proxy = null
ignore-scripts = false
init-author-email = ""
init-author-name = ""
init-author-url = ""
init-license = "ISC"
init-module = "C:\\Users\\caleb.everett\\.npm-init.js"
init-version = "1.0.0"
json = false
key = null
link = false
local-address = undefined
loglevel = "warn"
; long = false (overridden)
message = "%s"
node-version = "0.12.0"
npat = false
onload-script = null
optional = true
parseable = false
; prefix = "c:\\Program Files\\nodejs" (overridden)
production = false
proprietary-attribs = true
proxy = null
rebuild-bundle = true
registry = "https://registry.npmjs.org/"
rollback = true
save = false
save-bundle = false
save-dev = false
save-exact = false
save-optional = false
save-prefix = "^"
scope = ""
searchexclude = null
searchopts = ""
searchsort = "name"
shell = "C:\\Windows\\system32\\cmd.exe"
shrinkwrap = true
sign-git-tag = false
spin = true
strict-ssl = true
tag = "latest"
tmp = "C:\\Users\\CALEB~1.EVE\\AppData\\Local\\Temp"
umask = 0
unicode = true
unsafe-perm = true
usage = false
user = 0
; user-agent = "npm/{npm-version} node/{node-version} {platform} {arch}" (overridden)
userconfig = "C:\\Users\\caleb.everett\\.npmrc"
version = false
versions = false
viewer = "browser"
```

**Comment by KenanY** [comment]
@CalebEverett Are you behind a proxy by any chance? `npm` is having difficulty connecting to the internet.

**Comment by smikes** [comment]
Is this still a problem for you?

There is a bad interaction between two known bugs — one in `node@>0.11` and `iojs` and the other in `npm@<2.8.2`.  This can cause ECONNRESET and ETIMEDOUT errors.  The full writeup is here: https://github.com/npm/npm/issues/7699  You can fix this problem by updating your `npm` to the latest (see below).

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by CalebEverett** [comment]
thanks for following up

On Wed, Apr 29, 2015 at 1:14 PM, Sam Mikes <notifications@github.com> wrote:

> Is this still a problem for you?
>
> There is a bad interaction between two known bugs — one in node@>0.11 and
> iojs and the other in npm@<2.8.2. This can cause ECONNRESET and ETIMEDOUT
> errors. The full writeup is here: #7699
> <https://github.com/npm/npm/issues/7699> You can fix this problem by
> updating your npm to the latest (see below).
>
> To update npm on Windows, follow the instructions here:
> https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows
>
> We are trying to clean up older npm issues, so if we don't hear back from
> you within a week, we will close this issue. (Don't worry -- you can always
> come back again and open a new issue!)
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/npm/npm/issues/7567#issuecomment-97528482>.
>



-- 
Caleb Everett
Career College of California
201 E. 4th Street, Suite 200
Santa Ana, CA 92701
(714) 243-8614 phone and fax
www.careercalifornia.edu

Facebook <http://www.facebook.com/CareerCalifornia> | Twitter
<http://twitter.com/careercalif> |  LinkedIn
<http://www.linkedin.com/company/941062> | G+
<https://plus.google.com/b/104968762557101611990/104968762557101611990/posts>

**Comment by othiym23** [comment]
Closing as resolved.
