### ISSUE TITLE
Improve peerDependencies by including them in resolving

### ISSUE THREAD

**Issue by mal** [npm/npm#7569]
Forgive me if I'm duplicating something here, I've done my best to catch myself up with the various `peerDependencies` discussions but it's entirely possible I missed bits, there's an awful lot!

---

Current behavior for [this chain](https://gist.github.com/mal/7450946e77d2909abe77#file-example) is to kick out a warning (because the current version of `chai` is `>2`:

```
npm ERR! peerinvalid The package chai does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer sinon-chai@2.6.0 wants chai@>=1.9.2 <2
```

But if we look at it, we see that the chain is should be satisfiable. The constraints are simply that _any_ version of `chai` should be installed (`app`), and that it be `>=1.9.2 <2` (`sinon-chai`). Rather than a warning, it would be nice if `npm` resolved this for us, and installed a version of `chai` that matches these contraints.

This avoids the "magical" installation of peerDeps as it's only installed due to the explicit dependency at the `app` level, it just takes into account peerDeps when deciding the version to install. Obviously the `app` might have a real version requirement (not just `*`) at which point expected behaviour would be to find common ground between the various version constraints and install a matching version. Only when the constraints are not able to be satsified would there be a peerDep warning/error kicked out.

There is also a [plugin](https://gist.github.com/mal/7450946e77d2909abe77#file-plugins) style chain showing how this would work with more than one requirement, with the expected version of `framework` being `1.3.0`.

---

_EDIT:_ As an aside, if these additional constraints travelled up the dependency tree (rather than just the parent level), this could also potentially solve the singleton issue. Although at that point it's less `peerDependencies` and more `sharedDependencies`. Also, if I understand correctly, `npm link` would need to kick out an error if prior to linking if it realised it had a local install of something that ought to be peer'd/shared futher up the tree it was being linked into.

**Comment by smikes** [comment]
I believe this is implemented in the upcoming version, `npm@3`, but @iarna is the person who can definitively answer this question.

**Comment by iarna** [comment]
npm@3 (currently the multi-stage branch) does not install peerDependencies for you, instead it reports missing peer or invalid peer dependencies and leaves it to you, the application author, to figure out the best way to resolve them.

Current versions of npm have deprecation warnings around the current behavior.

**Comment by LongLiveCHIEF** [comment]
@iarna This isn't a feature request, it's a bug. Consider:

I have the following two dependencies in my package.json:

```json
"dependencies": {
  "react":"^0.13.2",
  "radium":"^0.10.1"
}
```
Now, when I try to `npm i --save-dev react-style-guide`, I get a `npm ERR! code EPEERINVALID`, which tells me `the package react does not satisfy its siblings' peerDependencies requirements`.

```log
760 error code EPEERINVALID
761 error peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!
761 error peerinvalid Peer radium@0.10.1 wants react@>=0.12.0 <0.14.0
761 error peerinvalid Peer react-style-guide@1.0.2 wants react@^0.12.2
```

BUT, my installed package of react **does** in fact satisfy the dependencies. (The installed version is `0.13.2`. Any version of react up to, but not including `0.14.0` should meet the combined requirements of both the `react-style-guide` and `radium` components.

This kicks out an error when there shouldn't be an error.

**Comment by iarna** [comment]
npm@3 is the stable version of npm these days (and has been since last September) so I'm going to close this issue as it no longer applies. Thank you for taking the time to write this up.
