### ISSUE TITLE
npm drops privileges for child processes (particularly node-gyp)

### ISSUE THREAD

**Issue by Alaneor** [npm/npm#7570]
`npm -v` -> 2.7.0
`node -v` -> 0.12.0
`node-gyp -v` -> v1.0.2

Here's what I normally do in my workflow:

1. Log in to a development box as normal user - *vagrant* (VirtualBox, ArchLinux, but I don't think it matters...)
1. Escalate to root user - `sudo su`
1. Install project dependencies - `npm install`

**Expectation:** I would expect to not see any access rights-related errors, since I am *root*
**Reality:** when *npm* executes `node-gyp` to compile native addons, it does so by running the `sh` and `node-gyp` commands as the user I originally logged in with, *vagrant*, not the root user. Thus, I am seeing a bunch of `EACCES` errors.
**Current workaround**: Run *npm* with `sudo`: `sudo npm install`. But... I am already *root* - how can I be more *root*?:)

I have verified that the owner/group of */root* is indeed *root:root*.

The error I am seeing:

![Installation Error][install-error]

And from the below process tree, you can see that I logged in as user *vagrant*, then switched to *root*, but as soon as *npm* starts compiling native addons, the user is again *vagrant*.

![Process Tree][process-tree]

The installation continues without problems because *node-gyp* switches to an alternate temporary directory, but this only works because **I happen to install something in the home directory of the original user**. Were I now to install something in */root*, all hell would break loose:

![Infinite Loop][infinite-loop]

This goes on until I kill the process.

### Summary

The core of the problem seems to be that *npm* does not spawn child processes with the same user as it is currently running under, and that leads to problems with permissions.

Thanks for reading! Let me know if I can provide any further troubleshooting information on this topic.

[install-error]: http://s29.postimg.org/sekxq6q07/install_error.png
[process-tree]: http://s2.postimg.org/b1i5vwus9/process_tree.png
[infinite-loop]: http://s8.postimg.org/9x95tuded/infinite_loop.png

**Comment by othiym23** [comment]
Almost anything can be in lifecycle or build scripts; proper security dictates that tools like npm automatically running third-party scripts shouldn't trust them unnecessarily. Therefore, npm drops permissions when running those scripts. If you know what you're doing and trust the build scripts you're running, you can include `--unsafe-perms` as a switch to tell npm to not do that. Be careful!

**Comment by Alaneor** [comment]
Oh... Well, thanks. Seems this is also a documented ["feature"](https://docs.npmjs.com/misc/scripts#user). :)

**Comment by Alaneor** [comment]
As a second thought, from user experience perspective, it would be great if *npm* informed me that it is dropping privileges because I am running it as *root*. From the examples above, you can see that the only information I got was that it cannot access a folder to which *root* clearly is privileged to write.

#### Example
As soon as `node-gyp` (or any child process with dropped privs, for that matter) is about to be invoked, *npm* would print a `warn` with meaning similar to the following:
> npm is about to execute external script - dropping privileges to protect you, dear developer

**Comment by othiym23** [comment]
A terse note that npm is dropping privileges might be useful for many developers. Feel free to open that as a separate feature request, or even as a pull request!
