### ISSUE TITLE
Error: fetch failed with status code 404

### ISSUE THREAD

**Issue by Tink-** [npm/npm#7575]
When trying to install the nlp-node module using npm install, I encountered a "fetch failed error". I already tried npm cache clean and trying again, but this did not help. I checked the npm server status, but everything seems to be ok there. I uploaded the debug log as a gist here: https://gist.github.com/Tink-/4f5b8ba93232443905e6

I am using version 0.12.0 of Node and version 2.7.0 of npm. Does anyone have experience with a similar error? Any ideas on how to solve this? I'm new to node and npm, and I'm afraid I don't really understand the debug log fully.

Thanks in advance,
Kind regards

**Comment by smikes** [comment]
If you are new to node, then I would recommend that you start with `node@0.10.36` because it is a known-good, stable version of node.  Node 0.12 was just recently released and may have some problems with `https`, especially on Windows.  The alternative fork, io.js, is also releasing very frequently right now.

There were no major features added between 0.10.36 and 0.12, and the things that were added (better support for version 6 of Javascript) can be emulated or shimmed.

Please check back soon, though! This is not advice for the ages, this is based on my observations of what the node/iojs landscape is like right now.

**Comment by Tink-** [comment]
I installed node version 0.10.36, but I still get an error message when trying to install the module. However, it is a different error. I placed the debug log in a gist here: https://gist.github.com/Tink-/fce211903ce917481069

Do you have any possible solutions or any ideas as to what could cause this error?

**Comment by smikes** [comment]
Thanks for trying the downgrade to 0.12. Unfortunately the fact that you're still seeing 404 errors probably means that my suggestion was wrong: it may not be a node version problem at all.

My next suggestion is to try updating npm to latest while keeping node at 0.10.36. This is a little tricky on windows but there is a guide here: https://github.com/npm/npm/wiki/Troubleshooting

If that doesn't work, then the next thing I'd ask you about are your http proxy settings. Is there an http proxy on your network? Do you have to log into it?

**Comment by Tink-** [comment]
I contacted the the author of the package, and apparently the package was not up to date and that was causing the fetch errors.

Thanks for all the help!!

**Comment by Tink-** [comment]
I contacted the author of the module, and apparantly the module was not up to date, causing the fetch errors.
Thanks for all the help!

**Comment by iarna** [comment]
Closing as resolved.

**Comment by saurabh1223** [comment]
22403 verbose stack Error: fetch failed with status code 404
22403 verbose stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\fetch.js:51:14)
22403 verbose stack     at emitOne (events.js:96:13)
22403 verbose stack     at Request.emit (events.js:188:7)
22403 verbose stack     at Request.onRequestResponse (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:954:10)
22403 verbose stack     at emitOne (events.js:96:13)
22403 verbose stack     at ClientRequest.emit (events.js:188:7)
22403 verbose stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:474:21)
22403 verbose stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
22403 verbose stack     at TLSSocket.socketOnData (_http_client.js:363:20)
22403 verbose stack     at emitOne (events.js:96:13)
22403 verbose stack     at TLSSocket.emit (events.js:188:7)
22404 verbose cwd D:\workspaces\28_10_2016\MobileAppNew17102016
22405 error Windows_NT 10.0.10586
22406 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "ionic@1.3.18"
22407 error node v6.9.1
22408 error npm  v3.10.8
22409 error fetch failed with status code 404
22410 error If you need help, you may report this error at:
22410 error     <https://github.com/npm/npm/issues>
22411 verbose exit [ 1, true ]
