### ISSUE TITLE
npm update randomly remove module 

### ISSUE THREAD

**Issue by sdnetwork** [npm/npm#7580]
hi,

sometimes when i do a npm update on my node app npm fai and after there are certain module was removed  !

npm version : 1.4.28.

this is my dependecie in my package.json project : 

```` javascript
"dependencies": {
    "express": "3.4.6",
    "jade": "0.35.0",
    "ini": "1.2.0",
    "csv": "0.3.6",
    "async": "0.9.0",
    "node-firebird": "0.5.1",
    "ws": "0.6.3",
	"node-uuid": "1.4.2",
	"xml2js": "0.4.4"
	}
````

After a npm update in the same path that package.json sometimes some modules are removed or empty, in my last case the module csv,ws was entierely removed, and express, jade, xml2js are near empty (only the skeleton are present under the module directory !

i don't find any log  (debug.log) when there is the problem.

Anybody have also see this kind of problem ?

**Comment by sdnetwork** [comment]
An other exemple, this times it is som sub module of express that miss after a npm update : 

this is the list of sub module of express and their presence after npm update

debug => yes
fresh => no
methods => yes
mkdirp => yes
range-parser => yes
send => yes
buffer-crc32 => no
commander => yes
connect => yes
cookie => yes
cookie-signature => yes

It is really strange, can somebody tell me where i would find a log file ?
just a precision i launch npm update via node with 
```` javascript
var inst_npm = spawn('npm.cmd', ['update'], { stdio: 'inherit' });
````

**Comment by KenanY** [comment]
@sdnetwork I just tried to reproduce this myself but looks like `node-firebird@0.5.2`, which is in your `package.json` does not exist:

``` sh
$ npm info node-firebird versions 
[ '0.0.1',
  '0.0.2',
  '0.0.3',
  '0.0.4',
  '0.0.5',
  '0.0.6',
  '0.0.7',
  '0.0.8',
  '0.1.0',
  '0.1.1',
  '0.1.2',
  '0.1.3',
  '0.1.4',
  '0.2.0',
  '0.2.1',
  '0.2.3',
  '0.2.4',
  '0.2.5',
  '0.2.6',
  '0.3.0',
  '0.4.0',
  '0.5.0',
  '0.5.1' ]
```

**Comment by sdnetwork** [comment]
sorry effectively, it was 0.5.1

**Comment by KenanY** [comment]
@sdnetwork Okay, I'm using the latest stable release, `npm@2.7.0`, and I cannot reproduce this. All the modules that are missing for you aren't missing for me:

``` sh
$ npm ls csv
└── csv@0.3.6 

$ npm ls ws
└── ws@0.6.3 

$ npm ls fresh
└─┬ express@3.4.6
  └── fresh@0.2.0 

$ npm ls buffer-crc32
└─┬ express@3.4.6
  └── buffer-crc32@0.2.1 
```

Can you try [updating](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) your `npm` to see if that resolves your issue?

**Comment by sdnetwork** [comment]
thanks but the problem is random, npm update works in 95% of case ! 
it arrives more often on windows XP.

In witch case npm update remove module for update ? because in my case the module express was in the same version that in package.json. so i thank that npm update do nothing in this case no ?

**Comment by sdnetwork** [comment]
I have found this kind of file when there is the problem : 

1) 1a4234bd-e-modules-ws-node-modules-ultron.lock.STALE
2) 6dea629c-les-express-node-modules-methods.lock.STALE

these files are in the npm-cache, it can explain the problem ?

**Comment by smikes** [comment]
> thanks but the problem is random, npm update works in 95% of case ! 
it arrives more often on windows XP.

> In witch case npm update remove module for update ? because in my case the module express was in the same version that in package.json. so i thank that npm update do nothing (for express module) in this case no ?

What you are running into is a symptom of race conditions during install; these do not always happen, so mostly the install succeeds.  `npm@1.4.28` has numerous race condition bugs that were fixed in later `npm` versions.  You should definitely update your `npm` to the latest version, following the guide here <https://github.com/npm/npm/wiki/Troubleshooting>

```
Option 3: navigate to C:\Program Files (x86)\nodejs with cmd.exe and then run the installation without -g:

npm install npm
```

Once you have a current version of `npm`, you will have a fix for the race conditions that are sometimes causing installs to fail, or leaving stale locks lying around.

The problem where `npm update` sometimes removes a module is a symptom of a different problem, which is that in `npm` prior to 2.6.1 an `update` would cause all dependent modules to be updated at once.  When one of these modules had a `postinstall` script that expected its dependencies to be present, this would cause the installation to fail, and the modules would be left in an inconsistent state.

The latest version of `npm` fixes this by only attempting to update the top-level dependencies, not every dependency down the tree.  This is a partial fix for update problems; the complete fix is coming in the next major version of `npm`, `npm@3.0.0`, which is currently in development and is expected to be released soon.

**Comment by sdnetwork** [comment]
Thanks for your explaination,

my main problem is taht i have about one hundred machine with this version ! 
my technique to update the module is remplace the main package.json then check if there is some modules changes then if yes call a npm update.

I'm scared that if i update npm himself automatically, it could break itself and definitevly broke the app.

so i think i don't have any solution :( 

a little question when a race condition happen or when module is left in inconsistent state, waht is the exit code of npm update ?

**Comment by smikes** [comment]
Because these race conditions are bugs, the exit code is undefined.  It may be an error, it may be success, we can't predict.

You really should update all of your machines to the latest npm.

```
sudo npm install -g npm@latest
```

is a safe command that will update npm on a Linux-like system.

**Comment by sdnetwork** [comment]
on Windows i can do the same thing 

````
npm install -g npm@latest
````

and normaly it is safe like on linux ?

**Comment by sdnetwork** [comment]
I have just done a test on one machine and i obtain that : 

````
Microsoft Windows XP [version 5.1.2600]
(C) Copyright 1985-2001 Microsoft Corp.

C:\Documents and Settings\Administrator>npm -v
1.4.28

C:\Documents and Settings\Administrator>npm install -g npm@2.7
C:\Documents and Settings\Administrator\Application Data\npm\npm -> C:\Documents
 and Settings\Administrator\Application Data\npm\node_modules\npm\bin\npm-cli.js

npm@2.7.0 C:\Documents and Settings\Administrator\Application Data\npm\node_modu
les\npm

C:\Documents and Settings\Administrator>npm -v
1.4.28

C:\Documents and Settings\Administrator>
````

After the command i'm still in 1.4.28, i need to restart the machine ?

**Comment by KenanY** [comment]
@sdnetwork Upgrading on Windows is a little trickier, we have a [guide](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows) for it.

**Comment by sdnetwork** [comment]
I have done my first test with npm 2.7 and it seems better but after that the module express has been removed but i have a npm-debug.log ;)

i can send you the npm-debug.log if you want ? (i can't attach it in this issue isn't it ?)

**Comment by KenanY** [comment]
@sdnetwork Could you upload it as a [gist](https://gist.github.com)?

**Comment by sdnetwork** [comment]
yes this is the gist : https://gist.github.com/sdnetwork/77de58e2982af30fb995

**Comment by KenanY** [comment]
@sdnetwork Thanks, I've only done a quick skim and this caught my eye:

```
8101 error Windows_NT 5.1.2600
8102 error argv "node" "C:\\Documents and Settings\\Administrator\\Application Data\\npm\\node_modules\\npm\\bin\\npm-cli.js" "update"
8103 error node v0.10.33
8104 error npm  v2.7.0
8105 error 0-byte tarball
8105 error Please run `npm cache clean`
8106 error If you need help, you may report this error at:
8106 error     <http://github.com/npm/npm/issues>
```

Could you try running `npm cache clean` and see if that somehow fixes this issue? I won't guarantee it will but it's definitely harmless to try.

**Comment by sdnetwork** [comment]
I have done the same test on other machine that was potentially the problem but i have done a npm cache clean before and effectively no problem the update is succesfull !

but i think there is still a problem in the precedent test in any case the Express module should have been removed ! do you think you have a solution to prevent this case in v3 ?
