### ISSUE TITLE
npm --version does not show update version

### ISSUE THREAD

**Issue by doberkofler** [npm/npm#7581]
I was wondering, why after updating npm to the latest version using `npm install npm --global` the command `npm --version` still shows the original one ?

```
D:\MyDev\ljs_app\trunk\periscope\build>npm --version
2.5.1

D:\MyDev\ljs_app\trunk\periscope\build>npm install npm --global
C:\Users\doberkofler.LBITS\AppData\Roaming\npm\npm -> C:\Users\doberkofler.LBITS\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
npm@2.7.0 C:\Users\doberkofler.LBITS\AppData\Roaming\npm\node_modules\npm

D:\MyDev\ljs_app\trunk\periscope\build>npm --version
2.5.1
```

**Comment by KenanY** [comment]
@doberkofler https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows explains the troubles of updating on Windows. Most importantly the first paragraph:

> By default, `npm` is installed alongside node in `C:\Program Files (x86)\nodejs`. `npm`'s globally installed packages (including, potentially, `npm` itself) are stored separately in a user-specific directory (which is currently `C:\Users\<username>\AppData\Roaming\npm`). Because the installer puts `C:\Program Files (x86)\nodejs` before `C:\Users\<username>\AppData\Roaming\npm` on your `PATH`, it will always use version of `npm` installed with node instead of the version of `npm` you installed using `npm -g install npm@<version>`.

**Comment by doberkofler** [comment]
@KenanY Thank you!
