### ISSUE TITLE
Error with rendering of table of contents in markdown

### ISSUE THREAD

**Issue by eGavr** [npm/npm#7585]
Hi, I have such [md](https://github.com/bem/html-differ/blob/master/README.md) file in my repo.
And it is shown incorrectly on [npm](https://www.npmjs.com/package/html-differ).

**Comment by KenanY** [comment]
@eGavr Please open issues with the website here: [`npm/newww`](https://github.com/npm/newww). This repo is for issues with `npm`, the CLI.

**Comment by eGavr** [comment]
https://github.com/npm/newww/issues/718
