### ISSUE TITLE
Strange paths in `npm-shrinkwrap.json`

### ISSUE THREAD

**Issue by micahlmartin** [npm/npm#7591]
I’m having a weird issue with `npm shrinkwrap` that causes weird file paths to show up in the from field.

```
"yar": {
      "version": "3.0.3",
      "from": "../../../../var/folders/g6/1ls5zynn1176qkks242mjc440000gn/T/npm-11740-b6d8c215/git-cache-84ce586bbe7d/7b6a3819be47034a7a2d2d303e695eefa2bdff2c",
      "resolved": "git://github.com/micahlmartin/yar#7b6a3819be47034a7a2d2d303e695eefa2bdff2c”,
```

I’m not sue if it’s an actual problem or not but it seems really strange. I’ve seen it happen with other packages too. Most everything else seems to have a much more normal looking from path like this:

```
"autoprefixer-loader": {
      "version": "1.1.0",
      "from": "autoprefixer-loader@>=1.1.0 <2.0.0",
      "resolved": "https://registry.npmjs.org/autoprefixer-loader/-/autoprefixer-loader-1.1.0.tgz”,
```

Any ideas what might be causing this? I'm running `nvm` so I'm not sure whether or not that has anything to do with it.

**Comment by KenanY** [comment]
@micahlmartin `npm --version`?

**Comment by ackernaut** [comment]
I have had the same issue and I'm currently using `2.7.0`.

**Comment by KenanY** [comment]
@ackernaut This was fixed in `npm@2.7.1`. Original issue: https://github.com/npm/npm/issues/7121, Fix: https://github.com/npm/npm/pull/7539 :)

**Comment by ackernaut** [comment]
:+1: Good to know, thanks!!

**Comment by iarna** [comment]
Closing as resolved.
