### ISSUE TITLE
Safety regarding publishing .npmrc

### ISSUE THREAD

**Issue by bucaran** [npm/npm#7592]
I would like to manage my user's `$HOME/.npmrc` along with my dotfiles, but I am not sure if I should worry about this field (is this my base64-encoded npm's password?)   

```
//registry.npmjs.org/:_password=P2Vl......UyOA==
```

**Comment by aredridel** [comment]
Yes, do: that is your password as base64. To see it, try `echo P2Vl......uY0A== | base64 -D` (if you're on a mac; there are base64 tools for every OS under various names.)

**Comment by bucaran** [comment]
@aredridel  How can I stop npm from adding this automatically to `.npmrc` so that I can safely sync it with my dotfiles?

**Comment by othiym23** [comment]
The short answer is you can't. The original purpose of that file was to store user credentials for the registry, and this is still one of its primary functions. At some point in the near future,the npm registry will switch to using token-based auth, but even that isn't safe to check in. Sorry, but this isn't safe config to share.

**Comment by bucaran** [comment]
Perhaps a solution would be to encrypt the file and sync it with my dotfiles.
