### ISSUE TITLE
"npm install" reinstalls git dependencies every time

### ISSUE THREAD

**Issue by rluba** [npm/npm#7593]
Whenever we run `npm install`, each dependency that is specified as a git URL (`"some-module": "git+ssh://git@repo-url#v1.2.3"`)  is fully removed and reinstalled. Is this intended behavior? If yes, can we avoid it somehow?

```
> npm -v
2.6.1
> node -v
v0.10.34
```

We started to notice this because some of the modules have native dependencies which causes multiple compile steps and _looong_ delays whenever we run `npm install`.

**Comment by rluba** [comment]
[Here's a small gist to illustrate the problem](https://gist.github.com/rluba/2e936f3e0e587715a52c).

**Comment by KenanY** [comment]
Dupe of https://github.com/npm/npm/issues/4191, I think.

**Comment by rluba** [comment]
@KenanY Yes, you are right.
