### ISSUE TITLE
npm.web relative links are broken.

### ISSUE THREAD

**Issue by llafuente** [npm/npm#7594]
Relative links should use "homepage" in package.json as base for href otherwise some links are broken.

Example: [mongoose-ref-query](https://www.npmjs.com/package/mongoose-ref-query)

at the end you will find an anchor "see http-interface" which target is `https://www.npmjs.com/package/docs/http-interface.md` and should be `https://github.com/fghibellini/mongoose-ref-query/docs/http-interface.md`

**Comment by KenanY** [comment]
@llafuente Issues with the website should be opened over at [`npm/newww`](https://github.com/npm/newww). This is the repo for `npm`, the CLI.
