### ISSUE TITLE
grunt issue

### ISSUE THREAD

**Issue by biebergagabcbs** [npm/npm#7599]
when I run grunt in Nodejs and Git I get the following error: 

Loading "Gruntfile.coffee" tasks...
Cannot find module: uproxy-lib/tools/taskmanager
Task "default" not found

how to fix this error. thanks.

**Comment by KenanY** [comment]
@biebergagabcbs Could you expand on your issue a bit more? With just those three lines, I cannot even tell if this is an `npm` issue to begin with.

**Comment by biebergagabcbs** [comment]
I ran the following ok.
npm install -g -d bower
npm install -g -d grunt-cli
npm install -d
bower install -d

when I run grunt I get the following messages.

Loading "Gruntfile.coffee" tasks...
Cannot find module: uproxy-lib/tools/taskmanager
Task "default" not found

**Comment by KenanY** [comment]
@biebergagabcbs Can you try running `grunt` with the `--verbose` flag: `grunt --verbose`? Might provide some more information on what's going on here.

**Comment by smikes** [comment]
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
