### ISSUE TITLE
Request: cli shortcut for shorthands

### ISSUE THREAD

**Issue by RichardLitt** [npm/npm#7600]
Typing `npm help 7 config` in order to see a list of shorthands is difficult to remember and oddly longwinded. Can there be a shortcut to show these?

**Comment by othiym23** [comment]
From my comment on #7601:

> It makes more sense to me to follow Git's model here and start pushing more of the shortcuts out to the documentation for the subcommands that use the shortcuts, which is something that people have been doing in fits and starts over the last couple months. I also think it would be nice to have Git-style command-line help tailored per subcommand.

Do either of those sound like things you'd be interested in hacking on?

**Comment by RichardLitt** [comment]
Yeah, I'm down. Sounds good to me. I'll see what I can do.

**Comment by RichardLitt** [comment]
@othiym23 Is this still an issue, or has npm 2 fixed it? Happy to hack away, back burned it until now.

**Comment by othiym23** [comment]
It would still be great to have a slightly less terse output for `npm --help`! If you're just starting it now, I'd probably do it against `master` / `npm@3` (which is veeeerrry close to general release now). Thanks for circling back to this!

**Comment by RichardLitt** [comment]
That's off of this commit, right? https://github.com/npm/npm/commit/1569304243ea91e01b5d8548950ace75a6e9fbfc

I haven't forked off of a tag before, just checking.

**Comment by othiym23** [comment]
No, just pull down master and target that. (`npm@2` is currently being developed off the `2.x` branch – apologies for not being clear).
