### ISSUE TITLE
npm install npm -g deletes /usr/local/bin/npm

### ISSUE THREAD

**Issue by natsn** [npm/npm#7603]
nathann@glitch ~ $ npm -v
    2.5.1
    nathann@glitch ~ $ npm install npm -g
    npm ERR! Darwin 14.1.0
    npm ERR! argv "node" "/usr/local/bin/npm" "install" "npm" "-g"
    npm ERR! node v0.12.0
    npm ERR! npm  v2.5.1
    npm ERR! path /usr/local/lib/node_modules/npm/.eslintrc
    npm ERR! code EACCES
    npm ERR! errno -13

    npm ERR! Error: EACCES, unlink '/usr/local/lib/node_modules/npm/.eslintrc'
    npm ERR!     at Error (native)
    npm ERR!  { [Error: EACCES, unlink '/usr/local/lib/node_modules/npm/.eslintrc']
    npm ERR!   errno: -13,
    npm ERR!   code: 'EACCES',
    npm ERR!   path: '/usr/local/lib/node_modules/npm/.eslintrc' }
    npm ERR!
    npm ERR! Please try running this command again as root/Administrator.
    npm ERR! error rolling back Error: EACCES, unlink '/usr/local/lib/node_modules/npm/.eslintrc'
    npm ERR! error rolling back     at Error (native)
    npm ERR! error rolling back  { [Error: EACCES, unlink '/usr/local/lib/node_modules/npm/.eslintrc']
    npm ERR! error rolling back   errno: -13,
    npm ERR! error rolling back   code: 'EACCES',
    npm ERR! error rolling back   path: '/usr/local/lib/node_modules/npm/.eslintrc' }

    npm ERR! Please include the following file with any support request:
    npm ERR!     /Users/nathann/npm-debug.log
    nathann@glitch ~ $ npm
    -bash: /usr/local/bin/npm: No such file or directory
    nathann@glitch ~ $

I'm on a mac and I reinstalled with the pkg from the node website. This time i ran it with sudo and it worked. But anytime I run `npm install npm -g` I get the same error npm is gone.

**Comment by smikes** [comment]
This is an unusual error.  `npm` does not ship the file `.eslintrc` -- do you have any idea how it is getting created in your `npm` directory?

The problem where attempting to update `npm` fails, causing `npm` to be removed, is a known bug.  I am not sure what the canonical issue for it is, but with either `npm update -g` or `npm install -g npm@latest` when `npm` encounters an error, it attempts to roll abck the installation; sometimes this results in `npm` being uninstalled and the system being left in a broken state.

It sounds like you have already found out how to recover from this, which is to run 

```
curl -L https://npmjs.com/install.sh | sudo sh
```

I'm sorry this bit you -- but the good news is that `npm@3` is nearly ready for release, and it will handle updates and installs much more robustly, so we are hoping this bug will be fixed, very soon.

**Comment by dapithor** [comment]
This looks to be related to an issue I had last year that is still unresolved Issue #5050

**Comment by smikes** [comment]
@dapithor this is probably a different issue; the problem where `npm update -g` removes `npm` occurs when multiple packages are being installed concurrently and a failure causes `npm` to roll back, removing `npm` itself.

This looks like the presence of an unexpected file prevents `npm` from removing the old version of the `/usr/local/bin/npm` directory, which is a prerequisite to installing a new `npm`.

**Comment by kevnchu** [comment]
I had the same issue when trying to update npm without root privileges.

```
$ npm install -g npm
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "npm"
npm ERR! node v1.1.0
npm ERR! npm  v2.4.1
npm ERR! path /usr/local/lib/node_modules/npm
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall unlink

npm ERR! Error: EACCES: permission denied, unlink '/usr/local/lib/node_modules/npm'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, unlink '/usr/local/lib/node_modules/npm']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'unlink',
npm ERR!   path: '/usr/local/lib/node_modules/npm' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
npm ERR! error rolling back Error: EACCES: permission denied, unlink '/usr/local/lib/node_modules/npm'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EACCES: permission denied, unlink '/usr/local/lib/node_modules/npm']
npm ERR! error rolling back   errno: -13,
npm ERR! error rolling back   code: 'EACCES',
npm ERR! error rolling back   syscall: 'unlink',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/npm' }

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kevnchu/Code/npm-debug.log
$ npm
bash: /usr/local/bin/npm: No such file or directory
```

**Comment by natsn** [comment]
`lrwxr-xr-x  1 nathann  admin                       38 Mar 11 14:59 npm@ -> ../lib/node_modules/npm/bin/npm-cli.js`
`-rwxr-xr-x  1 nathann  staff                  340 Jan 26 14:46 npm*`
`drwxr-xr-x  30 nathann  admin  1020 Apr  7 17:42 node_modules/`

Do you own the node_modules directory or does root?

I just tried the install again with those permissions and it worked...

```
nathann@glitch ~ $ npm install -g npm
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
npm WARN unmet dependency /usr/local/lib/node_modules/live-server/node_modules/connect/node_modules/multiparty/node_modules/stream-counter requires readable-stream@'~1.1.8' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/live-server/node_modules/connect/node_modules/multiparty/node_modules/readable-stream,
npm WARN unmet dependency which is version 1.1.13-1
npm@2.7.5 /usr/local/lib/node_modules/npm
nathann@glitch ~ $
```

**Comment by kevnchu** [comment]
Odd, root owns the node_modules directory in /usr/local/lib on my machine. Anytime I do a global install it requires root.

```
$ ls -l /usr/local/lib/
total 0
drwxrwxr-x  6 root   wheel  204 Apr  7 14:57 node_modules
```

I installed iojs / npm via the pkg.

**Comment by othiym23** [comment]
@kevnchu That's how the installer sets the permissions. You can either stick with doing `sudo npm install -g` for all your global installs, or you can run `sudo chown -R $(whoami) /usr/local/lib/node_modules` once per each time you upgrade npm using the installers (or you can follow the [instructions for installing Homebrew](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/FAQ.md#why-does-homebrew-say-sudo-is-bad-), which does something similar). Technically, anything in `/usr/local` should be owned by root / a wheel or system account, because that's a shared directory tree on multiuser systems and should be secured accordingly, but it's increasingly uncommon for people's Unix systems to be multiuser. Especially when they're your laptop.

@smikes Some versions of npm include a bundled `.eslintrc` (it's not in git, but it was in my local checkout before I decided to switch to `standard`), so that's kind of a red herring.

**Comment by othiym23** [comment]
(Closing in favor of #5050, which should be handled by the release of `npm@3`.)

**Comment by natsn** [comment]
@othiym23 Thanks for the concise clarifications.
