### ISSUE TITLE
npm dependencies not to install

### ISSUE THREAD

**Issue by SaveTimE** [npm/npm#7612]
I run into an error I don't understand.
nodejs and npm install worked fine.
OS Ubuntu Server 14.04.1 (x64) on VM
software installed: Apache, nodejs, npm

It seem it give a problem with package.json
How can I resolve it?

Thanks
TimE

```
root@myubuntu:/# npm install
npm ERR! install Couldn't read dependencies
npm ERR! Error: ENOENT, open '/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-24-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /npm-debug.log
npm ERR! not ok code 0
```

npm-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'install' ]
2 info using npm@1.3.10
3 info using node@v0.10.25
4 error install Couldn't read dependencies
5 error Error: ENOENT, open '/package.json'
6 error If you need help, you may report this log at:
6 error     <http://github.com/isaacs/npm/issues>
6 error or email it to:
6 error     <npm-@googlegroups.com>
7 error System Linux 3.13.0-24-generic
8 error command "/usr/bin/nodejs" "/usr/bin/npm" "install"
9 error cwd /
10 error node -v v0.10.25
11 error npm -v 1.3.10
12 error path /package.json
13 error code ENOENT
14 error errno 34
15 verbose exit [ 34, true ]
```

**Comment by KenanY** [comment]
@SaveTimE Do you have a `package.json` in your current working directory? `npm` has absolutely no idea what you want it to install unless you give it some arguments or you have a `package.json` in your current working directory. The documentation on [`npm install`](https://docs.npmjs.com/cli/install) might help; there's also a [tutorial](https://docs.npmjs.com/getting-started/installing-npm-packages-locally) on installing packages locally.

**Comment by SaveTimE** [comment]
Hi KenanY,
I solved it, found the missing file.
Thanks
TimE

**Comment by nwarrior** [comment]
Hey SaveTimE I am running into the same problem, and I verified that package.json is in my directory.

How did you manage to solve this issue?

**Comment by KenanY** [comment]
@nwarrior Could you upload the resulting `npm-debug.log` as a [gist](https://gist.github.com/)?

**Comment by nwarrior** [comment]
Hey KenanY thanks for the quick response, I seem to have figured it out.

I wasn't in a directory that had Admin Privileges, it seems to be working it's magic at the moment. I will let you know if I have any other problems.

Cheers

**Comment by kevva** [comment]
@KenanY, boom, close.

**Comment by KenanY** [comment]
@kevva I would if I could :)

**Comment by iarna** [comment]
Closing as resolved.
