### ISSUE TITLE
gulp is not getting installed on ubuntu

### ISSUE THREAD

**Issue by sumit-satnalika** [npm/npm#7617]
```
npm ERR! Error: version not found: gulp : gulp/gulp
npm ERR!     at RegClient.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:308:14)
npm ERR!     at Request._callback (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:246:65)
npm ERR!     at Request.self.callback (/usr/lib/node_modules/npm/node_modules/request/request.js:236:22)
npm ERR!     at Request.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:1142:14)
npm ERR!     at Request.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:1096:12)
npm ERR!     at IncomingMessage.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:943:16
npm ERR!     at process._tickCallback (node.js:419:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.2.0-40-virtual
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "gulp" "-g"
npm ERR! cwd /home/sumit/wow
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/sumit/wow/npm-debug.log
npm ERR! not ok code 0
```

**Comment by LoicMahieu** [comment]
Try to update your NPM with `npm update -g npm@latest`

**Comment by kevva** [comment]
What command are you trying to run? `npm ERR! Error: version not found: gulp : gulp/gulp` tells me you are doing something weird.

**Comment by KenanY** [comment]
@kevva Command is in the log:

```
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "gulp" "-g"
```

**Comment by kevva** [comment]
Well `gulp/gulp` is nothing so there is something weird going on here.

**Comment by KenanY** [comment]
@kevva Yeah... @sumit-satnalika could you upload the full `npm-debug.log` as a [gist](https://gist.github.com/) (preferably after trying out @LoicMahieu's suggestion)?

**Comment by sumit-satnalika** [comment]
Guys issue is resolved. 
npm config set registry https://registry.npmjs.org 
Solved the issue for me....
Thankyou all for ur suggestions...

**Comment by smikes** [comment]
Is this still a problem for you?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
