### ISSUE TITLE
insufficient space errors

### ISSUE THREAD

**Issue by stephencpd** [npm/npm#7619]
Hi,
I'm interested in using Yeoman and am following their getting started page.
node -v returns v0.12.0
npm -v returns 2.5.1

I have install globally, grunt-cli, bower, yo and generator-webapp (scaffolding for a bootstrap project)
Whenever I run yo webapp, it gets to the npm install section and fails as below:

```
npm WARN package.json yeoman@ No description
npm WARN package.json yeoman@ No repository field.
npm WARN package.json yeoman@ No README data
npm WARN optional dep failed, continuing imagemin-jpegtran@1.0.0
npm WARN optional dep failed, continuing imagemin-pngquant@1.0.2
npm WARN optional dep failed, continuing imagemin-optipng@1.0.0
npm WARN optional dep failed, continuing imagemin-gifsicle@1.0.0
npm WARN optional dep failed, continuing imagemin-svgo@1.0.2
npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! path ../rimraf/bin.js
npm ERR! code ENOTSUP
npm ERR! errno -95

npm ERR! nospc ENOTSUP, symlink '../rimraf/bin.js'
npm ERR! nospc This is most likely not a problem with npm itself
npm ERR! nospc and is related to insufficient space on your system.
```

I have also tried some other install, such as foundation (using libsass), as per the tutorial on the zurb website, but again I get the same error with the npm install section.

My debian install is in a 40GB partition and there is plenty of space in there, so I don't know how to proceed fixing this. I have googled, to no avail. It seems this problem is not common.

Any help would be greatly appreciated.

**Comment by aredridel** [comment]
What filesystem is this on?

Does it happen to be a virtual machine on a filesystem shared with the host?

**Comment by stephencpd** [comment]
Hi, aredridel, that's quite interesting that you should say that!
Yes, my Debian is running in Hyper-V and I'm mounting an NTFS share with cifs. It is into this mountpoint that I'm trying to start my projects.
I just tried yo webapp to my home directory and I didn't get the error (although interestingly, previously I had)

Do you have a similar experience, or perhaps a solution?

Stephen

**Comment by lukasbloom** [comment]
> Running with --no-bin-links fixed it for me:
> 
> npm install --no-bin-links
> 
> --no-bin-links tells npm to not create any symbolic links. There isn't a way (to my knowledge) of > translating symlinks to a windows share.

http://askubuntu.com/a/269735

**Comment by iarna** [comment]
stephencpd: The reason this is a problem is that systems that look like unix are expected to support symlinks and folders shared from Windows don't.  When running natively on Windows npm creates `.cmd` files to run it's binaries instead of making a symlink.

**Comment by smikes** [comment]
Is this still a problem for you?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by YoungElPaso** [comment]
I had the same issue, same fix (--no-bin-links) worked as well.  Nice @lukasbloom

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
