### ISSUE TITLE
Symlink errors are really unclear and difficult to resolve

### ISSUE THREAD

**Issue by jescalan** [npm/npm#7620]
Hi there,

So I'm only filing this after having dealt with it on multiple peoples' machines many times. Fairly often, when npm is installing dependencies, there will be a symlink error, most of the time, this is when it is trying to symlink a binary but it already exists (I think this occurs if the package is a local dependency but has already been installed globally). The error looks something like this in the latest version of npm (`2.5.1`):

```
npm ERR! EEXIST, symlink '[path to project]/node_modules/.bin/uglifyjs'
File exists: [path to project]/node_modules/.bin/uglifyjs
Move it away, and try again.
```

This is not just uglifyjs, there are many instances of this issue with various libraries, I'm just using this as an example since it's the most recent encounter. Now, the issue description is quite clear -- it's trying to symlink to a location where a symlink already exists. Move or remove the existing symlink then try again. Fair enough. The problem with this error message is that it tells you **the path to the file it's trying to symlink, rather than the path it's trying to symlink to**. This makes it extremely difficult to debug, since what you need to know in order to resolve an issue like this is the path that it's trying to symlink to.

I'm not sure if this is possible based on npm's architecture and they way it reports errors, but if possible it would be extremely useful if npm would report the path to the existing file/symlink that is actually causing the error.

Thanks for your time and your hard work on this amazing tool, and let me know if there's anything else I can do to help out with this!

**Comment by othiym23** [comment]
Try installing `npm@next` and see if this remedies the problem. One of the two big bug fixes in this release is intended to address exactly this issue: fb0ac26eecdd76f6eaa4a96a865b7c6f52ce5aa5

**Comment by jenius** [comment]
Cool, will give it a shot next time I can reproduce the issue and report back here :grinning:

**Comment by plato-cambrian** [comment]
I am still encountering this error after `npm install -g npm@next`:
```

npm ERR! Linux 3.13.0-44-generic
npm ERR! argv "node" "/home/ubuntu/node-v0.12.0-linux-x64/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.7.4
npm ERR! path /home/ubuntu/sopro/apps/chat/node_modules/.bin/cucumber-junit
npm ERR! code EEXIST
npm ERR! errno -17

npm ERR! EEXIST, symlink '/home/ubuntu/sopro/apps/chat/node_modules/.bin/cucumber-junit'
File exists: /home/ubuntu/sopro/apps/chat/node_modules/.bin/cucumber-junit
Move it away, and try again.
```

I do NOT have a `cucumber` binary in my system path.
I ran `rm -rf node_modules/` before running `npm install`.
Here is the contents of the .bin folder where the symlink fails:
```
ubuntu@ip-172-31-25-56:~/sopro/apps/chat/node_modules/.bin$ ls -l
total 0
lrwxrwxrwx 1 ubuntu ubuntu 18 Mar 20 16:18 bower -> ../bower/bin/bower
lrwxrwxrwx 1 ubuntu ubuntu 27 Mar 20 16:18 cucumber-js -> ../cucumber/bin/cucumber.js
lrwxrwxrwx 1 ubuntu ubuntu 27 Mar 20 16:18 cucumber.js -> ../cucumber/bin/cucumber.js
lrwxrwxrwx 1 ubuntu ubuntu 20 Mar 20 16:18 newman -> ../newman/bin/newman
lrwxrwxrwx 1 ubuntu ubuntu 26 Mar 20 16:18 phantomjs -> ../phantomjs/bin/phantomjs
```

**Comment by plato-cambrian** [comment]
I found a workaround:
```
$ rm -rf node_modules/
$ npm install cucumber-junit
$ npm install
```

For anyone wanting to reproduce this in the future, i am experiencing these problems with [this commit](https://github.com/SocietyPro/sopro/blob/e478aa7ed5e2998886d84a991a9a4aa23bc4093e/apps/chat/package.json) of my project

**Comment by othiym23** [comment]
@plato-cambrian I'll take a look -- I suspect, based on your workaround, that you're running into a separate issue a few other people have seen, which is related to multiple things trying to claim the same symlink name. I won't have time to get to this for a week or so, because of other work I have in the pipeline. Thanks for the report and the link to a repro case!

**Comment by iarna** [comment]
This may with the npm multi-stage branch, where bin conflicts are treated like package version conflicts.

**Comment by developit** [comment]
Got bit by this today, seemed to be related to `phantomjs` VS `phantomjs-prebuilt` trying to create the same `.bin/phantomjs` symlink.

**Comment by tridot-tp** [comment]
I'm having the exact same issue re: phantomjs VS phantomjs-prebuilt.  How are you working around it @developit ?

**Comment by incubus8** [comment]
is there any update and workaround on this issue? it happens on my machine with phantomjs.

**Comment by skliffmueller** [comment]
phantomjs-prebuilt attempts to use version 2.1.1, while phantomjs uses 1.9.8, if the npm repos would use the most current versions provided by phantomjs, there would be no need for one to write over the other. This needs to be addressed to phantomjs.
