### ISSUE TITLE
OS X: "npm ERR! cb() never called!" error when installing imagemin

### ISSUE THREAD

**Issue by hal-gh** [npm/npm#7625]
I raised this issue at [imagemin/issues/90](https://github.com/imagemin/imagemin/issues/90), but it's probably more appropriate here.

Environment:
* OS X 10.9.5 (Darwin macbookpro.local 13.4.0 Darwin Kernel Version 13.4.0: Wed Dec 17 19:05:52 PST 2014; root:xnu-2422.115.10~1/RELEASE_X86_64 x86_64)
* node: v0.10.36
* nvm: 0.24.0
* npm: 2.7.1
* imagemin-pngquant 4.0.0 (latest) [installs successfully, dependency of imagemin]
* imagemin 3.1.0 (latest)

On my OS X system, `npm install imagemin` fails with the error, "npm ERR! cb() never called!", after running these two commands in a fresh project:

```
npm install imagemin-pngquant
npm install imagemin
```

I have a project that depends on over 50 other packages, and none have this issue.

It has been tested by others (see the above thread), but no-one can seem to replicate it. It also works fine on my ubuntu 12.04 system.

I managed to get it to work correctly once, but it hasn't done this before or since.

I've used the `npm -ddd` debug argument to produce the log files in this gist:

https://gist.github.com/hal-gh/2d503006ad74013519b6

Any help would be appreciated.

**Comment by hal-gh** [comment]
It installs successfully when using npm 1.4.28.

**Comment by hal-gh** [comment]
The following environments also work:

```
nvm 0.24.0
node v0.12.0
npm 2.7.1
```

```
nvm 0.24.0
iojs v1.5.1
npm 2.7.1
```

**Comment by hal-gh** [comment]
I've updated the gist. There is a script, `remove-packages.sh`, that deletes everything in node_modules and clears the cache. The log file, `npm-install.log` is new, created by running `npm -ddd install &>npm-install.log`.

**Comment by shanesmith** [comment]
For what it's worth, had an almost exact situation (OS X 10.9.5, node v0.10.36, npm 2.5.1) that also produced the same error. 

An update to node v0.12.0 has also fixed it for us.

**Comment by hal-gh** [comment]
Just in case anyone else has issues like this, I'm now using the following environment, and it works fine.

```
nvm 0.24.0
node: v0.12.7
npm: 3.3.9
```

**Comment by othiym23** [comment]
I'm going to call this resolved for now @hal-gh. `npm@3` is now the supported release series for npm, and if you're no longer seeing the issue using `npm@3`, it's probably all good. It would be good to get this fixed in `npm@2` for now, but that would require us to have a reliable repro case, and I don't think we were ever able to reproduce this issue locally. Thanks for the update!
