### ISSUE TITLE
Error installing npm

### ISSUE THREAD

**Issue by maggiedziong** [npm/npm#7626]
I am trying to do an npm install in an angular-kickstarter project and I keep getting errors.. 

It starts with this :
> npm WARN engine karma@0.12.31: wanted: {"node":"~0.8 || ~0.10"} (current: {"node":"0.12.0","npm":"2.5.1"})

>fsevents@0.3.5 install /Users/maggiedziong/Documents/WebDev/BlogMap/node_modules/karma/node_modules/chokidar/node_modules/fsevents
node-gyp rebuild

> child_process: customFds option is deprecated, use stdio instead.
  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node: Finished
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
  SOLINK_MODULE(target) Release/fse.node: Finished
npm ERR! Darwin 13.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
>npm ERR! npm  v2.5.1

>npm ERR! null == true
> npm ERR!

Then it installs a bunch of stuff but ultimately fails. 

Here is the debug:
https://gist.github.com/maggiedziong/3f7358b207ff177b9248#file-npm-debug

**Comment by KenanY** [comment]
@maggiedziong 

```
npm ERR! null == true
```

Unfortunately, this is a Node bug: https://github.com/npm/npm/issues/7349

**Comment by anabellchan** [comment]
I have the same issue here with npm install -g karma.  Wonder if someone found a way to work around with this issue.

**Comment by KenanY** [comment]
@anabellchan There are no errors in the log you've posted. Are you concerned about the `WARN`s?

**Comment by anabellchan** [comment]
Yes, I'm eyeing particularly on npm WARN optional dep failed, continuing fsevents@0.3.5

This may be related to failed initialization on jasmine using karma:

C:\Program Files\nodejs\node_modules\karma\bin>karma init
'karma' is not recognized as an internal or external command,
operable program or batch file.

**Comment by KenanY** [comment]
@anabellchan `fsevents` provides access to some Mac OS X specific features. Since you are on Windows, that _optional_ dependency is of course not installed.

**Comment by anabellchan** [comment]
Thanks, that helps.

**Comment by niculistana** [comment]
Hello, have you tried changing the version of your node? Try installing nvm and install a stable build.

**Comment by anabellchan** [comment]
I found out how to fix the problem.  Use gitbash and run as Administrator on running karma.  Doh!

**Comment by iarna** [comment]
Closing this as resolved.

**Comment by dixon-afl** [comment]
I am also having the same problem , and couldn't able to fix it, can any one help?

**Comment by dixon-afl** [comment]
Fixed it by installing node version 0.10.29, any other fix?
