### ISSUE TITLE
Error installing castnow using npm

### ISSUE THREAD

**Issue by juanluperez** [npm/npm#7628]
```
# npm install castnow -g
npm ERR! Linux 3.17.7-hardened-r1
npm ERR! argv "node" "/usr/bin/npm" "install" "castnow" "-g"
npm ERR! node v0.10.30
npm ERR! npm  v2.7.1

npm ERR! Cannot call method 'trim' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN engine windows-no-runnable@0.0.6: wanted: {"node":"0.6"} (current: {"node":"0.10.30","npm":"2.7.1"})
npm ERR! Linux 3.17.7-hardened-r1
npm ERR! argv "node" "/usr/bin/npm" "install" "castnow" "-g"
npm ERR! node v0.10.30
npm ERR! npm  v2.7.1

npm ERR! Cannot call method 'trim' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.10.30","npm":"2.7.1"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.10.30","npm":"2.7.1"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.10.30","npm":"2.7.1"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.10.30","npm":"2.7.1"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.10.30","npm":"2.7.1"})

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
```
npm-debug.log: https://bpaste.net/show/0cf2912de30f

**Comment by smikes** [comment]
Thanks for the bug report.  

It looks like you have recently updated your `node` from 0.8 to 0.10.  Since you have a current `npm`, you can try `npm update`  and `npm update -g` to get your modules up to date; that's no longer broken.

Here is the relevant portion of the stack trace:
```
2811 verbose type non_object_property_call
2812 verbose stack TypeError: Cannot call method 'trim' of undefined
2812 verbose stack     at /usr/lib64/node_modules/npm/lib/cache/add-remote-git.js:98:32
2812 verbose stack     at /usr/lib64/node_modules/npm/lib/utils/git.js:50:14
2812 verbose stack     at F (/usr/lib64/node_modules/npm/node_modules/which/which.js:40:25)
2812 verbose stack     at E (/usr/lib64/node_modules/npm/node_modules/which/which.js:43:29)
2812 verbose stack     at /usr/lib64/node_modules/npm/node_modules/which/which.js:54:16
2812 verbose stack     at Object.oncomplete (fs.js:107:15)
2813 verbose cwd /root
2814 error Linux 3.17.7-hardened-r1
2815 error argv "node" "/usr/bin/npm" "install" "castnow" "-g"
2816 error node v0.10.30
2817 error npm  v2.7.1
2818 error Cannot call method 'trim' of undefined
2819 error If you need help, you may report this error at:
2819 error     <https://github.com/npm/npm/issues>
```

**Comment by juanluperez** [comment]
I had run npm update and npm update -g before reporting this issue. I ran those command again after you pointed this out, same result.

I have to say that I'm using nodejs from Gentoo stable package repository.

**Comment by juanluperez** [comment]
I installed git and now it is working, but, look at this:
# npm list sntp -g
 -> /usr/lib64 /usr/lib
├─┬ castnow@0.4.12
│ └─┬ read-torrent@1.3.0
│   └─┬ request@2.16.6
│     └─┬ hawk@0.10.2
│       └── sntp@0.1.4 
├─┬ npm@2.7.1
│ └─┬ request@2.53.0
│   └─┬ hawk@2.3.1
│     └── sntp@1.0.9 
└─┬ peerflix@0.29.0
  └─┬ read-torrent@1.3.0
    └─┬ request@2.16.6
      └─┬ hawk@0.10.2
        └── sntp@0.1.4

**Comment by smikes** [comment]
Is this still a problem for you?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.

**Comment by ram0811** [comment]
$ npm install castnow -g

npm WARN engine windows-no-runnable@0.0.6: wanted: {"node":"0.6"} (current: {"node":"4.0.0","npm":"2.14.3"})
npm WARN engine mdns-js@0.4.0: wanted: {"node":"^0.10.3 || ^0.12.0"} (current: {"node":"4.0.0","npm":"2.14.3"})
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"4.0.0","npm":"2.14.3"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"4.0.0","npm":"2.14.3"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"4.0.0","npm":"2.14.3"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"4.0.0","npm":"2.14.3"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"4.0.0","npm":"2.14.3"})
npm ERR! Linux 3.16.0-48-generic
npm ERR! argv "/home/ram/Apps/node-v4.0.0/bin/node" "/usr/bin/npm" "install" "castnow" "-g"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.3

npm ERR! shasum check failed for /tmp/npm-24032-1426c5b0/registry.npmjs.org/meow/-/meow-3.3.0.tgz
npm ERR! Expected: f8777fd0db67f73d1de1beee08c97c8665efc6ed
npm ERR! Actual:   da39a3ee5e6b4b0d3255bfef95601890afd80709
npm ERR! From:     https://registry.npmjs.org/meow/-/meow-3.3.0.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ram/npm-debug.log


Log file located here -- https://drive.google.com/file/d/0B4ZMDyTAMccPbExzelJTVHhScjA/view?usp=sharing

**Comment by KenanY** [comment]
@ram0811 Your issue seems unrelated to the thread you have commented on. Regardless, I suggest to take a look at http://status.npmjs.org/incidents/pyw00fmpjzrh
