### ISSUE TITLE
Problems using NPM as library

### ISSUE THREAD

**Issue by DaAwesomeP** [npm/npm#7631]
My app will use NPM as is package manager and I would like to install/update/remove packages with it. I would prefer to do this with a library and not use the CLI as a child process.

I found that I can include NPM in a `require()`, but how do I use it?

**Comment by DaAwesomeP** [comment]
Never mind. I just found this: https://github.com/npm/npm#using-npm-programmatically

**Comment by DaAwesomeP** [comment]
Actually, I'm having some problems:

1. When I install packages, it often misses lots of the packages' dependencies.
2. It always writes to the console by itself. I cannot seem to stop it.

To install (doesn't install all dependencies):
```javascript
npm.load({ prefix: "./modules" }, function (err) {
    if (err) throw err;
    npm.commands.install(names, function (err, data) {
      if (err) throw err;
      // command succeeded, and data might have some info
      callback();
    });
    //npm.registry.log.on("log", function (msg) { ... })
  });
```
To list (shows missing dependencies despite no intended output to console):
```javascript
npm.load({ prefix: "./modules" }, function (err) {
    if (err) throw err;
    npm.commands.list([], function (err, data) {
      if (err) throw err;
      // command succeeded, and data might have some info
      callback(data);
    });
    //npm.registry.log.on("log", function (msg) { ... })
  });
```
List function showing missing dependencies (I tested with random packages that came to mind):
```
├─┬ serialport@1.6.1
│ ├── UNMET DEPENDENCY async@0.9.0
│ ├── UNMET DEPENDENCY bindings@1.2.1
│ ├── UNMET DEPENDENCY debug@^2.1.1
│ ├── UNMET DEPENDENCY nan@~1.6.2
│ ├─┬ node-pre-gyp@0.5.19 invalid
│ │ ├─┬ mkdirp@0.5.0
│ │ │ └── minimist@0.0.8
│ │ ├─┬ nopt@2.2.1
│ │ │ └── abbrev@1.0.5
│ │ ├─┬ npmlog@0.0.6
│ │ │ └── ansi@0.2.1
│ │ ├─┬ rc@0.4.0
│ │ │ ├── deep-extend@0.2.10
│ │ │ ├── ini@1.1.0
│ │ │ ├── minimist@0.0.10
│ │ │ └── strip-json-comments@0.1.3
│ │ ├─┬ request@2.36.0
│ │ │ ├── aws-sign2@0.5.0
│ │ │ ├── UNMET DEPENDENCY forever-agent@~0.5.0
│ │ │ ├─┬ form-data@0.1.2
│ │ │ │ ├── async@0.2.10
│ │ │ │ └─┬ combined-stream@0.0.4
│ │ │ │   └── delayed-stream@0.0.5
│ │ │ ├─┬ hawk@1.0.0
│ │ │ │ ├── boom@0.4.2
│ │ │ │ ├── cryptiles@0.2.2
│ │ │ │ ├── hoek@0.9.1
│ │ │ │ └── sntp@0.2.4
│ │ │ ├─┬ http-signature@0.10.0
│ │ │ │ ├── UNMET DEPENDENCY asn1@0.1.11
│ │ │ │ ├── UNMET DEPENDENCY assert-plus@0.1.2
│ │ │ │ └── UNMET DEPENDENCY ctype@0.5.2
│ │ │ ├── UNMET DEPENDENCY json-stringify-safe@~5.0.0
│ │ │ ├── mime@1.2.11
│ │ │ ├── UNMET DEPENDENCY node-uuid@~1.4.0
│ │ │ └── UNMET DEPENDENCY qs@~0.6.0
│ │ ├── UNMET DEPENDENCY rimraf@~2.2.5
│ │ ├── UNMET DEPENDENCY semver@~2.3.0
│ │ ├── UNMET DEPENDENCY tar@~0.1.19
│ │ └── UNMET DEPENDENCY tar-pack@~2.0.0
│ ├── UNMET DEPENDENCY optimist@~0.6.1
│ └── UNMET DEPENDENCY sf@0.1.7
└── underscore@1.8.2
```
I plan on adding a feature to my program that will use NPM as its package manager kind of how Grunt and Gulp do. However, my app will not be aimed exclusively as developers, so I want to be able to automate the install of packages.

**Comment by DaAwesomeP** [comment]
Huh the example in the README differs a lot from the example here: https://docs.npmjs.com/api/install

**Comment by iarna** [comment]
@DaAwesomeP You'll notice that the first argument in the documentation is in square brackets– that indicates an optional argument.

If you want to suppress output, pass in `loglevel: 'none'` to `npm.load` you're setting your prefix.

As for your install not seeing all dependencies, it would be really helpful if you could include value of `names`.

**Comment by DaAwesomeP** [comment]
Oh I forgot to substitute that. The first time I ran it, `names` was an array with `serialport` in it. The second time it had only `underscore` in it.

Is it better to use the `where` argument in the install function or the `prefix` in `npm.load`?

Thank you for your help.

**Comment by DaAwesomeP** [comment]
It seems that it is `logLevel` and not `loglevel`. I still get output to the console though.

**Comment by DaAwesomeP** [comment]
Any answers? I really don't want to have to use the CLI version of NPM.

**Comment by DaAwesomeP** [comment]
It think it had to do with version 1.6.2 of serialport always failing to build.
