### ISSUE TITLE
Fails on Linux (Heroku)

### ISSUE THREAD

**Issue by johnkors** [npm/npm#7632]
Not sure if this is a Heroku thing or an npm thing, but trying here anyways :) Is the chmod failing?

-----> Rebuilding any native dependencies
       npm ERR! Error: ENOENT, chmod '/tmp/build_fe96d48b9176f0b5f8511ef2027fbb04/johnkors-links-8222ebff54166620757a30c92cf1f992be94032e/node_modules/googleapis/node_modules/request/node_modules/node-uuid/bin/uuid'
       npm ERR! If you need help, you may report this *entire* log,
       npm ERR! including the npm and node versions, at:
       npm ERR!     <http://github.com/npm/npm/issues>
       
       npm ERR! System Linux 3.13.0-40-generic
       npm ERR! command "/tmp/build_fe96d48b9176f0b5f8511ef2027fbb04/johnkors-links-8222ebff54166620757a30c92cf1f992be94032e/vendor/node/bin/node" "/tmp/build_fe96d48b9176f0b5f8511ef2027fbb04/johnkors-links-8222ebff54166620757a30c92cf1f992be94032e/vendor/node/bin/npm" "rebuild"
       npm ERR! cwd /tmp/build_fe96d48b9176f0b5f8511ef2027fbb04/johnkors-links-8222ebff54166620757a30c92cf1f992be94032e
       npm ERR! node -v v0.10.37
       npm ERR! npm -v 1.4.28
       npm ERR! path /tmp/build_fe96d48b9176f0b5f8511ef2027fbb04/johnkors-links-8222ebff54166620757a30c92cf1f992be94032e/node_modules/googleapis/node_modules/request/node_modules/node-uuid/bin/uuid
       npm ERR! code ENOENT
       npm ERR! errno 34
       npm ERR! 
       npm ERR! Additional logging details can be found in:
       npm ERR!     /tmp/build_fe96d48b9176f0b5f8511ef2027fbb04/johnkors-links-8222ebff54166620757a30c92cf1f992be94032e/npm-debug.log
       npm ERR! not ok code 0
0 info it worked if it ends with ok

Full logs: https://gist.github.com/johnkors/cd8ef4fcb56ebbb9af89

**Comment by smikes** [comment]
This is almost certainly a race condition; there were many present in older versions of npm.  If you have control over your heroku build scripts, add

```
npm install -g npm@latest
```

before any other use of npm, and you should see both better performance and fewer bugs.

**Comment by johnkors** [comment]
I got it working in the end by deleting modules that I had put in my repo being pushed to Heroku, but will definitely do that. Not sure why I'm on such an old version of npm in the first place. Thanks, @smikes !
