### ISSUE TITLE
use tarball when github shorthand includes a ref

### ISSUE THREAD

**Issue by wenzowski** [npm/npm#7633]
In the interest of speeding up installation of packages that haven't made it in to the registry yet, could we resolve github packages that include a ref using the special github tarball (one request) instead of fetching the entire repo over https (multiple requests)?
```
"npm": "npm/newww#10a1ecf9797ef88a5bbd0fe24a2e89c6d6cc631d"
```
would be equivalent to
```
"npm": "https://github.com/npm/newww/archive/10a1ecf9797ef88a5bbd0fe24a2e89c6d6cc631d.tar.gz"
```

and
```
"npm": "npm/newww#v2.1.0"
```
would be equivalent to 
```
"npm": "https://github.com/npm/newww/archive/v2.1.0.tar.gz"
```

---

The only concern I have is when the ref points to a branch it would resolve
```
"npm": "npm/newww#master"
```
as
```
"npm": "https://github.com/npm/newww/archive/master.tar.gz"
```
and not
```
"npm": "https://github.com/npm/newww/archive/10a1ecf9797ef88a5bbd0fe24a2e89c6d6cc631d.tar.gz"
```
so we wouldn't know if/when the contents of that tarball changed.

**Comment by silverwind** [comment]
Tarball dependencies don't get pruned of unnecessary files, so these aren't exactly equivalent.

See #7501. Might be good to solve that one first.

**Comment by othiym23** [comment]
It's maybe not obvious from watching npm work, but the thing that gets installed when you request a GitHub-hosted package isn't the same as what gets cloned via git. As @silverwind says, Git dependencies have to be repacked into tarballs for the cache, so all the npm-specific rules can be applied to the package. Also, once npm figures out that a dependency is hosted on GitHub, it becomes just another remote (ssh or https) Git repository, and having as little GitHub-specific code in npm greatly simplifies maintaining it. Thanks for the suggestion, though! I'm all in favor of finding creative ways to make npm more efficient.
