### ISSUE TITLE
Error on run-script test onvif

### ISSUE THREAD

**Issue by EastL** [npm/npm#7643]
I got error with this command 'npm run-script test'  from test https://github.com/agsh/onvif  :
```
  info it worked if it ends with ok
  verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run-script', 'test' ]
  info using npm@1.4.28
  info using node@v0.10.33
  verbose node symlink /usr/bin/node
  error Error: ENOENT, open '/home/eric/waste/onvif/lib/package.json'
  error If you need help, you may report this *entire* log,
  error including the npm and node versions, at:
  error     <http://github.com/npm/npm/issues>
  error System Linux 3.13.0-44-generic
  error command "/usr/bin/node" "/usr/bin/npm" "run-script" "test"
  error cwd /home/eric/waste/onvif/lib
  error node -v v0.10.33
  error npm -v 1.4.28
  error path /home/eric/waste/onvif/lib/package.json
  error code ENOENT
  error errno 34
  verbose exit [ 34, true ]
```
Can please someone help. Thanks a lot～

**Comment by KenanY** [comment]
@EastL Does `/home/eric/waste/onvif/lib/package.json` exist? I believe you should be running that command from the `/home/eric/waste/onvif` directory. `npm run-script test` has absolutely no idea what you want it to do unless you have a `package.json` in your current working directory; the [docs](https://docs.npmjs.com/cli/run-script) might help :)

**Comment by EastL** [comment]
@KenanY  Oh...thanks!!  The package.json file is in /home/eric/waste/onvif directory and I run command in /home/eric/waste/onvif/lib/ directory... Thank you ~~

**Comment by iarna** [comment]
Closing this as resolved.
