### ISSUE TITLE
How do I contribute to npmjs.com docs?

### ISSUE THREAD

**Issue by amZotti** [npm/npm#7647]
The documentation for [grunt-mocha-chai-sinon] (https://www.npmjs.com/package/grunt-mocha-chai-sinon) is quite poor. I would like to spruce it up but not sure how. Is it possible to do this through Github?

**Comment by KenanY** [comment]
@amZotti Yes! Send a pull request to the [GitHub repo](https://github.com/marcopeg/grunt-mocha-chai-sinon) of the package :)

**Comment by othiym23** [comment]
What @KenanY said. Closing this as resolved, as this is very much not an issue with npm's CLI. ;)

**Comment by amZotti** [comment]
I just figured it out as soon as I inquired. Doh! Thanks guys (;
