### ISSUE TITLE
Stats not available

### ISSUE THREAD

**Issue by tinganho** [npm/npm#7649]
Seems like all stats are not available since mars 9th.

http://npm-stat.com/charts.html?package=typescript

**Comment by KenanY** [comment]
@tinganho 

  1) This is the issue tracker for `npm`, the CLI tool
  2) `npm-stat.com` is not operated by npm, Inc. You should bring up any issues with it to its author.
  3) http://status.npmjs.org/incidents/s2cfqwpyqbr8

**Comment by iarna** [comment]
Closing this as – answered? redirected?
