### ISSUE TITLE
npm adduser creates user

### ISSUE THREAD

**Issue by startswithaj** [npm/npm#7652]
If you run ```npm adduser``` and enter a username with a spelling mistake for instance startswitaj instead of startswithaj and then a password it will create that account without prompting you. You can then therefore go ahead an mistakenly publish under the incorrect username.

npm adduser
username: anythingyouwant
password: anythingyouwant
email: same email as another account

npm publish
- publishes to new account you didnt know you jsut created because of spelling mistake

**Comment by smikes** [comment]
Thanks for the bug report.  

I believe this is in the works to be addressed with registry-2 in that the commands `npm adduser` and `npm login` will actually have distinct behavior; specifically `npm login` will not attempt to create a new user if the named user doesn't exist. (see https://github.com/npm/npm/issues/5068#issuecomment-70610292 )

**Comment by othiym23** [comment]
I think there may be a separate issue here, which @smikes alludes to (which is that `npm adduser` and `npm login` should have logically distinct functionality), but if you take a step back, the title of this issue captures why this isn't a bug: what would you _expect_ a command called `npm adduser` to do, if not create a new user? We do plan at some point in the not too distant future to split apart the two different roles of `npm adduser`, but until then, it's behaving as documented, for better and for worse.
