### ISSUE TITLE
npm ERR! Invalid protocol:

### ISSUE THREAD

**Issue by sabarinathancs** [npm/npm#7653]
```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\node
\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "n"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! Invalid protocol: null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\user\npm-debug.log



Log


0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'n' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 silly cache add args [ 'n', null ]
6 verbose cache add spec n
7 silly cache add parsed spec { raw: 'n',
7 silly cache add   scope: null,
7 silly cache add   name: 'n',
7 silly cache add   rawSpec: '',
7 silly cache add   spec: '*',
7 silly cache add   type: 'range' }
8 verbose addNamed n@*
9 silly addNamed semver.valid null
10 silly addNamed semver.validRange *
11 silly addNameRange { name: 'n', range: '*', hasData: false }
12 silly mapToRegistry name n
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry http://registry.npmjs.org/
15 silly mapToRegistry uri http://registry.npmjs.org/n
16 verbose addNameRange registry:http://registry.npmjs.org/n not in flight; fetching
17 verbose request uri http://registry.npmjs.org/n
18 verbose request no auth needed
19 info attempt registry request try #1 at 4:22:44 PM
20 verbose request id b16d4da98b465c81
21 http request GET http://registry.npmjs.org/n
22 info retry will retry, error on last attempt: Error: Invalid protocol: null
23 info attempt registry request try #2 at 4:22:54 PM
24 http request GET http://registry.npmjs.org/n
25 info retry will retry, error on last attempt: Error: Invalid protocol: null
26 info attempt registry request try #3 at 4:23:54 PM
27 http request GET http://registry.npmjs.org/n
28 verbose stack Error: Invalid protocol: null
28 verbose stack     at Request.init (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:591:31)
28 verbose stack     at new Request (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:264:8)
28 verbose stack     at request (C:\Program Files\nodejs\node_modules\npm\node_modules\request\index.js:50:10)
28 verbose stack     at CachingRegistryClient.makeRequest (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:155:13)
28 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:69:17
28 verbose stack     at RetryOperation._fn (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\attempt.js:15:5)
28 verbose stack     at null._onTimeout (C:\Program Files\nodejs\node_modules\npm\node_modules\retry\lib\retry_operation.js:32:10)
28 verbose stack     at Timer.listOnTimeout (timers.js:110:15)
29 verbose cwd C:\Users\user
30 error Windows_NT 6.1.7601
31 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "n"
32 error node v0.12.0
33 error npm  v2.5.1
34 error Invalid protocol: null
35 error If you need help, you may report this error at:
35 error     <http://github.com/npm/npm/issues>
36 verbose exit [ 1, true ]
```

**Comment by smikes** [comment]
Thanks for the bug report!

It looks like we are creating a `request` object with the protocol set to `null`:

```
28 verbose stack Error: Invalid protocol: null
28 verbose stack at Request.init (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:591:31)
28 verbose stack at new Request (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:264:8)
28 verbose stack at request (C:\Program Files\nodejs\node_modules\npm\node_modules\request\index.js:50:10)
28 verbose stack at CachingRegistryClient.makeRequest (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:155:13)
28 verbose stack at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:69:17
28 verbose stack at RetryOperation._fn (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\attempt.js:15:5)
28 verbose stack at null._onTimeout (C:\Program Files\nodejs\node_modules\npm\node_modules\retry\lib\retry_operation.js:32:10)
```

**Comment by smikes** [comment]
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially involving git dependencies -- since 2.5. Can you try updating your npm installation?

There is a bad interaction between two known bugs — one in `node@>0.11` and `iojs` and the other in `npm@<2.8.2`.  This can cause ECONNRESET and ETIMEDOUT errors.  The full writeup is here: https://github.com/npm/npm/issues/7699  You can fix this problem by updating your `npm` to the latest (see below).

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as abandoned.

**Comment by sabarinathancs** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'cordova',
1 verbose cli   'ionic' ]
2 info using npm@2.10.1
3 info using node@v0.12.4
4 verbose install initial load of C:\Users\user\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\user\AppData\Roaming\npm\package.json
6 silly cache add args [ 'cordova', null ]
7 verbose cache add spec cordova
8 silly cache add args [ 'ionic', null ]
9 verbose cache add spec ionic
10 silly cache add parsed spec { raw: 'cordova',
10 silly cache add   scope: null,
10 silly cache add   name: 'cordova',
10 silly cache add   rawSpec: '',
10 silly cache add   spec: '*',
10 silly cache add   type: 'range' }
11 silly addNamed cordova@*
12 verbose addNamed "*" is a valid semver range for cordova
13 silly addNameRange { name: 'cordova', range: '*', hasData: false }
14 silly mapToRegistry name cordova
15 silly mapToRegistry using default registry
16 silly mapToRegistry registry http://registry.npmjs.org/
17 silly mapToRegistry uri http://registry.npmjs.org/cordova
18 verbose addNameRange registry:http://registry.npmjs.org/cordova not in flight; fetching
19 silly cache add parsed spec { raw: 'ionic',
19 silly cache add   scope: null,
19 silly cache add   name: 'ionic',
19 silly cache add   rawSpec: '',
19 silly cache add   spec: '*',
19 silly cache add   type: 'range' }
20 silly addNamed ionic@*
21 verbose addNamed "*" is a valid semver range for ionic
22 silly addNameRange { name: 'ionic', range: '*', hasData: false }
23 silly mapToRegistry name ionic
24 silly mapToRegistry using default registry
25 silly mapToRegistry registry http://registry.npmjs.org/
26 silly mapToRegistry uri http://registry.npmjs.org/ionic
27 verbose addNameRange registry:http://registry.npmjs.org/ionic not in flight; fetching
28 verbose request uri http://registry.npmjs.org/cordova
29 verbose request no auth needed
30 info attempt registry request try #1 at 11:00:54 AM
31 verbose request id 56d60d4250f39551
32 http request GET http://registry.npmjs.org/cordova
33 info retry will retry, error on last attempt: Error: Invalid protocol: null
34 verbose request uri http://registry.npmjs.org/ionic
35 verbose request no auth needed
36 info attempt registry request try #1 at 11:00:54 AM
37 http request GET http://registry.npmjs.org/ionic
38 info retry will retry, error on last attempt: Error: Invalid protocol: null
39 info attempt registry request try #2 at 11:01:04 AM
40 http request GET http://registry.npmjs.org/cordova
41 info retry will retry, error on last attempt: Error: Invalid protocol: null
42 info attempt registry request try #2 at 11:01:04 AM
43 http request GET http://registry.npmjs.org/ionic
44 info retry will retry, error on last attempt: Error: Invalid protocol: null
45 info attempt registry request try #3 at 11:02:04 AM
46 http request GET http://registry.npmjs.org/cordova
47 info attempt registry request try #3 at 11:02:04 AM
48 http request GET http://registry.npmjs.org/ionic
49 verbose stack Error: Invalid protocol: null
49 verbose stack     at Request.init (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:640:31)
49 verbose stack     at new Request (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:272:8)
49 verbose stack     at request (C:\Program Files\nodejs\node_modules\npm\node_modules\request\index.js:56:10)
49 verbose stack     at CachingRegistryClient.makeRequest (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:147:13)
49 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:65:17
49 verbose stack     at RetryOperation._fn (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\attempt.js:18:5)
49 verbose stack     at null._onTimeout (C:\Program Files\nodejs\node_modules\npm\node_modules\retry\lib\retry_operation.js:32:10)
49 verbose stack     at Timer.listOnTimeout (timers.js:110:15)
50 verbose cwd C:\Users\user
51 error Windows_NT 6.1.7601
52 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova" "ionic"
53 error node v0.12.4
54 error npm  v2.10.1
55 error Invalid protocol: null
56 error If you need help, you may report this error at:
56 error     <https://github.com/npm/npm/issues>
57 verbose exit [ 1, true ]

**Comment by hridayakandel** [comment]
same problem how not to set protocol to not-null

**Comment by kanutsananlive** [comment]
strict-ssl=false
registry=http://registry.npmjs.org/
proxy = http://registry.npmjs.org/
http_proxy = null
https_proxy = null

**Comment by mpekalski** [comment]
I was getting the 
```
npm info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=connect EINVAL 0.0.12.56:80 - Local (0.0.0.0:0)
```
so I edited `˜/.npmrc` setting
```
proxy=http://my_proxy:port
registry=http://registry.npmjs.org/
````

the curcial part was `http://` in proxy without it I was getting 
```
npm info retry will retry, error on last attempt: Error: Invalid protocol: my_proxy
```
