### ISSUE TITLE
Updated and typed npm -g install and now all my apps wouldn't do ionic serve or upload

### ISSUE THREAD

**Issue by EjayJanis** [npm/npm#7655]
I was told by my terminal to update my ionic and i did npm -g install after that all ionic serve or ionic upload commands wouldn't work.

WHAT HAPPENED???????????? I should have not updated

**Comment by KenanY** [comment]
@EjayJanis Impossible to deduce anything from the information provided. Could be an ionic issue, could be a `npm` issue. Can you provide your Node.js version, `npm` version, ionic version, a `npm-debug.log`, an error message?

https://github.com/npm/npm/wiki/Contributing-Guidelines#a-great-bug-report-contains

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
