### ISSUE TITLE
Cannot set CAFILE when old cafile no longer exists

### ISSUE THREAD

**Issue by Feldhacker** [npm/npm#7656]
Attempting to execute:
  npm config set cafile "new.pem" --global
...Fails with:  
  Error: ENOENT, open 'old.pem'
...when "old.pem" no longer exists.  It seems npm is attempting to validate or open the old (currently set) cafile before changing it.  

Expected behavior:  The cafile should be set to the new value regardless of whether or not the current cafile can be validated.

**Comment by smikes** [comment]
Thanks for the bug report!

**Comment by KenanY** [comment]
I'm looking into this.

**Comment by othiym23** [comment]
Fixed in 5d7f704823f5f92ddd7ff3e7dd2b8bcc66c73005 thanks to @KenanY. :balloon:
