### ISSUE TITLE
Shasum check failed

### ISSUE THREAD

**Issue by adriatic** [npm/npm#7657]
Here is the relevant part of the error report (the complete log is at https://github.com/congral/Issue-support-evidence/blob/master/npm-debug03172015.log)

[v8-profiler] Success: "C:\Work\Learning\dashboar-app\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-profiler\build\pro
filer\v5.2.4\node-v14-win32-x64\profiler.node" is installed via remote
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! shasum check failed for C:\Users\nik\AppData\Local\Temp\2\npm-6384-4a619c3d\registry.npmjs.org\socket.io-client\-\socket.io-client-0.9.16.tgz

npm ERR! Expected: 4da7515c5e773041d1b423970415bcc430f35fc6
npm ERR! Actual:   184d255010f9ba2bd0356b3d3c3b23cb25e42e6e
npm ERR! From:     https://registry.npmjs.org/socket.io-client/-/socket.io-client-0.9.16.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Work\Learning\dashboar-app\npm-debug.log

C:\Work\Learning\dashboar-app>

**Comment by adriatic** [comment]
This could be a transient error - but I decided to report it anyway as the stability of npm on windows is of paramount value in my opinion.

**Comment by smikes** [comment]
Thanks for reporting this.  This can sometimes mean a package was corrupted in transit or it can mean there is a problem with the disk.  Can you try cleaning the cache for that package and re-installing?

```
npm cache clean socket.io-client
npm install
```

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.

**Comment by adriatic** [comment]
Thanks for being so diligent Ernie :-)

The problem I reported did never occur again - and I used npm several million times since. Sorry for not stating that before, as I completely forgot about this issue :-(

**Comment by vimniky** [comment]
npm cache clean socket.io-client
npm install

it works for me , thanks!!
