### ISSUE TITLE
npm login with specified port different from saved port failed

### ISSUE THREAD

**Issue by seldo** [npm/npm#7661]
Interesting bug, reproducible in npm@2.7.1. Requires an npm Enterprise or other registry operating on a non-standard port. First, login to the registry:

`npm login --registry=http://some.registry:8080 --scope=@somescope`

Now edit the lines in your .npmrc:

```
@somescope:registry=http://some.registry:1234/
//some.registry:1234/:_authToken=XXXX
```

Attempt to login again:

`npm login --registry=http://some.registry:8080 --scope=@somescope`

The login will time out, because npm will try port 1234 even though you've specified the port in the login.

(This was discovered by an npm Enterprise customer who changed ports post-install and then couldn't login anymore)

**Comment by othiym23** [comment]
Fixed in 3a127235076a1f00bc8befba56c024c6d0e7f477. It wasn't even that traumatic a change. Thanks for filing this, Coach!
