### ISSUE TITLE
Unable to publish censorify

### ISSUE THREAD

**Issue by navkmurthy** [npm/npm#7662]
```
0 info it worked if it ends with ok
1 verbose cli [ 'd:\\development\\nodejs\\node.exe',
1 verbose cli   'd:\\development\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'publish' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec { raw: '.',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: 'd:\\development\\project\\practice\\nodeJsMongoDbAngularJsWebDevelopment\\module\\censorify',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory C:\Users\Navneeth\AppData\Roaming\npm-cache\censorify\0.1.1\package.tgz not in flight; packing
9 verbose tar pack [ 'C:\\Users\\Navneeth\\AppData\\Roaming\\npm-cache\\censorify\\0.1.1\\package.tgz',
9 verbose tar pack   'd:\\development\\project\\practice\\nodeJsMongoDbAngularJsWebDevelopment\\module\\censorify' ]
10 verbose tarball C:\Users\Navneeth\AppData\Roaming\npm-cache\censorify\0.1.1\package.tgz
11 verbose folder d:\development\project\practice\nodeJsMongoDbAngularJsWebDevelopment\module\censorify
12 info prepublish censorify@0.1.1
13 verbose addLocalTarball adding from inside cache C:\Users\Navneeth\AppData\Roaming\npm-cache\censorify\0.1.1\package.tgz
14 silly cache afterAdd censorify@0.1.1
15 verbose afterAdd C:\Users\Navneeth\AppData\Roaming\npm-cache\censorify\0.1.1\package\package.json not in flight; writing
16 verbose afterAdd C:\Users\Navneeth\AppData\Roaming\npm-cache\censorify\0.1.1\package\package.json written
17 silly publish { author: { name: 'Brad Dayley' },
17 silly publish   name: 'censorify',
17 silly publish   version: '0.1.1',
17 silly publish   description: 'Censors words out of text',
17 silly publish   main: 'censortext',
17 silly publish   repository:
17 silly publish    { type: 'git',
17 silly publish      url: 'http://github.com/nodejsmongodbangularjswebdevelopment/module/censorify' },
17 silly publish   keywords: [ 'censor', 'words' ],
17 silly publish   dependencies: {},
17 silly publish   engines: { node: '*' },
17 silly publish   readme: 'ERROR: No README data found!',
17 silly publish   readmeFilename: 'README.md',
17 silly publish   _id: 'censorify@0.1.1',
17 silly publish   scripts: {},
17 silly publish   _shasum: 'ed3334db543ecba7aac57699c9a801fffda40d62',
17 silly publish   _from: '.' }
18 silly mapToRegistry name censorify
19 silly mapToRegistry using default registry
20 silly mapToRegistry registry https://registry.npmjs.org/
21 silly mapToRegistry uri https://registry.npmjs.org/censorify
22 verbose publish registryBase https://registry.npmjs.org/
23 silly publish uploading C:\Users\Navneeth\AppData\Roaming\npm-cache\censorify\0.1.1\package.tgz
24 verbose request uri https://registry.npmjs.org/censorify
25 verbose request sending authorization for write operation
26 info attempt registry request try #1 at 12:14:56 AM
27 verbose request id 9e485348b620edab
28 http request PUT https://registry.npmjs.org/censorify
29 http 403 https://registry.npmjs.org/censorify
30 verbose headers { date: 'Tue, 17 Mar 2015 18:44:57 GMT',
30 verbose headers   server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
30 verbose headers   'content-type': 'application/json',
30 verbose headers   'cache-control': 'max-age=60',
30 verbose headers   'content-length': '1833',
30 verbose headers   'accept-ranges': 'bytes',
30 verbose headers   via: '1.1 varnish',
30 verbose headers   'x-served-by': 'cache-lax1432-LAX',
30 verbose headers   'x-cache': 'MISS',
30 verbose headers   'x-cache-hits': '0',
30 verbose headers   'x-timer': 'S1426617896.891127,VS0,VE332',
30 verbose headers   'keep-alive': 'timeout=10, max=50',
30 verbose headers   connection: 'Keep-Alive' }
31 verbose request invalidating C:\Users\Navneeth\AppData\Roaming\npm-cache\registry.npmjs.org\censorify on PUT
32 error publish Failed PUT 403
33 verbose stack Error: forbidden cannot modify pre-existing version: 0.1.1
33 verbose stack old={"author":{"name":"Brad Dayley"},"name":"censorify","version":"0.1.1","description":"Censors words out of text","main":"censortext","repository":{"type":"git","url":"https://github.com/sisingh/nodebook-ch03-censorify"},"keywords":["censor","words"],"dependencies":{},"engines":{"node":"*"},"bugs":{"url":"https://github.com/sisingh/nodebook-ch03-censorify/issues"},"homepage":"https://github.com/sisingh/nodebook-ch03-censorify","_id":"censorify@0.1.1","dist":{"shasum":"359a8af77858685bf2926c93ec3fb582ae704aa9","tarball":"http://registry.npmjs.org/censorify/-/censorify-0.1.1.tgz"},"_from":".","_npmVersion":"1.3.21","_npmUser":{"name":"sisingh","email":"singh_siddhu@yahoo.com"},"maintainers":[{"name":"sisingh","email":"singh_siddhu@yahoo.com"}]}
33 verbose stack new={"author":{"name":"Brad Dayley"},"name":"censorify","version":"0.1.1","description":"Censors words out of text","main":"censortext","repository":{"type":"git","url":"http://github.com/nodejsmongodbangularjswebdevelopment/module/censorify"},"keywords":["censor","words"],"dependencies":{},"engines":{"node":"*"},"readme":"ERROR: No README data found!","readmeFilename":"README.md","_id":"censorify@0.1.1","scripts":{},"_shasum":"ed3334db543ecba7aac57699c9a801fffda40d62","_from":".","_npmVersion":"2.5.1","_nodeVersion":"0.12.0","_npmUser":{"name":"navkmurthy","email":"navkmurthy@gmail.com"},"maintainers":[{"name":"navkmurthy","email":"navkmurthy@gmail.com"}],"dist":{"shasum":"ed3334db543ecba7aac57699c9a801fffda40d62","tarball":"http://registry.npmjs.org/censorify/-/censorify-0.1.1.tgz"}}: censorify
33 verbose stack     at CachingRegistryClient.<anonymous> (d:\development\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:254:14)
33 verbose stack     at Request._callback (d:\development\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:178:14)
33 verbose stack     at Request.self.callback (d:\development\nodejs\node_modules\npm\node_modules\request\request.js:344:22)
33 verbose stack     at Request.emit (events.js:110:17)
33 verbose stack     at Request.<anonymous> (d:\development\nodejs\node_modules\npm\node_modules\request\request.js:1239:14)
33 verbose stack     at Request.emit (events.js:129:20)
33 verbose stack     at IncomingMessage.<anonymous> (d:\development\nodejs\node_modules\npm\node_modules\request\request.js:1187:12)
33 verbose stack     at IncomingMessage.emit (events.js:129:20)
33 verbose stack     at _stream_readable.js:908:16
33 verbose stack     at process._tickCallback (node.js:355:11)
34 verbose statusCode 403
35 verbose pkgid censorify
36 verbose cwd d:\development\project\practice\nodeJsMongoDbAngularJsWebDevelopment\module\censorify
37 error Windows_NT 6.1.7601
38 error argv "d:\\development\\nodejs\\node.exe" "d:\\development\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "publish"
39 error node v0.12.0
40 error npm  v2.5.1
41 error code E403
42 error forbidden cannot modify pre-existing version: 0.1.1
42 error old={"author":{"name":"Brad Dayley"},"name":"censorify","version":"0.1.1","description":"Censors words out of text","main":"censortext","repository":{"type":"git","url":"https://github.com/sisingh/nodebook-ch03-censorify"},"keywords":["censor","words"],"dependencies":{},"engines":{"node":"*"},"bugs":{"url":"https://github.com/sisingh/nodebook-ch03-censorify/issues"},"homepage":"https://github.com/sisingh/nodebook-ch03-censorify","_id":"censorify@0.1.1","dist":{"shasum":"359a8af77858685bf2926c93ec3fb582ae704aa9","tarball":"http://registry.npmjs.org/censorify/-/censorify-0.1.1.tgz"},"_from":".","_npmVersion":"1.3.21","_npmUser":{"name":"sisingh","email":"singh_siddhu@yahoo.com"},"maintainers":[{"name":"sisingh","email":"singh_siddhu@yahoo.com"}]}
42 error new={"author":{"name":"Brad Dayley"},"name":"censorify","version":"0.1.1","description":"Censors words out of text","main":"censortext","repository":{"type":"git","url":"http://github.com/nodejsmongodbangularjswebdevelopment/module/censorify"},"keywords":["censor","words"],"dependencies":{},"engines":{"node":"*"},"readme":"ERROR: No README data found!","readmeFilename":"README.md","_id":"censorify@0.1.1","scripts":{},"_shasum":"ed3334db543ecba7aac57699c9a801fffda40d62","_from":".","_npmVersion":"2.5.1","_nodeVersion":"0.12.0","_npmUser":{"name":"navkmurthy","email":"navkmurthy@gmail.com"},"maintainers":[{"name":"navkmurthy","email":"navkmurthy@gmail.com"}],"dist":{"shasum":"ed3334db543ecba7aac57699c9a801fffda40d62","tarball":"http://registry.npmjs.org/censorify/-/censorify-0.1.1.tgz"}}: censorify
43 error If you need help, you may report this error at:
43 error     <http://github.com/npm/npm/issues>
44 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@navkmurthy 

```
42 error forbidden cannot modify pre-existing version: 0.1.1
```

It appears as though you are trying to publish a version that has already been published. Have you tried bumping up the version?

**Comment by navkmurthy** [comment]
After changing the version ,The following error is occurred

0 info it worked if it ends with ok
1 verbose cli [ 'd:\\development\\nodejs\\node.exe',
1 verbose cli   'd:\\development\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'publish' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec { raw: '.',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: 'd:\\development\\project\\practice\\nodeJsMongoDbAngularJsWebDevelopment\\module\\censorify',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory C:\Users\Navneeth\AppData\Roaming\npm-cache\censorify\0.1.2\package.tgz not in flight; packing
9 verbose tar pack [ 'C:\\Users\\Navneeth\\AppData\\Roaming\\npm-cache\\censorify\\0.1.2\\package.tgz',
9 verbose tar pack   'd:\\development\\project\\practice\\nodeJsMongoDbAngularJsWebDevelopment\\module\\censorify' ]
10 verbose tarball C:\Users\Navneeth\AppData\Roaming\npm-cache\censorify\0.1.2\package.tgz
11 verbose folder d:\development\project\practice\nodeJsMongoDbAngularJsWebDevelopment\module\censorify
12 info prepublish censorify@0.1.2
13 verbose addLocalTarball adding from inside cache C:\Users\Navneeth\AppData\Roaming\npm-cache\censorify\0.1.2\package.tgz
14 silly cache afterAdd censorify@0.1.2
15 verbose afterAdd C:\Users\Navneeth\AppData\Roaming\npm-cache\censorify\0.1.2\package\package.json not in flight; writing
16 verbose afterAdd C:\Users\Navneeth\AppData\Roaming\npm-cache\censorify\0.1.2\package\package.json written
17 silly publish { author: { name: 'Brad Dayley' },
17 silly publish   name: 'censorify',
17 silly publish   version: '0.1.2',
17 silly publish   description: 'Censors words out of text',
17 silly publish   main: 'censortext',
17 silly publish   repository:
17 silly publish    { type: 'git',
17 silly publish      url: 'http://github.com/nodejsmongodbangularjswebdevelopment/module/censorify' },
17 silly publish   keywords: [ 'censor', 'words' ],
17 silly publish   dependencies: {},
17 silly publish   engines: { node: '*' },
17 silly publish   readme: 'ERROR: No README data found!',
17 silly publish   readmeFilename: 'README.md',
17 silly publish   _id: 'censorify@0.1.2',
17 silly publish   scripts: {},
17 silly publish   _shasum: '353206132ce4826fb154a73a7cacabf9b4499396',
17 silly publish   _from: '.' }
18 silly mapToRegistry name censorify
19 silly mapToRegistry using default registry
20 silly mapToRegistry registry https://registry.npmjs.org/
21 silly mapToRegistry uri https://registry.npmjs.org/censorify
22 verbose publish registryBase https://registry.npmjs.org/
23 silly publish uploading C:\Users\Navneeth\AppData\Roaming\npm-cache\censorify\0.1.2\package.tgz
24 verbose request uri https://registry.npmjs.org/censorify
25 verbose request sending authorization for write operation
26 info attempt registry request try #1 at 9:40:53 PM
27 verbose request id 743feeeac7acc6de
28 http request PUT https://registry.npmjs.org/censorify
29 http 403 https://registry.npmjs.org/censorify
30 verbose headers { date: 'Wed, 18 Mar 2015 16:10:54 GMT',
30 verbose headers   server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
30 verbose headers   'content-type': 'application/json',
30 verbose headers   'cache-control': 'max-age=60',
30 verbose headers   'content-length': '567',
30 verbose headers   'accept-ranges': 'bytes',
30 verbose headers   via: '1.1 varnish',
30 verbose headers   'x-served-by': 'cache-lax1433-LAX',
30 verbose headers   'x-cache': 'MISS',
30 verbose headers   'x-cache-hits': '0',
30 verbose headers   'x-timer': 'S1426695054.140282,VS0,VE155',
30 verbose headers   'keep-alive': 'timeout=10, max=50',
30 verbose headers   connection: 'Keep-Alive' }
31 verbose request invalidating C:\Users\Navneeth\AppData\Roaming\npm-cache\registry.npmjs.org\censorify on PUT
32 error publish Failed PUT 403
33 verbose stack Error: forbidden user: navkmurthy not authorized to modify censorify
33 verbose stack Changed: dist-tags.latest "0.1.1" -> "0.1.2"
33 verbose stack Added: versions.0.1.2
33 verbose stack Changed: readme "This is first node.js file\u000a" -> "ERROR: No README data found!"
33 verbose stack Changed: time.modified "2014-07-18T15:24:31.950Z" -> "2015-03-18T16:10:54.274Z"
33 verbose stack Added: time.0.1.2
33 verbose stack Deleted: homepage
33 verbose stack Changed: repository.url "https://github.com/sisingh/nodebook-ch03-censorify" -> "http://github.com/nodejsmongodbangularjswebdevelopment/module/censorify"
33 verbose stack Deleted: bugs
33 verbose stack Added: _attachments: censorify
33 verbose stack     at CachingRegistryClient.<anonymous> (d:\development\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:254:14)
33 verbose stack     at Request._callback (d:\development\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:178:14)
33 verbose stack     at Request.self.callback (d:\development\nodejs\node_modules\npm\node_modules\request\request.js:344:22)
33 verbose stack     at Request.emit (events.js:110:17)
33 verbose stack     at Request.<anonymous> (d:\development\nodejs\node_modules\npm\node_modules\request\request.js:1239:14)
33 verbose stack     at Request.emit (events.js:129:20)
33 verbose stack     at IncomingMessage.<anonymous> (d:\development\nodejs\node_modules\npm\node_modules\request\request.js:1187:12)
33 verbose stack     at IncomingMessage.emit (events.js:129:20)
33 verbose stack     at _stream_readable.js:908:16
33 verbose stack     at process._tickCallback (node.js:355:11)
34 verbose statusCode 403
35 verbose pkgid censorify
36 verbose cwd d:\development\project\practice\nodeJsMongoDbAngularJsWebDevelopment\module\censorify
37 error Windows_NT 6.1.7601
38 error argv "d:\\development\\nodejs\\node.exe" "d:\\development\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "publish"
39 error node v0.12.0
40 error npm  v2.5.1
41 error code E403
42 error forbidden user: navkmurthy not authorized to modify censorify
42 error Changed: dist-tags.latest "0.1.1" -> "0.1.2"
42 error Added: versions.0.1.2
42 error Changed: readme "This is first node.js file\u000a" -> "ERROR: No README data found!"
42 error Changed: time.modified "2014-07-18T15:24:31.950Z" -> "2015-03-18T16:10:54.274Z"
42 error Added: time.0.1.2
42 error Deleted: homepage
42 error Changed: repository.url "https://github.com/sisingh/nodebook-ch03-censorify" -> "http://github.com/nodejsmongodbangularjswebdevelopment/module/censorify"
42 error Deleted: bugs
42 error Added: _attachments: censorify
43 error If you need help, you may report this error at:
43 error     <http://github.com/npm/npm/issues>
44 verbose exit [ 1, true ]

**Comment by othiym23** [comment]
```
33 verbose stack Error: forbidden user: navkmurthy not authorized to modify censorify
```

You can't publish new versions of censorify because you're not one of the owners of the package. Either send the current maintainers a pull request with your desired changes, or request that they add you as an owner of the package so you can publish them yourself.

**Comment by tssxs** [comment]
Becuse the pagename "censorify" has publish
