### ISSUE TITLE
npm WARN package.json nan@1.7.0 No readme data.

### ISSUE THREAD

**Issue by mikefreak** [npm/npm#7663]
Hey guys, I try since some hours to install the nodejs serial port package for my graduation project at higher technical school but have no idea how to fix my issue. I need it fast, and would be very glad to find help here.

The problem comes up when I do # npm install serialport (or serialport2)
I work on a Raspbian on my raspi and tried to install phyton and many other ideas i found on the net. I basicly installed the NodeJS and the serialport package like voodoo described in his article.
So when i say install serialport the whole Error-rain starts with the warning i mentioned in the title - npm WARN package.json nan@1.7.0 No readme data.

The whole code looks like this:

```
root@raspberrypi:/home/pi/nodeSerialExample# npm install serialport
npm http GET https://registry.npmjs.org/serialport
npm http 304 https://registry.npmjs.org/serialport
npm http GET https://registry.npmjs.org/nan/1.7.0
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/sf/0.1.7
npm http GET https://registry.npmjs.org/async/0.9.0
npm http GET https://registry.npmjs.org/bindings/1.2.1
npm http GET https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/optimist
npm http 304 https://registry.npmjs.org/nan/1.7.0
npm http 304 https://registry.npmjs.org/bindings/1.2.1
npm http 304 https://registry.npmjs.org/sf/0.1.7
npm http 200 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/async/0.9.0
npm WARN package.json nan@1.7.0 No readme data.
npm ERR! Error: No compatible version found: debug@'^2.1.1'
npm ERR! Valid install targets:
npm ERR! ["0.0.1","0.1.0","0.2.0","0.3.0","0.4.0","0.4.1","0.5.0","0.6.0","0.7.0","0.7.1","0.7.2","0.7.3","0.7.4","0.8.0","0.8.1","1.0.0","1.0.1","1.0.2","1.0.3","1.0.4","2.0.0","2.1.0","2.1.1","2.1.2","2.1.3"]
npm ERR!     at installTargetsError (/opt/node/lib/node_modules/npm/lib/cache.js:719:10)
npm ERR!     at /opt/node/lib/node_modules/npm/lib/cache.js:641:10
npm ERR!     at saved (/opt/node/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.18.5+
npm ERR! command "/opt/node/bin/node" "/opt/node/bin/npm" "install" "serialport"
npm ERR! cwd /home/pi/nodeSerialExample
npm ERR! node -v v0.10.12
npm ERR! npm -v 1.2.32
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/nodeSerialExample/npm-debug.log
npm ERR! not ok code 0
```

Would be an extraordinary help to find the issue here. Thanks a lot. Mike

**Comment by KenanY** [comment]
@mikefreak The main issue is there error:

```
npm ERR! Error: No compatible version found: debug@'^2.1.1'
```

Your version of `npm` is **several years old**, and doesn't support the `^` semver operator you see in the error above. The solution is to simply [upgrade](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-nix-osx-linux-etc).

You can usually ignore `WARN`s with no consequence.

**Comment by mikefreak** [comment]
This can't be, I upgraded 10 mins before .. Will check it again, thanks atm

**Comment by mikefreak** [comment]
I thought u mean the PI upgrade ^^

I've done the upgrade now and have even there failures ..

root@raspberrypi:/home/pi# npm install -g npm@latest
npm http GET https://registry.npmjs.org/npm
npm http 200 https://registry.npmjs.org/npm
npm http GET https://registry.npmjs.org/npm/-/npm-2.7.1.tgz
npm http 200 https://registry.npmjs.org/npm/-/npm-2.7.1.tgz
/opt/node/bin/npm -> /opt/node/lib/node_modules/npm/bin/npm-cli.js
npm WARN package.json wcwidth@1.0.0 No repository field.
npm WARN package.json asap@1.0.0 No repository field.
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/async-some requires dezalgo@'^1.0.0' but will load
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/dezalgo,
npm WARN unmet dependency which is version 1.0.1
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/fs-vacuum requires graceful-fs@'^3.0.2' but will load
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/graceful-fs,
npm WARN unmet dependency which is version 3.0.5
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/fs-vacuum requires path-is-inside@'^1.0.1' but will load
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/path-is-inside,
npm WARN unmet dependency which is version 1.0.1
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/fs-vacuum requires rimraf@'^2.2.8' but will load
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/rimraf,
npm WARN unmet dependency which is version 2.3.1
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/fs-write-stream-atomic requires graceful-fs@'^3.0.2' but will load
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/graceful-fs,
npm WARN unmet dependency which is version 3.0.5
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/glob requires inflight@'^1.0.4' but will load
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/inflight,
npm WARN unmet dependency which is version 1.0.4
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/glob requires minimatch@'^2.0.1' but will load
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/minimatch,
npm WARN unmet dependency which is version 2.0.1
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/glob requires once@'^1.3.0' but will load
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/once,
npm WARN unmet dependency which is version 1.3.1
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/inflight requires once@'^1.3.0' but will load
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/once,
npm WARN unmet dependency which is version 1.3.1
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/init-package-json requires glob@'^4.0.2' but will load
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/glob,
npm WARN unmet dependency which is version 4.4.2
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/node-gyp requires fstream@'^1.0.0' but will load
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/fstream,
npm WARN unmet dependency which is version 1.0.4
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/node-gyp requires mkdirp@'^0.5.0' but will load
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/mkdirp,
npm WARN unmet dependency which is version 0.5.0
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/node-gyp requires tar@'^1.0.0' but will load
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/tar,
npm WARN unmet dependency which is version 1.0.3
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/normalize-package-data requires github-url-from-git@'^1.3.0' but will load
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/github-url-from-git,
npm WARN unmet dependency which is version 1.4.0
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/normalize-package-data requires github-url-from-username-repo@'^1.0.0' but will load
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/github-url-from-username-repo,
npm WARN unmet dependency which is version 1.0.2
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/npm-registry-client requires graceful-fs@'^3.0.0' but will load
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/graceful-fs,
npm WARN unmet dependency which is version 3.0.5
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/npm-registry-client requires mkdirp@'^0.5.0' but will load
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/mkdirp,
npm WARN unmet dependency which is version 0.5.0
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/npm-registry-client requires once@'^1.3.0' but will load
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/once,
npm WARN unmet dependency which is version 1.3.1
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/npm-registry-client requires request@'^2.47.0' but will load
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/request,
npm WARN unmet dependency which is version 2.53.0
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/npm-registry-client requires retry@'^0.6.1' but will load
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/retry,
npm WARN unmet dependency which is version 0.6.1
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/npm-registry-client requires slide@'^1.1.3' but will load
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/slide,
npm WARN unmet dependency which is version 1.1.6
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/read-package-json requires github-url-from-git@'^1.3.0' but will load
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/github-url-from-git,
npm WARN unmet dependency which is version 1.4.0
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/read-package-json requires glob@'^4.0.2' but will load
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/glob,
npm WARN unmet dependency which is version 4.4.2
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/read-package-json requires normalize-package-data@'^1.0.0' but will load
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/normalize-package-data,
npm WARN unmet dependency which is version 1.0.3
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/realize-package-specifier requires dezalgo@'^1.0.1' but will load
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/dezalgo,
npm WARN unmet dependency which is version 1.0.1
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/realize-package-specifier requires npm-package-arg@'^2.1.3' but will load
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/npm-package-arg,
npm WARN unmet dependency which is version 2.1.3
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/rimraf requires glob@'^4.4.2' but will load
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/glob,
npm WARN unmet dependency which is version 4.4.2
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/tar requires fstream@'^1.0.2' but will load
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/fstream,
npm WARN unmet dependency which is version 1.0.4
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/write-file-atomic requires graceful-fs@'^3.0.2' but will load
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/graceful-fs,
npm WARN unmet dependency which is version 3.0.5
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/write-file-atomic requires slide@'^1.1.5' but will load
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/slide,
npm WARN unmet dependency which is version 1.1.6
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore requires fstream@'^1.0.0' but will load
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/fstream,
npm WARN unmet dependency which is version 1.0.4
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore requires minimatch@'^2.0.1' but will load
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/minimatch,
npm WARN unmet dependency which is version 2.0.1
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/read-installed/node_modules/readdir-scoped-modules requires debuglog@'^1.0.1' but will load
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/read-installed/node_modules/debuglog,
npm WARN unmet dependency which is version 1.0.1
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/read-installed/node_modules/readdir-scoped-modules requires dezalgo@'^1.0.0' but will load
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/dezalgo,
npm WARN unmet dependency which is version 1.0.1
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/read-installed/node_modules/readdir-scoped-modules requires graceful-fs@'^3.0.4' but will load
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/graceful-fs,
npm WARN unmet dependency which is version 3.0.5
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/read-installed/node_modules/readdir-scoped-modules requires once@'^1.3.0' but will load
npm WARN unmet dependency /opt/node/lib/node_modules/npm/node_modules/once,
npm WARN unmet dependency which is version 1.3.1
npm@2.7.1 /opt/node/lib/node_modules/npm

**Comment by KenanY** [comment]
@mikefreak I don't see any failures in the output you've posted. All I see are `WARN`s, which again can usually be safely ignored. I think you might've ran `npm update -g` sometime in the past so now a bunch of your global packages don't have the exact versions of their dependencies.

**Comment by mikefreak** [comment]
@KenanY I shall have done it right now, but everything i do now with npm gives me the following error:


node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
TypeError: Cannot call method 'apply' of undefined
    at EventEmitter.<anonymous> (/opt/node/lib/node_modules/npm/node_modules/npmlog/log.js:63:25)
    at EventEmitter.log (native)
    at EventEmitter.<anonymous> (/opt/node/lib/node_modules/npm/node_modules/npmlog/log.js:137:21)
    at EventEmitter.info (native)
    at /opt/node/lib/node_modules/npm/bin/npm-cli.js:20:5
    at Object.<anonymous> (/opt/node/lib/node_modules/npm/bin/npm-cli.js:75:2)
    at Module._compile (module.js:411:26)
    at Object..js (module.js:417:10)
    at Module.load (module.js:343:31)
    at Function._load (module.js:302:12)

**Comment by KenanY** [comment]
@mikefreak Yikes, everything looks broken to me :( maybe a [reinstall](https://github.com/npm/npm/wiki/Troubleshooting#if-your-npm-is-broken) is in order

**Comment by mikefreak** [comment]
For those who struggle at the same problem, got the solution.

The error means:"TypeError: Cannot call method 'apply' of undefined"
that means npm wants to apply something where he gets undefined as a result.
This results because of searching in the wrong place. When i did node -v i misteriously got "v0.6.19" even though i never installed this version. what ever. 
Solution is completely uninstall nodejs with all of its components (for an instruction look here http://stackoverflow.com/questions/11177954/how-do-i-completely-uninstall-node-js-and-reinstall-from-beginning-mac-os-x) then install a new up to date version of nodejs and most important, set the paths correctly after installing the new nodejs, otherwise the system will try to take v0.6.19 every time.
You set the paths correctly by: PATH=$NODE_JS_HOME/bin/:$PATH (provided your newly installed path is "$NODE_JS_HOME")

hope that i could help some1, thanks @KenanY for the support
Mike

**Comment by iarna** [comment]
Closing this as resolved.
