### ISSUE TITLE
dist-tag failing against npm enterprise

### ISSUE THREAD

**Issue by jasonpincin** [npm/npm#7665]
Attempting to execute dist-tag against a private NPM registry is failing with the message:

```
npm ERR! 404 Package not found on remote : -/package/PACKAGE-NAME/dist-tags
```

When setting log level to `silly` I see two different URI's:

```
npm sill mapToRegistry uri https://npme.something.com/PACKAGE-NAME@2.4.0
npm verb request uri https://npme.something.com/-/package/PACKAGE-NAME@2.4.0/dist-tags
```

This is version `2.7.1`.

**Comment by othiym23** [comment]
It looks like you're running an old version of npmE that's lacking the newer `dist-tags` endpoint that npm relies upon to set dist-tags. @bcoe, what version of npmE does one need to be running to get that feature?

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
