### ISSUE TITLE
npm install webdriver.io

### ISSUE THREAD

**Issue by pkittali** [npm/npm#7666]
hi,

I am getting this error whenever trying to run install program. 
```
C:\Users\pkittali>npm install webdriver.io
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\pkittali\\NodeJS\\\\node.exe" "C:\\Users\\pkittali\\No
deJS\\node_modules\\npm\\bin\\npm-cli.js" "install" "webdriver.io"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code SELF_SIGNED_CERT_IN_CHAIN

npm ERR! self signed certificate in certificate chain
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\pkittali\npm-debug.log

C:\Users\pkittali>

This is the debug log
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Users\\pkittali\\NodeJS\\\\node.exe',
1 verbose cli   'C:\\Users\\pkittali\\NodeJS\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'webdriver.io' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose node symlink C:\Users\pkittali\NodeJS\\node.exe
5 verbose config Skipping project config: C:\Users\pkittali/.npmrc. (matches userconfig)
6 silly cache add args [ 'webdriver.io', null ]
7 verbose cache add spec webdriver.io
8 silly cache add parsed spec { raw: 'webdriver.io',
8 silly cache add   scope: null,
8 silly cache add   name: 'webdriver.io',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 verbose addNamed webdriver.io@*
10 silly addNamed semver.valid null
11 silly addNamed semver.validRange *
12 silly addNameRange { name: 'webdriver.io', range: '*', hasData: false }
13 silly mapToRegistry name webdriver.io
14 silly mapToRegistry using default registry
15 silly mapToRegistry registry https://registry.npmjs.org/
16 silly mapToRegistry uri https://registry.npmjs.org/webdriver.io
17 verbose addNameRange registry:https://registry.npmjs.org/webdriver.io not in flight; fetching
18 verbose request uri https://registry.npmjs.org/webdriver.io
19 verbose request no auth needed
20 info attempt registry request try #1 at 11:29:29 AM
21 verbose request id cef9bf839a2131c9
22 http request GET https://registry.npmjs.org/webdriver.io
23 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
24 info attempt registry request try #2 at 11:29:40 AM
25 http request GET https://registry.npmjs.org/webdriver.io
26 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
27 info attempt registry request try #3 at 11:30:41 AM
28 http request GET https://registry.npmjs.org/webdriver.io
29 verbose stack Error: self signed certificate in certificate chain
29 verbose stack     at Error (native)
29 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:927:36)
29 verbose stack     at TLSSocket.emit (events.js:104:17)
29 verbose stack     at TLSSocket._finishInit (_tls_wrap.js:458:8)
30 verbose cwd C:\Users\pkittali
31 error Windows_NT 6.1.7601
32 error argv "C:\\Users\\pkittali\\NodeJS\\\\node.exe" "C:\\Users\\pkittali\\NodeJS\\node_modules\\npm\\bin\\npm-cli.js" "install" "webdriver.io"
33 error node v0.12.0
34 error npm  v2.5.1
35 error code SELF_SIGNED_CERT_IN_CHAIN
36 error self signed certificate in certificate chain
37 error If you need help, you may report this error at:
37 error     <http://github.com/npm/npm/issues>
38 verbose exit [ 1, true ]
```

**Comment by smikes** [comment]
Are you using a firewall or https-intercepting proxy?

**Comment by pkittali** [comment]
hi Sam,

I am behind corporate proxy, ran the following commands to set the proxy:
npm config set proxy http://xxxxx:80
npm config set https-proxy http://xxxxx:443

but still I see the following error in log file:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Users\\pkittali\\NodeJS\\\\node.exe',
1 verbose cli   'C:\\Users\\pkittali\\NodeJS\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'nightwatch' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose node symlink C:\Users\pkittali\NodeJS\\node.exe
5 silly cache add args [ 'nightwatch', null ]
6 verbose cache add spec nightwatch
7 silly cache add parsed spec { raw: 'nightwatch',
7 silly cache add   scope: null,
7 silly cache add   name: 'nightwatch',
7 silly cache add   rawSpec: '',
7 silly cache add   spec: '*',
7 silly cache add   type: 'range' }
8 verbose addNamed nightwatch@*
9 silly addNamed semver.valid null
10 silly addNamed semver.validRange *
11 silly addNameRange { name: 'nightwatch', range: '*', hasData: false }
12 silly mapToRegistry name nightwatch
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/nightwatch
16 verbose addNameRange registry:https://registry.npmjs.org/nightwatch not in flight; fetching
17 verbose request uri https://registry.npmjs.org/nightwatch
18 verbose request no auth needed
19 info attempt registry request try #1 at 11:06:29 AM
20 verbose request id 62c4105d9fac8648
21 http request GET https://registry.npmjs.org/nightwatch
22 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
23 info attempt registry request try #2 at 11:06:40 AM
24 http request GET https://registry.npmjs.org/nightwatch
25 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
26 info attempt registry request try #3 at 11:07:41 AM
27 http request GET https://registry.npmjs.org/nightwatch
28 verbose stack Error: self signed certificate in certificate chain
28 verbose stack     at Error (native)
28 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:927:36)
28 verbose stack     at TLSSocket.emit (events.js:104:17)
28 verbose stack     at TLSSocket._finishInit (_tls_wrap.js:458:8)
29 verbose cwd C:\Users\pkittali\NodeJS
30 error Windows_NT 6.1.7601
31 error argv "C:\\Users\\pkittali\\NodeJS\\\\node.exe" "C:\\Users\\pkittali\\NodeJS\\node_modules\\npm\\bin\\npm-cli.js" "install" "nightwatch"
32 error node v0.12.0
33 error npm  v2.5.1
34 error code SELF_SIGNED_CERT_IN_CHAIN
35 error self signed certificate in certificate chain
36 error If you need help, you may report this error at:
36 error     <http://github.com/npm/npm/issues>
37 verbose exit [ 1, true ]

Then tried setting the ssl config using the command:
npm config set strict-ssl false

but still ran into same error.

**Comment by smikes** [comment]
There are a few more things you can try (see https://github.com/npm/npm/wiki/Troubleshooting#ssl-error )

This disables use of `npm`'s built-in ca list, and causes you to use the system list:
```
npm config set ca=""
```

This tells `npm` to use the unencrypted, unauthenticated registry endpoint:
```
npm config set registry=http://registry.npmjs.org
```

However that second one leaves you open to a variety of attacks, so we don't recommend it.

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
