### ISSUE TITLE
only npm -v can be used,other commands cannot be used. 

### ISSUE THREAD

**Issue by limerickgds** [npm/npm#7667]
how to handle this problem

**Comment by KenanY** [comment]
@limerickgds Could you perhaps provide an error log? Maybe [reinstalling](https://github.com/npm/npm/wiki/Troubleshooting#if-your-npm-is-broken) will help?

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
