### ISSUE TITLE
npm-parameter for HTTP-authentication

### ISSUE THREAD

**Issue by Z3roCoder** [npm/npm#7668]
Hello there. I have a little question/request here.

So for installing a package you need to entr the package + version into the package.json.

One entry of mine would look like this:
    "packagexxx": "https://somelink.com/someLinkToTarBall.tgz"

now the problem is that the server the package is on needs http-authentification like "https://username:password@someling.com..." - And I simply cannot write this out of safety reasons into my package.json. Is there actually any way to provide credentials so that I wont get a 401 Not Authorized?

**Comment by othiym23** [comment]
If you want to install from a remote tarball, you'll either need to make that tarball publicly accessible, embed the credentials in the URL (which is, as you noted, insecure), or perhaps make the package you want to install a private Git repo, either on GitHub or elsewhere, where you can use ssh keys or GitHub auth tokens to control access to it.

There isn't a way to store credentials for authed HTTP endpoints separately from the URL, and I can't really see the team adding anything like that, as it's a pretty niche use case and most of our attention is focused on making the CLI work better with npm registries.
