### ISSUE TITLE
npm not working after I installed nvm n and now I keep getting “dyld: bad external relocation length”

### ISSUE THREAD

**Issue by anwaukoni** [npm/npm#7670]
I installed nvm, n, using sudo and decided to test it out by downloading several versions of node on my system. When I tried to switch between the node versions I kept getting "Permissions denied." So I decided to sudo the command for switching between versions too. That's when all hell broke loose. I keep getting

         dyld:bad external relocation length

I've tried to reboot my terminal with some hope that it would magically fix itself out. Alas, I was wrong.Thanks in Advance.

Update 1: I've tried to use npm to install yo and it gives me the same "dyld" prompt, along with the following:

          Trace/BPT trap: 5

Essentially I can't use npm anymore.

**Comment by othiym23** [comment]
You appear to have broken your Node installation – that error message is not something that comes from npm (in fact, those are both messages from OS X). You should uninstall everything and start over again. In addition, nvm and n are two different ways of solving the same problem – they're both Node version managers. Maybe try only using one of them when you reinstall?

**Comment by anwaukoni** [comment]
Yes, you are right. Uninstalled and reinstalled using nvm and now all is working right. Thanks

**Comment by fairyeye** [comment]
I also had broken my Node installation by using n to upgrade. Thanks for your answer. I think i can get it.

**Comment by muzi131313** [comment]
`sudo n latest`, this was the update code by n.
