### ISSUE TITLE
npm explore reports "weird error 1" if subcommand exits w/ code != 0

### ISSUE THREAD

**Issue by smikes** [npm/npm#7671]
Repro case:

```
$ mkdir test && cd test
$ npm install nan
$ npm explore nan false
npm ERR! weird error 1
```

Similarly `npm explore foo find` on eg OSX where find requires an argument yields the slightly confusing:

```
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
npm ERR! weird error 1
```

**Comment by othiym23** [comment]
What's the action item here? Clarify the message printed by npm? Documentation? ?¿?

**Comment by smikes** [comment]
Just a reminder to myself to flesh out the issue when i get back from vacation :-). Clarify is probably right.

**Comment by smikes** [comment]
Looks like this is happening when `explore` is calling a callback with a non-null, but non-Error first argument.  The `ELIFECYCLE` error is probably not appropriate.  I will write a PR that creates a new error category, maybe.
