### ISSUE TITLE
Error when installing NodeJS package

### ISSUE THREAD

**Issue by anthonycluse** [npm/npm#7680]
I get an issue when installing a package on my linux server : 

    npm ERR! Error: getaddrinfo ESRCH
    npm ERR!     at errnoException (dns.js:37:11)
    npm ERR!     at Object.onanswer [as oncomplete] (dns.js:124:16)
    npm ERR! If you need help, you may report this *entire* log,
    npm ERR! including the npm and node versions, at:
    npm ERR!     <http://github.com/npm/npm/issues>

    npm ERR! System Linux 2.6.32-504.8.1.el6.x86_64
    npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "phantomjs"
    npm ERR! cwd /appli/GestionDettes
    npm ERR! node -v v0.10.36
    npm ERR! npm -v 1.4.28
    npm ERR! syscall getaddrinfo
    npm ERR! code ESRCH
    npm ERR! errno ESRCH
    npm ERR!
    npm ERR! Additional logging details can be found in:
    npm ERR!     /appli/GestionDettes/npm-debug.log
    npm ERR! not ok code 0

**Comment by KenanY** [comment]
@tonymx227 This looks like an issue with your internet connection. Are you behind a proxy by any chance? Could you run the command with the `-ddd` flag and upload the resulting `npm-debug.log` as a [gist](https://gist.github.com)?

**Comment by tonymx227** [comment]
I found the issue, It was a problem with my proxy.

**Comment by ehsalazar** [comment]
Good to hear.  I'll close this for now as we’re trying to clean up some old issues. We’ll be happy to reopen if necessary.

**Comment by aman-IoT** [comment]
I am facing alike issue, 
If it is a proxy problem then how to solve it
https://github.com/npm/npm/issues/9547

**Comment by aman-IoT** [comment]
What proxy error did you find? Please explain.
