### ISSUE TITLE
ERROR when install npm appnium

### ISSUE THREAD

**Issue by gxll** [npm/npm#7687]
C:\Users\i\AppData\Roaming\npm\node_modules\appium\node_modules\ws>node- "C:\Pro
gram Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp
\bin\node-gyp.js" rebuild
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {
"node":"0.12.0","npm":"2.5.1"})
/

> ws@0.4.31 install C:\Users\i\AppData\Roaming\npm\node_modules\appium\node_modu
les\socket.io\node_modules\engine.io\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

-
C:\Users\i\AppData\Roaming\npm\node_modules\appium\node_modules\socket.io\node_m
odules\engine.io\node_modules\ws>node "C:\Program Files\nodejs\node_modules\npm\
bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.12.0"
,"npm":"2.5.1"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.12.0",
"npm":"2.5.1"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.12.0",
"npm":"2.5.1"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.1
2.0","npm":"2.5.1"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.12.0",
"npm":"2.5.1"})
npm ERR! Windows_NT 6.1.7600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "--registry" "http://registry.cnpmjs.org"
"install" "-g" "appium"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! Cannot read property 'emit' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
\

> ws@0.4.31 install C:\Users\i\AppData\Roaming\npm\node_modules\appium\node_modu
les\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_m
odules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

C:\Users\i\AppData\Roaming\npm\node_modules\appium\node_modules\socket.io\node_m
odules\socket.io-client\node_modules\engine.io-client\node_modules\ws>node "C:\P
rogram Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-g
yp\bin\node-gyp.js" rebuild
npm ERR! Windows_NT 6.1.7600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "--registry" "http://registry.cnpmjs.org"
"install" "-g" "appium"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! shasum check failed for C:\Users\i\AppData\Local\Temp\npm-8484-e326cace
\registry.cnpmjs.org\traceur\download\traceur-0.0.74.tgz
npm ERR! Expected: 39de7450260d84df5aaa93b69c1adb4b65a631bf
npm ERR! Actual:   bd4a123284d4ae9cba525577494ecb744ba3c867
npm ERR! From:     http://registry.cnpmjs.org/traceur/download/traceur-0.0.74.tg
z
npm ERR!

**Comment by smikes** [comment]
It looks like there are a few problems here.  Let's approach them one by one.

First, it looks like you have some older packages and dependencies (did you used to have `node@0.8` installed?).  Let's clean those up, and update `npm` at the same time:

```
> cd C:\Program Files\nodejs
> npm install npm@latest
> npm update --depth=0 -g
```

Next, it looks like there's a bad copy of `traceur` in your cache:
```
> npm cache clean traceur
```

now you can try installing appium

```
npm install -g appium
```

If this doesn't help, please attach your full `npm-debug.log` as a gist <https://gist.github.com>

**Comment by gxll** [comment]
thank you very much，it fixed my problem
