### ISSUE TITLE
npm install failed 

### ISSUE THREAD

**Issue by UltimateFighter** [npm/npm#7688]
under Windows 8 the comand "npm install" ever failed because the path npm is searchinfg for ist ever "c:\".

The PATH enviroment varibale (C:\Users[#myusername]\AppData\Roaming\npm) seems to ignore.
# Error:

```
module.js:338
    throw err;
          ^
Error: Cannot find module 'c:\node_modules\protractor\bin\webdriver-manager'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.7.3
npm ERR! code ELIFECYCLE
npm ERR! votinggui@0.0.0 install: `node node_modules/protractor/bin/webdriver-manager update`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the votinggui@0.0.0 install script 'node node_modules/protractor/bin/webdriver-manager update'.
npm ERR! This is most likely a problem with the votinggui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/protractor/bin/webdriver-manager update
npm ERR! You can get their info via:
npm ERR!     npm owner ls votinggui
npm ERR! There is likely additional logging output above.
```

**Comment by smikes** [comment]
It looks like your package `votinggui` has an `install` script that assumes that its dependencies are already in place.  Can you try moving that to a `postinstall` script?

**Comment by UltimateFighter** [comment]
hallo,

here ist the complete npm-debug.log file

------------------------- Strat -----------------------------
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose install where, deps [ 'C:\\Data\\projects\\temp\\myproject',
5 verbose install   [ 'bower',
5 verbose install     'grunt',
5 verbose install     'grunt-autoprefixer',
5 verbose install     'grunt-cli',
5 verbose install     'grunt-concurrent',
5 verbose install     'grunt-connect-proxy',
5 verbose install     'grunt-contrib-clean',
5 verbose install     'grunt-contrib-concat',
5 verbose install     'grunt-contrib-connect',
5 verbose install     'grunt-contrib-copy',
5 verbose install     'grunt-contrib-cssmin',
5 verbose install     'grunt-contrib-htmlmin',
5 verbose install     'grunt-contrib-imagemin',
5 verbose install     'grunt-contrib-jshint',
5 verbose install     'grunt-contrib-uglify',
5 verbose install     'grunt-contrib-watch',
5 verbose install     'grunt-filerev',
5 verbose install     'grunt-google-cdn',
5 verbose install     'grunt-karma',
5 verbose install     'grunt-newer',
5 verbose install     'grunt-ng-annotate',
5 verbose install     'grunt-protractor-runner',
5 verbose install     'grunt-protractor-webdriver',
5 verbose install     'grunt-svgmin',
5 verbose install     'grunt-usemin',
5 verbose install     'grunt-wiredep',
5 verbose install     'jasmine-core',
5 verbose install     'jshint-stylish',
5 verbose install     'karma',
5 verbose install     'karma-coverage',
5 verbose install     'karma-jasmine',
5 verbose install     'karma-junit-reporter',
5 verbose install     'karma-firefox-launcher',
5 verbose install     'load-grunt-tasks',
5 verbose install     'protractor',
5 verbose install     'time-grunt',
5 verbose install     'request',
5 verbose install     'request-promise' ] ]
6 verbose install where, peers [ 'C:\\Data\\projects\\temp\\myproject', [] ]
7 info preinstall myproject@0.0.0
8 warn package.json karma-firefox-launcher@0.1.4 No README data
9 verbose already installed skipping grunt-contrib-concat@^0.5.0 C:\Data\projects\temp\myproject
10 verbose already installed skipping grunt-contrib-connect@^0.9.0 C:\Data\projects\temp\myproject
11 verbose already installed skipping grunt-contrib-copy@^0.7.0 C:\Data\projects\temp\myproject
12 verbose already installed skipping grunt-contrib-cssmin@^0.12.0 C:\Data\projects\temp\myproject
13 verbose already installed skipping grunt-contrib-htmlmin@^0.4.0 C:\Data\projects\temp\myproject
14 verbose already installed skipping grunt-contrib-imagemin@^0.9.2 C:\Data\projects\temp\myproject
15 verbose already installed skipping grunt-contrib-jshint@^0.11.0 C:\Data\projects\temp\myproject
16 verbose already installed skipping grunt-contrib-uglify@^0.7.0 C:\Data\projects\temp\myproject
17 verbose already installed skipping grunt-contrib-watch@^0.6.1 C:\Data\projects\temp\myproject
18 verbose already installed skipping grunt-filerev@^2.1.2 C:\Data\projects\temp\myproject
19 verbose already installed skipping grunt-google-cdn@^0.4.3 C:\Data\projects\temp\myproject
20 verbose already installed skipping grunt-karma@^0.10.1 C:\Data\projects\temp\myproject
21 verbose already installed skipping grunt-newer@^1.1.0 C:\Data\projects\temp\myproject
22 verbose already installed skipping grunt-ng-annotate@^0.9.2 C:\Data\projects\temp\myproject
23 verbose already installed skipping grunt-protractor-runner@^1.2.1 C:\Data\projects\temp\myproject
24 verbose already installed skipping grunt-protractor-webdriver@^0.2.0 C:\Data\projects\temp\myproject
25 verbose already installed skipping grunt-svgmin@^2.0.0 C:\Data\projects\temp\myproject
26 verbose already installed skipping grunt-usemin@^3.0.0 C:\Data\projects\temp\myproject
27 verbose already installed skipping grunt-wiredep@^2.0.0 C:\Data\projects\temp\myproject
28 verbose already installed skipping jasmine-core@^2.2.0 C:\Data\projects\temp\myproject
29 verbose already installed skipping jshint-stylish@^1.0.0 C:\Data\projects\temp\myproject
30 verbose already installed skipping karma@^0.12.31 C:\Data\projects\temp\myproject
31 verbose already installed skipping karma-coverage@^0.2.7 C:\Data\projects\temp\myproject
32 verbose already installed skipping karma-jasmine@^0.3.5 C:\Data\projects\temp\myproject
33 verbose already installed skipping karma-junit-reporter@^0.2.2 C:\Data\projects\temp\myproject
34 verbose already installed skipping karma-firefox-launcher@^0.1.4 C:\Data\projects\temp\myproject
35 verbose already installed skipping load-grunt-tasks@^3.1.0 C:\Data\projects\temp\myproject
36 verbose already installed skipping protractor@^2.0.0 C:\Data\projects\temp\myproject
37 verbose already installed skipping time-grunt@^1.0.0 C:\Data\projects\temp\myproject
38 verbose already installed skipping request@^2.54.0 C:\Data\projects\temp\myproject
39 verbose already installed skipping request-promise@^0.4.1 C:\Data\projects\temp\myproject
40 verbose already installed skipping bower@^1.3.12 C:\Data\projects\temp\myproject
41 verbose already installed skipping grunt@^0.4.5 C:\Data\projects\temp\myproject
42 verbose already installed skipping grunt-autoprefixer@^2.0.0 C:\Data\projects\temp\myproject
43 verbose already installed skipping grunt-cli@^0.1.13 C:\Data\projects\temp\myproject
44 verbose already installed skipping grunt-concurrent@^1.0.0 C:\Data\projects\temp\myproject
45 verbose already installed skipping grunt-connect-proxy@0.1.10 C:\Data\projects\temp\myproject
46 verbose already installed skipping grunt-contrib-clean@^0.6.0 C:\Data\projects\temp\myproject
47 silly install resolved []
48 info build C:\Data\projects\temp\myproject
49 verbose linkStuff [ false,
49 verbose linkStuff   false,
49 verbose linkStuff   false,
49 verbose linkStuff   'C:\\Data\\projects\\temp' ]
50 info linkStuff myproject@0.0.0
51 verbose linkBins myproject@0.0.0
52 verbose linkMans myproject@0.0.0
53 verbose rebuildBundles myproject@0.0.0
54 verbose rebuildBundles [ '.bin',
54 verbose rebuildBundles   'bower',
54 verbose rebuildBundles   'grunt',
54 verbose rebuildBundles   'grunt-autoprefixer',
54 verbose rebuildBundles   'grunt-cli',
54 verbose rebuildBundles   'grunt-concurrent',
54 verbose rebuildBundles   'grunt-connect-proxy',
54 verbose rebuildBundles   'grunt-contrib-clean',
54 verbose rebuildBundles   'grunt-contrib-concat',
54 verbose rebuildBundles   'grunt-contrib-connect',
54 verbose rebuildBundles   'grunt-contrib-copy',
54 verbose rebuildBundles   'grunt-contrib-cssmin',
54 verbose rebuildBundles   'grunt-contrib-htmlmin',
54 verbose rebuildBundles   'grunt-contrib-imagemin',
54 verbose rebuildBundles   'grunt-contrib-jshint',
54 verbose rebuildBundles   'grunt-contrib-uglify',
54 verbose rebuildBundles   'grunt-contrib-watch',
54 verbose rebuildBundles   'grunt-filerev',
54 verbose rebuildBundles   'grunt-google-cdn',
54 verbose rebuildBundles   'grunt-karma',
54 verbose rebuildBundles   'grunt-newer',
54 verbose rebuildBundles   'grunt-ng-annotate',
54 verbose rebuildBundles   'grunt-protractor-runner',
54 verbose rebuildBundles   'grunt-protractor-webdriver',
54 verbose rebuildBundles   'grunt-svgmin',
54 verbose rebuildBundles   'grunt-usemin',
54 verbose rebuildBundles   'grunt-wiredep',
54 verbose rebuildBundles   'jasmine-core',
54 verbose rebuildBundles   'jshint-stylish',
54 verbose rebuildBundles   'karma',
54 verbose rebuildBundles   'karma-coverage',
54 verbose rebuildBundles   'karma-firefox-launcher',
54 verbose rebuildBundles   'karma-jasmine',
54 verbose rebuildBundles   'karma-junit-reporter',
54 verbose rebuildBundles   'load-grunt-tasks',
54 verbose rebuildBundles   'protractor',
54 verbose rebuildBundles   'request',
54 verbose rebuildBundles   'request-promise',
54 verbose rebuildBundles   'time-grunt' ]
55 info install myproject@0.0.0
56 verbose unsafe-perm in lifecycle true
57 info myproject@0.0.0 Failed to exec install script
58 verbose stack Error: myproject@0.0.0 install: `node node_modules/protractor/bin/webdriver-manager update`
58 verbose stack Exit status 1
58 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
58 verbose stack     at EventEmitter.emit (events.js:110:17)
58 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
58 verbose stack     at ChildProcess.emit (events.js:110:17)
58 verbose stack     at maybeClose (child_process.js:1015:16)
58 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
59 verbose pkgid myproject@0.0.0
60 verbose cwd C:\Data\projects\temp\myproject
61 error Windows_NT 6.3.9600
62 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
63 error node v0.12.2
64 error npm  v2.7.4
65 error code ELIFECYCLE
66 error myproject@0.0.0 install: `node node_modules/protractor/bin/webdriver-manager update`
66 error Exit status 1
67 error Failed at the myproject@0.0.0 install script 'node node_modules/protractor/bin/webdriver-manager update'.
67 error This is most likely a problem with the myproject package,
67 error not with npm itself.
67 error Tell the author that this fails on your system:
67 error     node node_modules/protractor/bin/webdriver-manager update
67 error You can get their info via:
67 error     npm owner ls myproject
67 error There is likely additional logging output above.
68 verbose exit [ 1, true ]
---------------------------- End ---------------------------

**Comment by smikes** [comment]
Thanks for providing the npm-debug.log file.

It looks like there may be a race between getting all of your dependencies in place and running the install script (specified in `myproject`'s package.json file as `"scripts": { "install": "node node_modules/protractor/bin/webdriver-manager update" }`

Can you try removing the `install` script from your project and see if that allows the `npm install` to succeed?

**Comment by UltimateFighter** [comment]
yes if i remove the "install" line and the npm install runns.

it seems to be a problem withe the webdriver-manager?

if i go to cmd in administrator mode (Windows 8.1 64bit) and run "npm install -g protractor" the following error occurs.

Installed is:

- node: v0.12.2
- npm: 2.7.4
- python: 2.7.9
- MVS: Microsoft Visual Studio Express 2012 für Windows Desktop
------------------------- Start-----------------------------
c:\>npm install -g protractor
-
> utf-8-validate@1.0.1 install C:\Users\theuser\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\utf-8-validate
> node-gyp rebuild


c:\>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
gyp: binding.gyp not found (cwd: c:\) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok

> bufferutil@1.0.1 install C:\Users\theuser\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\bufferutil
> node-gyp rebuild


c:\>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
gyp: binding.gyp not found (cwd: c:\) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.0.1
npm WARN optional dep failed, continuing bufferutil@1.0.1
C:\Users\theuser\AppData\Roaming\npm\protractor -> C:\Users\theuser\AppData\Roaming\npm\node_modules\protractor\bin\protractor
C:\Users\theuser\AppData\Roaming\npm\webdriver-manager -> C:\Users\theuser\AppData\Roaming\npm\node_modules\protractor\bin\webdriver-manager
protractor@2.0.0 C:\Users\theuser\AppData\Roaming\npm\node_modules\protractor
├── jasminewd@1.1.0
├── jasminewd2@0.0.3
├── html-entities@1.1.2
├── saucelabs@0.1.1
├── q@1.0.0
├── minijasminenode@1.1.1
├── adm-zip@0.4.4
├── optimist@0.6.1 (wordwrap@0.0.2, minimist@0.0.10)
├── glob@3.2.11 (inherits@2.0.1, minimatch@0.3.0)
├── accessibility-developer-tools@2.6.0
├── lodash@2.4.1
├── source-map-support@0.2.10 (source-map@0.1.32)
├── request@2.36.0 (qs@0.6.6, forever-agent@0.5.2, json-stringify-safe@5.0.0, aws-sign2@0.5.0, oauth-sign@0.3.0, tunnel-agent@0.4.0, mime@1.2.11, node-uuid@1.4.3, http-signature@0.10.1, form-data@0.1.
4, tough-cookie@0.12.1, hawk@1.0.0)
├── jasmine@2.1.1 (jasmine-core@2.1.3)
└── selenium-webdriver@2.45.1 (tmp@0.0.24, rimraf@2.3.2, ws@0.7.1, xml2js@0.4.4)
------------------------- End -----------------------------

**Comment by smikes** [comment]
As you said in your initial problem report, the problem seems to involve inappropriate searching in the path `C:\`.  I noticed this in your latest npm-debug.log:

```
gyp: binding.gyp not found (cwd: c:) while trying to load binding.gyp
```

I am not running node 0.12.2 on my Windows test machine -- I have 0.10.36, and with that I am able to do the following commands successfully:

```
> npm i -g protractor
> npm explore -g protractor
> node bin\webdriver-manager update
```

If you have a test environment where you can see if working with the last 0.10 release -- I believe it's 0.10.38 -- then we could rule out the 0.10/0.12 difference as a cause of this problem.

**Comment by UltimateFighter** [comment]
same Problem with 0.10.36 and 0.10.38:

------------------------- Start -----------------------------
c:\>npm install -g protractor
-
> bufferutil@1.0.1 install C:\Users\theuser\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\bufferutil
> node-gyp rebuild


c:\>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
gyp: binding.gyp not found (cwd: c:\) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing bufferutil@1.0.1

> utf-8-validate@1.0.1 install C:\Users\theuser\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\utf-8-validate
> node-gyp rebuild


c:\>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
gyp: binding.gyp not found (cwd: c:\) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.0.1
C:\Users\theuser\AppData\Roaming\npm\protractor -> C:\Users\theuser\AppData\Roaming\npm\node_modules\protractor\bin\protractor
C:\Users\theuser\AppData\Roaming\npm\webdriver-manager -> C:\Users\theuser\AppData\Roaming\npm\node_modules\protractor\bin\webdriver-manager
protractor@2.0.0 C:\Users\theuser\AppData\Roaming\npm\node_modules\protractor
├── jasminewd@1.1.0
├── jasminewd2@0.0.3
├── html-entities@1.1.2
├── saucelabs@0.1.1
├── q@1.0.0
├── minijasminenode@1.1.1
├── adm-zip@0.4.4
├── lodash@2.4.1
├── optimist@0.6.1 (wordwrap@0.0.2, minimist@0.0.10)
├── glob@3.2.11 (inherits@2.0.1, minimatch@0.3.0)
├── accessibility-developer-tools@2.6.0
├── request@2.36.0 (json-stringify-safe@5.0.0, forever-agent@0.5.2, aws-sign2@0.5.0, qs@0.6.6, tunnel-agent@0.4.0, oauth-sign@0.3.0, mime@1.2.11, node-uuid@1.4.3, tough-cookie@0.12.1, http-signature@0
.10.1, form-data@0.1.4, hawk@1.0.0)
├── source-map-support@0.2.10 (source-map@0.1.32)
├── jasmine@2.1.1 (jasmine-core@2.1.3)
└── selenium-webdriver@2.45.1 (tmp@0.0.24, rimraf@2.3.2, xml2js@0.4.4, ws@0.7.1)
------------------------- End -----------------------------

**Comment by smikes** [comment]
That is strange.  Thanks for doing that extra testing - I will ask someone more experience with Windows issues to look into this later today.

**Comment by UltimateFighter** [comment]
Thank you for your efforts in advance

**Comment by xzyfer** [comment]
We're seeing reports of this on node-sass with some Windows users. It appears to be related to `spawn` not playing well with multiple node versions installed. Some systems get multiple node installs due to different shells (i.e. cmd vs powershell vs git bash) or prepacked node versions in software like Visual Studio.

One kicker we noticed is that lifecycle scripts _appear_ to always be run with `cmd` which can cause issues for users running in a different shell (as these shell may be running different node/npm versions).

More information in a real world situation can be found in https://github.com/sass/node-sass/issues/1012#issuecomment-115715502
