### ISSUE TITLE
Do you have CDN for China?!

### ISSUE THREAD

**Issue by dotku** [npm/npm#7690]
It seems slow over here...

**Comment by smikes** [comment]
There isn't an *official* mirror, but there is an unofficial mirror here: https://npm.taobao.org/

**Comment by boxxxie** [comment]
npm is slow everywhere

**Comment by xorgy** [comment]
Yeah, NPM is slow everywhere.

Yesterday it was so slow for me that it timed out and crashed(callback never called error) mid way through an install. This is on a big fat gigabit pipe to the internet, 10ms or lower pings to most major datacentres.

**Comment by dotku** [comment]
all right, thx guys... due to it seems a common issue... 
anyone donate for their hosting fee?!

**Comment by iarna** [comment]
I'm going to close this as answered, and because further discussion here won't be productive.
