### ISSUE TITLE
Unable to install bower on Yosemite

### ISSUE THREAD

**Issue by michaeldeitcher** [npm/npm#7691]
Here is my log file:

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', '-g', 'bower' ]
2 info using npm@2.7.1
3 info using node@v0.12.0
4 verbose node symlink /usr/local/bin/node
5 silly cache add args [ 'bower', null ]
6 verbose cache add spec bower
7 silly cache add parsed spec { raw: 'bower',
7 silly cache add   scope: null,
7 silly cache add   name: 'bower',
7 silly cache add   rawSpec: '',
7 silly cache add   spec: '*',
7 silly cache add   type: 'range' }
8 verbose addNamed bower@*
9 silly addNamed semver.valid null
10 silly addNamed semver.validRange *
11 silly addNameRange { name: 'bower', range: '*', hasData: false }
12 silly mapToRegistry name bower
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/bower
16 verbose addNameRange registry:https://registry.npmjs.org/bower not in flight; fetching
17 verbose request uri https://registry.npmjs.org/bower
18 verbose request no auth needed
19 info attempt registry request try #1 at 07:20:13
20 verbose request id 572bd259e1eed43e
21 http request GET https://registry.npmjs.org/bower
22 http 200 https://registry.npmjs.org/bower
23 silly get cb [ 200,
23 silly get   { date: 'Fri, 20 Mar 2015 13:20:13 GMT',
23 silly get     server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
23 silly get     etag: '"7XOOQCTYTAH7EZVNOT9V5QF1C"',
23 silly get     'content-type': 'application/json',
23 silly get     'cache-control': 'max-age=60',
23 silly get     'content-length': '106160',
23 silly get     'accept-ranges': 'bytes',
23 silly get     via: '1.1 varnish',
23 silly get     age: '49',
23 silly get     'x-served-by': 'cache-lax1435-LAX',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '2',
23 silly get     'x-timer': 'S1426857613.528535,VS0,VE0',
23 silly get     vary: 'Accept',
23 silly get     'keep-alive': 'timeout=10, max=50',
23 silly get     connection: 'Keep-Alive' } ]
24 verbose get saving bower to /Users/michaeldeitcher/.npm/registry.npmjs.org/bower/.cache.json
25 verbose getCacheStat cache creation not in flight; initializing
26 silly addNameRange number 2 { name: 'bower', range: '*', hasData: true }
27 silly addNameRange versions [ 'bower',
27 silly addNameRange   [ '0.1.0',
27 silly addNameRange     '0.1.2',
27 silly addNameRange     '0.1.3',
27 silly addNameRange     '0.2.0',
27 silly addNameRange     '0.3.0',
27 silly addNameRange     '0.3.1',
27 silly addNameRange     '0.3.2',
27 silly addNameRange     '0.4.0',
27 silly addNameRange     '0.5.0',
27 silly addNameRange     '0.5.1',
27 silly addNameRange     '0.6.0',
27 silly addNameRange     '0.6.1',
27 silly addNameRange     '0.6.2',
27 silly addNameRange     '0.6.3',
27 silly addNameRange     '0.6.4',
27 silly addNameRange     '0.6.5',
27 silly addNameRange     '0.6.6',
27 silly addNameRange     '0.6.7',
27 silly addNameRange     '0.6.8',
27 silly addNameRange     '0.7.0',
27 silly addNameRange     '0.7.1',
27 silly addNameRange     '0.8.0',
27 silly addNameRange     '0.8.1',
27 silly addNameRange     '0.8.2',
27 silly addNameRange     '0.8.3',
27 silly addNameRange     '0.8.4',
27 silly addNameRange     '0.8.5',
27 silly addNameRange     '0.8.6',
27 silly addNameRange     '0.9.0',
27 silly addNameRange     '0.9.1',
27 silly addNameRange     '0.9.2',
27 silly addNameRange     '0.10.0',
27 silly addNameRange     '1.0.0',
27 silly addNameRange     '1.0.1',
27 silly addNameRange     '1.0.2',
27 silly addNameRange     '1.0.3',
27 silly addNameRange     '1.1.0',
27 silly addNameRange     '1.1.1',
27 silly addNameRange     '1.1.2',
27 silly addNameRange     '1.2.0',
27 silly addNameRange     '1.2.1',
27 silly addNameRange     '1.2.2',
27 silly addNameRange     '1.2.3',
27 silly addNameRange     '1.2.4',
27 silly addNameRange     '1.2.5',
27 silly addNameRange     '1.2.6',
27 silly addNameRange     '1.2.7',
27 silly addNameRange     '1.2.8',
27 silly addNameRange     '1.3.0',
27 silly addNameRange     '1.3.1',
27 silly addNameRange     '1.3.2',
27 silly addNameRange     '1.3.3',
27 silly addNameRange     '1.3.4',
27 silly addNameRange     '1.3.5',
27 silly addNameRange     '1.3.6',
27 silly addNameRange     '1.3.7',
27 silly addNameRange     '1.3.8',
27 silly addNameRange     '1.3.9',
27 silly addNameRange     '1.3.10',
27 silly addNameRange     '1.3.11',
27 silly addNameRange     '1.3.12' ] ]
28 verbose addNamed bower@1.3.12
29 silly addNamed semver.valid 1.3.12
30 silly addNamed semver.validRange 1.3.12
31 silly mapToRegistry name bower
32 silly mapToRegistry using default registry
33 silly mapToRegistry registry https://registry.npmjs.org/
34 silly mapToRegistry uri https://registry.npmjs.org/bower
35 verbose addRemoteTarball https://registry.npmjs.org/bower/-/bower-1.3.12.tgz not in flight; adding
36 verbose addRemoteTarball [ 'https://registry.npmjs.org/bower/-/bower-1.3.12.tgz',
36 verbose addRemoteTarball   '37de0edb3904baf90aee13384a1a379a05ee214c' ]
37 info retry fetch attempt 1 at 07:20:13
38 info attempt registry request try #1 at 07:20:13
39 http fetch GET https://registry.npmjs.org/bower/-/bower-1.3.12.tgz
40 http fetch 200 https://registry.npmjs.org/bower/-/bower-1.3.12.tgz
41 silly fetchAndShaCheck shasum 37de0edb3904baf90aee13384a1a379a05ee214c
42 verbose addTmpTarball /var/folders/cp/tph_pqfj03ldzd8yz4j9zv5h0000gn/T/npm-3902-36b3d9d5/registry.npmjs.org/bower/-/bower-1.3.12.tgz not in flight; adding
43 verbose addTmpTarball already have metadata; skipping unpack for bower@1.3.12
44 silly cache afterAdd bower@1.3.12
45 verbose afterAdd /Users/michaeldeitcher/.npm/bower/1.3.12/package/package.json not in flight; writing
46 verbose afterAdd /Users/michaeldeitcher/.npm/bower/1.3.12/package/package.json written
47 silly install resolved [ { name: 'bower',
47 silly install resolved     version: '1.3.12',
47 silly install resolved     description: 'The browser package manager',
47 silly install resolved     author: { name: 'Twitter' },
47 silly install resolved     licenses: [ [Object] ],
47 silly install resolved     repository: { type: 'git', url: 'https://github.com/bower/bower' },
47 silly install resolved     main: 'lib',
47 silly install resolved     homepage: 'http://bower.io',
47 silly install resolved     engines: { node: '>=0.10.0' },
47 silly install resolved     dependencies:
47 silly install resolved      { abbrev: '~1.0.4',
47 silly install resolved        archy: '0.0.2',
47 silly install resolved        'bower-config': '~0.5.2',
47 silly install resolved        'bower-endpoint-parser': '~0.2.2',
47 silly install resolved        'bower-json': '~0.4.0',
47 silly install resolved        'bower-logger': '~0.2.2',
47 silly install resolved        'bower-registry-client': '~0.2.0',
47 silly install resolved        cardinal: '0.4.0',
47 silly install resolved        chalk: '0.5.0',
47 silly install resolved        chmodr: '0.1.0',
47 silly install resolved        'decompress-zip': '0.0.8',
47 silly install resolved        fstream: '~1.0.2',
47 silly install resolved        'fstream-ignore': '~1.0.1',
47 silly install resolved        glob: '~4.0.2',
47 silly install resolved        'graceful-fs': '~3.0.1',
47 silly install resolved        handlebars: '~2.0.0',
47 silly install resolved        inquirer: '0.7.1',
47 silly install resolved        insight: '0.4.3',
47 silly install resolved        'is-root': '~1.0.0',
47 silly install resolved        junk: '~1.0.0',
47 silly install resolved        lockfile: '~1.0.0',
47 silly install resolved        'lru-cache': '~2.5.0',
47 silly install resolved        mkdirp: '0.5.0',
47 silly install resolved        mout: '~0.9.0',
47 silly install resolved        nopt: '~3.0.0',
47 silly install resolved        opn: '~1.0.0',
47 silly install resolved        osenv: '0.1.0',
47 silly install resolved        'p-throttler': '0.1.0',
47 silly install resolved        promptly: '0.2.0',
47 silly install resolved        q: '~1.0.1',
47 silly install resolved        request: '~2.42.0',
47 silly install resolved        'request-progress': '0.3.0',
47 silly install resolved        retry: '0.6.0',
47 silly install resolved        rimraf: '~2.2.0',
47 silly install resolved        semver: '~2.3.0',
47 silly install resolved        'shell-quote': '~1.4.1',
47 silly install resolved        'stringify-object': '~1.0.0',
47 silly install resolved        'tar-fs': '0.5.2',
47 silly install resolved        tmp: '0.0.23',
47 silly install resolved        'update-notifier': '0.2.0',
47 silly install resolved        which: '~1.0.5' },
47 silly install resolved     devDependencies:
47 silly install resolved      { coveralls: '~2.11.0',
47 silly install resolved        'expect.js': '~0.3.1',
47 silly install resolved        grunt: '~0.4.4',
47 silly install resolved        'grunt-cli': '^0.1.13',
47 silly install resolved        'grunt-contrib-jshint': '~0.10.0',
47 silly install resolved        'grunt-contrib-watch': '~0.6.1',
47 silly install resolved        'grunt-exec': '~0.4.2',
47 silly install resolved        'grunt-simple-mocha': '~0.4.0',
47 silly install resolved        istanbul: '~0.3.2',
47 silly install resolved        'load-grunt-tasks': '~0.6.0',
47 silly install resolved        mocha: '~1.21.4',
47 silly install resolved        nock: '~0.46.0',
47 silly install resolved        'node-uuid': '~1.4.1',
47 silly install resolved        proxyquire: '~1.0.1' },
47 silly install resolved     scripts: { test: 'grunt test' },
47 silly install resolved     bin: { bower: 'bin/bower' },
47 silly install resolved     preferGlobal: true,
47 silly install resolved     gitHead: 'b26c072f0db054a1902ec4d2e3726dbf8a1c799a',
47 silly install resolved     bugs: { url: 'https://github.com/bower/bower/issues' },
47 silly install resolved     _id: 'bower@1.3.12',
47 silly install resolved     _shasum: '37de0edb3904baf90aee13384a1a379a05ee214c',
47 silly install resolved     _from: 'bower@*',
47 silly install resolved     _npmVersion: '2.0.0',
47 silly install resolved     _npmUser: { name: 'sheerun', email: 'sheerun@sher.pl' },
47 silly install resolved     maintainers: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
47 silly install resolved     dist:
47 silly install resolved      { shasum: '37de0edb3904baf90aee13384a1a379a05ee214c',
47 silly install resolved        tarball: 'http://registry.npmjs.org/bower/-/bower-1.3.12.tgz' },
47 silly install resolved     directories: {},
47 silly install resolved     _resolved: 'https://registry.npmjs.org/bower/-/bower-1.3.12.tgz' } ]
48 info install bower@1.3.12 into /usr/local/lib
49 info installOne bower@1.3.12
50 verbose installOne of bower to /usr/local/lib not in flight; installing
51 verbose lock using /Users/michaeldeitcher/.npm/_locks/bower-e8debc5417026b57.lock for /usr/local/lib/node_modules/bower
52 silly install write writing bower 1.3.12 to /usr/local/lib/node_modules/bower
53 silly cache addNamed cb bower@1.3.12
54 verbose unbuild lib/node_modules/bower
55 verbose gentlyRm vacuuming /usr/local/lib/node_modules/bower
56 silly gentlyRm purging /usr/local/lib/node_modules/bower
57 verbose unlock done using /Users/michaeldeitcher/.npm/_locks/bower-e8debc5417026b57.lock for /usr/local/lib/node_modules/bower
58 verbose stack Error: EIO, rmdir '/usr/local/lib/node_modules/bower/lib/commands'
58 verbose stack     at Error (native)
59 verbose cwd /Users/michaeldeitcher/Workspace/trekaroo_js
60 error Darwin 14.1.0
61 error argv "node" "/usr/local/bin/npm" "install" "-g" "bower"
62 error node v0.12.0
63 error npm  v2.7.1
64 error path /usr/local/lib/node_modules/bower/lib/commands
65 error code EIO
66 error errno -5
67 error EIO, rmdir '/usr/local/lib/node_modules/bower/lib/commands'
68 error If you need help, you may report this error at:
68 error     <https://github.com/npm/npm/issues>
69 verbose exit [ -5, true ]
70 verbose unbuild lib/node_modules/bower
71 verbose gentlyRm vacuuming /usr/local/lib/node_modules/bower
72 silly gentlyRm purging /usr/local/lib/node_modules/bower
73 error error rolling back Error: EIO, rmdir '/usr/local/lib/node_modules/bower/lib/commands'
73 error error rolling back     at Error (native)
73 error error rolling back  { [Error: EIO, rmdir '/usr/local/lib/node_modules/bower/lib/commands']
73 error error rolling back   errno: -5,
73 error error rolling back   code: 'EIO',
73 error error rolling back   path: '/usr/local/lib/node_modules/bower/lib/commands' }

**Comment by KenanY** [comment]
To quote @othiym23:

> `EIO` is a low-level Node / libuv / libc error indicating that something is seriously wrong with the running OS's disk I/O. If you can, try restarting the instance and see if the problem persists. This error is not raised by `npm` itself, so if that doesn't fix it, take a look at your Node installation.

**Comment by michaeldeitcher** [comment]
Ah I rebooted and it worked. Thanks KenanY
