### ISSUE TITLE
npm adduser - cannot auth an existing account in new machine

### ISSUE THREAD

**Issue by sytong** [npm/npm#7695]
I got the below error message and I am not sure what to do.
I have successfully auth my account on another machine earlier today but couldn't do this again when I am at home.
I am sure my id, password and email are correct as I can logon to the npm web site.

I was also having some trouble accessing npm web site earlier tonight, got 503 Backend Read Error but it seems to be ok now.

Any suggestions on fixing my problem with adduser command please?
(I have omitted my user name and email from the output)

```
npm WARN adduser Incorrect username or password
npm WARN adduser You can reset your account by visiting:
npm WARN adduser
npm WARN adduser     https://npmjs.org/forgot
npm WARN adduser
npm ERR! Windows_NT 6.1.7600
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "adduser"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code E403

npm ERR! forbidden may not mix password_sha and pbkdf2
npm ERR! You may need to upgrade your version of npm:
npm ERR!   npm install npm -g
npm ERR! Note that this may need to be run as root/admin (sudo, etc.)
npm ERR!
npm ERR! : -/user/org.couchdb.user:<user_name_hidden>/-rev/2-ce5b0d7d39c35cf28468d86a6abf22e1
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Code\npm-debug.log
```

**Comment by smikes** [comment]
This error: ` forbidden may not mix password_sha and pbkdf2` is usually fixed by changing your password at <https://npmjs.org/password> -- you can even "change" it to the same password as you currently have.  The important part is invalidating the older version of the auth token (password_sha).

Please let me know if this doesn't work, though.

**Comment by sytong** [comment]
That works!!
Thanks a lot Sam!!
