### ISSUE TITLE
npm ERR! network connect ETIMEDOUT

### ISSUE THREAD

**Issue by mushishi78** [npm/npm#7697]
Fresh install of node.js and npm, I'm getting a timeout when installing some, but not all, packages. Specifically, I can successfully install gulp, babel and webpack, but not browserify or bower.

I'm not behind a proxy server, and I've tried setting the registry to http rather than https.

[Here is the npm-debug.log from trying to install browserify.](https://gist.githubusercontent.com/mushishi78/320a7931187fdb2fb836/raw/gistfile1.txt)

As I assumed that it was not a bug, I [put this question on stackoverflow](http://stackoverflow.com/questions/29175262/npm-err-network-connect-etimedout) as well, and will close this issue if I get an answer there explaining that I did something obvious wrong.

**Comment by mushishi78** [comment]
Wouldn't you know, I got it working 10 minutes later. Sorry to be a bother.

**Comment by tomatosource** [comment]
How please?

**Comment by mushishi78** [comment]
Sorry I should've written that down, I wish I could remember. It was something like I had a previous installation which I had deleted by hand but has left behind a rsa key in my user folder maybe? I hope you figure it out :)
