### ISSUE TITLE
NPM Install command issue

### ISSUE THREAD

**Issue by vrn1kor** [npm/npm#7698]
Hello Team,

I have been using nodeJS for quite sometime and everything was fine. Unfortunately the npm installation command is not working anymore. I tried various ways including proxy settings. Which ever command I try to use I get the either of the following error.

1. ERROR -4048
2. ERROR ECONNRESET

NPM version is as follows,
NPM: 2.5.1
Node:0.12.0

Thanks in advance,
Venkat

**Comment by KenanY** [comment]
> ERROR -4048

Could you first try restarting the machine? If issue persists, could you also try downgrading to the latest Node.js v0.10? v0.12 is still kind of new, so maybe it causing an issue here. These are the steps from @smikes that solved this same issue here: https://github.com/npm/npm/issues/7528

> ERROR ECONNRESET

Yeah, this is an issue with your internet connection :/ (despite your mentioned proxy settings)....

If you still receive either of these, it would help a bit to upload the resulting `npm-debug.log` as a [gist](https://gist.github.com/).

**Comment by vrn1kor** [comment]
Hi Kenan,
Thanks.

ERROR -4048: I tried restarting the system (Windows 7) and the problem does not solve. I will try to downgrade rhe Node.JS version.

ERROR EPERM display when I try to set the proxy:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'config',
1 verbose cli   'set',
1 verbose cli   'proxy' ]
2 info using npm@1.4.28
3 info using node@v0.10.32
4 verbose node symlink C:\Program Files (x86)\nodejs\\node.exe
5 info config set "proxy" ""
6 error Error: EPERM, open 'C:\Users\XXXXXX\.npmrc'
6 error  { [Error: EPERM, open 'C:\Users\vrn1kor\.npmrc'] errno: 50, code: 'EPERM', path: 'C:\\Users\\vrn1kor\\.npmrc' }
7 error Please try running this command again as root/Administrator.
8 error System Windows_NT 6.1.7601
9 error command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "config" "set" "proxy"
10 error cwd C:\
11 error node -v v0.10.32
12 error npm -v 1.4.28
13 error path C:\Users\vrn1kor\.npmrc
14 error code EPERM
15 error errno 50
16 error stack Error: EPERM, open 'C:\Users\XXXXXXX\.npmrc'
17 verbose exit [ 50, true ]

Regards,
Venkat

**Comment by KenanY** [comment]
@vrn1kor 

```
11 error node -v v0.10.32
12 error npm -v 1.4.28
```

What happened to Node.js v0.12 and `npm@2.5.1` :scream:

As for the `EPERM`, it is strange to me how you don't have permission to access the config file. I guess you could try [changing the permissions](https://support.microsoft.com/en-us/kb/308419)?

**Comment by vrn1kor** [comment]
It looks really strange. If I try to run the command "npm version" I get the following,

NPM:2.5.1
NODE: 0.12.0

Then how come it is displaying a different version ?. I am surprised.

**Comment by KenanY** [comment]
@vrn1kor Oh, maybe you have `npm` installed in two places: the Node.js directory (`C:\Program Files (x86)\nodejs\`) and the `APPDATA` folder... it's a little complicated but this might help explain it: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows

**Comment by vrn1kor** [comment]
Yes, you are right I have it in 2 places. Is this a problem ? If so, which one to delete. ?.

**Comment by KenanY** [comment]
@vrn1kor Personally, I like option 2 from [here](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows) for its simplicity. Don't miss the paragraph about `.npmrc` that comes after the list :)

**Comment by vrn1kor** [comment]
I followed option 2, but I have the folder C:\Users\<username>\AppData\Roaming\npm\node_modules BUT NOT C:\Users\<username>\AppData\Roaming\npm\node_modules\npm to place the NPMRC file. Any idea ?.

**Comment by vrn1kor** [comment]
I created a new folder NPM I tried....

**Comment by KenanY** [comment]
@vrn1kor Ohhh shoot, I forgot to make sure you do `npm install -g npm` to get that folder there :( could you bring back the `C:\Program Files (x86)\nodejs\` files from the Recycling Bin and see if you can run `npm` from the command line?

**Comment by vrn1kor** [comment]
No, I created a new folder "npm" and placed the file "npmrc" under the folder : C:\Users\XXXXXXX\AppData\Roaming\npm\node_modules\. But now when I run the command "npm" it is saying the statement is not recognized.

**Comment by KenanY** [comment]
@vrn1kor Yeah because we deleted `npm` :( now I'm really confused though as to why it seemed like you had two different version of Node and `npm` installed....

**Comment by vrn1kor** [comment]
Shall I restart the system ?.

**Comment by vrn1kor** [comment]
Or shall I install the NodeJS again ?. How to delete the complete trace of NodeJS on my system ?.

**Comment by vrn1kor** [comment]
Hi Kenan,

I have resolved the problem. The issue was due to old credentials for proxy stored in the .npmrc file.

Regards,
Venkat
