### ISSUE TITLE
Attempt to unlock node_modules/socket.io, which hasn't been locked

### ISSUE THREAD

**Issue by shrisarnobat1980** [npm/npm#7701]
When I run node install command, I get below exception

npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.7.1

![image](https://cloud.githubusercontent.com/assets/9894601/6766667/792b9f5c-cfcc-11e4-8f04-21a7d65426aa.png)

npm ERR! Attempt to unlock /Users/smitasarnobat/website/node_modules/socket.io, which hasn't been locked

**Comment by KenanY** [comment]
@shrisarnobat1980 Looks like you might have lost permission to write to your `npm` cache folder. Could you try running the following command?:

``` sh
$ sudo chown -R $(whoami) "$HOME/.npm"
```

**Comment by shrisarnobat1980** [comment]
Gr8. It worked. It created node_modules folder.
