### ISSUE TITLE
Potential race condition on Windows 7 x64

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [npm/npm#7706]
Recently I started having a problem with my npm installation, I hope someone could shed some light in case this is a problem with my environment. I didn't found any issue regarding this.

Before explaining what happened here what I have done:

* I removed the previous node version, removed the folder `C:\Users\<user>\AppData\Roaming\npm`, installed the latest node `0.12.0` (x86) and updated npm to `2.7.4`.
* All versions comply with the ones mentioned above when using `node -v` and `npm -v` commands.
* I used `npm cache clean` before each test attempt and the problem below occurred in like 80% of the time. Sometimes in different operations.
* Microsoft Security Essentials real-time protection is disabled
* There is no proxy server in the network, only the ADSL router (with firewall disabled)

**Problem**
When installing any package, npm get stuck in some operations. Sometimes when dealing with json files, sometimes after receiving a successful `200` response from the server, sometimes when retrieving something from the network.

No error, and no satisfactory timeout after waiting at least 1 minute (One time this happened I left for hours, and it remained stuck).

**How to reproduce**
1. Create a `test-project` dir
2. Use `npm-init` inside the dir to start a placeholder project (all default)
3. Use some command to install any module

----- Attempt 1: 
`$ npm cache clean`
`$ npm install grunt-contrib-jshint -ddd --save-dev`
https://gist.github.com/FagnerMartinsBrack/d0c4da2571027e4ea180

----- Result 1:
It's stuck forever on `npm verb afterAdd C:\Users\Homer\AppData\Roaming\npm-cache\sigmund\1.0.0\package\package.json written`

----- Attempt 2: 
`$ npm cache clean`
`$ npm install grunt-contrib-jshint -ddd --save-dev`
https://gist.github.com/FagnerMartinsBrack/79432e77eae66cf7707b

----- Result 2:
It's stuck forever on `npm verb afterAdd C:\Users\Homer\AppData\Roaming\npm-cache\hooker\0.2.3\package\package.json written`

----- Attempt 3: 
`$ npm cache clean`
`$ npm install -g grunt-cli -ddd`
https://gist.github.com/FagnerMartinsBrack/7e52e3633e94dc1eb7ad

----- Result 3:
It's stuck forever on `npm http request GET https://registry.npmjs.org/grunt-cli` (no network activity, that's how I know it's stuck).

**System**
* Windows 7 Professional SP1 x64
* node 0.12.0
* npm 2.7.4

Any idea of what might be going on here? Everything points out to be a bug, although not consistently reproducible.

**Comment by smikes** [comment]
Now that node 0.12.1 is out, can you try with that version?  

We have seen some similar problems on Windows + node 0.12.0, but they usually crash weirdly instead of hanging.  If you need stability, I would recommend 0.10.38

**Comment by FagnerMartinsBrack** [comment]
This problem is not occurring anymore. I didn't changed anything in my local installation, it just don't hang anymore with `node -v` === `0.12.0`.

Weird right? Anyway, this anecdotal might help as an evidence to track down the problem, if this occur again I create a new report.
