### ISSUE TITLE
npm install fails when using dependencies assigned with https://github.com

### ISSUE THREAD

**Issue by bdefore** [npm/npm#7708]
I'm using nvm on OSX 10.10.1 and with a package.json of:

```
{
  "devDependencies": {
    "react-paginate": "https://github.com/bdefore/react-paginate"
  }
}
```

I get this output from node 0.12 and then 0.10: https://gist.github.com/bdefore/067b7372ad8406f35006

**Comment by KenanY** [comment]
@bdefore Please see the [docs for `npm install`](https://docs.npmjs.com/cli/install). If you want to provide a URL, it has to lead to a tarball. I assume you want `npm` to `git clone` that repository, in which case you should do:

``` json
{
  "devDependencies": {
    "react-paginate": "bdefore/react-paginate"
  }
}
```

Which is shorthand syntax.

**Comment by bdefore** [comment]
Cross posted from atom/apm#319

**Comment by bdefore** [comment]
That works, thanks.
