### ISSUE TITLE
Unable to install express in visual studio 2012 professional

### ISSUE THREAD

**Issue by shubha123** [npm/npm#7711]
I have installes ntvs software and able to add nodejs express project in my visual studio 2012.while adding it gives me a popup stating that to add npm pakage .while installing it will end with waring message with missing express installation.can you please help me in this.

**Comment by KenanY** [comment]
@shubha123 If this is indeed a `npm` issue, we can help :) is there any sort of error log that you could upload as a [gist](https://gist.github.com)? It's not immediately clear to me what the issue is nor who is at fault.

**Comment by shubha123** [comment]
Hi
Please find attached log file.
Waiting for your reply
Thanks in Advance
Shubha

**Comment by KenanY** [comment]
@shubha123 Could you please upload the log as a [gist](https://gist.github.com/), as I suggested? Attaching logs to an email reply does not work.

**Comment by shubha123** [comment]
Hi Kenan,
Am still facing the same issue .not able to install express.i have also posted a log in gist.waiting for your reply.Thanks in advance

**Comment by timoxley** [comment]
@shubha123 can please give us the link to the gist?

**Comment by shubha123** [comment]
https://gist.github.com/shubha123/fbb76d64185694296642

**Comment by shubha123** [comment]
https://gist.github.com/shubha123/fbb76d64185694296642

**Comment by timoxley** [comment]
```
36 error syscall getaddrinfo
37 error network getaddrinfo ENOTFOUND registry.npmjs.org
37 error network This is most likely not a problem with npm itself
37 error network and is related to network connectivity.
37 error network In most cases you are behind a proxy or have bad network settings.
37 error network
37 error network If you are behind a proxy, please make sure that the
37 error network 'proxy' config is set properly.  See: 'npm help config'
```

> This is most likely not a problem with npm itself and is related to network connectivity. In most cases you are behind a proxy or have bad network settings.

Are you behind a proxy?

**Comment by shubha123** [comment]
Yes .my system is under my company proxy..how can I over come from this.do I have to mention proxy address any where under npm pakage?if yes how and where?

**Comment by timoxley** [comment]
I've never had this issue, but a quick google gave me the following links which look about right:

* http://jjasonclark.com/how-to-setup-node-behind-web-proxy
* http://wil.boayue.com/blog/2013/06/14/using-npm-behind-a-proxy/

**Comment by kmanion** [comment]
Hi @shubha123, it looks like you got help configuring the proxy.

We’re trying to clean up some issues. If this is still a problem for you, can you please reply and let us know? We’ll be happy to reopen if necessary.

Also, feel free to reach out to support@npmjs.com if you have other questions.
