### ISSUE TITLE
Error downloading packages using a proxy with authenthication 

### ISSUE THREAD

**Issue by esemtia-aaa** [npm/npm#7714]
I have configured my proxy settings in .npmrc and my proxy sends me an error that says that i'm not authentificated. Is a proxy error or is an error of npm settings?

**Comment by smikes** [comment]
Not quite an error in either.  You might need to give `npm` more information, or run `cntlm` depending on what type of proxy you have -- see http://stackoverflow.com/questions/18569054/npm-behind-ntlm-proxy

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
