### ISSUE TITLE
unable to install jquery and nodequery

### ISSUE THREAD

**Issue by raghucssit** [npm/npm#7715]
hi am unable to install jquery and nodequery in node js

i got the below error message

```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "nodequery"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! Invalid protocol: socks:
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\bindu.nl\npm-debug.log
```

**Comment by KenanY** [comment]
@raghucssit Hmm, I don't think I have seen this before. However, there doesn't appear to be a package called `nodequery` on the registry:

```
$ npm info nodequery
npm ERR! 404 Not Found: nodequery
npm ERR! 404 
npm ERR! 404 'nodequery' is not in the npm registry.
```

I'm not sure where the `socks:` protocol came from. If you'd like help with that, could you upload the resulting `npm-debug.log` as a [gist](https://gist.github.com)?

**Comment by raghucssit** [comment]
hi kenon,

below is the npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'nodequery' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose config Skipping project config: C:\Users\bindu.nl/.npmrc. (matches userconfig)
6 silly cache add args [ 'nodequery', null ]
7 verbose cache add spec nodequery
8 silly cache add parsed spec { raw: 'nodequery',
8 silly cache add   scope: null,
8 silly cache add   name: 'nodequery',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 verbose addNamed nodequery@*
10 silly addNamed semver.valid null
11 silly addNamed semver.validRange *
12 silly addNameRange { name: 'nodequery', range: '*', hasData: false }
13 silly mapToRegistry name nodequery
14 silly mapToRegistry using default registry
15 silly mapToRegistry registry http://registry.npmjs.org/
16 silly mapToRegistry uri http://registry.npmjs.org/nodequery
17 verbose addNameRange registry:http://registry.npmjs.org/nodequery not in flight; fetching
18 verbose request uri http://registry.npmjs.org/nodequery
19 verbose request no auth needed
20 info attempt registry request try #1 at 4:23:04 PM
21 verbose request id 3e7dcd8741c7a6ba
22 http request GET http://registry.npmjs.org/nodequery
23 info retry will retry, error on last attempt: Error: Invalid protocol: socks:
24 info attempt registry request try #2 at 4:23:14 PM
25 http request GET http://registry.npmjs.org/nodequery
26 info retry will retry, error on last attempt: Error: Invalid protocol: socks:
27 info attempt registry request try #3 at 4:24:14 PM
28 http request GET http://registry.npmjs.org/nodequery
29 verbose stack Error: Invalid protocol: socks:
29 verbose stack     at Request.init (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:591:31)
29 verbose stack     at new Request (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:264:8)
29 verbose stack     at request (C:\Program Files\nodejs\node_modules\npm\node_modules\request\index.js:50:10)
29 verbose stack     at CachingRegistryClient.makeRequest (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:155:13)
29 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:69:17
29 verbose stack     at RetryOperation._fn (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\attempt.js:15:5)
29 verbose stack     at null._onTimeout (C:\Program Files\nodejs\node_modules\npm\node_modules\retry\lib\retry_operation.js:32:10)
29 verbose stack     at Timer.listOnTimeout (timers.js:110:15)
30 verbose cwd C:\Users\bindu.nl
31 error Windows_NT 6.1.7601
32 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "nodequery"
33 error node v0.12.0
34 error npm  v2.5.1
35 error Invalid protocol: socks:
36 error If you need help, you may report this error at:
36 error     <http://github.com/npm/npm/issues>
37 verbose exit [ 1, true ]

**Comment by raghucssit** [comment]
any body please help me on this

**Comment by iarna** [comment]
My best guess is that you have a proxy configured with a `socks:` protocol, which isn't supported?

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
