### ISSUE TITLE
Apache JMeter with Cassandra

### ISSUE THREAD

**Issue by TataCS** [npm/npm#7716]
I require the pre complied Cassandra jars that work with Apache Jmeter-2.13
I tried building the jars using CassJmeter and Cql-jmeter but could get only few of the functionlaity
The basic functionality of PUT,COUNTER PUT, BATCH PUT, COMPOSITE PUT, GET cannot be accessed.

**Comment by KenanY** [comment]
@TataCS Is this an issue with `npm`? If not, you might have better luck getting help from the developers of what you are having an issue with.

**Comment by TataCS** [comment]
no its isnt sorry for the wrong post
