### ISSUE TITLE
npm publish messed up fury version badge on npm module page.

### ISSUE THREAD

**Issue by cmpsoares91** [npm/npm#7718]
At the following package page, [nmae](https://www.npmjs.com/package/nmae) the badge is supposed to be like: [![GitHub version](https://badge.fury.io/gh/cmpsoares91%2Fnmae.svg)](http://badge.fury.io/gh/cmpsoares91%2Fnmae) Link: `http://badge.fury.io/gh/cmpsoares91%2Fnmae`

But instead of that on the published package page appears this: [![GitHub version](https://badge.fury.io/gh/cmpsoares91%252Fnmae.svg)](http://badge.fury.io/gh/cmpsoares91%252Fnmae) Link: `http://badge.fury.io/gh/cmpsoares91%252Fnmae`

Note that when published the link was changed:
before: `http://badge.fury.io/gh/cmpsoares91%2Fnmae`
after: `http://badge.fury.io/gh/cmpsoares91%252Fnmae`

I checked the [README.md](https://github.com/cmpsoares91/nmae/blob/master/README.md) to see if it was me who made the mistake but no, it had something to do with the parsing process on `npm publish`, I suppose.

**Comment by KenanY** [comment]
@cmpsoares91 This doesn't look like the fault of `npm publish` to me:

``` sh
$ npm install nmae
$ grep '%2F' < node_modules/nmae/README.md 
[![GitHub version](https://badge.fury.io/gh/cmpsoares91%2Fnmae.svg)](http://badge.fury.io/gh/cmpsoares91%2Fnmae) [![npm version](https://badge.fury.io/js/nmae.svg)](http://badge.fury.io/js/nmae) [![Code Climate](https://codeclimate.com/github/cmpsoares91/NMAE/badges/gpa.svg)](https://codeclimate.com/github/cmpsoares91/NMAE) [![Test Coverage](https://codeclimate.com/github/cmpsoares91/NMAE/badges/coverage.svg)](https://codeclimate.com/github/cmpsoares91/NMAE)
```

If anything, this might be an issue with how the website is rendering your `README.md`, in which case this is an issue for [`npm/newww`](https://github.com/npm/newww).

**Comment by cmpsoares91** [comment]
Ok I'll pass it to the website then.
