### ISSUE TITLE
Invalid name: "Technobabble Ipsum"

### ISSUE THREAD

**Issue by trailsandtribulations** [npm/npm#7719]
apm install Technobabble\ Ipsum

did not get so far as to create  /tmp/apm-install-dir-115224-18854-6b0naj/npm-debug.log

**Comment by KenanY** [comment]
@trailsandtribulations I don't understand what you are trying to do; if a `npm-debug.log` is generated it would help if you could upload it as a [gist](https://gist.github.com/). I should note that package names cannot have capital letters nor spaces.

**Comment by trailsandtribulations** [comment]
attempting to load a packing from atom, which apparently uses its own
flavor of npm called apm.

appears the problem is the package name itself. will attempt to contact
package maintainer.

thanks. please consider this issue closed.

**Comment by othiym23** [comment]
Closing as resolved!
