### ISSUE TITLE
Implement self update functionality in an npm global module

### ISSUE THREAD

**Issue by jviotti** [npm/npm#7723]
I'm looking forward to provide an `update` command for my CLI application which will self update the application to it's latest version using npm.

The code I'm using to perform the global update programatically (which should be analogous to `npm update -g <package-name>`):

```coffee
npm = require('npm')
async = require('async')
_ = require('lodash-contrib')

exports.update = (name, callback) ->
	async.waterfall([

		(callback) ->
			options =

				# TODO: There is no way to quiet npm install completely.
				# Some output is still shown once the module is updated
				# https://github.com/npm/npm/issues/2040
				loglevel: 'silent'
				global: true

			npm.load(options, _.unary(callback))

		(callback) ->
			npm.commands.update [ name ], (error, data) ->
				return callback(error, data)

		(data, callback) ->
			if _.isEmpty(data)
				error = new Error('You are already running the latest version')
				return callback(error)

			newVersion = _.last(_.first(_.last(data)).split('@'))
			return callback(null, newVersion)

	], callback)
```

The problem is that when I run this function within my package, I instantly get "You are already running the latest version", even when that's not true (I can check successfully that there is a newer version with `pm.commands.view`).

After tracking the error, it seems that `npm.commands.outdated` returns an empty array when being called by `npm.commands.update`.

Calling `npm.commands.ls` shows that my package is not between the list of installed packages.

It looks like if I install my app with the system available npm from the command line:

```sh
$ npm install -g <package>
```

It will not be seen by my local installation of the `npm` package within my application, therefore `npm.commands.update` fails.

Which is the correct way of implementing this functionality? Should I just delegate to the system npm with `child_process` instead?

**Comment by jviotti** [comment]
It turns out I can create a new file outside my main application, require the module containing my `update` function and it works in that case. What's going on?

**Comment by jviotti** [comment]
In case you want to reproduce this by yourselves:

Install an older version of `resin-cli` (e.g: 0.5.0):

```sh
$ npm install -g resin-cli@0.5.0
```

Try to perform an update:

```sh
$ resin update
You are already running the latest version
```

**Comment by jviotti** [comment]
I've tried running `npm.commands.ls` from within my application and from a file created in the root of my application.

From within my application, I get all the locally installed dependencies and devDependencies, even when `global` option is set to `true` in `npm.load`. 

From within a file in the root of my application, I get all the globally installed packages in my system, including the correct outdated version of my package.

How can it be that the same `npm` local module behaves in two different ways?

**Comment by othiym23** [comment]
You probably want to use `npm.commands.install`, and you should be using `prefix` instead of / in addition to forcing `global` to true.

This is not a super safe way to use the npm API, in any case. If you look over npm's issues, you'll see that there are many, many issues involving npm unexpectedly "deleting itself" when it has the privileges to remove the symbolic link to the binary from `/usr/local`, but not the privileges to remove the old version from or install the new version to the global prefix. If you really want to do this, a far (far (far)) safer thing to do is to call npm as a child process to run `npm install -g whatevs` (or even `npm update -g whatevs`, although I wouldn't do that with anything other than very recent (`npm@>=2.6.0`) versions of npm).

**Comment by snopeks** [comment]
Hello @jviotti, hope you've been well.  We haven’t heard back and we’re trying to clean up some issues. If you still need assistance, can you please reply and let us know? We’ll be happy to reopen if necessary. Thanks! -Stephanie, npm Tech Support.
