### ISSUE TITLE
unpublish, then publish (new version) and getting 409

### ISSUE THREAD

**Issue by davehorton** [npm/npm#7724]
Sorry if this is a newbie question or obvious.

I had a repo that I published in npm a while back.  Then I unpublished it.  Now I have a different code base that I want to publish under the same name.  (The version number BTW of the new package does not conflict with the old).  When I do 'npm publish' it fails with a 409 response to the put.  I've looked at the npm-debug log (available [here](https://gist.github.com/davehorton/24aa26518bd5e079863e) ) but cant make sense of any of the error messages 

(suggestion: it would be great if npm stuck a custom HTTP header X-something on the error response to give me some kind of hint)

Can someone point me to the rules of the road when it comes to unpublishing/republishing (if that is the problem here) or otherwise help point out what I am doing wrong?

**Comment by bcoe** [comment]
@davehorton we're in the process of doing some server maintenance which potentially caused your publication problem.

Would you mind attempting to publish again?

**Comment by davehorton** [comment]
Sure, just tried again, still failed though so perhaps the maintenance work wasn't the cause?

New gist of npm-debug.log [here](https://gist.github.com/davehorton/025e2747f1d3481a77ee)

**Comment by bcoe** [comment]
Thanks dave, I'm digging through the logs and will get back to you ASAP.

**Comment by bcoe** [comment]
Digging into the logs, I think I might see what happened to you. Could you do me a favor and try publishing a patch release:

`version = 0.1.1`, rather than `version = 0.1.0`.

Cheers,

-- Ben.

**Comment by davehorton** [comment]
yup doing that now..

**Comment by davehorton** [comment]
Worked!  I guess I can close this issue?  Thanks very much for the rapid response

**Comment by bcoe** [comment]
@davehorton awesome. You happen to have caught me in the middle of rolling out new servers -- so I'm keeping a very close eye on things -- let me know if you have any more problems :+1:
