### ISSUE TITLE
support setting the tag through npm.commands.publish

### ISSUE THREAD

**Issue by ghost** [npm/npm#7728]
the `--tag` option is available on the command line, but not included in the [publish api](https://docs.npmjs.com/api/publish)

While (from reading the docs, I think) it is possible to affect this behavior through the package.json, or by setting tag in the config, I think it would be handy to have the option to set the tag in the publish() call.

If there are reasons not to add it there, I suggest updating the api docs to show how to set the tag before making the call.

(see also: https://github.com/cmanzana/node-publish/issues/4)

**Comment by smikes** [comment]
Thanks for reporting this.

(Note to me: documentation bug).

**Comment by iarna** [comment]
You actually _can_ pass it in, via npm.load:
```
npm.load({tag: 'tag-name'}, function (er) {
  npm.commands.install(…)
})
```

**Comment by seanpkps** [comment]
It may not be local to the publish call, but another option.
