### ISSUE TITLE
npm publish failing with 504 Gateway Timeout

### ISSUE THREAD

**Issue by ldeluca** [npm/npm#7736]
Trying to publish an npm module to a private npm server and I'm getting a 504 Gateway Timeout error.  I published another module just to see if something was off with the private server but it published just fine.  The big difference I see between the module that worked and the module that failed was the module that failed is a much larger file.  32.3MB.  Would that cause the gateway timeout?  How do we increase the timeout value for a private npm server?

npm http request PUT http://npm.<ourprivateserver>.com/com.package.name
npm http 504 http://npm.<ourprivateserver>.com/com.package.name
npm verb bad json <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
npm verb bad json <html><head>
npm verb bad json <title>504 Gateway Timeout</title>
npm verb bad json </head><body>
npm verb bad json <h1>Gateway Timeout</h1>
npm verb bad json <p>The gateway did not receive a timely response
npm verb bad json from the upstream server or application.</p>
npm verb bad json </body></html>
npm verb bad json 
npm ERR! registry error parsing json
npm info retry will retry, error on last attempt: SyntaxError: Unexpected token <
npm info retry <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
npm info retry <html><head>
npm info retry <title>504 Gateway Timeout</title>
npm info retry </head><body>
npm info retry <h1>Gateway Timeout</h1>
npm info retry <p>The gateway did not receive a timely response
npm info retry from the upstream server or application.</p>
npm info retry </body></html>

**Comment by bcoe** [comment]
@ldeluca who is hosting the private npm server., are you running your own `npm-registry-couchapp`?

**Comment by ldeluca** [comment]
It's a test server at this point internal to our company.  So I can definitely speak with the person who set it up to change any config settings if that's what you're asking @bcoe

**Comment by bcoe** [comment]
@idelca could you have the individual who setup the inter npm server contact support [at] npmjs.com?
