### ISSUE TITLE
could not run npm in cmd prompt

### ISSUE THREAD

**Issue by soumyarsap** [npm/npm#7738]
This is the error log which is recorded on running this file.

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js' ]
2 info using npm@1.4.28
3 info using node@v0.10.32
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 error Error: ENOENT, stat 'C:\Users\I061951.GLOBAL\AppData\Roaming\npm'
6 error If you need help, you may report this *entire* log,
6 error including the npm and node versions, at:
6 error     <http://github.com/npm/npm/issues>
7 error System Windows_NT 6.1.7601
8 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js"
9 error cwd C:\Users\I061951.GLOBAL
10 error node -v v0.10.32
11 error npm -v 1.4.28
12 error path C:\Users\I061951.GLOBAL\AppData\Roaming\npm
13 error code ENOENT
14 error errno 34
15 verbose exit [ 34, true ]
```

**Comment by KenanY** [comment]
@soumyarsap This is a consequence of https://github.com/joyent/node/issues/8141, and is an issue with the Node installer for Windows. The workaround is to ensure that `C:\Users\I061951.GLOBAL\AppData\Roaming\npm` exists and is writable with your normal user account.

**Comment by soumyarsap** [comment]
PATH variable is set to the npm in user variables for my account. I can not run the npm install -g grunt-cli is failing now. proxy config needs t obe changed. now got the error as below for proxy.

aming\npm-cache\_locks\grunt-cli-59277df109f978ed.lock for C:\Users\I061951.GLOBAL\AppData\Roaming\npm\node_modules\grunt-cli
181 verbose stack Error: getaddrinfo ENOTFOUND registry.npmjs.org
181 verbose stack     at errnoException (dns.js:44:10)
181 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)
182 verbose cwd C:\Users\I061951.GLOBAL
183 error Windows_NT 6.1.7601
184 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "grunt-cli"
185 error node v0.12.1
186 error npm  v2.5.1
187 error code ENOTFOUND
188 error errno ENOTFOUND
189 error syscall getaddrinfo
190 error network getaddrinfo ENOTFOUND registry.npmjs.org
190 error network This is most likely not a problem with npm itself
190 error network and is related to network connectivity.
190 error network In most cases you are behind a proxy or have bad network settings.
190 error network
190 error network If you are behind a proxy, please make sure that the
190 error network 'proxy' config is set properly.  See: 'npm help config'
191 verbose exit [ 1, true ]
192 verbose unbuild node_modules\grunt-cli
193 info preuninstall grunt-cli@0.1.13
194 info uninstall grunt-cli@0.1.13
195 verbose unbuild rmStuff grunt-cli@0.1.13 from C:\Users\I061951.GLOBAL\AppData\Roaming\npm\node_modules
196 verbose gentlyRm verifying that C:\Users\I061951.GLOBAL\AppData\Roaming\npm is managed by npm
197 silly isManaged C:\Users\I061951.GLOBAL\AppData\Roaming\npm is not inside C:\Users\I061951.GLOBAL\AppData\Roaming\npm\node_modules
198 silly isManaged C:\Users\I061951.GLOBAL\AppData\Roaming\npm is not inside C:\Users\I061951.GLOBAL\AppData\Roaming\npm\node_modules
199 silly isManaged C:\Users\I061951.GLOBAL\AppData\Roaming\npm is inside C:\Users\I061951.GLOBAL\AppData\Roaming\npm
200 silly gentlyRm C:\Users\I061951.GLOBAL\AppData\Roaming\npm is managed by npm
201 silly gentlyRm C:\Users\I061951.GLOBAL\AppData\Roaming\npm\grunt.cmd is under C:\Users\I061951.GLOBAL\AppData\Roaming\npm
202 verbose gentlyRm vacuuming C:\Users\I061951.GLOBAL\AppData\Roaming\npm\grunt.cmd up to C:\Users\I061951.GLOBAL\AppData\Roaming\npm
203 verbose gentlyRm verifying that C:\Users\I061951.GLOBAL\AppData\Roaming\npm is managed by npm
204 silly isManaged C:\Users\I061951.GLOBAL\AppData\Roaming\npm is not inside C:\Users\I061951.GLOBAL\AppData\Roaming\npm\node_modules
205 silly isManaged C:\Users\I061951.GLOBAL\AppData\Roaming\npm is not inside C:\Users\I061951.GLOBAL\AppData\Roaming\npm\node_modules
206 silly isManaged C:\Users\I061951.GLOBAL\AppData\Roaming\npm is inside C:\Users\I061951.GLOBAL\AppData\Roaming\npm
207 silly gentlyRm C:\Users\I061951.GLOBAL\AppData\Roaming\npm is managed by npm
208 silly gentlyRm C:\Users\I061951.GLOBAL\AppData\Roaming\npm\grunt is under C:\Users\I061951.GLOBAL\AppData\Roaming\npm
209 verbose gentlyRm vacuuming C:\Users\I061951.GLOBAL\AppData\Roaming\npm\grunt up to C:\Users\I061951.GLOBAL\AppData\Roaming\npm
210 info postuninstall grunt-cli@0.1.13
211 verbose gentlyRm vacuuming C:\Users\I061951.GLOBAL\AppData\Roaming\npm\node_modules\grunt-cli
212 silly gentlyRm purging C:\Users\I061951.GLOBAL\AppData\Roaming\npm\node_modules\grunt-cli
213 silly gentlyRm quitting because other entries in C:\Users\I061951.GLOBAL\AppData\Roaming\npm\node_modules

**Comment by KenanY** [comment]
@soumyarsap Then you need to configure `npm` to use your proxy. Relevant documentation:

  - [`proxy`](https://docs.npmjs.com/misc/config#proxy)
  - [`https-proxy`](https://docs.npmjs.com/misc/config#https-proxy)
  - [`cafile`](https://docs.npmjs.com/misc/config#cafile)

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
