### ISSUE TITLE
error wile installing phonegap through command

### ISSUE THREAD

**Issue by ghost** [npm/npm#7740]
hello sir,
i was installing phonegap through the command
```
C:\> npm install -g phonegap
```

but it did not completed successfully, and errors occurred.
please help me to install and run this service.

**Comment by KenanY** [comment]
@ankitbhagat11 I unfortunately cannot help unless I can see what error you are receiving. Could you upload the resulting `npm-debug.log` as a [gist](https://gist.github.com/)?

**Comment by ankitbhagat11** [comment]
I was trying to upload that log file. But ur message page just supporting
jpg and png file to upload.

**Comment by KenanY** [comment]
@ankitbhagat11 I'm a bit lost... you can totally upload logs to gist.github.com, [here's a log](https://gist.github.com/KenanY/0e752b46334bf9fb4bc4) I uploaded a couple of weeks ago as an example. Gist was created for uploading text content, where are you seeing anything about jpg and png?

**Comment by ankitbhagat11** [comment]
https://github.com/npm/npm/issues/new


i was trying to upload here, see the error in red.

**Comment by KenanY** [comment]
@ankitbhagat11 Oh, that page is for opening a new issue on this issue tracker. You don't want to open a new issue if this one already exists :) try uploading here: https://gist.github.com/

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
