### ISSUE TITLE
401 when attempting to publish

### ISSUE THREAD

**Issue by iarna** [npm/npm#7744]
@rimunroe is getting a 401 when attempting to publish a new version of `pipeline-routing`. 

>  hi, I just tried to publish a new version of my package, and I'm getting a 401 on the put request
>  I just tried logging in again, but no dice
>  I mean, it yields the same error when I try to push after running `npm login` again

https://gist.github.com/rimunroe/9b059766419e6da9ffed
```
[…]
36 verbose pkgid pipeline-routing
37 verbose cwd /Users/rimunroe/pipeline/pipeline-routing
38 error Darwin 14.1.0
39 error argv "node" "/usr/local/bin/npm" "publish"
40 error node v0.10.33
41 error npm  v2.7.0
42 error code E401
43 error Request was not authorized : pipeline-routing
44 error If you need help, you may report this error at:
44 error     <http://github.com/npm/npm/issues>
45 verbose exit [ 1, true ]
```

**Comment by bcoe** [comment]
@iarna, @rimunroe was a huge help and  just helped me hunt down a parsing problem in our new auth-plugin. We've patched it and fixed the publishing issue. It related to `:`, in BasicAuth passwords.

```patch
-              var decoded = new Buffer(auth.replace('Basic ', ''), 'base64').toString();
-              if (decoded.indexOf(':') === -1) throw Error('malformed token');
-              userPass = decoded.split(':');
+              var decoded = basicAuthParser(auth);
+              if (!decoded.username || !decoded.password) throw Error('malformed token');
+              userPass = [decoded.username, decoded.password];
```

**Comment by bcoe** [comment]
Worth mentioning, one of the benefits of the new registry architecture is that there will no longer be BasicAuth passwords!

**Comment by rimunroe** [comment]
Thanks!
