### ISSUE TITLE
can't install stylus ERR 0-byte tarball

### ISSUE THREAD

**Issue by pola04** [npm/npm#7745]
hi, im trying to install stylus, on a Macbook OS X Yosemite v. 10.10.2;  but this is what's happening: 

npm ERR! tar.unpack error reading /Users/PolaNino/stylus
npm ERR! addLocal Could not install /Users/PolaNino/stylus
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "stylus" "-g"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! 0-byte tarball
npm ERR! Please run `npm cache clean`
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

I tried with npm cache clean but at the end the same error is over and over.
thanks!

**Comment by KenanY** [comment]
@pola04 Is there a `stylus/` folder in your current directory? I think `npm` is trying to install that. Can you try `npm install -g stylus@latest` after cleaning the cache?

**Comment by pola04** [comment]
Yes, there is but it's empty, and this is what happends if I try  "npm install -g stylus@latest": 
npm ERR! tar.unpack untar error /Users/PolaNino/.npm/stylus/0.50.0/package.tgz
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "stylus@latest"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! path /usr/local/lib/node_modules/stylus
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, mkdir '/usr/local/lib/node_modules/stylus'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, mkdir '/usr/local/lib/node_modules/stylus']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/stylus',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/stylus',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53',
npm ERR!      'FSReqWrap.oncomplete (fs.js:99:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

:(

**Comment by KenanY** [comment]
```
npm ERR! Please try running this command again as root/Administrator.
```

@pola04 Looks like you'll need to use `sudo` since you don't have the necessary permissions to write to `/usr/local`

**Comment by pola04** [comment]
Thanks,  it seems like it installed stylus with "sudo npm install -g stylus@latest",
