### ISSUE TITLE
npm info <repo-name> isn't valid JSON

### ISSUE THREAD

**Issue by stefanpenner** [npm/npm#7747]
It is quite handy that many aspects of npm are in json, this allows easy tooling.

for example:

```
cat package.json | jq '.version'
> "1.5.1"
```

unfortunately, `npm info` is not currently emitting valid JSON. Specifically, the keys are not correctly quoted `"`

example to reproduce:

```
npm info npm | jq '.versions'
```

which unfortunately fails with `parse error: Invalid literal at line 2, column 7`, if npm info produced valid json, it would provide an array of all the versions:

```js
[ '1.1.25', ....]
```

**Comment by KenanY** [comment]
@stefanpenner https://docs.npmjs.com/cli/view#output

> If the --json flag is given, the outputted fields will be JSON.

**Comment by othiym23** [comment]
@KenanY has it. In general, if you want to take the output from npm and use it as input to other JavaScript tools, tack `--json` onto the command line. It doesn't work everywhere you might want it to, but it works more frequently than you might expect. (And we're open to taking more patches to add it where it's missing!)

**Comment by stefanpenner** [comment]
:+1:
