### ISSUE TITLE
grunt command line interface

### ISSUE THREAD

**Issue by biebergagabcbs** [npm/npm#7749]
I installed grunt in git by running. 

```
npm install -g grunt-cli

npm install -g grunt
```

I am trying to run grunt in git and this is the error message I am getting.

grunt-cli: the grunt command line interface 
               unable to find local grunt

**Comment by KenanY** [comment]
@biebergagabcbs 

```
unable to find local grunt
```

Did you install `grunt` _locally_? Perhaps `grunt`'s [getting-started](http://gruntjs.com/getting-started) page might help:

> Note that installing `grunt-cli` does not install the Grunt task runner! The job of the Grunt CLI is simple: run the version of Grunt which has been installed next to a `Gruntfile`. This allows multiple versions of Grunt to be installed on the same machine simultaneously.
>
> Each time `grunt` is run, it looks for a locally installed Grunt using node's `require()` system. Because of this, you can run `grunt` from any subfolder in your project.
>
> If a locally installed Grunt is found, the CLI loads the local installation of the Grunt library, applies the configuration from your `Gruntfile`, and executes any tasks you've requested for it to run. To really understand what is happening, read the code.

**Comment by biebergagabcbs** [comment]
I ran 'npm install grunt' again and it seemed to work. thanks a lot for your help.

**Comment by biebergagabcbs** [comment]
grunt is currently giving the following error messages.

Loading "gruntfile.coffee" tasks
TypeError: undefined is not a function
Task: default is not found

**Comment by KenanY** [comment]
@biebergagabcbs That doesn't look like an issue with `npm` to me. Perhaps an issue with your Gruntfile. Might want to ask StackOverflow or on grunt's IRC channel maybe.

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
