### ISSUE TITLE
error instalation glup

### ISSUE THREAD

**Issue by sidahmedbenkhaoua** [npm/npm#7754]
hi, ihave archlinux and i install glup and i find this error !
npm ERR! Linux 3.18.6-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "gulp"
npm ERR! node v0.12.0
npm ERR! npm  v2.7.1
npm ERR! file /root/.npm/minimatch/2.0.4/package/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! No data, empty input at 1:1
npm ERR! 
npm ERR! ^
npm ERR! File: /root/.npm/minimatch/2.0.4/package/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

**Comment by msikma** [comment]
As the error log states, this isn't an npm bug:

> npm ERR! This is not a bug in npm.
> npm ERR! Tell the package author to fix their package.json file. JSON.parse

It seems to be a bug in [minimatch](https://www.npmjs.com/package/minimatch), but I'm not sure why since their 2.0.4 package.json seems to be correct.

You should take it up with that package's author, or try to remove and reinstall it.

**Comment by KenanY** [comment]
@sidahmedbenkhaoua Could you try `npm cache clean`?

**Comment by sidahmedbenkhaoua** [comment]
@KenanY  same issue

**Comment by sidahmedbenkhaoua** [comment]
it work thks for all i change repertory to install
