### ISSUE TITLE
npm tag latest failing

### ISSUE THREAD

**Issue by damianavila** [npm/npm#7756]
I published a package yesterday with:
```
npm publish --tag <version>
```
And then I tried to make it the latest with:
```
npm tag bokehjs@0.8.2 latest                                                   
```

And I am getting this:
```
npm http PUT https://registry.npmjs.org/bokehjs/latest                                                                             
npm http 500 https://registry.npmjs.org/bokehjs/latest                                                                             
```

So, no update so far... when I see the https://registry.npmjs.org/bokehjs/, I see the 0.8.2, but it is labelled as the latest one?

Any idea why `npm tag bokehjs@0.8.2 latest` is failing?

npm -v
1.4.9

**Comment by bcoe** [comment]
@damianavila thanks for bringing this bug to our attention, if you try tagging a release now it _should just work :tm:_

**Comment by othiym23** [comment]
Closing as resolved (by the registry team).

**Comment by damianavila** [comment]
Thanks for fixing it... now 0.8.2 in there as the latest... :+1:

**Comment by damianavila** [comment]
Pinging here again... I did a new release:
```
(py27devel)[bokehjs](master) npm publish --tag 0.9.0
npm http PUT https://registry.npmjs.org/bokehjs
npm http 200 https://registry.npmjs.org/bokehjs
+ bokehjs@0.9.0
(py27devel)[bokehjs](master) npm tag bokehjs@0.9.0 latest
npm http PUT https://registry.npmjs.org/bokehjs/latest
npm http 201 https://registry.npmjs.org/bokehjs/latest
(py27devel)[bokehjs](master) npm show bokeh
npm http GET https://registry.npmjs.org/bokeh
npm http 200 https://registry.npmjs.org/bokeh
```

and it I do: 
```
(py27devel)[bokehjs](master) npm show bokehjs | grep latest
npm http GET https://registry.npmjs.org/bokehjs
npm http 304 https://registry.npmjs.org/bokehjs
   { latest: '0.9.0',
```

But the I go the the npm webpage... the last release is not appearing, just the previous 0.8.2 release...

**Comment by damianavila** [comment]
OK, now I can see the page correctly, it seems to be some latency in the update of the webpage.

Cheers.
