### ISSUE TITLE
npm view prints a string instead of a list when there is only one version

### ISSUE THREAD

**Issue by rightfold** [npm/npm#7757]
For packages with many versions, `npm view --json $package versions` prints a JSON array:

    $ npm view --json coffee-script versions | head                                                                   
    
    [
      "0.7.0",
      "0.7.1",
      "0.7.2",
      "0.9.0",
      "0.9.1",
      "0.9.2",
      "0.9.3",
      "0.9.4",

However, for packages with only a single version, `npm view --json $package versions` prints a JSON string:

    $ npm view --json node-test versions
    "0.0.1"

This special case (which is invented; single-version packages aren't special in any way) makes it difficult to parse the output of `npm view`.

**Comment by KenanY** [comment]
Consistency is nice. This is apparently an intentional thing, for neatness, perhaps. It extends beyond `versions`: any _Array_ whose length is `1` will be turned into a _String_, there's even a test for it (`maintainers` in this case):

``` js
t.similar(out, {
  maintainers: "jashkenas <jashkenas@gmail.com>"
}, "should have the same maintainer")
```

**Comment by KenanY** [comment]
@rightfold This is now (https://github.com/npm/npm/commit/7d55ee5522dc51fa8f205c822485d826abd18130) fixed in [npm/npm#multi-stage](https://github.com/npm/npm/tree/multi-stage) so you'll see this in `npm@3` :)

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
