### ISSUE TITLE
npm local installation failes

### ISSUE THREAD

**Issue by HknLof** [npm/npm#7761]
I have a project in it i have a node_modules directory and a package.json file. But npm still installs  (via ```npm install```)  it to the global prefix.

I run npm@1.4.28 on a Ubuntu Trusty

**Comment by KenanY** [comment]
@HknLof My first thought is that somehow you have `global` set to `true`?

``` sh
$ npm config get global
```

**Comment by HknLof** [comment]
Yepp, that was the issue, thanks.
