### ISSUE TITLE
Compressed packages

### ISSUE THREAD

**Issue by piranna** [npm/npm#7762]
I've [proposed a change](https://github.com/joyent/node/issues/14169) on Node.js require() to accept to use compressed packages on the modules resolution algorythm. The other part of the equation is npm :-) This would take a great advantage of the new [flat tree dependencies](https://github.com/npm/npm/issues/6912), since npm would store the compressed files directly on the ```node_modules``` folder instead of expand them, and only do it due to a conflict between dependencies versions.

**Comment by bmeck** [comment]
I defer my comments to the IO.js issue

**Comment by iarna** [comment]
If node.js / io.js to implement this change, I'm sure we'd be interested in looking at supporting this then. Until then, I'm going to close this issue as we're not going to implement something that Node can't use.

**Comment by piranna** [comment]
Well, at Node.js nobody has answered, but on io.js seems [it have got a lot of interest](https://github.com/iojs/io.js/issues/1278)... :-)
