### ISSUE TITLE
user "root" does not have permission to access the dev dir "/.node-gyp/0.12.1"

### ISSUE THREAD

**Issue by donaldpipowitch** [npm/npm#7764]
I try to install https://github.com/babel/babel globally, but encounter errors. I switched to an admin user with `$ su myAdminUser` and called `$ sudo npm install -g babel`. This throws the following error:

````
> fsevents@0.3.5 install /usr/local/lib/node_modules/babel/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/Users/myAdminUser/.node-gyp/0.12.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/babel/node_modules/chokidar/node_modules/fsevents/.node-gyp"
````

From similar issues like https://github.com/npm/npm/issues/2952 I added `--unsafe-perm`. I don't get any errors now, but it looks the the install process holds or waits endlessly after `> node-gyp rebuild`.

Using Max OS X 10.10.2, npm 2.7.3, Node 0.12.1.

**Comment by donaldpipowitch** [comment]
It looks like Babel was correctly installed, but I didn't get a success message.

**Comment by cliveb** [comment]
same here npm-debug-log 

0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--unsafe-perm',
1 verbose cli   '--verbose',
1 verbose cli   '-g' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 silly cache add args [ '.', null ]
5 verbose cache add spec .
6 silly cache add parsed spec { raw: '.',
6 silly cache add   scope: null,
6 silly cache add   name: null,
6 silly cache add   rawSpec: '.',
6 silly cache add   spec: '/Users/seebe',
6 silly cache add   type: 'local' }
7 error addLocal Could not install /Users/seebe
8 verbose stack Error: EISDIR, read
8 verbose stack     at Error (native)
9 verbose cwd /Users/seebe
10 error Darwin 13.4.0
11 error argv "node" "/usr/local/bin/npm" "install" "--unsafe-perm" "--verbose" "-g"
12 error node v0.12.2
13 error npm  v2.7.4
14 error code EISDIR
15 error errno -21
16 error EISDIR, read
17 error If you need help, you may report this error at:
17 error     <https://github.com/npm/npm/issues>
18 verbose exit [ -21, true ]

**Comment by KenanY** [comment]
@cliveb Your issue appears to be unrelated... the error message is completely different. From what I can tell, you are running `npm install -g` in a directory that does not contain a package. `npm` has absolutely no idea what you would like it to install unless you pass it arguments (like `npm install -g npm` or run `npm install` in a directory that contains a package.

If this does not solve your issue, please open a new issue and include the _full_ `npm-debug.log` as a [gist](https://gist.github.com/).

**Comment by othiym23** [comment]
This is an issue with `node-gyp` and should be dealt with there, although it seems to be having a tough time getting traction over there, for whatever reason.

**Comment by cliveb** [comment]
@KenanY @othiym23 thanks. I have added an issue on node-gyp https://github.com/TooTallNate/node-gyp/issues/608

**Comment by nitinreddy3** [comment]
gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/nitin/.node-gyp/0.10.37"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/devtools-terminal/node_modules/pty.js/.node-gyp"


Seems I am also getting the same issue when I am trying to install Chrome's terminal dev-tools

**Comment by MaxSmile** [comment]
The same here... it is a pity, the tool was looking promising...

**Comment by aliquid** [comment]
```
cd /usr/lib/node_modules # or /usr/local/lib/node_modules
ls -l                    # look for owner nobody (or any non-root owner)
chown -R root xyzzy1     # replace xyzzy with whatever from above
cd xyzzy1                # replace xyzzy with whatever from above
npm install              # will rebuild the needful
cd ../xyzzyN             # rinse and repeat
```

**Comment by aliquid** [comment]
See also https://github.com/nodejs/node-gyp/issues/454

**Comment by pei-han** [comment]
npm i -g node-inspector --unsafe-perm
