### ISSUE TITLE
gnutls_handshake() failed: A TLS packet with unexpected length was received

### ISSUE THREAD

**Issue by kmalakoff** [npm/npm#7765]
We are using npm@2.7.3 and seem to be encountering issues installing our modules via git over HTTPS using basic auth on linux.

```
npm ERR! fatal: unable to access 'https://user:password@bitbucket.org/organization/project.git/': gnutls_handshake() failed: A TLS packet with unexpected length was received.
```

We first noticed it on Mar 23 and it is an intermittent problem that has had a few different error messages. 

We've got a support issue open with Atlassian and are trying the following: http://askubuntu.com/questions/186847/error-gnutls-handshake-falied-when-connecting-to-https-servers.

Was there a recent change in npm that changed the way a module referenced like "git+https://user:password@bitbucket.org/organization/project.git" is handled?

**Comment by kmalakoff** [comment]
Bitbucket got back to us confirming that gnutls is git is [known to be flaky](https://bitbucket.org/site/master/issue/9385/gnutls-recv-error-9-when-push-to-remote).

It looks like if we install using git in the terminal on our linux servers, there are no reliability problems, but when we install modules via npm, we get intermittent failures. Is npm using a version of git that is compiled using gnutls?

**Comment by KenanY** [comment]
@kmalakoff `npm` uses whatever `git` is in your `PATH`.

**Comment by kmalakoff** [comment]
@KenanY thank you for the information. Just looked at the path and `which git` gave us the same version of git we were comparing. Maybe it isn't a git version problem but something in how it is run?

**Comment by othiym23** [comment]
@kmalakoff The commands run by git are logged at `verbose` level, so you can be seen exactly what's being run (if not the complete runtime environment, which is sanitized by npm). Is it possible that you've got some proxy settings that might be getting in the mix in a bad way?

**Comment by kmalakoff** [comment]
We saw an article suggesting this, but our configuration hasn't changed recently so we didn't think this was the likely source of the problem.

We've found a workaround by rebuilding git with OpenSSL instead of the default gnutls, but still not sure on what changed to cause this problem.
