### ISSUE TITLE
RELEASE BLOCKER: fix broken tests  in multi-stage

### ISSUE THREAD

**Issue by iarna** [npm/npm#7774]
* [x] node test/run.js (107/107)

### npm-registry-couchapp
* [x] test/02-publish.js (33/35) - due to output format changes
* [x] test/03-star.js (5/10) - due to unicode detection

### general
* [x] test/tap/add-remote-git-fake-windows.js  -- hangs
* [x] test/tap/add-remote-git.js -- hangs
* [x] test/tap/builtin-config.js -- hangs
* [x] test/tap/cache-shasum-fork.js (8/10)
* [x] test/tap/circular-dep.js (6/7)
* [x] test/tap/config-meta.js (830/833)
* [x] test/tap/dedupe.js (5/6)
* [x] test/tap/false-name.js (2/3)
* [x] test/tap/gently-rm-overeager.js (3/4)
* [x] test/tap/gently-rm-symlink.js (8/10)
* [x] test/tap/ignore-install-link.js (1/2)
* [x] test/tap/ignore-shrinkwrap.js (1/2)
* [x] test/tap/install-bad-man.js (5/7)
* [x] test/tap/install-man.js (3/6)
* [x] test/tap/install-save-local.js (6/8)
* [x] test/tap/install-save-prefix.js (13/17)
* [x] test/tap/install-with-dev-dep-duplicate.js (1/1)
* [x] test/tap/optional-metadep-rollback-collision.js (3/5)
* [x] test/tap/repo.js (12/13)
* [x] test/tap/shrinkwrap-dev-dependency.js (0/1)
* [x] test/tap/shrinkwrap-local-dependency.js (3/5) _from looks different now, possibly bogus
* [x] test/tap/shrinkwrap-scoped-auth.js (4/5)
* [x] test/tap/uninstall-package.js (4/6) seems like an api change?
* [x] test/tap/unpack-foreign-tarball.js (3/5)
* [x] test/tap/update-save.js (21/26)
* [x] test/tap/url-dependencies.js (7/8)
* [x] test/tap/shrinkwrap-shared-dev-dependency.js (0/1) legit broken
* [x] test/tap/logout.js -- (1/3) I have no idea how this is related?

### api change that probably should be paved over
* [x] test/tap/outdated-depth-integer.js (0/1)
* [x] test/tap/outdated-long.js (3/4)
* [x] test/tap/outdated.js (3/4)

### peer deps were broken on purpose
* [x] test/tap/peer-deps-invalid.js (1/2)
* [x] test/tap/peer-deps-toplevel.js (4/5)
* [x] test/tap/peer-deps-without-package-json.js (1/4)
* [x] test/tap/peer-deps.js (0/1)

**Comment by johannestroeger** [comment]
awesome :+1:
