### ISSUE TITLE
Can we have multiple gyp files for C++ module?

### ISSUE THREAD

**Issue by am11** [npm/npm#7780]
Over at node-sass, we added a gyp file `libsass.gyp` in addition to existing `binding.gyp`, in order to unbundle libsass and provision static linking. Related PR: https://github.com/sass/node-sass/pull/763.

When I published the package (node-sass@v3.0.0-beta.2), with `binding.gyp` and `libsass.gyp` ([package.json#L34-L36](https://github.com/sass/node-sass/blob/v3.0.0-beta.2/package.json#L34-L36)), the subsequent installations showed a funny behavior; the contents of `binding.gyp` was ignored and replaced by the contents of `libsass.gyp`, while the contents of `libsass.gyp` were gone. The result was only libsass.gyp sources were compiled, leaving behind our binding source files. So I had to revert it back and unified the gyp setup into `binding.gyp` file. Now node-sass@v3.0.0-beta.4 is working as expected, while we lost the ability to have libsass as unbundled library: https://github.com/sass/node-sass/pull/809. 

I couldn't find any reference where multiple gyp files are used in npm.

Is it allowed? If it is; is there anything we need to modify in our code (https://github.com/sass/node-sass/pull/763) to incorporate the intended design?

**Comment by smikes** [comment]
Sounds like a bug to me.

When I look at the pack file for v3.0.0-beta.2, I see this:

```
Svarog:foo smikes$ npm pack node-sass@v3.0.0-beta.2
Svarog:foo smikes$ tar tzf node-sass-3.0.0-beta.2.tgz  | grep gyp
package/binding.gyp
package/binding.gyp
```

It looks like something renamed your second gyp file to `binding.gyp`.

**Comment by smikes** [comment]
Yup, this is a `feature` of fstream-npm:

```
// all *.gyp files are renamed to binding.gyp for node-gyp
// but only when they are in the same folder as a package.json file.
node_modules//fstream-npm/fstream-npm.js:    entry.basename = 'binding.gyp'
```

As a workaround, you could put your second gyp file in another directory while we sort this out on the `npm` side.  Fixing this involves adding state to `fstream-npm` such that a `gyp` file is not renamed to `binding.gyp` if `binding.gyp` is already present, so it's a simple fix, but not trivial.

**Comment by am11** [comment]
@smikes, thanks for diagnosing the root cause. I have added `libsass.gyp` in a separate directory. Hopefully it will be fixed in `fstream-npm` as well. :)

**Comment by smikes** [comment]
Just making a note here that if/when the node extension build system changes away from gyp, this mistake of renaming '*.gyp' to 'binding.gyp' should not be recapitulated.

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.

**Comment by anvaka** [comment]
It is still happening in npm v3.8.6, and looking at mainline code the bug is still there. 

You can reproduce it by:
1. run `npm init`
2. create file `foo.gyp` in the same folder with `package.json`
3. run `npm publish`

You will notice that `foo.gyp` will be renamed to `binding.gyp`.
