### ISSUE TITLE
npm ERR! Error: UNKNOWN, symlink '../coffee-script/bin/coffee'

### ISSUE THREAD

**Issue by mgiallu** [npm/npm#7783]
Hi,

I installed the open edx as described in the http://edx.readthedocs.org/projects/edx-installing-configuring-and-running/en/latest/devstack/install_devstack.html 

Here is what I get running the following commands...
Does somebody knows what is this issue ??

```
vagrant@precise64:~$ sudo su edxapp
edxapp@precise64:~/edx-platform$ paver devstack studio
---> pavelib.servers.devstack
---> pavelib.prereqs.install_prereqs
---> pavelib.prereqs.install_ruby_prereqs
Ruby prereqs unchanged, skipping...
---> pavelib.prereqs.install_node_prereqs
test `npm config get registry` = "http://registry.npmjs.org/" || (echo setting registry; npm config set registry http://registry.npmjs.org/)
npm install
npm WARN package.json edx@0.1.0 No repository field.
npm ERR! Error: UNKNOWN, symlink '../coffee-script/bin/coffee'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.2.0-23-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /edx/app/edxapp/edx-platform
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! path ../coffee-script/bin/coffee
npm ERR! code UNKNOWN
npm ERR! errno -1
npm ERR! not ok code 0


Captured Task Output:
---------------------

---> pavelib.servers.devstack
---> pavelib.prereqs.install_prereqs
---> pavelib.prereqs.install_ruby_prereqs
---> pavelib.prereqs.install_node_prereqs
test `npm config get registry` = "http://registry.npmjs.org/" || (echo setting registry; npm config set registry http://registry.npmjs.org/)
npm install
```

Build failed running pavelib.servers.devstack: Subprocess return code: 255

Regards.
ALain.

**Comment by mapmeld** [comment]
It sounds like you are missing the coffeescript module. Try running ```npm install coffee-script```

**Comment by mgiallu** [comment]
Hi, thanks for your reply but running the instqll did'nt change anything.....
Regards.
Alain.

**Comment by melarish** [comment]
If you're on Windows, try npm install coffee-script --no-bin-links

http://askubuntu.com/questions/269727/npm-errors-when-installing-packages-on-windows-share

**Comment by kmanion** [comment]
Hi @mgiallu , it looks like you've gotten some help with this issue. We're trying to close out some of the older support issues. Please don't hesitate to reopen if you are still running into this or email us at support@npmjs.com

Kiera, npm technical support
