### ISSUE TITLE
Usage of NPM for Non-NodeJS projects? 

### ISSUE THREAD

**Issue by youssefdetovernickr** [npm/npm#7785]
I was wondering if I should use npm for projects that don't need NodeJS. I can't really see any negative effects. 

I basically want to create a custom private package with an executable file and some data in it, and version it, and then use it for npm. Should I use npm or an other package manager (which I can't really find at all, except composer)

**Comment by smikes** [comment]
Sure, feel free!

I use `npm` for C/C++ unit test suites, which are not directly related to node.

**Comment by iarna** [comment]
Closing as answered.
