### ISSUE TITLE
Using npm update with custom private folder-based packages?

### ISSUE THREAD

**Issue by youssefdetovernickr** [npm/npm#7786]
Is this possible, because I currently have to specify the exact folder name for the package for each version. I can't find a possibility to make an one single named package where I can do NPM update.

**Comment by smikes** [comment]
No, `npm` only uses the version in `package.json` when installing from a registry.  But you can run your own version of the `npm` registry; see https://github.com/rlidwka/sinopia

**Comment by iarna** [comment]
Closing as answered.
