### ISSUE TITLE
npm Illegal instruction on Raspberry Pi B+

### ISSUE THREAD

**Issue by nathanjohnson320** [npm/npm#7789]
Compiled node v0.12.1 on my Raspberry Pi B+ and can run node commands (node -v, cli) but whenever I do an npm command (npm install, npm -v) it says "Illegal Instruction" and exits. Previous times I compiled I would get the Illegal Instruction error but only for npm -v, npm install would still work and I didn't report it as an issue but now it always throws this error.

See joyent/node#14186

**Comment by rlidwka** [comment]
Fixed in io.js a month ago, see https://github.com/iojs/io.js/issues/283.

**Comment by nathanjohnson320** [comment]
Uhg, I thought they merged the pull request to fix it in node but apparently it's still in PR limbo. Thanks for pointing me in the right direction.

**Comment by smikes** [comment]
Thanks for reporting this issue.  Unfortunately `npm` can't prevent an illegal instruction error caused by a bug in `node` or `iojs`.  Are you able to work around this by using a different version?
