### ISSUE TITLE
npm@3: global install fails with EISGIT if npm link has been used to make WIP modules globally available

### ISSUE THREAD

**Issue by seldo** [npm/npm#7790]
Full npm-debug:
https://gist.github.com/seldo/256d659e7b34632bafc8

If was attempting to install nvm in this case, but installing anything globally appears to fail the same way: the installer runs into `pnp`, one of my own modules that I have made globally available locally using `npm link`, and fails because it is a git repo and it is trying to move everything around to be flat and tidy.

Feels like this behaviour should simply be prevented when doing a global install.

**Comment by iarna** [comment]
Actually I think it probably shouldn't be walking into linked modules.

**Comment by iarna** [comment]
Closing this as fixed in [npm/npm#multi-stage](https://github.com/npm/npm/tree/multi-stage)
