### ISSUE TITLE
How to prevent  test codes, examples duing module  installation  dependencies using npm install

### ISSUE THREAD

**Issue by vgupta** [npm/npm#7792]
Hi,

When i am installing any dependency using npm install 'module name', then this command installing module with examples and test code. This is increasing our project size. 

how can i provent this?

**Comment by aredridel** [comment]
That's not generally considered a problem by most people -- there is no way for a dependency to say that some files are or are not required for operation in some cases.

Is the increased project size a problem?

**Comment by smikes** [comment]
@vgupta - if you control the dependency, then you can choose what gets installed via `npm` by listing files you wish to exclude in `.npmignore`, or by listing files you wish to include in the `files` field of `package.json`.

If you don't control the dependency, you have a lot less choice here.  You may wish to make sure that you're not installing your development dependencies in your production tree -- if you are, it can take an enormous amount of space.

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
