### ISSUE TITLE
Unable to install Karma using  npm install -g karma windows 7 using command prompt

### ISSUE THREAD

**Issue by 245449** [npm/npm#7793]
Hi All,

I have installed nodejs using windows installer and trying to install karma using command prompt `npm install -g karma`. but got below issues. Please help. 

```
C:\Windows\System32>npm install -g karma
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "karma"
npm ERR! node v0.12.1
npm ERR! npm  v2.5.1
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! syscall getaddrinfo

npm ERR! network getaddrinfo ENOTFOUND kcsh01
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\System32\npm-debug.log
```
Thanks
Chandrakant

**Comment by smikes** [comment]
It looks like you need to tell `npm` how to get through your Windows proxy.  See http://superuser.com/questions/347476/how-to-install-npm-behind-authentication-proxy-on-windows and http://stackoverflow.com/questions/18569054/npm-behind-ntlm-proxy for possible approaches.

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
