### ISSUE TITLE
error 404 Not Found: vs-mda

### ISSUE THREAD

**Issue by majkelo** [npm/npm#7794]
I can not install vs-mda or vs-mda-target. Please help!

    28 verbose cwd C:\Users\admin\Documents\test
    29 error Windows_NT 6.3.9600
    30 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "-g" "install" "vs-mda"
    31 error node v0.12.0
    32 error npm  v2.5.1
    33 error code E404
    34 error 404 Not Found: vs-mda
    34 error 404
    34 error 404 'vs-mda' is not in the npm registry.
    34 error 404 You should bug the author to publish it (or use the name yourself!)
    34 error 404
    34 error 404 Note that you can also install from a
    34 error 404 tarball, folder, http url, or git url.
    35 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@majkelo As the error message states, `vs-mda` is not a package in the registry... you cannot install what does not exist.

**Comment by majkelo** [comment]
@KenanY so how could I find it and add to registry? it is required to open project:
https://github.com/andijakl/ndef-nfc/tree/master/NdefDemoJS

**Comment by KenanY** [comment]
@majkelo From [this page](https://msdn.microsoft.com/en-us/library/dn757054.aspx#vsmda), it looks like `vs-mda` comes with Visual Studio... or Apache Cordova... I can't really tell. Sorry I can't help more, I'm proficient with `npm` issues not this stuff :)

**Comment by majkelo** [comment]
@KenanY Ok. Thanks for your help! :)
