### ISSUE TITLE
npm --save -dev builds the world

### ISSUE THREAD

**Issue by Ralt** [npm/npm#7795]
A simple typo (`-dev` on its own) caused someone to [build the world](http://stackoverflow.com/questions/29343691/npm-install-is-building-the-world).

**Comment by KenanY** [comment]
But that's what [`dev`](https://docs.npmjs.com/misc/config#dev) is intended to do: install `devDependencies` along with the packages.

**Comment by xbenjii** [comment]
@KenanY nearly 3 gigs worth?

**Comment by KenanY** [comment]
My bad, this is indeed a footgun. It'll be deprecated soon: https://github.com/npm/npm/issues/6200

**Comment by iarna** [comment]
Closing as duplicate-ish of #6200.
