### ISSUE TITLE
document logging when using npm programmatically

### ISSUE THREAD

**Issue by lookfirst** [npm/npm#7798]
https://github.com/npm/npm#using-npm-programmatically

```
  npm.registry.log.on("log", function (message) { .... })
```

It seems that `npm.registry` no longer exists, what is the replacement?

I'd also like to see some documentation on how to insert my own logger or at least better control the npm one. I use winston and would like to log through that instead.

**Comment by othiym23** [comment]
`npm.registry` is the registry client, and it absolutely should be there after the call to `npm.load`, which bootstraps npm's internals. `npm.registry.log` is passed into the `npm-registry-client` instance at `npm.load()` time, when the registry client is instantiated, and is the same thing you'd get if you called `require('npmlog')` from inside the code using the npm API. If you _have_ called `npm.load()` and `npm registry.log` isn't there, that's a bug. That code example should work as-is.

There is no reasonable way to swap out `npmlog` for another logging framework right now. As the name indicates, it's pretty much baked into npm at a very low level. And, as I mentioned on #7800, the API is kind of the Wild West. If you want documentation on how to use `npmlog` as a passthrough for another logger (which should be possible), you'll need to read [its documentation](https://www.npmjs.com/package/npmlog) for the details.

**Comment by lookfirst** [comment]
I stand corrected, I just tested the code again and it was fine. Sorry about that.
