### ISSUE TITLE
npm install problem

### ISSUE THREAD

**Issue by alexandarp** [npm/npm#7801]
Hello everyone,

I am running ```npm v2.7.4``` on my Jenkins build server. Whenever a build is in progress, it will fail at the ```npm install``` step and output the following:

```
npm ERR! cb() never called!
npm ERR! not ok code 0
```
However, when I downgrade ```npm``` to ```v2.7.3```, the build succeeds. Is anyone else experiencing this error? I would like to know the reason behind this. 

I am also running ```node v0.10.36```.

**Comment by KenanY** [comment]
@alexandarp `cb() never called!` pretty much always means this is a bug in `npm`, but more context is necessary. Could you run with a higher loglevel (like `--loglevel silly`)? _Maybe_ provide the relevant pieces of the `package.json` (dependencies)?

**Comment by KenanY** [comment]
@alexandarp ping? :)

**Comment by alexandarp** [comment]
@KenanY The ```--loglevel silly``` didn't output any relevant information. I suspect that this problem is related to private git repositories. I ended up updating ```npm``` to ```v2.8.3``` and the problem didn't occur again.
