### ISSUE TITLE
npm install express

### ISSUE THREAD

**Issue by wj704** [npm/npm#7808]
hi ,all:
I am running npm install -g express, it will fail at the npm install step and output the following:
```
npm ERR! 
```
this is the npm-debug.log

**Comment by KenanY** [comment]
@wj704 Could you upload the log as a [gist](https://gist.github.com/)?

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
