### ISSUE TITLE
npm init `scope` flag doesn't think @ is part of the scope

### ISSUE THREAD

**Issue by zeke** [npm/npm#7810]
@othiym23 wants `@` to be part of the scope name. Here's an instance of that not being the case:

```
Desktop* master » mkdir stuff && cd stuff

stuff* master » npm init --scope=@zeke
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sane defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg> --save` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
name: (@@zeke/stuff)
```

**Comment by othiym23** [comment]
Hmm... definitely a bug (probably in `npm-init-scope`) – when running `npm login`, it assumes the `@` is there and only adds it if it's missing (as a convenience).

**Comment by watilde** [comment]
I had overlooked how other feature like `npm login` have a scope option.. I tried to fix it as commented @othiym23. Here is the PR: https://github.com/npm/init-package-json/pull/33

**Comment by zeke** [comment]
thanks @watilde!
