### ISSUE TITLE
Version ranges ignore valid versions that have "prerelease" flags

### ISSUE THREAD

**Issue by sh1mmer** [npm/npm#7811]
I just checked and this works in npm 1.4.3 I haven't found a version since 2.0.0 that works with this though.

```
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/Users/sh1mmer/.nvm/v0.10.32/bin/npm" "i" "riak-client"
npm ERR! node v0.10.32
npm ERR! npm  v2.7.4
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: re@'>=0.1.1 <0.2.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.0.8-2","0.0.8-3","0.1.1-4","0.0.2-1","0.0.1-5","0.1.0-0","0.0.1-7","0.0.1-6","0.1.1-0","0.1.1-1","0.1.1-2","0.0.1-2","0.0.1-1","0.0.1-3","0.1.1-3","0.1.1-5","0.0.6-2","0.0.6-3","0.0.6-1","0.0.6-6","0.0.6-7","0.0.6-4","0.0.6-5","0.0.1-4","0.0.7-1"]
```

The including package.json specifies:
`"re": "^0.1.1",`

As you can see above the author of `re` only seems to publish versions with pre-release tags which is a little bit confusing to me, but who knows.

**Comment by sh1mmer** [comment]
cc @rrix @u-snuggie

**Comment by othiym23** [comment]
This is absolutely by design, and is _the_ primary changes from `semver@2` to `semver@4` – see https://github.com/npm/npm/issues/6997#issuecomment-68006017 for details.

**Comment by sh1mmer** [comment]
Somehow I missed this. Thanks for the quick response.

**Comment by lxe** [comment]
Although this change makes sense (>=1.0.0 < 2.0.0 will no longer match 2.0.0-prereleases), it breaks packages dependency chains of some archaic packages currently published to npm.

**Comment by lxe** [comment]
Although this change makes sense (>=1.0.0 < 2.0.0 will no longer match 2.0.0-prereleases), it breaks packages dependency chains of some archaic packages currently published to npm.

**Comment by othiym23** [comment]
@lxe Those packages really should be updated (and most of them have been over the last six months). Depending on prerelease versions is in many ways more brittle than depending on git repos, and while this change has caused some pain, I now believe that it is better for everybody if we force package consumers to explicitly pin dependencies on prerelease versions.
