### ISSUE TITLE
RE: npm install -g serialport

### ISSUE THREAD

**Issue by silver2row** [npm/npm#7817]
Hello,

I am working out of a book as of now. Christopher Rush is the author. I have Angstrom on my Beaglebone Black. I tried to pick up npm install -g serialport to add a GPS breakout board. 

Are there any remedies to this issue as of now?

Sincerely,

Seth

**Comment by silver2row** [comment]
Hello Again,

I forgot to mention that I get an ERR code instead of success.

Sincerely,

Seth

**Comment by KenanY** [comment]
@silver2row ...what error? As this stands there's no information for me to go on. Is a `npm-debug.log` generated? Could you upload it as [gist](https://gist.github.com)? Node.js version? `npm` version?

**Comment by silver2row** [comment]
Hello...

I will get you the ERR code soon. I am sorry it is taking me so long. I will re-enter the information and then get the ERR code. I will post it soon. I am sorry for the delay.

Sincerely,

Seth

**Comment by silver2row** [comment]
This may be what you are looking for: npm@1.2.14 usr/lib/node_modules/npm
                                                                        npm ERR! not ok code 0

**Comment by KenanY** [comment]
@silver2row Are those the last two lines of the output...? Can I see the _entire_ output? An `npm-debug.log` should be generated; you can upload it to [gist.github.com](https://gist.github.com/).

In addition, if you are indeed running `npm@1.2.14`:

```
$ git show v1.2.14
tag v1.2.14
Tagger: isaacs <i@izs.me>
Date:   Sat Mar 9 08:39:43 2013 -0800
```

It's just over 2 years old :) I highly recommend you update both [Node.js](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-node) and [`npm`](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm).

**Comment by silver2row** [comment]
Hello again...

I got that Gists thing to you. You can view it now...

Sincerely,

Seth

**Comment by KenanY** [comment]
For reference: https://gist.github.com/silver2row/c2d722669fd43ad666dc

Looks like an internet connection issue to me? I still recommend upgrading since `npm@1.2` is no longer supported (we are on `2.7` at the moment).

**Comment by silver2row** [comment]
Hello,

I got too many issues to keep you. I will have to keep on reading. My npm (1.2.14) is out of date like stated. I tried to update by updating via npm install -g npm@latest. I got more error codes.

Sincerely,

Seth

**Comment by silver2row** [comment]
Hello,

Do you think it could be the Version of Angstrom I am using, i.e. instead of Debian and the newer, upgraded version of the BBB?

Sincerely,

Seth

**Comment by silver2row** [comment]
Oh...Internet connection. Maybe since I am using the BBB via USB to computer over WIFI, I am getting a poor signal. 

Sincerely,

Seth

**Comment by silver2row** [comment]
Hello Again,

Okay...I just tried my Ubuntu BBB on the script for npm install -g serialport. It worked. I think npm was out of date and my configuration on the Angstrom BBB could not update. That is all...

Oh and if you have any info. on "30 BBB Projects for the Evil Genius," please let me know. I am on project 10 and I cannot read the schematic. The fritzing.org schematic is too dark and not viewable. 

Enjoy...

Seth

**Comment by ehsalazar** [comment]
Good to hear. I'll close this for now as we’re trying to clean up some old issues. We’ll be happy to reopen if necessary.
