### ISSUE TITLE
feature request: support for `npm version --no-git` option to not auto git tag

### ISSUE THREAD

**Issue by HenrikJoreteg** [npm/npm#7819]
Many times, especially in front-end JS projects, it's nice to be able to write the version into the JS in the built files as part of a release process. 

We do this for all the [ampersand.js](http://ampersandjs.com/) modules, for example. Then in a browser console you can quickly check what versions of everything you're running (screenshot here: https://cloudup.com/ce4Id4raIW4)

I want the version in `package.json` to be the authoritative version number, and then as part of a build script (using `scripts` section of package), i want to be able to `npm version --no-git` because I'm going to do write in the resulting version into a file first, and *then* create the git tag.

Right now, if git exists, it just does it. I think that's a sensible default, but I'd love the option to make that optional.

<3

**Comment by othiym23** [comment]
[`npm version --no-git-tag-version`](https://docs.npmjs.com/misc/config#git-tag-version) 💞

**Comment by HenrikJoreteg** [comment]
Well I feel sheepish, thanks Forrest :)
