### ISSUE TITLE
ERROR npm appnium

### ISSUE THREAD

**Issue by gxll** [npm/npm#7821]
help，when i install appnium，it tell me something errors，but i don't kown how to fix this

sorry,i don't know how to upload the debug error log to git,please see next pics

![ew_yse rw sod v vee x](https://cloud.githubusercontent.com/assets/11489593/6937774/a8205290-d890-11e4-83fa-2713fe977c07.jpg)

![6 kcm 5llqfht2 k3ksq23i](https://cloud.githubusercontent.com/assets/11489593/6937776/adfda3fc-d890-11e4-830e-bee4b72ad719.jpg)

![l3xe k3zx28mj i 0m7](https://cloud.githubusercontent.com/assets/11489593/6937778/b38e4fc4-d890-11e4-8bcc-610b2a91a678.jpg)

**Comment by smikes** [comment]
Thanks for the bug report.  You can upload the whole npm-debug.log at <https://gist.github.com> and then attach a link to the uploaded file here in this issue.

It looks to me like Visual Studio is emitting a localized error message about the `"/m"` option.  Can you tell me what the error text above `MSBUILD: error MSB6006` says?

**Comment by gxll** [comment]
hello smikes,I already add the npm-debug.log,you can visit this link to look:https://gist.github.com/gxll/109a68f6e1b587d74638#file-gistfile1-txt

about the 'MSBUILD: error MSB6006',i reboot my windows,so above of the logs can't see.if i meeting this again,i will add the image

thank you very much

**Comment by smikes** [comment]
Thanks.

It looks like part of the problem may be related to recent changes involving `git` support:

```
26736 verbose request uri http://registry.npmjs.org/through2
26737 verbose request no auth needed
26738 info attempt registry request try #1 at 16:17:54
26739 verbose etag "BOIIDAW4DV0RHV8PO93FIO8TI"
26740 http request GET http://registry.npmjs.org/through2
26741 verbose type non_object_property_call
26742 verbose stack TypeError: Cannot call method 'trim' of undefined
26742 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\cache\add-remote-git.js:98:32
26742 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\utils\git.js:50:14
26742 verbose stack     at F (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:40:25)
26742 verbose stack     at E (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:43:29)
26742 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:54:16
26742 verbose stack     at Object.oncomplete (fs.js:107:15)
26743 verbose cwd E:\adt_bundle_adb
26744 error Windows_NT 6.1.7600
26745 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "appium"
26746 error node v0.10.31
26747 error npm  v2.7.4
26748 error Cannot call method 'trim' of undefined
26749 error If you need help, you may report this error at:
26749 error     <https://github.com/npm/npm/issues>
26750 verbose exit [ 1, true ]
```

**Comment by iarna** [comment]
We've updated git support a few more times: Can you try again with `npm@2.8.0`

**Comment by smikes** [comment]
@gxll, can you try updating your `npm` to 2.8.3 (see the guide here:  https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows ) and let us know if the problem persists with current versions of npm?  As Rebecca (@iarna) says, the git support has recently been improved.

**Comment by smikes** [comment]
Is this still a problem for you?

There have been a lot of improvements to npm -- especially involving git dependencies -- since 2.7. Can you try updating your npm installation?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved / abandoned.
