### ISSUE TITLE
Certificate not trusted

### ISSUE THREAD

**Issue by sachinkadam99** [npm/npm#7822]

**Comment by KenanY** [comment]
@sachinkadam99 Could you please provide more information on what you are reporting here?

https://github.com/npm/npm/wiki/Contributing-Guidelines#a-great-bug-report-contains

**Comment by mayestrum** [comment]
I guess @sachinkadam99 had the problem that the certificate on https://npmjs.com does not match the certificate subject name, this was reported also here: https://github.com/npm/npm/issues/7818

Through the fix in the noted issue does not work:

CentOS 5.11:
[2015-04-11 11:36:21] app$ curl -L https://www.npmjs.com/install.sh
curl: (51) SSL: certificate subject name 'a.sni.fastly.net' does not match target host name 'www.npmjs.com'

**Comment by smikes** [comment]
Is this still a problem for you?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by wholehogsoftware** [comment]
+1

**Comment by othiym23** [comment]
Closing as resolved / abandoned.
