### ISSUE TITLE
Cannot publish a package which was unpublished recently by another user

### ISSUE THREAD

**Issue by IonicaBizau** [npm/npm#7823]
Scenario:

 1. Alice unpublished the `foo` package.
 2. Bob tries to publish his package `foo` since it's available.

The following error appears:

```sh
$ npm publish
npm http request PUT https://registry.npmjs.org/foo
npm http 401 https://registry.npmjs.org/foo
npm ERR! publish Failed PUT 401
npm ERR! Linux 3.19.0-10-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "publish"
npm ERR! node v0.12.1
npm ERR! npm  v2.5.1
npm ERR! code E401

npm ERR! Request was not authorized : foo
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ionicabizau/Documents/foo/npm-debug.log
```

I'm in the Bob's role. What I have tried is:

 - changed my password on NPM
 - authenticated again using `npm adduser`

Still the same error. Is there any solution/workaround?

**Comment by smikes** [comment]
Can you tell me specifically which package name you are trying to claim?

Because `npm` doesn't allow re-publishing a package with the same version number, you would be safest in choosing a starting version number much larger than the last `foo` version of Alice's.

Finally, if you continue to see problems with this, you should follow the Dispute Resolution process <https://docs.npmjs.com/misc/disputes>, specifically, email to support@npmjs.com

**Comment by IonicaBizau** [comment]
@smikes The package name is `pi` (I hope nobody will publish it before me). :smile: 

The version should not be a problem because the error is different.

**Comment by smikes** [comment]
Are you logged in to the `npm` registry?  What is the result of `npm whoami` ?

**Comment by IonicaBizau** [comment]
@smikes Yes, I am.

```sh
$ npm whoami
ionicabizau
```

**Comment by smikes** [comment]
I think your next step should be to email support@npmjs.com -- that's the
best way to reach the backend people.  I can't think of a reason why it
should fail, and I don't want to mess with the database by testing it
myself.

**Comment by IonicaBizau** [comment]
@smikes Sent an email. Keeping this issue open until the problem is fixed. Thanks! :+1:

**Comment by ZigGreen** [comment]
+1 
same error

**Comment by bcoe** [comment]
I've created a ticket to fix this issue, it relates to the new access-control-logic we're applying for package ownership.

In the meantime, to transfer ownership:

1. have the prior owner publish a point-release of the package.
2. have the prior owner add use as a collaborator `npm owner add foo`.
3. perform the `unpublish -f` yourself.
4. publish new versions of the package to your heart's content.

**Comment by bcoe** [comment]
@IonicaBizau, @ZigGreen this problem should now have been fixed in production. Let us know if you have any trouble publishing over a previously unpublished package.

**Comment by IonicaBizau** [comment]
@bcoe Thanks for updates, however I see no difference. Same errors appear when I'm trying to publish the `pi` package.

**Comment by bcoe** [comment]
@IonicaBizau sorry about that, give it one more go with a version # over 0.0.1.

**Comment by IonicaBizau** [comment]
@bcoe Awww, it worked! :smile: Thanks a lot! :cake:
