### ISSUE TITLE
Nmp start error

### ISSUE THREAD

**Issue by Abd3lk4d3r** [npm/npm#7827]
Hello i'm installing a script and when i want to run got this error

------------------------------------------------------------------------------------------
npm ERR! missing script: start
npm ERR! Linux 3.13.0-37-generic
npm ERR! argv "node" "/usr/bin/npm" "run" "start"
npm ERR! node v0.10.38
npm ERR! npm v2.7.4
npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR! <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR! /var/www/html/epochtalk-master/npm-debug.log 

------------------------------------------------------------------------------------------

What's the solution ??

**Comment by KenanY** [comment]
@Abd3lk4d3r 

```
npm ERR! missing script: start
```

Is there a `package.json` in your current working directory? Does it have a `"start"` script defined? Both need to exist in order for `npm` to know what you want it to do when you run `npm run start`. The documentation on [scripts](https://docs.npmjs.com/misc/scripts) and [`run-script`](https://docs.npmjs.com/cli/run-script) may help you.

**Comment by Abd3lk4d3r** [comment]
I'm installing this script : https://github.com/epochtalk/epochtalk 
 can you see if it contain errors ?

**Comment by KenanY** [comment]
@Abd3lk4d3r I've taken a look, and while I recognize that the `README` says to run `npm run start`, there is no `start` script in the `package.json`: https://github.com/epochtalk/epochtalk/blob/79c7b1824cd424fc7b84eb7ebd615eb86ae64ec9/package.json#L6-16

So, `npm` is doing the right thing here by erroring out as it is.

**Comment by Abd3lk4d3r** [comment]
Could you please show me how to fix it ? I'm on Skype : khalilnagi08 will be glad to receive help
from you .

Kind Of Respect .

**Comment by KenanY** [comment]
@Abd3lk4d3r Sorry, I have no idea how to use epochtalk. You should ask the developers of epochtalk instead of me, I'm only good for helping out with `npm` issues :)

**Comment by Abd3lk4d3r** [comment]
No problem Thanks ,

My repsepct .
