### ISSUE TITLE
Error when trying to "npm init"

### ISSUE THREAD

**Issue by Mizner** [npm/npm#7830]
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'init' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 silly package data undefined
5 info init written successfully
6 verbose stack Error: Invalid name: "Tuts Project"
6 verbose stack     at ensureValidName (/usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/fixer.js:322:15)
6 verbose stack     at Object.module.exports.fixNameField (/usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/fixer.js:211:5)
6 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/normalize.js:30:38
6 verbose stack     at Array.forEach (native)
6 verbose stack     at normalize (/usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/normalize.js:29:15)
6 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:368:33)
6 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:127:33)
6 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:317:48
6 verbose stack     at evalmachine.<anonymous>:263:20
6 verbose stack     at OpenReq.Req.done (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:141:5)
7 verbose cwd /Users/miz/Dropbox/Projects/Tuts Project
8 error Darwin 14.1.0
9 error argv "node" "/usr/local/bin/npm" "init"
10 error node v0.12.2
11 error npm  v2.7.4
12 error Invalid name: "Tuts Project"
13 error If you need help, you may report this error at:
13 error     <https://github.com/npm/npm/issues>
14 verbose exit [ 1, true ]
![screenshot 2015-04-02 00 38 15](https://cloud.githubusercontent.com/assets/2248154/6957851/983dd268-d8d0-11e4-9311-4b40786f6d16.png)

**Comment by Mizner** [comment]
...okay, so I designated a name and it seems to have worked?

**Comment by othiym23** [comment]
Packages can not have spaces in their names. They can include letters, numbers, dashes, and underscores, and that's about it, unless they're scoped packages, in which case they can start with `@` (to denote the name of the scope) and one `/`. The error message could stand to be friendlier (and it would be a good project to make `npm init` catch these errors before npm tries to create `package.json`), but this is [documented](https://docs.npmjs.com/files/package.json#name) – anything that would be escaped or encoded by `encodeURIComponent` won't be accepted by npm.
