### ISSUE TITLE
Unable to install cordova and add platform using npm command

### ISSUE THREAD

**Issue by meetrajatgupta** [npm/npm#7834]
Hi,

I am trying to install cordova (i am behind corporate proxy) but i am not able to do so. I am using command,

npm install -g cordova,

but getting following error

![message](https://cloud.githubusercontent.com/assets/4603151/6962647/f95b6424-d953-11e4-8756-5959a1f563b5.png)

**Comment by KenanY** [comment]
@meetrajatgupta Have you configured `npm` to use your proxy?

  - [`proxy`](https://docs.npmjs.com/misc/config#proxy)
  - [`https-proxy`](https://docs.npmjs.com/misc/config#https-proxy)
  - [`cafile`](https://docs.npmjs.com/misc/config#cafile)

**Comment by meetrajatgupta** [comment]
i have configured proxy and https-proxy but not cafile, can you help me in knowing how to set cafile proxy

**Comment by snopeks** [comment]
hi @meetrajatgupta we’re trying to clean up some issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary. Thanks! 
-Stephanie, npm Tech Support
