### ISSUE TITLE
npm 2.7.4 fails when installed with node 0.8.28

### ISSUE THREAD

**Issue by chorrell** [npm/npm#7836]
I hit this odd issue when trying to update the Docker node image (see docker-library/official-images/pull/630)

When I install npm 2.7.4 with node 0.8.28 under Debian Wheezy I get the following error when trying to use any npm command:

```
# npm -v

util.js:538
  ctor.prototype = Object.create(superCtor.prototype, {
                                          ^
TypeError: Cannot read property 'prototype' of undefined
    at Object.exports.inherits (util.js:538:43)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npmlog/node_modules/are-we-there-yet/index.js:115:6)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npmlog/log.js:2:16)
    at Module._compile (module.js:449:26)
```

Steps to reproduce:

**Install node 0.8.28**

```
gpg --keyserver pool.sks-keyservers.net --recv-keys 7937DFD2AB06298B2293C3187D33FF9D0246406D 114F43EE0176B71C7BC219DD50A3051F888C628D

NODE_VERSION=0.8.28

curl -SLO "http://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.gz"
curl -SLO "http://nodejs.org/dist/v$NODE_VERSION/SHASUMS256.txt.asc"
gpg --verify SHASUMS256.txt.asc
grep " node-v$NODE_VERSION-linux-x64.tar.gz\$" SHASUMS256.txt.asc | sha256sum -c -
tar -xzf "node-v$NODE_VERSION-linux-x64.tar.gz" -C /usr/local --strip-components=1
rm "node-v$NODE_VERSION-linux-x64.tar.gz" SHASUMS256.txt.asc
```

**Install npm (starting with 1.4.28 first)**
```
NPM_VERSION=2.7.4

export npm_config_loglevel=verbose
export npm_config_spin=false

npm install -g npm@1.4.28
npm install -g npm@${NPM_VERSION}
npm cache clear
```
The final command `npm cache clear` causes the error, but as noted above it happens with any npm command. The installation of 2.7.4 does successfully complete with `npm info ok `. I was not able to reproduce this with npm 2.7.3.

Here's a bash script I put together to reproduce:

https://gist.github.com/chorrell/f14d6141ad903a03af79

So far in my testing this happens on Debian Wheezy, Ubuntu 14.04, and CentOS 6.6. I have not tried this on OS X or SmartOS yet, but I this doesn't seem to be OS specific.

**Comment by KenanY** [comment]
I could very well be wrong, but I think this was fixed by https://github.com/iarna/are-we-there-yet/pull/2, although it won't be in a `npm` release until later today (https://github.com/npm/npm/commit/1f380f66c1e944b8ffbf096fa94d09e931626e12).

**Comment by othiym23** [comment]
This issue, at least, is fixed on `master`, but there are other `npm@npm/npm#master` tests failing under Node.js 0.8.28, and they're failing in such a way that indicates that not all is well with npm on 0.8: #7842. I'm closing this issue in favor of that one, but when I put out the new version of npm shortly, it should at least run under 0.8.

If at all possible, I'd strongly consider upgrading to at least Node.js 0.10. 0.10.38 is by far the most stable version of Node available.
