### ISSUE TITLE
Issues w/Multi-module project, unable to add dependency of a relative module

### ISSUE THREAD

**Issue by RameshRM** [npm/npm#7838]
I am using npm2.1.4, I still have issues w/npm module require from relative sub-projects. I am building a multi-module project and all the modules are not intended to be published.

I dont want to `require('../../relative-paths')`. Rather, i would do `npm install ../relative-module --save` and do `require('relative-module')`. This seem to be the problem, my module is unable to discover.

**Comment by KenanY** [comment]
@RameshRM Is this still an issue for you? If so, could you provide a means of reproducing this?

**Comment by RameshRM** [comment]
Nope, this is no longer an issue, thx.
