### ISSUE TITLE
tests fail against Node 0.8.28

### ISSUE THREAD

**Issue by othiym23** [npm/npm#7842]
* [ ] `test/tap/dedupe-scoped.js` (2/5)
* [ ] `test/tap/ls-depth-unmet.js` (10/20)
* [ ] `test/tap/peer-deps-invalid.js` (2/5)
* [ ] `test/tap/peer-deps-toplevel.js` (2/5)
* [ ] `test/tap/peer-deps.js` (0/2)
* [ ] `test/tap/shrinkwrap-scoped-auth.js` (3/6)
* [ ] `test/tap/sorted-package-json.js` (3/7)
* [x] `test/tap/spawn-enoent-help.js` (1/3)
* [x] `test/tap/umask-lifecycle.js` (0/3)
* [ ] `test/tap/update-save.js` (24/27)
* [ ] `test/tap/url-dependencies.js` (7/9)

## nock requires `setImmediate`

* [x] `test/tap/publish-access-scoped.js` (3/4)
* [x] `test/tap/publish-access-unscoped.js` (3/4)
* [x] `test/tap/publish-scoped.js` (2/3)

## `npm-registry-couchapp` tests require Node.js 0.10+ / io.js

* [x] ~~`test/tap/registry.js`~~

**Comment by smikes** [comment]
These are now fixed in master: 
 test/tap/dedupe-scoped.js (2/5)
 test/tap/peer-deps-toplevel.js (2/5)
 test/tap/peer-deps.js (0/2)
test/tap/url-dependencies.js (7/9)
test/tap/update-save.js (24/27)

#7850 contains a test for spawn-enoent-help (thanks @SonicHedgehog, I introduced that one).

Only ones still failing are the publish-access tests.  I will look at replacing `nock` with `mockRegistry`

**Comment by othiym23** [comment]
I think there may be an issue with newish versions of tap on Node 0.8, at least when used as the test runner. @isaacs, does this ring any bells with you? In the output below, I've marked the tests that work when run directly from the command line.

Current failure output on my machine when tests are run via `nave use 0.8.28 npm run-script test-all`:

* [`test/tap/dedupe-scoped.js`](https://gist.github.com/othiym23/eab27c1bff197b0442a7#file-npm-run-script-test-all-node-0-8-28-log-L2451) (works when run directly)
* [`test/tap/ls-depth-unmet.js`](https://gist.github.com/othiym23/eab27c1bff197b0442a7/30d920206ddf1d4d1a60664ef708dbc9d9209f7a#file-npm-run-script-test-all-node-0-8-28-log-L2572)  (flappy, always works when run directly)
* [`test/tap/peer-deps-invalid.js`](https://gist.github.com/othiym23/eab27c1bff197b0442a7/30d920206ddf1d4d1a60664ef708dbc9d9209f7a#file-npm-run-script-test-all-node-0-8-28-log-L2921) (flappy)
* [`test/tap/peer-deps-toplevel.js`](https://gist.github.com/othiym23/eab27c1bff197b0442a7#file-npm-run-script-test-all-node-0-8-28-log-L2598)
* [`test/tap/peer-deps.js`](https://gist.github.com/othiym23/eab27c1bff197b0442a7#file-npm-run-script-test-all-node-0-8-28-log-L2710)
* [`test/tap/shrinkwrap-scoped-auth.js`](https://gist.github.com/othiym23/eab27c1bff197b0442a7#file-npm-run-script-test-all-node-0-8-28-log-L2824) (works when run directly)
* [`test/tap/sorted-package-json.js`](https://gist.github.com/othiym23/eab27c1bff197b0442a7#file-npm-run-script-test-all-node-0-8-28-log-L2904) (works when run directly)
* [`test/tap/spawn-enoent-help.js`](https://gist.github.com/othiym23/eab27c1bff197b0442a7#file-npm-run-script-test-all-node-0-8-28-log-L3021) 
* [`test/tap/url-dependencies.js`](https://gist.github.com/othiym23/eab27c1bff197b0442a7#file-npm-run-script-test-all-node-0-8-28-log-L3021) (works when run directly)

**Comment by othiym23** [comment]
I fixed the `nock`-related tests via 269a62327bbe114583f3666c61fcbe81d17a1e57. `nock` uses `setImmediate` directly from the timers module for some reason, which makes monkeypatching `setImmediate` in gross enough that we should probably replace it altogether, probably with `npm-registry-mock`.

**Comment by isaacs** [comment]
`test/tap/dedupe-scoped.js` doesn't work for me when run directly under 0.8.  This patch fixes it:

```diff
diff --git a/node_modules/npmlog/node_modules/are-we-there-yet/index.js b/node_modules/npmlog/node_modules/are-we-there-yet/index.js
index ffbdfb1..a625ce2 100644
--- a/node_modules/npmlog/node_modules/are-we-there-yet/index.js
+++ b/node_modules/npmlog/node_modules/are-we-there-yet/index.js
@@ -1,5 +1,8 @@
 "use strict"
 var stream = require("stream");
+if (!stream.Transform)
+  stream = require("readable-stream");
+
 var EventEmitter = require("events").EventEmitter
 var util = require("util")
 var delegate = require("delegates")

```

Maybe others are breaking in a similar fashion due to `require("stream")`?

**Comment by isaacs** [comment]
Oh, wait, nevermind, it looks like that is AN issue, but not THE issue.  I was a few revs behind master.

**Comment by othiym23** [comment]
`test/tap/spawn-enoent-help.js` failures fixed by 26d36e9cf0eca69fe1863d2ea536c28555b9e8de, which will also make exec failures look a lot more consistent under 0.8.

**Comment by smikes** [comment]
Can this be closed?  The only remaining failure on 0.8 seems to be ls-depth-unmet which is marked above as "flappy" -- maybe spin that off into a separate issue?

**Comment by othiym23** [comment]
I think there's still something awry in the tap ruiner (sic), because I still see most of these tests failing intermittently, albeit less so now that we've increased the test timeout. I'll look into it this week.

**Comment by othiym23** [comment]
Still working on this! :crying_cat_face:

**Comment by phillipj** [comment]
I'm having issues with npm v3.3.3 on node v0.8.28. After updating npm I get this error for all npm commands:

```bash
Error: Cannot find module 'are-we-there-yet'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    ...
```

Seems to be a npm v3 issue as v2.14.5 works just fine.

https://travis-ci.org/janl/mustache.js/jobs/80962009

**Comment by othiym23** [comment]
@phillipj you're running into a different issue – see https://github.com/npm/npm/issues/9644 for details and a probable workaround. Also, if at all possible, upgrade to a newer Node than 0.8. The CLI team supports 0.8 because there are a number of large sites that are stuck with it, but you're missing out on a lot of good stuff.

**Comment by phillipj** [comment]
Thanks for replying in lightning speed with a good workaround. Ended up updating to npm@2.x for now.

Luckily I have upgraded from node v0.8 a long time ago, but we're still trying to test mustache.js against it as the lib has been around of ages. We just dropped v0.6 support, this is probably the first sign that we should consider doing the same with v0.8 :)

**Comment by timkrins** [comment]
Nock is also requiring setImmediate on:

`test/tap/splat-with-only-prerelease-to-latest.js`
`test/tap/add-named-update-protocol-port.js`
`test/tap/404-private-registry.js`
`test/tap/404-private-registry-scoped.js`

Also nock is using HTTP.IncomingMessage.push() class method incompatible with 0.8 used in:
`test/tap/publish-access-scoped.js`
`test/tap/publish-access-unscoped.js`
`test/tap/publish-scoped.js`

`TypeError: Object #<IncomingMessage> has no method 'push'`

**Comment by halhenke** [comment]
Think I just ran into this on Travis with `npm@2.14.16` for `test/tap/peer-deps-invalid.js`

https://travis-ci.org/npm/npm/builds/105208937
https://travis-ci.org/npm/npm/jobs/105208944

**Comment by iarna** [comment]
Tests now pass against 0.8.
