### ISSUE TITLE
write normalized `package.json` to package tarball as part of `npm pack`

### ISSUE THREAD

**Issue by othiym23** [npm/npm#7843]
See https://github.com/npm/npm/issues/7074#issuecomment-89092501 for details. Also,

> fixing [this] will require some reasonably extensive changes to either `fstream-npm` to allow it to replace the `package.json` from the folder being packed with what comes out of `read-package-json`, or the packing process will have to be made 2-phase, so that the new `package.json` can be put in place before being handed off to `fstream-npm`.

**Comment by smikes** [comment]
I can take a look at this, next week.

**Comment by othiym23** [comment]
The real upshot here is that the `package.json` in the package tarball is different than the `package.json` data in the tarball and _they should be the same_.

This has been moved to the [npm roadmap](https://github.com/npm/npm/wiki/Roadmap), which we're using instead of the confusing `next-*` labels now.
