### ISSUE TITLE
Can't run npm install learnyounode -g

### ISSUE THREAD

**Issue by jayadrath** [npm/npm#7844]
Hello all,
I have been trying to install learnyounode for some time now and keep getting this error:

0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   '/home/ekaucha/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'learnyounode' ]
2 info using npm@2.7.4
3 info using node@v0.10.37
4 verbose node symlink /usr/bin/node
5 silly cache add args [ 'learnyounode', null ]
6 verbose cache add spec learnyounode
7 silly cache add parsed spec { raw: 'learnyounode',
7 silly cache add   scope: null,
7 silly cache add   name: 'learnyounode',
7 silly cache add   rawSpec: '',
7 silly cache add   spec: '*',
7 silly cache add   type: 'range' }
8 verbose addNamed learnyounode@*
9 silly addNamed semver.valid null
10 silly addNamed semver.validRange *
11 silly addNameRange { name: 'learnyounode', range: '*', hasData: false }
12 silly mapToRegistry name learnyounode
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/learnyounode
16 verbose addNameRange registry:https://registry.npmjs.org/learnyounode not in flight; fetching
17 verbose request uri https://registry.npmjs.org/learnyounode
18 verbose request no auth needed
19 info attempt registry request try #1 at 16:36:32
20 verbose request id 55bf2dd9af0b8a67
21 http request GET https://registry.npmjs.org/learnyounode
22 http 200 https://registry.npmjs.org/learnyounode
23 silly get cb [ 200,
23 silly get   { date: 'Fri, 03 Apr 2015 11:06:35 GMT',
23 silly get     server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
23 silly get     etag: '"7GKEK5Q50I5SOM3U7S9TRF93Z"',
23 silly get     'content-type': 'application/json',
23 silly get     'cache-control': 'max-age=60',
23 silly get     'content-length': '104706',
23 silly get     'accept-ranges': 'bytes',
23 silly get     via: '1.1 varnish',
23 silly get     age: '0',
23 silly get     'x-served-by': 'cache-ams4123-AMS',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '1',
23 silly get     'x-timer': 'S1428059195.011340,VS0,VE385',
23 silly get     vary: 'Accept',
23 silly get     'keep-alive': 'timeout=10, max=50',
23 silly get     connection: 'Keep-Alive' } ]
24 verbose get saving learnyounode to /home/ekaucha/.npm/registry.npmjs.org/learnyounode/.cache.json
25 silly addNameRange number 2 { name: 'learnyounode', range: '*', hasData: true }
26 silly addNameRange versions [ 'learnyounode',
26 silly addNameRange   [ '0.0.0',
26 silly addNameRange     '0.0.1',
26 silly addNameRange     '0.0.2',
26 silly addNameRange     '0.0.3',
26 silly addNameRange     '0.0.4',
26 silly addNameRange     '0.0.5',
26 silly addNameRange     '0.0.6',
26 silly addNameRange     '0.0.7',
26 silly addNameRange     '0.0.8',
26 silly addNameRange     '0.0.9',
26 silly addNameRange     '0.1.0',
26 silly addNameRange     '0.1.1',
26 silly addNameRange     '0.2.0',
26 silly addNameRange     '0.2.1',
26 silly addNameRange     '0.2.2',
26 silly addNameRange     '0.2.3',
26 silly addNameRange     '0.2.4',
26 silly addNameRange     '0.2.5',
26 silly addNameRange     '0.2.6',
26 silly addNameRange     '0.2.7',
26 silly addNameRange     '0.2.8',
26 silly addNameRange     '0.2.9',
26 silly addNameRange     '0.2.10',
26 silly addNameRange     '0.2.11',
26 silly addNameRange     '0.2.12',
26 silly addNameRange     '0.2.13',
26 silly addNameRange     '0.2.14',
26 silly addNameRange     '0.2.15',
26 silly addNameRange     '0.2.16',
26 silly addNameRange     '0.2.16-mimbug',
26 silly addNameRange     '0.3.0',
26 silly addNameRange     '0.3.1',
26 silly addNameRange     '0.3.2',
26 silly addNameRange     '0.3.3',
26 silly addNameRange     '0.4.0',
26 silly addNameRange     '0.4.1',
26 silly addNameRange     '1.0.0-alpha01',
26 silly addNameRange     '1.0.0',
26 silly addNameRange     '1.0.1',
26 silly addNameRange     '1.0.2',
26 silly addNameRange     '1.0.3',
26 silly addNameRange     '1.0.4',
26 silly addNameRange     '1.0.5',
26 silly addNameRange     '1.0.6',
26 silly addNameRange     '1.0.7',
26 silly addNameRange     '2.0.0',
26 silly addNameRange     '2.0.1',
26 silly addNameRange     '2.1.0',
26 silly addNameRange     '2.2.0',
26 silly addNameRange     '2.2.1',
26 silly addNameRange     '2.2.2',
26 silly addNameRange     '2.3.0',
26 silly addNameRange     '2.3.1',
26 silly addNameRange     '2.3.2',
26 silly addNameRange     '2.3.3',
26 silly addNameRange     '2.3.4',
26 silly addNameRange     '2.4.0',
26 silly addNameRange     '2.5.0',
26 silly addNameRange     '2.6.0' ] ]
27 verbose addNamed learnyounode@2.5.0
28 silly addNamed semver.valid 2.5.0
29 silly addNamed semver.validRange 2.5.0
30 silly mapToRegistry name learnyounode
31 silly mapToRegistry using default registry
32 silly mapToRegistry registry https://registry.npmjs.org/
33 silly mapToRegistry uri https://registry.npmjs.org/learnyounode
34 verbose addRemoteTarball https://registry.npmjs.org/learnyounode/-/learnyounode-2.5.0.tgz not in flight; adding
35 verbose addRemoteTarball [ 'https://registry.npmjs.org/learnyounode/-/learnyounode-2.5.0.tgz',
35 verbose addRemoteTarball   '2597aca22d5759a05d9b417970005b3b67401291' ]
36 info retry fetch attempt 1 at 16:36:37
37 info attempt registry request try #1 at 16:36:37
38 http fetch GET https://registry.npmjs.org/learnyounode/-/learnyounode-2.5.0.tgz
39 http fetch 200 https://registry.npmjs.org/learnyounode/-/learnyounode-2.5.0.tgz
40 silly fetchAndShaCheck shasum 2597aca22d5759a05d9b417970005b3b67401291
41 verbose addTmpTarball /tmp/npm-8957-5d51936b/registry.npmjs.org/learnyounode/-/learnyounode-2.5.0.tgz not in flight; adding
42 verbose addTmpTarball already have metadata; skipping unpack for learnyounode@2.5.0
43 silly cache afterAdd learnyounode@2.5.0
44 verbose afterAdd /home/ekaucha/.npm/learnyounode/2.5.0/package/package.json not in flight; writing
45 verbose afterAdd /home/ekaucha/.npm/learnyounode/2.5.0/package/package.json written
46 silly install resolved [ { name: 'learnyounode',
46 silly install resolved     version: '2.5.0',
46 silly install resolved     description: 'Learn You The Node.js For Much Win! An intro to Node.js via a set of self-guided workshops.',
46 silly install resolved     author:
46 silly install resolved      { name: 'Rod Vagg',
46 silly install resolved        email: 'rod@vagg.org',
46 silly install resolved        url: 'https://github.com/rvagg' },
46 silly install resolved     contributors:
46 silly install resolved      [ [Object],
46 silly install resolved        [Object],
46 silly install resolved        [Object],
46 silly install resolved        [Object],
46 silly install resolved        [Object],
46 silly install resolved        [Object],
46 silly install resolved        [Object],
46 silly install resolved        [Object],
46 silly install resolved        [Object],
46 silly install resolved        [Object],
46 silly install resolved        [Object],
46 silly install resolved        [Object],
46 silly install resolved        [Object],
46 silly install resolved        [Object],
46 silly install resolved        [Object],
46 silly install resolved        [Object] ],
46 silly install resolved     repository:
46 silly install resolved      { type: 'git',
46 silly install resolved        url: 'https://github.com/rvagg/learnyounode.git' },
46 silly install resolved     license: 'MIT',
46 silly install resolved     dependencies:
46 silly install resolved      { after: '~0.8.1',
46 silly install resolved        bl: '~0.9.4',
46 silly install resolved        boganipsum: '~0.1.0',
46 silly install resolved        chalk: '~0.5.1',
46 silly install resolved        'colors-tmpl': '~1.0.0',
46 silly install resolved        'combined-stream': '~0.0.7',
46 silly install resolved        'concat-stream': '~1.4.7',
46 silly install resolved        duplexer: '~0.1.1',
46 silly install resolved        hyperquest: '~1.0.1',
46 silly install resolved        rimraf: '~2.2.8',
46 silly install resolved        through: '~2.3.6',
46 silly install resolved        through2: '~0.6.3',
46 silly install resolved        'through2-map': '~1.4.0',
46 silly install resolved        workshopper: '~2.3.1',
46 silly install resolved        'workshopper-exercise': '~2.3.0',
46 silly install resolved        'workshopper-wrappedexec': '~0.1.1' },
46 silly install resolved     bin: { learnyounode: './learnyounode.js' },
46 silly install resolved     preferGlobal: true,
46 silly install resolved     gitHead: '25cf9c5ba8a5298ca3bdf11c12619f4c2c2ff96a',
46 silly install resolved     bugs: { url: 'https://github.com/rvagg/learnyounode/issues' },
46 silly install resolved     homepage: 'https://github.com/rvagg/learnyounode',
46 silly install resolved     _id: 'learnyounode@2.5.0',
46 silly install resolved     scripts: {},
46 silly install resolved     _shasum: '2597aca22d5759a05d9b417970005b3b67401291',
46 silly install resolved     _from: 'learnyounode@*',
46 silly install resolved     _npmVersion: '2.5.1',
46 silly install resolved     _nodeVersion: '1.2.0',
46 silly install resolved     _npmUser: { name: 'rvagg', email: 'rod@vagg.org' },
46 silly install resolved     maintainers: [ [Object] ],
46 silly install resolved     dist:
46 silly install resolved      { shasum: '2597aca22d5759a05d9b417970005b3b67401291',
46 silly install resolved        tarball: 'http://registry.npmjs.org/learnyounode/-/learnyounode-2.5.0.tgz' },
46 silly install resolved     directories: {},
46 silly install resolved     _resolved: 'https://registry.npmjs.org/learnyounode/-/learnyounode-2.5.0.tgz' } ]
47 info install learnyounode@2.5.0 into /usr/lib
48 info installOne learnyounode@2.5.0
49 verbose installOne of learnyounode to /usr/lib not in flight; installing
50 verbose lock using /home/ekaucha/.npm/_locks/learnyounode-f994df939c84fab7.lock for /usr/lib/node_modules/learnyounode
51 silly install write writing learnyounode 2.5.0 to /usr/lib/node_modules/learnyounode
52 silly cache addNamed cb learnyounode@2.5.0
53 verbose unbuild lib/node_modules/learnyounode
54 silly gentlyRm /usr/lib/node_modules/learnyounode is being purged from base /usr
55 verbose gentlyRm don't care about contents; nuking /usr/lib/node_modules/learnyounode
56 verbose tar unpack /home/ekaucha/.npm/learnyounode/2.5.0/package.tgz
57 verbose tar unpacking to /usr/lib/node_modules/learnyounode
58 silly gentlyRm /usr/lib/node_modules/learnyounode is being purged
59 verbose gentlyRm don't care about contents; nuking /usr/lib/node_modules/learnyounode
60 silly gunzTarPerm modes [ '755', '644' ]
61 error tar.unpack untar error /home/ekaucha/.npm/learnyounode/2.5.0/package.tgz
62 verbose unlock done using /home/ekaucha/.npm/_locks/learnyounode-f994df939c84fab7.lock for /usr/lib/node_modules/learnyounode
63 verbose fstream_path /usr/lib/node_modules/learnyounode
64 verbose fstream_type Directory
65 verbose fstream_class DirWriter
66 verbose stack Error: EACCES, mkdir '/usr/lib/node_modules/learnyounode'
67 verbose fstream_stack /home/ekaucha/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23
67 verbose fstream_stack /home/ekaucha/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53
67 verbose fstream_stack Object.oncomplete (fs.js:108:15)
68 verbose cwd /home/ekaucha/Documents/work/npm
69 error Linux 3.2.0-67-generic
70 error argv "node" "/home/ekaucha/bin/npm" "install" "-g" "learnyounode"
71 error node v0.10.37
72 error npm  v2.7.4
73 error path /usr/lib/node_modules/learnyounode
74 error code EACCES
75 error errno 3
76 error Error: EACCES, mkdir '/usr/lib/node_modules/learnyounode'
76 error  { [Error: EACCES, mkdir '/usr/lib/node_modules/learnyounode']
76 error   errno: 3,
76 error   code: 'EACCES',
76 error   path: '/usr/lib/node_modules/learnyounode',
76 error   fstream_type: 'Directory',
76 error   fstream_path: '/usr/lib/node_modules/learnyounode',
76 error   fstream_class: 'DirWriter',
76 error   fstream_stack:
76 error    [ '/home/ekaucha/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23',
76 error      '/home/ekaucha/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53',
76 error      'Object.oncomplete (fs.js:108:15)' ] }
77 error Please try running this command again as root/Administrator.
78 verbose exit [ 3, true ]
79 verbose unbuild lib/node_modules/learnyounode
80 silly gentlyRm /usr/lib/node_modules/learnyounode is being purged from base /usr
81 verbose gentlyRm don't care about contents; nuking /usr/lib/node_modules/learnyounode

**Comment by KenanY** [comment]
@jayadrath Have you tried using `sudo`?

**Comment by jayadrath** [comment]
I was under the impression that if I tried sudo I would not be able to run it as a normal user?

**Comment by jayadrath** [comment]
@KenanY Thanks it installed now :+1:
