### ISSUE TITLE
bcrypt install failed. Node-gyp rebuild error. 

### ISSUE THREAD

**Issue by aryak93** [npm/npm#7845]
I have tried almost all possible solutions for this issue. I have the python path set also.
Where am I going wrong? Please help!!

    gyp ERR! build error
    gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
    failed with exit code: 1
    gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
    npm\node_modules\node-gyp\lib\build.js:267:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067
    :12)
    gyp ERR! System Windows_NT 6.1.7600
    gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
    les\\node-gyp\\bin\\node-gyp.js" "rebuild"
    gyp ERR! cwd E:\Mean.js stuffs\portal-ecom-sails\node_modules\bcrypt
    gyp ERR! node -v v0.12.0
    gyp ERR! node-gyp -v v1.0.2
    gyp ERR! not ok
    npm ERR! Windows_NT 6.1.7600
    npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
    \\node_modules\\npm\\bin\\npm-cli.js" "install" "bcrypt" "--save"
    npm ERR! node v0.12.0
    npm ERR! npm  v2.5.1
    npm ERR! code ELIFECYCLE

    npm ERR! bcrypt@0.8.2 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the bcrypt@0.8.2 install script 'node-gyp rebuild'.
    npm ERR! This is most likely a problem with the bcrypt package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls bcrypt
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     E:\Mean.js stuffs\portal-ecom-sails\npm-debug.log

**Comment by othiym23** [comment]
It looks like npm is holding up its end of the bargain, and something is awry with your VS install. As the output says, this is probably not an npm issue:

```
npm ERR! Failed at the bcrypt@0.8.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
```

You might want to [take a look](https://github.com/ncb000gt/node.bcrypt.js/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+msbuild.exe+failed+) at bcrypt's list of issues related to building on Windows, or maybe check StackOverflow, as it looks like `bcrypt@0.8.2` builds fine for other developers using VS and Node 0.12.0.

**Comment by zccaliDev** [comment]
npm install bcrypt --msvs_version=2012 or 2013 and then enter

**Comment by luishk807** [comment]
@zccaliDev both way failed for me :-(

**Comment by zccaliDev** [comment]
just enter the version of visual studio you have like if you installed 2015 or older
