### ISSUE TITLE
node08: npm 2.7.5 compile error

### ISSUE THREAD

**Issue by DomT4** [npm/npm#7849]
This is an odd one. Not sure if ` npm ` still formally support ` node08 ` so feel free to close if you don't.

With ` node08 ` & ` npm 2.7.0 ` installed ` npm install -g npm@latest ` works fine, and the new ` npm ` 2.7.5 afterwards happily installs packages and prints its version and all that good stuff.

Trying to compile ` npm ` afresh with ` node08 ` leads to this fun:

```
make install
node cli.js install -g -f

util.js:538
  ctor.prototype = Object.create(superCtor.prototype, {
                                          ^
TypeError: Cannot read property 'prototype' of undefined
    at Object.exports.inherits (util.js:538:43)
    at Object.<anonymous> (/private/tmp/node0820150404-38074-98cfzv/node-v0.8.26/npm_install/node_modules/npmlog/node_modules/are-we-there-yet/index.js:115:6)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/private/tmp/node0820150404-38074-98cfzv/node-v0.8.26/npm_install/node_modules/npmlog/log.js:2:16)
    at Module._compile (module.js:449:26)
make: *** [install] Error 1
```

This worked fine for 2.7.0, so I can't imagine the method itself is suddenly causing problems :cry:.

**Comment by othiym23** [comment]
Try `npm@2.7.6` (`npm@next`) – we upgraded the version of `npmlog` to the new major version, and it uses a Transform stream, so @iarna had to put a new version out that uses `readable-stream` instead of the built-in `streams` module. You may also find #7842 to be worthy of your interest and / or time.

I'm going to close this issue in favor of that one, but I would very much like to keep npm working with Node 0.8.

**Comment by DomT4** [comment]
Bingo, ` 2.7.6 ` compiles, installs and functions perfectly. Thanks!

I've always presumed I'm doing something wrong with ` npm `'s test mechanism, because I can never get it to work. I'll provide an example so you can laugh and point out what I'm doing wrong :smile:.

```
-> cd /usr/local/opt/node/libexec/npm/lib/node_modules/npm
~> npm test

> npm@2.7.4 test /usr/local/Cellar/node/0.12.2/libexec/npm/lib/node_modules/npm
> tap --timeout 120 test/tap/*.js

sh: tap: command not found
npm ERR! Test failed.  See above for more details.
```

**Comment by othiym23** [comment]
`npm install && npm test`

npm only bundles `dependencies`, not `devDependencies`.
