### ISSUE TITLE
Can't install underscore using "npm install underscore" command

### ISSUE THREAD

**Issue by PrabakaranSurian** [npm/npm#7851]
I'm new to nodejs, i want to execute my app, it throws error by saying it needs underscore. i couldn't install underscore using that command "npm install underscore" please help me

**Comment by KenanY** [comment]
@PrabakaranSurian Are you getting an error when you run `npm install underscore`? Is a `npm-debug.log` file created in your current directory when this happens? Could you upload it as a [gist](https://gist.github.com/). Node.js version? `npm` version? There's not enough information for me to go on here.

https://github.com/npm/npm/wiki/Contributing-Guidelines

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
