### ISSUE TITLE
Unable to install local grunt with npm 2.7.5

### ISSUE THREAD

**Issue by Reklino** [npm/npm#7853]
I can't seem to install grunt via npm. My npm is up to date. I'm running it on a homestead box. This happens any time I try `sudo npm install grunt --save-dev`.

[Here is a link to the error log file](https://github.com/Reklino/cors-stuff/blob/master/npm-debug.log)

**Comment by aredridel** [comment]
Cut the error log down to size:

```
2587 error Linux 3.13.0-11-generic
2588 error argv "node" "/usr/bin/npm" "install" "grunt" "--save-dev"
2589 error node v0.10.35
2590 error npm  v2.7.5
2591 error path ../which/bin/which
2592 error code UNKNOWN
2593 error errno -1
2594 error UNKNOWN, symlink '../which/bin/which'
2595 error If you need help, you may report this error at:
2595 error     <https://github.com/npm/npm/issues>
```

**Comment by ehsalazar** [comment]
@Reklino We're working through some of the older issues. You've likely moved beyond this issue but it sounds like you're working on a shared disk. This is causing the error as the symlink can't be correctly created. I'll close out this issue of now, but will be happy to reopen if this remains an issue for you.
