### ISSUE TITLE
npm install issue - Mac OS X 10.10.2  - minimst

### ISSUE THREAD

**Issue by mattwl** [npm/npm#7855]
Quite new to NPM/node - apologies in advance.  Trying to compile Tilemill via terminal on Mac OS X 10.10.2

When I do 'npm install', I get the following error in terminal:

npm ERR! Error: No compatible version found: minimist@'^1.1.0'
npm ERR! Valid install targets:
npm ERR! ["0.0.0","0.0.1","0.0.2","0.0.3","0.0.4","0.0.5","0.0.6","0.0.7","0.0.8","0.0.9","0.0.10","0.1.0","0.2.0","1.0.0","1.1.0","1.1.1"]
npm ERR!     at installTargetsError (/usr/local/Cellar/node/0.10.15/lib/node_modules/npm/lib/cache.js:719:10)
npm ERR!     at /usr/local/Cellar/node/0.10.15/lib/node_modules/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/local/Cellar/node/0.10.15/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/local/Cellar/node/0.10.15/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

Any ideas? Is this a bug in NPM?

Thanks

**Comment by aredridel** [comment]
Which version of node and npm?

My suspicion is that you've node 0.8 and a very old npm.

**Comment by KenanY** [comment]
Yeah, this error is almost certainly the result of an old `npm` that can't parse the `^` semver operator. [Updating](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) should fix this.

**Comment by mattwl** [comment]
Ok. thank you - needed to update. Thanks.
