### ISSUE TITLE
npm ERR! error while installing express (Ubuntu 14.04)

### ISSUE THREAD

**Issue by sushant047** [npm/npm#7856]
(I am new to node.js and almost a newbie to Linux too)
This is the error log

```
sushant047@sushant047-Inspiron-N5010:~/node-v0.12.2$ npm install express-generator -g
npm ERR! Linux 3.16.0-33-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "express-generator" "-g"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ECONNRESET

npm ERR! network tunneling socket could not be established, cause=write EPROTO 139792596907904:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:782:
npm ERR! network 
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Linux 3.16.0-33-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "express-generator" "-g"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4

npm ERR! Uncaught, unspecified "error" event.
npm ERR! 
```

**Comment by aredridel** [comment]
What it says on the tin: The network connection failed. Try again, or if you've got a firewall between you and the registry, that may be the problem too.

**Comment by sushant047** [comment]
@aredridel I have tried for 3 to 4 times where I am receiving the same errors. Meanwhile my system freezes and I need to hard reset my system. Thats the problem with my Ubuntu

**Comment by kgan4dev** [comment]
Once try with sudo.

**Comment by sushant047** [comment]
Sorry that I forgot to post it that its solved. THank you @kgan4dev , I did the same to solve this issue.

**Comment by tamirlancomas** [comment]
help me

gyp ERR! build error 
gyp ERR! stack Error: make failed with exit code: 2
gyp ERR! stack at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack at ChildProcess.emit (events.js:98:17)
gyp ERR! stack at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.16.0-30-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /pigsty/node_modules/unified2/node_modules/pcap
gyp ERR! node -v v0.10.37
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! pcap@0.3.3 install: node-gyp rebuild
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pcap@0.3.3 install script.
npm ERR! This is most likely a problem with the pcap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node-gyp rebuild
npm ERR! You can get their info via:
i have a problem help me

npm ERR! npm owner ls pcap
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.16.0-30-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /pigsty
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

for example: https://github.com/hillar/pigsty-moloch-plugin

**Comment by ehsalazar** [comment]
@sushant047 Good to hear. I'll close this for now as we’re trying to clean up some old issues. We’ll be happy to reopen if necessary.

@tamirlancomas Your running an older version of npm. Are you able to update to a current release? If this is still a problem, can you please reply and let us know by submitting a new, separate issue? https://github.com/npm/npm/issues/new
