### ISSUE TITLE
How to get npm warnings/errors when npm installing a package?

### ISSUE THREAD

**Issue by marcusoftnet** [npm/npm#7857]
Hello all, I wrote [this question up in StackOverflow](http://stackoverflow.com/questions/29454545/npm-install-on-a-folder-where-does-the-node-modules-go) and just thought I post a reference here, because I really don't understand this. 

It's quite a long question, but if you rather want it here, I'm happy to repost. Starting with this reference. Any help highly appreciated.

**Comment by smikes** [comment]
There is a heuristic `npm` uses to guess the `prefix` if it is not supplied: If you don't have a `package.json` file in your current directory, `npm` tries to climb up the directory tree to find a directory with `package.json`.  At the end, this will lead to modules being installed under `~/node_modules` for a non-root user or `/node_modules` for the root user.

The simplest way to avoid this is to create a `package.json` file for your modules, which can easily be done by running `npm init` in the module directory.

**Comment by marcusoftnet** [comment]
Ok, thank. Thought so. 

So let me ask it like this instead: is there a way to use ```npm``` to verify that my code (according to ```package.json``` ```{engines}``` will work on the runtime I'm running on? I want to get warnings. 

As far as I understand that check is only done when you install a *package*, not the dependencies for an application? Or is there another way?

**Comment by smikes** [comment]
`npm` will check the `engines` for all packages it installs, whether directory or as a required dependency, at installation time.  So you could check a module and all its dependencies by installing it, or you chould check all the dependencies of the current modules (and all their dependencies, etc.) by running

```
rm -rf node_modules
npm i
```

**Comment by marcusoftnet** [comment]
Ok (and sorry for being slow), but what about my own application. 

For example; let's say that my ```index.js``` only contains this row;
```console.log(`The result is ${2+2}`);```

This only works in io.js, so my engines and enginesStrict looks like this:
```javascript
"engineStrict" : "true", 
"engines:{
  "iojs" : "1.6.3"
}"
```

Can I now get npm to warn/throw error when I am running on Node 0.12.0?

**Comment by smikes** [comment]
Yes, there is a way to "dry run" the installation.  In the package directory you can run `npm link` which will attempt to install the project as a global package in your `npm` globals directory.

I think overall, though, there is less support than we might like to have for node version guarding.  I believe the prevailing workaround is to use transpilation and feature-testing.

**Comment by marcusoftnet** [comment]
Ok thanks a bunch for your patience and good answers. Appreciate it!
