### ISSUE TITLE
"is not in the npm registry." when publishing a new package

### ISSUE THREAD

**Issue by srph** [npm/npm#7858]
While trying to publish a new package which is not in the npm registry, I receive this error:

```bash
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "publish"
npm ERR! node v0.12.1
npm ERR! npm  v2.7.3
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/eidolon?write=true
npm ERR! 404
npm ERR! 404 '.....' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/srph/_/my-project/npm-debug.log
```

**Comment by bcoe** [comment]
When publishing a package that has been published before, you must bump the version #. I am going to be working on better messaging for this error this week.

Try publishing your package as version `1.0.0`, and it should do the trick. If not, please share a gist with the entire error log you receive.

**Comment by srph** [comment]
Ah, I see :+1:. Would there be any work on this? Because I'm afraid I can't release my package as `v1.0.0` when it's in its early versions :disappointed:.

**Comment by bcoe** [comment]
@srph it's an important assumption in the distributed system that powers npm, that package versions are not republished. To see what versions have been previously published for a package, you can look at the meta-information in the registry:

https://registry.npmjs.org/eidolon

You should be able to publish at `0.2.0` it looks like, would this be acceptable?

**Comment by srph** [comment]
Ah, yes. Thanks a lot for the quick response, @bcoe :+1: :sparkles:

**Comment by jlmonteagudo** [comment]
Hello,

I'm also getting this problem publishing a new version of a package.

I've tried updating the version number in package.json but it doesn't work for me.

This is the information that I get in npm-debug.log:

<pre>
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'publish', './' ]
2 info using npm@2.7.6
3 info using node@v0.10.21
4 verbose publish [ './' ]
5 silly cache add args [ './', null ]
6 verbose cache add spec ./
7 silly cache add parsed spec { raw: './',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: './',
7 silly cache add   spec: '/home/jlm/develop/node/projects/generators/generator-hottowel-table',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory /home/jlm/.npm/generator-hottowel-table/0.2.0/package.tgz not in flight; packing
9 verbose tar pack [ '/home/jlm/.npm/generator-hottowel-table/0.2.0/package.tgz',
9 verbose tar pack   '/home/jlm/develop/node/projects/generators/generator-hottowel-table' ]
10 verbose tarball /home/jlm/.npm/generator-hottowel-table/0.2.0/package.tgz
11 verbose folder /home/jlm/develop/node/projects/generators/generator-hottowel-table
12 info prepublish generator-hottowel-table@0.2.0
13 verbose addLocalTarball adding from inside cache /home/jlm/.npm/generator-hottowel-table/0.2.0/package.tgz
14 silly cache afterAdd generator-hottowel-table@0.2.0
15 verbose afterAdd /home/jlm/.npm/generator-hottowel-table/0.2.0/package/package.json not in flight; writing
16 verbose afterAdd /home/jlm/.npm/generator-hottowel-table/0.2.0/package/package.json written
17 silly publish { name: 'generator-hottowel-table',
17 silly publish   version: '0.2.0',
17 silly publish   description: 'Yeoman generator for HotTowel Table Angular',
17 silly publish   license: 'MIT',
17 silly publish   main: 'app/index.js',
17 silly publish   repository:
17 silly publish    { type: 'git',
17 silly publish      url: 'https://github.com/jlmonteagudo/generator-hottowel-table' },
17 silly publish   author:
17 silly publish    { name: 'Jose Luis Monteagudo',
17 silly publish      email: 'jl_monteagudo@yahoo.es',
17 silly publish      url: 'http://www.jlmonteagudo.com' },
17 silly publish   engines: { node: '>=0.10.0' },
17 silly publish   scripts: { test: 'mocha' },
17 silly publish   files: [ 'app' ],
17 silly publish   keywords:
17 silly publish    [ 'yeoman-generator',
17 silly publish      'angular',
17 silly publish      'angularjs',
17 silly publish      'mean',
17 silly publish      'meanjs',
17 silly publish      'sails',
17 silly publish      'sailsjs' ],
17 silly publish   dependencies:
17 silly publish    { chalk: '^0.5.0',
17 silly publish      'yeoman-generator': '^0.17.0',
17 silly publish      yosay: '^0.3.0',
17 silly publish      'underscore.inflections': '~0.2.1',
17 silly publish      lodash: '^2.4.1' },
17 silly publish   devDependencies:
17 silly publish    { gulp: '^3.8.11',
17 silly publish      'gulp-bump': '^0.1.11',
17 silly publish      'gulp-load-plugins': '^0.8.0',
17 silly publish      'gulp-task-listing': '^1.0.0',
17 silly publish      'gulp-util': '^3.0.1',
17 silly publish      yargs: '^1.3.3' },
17 silly publish   peerDependencies: { yo: '>=1.0.0' },
17 silly publish   readme: '## HOTTOWEL-TABLE with SAILSJS\n\nhottowel-table is a yeoman generator based on the great John Papa\'s [hottowel generator](https://github.com/johnpapa/generator-hottowel). This generator generates the code using the [Angular Style Guide](https://github.com/johnpapa/angular-styleguide) written by John Papa. The generated code is based in a proven structure and conventions for developing Angular applications.\n\nhottowel-table allows creating entities and CRUD operations very productively.\n\nThis generator is adapted for working with a Sails backend, although it\'s very easy to adapt it for working with whatever backend.\n\nThe generator allows creating entities automatically in a table form from where you can create, read, update and remove each database record.\n\n## Backend with Sails\n\nAt first place, you will have to create your API with Sails. However, when you get a list of records, Sails won\'t give you information regarding the total records, so you can\'t paginate properly. For example, if I request this: http://localhost:1337/customer, I get the following information:\n\n```\n[\n  {\n    code: \'customer 1\'\n  },\n  {\n    code: \'customer 2\'\n  },\n  {\n    code: \'customer 3\'\n  }\n]\n```\n\nBut if I have to paginate I need information regarding the total number of records. So, I have to override the **find** blueprint. To do this, you have to copy from this project the file [sails/api/blueprints/find.js](https://raw.githubusercontent.com/jlmonteagudo/generator-hottowel-table/master/sails/api/blueprints/find.js) into your **ROOT_PROJECT/api/blueprints/find.js**. Now, if I request this: http://localhost:1337/customer, I will get the following information:\n\n```\n{\n  total: 1000,\n  results: [\n    {\n      code: \'customer 1\'\n    },\n    {\n      code: \'customer 2\'\n    },\n    {\n      code: \'customer 3\'\n    }\n  ]\n}\n```\n\nWith this object we have all the information that we need to paginate.\n\n## Frontend Quickstart\n\nYou will need to install the hottowel-table generator:\n\n```\n$ npm install -g generator-hottowel-table\n```\n\nYou have to create a new folder for your project and from this folder you will generate your application:\n\n```\n$ yo hottowel-table MyProject\n```\n\nNext, you will create a new feature, a customer, for example:\n\n```\n$ yo hottowel-table:feature <customer>\n```\n\nThis will create an AngularJS application supporting full CRUD functionality.\n\nThis subgenerator will create an entity with two properties called \'name\' and \'street\'. If we want to add new properties to our entity, we weed to follow these steps:\n\n* Add new properties to the angular-formly array properties in src/client/app/**feature-name**/services/**feature-name**.form.client.service.js\n* Add new columns for the new properties in the HTML table in src/client/app/**feature-name**/views/list.html\n\n\n## License\n\n[BSD license](http://opensource.org/licenses/bsd-license.php)\n',
17 silly publish   readmeFilename: 'README.md',
17 silly publish   gitHead: '1e173407b1c7f7582d85f754d614af207dd9d6ed',
17 silly publish   bugs: { url: 'https://github.com/jlmonteagudo/generator-hottowel-table/issues' },
17 silly publish   homepage: 'https://github.com/jlmonteagudo/generator-hottowel-table',
17 silly publish   _id: 'generator-hottowel-table@0.2.0',
17 silly publish   _shasum: '76b4ed639032d37b663c37ebf477b37892b5c385',
17 silly publish   _from: '.' }
18 silly mapToRegistry name generator-hottowel-table
19 silly mapToRegistry using default registry
20 silly mapToRegistry registry https://registry.npmjs.org/
21 silly mapToRegistry uri https://registry.npmjs.org/generator-hottowel-table
22 verbose publish registryBase https://registry.npmjs.org/
23 silly publish uploading /home/jlm/.npm/generator-hottowel-table/0.2.0/package.tgz
24 verbose request uri https://registry.npmjs.org/generator-hottowel-table
25 verbose request sending authorization for write operation
26 info attempt registry request try #1 at 09:31:29
27 verbose request id 4686a5e1e8ba7ca8
28 http request PUT https://registry.npmjs.org/generator-hottowel-table
29 http 404 https://registry.npmjs.org/generator-hottowel-table
30 verbose headers { date: 'Mon, 13 Apr 2015 07:31:31 GMT',
30 verbose headers   server: 'Apache',
30 verbose headers   'content-type': 'application/json',
30 verbose headers   'cache-control': 'max-age=0',
30 verbose headers   'content-length': '21',
30 verbose headers   'accept-ranges': 'bytes',
30 verbose headers   via: '1.1 varnish',
30 verbose headers   'x-served-by': 'cache-fra1224-FRA',
30 verbose headers   'x-cache': 'MISS',
30 verbose headers   'x-cache-hits': '0',
30 verbose headers   'x-timer': 'S1428910290.195835,VS0,VE1761',
30 verbose headers   'keep-alive': 'timeout=10, max=50',
30 verbose headers   connection: 'Keep-Alive' }
31 verbose request invalidating /home/jlm/.npm/registry.npmjs.org/generator-hottowel-table on PUT
32 error publish Failed PUT 404
33 verbose stack Error: Not found : generator-hottowel-table
33 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:247:14)
33 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:170:14)
33 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:360:22)
33 verbose stack     at Request.EventEmitter.emit (events.js:98:17)
33 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1202:14)
33 verbose stack     at Request.EventEmitter.emit (events.js:117:20)
33 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1150:12)
33 verbose stack     at IncomingMessage.EventEmitter.emit (events.js:117:20)
33 verbose stack     at _stream_readable.js:920:16
33 verbose stack     at process._tickCallback (node.js:415:13)
34 verbose statusCode 404
35 verbose pkgid generator-hottowel-table
36 verbose cwd /home/jlm/develop/node/projects/generators/generator-hottowel-table
37 error Linux 3.13.0-49-generic
38 error argv "node" "/usr/local/bin/npm" "publish" "./"
39 error node v0.10.21
40 error npm  v2.7.6
41 error code E404
42 error 404 Not found : generator-hottowel-table
42 error 404
42 error 404 'generator-hottowel-table' is not in the npm registry.
42 error 404 You should bug the author to publish it (or use the name yourself!)
42 error 404
42 error 404 Note that you can also install from a
42 error 404 tarball, folder, http url, or git url.
43 verbose exit [ 1, true ]
</pre>

However, if I check this URL https://registry.npmjs.org/generator-hottowel-table I get information regarding the package, so it seems that the package is in the registry.

I'm getting the same error if I run these commands:

- npm publish ./
- npm publish https://github.com/jlmonteagudo/generator-hottowel-table.git

I have also tried these commands in different computers, but I'm always getting the same error.

Do you know why I'm getting this error?

**Comment by kdemarest** [comment]
I am having the same problem with a package that has never been published before. I just signed up to npmjs, and can not reach the page that seems like it should have my moniker on it:
```
https://registry.npmjs.org/appsoma
```

Perhaps the problem is that my records don't fully exist at npmjs yet?

Here is the error:

```
npm ERR! publish Failed PUT 404
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "publish"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code E404

npm ERR! 404 Not found : webhooks
npm ERR! 404 
npm ERR! 404 'webhooks' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ken/webhooks/npm-debug.log
```

**Comment by kdemarest** [comment]
I resolved my problem. The words above: "'webhooks' is not in the npm registry." are not correct. There is in fact such an entry in the registry.  When I re-named by package to "appsoma-webhooks" the publish succeeded.
