### ISSUE TITLE
Getting the following error during npm install command

### ISSUE THREAD

**Issue by nbalcom** [npm/npm#7863]
Hi folks,
This is my first time working with Node and am not really a javascript guy so I'm understandably not sure what I'm doing wrong here. That being said here's what I'm trying to accomplish.

I'm trying to set up an application built by another company and get it running on a local machine in order to assist with html, css and image updates. I have a configuration document, but again I'm new to Node, Rock Mongo, MPM, etc so I'm not exactly sure what to be asking about.

I have Node installed and running and I have Mongo DB configured to start when my machine does. When I try to "npm install" in the root folder I get a series of instances being installed from registry.js.org, but when I get 3/4 of the way through I start getting errors. "getaddrinfo ENOTFOUND".

I assume this is due to files not being found. Possibly something is not sourced properly. I need to contact the company that made the app, but I want to understand what this error is so I can speak to it with a little bit more intelligence. I'm more of a front end coder so any input about anyone has would be appreciated.

I haven't found a good resource for Node questions yet so I'm hoping someone can shed a little light for me here. Thanks in advance.

**Comment by dileephell** [comment]
Mostly we got this error  due to we are behind the proxy. I have written the post here: you can check at : -- http://node-tricks.com/corporate-proxy/

**Comment by ehsalazar** [comment]
@nbalcom We haven’t heard back and we’re trying to clean up some issues. Were you able to config your proxy setting allowing for the install? If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.
