### ISSUE TITLE
binDependencies (for installing non-node runtimes)

### ISSUE THREAD

**Issue by maxogden** [npm/npm#7864]
a `binDependencies` feature has been requested twice before ([1](https://github.com/npm/npm/issues/6304), [2](https://github.com/npm/npm/issues/3739)), but this one is different.

use case is, say you want to distribute an app using a non-node runtime (e.g. `#!/usr/bin/env atom-shell`) through npm. here's how you have to instruct users to do it now:

```
npm install -g atom-shell # has to be -g here so its in PATH
git clone git://github.com/user/myapp.git
cd myapp
npm link # symlinks myapp into PATH
myapp foobar # works because #!/usr/bin/env atom-shell resolved ok
```

and here's the proposal:

if you put `binDependencies: {"atom-shell": "0.22.1"}` into `myapp`'s package.json, then during the `npm install` for `myapp` npm would first install `atom-shell` into the normal location (e.g. `myapp/node_modules/atom-shell` and `myapp/node_modules/.bin/atom-shell`).

it would then parse the `bin`s defined in `myapp`, lets say for this example there is one: `"bin": {"myapp": "cli.js"}`. It would parse the shebang out of `cli.js`, and if the executable matches one of the `binDependencies` then npm would rewrite your shebang to point to e.g. `myapp/node_modules/.bin/atom-shell`

that way, `head -n1 myapp/node_modules/.bin/myapp` would be `e.g. #!/usr/local/lib/node_modules/myapp/node_modules/.bin/atom-shell` (or wherever `atom-shell` got installed above)

an alternative approach to rewriting the shebangs could be to generate cross-platform executable scripts that do e.g. `PATH=/usr/local/lib/node_modules/myapp/node_modules/.bin:PATH /usr/local/lib/node_modules/.bin/myapp`. then the symlink from `npm link` would point at this 'proxy' executable instead of direclty at the `.bin/myapp` executable.

in the [atom-shell module](https://github.com/mafintosh/atom-shell) we are using npm to install [pre-built binaries](https://github.com/atom/atom-shell/releases/tag/v0.22.3) in a cross-platform way using [similar tricks](https://github.com/mafintosh/atom-shell/blob/aa795507965e5863cc8e5015e8bfa62f21ba4bd5/install.js#L23-L46).

I mean, how cool would it be if I could `npm install python27 ruby19 java --save-bin` ??? (also you could install specific node runtimes along with your CLI tool this way)

**Comment by timoxley** [comment]
This does open the gates to dependency hell. i.e.how do you resolve two modules depending on different binaries of atom-shell?

Can you elaborate on the reason you can't rely on an atom-shell binary installed locally into ./node_modules/.bin?

**Comment by nathan7** [comment]
@timoxley Their bin-scripts run in separate processes, so this is perfectly fine.

**Comment by maxogden** [comment]
> This does open the gates to dependency hell. i.e.how do you resolve two modules depending on different versions of atom-shell?

At install-time the shebang gets hardcoded to the correct atom-shell path, so there is no runtime resolution that happens. When the user executes the newly-linked bin it won't spawn node -- it will spawn whatever is in the shebang

> Can you elaborate on the reason you can't rely on an atom-shell binary installed locally into ./node_modules/.bin?

This proposal does rely on that bin, but the missing thing is the mechanism to make the executable that `npm link` produces point at that bin (hope that makes sense)

**Comment by timoxley** [comment]
Understood. I retract my comments.

**Comment by othiym23** [comment]
I need to let this marinate in my brain for a little while, but I see the usefulness of the feature. I don't think @iarna or I are going to have the time to work on this anytime soon, so this will probably have to be a `patch-welcome` kind of thing, and it probably makes sense to try to land this post-`npm@3` (as I really don't want to add non-essential new features to `npm@2` – I'm kinda sorta preparing it for LTS status so we can concentrate on moving on with `npm@3`).

**Comment by piranna** [comment]
> an alternative approach to rewriting the shebangs could be to generate cross-platform executable scripts that do e.g. PATH=/usr/local/lib/node_modules/myapp/node_modules/.bin:PATH /usr/local/lib/node_modules/.bin/myapp. then the symlink from npm link would point at this 'proxy' executable instead of direclty at the .bin/myapp executable.

If using ```npm start``` instead of the ```bin``` entry, npm will have already pre-set $PATH pointing first to ```node_modules/.bin``` where it will find first the locally installed engine instead of the global one, so it's another alternative. This would require to have installed ```npm``` (a normal thing, but not something we can trust since it can be able to uninstall itself), but probably could be crafted something based on the wrapper scripts and [npm-path](https://www.npmjs.com/package/npm-path), and better if it could be handled automatically by npm in a standard way... :-)

**Comment by othiym23** [comment]
This has been moved to the [npm roadmap](https://github.com/npm/npm/wiki/Roadmap), which we're using instead of the confusing `next-*` labels now.

**Comment by maxogden** [comment]
@othiym23 hmm I don't see it on there, the closest thing is `built-in support for precompiled dependencies` but that is different IMO

**Comment by othiym23** [comment]
Reload. ;)

**Comment by maxogden** [comment]
WOOT!

**Comment by iarna** [comment]
I don't think we need a new kind of dependency, but I would support rewriting the shebang line of binaries provided by the module when they references binaries provided by its dependencies, for example, with `node-bin`:


```
#!node
```

Would be rewritten into:

```
#!/path/to/your/module/node_modules/.bin/node
```

The npm cli team isn’t going to have time to work on this, this year. We would accept a patch to that did something along the lines of the above, that works without introducing a new dependency type and we have confidence won’t break existing users. As the cli team won’t be working on this, I’m going to close this, but thank you for articulating this need so clearly.
