### ISSUE TITLE
handle GitHub shorthand syntax consistently

### ISSUE THREAD

**Issue by othiym23** [npm/npm#7867]
Here are the apparently not-so-simple requirements:

1. GitHub shorthand syntax (`org/repo`) should be handled the same way by the CLI, regardless of whether it's passed in via the command line, or edited into `package.json`.
2. `--save`, `--save-dev`, and `--save-optional` should save GitHub dependencies _as shorthand syntax_, and not normalized to `git+whatever:` URLs, so that the symmetry of using them is preserved between the first and subsequent times you install them (shrinkwrapped GitHub dependencies should continue to resolve to `git+x:` URLs + resolved commit hashes).
3. Explicit Git URLs pointing to GitHub repos should preserve the protocol that was provided either on the command line or in `package.json`.
4. Explicit Git URLs pointing elsewhere should also be left alone, whether passed in on the command line, or via `package.json`.

We've made a few passes at this, which can be seen in #2556, #6978, #7121, #7486, #7630, #7766, and #7829. It's time to nail this down once and for all, and to get the right set of tests around it to prevent it from regressing in the future (although that is proving to be hard to do).

**Comment by iarna** [comment]
https://github.com/npm/npm/pull/7873 brings in the updated modules, which is the first step in this.
