### ISSUE TITLE
Using node to install appium,it's failed

### ISSUE THREAD

**Issue by Huo613** [npm/npm#7869]
It's failed to install Appium .The node version is v0.12.2.I want to install appium using node.The commond is:$ npm install -g appium    $ appium & while It's failed.The log is shown:

```
29 error Windows_NT 6.1.7601
30 error argv "E:\\Android\\appium\\nodejs\\\\node.exe" "E:\\Android\\appium\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "appium"
31 error node v0.12.2
32 error npm  v2.7.4
33 error Unexpected end of input
```

**Comment by KenanY** [comment]
@Huo613 I only see 5 lines of the log... could you upload the _entire_ `npm-debug.log` as a [gist](https://gist.github.com)?

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
