### ISSUE TITLE
Unable to install phone gap in MAC OS Version 10.10

### ISSUE THREAD

**Issue by dheeraj-s** [npm/npm#7871]
When Install than getting below error:

```
dheerajs-imac:PhoneGap rahul$ sudo npm install -g PhoneGap
Password:
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "PhoneGap"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! error:0906D06C:PEM routines:PEM_read_bio:no start line
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rahul/PhoneGap/npm-debug.log
```

Please resolve any one :(

**Comment by dheeraj-s** [comment]
LOG ERROR:

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', '-g', 'PhoneGap' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 silly cache add args [ 'PhoneGap', null ]
5 verbose cache add spec PhoneGap
6 silly cache add parsed spec { raw: 'PhoneGap',
6 silly cache add   scope: null,
6 silly cache add   name: 'PhoneGap',
6 silly cache add   rawSpec: '',
6 silly cache add   spec: '*',
6 silly cache add   type: 'range' }
7 verbose addNamed PhoneGap@*
8 silly addNamed semver.valid null
9 silly addNamed semver.validRange *
10 silly addNameRange { name: 'PhoneGap', range: '*', hasData: false }
11 silly mapToRegistry name PhoneGap
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry https://registry.npmjs.org/
14 silly mapToRegistry uri https://registry.npmjs.org/PhoneGap
15 verbose addNameRange registry:https://registry.npmjs.org/PhoneGap not in flight; fetching
16 verbose request uri https://registry.npmjs.org/PhoneGap
17 verbose request no auth needed
18 info attempt registry request try #1 at 12:59:15 PM
19 verbose request id 6c818be74b2f5c61
20 http request GET https://registry.npmjs.org/PhoneGap
21 verbose stack Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
21 verbose stack     at Error (native)
21 verbose stack     at Object.createSecureContext (_tls_common.js:108:19)
21 verbose stack     at Object.exports.connect (_tls_wrap.js:850:21)
21 verbose stack     at Agent.createConnection (https.js:82:14)
21 verbose stack     at Agent.createSocket (_http_agent.js:194:16)
21 verbose stack     at Agent.addRequest (_http_agent.js:166:23)
21 verbose stack     at new ClientRequest (_http_client.js:154:16)
21 verbose stack     at Object.exports.request (http.js:49:10)
21 verbose stack     at Object.exports.request (https.js:136:15)
21 verbose stack     at Request.start (/usr/local/lib/node_modules/npm/node_modules/request/request.js:904:30)
22 verbose cwd /Users/rahul/PhoneGap
23 error Darwin 14.0.0
24 error argv "node" "/usr/local/bin/npm" "install" "-g" "PhoneGap"
25 error node v0.12.0
26 error npm  v2.5.1
27 error error:0906D06C:PEM routines:PEM_read_bio:no start line
28 error If you need help, you may report this error at:
28 error     <http://github.com/npm/npm/issues>
29 verbose exit [ 1, true ]

**Comment by ehsalazar** [comment]
@dheeraj-s We're moving through some of the older issues. You've likely moved beyond this issue but are you behind a proxy?

**Comment by ehsalazar** [comment]
As we haven't heard back, I've closed out this issue. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.
