### ISSUE TITLE
git+https urls don't seem to be honoured in 2.7.5

### ISSUE THREAD

**Issue by davetayls** [npm/npm#7872]
My builds started breaking in 2.7.5 saying they don't have permission on private dependencies with the url structure:

`git+https://user:pass@bitbucket.org/team/repo.git`

In the logs it looks like 

```
npm ERR! git clone --template=/app/.npm/_git-remotes/_templates --mirror ssh://git@bitbucket.org/team/repo.git /app/.npm/_git-remotes/ssh-git-bitbucket-org-team-repo-git-9307203e
npm ERR! git clone --template=/app/.npm/_git-remotes/_templates --mirror ssh://git@bitbucket.org/team/repo.git /app/.npm/_git-remotes/ssh-git-bitbucket-org-team-repo-git-9307203e: Initialized empty Git repository in /app/.npm/_git-remotes/ssh-git-bitbucket-org-team-repo-git-9307203e/
npm ERR! git clone --template=/app/.npm/_git-remotes/_templates --mirror ssh://git@bitbucket.org/team/repo.git /app/.npm/_git-remotes/ssh-git-bitbucket-org-team-repo-git-9307203e: 
npm ERR! git clone --template=/app/.npm/_git-remotes/_templates --mirror ssh://git@bitbucket.org/team/repo.git /app/.npm/_git-remotes/ssh-git-bitbucket-org-team-repo-git-9307203e: Host key verification failed.
npm ERR! git clone --template=/app/.npm/_git-remotes/_templates --mirror ssh://git@bitbucket.org/team/repo.git /app/.npm/_git-remotes/ssh-git-bitbucket-org-team-repo-git-9307203e: fatal: The remote end hung up unexpectedly
```

It seems like it is not using the correct https url with the username and password.

I rolled back to using npm `2.5` and the issues went away

**Comment by KenanY** [comment]
@davetayls Does this happen on [`npm@2.7.6`](https://github.com/npm/npm/releases/tag/v2.7.6) as well?

**Comment by kanongil** [comment]
I have the same issue, which i replicate on 2.7.6 as well. Note that I'm using the shrinkwrap feature, where it even though the url is directly specified in the package.json using `git+https`, it has recorded it now remembered as `git+ssh`.

**Comment by davetayls** [comment]
Hey. Sorry for the late reply, it went mental yesterday. I'm using the shrink wrap feature as well. I'll try the build with 2.7.6 this morning and feed back.

**Comment by cgreening** [comment]
Seeing this on heroku as well. Forced it to use the 2.7.6 version and it still fails.

**Comment by cgreening** [comment]
Rolled back npm to version 2.7.3 and it works fine, so I guess it's a problem introduced in 2.7.4

**Comment by davetayls** [comment]
I'm finding it quite tricky to test this without causing an issue to the testers, i think it works locally because i have the correct ssh keys for the ssh url to work. seems @kanongil and @cgreening can replicate as well which is useful :+1: thanks

**Comment by vschoettke** [comment]
+1 Still a problem with npm@2.7.6

**Comment by iarna** [comment]
This should be fixed in npm@2.8.0 (current npm@next). Could you verify that it works for you?

**Comment by cgreening** [comment]
Better, but it seems be missing the credentials that should be passed in the https url

```
 Npm version changed (2.7.3 => 2.8.0); invalidating cache
       Installing node modules
       npm ERR! git clone --template=/app/.npm/_git-remotes/_templates --mirror https://bitbucket.org/cgreening/noduleio.git /app/.npm/_git-remotes/https-bitbucket-org-cgreening-noduleio-git-5d0f1af7: Cloning into bare repository '/app/.npm/_git-remotes/https-bitbucket-org-cgreening-noduleio-git-5d0f1af7'...
       npm ERR! git clone --template=/app/.npm/_git-remotes/_templates --mirror https://bitbucket.org/cgreening/noduleio.git /app/.npm/_git-remotes/https-bitbucket-org-cgreening-noduleio-git-5d0f1af7: fatal: Authentication failed for 'https://bitbucket.org/cgreening/noduleio.git/'
```

In my package json the dependencies look like:

```
"noduleio": "git+https://cgreening:__PASSWOTRD_REDACTED__@bitbucket.org/cgreening/noduleio.git"
```

**Comment by othiym23** [comment]
This is one of the paths that I apparently didn't test enough – I can replicate that the credentials are getting stripped from the URLs and am working on a fix.

**Comment by othiym23** [comment]
The fix for @cgreening's issue landed in 15efe124753257728a0ddc64074fa5a4b9c2eb30, and after banging on it some more, I'm confident that this is something that `npm@2.8.1` (out very shortly) addresses.

**Comment by davetayls** [comment]
Thanks very much :)

**Comment by cgreening** [comment]
Works on 2.8.1

Thanks!

**Comment by iMerica** [comment]
I'm still seeing this. What is the preferred way of downgrading npm to a specific version?

**Comment by KenanY** [comment]
@iMerica What version are you still seeing this on? If you want to downgrade to, say, 2.7.3 for whatever reason:

``` sh
$ npm install -g npm@2.7.3
```
