### ISSUE TITLE
npm ERR! Attempt to unlock /usr/lib/node_modules/grunt-cli, which hasn't been locked

### ISSUE THREAD

**Issue by ThomasVanThillo** [npm/npm#7874]
on xubuntu 14.0.4 trying to install this:

```
sudo npm install -g grunt-cli
```

I get the error: 

```
npm WARN locking Error: EACCES, open '/home/thomas/.npm/_locks/grunt-cli-e8d57df188d50057.lock'
npm WARN locking  /home/thomas/.npm/_locks/grunt-cli-e8d57df188d50057.lock failed { [Error: EACCES, open '/home/thomas/.npm/_locks/grunt-cli-e8d57df188d50057.lock']
npm WARN locking   errno: 3,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/home/thomas/.npm/_locks/grunt-cli-e8d57df188d50057.lock' }
npm ERR! Linux 3.16.0-33-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "grunt-cli"
npm ERR! node v0.10.37
npm ERR! npm  v2.7.5

npm ERR! Attempt to unlock /usr/lib/node_modules/grunt-cli, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/thomas/npm-debug.log
```

please help!

**Comment by KenanY** [comment]
@VanThilloThomas Could you try:

``` sh
$ sudo chown -R $(whoami) "$HOME/.npm"
```

**Comment by VanThilloThomas** [comment]
this results in nothing...

**Comment by MeisterWebzr** [comment]
I too have run into this error while trying to run gulp, any updates would be very helpful.

**Comment by KenanY** [comment]
@ThomasVanThillo @MeisterWebzr hey, I know it's been like over a year now and sorry I never followed up. Is this still an issue for either of you?

**Comment by MeisterWebzr** [comment]
No, thank for reaching out.

Otto Burroughs | BS Web Designer & Developer | meister@fullsail.edu<mailto:meister@fullsail.edu> | (714) 797-7384

On Mar 24, 2017, at 7:22 AM, Kenan Yildirim <notifications@github.com<mailto:notifications@github.com>> wrote:


@ThomasVanThillo<https://github.com/ThomasVanThillo> @MeisterWebzr<https://github.com/MeisterWebzr> hey, I know it's been like over a year now and sorry I never followed up. Is this still an issue for either of you?
