### ISSUE TITLE
EPERM error, when trying install grunt-contrib-imagemin

### ISSUE THREAD

**Issue by BaNdErOzZz** [npm/npm#7881]
EPERM error, when trying install grunt-contrib-imagemin
-----------------------
```
26003 verbose stack Error: EPERM, open '/app/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin/node_modules/bin-wrapper/node_modules/is-path-global/node_modules/is-path-inside/node_modules/path-is-inside/package.json'
26003 verbose stack     at Error (native)
26004 verbose cwd /app
26005 error Linux 3.2.0-4-amd64
26006 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "grunt-contrib-imagemin"
26007 error node v0.12.2
26008 error npm  v2.7.4
26009 error path /app/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin/node_modules/bin-wrapper/node_modules/is-path-global/node_modules/is-path-inside/node_modules/path-is-inside/package.json
26010 error code EPERM
26011 error errno -1
26012 error Error: EPERM, open '/app/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin/node_modules/bin-wrapper/node_modules/is-path-global/node_modules/is-path-inside/node_modules/path-is-inside/package.json'
26012 error     at Error (native)
26012 error  { [Error: EPERM, open '/app/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin/node_modules/bin-wrapper/node_modules/is-path-global/node_modules/is-path-inside/node_modules/path-is-inside/package.json']
26012 error   errno: -1,
26012 error   code: 'EPERM',
26012 error   path: '/app/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin/node_modules/bin-wrapper/node_modules/is-path-global/node_modules/is-path-inside/node_modules/path-is-inside/package.json' }
26013 error Please try running this command again as root/Administrator.
26014 verbose exit [ -1, true ]
```
--
Install as root and with sudo.
Also used `npm cache clean`.

**Comment by tamilvjm** [comment]
Are you using NTFS file system?

**Comment by BaNdErOzZz** [comment]
Yes, NTFS. But trying to run on vagrant virtual maschine - "Linux packer-virtualbox-iso 3.2.0-4-amd64 #1 SMP Debian 3.2.57-3 x86_64 GNU/Linux"

**Comment by smikes** [comment]
I think this may be a known problem with maximum file lengths -- if Vagrant uses one version of the Windows filesystem APIs, the max file length is 256 characters.  Alternatively, it may genuinely be a permission error in your filesystem -- what have you done to rule that out?

**Comment by BaNdErOzZz** [comment]
Install as root and install as user with sudo. Did you mean this?

**Comment by smikes** [comment]
That addresses any possible permissions problems from inside the `vagrant` system; I am also curious whether NTFS permissions are coming into play.  From the Windows side, can you create the directory that corresponds to

```
/app/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin/node_modules/bin-wrapper/node_modules/is-path-global/node_modules/is-path-inside/node_modules/path-is-inside/
```

And once created, can you create files in it?

**Comment by BaNdErOzZz** [comment]
After `npm install grunt-contrib-imagemin` path is - `/app/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin/node_modules/bin-wrapper/node_modules`, without `is-path-global/node_modules/is-path-inside/node_modules/path-is-inside/`.  And yes, I can create files and dirs inside this path.

**Comment by Gimmo** [comment]
I have the same error in Windows and Debian. It's not a problem of NPM. First I resolve this by installing "deep" modules manually. Later I found that the reason of error is too long file path names (260 for Win and 255 in Linux).

**Comment by smikes** [comment]
@BaNdErOzZz Is this still a problem for you?

Gimmo, thanks for your suggestion.  We definitely see problems with long, deeply-nested paths.  The next version of `npm` -- `npm@3` -- will handle this a lot better because it will deduplicate and flatten module hierarchies by default.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved.
