### ISSUE TITLE
Error: No compatible version found: bytes@'^1.0.0'

### ISSUE THREAD

**Issue by D3Rnatch** [npm/npm#7883]
Hi, i am using a WIN7 x64 and am running a ROS-package (called HARK).
Can anyone help me ?
Thx,

Best

163 silly lockFile 2c051c6a-grunt-contrib-uglify-0-4-0 grunt-contrib-uglify@^0.4.0
164 verbose lock grunt-contrib-uglify@^0.4.0 C:\Users\212454547\AppData\Roaming\npm-cache\2c051c6a-grunt-contrib-uglify-0-4-0.lock
165 verbose url raw sqlite3/2.1.19
166 verbose url resolving [ 'https://registry.npmjs.org/', './sqlite3/2.1.19' ]
167 verbose url resolved https://registry.npmjs.org/sqlite3/2.1.19
168 info trying registry request attempt 1 at 16:13:16
169 http GET https://registry.npmjs.org/sqlite3/2.1.19
170 verbose url raw bytes
171 verbose url resolving [ 'https://registry.npmjs.org/', './bytes' ]
172 verbose url resolved https://registry.npmjs.org/bytes
173 info trying registry request attempt 1 at 16:13:16
174 http GET https://registry.npmjs.org/bytes
175 verbose url raw grunt
176 verbose url resolving [ 'https://registry.npmjs.org/', './grunt' ]
177 verbose url resolved https://registry.npmjs.org/grunt
178 info trying registry request attempt 1 at 16:13:16
179 http GET https://registry.npmjs.org/grunt
180 info addNameTag [ 'grunt-contrib-watch', '^0.6.1' ]
181 info addNameTag [ 'grunt-contrib-cssmin', '^0.9.0' ]
182 info addNameTag [ 'grunt-contrib-jshint', '^0.9.2' ]
183 info addNameTag [ 'grunt-contrib-qunit', '^0.4.0' ]
184 info addNameTag [ 'grunt-contrib-uglify', '^0.4.0' ]
185 verbose url raw grunt-contrib-cssmin
186 verbose url resolving [ 'https://registry.npmjs.org/', './grunt-contrib-cssmin' ]
187 verbose url resolved https://registry.npmjs.org/grunt-contrib-cssmin
188 info trying registry request attempt 1 at 16:13:16
189 http GET https://registry.npmjs.org/grunt-contrib-cssmin
190 verbose url raw grunt-contrib-watch
191 verbose url resolving [ 'https://registry.npmjs.org/', './grunt-contrib-watch' ]
192 verbose url resolved https://registry.npmjs.org/grunt-contrib-watch
193 info trying registry request attempt 1 at 16:13:16
194 http GET https://registry.npmjs.org/grunt-contrib-watch
195 verbose url raw grunt-contrib-jshint
196 verbose url resolving [ 'https://registry.npmjs.org/', './grunt-contrib-jshint' ]
197 verbose url resolved https://registry.npmjs.org/grunt-contrib-jshint
198 info trying registry request attempt 1 at 16:13:16
199 http GET https://registry.npmjs.org/grunt-contrib-jshint
200 verbose url raw grunt-contrib-qunit
201 verbose url resolving [ 'https://registry.npmjs.org/', './grunt-contrib-qunit' ]
202 verbose url resolved https://registry.npmjs.org/grunt-contrib-qunit
203 info trying registry request attempt 1 at 16:13:16
204 http GET https://registry.npmjs.org/grunt-contrib-qunit
205 verbose url raw grunt-contrib-uglify
206 verbose url resolving [ 'https://registry.npmjs.org/', './grunt-contrib-uglify' ]
207 verbose url resolved https://registry.npmjs.org/grunt-contrib-uglify
208 info trying registry request attempt 1 at 16:13:16
209 http GET https://registry.npmjs.org/grunt-contrib-uglify
210 http 200 https://registry.npmjs.org/bytes
211 silly registry.get cb [ 200,
211 silly registry.get   { date: 'Wed, 08 Apr 2015 14:13:17 GMT',
211 silly registry.get     server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
211 silly registry.get     etag: '"CDSKQ9SJMZ5EMN1RD9TC0UMV8"',
211 silly registry.get     'content-type': 'application/json',
211 silly registry.get     'cache-control': 'max-age=60',
211 silly registry.get     'content-length': '6627',
211 silly registry.get     'accept-ranges': 'bytes',
211 silly registry.get     via: '1.1 varnish',
211 silly registry.get     age: '21',
211 silly registry.get     'x-served-by': 'cache-lcy1127-LCY',
211 silly registry.get     'x-cache': 'HIT',
211 silly registry.get     'x-cache-hits': '2',
211 silly registry.get     'x-timer': 'S1428502397.058132,VS0,VE0',
211 silly registry.get     vary: 'Accept',
211 silly registry.get     'keep-alive': 'timeout=10, max=50',
211 silly registry.get     connection: 'Keep-Alive' } ]
212 silly lockFile 4ae3088b-bytes-1-0-0 bytes@^1.0.0
213 silly lockFile 4ae3088b-bytes-1-0-0 bytes@^1.0.0
214 error Error: No compatible version found: bytes@'^1.0.0'
214 error Valid install targets:
214 error ["0.0.1","0.1.0","0.2.0","0.2.1","0.3.0","1.0.0"]
214 error     at installTargetsError (C:\Program Files\nodejs\node_modules\npm\lib\cache.js:682:10)
214 error     at C:\Program Files\nodejs\node_modules\npm\lib\cache.js:597:10
214 error     at saved (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\get.js:138:7)
214 error     at Object.oncomplete (fs.js:93:15)
215 error If you need help, you may report this log at:
215 error     <http://github.com/isaacs/npm/issues>
215 error or email it to:
215 error     <npm-@googlegroups.com>
216 error System Windows_NT 6.1.7601
217 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
218 error cwd C:\ProgramData\HARK\hark-Designer
219 error node -v v0.10.0
220 error npm -v 1.2.14
221 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@D3Rnatch 

``` sh
$ git show v1.2.14
tag v1.2.14
Tagger: isaacs <i@izs.me>
Date:   Sat Mar 9 08:39:43 2013 -0800
```

`npm@1.2.14` was released 2 years ago and is no longer supported. I am willingly to bet that [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows) will solve your issue. The `^` semver operator is newer than your version of `npm`, hence your version of `npm` throws an error when it sees such an operator.

**Comment by D3Rnatch** [comment]
And this was it !
Thx a LOOOOOOOOOOT.

2015-04-08 17:00 GMT+02:00 Kenan Yildirim <notifications@github.com>:

> @D3Rnatch <https://github.com/D3Rnatch>
>
> $ git show v1.2.14
> tag v1.2.14
> Tagger: isaacs <i@izs.me>
> Date:   Sat Mar 9 08:39:43 2013 -0800
>
> npm@1.2.14 was released 2 years ago and is no longer supported. I am
> willingly to bet that upgrading
> <https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows>
> will solve your issue. The ^ semver operator is newer than your version
> of npm, hence your version of npm throws an error when it sees such an
> operator.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/npm/npm/issues/7883#issuecomment-90942365>.
>



-- 
﻿[image: JEECE]Alexandre BRAND
Chef de Projet
Junior-Entreprise de l'ECE Paris
 alexandre.brand@jeece.fr
<guillaume.bignon@jeece.fr?%20&subject=[JEECE]%20Objet%20de%20votre%20mail.%20&body=Votre%20message.>

 06 78 45 98 17
[image: F]  <https://www.facebook.com/JEECE.JE>[image: T]
<https://twitter.com/JuniorJEECE>[image: G+]
<https://plus.google.com/106376338307875330368/posts>[image: L]
<http://www.linkedin.com/company/jeece>[image: V]
<http://fr.viadeo.com/fr/profile/junior.jeece>[image: Y]
<http://www.youtube.com/user/JuniorJEECE>contact@jeece.fr
<contact@jeece.fr?%20&bcc=dsi@jeece.fr%20&subject=[JEECE]%20Objet%20de%20votre%20mail.%20&body=Votre%20message.>
 | 01 45 49 19 99 | www.jeece.fr

**Comment by othiym23** [comment]
Closing as resolved.
