### ISSUE TITLE
Error with npm install

### ISSUE THREAD

**Issue by panchowtf** [npm/npm#7884]
trying `npm install` on concat-map i get this error i already tried adding `sudo`
```BASH
 npm install concat-map
npm WARN locking Error: EACCES, open '/Users/mercadotecnia/.npm/_locks/concat-map-a127112b4f6ee84c.lock'
npm WARN locking  /Users/mercadotecnia/.npm/_locks/concat-map-a127112b4f6ee84c.lock failed { [Error: EACCES, open '/Users/mercadotecnia/.npm/_locks/concat-map-a127112b4f6ee84c.lock']
npm WARN locking   errno: 3,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/mercadotecnia/.npm/_locks/concat-map-a127112b4f6ee84c.lock' }
npm ERR! Darwin 11.4.2
npm ERR! argv "node" "/usr/local/bin/npm" "install" "concat-map"
npm ERR! node v0.10.35
npm ERR! npm  v2.7.0

npm ERR! Attempt to unlock /Users/mercadotecnia/Desktop/Sitios/bill/node_modules/concat-map, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
```

**Comment by KenanY** [comment]
@panchowtf Could you try the following?

``` sh
$ sudo chown -R $(whoami) "$HOME/.npm"
```

**Comment by panchowtf** [comment]
it worked
thanks

**Comment by tamirlancomas** [comment]
help me

npm WARN locking Error: EACCES, open '/home/user/.npm/_locks/debug-0d0df2f43f9ec1bb.lock'
npm WARN locking     at Error (native)
npm WARN locking  /home/user/.npm/_locks/debug-0d0df2f43f9ec1bb.lock failed { [Error: EACCES, open '/home/user/.npm/_locks/debug-0d0df2f43f9ec1bb.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/home/user/.npm/_locks/debug-0d0df2f43f9ec1bb.lock' }
npm ERR! Linux 3.16.0-34-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4

npm ERR! Attempt to unlock /home/user/pigsty-moloch-plugin/node_modules/debug, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/home/user/.npm/_locks/node-syslog-logger-simpl-487657484c8bef5f.lock'
npm WARN locking     at Error (native)
npm WARN locking  /home/user/.npm/_locks/node-syslog-logger-simpl-487657484c8bef5f.lock failed { [Error: EACCES, open '/home/user/.npm/_locks/node-syslog-logger-simpl-487657484c8bef5f.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/home/user/.npm/_locks/node-syslog-logger-simpl-487657484c8bef5f.lock' }
npm ERR! Linux 3.16.0-34-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4

npm ERR! Attempt to unlock /home/user/pigsty-moloch-plugin/node_modules/node-syslog-logger-simple, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/home/user/.npm/_locks/hashtable-bf79130dba9934ab.lock'
npm WARN locking     at Error (native)
npm WARN locking  /home/user/.npm/_locks/hashtable-bf79130dba9934ab.lock failed { [Error: EACCES, open '/home/user/.npm/_locks/hashtable-bf79130dba9934ab.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/home/user/.npm/_locks/hashtable-bf79130dba9934ab.lock' }
npm ERR! Linux 3.16.0-34-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4

npm ERR! Attempt to unlock /home/user/pigsty-moloch-plugin/node_modules/hashtable, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/home/user/.npm/_locks/pigsty-plugin-fb0f74df4f3fdd41.lock'
npm WARN locking     at Error (native)
npm WARN locking  /home/user/.npm/_locks/pigsty-plugin-fb0f74df4f3fdd41.lock failed { [Error: EACCES, open '/home/user/.npm/_locks/pigsty-plugin-fb0f74df4f3fdd41.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/home/user/.npm/_locks/pigsty-plugin-fb0f74df4f3fdd41.lock' }
npm ERR! Linux 3.16.0-34-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4

npm ERR! Attempt to unlock /home/user/pigsty-moloch-plugin/node_modules/pigsty-plugin, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 3.16.0-34-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4

npm ERR! Uncaught, unspecified "error" event.
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/pigsty-moloch-plugin/npm-debug.log
user@ubuntu:~/pigsty-moloch-plugin$ npm install https://github.com/hillar/pigsty-moloch-plugin/archive/master.tar.gz
npm WARN locking Error: EACCES, open '/home/user/.npm/_locks/pigsty-moloch-plugin-afb92b903ea340a5.lock'
npm WARN locking     at Error (native)
npm WARN locking  /home/user/.npm/_locks/pigsty-moloch-plugin-afb92b903ea340a5.lock failed { [Error: EACCES, open '/home/user/.npm/_locks/pigsty-moloch-plugin-afb92b903ea340a5.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/home/user/.npm/_locks/pigsty-moloch-plugin-afb92b903ea340a5.lock' }
npm ERR! Linux 3.16.0-34-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "https://github.com/hillar/pigsty-moloch-plugin/archive/master.tar.gz"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4

npm ERR! Attempt to unlock /home/user/pigsty-moloch-plugin/node_modules/pigsty-moloch-plugin, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 3.16.0-34-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "https://github.com/hillar/pigsty-moloch-plugin/archive/master.tar.gz"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4

npm ERR! Uncaught, unspecified "error" event.
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/pigsty-moloch-plugin/npm-debug.log

**Comment by KenanY** [comment]
@tamirlancomas Did you try [what I told](https://github.com/npm/npm/issues/7884#issuecomment-90936349) @panchowtf?

**Comment by iarna** [comment]
Closing this as @panchowtf's problem is resolved. @tamirlancomas if you find the suggest here doesn't help, please feel free to open a new ticket.

**Comment by bank1913** [comment]
trying  npm install -g narf     =>  Error  

npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "narf"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! path /Users/warachaikaewpoo/.node/bin/narf
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, unlink '/Users/warachaikaewpoo/.node/bin/narf'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, unlink '/Users/warachaikaewpoo/.node/bin/narf']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/Users/warachaikaewpoo/.node/bin/narf' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! error rolling back Error: EACCES, unlink '/Users/warachaikaewpoo/.node/bin/narf'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EACCES, unlink '/Users/warachaikaewpoo/.node/bin/narf']
npm ERR! error rolling back   errno: -13,
npm ERR! error rolling back   code: 'EACCES',
npm ERR! error rolling back   path: '/Users/warachaikaewpoo/.node/bin/narf' }

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/warachaikaewpoo/npm-debug.log

**Comment by iarna** [comment]
@bank1913 If you'd like help with this, I recommend opening a new issue. Comments on old closed issues usually go unnoticed.
