### ISSUE TITLE
Multiple npm install fails (EPERM error)

### ISSUE THREAD

**Issue by artemsvirskyi** [npm/npm#7885]
Im trying to install multiple packages in different child processes. And all the packages have some common dependency(browserify in my case).

	example
	|
	|_pkg1
	|   |_browserify
	|
	|_pkg2
	|   |_browserify
	|
	|_pkg3
	|   |_browserify
	|
	|_run.js

run.js:

	var packages = ['pkg1', 'pkg2', 'pkg3'];

	packages.forEach(function(pkg){
		exec('npm install ./' + pkg);
	});

And `node run.js` fails with log

		npm ERR! Windows_NT 6.3.9600
		npm ERR! argv "c:\\Program Files\\nodejs\\\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i
		nstall" "./pkg3"
		npm ERR! node v0.12.2
		npm ERR! npm  v2.7.4
		npm ERR! path C:\Users\Artem\AppData\Roaming\npm-cache\acorn\0.9.0\package\package.json
		npm ERR! code EPERM
		npm ERR! errno -4048

		npm ERR! Error: EPERM, rename 'C:\Users\Artem\AppData\Roaming\npm-cache\acorn\0.9.0\package\package.json'
		npm ERR!     at Error (native)
		npm ERR!  { [Error: EPERM, rename 'C:\Users\Artem\AppData\Roaming\npm-cache\acorn\0.9.0\package\package.json']
		npm ERR!   errno: -4048,
		npm ERR!   code: 'EPERM',
		npm ERR!   path: 'C:\\Users\\Artem\\AppData\\Roaming\\npm-cache\\acorn\\0.9.0\\package\\package.json',
		npm ERR!   parent: 'syntax-error' }
		npm ERR!
		npm ERR! Please try running this command again as root/Administrator.

Example: https://github.com/SakerONE/multiple-npm-install

**Comment by Ann-Dederkal** [comment]
+1 for this issue
It's very critical for our project. Please, fix it.

**Comment by tamirlancomas** [comment]
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.16.0-30-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /pigsty/node_modules/unified2/node_modules/pcap
gyp ERR! node -v v0.10.37
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

npm ERR! pcap@0.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pcap@0.3.3 install script.
npm ERR! This is most likely a problem with the pcap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
i have a problem help me

npm ERR!     npm owner ls pcap
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.16.0-30-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /pigsty
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0


for example: https://github.com/hillar/pigsty-moloch-plugin

**Comment by iarna** [comment]
Is there a reason you can't rewrite your run.js as:

```
var packages = ['pkg1', 'pkg2', 'pkg3'];

exec('npm install ' + packages.map(function (pkg) { return './' + pkg }).join(' '))
```

**Comment by SakerONE** [comment]
We needed to install packages in different child processes. Now we are looking for another approach. But this is still a bug..

**Comment by SakerONE** [comment]
Ok, that was, probably, useless example. Here is another one. 

https://github.com/SakerONE/multiple-npm-install2

Now npm install executes in each package directory.

    packages.forEach(function(pkg){
        exec('npm install', {cwd: pkg});
    });

And error is the same.

**Comment by bapti** [comment]
I'm seeing this same error running through our teamcity build agents, I've been monitoring it to see if there's file locks on the files that can't be renamed but I can't see anything.  When I remote onto the agent where the npm install fails it always passes when I run the command directly through a command prompt.  It's a bit odd, would be great if it's possible to get to the bottom of it.  

In our case it's just a single `npm install` - there should only be a single instance of npm running at a time.
