### ISSUE TITLE
why npm search failed?

### ISSUE THREAD

**Issue by chapgaga** [npm/npm#7886]
```

C:\>npm search -v express
2.7.5

C:\>npm search  express
No match found for "express"
```
but npm info express works, why?

```
  engines: { node: '>= 0.10.0' },
  files: [ 'LICENSE', 'History.md', 'Readme.md',
  scripts:
   { test: 'mocha --require test/support/env --r
eptance/',
     'test-ci': 'istanbul cover node_modules/moc
t/support/env --reporter spec --check-leaks test
     'test-cov': 'istanbul cover node_modules/mo
eporter dot --check-leaks test/ test/acceptance/
     'test-tap': 'mocha --require test/support/e
tance/' },
  gitHead: 'f56463f8bf24015736978d0dc4d398fa22a9
  dist:
   { shasum: '6b9d94aec5ae03270d86d390c277a8c5a5
     size: 47599,
     noattachment: false,
     tarball: 'http://registry.npm.taobao.org/ex
  directories: {},
  publish_time: 1426629893210 }


C:\>npm info express
```

**Comment by smikes** [comment]
`npm search` on the command line is broken right now.  Sometimes  `npm search` is able to successfullly download the 90+ MB file it needs, but sometimes this download fails.  So `npm search` sometimes results in partial or incorrect results.

`npm view` on the other hand, always goes to the registry and reports on the current status of a module.

For now, we recommend using the `Search` function on the website at https://www.npmjs.com until we are able to fix the search functionality.

**Comment by smikes** [comment]
Ref https://github.com/npm/npm/issues/6016

**Comment by chapgaga** [comment]
@smikes what is the difference between npm info and npm view, seems they return the same result

**Comment by smikes** [comment]
npm info and npm view do the same thing.

**Comment by othiym23** [comment]
Closing as a duplicate in favor of #6016. Sorry! :/ I'm not happy with the state of search on the CLI right now, but fixing it is a project for the whole team, and we have a bunch of other things to get to first.
