### ISSUE TITLE
unnamed binary path for globally-installed scoped modules is weird

### ISSUE THREAD

**Issue by isaacs** [npm/npm#7890]
If you just have a `"bin":"foo.js"` in your package.json, then you end up with a really weird result:

```
$ cat package.json
{"name":"@isaacs/foo","bin":"foo.js","version":"1.2.3"}

$ cat foo.js
#!/usr/bin/env node
console.log("foo")

$ npm i -g
/usr/local/bin/@isaacs/foo -> /usr/local/lib/node_modules/@isaacs/foo/foo.js
@isaacs/foo@1.2.3 /usr/local/lib/node_modules/@isaacs/foo

$ @isaacs/foo
bash: @isaacs/foo: No such file or directory

$ /usr/local/bin/@isaacs/foo
foo

$ PATH=/usr/local/bin/@isaacs:$PATH foo
foo
```

It seems like it should strip the scope off of the default bin key so that it's just `foo` instead of `@isaacs/foo` there?

**Comment by iarna** [comment]
Not just globals, this has the same problem for local installs too, as if you install `@isaacs/foo` as a dep, and then have a script that tries to `run` it, you basically can't win as neither `foo` nor `@isaacs/foo` can work.

```
$ find node_modules/.bin/
node_modules/.bin/
node_modules/.bin/@isaacs
node_modules/.bin/@isaacs/foo
```
