### ISSUE TITLE
npm login/adduser is not working

### ISSUE THREAD

**Issue by nodeofcode** [npm/npm#7891]
I am trying to login into system with npm account.

I re-checked and carefully typed the username,password and email so many times.
 
node -v v0.10.25
npm -v 1.3.10

Each time i get this error

 Error: Unknown error while authenticating : -/user/org.couchdb.user:<npmusername>
npm ERR!     at RegClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:272:14)
npm ERR!     at Request.self.callback (/usr/lib/nodejs/request/index.js:148:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/index.js:896:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/lib/nodejs/request/index.js:847:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

**Comment by ecwyne** [comment]
@nodeofcode did you figure this out? I'm having the same issue

**Comment by ecwyne** [comment]
Oh, looks like I just had to update my npm version! Worked like a charm!
