### ISSUE TITLE
Not able to read dependencies

### ISSUE THREAD

**Issue by bhargavpanth** [npm/npm#7897]

**Comment by KenanY** [comment]
@bhargavpanth Sorry, I don't quite understand what you are reporting here. Could you please expand?

https://github.com/npm/npm/wiki/Contributing-Guidelines

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
