### ISSUE TITLE
Error de Instalacion

### ISSUE THREAD

**Issue by Lizandro27** [npm/npm#7898]
Anexo Log de Error:

![error_phonegap](https://cloud.githubusercontent.com/assets/11875158/7073150/05e7299a-deb7-11e4-9030-9b86da294cb2.jpg)

**Comment by KenanY** [comment]
@Lizandro27 Hmm, an SSL error? Are you behind a proxy?

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
