### ISSUE TITLE
Installing gulp into my laravel project fails 

### ISSUE THREAD

**Issue by swamimayank** [npm/npm#7899]
I'm trying to install gulp for a Laravel Project (using their Homestead VM). I've tried the recommended fixes of updating NPM, or clearing the cache. 

1. gulp version 
  1. CLI version 3.8.11
  2. Local version 3.8.11

2. npm verison  - 1.4.28

3. nodejs version  - 0.10.23

This is the error I see when trying it:
```
vagrant@homestead:~/Code/Laravel$ npm install chalk --save-dev
npm ERR! Error: UNKNOWN, symlink '../supports-color/cli.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.13.0-30-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "chalk" "--save-dev"
npm ERR! cwd /home/vagrant/Code/Laravel
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! path ../supports-color/cli.js
npm ERR! code UNKNOWN
npm ERR! errno -1
npm ERR! not ok code 0
```

**Comment by KenanY** [comment]
Are you using a shared folder from Vagrant to share your Node.js projects between it and the host OS?

**Comment by swamimayank** [comment]
yes i am using shared folder , i am using windows8 and have virtual box with vagrant + Laravel
 homestead

**Comment by KenanY** [comment]
@swamimayank The problem is that the virtual filesystem running in Vagrant on top of the Windows filesystem doesn't support symbolic links. Can you try `npm install chalk --no-bin-links`?

**Comment by swamimayank** [comment]
@KenanY thanks its working with `--no-bin-links ` :)
