### ISSUE TITLE
npm init --yes prompts for author when it shouldn't

### ISSUE THREAD

**Issue by iarna** [npm/npm#7900]
`npm init --yes` should produce a package.json with defaults only. However, it still stops to ask for author currently.

As reported by @hunterloftis:
https://twitter.com/HunterLoftis/status/586239826199977984

**Comment by othiym23** [comment]
@hunterloftis

The thing is, it won't prompt if you've previously run `npm config set init.author.name "J Cool Person" && npm config set init.author.email xXxradcool420xXx@hotmail.com`, and I'm not sure exactly what a sensible default could be, especially when you consider cross-platform concerns.

**Comment by hunterloftis** [comment]
@othiym23 Maybe a sensible default could be ""? (that's what happens if you just press enter on the prompt).

**Comment by othiym23** [comment]
`author` isn't a required field, so that might work. Either way somebody else should probably take point on getting that through `init-package-data` and npm, because I'm otherwise not going to have time to work on this anytime soon.
