### ISSUE TITLE
Install failure - need help to understand

### ISSUE THREAD

**Issue by waynehiner** [npm/npm#7904]
As noted in the npm-debug.log, I am submitting my log for assistance.  This is my first time with Karma and I can't find the specific error in the log.
Many thanks,
Wayne Hiner

**Comment by KenanY** [comment]
@waynehiner Could you upload the full log as a [gist](https://gist.github.com/) and comment with the link here?

**Comment by waynehiner** [comment]
Gist created at https://gist.github.com/waynehiner/fa13fc4d394e29dc50b8.

**Comment by KenanY** [comment]
@waynehiner Thank you :)

``` sh
$ git show v1.3.5
tag v1.3.5
Tagger: isaacs <i@izs.me>
Date:   Wed Jul 24 13:21:22 2013 -0700
```

`npm@1.3.5` is over a year old and no longer supported. [Upgrading](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) should solve this issue :)

**Comment by waynehiner** [comment]
That did it! 
Thank you.
