### ISSUE TITLE
Error: It doesn't look like npm is installed.

### ISSUE THREAD

**Issue by HoffmannP** [npm/npm#7909]
After running `npm explore npm pwd` npm reports:

    npm ERR! Linux 3.13.0-49-generic
    npm ERR! argv "node" "/usr/local/bin/npm" "explore" "npm" "pwd"
    npm ERR! node v0.10.2
    npm ERR! npm  v2.7.5
    
    npm ERR! It doesn't look like npm is installed.
    npm ERR! 
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <https://github.com/npm/npm/issues>
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     /home/ber/npm-debug.log

which is quite strange, itsn't it?

Attached debug.log:

    0 info it worked if it ends with ok
    1 verbose cli [ 'node', '/usr/local/bin/npm', 'explore', 'npm', 'pwd' ]
    2 info using npm@2.7.5
    3 info using node@v0.10.2
    4 verbose config Skipping project config: /home/ber/.npmrc. (matches     userconfig)
    5 verbose stack Error: It doesn't look like npm is installed.
    5 verbose stack     at /usr/local/lib/node_modules/npm/lib/explore.js:23:43
    5 verbose stack     at Object.oncomplete (evalmachine.<anonymous>:107:15)
    6 verbose cwd /home/ber
    7 error Linux 3.13.0-49-generic
    8 error argv "node" "/usr/local/bin/npm" "explore" "npm" "pwd"
    9 error node v0.10.2
    10 error npm  v2.7.5
    11 error It doesn't look like npm is installed.
    12 error If you need help, you may report this error at:
    12 error     <https://github.com/npm/npm/issues>
    13 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@HoffmannP You want the global `npm`? If so, you gotta add the `--global`/`-g` flag:

``` sh
$ npm explore -g npm pwd
/home/kenan/.npm-packages/lib/node_modules/npm
```

**Comment by HoffmannP** [comment]
That is indeed a solution to my actual problem but I especially thought that the error message is kind of ironical as npm announces it is not installed.

**Comment by KenanY** [comment]
@HoffmannP True, but in the context of "local" it indeed isn't installed (unless you are within the appropriate folder). Perhaps the error message could be more specific in that regard.
