### ISSUE TITLE
Error of instration plugins

### ISSUE THREAD

**Issue by Mutu1986** [npm/npm#7911]
I'm trying setup the build environment, but I can't install a part of plugins.
What problem is occurred now?

I would like to get support...

![error_log](https://cloud.githubusercontent.com/assets/11886048/7087111/99495bd4-dfc2-11e4-88bf-50ff24fba166.png)

**Comment by KenanY** [comment]
@Mutu1986 `npm@1.2.30` is over a year old and no longer supported. [Upgrading `npm`](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows) will definitely solve your issue.

**Comment by Mutu1986** [comment]
Big thanks for your information!

issue is fixed on npm version 1.3.24!

**Comment by KenanY** [comment]
@Mutu1986 Why settle with `npm@1.3.24`?
