### ISSUE TITLE
"ENOENT, readdir" and "ENOENT, chown" errors with local modules and empty cache

### ISSUE THREAD

**Issue by hatchan** [npm/npm#7912]
I've been running into some racing conditions when using local modules (i.e. `file:`) and an empty cache directory:

```
npm ERR! addLocal Could not install /home/bvdberg/dev/wercker/npm-race/local_module/module_26
npm ERR! Linux 3.13.0-48-generic
npm ERR! argv "node" "/usr/bin/npm" "i"
npm ERR! node v0.10.37
npm ERR! npm  v2.7.5
npm ERR! path /tmp/tmp.9ZdjEg6TgJ/wercker/npm/@local/module_31/1.0.0/package.tgz.7a287fd706869e360c81dbeaa6177be5
npm ERR! code ENOENT
npm ERR! errno 34

npm ERR! enoent ENOENT, chown '/tmp/tmp.9ZdjEg6TgJ/wercker/npm/@local/module_31/1.0.0/package.tgz.7a287fd706869e360c81dbeaa6177be5'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bvdberg/dev/wercker/npm-race/npm-debug.log=
```

https://github.com/hatchan/npm-race/blob/master/logs/npm-debug-chown.log

and:

```
npm ERR! addLocal Could not install /home/bvdberg/dev/wercker/npm-race/local_module/module_21
npm ERR! Linux 3.13.0-48-generic
npm ERR! argv "node" "/usr/bin/npm" "i"
npm ERR! node v0.10.37
npm ERR! npm  v2.7.5
npm ERR! path /tmp/tmp.9ZdjEg6TgJ/wercker/npm/@local/module_20/1.0.0/package.tgz.5d11ea762c8b0098129b34000461b319
npm ERR! code ENOENT
npm ERR! errno 34

npm ERR! enoent ENOENT, readdir '/tmp/tmp.9ZdjEg6TgJ/wercker/npm/@local/module_20/1.0.0/package.tgz.5d11ea762c8b0098129b34000461b319'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bvdberg/dev/wercker/npm-race/npm-debug.log
```

https://github.com/hatchan/npm-race/blob/master/logs/npm-debug-readdir.log

Unfortunately I haven't been able to reliably reproduce it on all machines I have. I have created a small repository with more details and a small script which tries to force the problem.

https://github.com/hatchan/npm-race

**Comment by smikes** [comment]
Thanks for the bug report.

Soon, npm will be moving to a more transactional and less racy installation system.  In the meantime, could you try updating to `npm@latest` (2.8.3) and run your checks again?  It may be that some recent changes have made the race less likely to occur (or, worse, more likely to occur).  In any case, any attempt to fix this in npm@2 will go against the current `master`, which is 2.8.4

**Comment by syrnick** [comment]
I'm running into the same issue. It has been reported a few times: #6811, #6875.

I was initially on 2.1.14 and upgraded to latest stable: 2.14.1. It used to fail very consistently on syrnick/jison (from github), but now it fails on csv-parse that installs right after syrnick/jison. The fail rate is around 2% (2 out of 104). With just 8x parallelism it results in unacceptably high build failure rate.

Here's the end of the failure log https://gist.github.com/syrnick/ce3cabc3050440f16fde .

**Comment by syrnick** [comment]
Actually, it seems that all of these issues are trying to use npm 2.x with node 0.10.x. Downgrading npm to the latest 1.x (1.4.28 - picked from https://nodejs.org/en/download/releases/) seems to have made it way better (1 out of 136 builds failed).

**Comment by busches** [comment]
Are you still running into these issues on npm 3?
