### ISSUE TITLE
peerDependency issue with npm 2.7.4

### ISSUE THREAD

**Issue by gyandeeps** [npm/npm#7913]
Lets say I have a package `A` which depends on package `B` and `E` and package `B` and `E` has its own dependencies like this:

```
A --> B --> C (>=0.17.0) (Dependency)
  --> E --> D (latest)(peerDependency) --> C (>=0.8.0)(peerDependency)
```

Now when I install `A`, this is how the modular tree looks like

```
A --> B
  --> E
  --> C
  --> D
```

Npm throws an error here saying `D` doesn't satisfy its `peerDependency` requirements.  
I think this should be a successful install.
Any idea what might be going on? 

NodeJs: 0.12.2
npm: 2.7.4

**Comment by smikes** [comment]
That's odd.  Under 2.7.4 , without having run `dedupe`, I would expect your dependency tree to be

```
node_modules/
node_modules/B
node_modules/B/node_modules/C
node_modules/B/node_modules/D
```

Is this not what you are seeing?

Can you provide a cut-down `package.json` that I can use locally to reproduce the problem you are seeing?

**Comment by gyandeeps** [comment]
I think the tree which I have inside my question is correct. I think thats how it should be.
Its just the npm fails at the end.
One thing to note here is that `B` in my case is a dependency to a github branch. (I dont know if that makes any difference).

Since will try to find some modules which to prove this scenario as one of the module getting usewd in my case is my corporate github repo.

**Comment by smikes** [comment]
Okay. I can't edit my response conveniently right now so I'll just note that the tree I proposed was based on an earlier version of your issue and is now no longer accurate.
