### ISSUE TITLE
Tessera Install Error

### ISSUE THREAD

**Issue by nirvine** [npm/npm#7918]
I received a number of errors when installing Tessera and tilelive modules. Most relate to version numbers - the tilelive modules look for older versions of node.js, and I have 0.12.2
Critical is that the certificate for Tessera has expired. 
I would have attached the debug log, but it is over 12000 lines.
If anyone is interested, I can send it.

![capture](https://cloud.githubusercontent.com/assets/4746171/7101188/42db40be-e08f-11e4-955c-9a11bd01e03b.JPG)

**Comment by iarna** [comment]
Modules don't have their own certificates with npm and all of npm's certificates are up to date so the problem must lay elsewhere.

There are a few possibilities– if you post your `npm-debug.log` (to `gist.githug.com` or `pastebin.com`) then I could tell you specifically where this is coming from.

* It could be a proxy server that you're going through.
* It could be a dependency of tessera (or dependency of a dependency ad infinitum) that's stored in a non-npm source that's having a certificate issue.

**Comment by nirvine** [comment]
I just ran it again as I could not find the log file, and this time it installed with no errors.
Problem solved,
Thanks.
