### ISSUE TITLE
Zombie processes with npm scripts

### ISSUE THREAD

**Issue by aymericbeaumet** [npm/npm#7919]
npm doesn't always clean up the processes spawned in the scripts when it stops. Running a background job (with `&`) followed by a job finishing instantly results in the first one ending up as a zombie.

The two processes should be killed when npm stops (as it spawned them).

This can be reproduced by running `npm run task` with the following _package.json_:
```json
{
  "scripts": {
    "task": "npm run zombie & npm run done",
    "zombie": "while true; do echo zombie; sleep 1; done",
    "done": "echo done"
  }
}
```

Inverting the order in which the tasks are run solves the issue: `npm run instant & npm run zombie`.

---

My system:
```
$ uname -a
Darwin macbookpro 14.1.0 Darwin Kernel Version 14.1.0: Thu Feb 26 19:26:47 PST 2015; root:xnu-2782.10.73~1/RELEASE_X86_64 x86_64
$ zsh --version
zsh 5.0.7 (x86_64-apple-darwin14.0.0)
$ npm --version
2.7.6
$ node --version
v0.10.37
```

**Comment by iarna** [comment]
npm passes the right hand side of a script definition to your shell blindly for execution. It doesn't understand any of the contents. Your shell then sees the '&' and interprets that as backgrounding commands. It is, in my opinion, the responsibility of your shell to do this. Fortunately it can!

As your script is already not windows compatible (windows doesn't support '&') then you could do this:

```
"task": "npm run zombie & npm run done & wait %1 %2",
```
This runs `zombie` and `done` in the background and tells your shell to wait for both to complete before returning control to `npm`.

**Comment by aymericbeaumet** [comment]
I'm aware npm blindly passes the command to the shell. That said, I'm surprised that background tasks spawned in a process owned by npm are not killed when npm dies (e.g.: after a `^C`).

If I run a background task in my current shell (the same being used by npm) and kills it, the task stops.

**Comment by smikes** [comment]
Is this still a problem for you?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by aymericbeaumet** [comment]
@iarna's solution works. But having to use `wait` looks like a trick to me.

**Comment by othiym23** [comment]
This is how job control works – by using `&`, you're bypassing npm altogether. npm is far from alone from doing this when executing processes in a subshell. Keep in mind that npm does support both Windows and Unixlike systems, so it's fairly hands-off when it comes to job management. This looks, to me, like npm behaving as it should under Unix, so I'm going to close this as resolved.
