### ISSUE TITLE
which npm and npm -v gives different version numbers for npm ... related issue #7921

### ISSUE THREAD

**Issue by kadamsa21** [npm/npm#7922]
Santoshs-MacBook-Pro:lib santoshkadam$ curl -L https://www.npmjs.com/install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6239  100  6239    0     0   3889      0  0:00:01  0:00:01 --:--:--  3889
tar=/usr/bin/tar
version:
bsdtar 2.8.3 - libarchive 2.8.3
install npm@latest
fetching: http://registry.npmjs.org/npm/-/npm-2.7.6.tgz
unbuild npm@2.7.5
 
> npm@2.7.6 prepublish /private/var/folders/rd/cgsxrd214wxbp4t52cc8_b900000gn/T/npm.9956/package
> node bin/npm-cli.js prune --prefix=. --no-global && rimraf test/*/*/node_modules && make -j8 doc

sh: rimraf: command not found
/Users/santoshkadam/.nvm/v0.8.18/bin/npm -> /Users/santoshkadam/.nvm/v0.8.18/lib/node_modules/npm/bin/npm-cli.js
npm@2.7.6 /Users/santoshkadam/.nvm/v0.8.18/lib/node_modules/npm
It worked
Santoshs-MacBook-Pro:lib santoshkadam$ which node
/Users/santoshkadam/.nvm/v0.8.18/bin/node
Santoshs-MacBook-Pro:lib santoshkadam$ which npm
/Users/santoshkadam/.nvm/v0.8.18/bin/npm
Santoshs-MacBook-Pro:lib santoshkadam$ node --version
v0.8.18
Santoshs-MacBook-Pro:lib santoshkadam$ npm -v
2.7.6
Santoshs-MacBook-Pro:lib santoshkadam$ npm --version
2.7.6
Santoshs-MacBook-Pro:lib santoshkadam$

**Comment by othiym23** [comment]
`0.8.18` is the version of Node being used by nvm:
```
Santoshs-MacBook-Pro:lib santoshkadam$ which npm
/Users/santoshkadam/.nvm/v0.8.18/bin/npm
```

`2.7.6` is the installed version of Node:

```
Santoshs-MacBook-Pro:lib santoshkadam$ npm -v
2.7.6
Santoshs-MacBook-Pro:lib santoshkadam$ npm --version
2.7.6
```
