### ISSUE TITLE
NPM Install Error - Express.js

### ISSUE THREAD

**Issue by DKH202** [npm/npm#7926]
Trying to install Express with the following command:

npm install express

Getting the error below:

npm WARN locking Error: EACCES, open '/Users/DKH/.npm/_locks/express-b6870c0f6f5fc89c.lock'
npm WARN locking at Error (native)
npm WARN locking /Users/DKH/.npm/_locks/express-b6870c0f6f5fc89c.lock failed { [Error: EACCES, open '/Users/DKH/.npm/_locks/express-b6870c0f6f5fc89c.lock']
npm WARN locking errno: -13,
npm WARN locking code: 'EACCES',
npm WARN locking path: '/Users/DKH/.npm/_locks/express-b6870c0f6f5fc89c.lock' }
npm ERR! Darwin 14.1.1
npm ERR! argv "node" "/usr/local/bin/npm" "install" "express"
npm ERR! node v0.12.0
npm ERR! npm v2.5.1

npm ERR! Attempt to unlock /Users/DKH/Code/32CitiesTweet/node_modules/express, which hasn't been locked
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR! http://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR! /Users/DKH/Code/32CitiesTweet/npm-debug.log

Not sure how to go about fixing this one.

**Comment by KenanY** [comment]
@DKH202 Looks like a permissions issue. Could you try the following?:

``` bash
$ sudo chown -R $(whoami) "$HOME/.npm"
```

**Comment by DKH202** [comment]
That worked thanks!
