### ISSUE TITLE
Installing dependencies for non-authenticated github users

### ISSUE THREAD

**Issue by zerkms** [npm/npm#7930]
Guys, any reason why `npm` does not support installing dependencies for non-authenticated github users?

We do not authenticate to fetch packages from `npm` repository, why is it required to set up github key authentication to set up the dependency?

For private repositories - without doubts it's essential, but for public ones it looks like an overkill.

Thoughts?

**Comment by iarna** [comment]
zerkms: `npm` _does_ support installing dependencies for from github without authentication. Can you tell me what you were trying to do and what errors you got?

**Comment by zerkms** [comment]
Here is the complete log

    $ npm install "IronSummitMedia/startbootstrap-sb-admin-2"
    npm ERR! addLocal Could not install /tmp/npm-5882-68464f31/git-cache-05bde5fc65f7/a964f4b89cb60115301ca18c051a7cd143ad8e9a
    npm ERR! git clone --template=/home/vagrant/.npm/_git-remotes/_templates --mirror ssh://git@github.com/ironsummitmedia/startbootstrap-sb-admin-2.git /home/vagrant/.npm/_git-remotes/ssh-git-github-com-ironsummitmedia-startbootstrap-sb-admin-2-git-e15c2468: Cloning into bare repository '/home/vagrant/.npm/_git-remotes/ssh-git-github-com-ironsummitmedia-startbootstrap-sb-admin-2-git-e15c2468'...
    npm ERR! git clone --template=/home/vagrant/.npm/_git-remotes/_templates --mirror ssh://git@github.com/ironsummitmedia/startbootstrap-sb-admin-2.git /home/vagrant/.npm/_git-remotes/ssh-git-github-com-ironsummitmedia-startbootstrap-sb-admin-2-git-e15c2468: Permission denied (publickey).
    npm ERR! git clone --template=/home/vagrant/.npm/_git-remotes/_templates --mirror ssh://git@github.com/ironsummitmedia/startbootstrap-sb-admin-2.git /home/vagrant/.npm/_git-remotes/ssh-git-github-com-ironsummitmedia-startbootstrap-sb-admin-2-git-e15c2468: fatal: Could not read from remote repository.
    npm ERR! git clone --template=/home/vagrant/.npm/_git-remotes/_templates --mirror ssh://git@github.com/ironsummitmedia/startbootstrap-sb-admin-2.git /home/vagrant/.npm/_git-remotes/ssh-git-github-com-ironsummitmedia-startbootstrap-sb-admin-2-git-e15c2468:
    npm ERR! git clone --template=/home/vagrant/.npm/_git-remotes/_templates --mirror ssh://git@github.com/ironsummitmedia/startbootstrap-sb-admin-2.git /home/vagrant/.npm/_git-remotes/ssh-git-github-com-ironsummitmedia-startbootstrap-sb-admin-2-git-e15c2468: Please make sure you have the correct access rights
    npm ERR! git clone --template=/home/vagrant/.npm/_git-remotes/_templates --mirror ssh://git@github.com/ironsummitmedia/startbootstrap-sb-admin-2.git /home/vagrant/.npm/_git-remotes/ssh-git-github-com-ironsummitmedia-startbootstrap-sb-admin-2-git-e15c2468: and the repository exists.
    npm ERR! Linux 3.13.0-45-generic
    npm ERR! argv "node" "/usr/bin/npm" "install" "IronSummitMedia/startbootstrap-sb-admin-2"
    npm ERR! node v0.10.37
    npm ERR! npm  v2.7.6
    npm ERR! code 128

    npm ERR! Command failed: Cloning into bare repository '/home/vagrant/.npm/_git-remotes/ssh-git-github-com-ironsummitmedia-startbootstrap-sb-admin-2-git-e15c2468'...
    npm ERR! Permission denied (publickey).
    npm ERR! fatal: Could not read from remote repository.
    npm ERR!
    npm ERR! Please make sure you have the correct access rights
    npm ERR! and the repository exists.
    npm ERR!
    npm ERR!
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <https://github.com/npm/npm/issues>

    npm ERR! Please include the following file with any support request:
    npm ERR!     /tmp/npm-debug.log

I tried every single format of specifying a dependency name from the https://docs.npmjs.com/cli/install page and result is the same.

**Comment by iarna** [comment]
I don't get _that_ error message, but I do get a confusing error message and it fails to install.

Further investigation shows that the repository you're trying to install isn't an npm module and can't be installed by npm. For npm to install a module it needs to have a `package.json` in its root. (IronSummitMedia/startbootstrap-sb-admin-2)[https://github.com/IronSummitMedia/startbootstrap-sb-admin-2] has a `bower.json` but no `package.json` and so can't be installed with npm.

If you want that module then you should check out [bower](http://bower.io/).

**Comment by zerkms** [comment]
Indeed, your explanation makes sense for me.

The error message does not though (it clearly complains about permissions).

Thanks.

**Comment by othiym23** [comment]
When presented with GitHub shorthand syntax (e.g. `IronSummitMedia/startbootstrap-sb-admin-2` vs `https://github.com/IronSummitMedia/startbootstrap-sb-admin-2.git`), npm tries to cache the package using the `git:` protocol first. If that caching process fails – for any reason – it will fall back to trying `ssh:` (and, in `npm@2.8.0` and up, will fall back even further to trying `git+https:`. I agree that the current error message is unhelpful (it gives you no clue that the actual problem is that there's no `package.json` in the repository), but putting in the necessary backtracking logic to hold onto the previous error and figure out how to display that information usefully is a hefty chunk of work. It would definitely be nice to have, though.

**Comment by zerkms** [comment]
>  vs https://github.com/IronSummitMedia/startbootstrap-sb-admin-2.git

@othiym23 the latter is not supported as per https://docs.npmjs.com/cli/install 

> `<protocol>` is one of git, git+ssh, git+http, or git+https

**Comment by othiym23** [comment]
@zerkms That's why I ninja's in and changed that while you were leaving your response. ;)

**Comment by zerkms** [comment]
@othiym23  :-) thanks guys
