### ISSUE TITLE
npm Error: ENOENT every time I open a new bash console window

### ISSUE THREAD

**Issue by natatat** [npm/npm#7937]
It happens automatically whenever I open a new bash window, regardless which directory I'm in.

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/0.10.25/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'test',
1 verbose cli   '-n',
1 verbose cli   '3.2.51(1)-release',
1 verbose cli   '-o',
1 verbose cli   '-n',
1 verbose cli   '' ]
2 info using npm@1.3.24
3 info using node@v0.10.25
4 error Error: ENOENT, open '/Users/natalie/node_modules/3.2.51(1)-release/package.json'
5 error If you need help, you may report this *entire* log,
5 error including the npm and node versions, at:
5 error     <http://github.com/isaacs/npm/issues>
6 error System Darwin 13.4.0
7 error command "/usr/local/Cellar/node/0.10.25/bin/node" "/usr/local/bin/npm" "test" "-n" "3.2.51(1)-release" "-o" "-n" ""
8 error cwd /Users/natalie
9 error node -v v0.10.25
10 error npm -v 1.3.24
11 error path /Users/natalie/node_modules/3.2.51(1)-release/package.json
12 error code ENOENT
13 error errno 34
14 verbose exit [ 34, true ]
```

**Comment by iarna** [comment]
The version of npm you're using is over a year old, which is VERY old in npm terms. Since then we've fixed a lot of bugs, many which produced the kind of error message you're seeing. Please try updating to the current version of npm.

**Comment by KenanY** [comment]
If anything, I'm extremely perplexed as to why such an `npm` command is being executed upon every instantiation of bash :/

**Comment by othiym23** [comment]
I'm going to guess your completion settings may have gotten messed up somehow. Try cleaning out anything related to npm in your `.bashrc`, `.profile`, or `.zshrc` and re-adding it.

**Comment by natatat** [comment]
Thanks, I had tried to create an `alias test='npm test'` in my .bash_profile, removing that fixed it!
