### ISSUE TITLE
can not publish my module

### ISSUE THREAD

**Issue by williamherry** [npm/npm#7943]
searched on google seem no related info

```
npm ERR! publish Failed PUT 403
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "publish"
npm ERR! node v0.12.1
npm ERR! npm  v2.5.1
npm ERR! code E403

npm ERR! no_perms can't publish non-scoped package, please set `config.scopes`: qiniu-js-sdk
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/william/Codes/qiniu-js-sdk/npm-debug.log
```

**Comment by smikes** [comment]
Have you logged in to the `npm` registry?  What is the result of running `npm whoami` ?

**Comment by williamherry** [comment]
@smikes 

`npm whoami` return my username of npm website

**Comment by smikes** [comment]
Ah. It looks like you are trying to publish with a publish-config that sets "access", but you can only set access for scoped packages. 

Can you upload your package.json to https://gist.github.com ?

**Comment by williamherry** [comment]
@smikes https://gist.github.com/williamherry/335e514de5a9fedaeb82

**Comment by asjmtz** [comment]
@williamherry I meet the same error, and it works when I deleted my registry config. Maybe you can try this way.

**Comment by williamherry** [comment]
@asjmtz you are right, thank you :)

**Comment by lawrence-peng** [comment]
where is  registry config ? @williamherry

**Comment by williamherry** [comment]
@lawrence-peng `~/.npmrc` ?

**Comment by lawrence-peng** [comment]
thank you. npm config ls can view the path.delete ```registry = "http://r.cnpmjs.org/"``` config ,it working!

**Comment by Huangsrtext** [comment]
This relative module was not found:

* ./src/main.js in multi ./build/dev-client ./src/main.js
> Listening at http://localhost:80

**Comment by Huangsrtext** [comment]
can someone meet this problem？

**Comment by Huangsrtext** [comment]
can someone meet this problem？
