### ISSUE TITLE
npm ERR! network If you are behind a proxy

### ISSUE THREAD

**Issue by Nagarajmca** [npm/npm#7945]
Hi,

I am behind corporate proxy. 

After installing NodeJs i tried to install nsp or even any packages, i get the below error
 
```
C:\Windows\System32>npm install nsp -g
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "nsp" "-g"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect

npm ERR! network connect ETIMEDOUT
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\System32\npm-debug.log
```

Tried with various options and suggestions from various forum , but none worked

Please suggest here what to do.

Thanks
Nagaraj

**Comment by smikes** [comment]
Have you set the `http_proxy` variable in your npm config?  Sometimes Windows users find that they need to set up a local proxy to provide appropriate authentication to the corporate proxy -- if that's the case, try http://cntlm.sourceforge.net/

**Comment by smikes** [comment]
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially involving git dependencies -- since 2.5. Can you try updating your npm installation?

There is a bad interaction between two known bugs — one in `node@>0.11` and `iojs` and the other in `npm@<2.8.2`.  This can cause ECONNRESET and ETIMEDOUT errors.  The full writeup is here: https://github.com/npm/npm/issues/7699  You can fix this problem by updating your `npm` to the latest (see below).

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved / abandoned.

**Comment by iMohammadd** [comment]
i have same problem
-d flag worked for me

**Comment by hridayakandel** [comment]
did everything always same problem exist

**Comment by hridayakandel** [comment]
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>npm cache clean

C:\WINDOWS\system32>npm install -g ionic
^CTerminate batch job (Y/N)?
^C
C:\WINDOWS\system32>npm cache clean

C:\WINDOWS\system32>npm install -g ionic
npm WARN engine cordova-js@3.9.0: wanted: {"node":"~0.10.x"} (current: {"node":"
0.12.4","npm":"2.11.1"})
npm WARN engine npm@1.3.4: wanted: {"node":">=0.6","npm":"1"} (current: {"node":
"0.12.4","npm":"2.11.1"})
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {
"node":"0.12.4","npm":"2.11.1"})
npm WARN installMany normalize-package-data was bundled with npm@1.3.4, but bund
led package wasn't found in unpacked tree
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "node" "C:\\Users\\star\\AppData\\Roaming\\npm\\node_modules\\npm\
\bin\\npm-cli.js" "install" "-g" "ionic"
npm ERR! node v0.12.4
npm ERR! npm  v2.11.1
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
^CTerminate batch job (Y/N)? Y

C:\WINDOWS\system32>npm cache clean

**Comment by jaiganeshak** [comment]
From admin command prompt I tried 'npm install'. Upto certain level it goes fine & after that it hangs...
Please see the output...

My environment : windows 8.1 64 bit, mean 0.5.5,  npm 2.11.3, node 0.12.7

Followed all the steps indicated in http://learn.mean.io/
Installed Python 2.7.x, Microsoft Visual Studio C++ 2012 Express, etc.
Did cache clean, etc.

Can you please suggest a way to resolve this?  Thanks!
- Jai
.....
  Generating code
  Finished generating code
  bufferutil.vcxproj -> C:\mean\prisame2\node_modules\karma\node_modules\socket
  .io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\
  ws\node_modules\bufferutil\build\Release\\bufferutil.node
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
|

**Comment by deepaksisodiya** [comment]
try this
npm config set registry http://registry.npmjs.org/

**Comment by rorschach217** [comment]
I have this problem
W:\Node\SampleWebsite>npm install -g express-generator
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "express-generator"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code ECONNRESET

npm ERR! network tunneling socket could not be established, cause=getaddrinfo ENOTFOUND port port:80
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     W:\Node\SampleWebsite\npm-debug.log

**Comment by jozn** [comment]
same here

**Comment by mdarif** [comment]
+1

**Comment by prashanth-sams** [comment]
Kinda similar issue,

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall read

npm ERR! network read ETIMEDOUT
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

**Comment by yuzhanchao2015** [comment]
npm install *** -d

**Comment by ganeshMNAIK** [comment]
$ npm install -g yo
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "yo"
npm ERR! node v7.2.0
npm ERR! npm  v3.10.9
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect

npm ERR! network connect ETIMEDOUT 151.101.8.162:443
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Ganesh Naik\npm-debug.log

**Comment by bhandaribhumin** [comment]
Anyone know how to resolve this cordova installl error!
see below image of error message.

![image](https://cloud.githubusercontent.com/assets/3336047/20876268/cd08c940-bae6-11e6-9726-691f74d523b8.png)

I have latest version of Node.
Also set environment variable in advance settings.
Not set any Proxy on Desktop.
![image](https://cloud.githubusercontent.com/assets/3336047/20876392/a551462e-bae7-11e6-8590-95373673a6fa.png)

![image](https://cloud.githubusercontent.com/assets/3336047/20876399/b760ff12-bae7-11e6-9c42-2e0f694aebad.png)

**Comment by ansh0811** [comment]
Hi ,

Facing proxy issue on windows 7 on corporate network . Nodejs version : 6.10.3 , npm version : 3.10.10
Attaching the error which i am facing.

Please suggest possible ways to install cordova and ionic.

is it possible to install cordova and ionic manually ? and how?

Thanks..!!



![error](https://cloud.githubusercontent.com/assets/19550545/25948378/d09a91fa-3670-11e7-9cb4-b9fb43a36456.png)

**Comment by legodude17** [comment]
@ansh0811 Please update your `npm`. If the issue persists, open a new one.

**Comment by ansh0811** [comment]
@legodude17 Tried updating npm, facing same issue.
Yes open a new issue with #16607

**Comment by waqasraza123** [comment]
@iMohammadd -d flag worked for me too.

**Comment by jcollum-cambia** [comment]
What -d flag? where does it go? `npm install -d package-name here` ?

**Comment by simransethi08** [comment]
please set your npm proxy using:
npm config set proxy http://<proxy.company.com>:<port>
npm config set https-proxy http://<proxy.company.com>:<port>

**Comment by waqasraza123** [comment]
@jcollum-cambia put it anywhere. it would work.

**Comment by jcollum-cambia** [comment]
But there's no `-d` in the docs https://docs.npmjs.com/cli/install ; only `-D`; are you talking about verbose output? That's `-v`, so I'm a bit confused about what you mean

**Comment by sonmt23** [comment]
> 

try this npm config set registry http://registry.npmjs.org/
--

This is very works for me!

**Comment by yogeshpatil143** [comment]
I also suffer from the same problem

npm install -d is the correct answer

**Comment by kinjal-thaker-css** [comment]
For those, who's system is not running behind the proxy and getting errors like "bad network connection", "connection timeout" or "configure proxy". they can do as follows: which works for me.

check whether the  .npmrc file exists in your system (in C://Users/Admin)
If yes, then remove that file and restart your command prompt and run 2 commands as follows:
1) "npm cache clear --force"
2) "npm install -g @ angular/cli"

Hope this can help.

**Comment by va1729** [comment]
I was getting ETIMEDOUT error and I used a VPN to connect to the network and install packages. 

Is there any limit on the number of connections we can make to the registry? And who is setting this limit if there is one?

**Comment by yunisSong** [comment]
I was tortured by this problem for two days.
-d flag worked for me,
TKS.
