### ISSUE TITLE
Make private repository free

### ISSUE THREAD

**Issue by youssefdetovernickr** [npm/npm#7948]
What's wrong with the people that made this a paid service? Make a free service for a max of 10 packages or something, there's no reason people use this service right now as you can basically create your own for free and change the repository setting in npm.

**Comment by aredridel** [comment]
Yes, you're free to do that.

**Comment by othiym23** [comment]
This has nothing to do with the npm CLI, and I'm not interested in it becoming about the npm CLI, which has always been and will always be 100% free software.
