### ISSUE TITLE
how do i tell specify in package.json that install the packages locally ?

### ISSUE THREAD

**Issue by jpca999** [npm/npm#7951]
how do i tell specify in package.json that install the packages locally  ie.   --save

**Comment by iarna** [comment]
@jpca999: I'm not sure I understand your question? The package.json _only_ lists packages that are to be installed locally.

**Comment by smikes** [comment]
@jpca999 Can you tell us more about your use case?

On the one hand, if you want to install a package **and** save it into the local `package.json`, you can run

```
$ npm install --save <package>
```

On the other hand, if you are trying to create a package which **should not** be installed globally, I don't think there's a way to do that.  There is a way to say that a package **should** be installed globally -- see https://docs.npmjs.com/files/package.json#preferglobal -- but generally installing a package globally is harmless, so there's no way to warn against that.

Please let me know if I have answered your questions.

**Comment by othiym23** [comment]
Closing as abandoned.
