### ISSUE TITLE
Error installing node-gyp with npm

### ISSUE THREAD

**Issue by marcelo-ni** [npm/npm#7953]
Sorry. I closed my original issue by error. 

Reading the log, it seems that npm is trying to intall graceful-fs 3.0.6, but the most advanced version available is 0.5.0. Relevant lines follow
```
404 verbose read json /home/marcelo/.npm/graceful-fs/3.0.6/package/package.json
...
411 silly lockFile 06099a4c-graceful-fs-3 graceful-fs@3
412 silly lockFile 06099a4c-graceful-fs-3 graceful-fs@3
413 error Error: No compatible version found: mkdirp@'^0.5.0'
413 error Valid install targets:
413 error ["0.0.1","0.0.2","0.0.3","0.0.4","0.0.5","0.0.6","0.0.7","0.1.0","0.2.0","0.2.1","0.2.2","0.3.0","0.3.1","0.3.2","0.3.3","0.3.4","0.3.5","0.4.0","0.4.1","0.4.2","0.5.0"]
413 error at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:709:10)
```

**Comment by othiym23** [comment]
```
413 error Error: No compatible version found: mkdirp@'^0.5.0'
```

I'm going to guess that you're running an old version of npm. If you [upgrade to the latest stable version](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm), this problem will probably go away.

**Comment by marcelo-ni** [comment]
I'm running npm 1.2.25, and node is 0.10.10

**Comment by marcelo-ni** [comment]
Upgraded to npm 2.7.6; attempted to install node-gyp again with no special error message. 
node-gyp throws same error as previously:

Error: Cannot find module '/node_modules/node-gyp/bin/node-gyp.js'

So I think that node-gyp installation failed silently.

**Comment by othiym23** [comment]
What happens if you remove `node_modules` and try to run the install again? That's a different error than the one you were getting before:

```
413 error Error: No compatible version found: mkdirp@'^0.5.0'
413 error Valid install targets:
413 error ["0.0.1","0.0.2","0.0.3","0.0.4","0.0.5","0.0.6","0.0.7","0.1.0","0.2.0","0.2.1","0.2.2","0.3.0","0.3.1","0.3.2","0.3.3","0.3.4","0.3.5","0.4.0","0.4.1","0.4.2","0.5.0"]
```

**Comment by marcelo-ni** [comment]
Excuse me: the error regarding node-gyp.js is from node-gyp, even when I try to get the version.

You suggest to delete "node-modules", which of the various I can find?

**Comment by marcelo-ni** [comment]
I cannot fully undestand what was going, but after npm upgrade, a new node-gyp installation succeded and it's working perfectly now.
