### ISSUE TITLE
Aliasing modules

### ISSUE THREAD

**Issue by creynders** [npm/npm#7959]
I know this is somewhat of a :bomb: and @isaacs opinion is very clear on this in #2943, but I'd like to propose a different approach: allow creating unique, unused aliases, something like:

```js
{
  "alias": {
    "_": "lodash"
}
```

I.e. no lying, just remapping. This means you can do `require("_")` which will resolve to "lodash" in this case.

There really _is_ a use case for this, for instance in frameworks with plugin architectures it would be really beneficial to allow plugins to require modules decided upon by the framework architecture.

I'm sorry if this is possible already, just point me to the right direction, I'm definitely no npm expert.

**Comment by iarna** [comment]
@creynders If I understand your suggestion, you want to change `require`'s behavior to look in the alias section of the package.json? Changing the behavior of `require` is outside the purview of `npm` (it's a node.js/io.js thing) and isn't really on the table there either as the behavior is frozen.

You could easily write a module that reads from your package.json and allows something like `require("aliases")("_")`.

**Comment by zkat** [comment]
Hey, as you pointed out, Isaac did say no, and did even lock the thread about that discussion. Because of the fact that this sort of thing is easy enough with other ways, there's no clear reason to really have this as part of npm core, and thus I'm closing this issue.
