### ISSUE TITLE
npm-install throws "Uncaught, unspecified error event " from fs-write-stream-atomic

### ISSUE THREAD

**Issue by Krinkle** [npm/npm#7966]
```
$ rm -rf node_modules && npm install
npm WARN package.json mediawiki@0.0.0 No repository field.
npm ERR! Linux 3.13.0-45-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.25
npm ERR! npm  v2.7.6

npm ERR! Uncaught, unspecified "error" event.
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
|
npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/jenkins-workspace/workspace/mediawiki-core-qunit@2/src/npm-debug.log
```

npm-debug.log: https://gist.github.com/Krinkle/f07bf6008e693047e8a8
```
..
426 verbose stack TypeError: Uncaught, unspecified "error" event.
426 verbose stack     at TypeError (<anonymous>)
426 verbose stack     at EventEmitter.emit (events.js:74:15)
426 verbose stack     at cleanupSync (/usr/local/lib/node_modules/npm/node_modules/fs-write-stream-atomic/index.js:46:42)
426 verbose stack     at WriteStream.emit (/usr/local/lib/node_modules/npm/node_modules/fs-write-stream-atomic/index.js:53:12)
426 verbose stack     at WriteStream.<anonymous> (evalmachine.<anonymous>:1660:12)
426 verbose stack     at OpenReq.Req.done (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:141:5)
426 verbose stack     at OpenReq.done (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:61:22)
426 verbose stack     at Object.oncomplete (evalmachine.<anonymous>:107:15)
..
```

**Comment by smikes** [comment]
Thanks for the bug report!

**Comment by macnibblet** [comment]
Im having the same issue.

**Comment by prashathsenthil** [comment]
any resolution for this issue? i'm facing the similar error when installing npm (2.9.0) from POM.xml using  the frontend-maven-plugin version 0.0.23. (https://github.com/eirslett/frontend-maven-plugin/)

**Comment by bradparks** [comment]
seeing the same issue as well when running npm from an ant task....

**Comment by bradparks** [comment]
Turns out our issue wasn't an npm issue at all, but a server issue. The server wasn't out of space, but was out of inodes.

run `df -i` on your system

and if you see any mounts that have "100%" in the "IUse%" column, that's your trouble.

    Filesystem        Inodes   IUsed     IFree IUse% Mounted on
    /dev/sda1        1831424  289861   1541563   16% /
    udev            12372159     527  12371632    1% /dev
    tmpfs           12374358     409  12373949    1% /run
    none            12374358       5  12374353    1% /run/lock
    none            12374358       1  12374357    1% /run/shm
    /dev/sda4      342686464 8799054 333887410    3% /store
    /dev/sda2         610800   66850    543950  100% /home
