### ISSUE TITLE
npm install throws Error: No compatible version found: cors@'^2.5.2'

### ISSUE THREAD

**Issue by vinniks29** [npm/npm#7967]
When i run the npm install command. I am getting No compatible version found: cors@'^2.5.2' error. See the log below:

```
C:\Heroku\nibs-ibeacon>npm install
npm http GET https://registry.npmjs.org/cookie-session
npm http GET https://registry.npmjs.org/bcrypt
npm http GET https://registry.npmjs.org/body-parser
npm http GET https://registry.npmjs.org/node-uuid
npm http GET https://registry.npmjs.org/validator
npm http GET https://registry.npmjs.org/logfmt
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/cors
npm http GET https://registry.npmjs.org/nforce
npm http GET https://registry.npmjs.org/winston
npm http GET https://registry.npmjs.org/compression
npm http GET https://registry.npmjs.org/ejs
npm http GET https://registry.npmjs.org/method-override
npm http GET https://registry.npmjs.org/q
npm http GET https://registry.npmjs.org/pg
npm http GET https://registry.npmjs.org/express
npm http 304 https://registry.npmjs.org/body-parser
npm http 304 https://registry.npmjs.org/bcrypt
npm http 304 https://registry.npmjs.org/node-uuid
npm http 304 https://registry.npmjs.org/validator
npm http 304 https://registry.npmjs.org/request
npm http 304 https://registry.npmjs.org/cors
npm http 304 https://registry.npmjs.org/winston
npm http 304 https://registry.npmjs.org/compression
npm http 304 https://registry.npmjs.org/cookie-session
npm http 304 https://registry.npmjs.org/ejs
npm http 304 https://registry.npmjs.org/nforce
npm http 304 https://registry.npmjs.org/method-override
npm http 304 https://registry.npmjs.org/logfmt
npm http 304 https://registry.npmjs.org/q
npm http 304 https://registry.npmjs.org/express
npm http 304 https://registry.npmjs.org/pg
npm ERR! Error: No compatible version found: cors@'^2.5.2'
npm ERR! Valid install targets:
npm ERR! ["0.0.1","0.0.2","0.0.3","0.0.4","0.0.5","0.1.0","0.1.1","1.0.0","1.0.1","2.0.0","2.1.0","2.1.1","2.2.0","2.3.0","2.3.1","2.3.2","2.4.0","2.4.1","2.4.2","2.5.0","2.5.1","2
.5.2","2.5.3"]
npm ERR!     at installTargetsError (C:\Program Files (x86)\nodejs\node_modules\npm\lib\cache.js:719:10)
npm ERR!     at C:\Program Files (x86)\nodejs\node_modules\npm\lib\cache.js:641:10
npm ERR!     at saved (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:302:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\Heroku\nibs-ibeacon
npm ERR! node -v v0.8.28
npm ERR! npm -v 1.2.30
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Heroku\nibs-ibeacon\npm-debug.log
npm ERR! not ok code 0
```

**Comment by iarna** [comment]
The version of npm that you're using is very old and doesn't support version ranges specified using `^`. If you update your npm either by updating your node or by installing the latest npm with with `npm install -g npm` then you should be able to proceed.

**Comment by vinniks29** [comment]
when i update to the latest verion of node. this is the error i get

C:\Heroku\nibs-ibeacon>npm install
|
> bcrypt@0.7.8 install C:\nibs-ibeacon\node_modules\bcrypt
> node-gyp rebuild


C:\Heroku\nibs-ibeacon\node_modules\bcrypt>if not defined npm_config_node_gyp (node "C:\Softwares\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node
_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
Traceback (most recent call last):
  File "C:\Softwares\nodejs\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 11, in <module>
    import gyp
  File "C:\Softwares\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 8, in <module>
    import gyp.input
  File "C:\Softwares\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 873
    except ImportError as e:
                        ^
SyntaxError: invalid syntax
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Softwares\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Softwares\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Heroku\nibs-ibeacon\node_modules\bcrypt
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.12.2","npm":"2.7.4"})
-


> pg@2.11.1 install C:\Heroku\nibs-ibeacon\node_modules\pg
> node-gyp rebuild || (exit 0)


C:\Heroku\nibs-ibeacon\node_modules\pg>if not defined npm_config_node_gyp (node "C:\Softwares\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_mod
ules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
Traceback (most recent call last):
  File "C:\Softwares\nodejs\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 11, in <module>
    import gyp
  File "C:\Softwares\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 8, in <module>
    import gyp.input
  File "C:\Softwares\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 873
    except ImportError as e:
                        ^
SyntaxError: invalid syntax
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Softwares\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Softwares\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Heroku\nibs-ibeacon\node_modules\pg
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Softwares\\nodejs\\\\node.exe" "C:\\Softwares\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.7.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.7.8 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt

**Comment by KenanY** [comment]
@vinniks29 What version of python do you have installed?

**Comment by vinniks29** [comment]
python 2.5

**Comment by smikes** [comment]
Is this still a problem for you?

You may need to update your python version to 2.7 -- I am not certain of this, since I am not a heavy python user, but that's the version I'm using on my Windows test machine.

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially involving git dependencies -- since 2.7. Can you try updating your npm installation?

There is a bad interaction between two known bugs — one in `node@>0.11` and `iojs` and the other in `npm@<2.8.2`.  This can cause ECONNRESET and ETIMEDOUT errors.  The full writeup is here: https://github.com/npm/npm/issues/7699  You can fix this problem by updating your `npm` to the latest (see below).

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by jakwings** [comment]
@iarna Thank you! :+1:

**Comment by othiym23** [comment]
Closing as resolved.
