### ISSUE TITLE
npm ls -g causes "Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by mattdesl** [npm/npm#7968]
I am running the following to find the version of my globally installed watchify:

```
npm ls watchify -g
```

It takes a pretty long time (~6 seconds) and then errors out with the following:

```
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/Users/matt/npm/bin/npm" "ls" "watchify" "-g"
npm ERR! node v0.10.32
npm ERR! npm  v2.8.2

npm ERR! Maximum call stack size exceeded
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

OSX 10.10.1

**Comment by mattdesl** [comment]
Also: I have tried `npm cache clean` but the error persists.

**Comment by othiym23** [comment]
Is this still happening? Are you still running `npm@2`? I'm not seeing this happening with my own install of `watchify`, but I'm running `npm@3.7.4` and it's been almost a year. (I'm trying to nail down all the `Maximum call stack size exceeded` errors preparatory to getting them fixed, hence the sudden activity.) Thanks for your time, and your patience!
