### ISSUE TITLE
Searching packages using the npm library

### ISSUE THREAD

**Issue by IonicaBizau** [npm/npm#7970]
I want to fetch all the packages having the `jxengine` keyword. I [posted a question on SO](http://stackoverflow.com/q/29667151/1420197) about that and got the following snippet:

``` js
var npm = require("npm");

npm.load({}, function () {
    npm.commands.search(["jxengine"], true, function (err, result) {
        if (err) {
            throw new Error(err);
        }
        console.log(Object.keys(result));
    });
});
```

I have some questions:
- [x] Is there a way to disable completely the verbose output (using the `silent` parameter set to `true` seems only to disable the table)? Currently it outputs things like below:
  
  ![image](https://cloud.githubusercontent.com/assets/2864371/7178478/c9604fb6-e437-11e4-97aa-87d977a65cd9.png)
- [ ] How to get the same packages that are fetched on npm site? There are currently [8 packages](https://www.npmjs.com/search?q=jxengine), but the script above fetches only 4.
- [ ] How to use the `staleness` parameter? Probably it is related to my second point?

Thanks! :smile:

**Comment by thefourtheye** [comment]
:+1: Even I would like to know the answers :-)

**Comment by iarna** [comment]
If you're seeing `http` logs then you're using a pretty old version of `npm` so to begin with, I would suggest updating that.  You can control that sort of output by passing `loglevel: 'none'` in that first argument to `npm.load` (though again, more recent versions of npm only output warnings and errors by default).

**Comment by IonicaBizau** [comment]
@iarna I forgot to mention that I configured the log level in the `~/.npmrc` file to be `http`. When running `npm` commands, I like to see more verbose output. However, when using `npm` as library, I want to control that. I use `npm@2.7.6` (probably the latest stable one).

**Comment by iarna** [comment]
When using it as a library, which is how npm uses itself, it'll use what's in `.npmrc` of course. But you can override that by adding properties to the object you pass to `npm.load`. If you add `loglevel` as described above then it will suppress all logging. =)

**Comment by IonicaBizau** [comment]
@iarna That's a good point and makes sense! :+1: However, it seems not to work:

![selection_042](https://cloud.githubusercontent.com/assets/2864371/7196471/1b499118-e4db-11e4-9c40-60d38afb1b69.png)

Is it a :bug: ?

**Comment by othiym23** [comment]
No, `none` is not a valid value for `loglevel`, which can be `silly`, `verbose`, `http`, `info`, `warn`, `error`, or `silent` (I think that's all of them? _whew_). See what happens if you change that to `silent`, because that's the log level I think you want.

**Comment by IonicaBizau** [comment]
@othiym23 Problem 1 solved. :+1: So, `loglevel: "silent"` (everything lowercase) is what I need. 

Still two other questions needs to be solved. :smile:

**Comment by sindresorhus** [comment]
I wrote a lightweight module for this exact purpose: https://github.com/sindresorhus/npm-keyword

**Comment by IonicaBizau** [comment]
@sindresorhus Yes, that's a nice module! :sparkles: Is it possible to get the version as well?
