### ISSUE TITLE
npm completion script for `npm run` incorrectly lists dependencies

### ISSUE THREAD

**Issue by jasonkarns** [npm/npm#7973]
`npm run` prints only scripts listed in package.json
`npm run <tab>` prints scripts from package.json *and* all dependecies/devDependencies

At first I assumed the addition completion options were being fulfilled from the local node_modules binaries. However, attempting to execute `npm run jshint` for example failed with "missing script: jshint". (As it should.) Then I noticed that not just local binaries were listed, but all the package deps entirely.

`npm run <tab>` should only be listing scripts from package.json

(using npm v2.7.6)

**Comment by iarna** [comment]
This dates to pre npm@2 behavior where you could use: `npm run <module> <module's script>`

**Comment by jasonkarns** [comment]
Ah, yes. I remember that feature now. Will this feature remain? If so, I guess this isn't a bug?

**Comment by othiym23** [comment]
No, completion should be brought into line with what `npm run` does now – the old behavior isn't coming back. We probably also need better tests around completion so we know when this kind of drift happens.

**Comment by othiym23** [comment]
I believe that 5abfc9c9017da714e47a3aece750836b4f9af6a9 fixes this, as noted by @mantoni. Closing for now, and can reopen if it turns out that `npm@2.9.1` still doesn't work the way you would expect. Thanks for bringing this to our attention!
