### ISSUE TITLE
npm init failing

### ISSUE THREAD

**Issue by stevengill** [npm/npm#7986]
I created a new directory and ran npm init. It shows me the default name, I press enter and I get the following stack.

npm-debug.log

<code>
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/var/nvm/v0.10.36/bin/npm', 'init' ]
2 info using npm@2.7.6
3 info using node@v0.10.36
4 silly package data undefined
5 info init written successfully
6 verbose type non_object_property_call
7 verbose stack TypeError: Cannot call method 'join' of undefined
7 verbose stack     at exports.name (/usr/local/var/nvm/v0.10.36/lib/node_modules/npm/node_modules/init-package-json/default-input.js:51:45)
7 verbose stack     at PromZard.<anonymous> (/usr/local/var/nvm/v0.10.36/lib/node_modules/npm/node_modules/init-package-json/node_modules/promzard/promzard.js:226:19)
7 verbose stack     at Interface.onLine (/usr/local/var/nvm/v0.10.36/lib/node_modules/npm/node_modules/read/lib/read.js:111:5)
7 verbose stack     at Interface.emit (events.js:95:17)
7 verbose stack     at Interface._onLine (readline.js:203:10)
7 verbose stack     at Interface._line (readline.js:532:8)
7 verbose stack     at Interface._ttyWrite (readline.js:761:14)
7 verbose stack     at ReadStream.onkeypress (readline.js:100:10)
7 verbose stack     at ReadStream.emit (events.js:98:17)
7 verbose stack     at emitKey (readline.js:1096:12)
8 verbose cwd /Users/steveng/repo/cordova/tests/testModule22
9 error Darwin 14.1.0
10 error argv "node" "/usr/local/var/nvm/v0.10.36/bin/npm" "init"
11 error node v0.10.36
12 error npm  v2.7.6
13 error Cannot call method 'join' of undefined
14 error If you need help, you may report this error at:
14 error     <https://github.com/npm/npm/issues>
15 verbose exit [ 1, true ]
</code>

If I change the name, no error. Only when I accept the default.

**Comment by KenanY** [comment]
@stevengill Does that default name have a capital letters? This looks like https://github.com/npm/npm/issues/7927 and https://github.com/npm/init-package-json/issues/37.

**Comment by stevengill** [comment]
@KenanY You are right! I will close this
