### ISSUE TITLE
i want the java library for DeployR version 7.1

### ISSUE THREAD

**Issue by sneha247129** [npm/npm#7987]
I m using the DelpoyR version 7.1. I m integrating the DeplyR with java portal.So I need the java client libraries for DeployR version 7.1. Wher can I get that?

Its urgent requirement for us.

Thanks,
Sneha

**Comment by KenanY** [comment]
@sneha247129 Sorry, this is the issue tracker for `npm`, the package manager for JavaScript. Your question has nothing to do with `npm` as far as I can tell, so it will be very difficult for you to find an answer here. Perhaps there is somewhere else you could take your question? A mailing list perhaps?

**Comment by sneha247129** [comment]
ok thanks.

**Comment by othiym23** [comment]
Closing as not relevant to npm, and also as resolved.
