### ISSUE TITLE
how to resolve shasum check failed while installing bower?

### ISSUE THREAD

**Issue by neahpanilag** [npm/npm#7991]
i'm new to npm and package manager in general and i'm trying to install bower to work my way. i tried to run this line: npm install -g bower. i got these errors and i've been searching on how to troubleshoot this and still couldn't find a working solution. 

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "bower"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4

npm ERR! shasum check failed for C:\Users\mehhh\AppData\Local\Temp\npm-2652-dabe
0b4e\registry.npmjs.org\bower\-\bower-1.4.1.tgz
npm ERR! Expected: a18be39d030792754f30f1c5b32d37b0156ba8dd
npm ERR! Actual:   d1923ca0127496d35b35a7ce11e802767870f1e0
npm ERR! From:     https://registry.npmjs.org/bower/-/bower-1.4.1.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\mehhh\npm-debug.log

**Comment by smikes** [comment]
It looks like you have a corrupt version of the bower package in your local npm cache.  Usually you can fix this by running

```
> npm clean cache bower
```

on your command line.  Can you try that and let us know if it worked or not?

**Comment by neahpanilag** [comment]
it works now. thanks @smikes .

**Comment by ericbarch** [comment]
Also wanted to chime in that I'm seeing this with bower currently. Cleaning my cache before the install doesn't seem to help either.

```
npm ERR! Linux 3.16.0-38-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "bower"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1

npm ERR! shasum check failed for /tmp/npm-5-b8488a21/registry.npmjs.org/rx/-/rx-2.5.3.tgz
npm ERR! Expected: 21adc7d80f02002af50dae97fd9dbf248755f566
npm ERR! Actual:   90a592379a2d104c91cc98bcefd5d37c678ac2d7
npm ERR! From:     https://registry.npmjs.org/rx/-/rx-2.5.3.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by grepruby** [comment]
Have same issue. Any help please ?

~# sudo npm install --global gulp
npm WARN engine get-stdin@5.0.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.40","npm":"2.14.3"})
npm ERR! Linux 3.2.0-90-generic-pae
npm ERR! argv "node" "/usr/bin/npm" "install" "--global" "gulp"
npm ERR! node v0.10.40
npm ERR! npm  v2.14.3

npm ERR! shasum check failed for /tmp/npm-29996-7e9d4fa3/registry.npmjs.org/findup-sync/-/findup-sync-0.2.1.tgz
npm ERR! Expected: e0a90a450075c49466ee513732057514b81e878c
npm ERR! Actual:   da39a3ee5e6b4b0d3255bfef95601890afd80709
npm ERR! From:     https://registry.npmjs.org/findup-sync/-/findup-sync-0.2.1.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log

**Comment by lukemadera** [comment]
+1 - can't get anything to install right now.. And it seems to be sporadic - a different package has issues most times; not always the same one. I'm trying different node and npm versions and that doesn't seem to help.

**Comment by JonFriesen** [comment]
+1 Looks like the actual checksum is the same for every package, so far I've failed on Cordova, create-hmac, and a few others, all shows the actual checksum as:

`da39a3ee5e6b4b0d3255bfef95601890afd80709`

**Comment by rbeltran** [comment]
+1 doing the bower specific clean made it take a little longer to fail but it still failed

**Comment by rbeltran** [comment]
oh it seems like it worked now. Getting WARN unmet dependency though. Not sure if that's normal

**Comment by JustJenFelice** [comment]
<p>+1 @JonFriesen - I get the same actual checksum as well:</p>
<code>Actual:   da39a3ee5e6b4b0d3255bfef95601890afd80709</code>
<p>I've done cache clean specific to bower and in general...no dice. Any suggestions would be much appreciated.</p>

**Comment by KenanY** [comment]
@grepruby @lukemadera @JonFriesen @JustJenFelice Please see http://status.npmjs.org/incidents/pyw00fmpjzrh, and try not to "revive" old, solved issues with comments regarding an issue you just recently began seeing.

**Comment by JustJenFelice** [comment]
<p>@KenanY - sorry about that...didn't realize the date of the original post</p>

**Comment by TsumiNa** [comment]
@grepruby  @JustJenFelice  @rbeltran 

Maybe you should use another registry. find a mirror fit you then

`npm config set registry https://registry.for.you.best/`

seems the main sever is not unstable.


```bash
liuchang@iMac:~|⇒  ping registry.npmjs.org
PING a.sni.fastly.net (103.245.222.162): 56 data bytes
64 bytes from 103.245.222.162: icmp_seq=0 ttl=56 time=11.179 ms
64 bytes from 103.245.222.162: icmp_seq=1 ttl=56 time=11.162 ms
64 bytes from 103.245.222.162: icmp_seq=2 ttl=54 time=10.697 ms
64 bytes from 103.245.222.162: icmp_seq=3 ttl=56 time=10.819 ms
64 bytes from 103.245.222.162: icmp_seq=4 ttl=56 time=11.243 ms
64 bytes from 103.245.222.162: icmp_seq=5 ttl=54 time=10.839 ms
64 bytes from 103.245.222.162: icmp_seq=6 ttl=56 time=10.827 ms
64 bytes from 103.245.222.162: icmp_seq=7 ttl=54 time=11.001 ms
64 bytes from 103.245.222.162: icmp_seq=8 ttl=56 time=11.018 ms
64 bytes from 103.245.222.162: icmp_seq=9 ttl=54 time=11.169 ms
64 bytes from 103.245.222.162: icmp_seq=10 ttl=56 time=11.116 ms
64 bytes from 103.245.222.162: icmp_seq=11 ttl=54 time=10.930 ms
Request timeout for icmp_seq 12
Request timeout for icmp_seq 13
Request timeout for icmp_seq 14
64 bytes from 103.245.222.162: icmp_seq=15 ttl=54 time=10.790 ms
64 bytes from 103.245.222.162: icmp_seq=16 ttl=56 time=11.265 ms
64 bytes from 103.245.222.162: icmp_seq=17 ttl=54 time=10.838 ms
64 bytes from 103.245.222.162: icmp_seq=18 ttl=56 time=11.458 ms
64 bytes from 103.245.222.162: icmp_seq=19 ttl=54 time=10.909 ms
64 bytes from 103.245.222.162: icmp_seq=20 ttl=54 time=10.996 ms
64 bytes from 103.245.222.162: icmp_seq=21 ttl=54 time=11.021 ms
Request timeout for icmp_seq 22
64 bytes from 103.245.222.162: icmp_seq=23 ttl=54 time=11.352 ms
64 bytes from 103.245.222.162: icmp_seq=24 ttl=56 time=11.059 ms
64 bytes from 103.245.222.162: icmp_seq=25 ttl=56 time=11.242 ms
64 bytes from 103.245.222.162: icmp_seq=26 ttl=54 time=10.956 ms
64 bytes from 103.245.222.162: icmp_seq=27 ttl=54 time=11.100 ms
64 bytes from 103.245.222.162: icmp_seq=28 ttl=56 time=11.009 ms
64 bytes from 103.245.222.162: icmp_seq=29 ttl=54 time=10.954 ms
64 bytes from 103.245.222.162: icmp_seq=30 ttl=56 time=11.490 ms
64 bytes from 103.245.222.162: icmp_seq=31 ttl=54 time=11.276 ms
64 bytes from 103.245.222.162: icmp_seq=32 ttl=56 time=10.983 ms
Request timeout for icmp_seq 33
64 bytes from 103.245.222.162: icmp_seq=34 ttl=56 time=10.990 ms
64 bytes from 103.245.222.162: icmp_seq=35 ttl=56 time=11.140 ms
64 bytes from 103.245.222.162: icmp_seq=36 ttl=54 time=11.338 ms
Request timeout for icmp_seq 37
64 bytes from 103.245.222.162: icmp_seq=38 ttl=54 time=11.260 ms
64 bytes from 103.245.222.162: icmp_seq=39 ttl=54 time=11.105 ms
Request timeout for icmp_seq 40
64 bytes from 103.245.222.162: icmp_seq=41 ttl=56 time=11.161 ms
64 bytes from 103.245.222.162: icmp_seq=42 ttl=56 time=11.312 ms
Request timeout for icmp_seq 43
Request timeout for icmp_seq 44
64 bytes from 103.245.222.162: icmp_seq=45 ttl=54 time=10.914 ms
64 bytes from 103.245.222.162: icmp_seq=46 ttl=54 time=10.971 ms
Request timeout for icmp_seq 47
64 bytes from 103.245.222.162: icmp_seq=48 ttl=56 time=11.062 ms
64 bytes from 103.245.222.162: icmp_seq=49 ttl=54 time=10.812 ms
64 bytes from 103.245.222.162: icmp_seq=50 ttl=54 time=11.117 ms
64 bytes from 103.245.222.162: icmp_seq=51 ttl=54 time=10.744 ms
64 bytes from 103.245.222.162: icmp_seq=52 ttl=56 time=11.245 ms
64 bytes from 103.245.222.162: icmp_seq=53 ttl=56 time=11.327 ms
Request timeout for icmp_seq 54
64 bytes from 103.245.222.162: icmp_seq=55 ttl=54 time=10.992 ms
Request timeout for icmp_seq 56
64 bytes from 103.245.222.162: icmp_seq=57 ttl=56 time=11.441 ms
64 bytes from 103.245.222.162: icmp_seq=58 ttl=54 time=11.121 ms
64 bytes from 103.245.222.162: icmp_seq=59 ttl=54 time=10.872 ms
64 bytes from 103.245.222.162: icmp_seq=60 ttl=54 time=10.932 ms
64 bytes from 103.245.222.162: icmp_seq=61 ttl=56 time=11.090 ms
64 bytes from 103.245.222.162: icmp_seq=62 ttl=54 time=11.291 ms
64 bytes from 103.245.222.162: icmp_seq=63 ttl=56 time=11.057 ms
64 bytes from 103.245.222.162: icmp_seq=64 ttl=54 time=10.875 ms
64 bytes from 103.245.222.162: icmp_seq=65 ttl=56 time=11.354 ms
64 bytes from 103.245.222.162: icmp_seq=66 ttl=54 time=11.197 ms
64 bytes from 103.245.222.162: icmp_seq=67 ttl=56 time=10.998 ms
64 bytes from 103.245.222.162: icmp_seq=68 ttl=54 time=11.108 ms
64 bytes from 103.245.222.162: icmp_seq=69 ttl=54 time=11.091 ms
64 bytes from 103.245.222.162: icmp_seq=70 ttl=56 time=11.193 ms
64 bytes from 103.245.222.162: icmp_seq=71 ttl=54 time=10.997 ms
64 bytes from 103.245.222.162: icmp_seq=72 ttl=56 time=11.265 ms
64 bytes from 103.245.222.162: icmp_seq=73 ttl=56 time=10.968 ms
64 bytes from 103.245.222.162: icmp_seq=74 ttl=54 time=11.182 ms
64 bytes from 103.245.222.162: icmp_seq=75 ttl=54 time=11.281 ms
64 bytes from 103.245.222.162: icmp_seq=76 ttl=54 time=10.651 ms
Request timeout for icmp_seq 77
Request timeout for icmp_seq 78
64 bytes from 103.245.222.162: icmp_seq=79 ttl=56 time=12.482 ms
64 bytes from 103.245.222.162: icmp_seq=80 ttl=56 time=10.783 ms
^C
--- a.sni.fastly.net ping statistics ---
81 packets transmitted, 67 packets received, 17.3% packet loss
round-trip min/avg/max/stddev = 10.651/11.096/12.482/0.255 ms
```

**Comment by zerongchen** [comment]
@smikes works ! thanks

**Comment by plmachado** [comment]
I'm trying to install express to create a server, and one of the steps says that I should put the npm install command inside the server directory I created earlier. I have this error, if anyone could help me ??

npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformerregistry.npmjs.org/void-elements.4\package\package.json writtenrittenn
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5

npm ERR! shasum check failed for C:\Users\Pedro\AppData\Local\Temp\npm-3672-5341d4a5\registry.npmjs.org\source-map\-\source-map-0.5.6.tgz
npm ERR! Expected: 75ce38f52bf0733c5a7f0c118d81334a2bb5f412
npm ERR! Actual:   f13591d8c5390f9924efe7a9ad5374b379ce8cd0
npm ERR! From:     https://registry.npmjs.org/source-map/-/source-map-0.5.6.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Pedro\miservidor\npm-debug.log
