### ISSUE TITLE
"npm install bwip" not working on rhcloud

### ISSUE THREAD

**Issue by lcp2000** [npm/npm#7993]
Hi, while trying to run "npm install bwip" on rhcloud, I get the following errors (no log). Permissions?

Thanks, 
Bill

```
[nodejs.rhcloud.com 55302998e0b8cdb510000025]\> npm install bwip
npm ERR! tar.unpack untar error /var/lib/openshift/55302998e0b8cdb510000025/.npm
/bwip/0.7.1/package.tgz
npm ERR! Linux 2.6.32-504.3.3.el6.x86_64
npm ERR! argv "node" "/var/lib/openshift/55302998e0b8cdb510000025/app-root/data/
node-v0.12.0-linux-x64/bin/npm" "install" "bwip"
npm ERR! node v0.12.0
npm ERR! npm  v2.7.6
npm ERR! path /var/lib/openshift/55302998e0b8cdb510000025/node_modules
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, mkdir '/var/lib/openshift/55302998e0b8cdb510000025/node_
modules'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, mkdir '/var/lib/openshift/55302998e0b8cdb510000025/n
ode_modules']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/var/lib/openshift/55302998e0b8cdb510000025/node_modules',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/var/lib/openshift/55302998e0b8cdb510000025/node_modul
es/bwip',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack:
npm ERR!    [ '/var/lib/openshift/55302998e0b8cdb510000025/app-root/data/node-v0
.12.0-linux-x64/lib/node_modules/npm/node_modules/fstream/lib/writer.js:171:23',

npm ERR!      '/var/lib/openshift/55302998e0b8cdb510000025/app-root/data/node-v0
.12.0-linux-x64/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53',
npm ERR!      'FSReqWrap.oncomplete (fs.js:99:15)' ] }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
npm ERR! Linux 2.6.32-504.3.3.el6.x86_64
npm ERR! argv "node" "/var/lib/openshift/55302998e0b8cdb510000025/app-root/data/
node-v0.12.0-linux-x64/bin/npm" "install" "bwip"
npm ERR! node v0.12.0
npm ERR! npm  v2.7.6

npm ERR! Uncaught, unspecified "error" event.
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /var/lib/openshift/55302998e0b8cdb510000025/npm-debug.log
```

**Comment by smikes** [comment]
Yes, this looks like a permission problem, specifically, `npm` can't create this directory:

```
/var/lib/openshift/55302998e0b8cdb510000025/node_modules
```

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.

**Comment by KonQuestNow** [comment]
I still get this issue:

`npm install newman`

`npm ERR! Error: EACCES, mkdir '/var/lib/openshift/572ad9ad2d52711e5f000153/.npm'
npm ERR!  { [Error: EACCES, mkdir '/var/lib/openshift/572ad9ad2d52711e5f000153/.npm']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/var/lib/openshift/572ad9ad2d52711e5f000153/.npm' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 2.6.32-642.6.2.el6.x86_64
npm ERR! command "node" "/usr/bin/npm" "install" "newman"
npm ERR! cwd /tmp
npm ERR! node -v v0.6.20
npm ERR! npm -v 1.1.37
npm ERR! path /var/lib/openshift/572ad9ad2d52711e5f000153/.npm
npm ERR! code EACCES
npm ERR! message EACCES, mkdir '/var/lib/openshift/572ad9ad2d52711e5f000153/.npm'
npm ERR! errno 3
npm ERR! 3 errno
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /tmp/npm-debug.log
npm ERR! not ok code undefined
npm ERR! not ok code 3`
