### ISSUE TITLE
Error on install Yeoman!! Help-me

### ISSUE THREAD

**Issue by eduardoborges** [npm/npm#7996]
Checkout the error:
https://gist.github.com/eduardoborges/b89c67ace4541520add4

I cant install Yeoman, help, pls. :(

**Comment by smikes** [comment]
There are a couple of problems here.

For some Linux distributions (Debian/Ubuntu and RedHat/CentOS), the latest node version provided by the distribution may lag behind the stable version. [Here are instructions from NodeSource](https://github.com/nodesource/distributions) on getting the latest node.

Also, I saw this at the end of your npm-debug.log -

```
sh: 1: yodoctor: Permission denied
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
```

This usually means that you need to also install the debian package `nodejs-legacy`:

```
$ sudo apt-get install nodejs-legacy
```


Thanks!

**Comment by eduardoborges** [comment]
Oh, thanks! Resolved! :D
