### ISSUE TITLE
Git dependency with scoped module not pulling all files from repo

### ISSUE THREAD

**Issue by mscappini** [npm/npm#7998]
I have a weird situation occurring that I can't seem to figure out. I'm relatively new to Node and npm, and I was trying out the git:// dependency syntax when I noticed this issue.

I'm working in a Github org where we scope all of our modules for the sake of organization. None of them are published. However, we'd like to re-use one of these modules in other projects, so instead of having to publish the module, I've just referenced it via a Git dependency, like so:

"dependencies": {
        "@optbot/cfgloader": "git://github.com/optbot/cfgloader.git#mark"
}

Before merging to master, I wanted to test this feature on my branch. The "mark" branch (my branch) contains the package.json file that npm needs to install it as a Node module. `cfgloader`'s package.json "name" key is defined as **"name": "@optbot/cfgloader"** to scope it. But when I run `npm install`, it downloads all of the files from that repo that are NOT a directory. (There's a `lib` directory in there that isn't getting checked out, nor does it pull the `nconf` dependency defined in `cfgloader`'s dependencies.)

I am using Node 0.12.1 and npm 2.5.1 on Windows 8.1.

Am I doing something wrong?

**Comment by smikes** [comment]
There have been a lot of changes (mostly bugfixes) to the git support in `npm` recently.  Can you try updating your `npm` to the latest version?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows

**Comment by mscappini** [comment]
Okay, I updated `npm` from 2.5.1 to 2.8.3. I run `npm install` and still have the same issue. There are no errors or anything, so I assume `npm` thinks everything is cool.

**Comment by smikes** [comment]
Thanks for trying that out.  I can reproduce the error on my machine (OSX, io.js 1.7.1, npm@2.8.4),  but so far I have no idea what's causing it...

**Comment by mscappini** [comment]
Interesting problem. I thought for sure I was doing something wrong. Perhaps it's actually a bug.

**Comment by mscappini** [comment]
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'install',
npm verb cli   '--loglevel',
npm verb cli   'silly' ]
npm info using npm@2.8.3
npm info using node@v0.12.1
npm verb node symlink C:\Program Files\nodejs\\node.exe
npm verb readDependencies loading dependencies from D:\Source\Projects\invbot\OptBot\restapi\package.json
npm verb install where, deps [ 'D:\\Source\\Projects\\invbot\\OptBot\\restapi',
npm verb install   [ '@optbot/cfgloader',
npm verb install     'express',
npm verb install     'mongodb',
npm verb install     'nconf',
npm verb install     'yargs',
npm verb install     'chai',
npm verb install     'jscs',
npm verb install     'jshint',
npm verb install     'mocha' ] ]
npm verb install where, peers [ 'D:\\Source\\Projects\\invbot\\OptBot\\restapi', [] ]
npm verb installManyTop reading for lifecycle D:\Source\Projects\invbot\OptBot\restapi\package.json
npm info preinstall @optbot/restapi@0.0.1
npm verb installManyTop reading scoped package data from D:\Source\Projects\invbot\OptBot\restapi\node_modules\chai\package.json
npm verb installManyTop reading scoped package data from D:\Source\Projects\invbot\OptBot\restapi\node_modules\express\package.json
npm verb installManyTop reading scoped package data from D:\Source\Projects\invbot\OptBot\restapi\node_modules\jscs\package.json
npm verb installManyTop reading scoped package data from D:\Source\Projects\invbot\OptBot\restapi\node_modules\jshint\package.json
npm verb installManyTop reading scoped package data from D:\Source\Projects\invbot\OptBot\restapi\node_modules\mocha\package.json
npm verb installManyTop reading scoped package data from D:\Source\Projects\invbot\OptBot\restapi\node_modules\mongodb\package.json
npm verb installManyTop reading scoped package data from D:\Source\Projects\invbot\OptBot\restapi\node_modules\nconf\package.json
npm verb installManyTop reading scoped package data from D:\Source\Projects\invbot\OptBot\restapi\node_modules\yargs\package.json
npm verb readDependencies loading dependencies from D:\Source\Projects\invbot\OptBot\restapi\package.json
npm verb targetResolver reading package data from D:\Source\Projects\invbot\OptBot\restapi\node_modules\chai\package.json
npm verb targetResolver reading package data from D:\Source\Projects\invbot\OptBot\restapi\node_modules\express\package.json
npm verb targetResolver reading package data from D:\Source\Projects\invbot\OptBot\restapi\node_modules\jscs\package.json
npm verb targetResolver reading package data from D:\Source\Projects\invbot\OptBot\restapi\node_modules\jshint\package.json
npm verb targetResolver reading package data from D:\Source\Projects\invbot\OptBot\restapi\node_modules\mocha\package.json
npm verb targetResolver reading package data from D:\Source\Projects\invbot\OptBot\restapi\node_modules\mongodb\package.json
npm verb targetResolver reading package data from D:\Source\Projects\invbot\OptBot\restapi\node_modules\nconf\package.json
npm verb targetResolver reading package data from D:\Source\Projects\invbot\OptBot\restapi\node_modules\yargs\package.json
npm verb targetResolver reading package data from D:\Source\Projects\invbot\OptBot\restapi\node_modules\.bin\jscs\package.json
npm verb targetResolver reading package data from D:\Source\Projects\invbot\OptBot\restapi\node_modules\.bin\jscs.cmd\package.json
npm verb targetResolver reading package data from D:\Source\Projects\invbot\OptBot\restapi\node_modules\.bin\jshint\package.json
npm verb targetResolver reading package data from D:\Source\Projects\invbot\OptBot\restapi\node_modules\.bin\jshint.cmd\package.json
npm verb targetResolver reading package data from D:\Source\Projects\invbot\OptBot\restapi\node_modules\.bin\mocha\package.json
npm verb targetResolver reading package data from D:\Source\Projects\invbot\OptBot\restapi\node_modules\.bin\mocha.cmd\package.json
npm verb already installed skipping mocha@~2.2.4 D:\Source\Projects\invbot\OptBot\restapi
npm sill cache add args [ '@optbot/cfgloader@git://github.com/optbot/cfgloader.git#mark',
npm sill cache add   null ]
npm verb cache add spec @optbot/cfgloader@git://github.com/optbot/cfgloader.git#mark
npm verb already installed skipping express@~4.12.3 D:\Source\Projects\invbot\OptBot\restapi
npm verb already installed skipping mongodb@~2.0.27 D:\Source\Projects\invbot\OptBot\restapi
npm verb already installed skipping nconf@~0.7.1 D:\Source\Projects\invbot\OptBot\restapi
npm verb already installed skipping yargs@~3.7.1 D:\Source\Projects\invbot\OptBot\restapi
npm verb already installed skipping chai@~2.2.0 D:\Source\Projects\invbot\OptBot\restapi
npm verb already installed skipping jscs@~1.12.0 D:\Source\Projects\invbot\OptBot\restapi
npm verb already installed skipping jshint@~2.7.0 D:\Source\Projects\invbot\OptBot\restapi
npm sill cache add parsed spec { raw: '@optbot/cfgloader@git://github.com/optbot/cfgloader.git#mark',
npm sill cache add   scope: '@optbot',
npm sill cache add   name: '@optbot/cfgloader',
npm sill cache add   rawSpec: 'git://github.com/optbot/cfgloader.git#mark',
npm sill cache add   spec: 'git://github.com/optbot/cfgloader.git#mark',
npm sill cache add   type: 'hosted',
npm sill cache add   hosted: 
npm sill cache add    { type: 'github',
npm sill cache add      ssh: 'git@github.com:optbot/cfgloader.git#mark',
npm sill cache add      sshUrl: 'git+ssh://git@github.com/optbot/cfgloader.git#mark',
npm sill cache add      httpsUrl: 'git+https://github.com/optbot/cfgloader.git#mark',
npm sill cache add      gitUrl: 'git://github.com/optbot/cfgloader.git#mark',
npm sill cache add      shortcut: 'github:optbot/cfgloader#mark',
npm sill cache add      directUrl: 'https://raw.githubusercontent.com/optbot/cfgloader/mark/package.json' } }
npm verb addRemoteGit caching git://github.com/optbot/cfgloader.git#mark
npm verb addRemoteGit git://github.com/optbot/cfgloader.git#mark is a repository hosted by github
npm sill tryClone cloning git://github.com/optbot/cfgloader.git#mark via git://github.com/optbot/cfgloader.git#mark
npm verb tryClone git-github-com-optbot-cfgloader-git-dbf64213 not in flight; caching
npm info git [ 'config', '--get', 'remote.origin.url' ]
npm sill validateExistingRemote git://github.com/optbot/cfgloader.git#mark remote.origin.url: git://github.com/optbot/cfgloader.git
npm verb validateExistingRemote git://github.com/optbot/cfgloader.git#mark is updating existing cached remote C:\Users\Mark\AppData\Roaming\npm-cache\_git-remotes\git-github-com-optbot-cfgloader-git-dbf64213
npm info git [ 'fetch', '-a', 'origin' ]
npm verb updateRemote git fetch -a origin (git://github.com/optbot/cfgloader.git) 
npm verb setPermissions git://github.com/optbot/cfgloader.git#mark skipping chownr on Windows
npm verb resolveHead git://github.com/optbot/cfgloader.git#mark original treeish: mark
npm info git [ 'rev-list', '-n1', 'mark' ]
npm sill resolveHead git://github.com/optbot/cfgloader.git#mark resolved treeish: b7a2a8b9bfa877fa89936856c2709c0ae32e2402
npm verb resolveHead git://github.com/optbot/cfgloader.git#mark resolved Git URL: git://github.com/optbot/cfgloader.git#b7a2a8b9bfa877fa89936856c2709c0ae32e2402
npm sill resolveHead Git working directory: C:\Users\Mark\AppData\Local\Temp\npm-16524-778db873\git-cache-bec71b028c9d\b7a2a8b9bfa877fa89936856c2709c0ae32e2402
npm info git [ 'clone',
npm info git   'C:\\Users\\Mark\\AppData\\Roaming\\npm-cache\\_git-remotes\\git-github-com-optbot-cfgloader-git-dbf64213',
npm info git   'C:\\Users\\Mark\\AppData\\Local\\Temp\\npm-16524-778db873\\git-cache-bec71b028c9d\\b7a2a8b9bfa877fa89936856c2709c0ae32e2402' ]
npm verb cloneResolved git://github.com/optbot/cfgloader.git#mark clone Cloning into 'C:\Users\Mark\AppData\Local\Temp\npm-16524-778db873\git-cache-bec71b028c9d\b7a2a8b9bfa877fa89936856c2709c0ae32e2402'...
npm verb cloneResolved done.
npm info git [ 'checkout', 'b7a2a8b9bfa877fa89936856c2709c0ae32e2402' ]
npm verb checkoutTreeish git://github.com/optbot/cfgloader.git#mark checkout Note: checking out 'b7a2a8b9bfa877fa89936856c2709c0ae32e2402'.
npm verb checkoutTreeish 
npm verb checkoutTreeish You are in 'detached HEAD' state. You can look around, make experimental
npm verb checkoutTreeish changes and commit them, and you can discard any commits you make in this
npm verb checkoutTreeish state without impacting any branches by performing another checkout.
npm verb checkoutTreeish 
npm verb checkoutTreeish If you want to create a new branch to retain commits you create, you may
npm verb checkoutTreeish do so (now or later) by using -b with the checkout command again. Example:
npm verb checkoutTreeish 
npm verb checkoutTreeish   git checkout -b new_branch_name
npm verb checkoutTreeish 
npm verb checkoutTreeish HEAD is now at b7a2a8b... Moved the loader into lib/.
npm verb addLocalDirectory C:\Users\Mark\AppData\Roaming\npm-cache\@optbot\cfgloader\0.0.1\package.tgz not in flight; packing
npm verb tar pack [ 'C:\\Users\\Mark\\AppData\\Roaming\\npm-cache\\@optbot\\cfgloader\\0.0.1\\package.tgz',
npm verb tar pack   'C:\\Users\\Mark\\AppData\\Local\\Temp\\npm-16524-778db873\\git-cache-bec71b028c9d\\b7a2a8b9bfa877fa89936856c2709c0ae32e2402' ]
npm verb tarball C:\Users\Mark\AppData\Roaming\npm-cache\@optbot\cfgloader\0.0.1\package.tgz
npm verb folder C:\Users\Mark\AppData\Local\Temp\npm-16524-778db873\git-cache-bec71b028c9d\b7a2a8b9bfa877fa89936856c2709c0ae32e2402
npm verb addLocalTarball adding from inside cache C:\Users\Mark\AppData\Roaming\npm-cache\@optbot\cfgloader\0.0.1\package.tgz
npm verb addRemoteGit data._from: git://github.com/optbot/cfgloader.git#mark
npm verb addRemoteGit data._resolved: git://github.com/optbot/cfgloader.git#b7a2a8b9bfa877fa89936856c2709c0ae32e2402
npm sill cache afterAdd @optbot/cfgloader@0.0.1
npm verb afterAdd C:\Users\Mark\AppData\Roaming\npm-cache\@optbot\cfgloader\0.0.1\package\package.json not in flight; writing
npm verb afterAdd C:\Users\Mark\AppData\Roaming\npm-cache\@optbot\cfgloader\0.0.1\package\package.json written
npm sill install resolved [ { name: '@optbot/cfgloader',
npm sill install resolved     version: '0.0.1',
npm sill install resolved     description: 'Configuration loader for the optbot services.',
npm sill install resolved     main: 'lib/cfgloader.js',
npm sill install resolved     repository: { type: 'git', url: 'git://github.com/optbot/cfgloader.git' },
npm sill install resolved     scripts: { test: 'echo "Error: no test specified" && exit 1' },
npm sill install resolved     private: true,
npm sill install resolved     author: { name: 'Marshall Farrier, Robert Rodriguez, Mark Scappini' },
npm sill install resolved     license: 'MIT',
npm sill install resolved     files: [ 'cfgloader.js', 'LICENSE', 'README.md' ],
npm sill install resolved     dependencies: { nconf: '~0.7.1' },
npm sill install resolved     devDependencies: 
npm sill install resolved      { chai: '~2.2.0',
npm sill install resolved        jscs: '~1.12.0',
npm sill install resolved        jshint: '~2.7.0',
npm sill install resolved        mocha: '~2.2.4' },
npm sill install resolved     gitHead: 'b7a2a8b9bfa877fa89936856c2709c0ae32e2402',
npm sill install resolved     readme: 'OptBot Configuration Loader\r\n===========================\r\nDescription\r\n--\r\nConfiguration loader for the optbot services.\r\n\r\nUsage\r\n--\r\n\r\n`require(\'@optbot/cfgloader\')`',
npm sill install resolved     readmeFilename: 'README.md',
npm sill install resolved     bugs: { url: 'https://github.com/optbot/cfgloader/issues' },
npm sill install resolved     homepage: 'https://github.com/optbot/cfgloader#readme',
npm sill install resolved     _id: '@optbot/cfgloader@0.0.1',
npm sill install resolved     _shasum: '855652a267812479c328d41c1c503e398aa3b224',
npm sill install resolved     _from: 'git://github.com/optbot/cfgloader.git#mark',
npm sill install resolved     _resolved: 'git://github.com/optbot/cfgloader.git#b7a2a8b9bfa877fa89936856c2709c0ae32e2402' } ]
npm info install @optbot/cfgloader@0.0.1 into D:\Source\Projects\invbot\OptBot\restapi
npm info installOne @optbot/cfgloader@0.0.1
npm verb installOne of @optbot/cfgloader to D:\Source\Projects\invbot\OptBot\restapi not in flight; installing
npm verb lock using C:\Users\Mark\AppData\Roaming\npm-cache\_locks\optbot-cfgloader-70a4bdb7dc1d25f2.lock for D:\Source\Projects\invbot\OptBot\restapi\node_modules\@optbot\cfgloader
npm sill install write writing @optbot/cfgloader 0.0.1 to D:\Source\Projects\invbot\OptBot\restapi\node_modules\@optbot\cfgloader
npm verb unbuild node_modules\@optbot\cfgloader
npm sill gentlyRm D:\Source\Projects\invbot\OptBot\restapi\node_modules\@optbot\cfgloader is being purged from base D:\Source\Projects\invbot\OptBot\restapi
npm verb gentlyRm don't care about contents; nuking D:\Source\Projects\invbot\OptBot\restapi\node_modules\@optbot\cfgloader
npm verb tar unpack C:\Users\Mark\AppData\Roaming\npm-cache\@optbot\cfgloader\0.0.1\package.tgz
npm verb tar unpacking to D:\Source\Projects\invbot\OptBot\restapi\node_modules\@optbot\cfgloader
npm sill gentlyRm D:\Source\Projects\invbot\OptBot\restapi\node_modules\@optbot\cfgloader is being purged 
npm verb gentlyRm don't care about contents; nuking D:\Source\Projects\invbot\OptBot\restapi\node_modules\@optbot\cfgloader
npm sill gunzTarPerm modes [ '777', '666' ]
npm sill gunzTarPerm extractEntry package.json
npm sill gunzTarPerm extractEntry README.md
npm sill gunzTarPerm extractEntry LICENSE
npm verb write writing to D:\Source\Projects\invbot\OptBot\restapi\node_modules\@optbot\cfgloader\package.json
npm info preinstall @optbot/cfgloader@0.0.1
npm verb readDependencies loading dependencies from D:\Source\Projects\invbot\OptBot\restapi\node_modules\@optbot\cfgloader\package.json
npm verb readDependencies loading dependencies from D:\Source\Projects\invbot\OptBot\restapi\node_modules\@optbot\cfgloader\package.json
npm sill install resolved []
npm verb about to build D:\Source\Projects\invbot\OptBot\restapi\node_modules\@optbot\cfgloader
npm info build D:\Source\Projects\invbot\OptBot\restapi\node_modules\@optbot\cfgloader
npm info linkStuff @optbot/cfgloader@0.0.1
npm sill linkStuff @optbot/cfgloader@0.0.1 has D:\Source\Projects\invbot\OptBot\restapi\node_modules as its parent node_modules
npm verb linkBins @optbot/cfgloader@0.0.1
npm verb linkMans @optbot/cfgloader@0.0.1
npm verb rebuildBundles @optbot/cfgloader@0.0.1
npm info install @optbot/cfgloader@0.0.1
npm info postinstall @optbot/cfgloader@0.0.1
npm verb unlock done using C:\Users\Mark\AppData\Roaming\npm-cache\_locks\optbot-cfgloader-70a4bdb7dc1d25f2.lock for D:\Source\Projects\invbot\OptBot\restapi\node_modules\@optbot\cfgloader
npm info build D:\Source\Projects\invbot\OptBot\restapi
npm info linkStuff @optbot/restapi@0.0.1
npm sill linkStuff @optbot/restapi@0.0.1 has D:\Source\Projects\invbot as its parent node_modules
npm verb linkBins @optbot/restapi@0.0.1
npm verb linkMans @optbot/restapi@0.0.1
npm verb rebuildBundles @optbot/restapi@0.0.1
npm verb rebuildBundles [ '.bin',
npm verb rebuildBundles   '@optbot',
npm verb rebuildBundles   'chai',
npm verb rebuildBundles   'express',
npm verb rebuildBundles   'jscs',
npm verb rebuildBundles   'jshint',
npm verb rebuildBundles   'mocha',
npm verb rebuildBundles   'mongodb',
npm verb rebuildBundles   'nconf',
npm verb rebuildBundles   'yargs' ]
npm info install @optbot/restapi@0.0.1
npm info postinstall @optbot/restapi@0.0.1
npm info prepublish @optbot/restapi@0.0.1
npm verb validateInstall loading D:\Source\Projects\invbot\OptBot\restapi\package.json for validation
@optbot/cfgloader@0.0.1 node_modules\@optbot\cfgloader
npm verb exit [ 0, true ]
npm info ok

**Comment by mscappini** [comment]
I found that if I execute the same Git commands and hash provided from the log, it looks as though the `lib/` directory is actually included just fine. But if I go and look at the tar file that was created from the `npm cache`, it does not include the `lib/` folder.

**Comment by smikes** [comment]
Ha!  I bet it's a race condition between the files landing on disk and the npm-fstream-tar spinning up,
 and I bet it's triggered because git branch checkout takes a little bit longer than a HEAD or tag checkout.

Thanks, this looks like a fun one.

**Comment by mscappini** [comment]
Interesting thought, but I'm not so sure! If you inspect the pkgData in `npm/lib/cache/add-local.js`, you can see that the files collection actually has the file (cfgloader.js) that resides within the `lib/` directory, but it's not prefixed with the `lib/` directory. It's just considered to be among the same files located in the root along with the README.md and LICENSE files (properly excluding the package.json). This makes me wonder if the fstream-tar can't tar that file because it can't find it at the level that pkgData is reporting it to be.

**Comment by mscappini** [comment]
Ah, it looks like I had a "files" field in the package.json, and it was pointing to the old location of the main JS file. If I just omit the files field entirely, it picks up the `lib/` directory and file just fine.

**Comment by smikes** [comment]
Oh! Sorry for not thinking of that. I don't use "files" but it's absolutely the cause here.
