### ISSUE TITLE
Error when using npm install Intellij Idea

### ISSUE THREAD

**Issue by anshbansal** [npm/npm#8000]
I am getting the below error when I used npm install. I used it to install default template for angular js in intellij idea.

npm WARN optional dep failed, continuing fsevents@0.2.1
npm ERR! Error: shasum check failed for /home/aseem/tmp/npm-4114-xSHlstov/1429346217235-0.043880666606128216/tmp.tgz
npm ERR! Expected: 03726561bc268f2e5444f54c665b7fd4a8c029e2
npm ERR! Actual:   1c971ace888189226d22e8b54586fb511994ec6a
npm ERR!     at /usr/lib/nodejs/sha/index.js:38:8
npm ERR!     at ReadStream.<anonymous> (/usr/lib/nodejs/sha/index.js:85:7)
npm ERR!     at ReadStream.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-48-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/aseem/projects/practice/angular/test
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10

**Comment by smikes** [comment]
It looks like you have quite an old version of `node` and `npm`.  

For some Linux distributions (Debian/Ubuntu and RedHat/CentOS), the latest node version provided by the distribution may lag behind the stable version. [Here are instructions from NodeSource](https://github.com/nodesource/distributions) on getting the latest node.

Also, it looks like you're running into a problem that older versions of `npm` had, where corrupt versions of downloaded packages were written to the `npm` cache.  You can clean up the cache by running

```
npm cache clean
```

**Comment by anshbansal** [comment]
Using Nodesource my node was updated to 0.10.38. Not exactly the latest one but that solved my problem.
