### ISSUE TITLE
npm login doesn't work - unknown error

### ISSUE THREAD

**Issue by SMKS** [npm/npm#8002]
Put in the correct login credentials both on windows and mac. Error below:

npm http PUT https://registry.npmjs.org/-/user/org.couchdb.user:smks
npm http 400 https://registry.npmjs.org/-/user/org.couchdb.user:smks
npm ERR! Error: Unknown error while authenticating : -/user/org.couchdb.user:smks
npm ERR!     at RegClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:272:14)
npm ERR!     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:129:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:873:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:824:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "login"
npm ERR! cwd C:\Users\Shaun Stone\Desktop\ab-significance
npm ERR! node -v v0.10.20
npm ERR! npm -v 1.3.11
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\Shaun Stone\Desktop\ab-significance\npm-debug.log
npm ERR! not ok code 0

**Comment by KenanY** [comment]
@SMKS Could you first try [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows)?

**Comment by SMKS** [comment]
was on 1.3 :/ and fixed. Thanks.
