### ISSUE TITLE
Publish private module

### ISSUE THREAD

**Issue by corbinu** [npm/npm#8003]
I just signed up for the new private modules and am trying to move a module I had been keeping private via get to npm and I get this error:

```
npm publish                                                                                                                               [13:17:43]
npm ERR! Darwin 14.3.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "publish"
npm ERR! node v1.7.1
npm ERR! npm  v2.8.4

npm ERR! This package has been marked as private
npm ERR! Remove the 'private' field from the package.json to publish it.
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

Should this package not be able to be published under my private scope? My understanding is if I remove the "private" tag, publish and then run `npm access restricted` that the package may be public for a few min based upon reading this: 

https://www.npmjs.com/private-modules

which says "The package will be removed from listings on the site within a few minutes of making it private."

If this is incorrect or the process for publishing a module directly to private mode is different please let me know.

**Comment by smikes** [comment]
I think you are correct. You definitely need to remove the `"private": true` in order to publish to the npm registry.  

It may be possible to specify `access restricted` via a publish-config setting, but I am not familiar with that part of the client.

**Comment by corbinu** [comment]
Thanks much that helped yes the answer was to remove "private: true" ... add my username scope to the package name and then "npm publish --access restricted"

**Comment by smikes** [comment]
Correction to the above:

When you initially publish a scoped module, if you specify `--access=public`, the module will be public

If you don't specify `--access` or if you specify `--access restricted` then the module will be private (and you must have a paid account)

Thanks to @bcoe and I'm glad that my initial (though incorrect) posting got you on the track to figure it out yourself.

**Comment by smikes** [comment]
I have made a PR to fix the docs on npm-scope , to describe how scope and public / private modules interact.  I'd be grateful if you'd look them over and let me know if you think they can be improved further -- https://github.com/npm/npm/issues/8007

**Comment by corbinu** [comment]
There is a typo where it still says scoped packages are not supported on line 16 other then that looks great! Thanks
