### ISSUE TITLE
return log file & reply error(native)                                  

### ISSUE THREAD

**Issue by iaditya** [npm/npm#8004]
```
Adityas-MacBook-Air:~ aditya$ npm install -g express
npm WARN locking Error: EACCES, open '/Users/aditya/.npm/_locks/express-59b5b7164c5e2658.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/aditya/.npm/_locks/express-59b5b7164c5e2658.lock failed { [Error: EACCES, open '/Users/aditya/.npm/_locks/express-59b5b7164c5e2658.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/aditya/.npm/_locks/express-59b5b7164c5e2658.lock' }
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "express"
npm ERR! node v0.12.2
npm ERR! npm  v2.8.3
```

**Comment by KenanY** [comment]
@iaditya Looks like a permissions issue. Could you try the following?:

``` sh
$ sudo chown -R $(whoami) "$HOME/.npm"
```

**Comment by iaditya** [comment]
thank you.
Can you please describe more?

**Comment by iaditya** [comment]
what does this command do?

**Comment by KenanY** [comment]
@iaditya 

  - `sudo`: execute a command as another user
  - `chown`: change file owner and group
  - `-R`: operate on files and directories recursively
  - `$(whoami)`: print effective userid
  - `"$HOME/.npm"`: the `npm` cache directory

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
