### ISSUE TITLE
Error using yeoman generator when installing dependencies 

### ISSUE THREAD

**Issue by AsaToburen** [npm/npm#8005]
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.1
npm ERR! npm  v2.8.3

null == true

I would add debug log but body is too long.. if someone knows the relevant section to upload I can provide.

**Comment by watilde** [comment]
@AsaToburen Hello! How about to use `gist` or something like note hosting service to upload your `npm-debug.log`?

**Comment by smikes** [comment]
Hi! This is almost certainly a known bug in node 0.12.0 and 0.12.1 and can be fixed by upgrading to node 0.12.2 (or downgrading to 0.10.38).

If you do run into it again, please upload your npm-debug.log to https://gist.github.com/ and put the link to the `gist` into your issue.

Thanks!

**Comment by AsaToburen** [comment]
Upgrading to 0.12.2 fixed the issue. Thanks for your help!
