### ISSUE TITLE
Installing package: Binary not found

### ISSUE THREAD

**Issue by orschiro** [npm/npm#8010]
Dear all, 

I am experiencing the issue that the binary I am installing is not found on my path. I use npm from `nodejs 0.12.2-rwky1~trusty` on elementary OS Freya (based on Ubuntu 14.04). I tried to install the package `watchy`:

```
 sudo npm install npm -g                                                      ⏎
/usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js
npm@2.8.3 /usr/lib/node_modules/npm
~ ❯❯❯ npm install watchy
npm WARN optional dep failed, continuing fsevents@0.3.5
watchy@0.6.2 node_modules/watchy
├── herit@2.2.2
├── underscore@1.8.3
├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.0.1, supports-color@1.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)
├── optimist@0.6.1 (wordwrap@0.0.2, minimist@0.0.10)
└── chokidar@1.0.1 (arrify@1.0.0, is-glob@1.1.3, glob-parent@1.2.0, async-each@0.1.6, is-binary-path@1.0.0, readdirp@1.3.0, anymatch@1.2.1)
```

However, after installation, `watchy` is not found on my path:

```
~ ❯❯❯ watch
 -- corrections (errors: 1) --
watch  watch
 -- original --
watchy
```

Could anyone please help me with some tips?

Thank you very much!

Robert

**Comment by KenanY** [comment]
@orschiro You should install `watchy` _globally_ if you want it in your `PATH`:

``` sh
$ npm install -g watchy
```

**Comment by orschiro** [comment]
@KenanY 

Apologise for my beginner mistake. Installing it globally indeed does provide it on my `PATH`:

```
$ sudo npm install -g watchy
```

**Comment by othiym23** [comment]
Closing as resolved!
