### ISSUE TITLE
Use HTTP_PROXY and HTTPS_PROXY for proxy config

### ISSUE THREAD

**Issue by mdamien** [npm/npm#8011]
Looks like npm is ignoring the HTTP_PROXY and HTTPS_PROXY env var.

Looks like the problem is here: https://github.com/npm/npm/blob/448efd0eaa6f97af0889bf47efc543a1ea2f8d7e/lib/cache/caching-client.js#L196-L197

Would be more convenient if npm would just follow the env vars if nothing is set.

The code to modify is here: https://github.com/npm/npm/blob/91f5cb1fb91520fbe25a4da5b80848ed540b9ad3/lib/config/core.js#L348-L365

Will do a PR when I have the time

**Comment by smikes** [comment]
Thanks for the bug report.

`npm` doesn't use the http_proxy or https_proxy environment variables directly.  Instead, `npm`, uses the `request` module (see https://github.com/request/request), which is expected to honor the variables.

Can you tell us a bit more about the context of the error you are seeing?

**Comment by mdamien** [comment]
In fact, I made the PR a bit too fast. You're using the HTTP_PROXY env var. Sorry :sweat_smile:

 You're just having a problem with https proxies. I saw something similar with python `urllib` and I fixed it by using `urlib2` (or `requests`). Now it's more a bug for `request`.

Here is a trace for history:
        $ export https_proxy="https://myproxy:3128"
        $ npm install jasmine
        npm http GET https://registry.npmjs.org/jasmine
        npm http GET https://registry.npmjs.org/jasmine
        npm http GET https://registry.npmjs.org/jasmine
        npm ERR! network tunneling socket could not be established, cause=139996955195264:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:795:
        npm ERR! network 
        npm ERR! network This is most likely not a problem with npm itself
        npm ERR! network and is related to network connectivity.
        npm ERR! network In most cases you are behind a proxy or have bad network settings.
        npm ERR! network 
        npm ERR! network If you are behind a proxy, please make sure that the
        npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

        npm ERR! System Linux 3.13.0-49-generic
        npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "jasmine"
        npm ERR! cwd /home/bob/prog/__/ntest
        npm ERR! node -v v0.10.25
        npm ERR! npm -v 1.3.10
        npm ERR! code ECONNRESET
        npm ERR! 
        npm ERR! Additional logging details can be found in:
        npm ERR!     /home/bob/prog/__/ntest/npm-debug.log
        npm ERR! not ok code 0

And when I set my http_proxy var to a normal "http//" proxy, it works.

So, gonna find the bug and fix it against `request` instead, thanks!

**Comment by othiym23** [comment]
Closing as resolved and / or redirected to `request`.
