### ISSUE TITLE
Cannot read property of undefined running NPM install

### ISSUE THREAD

**Issue by jasperf** [npm/npm#8016]
Just updated npm
```
npm --version
2.8.3
````
and ran npm install inside Sage theme to install all needed files and ran into this error:
```
tail -n 30 /Users/jasper/webdesign/sage/site/web/app/themes/wprmote/npm-debug.log
82145 silly prepareForInstallMany adding get-stdin@^4.0.1 from indent-string dependencies
82146 silly prepareForInstallMany adding repeating@^1.1.0 from indent-string dependencies
82147 verbose readDependencies loading dependencies from /Users/jasper/webdesign/sage/site/web/app/themes/wprmote/node_modules/imagemin-pngcrush/node_modules/pngcrush-bin/node_modules/bin-wrapper/node_modules/bin-check/node_modules/executable/node_modules/meow/node_modules/indent-string/package.json
82148 silly install resolved []
82149 verbose about to build /Users/jasper/webdesign/sage/site/web/app/themes/wprmote/node_modules/imagemin-pngcrush/node_modules/pngcrush-bin/node_modules/bin-build/node_modules/download/node_modules/download-status/node_modules/chalk/node_modules/supports-color
82150 info build /Users/jasper/webdesign/sage/site/web/app/themes/wprmote/node_modules/imagemin-pngcrush/node_modules/pngcrush-bin/node_modules/bin-build/node_modules/download/node_modules/download-status/node_modules/chalk/node_modules/supports-color
82151 verbose readDependencies loading dependencies from /Users/jasper/webdesign/sage/site/web/app/themes/wprmote/node_modules/gulp-uglify/node_modules/through2/node_modules/readable-stream/node_modules/string_decoder/package.json
82152 silly prepareForInstallMany adding ansi-regex@^0.2.0 from has-ansi dependencies
82153 verbose readDependencies loading dependencies from /Users/jasper/webdesign/sage/site/web/app/themes/wprmote/node_modules/imagemin-pngcrush/node_modules/pngcrush-bin/node_modules/bin-build/node_modules/download/node_modules/download-status/node_modules/chalk/node_modules/has-ansi/package.json
82154 verbose type non_object_property_load
82155 verbose stack TypeError: Cannot read property 'dependencies' of undefined
82155 verbose stack     at prepareForInstallMany (/usr/local/lib/node_modules/npm/lib/install.js:1165:37)
82155 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:1096:20
82155 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:324:20
82155 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:111:20)
82155 verbose stack     at Glob.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:141:20)
82155 verbose stack     at Glob.f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:17:25)
82155 verbose stack     at Glob.emit (events.js:95:17)
82155 verbose stack     at Glob._readdirError (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:568:36)
82155 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/glob/glob.js:521:12
82155 verbose stack     at Object.oncomplete (fs.js:107:15)
82156 verbose cwd /Users/jasper/webdesign/sage/site/web/app/themes/wprmote
82157 error Darwin 14.3.0
82158 error argv "node" "/usr/local/bin/npm" "install"
82159 error node v0.10.33
82160 error npm  v2.8.3
82161 error Cannot read property 'dependencies' of undefined
82162 error If you need help, you may report this error at:
82162 error     <https://github.com/npm/npm/issues>
82163 verbose exit [ 1, true ]
````
Opened a ticket here https://discourse.roots.io/t/cannot-read-property-of-undefined-running-npm-install/3560 too, but as log suggested to report this bug I decided to do so too. Also I ran `npm cache clear && rm -rf node_modules && npm install` but that did not make the error go away.

PS See full log file here https://dl.dropboxusercontent.com/u/10342876/npm-debug.log

**Comment by The-Indigo-Plateau** [comment]
So are you saying that you can't do npm install until this is fixed? Darn. May have been my problem all along

**Comment by jasperf** [comment]
Seems my node version was the issue:

```
node -v
v0.10.33
jaspersmbp:wprmote jasper$ which node
/usr/local/bin/node
jaspersmbp:wprmote jasper$ sudo npm cache clean -f
Password:
npm WARN using --force I sure hope you know what you are doing.
jaspersmbp:wprmote jasper$ sudo npm install -g n
/usr/local/bin/n -> /usr/local/lib/node_modules/n/bin/n
n@1.3.0 /usr/local/lib/node_modules/n
jaspersmbp:wprmote jasper$ sudo n stable

     install : node-v0.12.2
       mkdir : /usr/local/n/versions/node/0.12.2
       fetch : https://nodejs.org/dist/v0.12.2/node-v0.12.2-darwin-x64.tar.gz
   installed : v0.12.2
```
and then another `npm cache clear && rm -rf node_modules && npm install` and I was able to run `npm install`

**Comment by mohsen1** [comment]
I can confirm this too. Node 10 and npm@2 doesn't play well together in OS X. Update to Node .12 or iojs

**Comment by joshperry** [comment]
If you're getting a flood of these errors suddenly, take a look at #7947

**Comment by latel** [comment]
same failure when  `yo webapp`, I upgrade node to solve this.

**Comment by AFZidan** [comment]
I have same issue with running `npm i` or any npm commands

> npm i
> npm ERR! Cannot read property '0' of undefined

node v8.0.0
npm v5.3.0
Linux Ubuntu 17.04 
I removed node_modules then reinstalled it `npm install`
my log file 

[2017-07-19T00_19_54_981Z-debug.txt](https://github.com/npm/npm/files/1157724/2017-07-19T00_19_54_981Z-debug.txt)

**Comment by justerest** [comment]
I have this problem too
node 8
npm 5.3
Linux Debian 9

**Comment by chris-hut** [comment]
I had was running into the same issue, but downgrading my npm seemed to fix the issue:
https://github.com/quaertym/ember-cli-dependency-checker/issues/76

**Comment by SunilRumbaLama** [comment]
apparently, the error occurs with npm@5.3.0. Try [npm install -g npm@5.2.0](url) and run npm install again.

**Comment by daton89** [comment]
I have this problem too
node 8.3.0 
npm 5.3.0
osx 10.11

**Comment by SunilRumbaLama** [comment]
@daton89 did you try downgrading your npm version??. Downgrading it to 5.2.0 worked for me.

**Comment by daton89** [comment]
@SunilRumbaLama yes, downgrading it to 5.2.0 worked for me too

**Comment by jaypatel04** [comment]
Same issue here with

None of the commands now working.

cli packages: (/Users/jay/.nvm/versions/node/v9.2.0/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 1.3.7
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.2.0

System:

    Android SDK Tools : 26.0.2
    ios-deploy        : 1.9.2 
    Node              : v9.2.0
    npm               : 5.5.1 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.1 Build version 9B55 

Environment Variables:

    ANDROID_HOME : /Users/jay/AndroidSDK

Misc:

    backend : pro

[2017-11-23T04_22_24_173Z-debug.log](https://github.com/npm/npm/files/1498009/2017-11-23T04_22_24_173Z-debug.log)
