### ISSUE TITLE
Fatal Error: Call_And_Retry_Last Allocation failed - process out of memory

### ISSUE THREAD

**Issue by yohored** [npm/npm#8019]
Environment:
Windows 7, 8g ram
npm -v : 2.7.4
Node js : 0.12.2 (x64)

When I try to "npm install" any package, it's just loading for about hours,
and Fatal Error: Call_And_Retry_Last Allocation failed - process out of memory
Tried reinstall, and also removed anything in Roaming folder

**Comment by othiym23** [comment]
That's an error coming out of Node, and is an unusual one for you to be getting given the amount of RAM on your system. Does that persist if you [upgrade npm](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows)? Does it persist if you uninstall Node.js and install [iojs](https://iojs.org/en/index.html)? Or downgrading to Node 0.10 and updating to the latest npm?

(I don't have a Windows 7 system handy to test this myself, but npm installs work fine for me on Windows 8.1 + Node.js 0.12.2 + `npm@2.8.4`).

**Comment by yohored** [comment]
I have just tried iojs way, but still same result.
Would you please tell me where can I download legacy version? So that I could try upgrade to the latest.

Thanks.

**Comment by yohored** [comment]
I found it. Node.js 0.10.28, work perfectly for me.
Thanks for the help :)

**Comment by LiuSuY** [comment]
内存溢出是版本问题？？？
