### ISSUE TITLE
Error on install --save react-native

### ISSUE THREAD

**Issue by thdave** [npm/npm#8023]
On trying to 
npm install --save react-native, I get the error 
Error: No compatible version found: chalk@'^1.0.0'
Install fails
Can anyone tell me how to get the install to succeed

Thanks for your time

**Comment by smikes** [comment]
It sounds like you have a rather old version of `npm`.  Can you try updating your `npm` first?

If your `npm` is older than 1.4, then do this first:

```
npm install -g npm@1.4
```

From 1.4 you can update to latest:

```
npm install -g npm@latest
```

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
