### ISSUE TITLE
Install error with npm install

### ISSUE THREAD

**Issue by RZhou94** [npm/npm#8024]
I am using Windows 8
and i just installed this node.js

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "D:\\AppliesVSCT\\DevHome\\App\\nodejs\\\\node.exe" "D:\\AppliesVSCT\\DevHome\\App\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd D:\AppliesVSCT\DevHome\Project\EclipseWS\jenkins-build-monitor-plugin
npm ERR! node -v v0.10.9
npm ERR! npm -v 1.2.24
npm ERR! path D:\AppliesVSCT\DevHome\Project\EclipseWS\jenkins-build-monitor-plugin\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\node_modules\request\CONTRIBUTING.md
npm ERR! fstream_path D:\AppliesVSCT\DevHome\Project\EclipseWS\jenkins-build-monitor-plugin\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\node_modules\request\CONTRIBUTING.md
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack D:\AppliesVSCT\DevHome\App\nodejs\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http 304 https://registry.npmjs.org/is-glob
npm ERR! error rolling back Error: ENOTEMPTY, rmdir 'D:\AppliesVSCT\DevHome\Project\EclipseWS\jenkins-build-monitor-plugin\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\node_modules\adm-zip\methods'
npm ERR! error rolling back  phantomjs@1.9.16 { [Error: ENOTEMPTY, rmdir 'D:\AppliesVSCT\DevHome\Project\EclipseWS\jenkins-build-monitor-plugin\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\node_modules\adm-zip\methods']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: 'D:\\AppliesVSCT\\DevHome\\Project\\EclipseWS\\jenkins-build-monitor-plugin\\node_modules\\karma-phantomjs-launcher\\node_modules\\phantomjs\\node_modules\\adm-zip\\methods' }
npm ERR! Error: ENOENT, lstat 'D:\AppliesVSCT\DevHome\Project\EclipseWS\jenkins-build-monitor-plugin\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\node_modules\npmconf\test\semver-tag.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

**Comment by smikes** [comment]
This is quite an old version of node.js : `npm ERR! node -v v0.10.9`

Can you install the latest 0.10 version, 0.10.38 -- https://nodejs.org/dist/v0.10.38/node-v0.10.38-x86.msi

**Comment by RZhou94** [comment]
Thank you, 

i think i fixed this problem :D

And I am trying to resolve my other bug, but this is maven error now.

Thank you again
