### ISSUE TITLE
nested git dependencies wrong versions

### ISSUE THREAD

**Issue by Matt-Esch** [npm/npm#8029]
Illustration:
----------------------
A depends on B (a git module, git+ssh://git@github.com:user/B#v1.0.0)
A depends on C (a git module, git+ssh://git@github.com:user/C#v1.0.0)

B depends on D git+ssh://git@github.com:user/**D#v1.0.0**
C depends on D git+ssh://git@github.com:user/**D#v2.0.0**

B and C both end up with **D#v1.0.0** installed (two copies, one in A/node_modules/B/node_modules/D and one in A/node_modules/C/node_modules/D)

Versions affected
----------------------
reproduced in npm 2.7.X and 2.8.X (node0.10)

Cause
----------------------
It looks like the install caching for git modules is not respecting the tag in all cases.

Similar issues
----------------------
https://github.com/npm/npm/issues/7994

**Comment by isqua** [comment]
+1

**Comment by jonathanong** [comment]
i'm getting wrong git dependencies in general, specifically when an older version is cached.

**Comment by othiym23** [comment]
Closing this as a duplicate of #7202, but I want to get this fixed soon.
