### ISSUE TITLE
`npm run` should have autocomplete prompt for available scripts

### ISSUE THREAD

**Issue by ljharb** [npm/npm#8030]
Similarly to how `npm run` now lists available scripts, it'd be awesome if `npm run [tab]` would show the available command names.

**Comment by luissquall** [comment]
Yep, totally agree 👍.

**Comment by akoenig** [comment]
Yap, that would be awesome.

Meanwhile, if you driving the `zsh`, you could use my autocompletion plugin: https://github.com/akoenig/npm-run.plugin.zsh

**Comment by tnrich** [comment]
+1

**Comment by noscripter** [comment]
This seems to be fixed and should be close, just follow these two steps to enable auto completion in npm:
1.  `echo $SHELL`, find out which shell are you using, for example, `zsh` or `bash`.
2.  `npm completion >> ~/.zshrc` in zsh shell or `npm completion >> ~/.bashrc` in bash shell.

ref:https://docs.npmjs.com/cli/completion

**Comment by ljharb** [comment]
@noscripter that's for `npm` completion. This is talking about `npm run-script`, which would involve listing all of the "scripts" keys in `package.json`

**Comment by noscripter** [comment]
@ljharb  they are the same, please run `npm help run` to see the manual.

**Comment by ljharb** [comment]
@noscripter they are not. if you execute `npm run` you will get a list of the available scripts. that list does NOT currently tab-complete, which is the purpose of this issue. Have you tried `npm run [tab]` anywhere? it will just list the files in the directory, which isn't useful.

**Comment by ljharb** [comment]
Thanks - in which version of npm was this added?

**Comment by ljharb** [comment]
In my basic testing this appears to work in npm 2 something, whatever comes with node 0.12 and later. @othiym23, I'm going to close this, since it seems to be working.

**Comment by tnrich** [comment]
yay! thanks for the info @noscripter :)

**Comment by Delapouite** [comment]
I confirm it's also working on my terminal. @ljharb could you close this issue? Thanks.

**Comment by liesislukas** [comment]
For OS X you might need this: `npm completion >> ~/.bash_profile`

**Comment by lwr** [comment]
for the manual:

```
NPM-COMPLETION(1)

NAME
       npm-completion - Tab Completion for npm

SYNOPSIS
         source <(npm completion)
```

but I don't know why it didn't work in OS X:
```bash
source <(npm completion)
```

however this command works instead:


```bash
eval "`npm completion`"
```

**Comment by DustinJSilk** [comment]
Dont forget to close and open a new shell window for it to work after adding to bash.

**Comment by ghost** [comment]
For those who still hit this page: "source ~/.bashrc" or "source ~/.bash_profile" will reload the appropriate file, and you won't have to kick your terminal to load up the new completion radness

**Comment by leoperfect** [comment]
is this solved for windows system ?
