### ISSUE TITLE
Error installing cordova

### ISSUE THREAD

**Issue by jonnypc123** [npm/npm#8033]
Installing node.js was successful and then tried to install cordova as per the documentation instructions.

npm install -g cordova.

![cordova_install_error](https://cloud.githubusercontent.com/assets/12069572/7276950/25f3daa2-e8db-11e4-908c-8c8092f718af.jpg)

The npm-debug.log file was nowhere to be found.   

Installation was being done on Windows 7 Professional 64-bit.

**Comment by KenanY** [comment]
@jonnypc123 Could you try?:

``` sh
$ npm cache clean cordova-app-hello-world
```

**Comment by jonnypc123** [comment]
That did the trick.
