### ISSUE TITLE
error in npm init Windows 7

### ISSUE THREAD

**Issue by iperel** [npm/npm#8035]
Hi, I am encountering a failure during npm init on Windows 7
npm-debug.log from npm init failure

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'init' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose config Skipping project config: C:\Users\ixp8299/.npmrc. (matches userconfig)
6 verbose stack Error: read EINVAL
6 verbose stack     at exports._errnoException (util.js:746:11)
6 verbose stack     at TTY.onread (net.js:559:26)
7 verbose cwd C:\Users\ixp8299\test
8 error Windows_NT 6.1.7601
9 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "init"
10 error node v0.12.2
11 error npm  v2.7.4
12 error code EINVAL
13 error errno EINVAL
14 error syscall read
15 error read EINVAL
16 error If you need help, you may report this error at:
16 error     <https://github.com/npm/npm/issues>
17 verbose exit [ 1, true ]
```

**Comment by Volox** [comment]
+1

**Comment by iperel** [comment]
Hi, could you please explain the meaning of +1?

Thank you,
Igor

**Comment by Subha** [comment]
Is this issue been resolved, if so can you please tell me how it has been resolved. 
Created a new directory myproject, and from there:

I am running: npm init 
This is my node version : node@v0.10.38. I need to use this to support node oracledb

This is my node-debug.log file

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'init' ]
2 info using npm@1.4.28
3 info using node@v0.10.38
4 verbose node symlink C:\Program Files (x86)\nodejs\\node.exe
5 error Error: read EINVAL
5 error     at errnoException (net.js:905:11)
5 error     at TTY.onread (net.js:559:19)
6 error If you need help, you may report this *entire* log,
6 error including the npm and node versions, at:
6 error     <http://github.com/npm/npm/issues>
7 error System Windows_NT 6.1.7601
8 error command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "init"
9 error cwd C:\Users\rajagopa\Documents\Matrix\Myproj
10 error node -v v0.10.38
11 error npm -v 1.4.28
12 error syscall read
13 error code EINVAL
14 error errno EINVAL
15 verbose exit [ 1, true ]

Thank you

**Comment by Mac-lp3** [comment]
Hi,

I've been recieving the same error as well - just when I run `npm init` (install has worked fine so far).

Has anyone had any luck resolving it?

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'init' ]
2 info using npm@3.3.12
3 info using node@v5.5.0
4 verbose stack Error: read EINVAL
4 verbose stack     at exports._errnoException (util.js:856:11)
4 verbose stack     at TTY.onread (net.js:544:26)
5 verbose cwd C:\Users\c42056\Documents\dev\servers\node\expressHello
6 error Windows_NT 6.1.7601
7 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "init"
8 error node v5.5.0
9 error npm  v3.3.12
10 error code EINVAL
11 error errno EINVAL
12 error syscall read
13 error read EINVAL
14 error If you need help, you may report this error at:
14 error     <https://github.com/npm/npm/issues>
15 verbose exit [ 1, true ]

**Comment by Prabhkaran** [comment]
Hi, 

Is this issue been resolved? 
I am also facing the same issue on running `npm init`

can anyone please help me with this?

npm-debug.log:

```
 0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'init' ]
2 info using npm@3.8.6
3 info using node@v4.2.1
4 verbose stack Error: read EINVAL
4 verbose stack     at exports._errnoException (util.js:874:11)
4 verbose stack     at TTY.onread (net.js:544:26)
5 verbose cwd D:\projects\react
6 error Windows_NT 6.1.7601
7 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "init"
8 error node v4.2.1
9 error npm  v3.8.6
10 error code EINVAL
11 error errno EINVAL
12 error syscall read
13 error read EINVAL
14 error If you need help, you may report this error at:
14 error     <https://github.com/npm/npm/issues>
15 verbose exit [ 1, true ]
```

**Comment by Prabhkaran** [comment]
Hi, 

Resolved, try this command: `npm init -y`

It will create `package.json` with default config. You can go ahead and make changes in file.
