### ISSUE TITLE
How do you install `devDependencies` without installing each dependency's `devDependencies`?

### ISSUE THREAD

**Issue by christianbundy** [npm/npm#8039]
This is the painful workaround I'm using now:

``` shell
npm install $(node -e "var o = require('./package.json').devDependencies; for (var p in o) { console.log(p + '@' + o[p]); }")
```

There _has_ to be a better way.

**Comment by othiym23** [comment]
Why does `npm install` run from the directory containing the `package.json` with your `devDependencies` not work for you? That will install all the current package's `devDependencies` without installing `devDependencies` for any of the children, which sounds like exactly what you want.

**Comment by dettier** [comment]
For some reason `npm install` does not install `devDependencies` while running under official docker `nodejs` image container. This does not happen under Windows or Ubuntu, so this is probably Debian specific bug.

**Comment by tpisto** [comment]
Can confirm this bug on Debian Wheezy. Using nvm with iojs-v1.8.1. Npm version is npm 2.8.3. And thanks for @christianbundy  for the workaround - was a lifesaver =)

**Comment by christianbundy** [comment]
@tpisto 
![giphy](https://cloud.githubusercontent.com/assets/537700/7821757/dcfb3134-03a5-11e5-9d45-55ce2da9b6b9.gif)

**Comment by fresheneesz** [comment]
On npm v3.3.12 I'm actually seeing devDependencies of dependency modules being installed when you just run `npm install` in a folder containing a `package.json` . Maybe there's a bug where devDependencies are always installed in normal cases?

**Comment by gelobelo02** [comment]
This is still happening @tpisto
