### ISSUE TITLE
trying to set up ng-store for the first time and can't

### ISSUE THREAD

**Issue by mrMustachos** [npm/npm#8040]
going through the process of setting ng-store from the wiki and after I put my personal access tokens and computer password in and the process was starting it gave me a few errors and then stopped and pointed me here. Ive had issues in the past with getting data captures built as well.

/Users/billdomanick/.grunt-init/ng-storefront/npm-debug.log

**Comment by KenanY** [comment]
@mrMustachos It is not clear to me whether or not this is an issue with `npm`. If you have a `npm-debug.log`, could you upload it as a [gist](https://gist.github.com/) and post the link here?

**Comment by mrMustachos** [comment]
here's the log

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install' ]
2 info using npm@2.5.1
3 info using node@v0.12.1
4 verbose install where, deps [ '/Users/billdomanick/.grunt-init/ng-storefront',
4 verbose install   [ 'request' ] ]
5 verbose install where, peers [
'/Users/billdomanick/.grunt-init/ng-storefront', [] ]
6 info preinstall ng-storefront-template@1.1.0
7 silly cache add args [ 'request@^2.44.0', null ]
8 verbose cache add spec request@^2.44.0
9 silly cache add parsed spec { raw: 'request@^2.44.0',
9 silly cache add   scope: null,
9 silly cache add   name: 'request',
9 silly cache add   rawSpec: '^2.44.0',
9 silly cache add   spec: '>=2.44.0 <3.0.0',
9 silly cache add   type: 'range' }
10 verbose addNamed request@>=2.44.0 <3.0.0
11 silly addNamed semver.valid null
12 silly addNamed semver.validRange >=2.44.0 <3.0.0
13 silly addNameRange { name: 'request', range: '>=2.44.0 <3.0.0',
hasData: false }
14 silly mapToRegistry name request
15 silly mapToRegistry using default registry
16 silly mapToRegistry registry https://registry.npmjs.org/
17 silly mapToRegistry uri https://registry.npmjs.org/request
18 verbose addNameRange registry:https://registry.npmjs.org/request
not in flight; fetching
19 verbose get https://registry.npmjs.org/request not expired, no request
20 silly addNameRange number 2 { name: 'request', range: '>=2.44.0
<3.0.0', hasData: true }
21 silly addNameRange versions [ 'request',
21 silly addNameRange   [ '0.10.0',
21 silly addNameRange     '0.8.3',
21 silly addNameRange     '0.9.0',
21 silly addNameRange     '0.9.1',
21 silly addNameRange     '0.9.5',
21 silly addNameRange     '1.0.0',
21 silly addNameRange     '1.1.0',
21 silly addNameRange     '1.1.1',
21 silly addNameRange     '1.2.0',
21 silly addNameRange     '1.9.0',
21 silly addNameRange     '1.9.1',
21 silly addNameRange     '1.9.2',
21 silly addNameRange     '1.9.3',
21 silly addNameRange     '1.9.5',
21 silly addNameRange     '1.9.7',
21 silly addNameRange     '1.9.8',
21 silly addNameRange     '1.9.9',
21 silly addNameRange     '2.0.0',
21 silly addNameRange     '2.0.1',
21 silly addNameRange     '2.0.2',
21 silly addNameRange     '2.0.3',
21 silly addNameRange     '2.0.4',
21 silly addNameRange     '2.0.5',
21 silly addNameRange     '2.1.0',
21 silly addNameRange     '2.1.1',
21 silly addNameRange     '2.2.0',
21 silly addNameRange     '2.2.5',
21 silly addNameRange     '2.2.6',
21 silly addNameRange     '2.2.9',
21 silly addNameRange     '2.9.0',
21 silly addNameRange     '2.9.1',
21 silly addNameRange     '2.9.2',
21 silly addNameRange     '2.9.3',
21 silly addNameRange     '2.9.100',
21 silly addNameRange     '2.9.150',
21 silly addNameRange     '2.9.151',
21 silly addNameRange     '2.9.152',
21 silly addNameRange     '2.9.153',
21 silly addNameRange     '2.9.200',
21 silly addNameRange     '2.9.201',
21 silly addNameRange     '2.9.202',
21 silly addNameRange     '2.9.203',
21 silly addNameRange     '2.10.0',
21 silly addNameRange     '2.11.0',
21 silly addNameRange     '2.11.1',
21 silly addNameRange     '2.11.2',
21 silly addNameRange     '2.11.3',
21 silly addNameRange     '2.11.4',
21 silly addNameRange     '2.12.0',
21 silly addNameRange     '2.14.0',
21 silly addNameRange     '2.16.0',
21 silly addNameRange     '2.16.2',
21 silly addNameRange     '2.16.4',
21 silly addNameRange     '2.16.6',
21 silly addNameRange     '2.18.0',
21 silly addNameRange     '2.19.0',
21 silly addNameRange     '2.20.0',
21 silly addNameRange     '2.21.0',
21 silly addNameRange     '2.22.0',
21 silly addNameRange     '2.23.0',
21 silly addNameRange     '2.24.0',
21 silly addNameRange     '2.25.0',
21 silly addNameRange     '2.26.0',
21 silly addNameRange     '2.27.0',
21 silly addNameRange     '2.28.0',
21 silly addNameRange     '2.29.0',
21 silly addNameRange     '2.30.0',
21 silly addNameRange     '2.31.0',
21 silly addNameRange     '2.32.0',
21 silly addNameRange     '2.33.0',
21 silly addNameRange     '2.34.0',
21 silly addNameRange     '2.35.0',
21 silly addNameRange     '2.36.0',
21 silly addNameRange     '2.37.0',
21 silly addNameRange     '2.38.0',
21 silly addNameRange     '2.39.0',
21 silly addNameRange     '2.40.0',
21 silly addNameRange     '2.41.0',
21 silly addNameRange     '2.42.0',
21 silly addNameRange     '2.43.0',
21 silly addNameRange     '2.44.0',
21 silly addNameRange     '2.45.0',
21 silly addNameRange     '2.46.0',
21 silly addNameRange     '2.47.0',
21 silly addNameRange     '2.48.0',
21 silly addNameRange     '2.49.0',
21 silly addNameRange     '2.50.0',
21 silly addNameRange     '2.51.0',
21 silly addNameRange     '2.52.0',
21 silly addNameRange     '2.53.0',
21 silly addNameRange     '2.54.0',
21 silly addNameRange     '2.55.0' ] ]
22 verbose addNamed request@2.55.0
23 silly addNamed semver.valid 2.55.0
24 silly addNamed semver.validRange 2.55.0
25 silly cache afterAdd request@2.55.0
26 verbose afterAdd
/Users/billdomanick/.npm/request/2.55.0/package/package.json not in
flight; writing
27 verbose afterAdd
/Users/billdomanick/.npm/request/2.55.0/package/package.json written
28 silly install resolved [ { name: 'request',
28 silly install resolved     description: 'Simplified HTTP request client.',
28 silly install resolved     tags: [ 'http', 'simple', 'util', 'utility' ],
28 silly install resolved     version: '2.55.0',
28 silly install resolved     author: { name: 'Mikeal Rogers', email:
'mikeal.rogers@gmail.com' },
28 silly install resolved     repository: { type: 'git', url:
'https://github.com/request/request.git' },
28 silly install resolved     bugs: { url:
'http://github.com/request/request/issues' },
28 silly install resolved     license: 'Apache-2.0',
28 silly install resolved     engines: { node: '>=0.8.0' },
28 silly install resolved     main: 'index.js',
28 silly install resolved     dependencies:
28 silly install resolved      { bl: '~0.9.0',
28 silly install resolved        caseless: '~0.9.0',
28 silly install resolved        'forever-agent': '~0.6.0',
28 silly install resolved        'form-data': '~0.2.0',
28 silly install resolved        'json-stringify-safe': '~5.0.0',
28 silly install resolved        'mime-types': '~2.0.1',
28 silly install resolved        'node-uuid': '~1.4.0',
28 silly install resolved        qs: '~2.4.0',
28 silly install resolved        'tunnel-agent': '~0.4.0',
28 silly install resolved        'tough-cookie': '>=0.12.0',
28 silly install resolved        'http-signature': '~0.10.0',
28 silly install resolved        'oauth-sign': '~0.6.0',
28 silly install resolved        hawk: '~2.3.0',
28 silly install resolved        'aws-sign2': '~0.5.0',
28 silly install resolved        stringstream: '~0.0.4',
28 silly install resolved        'combined-stream': '~0.0.5',
28 silly install resolved        isstream: '~0.1.1',
28 silly install resolved        'har-validator': '^1.4.0' },
28 silly install resolved     scripts:
28 silly install resolved      { test: 'npm run lint && node
node_modules/.bin/taper tests/test-*.js && npm run test-browser',
28 silly install resolved        'test-browser': 'node tests/browser/start.js',
28 silly install resolved        lint: 'node node_modules/.bin/eslint
lib/ *.js tests/ && echo Lint passed.' },
28 silly install resolved     devDependencies:
28 silly install resolved      { browserify: '~5.9.1',
28 silly install resolved        'browserify-istanbul': '~0.1.3',
28 silly install resolved        coveralls: '~2.11.2',
28 silly install resolved        eslint: '0.17.1',
28 silly install resolved        'function-bind': '~1.0.0',
28 silly install resolved        istanbul: '~0.3.2',
28 silly install resolved        karma: '~0.12.21',
28 silly install resolved        'karma-browserify': '~3.0.1',
28 silly install resolved        'karma-cli': '0.0.4',
28 silly install resolved        'karma-coverage': '0.2.6',
28 silly install resolved        'karma-phantomjs-launcher': '~0.1.4',
28 silly install resolved        'karma-tap': '~1.0.1',
28 silly install resolved        rimraf: '~2.2.8',
28 silly install resolved        'server-destroy': '~1.0.0',
28 silly install resolved        tape: '~3.0.0',
28 silly install resolved        taper: '~0.4.0',
28 silly install resolved        bluebird: '~2.9.21' },
28 silly install resolved     gitHead:
'b6000376387db12d0c2d7ed9ee87b0ba123e36dc',
28 silly install resolved     homepage: 'https://github.com/request/request',
28 silly install resolved     _id: 'request@2.55.0',
28 silly install resolved     _shasum:
'd75c1cdf679d76bb100f9bffe1fe551b5c24e93d',
28 silly install resolved     _from: 'request@>=2.44.0 <3.0.0',
28 silly install resolved     _npmVersion: '1.4.28',
28 silly install resolved     _npmUser: { name: 'simov', email:
'simeonvelichkov@gmail.com' },
28 silly install resolved     maintainers: [ [Object], [Object],
[Object], [Object] ],
28 silly install resolved     dist:
28 silly install resolved      { shasum:
'd75c1cdf679d76bb100f9bffe1fe551b5c24e93d',
28 silly install resolved        tarball:
'http://registry.npmjs.org/request/-/request-2.55.0.tgz' },
28 silly install resolved     directories: {},
28 silly install resolved     _resolved:
'https://registry.npmjs.org/request/-/request-2.55.0.tgz',
28 silly install resolved     readme: 'ERROR: No README data found!' } ]
29 info install request@2.55.0 into
/Users/billdomanick/.grunt-init/ng-storefront
30 info installOne request@2.55.0
31 verbose installOne of request to
/Users/billdomanick/.grunt-init/ng-storefront not in flight;
installing
32 warn locking Error: EACCES, open
'/Users/billdomanick/.npm/_locks/request-01c80240f9357592.lock'
32 warn locking     at Error (native)
32 warn locking
/Users/billdomanick/.npm/_locks/request-01c80240f9357592.lock failed {
[Error: EACCES, open
'/Users/billdomanick/.npm/_locks/request-01c80240f9357592.lock']
32 warn locking   errno: -13,
32 warn locking   code: 'EACCES',
32 warn locking   path:
'/Users/billdomanick/.npm/_locks/request-01c80240f9357592.lock' }
33 verbose stack Error: Attempt to unlock
/Users/billdomanick/.grunt-init/ng-storefront/node_modules/request,
which hasn't been locked
33 verbose stack     at unlock
(/usr/local/lib/node_modules/npm/lib/utils/locker.js:66:11)
33 verbose stack     at cb
(/usr/local/lib/node_modules/npm/lib/install.js:929:5)
33 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:933:20
33 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/locker.js:40:9
33 verbose stack     at cb
(/usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
33 verbose stack     at
/usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
33 verbose stack     at FSReqWrap.oncomplete (fs.js:99:15)
34 verbose cwd /Users/billdomanick/.grunt-init/ng-storefront
35 error Darwin 14.3.0
36 error argv "node" "/usr/local/bin/npm" "install"
37 error node v0.12.1
38 error npm  v2.5.1
39 error Attempt to unlock
/Users/billdomanick/.grunt-init/ng-storefront/node_modules/request,
which hasn't been locked
40 error If you need help, you may report this error at:
40 error     <http://github.com/npm/npm/issues>
41 verbose exit [ 1, true ]





  – Bill


––

Bill Domanick  |  Web Designer
bill.domanick@crowdsurge.com

Office:   +1 (718) 875-1133Mobile:   +1 (203) 913-3226
New York • Los Angeles • Nashville • London • São Paulo

Contents of this email subject to our confidentiality notice
<http://www.crowdsurge.com/confidentiality/>

**Comment by KenanY** [comment]
@mrMustachos It looks like you do not have the necessary permissions to write to the `npm` cache directory. Could you try the following?:

``` sh
$ sudo chown -R $(whoami) "$HOME/.npm"
```

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
