### ISSUE TITLE
npm ERR! Windows_NT 6.1.7601 - Unable to install Protractor on Windows 7

### ISSUE THREAD

**Issue by nattimorgan** [npm/npm#8048]
When I try to run npm -g install protractor, I get the following error.  I am unable to install protractor in my Windows 7 environment.  Please assist me if possible. Thanks.
```
c:\Program Files\nodejs>npm -g install protractor

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Program Files\\nodejs\\\\node.exe" "c:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "-g" "install" "protractor"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code DEPTH_ZERO_SELF_SIGNED_CERT

npm ERR! self signed certificate
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Program Files\nodejs\npm-debug.log

c:\Program Files\nodejs>npm -g install protractor
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Program Files\\nodejs\\\\node.exe" "c:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "-g" "install" "protractor"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code DEPTH_ZERO_SELF_SIGNED_CERT

npm ERR! self signed certificate
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Program Files\nodejs\npm-debug.log

c:\Program Files\nodejs>
```

**Comment by othiym23** [comment]
Do you have a [proxy](https://docs.npmjs.com/misc/config#https-proxy) between you and the internet? The error you're getting is an SSL error that indicates that something is interfering with the npm CLI's ability to talk to its registry securely.

**Comment by nattimorgan** [comment]
@othiym23 Thanks for your response.  Yes, I do have a proxy and that is partly to blame for what is causing the issue.  That and the antivirus firewall.  I am getting my IT department to help with resolving it. Thanks for your help.

**Comment by imabdul** [comment]
Has it been solved, if yes! how and what IT department did in order to solve it?

**Comment by cichy380** [comment]
I had similar errors
<pre>npm ERR! Windows_NT 6.1.7601
...</pre>
and I had to turn off my Firewall and AntiVir.

**Comment by mmathea1** [comment]
i run cmd as administrator and it worked

**Comment by daviatorstorm** [comment]
Guys write in CMD "echo %http_proxy%". If its return you some link you should write in CMD "set http_proxy=" (it will set http_proxy variable value to nothing. It works for me.). Otherwise it should returns you "%http_proxy%" and its will means that variable http_proxy does not exists. Then you have to find another way )

**Comment by sindo83** [comment]
Sorry, i have following problem, When i try to install serialport module node return me th error:

c:\Program Files\nodejs>npm -g install serialport.js
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "-g" "install" "serialport.js"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/serialp
ort.js
npm ERR! 404
npm ERR! 404 'serialport.js' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Program Files\nodejs\npm-debug.log

I do not get it working, can you help me please

**Comment by KenanY** [comment]
@sindo83 Your error looks unrelated to that of the user who created this thread. In the future please open a new ticket next time instead of commenting on issues that have been closed for months.

In the case of your issue, are you sure you don't want to install [`serialport`](https://www.npmjs.com/package/serialport) instead of `serialport.js`? As the error message states, there does not exist a module in the registry called `serialport.js`, so I believe `npm` is doing the right thing here in returning that error to you.

**Comment by sindo83** [comment]
Sorry, is not the same module but the error is similar. I open a new ticket

**Comment by daviatorstorm** [comment]
I discovered a problem solution )
If you go to windows variables menu find and delete variable name "http_proxy". You will have happiness.
In that menual were written that you can add proxy link if you have it and gives you a pattern to create a variable for it. But if you are not using proxy you do not have to create that variable )
That is all folks )

**Comment by h4harish** [comment]
it's throwing an error When am running- npm install -g cordova ionic

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\harish\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "cordova" "ionic" "-g"
npm ERR! node v5.4.0
npm ERR! v3.5.3
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.4.2 install: 'node scripts/install.js'
npm ERR! Exit status -4058
npm ERR!
npm ERR! Failed at the node-sass@3.4.2 install script 'node scripts/install.js'.

npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! if you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node scripts/install.js
npm ERR! you can get information on how to open an issue for this project with:
npm ERR! npm bugs node-sass
npm ERR! or if that isn't available,you can get their info via:
npm ERR! npm owner Is node-sass
npm ERR! There is likely additional logging output above.
npm ERR! Please include the additional logging output above.
npm ERR! c:\Windows\system32\npm-debug.log

please send me correct command.how to solve this probluem

**Comment by h4harish** [comment]
after without solving first probluem,if am trying to write this command
ionic start myApp sidemenu
module.js:328
throw err;

Error: Cannot find module 'c:\Program Files\nodejs\node_modules\ionic\bin\ionic'

at Function.Module._resolveFilename <module.js:326:15>
at Function.Module._load <module.js:277:25>
at Function.Module.runMain <module.js:430:10>
at startup <node.js:141:18>
at node.js:1003:3


please solve my Error's

**Comment by h4harish** [comment]
please solve my error

**Comment by angeliaz** [comment]
I fixed it.Every time I  run cmd I need to run 'chcp 850' first, so I write in my registry like this:
![image](https://cloud.githubusercontent.com/assets/8637938/12639326/b0bbfbac-c5de-11e5-961f-5d4e78d7deb7.png)

**Comment by chifundosaonda** [comment]
l am trying to install ionic but lam failing

**Comment by DanBzl** [comment]
I'm trying to install ionic 2 too ## npm install -g cordova ionic
but it does not work either ...

**Comment by Faseem** [comment]
Im getting following error can anyone guide me please 

node_modules/rxjs/Subject.d.ts(16,22): error TS2415: Class 'Subject<T>' incorrectly extends base class 'Observable<T>'.
  Types of property 'lift' are incompatible.
    Type '<T, R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
      Type 'Observable<T>' is not assignable to type 'Observable<R>'.
        Type 'T' is not assignable to type 'R'.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.4.6
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE
npm ERR! angular-quickstart@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run lite" `
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 start script 'tsc && concurrently "npm run tsc:w" "npm run lite" '.
npm ERR! This is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && concurrently "npm run tsc:w" "npm run lite"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Studies\Angular2\New Prac\Angular-2-Final-Template\npm-debug.log
