### ISSUE TITLE
npm ERR! Error: ENOENT, open '/home/linaro/package.json'

### ISSUE THREAD

**Issue by MarconiLab** [npm/npm#8049]
```
npm ERR! System Linux 3.18.7-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "test"
npm ERR! cwd /home/linaro
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! path /home/linaro/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/linaro/npm-debug.log
npm ERR! not ok code 0
```

**Comment by KenanY** [comment]
@MarconiLab Does `/home/linaro/package.json` exist?

**Comment by MarconiLab** [comment]
You are right @KenanY, it doesn't exist! What should I do??

**Comment by KenanY** [comment]
@MarconiLab What are you _expecting_ to happen when you run [`npm test`](https://docs.npmjs.com/cli/test) with no [`package.json`](https://docs.npmjs.com/files/package.json) in your current directory? `npm` has no idea what you want it to do unless you define a [`"test"` script](https://docs.npmjs.com/misc/scripts) in your `package.json`. You can use [`npm init`](https://docs.npmjs.com/cli/init) to generate a `package.json`.

**Comment by othiym23** [comment]
Closing as resolved. @KenanY's guidance here is sound.
