### ISSUE TITLE
git dependencies are not updated when the shasum does not match

### ISSUE THREAD

**Issue by jonathanong** [npm/npm#8052]
i pin my git dependencies like:

```
"my-package": "git://github.com/jonathanong/my-package#123412341234123412341234`
```

where i include the entire shasum.

a recent issue is that when i update the shasum, the package is not reinstalled. this completely breaks in environments like heroku where node modules are cached - my modules are no longer updated.

**Comment by othiym23** [comment]
This is probably related to #8055.

**Comment by jonathanong** [comment]
any update for this? i have to disable all caching on my node modules because of this, and it's making my deploys a lot slower =/

**Comment by iarna** [comment]
Fixed w/ npm@3
