### ISSUE TITLE
Error: Not found 

### ISSUE THREAD

**Issue by nategunn** [npm/npm#8053]
Trying to learn node through a book tutorial.  I carefully went through the steps of creating a packaged module and now I am trying to register the module.  I used the npm publish command and got this error message:

npm ERR! publish Failed PUT 404
npm ERR! Error: Not found : censorify
npm ERR!     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:300:14)
npm ERR!     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:238:65)
npm ERR!     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:123:22)
npm ERR!     at Request.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:893:14)
npm ERR!     at Request.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:844:12)
npm ERR!     at IncomingMessage.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:938:16
npm ERR!     at process._tickCallback (node.js:419:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 14.1.0
npm ERR! command "node" "/usr/local/bin/npm" "publish"
npm ERR! cwd /Users/nategunn2000/Desktop/censorify
npm ERR! node -v v0.10.30
npm ERR! npm -v 1.4.21
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/nategunn2000/Desktop/censorify/npm-debug.log
npm ERR! not ok code 0

and this is the content of my debug file:

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'publish' ]
2 info using npm@1.4.21
3 info using node@v0.10.30
4 verbose publish [ '.' ]
5 verbose cache add [ '.', null ]
6 verbose cache add name=undefined spec="." args=[".",null]
7 verbose parsed url { protocol: null,
7 verbose parsed url   slashes: null,
7 verbose parsed url   auth: null,
7 verbose parsed url   host: null,
7 verbose parsed url   port: null,
7 verbose parsed url   hostname: null,
7 verbose parsed url   hash: null,
7 verbose parsed url   search: null,
7 verbose parsed url   query: null,
7 verbose parsed url   pathname: '.',
7 verbose parsed url   path: '.',
7 verbose parsed url   href: '.' }
8 silly lockFile 3a52ce78- .
9 verbose lock . /Users/nategunn2000/.npm/3a52ce78-.lock
10 verbose tar pack [ '/Users/nategunn2000/.npm/censorify/0.1.1/package.tgz', '.' ]
11 verbose tarball /Users/nategunn2000/.npm/censorify/0.1.1/package.tgz
12 verbose folder .
13 info prepublish censorify@0.1.1
14 silly lockFile 1f1177db-tar tar://.
15 verbose lock tar://. /Users/nategunn2000/.npm/1f1177db-tar.lock
16 silly lockFile e36ce831--npm-censorify-0-1-1-package-tgz tar:///Users/nategunn2000/.npm/censorify/0.1.1/package.tgz
17 verbose lock tar:///Users/nategunn2000/.npm/censorify/0.1.1/package.tgz /Users/nategunn2000/.npm/e36ce831--npm-censorify-0-1-1-package-tgz.lock
18 silly lockFile 1f1177db-tar tar://.
19 silly lockFile 1f1177db-tar tar://.
20 silly lockFile e36ce831--npm-censorify-0-1-1-package-tgz tar:///Users/nategunn2000/.npm/censorify/0.1.1/package.tgz
21 silly lockFile e36ce831--npm-censorify-0-1-1-package-tgz tar:///Users/nategunn2000/.npm/censorify/0.1.1/package.tgz
22 silly lockFile 72d16d14-2000-npm-censorify-0-1-1-package /Users/nategunn2000/.npm/censorify/0.1.1/package
23 verbose lock /Users/nategunn2000/.npm/censorify/0.1.1/package /Users/nategunn2000/.npm/72d16d14-2000-npm-censorify-0-1-1-package.lock
24 silly lockFile 72d16d14-2000-npm-censorify-0-1-1-package /Users/nategunn2000/.npm/censorify/0.1.1/package
25 silly lockFile 72d16d14-2000-npm-censorify-0-1-1-package /Users/nategunn2000/.npm/censorify/0.1.1/package
26 silly lockFile 3a52ce78- .
27 silly lockFile 3a52ce78- .
28 silly publish { author: { name: 'Nate Gunn' },
28 silly publish   name: 'censorify',
28 silly publish   version: '0.1.1',
28 silly publish   description: 'censor words out of text',
28 silly publish   main: 'censortext',
28 silly publish   repository: { type: 'git', url: 'https://github.com/nategunn/censorify' },
28 silly publish   keywords: [ 'censor', 'words' ],
28 silly publish   dependencies: {},
28 silly publish   engines: { node: '*' },
28 silly publish   readme: 'this is my first shot at a node.js app\n# censorify\n',
28 silly publish   readmeFilename: 'README.md',
28 silly publish   gitHead: '85f07349d4b1b9b209778d77097c7841987594ee',
28 silly publish   bugs: { url: 'https://github.com/nategunn/censorify/issues' },
28 silly publish   homepage: 'https://github.com/nategunn/censorify',
28 silly publish   _id: 'censorify@0.1.1',
28 silly publish   scripts: {},
28 silly publish   _shasum: 'ea51783c93156f742132e072552e6c2f05f5e760',
28 silly publish   _from: '.' }
29 verbose request where is /censorify
30 verbose request registry https://registry.npmjs.org/
31 verbose request id eefe2a6c9f12fd50
32 verbose url raw /censorify
33 verbose url resolving [ 'https://registry.npmjs.org/', './censorify' ]
34 verbose url resolved https://registry.npmjs.org/censorify
35 verbose request where is https://registry.npmjs.org/censorify
36 info trying registry request attempt 1 at 12:49:51
37 http PUT https://registry.npmjs.org/censorify
38 http 404 https://registry.npmjs.org/censorify
39 verbose headers { date: 'Thu, 23 Apr 2015 19:49:52 GMT',
39 verbose headers   server: 'Apache',
39 verbose headers   'content-type': 'application/json',
39 verbose headers   'cache-control': 'max-age=0',
39 verbose headers   'content-length': '21',
39 verbose headers   'accept-ranges': 'bytes',
39 verbose headers   via: '1.1 varnish',
39 verbose headers   'x-served-by': 'cache-sjc3131-SJC',
39 verbose headers   'x-cache': 'MISS',
39 verbose headers   'x-cache-hits': '0',
39 verbose headers   'x-timer': 'S1429818591.965184,VS0,VE995',
39 verbose headers   'keep-alive': 'timeout=10, max=50',
39 verbose headers   connection: 'Keep-Alive' }
40 error publish Failed PUT 404
41 error Error: Not found : censorify
41 error     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:300:14)
41 error     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:238:65)
41 error     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:123:22)
41 error     at Request.emit (events.js:98:17)
41 error     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:893:14)
41 error     at Request.emit (events.js:117:20)
41 error     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:844:12)
41 error     at IncomingMessage.emit (events.js:117:20)
41 error     at _stream_readable.js:938:16
41 error     at process._tickCallback (node.js:419:13)
42 error If you need help, you may report this *entire* log,
42 error including the npm and node versions, at:
42 error     <http://github.com/npm/npm/issues>
43 error System Darwin 14.1.0
44 error command "node" "/usr/local/bin/npm" "publish"
45 error cwd /Users/nategunn2000/Desktop/censorify
46 error node -v v0.10.30
47 error npm -v 1.4.21
48 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@nategunn That name is already taken: https://www.npmjs.com/package/censorify

**Comment by nategunn** [comment]
ok! Thank you so much.
