### ISSUE TITLE
npm.commands.ls() is incorrect after installation

### ISSUE THREAD

**Issue by jerylvaz** [npm/npm#8061]
Programmatically installing a package does not update the list of installed packages

$ cat  im.js 
var npm = require('npm');

var npmConfig = {
    "cache": '/tmp/npmcache',
    "prefix": '/tmp/npm',
};

npm.load(npmConfig, function (err, packmgr) {
    packmgr.commands.ls("", false, function (err, data, liteData) {
        console.log('before install: ' + JSON.stringify(liteData));
        packmgr.commands.install(['abc'], function (err) {
            packmgr.commands.ls("", false, function (err, data, liteData) {
                console.log('after install ' + JSON.stringify(liteData));
            });
        });
    });
});

$ rm -r /tmp/npm /tmp/npmcache

$ nodejs im.js 
/tmp/npm
└── (empty)

before install: {}
npm http GET https://registry.npmjs.org/abc
npm http 200 https://registry.npmjs.org/abc
npm http GET https://registry.npmjs.org/abc/-/abc-0.6.1.tgz
npm http 200 https://registry.npmjs.org/abc/-/abc-0.6.1.tgz
abc@0.6.1 ../../../../../tmp/npm/node_modules/abc
/tmp/npm
└── (empty)

after install {}

$ npm version 
{ http_parser: '1.0',
  node: '0.10.25',
  v8: '3.14.5.9',
  ares: '1.10.0',
  uv: '0.10.23',
  zlib: '1.2.8',
  modules: '11',
  openssl: '1.0.1f',
  npm: '1.3.10',
  nodejspoc: '0.0.0' }

$ nodejs --version
v0.10.25

**Comment by KenanY** [comment]
```
npm: '1.3.10',
```

Is this the same `npm` version that you are `require()`ing in `im.js`? If so, it is quite old. Does this occur in the latest stable version of `npm`?

**Comment by jerylvaz** [comment]
The bug is seen also with npm@2.8.4 but seems to be fixed with npm@2.9.0
