### ISSUE TITLE
Auto-completion error. egrep: empty (sub)expression

### ISSUE THREAD

**Issue by vnctaing** [npm/npm#8063]
When ever I try to use completion and use tab, it doesn't work and it display this 

$ npm uninstall angul...
egrep: empty (sub)expression
egrep: empty (sub)expression
egrep: empty (sub)expression

**Comment by edwellbrook** [comment]
Getting this as well.

**Comment by smikes** [comment]
Thanks for the bug report.  Can you tell us a bit more about the version of `npm` you're using and environment you're using it OSX, Linux..?) and the shell you're using (bash, zsh, ...?) so we can try to reproduce the problem?

(I'm currently on a Windows box, so `npm` completion doesn't work at all and I can't verify it.)

**Comment by vnctaing** [comment]
I am using npm 2.7.6,zsh and Yosemite 10.3.3

**Comment by othiym23** [comment]
I used to get that (I also use zsh), but then I ran `npm completion >> ~/.zshrc`, restarted the shell, and everything started working (modulo the existing bugs in npm's completion, of which there are a few). This is documented (in `npm help completion`), but I'll admit that it's not the most intutive thing in the world.

Closing as resolved.

**Comment by stabenfeldt** [comment]
@othiym23, thanks for the tips. That worked. Would have been nice if it worked out of the box. ;-P

**Comment by omgaz** [comment]
@stabenfeldt add npm to your list of plugins in your `~/.zshrc` also seems to work and doesn't pollute the file.

For example if you want to use both `git` and `npm` plugins:
```zsh
    plugins=(git npm)
```

**Comment by ldong** [comment]
@othiym23 's answer works.

**Comment by shawninder** [comment]
Neither of these solutions work for autocompleting  extra args passed to an npm script.

Both proposed solutions remove the `egrep: empty (sub)expression` errors, but the tab completions still don't work.

For example: `npm test -- -f te<TAB>` in a directory with a folder named `test` does not autocomplete. Instead, nothing happens.
By contrast, `open te<TAB>` does autocomplete correctly, resulting in `open test/`

This is on OSX Yosemite 10.10.5, using zsh and npm 2.11.3

**Comment by bradbarrow** [comment]
Can confirm @shawninder

`npm  3.3.12` 
`OSX 10.10.5`
`zsh`

Tab completion is working for npm commands and npm script names
Tab completion of directories as `--` args to scripts does not work.

**Comment by shawninder** [comment]
I upgraded to npm@3.8.0 recently. Still the autocomplete doesn't work after the `--`.

**Comment by PSalant726** [comment]
Confirmed @shawninder 

`npm 4.1.2`
`macOS 10.12.4`
`zsh 5.3.1 (x86_64-apple-darwin16.3.0)`

This thread hasn't been active in a while. Does anyone have any insight?

**Comment by MoezGholami** [comment]
+1
