### ISSUE TITLE
npm link fails to install local dependency of local dependency

### ISSUE THREAD

**Issue by dmail** [npm/npm#8064]
npm has a bug when a local dependency declare a local dependency.
With the following directory structure (simplified for the example), npm will try to install **dir/b** instead of **dir/modules/b** 

Directory structure

```
/dir
  /modules
    /a
      index.js
      package.json
    /b
      index.js
      package.json
  /app
    package.json
```

Content of **dir/modules/a/package.json**

``` json
{
    "name": "a",
    "version": "0.0.1",
    "dependencies": {
        "b": "../b",
    }
}
```

Content of **dir/app/package.json**

``` json
{
    "name": "app",
    "version": "0.0.1",
    "dependencies": {
        "a": "../modules/a",
    }
}
```

`cd dir/app & npm install`

Results in

`npm ERR! addLocal Could not install dir/b`

**Comment by KenanY** [comment]
@dmail Shouldn't those local paths be prefixed with `file:`? https://docs.npmjs.com/files/package.json#local-paths

**Comment by dmail** [comment]
My bad I made a mistake, this snippet works fine even without the `file:` prefix.

But, with the same directory structure
`cd dir/app & npm link ../modules/a`

Results in
`npm ERR! addLocal Could not install dir/b`

Changing `"../b"` in **dir/modules/a/package.json** to `"../modules/b"` and npm link install module b in **dir/modules/a/node_module/b**
