### ISSUE TITLE
How to prevent duplication of module sources using npm?

### ISSUE THREAD

**Issue by dmail** [npm/npm#8066]
The scenario 
- I have developed module-a & and module-b (depending on module-a)
- I have separate folders for module-a & module-b
- I create a project under app/ depending on module-b, so I run `npm install module-b`

The goal
- I want to **symlink module-b & module-a sources** in app/, this way change on are propaged without having to run `npm update`

How would you do this?

**Comment by dmail** [comment]
It soulds like npm can't help me here, but this module add the functionnality I'm looking for : https://github.com/feross/zelda

**Comment by dmail** [comment]
If someone is interested I've made a preinstall script doing what I'm looking for : https://gist.github.com/dmail/c0a7901acba918c60ca3

**Comment by othiym23** [comment]
You might also want to take a look at [`linklocal`](http://npm.im/linklocal), which is solving a slightly different problem, but is in the same ballpark.
