### ISSUE TITLE
Is there a way to remove an mistakenly published module from the registry completely?

### ISSUE THREAD

**Issue by josiahsprague** [npm/npm#8068]
I accidentally published a private module to npm without the namespace. I promptly unpublished it, but then our `npm install`s started failing for projects that are using a module by the same name, but with a GitHub URL. Updating npm with `npm install npm -g` fixes the issue, but we've got close to 100 CI environments on old versions of of npm, and it's going to be a bit of a pain to update all of them. Is there any way to completely remove the entry at https://registry.npmjs.org/jungle-solidus ?

**Comment by smikes** [comment]
Your best bet is to email support@npmjs.com , and mention this issue.  Someone will be able to look into it pretty soon - Monday, probably.

**Comment by josiahsprague** [comment]
Thanks. Email sent!
