### ISSUE TITLE
error when doing the npm install

### ISSUE THREAD

**Issue by donnalcassan** [npm/npm#8072]
Below are the instructions I received to work with Node and Sails.

1. Install Node JS including NPM

2. From the root of the project run npm install to install node dependencies.

3. When running the app locally connect to the Mongo DB by adding the file I emailed to you named development.js to the config/env folder.

4. Launch the app by running sails lift from the root of the project folder.

5. Use a tool like Postman to interact with the app.

In number two I am not sure that I am running npm install from the correct place. Do you know what "From the root of the project" means and how to get there. I am totally new to this. Any help would be appreciated. Below is the error log I get when I run it from a prompt.

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose node symlink C:\Program Files (x86)\nodejs\\node.exe
5 verbose config Skipping project config: C:\Users\Donna/.npmrc. (matches userconfig)
6 error install Couldn't read dependencies
7 verbose stack Error: ENOENT, open 'C:\Users\Donna\package.json'
7 verbose stack     at Error (native)
8 verbose cwd C:\Users\Donna
9 error Windows_NT 6.1.7601
10 error argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
11 error node v0.12.2
12 error npm  v2.7.4
13 error path C:\Users\Donna\package.json
14 error code ENOPACKAGEJSON
15 error errno -4058
16 error package.json ENOENT, open 'C:\Users\Donna\package.json'
16 error package.json This is most likely not a problem with npm itself.
16 error package.json npm can't find a package.json file in your current directory.
17 verbose exit [ -4058, true ]
```

**Comment by KenanY** [comment]
@donnalcassan You need to `cd` to the directory where the `package.json` is. Impossible for me to find it for you :P

I guess you should follow this? https://github.com/balderdashy/sails#your-first-sails-project

If anything, this is not an appropriate ticket for the `npm` issue tracker.

**Comment by othiym23** [comment]
@KenanY's instructions are correct – you need to be in the root of the checked out SailsJS directory before running `npm install`, not in your home directory. I'm going to go ahead and close this as resolved. Good luck!
