### ISSUE TITLE
Error when installing Bower 1.4.1 on OS X 10.10.3

### ISSUE THREAD

**Issue by hawk-lord** [npm/npm#8076]
$ /usr/local/bin/node /usr/local/bin/npm install bower@1.4.1

less npm-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'bower@1.4.1' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose stack Error: Invalid version: "2.1.0.0"
4 verbose stack     at Object.module.exports.fixVersionField (/usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/fixer.js:190:13)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/normalize.js:30:38
4 verbose stack     at Array.forEach (native)
4 verbose stack     at normalize (/usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/normalize.js:29:15)
4 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:342:33)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:126:33)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:331:40
4 verbose stack     at evalmachine.<anonymous>:336:14
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:102:5
4 verbose stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:99:15)
5 verbose cwd /Users/per/WebstormProjects/Add-OnSDK/direct-currency-converter-2
6 error Darwin 14.3.0
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "bower@1.4.1"
8 error node v0.12.0
9 error npm  v2.5.1
10 error Invalid version: "2.1.0.0"
11 error If you need help, you may report this error at:
11 error     <http://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@hawk-lord Do you have a `package.json` in your current working directory? Does it have a `"version"` field of `2.1.0.0`? If so, that's not valid [SemVer](http://semver.org/), hence the error.

**Comment by hawk-lord** [comment]
Yes, it's true, thanks!
