### ISSUE TITLE
Can npm config set --global be shared across packages?

### ISSUE THREAD

**Issue by mscappini** [npm/npm#8078]
I've Googled a ton, read through `npm` source, searched these issues, but have come up empty-handed.

Can I do something like this:

    npm config set somekey 5 --global

...and then access that from different packages? I know the scoping works by package name, but I'd like to know if there is a way to share among many packages.

Secondly, if not, is there a good way to do this that's more along the lines of a best practice scenario?

**Comment by smikes** [comment]
It looks like you're trying to use `npm config` to share config settings between different modules.  That's not what `npm config` is for -- it's intended to provide a place for `npm` to store its configuration information.

While you may be able to work with that in the short run, in the long run you'll almost certainly want your own config management code and a config file or database for your packages to share.

**Comment by mscappini** [comment]
Okay, I was just checking to see if there was a way, or if that it was even the correct approach.

Thanks Sam!
