### ISSUE TITLE
Double quotes and backticks inconsistent in npm-shrinkwrap file

### ISSUE THREAD

**Issue by RichardLitt** [npm/npm#8079]
I'm looking [here](https://docs.npmjs.com/cli/shrinkwrap), and occasionally "npm shrinkwrap" is used, and occasionally  `npm shrinkwrap` is used. I can't tell the difference. Why don't we switch everything to `?

**Comment by KenanY** [comment]
Consistency would be nice. :+1: for using backticks for filenames (`package.json`, `npm-shrinkwrap.json`) and commands (`npm install`, `npm shrinkwrap`).

**Comment by othiym23** [comment]
The documentation as a whole could use a pass to clean that up, because it's not particularly consistent anywhere.

**Comment by RichardLitt** [comment]
@othiym23 Best way to do that? One massive PR? Or a lot of little ones, like #8082?
