### ISSUE TITLE
Integrity check of files upon publishing

### ISSUE THREAD

**Issue by jonathanKingston** [npm/npm#8080]
I have seen npm publish several times now and so I am raising this error.

The publish of:
ember-cli-eslint@0.2.3
https://github.com/jonathanKingston/ember-cli-eslint/commit/9f8d5d5c2f0dd979bfabbe5a76030d450f99e986

However this one was ok:
ember-cli-eslint@0.2.4
https://github.com/jonathanKingston/ember-cli-eslint/commit/cd88592c4338cc43101a891304be8d9b56730f08

When users installed the package the index.js file was missing completely with no warnings when I published the package.

It seems the checks done upon caching the npm doesn't seem to check correctly. It seems to happen every other publish with the same file being the trouble.

**Comment by KenanY** [comment]
@jonathanKingston 

> index.js file was missing

Duplicate of https://github.com/npm/npm/issues/5082?

**Comment by jonathanKingston** [comment]
@KenanY yup duplicate sorry missed that.
