### ISSUE TITLE
npm ERR! code DEPTH_ZERO_SELF_SIGNED_CERT

### ISSUE THREAD

**Issue by venkey524** [npm/npm#8089]
Unable to install bower or serve in development server. Got the below error. Can some one help me to resolve the issue. Thank you.

C:\Program Files\nodejs>npm install -g bower
npm ERR! Windows_NT 6.0.6002
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "bower"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code DEPTH_ZERO_SELF_SIGNED_CERT

npm ERR! self signed certificate
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files\nodejs\npm-debug.log

C:\Program Files\nodejs>

**Comment by venkey524** [comment]
installed in C:\users\profilename\

It solves the problem.

**Comment by staggeredIC** [comment]
Adding how to do that here from StackOverflow for fellow node/npm newbies like myself:
http://stackoverflow.com/questions/14469515/how-to-npm-install-to-a-specified-directory
