### ISSUE TITLE
Error: connect EADDRINUSE

### ISSUE THREAD

**Issue by karlbateman** [npm/npm#8090]
# Error: connect EADDRINUSE

Strange issue here, running NodeJS on Windows 8.1 x64. My current versions are:
* NodeJS - v0.12.2
* NPM - 2.7.4

Full log: [https://gist.github.com/karlbateman/31fcd180f6678f319366](https://gist.github.com/karlbateman/31fcd180f6678f319366)

**Comment by smikes** [comment]
Thanks for reporting this and providing the full log.  This looks like a `node@0.12` bug, unfortunately:
```
1643 verbose stack Error: connect EADDRINUSE
1643 verbose stack     at exports._errnoException (util.js:746:11)
1643 verbose stack     at connect (net.js:842:19)
1643 verbose stack     at net.js:945:9
1643 verbose stack     at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:81:16)
1643 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:99:10)
1644 verbose cwd C:\Users\Karl Bateman
```

**Comment by karlbateman** [comment]
Thank you Sam for getting back to me. Should I create an issue on Node?


Regards,

  [image: photo]
*Karl Bateman*
Sole Proprietor, Netfox Digital Solutions
0844 318 3049 | karl@netfox.io | www.netfox.io
 <http://twitter.com/karlbateman_uk>
<http://plus.google.com/112190439660943506185>
<http://github.com/karlbateman>

**Comment by smikes** [comment]
Creating an issue on joyent/node is probably the right thing.  Do you have a small repro case that consistently shows the problem?

In the meantime, you may be able to work around it by downgrading your node to 0.10.38 ; you can still install the latest `npm` by following the guide here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows

**Comment by karlbateman** [comment]
I just installed nodejs using the standard installation on windows and
running npm install --global @module_name@ causes the issue.

I have a development server which has everything so I won't bother running
node on windows. Thought I would raise the issue in case others ran into
similar issues.

I will go ahead and create the issue at joyent/node. Thanks for your help.

Regards,

Karl Bateman

This email has been sent from my mobile.

**Comment by smikes** [comment]
By the way, there is a bad interaction between two known bugs — one in `node@>0.11` and `iojs` and the other in `npm@<2.8.2`.  This can cause ECONNRESET and ETIMEDOUT errors.  The full writeup is here: https://github.com/npm/npm/issues/7699  You can fix this problem by updating your `npm` to the latest (see below).

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows

**Comment by smikes** [comment]
Can this issue now be closed?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by karlbateman** [comment]
Yeah sure, thanks for your help :smile:

**Comment by othiym23** [comment]
Closing as resolved.
