### ISSUE TITLE
Only show lifecycle script banner if stdout is a TTY

### ISSUE THREAD

**Issue by isaacs** [npm/npm#8091]
If stdout is not a TTY, then there's a good chance that the user is piping the output somewhere, perhaps as part of a CI system that consumes parseable test output, etc.

Let's skip the banner in those cases.

Here's a patch, but testing this is a little bit tricky, because I can't figure out how to run npm as a child process, in a test, and actually make stdout be a TTY, without piping to the top-level stdout, which then is not inspectable...  _<goes off to campaign for bringing createPTY() back to Node.js, windows-compatibility-be-damned>_

``` patch
diff --git a/lib/utils/lifecycle.js b/lib/utils/lifecycle.js
index 299fa56..a2fca4a 100644
--- a/lib/utils/lifecycle.js
+++ b/lib/utils/lifecycle.js
@@ -131,6 +131,9 @@ function runPackageLifecycle (pkg, env, wd, unsafe, cb) {

   var note = "\n> " + pkg._id + " " + stage + " " + wd
            + "\n> " + cmd + "\n"
+  if (!process.stdout.isTTY) {
+    note = ''
+  }
   runCmd(note, cmd, pkg, env, stage, wd, unsafe, cb)
 }

```

**Comment by smikes** [comment]
We can use `socat` (http://www.dest-unreach.org/socat/) to provide a mock TTY.  But that's a pretty heavy external dependency.

**Comment by othiym23** [comment]
This seems like a great idea but yeah, it really needs to be testable.

**Comment by iarna** [comment]
To test this: I would twiddle `process.stdout.isTTY` by hand and check the result. It may feel a bit heavy on the white-box-testing but as it actually is the only way for a node program to detect a tty, so regardless of internals eventually they'll be looking at that.

**Comment by othiym23** [comment]
This has been moved to the [npm roadmap](https://github.com/npm/npm/wiki/Roadmap), which we're using instead of the confusing `next-*` labels now. (@stefanpenner would probably really like this!)

**Comment by saper** [comment]
Would that affect npm-debug.log? In case of lifecycle scripts I'd say we need more logging ( https://github.com/npm/npm/issues/10491, https://github.com/npm/npm/pull/9227 ), not less..

**Comment by othiym23** [comment]
Still seems like a good idea, still needs tests to land, but this is a simple UX tweak that we can do at the same time we're improving the overall package script logging situation, so this is in scope for the next 6-12 months.
