### ISSUE TITLE
getLocalAddresses has no return statement (ie, always returns undefined) – is it even needed?

### ISSUE THREAD

**Issue by mhart** [npm/npm#8093]
See here: https://github.com/npm/npm/blob/21148620fa03a582f4ec436bb16bd472664f2737/lib/config/defaults.js#L318-L329

I discovered this when on a system that throws EPERM when calling `os.networkInterfaces()` – but it raises the question: can this function just be removed? It would certainly make life easier for systems that have issues with network interface access (Googling revealed a few)

**Comment by othiym23** [comment]
See #8096 for the very simple fix of this. We'd have to take a further look into the history of npm/npmconf, which is where this functionality originated, to understand why `getLocalAddresses` existed in the first place, but my understanding is that it is indeed necessary when dealing with some complex network infrastructures (i.e. large enterprise intranets, particularly those running dual-stack IPv4 and IPv6).
