### ISSUE TITLE
Wrap os.networkInterfaces() in try/catch in getLocalAddresses()

### ISSUE THREAD

**Issue by mhart** [npm/npm#8094]
Related to #8093 – if the function is to be kept, can we just wrap the `os.networkInterfaces()` call in `getLocalAddresses` in a try/catch statement for systems that don't support it or don't have permissions for it? Considering the function never actually returned anything I can't imagine this would affect anything.

**Comment by mhart** [comment]
Ah, sorry, code in question is here: https://github.com/npm/npm/blob/21148620fa03a582f4ec436bb16bd472664f2737/lib/config/defaults.js#L318-L329

**Comment by mhart** [comment]
Looks like someone else has needed to do the same thing (not sure what for though): https://api.merproject.org/package/view_file/home:sfietkonstantin:sailfish:experiments/nodejs/npm-network-interfaces.patch?expand=1

**Comment by othiym23** [comment]
> for systems that don't support it

Such as?

> or don't have permissions for it

Likewise – what needs elevated permissions to run `os.networkInterfaces()`?

**Comment by mhart** [comment]
Well – I already linked to one example – that person needed to patch it to run on Sailfish OS.

AWS Lambda is a sandboxed Node.js environment where the user doesn't have permissions to make this call – this is where I ran into it.

Here's another example where EAFNOSUPPORT is thrown with QEMU: https://github.com/joyent/node/issues/8616

If the call's not actually needed (unless there's some rare proxy environment?) – then it should be fine to continue if it fails. Or not?

**Comment by mhart** [comment]
(You get an EPERM on AWS Lambda FWIW)

**Comment by mhart** [comment]
(and once wrapped in a try/catch, npm works fine on AWS Lambda – at least in the testing I've done)

**Comment by othiym23** [comment]
I would like to have a test around this, but it will probably involve some epic Docker jiggery-pokery, so I've just contented myself with verifying that the existing tests pass. Fixed in a4b62387b41848818973eeed056fd5c6570274f3. Thanks for bringing this to our attention!

**Comment by mhart** [comment]
Great! Thanks for getting that in :+1:
