### ISSUE TITLE
Error when publishing package

### ISSUE THREAD

**Issue by regal60740** [npm/npm#8095]
I am trying to publish a package and I get errors. Since I'm getting this code from a textbook, I'm assuming it's correct but as we all know, these books sometimes have errors. Here is the log file and it's contents. If you can determine from this what the issue is, I would greatly appreciate it:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'publish' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose publish [ '.' ]
6 silly cache add args [ '.', null ]
7 verbose cache add spec .
8 silly cache add parsed spec { raw: '.',
8 silly cache add   scope: null,
8 silly cache add   name: null,
8 silly cache add   rawSpec: '.',
8 silly cache add   spec: 'C:\\node_samples\\math_example',
8 silly cache add   type: 'local' }
9 error addLocal Could not install C:\node_samples\math_example
10 verbose stack Error: EISDIR, read
10 verbose stack     at Error (native)
11 verbose cwd C:\node_samples\math_example
12 error Windows_NT 6.3.9600
13 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "publish"
14 error node v0.12.2
15 error npm  v2.7.4
16 error code EISDIR
17 error errno -4068
18 error EISDIR, read
19 error If you need help, you may report this error at:
19 error     <https://github.com/npm/npm/issues>
20 verbose exit [ -4068, true ]
```

**Comment by smikes** [comment]
You won't be able to publish that package to the `npm` registry because there's already a package by that name.  If you want to publish it under your own scope (eg `@regal60740/math_example`), then you can create an npmjs account and then publish it as a public, scoped module.

I'm not sure why the error code you are getting is EISDIR, though.  That looks like `npm` is expecting a file and getting a directory instead.

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.

**Comment by regal60740** [comment]
Not a problem, thanks.

**Comment by crobinson42** [comment]
Just adding to the knowledge base.. after I pulled my hair out for 7.2 minutes because of this same error... 

You have to be in the same directory as `package.json` when running `npm publish`
