### ISSUE TITLE
problem   installing sails module

### ISSUE THREAD

**Issue by brw31415** [npm/npm#8098]

**Comment by KenanY** [comment]
@brw31415 What issue are you experiencing? Is there a `npm-debug.log` you can upload as a [gist](https://gist.github.com/)? [etc](https://github.com/npm/npm/wiki/Contributing-Guidelines#a-great-bug-report-contains)

**Comment by tjwebb** [comment]
@brw31415 if you can provide more info on this, we'll try to help.

-- <3 the sails.js team

**Comment by brw31415** [comment]
much thanks, issue seemed to resolve itself after i switched to a different
(better) wifi network. of course, such things do not give any accurate
 error messages, unfortunately.

**Comment by othiym23** [comment]
Closing as (mysteriously) resolved.
