### ISSUE TITLE
404 on module I just published

### ISSUE THREAD

**Issue by tjwebb** [npm/npm#8099]
I just published `react-kendo` `0.13.9`. It's in the registry here: https://registry.npmjs.org/react-kendo/0.13.9. But the tarball returns 404: http://registry.npmjs.org/react-kendo/-/react-kendo-0.13.9.tgz, so it's impossible to install.

I tried publishing two other versions and they experience the same issue

published using npm 2.7.4

**Comment by smikes** [comment]
Now that you've got an updated npm (2.8.3) do you still see this problem?  I am able to install react-kendo using npm 2.8.4, on Mac OSX

**Comment by tjwebb** [comment]
Yea, except most of my modules are published automatically from travis-ci, which uses node 0.12.2, of course, since that's the freaking bundled version. (just hit this same issue with another module,  https://registry.npmjs.org/sails-backbone-client/-/sails-backbone-client-0.11.13.tgz) Now I get to manually npm pubish everything until a new version of node comes bundled with a new version of npm, and pray that they actually work together. It's seriously infuriating how unstable npm still is after all this time. </rant>

**Comment by smikes** [comment]
Hey I actually may have a fix for that - let me jump on my laptop (on phone now) but you can tell Travis to update the npm in the container

**Comment by smikes** [comment]
If you are using `npm` in a Travis CI environment, you can tell Travis to always run with the latest `npm`.  See here for an example .travis.yml file that runs with the latest npm: https://github.com/reid/node-jslint/blob/master/.travis.yml

```
before_install:
  - "npm install -g npm@latest"
```

Works for 0.8, 0.10, 0.11, 0.12 and iojs.

**Comment by tjwebb** [comment]
I mean, thanks for the advice, but I have over a hundred npm modules that I'd have to go through and change this setting on. I think the onus is on npm to not publish GA releases that are totally broken, but I'm not not optimistic.
