### ISSUE TITLE
error in installing express on windows

### ISSUE THREAD

**Issue by tanvip** [npm/npm#8101]
Hi, 

I am trying to install express with following command : 
npm install -g express

I get this error:

npm ERR! registry error parsing json
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files
x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "express"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4

npm ERR! Unexpected token <
npm ERR! <html><head><title>Apache Tomcat/7.0.37 - Error report</title><style><
--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;
ont-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-
olor:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:whi
e;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans
serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-ser
f;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif
background:white;color:black;font-size:12px;}A {color : black;}A.name {color :
lack;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 404 - /expr
ss</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>mes
age</b> <u>/express</u></p><p><b>description</b> <u>The requested resource is n
t available.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.37</h3
</body></html>
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\XYZ\node\npm-debug.log

npm-debug.log says:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'express' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose node symlink C:\Program Files (x86)\nodejs\\node.exe
5 silly cache add args [ 'express', null ]
6 verbose cache add spec express
7 silly cache add parsed spec { raw: 'express',
7 silly cache add   scope: null,
7 silly cache add   name: 'express',
7 silly cache add   rawSpec: '',
7 silly cache add   spec: '*',
7 silly cache add   type: 'range' }
8 verbose addNamed express@*
9 silly addNamed semver.valid null
10 silly addNamed semver.validRange *
11 silly addNameRange { name: 'express', range: '*', hasData: false }
12 silly mapToRegistry name express
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry http://registry.npmjs.org/
15 silly mapToRegistry uri http://registry.npmjs.org/express
16 verbose addNameRange registry:http://registry.npmjs.org/express not in flight; fetching
17 verbose request uri http://registry.npmjs.org/express
18 verbose request no auth needed
19 info attempt registry request try #1 at 11:57:38 AM
20 verbose request id fd926ae490cd7782
21 http request GET http://registry.npmjs.org/express
22 http 404 http://registry.npmjs.org/express
23 verbose bad json <html><head><title>Apache Tomcat/7.0.37 - Error report</title><style></style> </head><body><h1>HTTP Status 404 - /express</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>/express</u></p><p><b>description</b> <u>The requested resource is not available.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.37</h3></body></html>
24 error registry error parsing json
25 verbose headers { server: 'Apache-Coyote/1.1',
25 verbose headers   'content-type': 'text/html;charset=utf-8',
25 verbose headers   'content-length': '965',
25 verbose headers   date: 'Tue, 28 Apr 2015 06:27:38 GMT' }
26 silly get cb [ 404,
26 silly get   { server: 'Apache-Coyote/1.1',
26 silly get     'content-type': 'text/html;charset=utf-8',
26 silly get     'content-length': '965',
26 silly get     date: 'Tue, 28 Apr 2015 06:27:38 GMT' } ]
27 verbose stack SyntaxError: Unexpected token <
27 verbose stack <html><head><title>Apache Tomcat/7.0.37 - Error report</title><style></style> </head><body><h1>HTTP Status 404 - /express</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>/express</u></p><p><b>description</b> <u>The requested resource is not available.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.37</h3></body></html>
27 verbose stack     at Object.parse (native)
27 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:197:23)
27 verbose stack     at Request._callback (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:170:14)
27 verbose stack     at Request.self.callback (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:344:22)
27 verbose stack     at Request.emit (events.js:110:17)
27 verbose stack     at Request.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:1239:14)
27 verbose stack     at Request.emit (events.js:129:20)
27 verbose stack     at IncomingMessage.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:1187:12)
27 verbose stack     at IncomingMessage.emit (events.js:129:20)
27 verbose stack     at _stream_readable.js:908:16
28 verbose cwd C:\Users\tanpatel\node
29 error Windows_NT 6.1.7601
30 error argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "express"
31 error node v0.12.2
32 error npm  v2.7.4
33 error Unexpected token <
33 error <html><head><title>Apache Tomcat/7.0.37 - Error report</title><style></style> </head><body><h1>HTTP Status 404 - /express</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>/express</u></p><p><b>description</b> <u>The requested resource is not available.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.37</h3></body></html>
34 error If you need help, you may report this error at:
34 error     <https://github.com/npm/npm/issues>
35 verbose exit [ 1, true ]

Any idea as to how can I resolve this bug?

**Comment by smikes** [comment]
It looks like `npm` is not able to reach the `npm` registry and is instead talking to a proxy server.  How do you log in to the proxy at your site, and have you configured the `HTTP_PROXY` environment variable?

More information here: https://docs.npmjs.com/misc/config#proxy

**Comment by tanvip** [comment]
Hey...there was a problem while setting proxy server...Got it...it's running now.
thanks :)
But it would be great if you can explain the role of these proxy servers for npm

**Comment by Ingosmar89219** [comment]
hey friends, What Can I do for this error with express when im installing it in a project of "polymer".
C:\Users\osmarvirux\Documents\messenger>npm install express
express@4.14.0 ..\..\node_modules\express
├── escape-html@1.0.3
├── array-flatten@1.1.1
├── content-type@1.0.2
├── encodeurl@1.0.1
├── merge-descriptors@1.0.1
├── etag@1.7.0
├── methods@1.1.2
├── cookie@0.3.1
├── path-to-regexp@0.1.7
├── cookie-signature@1.0.6
├── utils-merge@1.0.0
├── range-parser@1.2.0
├── vary@1.1.0
├── serve-static@1.11.1
├── content-disposition@0.5.1
├── parseurl@1.3.1
├── fresh@0.3.0
├── depd@1.1.0
├── qs@6.2.0
├── on-finished@2.3.0 (ee-first@1.1.1)
├── finalhandler@0.5.0 (unpipe@1.0.0, statuses@1.3.0)
├── debug@2.2.0 (ms@0.7.1)
├── proxy-addr@1.1.2 (forwarded@0.1.0, ipaddr.js@1.1.1)
├── accepts@1.3.3 (negotiator@0.6.1, mime-types@2.1.12)
├── type-is@1.6.13 (media-typer@0.3.0, mime-types@2.1.12)
└── send@0.14.1 (destroy@1.0.4, statuses@1.3.0, ms@0.7.1, mime@1.3.4, http-error
s@1.5.0)

**Comment by KenanY** [comment]
@Ingosmar89219 There is no error in the output you've posted. Please just open a new issue rather than commenting on year-old, resolved issues.
