### ISSUE TITLE
Error downloading npm package.

### ISSUE THREAD

**Issue by pavanputhram** [npm/npm#8103]
Hi am new to npm. Just recently i uploaded npm package. When I try to install via windows command line it fails. If am using Git Bash to install npm it will work.

Following is npm-debug.log genereated when i try to run `npm install smsowl` in windows command line

	0 info it worked if it ends with ok
	1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
	1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
	1 verbose cli   'install',
	1 verbose cli   'smsowl' ]
	2 info using npm@2.7.4
	3 info using node@v0.12.2
	4 verbose node symlink C:\Program Files\nodejs\\node.exe
	5 warn package.json smsowltest@1.0.0 No repository field.
	6 warn package.json smsowltest@1.0.0 No README data
	7 silly cache add args [ 'smsowl@git://github.com/mahoujas/smsowl-nodejs.git', null ]
	8 verbose cache add spec smsowl@git://github.com/mahoujas/smsowl-nodejs.git
	9 silly cache add parsed spec { raw: 'smsowl@git://github.com/mahoujas/smsowl-nodejs.git',
	9 silly cache add   scope: null,
	9 silly cache add   name: 'smsowl',
	9 silly cache add   rawSpec: 'git://github.com/mahoujas/smsowl-nodejs.git',
	9 silly cache add   spec: 'git+ssh://git@github.com/mahoujas/smsowl-nodejs.git',
	9 silly cache add   type: 'hosted',
	9 silly cache add   hosted:
	9 silly cache add    { type: 'github',
	9 silly cache add      ssh: 'git@github.com:mahoujas/smsowl-nodejs.git',
	9 silly cache add      sshUrl: 'git+ssh://git@github.com/mahoujas/smsowl-nodejs.git',
	9 silly cache add      httpsUrl: 'https://github.com/mahoujas/smsowl-nodejs.git',
	9 silly cache add      directUrl: 'https://raw.githubusercontent.com/mahoujas/smsowl-nodejs/master/package.json' } }
	10 info maybeGithub Attempting git://github.com/mahoujas/smsowl-nodejs.git from git://github.com/mahoujas/smsowl-nodejs.git
	11 verbose addRemoteGit git-github-com-mahoujas-smsowl-nodejs-git-8417b30d not in flight; caching
	12 verbose stack TypeError: Cannot read property 'trim' of undefined
	12 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\cache\add-remote-git.js:98:31
	12 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\utils\git.js:50:14
	12 verbose stack     at F (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:40:25)
	12 verbose stack     at E (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:43:29)
	12 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:54:16
	12 verbose stack     at FSReqWrap.oncomplete (fs.js:95:15)
	13 verbose cwd D:\MyProgs\SmsOwl\test\nodejs
	14 error Windows_NT 6.3.9600
	15 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "smsowl"
	16 error node v0.12.2
	17 error npm  v2.7.4
	18 error Cannot read property 'trim' of undefined
	19 error If you need help, you may report this error at:
	19 error     <https://github.com/npm/npm/issues>
	20 verbose exit [ 1, true ]

**Comment by smikes** [comment]
There have been a lot of improvements to npm -- especially around git remotes -- since 2.7.4. Can you try updating your npm installation?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

Thanks!

**Comment by pavanputhram** [comment]
@smikes 

Thank you very much. It solved the problem.
