### ISSUE TITLE
json2csv installation

### ISSUE THREAD

**Issue by johannnnnnn** [npm/npm#8107]
$ sudo npm install json2csv

I get:

npm WARN deprecated json2csv@2.2.1: not maintained anymore
json2csv@2.2.1 node_modules/json2csv
├── async@0.2.10
├── cli-table@0.2.0 (colors@0.3.0)
└── commander@1.0.5 (keypress@0.1.0)

What else should I do before being able to use json2csv from the command line?

Thank you for you time.

**Comment by KenanY** [comment]
@johannnnnnn If you'd like to use `json2csv` from the command-line, you have to install it globally:

``` sh
$ sudo npm install -g json2csv
```

**Comment by johannnnnnn** [comment]
Thank You for the prompt reply.

Now it works...
Thank You!!
