### ISSUE TITLE
Add GitHub login option to website

### ISSUE THREAD

**Issue by brennanMKE** [npm/npm#8109]
I am logged into GitHub on my home and work computer but I only have my password for the npm website stored on my keychain on my home computer. I would like to simply log in using GitHub. Developer services like Parse have this option which is very helpful.

**Comment by smikes** [comment]
Thanks for making this feature request.

**Comment by KenanY** [comment]
[npm/newww](https://github.com/npm/newww) :eyes:

**Comment by othiym23** [comment]
Closing, because this is a feature request for the web site and not the CLI. You might want to take it over there!
