### ISSUE TITLE
Create weighted rating using GitHub

### ISSUE THREAD

**Issue by brennanMKE** [npm/npm#8110]
If accounts are linked with GitHub it would be possible to create a weighted rating based on a GitHub user's total number of stars across all of their repos with Node source code. If indutny rates a project at 5 I would definitely value that rating over someone who has no popular GitHub repos. Perhaps the weighted rating could be used to display the top 20 modules by category by this weight rating to help select useful modules for security, networking, social, etc.

**Comment by KenanY** [comment]
@brennanMKE Sounds like a feature request for the website at [npm/newww](https://github.com/npm/newww) :)

**Comment by othiym23** [comment]
Yes. This is a feature request for the web site team (or maybe the registry team?). If you do want to see this happen, go ahead and copy this to npm/newww. I'm going to close this one, because it's not an npm CLI issue.
