### ISSUE TITLE
Allow users to create and manage lists on the website

### ISSUE THREAD

**Issue by brennanMKE** [npm/npm#8111]
I would like to manage a list of my npm modules which I use. I could make my lists public or private so I can quickly get started with a new project. Later the command-line to automatically add all members on a list as dependencies.

**Comment by KenanY** [comment]
@brennanMKE Feature requests for the website should be opened at the [npm/newww](https://github.com/npm/newww) repo. What you have described here sounds like https://github.com/npm/newww/issues/313.

**Comment by othiym23** [comment]
Same as last two – take it to npm/newww. ;)
