### ISSUE TITLE
Scopes documentation is out of date

### ISSUE THREAD

**Issue by seldo** [npm/npm#8119]
https://github.com/npm/npm/blob/master/doc/misc/npm-scope.md

This needs to be updated to reflect the existence of private modules service.

**Comment by othiym23** [comment]
Is 546626059909dca1906454e820ca4e315c1795bd, which is included in `npm@2.9.0`, insufficient?

**Comment by othiym23** [comment]
546626059909dca1906454e820ca4e315c1795bd is indeed sufficient, and will hit the site on Thursday, so closing this as resolved.
