### ISSUE TITLE
npm install stuck forever

### ISSUE THREAD

**Issue by edravis** [npm/npm#8124]
Any module that I try install gets forever with this kind of log:
`Dependency 'SOME_MODULE' exists in both dependencies and devDependencies, using 'SOME_MODULE@x.y.z' from dependencies`

Looks like it's trying with the same modules all the time: `tap`, `karma`, `mocha`, etc. But of course, those are very popular modules and maybe it's normal.

I've uninstalled and purged the whole npm: including removing the global `node_modules` and `.npm`. After reinstall still failing.

My stack: 
* Mac OSX Yosemite 10.10 
* node v0.10.33
* npm v2.7.5

Note: I've tried to install my own module `buffer64` and it works.

Last one I tried is `wifi-password` (because it looks tiny) I'm still waiting, have been 30 minutes for now.

I don't think share the logs will help, as I've said there are tons of "(...) exists in both Dependencies bla bla (...)".

What should I do? At least to still working. Could you help me? Need more information?

I think there is a current trouble and many people is suffering it, i. e.: #7741

Also I realised that my .npm folder is growing so much, outputs:
* `ls | wc -l` throw 700
* `find . | wc -l` throw 30594

I've checked with the .npm of a fella which outputs:
* `ls | wc -l` throw 1056
* `find . | wc -l` throw 10291

He has 300 folders (npm modules) more but just a 1/3 part of files. Really weird.

P.S: If I run the modules in the `/usr/local/lib/node_modules/` they work.
P.S 2: After more than an hour I stopped because it will consume all my disk space and this is obvious wrong.

**Comment by smikes** [comment]
That sounds like a really annoying bug! Unfortunately we haven't heard of anything like it before.

Since your `npm` is at 2.7.5, could you please upgrade it to the latest by running

```
sudo npm install -g npm@latest
```
(depending on how you installed npm, you may not need the sudo)

And then let us know if you still see the problem?

Thanks!

**Comment by edravis** [comment]
First, thanks for reply. 
I've ran the instruction and it has stuck, confirming the reported error.

Irony.

**Comment by aniforprez** [comment]
I'm having the exact same issue. This only happens when I use the `--dev` flag.

**Comment by KenanY** [comment]
@aniforprez `--dev` is very bad. https://github.com/npm/npm/issues/6200

**Comment by smikes** [comment]
@edravis Sorry for dropping this.  Can you try updating your `npm` this way instead:

```
curl -L https://www.npmjs.com/install.sh | sudo /bin/sh
```

**Comment by aniforprez** [comment]
@KenanY But the separate devdependencies list was very convenient to keep the size of the node-modules folder small and tight during production. Do you know of any other way this can be done?

**Comment by smikes** [comment]
@aniforprez Separating `dependencies` and `devDependencies` is a very good idea, and it sounds like your project is set up to do that.

The problem with `npm install --dev` is that it **recursively** installs `devDependencies` for your module, all of its (`dependencies` + `devDependencies`), etc.  Thus if your module has a dependency that uses `jshint`, then you'll be getting not only `jshint` but all of `jshint`'s `devDependencies`... almost certainly not what you want.

A normal `npm install` in the module directory should get you all the (`dependencies` + `devDependencies`) for the current module, without installing the `devDependencies` of all of the child modules.

I think I don't understand your use case - could you tell me more about what `install --dev` is doing for you?

**Comment by aniforprez** [comment]
@smikes OK, I didn't know that `npm install` would install ALL the modules including the devDependency ones. A fundamental misunderstanding on my part :P

**Comment by smikes** [comment]
Yes, it's an odd gotcha -- that's why @kenanY says `install --dev` is bad, and why there's some talk of just making `install --dev` behave like `install`

`npm install` will install the dependencies + devDependencies of the current module, and then transitively install only the `dependencies` of anything it has installed.

`npm install --dev` will install deps + devDeps , transitively.  The total install tree for `npm install --dev` can run into the gigabytes...

**Comment by aniforprez** [comment]
So I can use `npm install --production` to not install the devDependencies right?

**Comment by edravis** [comment]
btw @smikes just for add more information, I didn't fix the problem I just formatted the computer because, you know, working reasons.

**Comment by othiym23** [comment]
I'm going to go ahead and close this as abandoned, but @aniforprez, yes, running `npm install --prod` or `npm install --production` from the application's directory won't install `devDependencies`, and you can run `npm prune --prod` after the fact to remove installed `devDependencies`.
