### ISSUE TITLE
SELF_SIGNED_CERT_IN_CHAIN

### ISSUE THREAD

**Issue by blemaire** [npm/npm#8125]
Hi all,

I am running into the following problem whilst trying to update npm or install any package:

npm install npm -g --ca=""
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "npm" "-g" "--ca="
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code SELF_SIGNED_CERT_IN_CHAIN

npm ERR! self signed certificate in certificate chain
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\reapit\prog\mobile\resources\npm-debug.log

I have tried running this first :
>npm config set ca=""
But no luck I get the same error...

Can anyone help?
Thanks
Bastien

**Comment by smikes** [comment]
Thanks for reporting this.  Is it possible that you have an SSL-intercepting proxy running?  See this part of the troubleshooting guide: https://github.com/npm/npm/wiki/Troubleshooting#ssl-error

**Comment by blemaire** [comment]
Thanks a lot, I set the proxy and https_proxy to use our corporate proxy server and all is well.
Thanks
