### ISSUE TITLE
mongodb Intallation issue

### ISSUE THREAD

**Issue by pkumar01** [npm/npm#8128]
Hi, 

I am trying to install mongodb but it is giving me some issues which i don't understand, could you please help me fix this issue.

i have attached the log screenshot, please help. 

![screen shot 2015-04-29 at 4 11 06 pm](https://cloud.githubusercontent.com/assets/5529095/7389310/5fdd5fb8-ee8a-11e4-9fd3-acd1d9156770.png)

**Comment by smikes** [comment]
It looks like your installation of `npm` is damaged.  Can you try reinstalling `node`, using either the 0.10.38 (older stable) or the latest, 0.12.2?  This should give you a valid installation of `npm`.

**Comment by pkumar01** [comment]
works fine now thanks...

**Comment by othiym23** [comment]
Closing as resolved!
