### ISSUE TITLE
SELF_SIGNED_CERT_IN_CHAIN (while installing bem-tools)

### ISSUE THREAD

**Issue by webcheriff** [npm/npm#8129]
I tried to install bem-tools and there was a problem. Although, both of NodeJS and npm packages were successfully installed. What's the problem about?
![2015-04-29 13 49 23](https://cloud.githubusercontent.com/assets/12167003/7389437/958f998c-ee76-11e4-8c65-dc67e80c23c9.png)

**Comment by smikes** [comment]
Usually this error message means you have a self-signed certificate somewhere in your trust chain.  Can you please run this command and let us know what the output is:

```
npm config get ca
```

Also, have you ever installed any certificates into your computer's root store?

**Comment by webcheriff** [comment]
When I run this command, i got that: "null". Oh, I don't remember. I suppose, yes.
