### ISSUE TITLE
bin/npm script seems to use the wrong path

### ISSUE THREAD

**Issue by TiddoLangerak** [npm/npm#8130]
The [`bin/npm`](https://github.com/npm/npm/blob/master/bin/npm) script seems to be a bash script that shims the actual `bin/npm-cli.js` script. However, when calling that script it tries to execute `node <basedir>/bin/node_modules/npm/bin/npm-cli.js`, which doesn't exist. It then throws the error `Error: Cannot find module '/<basedir>/bin/node_modules/npm/bin/npm-cli.js'.`

Shouldn't the path referenced in the script be `$basedir/npm-cli.js` instead? And if not, is there another way that I can add a local npm installation to path, since the script from the `bin` folder is apparently not usable for that at the moment?

**Comment by KenanY** [comment]
> Shouldn't the path referenced in the script be `$basedir/npm-cli.js` instead?

Looks like no: https://github.com/npm/npm/pull/7784

**Comment by TiddoLangerak** [comment]
Is it then somehow possible to add a local version of npm to the path? My use-case is that I need to run npm in an environment where npm might not be globally installed. I have no control over the invocation of npm (it's done via some other script) so I want to add a local npm installation to PATH. My initial "solution" was to add the `npm/bin` folder to the path since there was an `npm` shim there, but that doesn't work like I mentioned above.
