### ISSUE TITLE
When does an _authToken expire?

### ISSUE THREAD

**Issue by josiahsprague** [npm/npm#8133]
Forgive me if this is documented somewhere, but I couldn't find this information anywhere;

If I authenticate with `npm login` and get an auth token in my `.npmrc`;
```
//registry.npmjs.org/:_authToken=00000000-0000-0000-0000-000000000000
```
What conditions should I expect to invalidate that token? I've heard rumors that it's not a session token, that it only expires when my password changes, but I've also noticed that it seems to be invalidated if I do `npm logout` and then try to authenticate with the original token. Is the token invalidated if I log into a different account? Does it have an expiration date, or will it only be invalidated from certain actions?

**Comment by smikes** [comment]
These are great questions which can maybe be answered by someone from the npm-registry team - @bcoe maybe?

**Comment by bcoe** [comment]
@josiahsprague the token is not associated with your password, so a password change will not invalidate the prior token. 

Logging out will invalidate the token.

Eventually we would like to offer a UI, like in GitHub, which allows you to invalidate specific tokens.

**Comment by josiahsprague** [comment]
Thanks @bcoe ! 😎Will `npm login` with another account, and then `npm login` back into the original account invalidate the original token?

**Comment by bcoe** [comment]
@josiahsprague it will not invalidate the prior token.

This thread has convinced me to start a conversation with a few other npm people about token invalidation today. I think until we have a UI it might be good to invalidate all tokens on a password change perhaps? Right now I feel like the tokens are a bit too sticky.

Will keep you posted, good rule as of right now, is that your token is the keys to your account.

**Comment by josiahsprague** [comment]
Looks like the answers to this question are on the npm blog. http://blog.npmjs.org/post/118393368555/deploying-with-npm-private-modules
