### ISSUE TITLE
npm can't rename file: ETXTBSY

### ISSUE THREAD

**Issue by CharlieC3** [npm/npm#8134]
Hello,
I've looked around to see if this issue was already submitted but only found similar ones. I'm running Windows 7 and am trying to use npm in a shared folder in Vagrant.

I understand that there is little to no support for this use case, but am hoping to get more information and understand what's going on, and if there's anything I can do to work around this.

Here's the error I receive after running `npm install -g --no-bin-links`:

```
       npm verb stack Error: ETXTBSY, rename '/app/.npm/grunt-cli/0.1.13/package
.tgz.379c953b9be587e3ebf1bca95e044fb3'
       npm verb stack     at Error (native)
       npm verb cwd /app
       npm ERR! Linux 3.16.7-tinycore64
       npm ERR! argv "/app/vendor/node/bin/node" "/app/vendor/node/bin/npm" "ins
tall" "--userconfig" "/app/.npmrc"
       npm ERR! node v0.12.2
       npm ERR! npm  v2.7.4
       npm ERR! path /app/.npm/grunt-cli/0.1.13/package.tgz.379c953b9be587e3ebf1
bca95e044fb3
       npm ERR! code ETXTBSY
       npm ERR! errno -26
       al:
       npm ERR! ETXTBSY, rename '/app/.npm/grunt-cli/0.1.13/package.tgz.379c953b
9be587e3ebf1bca95e044fb3'
       npm ERR!
       npm ERR! If you need help, you may report this error at:
       npm ERR!     <https://github.com/npm/npm/issues>
       npm verb exit [ -26, true ]
       npm verb stack Error: ETXTBSY, rename 'npm-debug.log.c48eefa4ad9c973a39b8
563949d5b6da'
       npm verb stack     at Error (native)
       npm verb cwd /app
       npm ERR! Linux 3.16.7-tinycore64
       npm ERR! argv "/app/vendor/node/bin/node" "/app/vendor/node/bin/npm" "ins
tall" "--userconfig" "/app/.npmrc"
       npm ERR! node v0.12.2
       npm ERR! npm  v2.7.4
       npm ERR! path npm-debug.log.c48eefa4ad9c973a39b8563949d5b6da
       npm ERR! code ETXTBSY
       npm ERR! errno -26
       al:
       npm ERR! ETXTBSY, rename 'npm-debug.log.c48eefa4ad9c973a39b8563949d5b6da'

       npm ERR!
       npm ERR! If you need help, you may report this error at:
       npm ERR!     <https://github.com/npm/npm/issues>
       npm verb exit [ -26, true ]
       al:
       npm ERR! Please include the following file with any support request:
       npm ERR!     /app/npm-debug.log
```

So far, I've tried the solution posted here:
https://github.com/npm/npm/wiki/Troubleshooting#running-a-vagrant-box-on-windows-fails-due-to-path-length-issues

As well as using the `--no-bin-links` and `-g` flags in each possible combination.

I can't pinpoint why it's unable to rename any files. I'm not sure it's a permissions issue, otherwise I'd get a different error. It might be a race condition, but I'm unsure.

Has anyone seen this before, or know how to resolve it?

**Comment by smikes** [comment]
I have not seen this before, but it kind of looks like a race condition.  If you have the chance, and this problem is still present, can you try running with npm@3 to see if the multi-stage install feature helps?

Thanks!

**Comment by maennel** [comment]
Hi @smikes. Thanks for taking time. I'm having the same issue (vagrant, Windows7, npm install not being able to rename, terminating with ETXTBSY) as  @CharlieC3. Until this point, I ran installation using npm@2.11.3.
After updating to npm@3 (``sudo npm install -g npm@3``; ``npm --version`` now prints ``3.3.1``), I still get the same error:
```
[...]
==> default:   [RuntimeException]
==> default:   Error Output: npm ERR! Linux 3.2.0-23-generic
==> default:   npm ERR! argv "node" "/usr/bin/npm" "install" "--no-bin-links"
==> default:   npm ERR! node v0.12.7
==> default:   npm ERR! npm  v3.3.1
==> default:   npm ERR! path /vagrant/.npm/gulp-minify-css/1.2.1/package.tgz.cf2efa919491ec2a80599239b64ee1f9
==> default:   npm ERR! code ETXTBSY
==> default:   npm ERR! errno -26
==> default:   npm ERR! ETXTBSY, rename '/vagrant/.npm/gulp-minify-css/1.2.1/package.tgz.cf2efa919491ec2a80599239b64ee1f9'
[...]
```

The package being installed is in this example gulp-minify-css, but I have observed situations where it was gulp-util or even other packages.

I hope these details may ring the bell in someones head ;) Thanks!

**Comment by asnowfix** [comment]
Same problem with `npm@3.3.5` (installed as `npm@latest`). Did anyone find a workaround?
