### ISSUE TITLE
npm error on upgrading ionic

### ISSUE THREAD

**Issue by exblopz** [npm/npm#8135]
I've just following command 
npm cache clean
npm install -g ionic

and heres the result

npm ERR! code ENOSPC
npm ERR! errno 54
npm ERR! fetch failed https://registry.npmjs.org/lodash.templatesettings/-/lodash.templatesettings-3.1.0.tgz
npm ERR! nospc ENOSPC, open '/usr/lib/node_modules/ionic/node_modules/archiver/node_modules/file-utils/node_modules/minimatch/package.json'
npm ERR! nospc This is most likely not a problem with npm itself
npm ERR! nospc and is related to insufficient space on your system.

npm ERR! System Linux 3.2.0-80-generic-pae
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "-g" "ionic"
npm ERR! cwd /home/archangle
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! path /usr/lib/node_modules/ionic/node_modules/archiver/node_modules/file-utils/node_modules/minimatch/package.json
npm ERR! code ENOSPC
npm ERR! errno 54
npm ERR! nospc ENOSPC, mkdir '/usr/lib/node_modules/ionic/node_modules/archiver/node_modules/file-utils/node_modules/rimraf'
npm ERR! nospc This is most likely not a problem with npm itself
npm ERR! nospc and is related to insufficient space on your system.

npm ERR! System Linux 3.2.0-80-generic-pae
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "-g" "ionic"
npm ERR! cwd /home/archangle
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! path /usr/lib/node_modules/ionic/node_modules/archiver/node_modules/file-utils/node_modules/rimraf
npm ERR! fstream_path /usr/lib/node_modules/ionic/node_modules/archiver/node_modules/file-utils/node_modules/rimraf
npm ERR! fstream_type Directory
npm ERR! fstream_class DirWriter
npm ERR! code ENOSPC
npm ERR! errno 54
npm ERR! fstream_stack /usr/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23
npm ERR! fstream_stack /usr/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53
npm ERR! fstream_stack Object.oncomplete (fs.js:108:15)
npm ERR! nospc ENOSPC, mkdir '/usr/lib/node_modules/ionic/node_modules/archiver/node_modules/file-utils/node_modules/iconv-lite'
npm ERR! nospc This is most likely not a problem with npm itself
npm ERR! nospc and is related to insufficient space on your system.

npm ERR! System Linux 3.2.0-80-generic-pae
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "-g" "ionic"
npm ERR! cwd /home/archangle
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! path /usr/lib/node_modules/ionic/node_modules/archiver/node_modules/file-utils/node_modules/iconv-lite
npm ERR! fstream_path /usr/lib/node_modules/ionic/node_modules/archiver/node_modules/file-utils/node_modules/iconv-lite
npm ERR! fstream_type Directory
npm ERR! fstream_class DirWriter
npm ERR! code ENOSPC
npm ERR! errno 54
npm ERR! fstream_stack /usr/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23
npm ERR! fstream_stack /usr/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53
npm ERR! fstream_stack Object.oncomplete (fs.js:108:15)
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/archangle/npm-debug.log
npm ERR! not ok code 0

Can anyone give me an answer or have a same problem?

I following this issue https://github.com/npm/npm/issues/5920 but until right now I don't know how to solve this kind of problem.

**Comment by KenanY** [comment]
```
npm ERR! nospc This is most likely not a problem with npm itself
npm ERR! nospc and is related to insufficient space on your system.
```

Looks like you are trying to install on a drive that either has no space, or has no permission to write.

  - Free some disk space or
  - Set the tmp folder somewhere with more space: `npm config set tmp /path/to/big/drive/tmp` or
  - Build Node yourself and install it somewhere writable with lots of space.

**Comment by exblopz** [comment]
It solved when I delete some npm files in /tmp directory.
