### ISSUE TITLE
insufficient debug information in the `.parent` property of an Error

### ISSUE THREAD

**Issue by Mithgol** [npm/npm#8139]
Having launched `npm install nw` on a flash drive under Windows XP I've eventually got the following error:

```
npm ERR! Windows_NT 5.1.2600
npm ERR! argv "c:\\Utils\\Node.js\\\\node.exe" "c:\\Utils\\Node.js\\node_modules
\\npm\\bin\\npm-cli.js" "install" "nw"
npm ERR! node v0.12.2
npm ERR! npm  v2.8.4
npm ERR! path C:\Documents and Settings\username.DOMAINNAME\Application Data\npm-cache\concat-map\0.0.1\package\package.json
npm ERR! code EPERM
npm ERR! errno -4048

npm ERR! Error: EPERM, rename 'C:\Documents and Settings\username.DOMAINNAME\Application Data\npm-cache\concat-map\0.0.1\package\package.json'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM, rename 'C:\Documents and Settings\username.DOMAINNAME\Application Data\npm-cache\concat-map\0.0.1\package\package.json']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   path: 'C:\\Documents and Settings\\username.DOMAINNAME\\Application Data\\npm-cache\\concat-map\\0.0.1\\package\\package.json',
npm ERR!   parent: 'brace-expansion' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
```

where `username.DOMAINNAME` is my local user and domain.

I have the necessary administator rights and thus I have to suspect some other cause for that `EPERM`. For example, the tree of dependencies might be so deep that it does not fit into the FAT32 limit of full path's length.

However, `parent: 'brace-expansion'` (in the above Error) does not actually help me to understand how deep the dependency tree really is.

Could npm be altered for `parent` to contain the full “path” (the list of parent and its parent dependencies) to the failed dependency? Perhaps, as an array.

**Comment by Mithgol** [comment]
I have create the [`npmtree`](https://www.npmjs.com/package/npmtree) package as a workaround.

**Comment by smikes** [comment]
Thanks for raising this issue.

`npm` contains a similar feature, where you can view the dependencies of a module -

```
npm ls
```

The next major version of `npm` will automatically raise and deduplicate dependencies when possible, which should lead to shallower dependency trees and less pain for Windows users.  (Some Windows programs have an implicit 260-char limit on path names).  `npm@3`  is going through final testing now, and should be ready soon.

**Comment by Mithgol** [comment]
Unfortunately, `npm ls` works only if the package is already installed (unless I fail to notice something in its [docs](https://docs.npmjs.com/cli/ls)) and thus it does not help if an error happens during the installation.

I guess I'll wait for `npm@3` then. Thanks.

**Comment by Mithgol** [comment]
Today I was able to install `nw` after I upgraded `npm` to version 2.9.0.

It means that the error either was some problem in npm's 2.8.x branch or it had a random cause (such as a glitch of the network or of a repository).

Closing.
