### ISSUE TITLE
Automatically link devDependency to global module if installed

### ISSUE THREAD

**Issue by smikes** [npm/npm#8149]
This came up on the `#npm` IRC channel, and I wanted to keep a record of it -

```
ZenMaster_: But the workflow I envisioned was: a dev. clones git repo. Runs npm install. globally installed dependencies of suitable versions are not installed locally.
```

Specifically, the goal would be to avoid repeated installation of devdeps if a suitable version were present ~~locally~~ globally.

I theorized that this sort of thing could be looked into as a a post-3.0 feature

**Comment by dnutels** [comment]
@smikes "if a suitable version were present locally" probably should have been "globally", or up-hierarchy.

**Comment by smikes** [comment]
Yes, thanks!

**Comment by othiym23** [comment]
The CLI team's goal with installs is to make them increasingly consistent and self-contained. We envision a time in the not-too-distant future where there's a command like `npm sync` that ensures that what's on disk and what's in `package.json` match, and fixes things up (both ways) when that's not the case. This is a departure in the other direction from that goal, and while it might save some disk space and install time, that's not worth the fact that it makes it harder to know whether an install you have locally matches your colleagues' installs on other machines.

As such, the CLI team isn't going to change npm in this way, so I'm going to close this issue. Developers who are interested in this functionality might want to take a look at [`ied`](http://npm.im/ied) or [`pnpm`](http://npm.im/pnpm) / [`npm-install`](http://npm.im/npm-install), who are experimenting with using centralized package stores and symbolic links in a way somewhat similar to this. Thanks for your time, and your patience!
