### ISSUE TITLE
Errors publishing

### ISSUE THREAD

**Issue by rwwagner90** [npm/npm#8150]
```
Roberts-MBP:ember-shepherd rwwagner$ npm publish
npm ERR! registry error parsing json
```

Something is messed up. I've always had trouble, in some shape or form, publishing this one specific package, but all of my other packages work.

**Comment by smikes** [comment]
Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There is a bad interaction between two known bugs — one in `node@>0.11` and `iojs` and the other in `npm@<2.8.2`.  This can cause ECONNRESET and ETIMEDOUT errors.  The full writeup is here: https://github.com/npm/npm/issues/7699  You can fix this problem by updating your `npm` to the latest.

Thanks!

**Comment by rwwagner90** [comment]
https://gist.github.com/rwwagner90/019e860b74f7ce7cc82c

**Comment by smikes** [comment]
Thanks!  I will ask someone from the registry team to take a look at it.

In the meantime, could you try updating to the latest node (0.12.2) and the latest npm (2.8.4)?  There are a few bugs in node and npm that I would like to avoid hitting...

**Comment by rwwagner90** [comment]
I've upgraded both a few times, as I was having issues publishing before as well. It seemed to fix previous issues, but still left something unresolved. I'll try updating the next time I publish.

**Comment by rwwagner90** [comment]
Seems like this is no longer an issue.
