### ISSUE TITLE
npm ERR! network getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by amanjali** [npm/npm#8151]
![error](https://cloud.githubusercontent.com/assets/12200859/7432977/808e741a-f04a-11e4-8c39-6998cac24b09.jpg)

found  error in installing cordova in window 7, ENOTFOUND getaddinfo
please help...

thanks

**Comment by KenanY** [comment]
@amanjali Should be:

```
$ npm config set https-proxy "..."
```

https://docs.npmjs.com/cli/config

**Comment by amanjali** [comment]
i tried... but still same error

**Comment by smikes** [comment]
Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

Also, could you please attach the results of running

```
npm config get proxy
npm config get https-proxy
```

(Note that the names of `npm` config variables are case-sensitive).

There is a bad interaction between two known bugs — one in `node@>0.11` and `iojs` and the other in `npm@<2.8.2`.  This can cause ECONNRESET and ETIMEDOUT errors.  The full writeup is here: https://github.com/npm/npm/issues/7699  You can fix this problem by updating your `npm` to the latest (see below).

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

Thanks!

**Comment by amanjali** [comment]
C:\Program Files (x86)>cd nodejs

C:\Program Files (x86)\nodejs>npm install npm@latest
'npm' is not recognized as an internal or external command,
operable program or batch file.

C:\Program Files (x86)\nodejs>




face trouble again in updating

**Comment by smikes** [comment]
When you installed `nodejs` , it should have created a shortcut called something like `nodejs command prompt`  -- If you right-click on this and choose "Run as Administrator" then you should be able to use `npm` to install a new version of `npm` as described.

Sorry, I don't use new versions of Windows much, so I don't know where these things get installed.  In Windows 7 or older, it was in the Start Menu under Node.js

**Comment by amanjali** [comment]
i did uninstall and again install node.js and try to update according to your suggestion and still same error

C:\Program Files (x86)\nodejs>npm install npm@latest
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (
x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "npm@latest"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! syscall getaddrinfo

npm ERR! network getaddrinfo ENOTFOUND proxy
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files (x86)\nodejs\npm-debug.log

C:\Program Files (x86)\nodejs>


npm-debug.log


0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'npm@latest' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose node symlink C:\Program Files (x86)\nodejs\\node.exe
5 silly cache add args [ 'npm@latest', null ]
6 verbose cache add spec npm@latest
7 silly cache add parsed spec { raw: 'npm@latest',
7 silly cache add   scope: null,
7 silly cache add   name: 'npm',
7 silly cache add   rawSpec: 'latest',
7 silly cache add   spec: 'latest',
7 silly cache add   type: 'tag' }
8 verbose addNamed npm@latest
9 silly addNamed semver.valid null
10 silly addNamed semver.validRange null
11 info addNameTag [ 'npm', 'latest' ]
12 silly mapToRegistry name npm
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry http://registry.npms.org/
15 silly mapToRegistry uri http://registry.npms.org/npm
16 verbose addNameTag registry:http://registry.npms.org/npm not in flight; fetching
17 verbose request uri http://registry.npms.org/npm
18 verbose request no auth needed
19 info attempt registry request try #1 at 10:44:22 PM
20 verbose request id 345a5e621c930896
21 http request GET http://registry.npms.org/npm
22 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND proxy
23 info attempt registry request try #2 at 10:44:35 PM
24 http request GET http://registry.npms.org/npm
25 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND proxy
26 info attempt registry request try #3 at 10:45:37 PM
27 http request GET http://registry.npms.org/npm
28 verbose stack Error: getaddrinfo ENOTFOUND proxy
28 verbose stack     at errnoException (dns.js:44:10)
28 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)
29 verbose cwd C:\Program Files (x86)\nodejs
30 error Windows_NT 6.1.7601
31 error argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "npm@latest"
32 error node v0.12.2
33 error npm  v2.7.4
34 error code ENOTFOUND
35 error errno ENOTFOUND
36 error syscall getaddrinfo
37 error network getaddrinfo ENOTFOUND proxy
37 error network This is most likely not a problem with npm itself
37 error network and is related to network connectivity.
37 error network In most cases you are behind a proxy or have bad network settings.
37 error network
37 error network If you are behind a proxy, please make sure that the
37 error network 'proxy' config is set properly.  See: 'npm help config'
38 verbose exit [ 1, true ]

**Comment by amanjali** [comment]
@smikes  thank you for helping me..

**Comment by smikes** [comment]
It looks like you are still running with the old version of `npm`:

```
2 info using npm@2.7.4
```

Can you try removing `node 0.12.2` and using the previous version, `0.10.38` ?

**Comment by amanjali** [comment]
@smikes 

results of running

npm config get proxy
npm config get https-proxy

C:\>npm config get proxy
http://proxy:8080/

C:\>npm config get http-proxy
http://proxy:8080

**Comment by amanjali** [comment]
how can i get previous version..?


i am new to nodejs....

**Comment by smikes** [comment]
It's here: https://nodejs.org/dist/v0.10.38/node-v0.10.38-x86.msi

**Comment by amanjali** [comment]
i need to uninstall version 0.12.2 and install 0.12.38....
right

**Comment by smikes** [comment]
Also, when configuring your proxy, you need to substitute the name of your local network's proxy server.  You can find that by inspecting your Internet Settings or by following the suggestions here: https://github.com/npm/npm/issues/7156

**Comment by amanjali** [comment]
i installed older version 

next i try #7156
C:\Users\dell>Get-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVe
rsion\Internet Settings" -Name ProxyServer
'Get-ItemProperty' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\dell>reg query "HKCU\software\microsoft\windows\currentversion\internet
 Settings" /v "ProxyServer"


ERROR: The system was unable to find the specified registry key or value.

C:\Users\dell>npm

Usage: npm <command>

where <command> is one of:
    add-user, adduser, apihelp, author, bin, bugs, c, cache,
    completion, config, ddp, dedupe, deprecate, docs, edit,
    explore, faq, find, find-dupes, get, help, help-search,
    home, i, info, init, install, isntall, issues, la, link,
    list, ll, ln, login, ls, outdated, owner, pack, prefix,
    prune, publish, r, rb, rebuild, remove, repo, restart, rm,
    root, run-script, s, se, search, set, show, shrinkwrap,
    star, stars, start, stop, submodule, t, tag, test, tst, un,
    uninstall, unlink, unpublish, unstar, up, update, v,
    version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm faq          commonly asked questions
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    C:\Users\dell\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@1.4.28 C:\Program Files (x86)\nodejs\node_modules\npm

C:\Users\dell>npm install -g windows-getproxy
npm ERR! network getaddrinfo ENOTFOUND
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program File
s (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "windows-get
proxy"
npm ERR! cwd C:\Users\dell
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! syscall getaddrinfo
npm ERR! code ENOTFOUND

**Comment by amanjali** [comment]
can you please explain me step by step..
after installing older version... 
what next i suppose to do..?

sorry i am giving you trouble..

**Comment by smikes** [comment]
Okay, it looks like you don't have a proxy server configured.  What happens if you try to use the current node (0.10.38) and npm (1.4.28) to install a  package?

```
> npm install -g jshint
> jshint -h 
```

**Comment by amanjali** [comment]
C:\Users\dell>npm install -g windows-getproxy
npm ERR! network getaddrinfo ENOTFOUND
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program File
s (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "windows-get
proxy"
npm ERR! cwd C:\Users\dell
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! syscall getaddrinfo
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\dell\npm-debug.log
npm ERR! not ok code 0

C:\Users\dell>npm install -g jshint
npm ERR! network getaddrinfo ENOTFOUND
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program File
s (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "jshint"
npm ERR! cwd C:\Users\dell
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! syscall getaddrinfo
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\dell\npm-debug.log
npm ERR! not ok code 0

**Comment by amanjali** [comment]
C:\Users\dell>npm install -g jshint
npm ERR! network getaddrinfo ENOTFOUND
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program File
s (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "jshint"
npm ERR! cwd C:\Users\dell
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! syscall getaddrinfo
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\dell\npm-debug.log

**Comment by amanjali** [comment]
how to configure proxy server

**Comment by smikes** [comment]
Proxy servers are set up by your local IT staff, you may need to ask them for this information.

**Comment by amanjali** [comment]
i don't have proxy adders; it that case what should i do...?

**Comment by sahammed** [comment]
You have to check your server administrator or support. They should be able to provide you it. After that set up 

'npm config set http_proxy http://username:password@proxyofmycomp.com:itsport'
'npm config set proxy http://username:password@proxyofmycomp.com:itsport'

If you have any special character try with % urlencode. Eg:- pound(hash) shuold be replaced by %23.

**Comment by haydenhancock** [comment]
I am having a similar issue. Npm was working previously, however, after an update it's no longer working. I am not behind a corporate proxy so that doesn't apply.

**Comment by favoorr** [comment]
OK , I gets the same problem,It's my own fault ,not nodejs or npm

My version is like:

mac os x 10.10.4
node v0.12.7
npm 2.12.1

Just because I use a proxy server for visiting Google, As you konw,I live in china

The core error is the proxy server
For me, I can config a list for control which site use the proxy server or not,

I run command in Iterm before

```
$ npm --registry http://registry.cnpmjs.org info underscore

$ cat ~/.npmrc
registry=http://registry.cnpmjs.org
```

Proxy server list config just like

```
gitter.im # means use proxy server
travis-ci.org
coveralls.io
iojs.org
nodejs.org
npmjs.org
-cnpmjs.org #means not use proxy server
```

After ten minute as config list in use

Then everything is Ok.

Hopes can help you :)

**Comment by larnera** [comment]
If your username is in the format of domain\username, then don't do what I did and forget to encode the \ with %2F. 

Took me ages to figure this out!

**Comment by BernhardSchlegel** [comment]
@larnera Thanks mate, that saved me.

**Comment by xushvai** [comment]
npm config set registry http://registry.npmjs.org/

**Comment by jansanchez** [comment]
First, edit NetworkManager.conf file:
```
vim /etc/NetworkManager/NetworkManager.conf
```

Comment this line:
```
#dns=dnsmasq
```

Finally

```sudo service network-manager restart```
```sudo service docker restart```

**Comment by akashs4** [comment]
I was getting similar error, finally I came to know that there was proxy set in C:\Users\sinakash\.npmrc file, I cleared the file, everything works like it should now.....so happy !!!!

**Comment by Pradeep119** [comment]
may be that version not available in repo. try another one
