### ISSUE TITLE
Blue sky: obfuscate data that's opaque, not meant for end-user consumption

### ISSUE THREAD

**Issue by smikes** [npm/npm#8154]
Just thinking out loud here - what if the shrinkwrap file were `gzip`-ped by default?  Then it would be both a lot smaller and less of an attractive nuisance when people were fiddling things by hand.

Similarly, the metadata that's currently written to the `package.json` of an installed file could be instead written to a dotfile, which would be a gzipped json file that is ignored for purposes of calculating the checksum of an installed package.  (There's a connection here to the eventual goal of having installed packages be immutable and content-addressible).

Just vaguely thinking out loud.

Before:
```
node_modules/A/package.json (modified, contains metadata)
```

After:
```
node_modules/A/package.json (original, immutable)
node_modules/.A-version.md (gzipped json file contains metadata)
```

Now we have some opportunities where `A` might be a symlink or a hardlink to a globally installed package, but we can still track metadata about the context that existed when this particular version of A was chosen as a resolution of the desired semver range.

**Comment by othiym23** [comment]
There are good reasons to have those files be human-readable and human-editable – I think the real issue here is one of evangelism and education. The work we've done to make npm-generated files be more stable across installs is also helpful here. I dunno; I think this is a not-so-great idea for the same reason that security by obscurity is a not-so-good idea. What do you think, @iarna / @kat?

**Comment by iarna** [comment]
I'm... very not keen on having two copies, one fake and one real. I think that would be super confusing.

Further, node DOES read `package.json` (if only to find `main`), and I'm super hesitant to give node a different code path than npm.

I'm not opposed to `npm-shrinkwrap.json.gz` on principle, but my concern would be that without great care (and a hand rolled gzip implementation) the `gz` file will be different every time even when there have been no changes*.

If we view this a communication issue, it wouldn't be difficult to inject a key at the top of both of them warning folks about hand editing the files.

\* Due, I believe, to buffers with uninitialized portions being written to disk. If you have a gzip implementation that clears its buffers after mallocing them, I believe you won't get that churt.

**Comment by othiym23** [comment]
Most of a year later, and my thinking on this is basically unchanged. `npm@3` has made `npm-shrinkwrap.json` closer to idempotent (although there are still inconsistencies that we should address), and the ever-growing ecosystem of third-party tools to munge and fix up shrinkwrap files indicates that being able to operate on shrinkwrap outside the context of the CLI is important to users. Not a bad idea, though, and I completely understand where you were coming from with this. Thanks for filing the feature request, Sam!
