### ISSUE TITLE
Mac OS Error Unable to install any NPM packages

### ISSUE THREAD

**Issue by HardiBhattatWork** [npm/npm#8157]
npm WARN locking Error: EACCES, open '/Users/hardibhatt/.npm/_locks/grunt-3732043049c4c2bf.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/hardibhatt/.npm/_locks/grunt-3732043049c4c2bf.lock failed { [Error: EACCES, open '/Users/hardibhatt/.npm/_locks/grunt-3732043049c4c2bf.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/hardibhatt/.npm/_locks/grunt-3732043049c4c2bf.lock' }
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "grunt"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4

npm ERR! Attempt to unlock /usr/local/lib/node_modules/grunt, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/hardibhatt/Documents/MyFolder/MyWebsite/myWebsite/myWebsite/npm-debug.log

npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', '-g', 'grunt' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 silly cache add args [ 'grunt', null ]
5 verbose cache add spec grunt
6 silly cache add parsed spec { raw: 'grunt',
6 silly cache add   scope: null,
6 silly cache add   name: 'grunt',
6 silly cache add   rawSpec: '',
6 silly cache add   spec: '*',
6 silly cache add   type: 'range' }
7 verbose addNamed grunt@*
8 silly addNamed semver.valid null
9 silly addNamed semver.validRange *
10 silly addNameRange { name: 'grunt', range: '*', hasData: false }
11 silly mapToRegistry name grunt
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry https://registry.npmjs.org/
14 silly mapToRegistry uri https://registry.npmjs.org/grunt
15 verbose addNameRange registry:https://registry.npmjs.org/grunt not in flight; fetching
16 verbose request uri https://registry.npmjs.org/grunt
17 verbose request no auth needed
18 info attempt registry request try #1 at 3:16:59 PM
19 verbose request id 8bb4010b9211588e
20 verbose etag "BRTQUEFFRVDTET76EM5ELXRFA"
21 http request GET https://registry.npmjs.org/grunt
22 http 304 https://registry.npmjs.org/grunt
23 silly get cb [ 304,
23 silly get   { date: 'Fri, 01 May 2015 19:16:59 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     'last-modified': 'Fri, 01 May 2015 19:16:59 GMT',
23 silly get     'cache-control': 'max-age=60',
23 silly get     etag: '"BRTQUEFFRVDTET76EM5ELXRFA"',
23 silly get     age: '56',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-iad2145-IAD',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '1',
23 silly get     'x-timer': 'S1430507819.702494,VS0,VE1',
23 silly get     vary: 'Accept' } ]
24 verbose etag https://registry.npmjs.org/grunt from cache
25 verbose get saving grunt to /Users/hardibhatt/.npm/registry.npmjs.org/grunt/.cache.json
26 silly addNameRange number 2 { name: 'grunt', range: '*', hasData: true }
27 silly addNameRange versions [ 'grunt',
27 silly addNameRange   [ '0.1.0',
27 silly addNameRange     '0.1.1',
27 silly addNameRange     '0.1.2',
27 silly addNameRange     '0.2.0',
27 silly addNameRange     '0.2.1',
27 silly addNameRange     '0.2.2',
27 silly addNameRange     '0.2.3',
27 silly addNameRange     '0.2.4',
27 silly addNameRange     '0.2.5',
27 silly addNameRange     '0.2.6',
27 silly addNameRange     '0.2.7',
27 silly addNameRange     '0.2.8',
27 silly addNameRange     '0.2.9',
27 silly addNameRange     '0.2.10',
27 silly addNameRange     '0.2.11',
27 silly addNameRange     '0.2.12',
27 silly addNameRange     '0.2.13',
27 silly addNameRange     '0.2.14',
27 silly addNameRange     '0.2.15',
27 silly addNameRange     '0.3.0',
27 silly addNameRange     '0.3.1',
27 silly addNameRange     '0.3.2',
27 silly addNameRange     '0.3.3',
27 silly addNameRange     '0.3.4',
27 silly addNameRange     '0.3.5',
27 silly addNameRange     '0.3.6',
27 silly addNameRange     '0.3.7',
27 silly addNameRange     '0.3.8',
27 silly addNameRange     '0.3.9',
27 silly addNameRange     '0.3.10',
27 silly addNameRange     '0.3.11',
27 silly addNameRange     '0.3.12',
27 silly addNameRange     '0.3.13',
27 silly addNameRange     '0.3.14',
27 silly addNameRange     '0.3.15',
27 silly addNameRange     '0.3.16',
27 silly addNameRange     '0.3.17',
27 silly addNameRange     '0.4.0',
27 silly addNameRange     '0.4.1',
27 silly addNameRange     '0.4.2',
27 silly addNameRange     '0.4.3',
27 silly addNameRange     '0.4.4',
27 silly addNameRange     '0.4.5',
27 silly addNameRange     '0.3.13-a',
27 silly addNameRange     '0.4.0-a',
27 silly addNameRange     '0.4.0-rc1',
27 silly addNameRange     '0.4.0-rc2',
27 silly addNameRange     '0.4.0-rc3',
27 silly addNameRange     '0.4.0-rc4',
27 silly addNameRange     '0.4.0-rc5',
27 silly addNameRange     '0.4.0-rc6',
27 silly addNameRange     '0.4.0-rc7',
27 silly addNameRange     '0.4.0-rc8' ] ]
28 verbose addNamed grunt@0.4.5
29 silly addNamed semver.valid 0.4.5
30 silly addNamed semver.validRange 0.4.5
31 silly cache afterAdd grunt@0.4.5
32 verbose afterAdd /Users/hardibhatt/.npm/grunt/0.4.5/package/package.json not in flight; writing
33 verbose afterAdd /Users/hardibhatt/.npm/grunt/0.4.5/package/package.json written
34 silly install resolved [ { name: 'grunt',
34 silly install resolved     description: 'The JavaScript Task Runner',
34 silly install resolved     version: '0.4.5',
34 silly install resolved     author: { name: '"Cowboy" Ben Alman', url: 'http://benalman.com/' },
34 silly install resolved     homepage: 'http://gruntjs.com/',
34 silly install resolved     repository: { type: 'git', url: 'git://github.com/gruntjs/grunt.git' },
34 silly install resolved     bugs: { url: 'http://github.com/gruntjs/grunt/issues' },
34 silly install resolved     licenses: [ [Object] ],
34 silly install resolved     main: 'lib/grunt',
34 silly install resolved     scripts: { test: 'grunt test' },
34 silly install resolved     engines: { node: '>= 0.8.0' },
34 silly install resolved     keywords:
34 silly install resolved      [ 'task',
34 silly install resolved        'async',
34 silly install resolved        'cli',
34 silly install resolved        'minify',
34 silly install resolved        'uglify',
34 silly install resolved        'build',
34 silly install resolved        'lodash',
34 silly install resolved        'unit',
34 silly install resolved        'test',
34 silly install resolved        'qunit',
34 silly install resolved        'nodeunit',
34 silly install resolved        'server',
34 silly install resolved        'init',
34 silly install resolved        'scaffold',
34 silly install resolved        'make',
34 silly install resolved        'jake',
34 silly install resolved        'tool' ],
34 silly install resolved     dependencies:
34 silly install resolved      { async: '~0.1.22',
34 silly install resolved        'coffee-script': '~1.3.3',
34 silly install resolved        colors: '~0.6.2',
34 silly install resolved        dateformat: '1.0.2-1.2.3',
34 silly install resolved        eventemitter2: '~0.4.13',
34 silly install resolved        'findup-sync': '~0.1.2',
34 silly install resolved        glob: '~3.1.21',
34 silly install resolved        hooker: '~0.2.3',
34 silly install resolved        'iconv-lite': '~0.2.11',
34 silly install resolved        minimatch: '~0.2.12',
34 silly install resolved        nopt: '~1.0.10',
34 silly install resolved        rimraf: '~2.2.8',
34 silly install resolved        lodash: '~0.9.2',
34 silly install resolved        'underscore.string': '~2.2.1',
34 silly install resolved        which: '~1.0.5',
34 silly install resolved        'js-yaml': '~2.0.5',
34 silly install resolved        exit: '~0.1.1',
34 silly install resolved        getobject: '~0.1.0',
34 silly install resolved        'grunt-legacy-util': '~0.2.0',
34 silly install resolved        'grunt-legacy-log': '~0.1.0' },
34 silly install resolved     devDependencies:
34 silly install resolved      { temporary: '~0.0.4',
34 silly install resolved        'grunt-contrib-jshint': '~0.6.4',
34 silly install resolved        'grunt-contrib-nodeunit': '~0.2.0',
34 silly install resolved        'grunt-contrib-watch': '~0.5.3',
34 silly install resolved        difflet: '~0.2.3',
34 silly install resolved        semver: '2.1.0',
34 silly install resolved        shelljs: '~0.2.5' },
34 silly install resolved     _id: 'grunt@0.4.5',
34 silly install resolved     dist:
34 silly install resolved      { shasum: '56937cd5194324adff6d207631832a9d6ba4e7f0',
34 silly install resolved        tarball: 'http://registry.npmjs.org/grunt/-/grunt-0.4.5.tgz' },
34 silly install resolved     _from: 'grunt@*',
34 silly install resolved     _npmVersion: '1.4.4',
34 silly install resolved     _npmUser: { name: 'cowboy', email: 'cowboy@rj3.net' },
34 silly install resolved     maintainers: [ [Object], [Object] ],
34 silly install resolved     directories: {},
34 silly install resolved     _shasum: '56937cd5194324adff6d207631832a9d6ba4e7f0',
34 silly install resolved     _resolved: 'https://registry.npmjs.org/grunt/-/grunt-0.4.5.tgz',
34 silly install resolved     readme: 'ERROR: No README data found!' } ]
35 info install grunt@0.4.5 into /usr/local/lib
36 info installOne grunt@0.4.5
37 verbose installOne of grunt to /usr/local/lib not in flight; installing
38 warn locking Error: EACCES, open '/Users/hardibhatt/.npm/_locks/grunt-3732043049c4c2bf.lock'
38 warn locking     at Error (native)
38 warn locking  /Users/hardibhatt/.npm/_locks/grunt-3732043049c4c2bf.lock failed { [Error: EACCES, open '/Users/hardibhatt/.npm/_locks/grunt-3732043049c4c2bf.lock']
38 warn locking   errno: -13,
38 warn locking   code: 'EACCES',
38 warn locking   path: '/Users/hardibhatt/.npm/_locks/grunt-3732043049c4c2bf.lock' }
39 verbose stack Error: Attempt to unlock /usr/local/lib/node_modules/grunt, which hasn't been locked
39 verbose stack     at unlock (/usr/local/lib/node_modules/npm/lib/utils/locker.js:66:11)
39 verbose stack     at cb (/usr/local/lib/node_modules/npm/lib/install.js:1004:5)
39 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:1008:20
39 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/locker.js:40:9
39 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
39 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
39 verbose stack     at FSReqWrap.oncomplete (fs.js:95:15)
40 verbose cwd /Users/hardibhatt/Documents/MyFolder/MyWebsite/myWebsite/myWebsite
41 error Darwin 14.3.0
42 error argv "node" "/usr/local/bin/npm" "install" "-g" "grunt"
43 error node v0.12.2
44 error npm  v2.7.4
45 error Attempt to unlock /usr/local/lib/node_modules/grunt, which hasn't been locked
46 error If you need help, you may report this error at:
46 error     <https://github.com/npm/npm/issues>
47 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@HardiBhattatWork It looks like you current user account does not have the necessary permissions to read/write to `npm`'s cache directory. Could you try fixing the permissions?:

``` sh
$ sudo chown -R $(whoami) "$HOME/.npm
```

**Comment by HardiBhattatWork** [comment]
Thank you! This was the solution! I appreciate your help!

**Comment by zhe** [comment]
It worked! Thanks @KenanY !

**Comment by KenanY** [comment]
@zhe Whoops, good catch! I've edited my comment :)

**Comment by F3ryC** [comment]
Thanks, KenanY!  

I encountered similar issue on a different project/work, but nevertheless your solution helped me.
