### ISSUE TITLE
Initial publish of scoped package error message when leaving out --access=public should suggest to add --access=public

### ISSUE THREAD

**Issue by Havvy** [npm/npm#8161]
Sorry for the long issue name.

```
npm ERR! publish Failed PUT 402
npm ERR! Linux 3.14.33
npm ERR! argv "/nix/store/y0wqn1gvdhnjjadndra60rskg4snhb3q-iojs-1.3.0/bin/iojs" "/home/havvy/.nix-profile/bin/npm" "publish"
npm ERR! node v1.3.0
npm ERR! npm  v2.5.1
npm ERR! code E402

npm ERR! you need a paid account to perform this action. For more info, visit: https://www.npmjs.com/private-modules : @user%2fmodule-name
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/havvy/tennu/mock-net-socket/npm-debug.log
```

The error says you need a paid account to perform this action, but that's not strictly true. You can also do it if you pass `access=public`, but the error message doesn't suggest that. It should suggest that, so as to not confuse people into thinking it is a premium only feature.

**Comment by othiym23** [comment]
This is actually an issue for the registry team, as that error message is coming from there. They're doing a sweep on these error messages, so I'll raise the issue with them.

(The tl;dr for why we default to private is that we absolutely do not want to make it easy for people to accidentally publish a private module to the public on accident. I think tweaking that error message to suggest that you can set access to public on publish is a very useful usability tweak, though, so thanks for filing this issue!)

**Comment by kyleect** [comment]
I am running in to this issue. I'm specifying that its public but still getting this error: 

> $ npm publish --access public
> npm ERR! publish Failed PUT 402
> npm ERR! Windows_NT 10.0.10586
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "publish" "--access" "public"
> npm ERR! node v6.0.0
> npm ERR! npm  v3.8.6
> npm ERR! code E402
> 
> npm ERR! You need a paid account to perform this action. For more info, visit: https://www.npmjs.com/private-modules : @maexsoftware/datastore
> npm ERR!
> npm ERR! If you need help, you may report this error at:
> npm ERR!     <https://github.com/npm/npm/issues>
> 
> npm ERR! Please include the following file with any support request:
>

**Comment by ragusource** [comment]
I am also experiencing the same issue:

$ pwd
/Users/rrajaratnam/Documents/development/sourcier/collections
rrajaratnam at Rogers-MacBook-Pro in ~/Documents/development/sourcier/collections on develop*
$ npm publish --access public
npm ERR! publish Failed PUT 402
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node/5.9.0/bin/node" "/usr/local/bin/npm" "publish" "--access" "public"
npm ERR! node v5.9.0
npm ERR! npm  v3.7.3
npm ERR! code E402

npm ERR! You need a paid account to perform this action. For more info, visit: https://www.npmjs.com/private-modules : @sourcier/collections
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rrajaratnam/Documents/development/sourcier/collections/npm-debug.log

**Comment by ragusource** [comment]
@kyleect the solution in this ticket worked for me: https://github.com/npm/npm/issues/12168

**Comment by slavafomin** [comment]
I had no knowing about `--access=public` modifier and tried to push my package to the organization at least five times. It would be very useful to update the error message to make it more clear.

**Comment by capaj** [comment]
I had to google this thread to know how to publish a public scoped package. A suggestion in the error would be nice.
