### ISSUE TITLE
Set own output status for EPEERINVALID errors

### ISSUE THREAD

**Issue by piranna** [npm/npm#8164]
When an EPEERINVALID occurs, at this moment npm exits with a [generic output status error of 1](https://github.com/npm/npm/blob/d975aa08da5f0b473be008a298436e33625d2ac8/lib/utils/error-handler.js#L363) since the EPEERINVALID error [don't include a errno field](https://github.com/npm/npm/blob/d975aa08da5f0b473be008a298436e33625d2ac8/lib/install.js#L125-L130). I propose to add to the EPEERINVALID an errno field (not only a code) so the output status can be used to identify the problem.

Also, it would be good to have a file where to have listed all the errors codes and numbers so they don't get duplicated.

**Comment by othiym23** [comment]
This isn't an unreasonable request, but time has passed it by. `npm@3` no longer treats `peerDependency` validation failures as errors, so now it just prints out the warning and exits with status code 0.

> Also, it would be good to have a file where to have listed all the errors codes and numbers so they don't get duplicated.

Error handling is distributed across npm, and would be pretty difficult to standardize in the way you suggest. That said, a lot of the existing error handling is located in https://github.com/npm/npm/blob/master/lib/utils/error-handler.js, which also standardizes several categories of error message output. We're also increasingly interested in localizing npm, and that will probably bring with it at least standardized usage of a something like `intl.js`'s `messageFormat`, but that's still a ways away from having all of the error messages centralized. We plan to do a usability overhaul of the CLI towards the end of this year, and it may very well turn out that we include something like this as part of cleaning up error handling in general.

For now, I'm going to close this issue. Thanks for your time!
