### ISSUE TITLE
Cannot read property 'dependencies' of undefined

### ISSUE THREAD

**Issue by OwenMelbz** [npm/npm#8166]
I contacted the gruntjs team already via their issue tracker and posted a support issue with them, however they've 'kindly' passed me on, so was hoping somebody here would be able to shed some light on this issue and point me into the direction of some success.

The original issue is here https://github.com/gruntjs/grunt-contrib-imagemin/issues/300 

but for you guys here i'll re-attach hoping to get  solution.

---

I'm currently having issues installing this with the command

`npm install grunt-contrib-imagemin --save-dev`

my package.json looks like

``` json
{
  "name": "fatfriday",
  "version": "0.1.0",
  "description": "selesti fat friday internal project",
  "main": "Gruntfile.js",
  "scripts": {
    "test": "hi"
  },
  "repository": {
    "type": "git",
    "url": "git+https://owenmelbz@bitbucket.org/owenmelbz/fatfriday.git"
  },
  "author": "",
  "license": "ISC",
  "homepage": "https://bitbucket.org/owenmelbz/fatfriday#readme",
  "devDependencies": {
    "grunt": "^0.4.5",
    "grunt-autoprefixer": "^3.0.0",
    "grunt-browser-sync": "^1.9.2",
    "grunt-contrib-concat": "^0.5.1",
    "grunt-contrib-cssmin": "^0.12.2",
    "grunt-contrib-jshint": "^0.11.2",
    "grunt-contrib-less": "^1.0.1",
    "grunt-contrib-uglify": "^0.9.1",
    "grunt-contrib-watch": "^0.6.1",
    "grunt-newer": "^1.1.0",
    "grunt-notify": "^0.4.1",
    "matchdep": "^0.3.0"
  }
}
```

I've attached my `npm-debug.log` incase you can spot the issue [http://owenmelbourne.com/npm-debug.log](http://owenmelbourne.com/npm-debug.log)

Running `OSX Yasomite 10.10.3 (14D136)`

Help would be much appreciated! thank you

**Comment by smikes** [comment]
I think this is a bug in `npm`, and I think you might be able to fix it by updating npm:

```
sudo npm i -g npm@next
```

Normally I would send you to `npm@latest` but in this case I think you really want the bleeding-edge version.  Please try that and let me know if it helps.

Thanks!

**Comment by shakeelmohamed** [comment]
+1

**Comment by shakeelmohamed** [comment]
@smikes your solution didn't help either :(

**Comment by OwenMelbz** [comment]
@smikes I also tried your suggestion on a clean install and it made no difference :(

is there anyway around this for the time being? like to manually download the package and drop inside node_modules folder?

**Comment by smikes** [comment]
Thanks for reporting this bug!

Can you upload the `npm-debug.log` from the latest `npm`? (I like gist : https://gist.github.com , but pastebin or whatever else also works).  It will be easier to figure out what's going wrong from a stack trace that corresponds to the current `npm` code.

@shakeelmohamed Does this happen for you with grunt-contrib-imagemin, or with another package?

I can reproduce the problem with `npm@2.9.0` and grunt-contrib-imagemin; I will see if I can figure out the cause.

**Comment by smikes** [comment]
Here is a `loglevel=silly` (very long) version of the `npm-debug.log` showing the failure on `node@0.10.38` , `npm@2.9.0` https://gist.github.com/smikes/a615ddfc542c32e8ea53

**Comment by othiym23** [comment]
Wow. This sucks. Node.js 0.12.2 and io.js 1.8.1 both perform the steps listed in the original post flawlessly and repeatably, but Node 0.10.38 blows up, which means that something somewhere in npm's dependencies is depending on a behavior specific to new Node. I have no idea what it could be, although I suspect it's something in the guts of the streams code, or potentially the `child_process` code, but that's not backed up by anything substantive. This has to get fixed, obviously, but it's going to be a little while until I have the cycles to look into this more deeply, so if somebody else wants to figure out a minimal repro case for this, I'd be forever in their debt.

**Comment by othiym23** [comment]
I'll be darned -- `readDependencies` in `lib/install.js` isn't handling its error, which in this case turns out to be an `EMFILE`, so either something isn't using `graceful-fs` properly, or `graceful-fs` is busted under Node 0.10. I'll dig for a little while longer, because this is bizarre.

**Comment by othiym23** [comment]
_<colorful, anachronistic profanity>_ So it turns out this is definitely a ulimit thing, as well as a difference between Node.js 0.10 and Node.js 0.12 / io.js – I ran `ulimit -n` and found out that the number of open files was 256 again (because that is the default in OS X 10.10.3+ for obscure, Apple-related reasons). When I boost that to 2560 (`ulimit -n 2560`), the install runs without problems. So this is a bad interaction between Node 0.10, Apple's bonkers ulimit defaults, and `graceful-fs`. @isaacs, do you have any ideas what could cause this?

**Comment by othiym23** [comment]
Also, trying to handle the error in `readDependencies` turns into a catastrophic cascade of doom that ultimately results in a `cb() not called` before the rollback even starts. I _think_ this is due to how the fallback logic in the `npm@2` installer works, because there are several places where on error, `readdir` gets called anyway, which is going to fail when Node is stuck in `EMFILE` hell. Either way, capturing the underlying error so that we can tell poor users what's happening to them here is a tricky challenge that will have to wait for another day.

**Comment by OwenMelbz** [comment]
It's great to see a community who actually care about fixing issues for people! It's much appreciated!

So from what I can tell, Windows and Linux users are unaffected as it's an OSX quirk.

As a work around to install the package you must increase the ulimit as @othiym23 details

**Comment by vladikoff** [comment]
Also hitting this issue on 

```
npm: '2.9.1',
  ares: '1.9.0-DEV',
  http_parser: '1.0',
  modules: '11',
  node: '0.10.38',
  openssl: '1.0.1m',
  uv: '0.10.36',
  v8: '3.14.5.9',
  zlib: '1.2.8'
```

Running `ulimit -n 2560` seems to help!

**Comment by bartekn** [comment]
`npm cache clean` fixed this issue for me.

**Comment by rosskukulinski** [comment]
FYI @othiym23, someone on my team ran into this today.

**Comment by othiym23** [comment]
This has been moved to the [npm roadmap](https://github.com/npm/npm/wiki/Roadmap), which we're using instead of the confusing `next-*` labels now.
