### ISSUE TITLE
Could not load the Visual C++ component "VCBuild.exe".

### ISSUE THREAD

**Issue by adriatic** [npm/npm#8169]
I get to see this problem daily and do not see the reason why it remains unfixed. Here is the complete error message
```
C:\Users\Nikolaj\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-agent {git}   
{lamb} node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node
-gyp\bin\node-gyp.js" rebuild                                                                  
child_process: customFds option is deprecated, use stdio instead.                              
Building the projects in this solution one at a time. To enable parallel build, please add the 
"/m" switch.                                                                                   
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1 
) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the lo 
cation of the component to the system path if it is installed elsewhere.  [C:\Users\Nikolaj\Ap 
pData\Roaming\npm\node_modules\strongloop\node_modules\strong-agent\build\binding.sln]         
gyp ERR! build error    
```
Obviously it is not reasonable to expect that anyone would have Visual Studio 2005 handy 10 years after it was published.

As a result of this problem I have to use the JavaScript version of BSON instead of the compiled C++ version. This in itself is not a big issue, I care more about not seeing a river of red error messages shown at most `npm install` commands

**Comment by smikes** [comment]
Thanks for reporting this.

Can you tell me which version of `npm` you are using?

Do you have a C++ compiler installed on this computer?  I believe node-gyp is supposed to work with newer versions of Visual C++ as well, but it might be that the version of `node-gyp` you have installed is out of date...

**Comment by adriatic** [comment]
Hi Sam

I have node-gyp version 0.12.0 – do not remember which of my actions resulted in its installation. So, I did a little bit more research and found that whenever node-gyp is used on Windows to build some C++ code (BSON in my case, but it could be a lot of different targets) node-gyp's reference to VC++ compiler (msbuild actually) it is often referring to a non-existing msbuild version. In my case, the node-gyp was so old that it expected to find the msbuild component that was shipped with Visual Studio 2005. 

The proper solution to address this is to add the "smarts" to node-gyp to warn the user how to change its (node-gyp's reference to msbuild. The manual fix is this:

`npm config set msvs_version 20xx --global`

where `xx` stands for the last 2 digits of the Visual Studio version installed on user's system. In my case this command is `npm config set msvs_version 2013 --global`

A safer (and mode complicated) way is to first ensure that you have the latest version of node-gyp installed, expecting that this version would also have the reference to the latest version of the Visual Studio. Such approach is described in [this post](https://github.com/TooTallNate/node-gyp/wiki/Updating-npm%27s-bundled-node-gyp) - and if the user has the older version of Visual Studio installed, use the above mentioned method `npm config set msvs_version 20xx --global`.

Hope it helps

**Comment by smikes** [comment]
Thanks for following up.

**Comment by aivonix** [comment]
Hello there, 
Thank you very much for this post, it gave me a light of hope. But for me it did not solve the issue as the package installer still have a river of red messages displaying in the console. They are of the type *code is not working with itself well* . 

I tried your line of code: 
> npm config set msvs_version 2013 --global
But it yielded the same result as adding an environment variable for PYTHON

Software that got me here:
> npm --version : 3.3.6
> node --version: v.5.0.0
> MS VS 2012 express

At the end, I solved it with downgrading to node 4.2.2

**Comment by jalasem** [comment]
wow!
cant believe this solved the problem
thanks

**Comment by adriatic** [comment]
The approach to fix this is simply flawed - we should not try to mix and match components in order to make unnecessary error messages go away. In particular, **having** to downgrade node seems outright silly.

@smikes is there any ongoing effort to get this years old issue under control?

**Comment by abdufarag** [comment]
npm install --global --production windows-build-tools
No need for Visual Studio. This has what you need.
