### ISSUE TITLE
npm fetch errors

### ISSUE THREAD

**Issue by prashathsenthil** [npm/npm#8176]
Hi,

In our release builds we are facing a number of npm fetch related errors. Any idea on how it can be resolved?

When a http was made to grunt-contrib-clean it results in 403 and throws the following errors in log, the node version was v0.10.18 and npm version is 1.3.8
```
[INFO] npm http 403 https://xxxx.xxxx.com/content/groups/level0.npm/grunt-contrib-clean
[INFO] npm ERR! registry error parsing json
[INFO] npm ERR! Error: failed to fetch from registry: grunt-contrib-clean
[INFO] npm ERR!     at RegClient.<anonymous> (/bld/workspace/.....npm/node_modules/npm-registry-client/lib/get.js:134:18)
[INFO] npm ERR!     at cb (/bld/workspace/....npm/node_modules/npm-registry-client/lib/request.js:27:9)
[INFO] npm ERR!     at RegClient.<anonymous> (/bld/workspace/...npm/node_modules/npm-registry-client/lib/request.js:148:10)
[INFO] npm ERR!     at cb (/bld/workspace..../node/npm/node_modules/npm-registry-client/lib/request.js:158:9)
[INFO] npm ERR!     at RegClient.<anonymous> (/bld/workspace..../node/npm/node_modules/npm-registry-client/lib/request.js:243:16)
[INFO] npm ERR!     at Request.self.callback (/bld/workspace..../node/npm/node_modules/request/index.js:148:22)
[INFO] npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
[INFO] npm ERR!     at Request.<anonymous> (/bld/workspace..../node/npm/node_modules/request/index.js:891:14)
[INFO] npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
[INFO] npm ERR!     at IncomingMessage.<anonymous> (/bld/workspace..../node/npm/node_modules/request/index.js:842:12)
[INFO] npm ERR! If you need help, you may report this log at:
[INFO] npm ERR!     <http://github.com/isaacs/npm/issues>
[INFO] npm ERR! or email it to:
[INFO] npm ERR!     <npm-@googlegroups.com>
[INFO] 
[INFO] npm ERR! System Linux 2.6.32-431.el6.x86_64
[INFO] npm ERR! command "/bld/workspace.../node/node" "/bld/workspace.../node/npm/bin/npm-cli.js" "install" "--color=false" "--https-proxy=http://http.proxy.xxx.com:8000"
[INFO] npm ERR! cwd /bld/workspace..../client
[INFO] npm ERR! node -v v0.10.18
[INFO] npm ERR! npm -v 1.3.8
```

**Comment by KenanY** [comment]
@prashathsenthil `npm@1.3.8` is very old and no longer supported since months ago. Is it possible that you could [upgrade](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) first?

**Comment by prashathsenthil** [comment]
@KenanY Sure thing will give a try in the Linux box.

**Comment by prashathsenthil** [comment]
@KenanY what version of node and npm is recommended? Because we are using many node packages and some of them might not work with the bleeding edge version of node and npm. Currently we are using node (v0.10.18) npm (1.3.8). I went ahead and updated the version of node (v0.12.2) npm(2.9.0) but in the log i could see the below,

wanted: {"node":"~0.8 || ~0.10"} (current: {"node":"0.12.2","npm":"2.9.0"})

Also i'm installing node and npm via frontend-maven-plugin (v0.0.23) and the configuration resides in POM.XML

**Comment by KenanY** [comment]
@prashathsenthil _Generally_ those warnings can be ignored; depends on the package really. If the package does not work with 0.12.2 you can always install 0.10.38 instead. Recommended `npm` is the latest stable release (which at the moment is `2.9.0`).

**Comment by prashathsenthil** [comment]
cool thank you @KenanY

**Comment by othiym23** [comment]
Closing as resolved.
