### ISSUE TITLE
new to ember, just following installation instruction, npm install -g phantomjs

### ISSUE THREAD

**Issue by dkipnis** [npm/npm#8181]
C:\Users\Dima\AppData\Roaming\npm\phantomjs -> C:\Users\Dima\AppData\Roaming\npm
\node_modules\phantomjs\bin\phantomjs

> phantomjs@1.9.16 install C:\Users\Dima\AppData\Roaming\npm\node_modules\phanto
mjs
> node install.js

'node' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (
x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "phantomjs"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.16 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (
x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "phantomjs"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4

npm ERR! Uncaught, unspecified "error" event.
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files (x86)\nodejs\npm-debug.log

**Comment by pivotal-topher-bullock** [comment]
Ensure you have installed node correctly for all users, and that you can run ``node -v`` from the Windows Command Prompt.

If that doesn't work, try these steps and run ``node -v`` in Windows Command Prompt after each : 
1. restart the machine you are trying to run the command on and try again.
2. ensure that the 'PATH' variable has 'C:\Program Files\nodejs' (or similar, depending on where you have installed Node) been set in "System variables" and "User Variables" ( Control Panel -> System and Security -> System -> Advanced System Settings -> Environment Variables )

**Comment by dkipnis** [comment]
Thanks for advise, adding path resolved the issue.


Following installation verification, created new project "ember new my-app", "cd my-app", "ember server", which generated new error message:


ember server
version: 0.2.3
Cannot find module 'ember-cli/lib/broccoli/ember-app'
Error: Cannot find module 'ember-cli/lib/broccoli/ember-app'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\Dima\my-app\Brocfile.js:3:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17) 


Thanks.

**Comment by dkipnis** [comment]
Required Git installation and reboot after each install to update system path
