### ISSUE TITLE
Trying to install Karma on OS X Yosemite with node v0.10.36

### ISSUE THREAD

**Issue by udon3** [npm/npm#8190]
Hi,
I installed this earlier version (0.10.36) of node so that I could install Karma. But I'm still getting errors:

	14 error Darwin 14.3.0
	15 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "karma"
	16 error node v0.10.36
	17 error npm  v2.5.1
	18 error must pass params to get

Does this look or sound familiar to anyone? 
I'm on a Mac running OS X Yosemite, it's the first time I set up a dev environment on a Mac - I would appreciate any advice in the right direction!

Many thanks in anticipation

**Comment by smikes** [comment]
Thanks for opening this issue.

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially involving git dependencies -- since 2.5. Can you try updating your npm installation?

To update npm, run `sudo npm -g install npm@latest`.

Thanks!

**Comment by udon3** [comment]
Thanks for your reply - I just tried installing again today (in node v 0.12), and it worked! Strange though, as at the time of raising this issue, I read that I needed to be running an earlier version of node - now of course, I can't find that info!

**Comment by smikes** [comment]
I'm glad it's working, anyway.  The 0.12 versions of node are still quite new, so some people feel that 0.10 versions should be used.  However, whichever version of node you're using, the latest version of `npm` is usually the right choice.  `npm@2.9.1` works with node 0.8, 0.10, 0.12, and all versions of io.js

**Comment by udon3** [comment]
Thanks, I think it was the npm version update that got me through, but also I noticed I do sometimes still forget the 'sudo' command (Mac newbie!).

Just to clarify for the benefit of anyone coming across this thread: There *was* a warning regarding node version when installing Karma on node v 0.12 : `npm WARN engine karma-cli@0.0.4: wanted: {"node":"~0.8 || ~0.10"} (current: {"node":"0.12.0","npm":"2.9.1"})`, but both karma-CLI and karma installed ok (I'm just starting out, but can confirm the `karma` commands are running).
