### ISSUE TITLE
npm install remote-git-tags

### ISSUE THREAD

**Issue by Archiolidius** [npm/npm#8191]
```
Error: Bad Request
npm ERR! at errorResponse (/usr/lib/node_modules/npm/lib/cache/add-named.js:260:10)
npm ERR! at /usr/lib/node_modules/npm/lib/cache/add-named.js:203:12
npm ERR! at saved (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR! at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this entire log,
npm ERR! including the npm and node versions, at:
npm ERR! http://github.com/npm/npm/issues
```

**Comment by KenanY** [comment]
> npm ERR! If you need help, you may report this **entire** log,

Node.js version? `npm` version? System/OS information? `npm-debug.log` as a [gist](https://gist.github.com/)? Stack trace is basically _never_ enough to diagnose an issue.

https://github.com/npm/npm/wiki/Contributing-Guidelines#a-great-bug-report-contains

**Comment by Archiolidius** [comment]
It was problem with my local npm configuration.
