### ISSUE TITLE
error reading version SyntaxError: Unexpected token }

### ISSUE THREAD

**Issue by vladberteanu** [npm/npm#8194]
When one of our users is trying to install globally the [talentbuddy](https://www.npmjs.com/package/talentbuddy) package on Windows 8.1 he gets the following npm error.

```
0 info it worked if it ends with ok
1 info error reading version SyntaxError: Unexpected token }
1 info error reading version     at Object.parse (native)
1 info error reading version     at C:\Program Files\nodejs\node_modules\npm\lib\npm.js:44:16
1 info error reading version     at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\npm.js:469:3)
1 info error reading version     at Module._compile (module.js:460:26)
1 info error reading version     at Object.Module._extensions..js (module.js:478:10)
1 info error reading version     at Module.load (module.js:355:32)
1 info error reading version     at Function.Module._load (module.js:310:12)
1 info error reading version     at Module.require (module.js:365:17)
1 info error reading version     at require (module.js:384:17)
1 info error reading version     at C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js:23:11
```

The command to install the package was `npm install -g talentbuddy`

Surprisingly,  when running `npm install -g jsonfile` no error is thrown.

It looks like the error is thrown when npm is trying to read its own version [here](https://github.com/npm/npm/blob/master/lib/npm.js#L46).

Can you please advise if this is an npm issue?

Thank you!

**Comment by KenanY** [comment]
@vladberteanu `npm --version`?

**Comment by othiym23** [comment]
My guess is that you are

1. using an older version of npm, and
2. have something awry in your project's `package.json` file, like a missing `"`

Newer versions of npm include a more forgiving JSON parser that will at least tell you where to look for syntax errors, but for now, try running something like [`jsonlint`](http://npm.im/jsonlint) on `package.json` and make sure that it runs without errors.

**Comment by vladberteanu** [comment]
`npm --version` was throwing the same error. I asked the user to reinstall node & npm, this time the 64bit version and it worked well.

Thanks for your support!
