### ISSUE TITLE
npm run "note" goes to stdout instead of logstream

### ISSUE THREAD

**Issue by glenjamin** [npm/npm#8200]
As seen in:
https://github.com/npm/npm/blob/master/lib/utils/lifecycle.js#L163

This seems to have changed relatively recently, as on a project using an older npm I was able to do:
```sh
npm run command-that-outputs-xml > filename.xml
```

But in npm 2.7.4 (shipped with 0.12.2) and 2.9.0 (latest) the output goes to stdout

```
npm run lint -- -f checkstyle . 2>/dev/null

> identity-webapp@1.0.0 lint /Volumes/SkyBet/italy/identity-webapp
> eslint . "-f" "checkstyle" "."

<?xml version="1.0" encoding="utf-8"?><checkstyle version="4.3"><file name="test/basic-test.js"></file><file name="test/basic-test.js"></file></checkstyle>
```

**Comment by othiym23** [comment]
I think you're looking for `npm run --silent`, which will suppress that banner. As far as I know, that banner has _always_ gone to stdout, and has never been handled by the logging subsystem.

**Comment by glenjamin** [comment]
Ah, I've compared my older version more closely, and realised I wasn't quite doing the shell pipes in the same place.

However, I still think it would be useful to move the banner into the log subsystem, or at least to `stderr` - otherwise it's impossible to capture structured output cleanly from `npm run-script`. The banner is effectively debugging output, so `stderr` seems apt to me.

`npm run --silent` isn't desirable, as that swallows all the useful debugging and error output.

My workaround at the moment is:
```sh
npm run test | tee >(tail -n +4 > destination.xml)
```

This allows me to keep the banner in my console, but drop it inside the file.
