### ISSUE TITLE
statsd module installation fails on nodejs-0.12 because of node-syslog@1.1.7 dependency

### ISSUE THREAD

**Issue by bigunyak** [npm/npm#8204]
Hi there,

It seems the statsd module wouldn't install on nodejs-0.12 because of hardcoded dependency for node-syslog@1.1.7 which fails to install on nodejs-0.12. Seems the problem with node-syslog was fixed recently and the new npm module v1.2.0 is already available for it which installs on nodejs-0.12 with no problems.
Can you update this dependency for statsd module?

Thanks,
Dmitry

**Comment by KenanY** [comment]
@bigunyak Hello! This issue tracker is for bugs and feature requests for the `npm` CLI. If you'd like the `statsd` module to update the dependency, you should ask them over at [their issue tracker](https://github.com/etsy/statsd) :)

**Comment by bigunyak** [comment]
Ah, pardon me, I thought you guys also responsible for the modules. :)
Closing then.
