### ISSUE TITLE
Fresh npm and iojs install on Mac causes ENOTSUP error on first npm call

### ISSUE THREAD

**Issue by binarykitchen** [npm/npm#8209]
The title says it. Just installed a new Mac machine.

In the home folder, I just did this:

```
$ npm
Error: ENOTSUP: operation not supported on socket, mkdir '/home/michael-heuberger'
    at Error (native)
```

No idea what it means and what's missing.

```
$ npm -v
2.7.5

$ iojs -v
v1.8.1
```

**Comment by binarykitchen** [comment]
Never mind, I found the cause. A bad path in the .npmrc config file. But wish npm would give me a better warning ...

**Comment by othiym23** [comment]
I'm not really sure how npm would give you a better error message in that case, as this is something that appears to be a Node call failing somewhere deep in the guts of libc (`ENOTSUP` isn't an error I see very commonly).

Either way, closing as resolved.
