### ISSUE TITLE
install API closes over installation results

### ISSUE THREAD

**Issue by bendrucker** [npm/npm#8216]
`npm.install` closes over the `installed` object

https://github.com/npm/npm/blob/048aca3ee3c977e21db21a1c63ad2f9501d11e99/lib/install.js#L998

This means that calling `npm.install` and then `npm.uninstall` inside the same process doesn't work as expected since the state of `installed` doesn't reflect `npm.uninstall` calls

**Comment by othiym23** [comment]
All of this code is going to change very soon in `npm@3`, but even then, the CLI's API is meant for use by the CLI only, and we make no guarantees for its fitness for use for any other purpose. We're very slowly working towards a better long-term solution, which is breaking the CLI up into a set of components that fulfill its various roles, and which _will_ have their own semver-versioned APIs. Until then, the right thing to do is to drive npm from the command line if you want to do a set of installs and then uninstalls.

**Comment by bendrucker** [comment]
Fair enough!
