### ISSUE TITLE
Publishing scoped packages - authentication issues

### ISSUE THREAD

**Issue by charlierudolph** [npm/npm#8217]
Was trying to publish a scoped package to a privately hosted npm registry and ran into a ENEEDAUTH.
I thought my `.npmrc` would be sufficient in specifying the host with

```
@myorg:registry=http://my.host/
```

Looking at the silly level of logging, it appeared to correctly determine where to publish to without me setting the `publishConfig` in my `package.json`.

However I just kept getting the error 

```
npm ERR! code ENEEDAUTH

npm ERR! need auth auth required for publishing
npm ERR! need auth You need to authorize this machine using `npm adduser`
```

I thought this was a permissions error with my host and it ended up being cause by this [code](https://github.com/npm/npm/blob/master/lib/config/get-credentials-by-uri.js), which ignored the `_auth` option I supplied because the scope registry and my publish config did not match. 

I originally wanted to ask for an warning / error message anytime my "_auth" token is thrown away (due to the uri and registry being different), but can now see where this would be harder to deal with due to global config. Overall I think just more documentation on scoped packages and how to properly deal with authentication would be very valuable.

**Comment by smikes** [comment]
Thanks for reporting this.

**Comment by hulvei3** [comment]
:+1: I may have a related issue.

On our CI-machines we have a global .npmrc file with read/write access to our private npm hosting. But we also have a per-project .npmrc with read-only access to allow devs installing dependencies without having the need to setup each dev account. In the docs it is stating that "It (the per-project .npmrc) has no effect when your module is published.".

But every time I try to `npm publish` it reads from the project .npmrc file and then gets a `code ENEEDAUTH` like @charlierudolph gets - logical enough, but inconsistent with the docs!
