### ISSUE TITLE
trim

### ISSUE THREAD

**Issue by danish575** [npm/npm#8220]
![error](https://cloud.githubusercontent.com/assets/12373804/7551211/2ee97808-f635-11e4-82bc-645ebb0a65a5.png)
this error occurred..
Pakage url: https://github.com/anodejs/node-sharp
Pakage.json url: https://github.com/anodejs/node-sharp/blob/master/package.json

**Comment by danish575** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'git+ssh://git@github.com/anodejs/node-sharp.git' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 silly cache add args [ 'git+ssh://git@github.com/anodejs/node-sharp.git', null ]
6 verbose cache add spec git+ssh://git@github.com/anodejs/node-sharp.git
7 silly cache add parsed spec { raw: 'git+ssh://git@github.com/anodejs/node-sharp.git',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: 'git+ssh://git@github.com/anodejs/node-sharp.git',
7 silly cache add   spec: 'git+ssh://git@github.com/anodejs/node-sharp.git',
7 silly cache add   type: 'hosted',
7 silly cache add   hosted:
7 silly cache add    { type: 'github',
7 silly cache add      ssh: 'git@github.com:anodejs/node-sharp.git',
7 silly cache add      sshUrl: 'git+ssh://git@github.com/anodejs/node-sharp.git',
7 silly cache add      httpsUrl: 'https://github.com/anodejs/node-sharp.git',
7 silly cache add      directUrl: 'https://raw.githubusercontent.com/anodejs/node-sharp/master/package.json' } }
8 info maybeGithub Attempting git+ssh://git@github.com/anodejs/node-sharp.git from git://github.com/anodejs/node-sharp.git
9 verbose addRemoteGit git-github-com-anodejs-node-sharp-git-72fb63f4 not in flight; caching
10 verbose stack TypeError: Cannot read property 'trim' of undefined
10 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\cache\add-remote-git.js:98:31
10 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\utils\git.js:50:14
10 verbose stack     at F (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:40:25)
10 verbose stack     at E (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:43:29)
10 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:54:16
10 verbose stack     at FSReqWrap.oncomplete (fs.js:95:15)
11 verbose cwd D:\wamp\www\node\node-sharp-master
12 error Windows_NT 6.3.9600
13 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "git+ssh://git@github.com/anodejs/node-sharp.git"
14 error node v0.12.2
15 error npm  v2.7.4
16 error Cannot read property 'trim' of undefined
17 error If you need help, you may report this error at:
17 error     <https://github.com/npm/npm/issues>
18 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@danish575 Does this also occur if you [upgrade](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows) to the latest stable release of `npm`?

**Comment by KenanY** [comment]
@danish575 ping?

**Comment by othiym23** [comment]
Closing as abandoned. There were some problems with the git support in `npm@2.7.4` that led to this failure; if you're still seeing this, @KenanY's advice to try upgrading is sound.
