### ISSUE TITLE
Separate userconfig from .npmrc

### ISSUE THREAD

**Issue by watilde** [npm/npm#8223]
Recently my npm config settings has increased and I'd like to sync settings with some PC. However, because there are some values like _auto and _token, it cannot publish settings as .dotfile if it separate that value with something like include / import. I know it's very difficult to change ini format, so how about to set userconfig file?
```
npm config set userconfig <path>
```

Thanks.

**Comment by othiym23** [comment]
There is already the builtin configuration (`$(npm -g root)/npm/npmrc`), configuration via environment variables, the global configuration (`npm config get globalconfig`), and user configuration (`"$HOME"/.npmrc`). Splitting apart the current configuration setup even further would take a confusing situation and make it even harder to support, and wouldn't really solve the problem.

You're not the first person to request having a way to check the npm configuration in as a dotfile safely, but the answer remains the same: the original and primary purpose of that file is to contain registry configuration, and that includes the current registry credentials. In that respect, it's not a whole lot different than the `$HOME/.ssh` directory. If you reaaaallly want to move that data somewhere else, use environment variables:

```bash
# in .bashrc
export npm_config_userconfig=/path/to/userconfig # only keep registry credentials in there
export npm_config_save_default="~"`
# and so on
```

That way the shared settings go in your dotfiles, and the stuff you don't want in version control isn't.

**Comment by mightyiam** [comment]
This works for me:
https://github.com/mightyiam/dotfiles/commit/94b653449e36b2ce3f15fa705cef7b6380e31b63

And the `.npmrc` has only the secret.
