### ISSUE TITLE
Trim & Git Issues (Resolutions from other issues didn't help)

### ISSUE THREAD

**Issue by azkaiart** [npm/npm#8227]
Went through these issues (http://stackoverflow.com/questions/26620312/installing-git-in-path-with-github-client-for-windows, https://github.com/npm/npm/issues/7984 and https://github.com/npm/npm/issues/8220) and did the solutions multiple times and I still cannot get NPM to work or run any of my gulp tasks or install any packages anymore. I had GIT installed (using git bash) and than installed GitHub app as well. That is when this issue started. I did add the GitHub git.exe into my path as instructed by another issue.

Here is the full log:

https://gist.githubusercontent.com/azkaiart/b08520207c558b7beb55/raw/errlog

**Comment by KenanY** [comment]
@azkaiart Does this also occur if you [upgrade](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows) to the latest stable release of `npm`?

**Comment by azkaiart** [comment]
Hi @KenanY, yes, I did the first than the third option after the first did not work. I uninstalled Node.js and reinstalled between options, and also manually deleted the NPM folders between trying to set them.
