### ISSUE TITLE
"npm dist-tag add package@nonexistentversion" removes tag

### ISSUE THREAD

**Issue by aredridel** [npm/npm#8231]
I added a dist-tag to a typoed version name:

```
:; npm dist-tag add localizr@0.16 older
+older: localizr@0.16
```

and it seemed to confirm that it worked. In fact, it removed the dist-tag from 0.1.5, and there is no 0.16 to add it to.

```
:; npm dist-tag add localizr@0.1.6 older
+older: localizr@0.1.6
```

fixed it, but seems like a footgun

**Comment by othiym23** [comment]
Eh heh heh. Yeah, we should fix this.

**Comment by othiym23** [comment]
This has been moved to the [npm roadmap](https://github.com/npm/npm/wiki/Roadmap), which we're using instead of the confusing `next-*` labels now.
