### ISSUE TITLE
Error encountered while installing gulp-sass

### ISSUE THREAD

**Issue by wenzoto** [npm/npm#8234]
http://i.imgur.com/UJlE36k.png

npm-debug.log

https://gist.github.com/wenzoto/49d25ac4d876e444d7bb

**Comment by KenanY** [comment]
@wenzoto Does this occur if you [upgrade](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows) to the latest stable release of `npm`?

**Comment by KenanY** [comment]
@wenzoto ping

**Comment by othiym23** [comment]
Closing as abandoned.
