### ISSUE TITLE
Email change not reflected in packages

### ISSUE THREAD

**Issue by ajnisbet** [npm/npm#8235]
I changed my email a while ago at [npmjs.com/email-edit](https://www.npmjs.com/email-edit). The new email is shown on my profile page, but npm still has references to my old email.

Running `npm owner ls <pkg>` shows the old email for some packages. Also, `npm i <pkg>` has the old email under maintainers in `package.json`.

Is there something more I need to do to propagate my new email?

(For reference, my npm username is ajnisbet, and an example of a problematic package is odojs.)

**Comment by adef145** [comment]
I have the same problem. i changed my email in [npmjs.com/email-edit](url) and when running `npm owner ls`, still old email.
Can i remove onwer `npm owner rm` and add owner `npm owner add` again? but when remove the owner, the package not have an owner, is that okay?
