### ISSUE TITLE
Problem when running "npm install"

### ISSUE THREAD

**Issue by danielatk** [npm/npm#8243]
So I've downloaded bootstrap and node.js.
Afterwards I globally installed grunt-cli with the command "npm install -g grunt-cli"
But when I tried to run "npm install" this message came up:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose node symlink C:\Program Files (x86)\nodejs\\node.exe
5 verbose config Skipping project config: C:\Users\Daniel/.npmrc. (matches userconfig)
6 error install Couldn't read dependencies
7 verbose stack Error: ENOENT, open 'C:\Users\Daniel\package.json'
7 verbose stack     at Error (native)
8 verbose cwd C:\Users\Daniel
9 error Windows_NT 6.3.9600
10 error argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
11 error node v0.12.2
12 error npm  v2.7.4
13 error path C:\Users\Daniel\package.json
14 error code ENOPACKAGEJSON
15 error errno -4058
16 error package.json ENOENT, open 'C:\Users\Daniel\package.json'
16 error package.json This is most likely not a problem with npm itself.
16 error package.json npm can't find a package.json file in your current directory.
17 verbose exit [ -4058, true ]
```

I'm completely stuck. If anyone could help that would be great and really appreciated.

**Comment by KenanY** [comment]
@danielatk Does `C:\Users\Daniel\package.json` exist? What are you _expecting_ to happen when you run [`npm install`](https://docs.npmjs.com/cli/install) with no arguments and with no `package.json` in your current working directory? `npm` has no idea what you want to install.

**Comment by danielatk** [comment]
I was following the steps on this website: http://getbootstrap.com/getting-started/#download
"Navigate to the root /bootstrap/ directory, then run npm install. npm will look at the package.json file and automatically install the necessary local dependencies listed there."

**Comment by KenanY** [comment]
@danielatk The log says you are in your home directory:

```
8 verbose cwd C:\Users\Daniel
```

**Comment by danielatk** [comment]
When I try going to the /bootstrap/ directory it shows this error message:

![error](https://cloud.githubusercontent.com/assets/12404372/7601716/9371f620-f8f0-11e4-9eb7-ae82a17a548c.jpg)

**Comment by KenanY** [comment]
@danielatk I'm not very familiar with Bootstrap, and this is not an `npm` issue, so I can't provide the best help. As far as I can tell, you've downloaded the already-compiled version of Bootstrap. As such, you do not need to compile it yourself with `grunt` and `npm`. I think you've read into too much of that page, since you are following instructions for compiling Bootstrap from source (but you have not downloaded the source).

**Comment by danielatk** [comment]
I see. Thanks for all your help! I'll try to figure out the rest.

**Comment by othiym23** [comment]
Closing as resolved.
