### ISSUE TITLE
npm run protractor has error

### ISSUE THREAD

**Issue by tankgod** [npm/npm#8245]
![ka_0 7 4ho 4 pf 087aa](https://cloud.githubusercontent.com/assets/11535593/7603632/4fc4a1d8-f969-11e4-8767-72c6127475e0.png)
![axqtggeaiow e0n si ev](https://cloud.githubusercontent.com/assets/11535593/7603645/8024a01c-f969-11e4-8684-be99e174b0f7.png)

**Comment by watilde** [comment]
Hi tankgod,
If you like to use `run-script`, you should write the following:
```json
"dependencies": {
  "protractor": "^x.x.x"
},
"scripts": {
  "protractor": "protractor"
}
```
or also you can do it with npm bin: `$(npm bin)/protractor`.

Thanks.

**Comment by tankgod** [comment]
i cant understand what you say,can you say more clearly? I am a beginner！！

**Comment by watilde** [comment]
@tankgod Oh, I'm sorry about my unclearly comment.

So if you would like to use `npm run *`, you need to write the following to your package.json:
```json
"scripts": {
  "foo": "echo foo"
}
```

In this case, we would like to run `npm run protractor` and use protractor you installed as dependency, you need to write this to your package.json:
```json
"scripts": {
  "protractor": "protractor"
}
```

Also there are alias of dependencies bin in `node_modules/.bin`. You can get that path with `npm bin` so same result was gotten with `npm run  running protractor` by `$(npm bin)/protractor`. See also `ls /path/to/project/node_modules/.bin`, and here is `run-script` docs: https://docs.npmjs.com/cli/run-script

Any unclearly expression, please feel free to let me know.
Thanks!

**Comment by KenanY** [comment]
@tankgod Did you resolve this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
