### ISSUE TITLE
please help me i cannot install it properly 

### ISSUE THREAD

**Issue by Uttammgr** [npm/npm#8248]
![screen shot 2015-05-13 at 12 53 42 pm](https://cloud.githubusercontent.com/assets/9637242/7605465/9147baea-f96f-11e4-8806-7b246b20ae33.png)

i am unable to install yeoman and pull the things from the repository such as modernizer, sass and bootstrap

**Comment by Uttammgr** [comment]
i am having this issue now help me please anybody helping with team viewer 

![screen shot 2015-05-13 at 2 18 30 pm](https://cloud.githubusercontent.com/assets/9637242/7606706/05e674b2-f97b-11e4-805e-ca685447440c.png)

**Comment by KenanY** [comment]
@Uttammgr 

First screenshot: `yeoman` has been deprecated for a long time now; the log tells you that. I believe you mean to install [`yo`](https://www.npmjs.com/package/yo)?

Second screenshot: have you globally installed `jshint`, `bower`, `yo`, and `grunt-cli`?

**Comment by Uttammgr** [comment]
@kenanY 
yeah i was installing the yeoman but error came and i was unable to instal 

second one is that all packages are installed but it say command not found 
any solution to this problem I'm unable to use any of the services 

thanks

**Comment by KenanY** [comment]
@Uttammgr 

> yeah i was installing the yeoman but error came and i was unable to instal

Please try installing `yo` instead of `yeoman`. If you still receive an error, please upload the _entire_ `npm-debug.log` as a [gist](https://gist.github.com) and post the link here.

> second one is that all packages are installed but it say command not found 

Can you provide me with the output of `npm ls -g --depth=0`?

**Comment by Uttammgr** [comment]
@KenanY 
i tried  yo 
  different same command 
npm install -g yo
npm -g install yo
npm install --global yo 

also tried  similar 
     npm install -g yeoman 
    npm -g install yeoman
    npm install --global yeoman
still same error  yeoman has been deprecated
when yeoman is used instead of yo 

https://gist.github.com/Uttammgr/8d0c414a9c3b613728ad

**Comment by Uttammgr** [comment]
hey @KenanY 
i am unable to solve the problem on npm issue and it doesn't find any of the command including yeoman, coffee-script, grunt & bower

**Comment by KenanY** [comment]
@Uttammgr I had to think on this for a bit. What does your `PATH` look like?

**Comment by Uttammgr** [comment]
@KenanY 
uesd echo command 
![screen shot 2015-06-02 at 8 47 32 pm](https://cloud.githubusercontent.com/assets/9637242/7939165/45aa5bc4-0969-11e5-9b1e-7851b517acc4.png)

**Comment by eddiemonge** [comment]
@Uttammgr what do you get when you run `ls $(npm get prefix)/lib/node_modules`

**Comment by Uttammgr** [comment]
@eddiemonge
these are the stuff installed but still doesn't work correctly 

<img width="500" alt="screen shot 2015-12-05 at 12 41 10 am" src="https://cloud.githubusercontent.com/assets/9637242/11598323/61007b62-9ae9-11e5-8a53-4cf3e2739b2a.png">
