### ISSUE TITLE
problem in executing npm install node-xmpp

### ISSUE THREAD

**Issue by Harshavalli** [npm/npm#8250]

**Comment by KenanY** [comment]
@Harshavalli Is there a `npm-debug.log` you could upload as a [gist](https://gist.github.com)? Surely you cannot expect a solution to an empty issue.

https://github.com/npm/npm/wiki/Contributing-Guidelines#a-great-bug-report-contains

**Comment by othiym23** [comment]
Closing due to not being actionable. @Harshavalli if you're still having trouble, open a new issue, and include either a link to a gist, or a more detailed description of the problem you encountered.
