### ISSUE TITLE
Error installing Less

### ISSUE THREAD

**Issue by midweststudios** [npm/npm#8253]
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', '-g', 'less' ]
2 info using npm@2.9.1
3 info using node@v0.12.2
4 verbose node symlink /usr/local/bin/node
5 verbose install initial load of /usr/local/lib/package.json
6 verbose readDependencies loading dependencies from /usr/local/lib/package.json
7 silly cache add args [ 'less', null ]
8 verbose cache add spec less
9 silly cache add parsed spec { raw: 'less',
9 silly cache add   scope: null,
9 silly cache add   name: 'less',
9 silly cache add   rawSpec: '',
9 silly cache add   spec: '*',
9 silly cache add   type: 'range' }
10 silly addNamed less@*
11 verbose addNamed "*" is a valid semver range for less
12 silly addNameRange { name: 'less', range: '*', hasData: false }
13 silly mapToRegistry name less
14 silly mapToRegistry using default registry
15 silly mapToRegistry registry https://registry.npmjs.org/
16 silly mapToRegistry uri https://registry.npmjs.org/less
17 verbose addNameRange registry:https://registry.npmjs.org/less not in flight; fetching
18 verbose request uri https://registry.npmjs.org/less
19 verbose request no auth needed
20 info attempt registry request try #1 at 12:18:28 PM
21 verbose request id b90c74b304c2514b
22 http request GET https://registry.npmjs.org/less
23 http 200 https://registry.npmjs.org/less
24 silly get cb [ 200,
24 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
24 silly get     etag: '"70V2UMG20IOWENBSDDAXOOF2C"',
24 silly get     'content-type': 'application/json',
24 silly get     'cache-control': 'max-age=60',
24 silly get     'content-length': '90864',
24 silly get     'accept-ranges': 'bytes',
24 silly get     date: 'Wed, 13 May 2015 16:18:28 GMT',
24 silly get     via: '1.1 varnish',
24 silly get     age: '0',
24 silly get     connection: 'keep-alive',
24 silly get     'x-served-by': 'cache-dfw1834-DFW',
24 silly get     'x-cache': 'HIT',
24 silly get     'x-cache-hits': '1',
24 silly get     'x-timer': 'S1431533908.743872,VS0,VE63',
24 silly get     vary: 'Accept' } ]
25 verbose get saving less to /Users/Katie/.npm/registry.npmjs.org/less/.cache.json
26 silly addNameRange number 2 { name: 'less', range: '*', hasData: true }
27 silly addNameRange versions [ 'less',
27 silly addNameRange   [ '1.0.10',
27 silly addNameRange     '1.0.11',
27 silly addNameRange     '1.0.14',
27 silly addNameRange     '1.0.18',
27 silly addNameRange     '1.0.19',
27 silly addNameRange     '1.0.21',
27 silly addNameRange     '1.0.32',
27 silly addNameRange     '1.0.36',
27 silly addNameRange     '1.0.5',
27 silly addNameRange     '1.0.40',
27 silly addNameRange     '1.0.41',
27 silly addNameRange     '1.0.44',
27 silly addNameRange     '1.1.0',
27 silly addNameRange     '1.1.1',
27 silly addNameRange     '1.1.2',
27 silly addNameRange     '1.1.4',
27 silly addNameRange     '1.1.5',
27 silly addNameRange     '1.1.6',
27 silly addNameRange     '1.2.0',
27 silly addNameRange     '1.2.1',
27 silly addNameRange     '1.2.2',
27 silly addNameRange     '1.3.0',
27 silly addNameRange     '1.3.1',
27 silly addNameRange     '1.3.2',
27 silly addNameRange     '1.3.3',
27 silly addNameRange     '1.4.0-b1',
27 silly addNameRange     '1.4.0-b2',
27 silly addNameRange     '1.4.0-b3',
27 silly addNameRange     '1.4.0-b4',
27 silly addNameRange     '1.4.0',
27 silly addNameRange     '1.4.1',
27 silly addNameRange     '1.4.2',
27 silly addNameRange     '1.5.0-b1',
27 silly addNameRange     '1.5.0-b2',
27 silly addNameRange     '1.5.0-b3',
27 silly addNameRange     '1.5.0-b4',
27 silly addNameRange     '1.5.0',
27 silly addNameRange     '1.5.1',
27 silly addNameRange     '1.6.0',
27 silly addNameRange     '1.6.1',
27 silly addNameRange     '1.6.2',
27 silly addNameRange     '1.6.3',
27 silly addNameRange     '1.7.0',
27 silly addNameRange     '1.7.1',
27 silly addNameRange     '1.7.3',
27 silly addNameRange     '1.7.4',
27 silly addNameRange     '1.7.5',
27 silly addNameRange     '2.0.0-b1',
27 silly addNameRange     '2.0.0-b2',
27 silly addNameRange     '2.0.0-b3',
27 silly addNameRange     '2.0.0',
27 silly addNameRange     '2.1.0',
27 silly addNameRange     '2.1.1',
27 silly addNameRange     '2.1.2',
27 silly addNameRange     '2.2.0',
27 silly addNameRange     '2.3.0',
27 silly addNameRange     '2.3.1',
27 silly addNameRange     '2.4.0',
27 silly addNameRange     '2.5.0' ] ]
28 silly addNamed less@2.5.0
29 verbose addNamed "2.5.0" is a plain semver version for less
30 silly mapToRegistry name less
31 silly mapToRegistry using default registry
32 silly mapToRegistry registry https://registry.npmjs.org/
33 silly mapToRegistry uri https://registry.npmjs.org/less
34 verbose addRemoteTarball https://registry.npmjs.org/less/-/less-2.5.0.tgz not in flight; adding
35 verbose addRemoteTarball [ 'https://registry.npmjs.org/less/-/less-2.5.0.tgz',
35 verbose addRemoteTarball   '11d6d611586de6d5f808220649bc9bbfe7ad5e17' ]
36 info retry fetch attempt 1 at 12:18:29 PM
37 info attempt registry request try #1 at 12:18:29 PM
38 http fetch GET https://registry.npmjs.org/less/-/less-2.5.0.tgz
39 http fetch 200 https://registry.npmjs.org/less/-/less-2.5.0.tgz
40 silly fetchAndShaCheck shasum 11d6d611586de6d5f808220649bc9bbfe7ad5e17
41 verbose addTmpTarball /var/folders/20/6f7vptrn7ld0bv3b_rnv75_m0000gq/T/npm-40949-22c3e525/registry.npmjs.org/less/-/less-2.5.0.tgz not in flight; adding
42 verbose addTmpTarball already have metadata; skipping unpack for less@2.5.0
43 silly cache afterAdd less@2.5.0
44 verbose afterAdd /Users/Katie/.npm/less/2.5.0/package/package.json not in flight; writing
45 verbose afterAdd /Users/Katie/.npm/less/2.5.0/package/package.json written
46 silly install resolved [ { name: 'less',
46 silly install resolved     version: '2.5.0',
46 silly install resolved     description: 'Leaner CSS',
46 silly install resolved     homepage: 'http://lesscss.org',
46 silly install resolved     author: { name: 'Alexis Sellier', email: 'self@cloudhead.net' },
46 silly install resolved     contributors: [ [Object] ],
46 silly install resolved     bugs: { url: 'https://github.com/less/less.js/issues' },
46 silly install resolved     repository: { type: 'git', url: 'https://github.com/less/less.js.git' },
46 silly install resolved     licenses: [ [Object] ],
46 silly install resolved     bin: { lessc: './bin/lessc' },
46 silly install resolved     main: 'index',
46 silly install resolved     directories: { test: './test' },
46 silly install resolved     jam: { main: './dist/less.js' },
46 silly install resolved     browser: './dist/less.js',
46 silly install resolved     engines: { node: '>=0.10.0' },
46 silly install resolved     scripts: { test: 'grunt test' },
46 silly install resolved     optionalDependencies:
46 silly install resolved      { errno: '^0.1.1',
46 silly install resolved        'graceful-fs': '^3.0.5',
46 silly install resolved        'image-size': '~0.3.5',
46 silly install resolved        mime: '^1.2.11',
46 silly install resolved        mkdirp: '^0.5.0',
46 silly install resolved        promise: '^6.0.1',
46 silly install resolved        request: '^2.51.0',
46 silly install resolved        'source-map': '^0.4.2' },
46 silly install resolved     devDependencies:
46 silly install resolved      { diff: '^1.0',
46 silly install resolved        grunt: '^0.4.5',
46 silly install resolved        'grunt-contrib-clean': '^0.6.0',
46 silly install resolved        'grunt-contrib-concat': '^0.5.0',
46 silly install resolved        'grunt-contrib-connect': '^0.9.0',
46 silly install resolved        'grunt-contrib-jasmine': '^0.8.2',
46 silly install resolved        'grunt-contrib-jshint': '^0.11.0',
46 silly install resolved        'grunt-contrib-uglify': '^0.8.0',
46 silly install resolved        'grunt-jscs': '^1.6.0',
46 silly install resolved        'grunt-shell': '^1.1.1',
46 silly install resolved        'grunt-browserify': '~3.5.0',
46 silly install resolved        'jit-grunt': '^0.9.1',
46 silly install resolved        'time-grunt': '^1.0.0',
46 silly install resolved        'grunt-saucelabs': '^8.3.2' },
46 silly install resolved     keywords:
46 silly install resolved      [ 'compile less',
46 silly install resolved        'css nesting',
46 silly install resolved        'css variable',
46 silly install resolved        'css',
46 silly install resolved        'gradients css',
46 silly install resolved        'gradients css3',
46 silly install resolved        'less compiler',
46 silly install resolved        'less css',
46 silly install resolved        'less mixins',
46 silly install resolved        'less',
46 silly install resolved        'less.js',
46 silly install resolved        'lesscss',
46 silly install resolved        'mixins',
46 silly install resolved        'nested css',
46 silly install resolved        'parser',
46 silly install resolved        'preprocessor',
46 silly install resolved        'bootstrap css',
46 silly install resolved        'bootstrap less',
46 silly install resolved        'style',
46 silly install resolved        'styles',
46 silly install resolved        'stylesheet',
46 silly install resolved        'variables in css',
46 silly install resolved        'css less' ],
46 silly install resolved     gitHead: '9b7021a309a9010b04ddc89d5fd86f1d2d0b3433',
46 silly install resolved     dependencies:
46 silly install resolved      { errno: '^0.1.1',
46 silly install resolved        'graceful-fs': '^3.0.5',
46 silly install resolved        'image-size': '~0.3.5',
46 silly install resolved        mime: '^1.2.11',
46 silly install resolved        mkdirp: '^0.5.0',
46 silly install resolved        promise: '^6.0.1',
46 silly install resolved        request: '^2.51.0',
46 silly install resolved        'source-map': '^0.4.2' },
46 silly install resolved     _id: 'less@2.5.0',
46 silly install resolved     _shasum: '11d6d611586de6d5f808220649bc9bbfe7ad5e17',
46 silly install resolved     _from: 'less@*',
46 silly install resolved     _npmVersion: '2.5.1',
46 silly install resolved     _nodeVersion: '0.12.1',
46 silly install resolved     _npmUser: { name: 'agatronic', email: 'luke.a.page@gmail.com' },
46 silly install resolved     maintainers: [ [Object], [Object] ],
46 silly install resolved     dist:
46 silly install resolved      { shasum: '11d6d611586de6d5f808220649bc9bbfe7ad5e17',
46 silly install resolved        tarball: 'http://registry.npmjs.org/less/-/less-2.5.0.tgz' },
46 silly install resolved     _resolved: 'https://registry.npmjs.org/less/-/less-2.5.0.tgz' } ]
47 info install less@2.5.0 into /usr/local/lib
48 info installOne less@2.5.0
49 verbose installOne of less to /usr/local/lib not in flight; installing
50 warn locking Error: EACCES, open '/Users/Katie/.npm/_locks/less-c2213c903e2e7354.lock'
50 warn locking     at Error (native)
50 warn locking  /Users/Katie/.npm/_locks/less-c2213c903e2e7354.lock failed { [Error: EACCES, open '/Users/Katie/.npm/_locks/less-c2213c903e2e7354.lock']
50 warn locking   errno: -13,
50 warn locking   code: 'EACCES',
50 warn locking   path: '/Users/Katie/.npm/_locks/less-c2213c903e2e7354.lock' }
51 verbose stack Error: Attempt to unlock /usr/local/lib/node_modules/less, which hasn't been locked
51 verbose stack     at unlock (/usr/local/lib/node_modules/npm/lib/utils/locker.js:66:11)
51 verbose stack     at cb (/usr/local/lib/node_modules/npm/lib/install.js:1015:5)
51 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:1019:20
51 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/locker.js:40:9
51 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
51 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
51 verbose stack     at FSReqWrap.oncomplete (fs.js:95:15)
52 verbose cwd /Users/Katie
53 error Darwin 14.3.0
54 error argv "node" "/usr/local/bin/npm" "install" "-g" "less"
55 error node v0.12.2
56 error npm  v2.9.1
57 error Attempt to unlock /usr/local/lib/node_modules/less, which hasn't been locked
58 error If you need help, you may report this error at:
58 error     <https://github.com/npm/npm/issues>
59 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@midweststudios It looks like your current user does not have the necessary permissions to read/write to `npm`'s cache directory. Could you try taking ownership?:

``` sh
$ sudo chown -R $(whoami) "$HOME/.npm"
```

You may also need to prepend the install command with `sudo` if you do not have permission to write to `/usr/local` (which is usually the case on most systems, since it is designed with multiple users in mind).

**Comment by midweststudios** [comment]
That worked.  Thank you for the quick response!
