### ISSUE TITLE
when i use $yo webapp for a new projects in the  "zeng/workspace/yeoman/myapp" directory 

### ISSUE THREAD

**Issue by StarryF** [npm/npm#8255]
when i use $yo webapp for a new projects in the    "zeng/workspace/yeoman/myapp" directory  , but all the new files are created in the boot directory. why ?

**Comment by KenanY** [comment]
Hi @StarryF, issues with `yo` should be opened over at [its own issue tracker](https://github.com/yeoman/yo). This issue tracker is for bugs in `npm` :)

**Comment by othiym23** [comment]
Closing as resolved / not an npm issue.
