### ISSUE TITLE
The installation of NPM there is one thing I don't understand why

### ISSUE THREAD

**Issue by tankgod** [npm/npm#8261]
![image](https://cloud.githubusercontent.com/assets/11535593/7625666/419d5f22-fa2d-11e4-8891-5f19a8063328.png)

"Two" is I downloaded in GitHub, but after performing the complete installation command "node cli.js install -gf", generating the a "one", and not only so, files "one" and "node modules in the same. This is why, PS: I is nodejs beginners

**Comment by KenanY** [comment]
@tankgod Are you still interested in an answer to this?

**Comment by KenanY** [comment]
Closing as abandoned.
