### ISSUE TITLE
npm install express -g has error(ps:I am begginner)

### ISSUE THREAD

**Issue by tankgod** [npm/npm#8262]
![image](https://cloud.githubusercontent.com/assets/11535593/7625865/304e078c-fa30-11e4-8881-ae2243fbe8c4.png)

**Comment by kmanion** [comment]
Hi @tankgod, we’re trying to clean up some issues. 

Are you working from behind a proxy? If not, errors like this can be related to network connectivity. I would recommend making sure your proxy is configured correctly and trying the install again.

If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.

-Kiera, npm technical support
