### ISSUE TITLE
npm error when using in Git: "Error: EPERM, mkdir 'C:/Program Files (x86)/Git/local' at Error (native)"

### ISSUE THREAD

**Issue by b1tn3r** [npm/npm#8265]
Originally I was trying to use bower to install packages with Git Bash. I kept receiving the error bower command not found and found a post that said to run the command "npm config set prefix /usr/local" and then install bower. 

Instead of fixing the problem with bower it created issues with npm, in which every time I try to install a package with npm, use npm config, and any instance with npm, I get the error "Error: EPERM, mkdir 'C:/Program Files (x86)/Git/local' at Error (native)"

How do I fix this? Please help

**Comment by PrinceDavis** [comment]
You have to manually give permission to write to C:\Program Files (x86)\Git folder. inside the folder
Usin your windows explorer, right click, choose 'Properties' and go to 'Security' tab

You will see many users... just give privileges to the user you need and try running npm install again again...

**Comment by sali1982** [comment]
Did you fix this issue? I am having the same issue over that script!

**Comment by PrinceDavis** [comment]
Yes i did just follow the steps in my earlier post

**Comment by b1tn3r** [comment]
If I remember correctly, it was a security issue as Davis said. Either manually give permissions to your user account or make sure to run Git Bash as an administrator.
