### ISSUE TITLE
Error occurred during the execution of command npm install express

### ISSUE THREAD

**Issue by rejir** [npm/npm#8267]
Shows the error like this:-

argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "express"
node v0.12.2

**Comment by KenanY** [comment]
@rejir I do not see an error in the output you have posted. Please, if there is a `npm-debug.log` created, could you upload it as a [gist](https://gist.github.com)?

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
