### ISSUE TITLE
Error: ENOENT, open '/home/syslog-ng/package.json'

### ISSUE THREAD

**Issue by Maxwell101** [npm/npm#8271]
```
npm ERR! install Couldn't read dependencies
npm ERR! Error: ENOENT, open '/home/syslog-ng/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
Getting this error message when trying to run npm install



npm ERR! System Linux 3.16.0-33-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/syslog-ng
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/syslog-ng/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/syslog-ng/npm-debug.log
npm ERR! not ok code 0
```

**Comment by KenanY** [comment]
@Maxwell101 Does `/home/syslog-ng/package.json` exist?

**Comment by Maxwell101** [comment]
No.  It's in /usr/lib/nodejs/nmp.  Also when I try to enter:

use syslog
db.runCommand({
    convertToCapped: 'messages',
    size: 100000
    });

into the mongodb shell an error message - system.messages doesn't exist.
I obviously new to this.

**Comment by KenanY** [comment]
@Maxwell101 From your error log, it seems like you are running `npm install` without any arguments in  the `/home/syslog-ng/` directory. Without any arguments, and without a `package.json` in your current working directory, `npm` has no idea what you want to install. The documentation on [`npm install`](https://docs.npmjs.com/cli/install) and the [getting-started](https://docs.npmjs.com/getting-started/installing-npm-packages-locally) guide might be of great help to you :)

**Comment by KenanY** [comment]
@Maxwell101 ping?

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
