### ISSUE TITLE
Backend error while trying to deprecate scoped package

### ISSUE THREAD

**Issue by rudiculous** [npm/npm#8275]
When trying to deprecate a scoped package, I am getting a "503 backend read error". The command used is `npm deprecate @rdcl/framework@"< 0.0.3" 'Critical bug fixed in 0.0.3.'`.

I am using `npm@2.10.0`. I have tried with both `Node@v0.10.29` and `iojs@v2.0.0`.

I have been trying to deprecate this package for a couple of days now, so it does not seem to be an intermittent problem.

Running `npm cache clean` first does not seem to make a difference.

## npm-debug.log
    0 info it worked if it ends with ok
    1 verbose cli [ '/usr/bin/nodejs',
    1 verbose cli   '/usr/local/bin/npm',
    1 verbose cli   'deprecate',
    1 verbose cli   '@rdcl/framework@< 0.0.3',
    1 verbose cli   'Critical bug fixed in 0.0.3.' ]
    2 info using npm@2.10.0
    3 info using node@v0.10.29
    4 silly mapToRegistry name @rdcl/framework
    5 silly mapToRegistry scope (from package name) @rdcl
    6 verbose mapToRegistry no registry URL found in name for scope @rdcl
    7 silly mapToRegistry scope (from config) @rdcl
    8 verbose mapToRegistry no registry URL found in config for scope @rdcl
    9 silly mapToRegistry using default registry
    10 silly mapToRegistry registry https://registry.npmjs.org/
    11 silly mapToRegistry uri https://registry.npmjs.org/@rdcl%2fframework
    12 verbose get GET as part of write; not caching result
    13 verbose request uri https://registry.npmjs.org/@rdcl%2fframework?write=true
    14 verbose request no auth needed
    15 info attempt registry request try #1 at 08:12:56
    16 verbose request using bearer token for auth
    17 verbose request id 921d8dbe6b240b56
    18 http request GET https://registry.npmjs.org/@rdcl%2fframework?write=true
    19 http 200 https://registry.npmjs.org/@rdcl%2fframework?write=true
    20 silly get cb [ 200,
    20 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
    20 silly get     etag: '"9H0BI16XAJGL44NV22VYGHIPM"',
    20 silly get     'content-type': 'application/json',
    20 silly get     'cache-control': 'max-age=0',
    20 silly get     'content-length': '5884',
    20 silly get     'accept-ranges': 'bytes',
    20 silly get     date: 'Fri, 15 May 2015 06:12:57 GMT',
    20 silly get     via: '1.1 varnish',
    20 silly get     connection: 'keep-alive',
    20 silly get     'x-served-by': 'cache-ams4126-AMS',
    20 silly get     'x-cache': 'MISS',
    20 silly get     'x-cache-hits': '0',
    20 silly get     'x-timer': 'S1431670376.550883,VS0,VE659',
    20 silly get     vary: 'Accept' } ]
    21 verbose get saving @rdcl/framework to /home/rj/.npm/registry.npmjs.org/_40rdcl_252fframework_3Fwrite_3Dtrue/.cache.json
    22 verbose request uri https://registry.npmjs.org/@rdcl/framework
    23 verbose request sending authorization for write operation
    24 info attempt registry request try #1 at 08:12:57
    25 verbose request using bearer token for auth
    26 http request PUT https://registry.npmjs.org/@rdcl/framework
    27 http 503 https://registry.npmjs.org/@rdcl/framework
    28 verbose bad json <?xml version="1.0" encoding="utf-8"?>
    28 verbose bad json <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    28 verbose bad json  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
    28 verbose bad json <html>
    28 verbose bad json   <head>
    28 verbose bad json     <title>503 backend read error</title>
    28 verbose bad json   </head>
    28 verbose bad json   <body>
    28 verbose bad json     <h1>Error 503 backend read error</h1>
    28 verbose bad json     <p>backend read error</p>
    28 verbose bad json     <h3>Guru Mediation:</h3>
    28 verbose bad json     <p>Details: cache-ams4130-AMS 1431670417 2057953573</p>
    28 verbose bad json     <hr>
    28 verbose bad json     <p>Varnish cache server</p>
    28 verbose bad json   </body>
    28 verbose bad json </html>
    29 error registry error parsing json
    30 info retry will retry, error on last attempt: SyntaxError: Unexpected token <
    30 info retry
    30 info retry <?xml version="1.0" encoding="utf-8"?>
    30 info retry <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    30 info retry  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
    30 info retry <html>
    30 info retry   <head>
    30 info retry     <title>503 backend read error</title>
    30 info retry   </head>
    30 info retry   <body>
    30 info retry     <h1>Error 503 backend read error</h1>
    30 info retry     <p>backend read error</p>
    30 info retry     <h3>Guru Mediation:</h3>
    30 info retry     <p>Details: cache-ams4130-AMS 1431670417 2057953573</p>
    30 info retry     <hr>
    30 info retry     <p>Varnish cache server</p>
    30 info retry   </body>
    30 info retry </html>
    31 info attempt registry request try #2 at 08:13:47
    32 verbose request using bearer token for auth
    33 http request PUT https://registry.npmjs.org/@rdcl/framework
    34 http 503 https://registry.npmjs.org/@rdcl/framework
    35 verbose bad json <?xml version="1.0" encoding="utf-8"?>
    35 verbose bad json <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    35 verbose bad json  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
    35 verbose bad json <html>
    35 verbose bad json   <head>
    35 verbose bad json     <title>503 backend read error</title>
    35 verbose bad json   </head>
    35 verbose bad json   <body>
    35 verbose bad json     <h1>Error 503 backend read error</h1>
    35 verbose bad json     <p>backend read error</p>
    35 verbose bad json     <h3>Guru Mediation:</h3>
    35 verbose bad json     <p>Details: cache-ams4136-AMS 1431670467 1991009749</p>
    35 verbose bad json     <hr>
    35 verbose bad json     <p>Varnish cache server</p>
    35 verbose bad json   </body>
    35 verbose bad json </html>
    36 error registry error parsing json
    37 info retry will retry, error on last attempt: SyntaxError: Unexpected token <
    37 info retry
    37 info retry <?xml version="1.0" encoding="utf-8"?>
    37 info retry <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    37 info retry  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
    37 info retry <html>
    37 info retry   <head>
    37 info retry     <title>503 backend read error</title>
    37 info retry   </head>
    37 info retry   <body>
    37 info retry     <h1>Error 503 backend read error</h1>
    37 info retry     <p>backend read error</p>
    37 info retry     <h3>Guru Mediation:</h3>
    37 info retry     <p>Details: cache-ams4136-AMS 1431670467 1991009749</p>
    37 info retry     <hr>
    37 info retry     <p>Varnish cache server</p>
    37 info retry   </body>
    37 info retry </html>
    38 info attempt registry request try #3 at 08:15:27
    39 verbose request using bearer token for auth
    40 http request PUT https://registry.npmjs.org/@rdcl/framework
    41 http 503 https://registry.npmjs.org/@rdcl/framework
    42 verbose bad json <?xml version="1.0" encoding="utf-8"?>
    42 verbose bad json <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    42 verbose bad json  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
    42 verbose bad json <html>
    42 verbose bad json   <head>
    42 verbose bad json     <title>503 backend read error</title>
    42 verbose bad json   </head>
    42 verbose bad json   <body>
    42 verbose bad json     <h1>Error 503 backend read error</h1>
    42 verbose bad json     <p>backend read error</p>
    42 verbose bad json     <h3>Guru Mediation:</h3>
    42 verbose bad json     <p>Details: cache-ams4144-AMS 1431670568 1983810767</p>
    42 verbose bad json     <hr>
    42 verbose bad json     <p>Varnish cache server</p>
    42 verbose bad json   </body>
    42 verbose bad json </html>
    43 error registry error parsing json
    44 verbose headers { server: 'Varnish',
    44 verbose headers   'retry-after': '0',
    44 verbose headers   'content-type': 'text/html; charset=utf-8',
    44 verbose headers   'content-length': '448',
    44 verbose headers   'accept-ranges': 'bytes',
    44 verbose headers   date: 'Fri, 15 May 2015 06:16:08 GMT',
    44 verbose headers   via: '1.1 varnish',
    44 verbose headers   connection: 'close',
    44 verbose headers   'x-served-by': 'cache-ams4144-AMS',
    44 verbose headers   'x-cache': 'MISS',
    44 verbose headers   'x-cache-hits': '0',
    44 verbose headers   'x-timer': 'S1431670527.995100,VS0,VE40246' }
    45 verbose request invalidating /home/rj/.npm/registry.npmjs.org/_40rdcl/framework on PUT
    46 verbose type unexpected_token
    47 verbose stack SyntaxError: Unexpected token <
    47 verbose stack
    47 verbose stack <?xml version="1.0" encoding="utf-8"?>
    47 verbose stack <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    47 verbose stack  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
    47 verbose stack <html>
    47 verbose stack   <head>
    47 verbose stack     <title>503 backend read error</title>
    47 verbose stack   </head>
    47 verbose stack   <body>
    47 verbose stack     <h1>Error 503 backend read error</h1>
    47 verbose stack     <p>backend read error</p>
    47 verbose stack     <h3>Guru Mediation:</h3>
    47 verbose stack     <p>Details: cache-ams4144-AMS 1431670568 1983810767</p>
    47 verbose stack     <hr>
    47 verbose stack     <p>Varnish cache server</p>
    47 verbose stack   </body>
    47 verbose stack </html>
    47 verbose stack
    47 verbose stack     at Object.parse (native)
    47 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:197:23)
    47 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:170:14)
    47 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:368:22)
    47 verbose stack     at Request.emit (events.js:98:17)
    47 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1219:14)
    47 verbose stack     at Request.emit (events.js:117:20)
    47 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1167:12)
    47 verbose stack     at IncomingMessage.emit (events.js:117:20)
    47 verbose stack     at _stream_readable.js:929:16
    48 verbose cwd /home/rj/webapps/npm/rdcl/framework
    49 error Linux 3.16.0-4-amd64
    50 error argv "/usr/bin/nodejs" "/usr/local/bin/npm" "deprecate" "@rdcl/framework@< 0.0.3" "Critical bug fixed in 0.0.3."
    51 error node v0.10.29
    52 error npm  v2.10.0
    53 error Unexpected token <
    53 error
    53 error <?xml version="1.0" encoding="utf-8"?>
    53 error <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    53 error  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
    53 error <html>
    53 error   <head>
    53 error     <title>503 backend read error</title>
    53 error   </head>
    53 error   <body>
    53 error     <h1>Error 503 backend read error</h1>
    53 error     <p>backend read error</p>
    53 error     <h3>Guru Mediation:</h3>
    53 error     <p>Details: cache-ams4144-AMS 1431670568 1983810767</p>
    53 error     <hr>
    53 error     <p>Varnish cache server</p>
    53 error   </body>
    53 error </html>
    54 error If you need help, you may report this error at:
    54 error     <https://github.com/npm/npm/issues>
    55 verbose exit [ 1, true ]

**Comment by chester1000** [comment]
+1 I have the same error.

**Comment by migg24** [comment]
Is it still an issue with the newest versions of node and npm?

**Comment by rudiculous** [comment]
This issue seems to be resolved. I tested it with npm@3.7.3 and node@5.9.0, and with npm@2.14.20 and node@v4.4.0. I no longer get this error.
