### ISSUE TITLE
Git user.name and user.email wrong on npm version

### ISSUE THREAD

**Issue by Steditor** [npm/npm#8277]
Even though both local and global git config parameters are set to the correct `user.name` and `user.email`, npm still uses *unknown* and my computer's name when creating a commit (and tag) with `npm version`.

**Comment by KenanY** [comment]
@Steditor `npm --version`?

**Comment by Steditor** [comment]
Current `2.10.0`

**Comment by danpantry** [comment]
:+1 also having this issue on `2.11.1`. My git e-mail and author are configured correctly using a global config, but when npm creates a tag it is using a different e-mail and name which is associated with the machine.

**Comment by othiym23** [comment]
Here's the code:

* https://github.com/npm/npm/blob/2.x/lib/version.js
* https://github.com/npm/npm/blob/2.x/lib/utils/git.js

We do do some scrubbing of git environment variables elsewhere, but as you can see, there's nothing specifically overriding global configuration except the setting of `core.longpaths`. I'm at a bit of a loss to even speculate why the two of you might be seeing this behavior, so if you could do a little digging and help me figure it out, that would be very appreciated.

**Comment by busches** [comment]
Is this still occurring with anyone running the latest npm 2 or 3?

**Comment by KenanY** [comment]
Closing due to no response. Can reopen if this is still an issue.

**Comment by alexlokshin** [comment]
Have the same issue running a Gitlab CI build based on node:boron or node:7.8.0. All git commands issued directly are working fine (including git commit and git push), 'npm version patch' errors out due to the lack of user.name and user.email.
