### ISSUE TITLE
"npm ERR!" during gulp install

### ISSUE THREAD

**Issue by jesseshowalter** [npm/npm#8280]
Hope someone one can point me in the right direction. I had gulp working just fine the other day only to run into this today. The Gulp package was basically removed and I can't re install it. Anytime I try i am met with this...

Macintosh-2:_project-template jesseshowalter$ npm install -g gulp
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "gulp"
npm ERR! node v0.10.28
npm ERR! npm  v2.10.0
npm ERR! file /Users/jesseshowalter/.npm/once/1.3.2/package/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! No data, empty input at 1:1
npm ERR!
npm ERR! ^
npm ERR! File: /Users/jesseshowalter/.npm/once/1.3.2/package/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jesseshowalter/Sites/_project-template/npm-debug.log
Macintosh-2:_project-template jesseshowalter$ npm install jslint
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "jslint"
npm ERR! node v0.10.28
npm ERR! npm  v2.10.0

npm ERR! Invalid name: "Jesse Showalter"
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jesseshowalter/Sites/_project-template/npm-debug.log

Searched for an answer for hours. Thought maybe it was a permissions problem so I tried this https://docs.npmjs.com/getting-started/fixing-npm-permissions to no avail. Anyone know what to do in this situation?

- Jesse

**Comment by KenanY** [comment]
@jesseshowalter Hmm looks like an empty `package.json` file in your `npm` cache. Maybe try cleaning it?:

``` sh
$ npm cache clean once
```

Also looks like you've attached two error logs. The second tells me that you have [named](https://docs.npmjs.com/files/package.json#name) your package `"Jesse Showalter"`, but capital letters and spaces are not allowed in package names (hence the error: `"Invalid name`"). You should put your name in the [`"author"`](https://docs.npmjs.com/files/package.json#people-fields-author-contributors) field.

**Comment by jesseshowalter** [comment]
@KenanY you were spot on about the 2nd "name" issue, but the first issue still persists. Any ideas?

Macintosh-2:_project-template jesseshowalter$ sudo npm cache clean once
Password:
Macintosh-2:_project-template jesseshowalter$ sudo npm install -g gulp
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "gulp"
npm ERR! node v0.10.28
npm ERR! npm  v2.10.0
npm ERR! file /Users/jesseshowalter/.npm/brace-expansion/1.1.0/package/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! No data, empty input at 1:1
npm ERR!
npm ERR! ^
npm ERR! File: /Users/jesseshowalter/.npm/brace-expansion/1.1.0/package/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jesseshowalter/Sites/_project-template/npm-debug.log

**Comment by jesseshowalter** [comment]
Whatever this error was it was fixed by completely removing npm and node and re-installing. Thanks

**Comment by KenanY** [comment]
@jesseshowalter Ah, multiple empty `package.json`s. I could have suggested cleaning the whole cache too:

``` sj
$ npm cache clean
```

**Comment by icd2k3** [comment]
^ thanks @KenanY this did the trick for me

**Comment by neworldexport** [comment]
I installed at the root of computer cd/ and it works now

**Comment by sheshanireddy** [comment]
![image](https://cloud.githubusercontent.com/assets/26746407/24540270/ff8fb140-15b7-11e7-920d-3c621ea2048b.png)


I am getting this error while running command  $npm install

Can anyone help me out
