### ISSUE TITLE
Client allows `npm publish` when package name contains upper-case letter (let registry decide)

### ISSUE THREAD

**Issue by smikes** [npm/npm#8281]
Creating this here, because the implementation is a pair of pull requests to subsidiary modules

1. new option to allow `normalize-package-data` to pass names with an upper case char (https://github.com/npm/normalize-package-data/pull/62 )

2. use that option in `npm-registry-client` to defer checking that aspect of name validity until the registry (https://github.com/npm/npm-registry-client/pull/109 )

**Comment by othiym23** [comment]
We dealt with this a few months ago when it caused the universe to break for `JSONStream`, so yes, this was a very good thing to fix. Thanks, Sam!
