### ISSUE TITLE
when using npm programmatically, npm still sends output to stdout

### ISSUE THREAD

**Issue by jlipps** [npm/npm#8283]
I'm using NPM programmatically, in a script like this:

```js
var npm = require('npm');

npm.load({}, function (err, npm) {
  npm.commands.owner(['ls', 'mochawait'], function (err, res) {
    console.log(res);
  });
});
```

The output is not what I expect. I expect:

```
[ { name: 'jlipps', email: '<REDACTED> } ]
```

Instead, I get:

```
jlipps <REDACTED>
[ { name: 'jlipps', email: '<REDACTED>' } ]
```

I.e., inside the npm code, the e-mail address is getting sent to stdout. I've tried the following things:

* setting log level in the config, i.e., `{loglevel: 'silent'}`
* setting logstream to nothing, i.e., `{logstream: new stream.Writable()}`
* listening to the log events, i.e., adding `npm.registry.log.on("log", function () {});`

None of these have any effect. Is this a known issue? How do I work around it? I don't want npm polluting my script's output.

**Comment by smikes** [comment]
Thanks for raising this issue.

The `npm` API, although published and somewhat documented, is not intended for external use.  Most importantly, the `npm` project doesn't make any guarantees that the programmatic API is stable even across minor or patch versions; the programmatic API explicitly **does not** follow semver.  The semver-following version numbers describe the command-line use of `npm`, not its internal API (see https://github.com/npm/npm/issues/8216#issuecomment-100397681 for a clearer discussion of this).

So if you are planning to use `npm` from another program, it would be safest to treat `npm` as an opaque command-line program, not as a node program made up of node modules.

However, if you want a nice client for the `npm` registry that can be used programmatically, you might find that the https://github.com/npm/npm-registry-client/ module meets your needs.

**Comment by othiym23** [comment]
As @smikes said – the API isn't really meant to be consumed outside the CLI, and it's not our intention to have it behave differently from using the same command(s) from the command line. There's a longer-term architectural project to break npm up into smaller, more reusable components (`npm-registry-client` is the most fully fleshed out of those), but until then, the best way to run arbitrary npm commands from another program is to use child processes, which also gives you full control over what to do with npm's output.

**Comment by jlipps** [comment]
Ah, I didn't realize that was the situation. Thanks for the explanations. I'll check out npm-registry-client or simply use child_process.

Might I suggest an addition to the docs that also explains this? I found my way to the usage I described via npmjs.com, ostensibly a highly-trafficked source of information :-) It's also possible I missed some detail in my rush to the API documentation.
