### ISSUE TITLE
`npm install -g pkg` will install version in $PWD/pkg/package.json globally

### ISSUE THREAD

**Issue by dbkaplun** [npm/npm#8284]
Even if you use something like `npm install -g pkg@latest`, if there's a `$PWD/pkg@latest/package.json` file, it will use that.

This makes npm unreliable as a package manager for global packages.

Maybe we should consider prioritizing remote packages over local paths when using `-g`?

**Comment by othiym23** [comment]
@secrettriangle That would make it impossible to install local packages in some cases, or at least very confusing (e.g. if we required something like `./pkg@latest`). Why would you have a directory named `pkg@latest` in the current directory? What were you trying to do when you ran into this problem?

**Comment by secrettriangle** [comment]
Yes, that would make it impossible to install local packages in some cases.

The current implementation means it's impossible to install remote packages in some cases.
