### ISSUE TITLE
npm errors on install

### ISSUE THREAD

**Issue by stivyw** [npm/npm#8285]
I'm trying to install with npm, but it returned a lot of errors.

```
npm ERR! Linux 3.19.0-16-generic
npm ERR! argv "node" "/usr/bin/npm" "install" "-g" "bower"
npm ERR! node v0.12.3
npm ERR! npm  v2.10.0
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package grunt does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer grunt-contrib-jshint@0.10.0 wants grunt@~0.4.0
npm ERR! peerinvalid Peer grunt-contrib-nodeunit@0.3.3 wants grunt@~0.4.0
npm ERR! peerinvalid Peer grunt-contrib-watch@0.6.1 wants grunt@~0.4.0

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/include/npm-debug.log
```
And it return a error too
```
npm ls -g --depth=0
/usr/lib
├── UNMET DEPENDENCY node_modules@*
└── npm@2.10.0

npm ERR! missing: node_modules@*, required by undefined@undefined
```

**Comment by SFoster84** [comment]
Hi sitvyw, you may need to upgrade grunt with a command like: npm install grunt@latest which should install grunt 0.4.5

**Comment by stivyw** [comment]
It not fixed. But I have fixed it now.
Error 1 I changed the owner from `~/.npm/_locks` directory to my user. So, I do that.
`sudo chown stivyw:stivyw -R ~/.npm`
Error 2. removing the directory node_modules
sudo rm /usr/lib/node_modules/node_modules
Maybe, the second error was the bad install :(
I'm very curious
Seja lecal.

**Comment by stivyw** [comment]
How...Thanks very much @SFoster84 .

**Comment by SFoster84** [comment]
Hi Stivyw, thanks for sharing your answer - I tried deleting C:\Windows\system32\config\systemprofile\AppData\Roaming\npm-cache\_git-remotes and then re-running, I got the same error so I checked permissions and it seems ok.  Not sure why I keep getting the same error.
