### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by ianrobbs** [npm/npm#8297]
From the command prompt I entered the following command but keep getting the following errors:

C:\Windows\system32>npm install -g cordova ionic
npm WARN engine cordova-js@3.9.0: wanted: {"node":"~0.10.x"} (current: {"node":"
0.12.3","npm":"2.9.1"})
npm WARN engine npm@1.3.4: wanted: {"node":">=0.6","npm":"1"} (current: {"node":
"0.12.3","npm":"2.9.1"})
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {
"node":"0.12.3","npm":"2.9.1"})
npm ERR! tar.unpack error reading C:\Users\Ian\AppData\Roaming\npm-cache\estrave
rse\1.9.3\package.tgz
npm WARN installMany normalize-package-data was bundled with npm@1.3.4, but bund
led package wasn't found in unpacked tree
npm WARN engine cordova-js@3.8.0: wanted: {"node":"~0.10.x"} (current: {"node":"
0.12.3","npm":"2.9.1"})
npm WARN engine npm@1.3.4: wanted: {"node":">=0.6","npm":"1"} (current: {"node":
"0.12.3","npm":"2.9.1"})
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {
"node":"0.12.3","npm":"2.9.1"})
npm WARN installMany normalize-package-data was bundled with npm@1.3.4, but bund
led package wasn't found in unpacked tree
C:\Users\Ian\AppData\Roaming\npm\ionic -> C:\Users\Ian\AppData\Roaming\npm\node_
modules\ionic\bin\ionic
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova" "ionic"
npm ERR! node v0.12.3
npm ERR! npm  v2.9.1
npm ERR! code EBADF
npm ERR! errno -4083

npm ERR! EBADF, fstat
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\system32\npm-debug.log

**Comment by KenanY** [comment]
@ianrobbs Perhaps https://github.com/npm/npm/issues/7472#issuecomment-76510381 by @smikes could help?:

> EBADF is a bad file descriptor; and this error is coming from `node` without going through a javascript stack trace. So my first suggestion would just be to reboot and try again, on the possibility that there's something weird with your filesystem.

**Comment by niradler** [comment]
same problem here...

**Comment by ianrobbs** [comment]
@KenanY Thanks. I ran it from the node program folder and it seems to have worked. Don't know if it was something to do with permissions or my laptop just thrown a funny, but it's working now.

**Comment by niradler** [comment]
im still having the same issue...is this what u did ?
C:\Program Files\nodejs>npm install -g cordova

**Comment by ianrobbs** [comment]
Yes but I'm using ionic so my command line is:

npm install -g cordova ionic 

I dont know whether it makes a difference but i also reinstalled nodejs 32-bit version. Sorry I can't pinpoint exactly what fixed it but these were the steps I took to fixing it.

**Comment by niradler** [comment]
reinstall and try again from the folder same problem....

**Comment by smikes** [comment]
Sometimes people find that downgrading to the previous stable version (0.10.38) helps.  Could you try that and let me know if it helps?

**Comment by niradler** [comment]
i dont have explanation but now it working :/

**Comment by niradler** [comment]
im still getting the warn message but all function correctly to my knowledge

**Comment by imsho** [comment]
Make sure that you are not using "ionic serve" command during update :)

**Comment by gengjiawen** [comment]
Install it from the node program folder fixed for me.

**Comment by anupsalpe** [comment]
I was also facing same issue. 
Now install it from 'C:\Program Files\nodejs\node_modules>npm install -g cordova' worked for me :)

**Comment by johny1410** [comment]
execut cmd in administrator!

**Comment by AstmDesign** [comment]
guys i have the same error on mac

npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"5.0.0","npm":"3.3.6"})

how I can fix it ?

**Comment by johny1410** [comment]
Execute in mode administrator
Em 31/10/2015 08:57, "Astm" <notifications@github.com> escreveu:

**Comment by BDominik** [comment]
I had the same error, but after several minutes downloaded and installed it. :)
