### ISSUE TITLE
Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by CaitlinS9** [npm/npm#8298]
I get this error when trying to install. Every couple of times I try I get a git error but I have git installed. 

```
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\Caitlin>cd..

C:\Users>cd..

C:\>npm install -g javascripting
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_mod
ules\\npm\\bin\\npm-cli.js" "install" "-g" "javascripting"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4

npm ERR! Cannot read property 'trim' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "javascripting"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4

npm ERR! Uncaught, unspecified "error" event.
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\npm-debug.log

C:\>npm install -g javascripting
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_mod
ules\\npm\\bin\\npm-cli.js" "install" "-g" "javascripting"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4

npm ERR! Cannot read property 'trim' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "javascripting"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4

npm ERR! Uncaught, unspecified "error" event.
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\npm-debug.log

C:\>
```

**Comment by KenanY** [comment]
@CaitlinS9 I am fairly confident that [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows) will solve this issue.

**Comment by CaitlinS9** [comment]
After uninstalling and re-installing everything and upgrading I now get this error:

Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>cd..

C:\Windows>cd..

C:\>npm install -g javascripting
C:\Users\Caitlin\AppData\Roaming\npm\javascripting -> C:\Users\Caitlin\AppData\R
oaming\npm\node_modules\javascripting\index.js
javascripting@2.0.1 C:\Users\Caitlin\AppData\Roaming\npm\node_modules\javascript
ing
├── diff@1.4.0
├── colors@1.1.0
├── cli-md@0.1.0 (marked@0.3.3, chalk@0.5.1, concat-stream@1.4.8, cardinal@0.4.4
)
└── workshopper-adventure@3.4.2 (map-async@0.1.1, xtend@3.0.0, through@2.3.7, mk
dirp@0.3.5, minimist@1.1.1, visualwidth@0.0.1, simple-terminal-menu@1.0.0, chalk
@0.4.0, colors-tmpl@0.1.1, combined-stream@0.0.7, i18n-core@1.3.3, terminal-menu
@2.1.1, msee@0.1.1)

C:\>

**Comment by KenanY** [comment]
@CaitlinS9 I do not see an error in that output.

**Comment by CaitlinS9** [comment]
Okay, thanks!

**Comment by othiym23** [comment]
Things are installed correctly now! You should be able to run `javascripting` at the `C:>` prompt and start up the workshopper.

Closing as resolved.
