### ISSUE TITLE
npm Installation

### ISSUE THREAD

**Issue by Noeza** [npm/npm#8301]
```
mcheart@mcheart-Vostro-2521 ~ $ npm install -g yo
npm ERR! Error: getaddrinfo EIO
npm ERR!     at errnoException (dns.js:37:11)
npm ERR!     at Object.onanswer [as oncomplete] (dns.js:124:16)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.13.0-37-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "-g" "yo"
npm ERR! cwd /home/mcheart
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! syscall getaddrinfo
npm ERR! code EIO
npm ERR! errno EIO
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/mcheart/npm-debug.log
npm ERR! not ok code 0
```

**Comment by KenanY** [comment]
@Noeza From https://github.com/npm/npm/issues/6782#issuecomment-64277037:

> `EIO` is a low-level Node / libuv / libc error indicating that something is seriously wrong with the running OS's disk I/O. If you can, try restarting the instance and see if the problem persists. This error is not raised by npm itself, so if that doesn't fix it, take a look at your Node installation.

**Comment by othiym23** [comment]
Are you running on Elastic Beanstalk or AWS Lambda, by any chance? You may be running into an issue where some network operations are restricted. If you can convince the containerization system you're using to update to a newer version of Node or npm, there are some tweaks to recent versions of  `npm@2` that might make this problem go away. See #8094 for more discussion.

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
