### ISSUE TITLE
npm install with prefix

### ISSUE THREAD

**Issue by chrismcv** [npm/npm#8304]
I'm trying to lay out a project structure with multiple local packages, I'd like them to share the same node_modules folders so that npm install is fast, and disk space usage is moderate. Each package when used standalone has a few hundred MB of dependencies.

```
node_modules
main
  - package.json
packages
  lib1
    - package.json
  lib2
    - package.json
```

As an example each package depends on react, gulp and webpack, which will be defined as dependencies in each package.json.

I'm trying to work out how to have an easy script to install each packages dependencies into node_modules, but I can't make it work.

```
cd main
echo "prefix = .." > .npmrc
npm install 
for each in packages
  cd package
  echo "cat prefix = .." > .npmrc
  npm install
```

However, I can't make it work.

npm install --prefix .. also doesn't work without a package name, but as I'm trying to make this install all packages after a clone, it doesn't work.

Using local dependencies e.g. `"lib1": "./path/to/lib1"` seems to create copies of `lib1` rather than installing lib1's dependencies.

**Comment by smikes** [comment]
Maybe linking the common modules (see https://docs.npmjs.com/cli/link ) would be a better solution?  

What you are trying to is like working against the grain of the wood; `npm` is going to resist and/or fail.

**Comment by iarna** [comment]
Related to #8036

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
