### ISSUE TITLE
Dependency Issue?

### ISSUE THREAD

**Issue by SERVANT14** [npm/npm#8306]
Working with a fresh install of Laravel's Homestead. Running npm install on a fresh install of Laravel...

> node-sass@3.1.1 install /home/vagrant/Code/tdi/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /home/vagrant/Code/tdi/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-14/binding.node

> node-sass@3.1.1 postinstall /home/vagrant/Code/tdi/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js

` /home/vagrant/Code/tdi/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-14/binding.node ` exists.
 testing binary.
Binary is fine; exiting.
npm ERR! Linux 3.16.0-23-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4

npm ERR! shasum check failed for /tmp/npm-2375-ada527d4/registry.npmjs.org/node-notifier/-/node-notifier-3.4.1.tgz
npm ERR! Expected: ec0ba696bd6097aaf7c6c3e58b23c849f334bda1
npm ERR! Actual:   d55d891e5c0de3ae508c0d6bb7b9d5b3b4a9629a
npm ERR! From:     https://registry.npmjs.org/node-notifier/-/node-notifier-3.4.1.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 3.16.0-23-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! path npm-debug.log.a0d240319a24a5322fcd08e7e107d9d3
npm ERR! code ETXTBSY
npm ERR! errno -26

npm ERR! ETXTBSY, rename 'npm-debug.log.a0d240319a24a5322fcd08e7e107d9d3'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/Code/tdi/npm-debug.log

**Comment by SERVANT14** [comment]
Strange. Ran it again and it worked.

**Comment by shahidkhan021** [comment]
is there any way to install laravel-elixir bit by bit
