### ISSUE TITLE
npm install dep issue (Vagrant + symlinks)

### ISSUE THREAD

**Issue by bojank** [npm/npm#8307]
Im having a issue with NPM install on a vagrant box ( Ubuntu/trusty64 ) I create a symbolic link from my project folder /vagrant/project/node_modules to ~/node_modules_project then try running npm install. it installs almost all dependencies required but fails to get some child dependencies or my dependencies.

If I remove the symlink, and run npm install it installs everything. Anyone have a clue what is going on?

**Comment by othiym23** [comment]
`npm install` leaves packages that are symbolically linked into the current tree alone (by design). If you want to ensure that all of the dependencies of a linked directory are installed, you'll need to `cd` into that directory and run `npm install` or `npm update` there.
