### ISSUE TITLE
npm install --color=false does not carry over into postinstall

### ISSUE THREAD

**Issue by SimenB** [npm/npm#8310]
Not sure how you'd solve this, but still!

![image](https://cloud.githubusercontent.com/assets/1404810/7711966/7956f488-fe6e-11e4-8f2b-9df2ede9dae8.png)

Also not a real problem for me, just unexpected

**Comment by othiym23** [comment]
This is a bug! Running `npm --color=false` should set an environment variable to false: `npm_config_color=false`, that would be picked up by npm invocations being run by lifecycle scripts. But:

```
bauchelain% npm --color=false run env | grep npm_config_color
npm_config_color=
```

If you run `npm_config_color=false npm install`, the postinstall script should no longer be printing color output.

If you want to try fixing this (which would be great), take a look in `lib/config.js` and see if anything in there (or in the `config-chain` module used by the configuration) looks obviously out of whack. We'll fix this at some point, but might not get to it soon.

**Comment by SimenB** [comment]
I'd love to give fixing this a try! I'll poke around :smile:

**Comment by othiym23** [comment]
This has been moved to the [npm roadmap](https://github.com/npm/npm/wiki/Roadmap), which we're using instead of the confusing `next-*` labels now.

**Comment by gronke** [comment]
:+1:
