### ISSUE TITLE
npm won't run in PowerShell

### ISSUE THREAD

**Issue by garhbod** [npm/npm#8312]
Get the following error even if I am in the directory that npm exists

```
PS C:\Program Files\nodejs> dir


    Directory: C:\Program Files\nodejs


Mode                LastWriteTime     Length Name
----                -------------     ------ ----
d----        14/05/2015   7:19 AM            node_modules
-a---        31/03/2015  10:56 PM   11104640 node.exe
-a---        12/03/2015   3:37 AM        697 nodevars.bat
-a---        12/03/2015   3:37 AM       6612 node_etw_provider.man
-a---        12/03/2015   3:37 AM       4974 node_perfctr_provider.man
-a---        12/03/2015   3:37 AM        354 npm
-a---        12/03/2015   3:37 AM        209 npm.cmd


PS C:\Program Files\nodejs> npm.cmd
Program 'npm.cmd' failed to execute: The system cannot find the file specified
At line:1 char:8
+ npm.cmd <<<< .
At line:1 char:1
+  <<<< npm.cmd
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
```

**Comment by smikes** [comment]
What happens if you reboot, then run `npm` in Powershell?

```
PS C:\Program Files\nodejs> npm
```

The reboot is to ensure that changes to PATH and registry are seen by the new instance of PowerShell; and you probably don't need the `npm.cmd` version since that's only needed if you are using `cmd.exe`

**Comment by garhbod** [comment]
Makes no difference after restart. Even navigating to the folder that contains npm and using the command `.\npm` produces the same error.

**Comment by garhbod** [comment]
Node works. npm doesn't
```
PS C:\Users> node -v
v0.12.2
PS C:\Users> npm -v
Program 'npm.cmd' failed to execute: The system cannot find the file specified
At line:1 char:4
+ npm <<<<  -v.
At line:1 char:1
+  <<<< npm -v
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed

PS C:\Users>
```

**Comment by garhbod** [comment]
Found solution. A while back someone suggested creating an environment variable called NODE_PATH. Long story short I got rid of that variable and it's all good

**Comment by garhbod** [comment]
Actually it was my ComSpec variable that had PowerShell path in it for some reason

**Comment by ehsalazar** [comment]
Good to hear. I'll close this for now as we’re trying to clean up some old issues. We’ll be happy to reopen if necessary.

**Comment by abhijeetbhanjadeo** [comment]
Hi Team,

I happen to encounter this issue in following environment: Windows 7 Professional(64 bit) but running 32-bit Node versioned as v6.6.0 & npm version as 3.10.3.

I was executed the same command to inside "Powershell - 32bit", I re-installed couple of times but to no-avail. I need this to install "https://github.com/felixrieseberg/windows-build-tools" from powershell. 

![2016-11-02 21_27_06-administrator_ windows powershell](https://cloud.githubusercontent.com/assets/7709297/19930507/bf52dd8e-a143-11e6-80d4-5d915e4ea1f2.png)
![2016-11-02 21_27_49-administrator_ c__windows_system32_cmd exe](https://cloud.githubusercontent.com/assets/7709297/19930518/c4605a54-a143-11e6-93fc-624cad530757.png)
