### ISSUE TITLE
npm publish should fail when bundledDependencies out of sync with package.json

### ISSUE THREAD

**Issue by othiym23** [npm/npm#8315]
Right now it's possible to publish packages with `bundledDependencies` that will immediately cause `npm ls` to exit with unsatisfied dependency errors once the package is installed. npm itself has tests to guard against this problem, but this is something that a preflight check should really prevent. `npm@3` is better about filling in missing dependencies when installing a package with `bundledDependencies`, but there are going to be a lot of non-`npm@3` clients out there for years to come.

**Comment by othiym23** [comment]
See #8241 for an example of how this is a problem in practice.

**Comment by othiym23** [comment]
This is also related to #7887.

**Comment by stefanpenner** [comment]
:+1:

**Comment by othiym23** [comment]
This has been moved to the [npm roadmap](https://github.com/npm/npm/wiki/Roadmap), which we're using instead of the confusing `next-*` labels now.
