### ISSUE TITLE
not found:git while running npm installnode-xmpp

### ISSUE THREAD

**Issue by Harshavalli** [npm/npm#8317]

**Comment by KenanY** [comment]
@Harshavalli So, [not a lot](https://github.com/npm/npm/wiki/Contributing-Guidelines#a-great-bug-report-contains) of information here, so I'm shooting in the dark, but do you have `git` installed?

**Comment by Harshavalli** [comment]
Yes I have installed git. But somehow it is not finding it.

**Comment by KenanY** [comment]
@Harshavalli Is it in your `PATH`? Is there a `npm-debug.log` that you can upload as a [gist](https://gist.github.com)?

**Comment by Harshavalli** [comment]
Hello,I have set the path for Git in  System variables.But it is not finding it.. 
Regards,Harsha
 


     On Thursday, 21 May 2015 9:30 PM, Kenan Yildirim <notifications@github.com> wrote:
   

 @Harshavalli Is it in your PATH? Is there a npm-debug.log that you can upload as a gist?—

**Comment by KenanY** [comment]
@Harshavalli Are you able to run `git --version` in the command-line?

**Comment by Harshavalli** [comment]
Yes.very much so. it is showing git version 1.9.5.github.0

**Comment by Harshavalli** [comment]
Hello,In the node-js command prompt  I am unable to run git --version.But in the Dos command prompt ,I am able to run git --version.
Harsha 


     On Monday, 25 May 2015 8:17 PM, Kenan Yildirim <notifications@github.com> wrote:
   

 @Harshavalli Are you able to run git --version in the command-line?—
