### ISSUE TITLE
Can't run 

### ISSUE THREAD

**Issue by dhruvbird** [npm/npm#8331]
```
Every time I run "npm adduser", I get the following error:

npm http PUT https://registry.npmjs.org/-/user/org.couchdb.user:dhruvbird
npm http 400 https://registry.npmjs.org/-/user/org.couchdb.user:dhruvbird
npm ERR! Error: Unknown error while authenticating : -/user/org.couchdb.user:dhruvbird
npm ERR!     at RegClient.<anonymous> (/home/dhruvbird/bin/node-v0.10.20/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:272:14)
npm ERR!     at Request.self.callback (/home/dhruvbird/bin/node-v0.10.20/lib/node_modules/npm/node_modules/request/request.js:129:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/home/dhruvbird/bin/node-v0.10.20/lib/node_modules/npm/node_modules/request/request.js:873:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/home/dhruvbird/bin/node-v0.10.20/lib/node_modules/npm/node_modules/request/request.js:824:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

...
npm ERR! command "/home/dhruvbird/bin/node-v0.10.20/bin/node" "/home/dhruvbird/bin/node-v0.10.20/bin/npm" "adduser"
npm ERR! cwd /home/dhruvbird/projects/http-sync
npm ERR! node -v v0.10.20
npm ERR! npm -v 1.3.11
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/dhruvbird/projects/http-sync/npm-debug.log
npm ERR! not ok code 0
```

**Comment by othiym23** [comment]
`npm@1.3.11` is no longer supported, so you should probably start by upgrading to `npm@2` (the latest stable version is `npm@2.10.0`), and which works fine with Node 0.10.20. On top of that, it's possible your password is so old that the new registry architecture can't work with it, in which case you'll need to go to the web site and [reset it](https://www.npmjs.com/forgot). If you try both of those things and you're still unable to log in, contact support@npmjs.com, and we'll get you sorted out.

**Comment by dhruvbird** [comment]
I downloaded the latest node.js (v0.12.3) from https://nodejs.org/download/ and that too comes with npm v1.3.11. Am I doing something wrong? Where can I get the latest npm from, and why isn't it bundled with the latest node.js distribution?

**Comment by othiym23** [comment]
What Node version manager are you using? Node 0.12.3 is packaged with `npm@2.9.1`, so if you use the default installer, that's the version of npm you should end up with. If you want to upgrade npm independently of Node, run `npm install -g npm`, prefacing it with `sudo` if your node directory is owned by a user other than your account (`ls -ld $(npm -g root)` to check).

**Comment by dhruvbird** [comment]
eeks, sorry my bad. I was running 'npm' instead of './npm'. The version is 2.9.1 as you mentioned!
Sorry about the bother, and thanks for resolving this so quickly. adduser now works for me!
