### ISSUE TITLE
Problems with the nmp install. 

### ISSUE THREAD

**Issue by Stella33** [npm/npm#8334]
stelladeAir:~ Stella$ npm install -g browser-sync
npm WARN locking Error: EACCES, open '/Users/Stella/.npm/_locks/browser-sync-ed941186c435fb34.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/Stella/.npm/_locks/browser-sync-ed941186c435fb34.lock failed { [Error: EACCES, open '/Users/Stella/.npm/_locks/browser-sync-ed941186c435fb34.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/Stella/.npm/_locks/browser-sync-ed941186c435fb34.lock' }
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "browser-sync"
npm ERR! node v0.12.3
npm ERR! npm  v2.10.0

npm ERR! Attempt to unlock /usr/local/lib/node_modules/browser-sync, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Stella/npm-debug.log
stelladeAir:~ Stella$ $sudo chown -R $(whoami) ~/.npm
chown: /Users/Stella/.npm/_locks: Operation not permitted

**Comment by Futurial** [comment]
try 'sudo nmp install'
