### ISSUE TITLE
apm update and getaddrinfo ESRCH errors

### ISSUE THREAD

**Issue by fusion809** [npm/npm#8335]
I am trying to update my Atom packages using: 
`apm update`
but I get the error:
`Request for package information failed: getaddrinfo ESRCH`
Updating them via the GUI package manager fails too. 

| Specification name | Value                                                               |
| ------------------------- | ------------------------------------------------------------:|
| Operating system   | 32-bit Ubuntu 15.04                                         |
| RAM                       | 3.8 GB                                                              |
| Processor               | Intel® Core™ i5 CPU M 460 @ 2.53GHz × 4  |
| Graphics                 | Intel® Ironlake Mobile x86/MMX/SSE2            |

**Comment by laosb** [comment]
apm? npm?

**Comment by fusion809** [comment]
Sorry? Should I posted an issue about APM somewhere else?

**Comment by laosb** [comment]
You may post this to https://github.com/atom/atom , which is the repo of Atom editor(apm is a part of Atom).

**Comment by othiym23** [comment]
As this is an issue with apm, we're going to close it. Good luck getting it sorted out, though!
