### ISSUE TITLE
Docs: none of the "See also" list items are links?

### ISSUE THREAD

**Issue by kevinSuttle** [npm/npm#8338]
For example: 
![screen shot 2015-05-22 at 2 43 20 pm](https://cloud.githubusercontent.com/assets/95672/7778449/0590691a-0091-11e5-83ac-30202770f35a.png)

It would make sense that these are links, right? I'm not sure what the docs build looks like, or if there is a way to automate this, but I always try to click on them and remember that they're not links. Feels like they should be, though.

**Comment by othiym23** [comment]
This is an issue for the `docs` repo, and is already open as npm/docs#106. I agree, that would be useful!

**Comment by kevinSuttle** [comment]
Ah, ok. Maybe I should make another issue, because this is where 'Pull request' link took me. :)
