### ISSUE TITLE
Warn when package size is over (configurable) size?

### ISSUE THREAD

**Issue by seldo** [npm/npm#8339]
This exchange on twitter is hardly unique:
https://twitter.com/mrvautin/status/601921102546239491

Would it be a good idea to have npm warn when a package is over a certain threshold (say, 50MB? 99% of packages are smaller than this). The limit could be configurable to prevent annoying users who routinely publish large packages.

**Comment by mrvautin** [comment]
Absolutely. My total package was 93mb with the hidden folder making up 92mb of that. Silly me.

**Comment by ChALkeR** [comment]
I think that this should be implemented, in either a blocking (if possible, see #8617) or non-blocking mode. If the blocking mode is possible, we might want two thresholds — for a notice (i.e. 10 MiB unpacked) and for a warning (i.e. 50 MiB unpacked).

The configuration could go in `.npmrc`.

**Comment by thefourtheye** [comment]
+1

**Comment by ChALkeR** [comment]
Some examples:

 * https://github.com/JamenMarz/HTTP-Goose/issues/2 — 3.1 GiB MongoDB data dir.
 * https://github.com/petejohanson/angular-hy-res/issues/12 — 1.1 GiB coredump.
 * https://github.com/mtth/layer2/issues/4 — 475 MiB of pcap files.
 * https://github.com/guyellis/multi-level-cache/issues/20 — 250 MiB static unrelated site copy.
 * https://github.com/clear-code/sharetary/issues/5 — 271 MiB database.
 * https://github.com/infolis/mongoose-jsonld-express/issues/1 — 289 MiB MongoDB database.
 * https://github.com/jeef3/team-time/issues/1 — 161 MiB MongoDB database.
 * https://github.com/bnfinet/docker-dns/issues/11 — 82 MiB logs.
 * https://github.com/nickbabcock/jomini/issues/1 — 172 MiB total size, mostly tmp files.
 * https://github.com/ember-cli/ember-cli/issues/4199 — at least 2.8 GiB in `ember-***` packages, from 0 MiB to 621 MiB per package, 87 packages total, some of them listed below
  * https://github.com/srsgores/ember-accessible-icon/issues/2 — 522 MiB tmp dir (`ember-***`).
  * https://github.com/rwwagner90/ember-shepherd/issues/15 — 621 MiB tmp dir (`ember-***`).
  * https://github.com/bbooth/ember-cli-flot/issues/3 — 243 MiB tmp dir (`ember-***`).
  * https://github.com/thefrontside/emberx-select/issues/23 — 176 MiB tmp dir (`ember-***`).
  * https://github.com/jherdman/ember-cli-trackjs/issues/10 — 172 MiB tmp dir (`ember-***`).
  * https://github.com/lazybensch/ember-cli-sync-for-each/issues/3 — 117 MiB tmp dir (`ember-***`).

**Comment by ChALkeR** [comment]
It would be cool if this went into npm 3 release, see https://github.com/npm/npm/issues/8617#issuecomment-113605798.

**Comment by ChALkeR** [comment]
Another nice thing to have would be a _packageSize and _unpackedSize properties in `package.json`. Those, probably, would be approximate, as adding extra lines to `package.json` would change the package size by itself, but ± a few bytes would be ok. Not sure if this needs a separate issue.

**Comment by othiym23** [comment]
I don't think making this configurable makes a lot of sense – we've got a pretty solid idea of what package sizes cause problems (anything bigger than ~120MiB compressed causes problems for both the CLI and the registry, and anything above ~5MiB compressed is an outlier and probably merits a warning). I think this an example of an error that can be overridden with `--force` (although maybe, based on our experiences with npmE, we want to spell that `--enterprise-mode` instead in this case).

@ChALkeR, thanks for compiling that list. It does indeed make clear that in most cases where large publishes happen (and somehow succeed), it's frequently unintentional.

> It would be cool if this went into npm 3 release

It won't be part of `npm@3.0.0`, for the same reasons I set out in #8617. There's nothing saying this couldn't be added as a `semver-minor` fix, either to `npm@2` or `npm@3` (or higher), but the npm team probably won't get to this super soon themselves, as other projects are higher-priority.

> Another nice thing to have would be `_packageSize` and `_unpackedSize` properties in `package.json`.

The right place to calculate and display these properties is probably on the registry, as it's in the best place to make authoritative statements about what it's actually hosting. I'll create an issue on our internal tracker for that.

**Comment by ChALkeR** [comment]
@othiym23 Checking just the compressed size won't fix everything. Check the list above, for example https://github.com/infolis/mongoose-jsonld-express/issues/1 is 296 KiB packed, 289 MiB unpacked. MongoDB preallocates files and those are mostly empty if there is not much data in there.

**Comment by ChALkeR** [comment]
@othiym23, about `_packageSize` and `_unpackedSize`:
> I'll create an issue on our internal tracker for that.

Thanks =).

**Comment by othiym23** [comment]
> Checking just the compressed size won't fix everything.

Good point. Checking the unpacked size is a little trickier, and should have a separate warning, but would still be useful.

**Comment by othiym23** [comment]
This has been moved to the [npm roadmap](https://github.com/npm/npm/wiki/Roadmap), which we're using instead of the confusing `next-*` labels now.

**Comment by ChALkeR** [comment]
https://github.com/npm/npm/issues/6252 — same issue?

**Comment by othiym23** [comment]
This would indeed be handy to have, but it doesn't fit into what the CLI team has planned for the next 6-12 months. As such, I'm going to close this issue out, with the understanding that if somebody really wants to see this land sooner, because `patch-welcome` is tagged onto this, we'd be very happy to review and land a PR that adds this feature. Thanks to all for the discussion!
