### ISSUE TITLE
NPM thinks last published version is the latest version.

### ISSUE THREAD

**Issue by budhajeewa** [npm/npm#8342]
If you publish `x.x.2` first and `x.x.1` second, NPM will think `x.x.1` is the latest version. It doesn't respect Semver.

The bug is not in the CLI; for the website also displays `x.x.1` as the latest version.

**Comment by KenanY** [comment]
@budhajeewa `latest` does not equal "highest". `x.x.1` would indeed be the _newest_ thus _latest_ release. SemVer does not have a definition of "latest" as far as I know, so I'm not sure why this is an example of not respecting SemVer?

Relevant discussion from a couple years ago: https://github.com/npm/npm/issues/3397

**Comment by iarna** [comment]
Thanks for keeping an eye out for issues @budhajeewa, but as @KenanY says, this is intended behavior. "latest" is just the default tag when you publish, but you can publish with other tags if you prefer.

**Comment by budhajeewa** [comment]
@KenanY & @iarna , thanks for your replies.

After reading through #3397, I understand the reason for not changing this behaviour.

If I were there when the decision was taken to follow this when you started this, I'd have strongly opposed. But done is done. Thanks again. :smile:
