### ISSUE TITLE
npm ERR! when using private GitHub repository as dependency

### ISSUE THREAD

**Issue by decafdennis** [npm/npm#8345]
We use a private GitHub repository as a dependency. No matter how we specify the dependency (GitHub short form, `git://` URL, `git+ssh://` URL) in `package.json`, we get the following error (redacted):

```
$ npm install
npm ERR! git clone --template=/Users/dennis/.npm/_git-remotes/_templates --mirror git://github.com/my-org/my-mod.git /Users/dennis/.npm/_git-remotes/git-github-com-my-org-my-mod-git-12345678
```

*The package installs just fine.* The only problem here is that the error is displayed.

This is what our `package.json` looks like:

```json
{
  "private": true,
  "dependencies": {
    "my-mod": "my-org/my-mod"
  },
  "engines": {
    "node": ">= 0.10"
  }
}
```

By running `$ npm install --loglevel verbose` we figured out that when npm believes it is a GitHub repository, it always first attempts to clone using a `git://` URL, no matter how it's specified in `package.json`. When it fails, it then attempts to clone using a `git+ssh://` URL, which—unlike the previous attempt—does work for private repos.

It's not a blocker, but it would make us feel better if our `$ npm install` was free of errors.

**Comment by KenanY** [comment]
@decafdennis `npm --version`?

**Comment by decafdennis** [comment]
@KenanY 
```
$ npm --version
2.7.5
```

**Comment by KenanY** [comment]
@decafdennis Does this also occur on the latest stable release? https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm

**Comment by decafdennis** [comment]
Using the latest stable release fixes the problem. Doh. Thanks! Moving on...
