### ISSUE TITLE
can't install yo bower gulp etc

### ISSUE THREAD

**Issue by sudhinsr** [npm/npm#8346]
Iam getting following error while try to install these packages 

```
sudhin@sudhin:~$ npm install -g yo bower gulp nodemon generator-gulp-aangular
npm ERR! Linux 3.19.0-18-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "yo" "bower" "gulp" "nodemon" "generator-gulp-aangular"
npm ERR! node v0.13.0-pre
npm ERR! npm  v2.10.1
npm ERR! code EHOSTUNREACH
npm ERR! errno EHOSTUNREACH
npm ERR! syscall connect

npm ERR! connect EHOSTUNREACH
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sudhin/npm-debug.log
```

**Comment by KenanY** [comment]
@sudhinsr I believe `EHOSTUNREACH` is an error code pertaining to a failure in establishing a network connection. The lack of a JavaScript stack trace demonstrates how this is probably not a `npm` issue.

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
