### ISSUE TITLE
Unable to  install http-server using npm but npm command is working fine

### ISSUE THREAD

**Issue by krishnapremram** [npm/npm#8349]
```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "http-server" "-g"
npm ERR! node v0.12.3
npm ERR! npm  v2.9.1
npm ERR! code UNABLE_TO_VERIFY_LEAF_SIGNATURE

npm ERR! unable to verify the first certificate
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\prem.batchu\Desktop\npm-debug.log
```

**Comment by KenanY** [comment]
@krishnapremram Does running

``` sh
$ npm config set ca ""
```

solve this issue?

**Comment by krishnapremram** [comment]
Hello Kenan,


I’m trying to install in  windows machine.
Not yet resolved

**Comment by CodeTheInternet** [comment]
@KenanY I am having a similar issue with a different package. Removing the CA as you indicated did not help.

    $ npm install jshint
    npm ERR! Darwin 13.4.0
    npm ERR! argv "node" "/usr/local/bin/npm" "install" "jshint"
    npm ERR! node v0.12.3
    npm ERR! npm  v2.9.1
    npm ERR! code UNABLE_TO_VERIFY_LEAF_SIGNATURE

**Comment by busches** [comment]
No traction for a year, I assume this is fixed for everyone involved and can be closed?

**Comment by KenanY** [comment]
Closing as abandoned.
