### ISSUE TITLE
Unable to update appbuilder on MacBook Pro (13 inch, Late 2011) OSX Yosemite (10.10.3)

### ISSUE THREAD

**Issue by umeshchand1507** [npm/npm#8352]
Hello,
I'm not able to update appbuilder on my machine as getting following error:

Universals-MacBook-Pro-2:~ uchand$ sudo npm update -g appbuilder
Password:
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "update" "-g" "appbuilder"
npm ERR! node v0.12.3
npm ERR! npm  v2.9.1

npm ERR! shasum check failed for /tmp/npm-8875-5ad83448/registry.npmjs.org/appbuilder/-/appbuilder-2.9.3-426.tgz
npm ERR! Expected: 859ff93a605d4b04e7f2f265b0028d2ea53c9ba9
npm ERR! Actual:   e8152a67062f37e8e631cc73f160f7dd300034ea
npm ERR! From:     https://registry.npmjs.org/appbuilder/-/appbuilder-2.9.3-426.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by KenanY** [comment]
@umeshchand1507 Could you first try running `npm cache clean`?

**Comment by umeshchand1507** [comment]
@KenanY Thank you it works.
