### ISSUE TITLE
Unable to install Cordova on windows

### ISSUE THREAD

**Issue by futhrevo** [npm/npm#8362]
I am trying to install cordova on my PC but I keep on getting error

````
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "--verbose" "install" "-g" "cordova"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect

npm ERR! network connect ETIMEDOUT
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
````

I am able to ping to registry, and proxy and http proxy both are null
user-agent = "npm/2.10.1 node/v0.12.4 win32 x64"

**Comment by Jonrock23** [comment]
![image](https://cloud.githubusercontent.com/assets/11978110/7830883/8b2c7b18-0451-11e5-8726-1c18632af7da.png)

I am also having the same issue. However, I am behind a proxy.

**Comment by snopeks** [comment]
Hello @futhrevo, were you able to configure your proxy with npm? We’re trying to clean up some issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary. Thanks. -Stephanie, npm Tech Support
