### ISSUE TITLE
NPM Install Error

### ISSUE THREAD

**Issue by nonofficialcover** [npm/npm#8368]
5973 verbose fetch to= /root/tmp/npm-32385/1432688716535-0.9407456060871482/tmp.tgz
5974 http GET https://registry.npmjs.org/read/-/read-1.0.6.tgz
5975 http GET https://registry.npmjs.org/lru-cache/-/lru-cache-2.6.4.tgz
5976 error Error: No compatible version found: minimist@'^1.1.0'
5976 error Valid install targets:
5976 error ["0.0.0","0.0.1","0.0.2","0.0.3","0.0.4","0.0.5","0.0.6","0.0.7","0.0.8","0.0.9","0.0.10","0.1.0","0.2.0","1.0.0","1.1.0","1.1.1"]
5976 error     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:553:10)
5976 error     at /usr/local/lib/node_modules/npm/lib/cache.js:477:15
5976 error     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
5976 error     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:220:7
5976 error     at Object.oncomplete (fs.js:297:15)
5977 error If you need help, you may report this log at:
5977 error     <http://github.com/isaacs/npm/issues>
5977 error or email it to:
5977 error     <npm-@googlegroups.com>
5978 error System Linux 3.11.0-15-generic
5979 error command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "forever"
5980 error cwd /root/Nova/node-v0.8.5
5981 error node -v v0.8.5
5982 error npm -v 1.1.46
5983 verbose exit [ 1, true ]
***************************************
Thank you in advance!

**Comment by KenanY** [comment]
@nonofficialcover Your versions of Node.js and `npm` are _soooooo_ old! All you need to do to fix this particular issue is [update `npm`](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm), but I recommend you also [upgrade Node.js](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-node) for the sake of security patches.

**Comment by nonofficialcover** [comment]
Thanks @KenanY , I'll try that. I hope it doesn't affect the system I'm trying to setup.
What bothers me though is that I use the same versions of npm and node on the same installation procedure for about 6 identical systems, and it went well.
I'll let you know how it turns out. Cheers!

**Comment by nonofficialcover** [comment]
It worked ;) thanks @KenanY !
