### ISSUE TITLE
Static site - Not able to run

### ISSUE THREAD

**Issue by somudcis** [npm/npm#8371]
$ 'make build' is not working for me. It says "'make' is not recognized as an internal or external command, operable program or batch file."

And also how do you run static site "\metalsmith-master\examples\static-site" without any .js file

Note: I've npm and node installed in my system.

**Comment by KenanY** [comment]
@somudcis How is this an issue with `npm`?

> "'make' is not recognized as an internal or external command, operable program or batch file."

Do you have `make` installed?

> how do you run static site "\metalsmith-master\examples\static-site" without any .js file

Maybe ask metalsmith authors about this? I don't understand why you want to "run" a static site without using js.

**Comment by somudcis** [comment]
@KenanY 

I'm completely new to metalsmith. 

In the https://github.com/segmentio/metalsmith/#readme page, they have installed only 'metalsmith' with the help of 'npm install metalsmith'. If I've to install 'make' how do you do that?

And for the 'how do you run static site "\metalsmith-master\examples\static-site" without any .js file', they didn't have any .js file in the directory(please check : https://github.com/segmentio/metalsmith/tree/master/examples/static-site). I tried the same way. Any help would be much appreciated.

**Comment by KenanY** [comment]
@somudcis 

> If I've to install 'make' how do you do that?

https://www.gnu.org/software/make/

Ah, I see the example now. Looks like you should run this from within that directory:

``` sh
$ npm install
$ make build
```

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
