### ISSUE TITLE
Fail to update npm

### ISSUE THREAD

**Issue by ShinobiSlayer** [npm/npm#8373]
Hi,

Im getting an error when I try to update my version of npm.

Can you please help.

OS Name	Microsoft Windows 7 Home Premium
Version	6.1.7601 Service Pack 1 Build 7601
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Type	x64-based PC
Processor	Intel(R) Core(TM)2 Quad CPU    Q8200  @ 2.33GHz, 2331 Mhz, 4 Core(s), 4 Logical 

2602 info npm@2.10.1 Failed to exec prepublish script
2603 error addLocalDirectory Could not pack "c:\\Users\\dave\\AppData\\Local\\Temp\\npm-2420-yAx5gffC\\npm-2.10.11432737333561-0.3174854831304401\\package" to "C:\\Users\\dave\\AppData\\Roaming\\npm-cache\\npm\\2.10.1\\package.tgz"
2604 silly lockFile c5ee3d3b-try-npmjs-org-npm-npm-2-10-1-tgz https://registry.npmjs.org/npm/-/npm-2.10.1.tgz
2605 silly lockFile c5ee3d3b-try-npmjs-org-npm-npm-2-10-1-tgz https://registry.npmjs.org/npm/-/npm-2.10.1.tgz
2606 silly lockFile 5a3de119-npm-2-10-1 npm@2.10.1
2607 silly lockFile 5a3de119-npm-2-10-1 npm@2.10.1
2608 silly lockFile 2f990b75-npm npm@
2609 silly lockFile 2f990b75-npm npm@
2610 error npm@2.10.1 prepublish: `node bin/npm-cli.js prune --prefix=. --no-global && rimraf test/*/*/node_modules && make -j4 doc`
2610 error Exit status 1
2611 error Failed at the npm@2.10.1 prepublish script.
2611 error This is most likely a problem with the npm package,
2611 error not with npm itself.
2611 error Tell the author that this fails on your system:
2611 error     node bin/npm-cli.js prune --prefix=. --no-global && rimraf test/*/*/node_modules && make -j4 doc
2611 error You can get their info via:
2611 error     npm owner ls npm
2611 error There is likely additional logging output above.
2612 error System Windows_NT 6.1.7601
2613 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "npm" "-g"
2614 error cwd C:\Users\dave
2615 error node -v v0.11.9
2616 error npm -v 1.3.15
2617 error code ELIFECYCLE
2618 verbose exit [ 1, true ]

Thanks

**Comment by posita** [comment]
@ShinobiSlayer, what was this fix for this?

**Comment by ShinobiSlayer** [comment]
I installed the very latest version of node
