### ISSUE TITLE
When a direct devDependency dedupes a transitive production dependency, it is excluded from shrinkwrap

### ISSUE THREAD

**Issue by searls** [npm/npm#8375]
The tersest summary of this I can muster is "direct devDependencies which are coincidentally transitive production dependencies can lead to unreliable shrinkwrap files". I will describe my issue below as best I can, but I've also shared an [easy-to-run shell script](https://gist.github.com/searls/4ba7a2396d8e81f4f9e0) as a gist that'll demonstrate the issue on the latest releases of npm.

So if you have a few things going on:

1) a devDependency which is coincidentally also a dependency of a production dependency (in my example: 
```
"devDependencies": {
    "glob": "^4.5.3"
  },
  "dependencies": {
    "glob-stream": "^3.1.18"
  }
```

Where `glob-stream` depends on `glob` as a production dependency.

2) if these were automatically deduped by the cli at install time (by first calling `npm i --save-dev glob@4.5.3` and then `npm i --save glob-stream@3.1.18`)

3) if `npm shrinkwrap` is then run, `glob` will be excluded as a top-level depednency, but so will any mention of `glob` as a dependency of `glob-stream`, even though it's still a production dependency of `glob-stream`.

4) finally, clearing `node_modules` and running `npm i --production`, followed by `node -e "require('glob-stream')"` will throw an exception, as the `glob` module will not be found.

**Comment by searls** [comment]
Upon further searching, this is almost certainly a dupe of #6933

**Comment by jasonkarns** [comment]
definitely a dupe of #5161 which didn't come up in search results because it was closed
