### ISSUE TITLE
Unable to install grunt 0.3.17 

### ISSUE THREAD

**Issue by tulasiramthota** [npm/npm#8382]
Hi,

I'm unable to install grunt 0.3.17 in my local machine.My node version is v0.8.22.Below is the error stack i'm getting when i'm trying to install grunt

npm install -g grunt@0.3.17

Error :

```
npm http GET https://registry.npmjs.org/tap-parser
npm http GET https://registry.npmjs.org/signal-exit
npm ERR! Error: No compatible version found: opener@'^1.4.1'
npm ERR! Valid install targets:
npm ERR! ["1.0.0","1.0.1","1.1.0","1.2.0","1.3.0","1.4.0","1.4.1"]
npm ERR!     at installTargetsError (C:\Program Files\nodejs\node_modules\npm\lib\cache.js:682:10)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\lib\cache.js:597:10
npm ERR!     at saved (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:297:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "grunt@0.3.17"
npm ERR! cwd C:\Users\tthota1
npm ERR! node -v v0.8.22
npm ERR! npm -v 1.2.14
npm http GET https://registry.npmjs.org/nyc
npm http GET https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/stack-trace
npm http GET https://registry.npmjs.org/coveralls
npm http GET https://registry.npmjs.org/js-yaml
```

Could you please help me in resolving this issue.

Thanks,
Tulasi Ram

**Comment by KenanY** [comment]
@tulasiramthota `npm@1.2.14` is extremely old, and has not been supported for several months now. It does not support the `^` semver operator you see here:

```
npm ERR! Error: No compatible version found: opener@'^1.4.1'
```

hence the error. The solution is to simply [update](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm)! Also, you might find it beneficial to know that Node.js v0.8 development has ended with the release of v0.12, so [upgrading Node.js](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-node) might be in your best interest as well :)

**Comment by tulasiramthota** [comment]
Thanks Kenan

**Comment by othiym23** [comment]
Closing as resolved.
