### ISSUE TITLE
Custom license & url

### ISSUE THREAD

**Issue by IonicaBizau** [npm/npm#8384]
Is it possible to specify the license url in the latest npm versions?

**Comment by isaacs** [comment]
`"license": "SEE LICENSE IN <filename>"` should work.  However, there's a bug in the website, which leads to it not being linked properly.

You're doing the right thing.

**Comment by IonicaBizau** [comment]
@isaacs Good to know. Is it possible to display the custom license name there, as well?

**Comment by sakshamsaxena** [comment]
@IonicaBizau I was wondering the same thing. Does seem like a website issue though. Would like to help a bit maybe if there's actually something we can do, cuz I don't see or feel like blaming npm-cli for it :no_mouth:

**Comment by IonicaBizau** [comment]
I'm closing this as duplicate of https://github.com/npm/newww/issues/992, since it's a website rendering issue.
