### ISSUE TITLE
npm shrinkwrap --help

### ISSUE THREAD

**Issue by techtonik** [npm/npm#8385]
There is no help for this hacker tool. At least the `--dev` option should be documented.
```
$ npm shrinkwrap --help
npm shrinkwrap
$ npm shrinkwrap --version
1.3.10
```

**Comment by KenanY** [comment]
I'm surprised no one has requested this after all this time. I think simply expanding [this](https://github.com/npm/npm/blob/v2.11.0/lib/shrinkwrap.js#L14) is all that needs to be done.

@techtonik Also, you should know that `npm@1.3.10` is extremely old and has not been supported for months now. [Update](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) :)

**Comment by techtonik** [comment]
@KenanY well, that comes bundled with my Ubuntu 14.04 LTS container that I use to bootstrap Gratipay app, which is Python based, but uses npm to manage client script JavaScript dependencies, and I really can't fix some issues with jstest for several months, always learning something new along the way, but never arriving at the endpoint.

**Comment by othiym23** [comment]
What you want is `npm help shrinkwrap`, which will give you the complete online help for the command, which indeed takes no options by default (so that short help, while terse and not particularly helpful, is basically correct). I hope that documentation is enough to get you oriented, and be aware that the CLI team will be putting a bunch more work into `npm shrinkwrap`, probably this year, to make it easier to understand and use effectively. Thanks for your time!

**Comment by techtonik** [comment]
@othiym23 thanks for the heads up. Would be nice to have `-h` and `--help` available sooner that a bunch of more work arrives.

**Comment by othiym23** [comment]
@techtonik What does `npm help shrinkwrap` not give you? I'm pretty sure that even once we make the changes we intend to make, `npm shrinkwrap` isn't going to take any additional parameters (even `--development` / `--only=development` will probably only apply during install after the changes, and not be needed when creating the shrinkwrap file).

**Comment by techtonik** [comment]
@othiym23 I don't work with JavaScript at all. I am a poor DevOps who has to maintain toolchains that are left as a technical debt from former JavaScript gurus. It will make my life easier if every command line app supported `-h` `--help` notation. `man`, `info`, `help` all have different semantics. `-h` `--help` is most of the time the same.
