### ISSUE TITLE
Unable to install stacktrace.js

### ISSUE THREAD

**Issue by pritithakkar** [npm/npm#8392]
Getting below error, when trying to install using npm:
```
npm http GET https://registry.npmjs.org/stacktrace.js
npm http GET https://registry.npmjs.org/stacktrace.js
npm http GET https://registry.npmjs.org/stacktrace.js
npm ERR! Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE
npm ERR!     at SecurePair.<anonymous> (tls.js:1370:32)
npm ERR!     at SecurePair.EventEmitter.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:982:10)
npm ERR!     at CleartextStream.read [as _read] (tls.js:469:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:320:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:366:25)
npm ERR!     at doWrite (_stream_writable.js:226:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:216:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:183:11)
npm ERR!     at write (_stream_readable.js:583:24)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "stacktrace.js"
npm ERR! cwd C:\Users\m128540\git\NavApp\MacysNavApp
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\m128540\git\NavApp\MacysNavApp\npm-debug.log
npm ERR! not ok code 0
```

**Comment by KenanY** [comment]
@pritithakkar Could you [try the latest stable release of `npm`](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm)?

**Comment by pritithakkar** [comment]
tried doing that, but still, version remains same.
I have 1.4.3 npm version.

**Comment by KenanY** [comment]
@pritithakkar Did you take care to follow the [Windows-specific instructions](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows)?

**Comment by pritithakkar** [comment]
21 http GET https://registry.npmjs.org/stacktrace.js
22 http 404 https://registry.npmjs.org/stacktrace.js
23 silly registry.get cb [ 404,
23 silly registry.get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
23 silly registry.get     'content-type': 'application/json',
23 silly registry.get     'cache-control': 'max-age=0',
23 silly registry.get     'content-length': '51',
23 silly registry.get     'accept-ranges': 'bytes',
23 silly registry.get     date: 'Fri, 29 May 2015 05:44:04 GMT',
23 silly registry.get     via: '1.1 varnish',
23 silly registry.get     age: '0',
23 silly registry.get     connection: 'keep-alive',
23 silly registry.get     'x-served-by': 'cache-lax1435-LAX',
23 silly registry.get     'x-cache': 'MISS',
23 silly registry.get     'x-cache-hits': '0',
23 silly registry.get     'x-timer': 'S1432878244.240629,VS0,VE330' } ]
24 silly lockFile 805cb038-stacktrace-js stacktrace.js@
25 silly lockFile 805cb038-stacktrace-js stacktrace.js@
26 error 404 'stacktrace.js' is not in the npm registry.

**Comment by pritithakkar** [comment]
my Path & PATH variables are different, 
PATH=C:\Users\m128540\AppData\Roaming\npm

Path=;C:\Program Files\nodejs\; (does not contain appdata/roaming path here)

Option:2 - I do not have those in my environment variables
Option : 3 - worked !! I have the latest version of npm - 2.11.0

ran the below command to install stacktrace
----------------------------------------------------------
C:\Program Files\nodejs>npm install stacktrace.js
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "stacktrace.js"
npm ERR! node v0.10.26
npm ERR! npm  v2.11.0
npm ERR! code E404

npm ERR! 404 Not Found: stacktrace.js
npm ERR! 404
npm ERR! 404 'stacktrace.js' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files\nodejs\npm-debug.log

**Comment by eriwen** [comment]
@pritithakkar do you mean

npm install stacktrace-js

Note the dash instead of .js

**Comment by pritithakkar** [comment]
Thanks Able to install it now

**Comment by iarna** [comment]
Closing as resolved.
