### ISSUE TITLE
Have npm --outdated list alphabetically

### ISSUE THREAD

**Issue by binarykitchen** [npm/npm#8401]
Here an example, the list is not sorted alphabetically:

```
$ npm outdated --depth=0
Package            Current  Wanted  Latest  Location
angular             1.3.15  1.3.15   1.4.0  angular
angular-route       1.3.15  1.3.15   1.4.0  angular-route
browserify          10.2.1  10.2.1  10.2.3  browserify
require-directory    2.1.0   2.1.0   2.1.1  require-directory
cors                 2.6.0   2.6.0   2.7.1  cors
semver               4.3.4   4.3.4   4.3.5  semver
```

I think it should be because whenever you do an `npm install --save`, npm automatically makes an entry in the package.json and sorts the dependencies alphabetically which means, the developer parses that list resting assured it's sorted. Now imagine I scan that list of outdated packages, which is NOT sorted and compare it with the package.json which is sorted: you scroll up and down a couple of times. Not very "developer-user-friendly" (DX).

I know, it's a very small, unimportant, feature request. But it's always good to make the life of a hard-working developer a bit easier heh.

**Comment by Dashed** [comment]
Going to +1 to show some demand for this tiny detail.

**Comment by watilde** [comment]
Seems nice! +1

**Comment by KenanY** [comment]
This is available as of [`npm@2.11.2`](https://github.com/npm/npm/releases/tag/v2.11.2) :confetti_ball:

**Comment by zkat** [comment]
looks like another issue I forgot to close!

**Comment by watilde** [comment]
Thank you!
