### ISSUE TITLE
Issue with installation of forever@0.10.0 on Windows 7

### ISSUE THREAD

**Issue by karthiksagar** [npm/npm#8403]
Hi ,
i am trying to install a project. Following are versions of software's i am using
OS : Windows 7 64 bit version
Node: 0.18.8 64 bit version 

I have attached my package.json of main project

```json
{
  "name": "vegas-server",
  "preferGlobal": "false",
  "version": "0.1.0",
  "main": "./vegasNodeServer",
  "scripts": {
      "start": "forever startServer.js",
      "test" : "mocha tests --timeout 8000"
    },
    "dependencies" : {
      "restify"    : "2.3.4",
      "underscore" : "1.4.4",
      "cjson"      : "0.2.1",
      "sqlite3"    : "2.1.5",
      "forever"    : "0.10.0",
      "winston"    : "0.6.2",
      "requirejs"  : "2.1.5"
    },
    "devDependencies": {
      "mocha"   : "1.7.x",
      "should"  : "1.2.x",
      "mockery" : "1.4.x"
    },
    "private" : true
} 
```
![untitled](https://cloud.githubusercontent.com/assets/7107968/7897375/619af88a-06f7-11e5-8331-b6c4e91cef1a.png)

**Comment by KenanY** [comment]
@karthiksagar Your version of `npm` is ancient! The solution to your issue is to [upgrade](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows) :)

**Comment by karthiksagar** [comment]
but the Supported version as stated by the product owner is node 0.8.18
How can overcomee it.

**Comment by karthiksagar** [comment]
After upgrading my NPm i was able to succefully install my project but i have ran into following issue. My forever server does not start.

              ^
Error: JSON.parse error - "Unexpected token S"
File: "vegas-server-config.json"

    at Object.load (D:\tpenv\Smallworld412\gss430\extension-modules\NetworkViewe
r\server\node\vegas-server\node_modules\cjson\lib\cjson.js:217:15)
    at Object.<anonymous> (D:\tpenv\Smallworld412\gss430\extension-modules\Netwo
rkViewer\server\node\vegas-server\configLoader.js:1:101)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (D:\tpenv\Smallworld412\gss430\extension-modules\Netwo
rkViewer\server\node\vegas-server\vegasMapServer.js:1:367)
    at Module._compile (module.js:449:26)
Forever detected script exited with code: 1
Forever restarting script for 85 time

**Comment by KenanY** [comment]
@karthiksagar 

> but the Supported version as stated by the product owner is node 0.8.18

Then you can stick with that :) all I am saying is to upgrade `npm`, which can be done independently of Node.js (although, you should know that development on v0.8 has ended now with the release of v0.12, so I would not recommend staying there forever).

> forever server does not start

That error is not coming from `npm`. Looks like `vegas-server-config.json` is not valid JSON.

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
