### ISSUE TITLE
Error code: ESSL when trying to install

### ISSUE THREAD

**Issue by murphydanger** [npm/npm#8406]
My travis-ci builds for io.js seem to be failing because of the newest version of npm (v2.11.0). Is anyone else experiencing this?

```sh
npm ERR! npm  v2.11.0
npm ERR! code ESSL
npm ERR! SSL Error: https://registry.npmjs.org/gulp does not support SSL
```

**Comment by targos** [comment]
This is an error introduced by iojs@v2.2.0
See https://github.com/nodejs/io.js/issues/1850

**Comment by murphydanger** [comment]
Looks like they're working on it now. Sorry for bringing this to the wrong
people.

**Comment by othiym23** [comment]
This is a problem with `io.js@2.2.0` and not npm – see https://github.com/nodejs/io.js/pull/1572#issuecomment-107222737 for details, and pin to `iojs-v2.1.0` on Travis if you need io.js testing for your projects, at least until a version that isn't broken is released (which i hope is soon).

See also the discussion on

* https://github.com/nodejs/io.js/pull/1572
* https://github.com/nodejs/io.js/pull/1808
* https://github.com/nodejs/io.js/issues/1850
* https://github.com/nodejs/io.js/pull/1851
* https://github.com/nodejs/io.js/pull/1852
