### ISSUE TITLE
Error: invalid name: must be url-safe

### ISSUE THREAD

**Issue by bitliner** [npm/npm#8408]
I want to publish a private npm module.

Its package.json includes as name the usual format `@username/module-name` where module name contains dash.

When I run `npm publish` it throws

```
Error: invalid name: must be url-safe
```

**Comment by notduncansmith** [comment]
I just encountered this today, with no dash in the name (e.g. `@username/modulename`).

**Comment by bitliner** [comment]
Ipdate npm and let us now. Npm update npm -g

On Sunday, June 7, 2015, Duncan Smith <notifications@github.com> wrote:

> I just encountered this today, with no dash in the name (e.g.
> @username/modulename).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/npm/npm/issues/8408#issuecomment-109784158>.
>


-- 
*Giovanni Gaglione                            *

LinkedIn: http://lnkd.in/MyZGut
Telefono: +39 388 - 82.6666.2 / 0031-06.49.75.66.93 / 0031-06.11.06.22.17
Email: giovanni.gaglione@gmail.com
<giovanni.gaglione@gmail.com>Skype: bitliner

**Comment by notduncansmith** [comment]
Ah, it turned out to be a path issue for me.  `/.npm-packages/bin/npm` was the correct version, but `which npm` revealed I was using `/usr/local/bin/npm` for some reason.

**Comment by megalithic** [comment]
have up to date nvm, and npm is pathed correctly for my particular node version (0.10.32) and still having the same issue as @bitliner. anyone else having similar issues with having libs up to date?

**Comment by johnnn-mitchell** [comment]
I'm getting this issue as well. I have updated npm but still getting  Error: Invalid name when publishing a private module.  npm -v shows 1.4.14 and node -v shows 0.10.29

Module name takes the form "@company-name/module-name" with dashes in both segments.

**Comment by kmanion** [comment]
Hi, @bitliner and @megalithic, We’re trying to clean up some old support issues. If this is still a problem, can you please reply and let us know? As far as I know, private modules were not supported in early versions of npm. We’ll be happy to reopen if necessary.

-Kiera, npm technical support
