### ISSUE TITLE
README.md not updating for package node-9gag

### ISSUE THREAD

**Issue by sachinB94** [npm/npm#8409]
README.md is not updated on npmjs.com for version 0.1.4, although installing the package gives the updated README.md.

**Comment by KenanY** [comment]
@sachinB94 Maybe it just takes a few minutes? Issues with the website should be opened at [npm/newww](https://github.com/npm/newww).

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
