### ISSUE TITLE
npm start not finding the script.

### ISSUE THREAD

**Issue by vijay15joseph** [npm/npm#8410]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\apps\\nodejs\\\\node.exe',
1 verbose cli   'C:\\apps\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.10.1
3 info using node@v0.12.4
4 verbose stack Error: missing script: start
4 verbose stack     at run (C:\apps\nodejs\node_modules\npm\lib\run-script.js:142:19)
4 verbose stack     at C:\apps\nodejs\node_modules\npm\lib\run-script.js:58:5
4 verbose stack     at C:\apps\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:345:5
4 verbose stack     at handleExists (C:\apps\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:318:20)
4 verbose stack     at FSReqWrap.cb [as oncomplete] (evalmachine.<anonymous>:226:19)
5 verbose cwd C:\apps\nodejs\node_modules\npm
6 error Windows_NT 6.1.7601
7 error argv "C:\\apps\\nodejs\\\\node.exe" "C:\\apps\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
8 error node v0.12.4
9 error npm  v2.10.1
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@vijay15joseph So, uh, do you have a start script defined in your `package.json`?

**Comment by vijay15joseph** [comment]
No, it is not defined. I installed node.js, when i tried to start it.

**Comment by KenanY** [comment]
@vijay15joseph Sorry, I do not understand what you are _expecting_ to happen when you run [`npm start`](https://docs.npmjs.com/cli/start) without a ["start" script](https://docs.npmjs.com/misc/scripts) defined in your [`package.json`](https://docs.npmjs.com/files/package.json). `npm` has absolutely no idea what you want it to do.

**Comment by vijay15joseph** [comment]
I am new to nodejs or npm.  i downloaded it and when i tried to run it witn documentation, i got this error.

**Comment by KenanY** [comment]
@vijay15joseph What documentation or tutorial are you following that is telling you to run `npm start` as a way to "start node.js"?

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
