### ISSUE TITLE
Throw SSL Error with iojs<2.2.0> npm<2.11.0>

### ISSUE THREAD

**Issue by lichenhao** [npm/npm#8415]
npm ERR! Darwin 14.3.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "install" "busboy"
npm ERR! node v2.2.0
npm ERR! npm  v2.11.0
npm ERR! code ESSL

npm ERR! SSL Error: https://registry.npmjs.org/busboy does not support SSL
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Ryota/Tools/dawn/npm-debug.log

**Comment by lichenhao** [comment]
It seems like caused by the Chrome SSL upgrade.

**Comment by othiym23** [comment]
io.js includes a change that breaks `request` and therefore npm. See #8406 for details. Closing as duplicate.
