### ISSUE TITLE
Installing mongoose via npm, does not support SSL?

### ISSUE THREAD

**Issue by OmgImAlexis** [npm/npm#8417]
I can download the file fine from my browser and it gets it from the https page.
I'm not sure if this is a github, npm or mongodb issue.

````
npm ERR! fetch failed https://github.com/mongodb-js/node-pre-gyp/archive/v0.6.5-appveyor.tar.gz
npm WARN retry will retry, error on last attempt: Error: SSL Error: https://github.com/mongodb-js/node-pre-gyp/archive/v0.6.5-appveyor.tar.gz does not support SSL
````

**Comment by othiym23** [comment]
io.js 2.2.0 includes a change that breaks `request` and therefore npm. See #8406 for details. Closing as duplicate.
