### ISSUE TITLE
How to auth npm on a new machine with old, existing, valid user?

### ISSUE THREAD

**Issue by martensms** [npm/npm#8418]
I can't get npm to run. I can't find a simple tutorial that explains it.

npm adduser will fail with an unknown error.
How to auth my new machine with my account?

Why is it not simply using the git user/pub key as you use gravatar to display the avatars, i assume?

```bash
Username: lazerunicorns
Password: -hidden-
Email: -hidden-
npm http PUT https://registry.npmjs.org/-/user/org.couchdb.user:lazerunicorns
npm http 400 https://registry.npmjs.org/-/user/org.couchdb.user:lazerunicorns
npm ERR! Error: Unknown error while authenticating : -/user/org.couchdb.user:lazerunicorns
npm ERR!     at RegClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:272:14)
npm ERR!     at Request.self.callback (/usr/lib/nodejs/request/index.js:148:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/index.js:896:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/lib/nodejs/request/index.js:847:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
```

**Comment by KenanY** [comment]
@martensms Does this also happen on the [latest stable release](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) of `npm`?

**Comment by martensms** [comment]
For the record: This was not reproducible on Ubuntu 15.10 nor Ubuntu 15.04. It only occured on Ubuntu LTS (14.04), I guess it was related to the meanwhile deprecated linking of npm binary and/or the weird package setup there, as npm and node are available via Debian package there.

Installation via the non-native tar.gz file directly fixed the issue, so npm/node needs better packaging (added another issue for that already which is pending in discussion).
