### ISSUE TITLE
Shrinkwrap private git url inconsistency 

### ISSUE THREAD

**Issue by flankstaek** [npm/npm#8424]
I have two apps that I'm trying to shrinkwrap and both pull from private Git repos listed as 'Org/Repo' in the `package.json`

On one app the shrinkwrap prints out the git urls as git+ssh, the other it's git+https. I've tried using identical `package.json`s and one still ends up as ssh, and the other as https.

I'm not entirely sure what the cause of this could be, I've been looking for more information but I've hit a dead end. Any help would be appreciated.

**Comment by KenanY** [comment]
@flankstaek `npm --version`?

**Comment by flankstaek** [comment]
npm : 2.11.0
node : 0.10.25

**Comment by tarikjn** [comment]
I have the same issue on npm 3.10.5 and node 6.3.0 (latest versions at the date of this port). Except that the urls consistently get transformed to `git+https` while they were `npm install`'ed as `git+ssh`, which makes npm shrinkwrap unusable with short form private dependency urls.

The `from` field is correct as `org/repo`, but the `resolved` field is consistently incorrect as `git+https://github.com/org/repo.git#hash`.
