### ISSUE TITLE
Attempt to unlock /Users/anthonykosturos/test/node_modules/express, which hasn't been locked

### ISSUE THREAD

**Issue by akosturos** [npm/npm#8425]
I cannot do the npm install command. I get this

```
ERR code : Attempt to unlock /Users/anthonykosturos/test/node_modules/express, which hasn't been locked
```

I believe this is mongoose related... help!!

**Comment by KenanY** [comment]
@akosturos `npm --version`? Is there a `npm-debug.log` that you can upload as a [gist](https://gist.github.com/)?

**Comment by akosturos** [comment]
thanks, but I figured it out. I typed in this command in the command line
sudo chown -R `whoami` ~/.npm
sudo chown -R `whoami` /usr/local/lib/node_modules

**Comment by othiym23** [comment]
Closing as resolved!
