### ISSUE TITLE
sudo npm install tk102

### ISSUE THREAD

**Issue by redabkf** [npm/npm#8426]
Please help with the following issue:
```
GET https://registry.npmjs.org/tk102
npm http 200 https://registry.npmjs.org/tk102
npm http GET https://registry.npmjs.org/tk102/-/tk102-1.2.1.tgz
npm http 404 https://registry.npmjs.org/tk102/-/tk102-1.2.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/tk102/-/tk102-1.2.1.tgz
npm ERR! Error: 404 Not Found
npm ERR!     at WriteStream.<anonymous> (/usr/share/npm/lib/utils/fetch.js:57:12)
npm ERR!     at WriteStream.EventEmitter.emit (events.js:117:20)
npm ERR!     at fs.js:1601:14
npm ERR!     at /usr/lib/nodejs/graceful-fs/graceful-fs.js:103:5
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.16.0-31-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "tk102"
npm ERR! cwd /home/redabkf/Desktop/server/tk102
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/redabkf/Desktop/server/tk102/npm-debug.log
npm ERR! not ok code 0
```

**Comment by KenanY** [comment]
@redabkf Could you first try using the [latest stable release of `npm`](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm)? The `1.3` series has not been supported for months now.

**Comment by redabkf** [comment]
I have now moved to npm 2.11.0
Please advise accordingly now as I am getting the same error while installing the tk102: 
"
npm ERR! fetch failed https://registry.npmjs.org/tk102/-/tk102-1.2.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/tk102/-/tk102-1.2.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/tk102/-/tk102-1.2.1.tgz
npm ERR! Linux 3.16.0-38-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install" "tk102"
npm ERR! node v0.10.25
npm ERR! npm  v2.11.0

npm ERR! fetch failed with status code 404
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
"

**Comment by KenanY** [comment]
@redabkf Hmm, I am stumped as to why that tarball does not exist. Maybe the author hit an error while publishing. Looks like the tarball for `tk102@1.1.0` exists so could you simply use that?

**Comment by redabkf** [comment]
It works, Thank you ! 
This is the message I am getting and the node modules got copied to my file.
"
tk102@1.1.0 node_modules/tk102
"

**Comment by othiym23** [comment]
Closing as resolved. Sorry about that!
