### ISSUE TITLE
Always ignore the .idea directory?

### ISSUE THREAD

**Issue by ChALkeR** [npm/npm#8428]
About 2-3% of npm packages include the `.idea` directory, that numbers are pretty high.
Could that be added to the default npmignore maybe? (Like `.DS_Store`, `.lock-wscript` etc.)

Or is it not safe and someone actually _wants_ to package their `.idea` dir?

**Comment by othiym23** [comment]
The stuff that's ignored right now is the maximum set of things that we _know_ we don't want included in a package. I don't want to clutter that set up with other things that aren't platform- or Node-specific. Thanks for the suggestion, though!
