### ISSUE TITLE
npm ERR! when trying to install playfair

### ISSUE THREAD

**Issue by AngelaO** [npm/npm#8432]
I'm having trouble installing playfair with npm.  Here's my npm-debug.log file, does anyone have any ideas?...

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', '-g', 'playfair' ]
2 info using npm@2.11.0
3 info using node@v0.12.4
4 verbose install initial load of /usr/local/lib/package.json
5 verbose readDependencies loading dependencies from /usr/local/lib/package.json
6 silly cache add args [ 'playfair', null ]
7 verbose cache add spec playfair
8 silly cache add parsed spec { raw: 'playfair',
8 silly cache add   scope: null,
8 silly cache add   name: 'playfair',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed playfair@*
10 verbose addNamed "*" is a valid semver range for playfair
11 silly addNameRange { name: 'playfair', range: '*', hasData: false }
12 silly mapToRegistry name playfair
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/playfair
16 verbose addNameRange registry:https://registry.npmjs.org/playfair not in flight; fetching
17 verbose request uri https://registry.npmjs.org/playfair
18 verbose request no auth needed
19 info attempt registry request try #1 at 9:56:04 AM
20 verbose request id c8fdd26a5e1265d6
21 verbose etag "90BNMFLD0ZTBJOXECMVDDKVWJ"
22 http request GET https://registry.npmjs.org/playfair
23 http 304 https://registry.npmjs.org/playfair
24 silly get cb [ 304,
24 silly get   { date: 'Tue, 02 Jun 2015 08:56:04 GMT',
24 silly get     via: '1.1 varnish',
24 silly get     'cache-control': 'max-age=60',
24 silly get     etag: '"90BNMFLD0ZTBJOXECMVDDKVWJ"',
24 silly get     age: '0',
24 silly get     connection: 'keep-alive',
24 silly get     'x-served-by': 'cache-lhr6330-LHR',
24 silly get     'x-cache': 'MISS',
24 silly get     'x-cache-hits': '0',
24 silly get     'x-timer': 'S1433235364.926741,VS0,VE160',
24 silly get     vary: 'Accept' } ]
25 verbose etag https://registry.npmjs.org/playfair from cache
26 verbose get saving playfair to /Users/datascience1/.npm/registry.npmjs.org/playfair/.cache.json
27 silly addNameRange number 2 { name: 'playfair', range: '*', hasData: true }
28 silly addNameRange versions [ 'playfair', [ '0.1.0' ] ]
29 silly addNamed playfair@0.1.0
30 verbose addNamed "0.1.0" is a plain semver version for playfair
31 silly cache afterAdd playfair@0.1.0
32 verbose afterAdd /Users/datascience1/.npm/playfair/0.1.0/package/package.json not in flight; writing
33 verbose afterAdd /Users/datascience1/.npm/playfair/0.1.0/package/package.json written
34 silly install resolved [ { name: 'playfair',
34 silly install resolved     version: '0.1.0',
34 silly install resolved     description: 'Generate charts and graphs from the command line using d3 and PhantomJS.',
34 silly install resolved     main: 'index.js',
34 silly install resolved     bin: { playfair: './playfair.js' },
34 silly install resolved     files: [ 'src' ],
34 silly install resolved     scripts: { test: 'echo "Error: no test specified" && exit 1' },
34 silly install resolved     repository:
34 silly install resolved      { type: 'git',
34 silly install resolved        url: 'git+https://github.com/manleyjster/playfair.git' },
34 silly install resolved     keywords: [ 'phantomjs', 'chart', 'graph', 'd3', 'data', 'visualization' ],
34 silly install resolved     dependencies:
34 silly install resolved      { commander: '~2.3.0',
34 silly install resolved        augment: '~4.3.0',
34 silly install resolved        phantomjs: '~1.9.0',
34 silly install resolved        phantom: '0.6.5',
34 silly install resolved        underscore: '1.6.0' },
34 silly install resolved     author: { name: 'Justin Manley' },
34 silly install resolved     license: 'MIT',
34 silly install resolved     bugs: { url: 'https://github.com/manleyjster/playfair/issues' },
34 silly install resolved     homepage: 'https://github.com/manleyjster/playfair',
34 silly install resolved     _id: 'playfair@0.1.0',
34 silly install resolved     _shasum: 'f27290f75e2488feb795b8f0636a36334b390d68',
34 silly install resolved     _from: 'playfair@*',
34 silly install resolved     _npmVersion: '1.4.9',
34 silly install resolved     _npmUser: { name: 'justinmanley', email: 'manleyjster@gmail.com' },
34 silly install resolved     maintainers: [ [Object] ],
34 silly install resolved     dist:
34 silly install resolved      { shasum: 'f27290f75e2488feb795b8f0636a36334b390d68',
34 silly install resolved        tarball: 'http://registry.npmjs.org/playfair/-/playfair-0.1.0.tgz' },
34 silly install resolved     directories: {},
34 silly install resolved     _resolved: 'https://registry.npmjs.org/playfair/-/playfair-0.1.0.tgz',
34 silly install resolved     readme: 'ERROR: No README data found!' } ]
35 info install playfair@0.1.0 into /usr/local/lib
36 info installOne playfair@0.1.0
37 verbose installOne of playfair to /usr/local/lib not in flight; installing
38 warn locking Error: EACCES, open '/Users/datascience1/.npm/_locks/playfair-f64d5da4f3bba3cf.lock'
38 warn locking     at Error (native)
38 warn locking  /Users/datascience1/.npm/_locks/playfair-f64d5da4f3bba3cf.lock failed { [Error: EACCES, open '/Users/datascience1/.npm/_locks/playfair-f64d5da4f3bba3cf.lock']
38 warn locking   errno: -13,
38 warn locking   code: 'EACCES',
38 warn locking   path: '/Users/datascience1/.npm/_locks/playfair-f64d5da4f3bba3cf.lock' }
39 verbose stack Error: Attempt to unlock /usr/local/lib/node_modules/playfair, which hasn't been locked
39 verbose stack     at unlock (/usr/local/lib/node_modules/npm/lib/utils/locker.js:66:11)
39 verbose stack     at cb (/usr/local/lib/node_modules/npm/lib/install.js:1017:5)
39 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:1021:20
39 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/locker.js:40:9
39 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
39 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
39 verbose stack     at FSReqWrap.oncomplete (fs.js:95:15)
40 verbose cwd /Users/datascience1
41 error Darwin 14.3.0
42 error argv "node" "/usr/local/bin/npm" "install" "-g" "playfair"
43 error node v0.12.4
44 error npm  v2.11.0
45 error Attempt to unlock /usr/local/lib/node_modules/playfair, which hasn't been locked
46 error If you need help, you may report this error at:
46 error     <https://github.com/npm/npm/issues>
47 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@AngelaO Looks like a permissions issue to me, perhaps your user does not have permissions to read/write to `npm`'s cache directory? Could you try `chown`ing it?:

``` sh
$ sudo chown -R $(whoami) "$HOME/.npm"
```

**Comment by AngelaO** [comment]
I did as you said and then tried to install playfair again, got the following errors:

```
npm ERR! tar.unpack untar error /Users/datascience1/.npm/playfair/0.1.0/package.tgz
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "playfair"
npm ERR! node v0.12.4
npm ERR! npm  v2.11.0
npm ERR! path /usr/local/lib/node_modules/playfair
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, mkdir '/usr/local/lib/node_modules/playfair'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, mkdir '/usr/local/lib/node_modules/playfair']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/playfair',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/playfair',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:35:25',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:47:53',
npm ERR!      'FSReqWrap.oncomplete (fs.js:95:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/datascience1/npm-debug.log
```

Also tried `sudo install` and got the following:

```
> weak@0.4.1 install /usr/local/lib/node_modules/playfair/node_modules/phantom/node_modules/dnode/node_modules/weak
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/Users/datascience1/.node-gyp/0.12.4"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/playfair/node_modules/phantom/node_modules/dnode/node_modules/weak/.node-gyp"
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/weakref/src/weakref.o
  SOLINK_MODULE(target) Release/weakref.node
  SOLINK_MODULE(target) Release/weakref.node: Finished

> phantomjs@1.9.17 install /usr/local/lib/node_modules/playfair/node_modules/phantomjs
> node install.js

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-macosx.zip
Saving to /usr/local/lib/node_modules/playfair/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-macosx.zip
Receiving...
  [==================----------------------] 45% 0.0s
Received 9187K total.
Extracting zip contents
Removing /usr/local/lib/node_modules/playfair/node_modules/phantomjs/lib/phantom
Copying extracted folder /usr/local/lib/node_modules/playfair/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-macosx.zip-extract-1433253374804/phantomjs-1.9.8-macosx -> /usr/local/lib/node_modules/playfair/node_modules/phantomjs/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /usr/local/lib/node_modules/playfair/node_modules/phantomjs/lib/phantom/bin/phantomjs
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "playfair"
npm ERR! node v0.12.4
npm ERR! npm  v2.11.0
npm ERR! path /usr/local/lib/node_modules/playfair/playfair.js
npm ERR! code ENOENT
npm ERR! errno -2

npm ERR! enoent ENOENT, chmod '/usr/local/lib/node_modules/playfair/playfair.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/datascience1/npm-debug.log
```
