### ISSUE TITLE
Unable to install npm install selenium-webdriver

### ISSUE THREAD

**Issue by Agpandey** [npm/npm#8433]
Hi, I am getting error while installing selenium-webdriver on my mac machine.

```
npm WARN locking Error: EACCES, open '/Users/noimac-mini4/.npm/_locks/selenium-webdriver-61fc4844104a7029.lock'
npm WARN locking  /Users/noimac-mini4/.npm/_locks/selenium-webdriver-61fc4844104a7029.lock failed { [Error: EACCES, open '/Users/noimac-mini4/.npm/_locks/selenium-webdriver-61fc4844104a7029.lock']
npm WARN locking   errno: 3,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/noimac-mini4/.npm/_locks/selenium-webdriver-61fc4844104a7029.lock' }
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "selenium-webdriver"
npm ERR! node v0.10.13
npm ERR! npm  v2.11.0

npm ERR! Attempt to unlock /Users/noimac-mini4/node_modules/npm/node_modules/selenium-webdriver, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/noimac-mini4/node_modules/npm/node_modules/npm-debug.log
```

**Comment by KenanY** [comment]
@Agpandey Looks like your current user does not have the permissions necessary to read/write to `npm` cache directory. Maybe try taking ownership of that directory?:

``` sh
$ sudo chown -R $(whoami) "$HOME/.npm"
```

**Comment by Agpandey** [comment]
HI Kenan,
When I run following commands I am getting error-
Chown:  whoami:  illegal user name

Do I need to ask system admin to give some kind of permission? If yes then what exactly I need to ask?


Thanks,
Akhilesh Pandey

**Comment by Agpandey** [comment]
When i run $ sudo chown -R $(whoami) "$HOME/.npm" commands i am getting message saying Chown illigal option --n.

What to do now

**Comment by KenanY** [comment]
@Agpandey Sorry I never responded; I guess I was just lost as to what to try next :)

Are you still having this issue by any chance?

**Comment by Agpandey** [comment]
Hi Kenan,

This was old issue and its resolved, I don’t remember what I changed, but its resolved.

Thanks,
Akhilesh Pandey
