### ISSUE TITLE
private module behind http auth

### ISSUE THREAD

**Issue by chok** [npm/npm#8435]
npm: 2.11.0
node: 0.12.4

With this version of npm, if I do :

``` bash
npm install --save git+https://my.domain.com/my/repo.git
```

I obtain :

``` bash
npm ERR! fatal: Authentication failed for 'https://my.domain.com/my/repo.git'
```

With previous versions of npm, credentials was asked during the process to download the module. Is it possible with new versions ?

**Comment by WORMSS** [comment]
I have the same problem. Was working before I updated npm.
Was working in v2.3.5.
