### ISSUE TITLE
 npm install uglify-js or  npm install uglify-js -g is not working on my mac.

### ISSUE THREAD

**Issue by pravin-mindstix** [npm/npm#8442]
npm install uglify-js gives following error

npm WARN package.json cantoric@0.0.1 No repository field.
npm WARN package.json cantoric@0.0.1 No readme data.
npm http GET https://registry.npmjs.org/uglify-js
npm http 304 https://registry.npmjs.org/uglify-js
npm http GET https://registry.npmjs.org/source-map/0.1.34
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/uglify-to-browserify
npm http GET https://registry.npmjs.org/yargs
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/source-map/0.1.34
npm http 304 https://registry.npmjs.org/yargs
npm http 304 https://registry.npmjs.org/uglify-to-browserify
npm WARN package.json uglify-to-browserify@1.0.2 No readme data.
npm http GET https://registry.npmjs.org/camelcase
npm http GET https://registry.npmjs.org/decamelize
npm http GET https://registry.npmjs.org/wordwrap/0.0.2
npm http GET https://registry.npmjs.org/window-size/0.1.0
npm http GET https://registry.npmjs.org/amdefine
npm http 304 https://registry.npmjs.org/camelcase
npm http 304 https://registry.npmjs.org/window-size/0.1.0
npm http 304 https://registry.npmjs.org/decamelize
npm http 304 https://registry.npmjs.org/wordwrap/0.0.2
npm ERR! Error: No compatible version found: camelcase@'^1.0.2'
npm ERR! Valid install targets:
npm ERR! ["1.0.0","1.0.1","1.0.2","1.1.0"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:709:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:631:10
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 13.4.0
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "uglify-js"
npm ERR! cwd /Users/urmichawda/cantoricCloud
npm ERR! node -v v0.10.7
npm ERR! npm -v 1.2.21
npm http 304 https://registry.npmjs.org/amdefine
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/urmichawda/cantoricCloud/npm-debug.log
npm ERR! not ok code 0

**Comment by pravin-mindstix** [comment]
I have installed 
npm install camelcase

and then
 npm install source-map
Its not reproducing this error now.

**Comment by KenanY** [comment]
@pravin-mindstix I see that you have resolved this issue by manually installing the problematic dependencies yourself, but you should nevertheless understand why you were receiving the error you were.

`npm@1.2.21` is _extremely_ old, and does not support the `^` semver operator you see here:

```
npm ERR! Error: No compatible version found: camelcase@'^1.0.2'
```

hence, `npm` fails to find a valid version of `camelcase` which satisfies that range. The solution to this issue is to simply [upgrade](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm).

**Comment by pravin-mindstix** [comment]
Thanks KenanY for sharing this, its really helpful.
