### ISSUE TITLE
npm install not working (Cyberoam enabled)

### ISSUE THREAD

**Issue by technoknol** [npm/npm#8445]
Hello,

In my office they have installed CyberOam, it requires me to enter username and password in webpage. located at 192.168.10.4:8090 ,
I have tried setting proxy to 
```
http://usrnm:passwd@192.168.10.4:8090
```
but it's not working, giving error like
```
     Unexpected token <
```
What should I do ?
Please suggest.

**Comment by KenanY** [comment]
@technoknol Are you still seeing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.

**Comment by technoknol** [comment]
It was too long ago, and now I am in other company even, where nothing is restricted. 
Thanks though.
