### ISSUE TITLE
osenv in valid version

### ISSUE THREAD

**Issue by kestrada** [npm/npm#8446]
I am getting an invalid version "1.0" error when I run the command npm install osenv --save.  Here is the log:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'osenv',
1 verbose cli   '--save' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose stack Error: Invalid version: "1.0"
5 verbose stack     at Object.module.exports.fixVersionField (C:\Program Files\nodejs\node_modules\npm\node_modules\normalize-package-data\lib\fixer.js:190:13)
5 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\normalize-package-data\lib\normalize.js:30:38
5 verbose stack     at Array.forEach (native)
5 verbose stack     at normalize (C:\Program Files\nodejs\node_modules\npm\node_modules\normalize-package-data\lib\normalize.js:29:15)
5 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:368:33)
5 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:127:33)
5 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:317:48
5 verbose stack     at evalmachine.<anonymous>:263:20
5 verbose stack     at OpenReq.Req.done (C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:141:5)
5 verbose stack     at OpenReq.done (C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:61:22)
6 verbose cwd C:\Users\kestrada\Desktop\lorikeet
7 error Windows_NT 6.1.7601
8 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "osenv" "--save"
9 error node v0.12.2
10 error npm  v2.7.4
11 error Invalid version: "1.0"
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]

I am not sure what to do to fix this?

**Comment by KenanY** [comment]
@kestrada Looks like the `"version"` property in your `package.json` is not valid [SemVer](http://semver.org/), as per the [documentation](https://docs.npmjs.com/files/package.json#version):

> Version must be parseable by [node-semver](https://github.com/isaacs/node-semver)

Perhaps you should change it to `"1.0.0"`?

**Comment by kestrada** [comment]
That worked!  Thank you very much for your help.
