### ISSUE TITLE
Getting particular node name as array type

### ISSUE THREAD

**Issue by dsamit** [npm/npm#8447]
I am trying to parse a xml string to json in such a way that a node having particular name should always be an array type.
There is one option "explicitArray " while parsing. 
But it works for all of the elements.
I need array type conversion for a node having particular name.
I am not able to proceed for this.
Please help me out.
Any help from you people  matters a lot for me and  project development .

**Comment by KenanY** [comment]
@dsamit I'm sorry, this issue tracker is for bugs and feature requests in `npm`, the package manager. You should ask for help on a site like StackOverflow, perhaps.

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
