### ISSUE TITLE
npm install in a shrinkwrapped project performs only partial update of node_modules

### ISSUE THREAD

**Issue by IgorMinar** [npm/npm#8452]
If I have a project that is shrinkwrapped and I run `npm install` in the project for the first time, the dependencies are correctly pulled in and installed into node_modules and are in sync with the shrinkwrap definition.

If however, the npm-shrinkwrap.json changes in the source repository and I check out the change into my working directory and run `npm install`, npm client will only update dependencies that that got a version bump, but will not fully restore node_modules into a state that is in sync with the npm-shrinkwrap.json. This is especially true if the npm-shrinkwrap now has different structure due to deduping that happened as a result of a top level dependency being installed and shrinkwrapped. These structural changes to the dependency tree will not be reflected in node_modules after `npm install`.

The impact of this bug is that the only safe way to update node_modules for shrinkwrapped projects is to always delete node_modules and install all of the dependencies from scratch, which typically is a very expensive operation.

npm version affected: 2.11.0 and older.

**Comment by othiym23** [comment]
A bunch of this has been affected by the changes in `npm@3`, so this may be fixed. @iarna is going to do some investigation and will let you know where things stand right now.

**Comment by othiym23** [comment]
This has been moved to the [npm roadmap](https://github.com/npm/npm/wiki/Roadmap), which we're using instead of the confusing `next-*` labels now.

**Comment by iarna** [comment]
This is one of the core new features of npm@3 and should be resolved there.

**Comment by IgorMinar** [comment]
yay!
