### ISSUE TITLE
question on etc folder created by npm

### ISSUE THREAD

**Issue by smartmouse** [npm/npm#8455]
I saw that an etc folder created inside my node install path.  However, the etc folder is empty.
Is there any uses of the etc folder?  or just some unintended left over  folder?
Do we need to clean up manually?
Thanks in advance for your help.

npm version is  2.10.1
node version is 0.12.4

**Comment by Raynos** [comment]
It's a known issue ( https://github.com/npm/npm/pull/7249 ).

**Comment by iarna** [comment]
Closing as duplicate.
