### ISSUE TITLE
error during npm install

### ISSUE THREAD

**Issue by onizo** [npm/npm#8457]
```
npm ERR! Error: Callback called more than once.
npm ERR!     at errorHandler (/usr/share/npm/lib/utils/error-handler.js:80:16)
npm ERR!     at save (/usr/share/npm/lib/install.js:329:12)
npm ERR!     at /usr/share/npm/lib/install.js:98:7
npm ERR!     at /usr/share/npm/lib/install.js:188:5
npm ERR!     at /usr/share/npm/node_modules/read-installed/read-installed.js:119:5
npm ERR!     at /usr/share/npm/node_modules/read-installed/read-installed.js:233:14
npm ERR!     at cb (/usr/lib/nodejs/slide/lib/async-map.js:48:11)
npm ERR!     at /usr/share/npm/node_modules/read-installed/read-installed.js:233:14
npm ERR!     at cb (/usr/lib/nodejs/slide/lib/async-map.js:48:11)
npm ERR!     at /usr/share/npm/node_modules/read-installed/read-installed.js:233:14

npm ERR! System Linux 3.16.0-30-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/ops/projects/ma-insights
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ops/projects/ma-insights/npm-debug.log
npm ERR! not ok code 0
```

**Comment by KenanY** [comment]
@onizo Does this also occur if you [upgrade](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) to the latest stable release of `npm`?

**Comment by onizo** [comment]
ops @ ma-insights-~-$ npm -v

1.3.10

On Wed, Jun 3, 2015 at 8:59 PM, Kenan Yildirim <notifications@github.com>
wrote:

> @onizo <https://github.com/onizo> Does this also occur if you upgrade
> <https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm>
> to the latest stable release of npm?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/npm/npm/issues/8457#issuecomment-108711655>.
>



-- 
-jblack

**Comment by KenanY** [comment]
@onizo Erm, did you try upgrading? Your version has not changed.

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
