### ISSUE TITLE
git protocol not available

### ISSUE THREAD

**Issue by PetrPrazak** [npm/npm#8461]
During installation this command
git clone --template=/Users/prazak/.npm/_git-remotes/_templates --mirror git://github.com/frantic/stacktrace-parser.git /Users/prazak/.npm/_git-remotes/git-github-com-frantic-stacktrace-parser-git-cb466409:
fails because it is not possible to connect to github.com using the git protocol. 
Could it be possible to add a fallback to the http protocol? Thanks.

**Comment by aredridel** [comment]
You can configure git to rewrite these:

```
[url "git@github.com:"]
        insteadOf = https://github.com/
```

**Comment by thefourtheye** [comment]
Same as @aredridel said. But, if you want to configure globally you can use this command

    git config --global url.https://github.com/.insteadOf git://github.com/

This will make `git` to use `https` protocol to connect to github.com instead of git protocol.

**Comment by PetrPrazak** [comment]
Thanks, it works this way.
