### ISSUE TITLE
Install the packages into specific folder?

### ISSUE THREAD

**Issue by xlaywan** [npm/npm#8464]
How can I install package into another folder than `node_modules`?. `--prefix dir` will still install into node_modules. I think `node_modules` not very suitable folder for the front-end packages. I do not talk about package development, I just want to install my app's deps into my folder.

**Comment by KenanY** [comment]
@xlaywan Sorry, this is never going to happen. Please see [this FAQ entry](https://docs.npmjs.com/misc/faq#node-modules-is-the-name-of-my-deity-s-arch-rival-and-a-forbidden-word-in-my-religion-can-i-configure-npm-to-use-a-different-folder) for an explanation.

**Comment by othiym23** [comment]
"Never" is putting it too strongly – the npm team is considering new strategies for installing front end / browser dependencies, and at some point there will be features added to npm to support this use case. **There is no timeline for when these features will be added – they have _only just_ been added to npm's roadmap.** Therefore, for now @KenanY is correct, and that FAQ entry goes into the whys and wherefores of npm's installation strategy. Tools like `webpack` and `browserify` exist to help with packaging npm-installed assets for use by the front end, so if you want to have a better front-end development workflow, check those out.
