### ISSUE TITLE
"npm install" not installing all dependencies

### ISSUE THREAD

**Issue by adsteel** [npm/npm#8466]
To get this bug, I added `"youarei": "1.0.1"` to the dependencies and with `npm i`. I then deleted that module by hand, and removed it from the depencies list, and re-ran `npm i && npm shrinkwrap`. Then I re-added that same module to the dependencies list and `npm i` ran without a hitch, but `npm shrinkwrap` produced the following error:

```
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "shrinkwrap"
npm ERR! node v0.10.38
npm ERR! npm  v2.5.1

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! missing: youarei@1.0.1, required by m4@
```

The only way I could get around this was by installing that module manually. This allowed `shrinkwrap` to update the npm-shrinkwrap.json file correctly.

```
$ npm install youarei@1.0.1
youarei@1.0.1 node_modules/youarei
$ npm shrinkwrap
wrote npm-shrinkwrap.json
```

**Comment by busches** [comment]
Are you still facing this issue using the latest version of `npm@2` or `npm@3`?

**Comment by adsteel** [comment]
@busches I haven't used npm shrinkwrap for at least a year, so I couldn't tell you, unfortunately.

**Comment by KenanY** [comment]
Closing as abandoned then. Can reopen if this is demonstrated to still be an issue.
