### ISSUE TITLE
Why can't we `<git remote url>@<version>`?

### ISSUE THREAD

**Issue by jehoshua02** [npm/npm#8468]
It seems to me, from reading the [documentation](https://docs.npmjs.com/cli/install), that it is not an option to install from a `<git remote url>` with a `@<version>` and my attempts to do so have proven this true.

I often install packages with npm that I have good reason *not* to publish to the npm registry but also can't justify setting up my own npm registry. But I must use `#<commit-ish>` instead of `@<version>`, which means that for each package in a chain of dependencies, I have to update the `package.json` and cut a release, just to get even a minor change all the way through.

For example, I've built a header for a family of web applications. These applications are all separate and we use npm to install the header into each of them. But because of the company-centric nature of the header, it really doesn't make sense to publish to the npm registry. So we mark it private and install with `<git remote url>`. The header in turn is broken up into a collection of small reusable components that are each in their own separate repository, creating a chain of dependencies. If I have to change one thing, I have to walk up the chain all the way back to the header, updating the `package.json` and cutting a release on each one to get the update all the way back up to the header.

I would love help come up with a solution but I'm afraid I'm not familiar enough with the problem to do that yet. I would love if `@<version>` could be used with `<git remote url>` but what would that involve? Would it be difficult? I would expect npm to do this sort of thing and I'm wondering why it doesn't.

**Comment by KenanY** [comment]
@jehoshua02 #3014, #3328, #3347, #3442, #3511, #4527, https://github.com/npm/npm/issues/5826, etc.

**Comment by iarna** [comment]
Closing as duplicate
