### ISSUE TITLE
when I run 'sudo npm install -g mean-cli' I get an ENOMEM in the error log

### ISSUE THREAD

**Issue by jeffsp** [npm/npm#8471]
```
/opt/mean % sudo npm install -g mean-cli
> mean-cli@0.10.12 preinstall /usr/local/lib/node_modules/mean-cli
> node ./scripts/preinstall
npm WARN deprecated json-file-plus@2.0.0: Before v3.0.0, errors in fs.writeFile would not be propagated
> mean-health@0.1.7 postinstall /usr/local/lib/node_modules/mean-cli/node_modules/mean-health
> node ./postinstall.js
-
> kerberos@0.0.12 install /usr/local/lib/node_modules/mean-cli/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

/opt/mean % tail npm-debug.log              
31178 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "mean-cli"
31179 error node v0.12.1
31180 error npm  v2.5.1
31181 error code ENOMEM
31182 error errno ENOMEM
31183 error syscall spawn
31184 error spawn ENOMEM
31185 error If you need help, you may report this error at:
31185 error     <http://github.com/npm/npm/issues>
31186 verbose exit [ 1, true ]

/opt/mean % npm --version
2.5.1
```

**Comment by KenanY** [comment]
@jeffsp I take it `ENOMEM` means you ran out of memory?

**Comment by jeffsp** [comment]
@KenanY Yes.  ENOMEM is the Linux system error meaning 'out of memory'.

I am running Ubuntu 14.04 on a VPS with 512GB of memory.

It didn't really occur to me that I actually ran out of memory.  Seriously?  npm needs more than that just to install the cli?  Naw, I don't believe it.

**Comment by othiym23** [comment]
@jeffsp I'd recommend upgrading to Node 0.12.4 and `npm@latest` – Node 0.12.1 was kind of a doomed release, and it's possible you're running into one of its edge cases. It's pretty unlikely npm or node are using 512GiB of RAM, especially because V8 would barf long before then if it's stack or the heap got much bigger than a couple gigs. I think there's probably something else happening on that host.

**Comment by jeffsp** [comment]
That fixed it. Thanks.

**Comment by jeffsp** [comment]
Oops, no it is still broken.  I got confused.

I am now at version 0.12.4 of node, but I can't install the latest version of npm:

% sudo npm install -g npm
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
npm WARN unmet dependency /usr/local/lib/node_modules/mean-cli/node_modules/npm requires request@'~2.56.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/mean-cli/node_modules/request,
npm WARN unmet dependency which is version 2.57.0
npm WARN unmet dependency /usr/local/lib/node_modules/mean-cli/node_modules/mongoose/node_modules/bson/node_modules/bson-ext/node_modules/node-pre-gyp/node_modules/tar-pack/node_modules/fstream requires graceful-fs@'~3.0.2' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/mean-cli/node_modules/mongoose/node_modules/bson/node_modules/bson-ext/node_modules/node-pre-gyp/node_modules/tar-pack/node_modules/graceful-fs,
npm WARN unmet dependency which is version 1.2.3
npm@2.11.1 /usr/local/lib/node_modules/npm

% npm --version
2.10.1

% node --version
v0.12.4

**Comment by othiym23** [comment]
What happens when you run `which npm`? I suspect that the npm that's running is in `/usr/bin`, and the one that you're installing with `npm install -g npm` is going to `/usr/local/bin`. You may need to rejigger things on your path a little.

**Comment by jeffsp** [comment]
Hmm. Maybe I needed to log out and log back in because now I am at npm version 2.11.1.

However, I'm still having trouble installing mean-cli:

 jsp@gorilla ~ % npm --version
2.11.1
 jsp@gorilla ~ % node --version
v0.12.4
 jsp@gorilla ~ % sudo npm install -g mean-cli
\
> mean-cli@0.10.12 preinstall /usr/local/lib/node_modules/mean-cli
> node ./scripts/preinstall

npm WARN deprecated json-file-plus@2.0.0: Before v3.0.0, errors in fs.writeFile would not be propagated
 
> mean-health@0.1.7 postinstall /usr/local/lib/node_modules/mean-cli/node_modules/mean-health
> node ./postinstall.js

 jsp@gorilla ~ % mean
zsh: command not found: mean

**Comment by jeffsp** [comment]
Oh, and I should have answered your question:

 jsp@gorilla ~ % which node
/usr/local/bin/node

 jsp@gorilla ~ % which npm
/usr/local/bin/npm

**Comment by jeffsp** [comment]
I'm still having problems with this:

    jsp@gorilla ~/projects % node --version
    v0.12.4
    jsp@gorilla ~/projects % npm --version
    2.11.3
    jsp@gorilla ~/projects % sudo npm install -g mean-cli
    /
    > mean-cli@0.10.13 preinstall /usr/local/lib/node_modules/mean-cli
    > node ./scripts/preinstall

    npm WARN deprecated json-file-plus@2.0.0: Before v3.0.0, errors in fs.writeFile would not be     propagated
 
    > mean-health@0.1.7 postinstall /usr/local/lib/node_modules/mean-cli/node_modules/mean-health
    > node ./postinstall.js
    ...

    jsp@gorilla ~/projects % mean
    zsh: command not found: mean
    jsp@gorilla ~/projects % cat npm-debug.log
    ...
    39305 error Linux 3.13.0-43-generic
    39306 error argv "node" "/usr/local/bin/npm" "install" "-g" "mean-cli"
    39307 error node v0.12.4
    39308 error npm  v2.11.3
    39309 error code ENOMEM
    39310 error errno ENOMEM
    39311 error syscall spawn
    39312 error spawn ENOMEM
    39313 error If you need help, you may report this error at:
    39313 error     <https://github.com/npm/npm/issues>
    39314 verbose exit [ 1, true ]
    jsp@gorilla ~/projects % ls /usr/local/bin
    bower  forever  grunt  gulp  node  npm

Any ideas?

**Comment by jeffsp** [comment]
I finally fixed this. It really was running out of memory.  My Digital Ocean VPS did not have a swap partition allocated.  When I allocated a swap space, all my problems went away.

I've seen folks recommend that you don't allocate a swap partition, but I think it's a contentious recommendation. The logic is: if you are having to use swap space, then you are running suboptimal and should buy more RAM.  The flip side of the argument is that if you ever do run out of memory, things can get ugly, as they did for me.

It still seems crazy to me that npm would require this much memory to install mean.io dependencies.

**Comment by ile** [comment]
I also have this issue on EC2 micro instance with 1GB of memory and no swap. Three node processes consume that much memory that npm install fails.

I could perhaps add the swap but with micro instance that would be an EBS volume, which would possibly lead to unexpected costs.

So I see no good work-arounds...

**Comment by amandogra** [comment]
jeffsp comment helped me nail this. If anyone else is facing this kind of issue (ENOMEM) try https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04
Add or increase swap space.
