### ISSUE TITLE
npm pack doesn't properly resolve bundled dependency tree

### ISSUE THREAD

**Issue by oliversalzburg** [npm/npm#8474]
Consider the following `package.json`:

``` json
{
  "name": "foo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "strip-ansi": "^2.0.1"
  },
  "dependencies": {
    "chalk": "^1.0.0"
  },
  "bundledDependencies": [
    "chalk"
  ]
}
```

When you `npm pack` this package, `strip-ansi` will be missing from the packaged chalk dependency.

To be clear, `strip-ansi` will be missing from `node_modules/chalk/node_modules`, even through `chalk` depends on `strip-ansi`.

**Comment by KenanY** [comment]
@oliversalzburg Because it is in the root `node_modules/`.

**Comment by oliversalzburg** [comment]
@KenanY Okay. But it won't be there in the packaged bundle, so the package will not work without manually installing the dependency, which is what the bundling was supposed to prevent in the first place.

**Comment by KenanY** [comment]
@oliversalzburg Ah I see the issue now.

**Comment by robertgroh** [comment]
This issue desribes the same problem as in #11287.

Can someone please mark these as duplicates?
