### ISSUE TITLE
can't install ionic

### ISSUE THREAD

**Issue by wt911122** [npm/npm#8481]
I'm trying to install cordova and ionic using command <pre>sudo npm install -g cordova ionic</pre>  on my Mac for several times. But a same error happens every time.
The error outputs include:
<pre>
FengmatoMacBook-Pro-2:~ tony$ sudo npm install -g cordova ionic
Password:
npm ERR! registry error parsing json
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "cordova" "ionic"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1

npm ERR! Unexpected end of input
npm ERR! {"_id":"cordova","_rev":"499-674870f43b6456536a7c9811b210c0af","name":"cordova","description":"Cordova command line interface tool","dist-tags":{"latest":"5.0.0","rc":"4.3.1","3.6.0-0.2.8":"3.6.0-0.2.8","nightly":"4.1.3-nightly.2014.10.21"},"versions":{"0.0.1":{"name":"cordova","version":"0.0.1","preferGlobal":"true","description":"Cordova client tool","main":"cordova","bin":{"cordova":"./..........
</pre>

**Comment by Philippe96** [comment]
Same problem

**Comment by lingxuesonga** [comment]
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "cordova" "ionic"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8

npm ERR! shasum check failed for /tmp/npm-1304-298e0fe1/registry.npmjs.org/ionic/-/ionic-1.7.16.tgz
npm ERR! Expected: aeff62ee70b10b1563d85b9d4ea7005640bbc584
npm ERR! Actual:   c2e75ad9285eb373ce6e85f5704fd05b719eccb9
npm ERR! From:     https://registry.npmjs.org/ionic/-/ionic-1.7.16.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by KenanY** [comment]
@lingxuesonga Your issue looking completely unrelated. Please try running `npm cache clean`, and if you still have this issue then please open a new issue.

**Comment by KenanY** [comment]
@wt911122 Still seeing this issue?

**Comment by KenanY** [comment]
Closing due to no response.
