### ISSUE TITLE
How to release new version?

### ISSUE THREAD

**Issue by xiaoshao** [npm/npm#8482]
I'm making a node module and I have published it as version 1.0.0. But I don't know how to release new version (2.0.0) when I changed something.
Could you tell me how to do it?

Another question I want to publish my module by CI. It ask me to input username password and email, When I run `npm adduser`.  Do you know other ways to add user which don't need any inputs?

**Comment by yoshuawuyts** [comment]
`npm version <major | minor | patch>` - https://docs.npmjs.com/cli/version

**Comment by xiaoshao** [comment]
Thanks @yoshuawuyts .

Do you know how to add user without input username and password?

**Comment by yoshuawuyts** [comment]
You could set your credentials as [`env` vars](https://docs.npmjs.com/misc/config#environment-variables) in your CI setup.

**Comment by xiaoshao** [comment]
cool, thanks for your answer @yoshuawuyts.

**Comment by yoshuawuyts** [comment]
(': @xiaoshao if you're question is answered, can you close this issue? Thanks!
