### ISSUE TITLE
npm run postversion has a different process.cwd() output when triggered by version hook

### ISSUE THREAD

**Issue by yoshuawuyts** [npm/npm#8483]
# npm run postversion has a different process.cwd() output when triggered by version hook

Ran into this using the `gh-publish` package, didn't understand why it failed to detect repositories in root. It appears that `process.cwd()` appends `/node_modules` to the path when triggered by a hook. This causes all sorts of problems, as the script will now try to detect files in `node_modules` rather than the project root.

The project (repro?) is avaible at [`yoshuawuyts/about`](https://github.com/yoshuawuyts/about/blob/master/package.json#L10).

- `OSX@10.10.2`
- `io.js@2.0.0`
-  `npm@2.11.1`

## Steps to reproduce
- Install an npm cli module locally (e.g. `gh-publish`)
- Create a script to trigger it from npm `postversion`. e.g. `"postversion": "gh-publish -d dir"`
- Log `process.cwd()` from within the cli module. e.g. `console.log(process.cwd())`
- __manual__: Run the script as `npm run postversion`
- __hook__: Run the script as `npm version patch`

## Expected results
- __manual__: `$(pwd)` is logged
- __hook__: `$(pwd)` is logged

## Actual results
- __manual__: `$(pwd)` is logged
- __hook__: `$(pwd)/node_modules` is logged

**Comment by othiym23** [comment]
Take a look at the [release notes](https://github.com/npm/npm/releases/v2.11.2) for `npm@2.11.2`. ;)

**Comment by yoshuawuyts** [comment]
Ah, perfect! Didn't catch it was fixed because `npm i -g npm` installed `npm@2.11.1`, where I assumed it was the latest. Thanks! :D
