### ISSUE TITLE
unable to install phonegap

### ISSUE THREAD

**Issue by gauravsingh09** [npm/npm#8484]
I try installing phonegap by typing npm install -g phonegap
But its giving me error..like 
```
npm ERR! windows_NT 6.1.7600
npm ERR!  argv "d:\\
npm ERR! node v0.12.4
npm ERR! npm v2.10.1
npm ERR! Code ENOENT
npm  ERR! errno ENOENT
npm ERR! syscall getaddrinfo 

npm ERR! enoent getaddrinfo ENOENT
```

Plz help me.....

**Comment by smikes** [comment]
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

You may want to try updaring `npm` as well -- to update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

Thanks!

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
