### ISSUE TITLE
Signed NPM packages

### ISSUE THREAD

**Issue by corpix** [npm/npm#8489]
Why? Lets imagine that I'm a bad guy.
    1. I can run untrusted code with package.json [scripts][scripts-link] on users computers.
    2. If I steal npm registry authentication token of some maintainer of popular module I could create malicious version of that package. This release could include malicious package.json [scripts][scripts-link] or malicious code modifications.

At this time there is no protection from such things. I believe that PGP signature(that many Linux repos has) could solve this and all NPM packages in the future SHOULD be signed. For non signed packages package manager MUST show a warning before trying to do any operation with it.

[scripts-link]: https://docs.npmjs.com/misc/scripts

**Comment by zkat** [comment]
Hey! Indeed, signed packages are a pretty nice thing and it would be nice to have a good solution for it. This has come up before: See #4016 and node-forward/discussions#29 for the discussions that have gone one about it (and what we kinda already have in place to address part of the problem in re validity).

**Comment by corpix** [comment]
Sounds good for me.
Should I close this issue and continue discussion inside https://github.com/node-forward/discussions/issues/29?

**Comment by zkat** [comment]
Yup!
