### ISSUE TITLE
Failed npm install

### ISSUE THREAD

**Issue by monica-joseph** [npm/npm#8490]
The error  says :
```
2257 verbose stack     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1167:12)
2257 verbose stack     at IncomingMessage.emit (events.js:129:20)
2257 verbose stack     at _stream_readable.js:908:16
2258 verbose cwd C:\Users\Monica Joseph\Desktop\NODEprojects\myMEAN
2259 error Windows_NT 6.3.9600
2260 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
2261 error node v0.12.4
2262 error npm  v2.10.1
2263 error Unexpected end of input
```
![npm-debug log removejpg](https://cloud.githubusercontent.com/assets/12787293/8025405/2ecb9504-0d73-11e5-85ca-d4b99edd2e4c.jpg)

**Comment by smikes** [comment]
Thanks for reporting this.

Are you still seeing this problem?  If so, could you please run it again with these options:

```
> npm install -ddd
```

This should generate a lot of messages, and the file `npm-debug.log` in the current directory.  Upload that file to https://gist.github.com and post a link here - we need more contextual information to troubleshoot this problem.

Thanks!

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
