### ISSUE TITLE
npm does not update to latest version in iojs

### ISSUE THREAD

**Issue by tristanisfeld** [npm/npm#8492]
Have not tested in nodejs.
iojs version 2.2.1
npm version 2.11.0
Windows 10
Git bash

npm update -g npm@latest
C:\Users\trist\AppData\Roaming\npm\npm -> C:\Users\trist\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
npm@2.11.1 C:\Users\trist\AppData\Roaming\npm\node_modules\npm

Same results with npm@2.11.1 and npm@2.11.2

$ npm -v
2.11.0
npm-check -u -g shows and update for 2.11.1, after accepting and installing, it announces update complete, run tests to make sure everything works. running npm -v again gives 2.11.0. Yo doctor informs of outdated npm, running the same process.

using curl -L https://www.npmjs.org/install.sh | sh updates npm to 2.11.1
it will then give permission errors with various npm operations requesting system admin to perform the task. yo doctor still throws outdated npm error. While running npm install -g npm@latest (or 2.11.2 or 2.11.2) you get this:

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "c:\\Program Files\\iojs\\node.exe" "c:\\Program Files\\iojs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "npm@latest"
npm ERR! node v2.2.1
npm ERR! npm  v2.11.1
npm ERR! path c:\Program Files\iojs\npm
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall open

npm ERR! Error: EPERM: operation not permitted, open 'c:\Program Files\iojs\npm'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, open 'c:\Program Files\iojs\npm']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'open',
npm ERR!   path: 'c:\\Program Files\\iojs\\npm' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
npm ERR! error rolling back Error: EPERM: operation not permitted, lstat 'c:\Program Files\iojs\npm'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EPERM: operation not permitted, lstat 'c:\Program Files\iojs\npm']
npm ERR! error rolling back   errno: -4048,
npm ERR! error rolling back   code: 'EPERM',
npm ERR! error rolling back   syscall: 'lstat',
npm ERR! error rolling back   path: 'c:\\Program Files\\iojs\\npm' }

npm ERR! Please include the following file with any support request:
npm ERR!     c:\users\trist\_projects\npm-debug.log
/c/Program Files/iojs/npm: line 14:  9228 Signal 112              (core dumped) "$basedir/node" "$basedir/node_modules/npm/bin/npm-cli.js" "$@"

$ npm -v
sh: npm: command not found

then need to run installer or curl again for npm use.
curl npm breaks some global packages while running npm install throwing errors requesting packages be installed globally.

**Comment by drewish** [comment]
I'd love to know how to work around this. I'm trying to get Travis-CI to run tests for 0.8 which needs a newer version of npm but because of this I can't just do a `npm update -g npm`

**Comment by KenanY** [comment]
@drewish I usually do [this](https://github.com/npm/npm/wiki/Troubleshooting#travis-projects-using-08-cant-upgrade-to-npm-2) if I want to get `npm@2` on Node.js v0.8.

**Comment by drewish** [comment]
Ah nice, much cleaner than what I'd come up with.
