### ISSUE TITLE
Allow changing the prefix from .npmrc

### ISSUE THREAD

**Issue by alexandernst** [npm/npm#8493]
Disclaimer: I'm not sure if this is possible, if so, sorry for the opened issue.

Currently NPM doesn't respect the `prefix`set in `.npmrc`. I saw [this](https://github.com/npm/npm/issues/6358), and while I understand that NPM is designed to put everything in `node_modules`, I can't really understand what would break if that directory name/path is changed.

Moreover, it just doesn't make any sense that changing the prefix from the `.npmrc` file doesn't work, but using the `--prefix` arg in the command line works.

Please support properly the `prefix` property.

**Comment by othiym23** [comment]
Changing `prefix` in the configuration file has never changed the name of the folder that modules get installed into, which is hardcoded to `node_modules`. See npm's FAQ for details. Instead, it lets users change to where globally installed packages (`npm install -g`) are put. The default depends on platform, but on Linux it's `/usr/local`, and changing it allows you to put your binary scripts and manpages in your home directory instead (for example).

Using `--prefix` from the command line tells npm to run its command relative to the path provided to `prefix`. It's a little confusing that the two things are spelled the same but seem to do different things, but the configuration value is actually used the same inside the code. This is the documented behavior, and how npm has always worked.

**Comment by diogobaeder** [comment]
I recognize this isn't a "bug" per se, but no doubt it's a design flaw. I suggest this changes to allow the installation path to be determined in the `.npmrc` file. At the very least, there could be a new config that could change this behavior, as forcing users to pass along `--prefix=` in every single npm command related to their modules directory is rather irritating an impractical.
