### ISSUE TITLE
npm install error 

### ISSUE THREAD

**Issue by bradbergeron-us** [npm/npm#8497]
```
npm verb rmMans man files are [ 'gulp.1' ] in /Volumes/OSX_HD/Users/bradleybergeron/.npm-packages/share/man
npm verb gentlyRm vacuuming from /Volumes/OSX_HD/Users/bradleybergeron/.npm-packages/bin/gulp up to /Volumes/OSX_HD/Users/bradleybergeron/.npm-packages
npm verb gentlyRm vacuuming from /Volumes/OSX_HD/Users/bradleybergeron/.npm-packages/share/man/man1/gulp.1.1 up to /Volumes/OSX_HD/Users/bradleybergeron/.npm-packages
npm info postuninstall gulp@3.9.0
npm verb gentlyRm don't care about contents; nuking /Volumes/OSX_HD/Users/bradleybergeron/.npm-packages/lib/node_modules/gulp

npm ERR! Please include the following file with any support request:
npm ERR!     /Volumes/OSX_HD/Users/bradleybergeron/npm-debug.log
```

**Comment by bradbergeron-us** [comment]
325 verbose etag https://registry.npmjs.org/archy from cache
326 verbose get saving archy to /Volumes/OSX_HD/Users/bradleybergeron/.npm/registry.npmjs.org/archy/.cache.json
327 http 304 https://registry.npmjs.org/orchestrator
328 silly get cb [ 304,
328 silly get   { date: 'Mon, 08 Jun 2015 13:16:19 GMT',
328 silly get     via: '1.1 varnish',
328 silly get     'cache-control': 'max-age=60',
328 silly get     etag: '"2234CQLCKM58OHHIR1UMK6Q60"',
328 silly get     age: '30',
328 silly get     connection: 'keep-alive',
328 silly get     'x-served-by': 'cache-jfk1024-JFK',
328 silly get     'x-cache': 'HIT',
328 silly get     'x-cache-hits': '1',
328 silly get     'x-timer': 'S1433769379.979795,VS0,VE0',
328 silly get     vary: 'Accept' } ]
329 verbose etag https://registry.npmjs.org/orchestrator from cache
330 verbose get saving orchestrator to /Volumes/OSX_HD/Users/bradleybergeron/.npm/registry.npmjs.org/orchestrator/.cache.json
331 http 304 https://registry.npmjs.org/vinyl-fs
332 silly get cb [ 304,
332 silly get   { date: 'Mon, 08 Jun 2015 13:16:19 GMT',
332 silly get     via: '1.1 varnish',
332 silly get     'cache-control': 'max-age=60',
332 silly get     etag: '"7R67WBHV90IFE2EWKC6T7M74D"',
332 silly get     age: '56',
332 silly get     connection: 'keep-alive',
332 silly get     'x-served-by': 'cache-jfk1034-JFK',
332 silly get     'x-cache': 'HIT',
332 silly get     'x-cache-hits': '2',
332 silly get     'x-timer': 'S1433769379.982902,VS0,VE0',
332 silly get     vary: 'Accept' } ]
333 verbose etag https://registry.npmjs.org/vinyl-fs from cache
334 verbose get saving vinyl-fs to /Volumes/OSX_HD/Users/bradleybergeron/.npm/registry.npmjs.org/vinyl-fs/.cache.json
335 http 304 https://registry.npmjs.org/v8flags
336 silly get cb [ 304,
336 silly get   { date: 'Mon, 08 Jun 2015 13:16:19 GMT',
336 silly get     via: '1.1 varnish',
336 silly get     'cache-control': 'max-age=60',
336 silly get     etag: '"7N3YCPQA53BYWR2XC8CRO3PKV"',
336 silly get     age: '29',
336 silly get     connection: 'keep-alive',
336 silly get     'x-served-by': 'cache-jfk1022-JFK',
336 silly get     'x-cache': 'HIT',
336 silly get     'x-cache-hits': '2',
336 silly get     'x-timer': 'S1433769379.982862,VS0,VE0',
336 silly get     vary: 'Accept' } ]
337 verbose etag https://registry.npmjs.org/v8flags from cache
338 verbose get saving v8flags to /Volumes/OSX_HD/Users/bradleybergeron/.npm/registry.npmjs.org/v8flags/.cache.json
339 silly addNameRange number 2 { name: 'liftoff', range: '>=2.1.0 <3.0.0', hasData: true }
340 silly addNameRange versions [ 'liftoff',
340 silly addNameRange   [ '0.1.0',
340 silly addNameRange     '0.2.0',
340 silly addNameRange     '0.3.0',
340 silly addNameRange     '0.4.0',
340 silly addNameRange     '0.5.0',
340 silly addNameRange     '0.6.0',
340 silly addNameRange     '0.7.0',
340 silly addNameRange     '0.8.0',
340 silly addNameRange     '0.8.1',
340 silly addNameRange     '0.8.2',
340 silly addNameRange     '0.8.3',
340 silly addNameRange     '0.8.4',
340 silly addNameRange     '0.8.5',
340 silly addNameRange     '0.8.6',
340 silly addNameRange     '0.8.7',
340 silly addNameRange     '0.9.0',
340 silly addNameRange     '0.9.1',
340 silly addNameRange     '0.9.2',
340 silly addNameRange     '0.9.3',
340 silly addNameRange     '0.9.4',
340 silly addNameRange     '0.9.5',
340 silly addNameRange     '0.9.6',
340 silly addNameRange     '0.9.7',
340 silly addNameRange     '0.9.8',
340 silly addNameRange     '0.10.0',
340 silly addNameRange     '0.11.0',
340 silly addNameRange     '0.11.1',
340 silly addNameRange     '0.11.2',
340 silly addNameRange     '0.11.3',
340 silly addNameRange     '0.12.0',
340 silly addNameRange     '0.12.1',
340 silly addNameRange     '0.13.0',
340 silly addNameRange     '0.13.1',
340 silly addNameRange     '0.13.2',
340 silly addNameRange     '0.13.3',
340 silly addNameRange     '0.13.5',
340 silly addNameRange     '0.13.6',
340 silly addNameRange     '1.0.0',
340 silly addNameRange     '1.0.2',
340 silly addNameRange     '1.0.3',
340 silly addNameRange     '1.0.4',
340 silly addNameRange     '2.0.0',
340 silly addNameRange     '2.0.1',
340 silly addNameRange     '2.0.2',
340 silly addNameRange     '2.0.3',
340 silly addNameRange     '2.1.0' ] ]
341 silly addNamed liftoff@2.1.0
342 verbose addNamed "2.1.0" is a plain semver version for liftoff
343 silly addNameRange number 2 { name: 'semver', range: '>=4.1.0 <5.0.0', hasData: true }
344 silly addNameRange versions [ 'semver',
344 silly addNameRange   [ '1.0.0',
344 silly addNameRange     '1.0.1',
344 silly addNameRange     '1.0.2',
344 silly addNameRange     '1.0.3',
344 silly addNameRange     '1.0.4',
344 silly addNameRange     '1.0.5',
344 silly addNameRange     '1.0.6',
344 silly addNameRange     '1.0.7',
344 silly addNameRange     '1.0.8',
344 silly addNameRange     '1.0.9',
344 silly addNameRange     '1.0.10',
344 silly addNameRange     '1.0.11',
344 silly addNameRange     '1.0.12',
344 silly addNameRange     '1.0.13',
344 silly addNameRange     '1.0.14',
344 silly addNameRange     '1.1.0',
344 silly addNameRange     '1.1.1',
344 silly addNameRange     '1.1.2',
344 silly addNameRange     '1.1.3',
344 silly addNameRange     '1.1.4',
344 silly addNameRange     '2.0.0-alpha',
344 silly addNameRange     '2.0.0-beta',
344 silly addNameRange     '2.0.1',
344 silly addNameRange     '2.0.2',
344 silly addNameRange     '2.0.3',
344 silly addNameRange     '2.0.4',
344 silly addNameRange     '2.0.5',
344 silly addNameRange     '2.0.6',
344 silly addNameRange     '2.0.7',
344 silly addNameRange     '2.0.8',
344 silly addNameRange     '2.0.9',
344 silly addNameRange     '2.0.10',
344 silly addNameRange     '2.0.11',
344 silly addNameRange     '2.1.0',
344 silly addNameRange     '2.2.0',
344 silly addNameRange     '2.2.1',
344 silly addNameRange     '2.3.0',
344 silly addNameRange     '2.3.1',
344 silly addNameRange     '2.3.2',
344 silly addNameRange     '3.0.0',
344 silly addNameRange     '3.0.1',
344 silly addNameRange     '4.0.0',
344 silly addNameRange     '4.0.2',
344 silly addNameRange     '4.0.3',
344 silly addNameRange     '4.1.0',
344 silly addNameRange     '4.1.1',
344 silly addNameRange     '4.2.0',
344 silly addNameRange     '4.2.1',
344 silly addNameRange     '4.2.2',
344 silly addNameRange     '4.3.0',
344 silly addNameRange     '4.3.1',
344 silly addNameRange     '4.3.2',
344 silly addNameRange     '4.3.3',
344 silly addNameRange     '4.3.4',
344 silly addNameRange     '4.3.5',
344 silly addNameRange     '4.3.6' ] ]
345 silly addNamed semver@4.3.6
346 verbose addNamed "4.3.6" is a plain semver version for semver
347 silly addNameRange number 2 { name: 'deprecated', range: '>=0.0.1 <0.0.2', hasData: true }
348 silly addNameRange versions [ 'deprecated', [ '0.0.1' ] ]
349 silly addNamed deprecated@0.0.1
350 verbose addNamed "0.0.1" is a plain semver version for deprecated
351 silly addNameRange number 2 { name: 'interpret', range: '>=0.6.2 <0.7.0', hasData: true }
352 silly addNameRange versions [ 'interpret',
352 silly addNameRange   [ '0.1.0',
352 silly addNameRange     '0.2.0',
352 silly addNameRange     '0.3.0',
352 silly addNameRange     '0.3.1',
352 silly addNameRange     '0.3.2',
352 silly addNameRange     '0.3.3',
352 silly addNameRange     '0.3.4',
352 silly addNameRange     '0.3.5',
352 silly addNameRange     '0.3.6',
352 silly addNameRange     '0.3.7',
352 silly addNameRange     '0.3.8',
352 silly addNameRange     '0.3.9',
352 silly addNameRange     '0.3.10',
352 silly addNameRange     '0.4.0',
352 silly addNameRange     '0.4.1',
352 silly addNameRange     '0.4.2',
352 silly addNameRange     '0.4.3',
352 silly addNameRange     '0.5.0',
352 silly addNameRange     '0.5.1',
352 silly addNameRange     '0.5.2',
352 silly addNameRange     '0.6.0',
352 silly addNameRange     '0.6.1',
352 silly addNameRange     '0.6.2' ] ]
353 silly addNamed interpret@0.6.2
354 verbose addNamed "0.6.2" is a plain semver version for interpret
355 silly addNameRange number 2 { name: 'pretty-hrtime', range: '>=1.0.0 <2.0.0', hasData: true }
356 silly addNameRange versions [ 'pretty-hrtime', [ '0.2.0', '0.2.1', '0.2.2', '1.0.0' ] ]
357 silly addNamed pretty-hrtime@1.0.0
358 verbose addNamed "1.0.0" is a plain semver version for pretty-hrtime
359 silly addNameRange number 2 { name: 'gulp-util', range: '>=3.0.0 <4.0.0', hasData: true }
360 silly addNameRange versions [ 'gulp-util',
360 silly addNameRange   [ '0.0.1',
360 silly addNameRange     '1.0.0',
360 silly addNameRange     '1.1.0',
360 silly addNameRange     '1.1.1',
360 silly addNameRange     '1.2.0',
360 silly addNameRange     '1.3.0',
360 silly addNameRange     '2.0.0',
360 silly addNameRange     '2.1.1',
360 silly addNameRange     '2.1.2',
360 silly addNameRange     '2.1.3',
360 silly addNameRange     '2.1.4',
360 silly addNameRange     '2.2.0',
360 silly addNameRange     '2.2.1',
360 silly addNameRange     '2.2.2',
360 silly addNameRange     '2.2.3',
360 silly addNameRange     '2.2.5',
360 silly addNameRange     '2.2.6',
360 silly addNameRange     '2.2.7',
360 silly addNameRange     '2.2.8',
360 silly addNameRange     '2.2.9',
360 silly addNameRange     '2.2.10',
360 silly addNameRange     '2.2.11',
360 silly addNameRange     '2.2.12',
360 silly addNameRange     '2.2.13',
360 silly addNameRange     '2.2.14',
360 silly addNameRange     '2.2.15',
360 silly addNameRange     '2.2.16',
360 silly addNameRange     '2.2.17',
360 silly addNameRange     '2.2.18',
360 silly addNameRange     '2.2.19',
360 silly addNameRange     '2.2.20',
360 silly addNameRange     '3.0.0',
360 silly addNameRange     '3.0.1',
360 silly addNameRange     '3.0.2',
360 silly addNameRange     '3.0.3',
360 silly addNameRange     '3.0.4',
360 silly addNameRange     '3.0.5' ] ]
361 silly addNamed gulp-util@3.0.5
362 verbose addNamed "3.0.5" is a plain semver version for gulp-util
363 silly addNameRange number 2 { name: 'tildify', range: '>=1.0.0 <2.0.0', hasData: true }
364 silly addNameRange versions [ 'tildify', [ '0.1.0', '0.2.0', '1.0.0' ] ]
365 silly addNamed tildify@1.0.0
366 verbose addNamed "1.0.0" is a plain semver version for tildify
367 silly addNameRange number 2 { name: 'minimist', range: '>=1.1.0 <2.0.0', hasData: true }
368 silly addNameRange versions [ 'minimist',
368 silly addNameRange   [ '0.0.0',
368 silly addNameRange     '0.0.1',
368 silly addNameRange     '0.0.2',
368 silly addNameRange     '0.0.3',
368 silly addNameRange     '0.0.4',
368 silly addNameRange     '0.0.5',
368 silly addNameRange     '0.0.6',
368 silly addNameRange     '0.0.7',
368 silly addNameRange     '0.0.8',
368 silly addNameRange     '0.0.9',
368 silly addNameRange     '0.0.10',
368 silly addNameRange     '0.1.0',
368 silly addNameRange     '0.2.0',
368 silly addNameRange     '1.0.0',
368 silly addNameRange     '1.1.0',
368 silly addNameRange     '1.1.1' ] ]
369 silly addNamed minimist@1.1.1
370 verbose addNamed "1.1.1" is a plain semver version for minimist
371 silly addNameRange number 2 { name: 'chalk', range: '>=1.0.0 <2.0.0', hasData: true }
372 silly addNameRange versions [ 'chalk',
372 silly addNameRange   [ '0.1.0',
372 silly addNameRange     '0.1.1',
372 silly addNameRange     '0.2.0',
372 silly addNameRange     '0.2.1',
372 silly addNameRange     '0.3.0',
372 silly addNameRange     '0.4.0',
372 silly addNameRange     '0.5.0',
372 silly addNameRange     '0.5.1',
372 silly addNameRange     '1.0.0' ] ]
373 silly addNamed chalk@1.0.0
374 verbose addNamed "1.0.0" is a plain semver version for chalk
375 silly addNameRange number 2 { name: 'archy', range: '>=1.0.0 <2.0.0', hasData: true }
376 silly addNameRange versions [ 'archy', [ '0.0.0', '0.0.1', '0.0.2', '1.0.0' ] ]
377 silly addNamed archy@1.0.0
378 verbose addNamed "1.0.0" is a plain semver version for archy
379 silly addNameRange number 2 { name: 'orchestrator', range: '>=0.3.0 <0.4.0', hasData: true }
380 silly addNameRange versions [ 'orchestrator',
380 silly addNameRange   [ '0.0.2',
380 silly addNameRange     '0.0.3',
380 silly addNameRange     '0.0.4',
380 silly addNameRange     '0.0.5',
380 silly addNameRange     '0.0.6',
380 silly addNameRange     '0.0.7',
380 silly addNameRange     '0.0.8',
380 silly addNameRange     '0.1.0',
380 silly addNameRange     '0.2.0',
380 silly addNameRange     '0.2.1',
380 silly addNameRange     '0.3.0',
380 silly addNameRange     '0.3.1',
380 silly addNameRange     '0.3.3',
380 silly addNameRange     '0.3.4',
380 silly addNameRange     '0.3.5',
380 silly addNameRange     '0.3.6',
380 silly addNameRange     '0.3.7' ] ]
381 silly addNamed orchestrator@0.3.7
382 verbose addNamed "0.3.7" is a plain semver version for orchestrator
383 silly addNameRange number 2 { name: 'vinyl-fs', range: '>=0.3.0 <0.4.0', hasData: true }
384 silly addNameRange versions [ 'vinyl-fs', [ '0.0.1', '0.0.2', '0.1.0', '1.0.0' ] ]
385 silly addNameRange number 2 { name: 'v8flags', range: '>=2.0.2 <3.0.0', hasData: true }
386 silly addNameRange versions [ 'v8flags',
386 silly addNameRange   [ '0.1.0',
386 silly addNameRange     '0.2.0',
386 silly addNameRange     '0.3.0',
386 silly addNameRange     '1.0.0',
386 silly addNameRange     '1.0.1',
386 silly addNameRange     '1.0.2',
386 silly addNameRange     '1.0.3',
386 silly addNameRange     '1.0.4',
386 silly addNameRange     '1.0.5',
386 silly addNameRange     '1.0.6',
386 silly addNameRange     '1.0.7',
386 silly addNameRange     '1.0.8',
386 silly addNameRange     '2.0.0',
386 silly addNameRange     '2.0.2',
386 silly addNameRange     '2.0.3',
386 silly addNameRange     '2.0.4',
386 silly addNameRange     '2.0.5' ] ]
387 silly addNamed v8flags@2.0.5
388 verbose addNamed "2.0.5" is a plain semver version for v8flags
389 silly cache afterAdd liftoff@2.1.0
390 verbose afterAdd /Volumes/OSX_HD/Users/bradleybergeron/.npm/liftoff/2.1.0/package/package.json not in flight; writing
391 silly cache afterAdd deprecated@0.0.1
392 verbose afterAdd /Volumes/OSX_HD/Users/bradleybergeron/.npm/deprecated/0.0.1/package/package.json not in flight; writing
393 silly cache afterAdd interpret@0.6.2
394 verbose afterAdd /Volumes/OSX_HD/Users/bradleybergeron/.npm/interpret/0.6.2/package/package.json not in flight; writing
395 silly cache afterAdd pretty-hrtime@1.0.0
396 verbose afterAdd /Volumes/OSX_HD/Users/bradleybergeron/.npm/pretty-hrtime/1.0.0/package/package.json not in flight; writing
397 silly cache afterAdd semver@4.3.6
398 verbose afterAdd /Volumes/OSX_HD/Users/bradleybergeron/.npm/semver/4.3.6/package/package.json not in flight; writing
399 silly cache afterAdd gulp-util@3.0.5
400 verbose afterAdd /Volumes/OSX_HD/Users/bradleybergeron/.npm/gulp-util/3.0.5/package/package.json not in flight; writing
401 silly cache afterAdd tildify@1.0.0
402 verbose afterAdd /Volumes/OSX_HD/Users/bradleybergeron/.npm/tildify/1.0.0/package/package.json not in flight; writing
403 silly cache afterAdd minimist@1.1.1
404 verbose afterAdd /Volumes/OSX_HD/Users/bradleybergeron/.npm/minimist/1.1.1/package/package.json not in flight; writing
405 silly cache afterAdd chalk@1.0.0
406 verbose afterAdd /Volumes/OSX_HD/Users/bradleybergeron/.npm/chalk/1.0.0/package/package.json not in flight; writing
407 silly cache afterAdd archy@1.0.0
408 verbose afterAdd /Volumes/OSX_HD/Users/bradleybergeron/.npm/archy/1.0.0/package/package.json not in flight; writing
409 silly cache afterAdd orchestrator@0.3.7
410 verbose afterAdd /Volumes/OSX_HD/Users/bradleybergeron/.npm/orchestrator/0.3.7/package/package.json not in flight; writing
411 silly cache afterAdd v8flags@2.0.5
412 verbose afterAdd /Volumes/OSX_HD/Users/bradleybergeron/.npm/v8flags/2.0.5/package/package.json not in flight; writing
413 verbose afterAdd /Volumes/OSX_HD/Users/bradleybergeron/.npm/deprecated/0.0.1/package/package.json written
414 verbose afterAdd /Volumes/OSX_HD/Users/bradleybergeron/.npm/liftoff/2.1.0/package/package.json written
415 verbose afterAdd /Volumes/OSX_HD/Users/bradleybergeron/.npm/interpret/0.6.2/package/package.json written
416 verbose afterAdd /Volumes/OSX_HD/Users/bradleybergeron/.npm/pretty-hrtime/1.0.0/package/package.json written
417 verbose afterAdd /Volumes/OSX_HD/Users/bradleybergeron/.npm/semver/4.3.6/package/package.json written
418 verbose afterAdd /Volumes/OSX_HD/Users/bradleybergeron/.npm/tildify/1.0.0/package/package.json written
419 verbose afterAdd /Volumes/OSX_HD/Users/bradleybergeron/.npm/gulp-util/3.0.5/package/package.json written
420 verbose afterAdd /Volumes/OSX_HD/Users/bradleybergeron/.npm/minimist/1.1.1/package/package.json written
421 verbose afterAdd /Volumes/OSX_HD/Users/bradleybergeron/.npm/chalk/1.0.0/package/package.json written
422 verbose afterAdd /Volumes/OSX_HD/Users/bradleybergeron/.npm/orchestrator/0.3.7/package/package.json written
423 verbose afterAdd /Volumes/OSX_HD/Users/bradleybergeron/.npm/archy/1.0.0/package/package.json written
424 verbose afterAdd /Volumes/OSX_HD/Users/bradleybergeron/.npm/v8flags/2.0.5/package/package.json written
425 verbose about to build /Volumes/OSX_HD/Users/bradleybergeron/.npm-packages/lib/node_modules/gulp
426 verbose unlock done using /Volumes/OSX_HD/Users/bradleybergeron/.npm/_locks/gulp-d60c157284d5ebcc.lock for /Volumes/OSX_HD/Users/bradleybergeron/.npm-packages/lib/node_modules/gulp
427 verbose stack Error: No compatible version found: vinyl-fs@'>=0.3.0 <0.4.0'
427 verbose stack Valid install targets:
427 verbose stack ["0.0.1","0.0.2","0.1.0","1.0.0"]
427 verbose stack
427 verbose stack     at installTargetsError (/Volumes/OSX_HD/Users/bradleybergeron/.npm-packages/lib/node_modules/npm/lib/cache/add-named.js:274:12)
427 verbose stack     at next (/Volumes/OSX_HD/Users/bradleybergeron/.npm-packages/lib/node_modules/npm/lib/cache/add-named.js:253:17)
427 verbose stack     at setData (/Volumes/OSX_HD/Users/bradleybergeron/.npm-packages/lib/node_modules/npm/lib/cache/add-named.js:230:5)
427 verbose stack     at RES (/Volumes/OSX_HD/Users/bradleybergeron/.npm-packages/lib/node_modules/npm/node_modules/inflight/inflight.js:23:14)
427 verbose stack     at f (/Volumes/OSX_HD/Users/bradleybergeron/.npm-packages/lib/node_modules/npm/node_modules/once/once.js:17:25)
427 verbose stack     at fixName (/Volumes/OSX_HD/Users/bradleybergeron/.npm-packages/lib/node_modules/npm/lib/cache/add-named.js:29:5)
427 verbose stack     at saved (/Volumes/OSX_HD/Users/bradleybergeron/.npm-packages/lib/node_modules/npm/lib/cache/caching-client.js:173:7)
427 verbose stack     at FSReqWrap.oncomplete (fs.js:101:15)
428 verbose cwd /Volumes/OSX_HD/Users/bradleybergeron
429 error Darwin 14.3.0
430 error argv "node" "/Volumes/OSX_HD/Users/bradleybergeron/.npm-packages/bin/npm" "install" "-g" "gulp" "--verbose"
431 error node v0.13.0-pre
432 error npm  v2.11.1
433 error code ETARGET
434 error notarget No compatible version found: vinyl-fs@'>=0.3.0 <0.4.0'
434 error notarget Valid install targets:
434 error notarget ["0.0.1","0.0.2","0.1.0","1.0.0"]
434 error notarget
434 error notarget This is most likely not a problem with npm itself.
434 error notarget In most cases you or one of your dependencies are requesting
434 error notarget a package version that doesn't exist.
434 error notarget
434 error notarget It was specified as a dependency of 'gulp'
435 verbose exit [ 1, true ]
436 verbose unbuild lib/node_modules/gulp
437 info preuninstall gulp@3.9.0
438 info uninstall gulp@3.9.0
439 verbose unbuild rmStuff gulp@3.9.0 from /Volumes/OSX_HD/Users/bradleybergeron/.npm-packages/lib/node_modules
440 silly gentlyRm /Volumes/OSX_HD/Users/bradleybergeron/.npm-packages/bin/gulp is being gently removed
441 silly gentlyRm verifying /Volumes/OSX_HD/Users/bradleybergeron/.npm-packages is an npm working directory
442 verbose rmMans man files are [ 'gulp.1' ] in /Volumes/OSX_HD/Users/bradleybergeron/.npm-packages/share/man
443 silly rmMan preparing to remove gulp.1
444 silly gentlyRm /Volumes/OSX_HD/Users/bradleybergeron/.npm-packages/share/man/man1/gulp.1.1 is being gently removed
445 silly gentlyRm verifying /Volumes/OSX_HD/Users/bradleybergeron/.npm-packages is an npm working directory
446 silly gentlyRm containing path /Volumes/OSX_HD/Users/bradleybergeron/.npm-packages is under npm's control, in /Volumes/OSX_HD/Users/bradleybergeron/.npm-packages
447 silly gentlyRm deletion target /Volumes/OSX_HD/Users/bradleybergeron/.npm-packages/bin/gulp is under /Volumes/OSX_HD/Users/bradleybergeron/.npm-packages
448 verbose gentlyRm vacuuming from /Volumes/OSX_HD/Users/bradleybergeron/.npm-packages/bin/gulp up to /Volumes/OSX_HD/Users/bradleybergeron/.npm-packages
449 silly gentlyRm containing path /Volumes/OSX_HD/Users/bradleybergeron/.npm-packages is under npm's control, in /Volumes/OSX_HD/Users/bradleybergeron/.npm-packages
450 silly gentlyRm deletion target /Volumes/OSX_HD/Users/bradleybergeron/.npm-packages/share/man/man1/gulp.1.1 is under /Volumes/OSX_HD/Users/bradleybergeron/.npm-packages
451 verbose gentlyRm vacuuming from /Volumes/OSX_HD/Users/bradleybergeron/.npm-packages/share/man/man1/gulp.1.1 up to /Volumes/OSX_HD/Users/bradleybergeron/.npm-packages
452 info postuninstall gulp@3.9.0
453 silly gentlyRm /Volumes/OSX_HD/Users/bradleybergeron/.npm-packages/lib/node_modules/gulp is being purged from base /Volumes/OSX_HD/Users/bradleybergeron/.npm-packages
454 verbose gentlyRm don't care about contents; nuking /Volumes/OSX_HD/Users/bradleybergeron/.npm-packages/lib/node_modules/gulp
455 silly vacuum-fs purging /Volumes/OSX_HD/Users/bradleybergeron/.npm-packages/lib/node_modules/gulp
456 silly vacuum-fs quitting because other ent

**Comment by AbhinavMadahar** [comment]
I got the same error

**Comment by bradbergeron-us** [comment]
I wish I would have documented how I fixed this I think I have a recent gist I wrote that may have addressed this error

**Comment by PolakAllen** [comment]
Looks like it may have been the version of node

See https://github.com/strongloop/strongloop/issues/233

"this is a problem with your version of node. Anything with a -pre does not meet any engine requirements and versions of vinyl-fs before 1.0.0 had engineStrict: true."

Downgrading node to 0.12.7 fixed it for me.

**Comment by busches** [comment]
Is this still occurring with a recent version of node?
