### ISSUE TITLE
npm@2.11.1 fails to install libxmljs on OSX while npm@1.4.28 succeeds 

### ISSUE THREAD

**Issue by xaka** [npm/npm#8500]
Hi there,

I'm running on latest OSX with the following stuff:

```
$ node -v
v0.10.38
```

```
$ clang -v
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix
```

```
$ uname -a
Darwin ML-PSTRA-OSX-SF.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64
```

And whenever I'm installing `libxmljs` with `npm@2.11.1`, I'm getting the following errors:

```
  SOLINK(target) Release/xmljs.node
Undefined symbols for architecture x86_64:
  "v8::HandleScope::CreateHandle(v8::internal::HeapObject*)", referenced from:
      libxmljs::XmlSaxParser::Callback(char const*, int, v8::Local<v8::Value>*) in xml_sax_parser.o
  "v8::HandleScope::CreateHandle(v8::internal::Object*)", referenced from:
      libxmljs::XmlAttribute::New(_xmlNode*, unsigned char const*, unsigned char const*) in xml_attribute.o
      libxmljs::XmlAttribute::New(_xmlAttr*) in xml_attribute.o
      libxmljs::XmlAttribute::get_name() in xml_attribute.o
      libxmljs::XmlAttribute::get_value() in xml_attribute.o
      libxmljs::XmlAttribute::get_namespace() in xml_attribute.o
      libxmljs::XmlAttribute::Initialize(v8::Handle<v8::Object>) in xml_attribute.o
      libxmljs::XmlDocument::Root(v8::Arguments const&) in xml_document.o
...
...
...
  "v8::Function::NewInstance() const", referenced from:
      libxmljs::XmlAttribute::New(_xmlNode*, unsigned char const*, unsigned char const*) in xml_attribute.o
      libxmljs::XmlAttribute::New(_xmlAttr*) in xml_attribute.o
      libxmljs::XmlDocument::New(_xmlDoc*) in xml_document.o
      libxmljs::XmlElement::New(_xmlNode*) in xml_element.o
      libxmljs::XmlComment::New(_xmlNode*) in xml_comment.o
      libxmljs::XmlNamespace::New(_xmlNs*) in xml_namespace.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/xmljs.node] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/pavelstrashkin/.nvm/v0.10.38/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/Users/pavelstrashkin/.nvm/v0.10.38/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/pavelstrashkin/mulesoft/api-platform/node_modules/libxmljs
gyp ERR! node -v v0.10.38
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
```

While with `npm@1.4.28` everything is fine and no errors at all. I understand that the problem might be with `libxmljs` itself, not `npm`, but still seems kind of strange. 

https://github.com/polotek/libxmljs/issues/315

**Comment by smikes** [comment]
Thanks for reporting this!  This looks like a tricky one -- the errors you document look a lot like incompatibility between versions 0.10, 0.11, and 0.12 of `node`, which shouldn't be cropping up when you just change which version of `npm` you're using.

I see that you're also using `nvm` -- is it possible that there's some cross-talk between the version of `node` and `npm` that you're using?  Or maybe do you need to do a `npm rebuild` to make sure that all build artifacts are cleaned up before rebuilding?

**Comment by xaka** [comment]
It looks like it's an issue with `node-gyp`, which got upgraded in recent npm releases to next major version with backward-incompatible changes. You might want to follow https://github.com/polotek/libxmljs/issues/315#issuecomment-110212609 to get more details.

**Comment by othiym23** [comment]
Thanks, @xaka. I left a comment over there, but to bring things up to speed here: it wasn't the npm team's intention to introduce breaking changes with the upgrade to `node-gyp`, so if this turns out to be a serious headache for `libxmljs`'s maintainers, npm will revert to `node-gyp@1` until a subsequent major version of npm, probably `npm@4` (as `npm@3` is increasingly imminent).
