### ISSUE TITLE
Can't install Meteor Up on Mac OS X Yosemite 10.10.3

### ISSUE THREAD

**Issue by bradhall** [npm/npm#8502]
I tried installing Meteor Up by using npm install -g mup and got:

```
npm WARN locking Error: EACCES, open '/Users/Brad/.npm/_locks/mup-2c0f78d4aacbd233.lock'
npm WARN locking  /Users/Brad/.npm/_locks/mup-2c0f78d4aacbd233.lock failed { [Error: EACCES, open '/Users/Brad/.npm/_locks/mup-2c0f78d4aacbd233.lock']
npm WARN locking   errno: 3,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/Brad/.npm/_locks/mup-2c0f78d4aacbd233.lock' }
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "mup"
npm ERR! node v0.10.36
npm ERR! npm  v2.9.1

npm ERR! Attempt to unlock /usr/local/lib/node_modules/mup, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Brad/Sites/meteor/microscope/npm-debug.log

LOG INCLUDED:

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', '-g', 'mup' ]
2 info using npm@2.9.1
3 info using node@v0.10.36
4 verbose install initial load of /usr/local/lib/package.json
5 verbose readDependencies loading dependencies from /usr/local/lib/package.json
6 silly cache add args [ 'mup', null ]
7 verbose cache add spec mup
8 silly cache add parsed spec { raw: 'mup',
8 silly cache add   scope: null,
8 silly cache add   name: 'mup',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed mup@*
10 verbose addNamed "*" is a valid semver range for mup
11 silly addNameRange { name: 'mup', range: '*', hasData: false }
12 silly mapToRegistry name mup
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/mup
16 verbose addNameRange registry:https://registry.npmjs.org/mup not in flight; fetching
17 verbose request uri https://registry.npmjs.org/mup
18 verbose request no auth needed
19 info attempt registry request try #1 at 20:46:46
20 verbose request id 280a97a781740cd2
21 verbose etag "CGT0JNCYF3D21IF9B6A5EJMTE"
22 http request GET https://registry.npmjs.org/mup
23 http 304 https://registry.npmjs.org/mup
24 silly get cb [ 304,
24 silly get   { date: 'Tue, 09 Jun 2015 00:46:47 GMT',
24 silly get     via: '1.1 varnish',
24 silly get     'cache-control': 'max-age=60',
24 silly get     etag: '"CGT0JNCYF3D21IF9B6A5EJMTE"',
24 silly get     age: '0',
24 silly get     connection: 'keep-alive',
24 silly get     'x-served-by': 'cache-dfw1821-DFW',
24 silly get     'x-cache': 'MISS',
24 silly get     'x-cache-hits': '0',
24 silly get     'x-timer': 'S1433810807.108399,VS0,VE245',
24 silly get     vary: 'Accept' } ]
25 verbose etag https://registry.npmjs.org/mup from cache
26 verbose get saving mup to /Users/Brad/.npm/registry.npmjs.org/mup/.cache.json
27 silly addNameRange number 2 { name: 'mup', range: '*', hasData: true }
28 silly addNameRange versions [ 'mup',
28 silly addNameRange   [ '0.1.2',
28 silly addNameRange     '0.1.3',
28 silly addNameRange     '0.1.4',
28 silly addNameRange     '0.1.5',
28 silly addNameRange     '0.1.6',
28 silly addNameRange     '0.1.7',
28 silly addNameRange     '0.1.8',
28 silly addNameRange     '0.1.9',
28 silly addNameRange     '0.1.10',
28 silly addNameRange     '0.1.11',
28 silly addNameRange     '0.1.12',
28 silly addNameRange     '0.1.13',
28 silly addNameRange     '0.2.0',
28 silly addNameRange     '0.3.0',
28 silly addNameRange     '0.4.0',
28 silly addNameRange     '0.4.1',
28 silly addNameRange     '0.4.2',
28 silly addNameRange     '0.4.3',
28 silly addNameRange     '0.4.4',
28 silly addNameRange     '0.4.5',
28 silly addNameRange     '0.4.6',
28 silly addNameRange     '0.4.7',
28 silly addNameRange     '0.5.0',
28 silly addNameRange     '0.5.1',
28 silly addNameRange     '0.5.2',
28 silly addNameRange     '0.5.3',
28 silly addNameRange     '0.6.0',
28 silly addNameRange     '0.6.1',
28 silly addNameRange     '0.6.3',
28 silly addNameRange     '0.6.4',
28 silly addNameRange     '0.6.5',
28 silly addNameRange     '0.6.7',
28 silly addNameRange     '0.6.8',
28 silly addNameRange     '0.6.9',
28 silly addNameRange     '0.6.10',
28 silly addNameRange     '0.6.11',
28 silly addNameRange     '0.6.12',
28 silly addNameRange     '0.7.0',
28 silly addNameRange     '0.7.1',
28 silly addNameRange     '0.7.2',
28 silly addNameRange     '0.7.3',
28 silly addNameRange     '0.7.4',
28 silly addNameRange     '0.7.5',
28 silly addNameRange     '0.7.6',
28 silly addNameRange     '0.7.7',
28 silly addNameRange     '0.8.0',
28 silly addNameRange     '0.9.0',
28 silly addNameRange     '0.9.1',
28 silly addNameRange     '0.9.2',
28 silly addNameRange     '0.9.3',
28 silly addNameRange     '0.9.4',
28 silly addNameRange     '0.9.5',
28 silly addNameRange     '0.9.6',
28 silly addNameRange     '0.9.7',
28 silly addNameRange     '0.10.0',
28 silly addNameRange     '0.10.1',
28 silly addNameRange     '0.10.2',
28 silly addNameRange     '0.10.3',
28 silly addNameRange     '0.10.4',
28 silly addNameRange     '0.10.5',
28 silly addNameRange     '0.10.6',
28 silly addNameRange     '0.10.7' ] ]
29 silly addNamed mup@0.10.7
30 verbose addNamed "0.10.7" is a plain semver version for mup
31 silly cache afterAdd mup@0.10.7
32 verbose afterAdd /Users/Brad/.npm/mup/0.10.7/package/package.json not in flight; writing
33 verbose afterAdd /Users/Brad/.npm/mup/0.10.7/package/package.json written
34 silly install resolved [ { name: 'mup',
34 silly install resolved     version: '0.10.7',
34 silly install resolved     description: 'Production Quality Meteor Deployments',
34 silly install resolved     dependencies:
34 silly install resolved      { async: '^0.9.0',
34 silly install resolved        cjson: '0.3.x',
34 silly install resolved        colors: '0.6.x',
34 silly install resolved        nodemiral: '^1.0.1',
34 silly install resolved        rimraf: '2.x.x',
34 silly install resolved        underscore: '1.7.0',
34 silly install resolved        uuid: '1.4.x',
34 silly install resolved        archiver: '0.14.x' },
34 silly install resolved     bin: { mup: './bin/mup' },
34 silly install resolved     author:
34 silly install resolved      { name: 'Arunoda Susiripala',
34 silly install resolved        email: 'arunoda.susiripala@gmail.com' },
34 silly install resolved     repository: { type: 'git', url: 'git://github.com/arunoda/meteor-up.git' },
34 silly install resolved     license: 'MIT',
34 silly install resolved     gitHead: 'd5fa3b7ddda035e2b103601f787dfe5872fc614f',
34 silly install resolved     bugs: { url: 'https://github.com/arunoda/meteor-up/issues' },
34 silly install resolved     homepage: 'https://github.com/arunoda/meteor-up',
34 silly install resolved     _id: 'mup@0.10.7',
34 silly install resolved     scripts: {},
34 silly install resolved     _shasum: 'fea9a22b186cc685247ebc7f900435ff6ad32f7a',
34 silly install resolved     _from: 'mup@*',
34 silly install resolved     _npmVersion: '2.7.4',
34 silly install resolved     _nodeVersion: '0.12.2',
34 silly install resolved     _npmUser: { name: 'arunoda', email: 'arunoda.susiripala@gmail.com' },
34 silly install resolved     dist:
34 silly install resolved      { shasum: 'fea9a22b186cc685247ebc7f900435ff6ad32f7a',
34 silly install resolved        tarball: 'http://registry.npmjs.org/mup/-/mup-0.10.7.tgz' },
34 silly install resolved     maintainers: [ [Object] ],
34 silly install resolved     directories: {},
34 silly install resolved     _resolved: 'https://registry.npmjs.org/mup/-/mup-0.10.7.tgz',
34 silly install resolved     readme: 'ERROR: No README data found!' } ]
35 info install mup@0.10.7 into /usr/local/lib
36 info installOne mup@0.10.7
37 verbose installOne of mup to /usr/local/lib not in flight; installing
38 warn locking Error: EACCES, open '/Users/Brad/.npm/_locks/mup-2c0f78d4aacbd233.lock'
38 warn locking  /Users/Brad/.npm/_locks/mup-2c0f78d4aacbd233.lock failed { [Error: EACCES, open '/Users/Brad/.npm/_locks/mup-2c0f78d4aacbd233.lock']
38 warn locking   errno: 3,
38 warn locking   code: 'EACCES',
38 warn locking   path: '/Users/Brad/.npm/_locks/mup-2c0f78d4aacbd233.lock' }
39 verbose stack Error: Attempt to unlock /usr/local/lib/node_modules/mup, which hasn't been locked
39 verbose stack     at unlock (/usr/local/lib/node_modules/npm/lib/utils/locker.js:66:11)
39 verbose stack     at cb (/usr/local/lib/node_modules/npm/lib/install.js:1015:5)
39 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:1019:20
39 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/locker.js:40:9
39 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
39 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
39 verbose stack     at Object.oncomplete (fs.js:108:15)
40 verbose cwd /Users/Brad/Sites/meteor/microscope
41 error Darwin 14.3.0
42 error argv "node" "/usr/local/bin/npm" "install" "-g" "mup"
43 error node v0.10.36
44 error npm  v2.9.1
45 error Attempt to unlock /usr/local/lib/node_modules/mup, which hasn't been locked
46 error If you need help, you may report this error at:
46 error     <https://github.com/npm/npm/issues>
47 verbose exit [ 1, true ]
```

**Comment by smikes** [comment]
This looks like a problem where your `.npm/_locks` directory contains files that are not writable by you -- sometimes this happens because `npm install` was run as root (e.g., using `sudo`) but got interrupted before cleaning up its lock file.  Can you try this:

```
$ sudo chown -R $(whoami) ~/.npm
$ npm install -g mup
```

**Comment by bradhall** [comment]
Tried your suggestion, got this error:

npm ERR! tar.unpack untar error /Users/Brad/.npm/mup/0.10.7/package.tgz
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "mup"
npm ERR! node v0.10.36
npm ERR! npm  v2.9.1
npm ERR! path /usr/local/lib/node_modules/mup
npm ERR! code EACCES
npm ERR! errno 3

npm ERR! Error: EACCES, mkdir '/usr/local/lib/node_modules/mup'
npm ERR!  { [Error: EACCES, mkdir '/usr/local/lib/node_modules/mup']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/mup',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/mup',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53',
npm ERR!      'Object.oncomplete (fs.js:108:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Brad/Sites/meteor/microscope/npm-debug.log

LOG FILE:

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', '-g', 'mup' ]
2 info using npm@2.9.1
3 info using node@v0.10.36
4 verbose install initial load of /usr/local/lib/package.json
5 verbose readDependencies loading dependencies from /usr/local/lib/package.json
6 silly cache add args [ 'mup', null ]
7 verbose cache add spec mup
8 silly cache add parsed spec { raw: 'mup',
8 silly cache add   scope: null,
8 silly cache add   name: 'mup',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed mup@*
10 verbose addNamed "*" is a valid semver range for mup
11 silly addNameRange { name: 'mup', range: '*', hasData: false }
12 silly mapToRegistry name mup
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/mup
16 verbose addNameRange registry:https://registry.npmjs.org/mup not in flight; fetching
17 verbose request uri https://registry.npmjs.org/mup
18 verbose request no auth needed
19 info attempt registry request try #1 at 01:04:22
20 verbose request id 75b27796e017e17b
21 verbose etag "CGT0JNCYF3D21IF9B6A5EJMTE"
22 http request GET https://registry.npmjs.org/mup
23 http 304 https://registry.npmjs.org/mup
24 silly get cb [ 304,
24 silly get   { date: 'Tue, 09 Jun 2015 05:04:22 GMT',
24 silly get     via: '1.1 varnish',
24 silly get     'cache-control': 'max-age=60',
24 silly get     etag: '"CGT0JNCYF3D21IF9B6A5EJMTE"',
24 silly get     age: '0',
24 silly get     connection: 'keep-alive',
24 silly get     'x-served-by': 'cache-iad2136-IAD',
24 silly get     'x-cache': 'MISS',
24 silly get     'x-cache-hits': '0',
24 silly get     'x-timer': 'S1433826262.866563,VS0,VE54',
24 silly get     vary: 'Accept' } ]
25 verbose etag https://registry.npmjs.org/mup from cache
26 verbose get saving mup to /Users/Brad/.npm/registry.npmjs.org/mup/.cache.json
27 silly addNameRange number 2 { name: 'mup', range: '*', hasData: true }
28 silly addNameRange versions [ 'mup',
28 silly addNameRange   [ '0.1.2',
28 silly addNameRange     '0.1.3',
28 silly addNameRange     '0.1.4',
28 silly addNameRange     '0.1.5',
28 silly addNameRange     '0.1.6',
28 silly addNameRange     '0.1.7',
28 silly addNameRange     '0.1.8',
28 silly addNameRange     '0.1.9',
28 silly addNameRange     '0.1.10',
28 silly addNameRange     '0.1.11',
28 silly addNameRange     '0.1.12',
28 silly addNameRange     '0.1.13',
28 silly addNameRange     '0.2.0',
28 silly addNameRange     '0.3.0',
28 silly addNameRange     '0.4.0',
28 silly addNameRange     '0.4.1',
28 silly addNameRange     '0.4.2',
28 silly addNameRange     '0.4.3',
28 silly addNameRange     '0.4.4',
28 silly addNameRange     '0.4.5',
28 silly addNameRange     '0.4.6',
28 silly addNameRange     '0.4.7',
28 silly addNameRange     '0.5.0',
28 silly addNameRange     '0.5.1',
28 silly addNameRange     '0.5.2',
28 silly addNameRange     '0.5.3',
28 silly addNameRange     '0.6.0',
28 silly addNameRange     '0.6.1',
28 silly addNameRange     '0.6.3',
28 silly addNameRange     '0.6.4',
28 silly addNameRange     '0.6.5',
28 silly addNameRange     '0.6.7',
28 silly addNameRange     '0.6.8',
28 silly addNameRange     '0.6.9',
28 silly addNameRange     '0.6.10',
28 silly addNameRange     '0.6.11',
28 silly addNameRange     '0.6.12',
28 silly addNameRange     '0.7.0',
28 silly addNameRange     '0.7.1',
28 silly addNameRange     '0.7.2',
28 silly addNameRange     '0.7.3',
28 silly addNameRange     '0.7.4',
28 silly addNameRange     '0.7.5',
28 silly addNameRange     '0.7.6',
28 silly addNameRange     '0.7.7',
28 silly addNameRange     '0.8.0',
28 silly addNameRange     '0.9.0',
28 silly addNameRange     '0.9.1',
28 silly addNameRange     '0.9.2',
28 silly addNameRange     '0.9.3',
28 silly addNameRange     '0.9.4',
28 silly addNameRange     '0.9.5',
28 silly addNameRange     '0.9.6',
28 silly addNameRange     '0.9.7',
28 silly addNameRange     '0.10.0',
28 silly addNameRange     '0.10.1',
28 silly addNameRange     '0.10.2',
28 silly addNameRange     '0.10.3',
28 silly addNameRange     '0.10.4',
28 silly addNameRange     '0.10.5',
28 silly addNameRange     '0.10.6',
28 silly addNameRange     '0.10.7' ] ]
29 silly addNamed mup@0.10.7
30 verbose addNamed "0.10.7" is a plain semver version for mup
31 silly cache afterAdd mup@0.10.7
32 verbose afterAdd /Users/Brad/.npm/mup/0.10.7/package/package.json not in flight; writing
33 verbose afterAdd /Users/Brad/.npm/mup/0.10.7/package/package.json written
34 silly install resolved [ { name: 'mup',
34 silly install resolved     version: '0.10.7',
34 silly install resolved     description: 'Production Quality Meteor Deployments',
34 silly install resolved     dependencies:
34 silly install resolved      { async: '^0.9.0',
34 silly install resolved        cjson: '0.3.x',
34 silly install resolved        colors: '0.6.x',
34 silly install resolved        nodemiral: '^1.0.1',
34 silly install resolved        rimraf: '2.x.x',
34 silly install resolved        underscore: '1.7.0',
34 silly install resolved        uuid: '1.4.x',
34 silly install resolved        archiver: '0.14.x' },
34 silly install resolved     bin: { mup: './bin/mup' },
34 silly install resolved     author:
34 silly install resolved      { name: 'Arunoda Susiripala',
34 silly install resolved        email: 'arunoda.susiripala@gmail.com' },
34 silly install resolved     repository: { type: 'git', url: 'git://github.com/arunoda/meteor-up.git' },
34 silly install resolved     license: 'MIT',
34 silly install resolved     gitHead: 'd5fa3b7ddda035e2b103601f787dfe5872fc614f',
34 silly install resolved     bugs: { url: 'https://github.com/arunoda/meteor-up/issues' },
34 silly install resolved     homepage: 'https://github.com/arunoda/meteor-up',
34 silly install resolved     _id: 'mup@0.10.7',
34 silly install resolved     scripts: {},
34 silly install resolved     _shasum: 'fea9a22b186cc685247ebc7f900435ff6ad32f7a',
34 silly install resolved     _from: 'mup@*',
34 silly install resolved     _npmVersion: '2.7.4',
34 silly install resolved     _nodeVersion: '0.12.2',
34 silly install resolved     _npmUser: { name: 'arunoda', email: 'arunoda.susiripala@gmail.com' },
34 silly install resolved     dist:
34 silly install resolved      { shasum: 'fea9a22b186cc685247ebc7f900435ff6ad32f7a',
34 silly install resolved        tarball: 'http://registry.npmjs.org/mup/-/mup-0.10.7.tgz' },
34 silly install resolved     maintainers: [ [Object] ],
34 silly install resolved     directories: {},
34 silly install resolved     _resolved: 'https://registry.npmjs.org/mup/-/mup-0.10.7.tgz',
34 silly install resolved     readme: 'ERROR: No README data found!' } ]
35 info install mup@0.10.7 into /usr/local/lib
36 info installOne mup@0.10.7
37 verbose installOne of mup to /usr/local/lib not in flight; installing
38 verbose lock using /Users/Brad/.npm/_locks/mup-2c0f78d4aacbd233.lock for /usr/local/lib/node_modules/mup
39 silly install write writing mup 0.10.7 to /usr/local/lib/node_modules/mup
40 verbose unbuild lib/node_modules/mup
41 silly gentlyRm /usr/local/lib/node_modules/mup is being purged from base /usr/local
42 verbose gentlyRm don't care about contents; nuking /usr/local/lib/node_modules/mup
43 verbose tar unpack /Users/Brad/.npm/mup/0.10.7/package.tgz
44 verbose tar unpacking to /usr/local/lib/node_modules/mup
45 silly gentlyRm /usr/local/lib/node_modules/mup is being purged
46 verbose gentlyRm don't care about contents; nuking /usr/local/lib/node_modules/mup
47 silly gunzTarPerm modes [ '755', '644' ]
48 error tar.unpack untar error /Users/Brad/.npm/mup/0.10.7/package.tgz
49 verbose unlock done using /Users/Brad/.npm/_locks/mup-2c0f78d4aacbd233.lock for /usr/local/lib/node_modules/mup
50 verbose fstream_path /usr/local/lib/node_modules/mup
51 verbose fstream_type Directory
52 verbose fstream_class DirWriter
53 verbose stack Error: EACCES, mkdir '/usr/local/lib/node_modules/mup'
54 verbose fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23
54 verbose fstream_stack /usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53
54 verbose fstream_stack Object.oncomplete (fs.js:108:15)
55 verbose cwd /Users/Brad/Sites/meteor/microscope
56 error Darwin 14.3.0
57 error argv "node" "/usr/local/bin/npm" "install" "-g" "mup"
58 error node v0.10.36
59 error npm  v2.9.1
60 error path /usr/local/lib/node_modules/mup
61 error code EACCES
62 error errno 3
63 error Error: EACCES, mkdir '/usr/local/lib/node_modules/mup'
63 error  { [Error: EACCES, mkdir '/usr/local/lib/node_modules/mup']
63 error   errno: 3,
63 error   code: 'EACCES',
63 error   path: '/usr/local/lib/node_modules/mup',
63 error   fstream_type: 'Directory',
63 error   fstream_path: '/usr/local/lib/node_modules/mup',
63 error   fstream_class: 'DirWriter',
63 error   fstream_stack:
63 error    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23',
63 error      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53',
63 error      'Object.oncomplete (fs.js:108:15)' ] }
64 error Please try running this command again as root/Administrator.
65 verbose exit [ 3, true ]
66 verbose unbuild lib/node_modules/mup
67 silly gentlyRm /usr/local/lib/node_modules/mup is being purged from base /usr/local
68 verbose gentlyRm don't care about contents; nuking /usr/local/lib/node_modules/mup

**Comment by KenanY** [comment]
@bradhall Did you try prefixing that command with `sudo`?

**Comment by KenanY** [comment]
@bradhall Are you still seeing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
