### ISSUE TITLE
can not install appium

### ISSUE THREAD

**Issue by bingoreo** [npm/npm#8504]
When I tried to install appium by using cmd: npm install -g appium, and popup errors:

npm WARN invalid config registry="“http://registry.npmjs.vitecho.com/”"
npm WARN invalid config Must be a full url with 'http://'
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "F:\\Program Files\\nodejs\\\\node.exe" "F:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "appium"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1

npm ERR! shasum check failed for C:\Users\LENOVO\AppData\Local\Temp\npm-9708-8b1
eeaa3\registry.npmjs.org\appium\-\appium-1.4.2.tgz
npm ERR! Expected: 06b7e0e89423100fa3dfc9d1f27c21f6b240c8a5
npm ERR! Actual:   6c5419f15cdfe23cdf8e3343243b0800e2857094
npm ERR! From:     https://registry.npmjs.org/appium/-/appium-1.4.2.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\LENOVO\npm-debug.log

npm-debug.log content:

0 info it worked if it ends with ok
1 verbose cli [ 'F:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'F:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'appium' ]
2 info using npm@2.10.1
3 info using node@v0.12.4
4 warn invalid config registry="“http://registry.npmjs.vitecho.com/”"
5 warn invalid config Must be a full url with 'http://'
6 verbose install initial load of C:\Users\LENOVO\AppData\Roaming\npm\package.json
7 verbose readDependencies loading dependencies from C:\Users\LENOVO\AppData\Roaming\npm\package.json
8 silly cache add args [ 'appium', null ]
9 verbose cache add spec appium
10 silly cache add parsed spec { raw: 'appium',
10 silly cache add   scope: null,
10 silly cache add   name: 'appium',
10 silly cache add   rawSpec: '',
10 silly cache add   spec: '*',
10 silly cache add   type: 'range' }
11 silly addNamed appium@*
12 verbose addNamed "*" is a valid semver range for appium
13 silly addNameRange { name: 'appium', range: '*', hasData: false }
14 silly mapToRegistry name appium
15 silly mapToRegistry using default registry
16 silly mapToRegistry registry https://registry.npmjs.org/
17 silly mapToRegistry uri https://registry.npmjs.org/appium
18 verbose addNameRange registry:https://registry.npmjs.org/appium not in flight; fetching
19 verbose request uri https://registry.npmjs.org/appium
20 verbose request no auth needed
21 info attempt registry request try #1 at 10:39:18
22 verbose request id fe3a3953658a6a88
23 verbose etag "BMWY865RYUJ2ARBTF1UPNTHL9"
24 http request GET https://registry.npmjs.org/appium
25 http 304 https://registry.npmjs.org/appium
26 silly get cb [ 304,
26 silly get   { date: 'Tue, 09 Jun 2015 02:39:10 GMT',
26 silly get     via: '1.1 varnish',
26 silly get     'cache-control': 'max-age=60',
26 silly get     etag: '"BMWY865RYUJ2ARBTF1UPNTHL9"',
26 silly get     age: '0',
26 silly get     connection: 'keep-alive',
26 silly get     'x-served-by': 'cache-fra1231-FRA',
26 silly get     'x-cache': 'MISS',
26 silly get     'x-cache-hits': '0',
26 silly get     'x-timer': 'S1433817550.033157,VS0,VE404',
26 silly get     vary: 'Accept' } ]
27 verbose etag https://registry.npmjs.org/appium from cache
28 verbose get saving appium to C:\Users\LENOVO\AppData\Roaming\npm-cache\registry.npmjs.org\appium\.cache.json
29 silly addNameRange number 2 { name: 'appium', range: '*', hasData: true }
30 silly addNameRange versions [ 'appium',
30 silly addNameRange   [ '0.0.1',
30 silly addNameRange     '0.0.2',
30 silly addNameRange     '0.0.3',
30 silly addNameRange     '0.0.4',
30 silly addNameRange     '0.0.5',
30 silly addNameRange     '0.0.6',
30 silly addNameRange     '0.0.7',
30 silly addNameRange     '0.0.8',
30 silly addNameRange     '0.0.9',
30 silly addNameRange     '0.0.10',
30 silly addNameRange     '0.0.11',
30 silly addNameRange     '0.0.12',
30 silly addNameRange     '0.0.13',
30 silly addNameRange     '0.0.14',
30 silly addNameRange     '0.0.15',
30 silly addNameRange     '0.1.0',
30 silly addNameRange     '0.1.1',
30 silly addNameRange     '0.1.2',
30 silly addNameRange     '0.2.0',
30 silly addNameRange     '0.2.1',
30 silly addNameRange     '0.2.2',
30 silly addNameRange     '0.2.3',
30 silly addNameRange     '0.3.0',
30 silly addNameRange     '0.3.1',
30 silly addNameRange     '0.4.0',
30 silly addNameRange     '0.4.1',
30 silly addNameRange     '0.5.0',
30 silly addNameRange     '0.5.1',
30 silly addNameRange     '0.5.2',
30 silly addNameRange     '0.6.0',
30 silly addNameRange     '0.6.1',
30 silly addNameRange     '0.7.0',
30 silly addNameRange     '0.7.1',
30 silly addNameRange     '0.7.2',
30 silly addNameRange     '0.7.3',
30 silly addNameRange     '0.8.0',
30 silly addNameRange     '0.8.1',
30 silly addNameRange     '0.8.2',
30 silly addNameRange     '0.8.3',
30 silly addNameRange     '0.8.4',
30 silly addNameRange     '0.8.5',
30 silly addNameRange     '0.9.0',
30 silly addNameRange     '0.9.1',
30 silly addNameRange     '0.10.0',
30 silly addNameRange     '0.10.1',
30 silly addNameRange     '0.10.2',
30 silly addNameRange     '0.10.3',
30 silly addNameRange     '0.10.4',
30 silly addNameRange     '0.11.0',
30 silly addNameRange     '0.11.1',
30 silly addNameRange     '0.11.2',
30 silly addNameRange     '0.11.3',
30 silly addNameRange     '0.11.4',
30 silly addNameRange     '0.12.0',
30 silly addNameRange     '0.12.1-b',
30 silly addNameRange     '0.12.2',
30 silly addNameRange     '0.12.3',
30 silly addNameRange     '0.13.0',
30 silly addNameRange     '0.14.0',
30 silly addNameRange     '0.14.1',
30 silly addNameRange     '0.14.2',
30 silly addNameRange     '0.15.0',
30 silly addNameRange     '0.16.0',
30 silly addNameRange     '0.17.0',
30 silly addNameRange     '0.17.2',
30 silly addNameRange     '0.17.3',
30 silly addNameRange     '0.17.4',
30 silly addNameRange     '0.17.5',
30 silly addNameRange     '0.17.6',
30 silly addNameRange     '0.18.0',
30 silly addNameRange     '0.18.1',
30 silly addNameRange     '1.0.0-beta.1',
30 silly addNameRange     '0.18.2',
30 silly addNameRange     '1.0.0-beta.2',
30 silly addNameRange     '1.0.0',
30 silly addNameRange     '1.1.0',
30 silly addNameRange     '1.2.0',
30 silly addNameRange     '1.2.1',
30 silly addNameRange     '1.2.2',
30 silly addNameRange     '1.2.3',
30 silly addNameRange     '1.3.0-beta1',
30 silly addNameRange     '1.2.4',
30 silly addNameRange     '1.3.0',
30 silly addNameRange     '1.3.1',
30 silly addNameRange     '1.3.2-beta2',
30 silly addNameRange     '1.3.3',
30 silly addNameRange     '1.3.4-beta1',
30 silly addNameRange     '1.3.4',
30 silly addNameRange     '1.3.5-beta',
30 silly addNameRange     '1.3.5',
30 silly addNameRange     '1.3.6',
30 silly addNameRange     '1.3.7',
30 silly addNameRange     '1.4.0-beta',
30 silly addNameRange     '1.4.0',
30 silly addNameRange     '1.4.1',
30 silly addNameRange     '1.4.2' ] ]
31 silly addNamed appium@1.4.2
32 verbose addNamed "1.4.2" is a plain semver version for appium
33 silly mapToRegistry name appium
34 silly mapToRegistry using default registry
35 silly mapToRegistry registry https://registry.npmjs.org/
36 silly mapToRegistry uri https://registry.npmjs.org/appium
37 verbose addRemoteTarball https://registry.npmjs.org/appium/-/appium-1.4.2.tgz not in flight; adding
38 verbose addRemoteTarball [ 'https://registry.npmjs.org/appium/-/appium-1.4.2.tgz',
38 verbose addRemoteTarball   '06b7e0e89423100fa3dfc9d1f27c21f6b240c8a5' ]
39 info retry fetch attempt 1 at 10:39:21
40 info attempt registry request try #1 at 10:39:21
41 http fetch GET https://registry.npmjs.org/appium/-/appium-1.4.2.tgz
42 http fetch 200 https://registry.npmjs.org/appium/-/appium-1.4.2.tgz
43 silly fetchAndShaCheck shasum 06b7e0e89423100fa3dfc9d1f27c21f6b240c8a5
44 verbose stack Error: shasum check failed for C:\Users\LENOVO\AppData\Local\Temp\npm-9708-8b1eeaa3\registry.npmjs.org\appium\-\appium-1.4.2.tgz
44 verbose stack Expected: 06b7e0e89423100fa3dfc9d1f27c21f6b240c8a5
44 verbose stack Actual:   6c5419f15cdfe23cdf8e3343243b0800e2857094
44 verbose stack From:     https://registry.npmjs.org/appium/-/appium-1.4.2.tgz
44 verbose stack     at F:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:38:8
44 verbose stack     at ReadStream.<anonymous> (F:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:85:7)
44 verbose stack     at ReadStream.emit (events.js:129:20)
44 verbose stack     at _stream_readable.js:908:16
44 verbose stack     at process._tickCallback (node.js:355:11)
45 verbose cwd C:\Users\LENOVO
46 error Windows_NT 6.1.7601
47 error argv "F:\\Program Files\\nodejs\\\\node.exe" "F:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "appium"
48 error node v0.12.4
49 error npm  v2.10.1
50 error shasum check failed for C:\Users\LENOVO\AppData\Local\Temp\npm-9708-8b1eeaa3\registry.npmjs.org\appium\-\appium-1.4.2.tgz
50 error Expected: 06b7e0e89423100fa3dfc9d1f27c21f6b240c8a5
50 error Actual:   6c5419f15cdfe23cdf8e3343243b0800e2857094
50 error From:     https://registry.npmjs.org/appium/-/appium-1.4.2.tgz
51 error If you need help, you may report this error at:
51 error     <https://github.com/npm/npm/issues>
52 verbose exit [ 1, true ]

**Comment by smikes** [comment]
This looks like you may have a bad copy of `appium` in your cache, and your registry mirror also seems to be misconfigured -- note the smart quotes in `"“http://registry.npmjs.vitecho.com/”"`.  Can you try this:

```
> npm config set registry http://registry.npmjs.vitecho.com/
> npm cache clean appium
> npm install -g appium
```

**Comment by bingoreo** [comment]
Thanks for your supporting, and I have resolved it according to you advice, steps as bellow:
> npm config set registry http://registry.cnpmjs.org
> npm cache clean appium
> npm install -g appium
