### ISSUE TITLE
How to try npm@3 multi-stage ?

### ISSUE THREAD

**Issue by paulharris** [npm/npm#8505]
Hi,

Sorry if this is a stupid question, I just want to try out the flat node_modules feature...

My procedure:
Download and compile nodejs
add nodejs bin to PATH
mkdir trynpm3
cd trynpm3
git clone git@github.com:npm/npm.git
cd npm
git checkout -b multi-stage origin/multi-stage
./configure
make (this fails - can't use marked-man)
scripts/doc-build.sh: line 102: ./node_modules/.bin/marked-man: No such file or directory

make link (this does a lot of things, also fails with marked-man error)

./bin/npm
module.js:338
    throw err;
          ^
Error: Cannot find module '/home/paul/dev/20120605/nodejs/try_npm3/npm/bin/node_modules/npm/bin/npm-cli.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

?

cheers,
Paul

ps I also tried 
npm install github:npm/npm#multi-stage
which appeared to Do Things, but was not able to execute npm because of missing dependencies...
So I pursued the make link approach instead.

**Comment by aredridel** [comment]
What worked for me: clone, check out branch, `npm install`, then run `/path/to/checkout/bin/npm-cli.js`

**Comment by paulharris** [comment]
Ok thanks, the npm-cli.js bit worked,
but note that npm install step doesn't run successfully.  Did it for you?

```
> mkdir try_npm3
> cd try_npm3
try_npm3$ git clone etc etc
try_npm3$ cd npm
try_npm3$ git checkout -b multi-stage origin/multi-stage
try_npm3$ npm install

> npm@3.0.0-pre.10 prepublish /home/paul/dev/20120605/nodejs/try_npm3/npm
> node bin/npm-cli.js prune --prefix=. --no-global && rimraf test/*/*/node_modules && make -j4 doc

scripts/doc-build.sh doc/api/npm-rebuild.md man/man3/npm-rebuild.3
scripts/doc-build.sh doc/api/npm.md man/man3/npm.3
scripts/doc-build.sh doc/api/npm-init.md man/man3/npm-init.3
scripts/doc-build.sh doc/api/npm-config.md man/man3/npm-config.3
make[1]: Entering directory `/home/paul/dev/20120605/nodejs/try_npm3/npm'
make[1]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
node cli.js install marked-man --no-global
make[1]: Leaving directory `/home/paul/dev/20120605/nodejs/try_npm3/npm'
make[1]: Entering directory `/home/paul/dev/20120605/nodejs/try_npm3/npm'
make[1]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
node cli.js install marked --no-global
make[1]: Leaving directory `/home/paul/dev/20120605/nodejs/try_npm3/npm'
scripts/doc-build.sh: line 102: ./node_modules/.bin/marked-man: No such file or directory
make: *** [man/man3/npm-rebuild.3] Error 1
make: *** Waiting for unfinished jobs....
scripts/doc-build.sh: line 102: ./node_modules/.bin/marked-man: No such file or directory
scripts/doc-build.sh: line 102: ./node_modules/.bin/marked-man: No such file or directory
make: *** [man/man3/npm-config.3] Error 1
scripts/doc-build.sh: line 102: ./node_modules/.bin/marked-man: No such file or directory
make: *** [man/man3/npm-init.3] Error 1
make: *** [man/man3/npm.3] Error 1
npm WARN install:npm Couldn't install optional dependency: npm@3.0.0-pre.10 prepublish: `node bin/npm-cli.js prune --prefix=. --no-global && rimraf test/*/*/node_modules && make -j4 doc`
npm WARN install:npm Exit status 2
```

**Comment by iarna** [comment]
Ok, you all, here's how I do it:

```
npm install -g npm/npm#multi-stage
```

To switch back to 2.x:

```
npm install -g npm@latest
```

If you want to install from a checkout, I'd do this:

```
code$ git clone https://github.com/npm/npm.git
code$ cd npm
npm$ git checkout multi-stage
npm$ node . install
```

That'll get you all of the dev deps installed. Then to install npm@3 globally:

```
npm$ node . install -g .
````

To switch back, as with the other method:

```
npm$ npm install -g npm@latest
```

**Comment by paulharris** [comment]
I followed my procedure again, and this time it made it all the way through the procedure (it previously failed building man pages) but with a few warnings/errors:

```
$ cd try_npm3/npm
$ git checkout -b multi-stage2 origin/multi-stage
$ npm install
npm WARN prefer global marked@0.3.3 should be installed with -g
npm WARN engine follow@0.11.4: wanted: {"node":"0.10.x || 0.8.x"} (current: {"node":"0.12.4","npm":"2.11.1"})
...
npm WARN unmet dependency /home/paul/dev/20120605/nodejs/try_npm3/npm/node_modules/bl requires readable-stream@'~1.0.26' but will load
npm WARN unmet dependency /home/paul/dev/20120605/nodejs/try_npm3/npm/node_modules/readable-stream,
npm WARN unmet dependency which is version 1.1.13
npm WARN unmet dependency /home/paul/dev/20120605/nodejs/try_npm3/npm/node_modules/form-data requires combined-stream@'~0.0.4' but will load
npm WARN unmet dependency /home/paul/dev/20120605/nodejs/try_npm3/npm/node_modules/combined-stream,
npm WARN unmet dependency which is version 1.0.3
```

I am thinking that the bundled node_modules in npm are not updated.
I guess installing npm locally is not commonly tested - I see you just use npm install -g to switch between.  But doesn't that make it harder to switch between branches quickly?

anyway, thanks!

**Comment by paulharris** [comment]
Please put that in a hacking-npm FAQ, I don't remember seeing that written so clearly !
