### ISSUE TITLE
Working with an existing Grunt project - npm install error

### ISSUE THREAD

**Issue by rfoost** [npm/npm#8508]
Hey guys I cant seem to get this project to work at all. I recieved it from another developer and "npm install" throws an error every time. I've had no luck with google. Any suggestions would be greatly appreciated.

https://github.com/rfoost/error/blob/master/npm-debug.log

**Comment by watilde** [comment]
Hi Ryan. I did git clone [your repository](https://github.com/rfoost/error) and tried to `npm install`, then a simular error with you has displayed like the following:
```
npm ERR! ENOTDIR: not a directory, lstat '/path/to/error/node_modules/grunt-contrib-watch'
```

After that I saw the file list in the project root directory and found the file called [node_modules](https://github.com/rfoost/error/blob/master/node_modules). npm required the **directory** named `node_modules` for putting modules installed, so it can fix by removing this file if you need not this file.

Thanks.

**Comment by rfoost** [comment]
Hi watilde!
I removed the node_modules file. I believe it was probably file that got converted from pc to osx. I removed it and ran "npm install" again. I defintiely made progress but ran into more errors. Here is what I've found

> node-sass@0.8.6 install /Users/joecosta/error/node_modules/grunt-sass/node_modules/node-sass
> node build.js

child_process: customFds option is deprecated, use stdio instead.
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

Once again you can see the full error log here:
https://github.com/rfoost/error/blob/master/npm-debug.log

**Comment by watilde** [comment]
Thanks for your trying again. I think so too:-)
> The thing is i believe i have and installed xcode correctly.

Also maybe you need to update the version of `grunt-sass` in your [package.json](https://github.com/rfoost/error/blob/master/package.json#L32) to [latest version](https://github.com/sindresorhus/grunt-sass/blob/master/package.json#L3), related Issue and comment are here:
+ https://github.com/sass/node-sass/issues/301
+ https://github.com/sass/node-sass/issues/301#issuecomment-42294545

**Comment by rfoost** [comment]
Thanks for all the help watilde! I was able to get the project running with: 

sudo npm install --save-dev grunt-sass

I am relieved to get the project file operation but I am confused about what exactly i've done. If you or anyone else could shed some light on it I would appreciate it for future understanding.

**Comment by iarna** [comment]
Closing as resolved.
