### ISSUE TITLE
Unable to sudo npm install http-auth

### ISSUE THREAD

**Issue by nsuprin** [npm/npm#8509]
```
npm ERR! Error: UNKNOWN, symlink '../ncp/bin/ncp'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.2.0-4-amd64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "http-auth"
npm ERR! cwd /home/www/edf/node/node
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! path ../ncp/bin/ncp
npm ERR! code UNKNOWN
npm ERR! errno -1
npm ERR! not ok code 0
```

**Comment by smikes** [comment]
Thanks for reporting this!

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4. Can you try updating your npm installation?

To update npm, run `sudo npm -g install npm@latest`.

For some Linux distributions (Debian/Ubuntu and RedHat/CentOS), the latest node version provided by the distribution may lag behind the stable version. [Here are instructions from NodeSource](https://github.com/nodesource/distributions) on getting the latest node.

Thanks!

**Comment by nsuprin** [comment]
Thx for your support !

This is the result of the command line : (I successfuly do what I was
wanting to do an another server)


npm ERR! notarget No compatible version found: npm@'latest.'
npm ERR! notarget Valid install targets:
npm ERR! notarget
["1.1.25","1.2.32","1.3.2","1.3.4","1.2.20","1.2.21","1.2.22","1.2.23","1.2.24","1.2.25","1.2.27","1.2.28","1.2.30","1.2.31","1.3.0","1.3.1","1.2.19","1.1.70","1.1.71","1.3.5","1.3.6","1.3.7","1.3.8","1.3.9","1.3.10","1.3.11","1.3.12","1.3.13","1.3.14","1.3.15","1.3.16","1.3.17","1.3.18","1.3.20","1.3.21","1.3.22","1.3.23","1.3.24","1.3.25","1.3.26","1.4.0","1.4.1","1.4.2","1.4.3","1.4.4","1.4.5","1.4.6","1.4.7","1.4.8","1.4.9","1.4.10","1.4.11","1.4.12","1.4.13","1.4.14","1.4.15","1.4.16","1.2.8000","1.4.17","1.4.18","1.4.19","1.5.0-alpha-0","1.5.0-alpha-1","1.4.20","1.5.0-alpha-2","1.4.21","1.5.0-alpha-3","1.5.0-alpha-4","2.0.0-alpha-5","1.4.22","1.4.23","2.0.0-alpha.6.0","1.4.24","2.0.0-alpha.6","2.0.0-alpha.7","2.0.0-beta.0","1.4.25","2.0.0-beta.1","1.4.26","2.0.0-beta.2","1.4.27","2.0.0-beta.3","1.4.28","2.0.0","2.0.1","2.0.2","2.1.0","2.1.1","2.1.2","2.1.3","2.1.4","2.1.5","2.1.6","2.1.7","2.1.8","2.1.9","2.1.10","2.1.11","2.1.12","2.1.13","2.1.14","2.1.15","2.1.16","2.1.17","2.1.18","2.2.0","2.3.0","2.4.0","2.4.1","2.5.0","2.5.1","2.6.0","2.6.1","2.7.0","2.7.1","2.7.2","2.7.3","2.7.4","2.7.5","2.7.6","2.8.0","2.8.1","2.8.2","2.8.3","2.8.4","2.9.0","2.9.1","2.10.0","2.10.1","2.11.0","2.11.1","2.11.2"]
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are
requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! System Linux 3.2.0-4-amd64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "-g" "install"
"npm@latest."
npm ERR! cwd /home/www/edf/node/node
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ETARGET
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/www/edf/node/node/npm-debug.log
npm ERR! not ok code 0


2015-06-10 13:52 GMT+02:00 Sam Mikes <notifications@github.com>:

> Thanks for reporting this!
>
> There have been a lot of improvements to npm -- especially around
> conflicts and race conditions during install -- since 1.4. Can you try
> updating your npm installation?
>
> To update npm, run sudo npm -g install npm@latest.
>
> For some Linux distributions (Debian/Ubuntu and RedHat/CentOS), the latest
> node version provided by the distribution may lag behind the stable
> version. Here are instructions from NodeSource
> <https://github.com/nodesource/distributions> on getting the latest node.
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/npm/npm/issues/8509#issuecomment-110716175>.
>



-- 
Cordialement,
Nicolas SUPRIN

**Comment by smikes** [comment]
Sorry, my mistake. The command should be




$ sudo npm install -g npm@latest

**Comment by nsuprin** [comment]
@nudev02-06:~/node$ sudo npm install http-auth
npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "node" "/usr/local/bin/npm" "install" "http-auth"
npm ERR! node v0.10.33
npm ERR! npm  v2.11.1
npm ERR! path ../ncp/bin/ncp
npm ERR! code UNKNOWN
npm ERR! errno -1

npm ERR! UNKNOWN, symlink '../ncp/bin/ncp'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/www/edf/node/node/npm-debug.log


2015-06-10 14:23 GMT+02:00 Sam Mikes <notifications@github.com>:

> Sorry, my mistake. The command should be
>
>
>
>
> $ sudo npm install -g npm@latest
>
>
> On Wed, Jun 10, 2015 at 6:02 AM, nsuprin <notifications@github.com> wrote:
>
> > Thx for your support !
> > This is the result of the command line : (I successfuly do what I was
> > wanting to do an another server)
> > npm ERR! notarget No compatible version found: npm@'latest.'
> > npm ERR! notarget Valid install targets:
> > npm ERR! notarget
> >
> ["1.1.25","1.2.32","1.3.2","1.3.4","1.2.20","1.2.21","1.2.22","1.2.23","1.2.24","1.2.25","1.2.27","1.2.28","1.2.30","1.2.31","1.3.0","1.3.1","1.2.19","1.1.70","1.1.71","1.3.5","1.3.6","1.3.7","1.3.8","1.3.9","1.3.10","1.3.11","1.3.12","1.3.13","1.3.14","1.3.15","1.3.16","1.3.17","1.3.18","1.3.20","1.3.21","1.3.22","1.3.23","1.3.24","1.3.25","1.3.26","1.4.0","1.4.1","1.4.2","1.4.3","1.4.4","1.4.5","1.4.6","1.4.7","1.4.8","1.4.9","1.4.10","1.4.11","1.4.12","1.4.13","1.4.14","1.4.15","1.4.16","1.2.8000","1.4.17","1.4.18","1.4.19","1.5.0-alpha-0","1.5.0-alpha-1","1.4.20","1.5.0-alpha-2","1.4.21","1.5.0-alpha-3","1.5.0-alpha-4","2.0.0-alpha-5","1.4.22","1.4.23","2.0.0-alpha.6.0","1.4.24","2.0.0-alpha.6","2.0.0-alpha.7","2.0.0-beta.0","1.4.25","2.0.0-beta.1","1.4.26","2.0.0-beta.2","1.4.27","2.0.0-beta.3","1.4.28","2.0.0","2.0.1","2.0.2","2.1.0","2.1.1","2.1.2","2.1.3","2.1.4","2.1.5","2.1.6","2.1.7","2.1.8","2.1.9","2.1.10","2.1.11","2.1.12","2.1.13","2.1.14","2.1.15","2.1.16","2.1.17","2.1.18","2.2.0","2.3.0","2.4.0","2.4.1","2.5.0","2.5.1","2.6.0","2.6.1","2.7.0","2.7.1","2.7.2","2.7.3","2.7.4","2.7.5","2.7.6","2.8.0","2.8.1","2.8.2","2.8.3","2.8.4","2.9.0","2.9.1","2.10.0","2.10.1","2.11.0","2.11.1","2.11.2"]
> > npm ERR! notarget
> > npm ERR! notarget This is most likely not a problem with npm itself.
> > npm ERR! notarget In most cases you or one of your dependencies are
> > requesting
> > npm ERR! notarget a package version that doesn't exist.
> > npm ERR! System Linux 3.2.0-4-amd64
> > npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "-g"
> "install"
> > "npm@latest."
> > npm ERR! cwd /home/www/edf/node/node
> > npm ERR! node -v v0.10.33
> > npm ERR! npm -v 1.4.28
> > npm ERR! code ETARGET
> > npm ERR!
> > npm ERR! Additional logging details can be found in:
> > npm ERR! /home/www/edf/node/node/npm-debug.log
> > npm ERR! not ok code 0
> > 2015-06-10 13:52 GMT+02:00 Sam Mikes <notifications@github.com>:
> >> Thanks for reporting this!
> >>
> >> There have been a lot of improvements to npm -- especially around
> >> conflicts and race conditions during install -- since 1.4. Can you try
> >> updating your npm installation?
> >>
> >> To update npm, run sudo npm -g install npm@latest.
> >>
> >> For some Linux distributions (Debian/Ubuntu and RedHat/CentOS), the
> latest
> >> node version provided by the distribution may lag behind the stable
> >> version. Here are instructions from NodeSource
> >> <https://github.com/nodesource/distributions> on getting the latest
> node.
> >>
> >> Thanks!
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <https://github.com/npm/npm/issues/8509#issuecomment-110716175>.
> >>
> > --
> > Cordialement,
> > Nicolas SUPRIN
> > ---
> > Reply to this email directly or view it on GitHub:
> > https://github.com/npm/npm/issues/8509#issuecomment-110719392
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/npm/npm/issues/8509#issuecomment-110728716>.
>



-- 
Cordialement,
Nicolas SUPRIN

**Comment by smikes** [comment]
It looks like http-auth may have an undeclared dependency on "ncp". Can you check the docs to see if you are supposed to install ncp (wherever that is) first ?

**Comment by KenanY** [comment]
@nsuprin ping?

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
