### ISSUE TITLE
`main` should be included in published package even when omitted from `files`

### ISSUE THREAD

**Issue by jasonkarns** [npm/npm#8510]
It makes little sense to require that `main` be duplicated between `main` _and_ `files` in `package.json`. Shouldn't `main` always be included, even when omitted from the `files` array?

**Comment by smikes** [comment]
Thanks for suggesting this.

Just to clarify, it sounds like you're saying that the file named by `main` should always be included in the files that are packed into the package tarball, even if it's not mentioned in the `files` array.

**Comment by jasonkarns** [comment]
Yeah, that's what I'm thinking. I haven't been able to think of any scenarios where that *wouldn't* be desired.

And there is prior art. npm includes the LICENSE and README files even when they are not mentioned in the `files` array. And between the `main` file and LICENSE/README, I think `main` has a much stronger case for always being included (it being the file that is the actual purpose of the module, that is).

**Comment by rlidwka** [comment]
> And there is prior art. npm includes the LICENSE and README files even when they are not mentioned in the files array.

Maybe that's something that ought to be fixed. I mean if `files` don't contain `LICENSE`, maybe the author didn't want to include it in the first place.

**Comment by sindresorhus** [comment]
Same would be useful for the `bin` field. There's no reason you wouldn't want the file(s) defined there.

**Comment by zkat** [comment]
Hey! This is something super-relevant to the little [Filed and Ignores project](https://github.com/npm/npm/milestones/Files%20and%20Ignores) I've taken on, where I'm going through all the inclusion/exclusion logic for files with a fine-tooth comb. I'll make sure to do this as part of that work. :)

**Comment by jasonkarns** [comment]
I *think* the same should hold true for an implicit `main`. If `main` is omitted, but `index.js` exists, I would think it should be included, too.

So what we're really saying here is that the *resolved* value of `main` (either explicit, or implicit-via-index.js) should be included regardless of its inclusion in `files` array.

It sounds like the more general rule is that `files` should be *additive* to the other files-like properties.

So `main`, `bin` and `man` are always included, in addition to `files`.

Questions:

- should `LICENSE`'s and `README`'s inclusion be revisited? they don't have corresponding package.json properties, but excluding them would break a lot of things
- how should `directories` be handled?
    - `directories.bin` plays the same role as `bin`, so I think it should definitely be included
    - `directories.man` is described as 'sugar' for building up the array for `man`, so I would expect this one to be added, too
    - `directories.lib` ?
    - `directories.doc` ?
    - `directories.example` ?

**Comment by borela** [comment]
I think this issue was solved and can be closed because on NPM4 I tend to have a `build` directory that I ignore in the `.gitignore` but set it in the `main` field of the `package.json` and it is including the directory as expected.

**Comment by jasonkarns** [comment]
I am going to close this, as the current behavior of npm 4 does indeed meet expectations.

However, there is a slight quirk. The `main` field _defaults_ to `index.js` when `main` is not provided. But in such a case, `index.js` is not included in the package. I _suppose_ this could be argued for as intentional. The "default" value of `main` is really more of a feature of node's `require` resolution mechanism than it is a feature of npm has a package manager. And I would _almost_ consider it a boundary violation if npm included `index.js` in the package automatically, even when not listed as `main`. (And then have to deal with the scenario where `index.js` exists, but `main` also exists, but points to something else.)

So I'll consider this closed.
