### ISSUE TITLE
error installing sc5-styleguide

### ISSUE THREAD

**Issue by bienvu** [npm/npm#8511]
i install styleguide sc5 are being error.
Please help!

```
npm ERR! Linux 3.16.0-30-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "sc5-styleguide"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1

npm ERR! shasum check failed for /tmp/npm-30040-d7d802fd/registry.npmjs.org/sc5-styleguide/-/sc5-styleguide-0.3.20.tgz
npm ERR! Expected: e6346e1fa6258f5066c3a777b5164c4c0f75601f
npm ERR! Actual:   d5a7b6c687a17a5807ecb07872b53343c12e95f5
npm ERR! From:     https://registry.npmjs.org/sc5-styleguide/-/sc5-styleguide-0.3.20.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bb/npm-debug.log
bb@bb:~$ npm install -g sc5-styleguide
npm ERR! Linux 3.16.0-30-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "sc5-styleguide"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1

npm ERR! shasum check failed for /tmp/npm-31435-8c96a1c5/registry.npmjs.org/sc5-styleguide/-/sc5-styleguide-0.3.20.tgz
npm ERR! Expected: e6346e1fa6258f5066c3a777b5164c4c0f75601f
npm ERR! Actual:   f7b3e98858645acacb46eb32646f10031a62736b
npm ERR! From:     https://registry.npmjs.org/sc5-styleguide/-/sc5-styleguide-0.3.20.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bb/npm-debug.log
```

**Comment by smikes** [comment]
Thanks for reporting this!

This looks like `npm` has put corrupt copies of this module in its cache.  Can you try this:

```
$ npm cache clean sc5-styleguide 
$ npm install -g sc5-styleguide
```

**Comment by bienvu** [comment]
i run npm install -g sc5-styleguide it ok
but error when: npm run demo or sudo npm run demo


npm ERR! Linux 3.16.0-30-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "demo"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! path /home/bb/package.json
npm ERR! code ENOENT
npm ERR! errno -2

npm ERR! enoent ENOENT, open '/home/bb/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bb/npm-debug.log

**Comment by smikes** [comment]
It looks like you are following some sort of tutorial or instructions. Make sure you are in the correct directory when you invoke "npm run" -- npm will look for a package.json file in that directory to figure out what "demo" means.

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
