### ISSUE TITLE
Another cordova installation error

### ISSUE THREAD

**Issue by eantaru** [npm/npm#8513]
I try `sudo npm install -g cordova`
I got this
```
npm ERR! Darwin 12.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "cordova"
npm ERR! node v0.12.4
npm ERR! npm  v2.11.1

npm ERR! shasum check failed for /tmp/npm-3618-1042274d/registry.npmjs.org/cordova-app-hello-world/-/cordova-app-hello-world-3.9.0.tgz
npm ERR! Expected: 5866d8fed5582686c68ec59a6d1097c4ec0fcc4b
npm ERR! Actual:   77d0c2365efecec3117e4da467bda0adf21c1df9
npm ERR! From:     https://registry.npmjs.org/cordova-app-hello-world/-/cordova-app-hello-world-3.9.0.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rey***/Development/Ionic/npm-debug.log
```

Its been 2days to figure it out from googling and searching on github, please some advice to resolve this problem, I using mac os 10.8.5.

English is not my native, I'm so sorry if I use bad word, thank you :)

**Comment by smikes** [comment]
It looks like a corrupted copy of `cordova-app-hello-world` got saved in your npm cache.

Try this command:

```
$ npm cache clean cordova-app-hello-world
$ npm install -g cordova
```

**Comment by eantaru** [comment]
hallo, thanks smikes, installation cordova succeeded, but I got different issue, error installing ionic, here is I have done
I type npm install -g ionic, and then in several time processing I got result like below

npm ERR! tar.unpack untar error /tmp/npm-1086-feae8253/registry.npmjs.org/winston/-/winston-0.6.2.tgz
npm ERR! tar.unpack untar error /tmp/npm-1086-feae8253/registry.npmjs.org/liftoff/-/liftoff-0.12.1.tgz
npm ERR! tar.unpack untar error /tmp/npm-1086-feae8253/registry.npmjs.org/glob/-/glob-4.0.6.tgz
npm ERR! tar.unpack untar error /tmp/npm-1086-feae8253/registry.npmjs.org/request/-/request-2.47.0.tgz
npm ERR! Darwin 12.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "ionic"
npm ERR! node v0.12.4
npm ERR! npm  v2.11.1

npm ERR! unexpected eof
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rey***/Development/Ionic/npm-debug.log

I still googling to resolve my problem, but still need some advice to help me out :grin:

**Comment by EgbeEugene** [comment]
hey everyone i got the following 

npm ERR! Error: EACCES, mkdir '/usr/local/lib/node_modules/cordova'
npm ERR!  { [Error: EACCES, mkdir '/usr/local/lib/node_modules/cordova']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/cordova',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/cordova',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/lib/nodejs/fstream/lib/dir-writer.js:36:23',
npm ERR!      '/usr/lib/nodejs/mkdirp/index.js:46:53',
npm ERR!      'Object.oncomplete (fs.js:107:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 3.19.0-15-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "cordova"
npm ERR! cwd /home/eug3ne
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! path /usr/local/lib/node_modules/cordova
npm ERR! fstream_path /usr/local/lib/node_modules/cordova
npm ERR! fstream_type Directory
npm ERR! fstream_class DirWriter
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, mkdir '/usr/local/lib/node_modules/cordova'
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/dir-writer.js:36:23
npm ERR! fstream_stack /usr/lib/nodejs/mkdirp/index.js:46:53
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/eug3ne/npm-debug.log
npm ERR! not ok code 0
 
how do i go about it ?

**Comment by bankim** [comment]
i am also getting same problem. the problem is not able to install ionic. coredova was installed but still getting the bellow error. please anybody can help me out.

npm ERR! tar.unpack untar error /tmp/npm-776-1c23f39a/registry.npmjs.org/winston/-/winston-1.1.2.tgz
npm ERR! tar.unpack untar error /tmp/npm-776-1c23f39a/registry.npmjs.org/lodash/-/lodash-3.10.1.tgz
npm ERR! tar.unpack untar error /tmp/npm-776-1c23f39a/registry.npmjs.org/lodash/-/lodash-2.4.2.tgz
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "cordova" "ionic"
npm ERR! node v4.2.2
npm ERR! npm  v3.5.0

npm ERR! unexpected eof
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Documents/npm-debug.log
Bankims-MacBook-Pro:Documents bankimdebnath$
