### ISSUE TITLE
Installing new conflicting deps doesn't rebalance the tree

### ISSUE THREAD

**Issue by iarna** [npm/npm#8514]
As reported by @paulharris:

> Hi, I've been playing with multi-stage.
>
> This use-case fails using new npm, and is ok on old npm.
> I am using the "superheroes" package (on github, i saw it in someone's twitter randomly).
> It installs meow@3.1 as a dependency.
>
> So I thought, what if I'm developing something that requires both superheroes and an older meow ?
>
> npm install sindresorhus/superheroes
> npm install meow@2.1
>
> npm ls
> (for old npm -- all ok)
> (for new npm -- unmet dependencies as superheroes's meow is stomped by the old meow)
>
> is this a "do not fix" issue, or something real that developers are going to suffer with?
>
> cheers,
> Paul

And went on to add:

> Note that if you install the old meow first and THEN superheroes, then it works,
> as npm installs the newer meow as a nested mod.
>
> Installation ordering pain...

**Comment by iarna** [comment]
No, this is definitely a regression, in fact up till pretty recently it worked in the multi-stage branch. I actually know exactly what patch broke this so it'll be an easy fix. Thanks for pointing it out!

**Comment by paulharris** [comment]
Same issue using multi-stage if you reorder this:

FAIL
npm install tunnckoCore/gitlogin
npm install meow@2.1.0
AND the output after the 2nd install LIES, it states at the end
```
  │ │ ├── read-all-stream@2.1.2 
  │ │ ├── statuses@1.2.1 
  │ │ └── timed-out@2.0.0 
  │ └── meow@3.1.0 
  └── meow@3.1.0 
```

and immediately after, npm ls
```
│ │ │ ├── statuses@1.2.1
│ │ │ └── timed-out@2.0.0
│ │ └── meow@3.1.0
│ └── meow@3.1.0
└─┬ meow@2.1.0
  ├─┬ camelcase-keys@1.0.0
  │ ├── camelcase@1.1.0
```


THIS is OK
npm install meow@2.1.0
npm install tunnckoCore/gitlogin

**Comment by iarna** [comment]
I appreciate your diligence but I think we've got enough diagnostics now. 😄 I'll let ya know when this is fixed.

**Comment by iarna** [comment]
@paulharris This was fixed w/ https://github.com/npm/npm/commit/df7cc787b4338d53578af09137dff882d7530cc0

**Comment by paulharris** [comment]
Seems to work, interesting how the existing meow package (3.1.0) gets redeployed deeper into the n_m tree when I ask to install meow@2.1

**Comment by paulharris** [comment]
Just a thought...
I think I read somewhere that people "like to go into node_modules folder and quickly hack the submodules code".

What happens when the existing packages get moved around like this?

Did the existing meow@3.1.0 module get deleted and then downloaded and redeployed into their 2 new separate homes?

I'm wondering if some people are going to lose their little quick hacks unexpectedly.
Is this sort of hacking behaviour discouraged?  I haven't seen anything mentioned in any FAQ.
