### ISSUE TITLE
npm update - registry cannot be reached

### ISSUE THREAD

**Issue by charlierudolph** [npm/npm#8521]
This is assuming the default loglevel of warn.

When running "npm install" if the registry cannot be reached, it errors.
When running "npm update" if the registry cannot be reached, it succeeds and outputs nothing.
I believe that needs to at least issues warnings messages if not error.

**Comment by othiym23** [comment]
You're right that `npm outdated` / `npm update` should work similarly to `npm install` here. It may be a while before the team has time to get to this, though, so if you (or some other kind soul) wants to contribute a patch fixing this, that would be very helpful!

**Comment by ryantemple** [comment]
I've had a stab at this in #8566 - should fix the error for both outdated and update

**Comment by othiym23** [comment]
Fixed as per @ryantemple in 765fd4bfca8ea3e2a4a399765b17eec40a3d893d. Thanks for filing this!

**Comment by charlierudolph** [comment]
I believe that only fixes the issue for when the module is not found and not for when the registry cannot be reached.

Also since the fix does not include a test, it could easily get reverted by another developer.

**Comment by ryantemple** [comment]
When there is no internet connection or alternatively with an "unreachable/invalid registry set in .npmrc ECONNREFUSED errors are produced on the command line.  This appears to be consistent with the behaviour of npm install.
