### ISSUE TITLE
npm#multi-stage devDependencies won't install

### ISSUE THREAD

**Issue by bengl** [npm/npm#8525]
This morning I tried the latest of npm#multi-stage (at 16bb95e8ac2c6d1b750744fdb3bd66fd475d5c28), and found that most things involving devDependencies no longer work.

In particular, the following have issues:

* `npm i --save-dev foo`
    * Installs `foo` into `node_modules`, but doesn't write to `package.json` (also note: `--save` works correctly)
* `npm i` in a package dir whose `package.json` has `devDependencies`.
    * Installs the `dependencies` if present, but does not install `devDependencies`.
* `npm i foo` where `foo` is already in `devDependencies`.
    * Does nothing. Doesn't matter if you do `foo@<version>` on the CLI either.

I did a `git bisect` to figure out where this was introduced. The first commit where these are broken is 9e4cdf250e0b16aa44116589abb1b8ba52ea6d7c. Looks to me like there might be something up with how the "top level" is determined for devDeps?

I can provide simple examples with `npm-debug.log` if you'd like.

**Comment by iarna** [comment]
Hi there, thanks, this is fixed in the latest multi-stage branch.
