### ISSUE TITLE
`npm view <package-with-one-version> versions` output incorrect

### ISSUE THREAD

**Issue by davidchambers** [npm/npm#8527]
The behaviour is inconsistent for packages with one version:

```console
$ npm view <package-with-multiple-versions> versions

[ '1.0.0',
  '1.0.1' ]

$ npm view <package-with-one-version> versions
1.0.0
```

The expected output is:

```console
$ npm view <package-with-one-version> versions

[ '1.0.0' ]
```

**Comment by davidchambers** [comment]
The `--json` option has the same problem.

Here's a workaround:

```bash
for version in $(npm view "$name" versions | sed "s:[^0-9.]::g") ; do
  # ...
done
```

**Comment by KenanY** [comment]
@davidchambers Duplicate of https://github.com/npm/npm/issues/7757. This has been "fixed" on the `multi-stage` branch and will be coming in `npm@3` (since it _is_ kind of a breaking change).

**Comment by othiym23** [comment]
@iarna, can you confirm that this is fixed (and that it's fixed on purpose) in `multi-stage`?

**Comment by KenanY** [comment]
@othiym23 I hope so https://github.com/npm/npm/pull/7770#issuecomment-93762889 :see_no_evil:

**Comment by othiym23** [comment]
Me too! :speak_no_evil:

**Comment by iarna** [comment]
Yup, it does indeed look good!

**Comment by iarna** [comment]
Closing this as resolved in the `multi-stage` branch.
