### ISSUE TITLE
No way to auto-detect if installation was corrupted

### ISSUE THREAD

**Issue by donaldpipowitch** [npm/npm#8532]
Correct me if I'm wrong, but is there a way to auto-detect if an installation was corrupted? I want to auto-update my dependencies with a Git Hook.

Example: I want to install `module-a` and call `$ npm i modula-a`. `module-a` has as postinstall script which takes a while. If I abort the installation process with `Ctrl C`, I have a local `module-a` directory which isn't setup correctly. For now my Git Hook always called `$ npm i` on `postmerge`. But this doesn't work here, because `module-a` is already installed in the correct version - just without a finished postinstall script. But I don't want to remove my whole `node_modules/` directory and re-install everything  especially if some dependencies have long postinstall scripts. I only want to call them if it is really necessary.

**Comment by othiym23** [comment]
There’s a three-part answer to this:

1. In general, there’s no way for npm to know if the results of a package script are good or bad. That definition of “corrupt” is out of the scope for the CLI, so you’d have to write another package script (or do something similar) to tell you if `module-a` is in a good state after running.
2. Running `npm ls` will tell you if npm believes the tree is complete and correct, which can be used to verify the bits of the install that npm knows about and is responsible for.
3. If the install process is interrupted (in `npm@3`), there is code to roll back the install. 

This seems like about the best a package manager can do here without a lot more tooling to support external build processes. As such, I’m going to say the CLI addresses this about as well as it can, and close this issue.
