### ISSUE TITLE
problems during install of onvif

### ISSUE THREAD

**Issue by hartmutrohe** [npm/npm#8535]
Content of npm-debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'lint;',
1 verbose cli   'npm',
1 verbose cli   'run',
1 verbose cli   'jscs' ]
2 info using npm@2.10.1
3 info using node@v0.12.4
4 verbose stack Error: missing script: lint;
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:142:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:58:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:345:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:309:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:343:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:113:5)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:178:20
4 verbose stack     at evalmachine.<anonymous>:263:20
4 verbose stack     at OpenReq.Req.done (C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:141:5)
4 verbose stack     at OpenReq.done (C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:61:22)
5 verbose cwd E:\Recherche\Kameras\ONVIF\onvif
6 error Windows_NT 6.1.7601
7 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "lint;" "npm" "run" "jscs"
8 error node v0.12.4
9 error npm  v2.10.1
10 error missing script: lint;
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@hartmutrohe Do you have a `lint` script defined in your `package.json`?

**Comment by hartmutrohe** [comment]
How must I define this lint script?

The package.json contains:
  "scripts": {
    "jsdoc": "jsdoc ./lib/*.js --readme ./README.md --destination ./docs",
    "gh-pages": "jsdoc ./lib/*.js --readme ./README.md --destination ./",
    "jscs": "jscs lib/*.js",
    "lint": "jshint lib/*.js",
    "pretest": "npm run lint; npm run jscs",
    "test": "istanbul cover ./node_modules/.bin/_mocha",
    "test-on-travis": "istanbul cover ./node_modules/.bin/_mocha --report lcovonly",
    "test-coveralls": "istanbul cover ./node_modules/.bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls && rm -rf ./coverage",
    "upload-to-coveralls": "cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"
  },

**Comment by KenanY** [comment]
@hartmutrohe Oh, that looks correct. On second thought, it seems as though the script name is being interpreted with the semicolon you have after the command:

```
4 verbose stack Error: missing script: lint;
```

I don't know, does Windows support running multiple commands with a semicolon like bash?

**Comment by hartmutrohe** [comment]
I have modified package.json:

    "pretest": "npm run lint; npm run jscs",
to
    "pretest": "npm run lint",

in the scripts section.
It seems, there is a problem with semicolon.

The log output is now:

E:\Recherche\Kameras\ONVIF\onvif>npm test

> onvif@0.3.0 pretest E:\Recherche\Kameras\ONVIF\onvif
> npm run lint

> onvif@0.3.0 lint E:\Recherche\Kameras\ONVIF\onvif
> jshint lib/*.js

ERROR: Can't open lib/*.js

> onvif@0.3.0 test E:\Recherche\Kameras\ONVIF\onvif
> istanbul cover ./node_modules/.bin/_mocha

Der Befehl "istanbul" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
npm ERR! Test failed.  See above for more details.

**Comment by KenanY** [comment]
@hartmutrohe 

```
ERROR: Can't open lib/*.js
```

Yeah, I don't think Windows supports wildcards like this :/

**Comment by othiym23** [comment]
So, a couple things:

1. `cmd.exe` _doesn't_ support `;`, but both `cmd.exe` and `bash` support `command1 && command2`, so try that.
2. `cmd.exe`, unlike `bash`, doesn't perform glob expansion for you, so you'll need to somehow expand that list of files before running the command – if you want this to work on Windows, you may want to write a wrapper script that calls your linter after using `glob` to expand any wildcards. [`shelljs`](http://npm.im/shelljs) might be useful when writing that script.

I'm sorry this is proving to be such a pain – `npm run-script` is pretty powerful, but it's also pretty simple, and doesn't try to abstract over the differences between Windows and Unix, and in this case that's biting you a bit. This is all working as designed (hence why I'm going to close this issue), but making things work well between platforms is definitely a big thingy.
