### ISSUE TITLE
npm ERR! registry error parsing json

### ISSUE THREAD

**Issue by mtrisha** [npm/npm#8536]
I have installed the nodejs and npm.
I have set the proxy http-proxy and path to npm also.
but when i run command npm -g install grunt-cli karma bower 

we get the below error.

```
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "U:\\Tools\\nodejs\\\\node.exe" "U:\\Tools\\nodejs\\node_modules\\npm\\bin\\npm-cli.js
" "-g" "install" "grunt-cli" "karma" "bower"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1

npm ERR! Unexpected token A
npm ERR! Authentication Required
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

Any help is appreciated:

**Comment by exgile** [comment]
Try
 Invalid JSON
 npm ERR! registry error parsing json
 
Possible temporary npm registry glitch, or corrupted local server cache. Run [npm cache clean] and/or try again later.

**Comment by johnrc** [comment]
Based on 

> npm ERR! Authentication Required

it looks like your proxy requires authentication. Did you include your username and password when setting the proxy? So something like

    npm config set proxy http://username:password@proxy.example.com:8080
    npm config set https-proxy http://username:password@proxy.example.com:8080

**Comment by mtrisha** [comment]
Thanks for reply.
Yes i had set the proxy with user credentials.
we were using a wrong proxy host which was causing the error.
I was referring the proxy which is set in IE->connections->LAN settings only.

After changing to right proxy host it works fine. 


I would like to know how can we find the right proxy server that should be used?

**Comment by johnrc** [comment]
The only way is to ask you network admins or possibly check the Internet settings for your browser (IE, Chrome, Firefox).

**Comment by jezkie** [comment]
Same error here. But after changing the pproxy config, I'm getting HTTP 400 http://registry.npmjs.org/grunt-file and a registry error parsing json.

**Comment by loretoparisi** [comment]
@johnrc  I have a private repo and getting the same error. My `package.json` is like

```json
{
  "name": "@myscope/myrepo",
  "description": "some package",
  "version": "3.0.0",
  "homepage": "https://github.com/...",
  "author": {
    "name": "Loreto Parisi",
    "email": "loreto"
  },
  "repository": {
    "type": "git",
    "url": "git@github.com:.../....git"
  },
  "bugs": {
    "url": "https://github.com/.../.../issues"
  },
  "licenses": [
    {
      "type": "MIT",
      "url": "https://github.com/.../.../blob/master/LICENSE.md"
    }
  ],
  "main": "lib/index",
  "engines": {
    "node": "*"
  },
  "scripts": {
    "test": "grunt test"
  },
  "devDependencies": {},
  "keywords": [],
  "dependencies": {
    "@myscope/otherprivaterepo": ">=0.1.2",
    "async": "0.1.15",
    "aws-sdk": "^2.6.9",
    "mysql": "github:mysqljs/mysql"
    "redis": "^2.6.2",
    "request": "^2.75.0"
  }
}
```

When doing `npm update/install` on the other side I get

```
└── @myscope/mypackage@3.0.0  invalid
```

but the install works anyways.

Thanks for your help!

**Comment by jozip** [comment]
@loretoparisi Check for missing commas

**Comment by Charlotteis** [comment]
You need a comma at the end of

`"mysql": "github:mysqljs/mysql"`

**Comment by Elainelele** [comment]
I have met this problem before. Because I set the proxy lead to this error. So delete the proxy config is ok.
you can check the config. 
`npm config list`
