### ISSUE TITLE
Problem usr/local/bin/npm: 2: exec: /usr/local/bin/iojs: not found

### ISSUE THREAD

**Issue by Rub21** [npm/npm#8539]
someone could you help me 
```
$ npm -v
/usr/local/bin/npm: 2: exec: /usr/local/bin/iojs: not found
```

**Comment by KenanY** [comment]
@Rub21 Hmm, does `/usr/local/bin/iojs` exist? Can you run `iojs` at all?

**Comment by KenanY** [comment]
@Rub21 Are you still seeing this issue?

**Comment by b3rew** [comment]
this is how i fixed my error (but not iojs)
` /usr/local/bin/npm: 2: exec: /usr/local/bin/node: not found ` error

then run
`sudo ln -s `which nodejs` /usr/local/bin/node`

**Comment by KenanY** [comment]
Closing as abandoned. If you are still having this issue @Rub21, feel free to let me know and I can reopen this issue.
