### ISSUE TITLE
Unable to install "nmp install prompt"

### ISSUE THREAD

**Issue by RobRademeyer** [npm/npm#8540]
Hi
Can you please point me in the correct direction to resolve this problem...

Here is a screenshot of the end of the process:
![image](https://cloud.githubusercontent.com/assets/9085420/8112968/824a2eca-106b-11e5-827f-618af540befe.png)

I can post the the npm-debug.log file if required.

Thanks
R

**Comment by johnrc** [comment]
As explained in #7967, you need to update npm.

> The version of npm that you're using is very old and doesn't support version ranges specified using `^`. If you update your npm either by updating your node or by installing the latest npm with with `npm install -g npm` then you should be able to proceed.

**Comment by Ningegowda** [comment]
i got error like this,, please help me to solve that issue.. I have used windows vista with java 1.7 and nodejs..
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run-script',
1 verbose cli   'myPackage',
1 verbose cli   'generate' ]
2 info using npm@1.1.61
3 info using node@v0.8.9
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose read json C:\Users\abc\AppData\Roaming\npm\node_modules\myPackage\package.json
6 error Error: ENOENT, open 'C:\Users\abc\AppData\Roaming\npm\node_modules\myPackage\package.json'
7 error If you need help, you may report this log at:
7 error     <http://github.com/isaacs/npm/issues>
7 error or email it to:
7 error     <npm-@googlegroups.com>
8 error System Windows_NT 6.0.6001
9 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run-script" "myPackage" "generate"
10 error cwd C:\Users\abc\AppData\Roaming\npm\node_modules
11 error node -v v0.8.9
12 error npm -v 1.1.61
13 error path C:\Users\abc\AppData\Roaming\npm\node_modules\myPackage\package.json
14 error code ENOENT
15 error errno 34
16 verbose exit [ 34, true ]

Thanks..

**Comment by KenanY** [comment]
@Ningegowda Please try using [the latest stable release of `npm`](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm).

**Comment by KenanY** [comment]
@RobRademeyer Are you still seeing this issue after updating to `npm@2` or `npm@3`?

**Comment by KenanY** [comment]
Closing as abandoned.
