### ISSUE TITLE
There should be a doc somewhere that explains common cause for `npm WARN unmet dependency` and introduce preferred resolution

### ISSUE THREAD

**Issue by bitinn** [npm/npm#8541]
Quite often when we depend on a popular low-level module, say `mime-types`, bumping its version and `npm install` can result in lots of `npm WARN unmet dependency`, especially when the bump involves minor or major version changes.

```
$ npm install
...
npm WARN unmet dependency /Users/teambegin/git/mai/node_modules/koa/node_modules/accepts requires mime-types@'~2.0.11' but will load
npm WARN unmet dependency /Users/teambegin/git/mai/node_modules/mime-types,
npm WARN unmet dependency which is version 2.1.1
...
``` 

- I know clear up the whole `node_modules` folder and `npm install` usually works.
- I know manually `npm uninstall` affected packages and reinstall usually works.

But are there better ways to resolve such a common issue? If so, why isn't there a doc or readme or wiki page that SEO  `npm WARN unmet dependency` so that ppl don't have to browse through hundreds of issues and stackoverflow questions?

And avoid opening issues like this one :)

**Comment by johnrc** [comment]
Can you run `npm update` instead?

**Comment by bitinn** [comment]
Running `npm update` or `npm update koa` doesn't remove the warning.

**Comment by iarna** [comment]
Incidentally, `npm install` with npm@3 will fix these sorts of problems (and as a rule, never causes them anyway).

**Comment by iarna** [comment]
We would welcome a patch to the documentation in the `2.x` branch that does what you say. Unfortunately, this isn't on the roadmap for the core team for the next year. As such, I'm going to close this and we've flagged it as patch-welcome.
