### ISSUE TITLE
npm install take long time and forever

### ISSUE THREAD

**Issue by rkmax** [npm/npm#8545]
![captura de pantalla de 2015-06-11 21-14-43](https://cloud.githubusercontent.com/assets/395707/8122406/f96667f4-107e-11e5-8f94-b41e54e780ac.png)

![captura de pantalla de 2015-06-11 21-15-37](https://cloud.githubusercontent.com/assets/395707/8122410/07749866-107f-11e5-86ad-6589bc14d374.png)

My internet connection is working fine even I try downloading the urls using curl a works fine

I'm using npm 2.11.1 and node 0.12.4

**Comment by osirisguitar** [comment]
Are you sure all required ports are open? In a one location with only 22, 80 and 443 open, npm (and even more so bower) behaves very erratically for me, taking a lot of time and completing only intermittently. Might be related to some of our projects having references to github/gitlab tarballs for our private modules - do you have any of those?

**Comment by rkmax** [comment]
No private modules in my deps
