### ISSUE TITLE
npm install - - shasum check failed error

### ISSUE THREAD

**Issue by mtrisha** [npm/npm#8547]
Hello,

when we run the command npm install or npm -g install grunt-cli karma bower, the below error comes.
the versions installed are  node v0.12.4 ,  npm  v2.10.1

```
npm WARN package.json pulse-web-ui@0.0.1 No description
npm WARN package.json pulse-web-ui@0.0.1 No repository field.
npm WARN package.json pulse-web-ui@0.0.1 No README data
npm WARN package.json pulse-web-ui@0.0.1 No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "U:\\Tools\\nodejs\\\\node.exe" "U:\\Tools\\nodejs\\node_modules\\npm\\bin\\npm-cli.js
" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1

npm ERR! shasum check failed for C:\Users\user\AppData\Local\Temp\npm-4956-96b453a3\registry
.npmjs.org\karma-firefox-launcher\-\karma-firefox-launcher-0.1.6.tgz
npm ERR! Expected: e5e8336c35e9f2c87dcadd06c8ec568d06530b55
npm ERR! Actual:   e225d5d9b34a199208802f5ff84b2fa2f36f671d
npm ERR! From:     http://registry.npmjs.org/karma-firefox-launcher/-/karma-firefox-launcher-0.1.6.t
gz
```

we have karma-firefox-launcher-0.1.3 in the package.json file but it has downloaded 0.1.6 version under
..\AppData\Local\Temp\npm-4956-96b453a3\registry.npmjs.org\karma-firefox-launcher

can anyone help why this issue is coming.
looking forward for help.

**Comment by KenanY** [comment]
@mtrisha Usually, running `npm cache clean` is enough to fix shasum issues.

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.

**Comment by mtrisha** [comment]
You may remove this issue.
