### ISSUE TITLE
Fix broken installation when calling npm install repeatedly

### ISSUE THREAD

**Issue by DJCordhose** [npm/npm#8560]
Just bumped into Isaac at nodeconf and was requesting this: 

When you install using `npm install` and it fails for whatever reason and you call `npm install` later it might think everything is just fine leaving you with a permanently broken version of `node_modules`. The only solution known to me is to manually delete this folder and repeat the installation.

Could there be a mechanism to detect there was a failure during the installation and recover from that on the next call to `npm install`? Like writing to some sort of log which packages have been installed successfully. If this does not match the list of expected modules on calling `npm` you can react to it.

**Comment by othiym23** [comment]
This should be addressed by `npm@3`, coming very soon to a registry near you.

**Comment by iarna** [comment]
Yup! npm@3 does its best to rollback failed installs for you, so that future installs can do the right thing.

**Comment by iarna** [comment]
As this is resolved by the `multi-stage` branch and its release has *never been more imminent*, I'm going to close this ticket.

**Comment by DJCordhose** [comment]
:+1:
