### ISSUE TITLE
very unsuccessful at installing socket.io

### ISSUE THREAD

**Issue by fredito** [npm/npm#8563]
Hi everyone,
I need help installing socket.io on Centos 6. I have been amazingly unsuccessful at it.
`# npm install socket.io --save`

The error message is always 
`npm ERR! fetch failed https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz
n`

I tried it with a nodejs installed through yum, directly downloaded from https://nodejs.org/download/ or compiled from source, but the error message is always the same.

I don’t have proxy. I can curl down a6b6f2.tar.gz from github.com. I notice though that what I get through curl is 
`# cat a6b6f2.tar.gz`
`<html><body>You are being <a href="https://codeload.github.com/rase-/node-XMLHttpRequest/tar.gz/a6b6f296e0a8278165c2d0270d9840b54d5eeadd">redirected</a>.</body></html>`
Not the actual tar file but a redirect. Don’t know whether npm handles that.

Anyways, I downloaded the XMLHttpRequest tarball and ran:
`# npm install node-XMLHttpRequest-a6b6f296e0a8278165c2d0270d9840b54d5eeadd.tar.gz –-save`
`npm WARN package.json testnode@1.0.0 No description`
`npm WARN package.json testnode@1.0.0 No repository field.`
`npm WARN package.json testnode@1.0.0 No README data`
`xmlhttprequest@1.5.0 node_modules/xmlhttprequest`
`# npm install socket.io --save`
`npm WARN package.json testnode@1.0.0 No description`
`npm WARN package.json testnode@1.0.0 No repository field.`
`npm WARN package.json testnode@1.0.0 No README data`
`
`> ws@0.5.0 install /opt/testnode/node_modules/socket.io/node_modules/engine.io/node_modules/ws`
`> (node-gyp rebuild 2> builderror.log) || (exit 0)`
`
`npm ERR! fetch failed https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz`
`npm WARN retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN`

But the error is still the same.
I saw a problem with an old tar version. I updated it to latest from source (1.28) but still not working.

So at this point I can’t think of anything else to try. Does anyone have some suggestion?

**Comment by jskrzypek** [comment]
`xmlhttprequest` is a dependency of `engine.io-client` which lives in `socket.io/node_modules/socket.io-client/node_modules/engine.io-client/`. Navigate into that folder and try installing from the tarball again.
