### ISSUE TITLE
npm looking for HOME folder in project root

### ISSUE THREAD

**Issue by AlastairTaft** [npm/npm#8567]
For one project only (other projects work fine) I can't install any private packages. I don't have a .npmrc file in my project root either.

![npm error](https://cloud.githubusercontent.com/assets/3320742/8151005/95a7ade6-1343-11e5-90fd-5b3ce8dbf0b6.PNG)

I don't know why it's looking in my project root for my user folder.

**Comment by AlastairTaft** [comment]
Tracked it down to I think when... My pbx-core package had a git dependency as `"closure-library": "AlastairTaft/closure-library" and my pbx-ui package also had the same dependency but my pbx-ui package also depends on pbx-core.

**Comment by othiym23** [comment]
Can we close this now? Are you all good? Or is this a bug with `npm link`?

**Comment by AlastairTaft** [comment]
Seemed like a bug in npm to me, I had to convert my github dependency into a private package to get around it.

**Comment by AlastairTaft** [comment]
Unfortunately I now can't repo this. I'll close the issue.
