### ISSUE TITLE
Npm doesn't work

### ISSUE THREAD

**Issue by benjaminths** [npm/npm#8568]
Hey, can you help me ?

Don't know why, npm doesn't work.

Thanks

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.10.1
3 info using node@v0.12.4
4 verbose stack Error: Cannot find module './git-host-info.js'
4 verbose stack     at Function.Module._resolveFilename (module.js:336:15)
4 verbose stack     at Function.Module._load (module.js:278:25)
4 verbose stack     at Module.require (module.js:365:17)
4 verbose stack     at require (module.js:384:17)
4 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/hosted-git-info/index.js:3:16)
4 verbose stack     at Module._compile (module.js:460:26)
4 verbose stack     at Object.Module._extensions..js (module.js:478:10)
4 verbose stack     at Module.load (module.js:355:32)
4 verbose stack     at Function.Module._load (module.js:310:12)
4 verbose stack     at Module.require (module.js:365:17)
4 verbose stack     at require (module.js:384:17)
5 verbose cwd /etc/node/test
6 error Linux 2.6.32-042stab106.4
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
8 error node v0.12.4
9 error npm  v2.10.1
10 error code MODULE_NOT_FOUND
11 error Cannot find module './git-host-info.js'
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]
```

**Comment by vikashvverma** [comment]
Same problem here :

Error: Cannot find module './git-host-info.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/hosted-git-info/index.js:3:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
npm ERR! Linux 3.13.0-54-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.36
npm ERR! npm  v2.11.1
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module './git-host-info.js'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
