### ISSUE TITLE
bash variable format on windows

### ISSUE THREAD

**Issue by idoros** [npm/npm#8574]
When running npm script (`npm run *` / `npm test`), npm variables (`npm_config_*`) and env variables are provided to the process. If you write the code directly in project.json then you have no direct way of configuring the variable format (bash / cmd):

```
mocha --reporter $npm_config_reporter ./dist/test
mocha --reporter %npm_config_reporter% ./dist/test
```

Because of missing/minimal documentation on the subject, it seems that the `$npm_config_*` variable is supported by npm itself and that it will work on both platforms... but its not. It would have been nice to have some unified variable substitution format, or that npm will automatically translate bash variables to cmd variables (at list the basic usage).

I'm not sure if this should be automatically managed or left for the developer to configure, but I couldn't find any information in the npm documentation or issues and I hope the message will help anyone who encounter this issue.

**Comment by LeonFedotov** [comment]
:+1:

**Comment by kwonoj** [comment]
:+1: I'm also encountered this issue and would like to have way to access variable on different platform with unified way.

**Comment by AviVahl** [comment]
:+1:
