### ISSUE TITLE
npm ERR! registry error parsing json

### ISSUE THREAD

**Issue by oyearunpal** [npm/npm#8577]
I am using windows 8 32bit.
Please help me to solve this problem.

```
PS C:\Windows\system32> npm install -g gulp bower
npm ERR! registry error parsing json
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "I:\\node.js\\\\node.exe" "I:\\node.js\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "gulp" "bower"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1

npm ERR! Unexpected end of input
npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\system32\npm-debug.log
```

https://gist.github.com/oyearunpal/8cbfd50017c37b8e7869

**Comment by thephilip** [comment]
The `Unexpected end of input` message appears to be because of bad JSON installing bower (see: line 176 of your npm-debug.log).  In fact, it ends with `...,"maintainers":[{`.  It looks like you're running npm as Administrator.  Am I correct?
