### ISSUE TITLE
$ npm test

### ISSUE THREAD

**Issue by laleeth** [npm/npm#8579]
```
$ npm test
this is most likely not a problem with npm itself
and is related to npm not being able to find a file
```

**Comment by KenanY** [comment]
@laleeth Could you upload the _full_ `npm-debug.log` as a [gist](https://gist.github.com/)?

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
