### ISSUE TITLE
Unable to update,install.

### ISSUE THREAD

**Issue by Gosaviraje** [npm/npm#8582]
```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\my_username\npm-debug.log
```

**Comment by KenanY** [comment]
```
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
```

@Gosaviraje Are you behind a proxy or firewall by any chance?

**Comment by ncorison** [comment]
Thought it was just me ... I'm seeing the same ...

**Comment by ncorison** [comment]
Company firewall.

**Comment by ncorison** [comment]
I shut my machine down (off) and restarted it - it now seems to be working.

**Comment by Gosaviraje** [comment]
I have done the same several times.  Still not working.

**Comment by johnrc** [comment]
Does it only happen when installing `ionic`? It has tons of dependencies so maybe your proxy reset the connection.

**Comment by Gosaviraje** [comment]
It happens for everything. gulp, cordova , etc. Same error every time.

**Comment by osklil** [comment]
Same here. Windows Server 2012 R2.

**Comment by Ristaaf** [comment]
Same here Windows Server 2012 (not r2)

**Comment by Ristaaf** [comment]
Some more info:
To reproduce:
1. Install Windows Server 2012 on a virtual machine (have not had the chance to try on a dedicated server yet, but I have tried both via a VMWare cluster, and via Hyper-V on my client machine)
2. Install Git For Windows
3. Install Node.js
4. npm install -g gulp
Simple as that, this is a really serious error!

So for a workaround that works for me:
npm config set registry http://registry.npmjs.org

After that it all works fine. What it does is that it used http instead of https to download the packages.

**Comment by fultonm** [comment]
Having the problem as Ristaaf on Windows Server 2016 in a Hyper-V virtual machine.
using npm config set registry http://registry.npmjs.org solved the problem.
