### ISSUE TITLE
Failure: npm install -g ios-sim

### ISSUE THREAD

**Issue by msmith17** [npm/npm#8583]
I'm walking through the Ionic tutorial at 
https://www.youtube.com/watch?v=C-UwOWB9Io4&feature=youtu.be

When I do 
    > ionic emulate ios
it fails and tells me I need to do
    > npm install -g ios-sim

which fails with 'Error parsing json.'

I attempted to provide the log file, per
    ----------------------------------------------------------------------------
    npm ERR! If you need help, you may report this error at:
    npm ERR! <https://github.com/npm/npm/issues>
   npm ERR! Please include the following file with any support request:
    npm ERR! /Users/mksmith/Documents/Mike/ProjectsPrograms/Ionic/myApp/npm-debug.log
    --------------------------------------------------------------------------

It looks like it is getting xml where it is expecting json, but I'm not fluent enough with any of this to be confident.

Since this tool does not seem to support attaching text files, I have just just pasted it in below.

Any help or suggestions appreciated.

--------------------------------------------------------------------------
    0 info it worked if it ends with ok
    1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', '-g', 'ios-sim' ]
    2 info using npm@2.10.1
    3 info using node@v0.12.4
    4 verbose install initial load of /usr/local/lib/package.json
    5 verbose readDependencies loading dependencies from /usr/local/lib/package.json
    6 silly cache add args [ 'ios-sim', null ]
    7 verbose cache add spec ios-sim
    8 silly cache add parsed spec { raw: 'ios-sim',
    8 silly cache add   scope: null,
    8 silly cache add   name: 'ios-sim',
    8 silly cache add   rawSpec: '',
    8 silly cache add   spec: '*',
    8 silly cache add   type: 'range' }
    9 silly addNamed ios-sim@*
    10 verbose addNamed "*" is a valid semver range for ios-sim
    11 silly addNameRange { name: 'ios-sim', range: '*', hasData: false }
    12 silly mapToRegistry name ios-sim
    13 silly mapToRegistry using default registry
    14 silly mapToRegistry registry https://registry.npmjs.org/
    15 silly mapToRegistry uri https://registry.npmjs.org/ios-sim
    16 verbose addNameRange registry:https://registry.npmjs.org/ios-sim not in flight; fetching
    17 verbose request uri https://registry.npmjs.org/ios-sim
    18 verbose request no auth needed
    19 info attempt registry request try #1 at 12:36:50 PM
    20 verbose request id ac517574f9c00502
    21 http request GET https://registry.npmjs.org/ios-sim
    22 http 503 https://registry.npmjs.org/ios-sim
    23 verbose bad json <?xml version="1.0" encoding="utf-8"?>
    23 verbose bad json <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    23 verbose bad json  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
    23 verbose bad json <html>
    23 verbose bad json   <head>
    23 verbose bad json     <title>503 No healthy backends</title>
    23 verbose bad json   </head>
    23 verbose bad json   <body>
    23 verbose bad json     <h1>Error 503 No healthy backends</h1>
    23 verbose bad json     <p>No healthy backends</p>
    23 verbose bad json     <h3>Guru Mediation:</h3>
    23 verbose bad json     <p>Details: cache-ord1725-ORD 1434476211 873043612</p>
    23 verbose bad json     <hr>
    23 verbose bad json     <p>Varnish cache server</p>
    23 verbose bad json   </body>
    23 verbose bad json </html>
    24 error registry error parsing json
    25 info retry will retry, error on last attempt: SyntaxError: Unexpected token <
    25 info retry
    25 info retry <?xml version="1.0" encoding="utf-8"?>
    25 info retry <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    25 info retry  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
    25 info retry <html>
    25 info retry   <head>
    25 info retry     <title>503 No healthy backends</title>
    25 info retry   </head>
    25 info retry   <body>
    25 info retry     <h1>Error 503 No healthy backends</h1>
    25 info retry     <p>No healthy backends</p>
    25 info retry     <h3>Guru Mediation:</h3>
    25 info retry     <p>Details: cache-ord1725-ORD 1434476211 873043612</p>
    25 info retry     <hr>
    25 info retry     <p>Varnish cache server</p>
    25 info retry   </body>
    25 info retry </html>
    26 info attempt registry request try #2 at 12:37:01 PM
    27 http request GET https://registry.npmjs.org/ios-sim
    28 http 503 https://registry.npmjs.org/ios-sim
    29 verbose bad json <?xml version="1.0" encoding="utf-8"?>
    29 verbose bad json <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    29 verbose bad json  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
    29 verbose bad json <html>
    29 verbose bad json   <head>
    29 verbose bad json     <title>503 No healthy backends</title>
    29 verbose bad json   </head>
    29 verbose bad json   <body>
    29 verbose bad json     <h1>Error 503 No healthy backends</h1>
    29 verbose bad json     <p>No healthy backends</p>
    29 verbose bad json     <h3>Guru Mediation:</h3>
    29 verbose bad json     <p>Details: cache-ord1725-ORD 1434476221 873130132</p>
    29 verbose bad json     <hr>
    29 verbose bad json     <p>Varnish cache server</p>
    29 verbose bad json   </body>
    29 verbose bad json </html>
    30 error registry error parsing json
    31 info retry will retry, error on last attempt: SyntaxError: Unexpected token <
    31 info retry
    31 info retry <?xml version="1.0" encoding="utf-8"?>
    31 info retry <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    31 info retry  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
    31 info retry <html>
    31 info retry   <head>
    31 info retry     <title>503 No healthy backends</title>
    31 info retry   </head>
    31 info retry   <body>
    31 info retry     <h1>Error 503 No healthy backends</h1>
    31 info retry     <p>No healthy backends</p>
    31 info retry     <h3>Guru Mediation:</h3>
    31 info retry     <p>Details: cache-ord1725-ORD 1434476221 873130132</p>
    31 info retry     <hr>
    31 info retry     <p>Varnish cache server</p>
    31 info retry   </body>
    31 info retry </html>
    32 info attempt registry request try #3 at 12:38:01 PM
    33 http request GET https://registry.npmjs.org/ios-sim
    34 http 503 https://registry.npmjs.org/ios-sim
    35 verbose bad json <?xml version="1.0" encoding="utf-8"?>
    35 verbose bad json <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    35 verbose bad json  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
    35 verbose bad json <html>
    35 verbose bad json   <head>
    35 verbose bad json     <title>503 No healthy backends</title>
    35 verbose bad json   </head>
    35 verbose bad json   <body>
    35 verbose bad json     <h1>Error 503 No healthy backends</h1>
    35 verbose bad json     <p>No healthy backends</p>
    35 verbose bad json     <h3>Guru Mediation:</h3>
    35 verbose bad json     <p>Details: cache-ord1725-ORD 1434476281 873637133</p>
    35 verbose bad json     <hr>
    35 verbose bad json     <p>Varnish cache server</p>
    35 verbose bad json   </body>
    35 verbose bad json </html>
    36 error registry error parsing json
    37 verbose headers { server: 'Varnish',
    37 verbose headers   'retry-after': '0',
    37 verbose headers   'content-type': 'text/html; charset=utf-8',
    37 verbose headers   'content-length': '450',
    37 verbose headers   'accept-ranges': 'bytes',
    37 verbose headers   date: 'Tue, 16 Jun 2015 17:38:01 GMT',
    37 verbose headers   via: '1.1 varnish',
    37 verbose headers   connection: 'keep-alive',
    37 verbose headers   'x-served-by': 'cache-ord1726-ORD',
    37 verbose headers   'x-cache': 'MISS',
    37 verbose headers   'x-cache-hits': '0',
    37 verbose headers   'x-timer': 'S1434476281.511019,VS0,VE0' }
    38 silly get cb [ 503,
    38 silly get   { server: 'Varnish',
    38 silly get     'retry-after': '0',
    38 silly get     'content-type': 'text/html; charset=utf-8',
    38 silly get     'content-length': '450',
    38 silly get     'accept-ranges': 'bytes',
    38 silly get     date: 'Tue, 16 Jun 2015 17:38:01 GMT',
    38 silly get     via: '1.1 varnish',
    38 silly get     connection: 'keep-alive',
    38 silly get     'x-served-by': 'cache-ord1726-ORD',
    38 silly get     'x-cache': 'MISS',
    38 silly get     'x-cache-hits': '0',
    38 silly get     'x-timer': 'S1434476281.511019,VS0,VE0' } ]
    39 verbose stack SyntaxError: Unexpected token <
    39 verbose stack
    39 verbose stack <?xml version="1.0" encoding="utf-8"?>
    39 verbose stack <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    39 verbose stack  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
    39 verbose stack <html>
    39 verbose stack   <head>
    39 verbose stack     <title>503 No healthy backends</title>
    39 verbose stack   </head>
    39 verbose stack   <body>
    39 verbose stack     <h1>Error 503 No healthy backends</h1>
    39 verbose stack     <p>No healthy backends</p>
    39 verbose stack     <h3>Guru Mediation:</h3>
    39 verbose stack     <p>Details: cache-ord1725-ORD 1434476281 873637133</p>
    39 verbose stack     <hr>
    39 verbose stack     <p>Varnish cache server</p>
    39 verbose stack   </body>
    39 verbose stack </html>
    39 verbose stack
    39 verbose stack     at Object.parse (native)
    39 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:197:23)
    39 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:170:14)
    39 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:368:22)
    39 verbose stack     at Request.emit (events.js:110:17)
    39 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1219:14)
    39 verbose stack     at Request.emit (events.js:129:20)
    39 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1167:12)
    39 verbose stack     at IncomingMessage.emit (events.js:129:20)
    39 verbose stack     at _stream_readable.js:908:16
    40 verbose cwd /Users/mksmith/Documents/Mike/ProjectsPrograms/Ionic/myApp
    41 error Darwin 14.3.0
    42 error argv "node" "/usr/local/bin/npm" "install" "-g" "ios-sim"
    43 error node v0.12.4
    44 error npm  v2.10.1
    45 error Unexpected token <
    45 error
    45 error <?xml version="1.0" encoding="utf-8"?>
    45 error <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    45 error  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
    45 error <html>
    45 error   <head>
    45 error     <title>503 No healthy backends</title>
    45 error   </head>
    45 error   <body>
    45 error     <h1>Error 503 No healthy backends</h1>
    45 error     <p>No healthy backends</p>
    45 error     <h3>Guru Mediation:</h3>
    45 error     <p>Details: cache-ord1725-ORD 1434476281 873637133</p>
    45 error     <hr>
    45 error     <p>Varnish cache server</p>
    45 error   </body>
    45 error </html>
    46 error If you need help, you may report this error at:
    46 error     <https://github.com/npm/npm/issues>
    47 verbose exit [ 1, true ]

**Comment by msmith17** [comment]
Gah.  The instruction were wrong - order of arguments needed to be
    npm install ios-sim -g
Apologies.

**Comment by zkat** [comment]
@msmith17 that was not the problem. `npm install -g <package...>` is actually perfectly legal. What you ran into was a brief registry hiccup. Everything should be fine now. :)

**Comment by othiym23** [comment]
npm doesn't care in which position arguments are placed: `npm -g install ios-sim`, `npm install -g ios-sim`, and `npm install ios-sim -g` are all equivalent and should work. I think you encountered [a minor outage in the registry](http://status.npmjs.org/incidents/w5gfqx98m4qm) that happened around the time you were trying to run your install:

```
45 error <?xml version="1.0" encoding="utf-8"?>
45 error <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
45 error  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
45 error <html>
45 error   <head>
45 error     <title>503 No healthy backends</title>
45 error   </head>
45 error   <body>
45 error     <h1>Error 503 No healthy backends</h1>
45 error     <p>No healthy backends</p>
45 error     <h3>Guru Mediation:</h3>
45 error     <p>Details: cache-ord1725-ORD 1434476281 873637133</p>
45 error     <hr>
45 error     <p>Varnish cache server</p>
45 error   </body>
45 error </html>
```

**Comment by msmith17** [comment]
Thanks.  That is reassuring.  It seemed a bit fragile.

Mike

Michael Smith
msmith17@austin.rr.com
