### ISSUE TITLE
How about adding something like `bundle check`.

### ISSUE THREAD

**Issue by rapheld** [npm/npm#8586]
This would be helpful for automation scripts.

**Comment by KenanY** [comment]
For anyone else like me who didn't know what `bundle check` is:

```
bundle check(1)
        Determine whether the requirements for your application are installed and
        available to bundler
```

**Comment by othiym23** [comment]
`npm ls` will show you if your currently-installed tree is ready to go (and sets the exit code accordingly), and `npm outdated` will do the checking necessary to see if your packages are up to date with your registry. I believe that covers the use case pretty thoroughly, and so I'm going to call this something that is already addressed by npm. Let us know if there's something we're missing, and thank you for your time.
