### ISSUE TITLE
npm ERR! registry error parsing json

### ISSUE THREAD

**Issue by meisyal** [npm/npm#8591]
Hello all,

This is my first time using NodeJS technologies. I have plan build a project using this technology. I installed __NodeJS__ using __Windows 7 installer__ for __64-bit__ machine. My __NodeJS__ version is __0.12.4__ and __npm__ version is __2.11.2__ (I have updated to the latest version after I have the bundled version along with NodeJS installer). I have a problem here, when I was trying to install node package using npm, I always got ```npm ERR! registry error parsing json```. I have read several solutions on the internet. Unfortunately, It didn't work for me.
For example, I want to install **Bower**.
I got the result ```npm ERR! registry error parsing json```

I hope there is a solution.
Thank you.

**Comment by johnrc** [comment]
You might try the suggestions on the [npm wiki](https://github.com/npm/npm/wiki/Troubleshooting#invalid-json). If those don't work, can you try running the Node installer again and see if it works with the bundled version of `npm`?

**Comment by meisyal** [comment]
thank you for response @johnrc. I have followed the suggestions from npm wiki. But, I got no luck. The problem still exists. I have re-installed Node installer and restarted my computer. I still got no luck.

Here below is some screenshots where the problem occurred:
![npm-json-error](https://cloud.githubusercontent.com/assets/3685290/8223523/f08d9d86-15a2-11e5-94bf-e79e491e65fd.png)
![npm-json-error-2](https://cloud.githubusercontent.com/assets/3685290/8223526/f7cf9d42-15a2-11e5-8826-9738ab06c687.png)

**Comment by meisyal** [comment]
I just made an experiment installing node package which doesn't have any dependencies. 
The result is the node package was installed. When I was installing the node package which have more dependencies, I always failed with ```error parsing json```. 
I just don't know why. Could it be my internet connection so slow?

**Comment by meisyal** [comment]
OK. Sorry, I was late, to make clear the problem I upload my ```npm-debug.log``` in [here](https://gist.github.com/meisyal/7b21a74f12d23d4951ab).
This context is when I was installing cordova using ```npm install -g cordova -d```.

Thanks

**Comment by meisyal** [comment]
I have solve my own problem. Like I said before, the problem is my internet connection.
I tried to install Node package using another internet connection and it worked.

Thank you all for your responses.
