### ISSUE TITLE
linux curl https://registry.npmjs.org is not working

### ISSUE THREAD

**Issue by TylerYang** [npm/npm#8597]
Hi guys,
I try to curl https://registry.npmjs.org  from my remote linux server and it is not working, and the error message is 
<code>curl: (6) Could not resolve host: registry.npmjs.org; Name or service not known</code>

But it is working in my local mac.  Any ideas? Thx...

**Comment by tjwebb** [comment]
Your remote linux server is having a DNS fail of some sort.

```
$ curl registry.npmjs.org
{"db_name":"registry","doc_count":170285,"doc_del_count":364,"update_seq":1084433,"purge_seq":0,"compact_running":false,"disk_size":786051195,"data_size":610731883,"instance_start_time":"1426813045395799","disk_format_version":6,"committed_update_seq":1084433}tjwebb@latitude:/home/tjwebb $ 
```

**Comment by TylerYang** [comment]
Yes. Is there any way to solve this? I mean do we have any other registry url..?

**Comment by tjwebb** [comment]
The problem is the configuration of your machine, or its network, not npm.

**Comment by johnrc** [comment]
Is your linux server connected to the Internet via a proxy?

**Comment by TylerYang** [comment]
Seems not. And I can curl to another website from my linux server.  So wried...

**Comment by johnrc** [comment]
Yes, very strange. So you can curl an external website like www.google.com? You might also try `curl -v registry.npmjs.org` or `nslookup registry.npmjs.org` and see if you get more info to go off of.

**Comment by TylerYang** [comment]
I can curl some Chinese Website but not google/github/stackoverflow. Seems
it is because of the GFW.       ......   Anyway, thx for you guys' help.

2015-06-24 12:09 GMT+08:00 John Cragun <notifications@github.com>:

**Comment by tjwebb** [comment]
@tylergreen yes, I pointed this out here: https://github.com/npm/npm/issues/8597#issuecomment-113392410. If the server is in China, your DNS will point to all kinds of crazy places.

**Comment by TylerYang** [comment]
Seems I have to upload node_modules from my local. I didn't notice that before. Thank you. : )
