### ISSUE TITLE
npm appears to uninstall several things after installing them - Laravel Gulp / Elixir

### ISSUE THREAD

**Issue by zerojargon** [npm/npm#8600]
Having real issues working this out. It's taking about 3 hours to run npm install each time?!

Unfortunately the log is too long to be copied and pasted onto github.

I've uploaded the log here:
http://www.wepaste.com/npmerror/

Any help would be massively appreciated.

If it's any help, I'm using Virtual Box & Vagrant (Homestead), running Ubuntu within a Windows Environment.

The reason for running no-bin-links is due to the character length issue I've come across before where nested components exceed the character length that windows is happy with.

**Comment by KenanY** [comment]
@zerojargon `npm --version`?

**Comment by zerojargon** [comment]
Sorry! @KenanY 2.10.1

**Comment by zerojargon** [comment]
Just updated to 2.11.2 and trying again... will be some time before I can post result.

**Comment by KenanY** [comment]
Closing since user seems to have deleted their GitHub account.
