### ISSUE TITLE
feature request: expose Stats

### ISSUE THREAD

**Issue by iamstarkov** [npm/npm#8603]
![screen shot 2015-06-18 at 18 27 13](https://cloud.githubusercontent.com/assets/559321/8236322/ca100cf8-15e7-11e5-9b8f-1bb5d6391867.png)

> The current situation.

I cannot find any npm API exposing this information.

> How and why the current situation is problematic.

If I want to create fun project about npm packgages stats, I have to use web crawler to gather this information from web pages. it’s not fun at all.

> A detailed proposal or pull request that demonstrates how the problem could be solved.

You can find almost everything else on package’s web page, so probably there is some internal API which is not exposed yet now. My problem will be solved if npm will be able to show me package’s stats (cli and programmatically, of course)

> A use case – who needs this feature and why?

sorry, dunno about others, but I will be one step forward to be able to construct stats page, which can encourage new devs to contribute to OSS. Checkout [new stackoverflow profile pages][sf]. Right now, I want to grab statistics about personal packages’s installs and experiment with visualising it.
![](http://i.stack.imgur.com/UjNAf.png)

[sf]: http://blog.stackoverflow.com/2015/04/two-new-user-pages-one-new-stat-this-ones-big/

> Any caveats.

I don’t know that much, but if npm inc have internal api, then it will be easy (probably) to expose this api to cli and programmatical environment

**Comment by KenanY** [comment]
@iamstarkov Take a look at this: https://github.com/npm/download-counts :) I recommend the [npm-stats](https://github.com/hughsk/npm-stats) module.

**Comment by iamstarkov** [comment]
awsm, thanks a lot

**Comment by iamstarkov** [comment]
it works, thank you one more time
> TIL: get npm package’s downloads stats:
>
>      require('npm-stats')().module(name).downloads(console.log.bind(console))
> — https://twitter.com/iamstarkov/status/611647569798778880

**Comment by KenanY** [comment]
@iamstarkov No problem! Nice one-liner :)

**Comment by iamstarkov** [comment]
and now there is a package https://github.com/iamstarkov/npm-profile-downloads
