### ISSUE TITLE
Installation Errors

### ISSUE THREAD

**Issue by mkamaalr** [npm/npm#8610]
![npmerror](https://cloud.githubusercontent.com/assets/7060142/8248558/aa021980-168a-11e5-88ec-07eae1efdcc3.png)

Trying to install famous on my pc and got this error, but when i tried to install on another pc, the installation when fine. Sorry but what should i do? 
And this is the debug log:
https://gist.github.com/mkamaalr/1e37515d774bd7991a89

npm version : 2.5.1
*tested with the latest version, but the error still same
*tried the 'npm cache clean' but the result still same

**Comment by quarterto** [comment]
This looks like it could be an issue with Git, not npm. Which version of Git are you using, and how is it installed?

**Comment by mkamaalr** [comment]
@quarterto i'm using cygwin for windows , and the version of git is 1.7.9 (git --version). I installed it with cygwin, but i got Git bash also, maybe it got conflict?
