### ISSUE TITLE
lock failed . Latest NPM installed

### ISSUE THREAD

**Issue by bhanuc** [npm/npm#8613]
I am trying to install gm using command

```npm install gm --save```

My npm error log is at - https://gist.github.com/bhanuc/67f3c1fa33b80d5f6d19 . I would love to try to solve the error given someone can give me some hints. Complete solutions also appreciated.

**Comment by KenanY** [comment]
@bhanuc Try this first?:

``` sh
$ sudo chown -R $(whoami) "$HOME/.npm"
```

**Comment by bhanuc** [comment]
ok it worked. @KenanY  Can you please explain what was the issue

**Comment by KenanY** [comment]
@bhanuc Your user account did not have the permissions necessary to read/write to `npm`'s cache directory, probably because `npm` was executed with `sudo` at some point so the cache files were created with `sudo` permissions.

**Comment by bhanuc** [comment]
thanks
