### ISSUE TITLE
Run the postversion script after the commit and tag have been made

### ISSUE THREAD

**Issue by mike-engel** [npm/npm#8622]
Meta: I'm running iojs 2.3.0 and npm 2.11.1

Right now, at least I think, the `postversion` script gets run after the bump has been made to package.json, but before the commit and tag have been made. I'm trying to add a `postversion` script that will push up changes, publish to a private npm repo, then checkout a development branch to continue working. As of right now, it fails because the commit hasn't been made that contains the version bump.

Let me know if I'm doing something wrong.

Thanks!

**Comment by iarna** [comment]
Also related: #8620

**Comment by othiym23** [comment]
This is a great idea!

**Comment by iarna** [comment]
It looks like https://github.com/npm/npm/commit/21ce8fe7dfda78b5522963dc2caff080853da5e7 made this a reality!

**Comment by iarna** [comment]
I'm closing as resolved.

**Comment by othiym23** [comment]
Closing as resolved!

**Comment by othiym23** [comment]
Jinx!

**Comment by mike-engel** [comment]
![yes](https://media2.giphy.com/media/TsD8LGhM5jgs0/200.gif)

Thanks @jamestalmage, @iarna, and @othiym23!
