### ISSUE TITLE
npm publish excludes lib directory

### ISSUE THREAD

**Issue by waynebloss** [npm/npm#8623]
I don't have a `.npmignore` file in my project, but my `.gitignore` file does not exclude the `lib` directory. Yet, `npm publish` does not publish my lib directory. Here is my `.gitignore` file:

```
## Folders ############################

/dist

## - Amazon - Elastic Beanstalk

.elasticbeanstalk/*
!.elasticbeanstalk/*.cfg.yml
!.elasticbeanstalk/*.global.yml

## - JetBrains
.idea/

## - Visual Studio - Probably Ignore
#_ReSharper*/
#ipch/
obj/

## - Visual Studio - .NET
#[Bb]uild/
#[Bb]in
#[Dd]ebug*/
#[Rr]elease*/
#[Tt]est[Rr]esult*
#packages/

## - Visual Studio  - Node.js
bower_components/
node_modules/

## Files ###############################

## - Metadata
*.DS_Store
[Tt]humbs.db

## - Subversion
.svn

## - Office (Temp Files)
~$*

## - Visual Studio - Common
*_i.c
*_p.c
*.aps
*.bak
*.[Cc]ache
*.dbmdl
*.ilk
*.lib
*.log
*.ncb
*.[Oo]bj
*.opensdf
*.pch
*.resharper
*.sbr
*.sdf
*.suo
*.tlb
*.tlh
*.unsuccessfulbuild
*.user
*.vspscc
*.vssscc

## - Visual Studio - Node.js
*.ntvs_analysis.dat

```

**Comment by waynebloss** [comment]
I also tried adding a blank `.npmignore` file, but that did not change anything.

My project is here - https://github.com/devoptix/gulp-njrt

**Comment by waynebloss** [comment]
The next thing I tried was to add the `lib` directory to `directories` in `package.json` and that did not work.

**Comment by KenanY** [comment]
@waynebloss `npm --version`?

**Comment by waynebloss** [comment]
2.10.1

**Comment by waynebloss** [comment]
The problem was found by iarna from #npm on Freenode. I have a `files` entry in my `package.json` so that tells npm to only publish that file. Thanks again!
