### ISSUE TITLE
Install Issues with Pow on Mac OS X Yosemite

### ISSUE THREAD

**Issue by dleszcynski** [npm/npm#8624]
I'm trying to install Pow on my MacBook Pro running OS X Yosemite 10.10.3. Included below are screen shots from Terminal. Any assistance would be much appreciated. I'm a n00b developer so I'm hoping it's something I've done, not an actual issues with the computer. 

![screen shot 2015-06-20 at 2 30 25 pm](https://cloud.githubusercontent.com/assets/11574666/8268817/b8aa3ba6-175d-11e5-9ea1-27471b3cc7ed.png)

**Comment by thephilip** [comment]
Will you please post a copy of your npm-debug.log?  It located in `/Users/davidleszcynski/Library/Application Support/Pow/Hosts/pow/npm-debug.log`.

**Comment by busches** [comment]
@KenanY no reply to @thephilip's follow up almost a year ago.
