### ISSUE TITLE
peer dependency warning for shrinkwrap project

### ISSUE THREAD

**Issue by alistairjcbrown** [npm/npm#8634]
The peer dependency warning shows when installing with a shrinkwrap file, even if the peer dependency is part of the project dependency.
This has been tried both as `dependencies` and `devDependencies` with the same outcome.
#### Environment

```
$ npm -v
2.11.3
$ node -v
v0.10.36
```
#### Example
1. A project relies on `webpack` and has it listed in the dev dependencies in `package.json`.
2. `webpack` has a peer dependency on `node-libs-browser` and the `peerDependencies` warning is shown when running `npm install`.
3. To get rid of the warning, `node-libs-browser` is added to the project and saved in the `package.json` dev dependencies.
4. A clean `npm install` (after nuking `node_modules`) now shows no warnings.
5. To take a dependency version snapshot, `npm shrinkwrap --dev` is used to generate a `npm-shrinkwrap.json` file.
6. A clean `npm install` (after nuking `node_modules`) now shows the peer dependency warnings.

```
$ npm install
npm WARN peerDependencies The peer dependency node-libs-browser@>= 0.4.0 <=0.6.0 included from webpack will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
```

The files used for this are in the following gist:
https://gist.github.com/alistairjcbrown/1b6133372f00401ccabc#file-package-json

**Comment by iarna** [comment]
These warnings should be issued when we create the shrinkwrap, not when we install from it.

**Comment by sterpe** [comment]
@iarna In this case, it feels like there should be no warning at all -- seems like the explicit dependency is becoming a peerDependency from the perspective of the shrinkwrap file.  I have a simple reproduction of this issue using `browserify` & `browserify-shim` here  https://github.com/sterpe/npm-shrinkwrap

thanks!

**Comment by sterpe** [comment]
Still seeing this behavior in `npm@2.14.22` btw.
