### ISSUE TITLE
Error in running npm install -g npm

### ISSUE THREAD

**Issue by awongCM** [npm/npm#8635]
Hi,

I tried installing the update on npm using commands `npm install -g npm`

I got the following errors.

    npm ERR! Windows_NT 6.1.7601
	npm ERR! argv "node" "C:\\Users\\Andy Wong\\AppData\\Roaming\\npm\\node_modules\
	\npm\\bin\\npm-cli.js" "install" "-g" "npm"
	npm ERR! node v0.12.4
	npm ERR! npm  v2.11.3
	npm ERR! code MODULE_NOT_FOUND

	npm ERR! Cannot find module 'dezalgo'
	npm ERR!
	npm ERR! If you need help, you may report this error at:
	npm ERR!     <https://github.com/npm/npm/issues>

	npm ERR! Please include the following file with any support request:
	npm ERR!     D:\Projects\Javascript\npm-debug.log

I have no idea why it complains about the missing module `dezalgo`.  

My guess is going to be that the during the npm upgrade, it failed to fetch dezalgo module?  if that's the case, how do I fetch it again so I can upgrade npm properly...?

**Comment by alexey-shaposhnikov** [comment]
Have you tried to 
` npm i dezalgo` or `npm i dezalgo -g`?

**Comment by awongCM** [comment]
I've tried it. It doesn't work.

Just FYI - I'm running npm on 64-bit Windows 7.

**Comment by rstack** [comment]
I was just able to install it:

`λ npm i dezalgo
npm WARN unmet dependency C:\Users\psmith\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\imagemin-optipng requires image-type@'^0.1.1' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
dezalgo@1.0.3 node_modules\dezalgo
├── wrappy@1.0.1
└── asap@2.0.3`

**Comment by awongCM** [comment]
I show you tomorrow night. I haven't logged on my personal computer all day today....

**Comment by awongCM** [comment]
Hi @rstack 

Here's what my log says.


    0 info it worked if it ends with ok
	1 verbose cli [ 'node',
	1 verbose cli   'C:\\Users\\Andy Wong\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
	1 verbose cli   'i',
	1 verbose cli   'dezalgo',
	1 verbose cli   '-g' ]
	2 info using npm@2.11.3
	3 info using node@v0.12.4
	4 verbose stack Error: Cannot find module 'dezalgo'
	4 verbose stack     at Function.Module._resolveFilename (module.js:336:15)
	4 verbose stack     at Function.Module._load (module.js:278:25)
	4 verbose stack     at Module.require (module.js:365:17)
	4 verbose stack     at require (module.js:384:17)
	4 verbose stack     at Object.<anonymous> (C:\Users\Andy Wong\AppData\Roaming\npm\node_modules\npm\node_modules\read-installed\node_modules\readdir-scoped-modules\readdir.js:2:10)
	4 verbose stack     at Module._compile (module.js:460:26)
	4 verbose stack     at Object.Module._extensions..js (module.js:478:10)
	4 verbose stack     at Module.load (module.js:355:32)
	4 verbose stack     at Function.Module._load (module.js:310:12)
	4 verbose stack     at Module.require (module.js:365:17)
	4 verbose stack     at require (module.js:384:17)
	5 verbose cwd C:\Windows\system32
	6 error Windows_NT 6.1.7601
	7 error argv "node" "C:\\Users\\Andy Wong\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "dezalgo" "-g"
	8 error node v0.12.4
	9 error npm  v2.11.3
	10 error code MODULE_NOT_FOUND
	11 error Cannot find module 'dezalgo'
	12 error If you need help, you may report this error at:
	12 error     <https://github.com/npm/npm/issues>
	13 verbose exit [ 1, true ]

**Comment by rstack** [comment]
Thank you, @awongCM.  Will you please try updating npm as well?

`npm install -g npm`

Does that update successfully?  Are you able to install anything else globally?

**Comment by awongCM** [comment]
Thanks for that @rstack.

I've finally managed to resolved by uninstalling everything and then reinstalling.

I later discovered there was an npm-cache folder that had all the old installation files sitting there.

So I had to wiped it clean.  And now my npm install commands have been restored to normal.

Thanks again for helping me out! ^_^

**Comment by rstack** [comment]
No problem.  Glad to help.  Sometimes it helps to have a second set of eyes looking at something.

**Comment by awongCM** [comment]
Certainly does.

When you know you need help, don't hesitate to raise your hand to approach for it.

Especially if there's a good community out here to lend a helping hand.

**Comment by hardik-shah-28** [comment]
Hi can some 1 help me out please. 
My npm install was throwing lots of error and I went through this steps
$ npm install -g which 
$ which node 
after cd into the directory, inside the directory cd into node_modules\npm folder and finally: 
$ npm install node-gyp@latest 
here worked, the answer is from this site

and now when I am running this command
 npm install --global --production windows-build-tools

it throws me following error 
can not find "dezalgo"

PS C:\Program Files\nodejs\node_modules\npm> npm install --global --production windows-build-tools
module.js:471
    throw err;
    ^

Error: Cannot find module 'dezalgo'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\correct-mkdir.js:2:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
module.js:471
    throw err;
    ^

Error: Cannot find module 'dezalgo'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\correct-mkdir.js:2:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

PS: I went through all the above steps but nothing is useful

**Comment by awongCM** [comment]
the issue is a year old when I first raised it.  

A lot has changed in the node/npm module since then..

What version is your node/npm?

**Comment by hardik-shah-28** [comment]
Hi All,

I found out the problem, Thanks. it was like npm is of version 5 and node
was of version 6. then i installed node of version 8 and npm of version 4
and made some administrative command to solve it.

can you please help me how can I run the serverless code written in nodejs
and needs to be deployed on azure. but I need to run this code locally so
do I need to have azure account?? can you please help me with the steps??

Thanks,
Hardik Shah
