### ISSUE TITLE
npm install command error

### ISSUE THREAD

**Issue by rsa408** [npm/npm#8639]
```
npm ERR! network tunneling socket could not be established, cause=getaddrinfo ENOTFOUND
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "npm"
npm ERR! cwd C:\Program Files
npm ERR! node -v v0.10.30
npm ERR! npm -v 1.4.21
npm ERR! code ECONNRESET
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Program Files\npm-debug.log
npm ERR! not ok code 0
```
log file
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'cordova' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose config Skipping project config: C:\Users\ME/.npmrc. (matches userconfig)
6 silly cache add args [ 'cordova', null ]
7 verbose cache add spec cordova
8 silly cache add parsed spec { raw: 'cordova',
8 silly cache add   scope: null,
8 silly cache add   name: 'cordova',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 verbose addNamed cordova@*
10 silly addNamed semver.valid null
11 silly addNamed semver.validRange *
12 silly addNameRange { name: 'cordova', range: '*', hasData: false }
13 silly mapToRegistry name cordova
14 silly mapToRegistry using default registry
15 silly mapToRegistry registry https://registry.npmjs.org/
16 silly mapToRegistry uri https://registry.npmjs.org/cordova
17 verbose addNameRange registry:https://registry.npmjs.org/cordova not in flight; fetching
18 verbose request uri https://registry.npmjs.org/cordova
19 verbose request no auth needed
20 info attempt registry request try #1 at 6:25:53 PM
21 verbose request id 85bb90139165b3c4
22 http request GET https://registry.npmjs.org/cordova
23 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 1025
24 info attempt registry request try #2 at 6:26:10 PM
25 http request GET https://registry.npmjs.org/cordova
26 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 1025
27 info attempt registry request try #3 at 6:27:12 PM
28 http request GET https://registry.npmjs.org/cordova
29 verbose stack Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 1025
29 verbose stack     at ClientRequest.onError (C:\Program Files\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:168:17)
29 verbose stack     at ClientRequest.g (events.js:199:16)
29 verbose stack     at ClientRequest.emit (events.js:107:17)
29 verbose stack     at Socket.socketErrorListener (_http_client.js:272:9)
29 verbose stack     at Socket.emit (events.js:107:17)
29 verbose stack     at net.js:923:16
29 verbose stack     at process._tickCallback (node.js:355:11)
30 verbose cwd C:\Users\ME
31 error Windows_NT 6.1.7601
32 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "cordova"
33 error node v0.12.0
34 error npm  v2.5.1
35 error code ECONNRESET
36 error network tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 1025
36 error network This is most likely not a problem with npm itself
36 error network and is related to network connectivity.
36 error network In most cases you are behind a proxy or have bad network settings.
36 error network
36 error network If you are behind a proxy, please make sure that the
36 error network 'proxy' config is set properly.  See: 'npm help config'
37 verbose exit [ 1, true ]
```
there is no proxy server but for each command shows this error in same internet connection with same windows 7 version goes correctly.

**Comment by rstack** [comment]
What HTTP response do you get when you curl https://registry.npmjs.org/cordova?  Probably just went down for a bit.  Worked for me just now when I tested.

**Comment by rsa408** [comment]
when I open curl https://registry.npmjs.org/cordova in browse it shows me the content with starting "{"_id":"cordova","_rev":"510-d32d4b477e49fc8b8f287f4ff68f8969"" 
i think this is not cordova's problem it seems it is Node and npm registration problem yesterday in a same machine with same OS and same internet connection in two different user accounts i have tested in main account was not installing in second account it is installed by some warnings (for cordova)
npm WARN engine cordova-js@4.0.0: wanted: {"node":"~0.10.x"} (current: {"node":"0.12.4","npm":"2.10.1"})
npm WARN engine npm@1.3.4: wanted: {"node":">=0.6","npm":"1"} (current: {"node":"0.12.4","npm":"2.10.1"})
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"0.12.4","npm":"2.10.1"})
npm WARN installMany normalize-package-data was bundled with npm@1.3.4, but bundled package wasn't found in unpacked tree
C:\Users\ME\AppData\Roaming\npm\cordova -> C:\Users\ME\AppData\Roaming\npm\node_modules\cordova\bin\cordova
npm WARN unmet dependency C:\Users\ME\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\ionic-cordova-lib\node_modules\cordova-js\node_modules\browserify\node_modules\module-deps\node_modules\stream-combiner2\node_modules\through2 requires readable-stream@'~1.0.17' but will load
npm WARN unmet dependency C:\Users\ME\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\ionic-cordova-lib\node_modules\cordova-js\node_modules\browserify\node_modules\readable-stream,
npm WARN unmet dependency which is version 1.1.13
npm WARN unmet dependency C:\Users\ME\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\ionic-cordova-lib\node_modules\cordova-js\node_modules\browserify\node_modules\module-deps\node_modules\stream-combiner2\node_modules\through2 requires xtend@'~3.0.0' but will loadnpm WARN unmet dependency C:\Users\ME\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\ionic-cordova-lib\node_modules\cordova-js\node_modules\browserify\node_modules\xtend,
npm WARN unmet dependency which is version 4.0.0
cordova@5.1.1 C:\Users\ME\AppData\Roaming\npm\node_modules\cordova
├── underscore@1.7.0
├── q@1.0.1
├── nopt@3.0.1 (abbrev@1.0.7)
└── cordova-lib@5.1.1 (valid-identifier@0.0.1, osenv@0.1.0, properties-parser@0.2.3, bplist-parser@0.0.6, mime@1.2.11, unorm@1.3.3, semver@2.1.0, shelljs@0.3.0, cordova-app-hello-world@3.9.0, rc@0.5.2, dep-graph@1.1.0, xcode@0.6.7, d8@0.4.4, elementtree@0.1.6, through2@0.6.3, npmconf@0.1.16, glob@4.0.6, request@2.47.0, plist@1.1.0, npm@1.3.4, init-package-json@1.7.0, tar@1.0.2, cordova-registry-mapper@1.1.8, cordova-js@4.0.0)

today i alsso tried but same problem for cordova, ionic, bowe, alloy and cordova-lib, packages.

**Comment by rsa408** [comment]
I resolved, 
1) first completely removed all npm, folders
2) found npm configfile and removed it
3) removed node.js program
* completely cleaned system from any npm possible files.I also used registry optimizer 
4) install last release of node.js (0.12.5 I think today released) to a new path
after that ever thing is ok.
but these warnings occurred to me

npm WARN engine cordova-js@4.0.0: wanted: {"node":"~0.10.x"} (current: {"node":"0.12.5","npm":"2.11.2"})
npm WARN engine npm@1.3.4: wanted: {"node":">=0.6","npm":"1"} (current: {"node":"0.12.5","npm":"2.11.2"})
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"0.12.5","npm":"2.11.2"})
npm WARN installMany normalize-package-data was bundled with npm@1.3.4, but bundled package wasn't found in unpacked tree

**Comment by othiym23** [comment]
Closing as resolved!

**Comment by leotm** [comment]
You may have had npm installed in 2 locations globally!
- \Program Files\nodejs\node_modules\npm
- \AppData\Roaming\npm
(I found SublimeLinter-jshint could detect JSHint from either location)
