### ISSUE TITLE
Build unsuccessful for seemingly valid version

### ISSUE THREAD

**Issue by joshuarossi** [npm/npm#8645]
It says that this is not a compatible version, but then lists the version requested as a compatible version...I am new to the whole issue reporting thing, but the error message suggested i post here...

P.S. It worked fine with node version "0.10"

npm ERR! node -v v0.8.28
npm ERR! npm -v 1.2.30

npm ERR! Error: No compatible version found: **glob@'^4.4.2'**
npm ERR! Valid install targets:
npm ERR! ["1.1.0","2.0.9","2.0.8","2.0.7","2.1.0","3.0.0","3.0.1","3.1.0","3.1.1","3.1.2","3.1.3","3.1.4","3.1.5","3.1.6","3.1.7","3.1.9","3.1.10","3.1.11","3.1.12","3.1.13","3.1.14","3.1.15","3.1.16","3.1.17","3.1.18","3.1.19","3.1.20","3.1.21","3.2.0","3.2.1","3.2.3","3.2.4","3.2.5","3.2.6","3.2.7","3.2.8","3.2.9","3.2.10","3.2.11","4.0.0","4.0.1","4.0.2","4.0.3","4.0.4","4.0.5","4.0.6","4.1.2-beta","4.1.2","4.1.3","4.1.4","4.1.5","4.1.6","4.2.0","4.2.1","4.2.2","4.3.0","4.3.1","4.3.2","4.3.3","4.3.4","4.3.5","4.4.0",**"4.4.2"**,"4.5.0","5.0.0","4.5.1","5.0.1","4.5.2","5.0.2","4.5.3","5.0.3","5.0.4","5.0.5","5.0.6","5.0.7","5.0.9","5.0.10"]
npm ERR!     at installTargetsError (/home/travis/.nvm/v0.8.28/lib/node_modules/npm/lib/cache.js:719:10)
npm ERR!     at /home/travis/.nvm/v0.8.28/lib/node_modules/npm/lib/cache.js:641:10
npm ERR!     at saved (/home/travis/.nvm/v0.8.28/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:302:15)

**Comment by KenanY** [comment]
@joshuarossi `npm@1.2` is extremely old and does not support the `^` semver operator, so it thinks there is no valid version. Please try [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm).

**Comment by joshuarossi** [comment]
Thanks, I think this was part of testing older versions, as I mentioned I am using the current one and its fine. This was just a backwards test for a meteor package

**Comment by iarna** [comment]
joshuarossi: The thing is, if you updated your npm then it might work with `0.8`. The version of npm that ships with `0.8` doesn't work for many modules in the registry. Normal practice for folks still using `0.8` would still be to use a more recent version of npm.

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
