### ISSUE TITLE
Couldn't read dependencies

### ISSUE THREAD

**Issue by taylor009** [npm/npm#8646]
![screenshot from 2015-06-22 21 19 03](https://cloud.githubusercontent.com/assets/13009418/8296898/606e08a0-1924-11e5-9a59-da804605ba38.png)

**Comment by othiym23** [comment]
There's a lot on the screen there, so it's easy to overlook, but:

```
dont forget to install dependencies:
$ cd test && npm install
```

If that doesn't work, you may want to try [upgrading your Node](https://github.com/npm/npm/wiki/Troubleshooting#updating-node-on-linux) and [npm installations](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-nix-osx-linux-etc). `npm@1.3` is no longer supported and is filled with bugs.

**Comment by taylor009** [comment]
Thanks I updated my npm and I get these errors when I npm install on my file?
Here is what I get.
![error](https://cloud.githubusercontent.com/assets/13009418/8313469/ecd128ea-19b0-11e5-8b5b-4999ad5c26d6.png)
