### ISSUE TITLE
Error: Attempting to unlock when not locked

### ISSUE THREAD

**Issue by benoneal** [npm/npm#8647]
Getting this with almost every module when installing on v2.12.0
```
npm ERR! Attempt to unlock [MODULE_PATH], which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.5
npm ERR! npm  v2.12.0
```

**Comment by Toups-Chartboost** [comment]
I'm seeing this issue as well, and haven't been able to figure out how to get around it.

**Comment by KenanY** [comment]
@Toups-Chartboost have you tried

``` sh
sudo chown -R $(whoami) "$HOME/.npm"
```

**Comment by eric96k** [comment]
You issue looks to be the same as this one, which is a folder permission issue.
https://github.com/npm/npm/issues/8498

I had the same log file as you and run the solution there and it worked.

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.
