### ISSUE TITLE
while installing ionic getting error - npm ERR! tar.unpack

### ISSUE THREAD

**Issue by mayurr87** [npm/npm#8650]
![untitled](https://cloud.githubusercontent.com/assets/6565967/8301068/7bc741f0-19a8-11e5-804f-306bf5d1eb7a.png)

Tried 1. npm cache clean 2. run the cli  by administrator 3. restarted the system  but error remain same.

Badly stocked.

**Comment by ffacon** [comment]
Hello Mayur,

I had the same issue with Ionic Module with latest version of Node.js on WIndows.
It works fine for me with version 0.10.29. (https://nodejs.org/dist/)

François.

**Comment by mayurr87** [comment]
Thanks a lot for your reply.

1. Have tried to install the version 0.10.29 by <b>nvm install 0.10.29</b> command but getting error 
<b>(Node.js v0.10.29 is only available in 32-bit).</b>

2. Have downloaded node-v0.10.29-x64 From url https://nodejs.org/dist/ but while installing it showing <b>Later version of node.js is already installed. </b>

Will uninstall the current version and install this and again will try . 

Will get back to you once its done.

**Comment by mayurr87** [comment]
cheers!!!

It works like charm. Thanks a lot.

Have installed version mentioned above and every thing works fine for me.

Just a note if any one not able to uninstall node js just right click on the installer you will see the uninstaller option there it self.
