### ISSUE TITLE
Error: Make Install (v2.12.0)

### ISSUE THREAD

**Issue by MarkOSullivan94** [npm/npm#8652]
So I tried yesterday to issue the command 'make install' which gave me the below error.

![npm-error](https://cloud.githubusercontent.com/assets/6950843/8305061/639c24d8-19a3-11e5-9951-3af967ead2c1.PNG)

This seems to be just an error with version 2.12.0 as I tried 2.11.3 and I was able to successfully issue the command.

**Comment by iarna** [comment]
The error there is a dns lookup error trying to look up `registry.npmjs.org`. I suspect this was a transient network error– can you try again?

**Comment by MarkOSullivan94** [comment]
@iarna just tried it again there now and I'm getting the exact same error.
