### ISSUE TITLE
What about a npm cli command ?

### ISSUE THREAD

**Issue by nfroidure** [npm/npm#8653]
In order to avoid to install globally CLI modules, i often add a script like "env NPM_RUN_CLI=1" to be able to execute any binary installed on the current folder: https://github.com/nfroidure/ttf2woff2/blob/ccfa1e1be3d774496785df155110421d929aa1a7/package.json#L14

Usage: npm run cli -- gulp build

What about making it directly in NPM? I know you can modify your own PATH env var but i dislike the idea of having command completion relative to the working directory.

Any thought on adding an "npm cli" feature to npm ?

**Comment by gplancke** [comment]
:+1:

**Comment by KenanY** [comment]
I'm pretty late on this, but is this basically the same as [the `npm exec` request](https://github.com/npm/npm/labels/npm-exec)?

**Comment by nfroidure** [comment]
Looks like https://github.com/npm/npm/issues/6053 does a bit more but it could fit my needs.
