### ISSUE TITLE
Having trouble installing phonegap 

### ISSUE THREAD

**Issue by sidtuli** [npm/npm#8654]
I have been making several attempts to install phonegap with nodejs and haven't been able to figure out my issues on my own. 

Here is my debug log:
https://gist.github.com/18e895b4ed71d3f16bb7

**Comment by KenanY** [comment]
@sidtuli Could you try [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) first?

**Comment by sidtuli** [comment]
I tried it didn't work. Weirdly enough I got phonegap installed by using nodejs version 10.22.

**Comment by ehsalazar** [comment]
It sounds like you were able to get the package installed. I'll close this for now as we’re trying to clean up some old issues. We’ll be happy to reopen if necessary.
