### ISSUE TITLE
Feature request: npm publish should save the user who published

### ISSUE THREAD

**Issue by dominicbarnes** [npm/npm#8655]
Currently, I'm not sure whether or not npm keeps a record of which user published a given version of a module. It would be great if `npm show package@version` included the username of the person who published that particular version.

This is particularly useful in modules that have many collaborators, especially open-source projects. Sometimes, people forget to tag releases or something and it makes it harder to trace down the history of a particular version.

It could probably be added as `author`, structured similarly to `time`: (that should be backwards-compatible, right?)

```js
author: {
  '0.0.1': 'userA',
  '0.0.2': 'userA',
  '0.1.0': 'userB',
  // ...
}
```

**Comment by stephenmathieson** [comment]
+1

**Comment by othiym23** [comment]
The user that published a given version of a given package is stored on the version's portion of the package metadata as `_npmUser`, and there's also the `maintainers` field. This should do what you want! Closing as resolved. Thanks for your time!

**Comment by dominicbarnes** [comment]
Oh nifty! Just for future reference, using `npm show package@version _npmUser` shows what I asked for. However, `_npmUser` does not show up by default, presumably because fields prefixed by `_` are hidden from the full view.
