### ISSUE TITLE
Install Phonegap on Windows 8

### ISSUE THREAD

**Issue by mtorressantos** [npm/npm#8656]
I tried to install phonegap with the latest versions of json and NPM, I installed git in windows but still continues with this problem.

C:\Windows\system32>npm install -g phonegap
npm ERR! git clone --template=C:\Users\Mau\AppData\Roaming\npm-cache\_git-remote
s\_templates --mirror https://github.com/imhotep/plugman.git C:\Users\Mau\AppDat
a\Roaming\npm-cache\_git-remotes\https-github-com-imhotep-plugman-git-20c32d58:
undefined
npm ERR! git clone --template=C:\Users\Mau\AppData\Roaming\npm-cache\_git-remote
s\_templates --mirror https://github.com/imhotep/plugman.git C:\Users\Mau\AppDat
a\Roaming\npm-cache\_git-remotes\https-github-com-imhotep-plugman-git-20c32d58:
undefined
npm ERR! git clone --template=C:\Users\Mau\AppData\Roaming\npm-cache\_git-remote
s\_templates --mirror https://github.com/filmaj/node-plist.git C:\Users\Mau\AppD
ata\Roaming\npm-cache\_git-remotes\https-github-com-filmaj-node-plist-git-653fe2
2e: undefined
npm ERR! git clone --template=C:\Users\Mau\AppData\Roaming\npm-cache\_git-remote
s\_templates --mirror https://github.com/filmaj/node-plist.git C:\Users\Mau\AppD
ata\Roaming\npm-cache\_git-remotes\https-github-com-filmaj-node-plist-git-653fe2
2e: undefined
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "phonegap"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code ENOGIT

npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\system32\npm-debug.log

C:\Windows\system32>

**Comment by KenanY** [comment]
@mtorressantos Can you run, for example, `git --version` from your command-line?

**Comment by mtorressantos** [comment]
@KenanY  git version 1.9.5.msysgit.1
