### ISSUE TITLE
It should error when the `dist-tag` is a valid semver.

### ISSUE THREAD

**Issue by stevemao** [npm/npm#8657]
When I set my `dist-tag` as `0.1.0-alpha` it doesn't error. 
But when I install it with `npm install conventional-changelog@0.1.0-alpha` I got

```
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "conventional-changelog@0.1.0-alpha"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.3

npm ERR! version not found: conventional-changelog@0.1.0-alpha
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/stevemao/Documents/pub_games/number-pad/npm-debug.log
```

It should error when the `dist-tag` is a valid semver. So It's not ambiguous.
I changed the `dist-tag` to `next` it works fine.

**Comment by KenanY** [comment]
Interesting considering how that should have already not been allowed after https://github.com/npm/npm/pull/6098.

**Comment by stevemao** [comment]
Maybe because `0.1.0-alpha` is not a valid semver range? If so this should be a bug in semver.

**Comment by stevemao** [comment]
@iarna I think this bug hasn't been fixed yet?
