### ISSUE TITLE
multi-stage: npm ls fails on missing optional dependencies

### ISSUE THREAD

**Issue by mantoni** [npm/npm#8659]
When thre are optional dependencies in the tree that could not be installed, `npm ls` lists them like `─ UNMET DEPENDENCY fsevents@~0.3.1` amd fails with and exit code 1 and this message:

```
npm ERR! missing: fsevents@~0.3.1, required by chokidar@0.12.6
```

Since it's an optional dependency, the exit code should be 0. If you want to list it in the tree, I'd prefer the label to be `MISSING OPTIONAL DEPENDENCY` or something that clarifies that it's not an issue.

**Comment by iarna** [comment]
Yup, you're right, that's absolutely an error. Historically we didn't list them at all.

**Comment by iarna** [comment]
I fixed that with https://github.com/npm/npm/commit/6935aa3ee3e1b8e976a41a49f36ce3199fa4fab3

**Comment by mantoni** [comment]
:+1: Thanks!
