### ISSUE TITLE
Unclear difference between ^ and ~

### ISSUE THREAD

**Issue by JasperHorn** [npm/npm#8663]
On https://docs.npmjs.com/files/package.json:

`^` is described as "Approximately equivalent to version" See semver(7)
`~` is described as "Compatible with version" See semver(7)

However, the difference between "approximately equivalent" and "compatible with" is never explained (and semver doesn't deal in terms like "approximately equivalent" at all).

**Comment by KenanY** [comment]
@JasperHorn Does the referenced page, [`semver(7)`](https://docs.npmjs.com/misc/semver), explain it well enough?

**Comment by JasperHorn** [comment]
Ah yes, it does.

I had actually interpreted the reference as point 7 of http://semver.org
I suppose the real blame is on [semver](https://docs.npmjs.com/misc/semver) for being named confusingly... Still, it might be worth it to make the reference clearer.

**Comment by KenanY** [comment]
@JasperHorn I believe having those `semver(7)` references on https://docs.npmjs.com/files/package.json link to https://docs.npmjs.com/misc/semver would be a nice fix https://github.com/npm/docs/issues/106

**Comment by JasperHorn** [comment]
Agreed.

**Comment by sindresorhus** [comment]
https://nodesource.com/blog/semver-tilde-and-caret explans it clearly.

**Comment by othiym23** [comment]
Closing as resolved.
