### ISSUE TITLE
npm cannot find module ('..') 

### ISSUE THREAD

**Issue by Lakkss** [npm/npm#8665]

**Comment by KenanY** [comment]
@Lakkss Sorry, it's not clear to me what the issue is here. Do you have a `npm-debug.log` you could [upload](https://gist.github.com/)?

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
