### ISSUE TITLE
Unable to install using npm install -g genieacs

### ISSUE THREAD

**Issue by Godday** [npm/npm#8670]
Hello,

Please I get errors while trying to install the genieacs. Below is the error log while trying to install.

npm http GET https://registry.npmjs.org/genieacs
npm http 304 https://registry.npmjs.org/genieacs
npm WARN package.json genieacs@1.0.4 No readme data.
npm http GET https://registry.npmjs.org/libxmljs
npm http GET https://registry.npmjs.org/redis
npm http GET https://registry.npmjs.org/hiredis
npm http GET https://registry.npmjs.org/mongodb
npm http 304 https://registry.npmjs.org/redis
npm ERR! Error: No compatible version found: redis@'^0.12.1'
npm ERR! Valid install targets:
npm ERR! ["0.0.1","0.0.2","0.0.3","0.0.4","0.0.7","0.0.8","0.1.0","0.1.1","0.1.2","0.2.0","0.2.1","0.2.2","0.2.3","0.2.4","0.2.6","0.3.0","0.3.1","0.3.2","0.3.3","0.3.4","0.3.5","0.3.6","0.3.7","0.3.9","0.4.0","0.4.1","0.4.2","0.5.0","0.5.1","0.5.2","0.5.3","0.5.4","0.5.5","0.5.6","0.5.7","0.5.8","0.5.9","0.5.10","0.5.11","0.6.0","0.6.1","0.6.2","0.6.3","0.6.4","0.6.5","0.6.6","0.6.7","0.7.0","0.7.1","0.7.2","0.7.3","0.8.0","0.8.1","0.8.2","0.8.3","0.8.4","0.8.5","0.8.6","0.9.0","0.9.1","0.9.2","0.10.0","0.10.1","0.10.2","0.10.3","0.11.0","0.12.0","0.12.1"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:709:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:631:10
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-504.16.2.el6.i686
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "genieacs"
npm ERR! cwd /usr/local
npm ERR! node -v v0.10.9
npm ERR! npm -v 1.2.24
npm http 304 https://registry.npmjs.org/libxmljs
npm http 304 https://registry.npmjs.org/mongodb
npm http 304 https://registry.npmjs.org/hiredis
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/local/npm-debug.log
npm ERR! not ok code 0

Kindly assist in getting a solution to the installation process.
Thanks.

Best Regards,
Godday

**Comment by KenanY** [comment]
@Godday [Upgrading](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) should fix your issue :)

**Comment by Godday** [comment]
I was able to fix it.

Thanks a lot
