### ISSUE TITLE
package in node_modules without a package.json crashes `npm install` (npm v3.0.0)

### ISSUE THREAD

**Issue by substack** [npm/npm#8680]
I have a symlink to a package in node_modules/ that doesn't have a package.json. npm 3.0.0 fails with this message when I try to install a new package:

```
$ npm install memdown
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/home/substack/prefix/bin/node-iojs" "/home/substack/prefix/bin/npm" "install" "memdown"
npm ERR! node v2.0.0
npm ERR! npm  v3.0.0
npm ERR! path /home/substack/projects/versioned-function/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/home/substack/projects/versioned-function/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/substack/projects/hyperlog-index/npm-debug.log
```

The `versioned-function/` directory exists, but doesn't have a package.json yet. This behavior worked fine in all previous versions of npm.

**Comment by iarna** [comment]
Yup, that's `read-package-tree` being overly picky. We should probably only have it actually error out if it can't build a tree at all. Surprisingly, this is actually related to #8678

**Comment by iarna** [comment]
The fix for this landed in master as https://github.com/npm/npm/commit/0bb08c88c2b6ae2a07848ce78991dccb99441387 and will be in the 3.1.0 release.
