### ISSUE TITLE
Automatically compute include paths for binding.gyp files

### ISSUE THREAD

**Issue by iarna** [npm/npm#8684]
It'd be pretty DWIMy if we could fill in `include_dirs` automagically from your deps list. Currently folks have to do manual stuff like this:

https://github.com/strongloop/fsevents/blob/master/binding.gyp#L15-L17

Which isn't terrible, but also is a lotta make-work.

**Comment by othiym23** [comment]
This, like many affordances that would make working with `node-gyp` simpler, would be nice to have, but this isn't something that the CLI team is going to have time to work on within the next 6-12 months, so we're closing this. There's also a chance this is something that would be useful to add to `node-gyp` directly. So, internet, if you find this issue, you might want to propose a patch that does something like this to `node-gyp`. Thanks for capturing this, Rebecca!
