### ISSUE TITLE
npm hangs when installing some packages

### ISSUE THREAD

**Issue by brentonhouse** [npm/npm#8685]
npm@3.0.0

When running `npm install -verbose tonylukasavage/titanium-os`  on windows, it hangs and never finishes.  This worked fine on previous version of npm (2.x)

```
npm info it worked if it ends with ok
npm verb cli [ 'node',
npm verb cli   'C:\\Users\\Brenton\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'install',
npm verb cli   '-verbose',
npm verb cli   'tonylukasavage/titanium-os' ]
npm info using npm@3.0.0
npm info using node@v0.12.4
npm verb cache add spec tonylukasavage/titanium-os
npm verb addRemoteGit caching tonylukasavage/titanium-os
npm verb addRemoteGit tonylukasavage/titanium-os is a repository hosted by github
npm verb tryClone git-github-com-tonylukasavage-titanium-os-git-f50275ab06a43fbb1b26b7a4d93346d1 not in flight; caching
npm info git [ 'config', '--get', 'remote.origin.url' ]
npm verb validateExistingRemote tonylukasavage/titanium-os is updating existing cached remote C:\Users\Brenton\AppData\Roaming\npm-cache\_git-remotes\git-github-com-tonylukasavage-titanium-os-git-f50275ab06a43fbb1b26b7a4d93346d1
npm info git [ 'fetch', '-a', 'origin' ]
npm verb updateRemote git fetch -a origin (git://github.com/tonylukasavage/titanium-os.git)
npm verb setPermissions tonylukasavage/titanium-os skipping chownr on Windows
npm verb resolveHead tonylukasavage/titanium-os original treeish: master
npm info git [ 'rev-list', '-n1', 'master' ]
npm verb resolveHead tonylukasavage/titanium-os resolved Git URL: git://github.com/tonylukasavage/titanium-os.git#88204d41ca970cbc5a97ea8642b69b918585d41a
```

**Comment by iarna** [comment]
Well, my first try at reproing it didn't work– that module installs fine for me w/ npm@3 on mac. I'll try again on windows in a bit…

**Comment by mischkl** [comment]
Maybe related to #7862? If the running `install -ddd` results in a hang on `npm verb unlock done`, it seems like a match.

**Comment by busches** [comment]
I don't think this is related to #7862 as it works fine on npm 2. @iarna, here's another repro case. Happens every time on Windows 8.1. 

package.json
```
{
  "name": "npm3bug",
  "version": "0.0.0",
  "dependencies": {
  	"grunt-build-control": "DaftMonk/grunt-build-control"
  },
  "engines": {
    "node": ">=0.10.0"
  },
  "private": true
}
```

Silly Log:
```
C:\Users\Busche\Desktop\nodetest
λ npm install -ddd
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files (x86)\\nodejs\\\\node.exe',
npm verb cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'install',
npm verb cli   '-ddd' ]
npm info using npm@3.0.0
npm info using node@v0.12.4
npm sill loadCurrentTree Starting
npm sill install loadCurrentTree
npm sill install readLocalPackageData
npm sill install normalizeTree
npm sill loadCurrentTree Finishing
npm sill loadIdealTree Starting
npm sill install loadIdealTree
npm sill cloneCurrentTree Starting
npm sill install cloneCurrentTreeToIdealTree
npm sill cloneCurrentTree Finishing
npm sill loadShrinkwrap Starting
npm sill install loadShrinkwrap
npm sill loadShrinkwrap Finishing
npm sill loadAllDepsIntoIdealTree Starting
npm sill install loadAllDepsIntoIdealTree
npm sill fetchOtherPackageData grunt-build-control@github:daftmonk/grunt-build-control
npm sill cache add args [ 'grunt-build-control@github:daftmonk/grunt-build-control',
npm sill cache add   null ]
npm verb cache add spec grunt-build-control@github:daftmonk/grunt-build-control
npm sill cache add parsed spec { raw: 'grunt-build-control@github:daftmonk/grunt-build-control',
npm sill cache add   scope: null,
npm sill cache add   name: 'grunt-build-control',
npm sill cache add   rawSpec: 'github:daftmonk/grunt-build-control',
npm sill cache add   spec: 'github:daftmonk/grunt-build-control',
npm sill cache add   type: 'hosted',
npm sill cache add   hosted:
npm sill cache add    { type: 'github',
npm sill cache add      ssh: 'git@github.com:daftmonk/grunt-build-control.git',
npm sill cache add      sshUrl: 'git+ssh://git@github.com/daftmonk/grunt-build-control.git',
npm sill cache add      httpsUrl: 'git+https://github.com/daftmonk/grunt-build-control.git',
npm sill cache add      gitUrl: 'git://github.com/daftmonk/grunt-build-control.git',
npm sill cache add      shortcut: 'github:daftmonk/grunt-build-control',
npm sill cache add      directUrl: 'https://raw.githubusercontent.com/daftmonk/grunt-build-control/master/package.json' } }
npm verb addRemoteGit caching github:daftmonk/grunt-build-control
npm verb addRemoteGit daftmonk/grunt-build-control is a repository hosted by github
npm sill tryGitProto attempting to clone git://github.com/daftmonk/grunt-build-control.git
npm sill tryClone cloning daftmonk/grunt-build-control via git://github.com/daftmonk/grunt-build-control.git
npm verb tryClone git-github-com-daftmonk-grunt-build-control-git-c52534ab19c061b0254eee1cf44fefb2 not in flight; caching
npm info git [ 'config', '--get', 'remote.origin.url' ]
npm sill validateExistingRemote daftmonk/grunt-build-control remote.origin.url: git://github.com/daftmonk/grunt-build-control.git
npm verb validateExistingRemote daftmonk/grunt-build-control is updating existing cached remote C:\Users\Busche\AppData\Roaming\npm-cache\_git-remotes\git-github-com-daftmonk-grunt-build-control-git-c52534ab19c061b0254eee1cf44fefb2
npm info git [ 'fetch', '-a', 'origin' ]
npm verb updateRemote git fetch -a origin (git://github.com/daftmonk/grunt-build-control.git)
npm verb setPermissions daftmonk/grunt-build-control skipping chownr on Windows
npm verb resolveHead daftmonk/grunt-build-control original treeish: master
npm info git [ 'rev-list', '-n1', 'master' ]
npm sill resolveHead daftmonk/grunt-build-control resolved treeish: 3d03ebbe49f8f963ef43c50af1084a15f56611fa
npm verb resolveHead daftmonk/grunt-build-control resolved Git URL: git://github.com/daftmonk/grunt-build-control.git#3d03ebbe49f8f963ef43c50af1084a15f56611fa
npm sill resolveHead Git working directory: C:\Users\Busche\AppData\Local\Temp\npm-6732-b7d61a39\C:\Users\Busche\AppData\Local\Temp\npm-6732-b7d61a39\git-cache-dbe6e56ecde934a424fbe457fbc2de6d\3d03ebbe49f8f963ef43c50af1084a15f56611fa
```

**Comment by dseelinger** [comment]
I get the same error attempting to install gulp 4

npm install --save-dev -dd git://github.com/gulpjs/gulp.git#4.0
npm info it worked if it ends with ok
npm verb cli [ 'node',
npm verb cli   'C:\\Users\\doseelin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'install',
npm verb cli   '--save-dev',
npm verb cli   '-dd',
npm verb cli   'git://github.com/gulpjs/gulp.git#4.0' ]
npm info using npm@3.0.0
npm info using node@v0.12.4
npm verb cache add spec git://github.com/gulpjs/gulp.git#4.0
npm verb addRemoteGit caching git://github.com/gulpjs/gulp.git#4.0
npm verb addRemoteGit git://github.com/gulpjs/gulp.git#4.0 is a repository hosted by github
npm verb tryClone git-github-com-gulpjs-gulp-git-4-0-9508ac6e73bc4e2dd3065e6cd9e6f094 not in flight; caching
npm info git [ 'config', '--get', 'remote.origin.url' ]
npm verb validateExistingRemote git://github.com/gulpjs/gulp.git#4.0 is updating existing cached remote C:\Users\doseelin\AppData\Roaming\npm-cache\_git-remotes\git-github-com-gulpjs-gulp-git-4-0-9508ac6e73bc4e2dd3065e6cd9e6f094
npm info git [ 'fetch', '-a', 'origin' ]
npm verb updateRemote git fetch -a origin (git://github.com/gulpjs/gulp.git)
npm verb setPermissions git://github.com/gulpjs/gulp.git#4.0 skipping chownr on Windows
npm verb resolveHead git://github.com/gulpjs/gulp.git#4.0 original treeish: 4.0
npm info git [ 'rev-list', '-n1', '4.0' ]
npm verb resolveHead git://github.com/gulpjs/gulp.git#4.0 resolved Git URL: git://github.com/gulpjs/gulp.git#aaed69d1fd73750227e803035b2a75d0f49e7de0
loadRequestedDeps → resol ▌ ╢███████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟

**Comment by bdukes** [comment]
I'm also seeing hangs on windows 8.1 when resolving git URL dependencies with npm 3.   Typically I get silly output like http://pastebin.com/1f1biQ7A, but one recent time it failed (because it couldn't resolve github.com, apparently), so I got a proper `npm-debug.log` file (http://pastebin.com/y2iB8KME) which perhaps has other helpful information.

**Comment by dpogue** [comment]
This seems to be happening because it's duplicating part of the path when trying to clone.

I see if trying to install into `C:\Users\name\AppData\Local\Temp\npm-{numbers}\C:\Users\name\AppData\Local\Temp\npm-{numbers}\git-cache-{numbers}\...`

**Comment by iarna** [comment]
This has landed in master as https://github.com/npm/npm/commit/0030ade56d32aaec948b0c6310718974210a8c58 and will be in the 3.1.0 release.

**Comment by brentonhouse** [comment]
Awesome! Thank you @iarna !!    Is there a way of using "next" tag when installing to get that functionality earlier?

**Comment by iarna** [comment]
Nope, the next tag gets cut Thursday evening. You _can_ just work from the branch directly by installing `npm/npm` which will fetch it from github instead of the registry. But be aware that for reasons™, you can only do this with an existing npm@3. (Attempting with `npm@2` will tell you to use `npm@3` to install it. 😜)

**Comment by dsebastien** [comment]
Thanks @iarna unfortunately npm install -g npm/npm also hangs for me ;-). Do you think simply taking a zip of the repo on github will do it?

**Comment by dsebastien** [comment]
Well it seems to be working, cool! Thanks for the fix! :)

**Comment by euprogramador** [comment]
De nada

**Comment by flieks** [comment]
for me `npm dedupe` (npm >3) hangs (taking lots of cpu/ram).
What can i do ?

**Comment by pmckelvy1** [comment]
@flieks did you happen to solve the issue you were having w/ "npm dedupe"? I think I'm experiencing something similar.

**Comment by nikgupta1231** [comment]
loadRequestedDeps: sill install loadAllDepsIntoIdealTree 

its not finishing what should i do?

**Comment by menezee** [comment]
@nikgupta1231 https://github.com/npm/npm/issues/17228#issuecomment-318581491 maybe will fix your issue

**Comment by msieurtoph** [comment]
I was running for months into this issue ...
I tried to run npm cache clean, delete .staging, node_modules and even the npm-session folders listed in the npm config ... It never worked systematically

And I finally find out, looking at the resources monitor (I am on Win7) : 

I am behind an enterprise proxy and I have to use cntlm to make npm access internet.
And I saw that cntlm opened more and more threads while install progressed.
And I noticed that install hanged when cntlm process went over 1000 threads ... 

Then I killed and restart cntlm ... and npm unhanged few seconds after.

It seems to always work for me ... so here my conclusion : 
If npm hangs without any explicit error message, that means it is probably missing some ressources (threads, memory, ...). Try to resolve this issue and the install should unhang...

Hope that will help ...

**Comment by damienthiery** [comment]
> If npm hangs without any explicit error message, that means it is probably missing some ressources (threads, memory, ...). Try to resolve this issue and the install should unhang...
Hope that will help ...

Thanks you ! I was facing the same issue with cntlm and I confirm that restarting the service brings back npm working correctly
