### ISSUE TITLE
install failing with EPERM error on windows 10

### ISSUE THREAD

**Issue by tivac** [npm/npm#8687]
npm@3.0.0

I've tried with both a normal cmd prompt and an Administrator prompt, no difference. Also tried on two different machines running Windows 10 build 10130.

```
c:\Users\Patrick\Desktop\npm3test>npm i async
npm WARN checkPermissions Missing write access to c:\Users\Patrick\Desktop\npm3test
c:\Users\Patrick\Desktop\npm3test
└── async@1.2.1

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\iojs\\node.exe" "C:\\Users\\Patrick\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "
i" "async"
npm ERR! node v2.0.0
npm ERR! npm  v3.0.0
npm ERR! path c:\Users\Patrick\Desktop\npm3test
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall access

npm ERR! Error: EPERM: operation not permitted, access 'c:\Users\Patrick\Desktop\npm3test'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, access 'c:\Users\Patrick\Desktop\npm3test']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'access',
npm ERR!   path: 'c:\\Users\\Patrick\\Desktop\\npm3test' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Users\Patrick\Desktop\npm3test\npm-debug.log
```

[`npm-debug.log` output](https://gist.github.com/tivac/3c585b8ef6bea25d59f8)

**Comment by iarna** [comment]
@tivac: I'm curious if you get the same error with a more recent io.js (the current release is `2.3.1`). As of 0.12.0 and w/ all io.js releases we use the new [fs.access](https://iojs.org/api/fs.html#fs_fs_access_path_mode_callback) api– I don't *know* that it's been buggy in some io.js releases in Windows 10, but I could believe it.

**Comment by tivac** [comment]
Just noticed I was behind, updated to the Win64 build of io@2.3.1 and it's working. Sorry for the false alarm!

**Comment by iarna** [comment]
Well, good to know that's out there lurking anyway, so we can point others in the right direction. 😄

**Comment by tivac** [comment]
Other computer that was failing is still on io@1.5.1, so seems like it was a bug in there for a while.
