### ISSUE TITLE
Flat dependencies

### ISSUE THREAD

**Issue by gobwas** [npm/npm#8693]
Hi! 

I've just read your Changelog.md, and very excited of the **flat, flat, flat** part. Is it will be a flag to force npm to throw an error, when not all module could be flatten? 

Any way, it will be a useful thing for browser projects =)

Thanks!

**Comment by iarna** [comment]
@gobwas No, there's no flag to do that. We do see the need for "never nested deps" but we probably won't be addressing it by doing that to `node_modules`.  Over the summer and this autumn I would expect to see a solution for that sort of thing come out of us.

In the mean time, you'll need to keep doing that sort of flattening with things like `browserify`.
