### ISSUE TITLE
npm 3: got "abort trap 6" :-(

### ISSUE THREAD

**Issue by ljharb** [npm/npm#8695]
I installed npm v3 on io.js v2.3.1, fresh-faced and excited, like a puppy greeting somebody that's been gone for 30 seconds, which is like FOREVER. I `cd`'d into https://github.com/es-shims/es7-shim, `rm -rf node_modules`, and ran `npm install`, waiting for the glorious flat tree to appear.

This is the output I received:
```shell
 npm install
loadDevDep:replace → get  ▀ ╢███████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
Assertion failed: (ctx->mode_ != NONE && "already finalized"), function Write, file ../src/node_zlib.cc, line 122.
Abort trap: 6
```

Installing 3 or 4 of the deps one at a time allowed `npm install` to work, altho I still had to manually install a few deps after that.

Puppy sad.

**Comment by ljharb** [comment]
Also my .npmrc only has an auth token, fwiw.

**Comment by clloyd** [comment]
I'm seeing the same error, but specifically when installing 'hapi'. 

@ljharb I kept getting different package names, until I ran `npm i -dd` and it consistently failed on hapi

**Comment by othiym23** [comment]
`hapi` and a few other aggressive users of shrinkwrap files trigger a bug in `npm@3.0.0`. @iarna has started work on a fix that will probably be included in next week's beta release. Maybe @ljharb's issue is the same? Maybe maybe he can test the fix once @iarna lands it and confirm that it's gone??

**Comment by ljharb** [comment]
@othiym23 I'll be happy to do so :-) @iarna, please ping me anywhere when you're ready and I'll test; the issue is very reproducible for me.

**Comment by iarna** [comment]
Yeah, this is very reproducible across the board.

Yup, this is definitely the same issue and will be in next weeks release. I've already prepared a patch... lemme just push that branch up somewhere...

**Comment by izaakschroeder** [comment]
+1

**Comment by mikemaccana** [comment]
Hrm, ran `sudo npm install -g npm@3.0-latest` and still got this error. Has the fix been published?
