### ISSUE TITLE
did `search` and got "ERR! registry error parsing json"

### ISSUE THREAD

**Issue by M2vH** [npm/npm#8700]
I got this error after `npm search mango` for the second time

	npm ERR! registry error parsing json
	
See debug-log [here](#debug).

From Install to Error I did exactly what is described in Step 1 - 4 at end of post.

- [Step 1](#StepOne) Install node
- [Step 2](#StepTwo) Install nw
- [Step 3](#StepThree) Search mango
- [Step 4](#StepFour) Search Mango

#### npm-<a name="debug"></a>debug.log

	0 info it worked if it ends with ok
	1 verbose cli [ 'node', '/usr/local/bin/npm', 'search', 'mango' ]
	2 info using npm@2.7.3
	3 info using node@v0.12.1
	4 verbose node symlink /usr/local/bin/node
	5 silly mapToRegistry name -/all
	6 silly mapToRegistry using default registry
	7 silly mapToRegistry registry https://registry.npmjs.org/
	8 silly mapToRegistry uri https://registry.npmjs.org/-/all
	9 info updateIndex /Users/marco/.npm/registry.npmjs.org/-/all/.cache.json
	10 verbose request uri https://registry.npmjs.org/-/all/since?stale=update_after&startkey=1435317605576
	11 verbose request no auth needed
	12 info attempt registry request try #1 at 14:27:38
	13 verbose request id 502444cd025c0f21
	14 http request GET https://registry.npmjs.org/-/all/since?stale=update_after&startkey=1435317605576
	15 http 503 https://registry.npmjs.org/-/all/since?stale=update_after&startkey=1435317605576
	16 verbose bad json <?xml version="1.0" encoding="utf-8"?>
	16 verbose bad json <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	16 verbose bad json  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
	16 verbose bad json <html>
	16 verbose bad json   <head>
	16 verbose bad json     <title>503 backend read error</title>
	16 verbose bad json   </head>
	16 verbose bad json   <body>
	16 verbose bad json     <h1>Error 503 backend read error</h1>
	16 verbose bad json     <p>backend read error</p>
	16 verbose bad json     <h3>Guru Mediation:</h3>
	16 verbose bad json     <p>Details: cache-fra1233-FRA 1435321674 1144798079</p>
	16 verbose bad json     <hr>
	16 verbose bad json     <p>Varnish cache server</p>
	16 verbose bad json   </body>
	16 verbose bad json </html>
	17 error registry error parsing json
	18 info retry will retry, error on last attempt: SyntaxError: Unexpected token <
	18 info retry
	18 info retry <?xml version="1.0" encoding="utf-8"?>
	18 info retry <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	18 info retry  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
	18 info retry <html>
	18 info retry   <head>
	18 info retry     <title>503 backend read error</title>
	18 info retry   </head>
	18 info retry   <body>
	18 info retry     <h1>Error 503 backend read error</h1>
	18 info retry     <p>backend read error</p>
	18 info retry     <h3>Guru Mediation:</h3>
	18 info retry     <p>Details: cache-fra1233-FRA 1435321674 1144798079</p>
	18 info retry     <hr>
	18 info retry     <p>Varnish cache server</p>
	18 info retry   </body>
	18 info retry </html>
	19 info attempt registry request try #2 at 14:28:04
	20 http request GET https://registry.npmjs.org/-/all/since?stale=update_after&startkey=1435317605576
	21 http 503 https://registry.npmjs.org/-/all/since?stale=update_after&startkey=1435317605576
	22 verbose bad json <?xml version="1.0" encoding="utf-8"?>
	22 verbose bad json <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	22 verbose bad json  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
	22 verbose bad json <html>
	22 verbose bad json   <head>
	22 verbose bad json     <title>503 backend read error</title>
	22 verbose bad json   </head>
	22 verbose bad json   <body>
	22 verbose bad json     <h1>Error 503 backend read error</h1>
	22 verbose bad json     <p>backend read error</p>
	22 verbose bad json     <h3>Guru Mediation:</h3>
	22 verbose bad json     <p>Details: cache-fra1233-FRA 1435321699 1144969608</p>
	22 verbose bad json     <hr>
	22 verbose bad json     <p>Varnish cache server</p>
	22 verbose bad json   </body>
	22 verbose bad json </html>
	23 error registry error parsing json
	24 info retry will retry, error on last attempt: SyntaxError: Unexpected token <
	24 info retry
	24 info retry <?xml version="1.0" encoding="utf-8"?>
	24 info retry <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	24 info retry  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
	24 info retry <html>
	24 info retry   <head>
	24 info retry     <title>503 backend read error</title>
	24 info retry   </head>
	24 info retry   <body>
	24 info retry     <h1>Error 503 backend read error</h1>
	24 info retry     <p>backend read error</p>
	24 info retry     <h3>Guru Mediation:</h3>
	24 info retry     <p>Details: cache-fra1233-FRA 1435321699 1144969608</p>
	24 info retry     <hr>
	24 info retry     <p>Varnish cache server</p>
	24 info retry   </body>
	24 info retry </html>
	25 info attempt registry request try #3 at 14:29:19
	26 http request GET https://registry.npmjs.org/-/all/since?stale=update_after&startkey=1435317605576
	27 http 503 https://registry.npmjs.org/-/all/since?stale=update_after&startkey=1435317605576
	28 verbose bad json <?xml version="1.0" encoding="utf-8"?>
	28 verbose bad json <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	28 verbose bad json  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
	28 verbose bad json <html>
	28 verbose bad json   <head>
	28 verbose bad json     <title>503 backend read error</title>
	28 verbose bad json   </head>
	28 verbose bad json   <body>
	28 verbose bad json     <h1>Error 503 backend read error</h1>
	28 verbose bad json     <p>backend read error</p>
	28 verbose bad json     <h3>Guru Mediation:</h3>
	28 verbose bad json     <p>Details: cache-fra1233-FRA 1435321775 1145476563</p>
	28 verbose bad json     <hr>
	28 verbose bad json     <p>Varnish cache server</p>
	28 verbose bad json   </body>
	28 verbose bad json </html>
	29 error registry error parsing json
	30 verbose headers { server: 'Varnish',
	30 verbose headers   'retry-after': '0',
	30 verbose headers   'content-type': 'text/html; charset=utf-8',
	30 verbose headers   'content-length': '448',
	30 verbose headers   'accept-ranges': 'bytes',
	30 verbose headers   date: 'Fri, 26 Jun 2015 12:29:35 GMT',
	30 verbose headers   via: '1.1 varnish',
	30 verbose headers   connection: 'keep-alive',
	30 verbose headers   'x-served-by': 'cache-fra1223-FRA',
	30 verbose headers   'x-cache': 'MISS',
	30 verbose headers   'x-cache-hits': '0',
	30 verbose headers   'x-timer': 'S1435321759.789354,VS0,VE15274' }
	31 verbose stack SyntaxError: Unexpected token <
	31 verbose stack
	31 verbose stack <?xml version="1.0" encoding="utf-8"?>
	31 verbose stack <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	31 verbose stack  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
	31 verbose stack <html>
	31 verbose stack   <head>
	31 verbose stack     <title>503 backend read error</title>
	31 verbose stack   </head>
	31 verbose stack   <body>
	31 verbose stack     <h1>Error 503 backend read error</h1>
	31 verbose stack     <p>backend read error</p>
	31 verbose stack     <h3>Guru Mediation:</h3>
	31 verbose stack     <p>Details: cache-fra1233-FRA 1435321775 1145476563</p>
	31 verbose stack     <hr>
	31 verbose stack     <p>Varnish cache server</p>
	31 verbose stack   </body>
	31 verbose stack </html>
	31 verbose stack
	31 verbose stack     at Object.parse (native)
	31 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:205:23)
	31 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:178:14)
	31 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:344:22)
	31 verbose stack     at Request.emit (events.js:110:17)
	31 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1239:14)
	31 verbose stack     at Request.emit (events.js:129:20)
	31 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1187:12)
	31 verbose stack     at IncomingMessage.emit (events.js:129:20)
	31 verbose stack     at _stream_readable.js:908:16
	32 verbose cwd /Users/marco/Documents/m2vh/psycho-dad/JavaScriptApps
	33 error Darwin 10.8.0
	34 error argv "node" "/usr/local/bin/npm" "search" "mango"
	35 error node v0.12.1
	36 error npm  v2.7.3
	37 error Unexpected token <
	37 error
	37 error <?xml version="1.0" encoding="utf-8"?>
	37 error <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	37 error  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
	37 error <html>
	37 error   <head>
	37 error     <title>503 backend read error</title>
	37 error   </head>
	37 error   <body>
	37 error     <h1>Error 503 backend read error</h1>
	37 error     <p>backend read error</p>
	37 error     <h3>Guru Mediation:</h3>
	37 error     <p>Details: cache-fra1233-FRA 1435321775 1145476563</p>
	37 error     <hr>
	37 error     <p>Varnish cache server</p>
	37 error   </body>
	37 error </html>
	38 error If you need help, you may report this error at:
	38 error     <https://github.com/npm/npm/issues>
	39 verbose exit [ 1, true ]
[see debug.log](#debug)

#### <a name="StepOne"></a>Step 1 - installing node
	brew install node --with-openssl

	==> Downloading https://nodejs.org/dist/v0.12.1/node-v0.12.1.tar.gz
	######################################################################## 100,0%
	==> ./configure --prefix=/usr/local/Cellar/node/0.12.1 --without-npm --shared-op
	==> make install
	==> Downloading https://registry.npmjs.org/npm/-/npm-2.7.3.tgz
	######################################################################## 100,0%
	==> ./configure --prefix=/usr/local/Cellar/node/0.12.1/libexec/npm
	==> make install
	==> Caveats
	If you update npm itself, do NOT use the npm update command.
	The upstream-recommended way to update npm is:
	  npm install -g npm@latest

	Bash completion has been installed to:
	  /usr/local/etc/bash_completion.d
	==> Summary
	/usr/local/Cellar/node/0.12.1: 2240 files,  25M, built in 20.3 minutes
[see debug.log](#debug)

#### <a name="StepTwo"></a>Step 2 - install nw
	sudo npm install -g nw
	Passwort: 
	/usr/local/bin/nw -> /usr/local/lib/node_modules/nw/bin/nw

	> nw@0.12.2 postinstall /usr/local/lib/node_modules/nw
	> node scripts/install.js
[see debug.log](#debug)

#### <a name="StepThree"></a>Step 3 - search mango
	npm search mango

	npm WARN Building the local index for the first time, please be patient
[see debug.log](#debug)

#### <a name="StepFour"></a>Step 4 - search Mango
	npm search Mango

	npm ERR! registry error parsing json
	npm ERR! registry error parsing json
	npm ERR! registry error parsing json
	npm ERR! Darwin 10.8.0
	npm ERR! argv "node" "/usr/local/bin/npm" "search" "mango"
	npm ERR! node v0.12.1
	npm ERR! npm  v2.7.3

	npm ERR! Unexpected token <
	npm ERR! 
	npm ERR! <?xml version="1.0" encoding="utf-8"?>
	npm ERR! <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	npm ERR!  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
	npm ERR! <html>
	npm ERR!   <head>
	npm ERR!     <title>503 backend read error</title>
	npm ERR!   </head>
	npm ERR!   <body>
	npm ERR!     <h1>Error 503 backend read error</h1>
	npm ERR!     <p>backend read error</p>
	npm ERR!     <h3>Guru Mediation:</h3>
	npm ERR!     <p>Details: cache-fra1233-FRA 1435321775 1145476563</p>
	npm ERR!     <hr>
	npm ERR!     <p>Varnish cache server</p>
	npm ERR!   </body>
	npm ERR! </html>
	npm ERR! 
	npm ERR! 
	npm ERR! If you need help, you may report this error at:
	npm ERR!     <https://github.com/npm/npm/issues>

	npm ERR! Please include the following file with any support request:
	npm ERR!     /Users/marco/Documents/m2vh/psycho-dad/JavaScriptApps/npm-debug.log
[see debug.log](#debug)

**Comment by othiym23** [comment]
This is an issue that was resolved mid-2015 (probably shortly after this was filed) by putting the registries supporting search queries on dedicated hardware. Now the problem is much more likely to be on the client side, and you can peruse #6016 for the details. Thanks for filing this!
