### ISSUE TITLE
Error installing any module in AppVeyor environment with npm 2.12.0 and 3.0.0

### ISSUE THREAD

**Issue by FeodorFitsner** [npm/npm#8702]
Hello,

Many projects in AppVeyor environment are installing the latest npm 2.x on *every build* with the following command:

    npm -g install npm@2

As of this morning (June 26) we started getting the following error in AppVeyor environment while installing any npm module with npm 2.12.0, 2.12.1 and 3.0.0:

    npm ERR! Object #<process> has no method 'getuid'

another form of this error could be:

    npm ERR! process.getuid is not a function

I reproduced this error here with `npm-debug.log` shown: https://ci.appveyor.com/project/FeodorFitsner/av-build-problem/build/1.0.28

Relevant part from `npm-debug.log`:

    verbose type undefined_method
    26 verbose stack TypeError: Object #<process> has no method 'getuid'
    26 verbose stack     at calculateOwner (C:\Users\appveyor\AppData\Roaming\npm\node_modules\npm\lib\utils\correct-mkdir.js:37:24)
    26 verbose stack     at C:\Users\appveyor\AppData\Roaming\npm\node_modules\npm\lib\utils\correct-mkdir.js:23:22
    26 verbose stack     at Object.oncomplete (evalmachine.<anonymous>:108:15)

The error is [not reproducible on npm 2.11.3](https://ci.appveyor.com/project/FeodorFitsner/av-build-problem/build/1.0.24).

Could you please take a look?

**Comment by FeodorFitsner** [comment]
What's interesting is that according to [this page](https://github.com/npm/npm/tags) npm 2.12.0 was released 7 days ago, but it started to be downloaded only today (around 7 hours ago).

**Comment by FeodorFitsner** [comment]
OK, the issue confirmed by @marcominetti: https://github.com/npm/npm/commit/85d1a53d7b5e0fc04823187e522ae3711ede61fa (comment to `lib/utils/correct-mkdir.js`) - looks like it might be our case.

@othiym23 - do you have an ETA for a fix?

**Comment by itajaja** [comment]
sweet. Waiting for this :+1:

**Comment by othiym23** [comment]
@FeodorFitsner: Can you give me a stack trace from `npm@2.12.1` for this error? https://github.com/npm/npm/commit/7e5da238ee869201fdb9027c27b79b0f76b440a8 is the fix for this issue added to that version (which is currently `npm@next`, following npm's release-train release process). If we missed something, we'll fix it immediately, but I'm not sure what I could have overlooked.

**Comment by FeodorFitsner** [comment]
With `npm -g install npm@2.12.1` it works like a charm!

It's `npm -g install npm@2` pulls `2.12.0` which is broken, not the latest `2.12.1`.

Thanks for looking into that! When 2.12.1 is planned for release?

**Comment by blainekasten** [comment]
+1, causing me a hiccup installing jest

**Comment by othiym23** [comment]
`npm@2.12.1` will be the next stable version of `npm@2`, released next Thursday (all npm releases happen on Thursday). If 2.12.1 is working for you, there's no reason to not keep using it, and it can easily be installed via `npm install -g npm@next`, so uh do that. ;)

**Comment by FeodorFitsner** [comment]
Cool, thanks for the update!

**Comment by blainekasten** [comment]
@othiym23, I can't even run `npm install -g npm@next` right now due to this issue. Is there a safe way to update to that while being on `npm@2.12.0` ?

**Comment by othiym23** [comment]
@blainekasten You're going to need to roll back to a known good version, probably via using a Node or io.js installer for Windows. That's the fastest and easiest way, at any rate.

**Comment by spirau** [comment]
To install the 2.12.1, first clear the cache : <code>npm cache clear</code>

**Comment by iarna** [comment]
I'm closing this as resolved.

**Comment by stefanpenner** [comment]
should i see see failures https://ci.appveyor.com/project/embercli/ember-cli/build/3516 ?

**Comment by iarna** [comment]
@stefanpenner Not _now_– `2.12.1` is `latest` now, which provides the fix for that. Your log appears to have been from a build run about an hour and a half before the release was completed.
