### ISSUE TITLE
Disable spinner and status bar in npm 3

### ISSUE THREAD

**Issue by yunong** [npm/npm#8704]
In npm version 2, I could disable the spinner by `#npm set spin=false`. This no longer works in 3. Is it possible to disable the status bar and spinner in 3? If not could you please make this configurable?

**Comment by iarna** [comment]
This probably should have an option flag.

You can work around this by redirecting stderr to something that's not a terminal. For instance (on mac/linux), if you run:

```
npm install xyz 2>&1 | cat
```

It won't show the progress bar as the pipe to `cat` isn't a terminal, but you'll still see the output because `cat` prints it for you.

**Comment by nikolai-b** [comment]
Thanks for the advice, with npm v.2 I was using:
`npm install --no-spin`
just to be clear on what the flag was called.

**Comment by iarna** [comment]
Happily this is now live in `npm@3.2.0`!

**Comment by saper** [comment]
The progress bar should also be disabled if doing some form of verbose of silly loggin. I am using `script(1)` to record `npm install -ddd node-sass` and it's a huge mess...

**Comment by robey** [comment]
Just for people who end up here trying to turn off the spinner, it's this (undocumented) flag, not the one mentioned above:

```
npm i --no-progress
```

**Comment by othiym23** [comment]
[It's documented](https://docs.npmjs.com/misc/config#progress), but information architecture is hard, and maybe that's not where people are expecting that documentation to be. :grimacing:

**Comment by shellscape** [comment]
@othiym23 is there any way to disable it via .npmrc? general consensus in our shop is that it's not pleasant to view.

**Comment by anija** [comment]
Just add the word "SPIN" it would help :) We search for "spin" to disable what we previus disabled with "--no-spin".

**Comment by aaron-em** [comment]
For those looking to deal with this by the same (config-based) approach as NPM 2.x,

    npm3 config set progress false

seems to work for me.
