### ISSUE TITLE
Maximum call stack size exceeded when trying to publish package

### ISSUE THREAD

**Issue by avidas** [npm/npm#8706]
Hi,

I am trying to publish the paypal-rest-sdk module on npm and running into a "Maximum call stack size exceeded" when trying to publish the package. I have been publishing this package for a while without much issues. I doubt that the size of package has increased considerably between the last release and this. This is the release that is getting published https://github.com/paypal/PayPal-node-SDK/releases/tag/v1.6.0 . I have recently upgraded to npm3.

------------the error----------

npm ERR! argv "node" "/usr/local/bin/npm" "publish"
npm ERR! node v0.12.2
npm ERR! npm  v3.0.0

npm ERR! Maximum call stack size exceeded
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:

-------------- contents of npm_debug.log --------------

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'publish' ]
2 info using npm@3.0.0
3 info using node@v0.12.2
4 verbose node symlink /usr/local/bin/node
5 verbose publish [ '.' ]
6 silly cache add args [ '.', null ]
7 verbose cache add spec .
8 silly cache add parsed spec { raw: '.',
8 silly cache add   scope: null,
8 silly cache add   name: null,
8 silly cache add   rawSpec: '.',
8 silly cache add   spec: '/Users/anadas/src/javascript/node_projects/rest-api-sdk-nodejs',
8 silly cache add   type: 'directory' }
9 verbose addLocalDirectory /Users/anadas/.npm/paypal-rest-sdk/1.6.0/package.tgz not in flight; packing
10 info prepublish paypal-rest-sdk@1.6.0
11 verbose tar pack [ '/Users/anadas/.npm/paypal-rest-sdk/1.6.0/package.tgz',
11 verbose tar pack   '/Users/anadas/src/javascript/node_projects/rest-api-sdk-nodejs' ]
12 verbose tarball /Users/anadas/.npm/paypal-rest-sdk/1.6.0/package.tgz
13 verbose folder /Users/anadas/src/javascript/node_projects/rest-api-sdk-nodejs
14 verbose stack RangeError: Maximum call stack size exceeded
14 verbose stack     at String.split (native)
14 verbose stack     at encodeField (/usr/local/lib/node_modules/npm/node_modules/tar/lib/extended-header-writer.js:149:15)
14 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/tar/lib/extended-header-writer.js:139:32
14 verbose stack     at Array.forEach (native)
14 verbose stack     at encodeFields (/usr/local/lib/node_modules/npm/node_modules/tar/lib/extended-header-writer.js:98:23)
14 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/tar/lib/extended-header-writer.js:137:32
14 verbose stack     at Array.forEach (native)
14 verbose stack     at encodeFields (/usr/local/lib/node_modules/npm/node_modules/tar/lib/extended-header-writer.js:98:23)
14 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/tar/lib/extended-header-writer.js:137:32
14 verbose stack     at Array.forEach (native)
15 verbose cwd /Users/anadas/src/javascript/node_projects/rest-api-sdk-nodejs
16 error Darwin 14.3.0
17 error argv "node" "/usr/local/bin/npm" "publish"
18 error node v0.12.2
19 error npm  v3.0.0
20 error Maximum call stack size exceeded
21 error If you need help, you may report this error at:
21 error     <https://github.com/npm/npm/issues>
22 verbose exit [ 1, true ]

**Comment by avidas** [comment]
Any updates on this one or a workaround for now?

**Comment by aredridel** [comment]
My workaround: install npm 2.12 in a different place. `npm install -g --prefix=$HOME/oldnpm npm`

Then you can run the old npm to publish: `~/oldnpm/bin/npm publish`.

Not a fun workaround, but perfectly workable for me.

When the bug is resolved, wipe out `~/oldnpm` and it all vanishes.

**Comment by avidas** [comment]
:+1: Thanks @aredridel , this workaround works for me as well.

**Comment by iarna** [comment]
This isn't gonna be a single-milestone project, but I'd like to start on it this week.

**Comment by iarna** [comment]
(Work has begun in https://github.com/npm/npm/tree/iarna/safe and will continue there out of band till I'm ready to merge.)

**Comment by iarna** [comment]
Testing with the safe branch didn't get us a stack trace, but does imply this is happening in fstream.

**Comment by avidas** [comment]
Appreciate the updates!

**Comment by iarna** [comment]
Closing in preference to https://github.com/npm/npm/issues/9224
