### ISSUE TITLE
Object #<process> has no method 'getuid'

### ISSUE THREAD

**Issue by Fabii23** [npm/npm#8710]
I get the following error when I try to update npm or install any module

npm ERR! node v0.10.22
npm ERR! npm  v2.12.0

npm ERR! Object #<process> has no method 'getuid'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by Fabii23** [comment]
I just reinstalled node and everything is good to go.

**Comment by othiym23** [comment]
@Fabii23 there was a bug in `npm@2.12.0` that caused the exact behavior you were seeing. That's terrible! Fortunately, it was fixed in `npm@2.12.1`, which is currently `npm@next`. So if you upgrade to `npm@next`, you can have the latest `npm@2` *and* still have everything working on Windows!

**Comment by Fabii23** [comment]
@othiym23  Lol I got fed and just ended up reinstalling everything . Thanks for the reply though.

**Comment by gabmontes** [comment]
@othiym23 you may not even be able to upgrade to `npm@next` after `npm@2.12.0` since the install/upgrade functionality is broken. LOL

I had to remove `npm` globally and then install `npm@2.10.0` again. Now everything goes fine.
