### ISSUE TITLE
npm install esprima-fb broken

### ISSUE THREAD

**Issue by heavyk** [npm/npm#8711]
appears to have something to do with the `*` version combined with a bunch of non-semver versions. (cause `latest` works fine)

```
$ npm i esprima-fb
npm ERR! Darwin 13.4.0
npm ERR! argv "/opt/boxen/nodenv/versions/iojs/bin/iojs" "/opt/boxen/nodenv/versions/iojs/bin/npm" "i" "esprima-fb"
npm ERR! node v2.3.1
npm ERR! npm  v2.12.0
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: esprima-fb@'*'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["1001.1001.1000-dev-harmony-fb","1001.1001.1001-dev-harmony-fb","1001.1001.2000-dev-harmony-fb","2001.1001.2000-dev-harmony-fb","2001.1001.0-dev-harmony-fb","3001.1.0-dev-harmony-fb","4001.1.0-dev-harmony-fb","4001.1001.0-dev-harmony-fb","4001.3001.0-dev-harmony-fb","5001.1.0-dev-harmony-fb","6001.1.0-dev-harmony-fb","6001.1001.0-dev-harmony-fb","7001.1.0-dev-harmony-fb","8001.1.0-dev-harmony-fb","8001.1001.0-dev-harmony-fb","8001.2001.0-dev-harmony-fb","9001.1.0-dev-harmony-fb","10001.1.0-dev-harmony-fb","11001.1.0-dev-harmony-fb","12001.1.0-dev-harmony-fb","13001.1.0-dev-harmony-fb","13001.1001.0-dev-harmony-fb","14001.1.0-dev-harmony-fb","15001.1.0-dev-harmony-fb"]
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'module-dependencies'
npm ERR! notarget
```

**Comment by rosen-vladimirov** [comment]
Hi,
Is this expected behavior? It looks like we are unable to install any npm package, which has dash in its name. I'm able to install only packages with strict versions (1.0.0, 1.0.1, etc.), but versions like 1.0.0-211 is not installed and ETARGET error is raised. I've tried npm 2.11.2, 2.11.3, 2.12.0 and each of them is failing to install packages with dash in the name.  I've also tried 2.11.0 and 2.11.1 and all of the packages are installed correctly. 
Can someone confirm what and why had been changed?

**Comment by KenanY** [comment]
According to SemVer, versions with hyphens are defined as pre-releases, and as of `npm@2` pre-releases are no longer installed unless you explicitly ask for one.

**Comment by heavyk** [comment]
right. the `latest` tag should point to the latest pre-release. so, I would assume that the `*` tag should do the same. if I change the `*` to `latest` I notice it works, however I still think there's a bug somewhere.

**Comment by KenanY** [comment]
`*` is not the same as `latest` hence the different behaviors :)

**Comment by heavyk** [comment]
I see... what's the difference?

I assumed they were the same, because to `*` sounds like "any version possible"

so you're saying that `*` doesn't include any pre-release versions?

**Comment by KenanY** [comment]
@heavyk `latest` points to whatever version is [tagged](https://docs.npmjs.com/cli/dist-tag) as `latest`. `*` is any version ([besides pre-realeases](https://docs.npmjs.com/misc/semver#prerelease-tags) as of `npm@2`).

**Comment by heavyk** [comment]
ok. would it be possible to, if the package does not have any non-pre-release versions, print a WARN or a DEPRECATED or something, and still install any version?

I say this because I understand all the stuff says in the readme and I agree with it. yet, if a module does not have any release versions, it should still install something... for example, `npm i module-dependencies` will always fail and the error message doesn't provide any feedback to what is going on.

**Comment by iarna** [comment]
@heavyk: That seems like a reasonable interpretation to me. How does this logic sound?

1. If your specifier is '*'
2. And there ARE published versions
3. And NONE of them match
4.Then use the one tagged as `latest` instead (maybe w/ a warning)

**Comment by heavyk** [comment]
I think that sounds good, yeah :)

**Comment by rosen-vladimirov** [comment]
Interesting suggestion and explanation, but can you please explain me the following situation:
I've published several releases of one package - each of them has "-" in the version, for example 1.0.0-013, 1.0.1-124, etc.
Until 2.11.2, I was able to install the package with `npm install -g <package_name>`, however with npm 2.11.2 this is failing with ETARGET.
@KenanY , you've said that with npm@2.x I'm unable to install any prerelease, except I ask for it, but that's not the behavior I've seen so far. The first version that has this behavior is 2.11.2, which was released a lot of time after 2.0.0 version. So where's the bug - all versions before 2.11.2 are not working correctly as they are installing prerelease versions or version 2.11.2 and later ones have another bug.

By the way, the error message is really confusing and does not give you any idea what's wrong with the package. `No compatible version found: esprima-fb@'*'` looks like you've not found any version (based on the concept that * means any).

**Comment by KenanY** [comment]
@rosen-vladimirov Hmm, I don't see anything in the `2.11.2` changelog that touched this behavior. I should do some testing when I find time....

**Comment by iamstarkov** [comment]
isnt it an esprima-fb’s problem?
