### ISSUE TITLE
npm 3 global installs ignoring .npmrc prefix setting

### ISSUE THREAD

**Issue by busches** [npm/npm#8717]
I have `npm@3.0-latest` installed on Windows 8.1 running node `v0.12.4`. Prior to updating to npm 3 global modules were being installed to `%APPDATA%\npm`. After upgrading, global modules are trying to install to the node install location of `C:\Program Files (x86)\nodejs\node_modules\`. Per the [wiki](https://github.com/npm/npm/wiki/Troubleshooting#a-brief-note-on-the-built-in-windows-configuration) I should be able to add the following line to my `.npmrc` file to return to install to `%APPDATA%\npm` - `prefix=${APPDATA}/npm`. 

The wiki points to the file being here:
`%APPDATA%\npm\node_modules\npm\npmrc`, but my npm is installed at `C:\Program Files (x86)\nodejs\node_modules\npm` and that folder contains the `.npmrc` file.

Updating that`.npmrc` file to the following, does nothing to the global install location:
```
save-prefix = ~
proprietary-attribs = false
prefix=${APPDATA}/npm
```

Additionally there is `.npmrc` file here: `C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npmlog` updating that also has no effect.

Just to be exhaustive, I also created a `.npmrc` file and folder here `C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm`, which also had no effect.

Do I need to move my npm install to `%APPDATA%\npm` to get it to work or has the location/value of `.npmrc` changed with `npm@3`?

**Comment by iarna** [comment]
None of that *should* have changed.  Can you try running `npm config get prefix -g` and tell me what you  get?  That'll tell us if it's actually seeing your `.npmrc`. If it is, that's definitely a bug in `npm@3`.

**Comment by busches** [comment]
I did not realize you could run `npm config` for global variables, that's neato.

Running `npm config get prefix -g` returns:
`C:\Program Files (x86)\nodejs`

Running `npm config set prefix "${APPDATA}/npm" -g` and then `npm config get prefix -g` returns the desired value now:
`C:\Users\Busche\AppData\Roaming\npm`

So, not a bug in `npm@3`, but perhaps a bug in the documentation in the wiki. Is there a reason we don't suggest to the user to use `npm config set prefix "${APPDATA}/npm" -g` and instead suggest they create their own `.npmrc` file with that value in a specific location? Also, the location appears to have changed with `npm@3`, at least it was created at `C:\Program Files (x86)\nodejs\etc\npmrc` (yes no `.` at the start) for me. If not, let me know and I'll open a PR against this issue to update the wiki and we can consider this closed. Thanks for the help @iarna.

**Comment by iarna** [comment]
You know, I don't know why we ask people to create an npmrc by hand, that does seem silly on retrospect. 😁

Let's update the wiki to have people set using the command, that's gonna be a lot easier than trying to figure out where npm is installed.

**Comment by busches** [comment]
I have tweaked the wording on the [wiki](https://github.com/npm/npm/wiki/Troubleshooting#a-brief-note-on-the-built-in-windows-configuration), hopefully it's understandable. :)
