### ISSUE TITLE
npm trying to install from Git working directory and crashing @ 3.0.0

### ISSUE THREAD

**Issue by ashtonwar** [npm/npm#8721]
Hi, `npm install` is failing for me. Content of console:

```log
ashton@laptop:~/workspace/big-realtime-app$ npm install
npm ERR! addLocal Could not install /tmp/npm-16042-98f4f302/tmp/npm-16042-98f4f302/git-cache-822704e2614b4c3b13ea983a3ccb6ea9/c5226a8b23fb14bb3a507f12eb1b3f047eee33a5
npm ERR! Linux 3.13.0-29-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.4
npm ERR! npm  v3.0.0
npm ERR! code EISDIR
npm ERR! errno -21

npm ERR! EISDIR, read
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ashton/workspace/big-realtime-app/npm-debug.log
```

Content of `npm-debug.log`:

http://pastebin.com/jvDb7n64

**Comment by ashtonwar** [comment]
After downgrading to `2.12.0` the problem persists. Using `sudo` doesn't work so my guess is the file npm is looking for does not exist.

**Comment by ashtonwar** [comment]
And after git cloning the repo the issue went away for both `2.12.0` and `3.0.0`. Not quite sure how the project got messed up.

**Comment by iarna** [comment]
It's an interesting problem because the log shows it happening _really late_ in the install process. Like, it shows it happening when it went to print out the results of the install. There's not much room for more stuff to happen then…

**Comment by iarna** [comment]
(And no matter how weird your directory, I don't want you getting EISDIR errors. 😁We can do better than that.)

**Comment by ashtonwar** [comment]
Are you sure about that? NPM errored within about 2 seconds. But when completed successfully NPM installed > 100MB of files. My internet speed is nowhere near that fast. I also deleted the `node_modules` folder immediately before this test.

**Comment by iarna** [comment]
I was basing that on this:

```
672 silly install printInstalled
673 verbose stack Error: EISDIR, read
```

Buut, I forgot that I moved `printInstalled` out of the chain that depends on the success of the install.

The last actual action was:

```
667 silly addShrinkwrap Adding shrinkwrap to mongoose
```
Which implies it failed while looking for an `npm-shrinkwrap.json`, but seeing as `mongoose` doesn't have one, that seems unlikely, so it was _probably_ whatever the next module it looked at was. Unfortunately the logs don't share this.

I really hate EISDIR and other internal node errors. They eat all the stacks by dent of being async. It may be worth just wrapping them all in something that maintains the call stack.

**Comment by ashtonwar** [comment]
Go for it, sounds like a good idea.

**Comment by iarna** [comment]
Closing this as the original issue was resolved, plus, I suspect that the most recent versions of npm will, at the very least, give actionable error messages, if not just outright work.
