### ISSUE TITLE
npm v3: "path must be a string"

### ISSUE THREAD

**Issue by ljharb** [npm/npm#8722]
On `array-includes`, I ran `salita` to upgrade deps, and `npm install`. I got this:
```shell
npm ERR! Darwin 14.3.0
npm ERR! argv "~/.nvm/versions/io.js/v2.3.1/bin/iojs" "~/.nvm/versions/io.js/v2.3.1/bin/npm" "install"
npm ERR! node v2.3.1
npm ERR! npm  v3.0.0

npm ERR! Path must be a string. Received undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     ~/Dropbox/git/array-includes.git/npm-debug.log
```

npm-debug.log: https://gist.github.com/ljharb/e77adbd23f3f1bd5282e

**Comment by iarna** [comment]
This somehow managed to trigger the move rollback code, which really shouldn't have been there in the first place (it's still untested). At any rate, I've removed that offending code w/ d6f7c98 which'll be in 3.1.0.  So I can definitely say you won't get _this_ error again. 😁

But I'm gonna keep this open as I can reproduce a related error (if I start w/`array-includes@2.0.0`) with:

1. `npm install -g salita`
2. `git clone https://github.com/ljharb/array-includes`
3. `cd array-includes`
4. `npm install`
5. `salita`
6. `npm install` -- this actually works
7. `npm dedupe` -- explodes

**Comment by ljharb** [comment]
Sounds good, thanks

**Comment by iarna** [comment]
Ok, so I've verified that this _doesn't_ crash in `3.2.0`. So \o/

**Comment by ljharb** [comment]
yay, thanks!
