### ISSUE TITLE
Why can't I install the npm?

### ISSUE THREAD

**Issue by PleasantPro** [npm/npm#8726]
I attached here with a picture of the problem when I installed the npm. I input the cmd.exe with the below command line: "node cli.js install npm -gf" and I saw in the screen a full screen of emails and names...and error message:
![installnpm](https://cloud.githubusercontent.com/assets/11971721/8391837/18e8ad30-1d04-11e5-8c8e-9c90d8daca3d.PNG)

**Comment by ldez** [comment]
NPM is installed by default with Node.js.

you don't need to install.

If you want update NPM, just do:
```
npm install -g npm
```
You have permission problem (Windows UAC).
If previous command don't solve your problem, try to open a shell with admin privileges and try again the previous command.

**Comment by ldez** [comment]
I see you alreday have NPM 3 installed, is your choice ?
if you really want to install NPM 3, see: http://blog.npmjs.org/
```shell
npm install -g npm@3.0-latest
```
If you don't know NPM 3, stay with NPM 2 because NPM 3 is in beta.

**Comment by PleasantPro** [comment]
Thank you very much for your quick and detailed responses. I finally solved this problem by downloading git client-side tool and by connecting with cnpm, a chinese mirror site. I use the command line "npm install -g npm@3.5 " and it works. 
I were going to create a microblog for testing the express. but when I followed the microblog setup procedures step by step, I met the following problems. I attached with the pictures. Can you answer it? 
![Uploading installexpress.PNG…]()
![Uploading noservestatic.PNG…]()
![Uploading nobytes.PNG…]()

**Comment by PleasantPro** [comment]
Attached the picture as below:
![Uploading nobytes.PNG…]()
![Uploading noservestatic.PNG…]()

**Comment by ldez** [comment]
can you upload your `package.json` file ?

**Comment by ldez** [comment]
First, the following command don't do what you think:
```shell
npm install -g npm@3.5
```
When you put `@3.5` you say to npm do download NPM 3.5 but NPM 3.5 don't exist.
In your console you can see `npm v2.11.2`.

Secondly, I think you have a problem with your environment variables:
- Control panel -> System -> Advanced System Settings -> Advanced -> Environment variables.
- In environment variables search `PATH` variable. `PATH` variable must contains the following paths:
  - `C:\Users\[your username]\AppData\Roaming\npm`
  - `C:\nodejs\`
- Check you have the 2 paths in `PATH` variable **and** `C:\Users\[login]\AppData\Roaming\npm` is before `C:\nodejs\`

Thirdly, when your speak of microblog, you speak of https://github.com/cythilya/NodeJS-Microblog ?

**Comment by PleasantPro** [comment]
Hi, ldez, Thanks for your quick response and yes, I were going to install this NodeJS-Microblog. However, I met the following error message: TypeError: Cannot read property 'Store' of undefined
c:/nodejs/node_modules/connect-mongo/lib/connect-mongo.js:69
var Store=connect.Store||connect.session.Store; 
Can you correct it? thks!

**Comment by PleasantPro** [comment]
Hi, ldez, Thanks for your quick response and yes, I were going to install this NodeJS-Microblog. However, I met the following error message: TypeError: Cannot read property 'Store' of undefined
c:/nodejs/node_modules/connect-mongo/lib/connect-mongo.js:69
var Store=connect.Store||connect.session.Store; 
Can you correct it? thks!

**Comment by PleasantPro** [comment]
Idez, I got a question abt installing express. What is the most correct command line I shall input for installing the express? What version is compatible with npm @ 2.11.2?

**Comment by ldez** [comment]
- Cannot read property 'Store' : concerns MongoDB drivers or MongoDB instance.
- No incompatiblity with all version of Express and NPM.
```shell
npm install express --save
```

Your question doesn't concern NPM, please close this issue.
It's not the place for speak about this, go on StackOverflow ou open issue in https://github.com/cythilya/NodeJS-Microblog/issues

**Comment by ldez** [comment]
if you have clone repo https://github.com/cythilya/NodeJS-Microblog, you must do:
```shell
npm install ejs --save
```

**Comment by PleasantPro** [comment]
Thanks very much Idez! But I followed up your solution the problem exists. I don't know the root cause. Actually, I was going to build up my own website, but I want to decide which framework to adopt. The Express? Sails? I need to add some social functionalities. I am a newbie of nodejs. But I want to get on hands quickly. Is there any quick path to learn? Thanks.

**Comment by ldez** [comment]
Your problem concern MongoDB, did you install MongoDB?

You can see here : https://www.airpair.com/node.js/posts/nodejs-framework-comparison-express-koa-hapi

Sorry but we must stop speaking here, close this issue please.

**Comment by PleasantPro** [comment]
Thanks very much for Idez's help. I am closing this issue. It is clear now.
