### ISSUE TITLE
problem installing cordova on Windows

### ISSUE THREAD

**Issue by axtens** [npm/npm#8729]
Instead of installing nodejs into C:\Program Files\nodejs, I installed it into P:\nodejs. This may or may not have anything to do with the issue. 

Attempting to install cordova as per the docs, gives the following

```
P:\nodejs>npm install -g cordova
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "P:\\nodejs\\\\node.exe" "P:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
npm ERR! node v0.12.5
npm ERR! npm  v2.12.0

npm ERR! undefined is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
|
npm ERR! Please include the following file with any support request:
npm ERR!     P:\nodejs\npm-debug.log
```

Below is the npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ 'P:\\nodejs\\\\node.exe',
1 verbose cli   'P:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'cordova' ]
2 info using npm@2.12.0
3 info using node@v0.12.5
4 verbose install initial load of P:\nodejs\package.json
5 verbose readDependencies loading dependencies from P:\nodejs\package.json
6 silly cache add args [ 'cordova', null ]
7 verbose cache add spec cordova
8 silly cache add parsed spec { raw: 'cordova',
8 silly cache add   scope: null,
8 silly cache add   name: 'cordova',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed cordova@*
10 verbose addNamed "*" is a valid semver range for cordova
11 silly addNameRange { name: 'cordova', range: '*', hasData: false }
12 silly mapToRegistry name cordova
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/cordova
16 verbose addNameRange registry:https://registry.npmjs.org/cordova not in flight; fetching
17 verbose request uri https://registry.npmjs.org/cordova
18 verbose request no auth needed
19 info attempt registry request try #1 at 10:26:09 PM
20 verbose request id 6681751cfd2490bf
21 http request GET https://registry.npmjs.org/cordova
22 http 200 https://registry.npmjs.org/cordova
23 silly get cb [ 200,
23 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
23 silly get     etag: '"85NHKAIVXUC9GOV1AH5FU2UTC"',
23 silly get     'content-type': 'application/json',
23 silly get     'cache-control': 'max-age=60',
23 silly get     'content-length': '352002',
23 silly get     'accept-ranges': 'bytes',
23 silly get     date: 'Sat, 27 Jun 2015 14:26:14 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     age: '0',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-syd1625-SYD',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '1',
23 silly get     'x-timer': 'S1435415173.982273,VS0,VE773',
23 silly get     vary: 'Accept' } ]
24 verbose get saving cordova to C:\Users\Admin\AppData\Roaming\npm-cache\registry.npmjs.org\cordova\.cache.json
25 verbose stack TypeError: undefined is not a function
25 verbose stack     at calculateOwner (P:\nodejs\node_modules\npm\lib\utils\correct-mkdir.js:37:24)
25 verbose stack     at P:\nodejs\node_modules\npm\lib\utils\correct-mkdir.js:23:22
25 verbose stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
26 verbose cwd P:\nodejs
27 error Windows_NT 6.1.7601
28 error argv "P:\\nodejs\\\\node.exe" "P:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
29 error node v0.12.5
30 error npm  v2.12.0
31 error undefined is not a function
32 error If you need help, you may report this error at:
32 error     <https://github.com/npm/npm/issues>
33 verbose exit [ 1, true ]

```

**Comment by ldez** [comment]
try to do:
```shell
npm install -g npm@2.12.1
```

**Comment by ldez** [comment]
Try to do:
```shell
npm uninstall -g npm
npm install -g npm@2.12.1
```

**Comment by jamiewq** [comment]
Have a look at this
https://github.com/npm/npm/issues/8626

**Comment by ldez** [comment]
@jamiewq same problem same solution:
- uninstall npm@2.12.0
- install npm@2.12.1
- don't do `npm install -g npm` because this install npm@2.12.0

```shell
npm uninstall -g npm
npm install -g npm@2.12.1
```

**Comment by ldez** [comment]
If you think I'm not trying to help you, directory you can follow the solution proposed NPM owner @othiym23 in issue #8626:
> This is fixed in npm@2.12.1 (via 7e5da23), but unfortunately, to upgrade to it (it's npm@next right now) on Windows, you might have to downgrade. The fastest and easiest way to do this is using one of the official Node.js or io.js installers to reinstall both Node and npm. Thanks for filing this issue, because it's what alerted me that there was a problem here. And sorry for introducing the regression in the first place! This kind of change is very hard to test, but that's not an excuse.

**Comment by ldez** [comment]
Just for information, I had the same problem, and I give you how I solved it.

**Comment by ldez** [comment]
Check your environment variables:
- Control panel -> System -> Advanced System Settings -> Advanced -> Environment variables.
- In environment variables search `PATH` variable. `PATH` variable must contains the following paths:
  - `C:\Users\[your username]\AppData\Roaming\npm`
  - ` P:\nodejs\`
- Check you have the 2 paths in `PATH` variable **and** `C:\Users\[your username]\AppData\Roaming\npm` is **before** ` P:\nodejs\`

**Comment by ldez** [comment]
I'm trying to find why you cannot use npm [installed by Node.js installer] before you uninstall npm [updated version].
You have change `prefix` in your npm config ? or change `.npmrc` and/or `npmrc` files?

**Comment by ldez** [comment]
You have uninstall npm 2 times ?

**Comment by ldez** [comment]
Please close issue if your problem is solve, thanks.

**Comment by jdoose** [comment]
The "undefined is not a function" was resolved on my computer with installing the 2.12.1 version as suggested.
Afterwords I saw the hint in then changelog (https://github.com/npm/npm/blob/master/CHANGELOG.md): "Windows users might want to skip npm@2.12.0 and go straight to npm@2.12.1". It would be great if this hint would be bold (or larger) for better visibility.

**Comment by gnganpath** [comment]
For my case, I followed
 C:\Users\[your username]\AppData\Roaming\npm THEN
P:\nodejs\ and one more is tools.jar file not found in c:\prom files\jre_vesion. Copy tools.jar from c:\
prom files\jdk_version and paste.  Kindly make sure the  path is current user and environment variables

**Comment by aysham94** [comment]
try the following commands sequentially

 npm i test-travis-npm-deploy-shasum-check-failed

npm cache clear

npm install -g ionic

**Comment by umi22** [comment]
still error...

**Comment by skarya992** [comment]
dear all
i have successfully installed cordova using npm on windows 7..............
but i am unable to install cordova, even with the same or higher version of npm and node........please help me out

**Comment by legodude17** [comment]
What OS and `npm` and `node` versions are you using?

**Comment by skarya992** [comment]
i am using window 10
npm v2.15.9
node v4.6.1

though i also tried with latest node also .........but unable to install

**Comment by gnganpath** [comment]
I was tried windows 7
no idea about npm and node -v. While doing installation, 
Install jre - java c:\program files\jre..... copy the tools.jar file and paste to c:\progr files\nodejs\ - 
Sometimes tools.jar not located at nodejs intalled path.
this is what i resolved.

**Comment by legodude17** [comment]
What is the error? Can you put `npm-debug.log` in a gist and then post the link?

**Comment by skarya992** [comment]
previously it was showing an error.....something like "unable to found
debug.log"

then i run the command  "npm install --save debug-log"...............bcz it
work for win7

now if i am running "npm install -g cordova" or  "npm install --save
debug-log".........only cursor is rotating from last 14 hrs

what to do???

**Comment by Ankitgutpa2015** [comment]
Here Is A ssl Error this error can be resolved using this piece of code 
Copy and paste this code to nodejs command promt
npm set registry http://registry.npmjs.org/

**Comment by Nagaraj668** [comment]
I am also facing the same error. Could not install cordova using npm.
Windows 7
npm - 2.15.9
node - 4.5.0
npm set registry http://registry.npmjs.org/ is already set. Still is hanging up.

please help.
