### ISSUE TITLE
npm start failed dont get why its happened error windows_nt 6.3.9600 error on npm start

### ISSUE THREAD

**Issue by kashikhan1** [npm/npm#8734]
0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   'C:\\Users\\Kashi Khan\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.12.0
3 info using node@v0.12.5
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart express_website@1.0.0
6 info start express_website@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info express_website@1.0.0 Failed to exec start script
9 verbose stack Error: express_website@1.0.0 start: `node ./bin/www`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Users\Kashi Khan\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (C:\Users\Kashi Khan\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid express_website@1.0.0
11 verbose cwd C:\Users\Kashi Khan\Desktop\nodeauth-master
12 error Windows_NT 6.3.9600
13 error argv "node" "C:\\Users\\Kashi Khan\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
14 error node v0.12.5
15 error npm  v2.12.0
16 error code ELIFECYCLE
17 error express_website@1.0.0 start: `node ./bin/www`
17 error Exit status 1
18 error Failed at the express_website@1.0.0 start script 'node ./bin/www'.
18 error This is most likely a problem with the express_website package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node ./bin/www
18 error You can get their info via:
18 error     npm owner ls express_website
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by ldez** [comment]
try to do:
```shell
npm install -g npm@2.12.1
```

**Comment by ldez** [comment]
Do:
```shell
npm uninstall -g npm
npm install -g npm@2.12.1
```

**Comment by kashikhan1** [comment]
@idez i update npm node but still its not working

**Comment by ldez** [comment]
You must uninstall before : `npm uninstall -g npm`

NPM is installed into 2 places:
  - `C:\Users\[your username]\AppData\Roaming\npm`: it's the place for the updated npm version.
  - `C:\Programs files\nodejs\node_modules\npm`: it's npm@2.11.2 installed by default with Node.js

When your do `npm uninstall -g npm` this uninstall `C:\Users\[your username]\AppData\Roaming\npm` but not  `C:\Programs files\nodejs\node_modules\npm`

**Comment by ldez** [comment]
But you can have a problem with `express_website` like you can read into the log `This is most likely a problem with the express_website package,`

If the problem persist after updated npm to 2.12.1, your issue concern `express_website` not npm.

**Comment by kashikhan1** [comment]
sorry to day i am new no i unistall all npm and run npm install -g npm@2.12.1 its show error can't find module

**Comment by ldez** [comment]
Can you put console output here ?

**Comment by kashikhan1** [comment]
![capture](https://cloud.githubusercontent.com/assets/7945378/8396974/36506058-1dd5-11e5-83cb-c0b977ffdf62.JPG)

**Comment by ldez** [comment]
ok you have a new problem: you have uninstall npm 2 times ?

**Comment by kashikhan1** [comment]
yes  sir

**Comment by ldez** [comment]
Fail, you have uninstall npm@2.12.0 **and** npm@2.11.2 installed by default with Node.js.
Now you're stuck, you must reinstall Node.js.

**Comment by kashikhan1** [comment]
hahaha okay this is 3rd time i m going to install  nodejs

**Comment by ldez** [comment]
Sorry for this.

**Comment by kashikhan1** [comment]
no its okay thanks sir for your help and time :)

**Comment by ldez** [comment]
After install do `npm install -g npm@2.12.1`.

If the problem persist, your issue concern express_website not npm.

**Comment by ldez** [comment]
I think I found your problem:
In your `package.json` file you have defined `"start" : "./bin/www"` but this folder doesn't contain any file or start file (`index.js`)

**Comment by kashikhan1** [comment]
i have index file in views folder

**Comment by ldez** [comment]
`./bin/www` must exists and contains valid `index.js` file.
You can change folder value for `start` property.

I think it's not a NPM issue, please close this issue.
Go on StackOverflow or Google something like `express npm start node ./bin/www`

I hope I have helped you.

**Comment by kashikhan1** [comment]
i will but not working thank 
u

**Comment by afreshtech** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'manual' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose run-script [ 'premanual', 'manual', 'postmanual' ]
5 info premanual webfetch-shopper@1.0.0
6 info manual webfetch-shopper@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info webfetch-shopper@1.0.0 Failed to exec manual script
9 verbose stack Error: webfetch-shopper@1.0.0 manual: `node manual.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid webfetch-shopper@1.0.0
11 verbose cwd C:\webfetch
12 error Windows_NT 5.1.2600
13 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "manual"
14 error node v0.12.7
15 error npm  v2.11.3
16 error code ELIFECYCLE
17 error webfetch-shopper@1.0.0 manual: `node manual.js`
17 error Exit status 1
18 error Failed at the webfetch-shopper@1.0.0 manual script 'node manual.js'.
18 error This is most likely a problem with the webfetch-shopper package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node manual.js
18 error You can get their info via:
18 error     npm owner ls webfetch-shopper
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by tecnosoftware** [comment]
help!!!!
I am trying to install angular-cli...

npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or
 locked, rename 'C:\Users\JOSECE~1\AppData\Local\Temp\npm-892-22b046df\registry.
npmjs.org\request\-\request-2.67.0.tgz.3223235623' -> 'C:\Users\JOSECE~1\AppData
\Local\Temp\npm-892-22b046df\registry.npmjs.org\request\-\request-2.67.0.tgz'
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "angular-cli"
npm ERR! node v6.9.0
npm ERR! npm  v3.10.8

**Comment by amolbhandari52** [comment]
![image](https://cloud.githubusercontent.com/assets/20103742/25387487/a9722ffa-29e8-11e7-9ecb-3966d4d7a0a4.png)

I have this issue can anyone help me?
