### ISSUE TITLE
node-gyp not executed on npm@3

### ISSUE THREAD

**Issue by piranna** [npm/npm#8736]
I've downloaded node-canvas using git clone (I'm modifying it), but after upgrading to npm@3 and deleting the build, node_modules and deps folders, when doing ```npm install``` the dependencies get installed but node-gyp don't get executed and due to this, node-canvas module don't gets compiled. npm don't show any error nor get any error status code.

**Comment by iarna** [comment]
Yup, sure looks like a bug. Easy to repro too. 

Aand, yeah, we just explicitly weren't running the `install` lifecycle on the top level module. oops!

**Comment by piranna** [comment]
:+1:

**Comment by iarna** [comment]
This landed in master as https://github.com/npm/npm/commit/3cb6ad2a86a8d228fb10c389b3219855efd564b3 and will be in the 3.1.0 release.

**Comment by piranna** [comment]
Thank you :-) Just curious, why not in 3.0.0? It's not still released...
