### ISSUE TITLE
npm install (everything) would be failed on mac

### ISSUE THREAD

**Issue by Lucifier129** [npm/npm#8740]
I can not use npm install anything these days, it would be failed every time.

npm install -g npm@3-lastest also doesn't work

for example:

---

sudo npm install -g gulp
Password:
npm ERR! registry error parsing json
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "gulp"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2

npm ERR! Unexpected token t
npm ERR! {"_id":"gulp","_rev":"775-6e4f471c54a63ea6d22a4c6312927e7c","name":"gulp","description":"The streaming build system","dist-tags":{"latest":"3.9.0"},"versions":{"0.0.1":{"name":"gulp","description":"Simple stream-y build helper","ve

**Comment by easonzhuyi** [comment]
I used to have the same problem.
for example:
npm install -g grunt
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "grunt"
npm ERR! node v0.10.28
npm ERR! npm  v3.0.0
npm ERR! path /usr/local/lib/node_modules/npm-debug.log/package.json
npm ERR! code ENOTDIR
npm ERR! errno 27

npm ERR! ENOTDIR, open '/usr/local/lib/node_modules/npm-debug.log/package.json'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/easonzhuyi/npm-debug.log
easonzhuyidembp:~ easonzhuyi$ npm install -g grunt-cli
npm ERR! Darwin 13.4.0

**Comment by easonzhuyi** [comment]
I used to have the same problem,but 'package.json' is a empty file.

for example:
npm install -g grunt-cli
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "grunt-cli"
npm ERR! node v0.10.28
npm ERR! npm  v3.0.0
npm ERR! path /usr/local/lib/node_modules/npm-debug.log/package.json
npm ERR! code ENOTDIR
npm ERR! errno 27

npm ERR! ENOTDIR, open '/usr/local/lib/node_modules/npm-debug.log/package.json'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by iarna** [comment]
@easonzhuyi I'm going to delete your comment as it's: A) Not related in anyway and B) will be fixed by the next release.
