### ISSUE TITLE
代码高亮失效了

### ISSUE THREAD

**Issue by bluedusk** [npm/npm#8741]
环境如下：

hexo: 3.1.1
os: Darwin 14.3.0 darwin x64
http_parser: 2.3
node: 0.12.5
v8: 3.28.71.19
uv: 1.6.1
zlib: 1.2.8
modules: 14
openssl: 1.0.1o

代码着色和行标都失效了，行标只显示了一个 1；
md的写法没有指定语言，昨天还好用~~

```
code
```

**Comment by othiym23** [comment]
I'm pretty sure this issue is on `hexo` instead of npm, as npm itself doesn't offer code highlighting. As such the CLI team can't really help you out, so I'm going to close this.
