### ISSUE TITLE
Webpage search not returning obvious results

### ISSUE THREAD

**Issue by flyswatter** [npm/npm#8744]
If I search with the query `tape`, looking for the module by that name, it does not appear on the first 13 pages of results.  I stopped looking after that point.

There's definitely some optimization to be done here.

**Comment by KenanY** [comment]
@flyswatter This is the issue tracker for `npm`, the CLI package manager. Issues with the website should be opened over at [npm/newww](https://github.com/npm/newww). In fact, this issue sounds just like https://github.com/npm/newww/issues/1066 :)

**Comment by flyswatter** [comment]
Ahh, thank you!
