### ISSUE TITLE
npm install gets stuck on windows

### ISSUE THREAD

**Issue by vraptorche** [npm/npm#8745]
When trying to execute npm install it gets stuck om loadDep npm-fetch

**Comment by ldez** [comment]
Hi,
Please, give versions of Node, NPM and logs.

**Comment by vraptorche** [comment]
Hi,
I'm using these vesrions: Node version - 0.12.5, npm 3.0.0

**Comment by iarna** [comment]
Closing this as a duplicate of #8685.

**Comment by iarna** [comment]
The mention of `loadDep` makes it clear this is an `npm@3` bug.
