### ISSUE TITLE
npm should use /d command line argument to prevent Autorun commands when spawning cmd.exe

### ISSUE THREAD

**Issue by jkwuc89** [npm/npm#8751]
Please see https://github.com/npm/npm/issues/7688 for background information regarding this issue.
Specifically, these comments:

* https://github.com/sass/node-sass/issues/1012#issuecomment-115715502
* https://github.com/sass/node-sass/issues/1012#issuecomment-116608862

When npm spawns cmd.exe /c to start any process under Windows, it should also use the /d command line argument to prevent Autorun script commands from impacting the process being started.

**Comment by saper** [comment]
I think Autorun scripts can have its legitmate uses, for example if somebody wants to log all invocations of cmd.exe or something like that.

**Comment by saper** [comment]
This is one of possible solutions to #7333 problem, not a feature request per se.

**Comment by othiym23** [comment]
Fixed by 204ebbb3e0cab696a429a878ceeb4a7e78ec2b94 / #9245, included in `npm@2.14.1`.
