### ISSUE TITLE
npm start issue

### ISSUE THREAD

**Issue by JudyJdd** [npm/npm#8758]
Hi there,

I am new to Node js and to npm as well. I am trying to develop an application with Angular js framework and node js library. 

I installed node js and npm
```
E:\dev\GlobalAddinDeploymentTool>node --version
v0.12.5
E:\dev\GlobalAddinDeploymentTool>npm --version
2.11.2
```
But when I try to run "npm start" in the windows console, it shows some error message. I cannot figure out what's wrong with my setting. Could you please help me with it?

Following is the debug.log file 

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.11.2
3 info using node@v0.12.5
4 verbose stack Error: missing script: start
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:142:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:58:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:345:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:309:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:343:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:113:5)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:284:20
4 verbose stack     at evalmachine.<anonymous>:263:20
4 verbose stack     at OpenReq.Req.done (C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:141:5)
4 verbose stack     at OpenReq.done (C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:61:22)
5 verbose cwd E:\dev\GlobalAddinDeploymentTool
6 error Windows_NT 6.1.7601
7 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
8 error node v0.12.5
9 error npm  v2.11.2
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

**Comment by busches** [comment]
According to this line, `4 verbose stack Error: missing script: start`, there is no `start` command listed in your `package.json`. If there is one, please post your `package.json` file.

**Comment by KenanY** [comment]
Closing as abandoned; @busches is right in that you need to have a `"start"` script defined in your `package.json` before running `npm start`, otherwise you will get this error. This is intentional behavior. I can reopen this if you are still having this issue, @JudyJdd.

**Comment by deedaralam** [comment]
Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! angular-seed@0.0.0 prestart: `npm install`
npm ERR! Exit status 243
npm ERR! 
npm ERR! Failed at the angular-seed@0.0.0 prestart script 'npm install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/deedaralam/Desktop/projects/templatestore/npm-debug.log

**Comment by deedaralam** [comment]
When i write npm start show this error

**Comment by legodude17** [comment]
This is a problem with `angular-seed`, please file an issue there.

**Comment by pulkittulsyan** [comment]
{
  "name": "angular2-start",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "concurrently \"npm run tsc:w\" \"npm run lite\" ",
    "lite": "lite-server",
    "postinstall": "typings install",
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "typings": "typings"
  },
  "keywords": [],
  "author": "",
  "license": "MIT",
  "dependencies": {
    "@angular/common": "~2.4.1",
    "@angular/compiler": "~2.4.1",
    "@angular/core": "~2.4.1",
    "@angular/forms": "~2.4.1",
    "@angular/http": "~2.4.1",
    "@angular/platform-browser": "~2.4.1",
    "@angular/platform-browser-dynamic": "~2.4.1",
    "@angular/router": "~3.1.0",
    "@angular/upgrade": "~2.4.1",
    "angular-in-memory-web-api": "~0.1.5",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "ng2-file-upload": "^1.2.1",
    "reflect-metadata": "^0.1.8",
    "rxjs": "5.0.0-beta.12",
    "systemjs": "0.19.39",
    "zone.js": "^0.6.25"
  },
  "devDependencies": {
    "concurrently": "^3.1.0",
    "live-server": "^1.1.0",
    "typescript": "^2.0.3",
    "typings": "^1.4.0"
  }
}



As i have start command here, still it is showing the same error as the following.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\559524\AppData\Roaming\npm-cache\_logs\2017-07-06T12_08_33
_124Z-debug.log
