### ISSUE TITLE
Mention absolute path on EACCES: permission denied

### ISSUE THREAD

**Issue by binarykitchen** [npm/npm#8764]
Sometimes I see errors like these due to wrong permissions on the server which is fine:

```
npm ERR! Error: EACCES: permission denied, open 'npm-debug.log.df5cdcec9cab26b2125dd86e0b8d00cb'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, open 'npm-debug.log.df5cdcec9cab26b2125dd86e0b8d00cb']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: 'npm-debug.log.df5cdcec9cab26b2125dd86e0b8d00cb' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
```

But because it's coming from a script running multiple node.js instances, I wish the path `'npm-debug.log.df5cdcec9cab26b2125dd86e0b8d00cb' ` is absolute so that I can know to which one directory it refers on the server and I can adjust its permissions.

Thanks

**Comment by othiym23** [comment]
This would be useful, but it's not something the CLI team is going to have time to get to in the next 6-12 months. As such, we've added the `patch-welcome` tag to this, because we'd love to land a patch that adds this, and are closing the issue.

**Comment by binarykitchen** [comment]
Guess the patch must be done within `/lib/utils/error-handler.js` but is not obvious on what line and what's needed.
