### ISSUE TITLE
npm doesn't check if dependency was correctly installed

### ISSUE THREAD

**Issue by warrenseine** [npm/npm#8765]
Using npm 2.10.1, if I run `npm install` then closes the process in the middle of an installation of a dependency, npm has a corrupted module in `node_modules` (which is expected). However, the next time I run `npm install`, I would expect `npm` to detect the installation failed and correctly reinstall. That's not the behavior I'm seeing.

**Comment by iarna** [comment]
You'll be pleased that this is the behavior of npm version 3, which is currently in beta.

You can read a bit about it (and try it for yourself) over on our blog:

http://blog.npmjs.org/post/122450408965/npm-weekly-20-npm-3-is-here-ish

**Comment by joshperry** [comment]
Yes! So much yes.
