### ISSUE TITLE
npm Windows 7 error

### ISSUE THREAD

**Issue by toddler4372** [npm/npm#8771]
I'm trying to run a local server and I can't seem to get past this error.  I'm running this in Windows 7 from a Cygwin terminal, and I've installed the latest npm.  I can't seem to find much support elsewhere on Google for this error:

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files (x86)\nodejs\\node.exe" "C:\Program Files (x86)\nodejs\node_modules\npm\bin\npm-cli.js" "run" "select:continu"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! content-delivery-network@1.0.0 select:continu: `replace 'requireDotFile\(([^)]+)\)' 'requireDotFile("semantic-continu.json")' semantic/tasks/config/user.js`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the content-delivery-network@1.0.0 select:continu script 'replace 'requireDotFile(([^)]+))' 'requireDotFile("semantic-continu.json")' semantic/tasks/config/user.js'.
npm ERR! This is most likely a problem with the content-delivery-network package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     replace 'requireDotFile(([^)]+))' 'requireDotFile("semantic-continu.json")' semantic/tasks/config/user.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls content-delivery-network
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\cygwin64\home\todd_Continu\content-delivery-network\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files (x86)\nodejs\\node.exe" "C:\Program Files (x86)\nodejs\node_modules\npm\bin\npm-cli.js" "run" "build:semantic:continu"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! content-delivery-network@1.0.0 build:semantic:continu: `npm run select:continu && npm run gulp:semantic:build && npm run build:semantic:synchronize`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the content-delivery-network@1.0.0 build:semantic:continu script 'npm run select:continu && npm run gulp:semantic:build && npm run build:semantic:synchronize'.
npm ERR! This is most likely a problem with the content-delivery-network package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run select:continu && npm run gulp:semantic:build && npm run build:semantic:synchronize
npm ERR! You can get their info via:
npm ERR!     npm owner ls content-delivery-network
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\cygwin64\home\todd_Continu\content-delivery-network\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files (x86)\nodejs\\node.exe" "C:\Program Files (x86)\nodejs\node_modules\npm\bin\npm-cli.js" "run" "build"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! content-delivery-network@1.0.0 build: `npm run build:semantic:continu && npm run build:semantic:airbnb && npm run build:semantic:semantic && npm run build:applications`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the content-delivery-network@1.0.0 build script 'npm run build:semantic:continu && npm run build:semantic:airbnb && npm run build:semantic:semantic && npm run build:applications'.
npm ERR! This is most likely a problem with the content-delivery-network package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:semantic:continu && npm run build:semantic:airbnb && npm run build:semantic:semantic && npm run build:applications
npm ERR! You can get their info via:
npm ERR!     npm owner ls content-delivery-network
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\cygwin64\home\todd_Continu\content-delivery-network\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files (x86)\nodejs\\node.exe" "C:\Program Files (x86)\nodejs\node_modules\npm\bin\npm-cli.js" "run" "serve"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! content-delivery-network@1.0.0 preserve: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the content-delivery-network@1.0.0 preserve script 'npm run build'.
npm ERR! This is most likely a problem with the content-delivery-network package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get their info via:
npm ERR!     npm owner ls content-delivery-network
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\cygwin64\home\todd_Continu\content-delivery-network\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files (x86)\nodejs\node.exe" "C:\Program Files (x86)\nodejs\node_modules\npm\bin\npm-cli.js" "start"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! content-delivery-network@1.0.0 start: `npm run serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the content-delivery-network@1.0.0 start script 'npm run serve'.
npm ERR! This is most likely a problem with the content-delivery-network package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run serve
npm ERR! You can get their info via:
npm ERR!     npm owner ls content-delivery-network
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\cygwin64\home\todd_Continu\content-delivery-network\npm-debug.log

**Comment by khurramijazm** [comment]
just a suggestion if you could move nodejs.exe out from windows program files to some where else on C:/nodejs or other and try..i hope it fixes for you.

**Comment by nelsonrubiof** [comment]
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "express-generator"
npm ERR! node v0.12.3
npm ERR! npm  v2.12.0

npm ERR! undefined is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\cygwin64\home\nrubio\npm-debug.log

other error

**Comment by ldez** [comment]
@nelsonrubiof It's not the same problem.

3 solutions:

## Manual solution
open file `C:\Users\[your username]\AppData\Roaming\npm\node_modules\npm\lib\utils\correct-mkdir.js`

In this file, find `calculateOwner` function, and replace by:
```javascript
function calculateOwner () {
  if (!effectiveOwner) {
    effectiveOwner = { uid: 0, gid: 0 }

    if (process.getuid) effectiveOwner.uid = +process.getuid()
    if (process.getgid) effectiveOwner.gid = +process.getgid()

    if (effectiveOwner.uid === 0) {
      if (process.env.SUDO_UID) effectiveOwner.uid = +process.env.SUDO_UID
      if (process.env.SUDO_GID) effectiveOwner.gid = +process.env.SUDO_GID
    }
  }

  return effectiveOwner
}
```
After do `npm install -g npm@2.12.1`

## NPM unistall solution
Uninstall npm@2.12.0 `npm uninstall -g npm` [ONLY one time] and update `npm install -g npm@2.12.1`

## Uninstall Node.js solution

Else you can use the solution proposed by NPM owner @othiym23 in issue #8626:
> This is fixed in npm@2.12.1 (via 7e5da23), but unfortunately, to upgrade to it (it's npm@next right now) on Windows, you might have to downgrade. The fastest and easiest way to do this is using one of the official Node.js or io.js installers to reinstall both Node and npm. Thanks for filing this issue, because it's what alerted me that there was a problem here. And sorry for introducing the regression in the first place! This kind of change is very hard to test, but that's not an excuse.

**Comment by toddler4372** [comment]
I followed the instructions and am still getting the error.  Also, when I check, the npm version number it shows 2.11.2, but when I uninstall it it gives me version 2.11.2.  Then I install version 2.12.1 and it tells me my version is still 2.11.2.

------------------------------------------

todd@ResDev_todd-HP ~/_Continu/content-delivery-network
$ npm -v
2.11.2

todd@ResDev_todd-HP ~/_Continu/content-delivery-network
$ npm uninstall -g npm
unbuild npm@2.12.1

todd@ResDev_todd-HP ~/_Continu/content-delivery-network
$ npm install -g npm@2.12.1
C:\Users\todd\AppData\Roaming\npm\npm -> C:\Users\todd\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
npm@2.12.1 C:\Users\todd\AppData\Roaming\npm\node_modules\npm

todd@ResDev_todd-HP ~/_Continu/content-delivery-network
$ npm -v
2.11.2

todd@ResDev_todd-HP ~/_Continu/content-delivery-network
$ npm start

> content-delivery-network@1.0.0 start C:\cygwin64\home\todd\_Continu\content-delivery-network
> npm run serve


> content-delivery-network@1.0.0 preserve C:\cygwin64\home\todd\_Continu\content-delivery-network
> npm run build


> content-delivery-network@1.0.0 prebuild C:\cygwin64\home\todd\_Continu\content-delivery-network
> npm run clean


> content-delivery-network@1.0.0 clean C:\cygwin64\home\todd\_Continu\content-delivery-network
> rm -rf public/js public/templates public/css public/learn-app sematic/dist


> content-delivery-network@1.0.0 postclean C:\cygwin64\home\todd\_Continu\content-delivery-network
> mkdirp public/js public/templates public/css public/learn-app


> content-delivery-network@1.0.0 build C:\cygwin64\home\todd\_Continu\content-delivery-network
> npm run build:semantic:continu && npm run build:semantic:airbnb && npm run build:semantic:semantic && npm run build:applications


> content-delivery-network@1.0.0 build:semantic:continu C:\cygwin64\home\todd\_Continu\content-delivery-network
> npm run select:continu && npm run gulp:semantic:build && npm run build:semantic:synchronize


> content-delivery-network@1.0.0 select:continu C:\cygwin64\home\todd\_Continu\content-delivery-network
> replace 'requireDotFile\(([^)]+)\)' 'requireDotFile("semantic-continu.json")' semantic/tasks/config/user.js

]+)\)' was unexpected at this time.

C:\cygwin64\home\todd\_Continu\content-delivery-network>  "C:\cygwin64\home\todd\_Continu\content-delivery-network\node_modules\.bin\\node.exe"  "C:\cygwin64\home\todd\_Continu\content-delivery-network\node_modules\.bin\\..\replace\bin\replace.js" 'requireDotFile\(([)]+)\)' 'requireDotFile("semantic-continu.json")' semantic/tasks/config/user.js

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "select:continu"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE
npm ERR! content-delivery-network@1.0.0 select:continu: `replace 'requireDotFile\(([^)]+)\)' 'requireDotFile("semantic-continu.json")' semantic/tasks/config/user.js`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the content-delivery-network@1.0.0 select:continu script 'replace 'requireDotFile\(([^)]+)\)' 'requireDotFile("semantic-continu.json")' semantic/tasks/config/user.js'.
npm ERR! This is most likely a problem with the content-delivery-network package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     replace 'requireDotFile\(([^)]+)\)' 'requireDotFile("semantic-continu.json")' semantic/tasks/config/user.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls content-delivery-network
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\cygwin64\home\todd\_Continu\content-delivery-network\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:semantic:continu"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE
npm ERR! content-delivery-network@1.0.0 build:semantic:continu: `npm run select:continu && npm run gulp:semantic:build && npm run build:semantic:synchronize`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the content-delivery-network@1.0.0 build:semantic:continu script 'npm run select:continu && npm run gulp:semantic:build && npm run build:semantic:synchronize'.
npm ERR! This is most likely a problem with the content-delivery-network package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run select:continu && npm run gulp:semantic:build && npm run build:semantic:synchronize
npm ERR! You can get their info via:
npm ERR!     npm owner ls content-delivery-network
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\cygwin64\home\todd\_Continu\content-delivery-network\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE
npm ERR! content-delivery-network@1.0.0 build: `npm run build:semantic:continu && npm run build:semantic:airbnb && npm run build:semantic:semantic && npm run build:applications`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the content-delivery-network@1.0.0 build script 'npm run build:semantic:continu && npm run build:semantic:airbnb && npm run build:semantic:semantic && npm run build:applications'.
npm ERR! This is most likely a problem with the content-delivery-network package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:semantic:continu && npm run build:semantic:airbnb && npm run build:semantic:semantic && npm run build:applications
npm ERR! You can get their info via:
npm ERR!     npm owner ls content-delivery-network
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\cygwin64\home\todd\_Continu\content-delivery-network\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "serve"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE
npm ERR! content-delivery-network@1.0.0 preserve: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the content-delivery-network@1.0.0 preserve script 'npm run build'.
npm ERR! This is most likely a problem with the content-delivery-network package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get their info via:
npm ERR!     npm owner ls content-delivery-network
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\cygwin64\home\todd\_Continu\content-delivery-network\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE
npm ERR! content-delivery-network@1.0.0 start: `npm run serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the content-delivery-network@1.0.0 start script 'npm run serve'.
npm ERR! This is most likely a problem with the content-delivery-network package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run serve
npm ERR! You can get their info via:
npm ERR!     npm owner ls content-delivery-network
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\cygwin64\home\todd\_Continu\content-delivery-network\npm-debug.log

**Comment by toddler4372** [comment]
Also, my function calculateOwner() in correct-mkdir.js is identical to above^.

**Comment by ldez** [comment]
@thlorenz sorry the answer is for @nelsonrubiof

**Comment by toddler4372** [comment]
Did my thread get hijacked?

**Comment by ldez** [comment]
yes ;)

**Comment by ldez** [comment]
@toddler4372 for your npm version problem : 
You have a problem with your environment variables:
- Control panel -> System -> Advanced System Settings -> Advanced -> Environment variables.
- In environment variables search `PATH` variable. `PATH` variable must contains the following paths:
  - `C:\Users\[your username]\AppData\Roaming\npm`
  - `C:\Program Files (x86)\nodejs\`
- Check you have the 2 paths in `PATH` variable **and** `C:\Users\[your username]\AppData\Roaming\npm` is before `C:\Program Files (x86)\nodejs\`

**Comment by ldez** [comment]
I see you have openning à new issue #8775; please close this issue.

**Comment by dinagr** [comment]
Hello @ldez,

I have the same problem.
But I don't have a path of  'C:\Users\[your username]\AppData\Roaming\npm'
It was supposed to be created during the npm installation?
What else can I do?

Thanks,
Dina

**Comment by ldez** [comment]
@dinagr It was created before you try to install a lib.

**Comment by dinagr** [comment]
@ldez  I don't understand. I need to create it manually?

**Comment by ldez** [comment]
@dinagr sorry mispoke :wink: 

It was created **after** you try to install a lib.

**Comment by pthorsley** [comment]
@ldez your solution worked like a charm. did not have to mess with firewall at all, just added C:\Users\[your username]\AppData\Roaming\npm   and it worked great.
