### ISSUE TITLE
npm install hangs in VPN connection

### ISSUE THREAD

**Issue by shaunthomas999** [npm/npm#8776]
Hi,

I am trying to install npm packages inside a docker container. When in VPN connection npm install hangs most of the time at lines containing afterAdd. For e.g.,

```
npm verb addTmpTarball /tmp/npm-28-1e8b0720/registry.npmjs.org/deasync/-/deasync-0.0.10.tgz not in flight; adding
npm verb addTmpTarball already have metadata; skipping unpack for deasync@0.0.10
npm sill cache afterAdd deasync@0.0.10
npm verb afterAdd /usr/local/nonroot/.npm/deasync/0.0.10/package/package.json not in flight; writing
npm verb afterAdd /usr/local/nonroot/.npm/deasync/0.0.10/package/package.json written
npm sill fetchAndShaCheck shasum 662d6507426ba2af0cdaf894a1766c8099c0e435
npm verb addTmpTarball /tmp/npm-28-1e8b0720/registry.npmjs.org/sqlite3/-/sqlite3-3.0.8.tgz not in flight; adding
npm verb addTmpTarball already have metadata; skipping unpack for sqlite3@3.0.8
npm sill cache afterAdd sqlite3@3.0.8
npm verb afterAdd /usr/local/nonroot/.npm/sqlite3/3.0.8/package/package.json not in flight; writing
npm verb afterAdd /usr/local/nonroot/.npm/sqlite3/3.0.8/package/package.json written

```

Rarely installation completes. With direct internet connection there is no problem.

I tried to change registry to use http connection instead of https by doing

`npm config set registry http://registry.npmjs.org/`

But issue still exists.

**Comment by shaunthomas999** [comment]
More information, I am using Ubuntu 14.04 and I am trying to make a Docker container which is also based on Ubuntu 14.04. There is no issue in host OS. It is only when I am building a Docker image from a Dockerfile.

**Comment by varunpalekar** [comment]
Npm sucks.. its hangs at installation dockerode and node-slack.. stops my development..

**Comment by erfangc** [comment]
Can someone respond to this issue? Behind our corporate VPN proxy we experience the same issues. This is a show stopper for many web projects. Installation occasionally finishes successfully.

Can we be provided with a rationale or work around? It seem's like NPM is simply overwhelming the proxy servers with too many requests or sessions ... can NPM install be throttled?

**Comment by erfangc** [comment]
+1

**Comment by danwkennedy** [comment]
If you're using docker-compose, I've found it to be incredibly messy after extended use. It creates a bunch of docker networks behind the scenes and after a while everything gets "jumbled" (operating term). I'm not sure exactly what goes bad, but if I remove all the extra crap docker compose leaves behind, it seems to clear up my timeout issues.

My flow usually goes like this:

1. Go here: https://docs.docker.com/engine/userguide/networking/, see the 3 default networks Docker creates
2. Do a `docker network ls`
3. Call `docker network rm <ids>` where the ids are any networks that aren't the 3 default networks

I've done this while npm was chewing on a request and once the offending network went away, npm started churning happily.

**Comment by legodude17** [comment]
Does @danwkennedy's solution not work for anyone? @varunpalekar, if it sucks, why use it? Please be more respectful.

**Comment by danwkennedy** [comment]
After looking at the docs for the Docker network, the process I outlined above can be done with the following script:
`docker network rm $(docker network ls -f "type=custom" -q)`
Just note that if you have any custom networks that you actually need, this will kill those as well so use at your own risk

**Comment by tpenakov** [comment]
Seems that using this in package.json in config section (in example below the entire config section is present) helps a lot and speed up the development through the VPN:

`"config": {
    "prefer-offline": "true"
  }`
