### ISSUE TITLE
npm install error using node v0.10.38 and npm v3.0.0 

### ISSUE THREAD

**Issue by icirellik** [npm/npm#8780]
I'm receiving the following error when attempting to npm install using v3.0.0

```
npm ERR! Linux 3.16.0-36-generic
npm ERR! argv "node" "/home/user/node/bin/npm" "install"
npm ERR! node v0.10.38
npm ERR! npm  v3.0.0

npm ERR! zlib binding closed
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by iarna** [comment]
This is another variation on #8695, though you'd have no way of knowing that. I'm closing this as a duplicate. The good news is the fix will be in the next release. 😄
