### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by EmmaRamirez** [npm/npm#8783]
I'm currently running Windows 8 with v0.12.5 of node.js and v2.12.0 of npm. For some reason, I keep getting this error that includes "error undefined is not a function" when I attempt to install hexo

<pre><code>0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   'C:\\Users\\Erick\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'hexo-cli',
1 verbose cli   '-g' ]
2 info using npm@2.12.0
3 info using node@v0.12.5
4 verbose install initial load of C:\Users\Erick\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\Erick\AppData\Roaming\npm\package.json
6 silly cache add args [ 'hexo-cli', null ]
7 verbose cache add spec hexo-cli
8 silly cache add parsed spec { raw: 'hexo-cli',
8 silly cache add   scope: null,
8 silly cache add   name: 'hexo-cli',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed hexo-cli@*
10 verbose addNamed "*" is a valid semver range for hexo-cli
11 silly addNameRange { name: 'hexo-cli', range: '*', hasData: false }
12 silly mapToRegistry name hexo-cli
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/hexo-cli
16 verbose addNameRange registry:https://registry.npmjs.org/hexo-cli not in flight; fetching
17 verbose request uri https://registry.npmjs.org/hexo-cli
18 verbose request no auth needed
19 info attempt registry request try #1 at 3:49:09 AM
20 verbose request id a8fcd9644e76e328
21 http request GET https://registry.npmjs.org/hexo-cli
22 http 200 https://registry.npmjs.org/hexo-cli
23 silly get cb [ 200,
23 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
23 silly get     etag: '"B9TADAH697TUQSLL9BMG5HWSF"',
23 silly get     'content-type': 'application/json',
23 silly get     'cache-control': 'max-age=60',
23 silly get     'content-length': '14463',
23 silly get     'accept-ranges': 'bytes',
23 silly get     date: 'Wed, 01 Jul 2015 07:49:21 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     age: '0',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-ord1729-ORD',
23 silly get     'x-cache': 'MISS',
23 silly get     'x-cache-hits': '0',
23 silly get     'x-timer': 'S1435736961.451042,VS0,VE36',
23 silly get     vary: 'Accept' } ]
24 verbose get saving hexo-cli to C:\Users\Erick\AppData\Roaming\npm-cache\registry.npmjs.org\hexo-cli\.cache.json
25 verbose stack TypeError: undefined is not a function
25 verbose stack     at calculateOwner (C:\Users\Erick\AppData\Roaming\npm\node_modules\npm\lib\utils\correct-mkdir.js:37:24)
25 verbose stack     at C:\Users\Erick\AppData\Roaming\npm\node_modules\npm\lib\utils\correct-mkdir.js:23:22
25 verbose stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
26 verbose cwd C:\Users\Erick
27 error Windows_NT 6.2.9200
28 error argv "node" "C:\\Users\\Erick\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "hexo-cli" "-g"
29 error node v0.12.5
30 error npm  v2.12.0
31 error undefined is not a function
32 error If you need help, you may report this error at:
32 error     <https://github.com/npm/npm/issues>
33 verbose exit [ 1, true ]
</code></pre>

**Comment by mthierba** [comment]
v2.12.0 is broken on Windows. Current work-around is to explicitly install v2.12.1 (pre-release). This is described in more detail here: https://github.com/npm/npm/releases/tag/v2.12.1, and also discussed in #8702.

Be aware that even in order to be able to install 2.12.1 you MUST first roll back to a version earlier than 2.12.0 as with that one any `npm install` will fail on Windows.

**Comment by busches** [comment]
@EmmaRamirez are you still facing this issue with the latest `npm@2` or `npm@3`? Did @mthierba's suggestion work?

cc\ @KenanY

**Comment by EmmaRamirez** [comment]
This was fixed quite a long time ago (not sure what version number) with getting all of the Windows tests to pass :]

**Comment by busches** [comment]
@KenanY can you close this>
