### ISSUE TITLE
How to start npm in background?

### ISSUE THREAD

**Issue by pokal4u** [npm/npm#8788]
HI,

I am new to nodejs.

I started npm every time using: "npm start", but when I close the putty or enter Cntrl+z automatically npm stopped.

So how to start npm in background?

Please tell me the command.

I am using: express.js. ubuntu

Thanks
Pokal

**Comment by pokal4u** [comment]
any one help me please....

**Comment by KenanY** [comment]
@pokal4u I think you can use [`nohup`](https://en.wikipedia.org/wiki/Nohup) for that?

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
