### ISSUE TITLE
npm pack obeys .gitignore

### ISSUE THREAD

**Issue by radare** [npm/npm#8790]
Looks like `npm pack` is obeying `.gitignore` while the documentation only refers to `.npmignore`.

When using the `--verbose` flag, it doesn't even shows which files are ignored, so it was a little pain to find the bug.

**Comment by iarna** [comment]
This is documented here:

https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package

But I don't disagree that having those docs in the actual relevant commands would be better.
