### ISSUE TITLE
NPM Start Error

### ISSUE THREAD

**Issue by CapScroLL** [npm/npm#8792]
Please Help !
http://i.imgur.com/jP9FPZZ.jpg

VDS Windows 2008 Server R2 4 GB Ram

**Comment by KenanY** [comment]
@CapScroLL Do you have a `"start"` script defined in your `package.json`?

**Comment by CapScroLL** [comment]
sorry I forgot to give CDs

**Comment by CapScroLL** [comment]
Thank You

**Comment by ehsalazar** [comment]
It sounds like you have things figured out. I'll close this for now as we’re trying to clean up some old issues. We’ll be happy to reopen if necessary.
