### ISSUE TITLE
_resolved field not added to all installed packages.

### ISSUE THREAD

**Issue by knpwrs** [npm/npm#8797]
Try installing `gulp-spawn-mocha`, for example. The `_resolved` field in its `package.json` file reads `"https://registry.npmjs.org/gulp-spawn-mocha/-/gulp-spawn-mocha-2.2.1.tgz"`. Try looking at another arbitrary `package.json` file and it won't have a `_resolved` field at all. For example, `node_modules/gulp-spawn-mocha/node_modules/gulp-util/node_modules/lodash.template/node_modules/lodash.keys/node_modules/lodash.isobject/package.json`:

```json
{
  "name": "lodash.isobject",
  "version": "2.4.1",
  "description": "The Lo-Dash function `_.isObject` as a Node.js module generated by lodash-cli.",
  "homepage": "http://lodash.com/custom-builds",
  "license": "MIT",
  "keywords": [
    "functional",
    "lodash",
    "lodash-modularized",
    "server",
    "util"
  ],
  "author": {
    "name": "John-David Dalton",
    "email": "john.david.dalton@gmail.com",
    "url": "http://allyoucanleet.com/"
  },
  "contributors": [
    {
      "name": "John-David Dalton",
      "email": "john.david.dalton@gmail.com",
      "url": "http://allyoucanleet.com/"
    },
    {
      "name": "Blaine Bublitz",
      "email": "blaine@iceddev.com",
      "url": "http://www.iceddev.com/"
    },
    {
      "name": "Kit Cambridge",
      "email": "github@kitcambridge.be",
      "url": "http://kitcambridge.be/"
    },
    {
      "name": "Mathias Bynens",
      "email": "mathias@qiwi.be",
      "url": "http://mathiasbynens.be/"
    }
  ],
  "bugs": {
    "url": "https://github.com/lodash/lodash-cli/issues"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/lodash/lodash-cli.git"
  },
  "dependencies": {
    "lodash._objecttypes": "~2.4.1"
  },
  "readme": "# lodash.isobject v2.4.1\n\nThe [Lo-Dash](http://lodash.com/) function [`_.isObject`](http://lodash.com/docs#isObject) as a [Node.js](http://nodejs.org/) module generated by [lodash-cli](https://npmjs.org/package/lodash-cli).\n\n## Author\n\n| [![twitter/jdalton](http://gravatar.com/avatar/299a3d891ff1920b69c364d061007043?s=70)](https://twitter.com/jdalton \"Follow @jdalton on Twitter\") |\n|---|\n| [John-David Dalton](http://allyoucanleet.com/) |\n\n## Contributors\n\n| [![twitter/blainebublitz](http://gravatar.com/avatar/ac1c67fd906c9fecd823ce302283b4c1?s=70)](https://twitter.com/blainebublitz \"Follow @BlaineBublitz on Twitter\") | [![twitter/kitcambridge](http://gravatar.com/avatar/6662a1d02f351b5ef2f8b4d815804661?s=70)](https://twitter.com/kitcambridge \"Follow @kitcambridge on Twitter\") | [![twitter/mathias](http://gravatar.com/avatar/24e08a9ea84deb17ae121074d0f17125?s=70)](https://twitter.com/mathias \"Follow @mathias on Twitter\") |\n|---|---|---|\n| [Blaine Bublitz](http://www.iceddev.com/) | [Kit Cambridge](http://kitcambridge.be/) | [Mathias Bynens](http://mathiasbynens.be/) |\n",
  "readmeFilename": "README.md",
  "_id": "lodash.isobject@2.4.1",
  "_from": "lodash.isobject@>=2.4.1 <2.5.0",
  "scripts": {}
}
```

My goal here is to get the source for any given module installed for a given project (be it from `npm`, `git`, or just an http url), however arbitrarily deep in the dependency tree that module may be. So far I haven't yet determined how `npm` decides which `package.json` files to add `_resolved` to, I have just observed this behavior. It may have something to do with reinstalling modules, as in npm/npm-www#351.

**Comment by zkat** [comment]
Hi! So just to get it out of the way, anything prefixed with `_` in installed `package.json` files in the tree is considered private and internal to npm’s plumbing and it is bad news to rely on it, since it’s not really part of our public contract. We will break it. We promise. 🙅

That said, I’m also not sure what you’re hoping to get out of this particular feature. I’m closing this issue. However, if you’d like, open another issue that describes what problem you’re trying to solve, rather than a specific solution, we can maybe find a way to help out if it’s within the scope of our plans. 💁
