### ISSUE TITLE
Crash when using eslint via run-script

### ISSUE THREAD

**Issue by simonewebdesign** [npm/npm#8802]
I have no clue if this is a bug on [eslint](https://github.com/eslint/eslint) or npm, but I'm reporting it here.

I am using eslint v0.24.0 and I put a script in my application's package.json, in order to be able to run eslint via `npm run lint`. The package.json looks like this:

``` json
{
  "name": "my-app",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "lint": "eslint index.js"
  },
  "dependencies": {
    "eslint": "^0.24.0"
  }
}
```
This is what happens:

```
simone@ubuntu:~/Projects/eslint-demo$ npm run lint

> eslint-demo@1.0.0 lint /home/simone/Projects/eslint-demo
> eslint index.js


index.js
  1:0   error  Unexpected console statement  no-console
  1:0   error  "console" is not defined      no-undef
  1:12  error  Strings must use doublequote  quotes
  1:19  error  Missing semicolon             semi

✖ 4 problems (4 errors, 0 warnings)


npm ERR! Linux 3.19.0-18-generic
npm ERR! argv "/home/simone/.nvm/versions/node/v0.12.5/bin/node" "/home/simone/.nvm/versions/node/v0.12.5/bin/npm" "run" "lint"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE
npm ERR! eslint-demo@1.0.0 lint: `eslint index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the eslint-demo@1.0.0 lint script 'eslint index.js'.
npm ERR! This is most likely a problem with the eslint-demo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls eslint-demo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/simone/Projects/eslint-demo/npm-debug.log
simone@ubuntu:~/Projects/eslint-demo$ node -v
v0.12.5
simone@ubuntu:~/Projects/eslint-demo$ npm -v
2.11.2
```

So it seems to be working actually, but then it exits with status 1.
Also tried with node v0.11.16 (npm v2.3.0), getting the same behaviour.

I've isolated and reproduced the bug in this repo: https://github.com/simonewebdesign/npm-eslint-bug

Here's the `npm-debug.log` file for completeness: https://raw.githubusercontent.com/simonewebdesign/npm-eslint-bug/master/npm-debug.log

**Comment by iarna** [comment]
This doesn't appear to be a bug in either eslint nor in npm. Let's go through the steps...

1. You setup a lifecycle script called `lint` that runs `eslint index.js`.
2. When eslint finds errors in a file it runs them and exits with an error status.
3. When you run `npm lint` it runs eslint, which exits with an error status.
4. When a lifecycle script exits with an error status, npm will report that it did so as above.

This is normal behavior.

**Comment by simonewebdesign** [comment]
Thanks for the clarification!

**Comment by hayesmaker** [comment]
except when i run eslint command outside npm I get 61 errors and the same eslint command in an npm script gives me 58 errors... :S

**Comment by kurumkan** [comment]
but what if I want a watch mode?

**Comment by legodude17** [comment]
Then just configure `eslint` to watch
