### ISSUE TITLE
npm@3.0: scripts preuninstall, uninstall - cannot find module ...

### ISSUE THREAD

**Issue by yokun** [npm/npm#8806]
When using preuninstall or uninstall  script with dependencies throws an error. Dependencies being uninstalled prior script execution.

Thank you!

**Comment by iarna** [comment]
Ooh! This is an exciting edge case!

(I'm not being sarcastic here, I'm really am excited! =D)

**Comment by iarna** [comment]
Ok, so the easiest way to fix this is to decouple the uninstall lifecycle running from actually removing the thing. We probably want to reverse the order we uninstall things too, which is trickier (we don't have any facility for that currently).

**Comment by iarna** [comment]
Ok, I was wrong, reverse things turned out to be trivial and does exactly what we want. \o/

**Comment by iarna** [comment]
Fixed in v3.1.1

**Comment by cuginoAle** [comment]
HI there,
I am facing this exact issue and I am running version 3.8.6
The dependency is uninstalled before preuninstall gets executed
thanks

**Comment by pmuens** [comment]
Facing the same issue where the dependencies are removed before the `preuninstall` hook kicks in.... (see: https://github.com/serverless/serverless/issues/3251).

**Comment by israelroldan** [comment]
I can reproduce with v4.0.3 as well.

**Comment by exah** [comment]
Same here

**Comment by garronej** [comment]
Same with 4.4.4

**Comment by thomasklein** [comment]
Same with 3.10.10

**Comment by LitoMore** [comment]
I can reproduce with 4.2.0 and 4.6.1
