### ISSUE TITLE
Maximum call stack size exceeded running `npm ls -g`

### ISSUE THREAD

**Issue by isaacs** [npm/npm#8807]
npm-debug.log file:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/iojs', '/usr/local/bin/npm', 'ls', '-g' ]
2 info using npm@3.0.0
3 info using node@v2.2.1
4 verbose stack RangeError: Maximum call stack size exceeded
4 verbose stack     at Function.keys (native)
4 verbose stack     at exports.create (/Users/isaacs/dev/npm/npm/lib/install/node.js:26:10)
4 verbose stack     at /Users/isaacs/dev/npm/npm/lib/install/node.js:29:14
4 verbose stack     at Array.forEach (native)
4 verbose stack     at exports.create (/Users/isaacs/dev/npm/npm/lib/install/node.js:26:25)
4 verbose stack     at /Users/isaacs/dev/npm/npm/lib/install/node.js:29:14
4 verbose stack     at Array.forEach (native)
4 verbose stack     at exports.create (/Users/isaacs/dev/npm/npm/lib/install/node.js:26:25)
4 verbose stack     at exports.reset (/Users/isaacs/dev/npm/npm/lib/install/node.js:40:15)
4 verbose stack     at Array.forEach (native)
5 verbose cwd /Users/isaacs/dev/js/glob
6 error Darwin 14.3.0
7 error argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "ls" "-g"
8 error node v2.2.1
9 error npm  v3.0.0
10 error Maximum call stack size exceeded
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

Note: I've probably got lots of weird cruft in there, dating back to ancient versions of npm.

**Comment by isaacs** [comment]
Somewhat unhelpfully, `git bisect` says the first commit with the problem is bd6919729f9535f4e3698e78eeb2331236dcdeea

**Comment by isaacs** [comment]
`npm ls -gpl` is this https://gist.github.com/isaacs/bec3044d1d7c8b09bc12

**Comment by iarna** [comment]
Yeah, definitely knew that one of these was still lurking out there…

**Comment by iarna** [comment]
If the commits had been less squashed it wouldn't have helped in this case as it was introduced with the commit where `ls` was changed to use readPackageTree + asReadInstalled, which was a later stage step. Alas.

**Comment by iarna** [comment]
I'm hoping that https://github.com/npm/npm/tree/iarna/safe will bring better error messages for this scenario. I believe I've got a tarball of someone's global node_modules that should reproduce this.

**Comment by iarna** [comment]
I'm closing this in preference to https://github.com/npm/npm/issues/9224 and more specifically https://github.com/npm/npm/issues/9223.
