### ISSUE TITLE
Installation Issue  - in Ubuntu

### ISSUE THREAD

**Issue by tameen** [npm/npm#8810]
I wrote this command:
 sudo npm install -g cordova
and it shows this result : 
![screenshot from 2015-07-03 15 38 01](https://cloud.githubusercontent.com/assets/2864934/8493200/57a71dc0-2170-11e5-9902-95507949fb89.png)

Could anyone please help?

**Comment by KenanY** [comment]
@tameen Hmm, maybe try [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) first?

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
