### ISSUE TITLE
Error: No compatible version found: multimatch@'^1.0.0'

### ISSUE THREAD

**Issue by rickyzyj** [npm/npm#8811]
Hi,
After I cloned Jquery project to local repository, i tried to build it through command "npm run build", in npm-debug.log, there are following error message and it seems fail in "postuninstall load-grunt-tasks@1.0.0".
```
1084 info preuninstall load-grunt-tasks@1.0.0                          
1085 info uninstall load-grunt-tasks@1.0.0
1086 verbose true,/root/MY_SW/jquery/node_modules,/root/MY_SW/jquery/node_modules unbuild load-grunt-tasks@1.0.0
1087 info postuninstall load-grunt-tasks@1.0.0
1088 error Error: No compatible version found: multimatch@'^1.0.0'
1088 error Valid install targets:
1088 error ["0.1.0","0.2.0","0.3.0","1.0.0","1.0.1","2.0.0"]
1088 error     at installTargetsError (/usr/local/node/0.10.0/lib/node_modules/npm/lib/cache.js:682:10)
1088 error     at /usr/local/node/0.10.0/lib/node_modules/npm/lib/cache.js:597:10
1088 error     at saved (/usr/local/node/0.10.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
1088 error     at Object.oncomplete (fs.js:93:15)
1089 error If you need help, you may report this log at:
1089 error     <http://github.com/isaacs/npm/issues>
1089 error or email it to:
1089 error     <npm-@googlegroups.com>
1090 error System Linux 2.6.32-504.el6.x86_64                                                      
```
Before run build command, i installed g++/npm/gruntcli in my linux (CentOS6.5) machine. But i'm not sure if following message is related to the failure when I run "grunt" command in my terminal. I did run "npm install -g grunt-cli" to install grunt-cli.
```
[root@ricky jquery]# grunt
grunt-cli: The grunt command line interface. (v0.1.13)

Fatal error: Unable to find local grunt.

If you're seeing this message, either a Gruntfile wasn't found or grunt
hasn't been installed locally to your project. For more information about
installing and configuring grunt, please see the Getting Started guide:

http://gruntjs.com/getting-started                                                                ||
```
BTW, all installations, clone and build commands are run with root previliage on my machine.

Thanks for your help!
Rickyzyj

**Comment by KenanY** [comment]
@rickyzyj Your `npm` version must be very old. Could you try [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm)?

**Comment by rickyzyj** [comment]
Updated. It works now. Thanks very much!
BRs,
Fred

Date: Fri, 3 Jul 2015 09:19:14 -0700

**Comment by ehsalazar** [comment]
Good to hear. I'll close this for now as we’re trying to clean up some old issues. We’ll be happy to reopen if necessary.
