### ISSUE TITLE
Slow `npm ls`

### ISSUE THREAD

**Issue by williamboman** [npm/npm#8813]
### `node@0.10.39` `npm@2.12.1`
```sh
$ time npm ls -g --depth=0
real	0m0.599s
user	0m0.514s
sys	0m0.088s
```

---

### `node@0.12.5` `npm@3.1.0`
```sh
$ time npm ls -g --depth=0
real	0m9.945s
user	0m9.920s
sys	0m0.531s
```

With the same global modules installed.

**Comment by iarna** [comment]
I'm closing this in preference to #8826, which will track improving npm@3 speed generally.
