### ISSUE TITLE
Publishing through Travis CI breaks checksum

### ISSUE THREAD

**Issue by astorije** [npm/npm#8822]
As reported on https://github.com/astorije/chai-immutable/issues/17, a package of mine has an invalid checksum. However, looking at [the Travis CI build report](https://travis-ci.org/astorije/chai-immutable/jobs/69491431), everything went fine...

We already identified an issue on https://github.com/astorije/chai-immutable/issues/15 and https://github.com/npm/npm/issues/8354, could it be related?

**Comment by grabbou** [comment]
There was yet another issue AFAIK with the checksum in title, but was kinda old and I guess the origin was a bit different.

**Comment by astorije** [comment]
FYI, here is the output I get when trying to install the package:

```
$ npm install chai-immutable
npm ERR! Linux 3.13.0-53-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install" "chai-immutable"
npm ERR! node v0.10.25
npm ERR! npm  v2.3.0

npm ERR! shasum check failed for /tmp/npm-12989-d9060333/registry.npmjs.org/chai-immutable/-/chai-immutable-1.1.0.tgz
npm ERR! Expected: bda9ba9c819e2fe8c5e037cc6c50114ef1101527
npm ERR! Actual:   0a3c18fea315757287ee360031505dff3faad5b7
npm ERR! From:     https://registry.npmjs.org/chai-immutable/-/chai-immutable-1.1.0.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jeremie/w3repos/specberus/npm-debug.log
```

I have no idea what caused the invalid checksum here... That package is used in production so I need to find a solution soon but I can leave version `1.1.0` as the latest for one more day in case you guys can look into it. Thank you so much in advance anyway!

**Comment by astorije** [comment]
Thanks for the labelization, @iarna. Any chance someone can take a look at this? Currently, installing the package fails and I have no idea what to do.
I haven't re-published or un-published anything yet to be ready to follow your instructions if it helps debugging, but I'll do that tomorrow to find a quick fix until the bigger issue gets resolved.

**Comment by astorije** [comment]
I fixed this issue on my end by manually publishing [version 1.1.1](https://github.com/astorije/chai-immutable/releases/tag/v1.1.1), but this doesn't solve this bug IMO.

FYI, I'll leave 1.1.0 published in case it's of any use for you and will unpublish it (or the package can be fixed) once you can figure this out.

Thanks!

**Comment by iarna** [comment]
Ok, so I got a moment to look at this. Thank you for keeping that around!

Usually when we see shasum errors its because somethings gone wrong with a user's cache dir, but in this case the shasum of the tarball in the registry actually doesn't match the shasum stored in the registry.

**Comment by iarna** [comment]
Ok, so the problem here is that chai-immutable@1.1.0 was published with a known bad version of Node.js (0.11.16, which had a broken crypto.Hash implementation).  Any package published with that version of node will be busted. I'm going to close this ticket now.

(We are looking into catching that server side, but that's another repo entirely. 😁)

**Comment by astorije** [comment]
Argh, that's a bummer. Since my [Travis CI configuration](https://github.com/astorije/chai-immutable/blob/a5b6b465a6ddf79b5dd9479d79b9e821d0588a7c/.travis.yml#L3) supports versions `0.10`, `0.11` and `0.12`, it means that at every deploy I'll have 1 chance out of 3 to publish an invalid version!

**Comment by othiym23** [comment]
@astorije Just asking: why is 0.11 still in the mix? As the developmental branch, it was never intended to be used beyond the release of 0.12. A way to solve this oroblem would just be to pull it from your Travis config.

**Comment by astorije** [comment]
That's right, I'll probably just keep @othiym23 0.10 and 0.12 around. I actually just learned that versions `0.(2n)` are the stable ones and versions `0.(2n+1)` were the unstable ones, shame on me...

**Comment by othiym23** [comment]
No shame! It's weird that Node doesn't follow semver, given how much of the ecosystem is based on semver.

**Comment by astorije** [comment]
Agreed...
