### ISSUE TITLE
linux command download npm package is too slow, how can I improve it?

### ISSUE THREAD

**Issue by PleasantPro** [npm/npm#8828]
Recently, I installed linux for development. But when I download npm package, I found the speed is very low. 
Below is the cmd line I input:
git clone --recursive git://github.com/isaacs/npm.git
Then, I tried another cmd line:
curl http://npmjs.org/install.sh | sh
sudo sh install.sh
It shows the following lines:
fetching ....
But it took a very long time without showing any thing. 

Can anyone help me? Thanks very much!

**Comment by yesmeck** [comment]
Try using a HTTP proxy or VPN.
