### ISSUE TITLE
npm doesn't like pipes

### ISSUE THREAD

**Issue by shanemikel** [npm/npm#8829]
```
$ npm search express | less
npm ERR! Error: write EPIPE
npm ERR!     at errnoException (net.js:901:11)
npm ERR!     at Object.afterWrite (net.js:718:19)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.19.0-21-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "search" "express"
npm ERR! cwd /home/op/nodejsApp
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! syscall write
npm ERR! code EPIPE
npm ERR! errno EPIPE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/op/nodejsApp/npm-debug.log
npm ERR! not ok code 0
```

(EDIT) -- actually, I seem to be getting errors like this without the bash glue; I'm starting to think that it has to do with the size of the response...

**Comment by KenanY** [comment]
@shanemikel Is this also an issue in the [latest release](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) of `npm`?

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
