### ISSUE TITLE
Failed to install gemini

### ISSUE THREAD

**Issue by Atanoly** [npm/npm#8831]
Colleagues,
I am failed to install Gemini. Pls advise...

```
C:\Users\a.kushnarev>node -v
v0.12.5

C:\Users\a.kushnarev>npm -v
2.11.2

C:\Users\a.kushnarev>npm install npm
npm@2.12.1 node_modules\npm

C:\Users\a.kushnarev>npm uninstall -g npm
unbuild npm@2.12.1

C:\Users\a.kushnarev>npm -v
2.11.2

C:\Users\a.kushnarev>npm install -g npm@2.12.1
C:\Users\a.kushnarev\AppData\Roaming\npm\npm -> C:\Users\a.kushnarev\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
npm@2.12.1 C:\Users\a.kushnarev\AppData\Roaming\npm\node_modules\npm

C:\Users\a.kushnarev>npm install -g gemini
npm WARN engine pngjs@0.4.0: wanted: {"node":"0.8.x"} (current: {"node":"0.12.5","npm":"2.11.2"})
-


> png-img@1.1.1 install C:\Users\a.kushnarev\AppData\Roaming\npm\node_modules\gemini\node_modules\png-img
> node-gyp rebuild


C:\Users\a.kushnarev\AppData\Roaming\npm\node_modules\gemini\node_modules\png-img>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bi
n\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Сборка проектов в этом решении по одному. Чтобы включить параллельную сборку, добавьте параметр "/m".
  png.c
  pngerror.c
  pngget.c
  pngmem.c
  pngpread.c
  pngread.c
  pngrio.c
  pngrtran.c
  pngrutil.c
  pngset.c
  pngtest.c
  pngtrans.c
  pngwio.c
  pngwrite.c
  pngwtran.c
  pngwutil.c
  libpng.vcxproj -> C:\Users\a.kushnarev\AppData\Roaming\npm\node_modules\gemini\node_modules\png-img\build\Release\\libpng.lib
  adler32.c
\  compress.c
  deflate.c
  gzclose.c
  gzlib.c
  gzread.c
  gzwrite.c
  infback.c
  inffast.c
  inflate.c
  inftrees.c
  trees.c
  uncompr.c
  zutil.c
  zlib.vcxproj -> C:\Users\a.kushnarev\AppData\Roaming\npm\node_modules\gemini\node_modules\png-img\build\Release\\zlib.lib
  init.cc
  PngImgAdapter.cc
  PngImg.cc
..\src\PngImg.cc(56): warning C4267: =: преобразование из "size_t" в "png_uint_32"; возможна потеря данных [C:\Users\a.kushnarev\AppData\Roaming\npm\node_modules\gemini\node_modul
es\png-img\build\png_img.vcxproj]
..\src\PngImg.cc(102): warning C4267: аргумент: преобразование из "size_t" в "png_uint_32"; возможна потеря данных [C:\Users\a.kushnarev\AppData\Roaming\npm\node_modules\gemini\no
de_modules\png-img\build\png_img.vcxproj]
..\src\PngImg.cc(113): warning C4244: =: преобразование "const short" в "png_byte", возможна потеря данных [C:\Users\a.kushnarev\AppData\Roaming\npm\node_modules\gemini\node_modul
es\png-img\build\png_img.vcxproj]
..\src\PngImg.cc(114): warning C4244: =: преобразование "const short" в "png_byte", возможна потеря данных [C:\Users\a.kushnarev\AppData\Roaming\npm\node_modules\gemini\node_modul
es\png-img\build\png_img.vcxproj]
..\src\PngImg.cc(115): warning C4244: =: преобразование "const short" в "png_byte", возможна потеря данных [C:\Users\a.kushnarev\AppData\Roaming\npm\node_modules\gemini\node_modul
es\png-img\build\png_img.vcxproj]
..\src\PngImg.cc(117): warning C4244: =: преобразование "const short" в "png_byte", возможна потеря данных [C:\Users\a.kushnarev\AppData\Roaming\npm\node_modules\gemini\node_modul
es\png-img\build\png_img.vcxproj]
     ╤ючфрхЄё  сшсышюЄхър C:\Users\a.kushnarev\AppData\Roaming\npm\node_modules\gemini\node_modules\png-img\build\Release\png_img.lib ш юс·хъЄ C:\Users\a.kushnarev\AppData\Roaming
  \npm\node_modules\gemini\node_modules\png-img\build\Release\png_img.exp
  ╤ючфрэшх ъюфр
  ╤ючфрэшх ъюфр чртхЁ°хэю
  png_img.vcxproj -> C:\Users\a.kushnarev\AppData\Roaming\npm\node_modules\gemini\node_modules\png-img\build\Release\\png_img.node
npm ERR! fetch failed https://registry.npmjs.org/es6-set/-/es6-set-0.1.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/expect.js/-/expect.js-0.3.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/minimist/-/minimist-0.2.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/handlebars/-/handlebars-1.3.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/express/-/express-4.10.6.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/lodash/-/lodash-2.4.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/uglify-js/-/uglify-js-2.4.16.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/forever/-/forever-0.11.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/q/-/q-1.1.2.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/semver/-/semver-2.3.2.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/tsort/-/tsort-0.0.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/useragent/-/useragent-2.1.3.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/6to5/-/6to5-1.15.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/mocha/-/mocha-1.21.5.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/request/-/request-2.51.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/caniuse-db/-/caniuse-db-1.0.20140710.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/moment/-/moment-2.8.4.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/request-promise/-/request-promise-0.3.2.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/es6-set/-/es6-set-0.1.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/expect.js/-/expect.js-0.3.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/minimist/-/minimist-0.2.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/moment/-/moment-2.8.4.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/express/-/express-4.10.6.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/q/-/q-1.1.2.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/request/-/request-2.51.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/lodash/-/lodash-2.4.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/handlebars/-/handlebars-1.3.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/6to5/-/6to5-1.15.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/request-promise/-/request-promise-0.3.2.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/uglify-js/-/uglify-js-2.4.16.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/caniuse-db/-/caniuse-db-1.0.20140710.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/useragent/-/useragent-2.1.3.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/semver/-/semver-2.3.2.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/forever/-/forever-0.11.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/mocha/-/mocha-1.21.5.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/tsort/-/tsort-0.0.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/es6-set/-/es6-set-0.1.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/expect.js/-/expect.js-0.3.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/q/-/q-1.1.2.tgz
npm ERR! fetch failed https://registry.npmjs.org/minimist/-/minimist-0.2.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/moment/-/moment-2.8.4.tgz
npm ERR! fetch failed https://registry.npmjs.org/request/-/request-2.51.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/6to5/-/6to5-1.15.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/handlebars/-/handlebars-1.3.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/express/-/express-4.10.6.tgz
npm ERR! fetch failed https://registry.npmjs.org/lodash/-/lodash-2.4.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/request-promise/-/request-promise-0.3.2.tgz
npm ERR! fetch failed https://registry.npmjs.org/caniuse-db/-/caniuse-db-1.0.20140710.tgz
npm ERR! fetch failed https://registry.npmjs.org/useragent/-/useragent-2.1.3.tgz
npm ERR! fetch failed https://registry.npmjs.org/forever/-/forever-0.11.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/tsort/-/tsort-0.0.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/uglify-js/-/uglify-js-2.4.16.tgz
npm ERR! fetch failed https://registry.npmjs.org/mocha/-/mocha-1.21.5.tgz
npm ERR! fetch failed https://registry.npmjs.org/semver/-/semver-2.3.2.tgz
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "gemini"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2

npm ERR! fetch failed with status code 401
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\a.kushnarev\npm-debug.log

C:\Users\a.kushnarev>
```

**Comment by Atanoly** [comment]
I have upgraded npm to latest version and tried to install gemini again.
But got the same error

C:\Users\a.kushnarev\AppData\Roaming\npm>npm -v
2.12.1

C:\Users\a.kushnarev\AppData\Roaming\npm>npm install gemini@latest
/
> png-img@1.1.1 install C:\Users\a.kushnarev\AppData\Roaming\npm\node_modules\gemini\node_modules\png-img
> node-gyp rebuild


C:\Users\a.kushnarev\AppData\Roaming\npm\node_modules\gemini\node_modules\png-img>if not defined npm_config_node_gyp (node "C:\Users\a.kushn
arev\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Сборка проектов в этом решении по одному. Чтобы включить параллельную сборку, добавьте параметр "/m".
  png.c
  pngerror.c
  pngget.c
  pngmem.c
  pngpread.c
  pngread.c
  pngrio.c
  pngrtran.c
  pngrutil.c
  pngset.c
  pngtest.c
  pngtrans.c
  pngwio.c
  pngwrite.c
  pngwtran.c
  pngwutil.c
  libpng.vcxproj -> C:\Users\a.kushnarev\AppData\Roaming\npm\node_modules\gemini\node_modules\png-img\build\Release\\libpng.lib
  adler32.c
  compress.c
  crc32.c
  deflate.c
  gzclose.c
  gzlib.c
  gzread.c
  gzwrite.c
  infback.c
  inffast.c
  inflate.c
  inftrees.c
  trees.c
  uncompr.c
  zutil.c
  zlib.vcxproj -> C:\Users\a.kushnarev\AppData\Roaming\npm\node_modules\gemini\node_modules\png-img\build\Release\\zlib.lib
  init.cc
  PngImgAdapter.cc
  PngImg.cc
..\src\PngImg.cc(56): warning C4267: =: преобразование из "size_t" в "png_uint_32"; возможна потеря данных [C:\Users\a.kushnarev\AppData\Ro
aming\npm\node_modules\gemini\node_modules\png-img\build\png_img.vcxproj]
..\src\PngImg.cc(102): warning C4267: аргумент: преобразование из "size_t" в "png_uint_32"; возможна потеря данных [C:\Users\a.kushnarev\Ap
pData\Roaming\npm\node_modules\gemini\node_modules\png-img\build\png_img.vcxproj]
..\src\PngImg.cc(113): warning C4244: =: преобразование "const short" в "png_byte", возможна потеря данных [C:\Users\a.kushnarev\AppData\Ro
aming\npm\node_modules\gemini\node_modules\png-img\build\png_img.vcxproj]
..\src\PngImg.cc(114): warning C4244: =: преобразование "const short" в "png_byte", возможна потеря данных [C:\Users\a.kushnarev\AppData\Ro
aming\npm\node_modules\gemini\node_modules\png-img\build\png_img.vcxproj]
..\src\PngImg.cc(115): warning C4244: =: преобразование "const short" в "png_byte", возможна потеря данных [C:\Users\a.kushnarev\AppData\Ro
aming\npm\node_modules\gemini\node_modules\png-img\build\png_img.vcxproj]
..\src\PngImg.cc(117): warning C4244: =: преобразование "const short" в "png_byte", возможна потеря данных [C:\Users\a.kushnarev\AppData\Ro
aming\npm\node_modules\gemini\node_modules\png-img\build\png_img.vcxproj]
     ╤ючфрхЄё  сшсышюЄхър C:\Users\a.kushnarev\AppData\Roaming\npm\node_modules\gemini\node_modules\png-img\build\Release\png_img.lib ш юс·
  хъЄ C:\Users\a.kushnarev\AppData\Roaming\npm\node_modules\gemini\node_modules\png-img\build\Release\png_img.exp
  ╤ючфрэшх ъюфр
  ╤ючфрэшх ъюфр чртхЁ°хэю
  png_img.vcxproj -> C:\Users\a.kushnarev\AppData\Roaming\npm\node_modules\gemini\node_modules\png-img\build\Release\\png_img.node
npm ERR! fetch failed https://registry.npmjs.org/expect.js/-/expect.js-0.3.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/forever/-/forever-0.11.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/minimist/-/minimist-0.2.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/tsort/-/tsort-0.0.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/express/-/express-4.10.6.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/semver/-/semver-2.3.2.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/request/-/request-2.51.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/caniuse-db/-/caniuse-db-1.0.20140710.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/uglify-js/-/uglify-js-2.4.16.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/useragent/-/useragent-2.1.3.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/handlebars/-/handlebars-1.3.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/lodash/-/lodash-2.4.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/q/-/q-1.1.2.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/request-promise/-/request-promise-0.3.2.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/es6-set/-/es6-set-0.1.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/moment/-/moment-2.8.4.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/6to5/-/6to5-1.15.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/mocha/-/mocha-1.21.5.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/expect.js/-/expect.js-0.3.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/forever/-/forever-0.11.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/minimist/-/minimist-0.2.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/lodash/-/lodash-2.4.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/semver/-/semver-2.3.2.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/express/-/express-4.10.6.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/tsort/-/tsort-0.0.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/q/-/q-1.1.2.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/useragent/-/useragent-2.1.3.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/request/-/request-2.51.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/handlebars/-/handlebars-1.3.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/uglify-js/-/uglify-js-2.4.16.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/caniuse-db/-/caniuse-db-1.0.20140710.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/request-promise/-/request-promise-0.3.2.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/6to5/-/6to5-1.15.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/moment/-/moment-2.8.4.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/es6-set/-/es6-set-0.1.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/mocha/-/mocha-1.21.5.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://registry.npmjs.org/expect.js/-/expect.js-0.3.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/minimist/-/minimist-0.2.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/semver/-/semver-2.3.2.tgz
npm ERR! fetch failed https://registry.npmjs.org/forever/-/forever-0.11.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/lodash/-/lodash-2.4.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/request/-/request-2.51.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/tsort/-/tsort-0.0.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/useragent/-/useragent-2.1.3.tgz
npm ERR! fetch failed https://registry.npmjs.org/q/-/q-1.1.2.tgz
npm ERR! fetch failed https://registry.npmjs.org/handlebars/-/handlebars-1.3.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/express/-/express-4.10.6.tgz
npm ERR! fetch failed https://registry.npmjs.org/uglify-js/-/uglify-js-2.4.16.tgz
npm ERR! fetch failed https://registry.npmjs.org/caniuse-db/-/caniuse-db-1.0.20140710.tgz
npm ERR! fetch failed https://registry.npmjs.org/request-promise/-/request-promise-0.3.2.tgz
npm ERR! fetch failed https://registry.npmjs.org/es6-set/-/es6-set-0.1.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/moment/-/moment-2.8.4.tgz
npm ERR! fetch failed https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/mocha/-/mocha-1.21.5.tgz
npm ERR! fetch failed https://registry.npmjs.org/6to5/-/6to5-1.15.0.tgz
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "node" "C:\\Users\\a.kushnarev\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "gemini@latest"
npm ERR! node v0.12.5
npm ERR! npm  v2.12.1

npm ERR! fetch failed with status code 401
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\a.kushnarev\AppData\Roaming\npm\npm-debug.log

C:\Users\a.kushnarev\AppData\Roaming\npm>

**Comment by gopalisoft** [comment]
Hi, Are you able to install gemini? I am facing same problem. If yes, can you please help me?

**Comment by legodude17** [comment]
Check your internet connection and update `npm`.
