### ISSUE TITLE
Add a "progress" event to API.

### ISSUE THREAD

**Issue by spetrenko** [npm/npm#8833]
Hi.

   Progress bar looks nice, but, for example, I use npm programmatically and since I have slow internet connection, it would be very useful to report an operation progress via npm API also. Up to now I use following solution:

```
diff --git a/lib/npm.js b/lib/npm.js
index 180e3d4..6bf028e 100644
--- a/lib/npm.js
+++ b/lib/npm.js
@@ -283,6 +283,10 @@
       }
     }
 
+    log.tracker.on('change', function() {
+      npm.emit('progress', log.tracker.completed())
+    })
+
     log.pause()
 
     load(npm, cli, cb)
```

Could this functionality be added to the main branch in one or another form? Thanks!

**Comment by iarna** [comment]
`npmlog` is a singleton, so you could actually just require it yourself and then run that code w/o having to patch `npm` itself.

**Comment by iarna** [comment]
Closing this as we are not going to add change events to the unsupported API.
