### ISSUE TITLE
Speeding up `npm install` in docker

### ISSUE THREAD

**Issue by olalonde** [npm/npm#8836]
I'm using a `Dockerfile.dev` file for Node.js development and am using the following "trick" to only `npm install` when `package.json` is modified:

``` dockerfile
COPY package.json /src/
RUN npm install --unsafe-perm
COPY . /src
```

However, as I frequently install new modules and the `npm install` is quite slow, this is not good enough. I've tried mounting my local `node_modules` as a mounted volume but it seems `npm install` installs everything from scratch regardless of whether there are already installed modules in `node_modules/`. Is this correct? in this case, are there any flags or commands I can use to only `npm install` modules which aren't already present in `node_modules/`? Would mounting `./docker_npm_cache:/root/.npm` in the Docker container be another suitable option?

**Comment by vectart** [comment]
Got this problem, too

**Comment by blackjackcf** [comment]
@olalonde, @vectart - npm install is very, very slow in Docker.

I found what helped was caching the npm install layer and pointing npm to a registry (I use a private repository, but I found just using npm registry sped things up too), so:

    WORKDIR /tmp
    ADD package.json /tmp/
    RUN npm config set registry https://www.npmjs.com/package/npm-registry
    RUN npm install
    RUN cp -a /tmp/node_modules /app/

**Comment by nmccready** [comment]
Which version of npm are you using? Just double checking w 2.X vs 3.X as 3.X is much much slower.

**Comment by brownoxford** [comment]
I'm seeing the same issue being reported by @olalonde, I'm just using docker as a container run npm install as part of a build process for my app:

```bash
docker run --rm -v $(pwd):/app -w /app node:4.2.1 npm install
```

No matter what I do this keeps installing everything from scratch... This image provides npm v2.14.7 and node v4.2.1.

**Comment by olalonde** [comment]
I've been using this Dockerfile as a workaround for not always having to build everything from scratch as long as my package.json hasn't changed. It's still slow though and I ended up giving up on Docker for local Node.js development. I'm now only using Docker to run backend services like postgres or rabbitmq and running the Node.js code locally.

```Dockerfile
FROM node:0.12

RUN mkdir -p /app
WORKDIR /app

ENV PATH=/app/node_modules/.bin:$PATH

# We add package.json first so that the
# image build can use the cache as long as the
# contents of package.json hasn't changed.

COPY package.json /app/
RUN npm install --ignore-scripts --unsafe-perm

COPY . /app

CMD npm run postinstall && npm start
EXPOSE 5000
```

**Comment by cancan101** [comment]
I believe that I am seeing similar slowness (I am using docker-machine with Virtualbox). This might be related: http://qiita.com/neofreko/items/c36b3fd14dc77ab18a1a.

**Comment by withinboredom** [comment]
It has to do with how docker uses shared volumes. The disk volume is extremely slow. I haven't tried copying the package.json to a directory elsewhere and doing the npm install there, then copying the node_modules back. I'll report here after I do.

**Comment by NickClark** [comment]
I've reverted to just using a symbolic link to my dependencies instead of copying them.

**Comment by max-mykhailenko** [comment]
Nobody use docker for npm? With `npm install`time around 30+ minutes all docker stuff should burn in hell :) How I can improve performance and why it's so slow?

**Comment by Andyccs** [comment]
Hi @max-mykhailenko , currently I found out that solution by @blackjackcf above is the best work around.

**Comment by mariohmol** [comment]
I have same problem! Using @blackjackcf  helped a little, but is quite the same. For a building in other environments (stagin.. productio) its ok to install all again. but for local development is crazy!

**Comment by Misterhex** [comment]
+1 out of the box yeoman angular-fullstack take over 30 minutes to install..

**Comment by mariohmol** [comment]
What we did that made a LOT of difference is to change the network configuration in the docker VM. You have to change from NAT to Bridge and this happens just in MAC. Now i can make all installs in 5 minutes.

**Comment by vjpr** [comment]
My `node_modules` is 400MB. An `npm install` from scratch takes a life time to finish (30mins+).

If you really want to speed up the `npm install` during the Dockerfile build process, you can copy your existing `node_modules` from your host machine to your Docker image over ssh.

This allows you to build a `node_modules` from scratch natively (or use your existing dev `node_modules`) on your host which is fast-*er*.

So basically you never have to wait for an unneccesary `npm install` anymore. This is useful for when you want to debug while preparing a production Dockerfile for your CI, or gold-master build process.

If I used Docker for dev (I prefer to develop natively) I would use a `docker-machine-nfs` and run `npm install` on a running container using an NFS volume.

Here is the code:

```
RUN mkdir -p /var/www/current
WORKDIR /var/www/current

COPY package.json .

ARG HOST_SSH="user@your-host-ip"
ARG HOST_ROOT="full-path-to-your-source-code-on-host"
ARG HOST_SSH_PASSWORD="ssh-password"

RUN apt-get install -y sshpass
RUN set -x && sshpass -p $HOST_SSH_PASSWORD ssh -o StrictHostKeyChecking=no $HOST_SSH "tar -zc -C $HOST_ROOT node_modules" | tar -zx --verbose -C /var/www/current/
# Remove `npm link`ed dependencies.
RUN find node_modules -maxdepth 1 -type l -exec rm -f {} \;

# Takes 1 minute.
RUN npm install

# Takes another minute.
RUN npm rebuild
```

And a script to run it. NOTE: You must run this script from your context.

```
#!/bin/sh

set -x

BASEDIR=$(dirname $0)

docker build \
--file $BASEDIR/Dockerfile \
--tag foo \
--build-arg HOST_SSH=xxx HOST_ROOT=xxx HOST_SSH_PASSWORD=xxx \
.
```

**Comment by blackjackcf** [comment]
Another thing that might potentially alleviate the speed is this related issue: https://github.com/npm/npm/issues/11283#issuecomment-175246823. Apparently, the progress bar in npm 3 significantly slows down the npm install process. Turning it off might give it another bit of a speed boost.

**Comment by mariohmol** [comment]
My problem was a network problem, some connections was not closing and npm opens thousands of simultaneos connections.. if you check using nettop you can see it.

The problem with @vjpr is if you use OSX as dev machine and linux as VM, you cant just copy you have to compile again

**Comment by vjpr** [comment]
@mariohmol You can. You just have to run `npm rebuild` as it does in the script.

**Comment by mariohmol** [comment]
True, in my case that is a problem with downloading.. this is a good solution!! =)

**Comment by vjpr** [comment]
I have found a new approach...

1. Create a [data volume container](https://docs.docker.com/engine/userguide/dockervolumes/#creating-and-mounting-a-data-volume-container).

```bash
docker create -v /tmp/app --name foo-app--node-modules ubuntu
```

2. Mount your `package.json` file inside a temporary container one dir below your data volume container mount location

```bash
docker run \
--rm \ 
--volumes-from=foo-app--node-modules \
-v $PWD/package.json:/tmp/app/package.json:ro \
node:4.2.6 \
/bin/bash -c "cd /tmp/app/; npm install"
```

E.g. The file structure inside the temporary vm will look like this:-

```
- /tmp/app
  - package.json  <- host file from project context mount
  - /node_modules <- data volume container mount point (set during `docker create -v ...`)
```

3. Build your Node.js Docker image.

```.dockerignore
node_modules
.git
etc.
```

```Dockerfile
FROM node:4.2.6
WORKDIR /app
COPY . .
RUN ln -s /tmp/app/node_modules node_modules
```

```
docker build -t foo-app
```

4. Run with data volume container.

```
docker run --volumes-from=foo-app--node-modules foo-app /bin/bash -c "node index.js"
```

**Comment by bpanahij** [comment]
What I've done in the past is to have two Dockerfiles:

The first Dockerfile builds an image with just the package.json copied to /src/package.json, and an npm install in src. That creates a node_modules directory in /src.

Then I base a second Dockerfile from the first image, and copy the source files, to a subdirectory of /src, for instance /src/my-app/

Dockerfile:
FROM first-image
...

I only rebuild the first image when I change dependencies.

**Comment by imdevin567** [comment]
I was having this issue with the official node images from Docker, so I switched to an image based off of Alpine Linux. Amazingly, my npm installs are now **at least** 6x faster than what they used to be. The major difference between the two is logging: the Alpine-based image only logs warnings, whereas the official image has verbose logging. This may be related to what @blackjackcf mentioned above.

In any case, I would recommend turning off logging and seeing if that speeds up the installs.

**Comment by rauchg** [comment]
@imdevin567 I find the same thing. +1 on this tip.

**Comment by mariuslundgard** [comment]
Was there really a reason to close this issue?

**Comment by Andyccs** [comment]
@mariuslundgard I am not in charge of this issue, but I have been following this for a while now. I have no idea why, but after switching to nodejs 5 or 6, I don't have such issue anymore.

**Comment by hpurmann** [comment]
@mariuslundgard It's not closed. The above notice is just a reference to another issue which is closed.

**Comment by Dev-Dipesh** [comment]
This is what I'm doing - 

```
FROM node:4.4.4

# use changes to package.json to force Docker not to use the cache
# when we change our application's nodejs dependencies:
ADD package.json /tmp/package.json

RUN cd /tmp && npm i --production --ignore-scripts --unsafe-perm
RUN cd /tmp && npm i --only=dev --ignore-scripts --unsafe-perm
RUN npm i -g pm2 nodemon gulp gulp-cli

RUN mkdir -p /opt/app && cp -a /tmp/node_modules /opt/app/

# From here we load our application's code in, therefore the previous docker
# "layer" thats been cached will be used if possible
WORKDIR /opt/app

ADD . /opt/app

RUN chmod +x /opt/app/configure-node.sh

EXPOSE 3000

CMD ["/opt/app/configure-node.sh"]
```
Separate installation of dev & prod helps me escape from out of space problems, else I've to create swap and do a bunch of fixes.

`--only=dev` ask npm to not install all devDependencies recursively - https://github.com/npm/npm/issues/5554

Using `/tmp` helps in getting the benefit of Docker layers and caching - http://bitjudo.com/blog/2014/03/13/building-efficient-dockerfiles-node-dot-js/

**NOTE:** I've not set ENV variable yet in this file, which you can set and accordingly install only respective dependencies.

**Comment by arypurnomoz** [comment]
how about using the `--cache-min` option?

**Comment by chippawah** [comment]
Is there really not an official solution nearly a year after opening this issue? It seems like there's about to be a mass flood to Docker and a really poor dev experience if you want to use node.

**Comment by olalonde** [comment]
@chippawah as the guy who opened this issue, the problem is largely "solved" for me... I run my node code locally and only use docker for things like databases, etc. It would be cool if I could run my node code in docker as well but yeah, it still is a poor experience. I use docker + node in production but the build is handled by http://deis.io/

**Comment by puppybits** [comment]
I run a pre-build script to keep docker's cache working as expected. This will skip `npm install` until the dependencies change. My build times for docker are also < 10s (unless I add/remove a dependency).

package.json  

    "build": "node -e \"require('fs').writeFileSync('.deps.json',JSON.stringify({dependencies:require('./package.json').dependencies}))\" && docker build -t my/image .",

Dockerfile  

    # .deps.json only has the dependencies from the package.json.
    COPY deps.json /app/package.json
    # Docker will use the cache until the dependencies in the package.json have changed
    RUN npm install
    
    # this next line will bust the cache when anything changes but the copies are quick
    COPY package.json /app/package.json
    COPY src /app/src
    CMD npm start

**Comment by krukid** [comment]
The simplest thing you can do to speed up your builds is double-cache your npm modules, i.e.:

```Dockerfile
# ...

# install from shadow .package.json (notice the dot)
ADD .package.json /tmp/package.json
RUN cd /tmp && npm install

# install from actual package.json
ADD package.json /tmp/package.json
RUN cd /tmp && npm install

# ...
```

Then, whenever your build gets slow again, just `cp package.json .package.json` and rebuild the whole thing once.

**Comment by rlabrecque** [comment]
So my workaround for this is to just do this all at runtime, not build time. I actually ditched my Dockerfile completely and just went with docker-compose with a huge `command:` that does everything my Dockerfile did. Start up is a little slower obviously, and I probably can't use run anymore but this works well for my needs.

**Comment by steinbachr** [comment]
also had this problem. For me, updating the image to use the most recent version of Node (v 6.x) yielded an immediate speedup

**Comment by agilgur5** [comment]
In case anyone hasn't heard of it, [Rockerfiles](https://github.com/grammarly/rocker) solve this problem with their [`MOUNT`](https://github.com/grammarly/rocker#mount) directive, which lets you mount a volume _during_ your Docker build (in this case, your previous `node_modules` volume). It has a ton of other useful features to deal with common problems in Docker as well.

**Comment by sanmai-NL** [comment]
You also use [Packer](https://www.packer.io/), this builds images inside a container so you can mount volumes during build as well.

**Comment by pallickal** [comment]
I've managed a solution using rocker and yarn. Rocker allows mounting files and directories during build, and yarn is a new npm alternative that has a cache directory and an offline mode. 

The trick is to mount a persistent yarn-cache sub-directory from the project, into the image during its build phase, using rocker. yarn.lock also needs to be mounted from the project's root folder in order for offline caching to work.

My goal was to be able to work totally offline, so I've also cached a download of yarn in my project folder rather than relying on accessing the unofficial Debian repository through apt-get in the Rockerfile.

First, in my package.json scripts section -
```
  "scripts": {
    "update-dev-cache": "mkdir -p dev-cache  && touch yarn.lock && wget -N -O dev-cache/yarn-latest.tar.gz https://yarnpkg.com/latest.tar.gz && mkdir -p dev-cache/yarn-latest && tar zvxf dev-cache/yarn-latest.tar.gz -C dev-cache/yarn-latest --strip-components=1 && test -e dev-cache/yarn-latest/bin/yarn",
    "rocker-build-dev": "rocker build -f Rockerfile.dev --build-arg YARN_OFFLINE=$YARN_OFFLINE"
  }
```
The less obvious parts of update-dev-cache are -

1. It creates a blank yarn.lock if none exists, so rocker does not try and create a directory called yarn.lock during mount.
2. It downloads the latest yarn tarball into the persistent dev-cache folder, and unpacks it into a consistent folder name so it can be mounted during build.

Here are the relevant parts of my Rockerfile
```
ARG YARN_OFFLINE

# Create app directory
RUN mkdir -p /usr/src/my-app-name
WORKDIR /usr/src/my-app-name

ADD ./dev-cache/yarn-latest/ /opt/yarn-latest/
RUN ln -s /opt/yarn-latest/bin/yarn /bin/

# Install app dependencies
COPY package.json ./package.json
MOUNT ./dev-cache/yarn-cache:/root/.yarn-cache
MOUNT ./yarn.lock:/usr/src/my-app-name/yarn.lock
RUN yarn ${YARN_OFFLINE:+--offline}
```
To work offline I run `export YARN_OFFLINE=true` in the shell before running the rocker-build-dev script in my package.json. `${YARN_OFFLINE:+--offline}` will only inject the --offline option to yarn if the YARN_OFFLINE build-arg is set to a non-empty value. The YARN_OFFLINE environment variable is passed on as a build-arg of the same name in the rocker-build-dev script, so that I don't have to edit package.json every time I want to work offline.

One caveat is that yarn is still very new and may have bugs. For example I still have to use npm run because of a bug that is not allowing a few of my scripts to run through yarn. A fix has been committed but has not propagated to an official release as of this writing.

**Comment by olalonde** [comment]
I just came up with this trick to speed up npm installs in docker (also plays well with CI/CD servers that don't cache image layers):

Dockerfile

```Dockerfile
# vim:set ft=dockerfile:
FROM node:6

# Create app directory
RUN mkdir -p /app
WORKDIR /app

# Create .npmrc (required for private registry)
RUN echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc

# Re-use npm cache to speedup installs

# Usually, "npm install" only runs when package.json changes due to cached
# layers. However, with .node_modules.tar.gz the cache will be busted twice
# after package.json changes (instead of just once) because
# the next docker build will see a different .node_modules.tar.gz

# This still speeds things in general, because npm install
# from scratch is slow. Also, it definitely speed things up
# in environments that don't benefit from cached image layers
# like CircleCI
COPY .node_modules.tar.gz /app/
# Only extract if file not empty
RUN test -s .node_modules.tar.gz \
  && tar xzf .node_modules.tar.gz -C /app \
  && echo "Extracted .node_modules.tar.gz to /app/node_modules" \
  || true

## Install app dependencies
COPY package.json /app/
ARG NPM_TOKEN
# make sure to remove unused packages in node_modules (in case we use a cache)
RUN npm prune
RUN npm install

# Bundle app source
COPY . /app

# Build
RUN npm run build

# If we don't remove this, npm start will fail if NPM_TOKEN is not set
# at run time
RUN rm .npmrc

EXPOSE 5000

CMD [ "npm", "start" ]
```

Basically, the Dockerfile copies and extracts `.node_modules.tar.gz` which if it exists should be the `node_modules` directory from a previous build. I automatically generate `.node_modules.tar` when I build my images through a Makefile:

```Makefile
.PHONY: docker-build
# IMAGE := someimage/sometag
docker-build:
	# create empty .docker-npm-cache.tar.gz if not exists, otherwise,
	# COPY will fail in Dockerfile
	ls .node_modules.tar.gz || touch .node_modules.tar.gz
	docker build --pull \
		--build-arg NPM_TOKEN=${NPM_TOKEN} \
		-t ${IMAGE} .
	make docker-cache-node-modules

.PHONY: docker-cache-node-modules
# Extracts node_modules from the image so it is cached in subsequent builds
docker-cache-node-modules:
	rm -rf .node_modules.tar.gz
	docker create ${IMAGE} > .docker-id
	# -n flag required to make resulting file deterministic
	docker cp `cat .docker-id`:/app/node_modules - | gzip -n > .node_modules.tar.gz
	docker rm -v `cat .docker-id`
	rm .docker-id
```

**Comment by cachemoney** [comment]
@olalonde +1 for the whole Makefile

**Comment by olalonde** [comment]
```Makefile
# This is used for CI/CD deployment, not needed locally
# NPM_TOKEN must be set
# AWS_ACCOUNT_ID or PRIVATE_REGISTRY must be set
SHELL = /bin/bash

CIRCLE_PROJECT_REPONAME ?= $(shell basename "${PWD}")
IMAGE_PREFIX ?=
MUTABLE_VERSION ?= canary
VERSION ?= git-$(shell git rev-parse --short HEAD)
PRIVATE_REGISTRY ?= ${AWS_ACCOUNT_ID}.dkr.ecr.us-west-1.amazonaws.com
DOCKER_BUILD_RM ?= true

SHORT_NAME:= ${CIRCLE_PROJECT_REPONAME}
IMAGE := ${PRIVATE_REGISTRY}/${IMAGE_PREFIX}${SHORT_NAME}:${VERSION}
MUTABLE_IMAGE := ${PRIVATE_REGISTRY}/${IMAGE_PREFIX}${SHORT_NAME}:${MUTABLE_VERSION}

info:
	@echo "Build tag:       ${VERSION}"
	@echo "Immutable image: ${IMAGE}"
	@echo "Mutable image:   ${MUTABLE_IMAGE}"

build: docker-build
push: docker-push
release: docker-push-mutable

.PHONY: run
run:
	docker run -d -p 5000:5000 ${IMAGE}

.PHONY: run-interactive
run-interactive:
	docker run -it ${IMAGE} bash

.PHONY: run-test
run-test:
	npm run docker:bootstrap
	docker-compose run test

.PHONY: test
test: docker-build run-test

.PHONY: docker-build
docker-build:
	# create empty .node_modules.tar.gz if not exists, otherwise,
	# COPY will fail in Dockerfile
	ls .node_modules.tar.gz || touch .node_modules.tar.gz
	docker build --pull \
		--rm=${DOCKER_BUILD_RM} \
		--build-arg NPM_TOKEN=${NPM_TOKEN} \
		-t ${IMAGE} .
	rm .node_modules.tar.gz
	docker tag ${IMAGE} ${SHORT_NAME}:test

.PHONY: docker-cache-node-modules
# Extracts node_modules from the image so it is cached in subsequent builds
docker-cache-node-modules:
	rm .node_modules.tar.gz || true
	docker create ${IMAGE} > .docker-id
	# -n flag required to make resulting file deterministic
	docker cp `cat .docker-id`:/app/node_modules - \
		| gzip -n > .node_modules.tar.gz.part \
		&& mv .node_modules.tar.gz.part .node_modules.tar.gz
	docker rm -v `cat .docker-id` || true
	rm .docker-id

.PHONY: docker-push
docker-push:
	docker push ${IMAGE}

.PHONY: docker-push-mutable
docker-push-mutable:
	docker tag ${IMAGE} ${MUTABLE_IMAGE}
	docker push ${MUTABLE_IMAGE}
```

**Comment by ORESoftware** [comment]
symbolic link is smart solution, also NODE_PATH might work

**Comment by abdennour** [comment]
https://www.digitalocean.com/community/questions/npm-gets-killed-no-matter-what
