### ISSUE TITLE
conflict package.json --- it seems problem with karma

### ISSUE THREAD

**Issue by BahramN** [npm/npm#8845]
I have installed latest nodejs v0.12.6 and grunt-cli , bower and yo with generator-angular and generator-karma  on ubuntu but when I use " yo angular " shows error conflict package.json

**Comment by KenanY** [comment]
@BahramN Is this an issue with `npm` or `yo`?

**Comment by BahramN** [comment]
yo probably

**Comment by snopeks** [comment]
Hi @BahramN! Since this is related to `yo` rather than `npm`, I recommend raising this issue with the `yo` package authors, they'll be more able to help you out. https://github.com/yeoman/yo 

If you notice any npm-related errors please open another issue and we will be happy to help. Thanks!
