### ISSUE TITLE
'*' should match latest when there are only prerelease versions

### ISSUE THREAD

**Issue by iarna** [npm/npm#8855]
npm v2.11.2 introduced [a change](https://github.com/npm/node-semver/issues/123) from semver@4.3.5 which caused '*' to stop matching prerelease versions. This is well and good, until you have a package that's never had a non-prerelease version, at which point it would be reasonable to pick up latest instead.

**Comment by KenanY** [comment]
I believe this should be fixed now that https://github.com/npm/npm/pull/8857 has been merged and released in [`npm@2.13.1`](https://github.com/npm/npm/releases/tag/v2.13.1).

**Comment by iarna** [comment]
Ah, yes, agreed, good catch.
