### ISSUE TITLE
NPM Cordova 5.1.1 Android Gradle build: peer not authenticated for maven repository

### ISSUE THREAD

**Issue by sumitsoman** [npm/npm#8860]
I am trying to use the command cordova build android but am getting the following error:

 A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:1.0.0+.
 Required by:
     :android:unspecified
  > Failed to list versions for com.android.tools.build:gradle.
     > Unable to load Maven meta-data from https://repo1.maven.org/maven2/com/android/tools/build/gradle/maven-metadata.xml.
        > Could not GET 'https://repo1.maven.org/maven2/com/android/tools/build/gradle/maven-metadata.xml'.
           > peer not authenticated

How do I resolve this issue? Where can I set gradle to use http instead of https? 

I tried changing the build.gradle file in the project folder to use classpath 'com.android.tools.build:gradle:1.1.0+' but that didn't help.

**Comment by othiym23** [comment]
These error messages aren't coming from npm, and unfortunately I don't know enough about Gradle to be able to tell you what its error messages mean, although if I had to guess I'd say this is something related to proxy configuration. Perhaps the kind people of the Cordova community could help you out? Good luck!

**Comment by SherlockStoneed** [comment]
These error aren't coming from Gradle, but from Java SSL Security :)

View my solution here : [Error occuring when build for android with cordova](https://github.com/meteor/meteor/issues/6362#issuecomment-189852511)
