### ISSUE TITLE
global install of scoped packages cannot run scripts

### ISSUE THREAD

**Issue by tcort** [npm/npm#8862]
Any time a scoped package tries to run something in the `install` script (even the implicit `node-gyp rebuild`), `npm` warns that it cannot run in the working directory. At first I thought it was a permissions issue (issue #3497); however, it doesn't affect the same package with a non-scoped package name (those work fine).

Steps to reproduce:

```
git clone https://github.com/schamane/node-syslog.git
cd node-syslog
sudo npm install -g # Works great!
$EDITOR package.json # change `name` from `node-syslog` to `@foo/node-syslog`
sudo npm install -g # npm WARN cannot run in wd @foo/node-syslog@1.2.0 node-gyp rebuild (wd=...
```

Tried with npm 2.1.9, 2.11.2, 2.12.1 and node 0.10.28, 0.10.32, and 0.12.6.

I don't think it's just me. I found another person with the same issue nodejs/docker-iojs#72

**Edit** still happens with iojs v2.3.3 and npm v3.1.0

**Comment by tcort** [comment]
Just looking at the code, on line 51 of `lib/utils/lifecycle.js` it's comparing the base name of the working directory to the package name:

```
    if ((wd.indexOf(npm.dir) !== 0 || path.basename(wd) !== pkg.name) &&
        !unsafe &&
        pkg.scripts[stage]) {
      log.warn(
        'cannot run in wd',
        '%s %s (wd=%s)', pkg._id, pkg.scripts[stage], wd
      )
      return cb()
    }
```

In my example above, the condition `path.basename(wd) !== pkg.name` is always always true for scoped packages because `path.basename('@foo/node-syslog')` returns the last path component `node-syslog` (i.e. without the scope) and `pkg.name` is `@foo/node-syslog` (i.e. with the scope). That's why the warning (and skipped script execution) happens with scoped packages and not with non-scoped packages. I'll put together a patch and pull request later today.

**Comment by othiym23** [comment]
Thanks for investigating, and a patch would be most welcome, especially if it includes a test!

**Comment by codvio** [comment]
it gives warning for gifsicle when its dependency of imagemin-gifsicle. Because wd.indexOf(pkg.name) gives first occurance value.


```
    if ((wd.indexOf(npm.dir) !== 0 ||
          wd.indexOf(pkg.name) !== wd.length - pkg.name.length) &&
        !unsafe && pkg.scripts[stage]) {
      log.warn( "cannot run in wd", "%s %s (wd=%s)"
              , pkg._id, pkg.scripts[stage], wd)
      return cb()
    }
```

The values:

```
wd: /tmp/client/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle
npm.dir: /tmp/client/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules
wd.indexOf(npm.dir): 0
wd.indexOf(pkg.name): 92
wd.length - pkg.name.length: 114
unsafe: false
pkg.scripts[stage]: node lib/install.js
```
92 != 114 so it gives warning.

i changed the method indexOf to lastIndexOf and it works now.

```
    if ((wd.indexOf(npm.dir) !== 0 ||
          wd.lastIndexOf(pkg.name) !== wd.length - pkg.name.length) &&
        !unsafe && pkg.scripts[stage]) {
      log.warn( "cannot run in wd", "%s %s (wd=%s)"
              , pkg._id, pkg.scripts[stage], wd)
      return cb()
    }
```

**Comment by TomFreudenberg** [comment]
@codvio 

I can confirm that changing the method to `lastIndexOf` does also solve the attached error on ARM architecture when using node v0.10.45 and npm v2.15.1

Thanks for this post
Tom
