### ISSUE TITLE
npm not updating to latest version

### ISSUE THREAD

**Issue by leandroong** [npm/npm#8867]
```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Windows\system32>node -V
node: bad option: -V

C:\Windows\system32>node -v
v0.12.6

C:\Windows\system32>npm install -g npm
C:\Users\lean\AppData\Roaming\npm\npm -> C:\Users\lean\AppData\Roaming\npm\node_
modules\npm\bin\npm-cli.js
npm@2.12.1 C:\Users\lean\AppData\Roaming\npm\node_modules\npm

C:\Windows\system32>npm -v
2.11.2

C:\Windows\system32>
```

**Comment by leandroong** [comment]
same issue with dispatch-proxy, version shows 0.1.2 instead of 3.1.3
command use: npm update -g dispatch-proxy

**Comment by othiym23** [comment]
Updating npm on Windows can be [a little tricky](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows). Follow those instructions (that new script from Microsoft OpenTech looks pretty nifty!) and let us know if they help you out!

**Comment by leandroong** [comment]
In System variables PATH, there is no %appdata%\npm. Adding that fixed the problem
".. ;C:\Users\lean\AppData\Roaming\npm;C:\Program Files\nodejs\ "

"
C:\Windows\system32>npm install -g npm
C:\Users\lean\AppData\Roaming\npm\npm -> C:\Users\lean\AppData\Roaming\npm\node_
modules\npm\bin\npm-cli.js
npm@2.12.1 C:\Users\lean\AppData\Roaming\npm\node_modules\npm

C:\Windows\system32>npm -v
2.12.1
"
++++++++++++
Regarding dispatch-proxy, version not updating

"
C:\Windows\system32>npm update -g dispatch-proxy
C:\Windows\system32>dispatch -V
0.1.2

C:\Windows\system32>npm install -g dispatch-proxy
C:\Users\lean\AppData\Roaming\npm\dispatch -> C:\Users\lean\AppData\Roaming\npm\
node_modules\dispatch-proxy\bin\dispatch.js
dispatch-proxy@0.1.3 C:\Users\lean\AppData\Roaming\npm\node_modules\dispatch-pro
xy
├── commander@2.0.0
├── tmpl-log@0.0.3
└── socks-handler@0.2.1 (ip@0.1.0, through@2.3.4)

C:\Windows\system32>dispatch -V
0.1.2
"

**Comment by iarna** [comment]
Great! Closing this as resolved.
