### ISSUE TITLE
npm@3 global install issues in node 0.12.6, windows 7

### ISSUE THREAD

**Issue by lukeapage** [npm/npm#8869]
Hi,

I updated to npm 3.1 and I'm getting all sorts of issues.

Its happened on 2 different computers now, similar symptoms. Both node 0.12.x and windows 7. I get eperm errors e.g.

```
Error: EPERM, mkdir 'c:\Program Files (x86)\nodejs\node_modules\.staging'
    at Error (native)
 { [Error: EPERM, mkdir 'c:\Program Files (x86)\nodejs\node_modules\.staging']
  errno: -4048,
  code: 'EPERM',
  path: 'c:\\Program Files (x86)\\nodejs\\node_modules\\.staging' }
```

Then I try to global install npm back to 2.11.x and it fails with the same problems, then at some point it corrupts the npm v3 install and I can not run npm any longer

```
$ npm
module.js:338
    throw err;
          ^
Error: Cannot find module 'c:\Program Files (x86)\nodejs\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (module.js:336:15)
```

So I re-install node and overwrite npm back.

Are these known issues or do you need me to investigate? I'm running as admin.

**Comment by iarna** [comment]
Hi, so nope, this isn't a known issue– it doesn't happen with my windows install. Can you tell me exactly what command you ran for the first error? Given the directories I assume `npm i -g something`?

Does `mkdir c:\"Program Files (x86)"\nodejs\node_modules\.staging` work for you from the command line?

**Comment by lukeapage** [comment]
mkdir works fine
```
$ mkdir c:\Program\ Files\ \(x86\)\nodejs\node_modules\.staging
```

I am trying to reproduce and no longer get that exact error with a different package, it might depend on what I am installing... Will get back to you on that tomorrow. I can reproduce the 2nd issue though.

```
# with admin
npm install npm@3.1 -g
# without admin
npm install npm@3.0 -g
# npm fails and npm is now broken
```

**Comment by lukeapage** [comment]
The first issue btw it was node-inspector and it fails to compile and falls
back during post install.

**Comment by lukeapage** [comment]
@iarna I investigated a bit more...

`fs.access` on windows does not appear to be respecting admin mode, when asking for whether access permission is allowed on *directories*. Files work fine, but directories fail. 

For directories it seems to be returning no `W_OK` access on all directories other than the ones under my user folder...

If I move the 

```
if (process.platform === 'win32') return done()
```

to the `hasWriteAccess` function, so it bypasses fs.access, then I don't get problems.

**Comment by lukeapage** [comment]
raised a bug for node - https://github.com/joyent/node/issues/25657

but I guess you will have to work around it? :(

**Comment by lukeapage** [comment]
I tracked it down to a libuv bug - see linked node.js bug. 
The fix already in libuv treats all win32 directories as writable..  Meaning even after this is fixed, in win32 fs. access on directories is not 100% reliable.

**Comment by iarna** [comment]
@lukeapage: Oh geez, thanks for tracking this down! I guess we'll have to generally use the fallback on win32

**Comment by lukeapage** [comment]
this is okay now in 3.1.3.
I'm going raise a seperate bug for the `npm install npm -g` w/o admin issue, if there isn't one already
