### ISSUE TITLE
npm ls should show dependencies loaded from parent folder

### ISSUE THREAD

**Issue by kkaefer** [npm/npm#887]
`npm ls` currently only traverses rom the cwd down, but does not show dependencies that are loaded from parent folder's `node_modules` directories.

**Comment by peter-mouland** [comment]
old issue, but is this relevant any more since `npm 3` is flat rather than nesting node_modules?
Also i suspect `npm link` is the preferred way to link to modules that are not within your dir-structure (rather than relying on parents)?

**Comment by yhaskell** [comment]
Is this not fixed yet?
```
~/test-npm-subdir-ls $ ls
node_modules/ package.json  subdir/
~/test-npm-subdir-ls $ npm ls
test-npm-subdir-ls@1.0.0 /Users/yhaskell/test-npm-subdir-ls
└── leftpad@0.0.0 extraneous

~/test-npm-subdir-ls $ cd subdir/
~/test-npm-subdir-ls/subdir $ ls
~/test-npm-subdir-ls/subdir $ npm ls
test-npm-subdir-ls@1.0.0 /Users/yhaskell/test-npm-subdir-ls
└── leftpad@0.0.0 extraneous

~/test-npm-subdir-ls/subdir $
```
