### ISSUE TITLE
msys2 / scoped private packages will not npm link

### ISSUE THREAD

**Issue by cchamberlain** [npm/npm#8874]
I've been having issues linking scoped packages recently.  I'm not sure if it was the upgrade to npm@3 or the other recent upgrade to msys2 (was using msysgit prior).  I know msys2 / cygwin / etc. is unsupported but I'm stuck with it at work and seems like it could be a valid bug on other platforms unless I'm overlooking something.

Issue was it was throwing regarding `Cannot read property '0' of undefined` because lib/link.js was attempting to compare `path.resolve(folder, '..') === npm.globalDir`.  Since its a scoped package I'm linking, it needed to traverse up two levels instead and was effectively comparing `npm.globalDir + '@tixinc' === npm.globalDir`.

Here is pastebin of output from running `npm link ../ext` (where ext is private scoped module @tixinc/ext) - http://pastebin.com/raw.php?i=khHxFqzL

I was able to fix in this fork by adding a check to see if there is a private scoped module in the folder path, and if so, I run a second path.resolve to traverse up an extra level.  Tested and working for me with a few different scoped package links. - https://github.com/npm/npm/compare/master...cchamberlain:master

If this is msys2 specific I'm fine carrying on this fork since it's working for me, but if this can be of benefit I can squash the commits and cleanup the code for a pull request.

![image](https://cloud.githubusercontent.com/assets/424694/8589992/ec857de2-25d0-11e5-848f-7350f5b10cd7.png)

**Comment by iarna** [comment]
That's a 3.x bug for sure– I'll fix that for next weeks release! Thanks for catching this!

**Comment by cchamberlain** [comment]
Awesome, I'm relieved it is not specific to my FrankensteinOS. =]

Thanks!

**Comment by iarna** [comment]
The fix for this landed in master with fdb360f and in 3.1.3.
