### ISSUE TITLE
Can't install cordova + spawn ENOENT visual studio 2015 RC

### ISSUE THREAD

**Issue by rainpher** [npm/npm#8875]
Faced issues regarding npm. When i try to build a HelloWorld Apache Cordova project in Visual Studio 2015 RC, i keep on getting spawn ENOENT error while vs trying to install global packages. Found no exact solution from internet ( there's a solution dealing with vs-mda but my VS folder doesn't contain that! (only vs-tac exist). 

Then i look around into system folder and found that my cordova folder in node_modules\cordova\bin doesn't contain anything. then i try to install with "npm install -g cordova", it gives the following error.

<pre>C:\windows\system32>npm install -g cordova
npm ERR! Error: EISDIR, open 'C:\Users\Rainpher\AppData\Roaming\npm-cache\cordov
a'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program File
s (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
npm ERR! cwd C:\windows\system32
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! path C:\Users\Rainpher\AppData\Roaming\npm-cache\cordova
npm ERR! code EISDIR
npm ERR! errno 28
npm ERR! not ok code 0
</pre>

Please help me with these issues. I'm stuck for 1 week in setting up IDE for cordova and can't do a HelloWorld yet.

**Comment by M4cJunk13** [comment]
I too am banging my head over this. 5 Days now! Sorry, just a little frustrated :( Please help!

**Comment by rainpher** [comment]
At last, i felt despaired and restore my pc to factory state and start it all over again, and now it works.

But i still think there are better ways to fix this thing.
