### ISSUE TITLE
 npm install failed dont get why its happened error windows_nt 6.1.7601 nad other like version and proxy

### ISSUE THREAD

**Issue by sulema** [npm/npm#8877]
When I try to install any library this error always appears
Help !!
![problem](https://cloud.githubusercontent.com/assets/6723106/8591479/89ea2a8c-2663-11e5-982c-e261891e8f98.PNG)

**Comment by KenanY** [comment]
@sulema So, it looks like you might have set [`proxy`](https://docs.npmjs.com/misc/config#proxy) to `proxy.company.com`?

**Comment by sulema** [comment]
Hi , thanks for your response I use this 
npm config set proxy http://proxy.company.com:8080
npm config set https-proxy http://proxy.company.com:8080
but the window show me the same problem.

**Comment by KenanY** [comment]
@sulema Is your proxy actually `proxy.company.com`?

**Comment by sulema** [comment]
I dont know how to configure a proxy

**Comment by KenanY** [comment]
@sulema Configure a proxy itself or configure `npm` to use your proxy? I can only help with the latter....

**Comment by sulema** [comment]
Thanks, I use this

npm config set proxy http://wwwproxy.kanazawa-it.ac.jp:8080
npm config set https-proxy http://wwwproxy.kanazawa-it.ac.jp:8080

but now I have this problem tooo
![problema2](https://cloud.githubusercontent.com/assets/6723106/8715993/64661c5a-2bc5-11e5-9cbc-47e62aab8c22.PNG)
