### ISSUE TITLE
Deploy from travis fails with 500 + 404

### ISSUE THREAD

**Issue by justincy** [npm/npm#8879]
You can see it on this build: https://travis-ci.org/FamilySearch/familysearch-javascript-sdk/builds/70228176

```
npm ERR! publish Failed PUT 500
npm ERR! Error: unexpected status code: 404 : familysearch-javascript-sdk
npm ERR!     at RegClient.<anonymous> (/home/travis/.nvm/v0.10.39/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:308:14)
npm ERR!     at Request._callback (/home/travis/.nvm/v0.10.39/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:246:65)
npm ERR!     at Request.self.callback (/home/travis/.nvm/v0.10.39/lib/node_modules/npm/node_modules/request/request.js:236:22)
npm ERR!     at Request.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/home/travis/.nvm/v0.10.39/lib/node_modules/npm/node_modules/request/request.js:1142:14)
npm ERR!     at Request.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/home/travis/.nvm/v0.10.39/lib/node_modules/npm/node_modules/request/request.js:1096:12)
npm ERR!     at IncomingMessage.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:944:16
npm ERR!     at process._tickCallback (node.js:448:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>
npm ERR! System Linux 2.6.32-042stab090.5
npm ERR! command "/home/travis/.nvm/v0.10.39/bin/node" "/home/travis/.nvm/v0.10.39/bin/npm" "publish"
npm ERR! cwd /home/travis/build/FamilySearch/familysearch-javascript-sdk
npm ERR! node -v v0.10.39
npm ERR! npm -v 1.4.28
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/travis/build/FamilySearch/familysearch-javascript-sdk/npm-debug.log
npm ERR! not ok code 0
```

Any hints on what might be causing this? It's not a one-time fluke; it consistently happens. Though it is able to successfully detect when the version hasn't changed and therefore it doesn't need to update.

**Comment by justincy** [comment]
Might be related to some of the comments at the end of https://github.com/npm/npm/issues/7914

**Comment by justincy** [comment]
Looks like it was a problem with our token.

**Comment by rlucha** [comment]
Can you develop on how you solved it please?

**Comment by justincy** [comment]
@rlucha We just tried re-encrypting our token a few times until it worked. I guess somehow extra characters kept sneaking in.

**Comment by MrSwitch** [comment]
I downgraded my node version from ["0.12" to "0.10" in `.travis.yml`](https://github.com/MrSwitch/tricks/commit/cbf4fc67d0cd837dd1b91ba46e34419b8777bfdd#diff-354f30a63fb0907d4ad57269548329e3), because another script of mine could deploy from `0.10`. Perhaps its more likely an issue with the corresponding NPM package which is used 1.4.28 (rather than 2.11.3). In any case it now [succeeds with Travis](https://travis-ci.org/MrSwitch/tricks/builds/83452250#L669)
