### ISSUE TITLE
npm install writes the wrong path to package.json when installing from Windows network share

### ISSUE THREAD

**Issue by jimbolla** [npm/npm#8884]
Steps to reproduce:
1. Install a package stored on a windows network share, such as: `npm install \\pitasci5\c$\npm\AppCenter\2.1.0\ --save-dev`
2. This adds `"appcenter": "file:\\\\pitasci5\\c$\\npm\\AppCenter\\2.1.0",` to the packages.json file, and the appropriate files are added into the node_modules folder.
3. Delete the package from the node_modules folder
4. Run `npm install` and get the error:

```
63 error addLocal Could not install C:\c$\npm\AppCenter\2.1.0
64 verbose stack Error: ENOENT, open 'C:\c$\npm\AppCenter\2.1.0'
64 verbose stack     at Error (native)
65 verbose cwd C:\Users\bollaj\Projects\official\Amerinet.FacilityManager\dev\FacilityManager.WebApp2
66 error Windows_NT 6.1.7601
67 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
68 error node v0.12.5
69 error npm  v2.11.2
70 error path C:\c$\npm\AppCenter\2.1.0
71 error code ENOENT
72 error errno -4058
73 error enoent ENOENT, open 'C:\c$\npm\AppCenter\2.1.0'
73 error enoent This is most likely not a problem with npm itself
73 error enoent and is related to npm not being able to find a file.
74 verbose exit [ -4058, true ]
```

It is trying to install from the c:\ drive instead of the network share. This fix seems to be to manually change the dependency path to `"appcenter": "file:\\\\\\\\pitasci5\\c$\\npm\\AppCenter\\2.1.0",` by adding 4 more backslashes between the file:\ and the server name. Unescaped, the proper formatting would be `file:\\\\servername\share\...`, so escaped there should be 8 total.

**Comment by aarmand** [comment]
At 00:42 second mark of [this ](https://mva.microsoft.com/en-US/training-courses/mastering-nodejs-part-1-introduction-to-nodejs-16665?l=XKK8KImtC_4706218965)video, we install gulp. On my machine, Windows 10 Pro running in bootcamp, npm install is installing one directory up from project.  Ran npm install in aarmand/mva-web-app. Errors reference aarmand. Also not no node moudules showing in VS Code project tree. See screenshot.
![2016-09-04](https://cloud.githubusercontent.com/assets/2370391/18231796/a5f98af4-72c2-11e6-9df3-4da56ec0ae6b.png)
