### ISSUE TITLE
Package failure needed at creation rather than install

### ISSUE THREAD

**Issue by snopeks** [npm/npm#8885]
A user is experiencing install failure when the issue is related to incorrect pathing in their package.json.
This should preferably be picked up at the point of publishing, so it can be fixed before installation. 

Example: user publishes the following: 
`bin: { expressboilerplate: 'www.js' },`
Installation fails because there is no `www.js` in the root of their package.
That should be `"bin": { "expressboilerplate": "bin/www.js" },`

**Comment by anko** [comment]
There are legitimate use-cases for not publishing a file but still listing it in `bin`. For example, `www.js`could be generated on `preinstall.

This a package consisting only of this `package.json` file for example—

```json
{
  "name": "test",
  "version": "1.0.0",
  "scripts": {
    "preinstall": "echo \"echo hi\" > www.js"
  },
  "bin": {
      "expressboilerplate" : "www.js"
  }
}
```

—installs cleanly and marks the generated file with `echo hi` in it as executable.

**Comment by iarna** [comment]
@snopeks This does seem like the sort of foot gun we could protect from people

@anko I'd like to see an actual real world example of this before I preserved this footgun.

That said, I think the ordinary mechanism for this might meet both needs:

This could be an error from `npm publish` that can be overridden with `npm publish --force`. What do you think?

**Comment by anko** [comment]
@iarna 

My main argument is that I think generality should be the default. Generating an executable on `preinstall` isn't *obviously a bad idea*.

> I'd like to see a real world example

An npm package can represent an executable on [Node OS](https://node-os.com/blog/get-involved/), and [might be a C program](https://github.com/substack/lxjs-2013-slides), both of which (and many other things I can't imagine) may want to do some platform-specific compilation on install.

> This could be an error from `npm publish` that can be overridden with `npm publish --force`. What do you think?

That would make me worry about what *else* was being forced.

How about an "`npm lint`"-command that checks for signs of possible errors, including of this one? That would keep the hand-holding optional.

**Comment by iarna** [comment]
@anko You've offered up some more hypotheticals, and that's well and good, but I was hoping for something more concrete. 

I definitely wouldn't want to introduce a new command for this– the least case scenario would be a warning, like we warn about other issues with your package.json.

Ok, so I've found an actual concrete example in:

https://www.npmjs.com/package/node-bin
&
https://www.npmjs.com/package/iojs-bin

@aredridel – you've used this feature, how do you feel about it?
