### ISSUE TITLE
'npm ERR! Error: ENOENT' on npm run-script init-cloudsql

### ISSUE THREAD

**Issue by mananhora** [npm/npm#8888]
I'm trying to use google cloud to deploy my nodejs app. I ran the command : npm run-script init-cloudsql

Got the following result:

```
npm ERR! Error: ENOENT, open '/Users/mananhora/google-cloud-sdk/package.json'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 14.3.0
npm ERR! command "/Users/mananhora/.nvm/v0.10.40/bin/node" "/Users/mananhora/.nvm/v0.10.40/bin/npm" "run-script" "init-cloudsql"
npm ERR! cwd /Users/mananhora/google-cloud-sdk
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! path /Users/mananhora/google-cloud-sdk/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/mananhora/google-cloud-sdk/npm-debug.log
npm ERR! not ok code 0
```

Any suggestions?

**Comment by KenanY** [comment]
@mananhora Does `/Users/mananhora/google-cloud-sdk/package.json` exist?

**Comment by mananhora** [comment]
No...do I need to add it manually?

**Comment by KenanY** [comment]
@mananhora `npm` has no idea what to do when you execute `npm run init-cloudsql` unless you have a `package.json` in your current directory that defined such a [script](https://docs.npmjs.com/misc/scripts). You can use `npm init` to create a `package.json` if you'd like :)

**Comment by mananhora** [comment]
@KenanY Ah, okay, that makes sense!
Also, I'm not sure which directory I'm supposed to execute that command from..
