### ISSUE TITLE
missing script:build

### ISSUE THREAD

**Issue by ramaraman** [npm/npm#8890]
![untitled](https://cloud.githubusercontent.com/assets/13233022/8614084/095fab3e-269b-11e5-8c67-4c01574e546e.png)

**Comment by KenanY** [comment]
@ramaraman Well, _do_ you have a script called `build:css`?

**Comment by ramaraman** [comment]
@KenanY No, i m trying to find what is that and how can i build that. Actually I want to run page designed through polymer on nodejs and going never and getting nothing clear...

**Comment by KenanY** [comment]
@ramaraman If a `build:css` [script](https://docs.npmjs.com/misc/scripts) is not defined in your [`package.json`](https://docs.npmjs.com/files/package.json), `npm` will have no idea what you want it to do when you run `npm run build:css`.

**Comment by ramaraman** [comment]
How can i define it?

**Comment by KenanY** [comment]
@ramaraman https://docs.npmjs.com/misc/scripts#examples

**Comment by ramaraman** [comment]
please tell me the way to  runner a polymer designed web page on nodejs server. m completely stuck here :(

**Comment by KenanY** [comment]
@ramaraman Is there a forum somewhere where you can ask other polymer users? This issue tracker is for `npm`-related stuff :)

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
