### ISSUE TITLE
--no-color ignored for --loglevel verbose

### ISSUE THREAD

**Issue by akovari** [npm/npm#8895]
`npm --no-color --loglevel verbose install` only disables colors for normal messages, not for the verbose ones. Maybe the --no-color option should be applied to all messages?

**Comment by KenanY** [comment]
@akovari `npm --version`?

**Comment by akovari** [comment]
➜  npm --version
2.11.2

**Comment by zeorin** [comment]
I'm running npm version 3.3.3 and this doesn't seem to be an issue anymore. Perhaps time to close?
