### ISSUE TITLE
On trying to install grunt via npm -g grunt-cli get   npm err Callback called more than once

### ISSUE THREAD

**Issue by harriedharry** [npm/npm#8898]
Before the error there was  message that node v0.12.0
                                                                   npm v2.5.1

The log file when i try to attach here it gets too big ----: Error creating issue: body is too long.
 It is more than 668 pages in word.

The last page or so is.

48551 silly gunzTarPerm extractEntry lib/rules/validate-line-breaks.js
48552 silly gunzTarPerm modified mode [ 'lib/rules/validate-line-breaks.js', 420, 438 ]
48553 silly gunzTarPerm extractEntry lib/rules/disallow-curly-braces.js
48554 silly gunzTarPerm modified mode [ 'lib/rules/disallow-curly-braces.js', 420, 438 ]
48555 silly gunzTarPerm extractEntry test/css/globalVars/extended.css
48556 silly gunzTarPerm extractEntry test/css/globalVars/simple.css
48557 silly gunzTarPerm extractEntry collection/eachRight.js
48558 silly gunzTarPerm modified mode [ 'collection/eachRight.js', 420, 438 ]
48559 silly gunzTarPerm extractEntry test/css/ie-filters.css
48560 silly gunzTarPerm extractEntry test/css/import-inline.css
48561 silly gunzTarPerm extractEntry test/css/import-interpolation.css
48562 silly gunzTarPerm extractEntry lib/rules/validate-newline-after-array-elements.js
48563 silly gunzTarPerm modified mode [ 'lib/rules/validate-newline-after-array-elements.js',
48563 silly gunzTarPerm   420,
48563 silly gunzTarPerm   438 ]
48564 silly gunzTarPerm extractEntry lib/rules/disallow-comma-before-line-break.js
48565 silly gunzTarPerm modified mode [ 'lib/rules/disallow-comma-before-line-break.js', 420, 438 ]
48566 verbose stack Error: read ECONNRESET
48566 verbose stack     at exports._errnoException (util.js:746:11)
48566 verbose stack     at TCP.onread (net.js:550:26)
48567 verbose cwd C:\Users\haris_000\code\bootstrap\Module1\2\bootstrap
48568 error Windows_NT 6.3.9600
48569 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
48570 error node v0.12.0
48571 error npm  v2.5.1
48572 error code ECONNRESET
48573 error errno ECONNRESET
48574 error syscall read
48575 error network read ECONNRESET
48575 error network This is most likely not a problem with npm itself
48575 error network and is related to network connectivity.
48575 error network In most cases you are behind a proxy or have bad network settings.
48575 error network
48575 error network If you are behind a proxy, please make sure that the
48575 error network 'proxy' config is set properly.  See: 'npm help config'
48576 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@harriedharry As the error message states, this is an issue with your internet connection. Are you behind a proxy or a firewall?

**Comment by harriedharry** [comment]
No I think at one point I had installed more than one version of node  and that has got something to do with it.
