### ISSUE TITLE
NPM 3 deduping behavior

### ISSUE THREAD

**Issue by tolmasky** [npm/npm#8900]
Unfortunately I'm not sure how to test this (since it kind of relies on time), but with the auto-dedupe behavior,I'm curious what happens in this scenario. Say I do:

> npm install A

A requires B with a 1.x dependency, at the time of install, B is at 1.1 so it installs:

- A@1
- B@1.1

Great, now a few weeks later I do

> npm install C

C also requires B, with a 1.x dependency, but this time B is now at 1.2. Will it 1) just use the existing 1.1 dependency because it is sufficient, 2) upgrade my existing B to 1.2, or 3) install a custom 1.2 in B:

**Comment by iarna** [comment]
It will do #1. A fresh install would get you #2 of course.

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If you still have questions about this, can you please reply and let us know?  We’ll be happy to reopen if necessary.
