### ISSUE TITLE
flattening, dependencies, npm link, clever shortcuts, shooting self in foot

### ISSUE THREAD

**Issue by boneskull** [npm/npm#8902]
So, if you execute `npm link <package>`, the dir is symlinked, probably some other stuff happens, but what *doesn't* happen is the `node_modules` tree getting flattened.

I assume this is simply because if package *A* is linked in both package *B* and package *C*, the result of flattening in either *B* or *C* would potentially hose the other one.

This is an XY problem.  That was "Y", so here's "X":

I want package *A* to include a bunch of dev deps.  I want packages *B*, *C*, *D*, *E*, and *F* to each `npm link A`, because I want to leverage the flattening to not have to explicitly define the dev deps of packages *B* through *F*.  So running `npm install` in say package *B* will install its dev dependencies (of which there is only one: package *A*), and package's *A*'s *dependencies* are actually the dev dependencies of *B* through *F*.  I hope that makes sense.

This works fine while not using `npm link`, but if I do that, things like this happen (with say, the `debug` package):

```
B
 |- node_modules
 |--- debug
 |--- A (symlinked)
 |----- node_modules
 |------- debug
```

...but in the case of `debug`, if I set `DEBUG=A,B`, I would expect to see the debug output from both modules, but instead I only see `B` (I'm unclear if this particular problem is an `npm` issue or a `debug` issue, however).

* * *

This is probably Bad, Evil & Wrong, but it's a pain to have to manually manage the versions of dev deps in many separate packages--especially when they are all intended to be the same.  Meanwhile, I've resorted to a `prepublish` script to symlink package *A*'s dotfiles into packages *B* through *F*, because those are all the same as well.

I was *hoping* the new flattening strategy of npm v3 would make this super-easy, but it ain't work with `npm link`.

I'm assuming npm supports my use case somehow?  Bundle deps?  Just symlink everything?  Maybe ditch package *A*'s dependencies altogether, and have a prepublish script that `npm install`'s a bunch of stuff?!

If there's some good reason *not* to do this sort of thing, please let me know.  It really saves me a lot of time updating dev deps (or an `.editorconfig`) in *one* place instead of seven or ten.

**Comment by boneskull** [comment]
(I'm not sure, but I think if you `npm install x`, then `npm link x` later, the flattened dependencies of *x* are leftover?  Maybe not...)

**Comment by boneskull** [comment]
Alternatively, if this can be solved with Git somehow, I'm open to ideas, because this *feels* like a misuse of npm

**Comment by iarna** [comment]
Since you mention flattening I assume you're talking about npm@3?

**Comment by boneskull** [comment]
@iarna yes, sorry, thought I mentioned that, but apparently not

**Comment by iarna** [comment]
Ok, so if you run, `npm link super-keen-package` that you've never installed before, npm effectively runs `npm install -g super-keen-package` and then symlinks it from your global dir to your local `node_modules`.

Global modules are flattened but only within themselves– they obviously don't have any other context to flatten with.

Flattening never enters symlinks for exactly the reasons you've mentioned, so even if you run `npm dedupe` it'll leave them alone.

(There are some interesting edge cases to `npm link` that makes it more complicated than this, but most of the time this describes its behavior.)

**Comment by boneskull** [comment]
@iarna Thanks. I understand this, but how should I approach my use case?  I want to have a single package handle all my dev dependencies for a multitude of other packages

**Comment by boneskull** [comment]
(or something to that effect--I just don't want to maintain dev deps in 10 packages)

**Comment by iarna** [comment]
Yeah, just setting the stage…

Sooo... you VERY much should not be using any module you didn't directly depend on. It's not safe... npm reserves the right to sink flattened deps deeper into the tree if it needs to.

I do see what you're getting at, there's another open issue with someone asking for a template `package.json`, which has its own issues, but I find preferable to this. I'm not too keen on either though.

For what you're talking about I think I'd approach it thusly:

Package A would export a binary, let's call it `setup-A`. When run, it would load the requiring package's package.json (`module.parent.require('./package.json')`) and look for missing dev deps... for any it found it would run `npm install --save-dev <pkgname>`.

Then in Package B, C etc, I would have a `prepublish` script that runs `setup-A`.

I know using `prepublish` this way sounds weird, but it will be run when you run `npm install` with no args inside B/C/etc, but not when folks USING B/C install them. Having it ALSO run when you run `npm publish` or `npm pack` is weird but harmless.

**Comment by boneskull** [comment]
@iarna okay, that sounds workable.  Thanks for the suggestion.  I'm going to close this.
