### ISSUE TITLE
Can you customize `npm i` output?

### ISSUE THREAD

**Issue by bucaran** [npm/npm#8903]
Of course I could write a script that does what I need wrapping `npm i`, and now that I think about it after writing this, that's probably the way to go, but it does not hurt to ask, I would like to know if there is any way to customize the output of `npm i`.

I would like to make the output more friendly or _less scary_, but I am sure there could be other more valid reasons, like displaying even more information.

**Comment by sinkingshriek** [comment]
Not sure if you can customize it but you can definitely see different `loglevels` when installing. The followings are what's available and is taken from [docs](https://docs.npmjs.com/misc/config#default-configs)

```
-s, --silent: --loglevel silent
-q, --quiet: --loglevel warn
-d: --loglevel info
-dd, --verbose: --loglevel verbose
-ddd: --loglevel silly
```
Now, technically, you can have a `silly` loglevel and just pipe it to the "customized" format that you want but there aren't any default customization from npm at this point. Atleast, not that I'm aware of.

**Comment by othiym23** [comment]
While you can set the log level, as @sinkingshriek suggests, you can't actually change how the log output is formatted. npm's logging is kind of overwhelming, at more verbose log levels, but that's what we as maintainers need to do postmortem analysis of your `npm-debug.log` files (which uses the same stream as what's logged to stderr, albeit always at a log level of `silly`). I think writing an adapter to read that log stream and turn it into a friendlier format is a perfectly fine idea. Several tools that wrap around npm (like `ember-cli`) are already doing something similar.

This isn't something the core project is likely to change anytime soon, so I'm going to go ahead and close this. Thanks for taking the time together to put together a feature request, though!

**Comment by bucaran** [comment]
@othiym23 @sinkingshriek Thanks!
