### ISSUE TITLE
npm install --silent still outputs from native builds

### ISSUE THREAD

**Issue by robotbrain** [npm/npm#8905]
WTTS

**Comment by KenanY** [comment]
@robotbrain Hmm, example (just so I understand correctly)? `npm --version`?

**Comment by robotbrain** [comment]
here is a log where it happens
https://s3.amazonaws.com/archive.travis-ci.org/jobs/70521438/log.txt

**Comment by sinkingshriek** [comment]
```
node --version
v0.10.40
$ npm --version
1.4.28
$ nvm --version
0.23.3
```
@robotbrain `npm` is already > `3`. Can you try upgrading to `3` and see if it fixes your issue?

**Comment by KenanY** [comment]
@robotbrain ping?

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
