### ISSUE TITLE
Feature Request: Installing according to given date

### ISSUE THREAD

**Issue by jugglinmike** [npm/npm#8907]
I'd like to be able to instruct npm to install dependencies as if I were running
the command at a given date. For instance:

    $ npm install --atdate 2015-06-12

would install the project's dependencies (and nested dependencies) following
semver as if it were June 12 of this year. This means that a dependency on
`express` specified as `^4.11.0` would resolve to version `4.12.4`, despite the
fact that version `4.13.0` satisfies the version range (since it was released
on June 21).

My use case: I'm looking to perform some automated benchmark tests to vet pull
requests for performance regressions. The baseline will be the performance of
the library at the last release.

I believe this would be useful for many auditing tasks, such as bisecting
regressions that may have come from dependencies.

I'd be interested in helping with the implementation effort, but I would like
to get some feedback on the appropriateness of this feature before going any
further.

Thanks for the great tool!

**Comment by othiym23** [comment]
So, this isn't in scope for the CLI team (in that I don't realistically see us ever having the time to do this ourselves, given its importance), so I'm going to close this issue. That said, if somebody wanted to put this together as a PR, we'd take the functionality.
