### ISSUE TITLE
STD ERR npm ERR! at installTargetsError

### ISSUE THREAD

**Issue by andrezporter** [npm/npm#8908]
I'm using meteor up to deploy my app but I'm getting getting the following error and I just need some help.
Currently I'm using:
node 0.10.36
npm 2.11.3
and 
Ubuntu 14.04x64

	-----------------------------------STDERR-----------------------------------
	0.5","1.0.6","1.0.7","1.0.8","1.0.10","1.1.0","1.1.3","1.1.4","1.2.0","1.2.1","1.3.0","1.3.1"]
	npm ERR!     at installTargetsError (/opt/nodejs/lib/node_modules/npm/lib/cache.js:685:10)
	npm ERR!     at /opt/nodejs/lib/node_modules/npm/lib/cache.js:607:10
	npm ERR!     at saved (/opt/nodejs/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
	npm ERR!     at Object.oncomplete (fs.js:107:15)
	npm ERR! If you need help, you may report this log at:
	npm ERR!     <http://github.com/isaacs/npm/issues>
	npm ERR! or email it to:
	npm ERR!     <npm-@googlegroups.com>
	
	npm ERR! System Linux 3.13.0-52-generic
	npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
	npm ERR! cwd /opt/meteor/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt
	npm ERR! node -v v0.10.3
	npm ERR! npm -v 1.2.17
	npm ERR! 
	npm ERR! Additional logging details can be found in:
	npm ERR!     /opt/meteor/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/npm-debug.log
	npm ERR! not ok code 0
	-----------------------------------STDOUT-----------------------------------
	 > ./bcrypt: npm install due to binary npm modules
	----------------------------------------------------------------------------

**Comment by KenanY** [comment]
@andrezporter 

> Currently I'm using:
> node 0.10.36
> npm 2.11.3

Log says otherwise:

```
npm ERR! node -v v0.10.3
npm ERR! npm -v 1.2.17
```

**Comment by andrezporter** [comment]
@kenanY your right whoops....

But when I type

npm -v 

it says I'm using 2.11.3. Why would 'mup deploy' use 1.2.17?

**Comment by KenanY** [comment]
@andrezporter Then I guess you have a couple of Node/`npm` installations co-existing.

What does `which npm` print?

**Comment by andrezporter** [comment]
Says its in local. 

/usr/local/bin/npm

**Comment by andrezporter** [comment]
If i ran 

npm -g ls | grep -v 'npm@' | awk '/@/ {print $2}' | awk -F@ '{print $1}' | xargs npm -g rm

which I found here 

http://stackoverflow.com/questions/9283472/command-to-remove-all-npm-modules-globally

Then just reinstalled npm once locally, would this all be solved?

**Comment by andrezporter** [comment]
... oops forgot to call you. 

@KenanY 

Thanks for helping me out

**Comment by andrezporter** [comment]
Issue resolved! But, oldest programming joke in the book: I don't why. I did reinstall Node and Meteor, but I'm not sure how either of those would have taken care of my problem.

**Comment by iarna** [comment]
Closing this as resolved.
