### ISSUE TITLE
Wrong dependency handling? (mongoose version requested by nodemail)

### ISSUE THREAD

**Issue by vor0nwe** [npm/npm#8915]
When trying to install `nodemail`, I get the following error:

    (...)
    npm http 304 https://registry.npmjs.org/express-partials
    npm ERR! Error: No compatible version found: mongoose@'>=3.1.2-0 <3.2.0-0'
    npm ERR! Valid install targets:
    npm ERR!     ["0.0.1","0.0.2","0.0.3","0.0.4","0.0.5","1.0.0","1.0.1","1.0.2","0.0.6","1.0.3","1.0.4","1.0.5","1.0.6","1.0.7","1.0.8","1.0.10","1.0.11","1.0.12","1.0.13","1.0.14","1.0.15","1.0.16","1.1.0","1.1.1","1.1.2","1.1.3","1.1.4","1.1.5","1.1.6","1.1.7","1.1.8","1.1.9","1.1.10","1.1.11","1.1.12","1.1.13","1.1.14","1.1.15","1.1.16","1.1.17","1.1.18","1.1.19","1.1.20","1.1.21","1.1.22","1.1.23","1.1.24","1.1.25","1.2.0","1.3.0","1.3.1","1.3.2","1.3.3","1.3.4","1.3.5","1.3.6","1.3.7","1.4.0","1.5.0","1.6.0","1.7.2","1.7.3","1.7.4","1.8.0","1.8.1","1.8.2","1.8.3","1.8.4","2.0.0","2.0.1","2.0.2","2.0.3","2.0.4","2.1.0","2.1.1","2.1.2","2.1.3","2.1.4","2.2.0","2.2.1","2.2.2","2.2.3","2.2.4","2.3.0","2.3.1","2.3.2","2.3.3","2.3.4","2.3.5","2.3.6","2.3.7","2.3.8","2.3.9","2.3.10","2.3.11","2.3.12","2.3.13","2.4.0","2.4.1","2.4.2","2.4.3","2.4.4","2.4.5","2.4.6","2.4.7","2.4.8","2.4.9","2.4.10","2.5.0","2.5.1","2.5.2","2.5.3","2.5.4","2.5.5","2.5.6","2.5.7","2.5.8","2.5.9","2.5.10","2.5.11","2.5.12","2.5.13","2.5.14","2.6.0","2.6.1","2.6.2","2.6.3","2.6.4","2.6.5","2.6.6","2.6.7","2.6.8","2.7.0","2.7.1","2.7.2","2.7.4","2.7.3","3.0.0","3.0.1","3.0.2","2.8.0","3.0.3","3.1.0","2.8.1","3.1.1","2.8.2","2.8.3","2.9.0","3.2.0","2.9.1","3.2.1","2.9.2","3.2.2","3.3.0","3.3.1","2.9.3","3.4.0","2.9.4","2.9.5","3.5.0","3.5.1","3.5.2","3.5.3","2.9.6","2.9.7","3.5.4","3.5.5","2.9.8","2.9.9","3.5.6","3.5.7","3.5.8","2.9.10","3.5.9","3.6.2","3.5.10","3.6.3","3.5.11","3.6.4","3.6.5","3.6.6","3.6.7","3.5.12","3.6.8","3.6.9","3.6.10","3.5.13","3.5.14","3.6.11","3.6.12","3.6.13","3.6.14","3.6.15","3.5.15","3.7.0","3.6.16","3.5.16","3.6.17","3.7.2","3.0.0-alpha1","3.0.0-alpha2","3.0.0-rc0","3.6.0-rc0","3.6.0-rc1","3.6.18","3.7.3","3.6.19","3.6.20","3.7.4","3.8.0","3.8.1","3.8.2","3.8.3","3.8.4","3.8.5","3.8.6","3.8.7","3.8.8","3.8.9","3.8.10","3.8.11","3.9.0","3.8.12","3.8.13","3.8.14","3.8.15","3.9.1","3.8.16","3.9.2","3.8.17","3.9.3","3.8.18","3.9.4","3.8.19","3.9.5","3.8.20","3.9.6","3.8.21","3.9.7","3.8.22","4.0.0-rc0","4.0.0-rc1","3.8.23","4.0.0-rc2","3.8.24","4.0.0-rc3","3.8.25","4.0.0-rc4","4.0.0","4.0.1","3.8.26","3.8.27","4.0.2","3.8.28","4.0.3","3.8.29","4.0.4","3.8.30","4.0.5","3.8.31","4.0.6","3.8.33","4.0.7"]
    npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:719:10)
    npm ERR!     at next (/usr/share/npm/lib/cache.js:698:17)
    npm ERR!     at /usr/share/npm/lib/cache.js:675:5
    npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
    npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
    npm ERR!     at Object.oncomplete (fs.js:107:15)
    npm ERR! If you need help, you may report this log at:
    npm ERR!     <http://github.com/isaacs/npm/issues>
    npm ERR! or email it to:
    npm ERR!     <npm-@googlegroups.com>

But a supported version of mongoose _is_ installed:

mongoose@4.0.7 node_modules/mongoose
├── regexp-clone@0.0.1
├── sliced@0.0.5
├── muri@1.0.0
├── hooks-fixed@1.0.1
├── mpromise@0.5.4
├── kareem@1.0.1
├── mpath@0.1.1
├── async@0.9.0
├── ms@0.1.0
├── mquery@1.6.1 (debug@2.2.0, bluebird@2.9.26)
├── mongodb@2.0.34 (readable-stream@1.0.31, mongodb-core@1.2.0)
└── bson@0.3.2 (bson-ext@0.1.10)

**Comment by KenanY** [comment]
@vor0nwe What version of `npm` do you have? It must be old....

**Comment by vor0nwe** [comment]
Ah, that is possible. `npm@1.3.10`, installed from the repositories for Ubuntu 14.04.

**Comment by KenanY** [comment]
@vor0nwe Yeah. support for `npm@1.3` ended many months ago. I suggest you [upgrade](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) :)

Some Linux distributions lag behind the latest Node.js release. I've seen [NodeSource's distribution](https://github.com/nodesource/distributions) recommended a lot.

**Comment by vor0nwe** [comment]
Thanks @KenanY . Will try NodeSource, and try to get the latest version of `npm` as well.
