### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by Seb137** [npm/npm#8916]
Hi there!

I need a little to help to setup npm.
I am running OS 10.8.5 and try to install npm with command line and there are error messages I can't understand.
The system has generated a npm-debug.log file. 
Is there someone could help me to pass through this please?
Thank you
Seb137

**Comment by KenanY** [comment]
@Seb137 Upload the `npm-debug.log` file as a [gist](https://gist.github.com/) :)

**Comment by Seb137** [comment]
here is my debug file https://gist.github.com/Seb137
Thank you!

**Comment by KenanY** [comment]
@Seb137 Looks like a permissions issue. Could you try running this?:

``` bash
$ sudo chown -R $(whoami) "$HOME/.npm"
```

**Comment by Seb137** [comment]
I followed your advice and it return to bash:
imac:PopcornTV maison$ sudo chown -R $(whoami) "$HOME/.npm"
Password:
imac:PopcornTV maison$

Did I had have something else?

Thank you @KenanY

**Comment by Seb137** [comment]
I updated the gist

**Comment by KenanY** [comment]
@Seb137 Hmm, the error is coming from your installation of `git`. Maybe it's corrupted or something?

```
10002 verbose stack Error: Command failed: git clone --template=/Users/maison/.npm/_git-remotes/_templates --mirror https://github.com/xeoncore/progress-stream.git /Users/maison/.npm/_git-remotes/https-github-com-xeoncore-progress-stream-git-609443b1
10002 verbose stack dyld: lazy symbol binding failed: Symbol not found: ___strlcpy_chk
10002 verbose stack   Referenced from: /usr/local/git/bin/git
10002 verbose stack   Expected in: /usr/lib/libSystem.B.dylib
10002 verbose stack
10002 verbose stack dyld: Symbol not found: ___strlcpy_chk
10002 verbose stack   Referenced from: /usr/local/git/bin/git
10002 verbose stack   Expected in: /usr/lib/libSystem.B.dylib
```

**Comment by Seb137** [comment]
Ok, I installed nodejs who is included git (if I'm not wrong)
When I enter 'git --version' I get 'git version 2.4.3'
Is there another war to get git and re-install it properly?
(I can't use github for Mac because it requires 10.9 and I'm running 10.8.5)
thanks

**Comment by KenanY** [comment]
@Seb137 https://git-scm.com/downloads

**Comment by Seb137** [comment]
Sorry for the time.
Thank you for your support, all is in order now
