### ISSUE TITLE
npm@3 should not be trying to install modules that arch/os say are incompatible

### ISSUE THREAD

**Issue by cchamberlain** [npm/npm#8921]
Using Windows 8.1 and NPM 3.1 I seem to always get node-gyp errors for packages that don't affect the Windows platform (fsevents).  If I use --no-optional on all npm installs, I don't see the errors.  Is there any way to set a default to always use --no-optional?  Simple export of an environment variable like npm_config_install_nooptional would solve a lot of short-term Windows issues.

Maybe something like this already exists and I just can't find it?

**Comment by iarna** [comment]
It shouldn't actually be trying to install an optional fsevents on Windows. (fsevents marks itself as OS specific.) I'll be correcting this…

**Comment by cchamberlain** [comment]
I saw that fsevents is set to only run for OSX in the gyp file but I couldn't get it to respect that.

Here are dumps of my environment.  I'd be happy to test.  Still think that a global no-optional setting would be helpful (unless I am missing something).

from ZSH:
`uname` => `MSYS_NT-6.3`
`env` => http://pastebin.com/Pstc7MZu
`node -p process` => http://pastebin.com/ad2PuTMa
`npm config list -g` =>

    ; cli configs
    global = true
    user-agent = "npm/3.1.0 node/v0.12.6 win32 ia32"

    ; environment configs
    prefix = "C:\\Users\\ColeChamberlain\\local\\npm"

    ; userconfig C:\Users\ColeChamberlain\.npmrc
    shell = "bash"

    ; globalconfig C:\Users\ColeChamberlain\local\npm\etc\npmrc
    loglevel = "warn"

    ; node bin location = C:\Users\ColeChamberlain\local\npm\node.exe
    ; cwd = C:\Users\ColeChamberlain\cchamberlain\npm
    ; HOME = C:\Users\ColeChamberlain
    ; "npm config ls -l" to show all defaults.

**Comment by iarna** [comment]
I updated the title to reflect the underlying cause

**Comment by iarna** [comment]
Welp, I've found the code that does this. It exists. I didn't forget it. =D It just, apparently, doesn't work for some reason. And apparently we didn't have any tests for it. So we'll be fixing both of those things.

**Comment by cchamberlain** [comment]
Awesome! All the recent fixes with npm 3 have been making my life much easier.

**Comment by iarna** [comment]
\o/ Awesome, glad to hear it! =)

**Comment by iarna** [comment]
Hey! Good news, this should be fixed in the just released `npm@3.2.0`!

**Comment by giggio** [comment]
@iarna I just installed and it brought down `3.1.3`, using `latest`:

````powershell
C:\Program Files (x86)\Microsoft Visual Studio 14.0> npm i npm@3.x-latest -g
C:\Program Files\nodejs\npm -> C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js
C:\Program Files\nodejs
└── npm@3.1.3

npm WARN EPACKAGEJSON C:\Program Files\nodejs No description
npm WARN EPACKAGEJSON C:\Program Files\nodejs No repository field.
npm WARN EPACKAGEJSON C:\Program Files\nodejs No README data
npm WARN EPACKAGEJSON C:\Program Files\nodejs No license field.
C:\Program Files (x86)\Microsoft Visual Studio 14.0>
````

Should I install it using `npm i -g npm@3.x-next`?

**Comment by iarna** [comment]
Yup, or npm@3.2.0

**Comment by rstoenescu** [comment]
This happens again in NPM 3.5.0....

**Comment by kevcraey** [comment]
confirmed that this happens in NPM 3.5.0

**Comment by manuelbieh** [comment]
Same here:

```
npm ERR! node v4.2.3
npm ERR! npm  v3.5.1
npm ERR! code EBADPLATFORM
npm ERR! notsup Not compatible with your operating system or architecture: fsevents@1.0.5
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64
```

when trying to install fsevents

**Comment by rstoenescu** [comment]
Let's move on to https://github.com/npm/npm/issues/10768 for discussion. I've opened this bug for npm 3.5.0.

**Comment by aggieben** [comment]
I still have this issue in 3.10.3, and now that #10768 has been closed and locked, it seems that this would be the place to pick it up.  

Just to be clear, this is not just an issue of having a confusing warning printed to the console.  My build actually terminates with an error code and no `node_modules` directory is left behind.
