### ISSUE TITLE
Unknown error while authenticating

### ISSUE THREAD

**Issue by ymc-thzi** [npm/npm#8923]
```
npm http 400 https://registry.npmjs.org/-/user/org.couchdb.user:ymc-thzi
npm ERR! Error: Unknown error while authenticating : -/user/org.couchdb.user:ymc-thzi
npm ERR!     at RegClient.<anonymous> (/usr/local/Cellar/node/0.10.22/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:272:14)
npm ERR!     at Request.self.callback (/usr/local/Cellar/node/0.10.22/lib/node_modules/npm/node_modules/request/request.js:129:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/local/Cellar/node/0.10.22/lib/node_modules/npm/node_modules/request/request.js:873:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/local/Cellar/node/0.10.22/lib/node_modules/npm/node_modules/request/request.js:824:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
```

**Comment by KenanY** [comment]
@ymc-thzi `npm --version`?

**Comment by garex** [comment]
1.2.18

**Comment by KenanY** [comment]
@garex That's extremely old. Try [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm).

**Comment by garex** [comment]
+1 already )) I want something like `composer selfupdate`

**Comment by ymc-thzi** [comment]
1.3.14

**Comment by garex** [comment]
@ymc-thzi Mine after upgrade:

    npm -v
    2.13.0

**Comment by othiym23** [comment]
@garex `npm install -g npm` will upgrade npm (if you don't have `/usr/local` (or wherever you have npm installed) owned by you, you'll need `sudo` in front)

@ymc-thzi You'll need to upgrade as well. Support for `npm@1.3` ended sometime last year.

**Comment by garex** [comment]
@othiym23 I did already. Tnx )) But I think authors of all package tools in the world must go to conference in some forest and deside here about single tool keys and behavior. Standartize it.

**Comment by cchamberlain** [comment]
npm's upgrade command seems closer to the standard than the one you suggested @garex.  See pacman, apt-get, etc. The difference with npm is you can install to local or global scope, and the package you access in your path is the global one.  I can't see this being made much more straightforward.

Windows on the other hand...

**Comment by ymc-thzi** [comment]
upgraded, works, thx
