### ISSUE TITLE
`npm la` should check `npm-shrinkwrap.json` as well as `package.json` for version validity

### ISSUE THREAD

**Issue by flarnie** [npm/npm#8928]
> "A great feature request contains
> •   The current situation."

Running `npm la` will ["print out extraneous, missing, and invalid packages."](https://docs.npmjs.com/cli/ls#description)
It looks at the versions in the `package.json` to determine which modules are out of sync in the local `node_modules` directory, but doesn't analyze based on the `npm-shrinkwrap.json` file.

> " •  How and why the current situation is problematic." + " •  A use case – who needs this feature and why?"

We have the following scenario:
1. 'Developer A' bumps a dependency version, updating the `npm-shrinkwrap.json`, but this may not result in a change to the `package.json` if the new version is within the accepted range.
2.  'Developer B' rebases onto master, getting the updated `npm-shrinkwrap.json`, but since the `node_modules` are `.gitignore`'ed they won't get the updated version of the module without doing `npm install`.
3. If `npm ls` outputs the 'invalid: true' tag, then git hooks or a manual check can tell 'Developer B' when they need to run `npm install`.

See similar issue [#5107: Check dependency versions before running any commands](https://github.com/npm/npm/issues/5107)

> " •  A detailed proposal or pull request that demonstrates how the problem could be solved."

Using the `npm ls` command and a git hook or start-up script can prompt developers to run `npm install` when dependencies are updated, and this will be more accurate if the command reflects changes in the `npm-shrinkwrap.json` as well as `package.json`.

> " •  Any caveats."

This doesn't (by itself) solve the problem of prompting developers to update npm modules after rebasing, but having more specific output from `npm ls` still seems useful.

**Comment by othiym23** [comment]
Thank you for the careful feature request and for providing so much context, @flarnie! I think this is in fact a good tweak to make to shrinkwrap now that we're doing a better job of using and maintaining shrinkwraps in `npm@3`. Speaking of which, @iarna, does `npm@3` change the story? And how do you feel about this idea overall? It makes sense to me that if there's a shrinkwrap, `npm ls` should use it as part of checking the validity of the installed tree.

**Comment by othiym23** [comment]
Looking at this, this is actually an inconsistency in `npm ls` behavior, and therefore better classified as a bug. We have a project on the roadmap for this year to improve `npm shrinkwrap` and make it behave more consistently with the rest of the tool, but if somebody wants to take a stab at fixing this before then, this is a relatively self-contained thing to work on.
