### ISSUE TITLE
Win7: npm install -g bower: ERR! connect ENOBUFS

### ISSUE THREAD

**Issue by stlawrence** [npm/npm#8934]
Trying to install bower with npm on windows 7 vm:
```
C:\Users\edward.stlawrence>npm install -g bower
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "bower"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ENOBUFS
npm ERR! errno ENOBUFS
npm ERR! syscall connect
npm ERR! connect ENOBUFS
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\edward.stlawrence\npm-debug.log

C:\Users\edward.stlawrence>
```
I've re-run this several times and restarted the vm.  Sometimes the error happens on a Fetch of a source tar.gz, and sometimes like this without a fetch failing. I've spent a couple hours on stackoverflow and google but haven't found anyone who encountered this error with npm. There are some hits for ENOBUFS when using $http.get but the solutions were not relevant to npm. Most of the npm errors did not have the ENOBUFS message and referenced git connectivity problems which I don't have. 

Any help appreciated.

Relevant error from log:
```
26612 info install inquirer@0.8.0
26613 info postinstall inquirer@0.8.0
26614 verbose unlock done using C:\Users\edward.stlawrence\AppData\Roaming\npm-cache\_locks\inquirer-10e7d32c9182a474.lock for C:\Users\edward.stlawrence\AppData\Roaming\npm\node_modules\bower\node_modules\inquirer
26615 verbose about to build C:\Users\edward.stlawrence\AppData\Roaming\npm\node_modules\bower
26616 verbose unlock done using C:\Users\edward.stlawrence\AppData\Roaming\npm-cache\_locks\bower-1e8f2ba1aefdb781.lock for C:\Users\edward.stlawrence\AppData\Roaming\npm\node_modules\bower
26617 verbose stack Error: connect ENOBUFS
26617 verbose stack     at exports._errnoException (util.js:746:11)
26617 verbose stack     at connect (net.js:842:19)
26617 verbose stack     at net.js:955:9
26617 verbose stack     at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:81:16)
26617 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:99:10)
26618 verbose cwd C:\Users\edward.stlawrence
26619 error Windows_NT 6.1.7601
26620 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "bower"
26621 error node v0.12.7
26622 error npm  v2.11.3
26623 error code ENOBUFS
26624 error errno ENOBUFS
26625 error syscall connect
26626 error connect ENOBUFS
26627 error If you need help, you may report this error at:
26627 error     <https://github.com/npm/npm/issues>
26628 verbose exit [ 1, true ]
26629 verbose unbuild node_modules\bower\node_modules\github
```
(The message says to include the log file but there isn't a way to attach and I get an error about the body being too long if I try to paste it.)

**Comment by othiym23** [comment]
This is going to sound super stupid, but have you tried rebooting and then trying again? `ENOBUFS` is typically an error that comes out of the OS when it doesn't have the resources to create a client connection. (It's sort of like running out of file descriptors on a Unix-like system.) It's possible something else is going on, but I think a full reboot might help. Either that, or you might want to look at how resources are allocated to the vm, because it might need more juice (RAM, virtual CPUs, or something) of some kind.

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
