### ISSUE TITLE
I need to remove all release versions from my library in npm

### ISSUE THREAD

**Issue by jdnichollsc** [npm/npm#8935]
I need to publish mi package with the new git url, please help me to remove all releases.

https://www.npmjs.com/package/phaser-kinetic-scrolling-plugin

**Comment by sinkingshriek** [comment]
You can [unpublish](https://docs.npmjs.com/cli/unpublish) your packages but it's generally recommended not to. 
P.S. I already see it removed from the given url.

**Comment by jdnichollsc** [comment]
But I tried to publish again and appears this error:

"You cannot publish over the previously published version 0.1.1. Try bumping the version to 1.0.0" : phaser-kinetic-scrolling-plugin

If you need help, you may report this error at:
<https://github.com/npm/npm/issues>

and see me here haha, help me please. My library is => http://jdnichollsc.github.io/Phaser-Kinetic-Scrolling-Plugin/

**Comment by sinkingshriek** [comment]
Have you tried bumping up the version to `1.0.0` in your `package.json` and publishing again?  In the past you could `force` publish a package but it's [no longer possible](http://blog.npmjs.org/post/77758351673/no-more-npm-publish-f). The only way is to bump up the version number.

**Comment by cchamberlain** [comment]
Packages must always increase in version, it's built into npm.

'npm version patch && npm publish'

**Comment by jdnichollsc** [comment]
ahh of this way the versions do not match with GitHub :(
Impossible?

**Comment by othiym23** [comment]
Once a version of a package has been published to the registry, it can't ever be republished at that version.  So yeah, you're going to have to come up with something else to get your GitHub and npm versions back in sync. (Maybe delete the tags for the obsolete versions from the GitHub repo? It seems extreme, but it's one way to get them back in sync.)

For future reference, you should be able to just change the GitHub URL in `package.json` and then publish a new version, and that URL will be used on the web site and from the command line from that time on. Sorry you had to find that out in such a convoluted way!

I'm closing this as this isn't a bug in npm. Good luck getting it sorted out!
