### ISSUE TITLE
ECONNRESET followed by null

### ISSUE THREAD

**Issue by waivek** [npm/npm#8936]
Hey! 
So I've been struggling with installing packages via npm recently. I am not behind any proxy and yet whenever I ran an install command I would get the ECONNRESET error message. Someone on the Internet suggested that I run

`npm config set registry https://registry.npmjs.org/`

I did this and now I am getting an "Invalid Protocol: null" error

I've uninstalled and re-installed it a couple of times too

This is my npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\nodejs\\\\node.exe',
1 verbose cli   'C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'yo' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose install initial load of C:\Users\Toshiba PC\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\Toshiba PC\AppData\Roaming\npm\package.json
6 silly cache add args [ 'yo', null ]
7 verbose cache add spec yo
8 silly cache add parsed spec { raw: 'yo',
8 silly cache add   scope: null,
8 silly cache add   name: 'yo',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed yo@*
10 verbose addNamed "*" is a valid semver range for yo
11 silly addNameRange { name: 'yo', range: '*', hasData: false }
12 silly mapToRegistry name yo
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry http://registry.npmjs.org/
15 silly mapToRegistry uri http://registry.npmjs.org/yo
16 verbose addNameRange registry:http://registry.npmjs.org/yo not in flight; fetching
17 verbose request uri http://registry.npmjs.org/yo
18 verbose request no auth needed
19 info attempt registry request try #1 at 11:56:56 AM
20 verbose request id d55b26a24e55daf7
21 http request GET http://registry.npmjs.org/yo
22 info retry will retry, error on last attempt: Error: Invalid protocol: null
23 info attempt registry request try #2 at 11:57:06 AM
24 http request GET http://registry.npmjs.org/yo
25 info retry will retry, error on last attempt: Error: Invalid protocol: null
26 info attempt registry request try #3 at 11:58:06 AM
27 http request GET http://registry.npmjs.org/yo
28 verbose stack Error: Invalid protocol: null
28 verbose stack     at Request.init (C:\nodejs\node_modules\npm\node_modules\request\request.js:626:31)
28 verbose stack     at new Request (C:\nodejs\node_modules\npm\node_modules\request\request.js:265:8)
28 verbose stack     at request (C:\nodejs\node_modules\npm\node_modules\request\index.js:56:10)
28 verbose stack     at CachingRegistryClient.makeRequest (C:\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:147:13)
28 verbose stack     at C:\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:65:17
28 verbose stack     at RetryOperation._fn (C:\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\attempt.js:18:5)
28 verbose stack     at null._onTimeout (C:\nodejs\node_modules\npm\node_modules\retry\lib\retry_operation.js:32:10)
28 verbose stack     at Timer.listOnTimeout (timers.js:119:15)
29 verbose cwd C:\Users\Toshiba PC
30 error Windows_NT 6.3.9600
31 error argv "C:\\nodejs\\\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "yo"
32 error node v0.12.7
33 error npm  v2.11.3
34 error Invalid protocol: null
35 error If you need help, you may report this error at:
35 error     <https://github.com/npm/npm/issues>
36 verbose exit [ 1, true ]
```

**Comment by othiym23** [comment]
Hmmm...:

```
14 silly mapToRegistry registry http://registry.npmjs.org/
```

So that seems to indicate that what you actually ran was `npm config set registry http://registry.npmjs.org/` (note the `http` instead of `https`). What happens if you run `npm config delete registry` and try again? And if that doesn't work, what about trying `npm config set registry https://registry.npmjs.org/` (with `https`)?

**Comment by waivek** [comment]
I tried that and I'm back to the ECONNRESET error

This is my npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\nodejs\\\\node.exe',
1 verbose cli   'C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'connect' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose config Skipping project config: C:\Users\Toshiba PC/.npmrc. (matches userconfig)
5 verbose install initial load of C:\Users\Toshiba PC\package.json
6 verbose readDependencies loading dependencies from C:\Users\Toshiba PC\package.json
7 silly cache add args [ 'connect', null ]
8 verbose cache add spec connect
9 silly cache add parsed spec { raw: 'connect',
9 silly cache add   scope: null,
9 silly cache add   name: 'connect',
9 silly cache add   rawSpec: '',
9 silly cache add   spec: '*',
9 silly cache add   type: 'range' }
10 silly addNamed connect@*
11 verbose addNamed "*" is a valid semver range for connect
12 silly addNameRange { name: 'connect', range: '*', hasData: false }
13 silly mapToRegistry name connect
14 silly mapToRegistry using default registry
15 silly mapToRegistry registry https://registry.npmjs.org/
16 silly mapToRegistry uri https://registry.npmjs.org/connect
17 verbose addNameRange registry:https://registry.npmjs.org/connect not in flight; fetching
18 verbose request uri https://registry.npmjs.org/connect
19 verbose request no auth needed
20 info attempt registry request try #1 at 12:12:34 AM
21 verbose request id 6b580155d3b10ab6
22 http request GET https://registry.npmjs.org/connect
23 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=Parse Error
24 info attempt registry request try #2 at 12:12:44 AM
25 http request GET https://registry.npmjs.org/connect
26 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=Parse Error
27 info attempt registry request try #3 at 12:13:44 AM
28 http request GET https://registry.npmjs.org/connect
29 verbose stack Error: tunneling socket could not be established, cause=Parse Error
29 verbose stack     at ClientRequest.onError (C:\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:168:17)
29 verbose stack     at ClientRequest.g (events.js:199:16)
29 verbose stack     at ClientRequest.emit (events.js:107:17)
29 verbose stack     at Socket.socketOnData (_http_client.js:322:9)
29 verbose stack     at Socket.emit (events.js:107:17)
29 verbose stack     at readableAddChunk (_stream_readable.js:163:16)
29 verbose stack     at Socket.Readable.push (_stream_readable.js:126:10)
29 verbose stack     at TCP.onread (net.js:538:20)
30 verbose cwd C:\Users\Toshiba PC
31 error Windows_NT 6.3.9600
32 error argv "C:\\nodejs\\\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "connect"
33 error node v0.12.7
34 error npm  v2.11.3
35 error code ECONNRESET
36 error network tunneling socket could not be established, cause=Parse Error
36 error network This is most likely not a problem with npm itself
36 error network and is related to network connectivity.
36 error network In most cases you are behind a proxy or have bad network settings.
36 error network
36 error network If you are behind a proxy, please make sure that the
36 error network 'proxy' config is set properly.  See: 'npm help config'
37 verbose exit [ 1, true ]

**Comment by waivek** [comment]
Is there any solution or will I have to install npm packages manually?

**Comment by waivek** [comment]
I solved it, and the mistake was really stupid. It wasn't a problem with npm, my git was configured incorrectly. Running

`git config --global url."https://".insteadOf git://`

fixed my problem. Sorry for wasting your time.
