### ISSUE TITLE
npm@3 global install issues in node 0.12., windows 8.1

### ISSUE THREAD

**Issue by HansS** [npm/npm#8939]
```
C:\Users\Hans\web\angular\test\test1>npm i -g phonegap
(try to install phonegap globally)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "node" "C:\\Users\\Hans\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "-g" "phonegap"
npm ERR! node v0.12.7
npm ERR! npm  v3.0.0
npm ERR! path C:\Users\Hans\AppData\Roaming\npm\node_modules\cli-example
npm ERR! code ENOENT
npm ERR! errno -4058

npm ERR! enoent ENOENT, stat 'C:\Users\Hans\AppData\Roaming\npm\node_modules\cli-example'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
```

**Comment by othiym23** [comment]
The `npm@3` beta is moving pretty fast, and `npm@v3.x-latest` is currently `npm@3.1.0`. Try upgrading and see if it (or perhaps `npm@v3.x-next`, which `npm@3.1.2`) still has the same problem?

**Comment by HansS** [comment]
Hi Forrell,
thank's for the message!
npm install -g is not working anymore, so i can not install any other npm version.
kind regards!Hans

Date: Tue, 14 Jul 2015 20:42:34 -0700

**Comment by cchamberlain** [comment]
'npm install -g npm' has always broken the windows npm paths for me.   I would try to install npm 2 from the windows installer and then use https://www.npmjs.com/package/npm-windows-upgrade to upgrade.

**Comment by robertbaker** [comment]
This works https://github.com/felixrieseberg/npm-windows-upgrade

**Comment by iarna** [comment]
I'm closing this as resolved. If you run into issues again in the future, please open a new issue, thank you! =)
