### ISSUE TITLE
Events for output on npm.commands.install, and npm.commands.start

### ISSUE THREAD

**Issue by erikmellum** [npm/npm#8941]
When you use NPM programmatically there is no way to get feedback until the commands finish executing. If events were added for when stdout, and stderr get new data it would be useful to people who use the tool programatically.

**Comment by othiym23** [comment]
Although it is (occasionally?) useful to external developers, the current API is unsupported and and not guaranteed to be fit for any particular purpose. As such, we're unlikely to make changes to it for third-party uses. Our goal is to break the CLI down into a set of smaller, more loosely-coupled independent APIs. Closing as not applicable to the current API.

**Comment by othiym23** [comment]
(Thanks for taking the time to put together the feature request with a use case included!)
