### ISSUE TITLE
Could not find npm after installing npm@3

### ISSUE THREAD

**Issue by monolithed** [npm/npm#8942]
```
➜ sudo npm install -g npm@3

➜ npm -v
bash: /usr/local/bin/npm: No such file or directory
```

[npm-debug.log](http://pastebin.com/9Nz1dEhu)

After reinstalling:

```
➜ sudo npm install -g npm@3.1.2

➜ npm -v
3.1.2
```

**Comment by cchamberlain** [comment]
If you installed initially with brew it might be related to that - https://gist.github.com/DanHerbert/9520689

**Comment by monolithed** [comment]
I can replicate it using [pkg](https://nodejs.org/dist/v0.12.7/node-v0.12.7.pkg)

**Comment by iarna** [comment]
npm@2 has this bug where it can delete itself when updating. This is something npm@3 fixes for upgrades _from_ npm@3, but obviously that doesn't help npm@2 installs. It's unfortunate, but I'm going close this as it's fixed going forward.
