### ISSUE TITLE
'npm init' difficulties

### ISSUE THREAD

**Issue by rcardiff1** [npm/npm#8944]
// Hi, when I went to 'npm init' using my terminal, I dragged and dropped my folder into my terminal, typed in 'npm init' and the terminal prompted with:

This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg> --save` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
name: (Cardiff) n

// Once I saw the 'name: (Cardiff)' ...which was wrong I typed 'n' so that I could change the 'name:' but  I  immediately received the following:

version: (1.0.0) (simpleserver)
Invalid version: "(simpleserver)"

// Now the terminal is now allowing me to type anything. I would like to change the 'name:' to (simpleserver). Can anyone help me with this simple issue?

**Comment by rcardiff1** [comment]
![screen shot 2015-07-14 at 6 25 14 pm](https://cloud.githubusercontent.com/assets/12597399/8688773/e61c8f58-2a54-11e5-96b2-aa3c287b7979.png)

**Comment by KenanY** [comment]
@rcardiff1 When it asks for the module's name you should simply enter the name you'd like; "name" isn't a y/n thing.

**Comment by rcardiff1** [comment]
Hi, I figured it out after playing with it for a while. Next time I'll work at it a bit more prior to asking... thanks for the response!

**Comment by othiym23** [comment]
Closing as resolved! Thanks as always, @KenanY!

**Comment by LaNa215** [comment]
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg> --save` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
name: (hxgntagpro jsfiles).....................wen i went to npm init in comment prompt...i m seeing the above lines ..and package.json file is not created in folder...what am i supposed to do.

**Comment by Charlotteis** [comment]
Hey @LaNa215, itd be best to create a new issue for this as this is a very old resolved issue.

As @KenanY said, 

> When it asks for the module's name you should simply enter the name you'd like; "name" isn't a y/n thing.

So you are supposed to fill out the fields and then a package.json will be created.

If you pressed ^C to quit, a package.json won't be created.
