### ISSUE TITLE
Unable to unpublish initial version

### ISSUE THREAD

**Issue by binarykitchen** [npm/npm#8946]
```
$ npm unpublish @1.0.1
- zxcvbn-npm@1.0.1
```

worked fine. But when I did

```
$ npm unpublish @1.0.0
- zxcvbn-npm@1.0.1
```

then it says it didn't really unpublish the initial version. I indicated version X but it responded with version Y. A bug?

Then, I want this package to be removed completely. How?

**Comment by othiym23** [comment]
Running `npm unpublish zxcvbn-npm` again will unpublish the whole package. If that doesn't work, try `npm unpublish -f zxcvbn-npm`. If that doesn't work, leave another message here and we'll take a look at the registry and / or npm.

> A bug?

I don't think so. The behavior of npm when omitting the package number but including the version number is undefined, and I'm not exactly sure what npm will decide to do at that point. If it fails for `npm unpublish zxcvbn-npm@1.0.0`, then that's a bug.

**Comment by binarykitchen** [comment]
Ah, thanks `npm unpublish -f zxcvbn-npm` did it
