### ISSUE TITLE
Attempt to unlock /home/optimist230994/node_modules/connect, which hasn't been locked

### ISSUE THREAD

**Issue by optmist2309** [npm/npm#8948]
![screenshot from 2015-07-15 13 22 13](https://cloud.githubusercontent.com/assets/8707393/8693424/9bf7e9ea-2af4-11e5-8161-197195f81359.png)

**Comment by KenanY** [comment]
@optmist2309 Looks like a permissions issue to me. Could you try?:

``` bash
$ sudo chown -R $(whoami) "$HOME/.npm"
```

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
