### ISSUE TITLE
Getting Issue while running npm install –g grunt-cli

### ISSUE THREAD

**Issue by RonanTheAccuser** [npm/npm#8950]
Hi All
I am trying to install Grunt and Bower and i am getting below error while doing installation

```
verbose cwd C:\Users\admin\angularjs\work\–g
40 error Windows_NT 6.1.7601
41 error argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "–g" "grunt"
42 error node v0.12.2
43 error npm  v2.7.4
44 error path C:\Users\admin\angularjs\work\–g
45 error code ENOENT
46 error errno -4058
47 error enoent ENOENT, open 'C:\Users\admin\angularjs\work\–g'
47 error enoent This is most likely not a problem with npm itself
47 error enoent and is related to npm not being able to find a file.
48 verbose exit [ -4058, true ]
```

**Comment by KenanY** [comment]
@RonanTheAccuser Try using a regular hyphen:

```
$ npm install -g grunt-cli
```

**Comment by othiym23** [comment]
What @KenanY said: you were using some other kind of dash on the command line, so npm was trying to install a package named `–g` and not installing the package globally, and the Windows filesystem didn't like that name. Closing as resolved!

**Comment by RonanTheAccuser** [comment]
Hi
I tried using normal hyphen in the Git bash command line and tried to run that again, but still getting same error, please help

**Comment by KenanY** [comment]
@RonanTheAccuser That's odd. If you're using a regular hyphen but the error is the same, then somehow it's being... mutated to a hyphen-minus?
