### ISSUE TITLE
Git URLs as nested Dependencies

### ISSUE THREAD

**Issue by rashtao** [npm/npm#8952]
In case I have many times the same dependency (same pkg, same ver) in my dependency tree, the default behaviour of `npm install` (when fetching packages from `npmjs.com`) is to fetch that dependency only once.

But when using [Git URLs as Dependencies](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies), that dependency is fetched many times and each package has its own copy of that dependency!

I created a tests project to show the problem: [npm_git_deps_bug](https://github.com/rashtao/npm_git_deps_bug)

**Comment by othiym23** [comment]
What's the bug? The duplication? Or is it fetching the wrong version of the dependency? In general, npm's handling of git dependencies is pretty conservative, because of the way committishes can move around.

**Comment by rashtao** [comment]
The bug is the duplication, the versions fetched are fine.
I have updated my [example](https://github.com/rashtao/npm_git_deps_bug) to show more explicitly the problems that this could cause:

```js
var assert = require("assert");
var bunyan = require("bunyan");
var dep = require("npm_deps_test_dep");

assert(bunyan === dep.bunyan);
```

The assertion is satisfied when fetching the packages from `npm.js`, while it fails when fetching from `git`.

This represents a problem in all the cases that the required package has its own internal state variables (so I think it's a **huge problem**!).

PS: The nodejs behaviour is described here: [https://nodejs.org/api/modules.html#modules_module_caching_caveats](https://nodejs.org/api/modules.html#modules_module_caching_caveats).

**Comment by iarna** [comment]
Hi! Thanks for taking the time to make this request. If you give a try with `npm@3` I think you'll see deduplication of git deps just as it does registry deps too. But what you're asking for in your example is never guaranteed with `npm`, because a dep conflict can always trigger nesting and different copies. If you need singleton-style behavior, your module should explicitly implement this itself.
