### ISSUE TITLE
npm lowercases the links in package.json

### ISSUE THREAD

**Issue by tunnckoCore** [npm/npm#8961]
Hi.
That is from awhile.. i think from v2, but not sure. It seems that it lowercase _all_ (im not sure for now) links that are written to package.json and the registry - if not all, it's for "homepage" links. It's like so, because cuz github is not case sensitive, but it's not good, imo.

Try https://github.com/helpers/helper-related or run https://github.com/tunnckoCore/npm-related CLI to see the case.

```
- [is-typeof-error](https://github.com/tunnckocore/is-typeof-error#readme): Check that given value is any type of error and instanceof Error
- [is-missing](https://github.com/tunnckocore/is-missing#readme): Check that given `name` or `user/repo` exists in npm registry or in github as user repository.
- [ip-filter](https://github.com/tunnckocore/ip-filter#readme): Filter valid IPv4 or IPv6 IP against glob pattern, array, string, regexp or matcher function, if match return the checked IP, otherwise return falsey value.
```

First: it lowercase my username.
Second: It also started to adds that weird `#readme` to the end of github links and that's strange and not okey for me.

I open the issue here, cuz im not sure which package is responsible for these things.

**Comment by cchamberlain** [comment]
@tunnckoCore - Usernames are always lowercased on npm, you can't create a username with uppercase letters.  IMO - urls should be lowercased, urls are case insensitive but you shouldn't rely on the case being persistent.  Urls will often be rewritten by module middleware.

GitHub clone works interchangeably with uppercase or lowercase letters as well so their shouldn't be a bug unless you've implemented something that depends on case sensitivity in urls.

The #readme just makes the browser jump to a readme anchor on your GitHub page and you can modify it if you like but it should work well with GitHub defaults.

**Comment by tunnckoCore** [comment]
Know that things about the npm username and case insensitivity of Github. And I almost never relies on case sensitivity of whatever, but it's weird to lowercase and add some things somewhere.
These things forces you to do some manipulations on your side, instead of just AS IS; which is cost on one or another side.

**Comment by iamstarkov** [comment]
> Second: It also started to adds that weird #readme to the end of github links and that's strange and not okey for me.

it totally fine, because you really get a link to readme, not to repo with need to scroll down to get readme

**Comment by cchamberlain** [comment]
@tunnckoCore - As I said, you shouldn't need to do anything special unless you've implemented case sensitive url handling (not recommended). Is there something specific that is being broken right now?

**Comment by tunnckoCore** [comment]
>  do anything special unless you've implemented case sensitive url handling

and removing last weird `#readme`

> Is there something specific that is being broken right now?

actually, code no. my and im sure not only my habits, principales and habits. im sure that im not the only one that dont like these things and these "defaults" forced without notice and (i think, but not sure) without announcement in the release/changelog.
