### ISSUE TITLE
some packages installed and saved without default semver range operator

### ISSUE THREAD

**Issue by iamstarkov** [npm/npm#8964]
For example if you will install [`npm i -d eslint-config-airbnb`](https://npmjs.com/package/eslint-config-airbnb), then you will end with strict version "0.0.6", but expected string looks like "^0.0.6".

its quite confusing and I cannot find explanation [in the docs](https://docs.npmjs.com/all).

If it can help, I create [testcase in the repo](https://github.com/iamstarkov/npm-save-testcase).

    ➜  ~  node -v && npm -v # OS X 10.10.4
    v2.3.4
    2.13.0

**Comment by charlierudolph** [comment]
I believe that's because "^0.0.6" is equivalent to "0.0.6". This is because when on "0.0.X", patch updates are considered breaking. Take a look at [node-sermver](https://github.com/npm/node-semver#caret-ranges-123-025-004)'s explanation of carat.

**Comment by iamstarkov** [comment]
Thanks a lot
