### ISSUE TITLE
npm version runs git commit and git tag before version script ends

### ISSUE THREAD

**Issue by ClementParis016** [npm/npm#8966]
I am trying to run a Grunt task on npm version using npm scripts like follows:

```js
"scripts": {
    "version": "grunt release --compile && git add -A"
  }
```

According to the [official documentation for npm version](https://docs.npmjs.com/cli/version), the git commit and git tag are run **after** the version script itself. But in my case, the files created by the grunt task and staged with git are never part of the commit and tag created by npm version.

Maybe npm doesn't wait for the version script to finish before committing and tagging? Any help would be appreciate! :)

I am running npm 2.11.2 along Node 0.12.5 on Windows 8.1

**Comment by othiym23** [comment]
The thing about that documentation is that it reflects the newest stable version of npm, which in this case is `npm@2.13.0`. If you look at that version's [release notes](https://github.com/npm/npm/releases/tag/v2.13.0), you'll see that this behavior has been tweaked a little recently. Give the new version a shot and let us know if that has the behavior you're expecting?

**Comment by ClementParis016** [comment]
Great, this is exactly what I wanted! My files are now correctly added to the version commit and tag.
Thanks for your help.
