### ISSUE TITLE
'npm install -g ungit' fails with error:140770FC

### ISSUE THREAD

**Issue by RobSmyth** [npm/npm#8976]
Hi,

I'm unable to install ungit using the command line "npm install -g ungit'. The error message is:
```
$ npm install -g ungit
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ungit"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code EPROTO
npm ERR! errno EPROTO
npm ERR! syscall write

npm ERR! write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:782:
npm ERR!
```

Any help?

Thx

Rob Smyth

**Comment by RobSmyth** [comment]
Here is contents from the log file:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'ungit@0.8.4' ]
2 info using npm@2.11.2
3 info using node@v0.12.5
4 verbose install initial load of C:\Users\rsx\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\rsx\AppData\Roaming\npm\package.json
6 silly cache add args [ 'ungit@0.8.4', null ]
7 verbose cache add spec ungit@0.8.4
8 silly cache add parsed spec { raw: 'ungit@0.8.4',
8 silly cache add   scope: null,
8 silly cache add   name: 'ungit',
8 silly cache add   rawSpec: '0.8.4',
8 silly cache add   spec: '0.8.4',
8 silly cache add   type: 'version' }
9 silly addNamed ungit@0.8.4
10 verbose addNamed "0.8.4" is a plain semver version for ungit
11 silly mapToRegistry name ungit
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry https://registry.npmjs.org/
14 silly mapToRegistry uri https://registry.npmjs.org/ungit
15 verbose addNameVersion registry:https://registry.npmjs.org/ungit not in flight; fetching
16 verbose request uri https://registry.npmjs.org/ungit
17 verbose request no auth needed
18 info attempt registry request try #1 at 7:23:26 PM
19 verbose request id ad05d93a2f5381e7
20 http request GET https://registry.npmjs.org/ungit
21 info retry will retry, error on last attempt: Error: write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:782:
22 info attempt registry request try #2 at 7:23:36 PM
23 http request GET https://registry.npmjs.org/ungit
24 info retry will retry, error on last attempt: Error: write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:782:
25 info attempt registry request try #3 at 7:24:36 PM
26 http request GET https://registry.npmjs.org/ungit
27 verbose stack Error: write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:782:
27 verbose stack
27 verbose stack     at exports._errnoException (util.js:746:11)
27 verbose stack     at WriteWrap.afterWrite (net.js:775:14)
28 verbose cwd C:\ProgramData\chocolatey
29 error Windows_NT 6.1.7601
30 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ungit@0.8.4"
31 error node v0.12.5
32 error npm  v2.11.2
33 error code EPROTO
34 error errno EPROTO
35 error syscall write
36 error write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:782:
37 error If you need help, you may report this error at:
37 error     <https://github.com/npm/npm/issues>
38 verbose exit [ 1, true ]

**Comment by meklarian** [comment]
I was able to workaround the same error by setting the npm registry url to the non-https version (I'm behind a web proxy / firewall) as described here:

http://stackoverflow.com/questions/8874363/npm-install-without-ssl

... and issuing this before installing the package I wanted.

npm config set registry http://registry.npmjs.org/

**Comment by RobSmyth** [comment]
Thank you meklarian ... that worked!

Rob

**Comment by thiagobarso** [comment]
The error persist. I change the registry variable to use **http** instead of https. I'm using ubuntu version 16.04, node version 8.9.1, npm v5.5.1 and behind a proxy.
