### ISSUE TITLE
'npm install -g bower' error 

### ISSUE THREAD

**Issue by cuongnv764119** [npm/npm#8978]
i'm trying to install package bower but it always thow error. Can any one help me to slove this?
Here is my .log

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'bower' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose install initial load of C:\Users\Itachi-Sama\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\Itachi-Sama\AppData\Roaming\npm\package.json
6 silly cache add args [ 'bower', null ]
7 verbose cache add spec bower
8 silly cache add parsed spec { raw: 'bower',
8 silly cache add   scope: null,
8 silly cache add   name: 'bower',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed bower@*
10 verbose addNamed "*" is a valid semver range for bower
11 silly addNameRange { name: 'bower', range: '*', hasData: false }
12 silly mapToRegistry name bower
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry http://registry.npmjs.org/
15 silly mapToRegistry uri http://registry.npmjs.org/bower
16 verbose addNameRange registry:http://registry.npmjs.org/bower not in flight; fetching
17 verbose request uri http://registry.npmjs.org/bower
18 verbose request no auth needed
19 info attempt registry request try #1 at 9:03:15 PM
20 verbose request id 72bb93a04a1ba34e
21 verbose etag "D166K4DV3FKFHHDXX16WKIR59"
22 http request GET http://registry.npmjs.org/bower
23 http 304 http://registry.npmjs.org/bower
24 silly get cb [ 304,
24 silly get   { date: 'Fri, 17 Jul 2015 14:03:57 GMT',
24 silly get     via: '1.1 varnish',
24 silly get     'cache-control': 'max-age=60',
24 silly get     etag: '"D166K4DV3FKFHHDXX16WKIR59"',
24 silly get     age: '53',
24 silly get     connection: 'keep-alive',
24 silly get     'x-served-by': 'cache-hkg6822-HKG',
24 silly get     'x-cache': 'HIT',
24 silly get     'x-cache-hits': '1',
24 silly get     'x-timer': 'S1437141837.720092,VS0,VE0',
24 silly get     vary: 'Accept' } ]
25 verbose etag http://registry.npmjs.org/bower from cache
26 verbose get saving bower to C:\Users\Itachi-Sama\AppData\Roaming\npm-cache\registry.npmjs.org\bower\.cache.json
27 silly addNameRange number 2 { name: 'bower', range: '*', hasData: true }
28 silly addNameRange versions [ 'bower',
28 silly addNameRange   [ '0.1.0',
28 silly addNameRange     '0.1.2',
28 silly addNameRange     '0.1.3',
28 silly addNameRange     '0.2.0',
28 silly addNameRange     '0.3.0',
28 silly addNameRange     '0.3.1',
28 silly addNameRange     '0.3.2',
28 silly addNameRange     '0.4.0',
28 silly addNameRange     '0.5.0',
28 silly addNameRange     '0.5.1',
28 silly addNameRange     '0.6.0',
28 silly addNameRange     '0.6.1',
28 silly addNameRange     '0.6.2',
28 silly addNameRange     '0.6.3',
28 silly addNameRange     '0.6.4',
28 silly addNameRange     '0.6.5',
28 silly addNameRange     '0.6.6',
28 silly addNameRange     '0.6.7',
28 silly addNameRange     '0.6.8',
28 silly addNameRange     '0.7.0',
28 silly addNameRange     '0.7.1',
28 silly addNameRange     '0.8.0',
28 silly addNameRange     '0.8.1',
28 silly addNameRange     '0.8.2',
28 silly addNameRange     '0.8.3',
28 silly addNameRange     '0.8.4',
28 silly addNameRange     '0.8.5',
28 silly addNameRange     '0.8.6',
28 silly addNameRange     '0.9.0',
28 silly addNameRange     '0.9.1',
28 silly addNameRange     '0.9.2',
28 silly addNameRange     '0.10.0',
28 silly addNameRange     '1.0.0',
28 silly addNameRange     '1.0.1',
28 silly addNameRange     '1.0.2',
28 silly addNameRange     '1.0.3',
28 silly addNameRange     '1.1.0',
28 silly addNameRange     '1.1.1',
28 silly addNameRange     '1.1.2',
28 silly addNameRange     '1.2.0',
28 silly addNameRange     '1.2.1',
28 silly addNameRange     '1.2.2',
28 silly addNameRange     '1.2.3',
28 silly addNameRange     '1.2.4',
28 silly addNameRange     '1.2.5',
28 silly addNameRange     '1.2.6',
28 silly addNameRange     '1.2.7',
28 silly addNameRange     '1.2.8',
28 silly addNameRange     '1.3.0',
28 silly addNameRange     '1.3.1',
28 silly addNameRange     '1.3.2',
28 silly addNameRange     '1.3.3',
28 silly addNameRange     '1.3.4',
28 silly addNameRange     '1.3.5',
28 silly addNameRange     '1.3.6',
28 silly addNameRange     '1.3.7',
28 silly addNameRange     '1.3.8',
28 silly addNameRange     '1.3.9',
28 silly addNameRange     '1.3.10',
28 silly addNameRange     '1.3.11',
28 silly addNameRange     '1.3.12',
28 silly addNameRange     '1.4.0',
28 silly addNameRange     '1.4.1' ] ]
29 silly addNamed bower@1.4.1
30 verbose addNamed "1.4.1" is a plain semver version for bower
31 silly mapToRegistry name bower
32 silly mapToRegistry using default registry
33 silly mapToRegistry registry http://registry.npmjs.org/
34 silly mapToRegistry uri http://registry.npmjs.org/bower
35 verbose addRemoteTarball http://registry.npmjs.org/bower/-/bower-1.4.1.tgz not in flight; adding
36 verbose addRemoteTarball [ 'http://registry.npmjs.org/bower/-/bower-1.4.1.tgz',
36 verbose addRemoteTarball   'a18be39d030792754f30f1c5b32d37b0156ba8dd' ]
37 info retry fetch attempt 1 at 9:03:17 PM
38 info attempt registry request try #1 at 9:03:17 PM
39 http fetch GET http://registry.npmjs.org/bower/-/bower-1.4.1.tgz
40 http fetch 200 http://registry.npmjs.org/bower/-/bower-1.4.1.tgz
41 info retry will retry, error on last attempt: Error: read ECONNRESET
42 info retry will retry, error on last attempt: Error: read ECONNRESET
43 silly fetchAndShaCheck shasum a18be39d030792754f30f1c5b32d37b0156ba8dd
44 verbose stack Error: shasum check failed for C:\Users\ITACHI~1\AppData\Local\Temp\npm-4084-ce8564d3\registry.npmjs.org\bower\-\bower-1.4.1.tgz
44 verbose stack Expected: a18be39d030792754f30f1c5b32d37b0156ba8dd
44 verbose stack Actual:   f3af2edb6a8bb54e70804059ebe5391787e151c5
44 verbose stack From:     http://registry.npmjs.org/bower/-/bower-1.4.1.tgz
44 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:38:8
44 verbose stack     at ReadStream.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:85:7)
44 verbose stack     at ReadStream.emit (events.js:129:20)
44 verbose stack     at _stream_readable.js:908:16
44 verbose stack     at process._tickCallback (node.js:355:11)
45 verbose cwd C:\Windows\system32
46 error Windows_NT 6.3.9600
47 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "bower"
48 error node v0.12.7
49 error npm  v2.11.3
50 error shasum check failed for C:\Users\ITACHI~1\AppData\Local\Temp\npm-4084-ce8564d3\registry.npmjs.org\bower\-\bower-1.4.1.tgz
50 error Expected: a18be39d030792754f30f1c5b32d37b0156ba8dd
50 error Actual:   f3af2edb6a8bb54e70804059ebe5391787e151c5
50 error From:     http://registry.npmjs.org/bower/-/bower-1.4.1.tgz
51 error If you need help, you may report this error at:
51 error     <https://github.com/npm/npm/issues>
52 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@cuongnv764119 Have you tried `npm cache clean`?

**Comment by cuongnv764119** [comment]
thanks you @KenanY  i sloved it
