### ISSUE TITLE
Regression in npm 2.13.1

### ISSUE THREAD

**Issue by pkaminski** [npm/npm#8982]
When installing `grunt-contrib-imagemin` 0.9.4 (with deps `imagemin` 3.1.0, `imagemin-gifsicle` 4.1.0, `gifsicle` 2.0.1), the nested `gifsicle` dependency installs fine when using `npm` 2.13.0 and below:

```
> gifsicle@2.0.1 postinstall /root/workspace/src/github.com/Reviewable/reviewable-client/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle
> node lib/install.js
✔ gifsicle pre-build test passed successfully
```

But with 2.13.1 and 2.13.2, it fails:

```
npm WARN cannot run in wd gifsicle@2.0.1 node lib/install.js (wd=/root/workspace/src/github.com/Reviewable/reviewable-client/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle)
```

**Comment by othiym23** [comment]
Yep, this is definitely a regression, introduced by 40981f2e0c9c12bb003ccf188169afd1d201f5af, which adds a check that's meant to be safer for use with scoped packages, but which causes problems when the package name appears multiple times in the working directory's full path. Thanks for filing this!

**Comment by blairstark** [comment]
I also think it reintroduced the permissions issues noted in https://github.com/npm/npm/releases/tag/v2.12.1

'REMEMBER WHEN I SAID "REMEMBER WHEN I SAID THAT THING ABOUT PERMISSIONS?" '

used clean machine with npm@latest which installed 2.13.1

ran 
    yo angular myapp

got a bunch of "npm ERR! tar.unpack untar error" messages...

did 
  npm uninstall -g npm && npm install -g npm@2.12.1

then 
   yo angular myapp

ran without a problem

**Comment by LoicMahieu** [comment]
Fixed with npm@3.3.5
```
> gifsicle@3.0.1 postinstall /builds/node_modules/gifsicle
> node lib/install.js

  ✔ gifsicle pre-build test passed successfully
```

**Comment by elvanja** [comment]
I've stumbled upon this "multiple package name occurrence in working directory's full path" regression issue for some very strange edge cases, CentOS related only. I've created a PR #10582 that resolves this for my usage. Hope this helps.

**Comment by pkaminski** [comment]
Any chance that this fix will be backported to the 2.x LTS branch?
