### ISSUE TITLE
man page renders post-grave content strangely

### ISSUE THREAD

**Issue by steveklabnik** [npm/npm#8984]
If this is just a bug in https://github.com/kapouer/marked-man, let me know and I'll re-file. I tried to figure out how NPM generates its manfiles, and I _think_ that's true, but I'm not sure!

I'm getting strangeness in my manfiles:

![2015-07-17-191638_694x71_scrot](https://cloud.githubusercontent.com/assets/27786/8758918/9d7443a2-2cb8-11e5-889b-fc56d9cbec9f.png)
![2015-07-17-191658_472x67_scrot](https://cloud.githubusercontent.com/assets/27786/8758917/9d7360cc-2cb8-11e5-86af-a3222154b94f.png)

from these two examples, I would _guess the issue is having graves ( \` ) in a second-level heading ( `##` ) causes strangeness. These two examples both from the FAQ

**Comment by othiym23** [comment]
Yes, those docs are indeed run through `marked-man`, so that would be the place to point out Markdown parsing irregularities. I'll leave this open until it's sorted out to your satisfaction, though. Thanks for the screenshots!

**Comment by steveklabnik** [comment]
:confetti_ball:
