### ISSUE TITLE
Packages ending in .app are interpreted as an application in OSX

### ISSUE THREAD

**Issue by paulfalgout** [npm/npm#8986]
XRef: https://github.com/RoundingWellOS/marionette.toolkit/issues/129

We started packaging the modules of our marionette.toolkit separately and publishing them on npm, but we noticed on OSX if you add marionette.toolkit.app as a dependency it will download, but npm will fail as, I believe once downloaded OSX sees it as an Application instead of a directory (so its dependencies are never installed)

Any way around this?

If not, it seems like this needs to be documented on the troubleshooting wiki?

https://github.com/RoundingWellOS/marionette.toolkit/blob/master/packages/App/package.json

**Comment by othiym23** [comment]
I'm not sure what behavior you're seeing that's a problem:

```
bauchelain% npm i marionette.toolkit.app
npm WARN package.json test-marionette-app@1.0.0 No description
npm WARN package.json test-marionette-app@1.0.0 No repository field.
npm WARN package.json test-marionette-app@1.0.0 No README data
marionette.toolkit.app@0.4.1 node_modules/marionette.toolkit.app
├── underscore@1.8.3
├── backbone@1.2.1
└── backbone.marionette@2.4.2 (backbone.babysitter@0.1.8, backbone.wreqr@1.3.3)
```

Run on OS X 10.10.4. OS X applications are treated specially by the Finder, but unless you run `open` on them in a terminal, they're basically just another directory. What behavior are you seeing?

npm isn't treating them specially, and I'm not sure what npm could do to work around this, unless something pops out at me when you describe the problems you're having.

**Comment by paulfalgout** [comment]
Sorry for the delay.

Originally I was looking over the shoulder of a colleague who was getting npm errors on install..  it was failing on our `.app` library and the only thing that seemed out of place was that it was showing up as an Application in finder.

But now I can't reproduce the issue myself.  I'll close this for now, and see if we can reproduce it in the office later.  It seemed suspicious that we'd be the first to run into this issue, so I wouldn't be surprised if it isn't a thing.
