### ISSUE TITLE
npm install module@~version dont match max satisfying version

### ISSUE THREAD

**Issue by fengmk2** [npm/npm#8991]
e.g.: https://www.npmjs.com/package/testnpm2
- latest: 1.0.0
- versions: [1.0.0, 1.0.1]

Except: 

```
npm install testnpm2@~1.0.0 => 1.0.1
```

Actual:

```
npm install testnpm2@~1.0.0 => 1.0.0
```

**Comment by iarna** [comment]
I'm adding this to a 3.x milestone, because that defines the work I'm going to do really soon, but it may go into 2.x if appropriate. =)

**Comment by iarna** [comment]
But I want to step back and document exactly what the current version resolution behavior is in both 2.x and 3.x, and then we can come back and talk about how it needs to change. It's implemented in multiple files so just patching the cache won't necessarily fix it for all scenarios.

**Comment by fengmk2** [comment]
@iarna Thanks.

**Comment by iarna** [comment]
Ok, here's how the code in `lib/cache/add-named.js` works:

cache.add:

1. If the version specifier is `semver.valid`:
  1. Fetch registry information for package.
  2. If the a copy of that package exists in the cache and the shasum matches what
     we got from the registry:
     1. Return the package.json from the cache
  3. Else
     1. Fetch the tarball from the registry, mutating the registry url to match
        the protocol of the registry, eg, https registry -> https tarballs.
     2. Pass the tarball off to `cache/add-remote-tarball.js`
2. If the version specifier is `semver.validRange`:
  1. Fetch registry information for package.
  2. If `engine-strict` is set and `force` is NOT set, remove versions that
     don't match from the list of versions.
  3. If the value of `--tag` (or `latest` by default`) isin `data['dist-tags']` and the
     version it references exists, and that version matches your semver
     range then we go back to the start but using the tag name as the version specifier.
  4. The list of version humbers is passed to `semver.maxSatisfying` with the range
     specifier.
  5. If nothing is returned:
     1. And the range is '*' and there ARE versions published, try again with `latest`
        as the version specifier.
     2. Else return an error reporting no versions matching
  6. Else, loop back in with the specific version as the version specifier.
3. Else we assume the verion is a tag:
  1. Fetch registry information for package.
  2. If `engine-strict` is set and `force` is NOT set, remove versions that
     don't match from the list of versions.
  3. If the tag is in dist tags and that dist tag refers to an existing version:
    1. Loop back with that matching tag as the version specifier
  4. Else if no tag name was passed in and there are available versions
    1. Loop back with `*` as the version specifier
  5. Else return an error reporting no versions matching

**Comment by iarna** [comment]
Your patch is deleting `2.iii.`.  This is intended behavior, and changing this would be a breaking change. I'd like to understand more about why you want this if we're going to consider changing this behavior.

We currently use this behavior with npm. If you run `npm install -g npm@2` you'll get the `2.13.2` which is tagged as `latest`.  This despite the fact that `2.13.3` is currently in the registry (it'll be made `latest` when we release a new version this Thursday). 

Can you describe a use case where you want `npm install` to ignore `latest` and install the highest version published instead?

**Comment by fengmk2** [comment]
I think `npm@2` need to follow `semver` rule and not to follow `latest` tag.

**Comment by KenanY** [comment]
@fengmk2 Where in [SemVer](http://semver.org/) is this rule?
