### ISSUE TITLE
npm ERR notsup ?

### ISSUE THREAD

**Issue by TreBey** [npm/npm#8993]
Hi, i'm running into a lot of problems using npm today. I tried to npm install semantic-ui and it threw an error, so i tried updating npm itself, and it threw another error. Not really sure what's going on, as i'm still pretty unfamiliar with the command prompt in general. Can someone tell me what I may be doing wrong? Thanks! 

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'n' ]
2 info using npm@2.10.1
3 info using node@v0.12.4
4 verbose install initial load of C:\Users\T\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\T\AppData\Roaming\npm\package.json
6 silly cache add args [ 'n', null ]
7 verbose cache add spec n
8 silly cache add parsed spec { raw: 'n',
8 silly cache add   scope: null,
8 silly cache add   name: 'n',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed n@*
10 verbose addNamed "*" is a valid semver range for n
11 silly addNameRange { name: 'n', range: '*', hasData: false }
12 silly mapToRegistry name n
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/n
16 verbose addNameRange registry:https://registry.npmjs.org/n not in flight; fetching
17 verbose request uri https://registry.npmjs.org/n
18 verbose request no auth needed
19 info attempt registry request try #1 at 6:56:45 PM
20 verbose request id 571d8acba59fd532
21 http request GET https://registry.npmjs.org/n
22 http 200 https://registry.npmjs.org/n
23 silly get cb [ 200,
23 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
23 silly get     etag: '"EN1IKGWSZ46GDCRWKSMQQ2N65"',
23 silly get     'content-type': 'application/json',
23 silly get     'cache-control': 'max-age=60',
23 silly get     'content-length': '41921',
23 silly get     'accept-ranges': 'bytes',
23 silly get     date: 'Sat, 18 Jul 2015 23:56:52 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     age: '0',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-dfw1825-DFW',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '1',
23 silly get     'x-timer': 'S1437263812.191947,VS0,VE191',
23 silly get     vary: 'Accept' } ]
24 verbose get saving n to C:\Users\T\AppData\Roaming\npm-cache\registry.npmjs.org\n\.cache.json
25 silly addNameRange number 2 { name: 'n', range: '*', hasData: true }
26 silly addNameRange versions [ 'n',
26 silly addNameRange   [ '0.0.1',
26 silly addNameRange     '0.0.2',
26 silly addNameRange     '0.0.3',
26 silly addNameRange     '0.0.4',
26 silly addNameRange     '0.1.0',
26 silly addNameRange     '0.1.1',
26 silly addNameRange     '0.1.2',
26 silly addNameRange     '0.2.0',
26 silly addNameRange     '0.2.1',
26 silly addNameRange     '0.2.2',
26 silly addNameRange     '0.3.0',
26 silly addNameRange     '0.4.0',
26 silly addNameRange     '0.4.1',
26 silly addNameRange     '0.4.2',
26 silly addNameRange     '0.5.0',
26 silly addNameRange     '0.5.1',
26 silly addNameRange     '0.5.2',
26 silly addNameRange     '0.5.3',
26 silly addNameRange     '0.5.4',
26 silly addNameRange     '0.6.0',
26 silly addNameRange     '0.6.1',
26 silly addNameRange     '0.7.0',
26 silly addNameRange     '0.7.1',
26 silly addNameRange     '0.7.2',
26 silly addNameRange     '0.7.3',
26 silly addNameRange     '0.8.0',
26 silly addNameRange     '0.8.1',
26 silly addNameRange     '0.8.2',
26 silly addNameRange     '0.9.0',
26 silly addNameRange     '0.9.1',
26 silly addNameRange     '0.9.2',
26 silly addNameRange     '0.9.3',
26 silly addNameRange     '1.0.0',
26 silly addNameRange     '1.1.0',
26 silly addNameRange     '1.2.1',
26 silly addNameRange     '1.2.2',
26 silly addNameRange     '1.2.3',
26 silly addNameRange     '1.2.4',
26 silly addNameRange     '1.2.5',
26 silly addNameRange     '1.2.6',
26 silly addNameRange     '1.2.7',
26 silly addNameRange     '1.2.8',
26 silly addNameRange     '1.2.9',
26 silly addNameRange     '1.2.11',
26 silly addNameRange     '1.2.13',
26 silly addNameRange     '1.2.14',
26 silly addNameRange     '1.3.0' ] ]
27 silly addNamed n@1.3.0
28 verbose addNamed "1.3.0" is a plain semver version for n
29 silly mapToRegistry name n
30 silly mapToRegistry using default registry
31 silly mapToRegistry registry https://registry.npmjs.org/
32 silly mapToRegistry uri https://registry.npmjs.org/n
33 verbose addRemoteTarball https://registry.npmjs.org/n/-/n-1.3.0.tgz not in flight; adding
34 verbose addRemoteTarball [ 'https://registry.npmjs.org/n/-/n-1.3.0.tgz',
34 verbose addRemoteTarball   '95afad80d2c73e89151efc0b4e6a8905cbb8ed2d' ]
35 info retry fetch attempt 1 at 6:56:53 PM
36 info attempt registry request try #1 at 6:56:53 PM
37 http fetch GET https://registry.npmjs.org/n/-/n-1.3.0.tgz
38 http fetch 200 https://registry.npmjs.org/n/-/n-1.3.0.tgz
39 silly fetchAndShaCheck shasum 95afad80d2c73e89151efc0b4e6a8905cbb8ed2d
40 verbose addTmpTarball C:\Users\T\AppData\Local\Temp\npm-3692-918bd8c9\registry.npmjs.org\n\-\n-1.3.0.tgz not in flight; adding
41 verbose addTmpTarball already have metadata; skipping unpack for n@1.3.0
42 silly cache afterAdd n@1.3.0
43 verbose afterAdd C:\Users\T\AppData\Roaming\npm-cache\n\1.3.0\package\package.json not in flight; writing
44 verbose afterAdd C:\Users\T\AppData\Roaming\npm-cache\n\1.3.0\package\package.json written
45 silly install resolved [ { name: 'n',
45 silly install resolved     description: 'node version manager',
45 silly install resolved     version: '1.3.0',
45 silly install resolved     author: { name: 'TJ Holowaychuk', email: 'tj@vision-media.ca' },
45 silly install resolved     homepage: 'https://github.com/tj/n',
45 silly install resolved     bugs: { url: 'https://github.com/tj/n/issues' },
45 silly install resolved     contributors: [ [Object] ],
45 silly install resolved     keywords:
45 silly install resolved      [ 'nvm',
45 silly install resolved        'node',
45 silly install resolved        'version',
45 silly install resolved        'manager',
45 silly install resolved        'switcher',
45 silly install resolved        'node',
45 silly install resolved        'binary',
45 silly install resolved        'env' ],
45 silly install resolved     bin: { n: './bin/n' },
45 silly install resolved     repository: { type: 'git', url: 'git://github.com/tj/n.git' },
45 silly install resolved     preferGlobal: true,
45 silly install resolved     os: [ '!win32' ],
45 silly install resolved     engines: { node: '*' },
45 silly install resolved     license: 'MIT',
45 silly install resolved     gitHead: 'ab194b3b1ca8539b2b1f9f9755d1401a667d0a95',
45 silly install resolved     _id: 'n@1.3.0',
45 silly install resolved     scripts: {},
45 silly install resolved     _shasum: '95afad80d2c73e89151efc0b4e6a8905cbb8ed2d',
45 silly install resolved     _from: 'n@*',
45 silly install resolved     _npmVersion: '1.4.28',
45 silly install resolved     _npmUser: { name: 'tjwebb', email: 'me@traviswebb.com' },
45 silly install resolved     maintainers: [ [Object], [Object], [Object] ],
45 silly install resolved     dist:
45 silly install resolved      { shasum: '95afad80d2c73e89151efc0b4e6a8905cbb8ed2d',
45 silly install resolved        tarball: 'http://registry.npmjs.org/n/-/n-1.3.0.tgz' },
45 silly install resolved     directories: {},
45 silly install resolved     _resolved: 'https://registry.npmjs.org/n/-/n-1.3.0.tgz' } ]
46 info install n@1.3.0 into C:\Users\T\AppData\Roaming\npm
47 info installOne n@1.3.0
48 verbose installOne of n to C:\Users\T\AppData\Roaming\npm not in flight; installing
49 verbose lock using C:\Users\T\AppData\Roaming\npm-cache\_locks\n-a1140d00a9f47103.lock for C:\Users\T\AppData\Roaming\npm\node_modules\n
50 verbose unlock done using C:\Users\T\AppData\Roaming\npm-cache\_locks\n-a1140d00a9f47103.lock for C:\Users\T\AppData\Roaming\npm\node_modules\n
51 verbose stack Error: Unsupported
51 verbose stack     at checkPlatform (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-install-checks\index.js:47:14)
51 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
51 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
51 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
51 verbose stack     at checkEngine (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-install-checks\index.js:26:10)
51 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
51 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
51 verbose stack     at chain (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
51 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:1037:5
51 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\utils\locker.js:40:9
52 verbose pkgid n@1.3.0
53 verbose cwd C:\Users\T\Desktop\Projects\Prolific Me
54 error Windows_NT 6.3.9600
55 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "n"
56 error node v0.12.4
57 error npm  v2.10.1
58 error code EBADPLATFORM
59 error notsup Unsupported
59 error notsup Not compatible with your operating system or architecture: n@1.3.0
59 error notsup Valid OS:    !win32
59 error notsup Valid Arch:  any
59 error notsup Actual OS:   win32
59 error notsup Actual Arch: x64
60 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@TreBey The log says you are running:

``` bash
$ npm install -g n
```

Do you mean to be running?:

``` bash
$ npm install -g npm
```

**Comment by KenanY** [comment]
@TreBey There's also [a guide on the wiki](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows) for upgrading on Windows :)

**Comment by TreBey** [comment]
Thanks KenanY, that link helped!
