### ISSUE TITLE
npm@3 modules that link the same bin can remove a bin it doesn't own

### ISSUE THREAD

**Issue by phated** [npm/npm#8996]
As per @iarna at https://github.com/gulpjs/gulp-cli/issues/7#issuecomment-121037259

I haven't tested this, but a gulp core contributor tested and linked results at https://github.com/gulpjs/gulp-cli/issues/7#issuecomment-120907981

**Comment by iarna** [comment]
Argh, yes, thank you for making these. =D They've been sitting on my todo list for the past few weeks. <.<

**Comment by contra** [comment]
Any ETA on fixing this? We aren't able to release gulp 4.0 until this is fixed

**Comment by iamstarkov** [comment]
im waitin gulp4 for almost one year, pls fix it 🐱

**Comment by iarna** [comment]
You'll note that this is scheduled for today's release.

**Comment by phated** [comment]
Awesome! Thanks @iarna!

**Comment by iarna** [comment]
Hey! Good news! This is out and live in 3.3.0!

**Comment by phated** [comment]
Hooray! :fireworks:
