### ISSUE TITLE
ENOENT error when run "npm install" open '...\yield\invalid-yield-generator-function-declaration.js'

### ISSUE THREAD

**Issue by megion** [npm/npm#9003]
npm ERR! Error: ENOENT, open 'C:\Users\IZADOR~1\AppData\Local\Temp\npm-3484-rUZ_yHxO\github.com\ariya\esprima\tarball\master-unpack\test\fixtures\ES6\yield\invalid-yield-generator-function-declaration.js:'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\Users\izadorozhny\workspaces\lanit-hcs\hcs-new\branches\5.1.0\web\web-packages\common-web-package
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! path C:\Users\IZADOR~1\AppData\Local\Temp\npm-3484-rUZ_yHxO\github.com\ariya\esprima\tarball\master-unpack\test\fixtures\ES6\yield\invalid-yield-generator-function-declaration.js:
npm ERR! code ENOENT
npm ERR! errno 34

My package.json
```
"devDependencies": {
    "gulp": "^3.8",
    "gulp-connect": "^2.0.5",
    "gulp-htmlhint": "0.0.7",
    "gulp-htmlmin": "~0.1.1",
    "gulp-imagemin": "^0.6.1",
    "gulp-karma": "0.0.3",
    "gulp-minify-css": "^0.3.11",
    "gulp-uglify": "^0.1.0",
    "gulp-util": "^2.2.20",
    "gulp-concat": "^2.5.2",
    "gulp-sourcemaps": "^1.5.2",
    "del": "^1.1.1",
    "gulp-jshint": "^1.10.0",
    "gulp-less": "^3.0.3",
    "path": "^0.11.14",
    "run-sequence": "^1.1",
    "gulp-inject": "^1.2",
    "gulp-using": "0.0.1",
    "gulp-merge": "^0.1",
    "gulp-bower": "~0.0.10",
    "gulp-watch": "^4.2",
    "jshint-stylish": "^1.0.0",
    "gulp-ng-html2js": "^0.2",
    "gulp-template": "latest",
    "gulp-data": "latest",
    "gulp-collector" : "latest",
    "list-files" : "latest",

    "grunt": "~0.4.1",
    "grunt-contrib-connect": "~0",
    "grunt-connect-proxy": "0.1.10",
    "grunt-contrib-less": "0.11.2",
    "grunt-contrib-clean": "^0.4.1",
    "grunt-contrib-copy": "^0.4.1",
    "grunt-contrib-jshint": "^0.4.3",
    "grunt-contrib-concat": "^0.3.0",
    "grunt-contrib-watch": "^0.4.4",
    "grunt-contrib-uglify": "^0.2.7",
    "grunt-ngmin": "0.0.2",
    "grunt-html2js": "^0.1.9",
    "grunt-contrib-coffee": "^0.7.0",
    "grunt-coffeelint": "~0.0.10",
    "grunt-conventional-changelog": "^0.1.2",
    "grunt-bump": "0.0.6",
    "karma-firefox-launcher": "^0.1.3",
    "karma-jasmine": "^0.1.5",
    "grunt-karma": "^0.8.2",
    "karma-coffee-preprocessor": "^0.2.1",
    "karma": "^0.12.9",
    "karma-ng-html2js-preprocessor": "^0.1.2",
    "lodash": "~2.4.1",
    "load-grunt-tasks": "~0.3.0",
    "rimraf": "2.1",
    "grunt-shell": "0.7"
  }
```

**Comment by RamyElkest** [comment]
I experience the same with a clean checkout of https://github.com/ngbp/ngbp tracked with https://github.com/ngbp/ngbp/issues/395

**Comment by RamyElkest** [comment]
https://github.com/jquery/esprima/issues/1239#issue-95679204
