### ISSUE TITLE
 error argv "node" "/usr/local/bin/npm" "install" "-g" "ionic"

### ISSUE THREAD

**Issue by cmy111246** [npm/npm#9006]
error argv "node" "/usr/local/bin/npm" "install" "-g" "ionic"
2221 error node v0.12.5
2222 error npm  v2.11.2
2223 error unexpected eof
2224 error If you need help, you may report this error at:
2224 error     <https://github.com/npm/npm/issues>
2225 verbose exit [ 1, true ]
2226 verbose unbuild lib/node_modules/ionic
2227 info preuninstall ionic@1.6.1
2228 info uninstall ionic@1.6.1
2229 verbose unbuild rmStuff ionic@1.6.1 from /usr/local/lib/node_modules
2230 silly gentlyRm /usr/local/bin/ionic is being gently removed
2231 silly gentlyRm verifying /usr/local is an npm working directory
2232 silly gentlyRm containing path /usr/local is under npm's control, in /usr/local
2233 silly gentlyRm deletion target /usr/local/bin/ionic is under /usr/local
2234 verbose gentlyRm vacuuming from /usr/local/bin/ionic up to /usr/local
2235 info postuninstall ionic@1.6.1
2236 silly gentlyRm /usr/local/lib/node_modules/ionic is being purged from base /usr/local
2237 verbose gentlyRm don't care about contents; nuking /usr/local/lib/node_modules/ionic
2238 silly vacuum-fs purging /usr/local/lib/node_modules/ionic
2239 silly vacuum-fs quitting because other entries in /usr/local/lib/node_modules

**Comment by usandfriends** [comment]
Try `sudo`.
