### ISSUE TITLE
Cannot find module './permuteDomain' for every install

### ISSUE THREAD

**Issue by kstrack-grose** [npm/npm#9007]
As the title says, every time I try to install or uninstall a module, npm gives me an error where it "cannot find module './permuteDomain'".

**Comment by othiym23** [comment]
What version of npm are you using? Did you update it recently? `permuteDomain` is not something used by npm directly. The only mentions of it I can find is googling is that it's something used by `tough-cookie`, which is a dependency of `request` (which npm does use), which makes me believe that this is perhaps an `npm update -g` gone awry. Can you reinstall npm using the Node installer? That's probably the fastest way to get out of this situation.

**Comment by kstrack-grose** [comment]
Hi,

I hadn't updated npm recently, and also decided that reinstalling npm was
probably the best way to go, and then went and did that. Everything is
working fine now. Thank you for the fast reply!

Best,
K

On Mon, Jul 20, 2015 at 1:53 PM, Forrest L Norvell <notifications@github.com

**Comment by othiym23** [comment]
You're welcome! Closing as resolved!
