### ISSUE TITLE
npm install error EOI -r error

### ISSUE THREAD

**Issue by movie4** [npm/npm#9014]
Hello,
i connect via usb NTFS drive on `mac os yosemite`, and install `tuxera ntfs` for work with ntfs.

Tuxera NTFS — http://www.tuxera.com/products/tuxera-ntfs-for-mac/

```
npm install gulp

output error

npmERR! Darwin 14.4.0
npmERR! argv "node" "/Users/Arkasha/.nvm/versions/node/v0.12.7/bin/npm" "install" "gulp"
npmERR! node v0.12.7
npmERR! npm  v2.13.1
npmERR! path /Volumes/ADATA/node_modules/gulp
npmERR! code EIO
npmERR! errno -5
npmERR! EIO, lstat '/Volumes/ADATA/node_modules/gulp'
npmERR! 
npmERR! If you need help, you may report this error at:
npmERR!     <https://github.com/npm/npm/issues>
npmERR! error rolling back Error: EIO, lstat '/Volumes/ADATA/node_modules/gulp'
npmERR! error rolling back     at Error (native)
npmERR! error rolling back  { [Error: EIO, lstat '/Volumes/ADATA/node_modules/gulp']
npmERR! error rolling back   errno: -5,
npmERR! error rolling back   code: 'EIO',
npmERR! error rolling back   path: '/Volumes/ADATA/node_modules/gulp' }
npmERR! Please include the following file with any support request:
npmERR! /Volumes/ADATA/ITCase/npm-debug.log
```

Thanks

**Comment by othiym23** [comment]
You might try `npm install --no-bin-links gulp`, but if Tuxera causes an I/O error when `lstat` is called on files or directories hosted on it, there's not a lot that npm can do. If `--no-bin-links` doesn't fix your problem, let us know, but I'm afraid the only thing we can say at that point is that Tuxera-hosted NTFS filesystems aren't supported for use with npm.

**Comment by movie4** [comment]
Thanks for you answer - i update Tuxera to 2014 version, and now it works when type 

```
npm install 
```
