### ISSUE TITLE
npm install in cached node_modules

### ISSUE THREAD

**Issue by myitcv** [npm/npm#9017]
We are seeing an issue when running `npm install` where `node_modules` is cached between builds on a CI server.

We depend on `jscs` (the problem is not specific to this package however):
- On our `dev` branch we depend on version `1.13.1`
- On a feature branch we depend on `github@master` of the project for a new feature. It is worth noting the [`package.json@master`](https://github.com/jscs-dev/node-jscs/blob/master/package.json#L8) on Github has a version of `1.13.1`

The problem we are seeing occurs after the following sequence:
- CI build of feature branch happens, installs `github@master` version of `jscs` into cached `node_modules` cache
- CI build of `dev` branch happens, sees `1.13.1` is installed in the cached `node_modules` cache and so does nothing (even though this is the 'version' from `github@master`)
- Things break in the `dev` build because the changes introduced by `github@master` are not backwards compatible (or for other reasons, i.e. we need to fix up our code as is the case here)

It doesn't feel like this is the first time people using a cached `node_modules` would have run into this problem.

Looking through the numerous issues listed on this project (and indeed Google) I can't find any reference to it.

One solution would be for every package maintainer, like `jscs`, to ensure that their `master` branch refers to a new, as yet unreleased version. But glancing at a couple of other projects (e.g. React, `eslint`) this doesn't appear to be common practice and so isn't practical.

Is there another solution?

Thanks

**Comment by othiym23** [comment]
What version of npm are you running? There was a bug in how we were handling git remotes for a while that caused them to not deal with multiple committishes from the same repo in a single install properly that has since been fixed. You might want to try upgrading npm on your CI hosts as a first step towards getting this problem resolved, and letting us know if that doesn't work.

**Comment by myitcv** [comment]
Thanks for the response. This error was seen with `npm --version === 2.11.3` (this appears to be the default version shipping with NodeJS `0.12.7`)

I will try with later version

**Comment by myitcv** [comment]
This issue appears to remain in `2.13.2`
