### ISSUE TITLE
`npm install` fails with "cb() never called" when used with bundledDependencies

### ISSUE THREAD

**Issue by mik01aj** [npm/npm#9019]
In my module, when I do `npm install` and have anything specified in `bundledDependencies` (i.e. a non-empty list) in `package.json`, the install fails. That's the end of the log:

```
npm verb rebuild bundle /Users/mikolajdadela/code/lb-node-api/node_modules/tmp
npm info build /Users/mikolajdadela/code/lb-node-api/node_modules/tmp
npm info preinstall tmp@0.0.26
npm verb linkStuff [ false,
npm verb linkStuff   false,
npm verb linkStuff   false,
npm verb linkStuff   '/Users/mikolajdadela/code/lb-node-api/node_modules' ]
npm info linkStuff tmp@0.0.26
npm verb linkBins tmp@0.0.26
npm verb linkMans tmp@0.0.26
npm verb rebuildBundles tmp@0.0.26
npm verb rebuildBundles [ 'os-tmpdir' ]
npm info install tmp@0.0.26
npm info postinstall tmp@0.0.26
npm info install lb-node-api@0.0.2
npm info postinstall lb-node-api@0.0.2
npm info prepublish lb-node-api@0.0.2
npm ERR! cb() never called!
```

`lb-node-api` is my module I'm developing. It doesn't have a `prepublish` script, so this message is kinda weird.

The interesting thing is, that when I remove `bundledDependencies`, everything works normally.

**Comment by KenanY** [comment]
@mik01aj `npm --version`? End of the entire log is usually not sufficient to diagnose an issue.

**Comment by mik01aj** [comment]
I use npm `2.7.5`, node `v0.10.33`.

I did some more checking and found out that this happens only when I have a git dependency, which is also linked using `npm link`. It doesn't matter which packages does the `bundledDependencies` list contain.

After some more checking, I see that this is also not enough. What I see for sure is that this happens when I'm using `npm link` on some of the dependencies.

You can see the full `silly` log here: https://gist.github.com/mik01aj/2c5a320e4b6857585b30

**Comment by KenanY** [comment]
@mik01aj Could you [try the latest stable release of `npm`](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm)?

**Comment by mik01aj** [comment]
I just upgraded and the problem is gone! :+1:
