### ISSUE TITLE
always reinstalls commitish git devDependencies

### ISSUE THREAD

**Issue by zowers** [npm/npm#9020]
having
npm 2.11.3

```
devDependencies: {
    "grunt-contrib-copy": "git://github.com/gruntjs/grunt-contrib-copy.git#6b7d1f475151c81c3c1e0e0bbe0f53fadea5937c",
}
```
- `npm install` **always** re-downloads and re-installs the grunt-contrib-copy (BUG 1)
- leaves '/tmp/npm-nnn-mmm' directory with git cache inside (BUG 2) which eventually overflows the /tmp disk

if I move it to

```
dependencies: {
    "grunt-contrib-copy": "git://github.com/gruntjs/grunt-contrib-copy.git#6b7d1f475151c81c3c1e0e0bbe0f53fadea5937c",
}
```

`npm install` installs it only once as it should

**Comment by thynson** [comment]
Same with npm 2.14.6
