### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by torontom** [npm/npm#9023]
npm-debug.log is as following, can anyone take a look please.

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'gulp',
1 verbose cli   '-g' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose install initial load of C:\Users\pc123\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\pc123\AppData\Roaming\npm\package.json
6 silly cache add args [ 'gulp', null ]
7 verbose cache add spec gulp
8 silly cache add parsed spec { raw: 'gulp',
8 silly cache add   scope: null,
8 silly cache add   name: 'gulp',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed gulp@*
10 verbose addNamed "*" is a valid semver range for gulp
11 silly addNameRange { name: 'gulp', range: '*', hasData: false }
12 silly mapToRegistry name gulp
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/gulp
16 verbose addNameRange registry:https://registry.npmjs.org/gulp not in flight; fetching
17 verbose request uri https://registry.npmjs.org/gulp
18 verbose request no auth needed
19 info attempt registry request try #1 at 3:40:42 PM
20 verbose request id ec1a7b575277dbb1
21 http request GET https://registry.npmjs.org/gulp
22 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=connect ECONNREFUSED
23 info attempt registry request try #2 at 3:40:53 PM
24 http request GET https://registry.npmjs.org/gulp
25 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=connect ECONNREFUSED
26 info attempt registry request try #3 at 3:41:54 PM
27 http request GET https://registry.npmjs.org/gulp
28 verbose stack Error: tunneling socket could not be established, cause=connect ECONNREFUSED
28 verbose stack     at ClientRequest.onError (C:\Program Files\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:168:17)
28 verbose stack     at ClientRequest.g (events.js:199:16)
28 verbose stack     at ClientRequest.emit (events.js:107:17)
28 verbose stack     at Socket.socketErrorListener (_http_client.js:271:9)
28 verbose stack     at Socket.emit (events.js:107:17)
28 verbose stack     at net.js:459:14
28 verbose stack     at process._tickCallback (node.js:355:11)
29 verbose cwd C:\Program Files\nodejs
30 error Windows_NT 6.1.7601
31 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "gulp" "-g"
32 error node v0.12.7
33 error npm  v2.11.3
34 error code ECONNRESET
35 error network tunneling socket could not be established, cause=connect ECONNREFUSED
35 error network This is most likely not a problem with npm itself
35 error network and is related to network connectivity.
35 error network In most cases you are behind a proxy or have bad network settings.
35 error network
35 error network If you are behind a proxy, please make sure that the
35 error network 'proxy' config is set properly.  See: 'npm help config'
36 verbose exit [ 1, true ]

**Comment by sinkingshriek** [comment]
@torontom Are you by any chance behind proxy?

**Comment by torontom** [comment]
I was suspecting the proxy setting, so I take the laptop to home (no proxy), but still no luck. what I did is following:

C:\Program Files\nodejs>npm cache clean
C:\Program Files\nodejs>npm -g cache clean
C:\Program Files\nodejs>npm --registry http://registry.npmjs.org/ -g install bower
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "--registry" "http://registry.npmjs.org/" "-g" "install" "bower"
npm ERR! node v0.12.7
npm ERR! npm  v3.1.3
npm ERR! code ECONNREFUSED
npm ERR! errno ECONNREFUSED
npm ERR! syscall connect

npm ERR! Error: connect ECONNREFUSED
npm ERR!     at exports._errnoException (util.js:746:11)
npm ERR!     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
npm ERR!  { [Error: connect ECONNREFUSED]
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   syscall: 'connect' }
npm ERR!
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "--registry" "http://registry.npmjs.org/" "-g" "install" "bower"
npm ERR! node v0.12.7
npm ERR! npm  v3.1.3
npm ERR! path C:\Program Files\nodejs\npm-debug.log.2ad4fda7ca7c81d189dbac9c449e9ad3
npm ERR! code EPERM
npm ERR! errno -4048

npm ERR! Error: EPERM, open 'C:\Program Files\nodejs\npm-debug.log.2ad4fda7ca7c81d189dbac9c449e9ad3'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM, open 'C:\Program Files\nodejs\npm-debug.log.2ad4fda7ca7c81d189dbac9c449e9ad3']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   path: 'C:\\Program Files\\nodejs\\npm-debug.log.2ad4fda7ca7c81d189dbac9c449e9ad3' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files\nodejs\npm-debug.log

But I have a desktop at home that can install those packages without problem.

**Comment by sinkingshriek** [comment]
Okay let's go ahead and try in no proxy network first. 
Go ahead and unset any configs that you might have set already. 
`npm config rm proxy`
`npm config rm https-proxy`
Try downloading any package from npm. 
If the problem still persists then check if your Anti-Virus program is blocking the connection(if possible disable it altogether and try again).
People have had this same issue in the [past].(https://github.com/Medium/phantomjs/issues/19#issuecomment-13995639).

**Comment by torontom** [comment]
This is what I got:

C:\Program Files\nodejs>git config --global url."https://".insteadOf git://
C:\Program Files\nodejs>npm install express
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "express"
npm ERR! node v0.12.7
npm ERR! npm  v3.1.3
npm ERR! code ECONNRESET

npm ERR! network tunneling socket could not be established, cause=connect ECONNREFUSED
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "express"
npm ERR! node v0.12.7
npm ERR! npm  v3.1.3
npm ERR! path C:\Program Files\nodejs\npm-debug.log.6a053b96717a90960f85595d494b8a88
npm ERR! code EPERM
npm ERR! errno -4048

npm ERR! Error: EPERM, open 'C:\Program Files\nodejs\npm-debug.log.6a053b96717a90960f85595d494b8a88'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM, open 'C:\Program Files\nodejs\npm-debug.log.6a053b96717a90960f85595d494b8a88']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   path: 'C:\\Program Files\\nodejs\\npm-debug.log.6a053b96717a90960f85595d494b8a88' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files\nodejs\npm-debug.log

**Comment by sinkingshriek** [comment]
This is happening where you are behind proxy/firewall?

**Comment by torontom** [comment]
Actually that is not behind proxy... and it's the same result with firewall on or off.

**Comment by sinkingshriek** [comment]
Okay, let's try this one more time. I unfortunately don't have a windows machine to test this out right now but let's try this instead. 

`git config --global url."https://github.com/".insteadOf git@github.com:` which was discussed [here](https://github.com/npm/npm/issues/5257#issuecomment-60404802).  
instead of `git config --global url."https://".insteadOf git://` which I see that you did on your previous comment.

**Comment by torontom** [comment]
Tried but still does not work, I think it's something wrong with this laptop, installed too many things. I have a desktop in the same network simply works without doing anything... thanks anyway, I think I may try repair windows...
