### ISSUE TITLE
repl: create template file for main script

### ISSUE THREAD

**Issue by yorkie** [npm/npm#9028]
This is just a proposal about npm REPL program as title

**Comment by othiym23** [comment]
I need more detail here to figure out what you're requesting? What do you mean by "REPL program"? What's the "main script" you're talking about here? Thanks for any clarification you can provide!

**Comment by KenanY** [comment]
I could be wrong but maybe @yorkie wants `npm init` to also create an `index.js`?

**Comment by yorkie** [comment]
yes just want create the `main` script if it doesn't exist, but i'm not sure if it is real necessary now :(

**Comment by othiym23** [comment]
This would be convenient, but it doesn't really feel like it's within scope for npm. This does seem like it would be an excellent thing for a small, focused package to do – simpler than Yeoman, but enough to get people (particularly new Node developers) up and running. Thanks for your time!
