### ISSUE TITLE
Can't install private repo (using these specific steps)

### ISSUE THREAD

**Issue by remy** [npm/npm#9030]
I just signed up for private modules and couldn't install a newly published private module.

These are the steps I ran through - note that I changed my email address (which I had done *already* on npmjs.com and confirmed via email):

```shell
» npm login
Username: (remy) remy
Password: (or leave unchanged)
Email: (this IS public) (remy@remysharp.com) remy@leftlogic.com

» npm whoami
remy
```

In another terminal window I ran `npm pub` on the `@remy/snk` module which worked.

```shell
» npm install -S @remy/snk
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/Users/remy/.nvm/v0.10.38/bin/npm" "install" "-S" "@remy/snk"
npm ERR! node v0.10.38
npm ERR! npm  v2.13.1
npm ERR! code E404

npm ERR! 404 Not found : @remy/snk
npm ERR! 404
npm ERR! 404 '@remy/snk' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'snk-vuln'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/remy/Sites/snk-vuln/npm-debug.log
```

Then when I re-ran `npm login` and just hit enter through each prompt, it worked.

Also context of conversations: https://twitter.com/seldo/status/623886439135248384 (specifically, last time I signed in to the cli on this machine would have been pre-April 2015).

**Comment by smikes** [comment]
/cc @seldo 

If you have not yet been able to fix/work around the login problem, I would recommend trying this workaround --

```
$ npm logout
$ npm login
```

To get a new auth token.  However, that's not a permanent solution on the registry side, which might need to be created as a separate issue..

**Comment by ehsalazar** [comment]
@remy I believe between the Twitter and Zendesk communications, you're back in business. I'll close this for now as we’re trying to clean up some old issues. We’ll be happy to reopen if necessary.
