### ISSUE TITLE
Install dependency from a dir

### ISSUE THREAD

**Issue by kof** [npm/npm#9031]
Why  does npm i some_dir works, but same as dependency don't?

**Comment by kof** [comment]
I want to have a module requreable without path for e.g. require('conf') but I don't want to create a separate repository or package for it. Its just a folder within the current project I want to map to node_modules. Of course I could just symlink it to node_modules, but its way nicer to install it using npm because this way it can define its own dependencies and act like a real standalone package.

**Comment by KenanY** [comment]
@kof So all the directory needs is a `package.json`, if I am understanding you correctly.

**Comment by kof** [comment]
sure

**Comment by kof** [comment]
its basically nothing else than what already works using npm i some_dir

**Comment by KenanY** [comment]
@kof I think the [documentation on local paths](https://docs.npmjs.com/files/package.json#local-paths) might help?

**Comment by kof** [comment]
Oh, the issue was wrong npm version. Thanks!
