### ISSUE TITLE
Why is verison aliased to version?

### ISSUE THREAD

**Issue by aneeshvaidya** [npm/npm#9035]
I'm legitimately curious as to why this pull request was chosen to be incorporated when it seems kind of silly to do so. Any thoughts?

**Comment by othiym23** [comment]
It's easy and friendly to handle common typos like `npm verison` and `npm isntall`. If it's something that bites maintainers (or npm users) enough that somebody thinks it's worth the time to propose a PR, and provided it doesn't create a hazardous ambiguity, a patch for this kind of thing will generally get landed pretty quickly. Why not?

**Comment by aneeshvaidya** [comment]
I understand now, I just found it weird that when I typed npm, it listed verison and version as available commands, I thought it would just quietly work with verison

**Comment by iarna** [comment]
I think there's a good argument that we shouldn't list aliases in the synopsis, but I expect that will come up when we do the [ux overhall](https://github.com/npm/npm/wiki/Roadmap#usability-assessment-and-ux-overhaul)
