### ISSUE TITLE
Trying to create an advanced form scraper

### ISSUE THREAD

**Issue by ekiziltas** [npm/npm#9049]
Dear all,

I am trying to create a npm application for which the data is implemented automatically from my client directory, but I couldn't achieve that. I have decided to use form-scraper but couldn't find enough docs. Is there any idea to fill any given form which comes form a specific url?

Regards.

**Comment by sinkingshriek** [comment]
Hello @ekiziltas. Welcome to npm issue tracker. Unfortunately, your question relates more on implementation details rather than about npm itself. You might want to try other forums like [Stackoverflow](http://stackoverflow.com) for much broader discussions.

**Comment by snopeks** [comment]
Hello @ekiziltas! As @sinkingshriek mentioned, Stackoverflow is a great place for project discussions like this. If you run into any npm-related issues while creating your project, please open a new issue and we will be happy to help. Thanks!
