### ISSUE TITLE
Can't run npm ,there is an error got "error UNKNOWN, mkdir 'H:\'C:\Software\NPM''

### ISSUE THREAD

**Issue by pengpai01** [npm/npm#9052]
Hi,
It's my first time I used NPM ,but unfortunately, it seems hard for me ,I try to config the path ,but an error got ,like below:
```
 6 error Windows_NT 6.1.7601
7 error argv "C:\\Nodejs\\\\node.exe" "C:\\Nodejs\\node_modules\\npm\\bin\\npm-cli.js" "mkdir" "'c:\\software'"
8 error node v0.12.7
9 error npm  v2.11.3
10 error path H:\'C:\Software\NPM'
11 error code UNKNOWN
12 error errno -4094
13 error UNKNOWN, mkdir 'H:\'C:\Software\NPM''
14 error If you need help, you may report this error at:
```
Could you help me to fix it ? I had reinstall many times .

**Comment by KenanY** [comment]
@pengpai01 It looks to me like you are trying to run some kind of `npm mkdir` command, which does not actually exist. What are you expecting to happen? If you'd like to create a new folder, you should simply use `mkdir`.

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.

**Comment by pengpai01** [comment]
@KenanY  thank you very much!
