### ISSUE TITLE
Old README version

### ISSUE THREAD

**Issue by celsomarques** [npm/npm#9055]
Hi folks,

I publish a package yesterday but when I open the link after a search it shows the old README.
How can I fix that?

And today I included the repository url in package.json, how can I update this info here?

The package is: datepicker-for-ionic.

Thank you in advance.

**Comment by KenanY** [comment]
@celsomarques Issues with the website should be opened over at [newww](https://github.com/npm/newww) :)

**Comment by celsomarques** [comment]
Ooops....sorry dude :)
