### ISSUE TITLE
coDependencies: a new type of dependency field

### ISSUE THREAD

**Issue by bucaran** [npm/npm#9057]
I am having a bit of an issue over at [Fly](https://github.com/flyjs/fly) => flyjs/fly/issues/61

#### Actors

+ Host (`fly`, `gulp`, `broccoli`, etc)
+ Plugins (`fly-*`, etc.)
+ Guests (plugin dependencies)

#### Problem

+ Plugins always pull in the guest dependency (mocha, tape, eslint, jade, ...) while the end user only lists the plugin (`fly-mocha`, `fly-tape`, `fly-eslint`, ...) as a dependency. Users are forced to use the version the plugin author has decided to support.

+ Adding support to multiple versions of the guest dependency is the plugin responsibility.

#### Example

_Mr. Node_'s organization has decided to try out Fly to compile their asset pipeline, but for whatever reason they are stuck using `mocha` `v2.0.0` in their project. Since `fly-mocha` always ships with the latest and hottest (`v2.2.5` at the time of this writing), _Mr. Node_ is stuck.

#### A possible solution...

`package.json` could list yet another type of dependency:

+ `coDependencies` :white_check_mark: 
+ ~~`guestDependencies`~~
+ ~~`clientDependencies`~~

This field would list all the dependencies and versions the _plugin_ supports as well as the default version (extreme example follows):

```json
  },
  "coDependencies": {
    "mocha": { 
      "versions": ["1.0.0", "^1.5.0", "2.0.0", "2.2.5"],
      "default": "2.2.5"
    },
  },
```

Just like`devDependencies`, `coDependencies` are available only during development (they do not ship with the plugin when it becomes a package). The version~install strategy could make your `node_modules` look like this (other strategies are conceivable):

+ `node_modules/1.0.0/mocha`  
+ `node_modules/1.5.0/mocha`
+ `node_modules/2.0.0/mocha`

The default version would be symlinked to `node_modules/mocha`. `npm link` could be used to switch versions or a new `npm switch` or `npm use` action could be added to make this more obvious:

```
npm use mocha 1.5.0
```

##### Plugin Side

During development, authors would switch between versions to test the plugin in all its incarnations. 

Plugins will need to be aware of the multiple version support and accommodate for version specific code / behavior. 

Most plugins will support the latest version of their guest library, and that will be fine. But plugins with very special version requirements (due to their guest library dysfunctional version history) would have a way to accommodate all users.

##### Host Side

As usual, `npm i -D fly-mocha` would pull `fly-mocha` into my `node_modules` and add it to my `devDependency` field:

```json
  },
  "devDependencies": {
    "fly-mocha": "0.1.0",
  },
```

But `npm` which is aware of `fly-mocha`'s `coDependencies` field, would also install each of the supported dependencies and add the following to the user `package.json` (same as `fly-mocha`'s `coDependencies` above):

```json
  "coDependencies": {
    "mocha": { 
      "versions": ["1.0.0", "^1.5.0", "2.0.0", "2.2.5"],
      "default": "2.2.5"
    },
```

The version~install strategy would be the same as above, a directory for each version and the default version `2.2.5/mocha` would be symlinked to `node_modules/mocha`. Finally, _Mr. Node_, can use mocha `2.0.0`:

```
npm use mocha 2.0.0
```

This would update the default field above in his `package.json` and change the symlink inside `node_modules/mocha`.

#### Vaguely Related?

+ #930
+ #1400

**Comment by iarna** [comment]
Hey, you may or may not know that we've changed how `peerDependencies` work with `npm@3` (see the first of the breaking changes here: https://github.com/npm/npm/releases/tag/v3.0.0). Our change does a lot less, but it may solve the core of your issue?

**Comment by bucaran** [comment]
@iarna Thanks. We are reviewing how we can use `peerDependencies` to solve our core issue. I'll refer to this again with a report of how we handled this later :hap

**Comment by othiym23** [comment]
Given the changes to `peerDependencies` in `npm@3`, I don't think this feature makes as much sense, and it also brings a considerable degree of complexity with it, so I don't think we're going to implement this. Thanks for putting this proposal together!
