### ISSUE TITLE
npm install error 'npm ERR! code ETIMEDOUT'

### ISSUE THREAD

**Issue by Varun006** [npm/npm#9058]
I have been trying to install GULP using command  'npm install'  from nodejs command prompt using as administrator , with firewall turned off and using xampp( if it matters) but have always got this error.

![npm_error](https://cloud.githubusercontent.com/assets/9958681/8888485/e4bebfa2-32cc-11e5-9604-c18a5dbc5bcf.png)

I am pretty sure that i am not using any proxy, this is home pc.

I have also asked this question <a href="http://stackoverflow.com/questions/31560262/npm-install-etimed-out-laravel" target="_blank">here</a> at stackoverflow.com, and also at laracasts.com but with no luck..

I have tried the following things.

1) npm cahce clean

2) composer update

3) Running npm install gulp , npm install laravel-elixir individually one after another. This runs perfectly and does not gives any error. But only 'npm install'  gives.

4) Re-install node

5) Connecting my personal hotspot instead of WiFi, in case there would have been some network related issue.

6) Tried almost every suggestion on stackoverflow and google.

But none of the them worked.

Can you please let me know what needs to be done to get it working properly??

**Comment by smikes** [comment]
When you specify `npm install` like that, you are asking `npm` to install the packages named in `package.json`.  Can you please attach the contents of your `package.json` as a gist <https://gist.github.com> ?

To test whether `npm` can install things in general, please you run the following command:

```
> npm -d install -g rimraf
```

and if that fails, it should produce an `npm-debug.log` file.  Please upload that as a gist and post the link to it in this issue.

**Comment by Varun006** [comment]
Hi smikes,

Thanks for the reply,I have managed to get rid of the error. It had to do something with package.json file. After a fresh installation of laravel 5 the content of package.json were as below. 

{
  "private": true,
  "devDependencies": 
     {
       "gulp": "^3.8.8"
     },
  "dependencies": 
  {
    "laravel-elixir": "^2.0.0",
    "bootstrap-sass": "^3.0.0"
  }
}

I changed the content to below and it worked.

{
  "devDependencies": 
 {
    "gulp": "^3.8.8",
    "bootstrap-sass": "^3.0.0",
    "laravel-elixir": "^2.0.0"
  }
}

**Comment by smikes** [comment]
I'm glad you found a solution or workaround.  Can this issue now be closed?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
