### ISSUE TITLE
make npm.load re-evaluate the cwd each time it is called

### ISSUE THREAD

**Issue by trusktr** [npm/npm#9059]
I'd like to change the cwd of npm after it's been loaded. For example, I've got something like this, where I run `npm.load` and `npm.command.install` twice, `Meteor.wrapAsync` just causes the execution to be "synchronous":

```js
            fs.existsSync(path.resolve(DIR_ONE, 'node_modules')) // false
            fs.existsSync(path.resolve(DIR_TWO, 'node_modules')) // false

                process.chdir(DIR_ONE)
                Meteor.wrapAsync((callback) =>
                    npm.load({}, () => callback(null, 'blah'))
                )()
                Meteor.wrapAsync((callback) => {
                    npm.commands.install([], () => callback(null, 'blah'))
                })()

            fs.existsSync(path.resolve(DIR_ONE, 'node_modules')) // true
            fs.existsSync(path.resolve(DIR_TWO, 'node_modules')) // false
            shell.exec('rm -rf '+path.resolve(DIR_ONE, 'node_modules')) // start over
            fs.existsSync(path.resolve(DIR_ONE, 'node_modules')) // false
            fs.existsSync(path.resolve(DIR_TWO, 'node_modules')) // false

                process.chdir(DIR_TWO)
                Meteor.wrapAsync((callback) =>
                    npm.load({}, () => callback(null, 'blah'))
                )()
                Meteor.wrapAsync((callback) => {
                    npm.commands.install([], () => callback(null, 'blah'))
                })()

            fs.existsSync(path.resolve(DIR_ONE, 'node_modules')) // true again
            fs.existsSync(path.resolve(DIR_TWO, 'node_modules')) // still false
```

The second time, npm doesn't install inside of DIR_TWO as expected. How can we change npm's cwd?

**Comment by trusktr** [comment]
I see that Meteor wraps the CLI tool and uses child_process to manipulate it. Maybe that's what I'll have to do. It would be cool to easily change npm dir programmatically though.

**Comment by trusktr** [comment]
Aha, found the solution that (as far as my case goes) works:

```js
            Meteor.wrapAsync((callback) => {
                npm.load({ prefix: DIR_ONE }, callback)
            })()
            Meteor.wrapAsync((callback) => {
                npm.commands.install(DIR_ONE, [], callback)
            })()

...

            Meteor.wrapAsync((callback) => {
                npm.load({ prefix: DIR_TWO }, callback)
            })()
            Meteor.wrapAsync((callback) => {
                npm.commands.install(DIR_TWO, [], callback)
            })()
```

Now, I don't know if the `prefix` value is changing between these two npm installs, but luckily both prefixes contain the same package.json, so even if the second location get installed based on the first prefix, it works out.

**Comment by trusktr** [comment]
Actually, re-opening, as I think that the second call to `npm.load` should re-evaluate the cwd.

**Comment by othiym23** [comment]
The current programmatic API for npm is unsupported for use outside itself, and there are no guarantees that it will remain stable or has any particular fitness for purpose. If you want to invoke multiple npm commands from another program, the best thing to do is to call npm as a child process twice. At some point, we'll have a better interface for using the installer programmatically, but we're not there yet. As such, I'm closing this.
