### ISSUE TITLE
Git Bash Path problem

### ISSUE THREAD

**Issue by Faleij** [npm/npm#9061]
Calling any NPM command from Git Bash on Windows 10 spawns a CMD process with corrupted paths and NPM fails to find node and other path dependencies. I honestly don't know if this is just a local issue or if this might be a Git Bash issue but NPM can bypass it by correcting Path before execution.

from Git Bash:
```
Welcome to Git (version 1.9.5-preview20150319)
...
$ npm -v
2.11.3
$ cmd
Microsoft Windows [Version 10.0.10240]
(c) 2015 Microsoft Corporation. All rights reserved.
> echo %PATH%
/c/Users/falei/bin:.:/usr/local/bin:/mingw/bin:/bin:/c/Program Files/nodejs/:/c/Users/falei/AppData/Roaming/npm...
> exit
$ npm start
... 'node' is not recognized as an internal or external command...
$ node -v
v0.12.7
```
npm start = ``node app.js``

One thing that fixes this would be to modify the Path before launching the CMD process.
```
### lib\utils\lifecycle.js @ 201:
if (process.platform === "win32") {
    env.PATH = env.PATH.replace(/(^|:)\/(.)\//g,';$2:\\').replace(/\//g, '\\');
```

**Comment by smikes** [comment]
Could you please upload the npm-debug.log from your `npm start` command as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

Can you verify the problem in the latest version of `npm`, which is 2.13.3?

To update npm on Windows, you can use this command-line tool from Microsoft: https://github.com/felixrieseberg/npm-windows-upgrade
or follow the manual instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

I don't have Windows 10 here - do you believe this is specific to the Windows version, or do you expect it would fail this way in general?

Thanks!

**Comment by Faleij** [comment]
npm-debug.log:
http://pastebin.com/9fvsreFG npm-2.11.3
http://pastebin.com/iEJ2j7CX npm-2.13.3

I do believe this might be specific to Windows 10 but I have not tried it on another Windows 10 installation so I can't be sure, I have not had this issue prior to Windows 10 and it worked flawlessly on Windows 10 until recently.

**Comment by smikes** [comment]
Thanks.  I see the failure on 2.13.3 that you posted, above.

How should we fix this in `npm`?  It looks like `npm` is just using the PATH variable unmodified.  If we adopted your suggested fix above, wouldn't that break `npm` under git bash?

**Comment by Faleij** [comment]
I just installed Win10 in a virtual machine along with git bash, node and npm, and can't reproduce my problems so I guess my real win10 installation has some problems.

>wouldn't that break npm under git bash?
No, npm spawns a cmd process from git bash - at least it did for me. But nothing should be fixed as it's a local problem with my installation.
