### ISSUE TITLE
Can't Install/Update cordova

### ISSUE THREAD

**Issue by deavisdude** [npm/npm#9065]
This is the error log:

http://1drv.ms/1Ivxqjd

**Comment by KenanY** [comment]
@deavisdude Could you first try running `npm cache clean`? If that does not solve the issue, could you then try [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) to the latest stable release of `npm`?

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.
