### ISSUE TITLE
Can't install anything

### ISSUE THREAD

**Issue by gabri3l3onardo** [npm/npm#9067]
```
C:\....>npm install -g ember-cli
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "node" "C:\\......\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ember-cli"
npm ERR! node v0.12.7
npm ERR! npm  v2.13.3
npm ERR! code EADDRINUSE
npm ERR! errno EADDRINUSE
npm ERR! syscall connect

npm ERR! connect EADDRINUSE
```

**Comment by smikes** [comment]
Could you please upload your full npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

Thanks!

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.

**Comment by MasterFrese** [comment]
different user same problem... here you go.
I realy hope you guys can help me with this.
i already read countless forum entries / issues / ... 

[npm-debug.txt](https://github.com/npm/npm/files/111064/npm-debug.txt)
