### ISSUE TITLE
Ability to install package's dependencies (or devDependencies) to local node_modules?

### ISSUE THREAD

**Issue by spoco2** [npm/npm#9070]
**Short version:**
We'd love to be able to do something like *npm install [foldername] -localDev* within a main 'build area' folder and have it install any devDependencies within the package.json in the 'foldername' folder into our main build area's node_modules folder... without including the package name as a parent dir (so then doubling/tripling up on them being installed). 

This is so we can run the gulpfile within that folder from some main build area and have it run because we have all required node modules installed.

**Our use case:**
We have a HTML client that has many 'programs', each of which can be built and release managed individually. These are built for production using a common, main gulpfile that sits above them all, in a project root folder that also has our package.json (and bower.json etc.).

This package.json has the required modules needed for our gulpfile to run, structure like:

```js

MAIN BUILD FOLDER
|--node_modules/
|--Some Java program/
|--Some other Java program/
|--Main HTML client folder/ (checked out from hg)
   |--package.json
   |--gulpfile.js
   |--client program 1/
   |--client program 2/
```
The build system wants to be able to checkout a version of the code from our Mercurial repo, and call the gulpfile from outside that directory, passing arguments of which particular program to build, and where to output it.

This works fine.

Except this build system sits up above the main project, and we'd love for it to be able to, as part of the process say: 

"Before I run the gulpfile, install to my node_modules any devDependencies I'm going to need to build this that are listed within the package.json"

Because if we don't, then any newly added dependencies to the build gulpfile build process will die.

Currently, the only options I can see are:

* Run *npm install* within the "main HTML client folder". This will create the node_modules folder within it, meaning that the gulpfile can run. This means though that what's in this folder is no longer what's checkout out from the repo, but that plus downloaded node_modules... which is time consuming to do every build
* Run *npm install [foldername]* within the "MAIN BUILD FOLDER". This has the undesired result of installing everything under the name of the HTML client within the local node_modules folder, including all the client code, and all dependencies regardless of whether those dependencies already exist at the top level of our node_modules folder
* Run *npm install [foldername] -g* within the main folder... this is like the last version, except we're dirtying the main build system's node_module global space now.

Am I missing something obvious here?

**Comment by othiym23** [comment]
This sounds like a good use for `npm -C <path> i` / `npm --prefix=<path> install`, which says "run install with the package root set to `<path>`. Does that work for you?

**Comment by spoco2** [comment]
Thanks for this reply. Sorry I didn't notice the notification. I'm not in a position to actually test this at the moment, but will look into it in the future. Thank you.

**Comment by othiym23** [comment]
I'm going to close this issue as resolved, then. If you run into issues using `npm -C`, please open a new issue, and the team will see if we can get you sorted out.
