### ISSUE TITLE
windows 7 npm install always loading

### ISSUE THREAD

**Issue by anhuisunfei** [npm/npm#9072]
windows 7 npm install always loading

**Comment by othiym23** [comment]
Can you describe what issue you're seeing here in a little more detail? There's not enough info here for us to be able to help you right now.

**Comment by anhuisunfei** [comment]
For example, I installed Express  I have been waiting for this


E:\>npm install -g express
npm info it worked if it ends with ok
npm info using npm@2.11.3
npm info using node@v0.12.7
npm info attempt registry request try #1 at 13:41:50
npm http request GET https://registry.npm.taobao.org/e
npm http 200 https://registry.npm.taobao.org/express

**Comment by othiym23** [comment]
It seems like there may be a connectivity issue between your computer and `registry.npm.taobao.org`. What happens if you try to load https://registry.npm.taobao.org/express` in a web browser on the computer that's hanging?

**Comment by anhuisunfei** [comment]
response like this json data

{"_id":"express","_rev":"979945","name":"express","description":"Fast, unopinionated, minimalist web framework","dist-tags":{"latest":"4.13.1","rc":"4.0.0-rc4"},"maintainers":[{"name":"aredridel","email":"aredridel@nbtsc.org"},{"name":"defunctzombie","email":"shtylman@gmail.com"},{"name":"dougwilson","email":"doug@somethingdoug.com"},{"name":"jongleberry","email":"jonathanrichardong@gmail.com"},{"name":"rfeng","email":"enjoyjava@gmail.com"},{"name":"strongloop","email":"callback@strongloop.com"},{"name":"tjholowaychuk","email":"tj@vision-media.ca"}],"time":{"modified":"2015-07-07T05:55:54.000Z","created":"2010-12-29T19:38:25.450Z","5.0.0-alpha.2":"2015-07-07T05:46:20.081Z","4.13.1":"2015-07-06T05:42:59.627Z","3.21.1":"2015-07-06T04:55:30.351Z","4.13.0":"2015-06-21T06:50:18.321Z","3.21.0":"2015-06-19T01:42:28.037Z","4.12.4":"2015-05-18T04:41:14.788Z","3.20.3":"2015-05-18T04:06:45.934Z","4.12.3":"2015-03-17T22:04:53.210Z","3.20.2":"2015-03-17T05:06:28.342Z","4.12.2":"2015-03-03T05:46:29.969Z","4.12.1":"2015-03-02T01:13:30.608Z","3.20.1":"2015-03-01T04:23:20.434Z","4.12.0":"2015-02-23T06:58:39.027Z","3.20.0":"2015-02-19T02:53:28.667Z","4.11.2":"2015-02-01T20:45:09.837Z","3.19.2":"2015-02-01T20:24:05.444Z","4.11.1":"2015-01-21T08:34:52.857Z","3.19.1":"2015-01-21T08:23:41.579Z","4.11.0":"2015-01-14T04:21:56.291Z","4.10.8":"2015-01-13T17:48:23.443Z","3.19.0":"2015-01-09T06:36:21.099Z","4.10.7":"2015-01-05T00:40:37.634Z","4.10.6":"2014-12-13T04:17:13.785Z","3.18.6":"2014-12-13T02:45:59.136Z","3.18.5":"2014-12-12T04:24:32.541Z","4.10.5":"2014-12-11T05:08:02.089Z","4.10.4":"2014-11-25T05:19:30.905Z","4.10.3":"2014-11-24T03:12:32.210Z","3.18.4":"2014-11-23T20:52:49.813Z","4.10.2":"2014-11-10T00:10:27.638Z","3.18.3":"2014-11-09T23:38:00.888Z","5.0.0-alpha.1":"2014-11-07T02:54:34.556Z","4.10.1":"2014-10-29T05:21:08.596Z","3.18.2":"2014-10-29T05:14:04.974Z","4.10.0":"2014-10-24T02:36:30.641Z","3.18.1":"2014-10-23T05:30:25.689Z","3.18.0":"2014-10-18T05:10:21.951Z","4.9.8":"2014-10-18T02:05:05.528Z","3.17.8":"2014-10-16T04:36:53.277Z","4.9.7":"2014-10-10T20:43:34.045Z","4.9.6":"2014-10-09T02:35:55.395Z","3.17.7":"2014-10-08T21:22:35.229Z","3.17.6":"2014-10-03T04:05:10.920Z","4.9.5":"2014-09-

**Comment by othiym23** [comment]
Do you have a proxy configured for that web browser? You'll need to [configure a proxy](https://docs.npmjs.com/misc/config#https-proxy) for use with npm as well, probably by setting an environment variable for your system (and then closing and opening a new command shell so the changes get picked up).

**Comment by anhuisunfei** [comment]
Then how can I solve

**Comment by othiym23** [comment]
Either run `npm config set https-proxy proxy.company.cn` or set HTTPS_PROXY in your computer's environment, as I suggested in my previous comment.

**Comment by anhuisunfei** [comment]
I did not set up a proxy   
 I changed it to https://registry.npmjs.org/ can not be installed
npm http 304 https://registry.npmjs.org/express

**Comment by othiym23** [comment]
`304` indicates that it already has `express` in the npm cache, and so it's installing from the cached version. What does `npm install express -ddd` print out? (You might want to upload that to gist.github.com, as it can be very verbose.)

**Comment by anhuisunfei** [comment]
Well I reinstalled

**Comment by snopeks** [comment]
Hello @anhuisunfei, did the reinstall and/or proxy configuration solve your issue? Since we haven't heard back from you, I'm going to go ahead and close this issue. If you still need help, let me know, and I'll happily reopen it.
