### ISSUE TITLE
npm doesn't automatically update local deps when they're edited

### ISSUE THREAD

**Issue by trusktr** [npm/npm#9073]
I have a case where I've added a new dependency to a project, and npm won't install it when I `npm install`. If I remove node_modules, then try again, it works and I'll see the dependency sitting inside node_modules as expected.

This is happening with NPM v3.2.0. I'll see if I can post a way to replicate the problem..

**Comment by trusktr** [comment]
@othiym23 I made a repo where the bug can be reproduced: https://g.trusktr.io/trusktr/npm-bug-9073.git

Just clone it, go inside, then `npm install` with npm@3.2.0. The expected result is that after `npm install` there should be a folder `node_modules/jss-nested` but there isn't. This dependency is listed in a local dependency, one that is specified with the `file:path` syntax inside of the root `package.json` file:

```js
{
    "dependencies": {
        "rocket_module": "file:./packages/rocket_module",
        "rocket_module__app": "file:./packages/rocket_module__app", // <== this one.
        "trusktr_lib2": "file:./packages/trusktr_lib2",
        "trusktr_scratchpaper": "file:./packages/trusktr_scratchpaper"
    }
}
```

That package is located in `packages/rocket_module__app` and contains a `package.json` with the `jss-nested` dependency:

```js
{
    "dependencies": {
        "famous": "^0.6.0",
        "jss": "^2.0.0",
        "jss-nested": "^0.1.8" // <== right here.
    },
    "name": "rocket_module__app",
    "version": "0.0.0"
}
```

Now, if you `rm -rf node_modules` then try `npm install` again, you'll find that the `jss-nested` dependency gets installed properly.

I'm loving npm 3. The loading animation and the flat dependency structure: aaaaah, to die for.

**Comment by iarna** [comment]
So on the first install `rocket_module__app` ends up installed with THIS in it's package.json:

```
  "dependencies": {
    "famous": "^0.6.0",
    "jss": "^2.0.0"
  },
```

**Comment by iarna** [comment]
The original source file is:
```
{
                    "name": "rocket_module__app",
                    "version": "0.0.0",
                    "dependencies": {"famous":"^0.6.0","jss":"^2.0.0","jss-nested":"^0.1.8"}
                }
```

**Comment by iarna** [comment]
As best as I can tell what you're seeing is the fact that npm doesn't update local deps when you edit them directly. It currently has no facility for detecting changes.

Now, if you edited the version of `rocket_module__app` from `0.0.0` to say `0.0.1`... it still wouldn't work, BUT, `npm outdated` does see it as outdated:
```
Package             Current  Wanted  Latest  Location
rocket_module__app    0.0.0   0.0.1   0.0.1  npm-bug-9073
```
This would imply that `npm update` should work. And I bet it would for you.

For me, it exposes another bug where it uses the pre-resolved spec from the already installed version's `_requested` property, instead of using the spec from the `package.json`

**Comment by iarna** [comment]
I'm tagging this `post-npm3-stable` not because it's not important, but because the current behavior is no worse than `npm@2` and I don't want to have any more blockers than we absolutely have to.

**Comment by trusktr** [comment]
That's what I was guessing, that npm wasn't detecting the changes to the local packages. Quick question: does `npm update` behave (essentially) the same as `npm install` when nothing has been installed yet?

**Comment by trusktr** [comment]
I guess they aren't the same. `npm update` on a fresh repo:

```
npm ERR! Cannot read property 'version' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "update"
npm ERR! node v0.12.2
npm ERR! npm  v3.2.0
```

**Comment by trusktr** [comment]
@iarna When I clone the sample repo, then run `npm outdated`, I see no output.

**Comment by timoxley** [comment]
> npm doesn't automatically update local deps when they're edited

@trusktr [linklocal](https://github.com/timoxley/linklocal) was created to solve this exact issue

**Comment by iarna** [comment]
This is a feature we too would like to see. It seems to me that updating local (and other non-semver deps) on install makes sense. Unfortunately, the npm cli team isn’t going to have time to get to this in the foreseeable future, and so I’m going to close this issue. If you (or someone reading) would like to take a stab at this, we would be very interested in a PR-- early PRs are also welcome as I would be happy to help you find the best implementation path.

**Comment by ashleygwilliams** [comment]
This is a really neat challenge for several reasons:

- Firstly, this feature will necessarily be a performance hit. Mitigating that will be a super important aspect of any implementation.
- Given that local dependencies don't have versions, "knowing" when they have changed (and therefore when to update them) is a Hard problem which could be addressed several ways, the best of which we aren't sure about!

**Comment by nmuth** [comment]
@ashleygwilliams Is there a reason we need to know whether the dependency changed? It seems to me that it would be acceptable to always assume that there are changes and copy the dependency over every time the user runs `npm install`. Maybe I don't understand the performance risks very well.
