### ISSUE TITLE
Windows 8.1 pro npm update bug (3.2.0)

### ISSUE THREAD

**Issue by Sogl** [npm/npm#9081]
Hi!

I'm trying to update my npm (https://github.com/npm/npm/issues/5816). After update process I can't install any package:
```
Артем@SOGL c:\nodejs\node_modules\npm
$ npm -v
2.11.3

Артем@SOGL c:\nodejs\node_modules\npm
$ cd c:\nodejs\

Артем@SOGL c:\nodejs
$ npm install npm@3.2.0
npm@3.2.0 node_modules\npm

Артем@SOGL c:\nodejs
$ npm -v
3.2.0

Артем@SOGL c:\nodejs
$ npm install -g browser-sync
```
Nothing =(

Node v 0.12.7
Found way how to fix - repair node installation, but npm becomes 2.11.3 again.

**Comment by Sogl** [comment]
Fixed by deleting node with this instruction:
http://stackoverflow.com/questions/20711240/how-to-completely-remove-node-js-from-windows

After reinstall I use this:
https://github.com/npm/npm/wiki/Troubleshooting

But 'node-gyp rebuild' still not working...

**Comment by robertbaker** [comment]
@Sogl  Re install Node.js then install this. https://github.com/felixrieseberg/npm-windows-upgrade

Works for me just fine on Windows 8.1 Pro x64.

```
irst, ensure that you can execute scripts on your system by running the following command from an elevated command prompt (either PowerShell or CMD.exe). To run PowerShell as Administrator, click Start, search for PowerShell, right-click PowerShell and select Run as Administrator.

Set-ExecutionPolicy Unrestricted -Scope CurrentUser -Force
Then, to install and use this upgrader tool, run:

npm install -g npm-windows-upgrade
npm-windows-upgrade
```

**Comment by Sogl** [comment]
@robertbaker, Thanks, man! It works too!

**Comment by othiym23** [comment]
Closing as resolved!
