### ISSUE TITLE
mup deploy error  with nodejs 0.10.9 installed in server

### ISSUE THREAD

**Issue by ennea8** [npm/npm#9082]
45.55.23.52] - Uploading bundle
[45.55.23.52] - Uploading bundle: SUCCESS
[45.55.23.52] - Setting up Environment Variables
[45.55.23.52] - Setting up Environment Variables: SUCCESS
[45.55.23.52] - Invoking deployment process
[45.55.23.52] x Invoking deployment process: FAILED

	-----------------------------------STDERR-----------------------------------
	1.0.6","1.0.7","1.0.8","1.0.10","1.1.0","1.1.3","1.1.4","1.2.0","1.2.1","1.3.0","1.3.1"]
	npm ERR!     at installTargetsError (/opt/nodejs/lib/node_modules/npm/lib/cache.js:709:10)
	npm ERR!     at /opt/nodejs/lib/node_modules/npm/lib/cache.js:631:10
	npm ERR!     at saved (/opt/nodejs/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
	npm ERR!     at Object.oncomplete (fs.js:107:15)
	npm ERR! If you need help, you may report this log at:
	npm ERR!     <http://github.com/isaacs/npm/issues>
	npm ERR! or email it to:
	npm ERR!     <npm-@googlegroups.com>

	npm ERR! System Linux 3.13.0-52-generic
	npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
	npm ERR! cwd /opt/coffeewoo/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt
	npm ERR! node -v v0.10.9
	npm ERR! npm -v 1.2.24
	npm ERR!
	npm ERR! Additional logging details can be found in:
	npm ERR!     /opt/coffeewoo/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/npm-debug.log
	npm ERR! not ok code 0
	-----------------------------------STDOUT-----------------------------------
	 > ./bcrypt: npm install due to binary npm modules
	----------------------------------------------------------------------------

**Comment by othiym23** [comment]
Those versions of Node and npm are very old, and `npm@1.2` has been unsupported for even longer than `npm@1.3`, which we stopped supporting over a year ago. Is there a newer version of npm and / or Node available for your OS distribution? Or is there an upgrade to Meteor that bundles a newer npm?

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.
