### ISSUE TITLE
install specific version of the library using cli

### ISSUE THREAD

**Issue by debris** [npm/npm#9085]
According to the `-help`

```
npm install <pkg>@<tag>
npm install <pkg>@<version>
npm install <pkg>@<version range>
```

and [docs](https://docs.npmjs.com/cli/install)

```
npm install sax@0.1.1
```

it should be possible to install specific version of the library using cli. Although when I try to install library `node-inspector` the command is not working (it is not recognised).

```
# install by tag
npm intstall node-inspector@v0.11.2 -g
```

```
# by npm register name
npm intstall node-inspector@0.11.2 -g
```

npm version: 2.12.1
os: osx 10.10.3

**Comment by alrra** [comment]
> npm intstall 

@debris I should be "install" not "intstall", try:

```bash
npm install -g node-inspector@v0.11.2
```

**Comment by debris** [comment]
... thanks!
