### ISSUE TITLE
GULP install fail

### ISSUE THREAD

**Issue by 207704** [npm/npm#9088]
I was getting error while installing GULP. Please advice.

![image](https://cloud.githubusercontent.com/assets/13542130/8937040/922894ba-351b-11e5-9d4b-8247ce791f29.png)

**Comment by robertbaker** [comment]
+1 getting gulp with 3.2.0 cannot install gulp as it's a dependency of itself.

(I'm not getting the cert untrusted error though)

**Comment by sinkingshriek** [comment]
@207704 You have got a very old version of `npm`. Can you try again with the upgraded one?

**Comment by robertbaker** [comment]
@207704 I would install the latest node. You are running on old stuff.

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.
