### ISSUE TITLE
Error while installing mean stack generator on Windows.

### ISSUE THREAD

**Issue by billabrian6** [npm/npm#9090]
Can anyone help with this issue? It looks like a checksum error on node-inspector...

![image](https://cloud.githubusercontent.com/assets/3662566/8938363/d9722810-3523-11e5-9f28-e37b8b80b82a.png)

**Comment by billabrian6** [comment]
npm-debug file output (last part of it)

124479 info install karma@0.12.37
124480 info postinstall karma@0.12.37
124481 verbose unlock done using C:\Users\brian.green\AppData\Roaming\npm-cache\_locks\karma-7fe1959a207af13c.lock for C:\Users\brian.green\WebstormProjects\GuildKSK\node_modules\karma
124482 verbose stack Error: shasum check failed for C:\Users\BRIAN~1.GRE\AppData\Local\Temp\npm-3096-36c58be2\registry.npmjs.org\node-inspector\-\node-inspector-0.9.2.tgz
124482 verbose stack Expected: f25e2be0dbd672f7f09b50af01ef81da3157ae7c
124482 verbose stack Actual:   b18a28494ddefaa3035f919ea60b00a61622bfe5
124482 verbose stack From:     https://registry.npmjs.org/node-inspector/-/node-inspector-0.9.2.tgz
124482 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:38:8
124482 verbose stack     at ReadStream.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:85:7)
124482 verbose stack     at ReadStream.emit (events.js:129:20)
124482 verbose stack     at _stream_readable.js:908:16
124482 verbose stack     at process._tickCallback (node.js:355:11)
124483 verbose cwd C:\Users\brian.green\WebstormProjects\GuildKSK
124484 error Windows_NT 6.3.9600
124485 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
124486 error node v0.12.4
124487 error npm  v2.10.1
124488 error shasum check failed for C:\Users\BRIAN~1.GRE\AppData\Local\Temp\npm-3096-36c58be2\registry.npmjs.org\node-inspector\-\node-inspector-0.9.2.tgz
124488 error Expected: f25e2be0dbd672f7f09b50af01ef81da3157ae7c
124488 error Actual:   b18a28494ddefaa3035f919ea60b00a61622bfe5
124488 error From:     https://registry.npmjs.org/node-inspector/-/node-inspector-0.9.2.tgz
124489 error If you need help, you may report this error at:
124489 error     <https://github.com/npm/npm/issues>
124490 verbose exit [ 1, true ]
124491 verbose unbuild node_modules\grunt-node-inspector
124492 info preuninstall grunt-node-inspector@0.1.6
124493 info uninstall grunt-node-inspector@0.1.6
124494 verbose unbuild rmStuff grunt-node-inspector@0.1.6 from C:\Users\brian.green\WebstormProjects\GuildKSK\node_modules
124495 info postuninstall grunt-node-inspector@0.1.6
124496 silly gentlyRm C:\Users\brian.green\WebstormProjects\GuildKSK\node_modules\grunt-node-inspector is being purged from base C:\Users\brian.green\WebstormProjects\GuildKSK
124497 verbose gentlyRm don't care about contents; nuking C:\Users\brian.green\WebstormProjects\GuildKSK\node_modules\grunt-node-inspector
124498 silly vacuum-fs purging C:\Users\brian.green\WebstormProjects\GuildKSK\node_modules\grunt-node-inspector
124499 silly vacuum-fs quitting because other entries in C:\Users\brian.green\WebstormProjects\GuildKSK\node_modules

**Comment by othiym23** [comment]
This is the third or fourth issue we got with a shasum mismatch in it today, which in olden times (read: beginning of last year) meant that something bad was going on with the registry. If there _was_ something up with the registry today, it was very localized, because that's actually a pretty small number of issues filed for this kind of problem, and I can't reproduce any of these problems myself.

So! You might try running `npm cache clean` and then try running your install again. If everything works, then this was probably something transient, and if it's a problem, it's a problem for us and not for you (so letting us know if it fixed itself is helpful). If not, there's something deeper going on that we should look into.

**Comment by billabrian6** [comment]
It worked this morning. Thanks for helping.

**Comment by ehsalazar** [comment]
Good to hear. I'll close this for now as we’re trying to clean up some old issues. We’ll be happy to reopen if necessary.
