### ISSUE TITLE
npm

### ISSUE THREAD

**Issue by choisiwon31** [npm/npm#9096]
i have a problem when uninstal npm.. error:
```
C:\Windows\system32>npm uninstall npm -g
module.js:338
    throw err;
          ^
Error: Cannot find module 'C:\Program Files\nodejs\node_modules\npm\bin\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```
is there a missing folder ?? What should I do?

**Comment by othiym23** [comment]
It looks like npm is already mostly removed, except for `npm.cmd` itself. What are you trying to do?

**Comment by jcollum** [comment]
The title of this issue needs more... something. You should be more descriptive with your issue titles.

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.
