### ISSUE TITLE
npm version while in a subdirectory of the project increments the version but fails to commit to git

### ISSUE THREAD

**Issue by aredridel** [npm/npm#9099]
```
ariastewart@LM-BOS-00872654:cases (master:8dbeb8c)
:; npm version patch
v3.0.1
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "version" "patch"
npm ERR! node v0.12.7
npm ERR! npm  v3.1.3
npm ERR! code 128

npm ERR! Command failed: git add package.json
npm ERR! fatal: pathspec 'package.json' did not match any files
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ariastewart/Projects/json-ometajs/test/cases/npm-debug.log
ariastewart@LM-BOS-00872654:cases (master:8dbeb8c Δ )
```

**Comment by othiym23** [comment]
Good catch! Thanks! It would be nice to have this just work, but it also would be nice to document how npm works here, because there's some conflusion (and differences of opinion) about what should happen when `npm version` is run somewhere other than the root of a package and / or git repository.

It also might be a little while until the team has cycles to address this, so I stuck `patch-welcome` on this issue if somebody wants to take a whack at it.

**Comment by simonvanderveldt** [comment]
This does not work for me on 2.15.1 which does include this fix. Looking at the commit I don't really see how that change would solve this issue to be honest.
@aredridel did this actually work for you?

**Comment by dcolens** [comment]
npm: 3.9.5, it fails to commit when running from a subfolder (package.json is also in the subfolder)

**Comment by othiym23** [comment]
@simonvanderveldt, @dcolens: are you saying

1. `package.json` doesn't get incremented and checked in when `npm version` is run from a subdirectory, or
2. dirty files in the current directory don't get checked in when `npm version` is run from a subdirectory?

1 is the intent of this patch, but 2 is not.

**Comment by simonvanderveldt** [comment]
@othiym23 To be more precise this is what I'm doing and what happens:
- I `cd` in to a project with a clean working directory that resides in a subdir of the repository
- Then run `npm version minor` (but the same happens for other ones obviously)
- `package.json` gets updated with the new version
- `package.json` is not staged/added nor committed
- No tag is created

**Comment by drew-r** [comment]
Get anywhere with this @simonvanderveldt ?

**Comment by simonvanderveldt** [comment]
> Get anywhere with this @simonvanderveldt ?

AFAIK nothing has changed. We've just fixed it with some scripting. I don't use npm myself so can't check if it still doesn't work.

But judging by your question

**Comment by giltayar** [comment]
[Edited: Sorry - my bad. I believe it's still a bug, but it's not _this_ bug. This bug refers to running `npm version` in a subdir and not the fact that the package _itself_ is in a subdir. I'll still leave it here for historical reference].

This is not working for me (npm is modifying the files, but not committing them to git), and in some versions of git, the workaround of creating an empty `.git` folder also fails, as git assumes that this folder has a git repo inside it.

Node: v8.4.0
NPM: v5.3.0
Git: v2.13.5

```bash
~/builddir/a $ git reset --hard
HEAD is now at 03f04ce 1.0.11
~/builddir/a $ npm version patch
npm info it worked if it ends with ok
npm info using npm@5.3.0
npm info using node@v8.4.0
npm info lifecycle @bildit/test-repo-a@1.0.12~preversion: @bildit/test-repo-a@1.0.12
v1.0.12
npm info lifecycle @bildit/test-repo-a@1.0.12~version: @bildit/test-repo-a@1.0.12
npm info lifecycle @bildit/test-repo-a@1.0.12~postversion: @bildit/test-repo-a@1.0.12
npm info ok
~/builddir/a $ git status --porcelain
 M a/package-lock.json
 M a/package.json
```

And this with an empty `.git` directory. This time, git balks on this workaround:

```bash
~/builddir/a $ git reset --hard
HEAD is now at 03f04ce 1.0.11
~/builddir/a $ mkdir .git
~/builddir/a $ npm version patch
npm info it worked if it ends with ok
npm info using npm@5.3.0
npm info using node@v8.4.0
npm info git [ 'status', '--porcelain' ]
npm info lifecycle @bildit/test-repo-a@1.0.12~preversion: @bildit/test-repo-a@1.0.12
v1.0.12
npm info lifecycle @bildit/test-repo-a@1.0.12~version: @bildit/test-repo-a@1.0.12
npm info git [ 'add', '/home/node/builddir/a/package.json' ]
npm info git [ 'add', '/home/node/builddir/a/package-lock.json' ]
npm info git [ 'commit', '-m', '1.0.12' ]
npm ERR! code 128
npm ERR! Command failed: git commit -m 1.0.12
npm ERR!
npm ERR! *** Please tell me who you are.
npm ERR!
npm ERR! Run
npm ERR!
npm ERR!   git config --global user.email "you@example.com"
npm ERR!   git config --global user.name "Your Name"
npm ERR!
npm ERR! to set your account's default identity.
npm ERR! Omit --global to set the identity only in this repository.
npm ERR!
npm ERR! fatal: empty ident name (for <>) not allowed
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2017-08-26T09_17_06_272Z-debug.log
```
