### ISSUE TITLE
issue publishing

### ISSUE THREAD

**Issue by stefanpenner** [npm/npm#9102]
When attempting to publish `ember-cli@v1.13.5` the publish failed mid-flight with:

``` 
ember-cli git:(release) npm publish
npm ERR! registry error parsing json
npm ERR! publish Failed PUT 403
npm ERR! Darwin 14.4.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "publish"
npm ERR! node v2.2.1
npm ERR! npm  v2.11.0
npm ERR! code E403

npm ERR! "You cannot publish over the previously published version 1.13.5." : ember-cli
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/stefanpenner/src/ember-cli/npm-debug.log
```

I am confident there was no `1.13.5` prior to this, interestingly `npm info ember-cli | jq '.times'` reveals there is a 1.13.5 but based on the timestamps it is the 1.13.5 that particular `npm publish` was trying to publish:

```
npm info ember-cli | jq '.time'
>  ...
>  "0.2.6": "2015-05-30T21:19:43.896Z",
>  "0.2.7": "2015-06-02T16:55:07.094Z",
>  "1.13.0": "2015-07-08T18:31:07.377Z",
>  "1.13.1": "2015-07-08T23:05:17.237Z",
>  "1.13.5": "2015-07-29T17:40:06.527Z"  <<-- this is around the time i attempted the npm publish
```

**Comment by stefanpenner** [comment]
It appears the website displays: 1.13.1 but the registry believe 1.13.5 is the latest.

**Comment by othiym23** [comment]
Thanks for the report, Stefan. I'll have the registry team take a look at this.

**Comment by stefanpenner** [comment]
Thanks let me know if there is anything else i can provide.

**Comment by stefanpenner** [comment]
Is it recommended that I re-publish, or should I sit tight.

**Comment by stefanpenner** [comment]
todays release had a similar issue:

```
➜  ember-cli git:(master) npm publish ./ember-cli-1.13.6.tgz
npm ERR! registry error parsing json
npm ERR! publish Failed PUT 403
npm ERR! Darwin 14.4.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "publish" "./ember-cli-1.13.6.tgz"
npm ERR! node v2.2.1
npm ERR! npm  v2.11.0
npm ERR! code E403

npm ERR! "You cannot publish over the previously published version 1.13.6." : ember-cli
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/stefanpenner/src/ember-cli/npm-debug.log
```

note the following indicates some sort of json parsing issue. A quick check does not reveal anything obviously broken on my side, but I will investigate further.

```
npm ERR! registry error parsing json
```

**Comment by stefanpenner** [comment]
just a quick test to see if we have invalid package.json's.

All that i could find where some fixture data (yes we shouldn't ship those to npm) with invalid package.jsons. But I am doubtful that is causing the issue.


given:

```
for file in (find . -iname package.json)
  jsonlint -q $file
end
```

output:

```
[Error: Parse error on line 1:

^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'EOF']
./tests/fixtures/installation-checker/invalid-npm-installation/package.json
[Error: Parse error on line 1:

^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'EOF']
./tests/fixtures/installation-checker/valid-npm-installation/package.json
[Error: Parse error on line 1:

^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'EOF']
./tests/fixtures/missing-before-addon/lib/sample-addon/package.json
```

**Comment by othiym23** [comment]
> does the publish step recurse and parse child deps `package.json`?

I don't think the _contents_ of the package are the problem here. The only `package.json` that npm cares about is the root one that you publish – anything in `node_modules` in a bundled dependency has nothing to do with the publishing process.

The fact that you've hit this twice indicates that this is a more serious issue. I took a look at `ember-cli`'s `package.json` and didn't see anything suspicious, so while it's _possible_ that there's something that npm is doing wrong, I think this is probably a bad interaction between the CLI and the registry.

Could you try bumping and republishing, and either pass along the `npm-debug.log` or run with `-ddd` and cutting and pasting the debug output? There may be further clues in there that I can pass along to the registry team.

**Comment by stefanpenner** [comment]
> Could you try bumping and republishing, and either pass along the npm-debug.log or run with -ddd and cutting and pasting the debug output? There may be further clues in there that I can pass along to the registry team.

Gladly, I'll likely cut another release shortly (or later tonight) and do so with `-ddd` and share the logs.

@othiym23 just spit balling here but one unique characteristic is the share size of the ember-cli tarball. Maybe that is uncovering some race?

**Comment by othiym23** [comment]
So, two bits of insight from the registry team:

1. In both cases, the publishes actually succeeded the first time, and the reason it wasn't visible on the web site is simply because the web site's cache lags the registry a little bit.
2. You might have encountered a bug in the code that handles publishing a tarball, which is something that not a lot of people use. It's absolutely supported, but I'm not sure it has adequate test coverage. I'll take a look at the source and see what jumps out at me.

**Comment by stefanpenner** [comment]
> In both cases, the publishes actually succeeded the first time, and the reason it wasn't visible on the web site is simply because the web site's cache lags the registry a little bit.

:+1: 

> You might have encountered a bug in the code that handles publishing a tarball, which is something that not a lot of people use. It's absolutely supported, but I'm not sure it has adequate test coverage. I'll take a look at the source and see what jumps out at me.

Ya this is most likely related.

**Comment by bcoe** [comment]
@stefanpenner I would love to try to debug this problem this week, are you available on IRC to ask some questions?

1. I'd love to know what your publication flow looks like. do you run `npm pack`, `npm publish`, do you usually just run `npm publish` -- I'm mainly curious as to why you're publishing a tarball.
2. it would be great to get you to try a few publishes with some more debugging in place.

**Comment by stefanpenner** [comment]
I believe this issue has been dealt with, I will be doing another publish later this week. If something goes side-ways, I will reopen.

**Comment by stefanpenner** [comment]
Can confirm, my latest release went off without a hitch during npm publish
