### ISSUE TITLE
PopcornTV error Windows 8.1 

### ISSUE THREAD

**Issue by kevinmeland** [npm/npm#9106]
```
C:\Users\Kevin\Desktop\PopcornTV>node atv.js
notice: Starting PopcornTV
DNS: DnsProxy binding on 10.77.99.148:53
error: There is an error starting Popcorn TV, please post this on the Github pag
e
{ [Error: Cannot find module 'popcorn-streamer'] code: 'MODULE_NOT_FOUND' }
```

**Comment by robertbaker** [comment]
@kevinmeland I doubt this is an NPM issue. This is a popcorn-streamer issue. nothing to do with npm.

**Comment by snopeks** [comment]
Hi @kevinmeland ! Since this isn't an issue with npm, I recommend reaching out to the folks behind Popcorn TV, they will be much more able to assist you. If you encounter an error related to npm feel free to open another issue. Thanks!
