### ISSUE TITLE
'npm publish' a scoped module

### ISSUE THREAD

**Issue by cmwood** [npm/npm#9109]
I was able to successfully publish a scoped module. But after I made some changes to the module, including incrementing the package version, I was unable to publish the update (I was logged in as the appropriate permitted owner/username). The following exception was displayed :

```
npm ERR! Darwin 14.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "publish"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4

npm ERR! Invalid name: "@flightstats/edge-config"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/cwood/Workspaces/fs-node/edge-config/npm-debug.log 
```

**Comment by othiym23** [comment]
@cwood Can you upload that `npm-debug.log` to gist.github.com? There's not enough context from that error message to figure out why the publish worked the first time but failed the next. Thanks!

**Comment by cmwood** [comment]
Will this do? https://gist.github.com/cmwood/7b174ff6725d2b984f2d

**Comment by pselle** [comment]
I ran into a similar issue when running `npm install` on a freshly checked out repository that is a scoped package. Log: https://gist.github.com/pselle/d87051ceb0bf083d2f1d
