### ISSUE TITLE
Issue publishing with version 2.13.2

### ISSUE THREAD

**Issue by cjihrig** [npm/npm#9110]
Trying to publish on io.js 2.5.0, npm 2.13.2 on OS X. Received the following error:

```
npm ERR! publish Failed PUT 500
npm ERR! Darwin 12.5.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "publish"
npm ERR! node v2.5.0
npm ERR! npm  v2.13.2
npm ERR! code E500

npm ERR! unexpected status code: 404 : code
```

Someone else was able to publish the module, so I'm thinking it's either an issue with the version or my setup.

**Comment by othiym23** [comment]
Have you tried logging in to the registry recently? It's possible you don't have the right kind of access token in your `~/.npmrc`.

**Comment by cjihrig** [comment]
That fixed it. Could it have been related to upgrading? Or the fact that I'm also signed into a private npm registry? Either way, thanks, Forrest!
