### ISSUE TITLE
npm install error.  (tar.unpack untar error)

### ISSUE THREAD

**Issue by merlin-li** [npm/npm#9112]
```
npm ERR! tar.unpack untar error /tmp/npm-1092-d5217643/registry.npmjs.org/npm/-/npm-2.1.3.tgz
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/lib/node_modules/cnpm/node_modules/.bin/npm" "--userconfig=/Users/admin/.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--cache=/Users/admin/.cnpm" "--registry=https://registry.npm.taobao.org" "--node-gyp=/usr/local/lib/node_modules/cnpm/node_modules/pangyp/bin/node-gyp.js" "install" "-g" "ionic"
npm ERR! node v0.12.7
npm ERR! npm  v2.13.2

npm ERR! unexpected eof
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/admin/npm-debug.log
```

This issure still exists after I execute "npm cache clean".

**Comment by KenanY** [comment]
@merlin-li Does this also occur if you use the default registry?

**Comment by letsila** [comment]
I have got the same error. I have executed "npm install" with sudo and "sudo npm cache clean" but still got the tar.unpack untar error
npm version : 2.12.1
Mac OS version : 10.10.4

**Comment by letsila** [comment]
Updating node and npm to the latest version have solved it.

**Comment by dakoo** [comment]
When I bumped into the tar.unpack untar error on OSX, I used **sudo** and It worked. 
> sudo npm cache clean
> sudo npm install -g ...

**Comment by ehsalazar** [comment]
Good to hear. I'll close this for now as we’re trying to clean up some solved issues. We’ll be happy to reopen if necessary.

**Comment by Romasato** [comment]
One more thing: if you're on Virtualbox VM and have your project hosted on other partition (separate mounted *.vdi file), moving it to the main system partition has solved it for me :)
