### ISSUE TITLE
npm install issue on Windows 7

### ISSUE THREAD

**Issue by KrisVos130** [npm/npm#9115]
Every time I try to install something by either typing `npm install` or just `npm install mongodb` (or when I try to install anything else), it gives me the same error message. I installed npm a few days ago and it has done this from the start. Here is the [npm-debug.log](https://gist.github.com/KrisVos130/b77ab6f2c59981656b5f).

Things I have already tried:
* `npm cache clean`.
* Restarting my pc.
* Reinstalling Node.js and npm.
* Setting/changing proxy and https-proxy.
* Setting/changing registry.

And I'm sure I missed a few things in that list.

Help with this would be appreciated.

**Comment by othiym23** [comment]
It looks like you're behind a proxy. Do you need to configure [`https-proxy`](https://docs.npmjs.com/misc/config#https-proxy) and / or `HTTP_PROXY` / `HTTPS_PROXY`?

**Comment by KrisVos130** [comment]
I don't think I am behind a proxy. This happend from the start before I changed any settings. How would I check t see if I am behind a proxy? And if I am behind a proxy, what would I have to change then and to what?

**Comment by othiym23** [comment]
```html
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /npm. Reason:
<pre>    Not Found</pre></p><hr /><i><small>Powered by Jetty://</small></i><br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>

</body>
</html>
```

and

```javascript
{ 'x-content-type-options': 'nosniff',
  'content-type': 'text/html;charset=ISO-8859-1',
  'cache-control': 'must-revalidate,no-cache,no-store',
  'content-length': '1368',
  server: 'Jetty(winstone-2.8)' }
```
(the last line)

indicate pretty strongly that something in your network is intercepting requests to `registry.npmjs.org`, as that's proxy output that never comes from npm's servers or its CDN. You'll need to find out what the proxy settings are for your network (they might be in the Control Panel if you're running Windows, or maybe you'll have to ask your team's network administrator / your ISP), and then use the configuration settings I linked to above.

**Comment by KrisVos130** [comment]
I will do that then and report back tomorrow.

**Comment by KrisVos130** [comment]
Still no success, I could not find any proxy. I think I am just going to give up, thank you for your help though.
