### ISSUE TITLE
npm shrinkwrap from field inconsistency

### ISSUE THREAD

**Issue by Sinewyk** [npm/npm#9117]
I've been using npm shrinkwrap for a while now and we have some trouble with the "from" field in it being different between uses.

Sometimes it's
```json
"escape-html": {
  "version": "1.0.2",
  "from": "escape-html@1.0.2",
  "resolved": "https://registry.npmjs.org/escape-html/-/escape-html-1.0.2.tgz"
}
```

sometimes it's
```json
"escape-html": {
  "version": "1.0.2",
  "from": "https://registry.npmjs.org/escape-html/-/escape-html-1.0.2.tgz",
  "resolved": "https://registry.npmjs.org/escape-html/-/escape-html-1.0.2.tgz"
}
```

with the from field equal to the resolved field. Any idea why and how I can make this behavior stop and only use one or the other for me and my team ?

It's causing us some troubles (git conflict) when upgrading a dep in a "current" branch and then merging in a "next" branch that also touched deps, because of those we have like conflicts everywhere through the file because this "from" field is not consistent :disappointed:

**Comment by madtimber** [comment]
I just saw this today and was wondering the same thing. Just out of the blue it decided to change.

**Comment by Sinewyk** [comment]
Ok so, found why.

Npm shrinkwrap simply copy what was inside the package.json `_from` field at the time of package installation.

I have (had?) the habit of manually doing my packages upgrade after checking changelogs and stuff, so began doing stuff like running:
`npm i escape-html@1.0` for example if I just saw that 1.1 broke compatibility
`npm shrinkwrap --dev`
but in this case, when you just installed something with @ syntax, the from field is equal to the parsed expression, so `escape-html@>=1.0.0 <1.1.0` and shrinkwrap command copy that into its file.

If you delete the node_modules folder and run npm i, it will properly save the "from" field in each modules package.json, and if you run `npm shrinkwrap` again you will get the expected `resolved === from` field. So, I guess I'll probably start using `npm update` and/or stop installing with the @ syntax for upgrading, hopefully my problem won't appear again.
