### ISSUE TITLE
When including npm install in a pre-script, running the script goes to a infinite cycle 

### ISSUE THREAD

**Issue by mohsen1** [npm/npm#9119]
I have [following npm scripts](https://github.com/apigee-127/swagger-converter/blob/c11b0d8a744cfd3ec01f416aafccf5a24ddf3c0d/package.json#L6-L13) in my package.json:

```
  "scripts": {
    "test": "mocha",
    "pretest": "npm run build",
    "browserify": "browserify index.js > browser.js",
    "preuglify": "npm run browserify",
    "uglify": "uglifyjs browser.js > browser.min.js",
    "build": "npm run uglify",
    "prepublish": "npm run build"
  },
```

When I add `npm i` to `prebuild` script so it always install the dependencies before building which happens before testing it goes to an infinite loop of install/build tasks:

```
swagger-converter (master|✚1) ❯❯ npm t

> swagger-converter@0.1.7 pretest /Users/mohsen/Google Drive/Projects/swagger-converter
> npm run build


> swagger-converter@0.1.7 prebuild /Users/mohsen/Google Drive/Projects/swagger-converter
> npm i

/
> swagger-converter@0.1.7 prepublish /Users/mohsen/Google Drive/Projects/swagger-converter
> npm run build


> swagger-converter@0.1.7 prebuild /Users/mohsen/Google Drive/Projects/swagger-converter
> npm i


> swagger-converter@0.1.7 prepublish /Users/mohsen/Google Drive/Projects/swagger-converter
> npm run build

------- the loop continues ------
```

```
❯❯ node -v; npm -v
v2.5.0
2.13.2
```

**Comment by mohsen1** [comment]
Just noticed `prepublish` is being called which doesn't sound right.

**Comment by KenanY** [comment]
@mohsen1 https://docs.npmjs.com/misc/scripts

> prepublish: Run BEFORE the package is published. (Also run on local `npm install` without any arguments.)

**Comment by mohsen1** [comment]
Thanks @KenanY. I didn't notice that. It doesn't make much sense to run `prepublish` on `npm install`. Why npm does this?

**Comment by KenanY** [comment]
@mohsen1 Lots of discussion over at https://github.com/npm/npm/issues/3059 :)

**Comment by KenanY** [comment]
`prepublish-on-install` is going away in `npm@5` [[1]](https://github.com/npm/npm/blob/latest/doc/misc/npm-scripts.md#prepublish-and-prepare).
