### ISSUE TITLE
Registry error

### ISSUE THREAD

**Issue by mchisty** [npm/npm#9120]
I am getting a error that gives an error like this when I was trying to execute the "npm install -g tsd" command:

```
C:\Personal\AngularJS2>npm install -g tsd
npm ERR! registry error parsing json
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "tsd"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! Unexpected token <
npm ERR! <html><!-- InstanceBegin template="/Templates/template.dwt" codeOutsideHTMLIsLocked="false" -->
npm ERR! <head>
npm ERR! <!-- InstanceBeginEditable name="doctitle" -->
npm ERR! <title>OScaR</title>
npm ERR! <!-- InstanceEndEditable -->
npm ERR! <link rel="stylesheet" href="/includes/oscar_styles.css" type="text/css">
npm ERR! <link rel="stylesheet" href="/includes/menu.css" type="text/css">
npm ERR! <script language="JavaScript1.2" TYPE="text/javascript" src="/includes/menu_code.js"> </script>
npm ERR! <script language="JavaScript" TYPE="text/javascript" src="/includes/util.js"> </script>
npm ERR! <script language="JavaScript" TYPE="text/javascript" src="/includes/menu_settings.js"> </script>
npm ERR! <!-- InstanceBeginEditable name="head" -->
npm ERR! <style type="text/css">
npm ERR! <!--
npm ERR! .style2 {
npm ERR!        font-size: 9pt;
npm ERR!        color: #003366;
npm ERR! }
npm ERR! -->
npm ERR! </style>
npm ERR! <!-- InstanceEndEditable -->
npm ERR! </head>
npm ERR! <body>
npm ERR! <table width="100%" height="100%" border="0" cellspacing="0" cellpadding="0">
npm ERR!   <tr>
npm ERR!     <td height="90" colspan="2" valign="top"><!--<object id="WebUtility"
npm ERR!        width=0 height=0
npm ERR!         classid="CLSID:E460EAC9-0C3B-11D4-9031-000232A24A94"
npm ERR!         codebase="templates/HSWUOSR.CAB#version=1,0,0,0">
npm ERR! </object>
npm ERR! -->
npm ERR! <script language="javascript" type="text/javascript">
npm ERR! <!--
npm ERR! function launch_app(location)
npm ERR! {
npm ERR!   var oShell = new ActiveXObject("WScript.Shell");
npm ERR!   var prog = "Q:\\" + location;
npm ERR!   oShell.run ('"'+prog+'"',1);
npm ERR!
npm ERR! }
npm ERR! -->
npm ERR! </script>
npm ERR! <style type="text/css">
npm ERR! body {
npm ERR!        margin-left: 0px;
npm ERR!        margin-top: 0px;
npm ERR!        margin-right: 0px;
npm ERR!        margin-bottom: 0px;
npm ERR! }
npm ERR! </style>
....
....
....


npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Personal\AngularJS2\npm-debug.log

C:\Personal\AngularJS2>
```

I was also trying to attach the npm-debug.log file but since GitHub is rubbish, it does not allow to do so. It says "Unfortunately, we don’t support that file type. Try again with a PNG, GIF, JPG"  (don't understand why GitHub has recently been a hype? What's wrong with SVN, CVS, ...? Anyway.. that's another topic)

Thanks.
... Chisty

**Comment by KenanY** [comment]
@mchisty Are you behind a proxy by any chance?

**Comment by mchisty** [comment]
Yes. I am trying to do this from my office which is behind a firewall.
Probably this might be the issue. I do not face such problem at home.
Question is: if this is due to proxy, then npm should report some kind of
proxy error... but it does not say so.

Thanks.

**Comment by KenanY** [comment]
@mchisty Usually `npm` does throw a proxy error, but your proxy is returning an actual webpage (seen in your error log) rather than rejecting the request altogether. Relevant settings you may need to configure:

  - [`proxy`](https://docs.npmjs.com/misc/config#proxy)
  - [`https-proxy`](https://docs.npmjs.com/misc/config#https-proxy)
  - [`cafile`](https://docs.npmjs.com/misc/config#cafile)

**Comment by mchisty** [comment]
Nope. Does not work. This is really surprising why it returns an html with
error. It used to throw a proxy error once proxy was null. But once these
proxy configs are set  were set as follows:

npm config set proxy=http://proxypac/osrproxy/proxy.pac
npm config set https-proxy=http://proxypac/osrproxy/proxy.pac

*(as per your previous email, proxy, https-proxy... I reset the proxies to
null and reconfigured them again as above.)*

i.e. it does not throw the proxy error anymore. But it does show some html
(with Unexpected token < error .... etc).

Log attached.

Thanks,
... Chisty

On 1 August 2015 at 08:10, Kenan Yildirim <notifications@github.com> wrote:

> @mchisty <https://github.com/mchisty> Usually npm does throw a proxy
> error, but your proxy is returning an actual webpage (seen in your error
> log) rather than rejecting the request altogether. Relevant settings you
> may need to configure:
>
>    - proxy <https://docs.npmjs.com/misc/config#proxy>
>    - https-proxy <https://docs.npmjs.com/misc/config#https-proxy>
>    - cafile <https://docs.npmjs.com/misc/config#cafile>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/npm/npm/issues/9120#issuecomment-126824841>.
>


C:\Personal\AngularJS2>npm install -g tsd
npm ERR! registry error parsing json
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "tsd"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! Unexpected token <
npm ERR! <html>
npm ERR! <head>
npm ERR! 
npm ERR! <title>OScaR</title>
npm ERR! 
npm ERR! <link rel="stylesheet" href="/includes/oscar_styles.css" type="text/css">
npm ERR! <link rel="stylesheet" href="/includes/menu.css" type="text/css">
npm ERR! <script language="JavaScript1.2" TYPE="text/javascript" src="/includes/menu_code.js"> </script>
npm ERR! <script language="JavaScript" TYPE="text/javascript" src="/includes/util.js"> </script>
npm ERR! <script language="JavaScript" TYPE="text/javascript" src="/includes/menu_settings.js"> </script>
npm ERR! 
npm ERR! <style type="text/css">
npm ERR! 
npm ERR! </style>
npm ERR! 
npm ERR! </head>
npm ERR! <body>
npm ERR! <table width="100%" height="100%" border="0" cellspacing="0" cellpadding="0">
npm ERR!   <tr>
npm ERR!     <td height="90" colspan="2" valign="top">
npm ERR! <script language="javascript" type="text/javascript">
npm ERR! 
npm ERR! </script>
npm ERR! <style type="text/css">
npm ERR! body {
npm ERR!        margin-left: 0px;
npm ERR!        margin-top: 0px;
npm ERR!        margin-right: 0px;
npm ERR!        margin-bottom: 0px;
npm ERR! }
npm ERR! </style>
npm ERR!
npm ERR! <table width="100%" border="0" cellspacing="0" cellpadding="0">
npm ERR! 
npm ERR!   <tr>
npm ERR!     <td>
npm ERR!                <table width="100%" border="0" cellspacing="0" cellpadding="1">
npm ERR!         <tr>
npm ERR!           <td width="1053" valign="middle" class="topmenu">
npm ERR!                        <table width="100%" border="0" cellspacing="0" cellpadding="0">
npm ERR!                        <tr>
npm ERR!                                <td width="16%" valign="bottom" class="topmenu"><a href="/"><img src="/images/logo_os
car.gif"   border="0" alt="OscaR logo" /></a></td>
npm ERR!         <td width="88%" valign="bottom" class="topmenu">
npm ERR!                                        <a class="topmenu" href="/index.php">home</a> |
npm ERR!                                        <a class="topmenu" href="/general/help.php">help</a> |
npm ERR!                                        <a class="topmenu" href="/general/sitemap.php">sitemap</a> |
npm ERR!                                        <a class="topmenu" href="/general/feedback.php">feedback</a>
npm ERR!                                </td>
npm ERR!                  <td width="88%" valign="bottom" class="topmenu" ></td>
npm ERR!                        </tr>
npm ERR!                        </table>
npm ERR!                  </td>
npm ERR!           <td width="250" align="right" valign="bottom" class="topmenu">
npm ERR!           <form action="http://igoogle/search" method="get" name="gs">
npm ERR!       <table cellspacing="0" cellpadding="0" border="0">
npm ERR!          <tbody>
npm ERR!          <tr>
npm ERR!             <td>
npm ERR!                <table cellspacing="0" cellpadding="0">
npm ERR!                   <tbody><tr>
npm ERR!                      <td valign="middle"><font size="-1"><input type="text" value="" maxlength="256" size="20" name="q"/></font></td>
npm ERR!                      <td valign="middle"><font size="-1"> <input type="submit" value="search" name="btnG"/></font></td>
npm ERR!                   </tr>
npm ERR!                </tbody></table>
npm ERR!             </td>
npm ERR!          </tr>
npm ERR!       </tbody></table>
npm ERR!       <input type="hidden" value="0" name="entqr"/>
npm ERR!       <input type="hidden" value="date:D:L:d1" name="sort"/>
npm ERR!       <input type="hidden" value="xml_no_dtd" name="output"/>
npm ERR!       <input type="hidden" value="OSR" name="client"/>
npm ERR!       <input type="hidden" value="1" name="ud"/>
npm ERR!       <input type="hidden" value="UTF-8" name="oe"/><input type="hidden" value="UTF-8" name="ie"/>
npm ERR!       <input type="hidden" value="OSR" name="proxystylesheet"/>
npm ERR!       <input type="hidden" value="yes" name="proxyreload"/>
npm ERR!       <input type="hidden" value="All" name="site"/>
npm ERR! </form>
npm ERR! 
npm ERR!           </td>
npm ERR!         </tr>
npm ERR!       </table></td>
npm ERR!   </tr>
npm ERR!   <tr>
npm ERR!        <td bgcolor="#c8c8e5" valign="bottom">
npm ERR!                <script language="JavaScript" type="text/javascript" src="/includes/menu1.js"></script>
npm ERR!                <script language="JavaScript" type="text/javascript" src="/includes/submenus.js"></script>
npm ERR!        </td>
npm ERR!   </tr>
npm ERR!   <tr>
npm ERR!     <td>
npm ERR!                <table width="100%" border="0" cellspacing="0" cellpadding="0">
npm ERR!                <tr>
npm ERR!                        <td width="85%" align="left" class="topbar"><img src="/images/space.gif" alt="space logo" width="10" height="1"></td>
npm ERR!                        <td width="15%" align="right" class="topbar">04 August 2015&nbsp;</td>
npm ERR!                </tr>
npm ERR!                </table>
npm ERR!        </td>
npm ERR!   </tr>
npm ERR! </table></td>
npm ERR!   </tr>
npm ERR!   <tr>
npm ERR!     <td width="170" valign="top" align="center">
npm ERR!                <table width="100%" height="100%" border="0" cellspacing="1" cellpadding="3">
npm ERR!                <tr>
npm ERR!                        <td valign="top">
npm ERR!                                                                <script language="JavaScript">
npm ERR! 
npm ERR! var height = screen.height - 90;
npm ERR! 
npm ERR! function marsNoticepage() {
npm ERR! var load = window.open('https://mars/mars','','scrollbars=yes,menubar=no,height='+ height +',width=1024,resizable=yes,toolbar=no,location=no,status=yes,top=0,left=0');
npm ERR! }
npm ERR! </script>
npm ERR!
npm ERR! <table width="150" border="0" cellspacing="0" cellpadding="2" class="border">
npm ERR! <tr>
npm ERR!        <td class="leftnav_hdr">Tools</td>
npm ERR! </tr>
npm ERR! <tr>
npm ERR!        <td class="leftnav">
npm ERR!                <table width="100%" border="0" cellspacing="0" cellpadding="0">
npm ERR!         <tr align="center" height="40">
npm ERR!           <td width="25%"><a href="/tools/ESS_Home.php"><img src="/images/tool_ess.gif" alt="ESS" title="ESS - Apply for leave and overtime, view pay and personal details and other
employment information" width="25" height="25" border="0"></a></td>
npm ERR!           <td width="25%"><a href="https://webmail.osr.nsw.gov.au" target="_blank"><img src="/images/tool_gpwise.gif" alt="Groupwise Web Access" title="Groupwise (web version) - OSR
's email application" width="27" height="28" border="0"></a></td>
npm ERR!           <td width="25%"><a href="/tools/uam/uam_home.php"><img src="/images/tool_uam.png" alt="UAM" title="User Account Management (UAM) - add new employees and contractors, modif
y details, request access to systems, remove employee details" border="0"></a></td>
npm ERR!           <td width="25%"><a href="http://nswosr.firstsoftwaresolutions.com/" target="blank"><img src="/images/tool_library.gif" alt="Library Search" title="Library search - search
for books or serials in the OSR library" width="28" height="27" border="0"></a></td>
npm ERR!         </tr>
npm ERR!         <tr align="center" height="40">
npm ERR!            <td><a href="javascript:marsNoticepage()"><img src="/images/iconmars.gif" alt="MARS" title="MARS - Modernised Advanced RECOUPS System" width="27" height="27" border="0" /
></a></td>
npm ERR!           <td><a href="http://wnessp01/aries/ariesmenu.htm" target="_blank"><img src="/images/tool_aries.png" alt="ARiES" title="ARiES - HR information reporting suite for managers"
 width="30" height="30" border="0"></a></td>
npm ERR!           <td><a href="javascript:impsWindow();"><img src="/images/tool_imps.gif" alt="IMPS" title="IMPS - Infringement Management Processing System (for penalty notices)" width="25
" height="25" border="0"></a></td>
npm ERR!           <td><a href="https://fes/fes-prod/" class="black_link"><img src="/images/tool_fes.gif" alt="FES" title="FES - Fine Enforcement System (for enforcement orders)" border="0">
</a></td>
npm ERR!         </tr>
npm ERR!         <tr align="center" height="40">
npm ERR!           <td><a href="https://www.apps08.osr.nsw.gov.au/erevenue/calculators/" target="_blank"><img src="/images/tool_calc.gif" alt="Calculators" title="Calculators - web calculato
rs for duties and land tax" width="24" height="27" border="0" /></a></td>
npm ERR!           <td><a href="http://parwnsdm01:8080/CAisd/pdmweb.exe" target="_blank"><img src="/images/tool_serviceplus.gif" alt="ServiceDesk Manager" title="CA Service Desk Manager - he
lp desk incidents and change management jobs" border="0" /></a></td>
npm ERR!           <td><a href="http://jira:8080/" target="_blank"><img src="/images/tool_jira.png" alt="Jira" title="Jira" width="30" height="30" border="0" /></a></td>
npm ERR!           <td><a href="/tools/dictionary.php" class="black_link"><img src="/images/tool_dict.gif" alt="Dictionary" title="Macquarie Dictionary - search for words and their meaning,
thesaurus, acronyms, abbreviations" border="0"></a> </td>
npm ERR!         </tr>
npm ERR!         <tr align="center" height="40">
npm ERR!           <td><a href="http://parwnfx02/webutil" target="_blank"><img src="/images/tools_box_fax.gif" alt="RightFax" title="RightFax - fax documents from your desktop" width="27" he
ight="32" border="0" /></a></td>
npm ERR!                  <td><a href="http://parwnmp02:8080/SSAFM" target="_blank"><img src="/images/tools_masterpiece.gif" alt="Masterpiece" title="Masterpiece - accounting software for pr
ocessing invoices" width="27" height="32" border="0" /></a></td>
npm ERR!           <td><a href="http://vwikp1:8090" target="_blank"><img src="/images/tools/apollo.gif" alt="Apollo" title="Apollo - OSR's Knowledge Management System" width="26" height="28"
 border="0" /></a></td>
npm ERR!           <td align="right"><img src="/images/arrow_orange.gif" width="7" height="10" />
npm ERR!             <a class="leftnav_small" href="/tools/more_tools.php">more</a></td>
npm ERR!         </tr>
npm ERR!         <tr>
npm ERR!
npm ERR!         </tr>
npm ERR!       </table>
npm ERR!        </td>
npm ERR! </tr>
npm ERR! </table><br>
npm ERR!                                <table width="150" border="0" cellspacing="0" cellpadding="2" class="border">
npm ERR! <tr valign="top">
npm ERR!        <td class="leftnav_hdr">Quick Links</td>
npm ERR! </tr>
npm ERR! <tr valign="top">
npm ERR!        <td class="leftnav">
npm ERR!        <table width="100%" border="0" cellspacing="0" cellpadding="1">
npm ERR!        <tr class="leftnav">
npm ERR!                <td align="center"><img src="/images/bullet_purple.gif" width="12" height="13"></td>
npm ERR!                <td><a class="leftnav" href="/osr_business/projects/epmo/ci.html">Continuous Improvement</a></td>
npm ERR!        </tr>
npm ERR!        <tr class="leftnav">
npm ERR!                <td align="center"><img src="/images/bullet_purple.gif" width="12" height="13"></td>
npm ERR!                <td><a class="leftnav" href="/whos_who/osrpeople/ms/ssrm_cm.php?menuid=0">Contracts &amp Procurement</a></td>
npm ERR!        </tr>
npm ERR!        <tr class="leftnav">
npm ERR!                <td align="center" width="20"><img src="/images/bullet_purple.gif" width="12" height="13"></td>
npm ERR!                <td><a class="leftnav" href="/ohands/reactinemergency.php?menuid=0">Emergency</a></td>
npm ERR!        </tr>
npm ERR!        <tr class="leftnav">
npm ERR!                <td align="center"><img src="/images/bullet_purple.gif" width="12" height="13"></td>
npm ERR!                <td><a class="leftnav" href="/general/forms.php?menuid=0">Forms</a></td>
npm ERR!        </tr>
npm ERR!        <tr class="leftnav">
npm ERR!                <td align="center"><img src="/images/bullet_purple.gif" width="12" height="13"></td>
npm ERR!                <td><a class="leftnav" href="/general/leglinks.php?menuid=0">Legislation links</a></td>
npm ERR!        </tr>
npm ERR!        <tr class="leftnav">
npm ERR!                <td align="center"><img src="/images/bullet_purple.gif" width="12" height="13"></td>
npm ERR!                <td><a class="leftnav" href="/meet_mins/minutes.php?menuid=0">Meeting Minutes</a></td>
npm ERR!        </tr>
npm ERR!        <tr class="leftnav">
npm ERR!                <td align="center"><img src="/images/bullet_purple.gif" width="12" height="13"></td>
npm ERR!                <td><a class="leftnav" href="/tools/cura.php">Report an incident or injury</a></td>
npm ERR!        </tr>
npm ERR!        <tr class="leftnav">
npm ERR!                <td align="center"><img src="/images/bullet_purple.gif" width="12" height="13"></td>
npm ERR!                <td><a class="leftnav" href="/osr_business/corp_info/risk/index.php?menuid=0">Risk Management</a></td>
npm ERR!        </tr>
npm ERR!        <tr class="leftnav">
npm ERR!                <td align="center"><img src="/images/bullet_purple.gif" width="12" height="13"></td>
npm ERR!                <td><a class="leftnav" href="/osr_business/corp_info/template_styles/index.php?menuid=0">Templates &amp Style</a></td>
npm ERR!        </tr>
npm ERR!        <tr class="leftnav">
npm ERR!                <td align="center"><img src="/images/bullet_purple.gif" width="12" height="13"></td>
npm ERR!                <td><a class="leftnav" href="/ohands/index.php?menuid=0">WHS</a></td>
npm ERR!        </tr>
npm ERR!        </table>
npm ERR!        </td>
npm ERR! </tr>
npm ERR! </table>
npm ERR!
npm ERR!                        </td>
npm ERR!                </tr>
npm ERR!                </table>
npm ERR!        </td>
npm ERR!     <td valign="top" width="100%">
npm ERR!                <table width="100%" height="100%" border="0" cellspacing="1" cellpadding="3">
npm ERR!                <tr><td valign="top">
npm ERR!                
npm ERR!     <h1>Page can not be found</h1>
npm ERR! <h2>The page you requested is not available. </h2>
npm ERR! <p>The page may have changed name, been removed, or is temporarily unavailable.</p>
npm ERR! <p>Contact <a href="mailto:communications.communications@osr.nsw.gov.au
npm ERR! ">Business Communications</a> if you need assistance.</p>
npm ERR!
npm ERR!             <table width="95%"  border="0" cellspacing="0" cellpadding="0">
npm ERR!   <tr valign="top">
npm ERR!        <td height="156" align="left" valign="middle"><a href="javascript:history.go(-1)"><img alt="back icon" src="/images/arrow_back.gif" border="0"></a></td>
npm ERR!        <td align="right" valign="middle" class="orange_text_small"> Last Updated
npm ERR!          19-Jul-2013 </td>
npm ERR!   </tr>
npm ERR! </table>
npm ERR!     
npm ERR!                </td>
npm ERR!                </tr>
npm ERR!                </table>
npm ERR!        </td>
npm ERR!   </tr>
npm ERR!   <tr>
npm ERR!     <td height="85" colspan="2" valign="bottom"><img src="/images/space.gif" height="20" border="0" />
npm ERR! <table width="100%" border="0" cellspacing="0" cellpadding="0">
npm ERR! <tr align="justify" valign="top">
npm ERR!        <td>
npm ERR!        <table width="100%" border="0" cellspacing="0" cellpadding="0">
npm ERR!     <tr>
npm ERR!        <td colspan="5" class="bordertop"><img src="/images/space.gif" alt="space logo" width="1" height="6" /></td>
npm ERR!        </tr>
npm ERR!     </table>
npm ERR!     <table width="100%" border="0" cellspacing="0" cellpadding="0">
npm ERR!     <tr align="left" valign="top">
npm ERR!        <td width="25%">
npm ERR!         <table border="0" cellspacing="0" cellpadding="0">
npm ERR!         <tr align="left" valign="top">
npm ERR!                <td width="1" >&nbsp;</td>
npm ERR!             <td width="157"><img src="/images/space.gif" alt="space logo" width="5" /><img src="/images/logo_osr_footer.gif" alt="osr logo" border="0" /><img src="/images/space.gif"
 alt="space logo" width="100" height="1" /></td>
npm ERR!                </tr>
npm ERR!         </table>
npm ERR!         </td>
npm ERR!         <td width="75%">
npm ERR!         <table border="0" cellspacing="0" cellpadding="0">
npm ERR!         <tr align="left" valign="top">
npm ERR!                <td><img src="/images/footer_casii.png" alt="Collaboration Achievement Service Integrity Innovation" /></td>
npm ERR!                </tr>
npm ERR!         <tr align="left" valign="top">
npm ERR!                <td colspan="4" align="center" class="footnote_small">This page is <a href="http://fastrac.finance.nsw.gov.au/common_assets/Fastrac/docs/policies/DP0019.pdf" target="
_blank" class="footnote_small">approved for OSR internal release</a> only</td>
npm ERR!                </tr>
npm ERR!         </table>
npm ERR!         </td>
npm ERR!        </tr>
npm ERR!     </table>
npm ERR!     </td>
npm ERR! </tr>
npm ERR! </table>
npm ERR! <img src="/images/space.gif" height="20" border="0" />
npm ERR!
npm ERR! </td>
npm ERR!   </tr>
npm ERR! </table>
npm ERR! </body>
npm ERR! </html>19-Jul-2013
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Personal\AngularJS2\npm-debug.log
