### ISSUE TITLE
npm install appium error

### ISSUE THREAD

**Issue by liuxiu820** [npm/npm#9121]
`npm install appium` failed
refer to info:

```
C:\Users\Administrator>npm --registry http://registry.cnpmjs.org install -g appium
npm ERR! tar.unpack untar error C:\Users\ADMINI~1\AppData\Local\Temp\npm-7352-d96848da\registry.npmjs.org\appium-uiauto\-\appium-uiauto-1.10.8.tgz
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\tools\\nodejs\\\\node.exe" "D:\\tools\\nodejs\\node_modules\\
npm\\bin\\npm-cli.js" "--registry" "http://registry.cnpmjs.org" "install" "-g" "appium"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! unexpected eof
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

looking forward your resolution. Best regards

**Comment by KenanY** [comment]
@liuxiu820 Does this also occur if you use the default registry?

**Comment by liuxiu820** [comment]
Thank you for your reply

 

Default registry ,do you mean “npm install -g appium”? This also falied. 

 

I tried many times found that maybe our network doesn’t work well in China when download resourse from foreign websites

 

发件人: noreply@github.com [mailto:noreply@github.com] 代表 Kenan Yildirim
发送时间: 2015年7月31日 22:15
收件人: npm/npm
抄送: liuxiu820
主题: Re: [npm] npm install appium error (#9121)

 

@liuxiu820 <https://github.com/liuxiu820>  Does this also occur if you use the default registry?

**Comment by pawarlalit29** [comment]
I am also getting this error. I have tried like 3-4 times but not sure what has gone wrong. Any response towards resolving this issue will be super helpful to us. The log below shows the error along with NPM and node versions. Thanks a ton.

npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.12.1"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.12.1"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.12.1"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.12.1"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.12.1"})
npm ERR! Linux 3.13.0-48-generic
npm ERR! argv "node" "/home/lalit/.linuxbrew/bin/npm" "install" "-g" "appium"
npm ERR! node v0.12.7
npm ERR! npm  v2.12.1

npm ERR! unexpected eof
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/lalit/npm-debug.log
