### ISSUE TITLE
npm install problems Exit status -1

### ISSUE THREAD

**Issue by peterpalace** [npm/npm#9122]
hello everyone. I have a problem with npm and I can't figure it out .
This is the error after the command "npm start":
```
npm ERR! Linux 3.16.0-45-generic
npm ERR! argv "node" "/usr/bin/npm" "start"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! angular-seed@0.0.0 prestart: `npm install`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the angular-seed@0.0.0 prestart script 'npm install'.
npm ERR! This is most likely a problem with the angular-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-seed
npm ERR! There is likely additional logging output above.
npm ERR! Linux 3.16.0-45-generic
npm ERR! argv "node" "/usr/bin/npm" "start"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! angular-seed@0.0.0 prestart: `npm install`
npm ERR! Exit status -1
npm ERR! 
npm ERR! Failed at the angular-seed@0.0.0 prestart script 'npm install'.
npm ERR! This is most likely a problem with the angular-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-seed
npm ERR! There is likely additional logging output above.

```
It is not a problem with angular-seed because It gives me the same error with others projects.
It worked fine yesterday.
I've tried "npm update -g", "npm cache clean" but nothing change.
Thanks for the help.

**Comment by peterpalace** [comment]
With  "sudo npm start" it works.
of which directory do I have to change the permissions to use npm without sudo?
I've already done "sudo chown -R $(whoami) ~/.npm"

**Comment by sinkingshriek** [comment]
@peterpalace Give this [link](https://docs.npmjs.com/getting-started/fixing-npm-permissions) a try.

**Comment by peterpalace** [comment]
Thank you. It works. 
I changed the npm's default directory (which was /usr) to another directory inside the Home with 
``` shell
npm config set prefix '~/new_directory_name'
```
and then I added it to the PATH variable.
Perfect.
Thank you again.

**Comment by tweaty100** [comment]
how to solve this anyone please npm ERR!! exit status 1 ?i am using debian jessie.

**Comment by antonk52** [comment]
@tweaty100 have you tried the link that @shri3k provided? Worked for me
