### ISSUE TITLE
error on installing mongoose on win 8.1

### ISSUE THREAD

**Issue by hrahmani** [npm/npm#9124]
Cannot read property 'emit' of null

python installed

please help.
```
5196 verbose stack     at TLSSocket.emit (events.js:129:20)
5196 verbose stack     at TLSSocket._tlsError (_tls_wrap.js:430:10)
5196 verbose stack     at TLSWrap.ssl.onerror (_tls_wrap.js:339:12)
5197 verbose cwd D:\projects\node\userstory
5198 error Windows_NT 6.3.9600
5199 error argv "D:\\node\\\\node.exe" "D:\\node\\node_modules\\npm\\bin\\npm-cli.js" "install" "mongoose" "--save"
5200 error node v0.12.7
5201 error npm  v2.13.3
5202 error Cannot read property 'emit' of null
5203 error If you need help, you may report this error at:
5203 error     <https://github.com/npm/npm/issues>
5204 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@hrahmani Could you upload the _entire_ log as a [gist](https://gist.github.com/)?

**Comment by hrahmani** [comment]
https://gist.github.com/hrahmani/5936e852740744da4ace

**Comment by KenanY** [comment]
@hrahmani Hmm, I don't recognize that error. It almost looks like a connection/SSL issue, but I can't really tell. Maybe try [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows) to the latest stable release?

**Comment by snopeks** [comment]
Hi @hrahmani, did upgrading to the latest stable release solve the issue? We're trying to close out old issues, however if this is still affecting you please let me know, I'll be happy to re-open. Thanks!
