### ISSUE TITLE
Still same problem

### ISSUE THREAD

**Issue by Rashmi-Kolte** [npm/npm#9125]
I am getting same error(proxy settings bad connection network error while installing phonegap). I checked out internet connection. It is ok.
Please help me

**Comment by KenanY** [comment]
@Rashmi-Kolte So you are not behind a proxy or firewall that could be blocking `npm`'s registry requests? Do you have an error log that you can upload as a [gist](https://gist.github.com/)?

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.
