### ISSUE TITLE
 Unknown stratum method from XXXXX [XXXXXXX]: mining.extranonce.subscribe

### ISSUE THREAD

**Issue by lahlor** [npm/npm#9127]
Hi,

i tried to implement x11 pool but getting  Unknown stratum method from XXXXX [XXXXXXX]: mining.extranonce.subscribe after starting the mining software.

What is the problem here and what can I do to invetigate it further.
All other coins working well, but only my x11 coins having alle the same issue with stratum.

**Comment by KenanY** [comment]
@lahlor Am I wrong in saying that this is not an issue with `npm`?

**Comment by lahlor** [comment]
Ok it would be great if some than tell me where i have to look and what the message exactly indicates?

**Comment by lahlor** [comment]
So just for clarification. I tried to setup a pool for chipcoin which is x11 algo. I am trying different cpu and gpu miner with algo x11. Connection looks good but nothing happen so far on stratum but the message above just prompts in the logs after trying to connect. My other pool (dashcoin) isn't working as well. Same message.

**Comment by othiym23** [comment]
@lahlor I think bitcoin.stackexchange.com might be a better place than the issue tracker for npm, which is but a humble package manager for JavaScript and web development. We can help you with lots of things related to package management, but Bitcoin is a bit beyond our area of expertise.
