### ISSUE TITLE
Any npm code recived Error: EISDIR, read     at Error (native)

### ISSUE THREAD

**Issue by coicoronado** [npm/npm#9130]
Hello
after doing a npm config set ca='' i keep getting a Error: EISDIR, read     at Error (native)
even when i try to start my application with npm start
this is the response of the npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'npm',
1 verbose cli   '-g',
1 verbose cli   '--ca=null' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose stack Error: EISDIR, read
4 verbose stack     at Error (native)
5 verbose cwd /Users/kratos/Documents/projects/eemra
6 error Darwin 14.4.0
7 error argv "node" "/usr/local/bin/npm" "install" "npm" "-g" "--ca=null"
8 error node v0.12.2
9 error npm  v2.7.4
10 error code EISDIR
11 error errno -21
12 error EISDIR, read
13 error If you need help, you may report this error at:
13 error     <https://github.com/npm/npm/issues>
14 verbose exit [ -21, true ]

Any kind of help will be great because the only solution that i'm thinking of is a full format of my machine.    I already try to fully uninstall node and npm but i keep getting this error

The installation of the node was from brew

**Comment by KenanY** [comment]
@coicoronado `EISDIR` generally means you are missing a `package.json` somewhere, so `npm` thinks you are trying to install a directory rather than a package. Do you have a directory called `npm/` in `/Users/kratos/Documents/projects/eemra`?

**Comment by coicoronado** [comment]
@KenanY Actually i have the file package.json and i have the same result, i tried with a previous node project and also the same result, maybe is something with the global configuration

**Comment by coicoronado** [comment]
As a response to my question, i got it working doing a "reset" of configurations

1- First
```
 sudo rm -rf /usr/local/{lib/node{,/.npm,_modules},bin,share/man}/{npm*,node*,man1/node*}
```
2- Go to the folders
 ```
cd /usr/local/lib
```
And delete any **node** and **node_module** folder using this command
```
sudo rm -rf [node | node_module]
```
3- Repeat the step 2 but in the include folder
```
cd /usr/local/include
```
4- Since i installed node from homebrew need to run this command
```
brew uninstall node
```
5- Check in your **Home directory**  and delete the folders .node, .node-gyp, .npm and .npmrc
```
sudo rm -rf [.node | .node-gyp | .npm | .npmrc]
```
note that this command in .node and .npm take a little bit of time but keep calm

After all this steps just run 
```
brew install node
```
And this will return node and npm back to normal

BTW [thanks to this link](http://stackoverflow.com/questions/11177954/how-do-i-completely-uninstall-node-js-and-reinstall-from-beginning-mac-os-x/11178106#11178106) i could make it work

**Comment by olingerc** [comment]
I actually had the same error appear today. Thanks to your tip I saw that my .npmrc had a leftover
```
ca=
```
form a few days ago when I played with certificates. Removing that line made npm work again.

**Comment by ehsalazar** [comment]
@coicoronado Thanks for breaking down the steps you took to get beyond the issue. It sounds like you're back in business. I'll close this for now as we’re trying to clean up some old issues. We’ll be happy to reopen if necessary.

**Comment by coicoronado** [comment]
@olingerc yeah actually this trigger for the same reason for using or try to use certificates, maybe a heads up will be ok for future

@ehsalazar yeah it actually work and the project keeps working thanks
