### ISSUE TITLE
Executable files from dependencies in `node_modules`

### ISSUE THREAD

**Issue by kemitchell** [npm/npm#9132]
I have had issues installing packages which use binary scripts found in their dependencies, like:

```json
"bin":"node_modules/someDependency/someScript"
```

So far I've been able to reproduce a warning that an executable found in a dependency does not exist at install time:

```shellsession
$ git clone https://github.com/kemitchell/bfn_m-child.js
$ cd bfn_m-child.js
$ git checkout gitdeps
$ npm install --force
npm WARN using --force I sure hope you know what you are doing.
npm WARN package.json bfn_m-child@0.0.0 No bin file found at node_modules/bfn_m-grandchild/script
bfn_m-grandchild@0.0.0 node_modules/bfn_m-grandchild
```

The repository is https://github.com/kemitchell/bfn_m-child.js, and its dependency, which includes the executable script, is https://github.com/kemitchell/bfn_m-granchild.js. I've since pushed versions to the public registry that install dependencies from the public registry.

Before I dig too much deeper: Is referencing a path within `node_modules` in `bin` supported behavior? The [`package.json` doc](https://docs.npmjs.com/files/package.json#bin) doesn't seem to address this use case.

Ran into this writing [stdin-transform-cli](https://www.npmjs.com/package/stdin-transform-cli).

**Comment by othiym23** [comment]
Just use the bare name of the installed binary. As long as you're directly depending on the package exporting the binary, `npm run-script` will configure the paths automatically so you don't need the hard-coding (which can break when you deduped the app anyway).

**Comment by kemitchell** [comment]
Sorry, I wasn't clear.

The script set as bin in the depending package is not set as a bin executable in the providing dependency.
