### ISSUE TITLE
please am finding it difficult to install stf on mac .pls link me to any tutorial on how to install

### ISSUE THREAD

**Issue by tejumola** [npm/npm#9134]

**Comment by KenanY** [comment]
@tejumola Sorry, this issue tracker is for bugs/feature requests/discussions regarding `npm`, the package manager. If you are talking about [this `stf`](https://github.com/openstf/stf), I would suggest you try going through their `README.md`, or maybe asking one of the authors for help. Good luck!

**Comment by tejumola** [comment]
Ok.Thanks

On Sat, Aug 1, 2015 at 6:56 PM, Kenan Yildirim <notifications@github.com>
wrote:

> @tejumola <https://github.com/tejumola> Sorry, this issue tracker is for
> bugs/feature requests/discussions regarding npm, the package manager. If
> you are talking about this stf <https://github.com/openstf/stf>, I would
> suggest you try going through their README.md, or maybe asking one of the
> authors for help. Good luck!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/npm/npm/issues/9134#issuecomment-126942203>.
>



-- 
david

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues. Hopefully reaching out to the folks behind the `stf` package helped. If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.

**Comment by tejumola** [comment]
ok.am cool with it now



-- 
david
