### ISSUE TITLE
Roundup of stale (<2015) issues possibly fixed by Multi-stage-install

### ISSUE THREAD

**Issue by smikes** [npm/npm#9135]
This is from the old npm 'great cleansing' sheet, and these issues may all already be closed, but the simplest way for me to find out is to paste them all into a github issue --

3080	https://github.com/npm/npm/issues/3080
3581	https://github.com/npm/npm/issues/3581
3675	https://github.com/npm/npm/issues/3675
4012	https://github.com/npm/npm/issues/4012
4096	https://github.com/npm/npm/issues/4096
4134	https://github.com/npm/npm/issues/4134
5024	https://github.com/npm/npm/issues/5024
5083	https://github.com/npm/npm/issues/5083
5693	https://github.com/npm/npm/issues/5693
6491	https://github.com/npm/npm/issues/6491
6725	https://github.com/npm/npm/issues/6725
7268	https://github.com/npm/npm/issues/7268
7320	https://github.com/npm/npm/issues/7320
6981	https://github.com/npm/npm/issues/6981
3504	https://github.com/npm/npm/issues/3504
3523	https://github.com/npm/npm/issues/3523

**Comment by othiym23** [comment]
Thanks for putting this together, Sam. If we have time, we'll pull discussion of this into the next triage / release planning meeting (we have those on Tuesday now). We'll get these closed or prioritized eventually!

**Comment by deepu105** [comment]
does this mean NPM will not install dependencies in the nested structure with all that duplicate dependencies and long file paths?

**Comment by ehsalazar** [comment]
@smikes Thanks for this list. Most have been closed or tagged for the proper follow up.
