### ISSUE TITLE
Facing issue with running npm adduser

### ISSUE THREAD

**Issue by CharanyaR** [npm/npm#9140]
I tried to run npm adduser though i gave right username/password its giving me below error and i am able to login through web , npm version is 1.3.17:

```
Username: charanyar
Password:
Email: ravichandran.charanya@gmail.com
npm http PUT https://registry.npmjs.org/-/user/org.couchdb.user:charanyar
npm http 400 https://registry.npmjs.org/-/user/org.couchdb.user:charanyar
npm ERR! Error: Unknown error while authenticating : -/user/org.couchdb.user:charanyar
npm ERR!     at RegClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:272:14
npm ERR!     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:123:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:877:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:828:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/isaacs/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "adduser"
npm ERR! cwd C:\test-app-charr
npm ERR! node -v v0.10.23
npm ERR! npm -v 1.3.17
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\test-app-charr\npm-debug.log
npm ERR! not ok code 0
```

**Comment by KenanY** [comment]
@CharanyaR Please try [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows). I am pretty sure that `npm@1.3` is so old that it is impossible for it to communicate with the current version of the registry.

**Comment by CharanyaR** [comment]
Hi Kenan,

I tried updating my npm earlier as well but it didnt pick. I used npm
install -g npm as well npm update -g npm.

Even tried to clear cache so that the latest version gets picked. It is
still pointing to 1.3.17.

Though when i gave install it tried to download from registry 2.13.3. Its
pointing to 1.3.17.

Please help me out with this.

Regards,
Charanya

**Comment by KenanY** [comment]
@CharanyaR Yeah, upgrading on Windows can be a little tricky. Be sure to follow the instructions under the [_Upgrading on Windows_](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows) heading.

**Comment by CharanyaR** [comment]
Thanks Kenan. I will check that up hopefully it works.

Regards,
Charanya

**Comment by KenanY** [comment]
Closing since it has been over a year now. I hope you got this resolved :)
