### ISSUE TITLE
I can't install with npm

### ISSUE THREAD

**Issue by sespin** [npm/npm#9141]
Hi, I try install yeoman and bower and the installation never finish.

Any can help?
![npm_loop](https://cloud.githubusercontent.com/assets/13623975/9037224/75032846-39e9-11e5-8b2c-624802eda4ca.png)
![npm_loop_verbose](https://cloud.githubusercontent.com/assets/13623975/9037229/7b2e09de-39e9-11e5-9418-95c090c2a31d.png)

**Comment by LupDre** [comment]
How's your Internet connection? I've heard that some installations require a lot of bandwidth or else it will hang for a while.
