### ISSUE TITLE
npm install --no-bin-links: code EPERM

### ISSUE THREAD

**Issue by DmitryRomanenko** [npm/npm#9144]
I created a new Laravel project in vagrant (guest OS is Ubuntu 14.04, host OS is Windows 8.1), installed nodejs (see bellow) and ran `npm install --no-bin-links`.

There is no log file.

```
apt-key list | grep NodeSource >/dev/null || curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
echo 'deb https://deb.nodesource.com/node_0.12 trusty main' > /etc/apt/sources.list.d/nodesource.list
```

```
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ npm install --no-bin-links
npm WARN optional dep failed, continuing fsevents@0.3.7
npm ERR! tar.unpack untar error /home/vagrant/.npm/readable-stream/2.0.2/package.tgz
npm WARN optional dep failed, continuing request@2.60.0
npm ERR! Linux 3.13.0-55-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--no-bin-links"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! path /vagrant/node_modules/laravel-elixir/node_modules/gulp-phpunit/node_modules/gulp-util/node_modules/lodash.template/node_modules/lodash.escape/node_modules/lodash._escapehtmlchar/node_modules/lodash._htmlescapes/package.json.259f73027629d3ac040df45c03c81a5b
npm ERR! code EPERM
npm ERR! errno -1

npm ERR! Error: EPERM, open '/vagrant/node_modules/laravel-elixir/node_modules/gulp-phpunit/node_modules/gulp-util/node_modules/lodash.template/node_modules/lodash.escape/node_modules/lodash._escapehtmlchar/node_modules/lodash._htmlescapes/package.json.259f73027629d3ac040df45c03c81a5b'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM, open '/vagrant/node_modules/laravel-elixir/node_modules/gulp-phpunit/node_modules/gulp-util/node_modules/lodash.template/node_modules/lodash.escape/node_modules/lodash._escapehtmlchar/node_modules/lodash._htmlescapes/package.json.259f73027629d3ac040df45c03c81a5b']
npm ERR!   errno: -1,
npm ERR!   code: 'EPERM',
npm ERR!   path: '/vagrant/node_modules/laravel-elixir/node_modules/gulp-phpunit/node_modules/gulp-util/node_modules/lodash.template/node_modules/lodash.escape/node_modules/lodash._escapehtmlchar/node_modules/lodash._htmlescapes/package.json.259f73027629d3ac040df45c03c81a5b' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! Linux 3.13.0-55-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--no-bin-links"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! path npm-debug.log.af07173175c424a1c67f291d772cb392
npm ERR! code ETXTBSY
npm ERR! errno -26

npm ERR! ETXTBSY, rename 'npm-debug.log.af07173175c424a1c67f291d772cb392'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /vagrant/npm-debug.log
```

```
{
  "private": true,
  "devDependencies": {
    "gulp": "^3.8.8"
  },
  "dependencies": {
    "laravel-elixir": "^2.0.0",
    "bootstrap-sass": "^3.0.0"
  }
}
```

`sudo` didn't fix this problem.
How  can I fix it?

**Comment by SamStenton** [comment]
Also getting this problem on Win7

**Comment by DmitryRomanenko** [comment]
@othiym23 actually guest OS is Ubuntu 14.04 LTS. Why does it have `windows` tag?

**Comment by langri-sha** [comment]
You need to pass extra configuration options for `vboxsf` to create symbolic links. 

```
config.vm.provider "virtualbox" do |v|
    v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
end
```

On Windows, you have to run Vagrant from an elevated prompt that's running as a system administrator. More [here](http://stackoverflow.com/questions/24200333/symbolic-links-and-synced-folders-in-vagrant).

Alternatively, you can copy your `package.json` and run `npm install` from a path outside the `vboxsf` mount and then use [`NODE_PATH`](https://nodejs.org/api/modules.html#modules_loading_from_the_global_folders) to point Node to your `node_modules` directory.

This should also **considerably** speed up your experience with cold-starting processes that load scores of dependencies, as VBox will not have to go through the overhead of reconciling with your host filesystem when reading files.

**Comment by DmitryRomanenko** [comment]
@langri-sha Thanks, but it's not suitable.

I know that it should work, but it's not a solution, just a cludge.
It will require additional steps and break IDE integration, etc.

**Comment by langri-sha** [comment]
Truth be told, using symlinks has never been for the feint of heart since forever, doubly so on Windows. 

But, @DmitryRomanenko, I'm sorry, your right. I didn't look at the logs closely enough. This isn't good that NPM is trying to create symlinks during the course of the installation. I guess `package.json.259f73027629d3ac040df45c03c81a5b` is coming from some attempt to safely write to a path without race conditions? 

I do get this with error logs, `ETXTBSY, rename 'npm-debug.log.af07173175c424a1c67f291d772cb392'` and people never understand why I add the Git ignore `npm-debug.log*` specifically, but I never got this for other package artifacts. Which version of NPM are you using, perhaps downgrading might help?

**Comment by DmitryRomanenko** [comment]
@langri-sha I used different versions.

    npm ERR! node v0.12.7
    npm ERR! npm  v2.11.3

Also I tried with node 5.0 and current npm, and it had same trouble.
