### ISSUE TITLE
can not publish a scoped module

### ISSUE THREAD

**Issue by MarkSwanson** [npm/npm#9152]
(I'm using npm-registry-couchapp - but I'm also posting here because it may be an npm issue. I'm assuming the public registry also uses the npm-registry-couchapp project?)

npm publish works fine - so authentication is working.

As the same user, I try to publish in a scope - so I:

edit package.json
change name from "package-test" to "@deleteme/package-test"
npm publish
And I get an authentication error: Error: unauthorized Name or password is incorrect.: @deleteme/package-test

Maybe npm is sending different username / json document when a scope is used?
Or maybe the npm-registry-couchapp doesn't grok scope?

npm verb stack at CachingRegistryClient. (/home/deleteme/node-v0.12.7-linux-x64/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:247:14)
npm verb stack at Request._callback (/home/deleteme/node-v0.12.7-linux-x64/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:170:14)
npm verb stack at Request.self.callback (/home/deleteme/node-v0.12.7-linux-x64/lib/node_modules/npm/node_modules/request/request.js:354:22)
npm verb stack at Request.emit (events.js:110:17)
npm verb stack at Request. (/home/deleteme/node-v0.12.7-linux-x64/lib/node_modules/npm/node_modules/request/request.js:1207:14)
npm verb stack at Request.emit (events.js:129:20)
npm verb stack at IncomingMessage. (/home/deleteme/node-v0.12.7-linux-x64/lib/node_modules/npm/node_modules/request/request.js:1153:12)
npm verb stack at IncomingMessage.emit (events.js:129:20)

Should this work?

Thanks.

**Comment by othiym23** [comment]
To publish to a scoped package, you must either be added to that package or an owner or have admin rights over the scope. For now, "admin rights" means you must be logged in as the user with the same name as the scope (this will change shortly when the primary registry rolls out orgs and teams, but I don't think those changes will be coming to `npm-registry-couchapp`, which is a relatively small component of the primary registry's architecture these days).

So no, that shouldn't work, but if you add a user to your `npm-registry-couchapp` installation with the name `deleteme` and then try that publish again (when logged in as `deleteme`), it should work.

**Comment by MarkSwanson** [comment]
The user 'deleteme' _does_ exist in the npm-registry-couchapp installation.

The user 'deleteme' can and does publish non-scoped packages just fine, so the account/password/permissions are set up correctly.

Scoped publish simply doesn't work.
