### ISSUE TITLE
'npm start' ERR! Trying to setup Ghost Blog

### ISSUE THREAD

**Issue by ghost** [npm/npm#9159]
This is what happens when I enter 'npm start'. Please help

Ghost directions: 

• Next, grab the newly extracted ‘ghost-#.#.#’ folder and drag it onto the tab bar of your open terminal window, this will make a new terminal tab which is open at the correct location.
• In the new terminal tab type npm install --production note the two dashes
• When npm is finished installing, type npm start to start Ghost in development mode
• In a browser, navigate to 127.0.0.1:2368 to see your newly setup Ghost blog
• Change the url to 127.0.0.1:2368/ghost and create your admin user to login to the Ghost admin.

TERMINAL:

Jacobs-MacBook-Pro:~ Jacob$ /Users/Jacob/Downloads/ghost-0.6.4 npm install --production
-bash: /Users/Jacob/Downloads/ghost-0.6.4: is a directory
Jacobs-MacBook-Pro:~ Jacob$ npm start
npm ERR! Error: ENOENT, open '/Users/Jacob/package.json'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 14.3.0
npm ERR! command "node" "/usr/local/bin/npm" "start"
npm ERR! cwd /Users/Jacob
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! path /Users/Jacob/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/Jacob/npm-debug.log
npm ERR! not ok code 0

**Comment by KenanY** [comment]
@jacob0823 The log indicates that you are in your home directory. You must `cd` into the directory where you installed Ghost in order to run commands like `npm install --production` (with no arguments) or `npm start`. If your current directory does not contain a `package.json` then those commands will throw `ENOENT` errors. Newer versions of `npm` communicate this better, so consider [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm).

**Comment by jacob0823** [comment]
@KenanY Ghost is not installed. This is the process in which to install & run Ghost. Npm installed fine but I got the error once I input npm "start". I downloaded the latest npm package and it has .json

**Comment by jacob0823** [comment]
@KenanY And this wasn't the original terminal window that i got the error on. I closed it and opened a new one to see if I could get it to work but I received the same error. That's why the log above doesn't show the installation of npm

**Comment by KenanY** [comment]
Closing since user has since deleted their GitHub account.

**Comment by ekeegan** [comment]
Just another OS X(El Capitan V10.11.6) user posting error output for "npm install --production"

No npm-debug.log produced.  Was hoping to install natively on Mac to play with offline, but I'll work with Vagrant / Ubuntu instead.

npm ERR! Darwin 15.6.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! ghost@1.0.0-alpha.14 start: `node index`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the ghost@1.0.0-alpha.14 start script 'node index'.
npm ERR! This is most likely a problem with the ghost package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index
npm ERR! You can get their info via:
npm ERR!     npm owner ls ghost
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! /Users/abc/Sites//npm-debug.log
