### ISSUE TITLE
I cant install any package

### ISSUE THREAD

**Issue by jbfm21** [npm/npm#9163]
Hello, 

I´m trying to install **Bower** (and **gulp**) and always get the same error. 

    Error: connect EADDRINUSE
        at exports._errnoException (util.js:746:11)
        at connect (net.js:842:19)
        at net.js:955:9
        at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:81:16)
        at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:99:10)

Full log: https://gist.github.com/jbfm21/a30d47a3335a6ecbd39c

My OS is Windows 10 (x64), my speed network is OK, and I dont use proxy

I have tried the following things.

   a) use Node version 0.12.7 and 0.12.4
   b) cache clean
   c) increase fetch timeout
   d) change to  http://registry.npmjs.org
   e) others suggestions that i found in stackoverflow
   f) turn off Norton AntiVirus

Someone can help me.

**Comment by iamstarkov** [comment]
it seams like you had a problem with this abbrev package, but now its up and alive http://registry.npmjs.org/abbrev.

@jbfm21 can you try again?

**Comment by jbfm21** [comment]
Hello, 

same error :(

I would like to highlight this part of the log

"
    ............
	*npm info attempt registry request try #1 at 19:55:09*
	npm http request GET http://registry.npmjs.org/bower-config
	npm verb request uri http://registry.npmjs.org/bower-endpoint-parser
	npm verb request no auth needed
	npm info attempt registry request try #1 at 19:55:09
	npm http request GET http://registry.npmjs.org/bower-endpoint-parser
	npm verb request uri http://registry.npmjs.org/bower-json
	npm verb request no auth needed
	npm info attempt registry request try #1 at 19:55:09
	npm http request GET http://registry.npmjs.org/bower-json
	npm verb request uri http://registry.npmjs.org/bower-logger
	npm verb request no auth needed
	npm info attempt registry request try #1 at 19:55:09
	npm http request GET http://registry.npmjs.org/bower-logger
	npm verb request uri http://registry.npmjs.org/bower-registry-client
	npm verb request no auth needed
	npm info attempt registry request try #1 at 19:55:09
	npm http request GET http://registry.npmjs.org/bower-registry-client
	npm verb request uri http://registry.npmjs.org/cardinal
	npm verb request no auth needed
	npm info attempt registry request try #1 at 19:55:09
	npm http request GET http://registry.npmjs.org/cardinal
	npm verb request uri http://registry.npmjs.org/chalk
        ............
	npm info retry will retry, error on last attempt: Error: connect EADDRINUSE
	npm info retry will retry, error on last attempt: Error: connect EADDRINUSE
	npm info retry will retry, error on last attempt: Error: connect EADDRINUSE
	npm info retry will retry, error on last attempt: Error: connect EADDRINUSE
	npm info retry will retry, error on last attempt: Error: connect EADDRINUSE
	npm info retry will retry, error on last attempt: Error: connect EADDRINUSE
	npm info retry will retry, error on last attempt: Error: connect EADDRINUSE
	npm info retry will retry, error on last attempt: Error: connect EADDRINUSE
	npm info retry will retry, error on last attempt: Error: connect EADDRINUSE
	npm info retry will retry, error on last attempt: Error: connect EADDRINUSE
	npm info retry will retry, error on last attempt: Error: connect EADDRINUSE
	npm info retry will retry, error on last attempt: Error: connect EADDRINUSE
	npm info retry will retry, error on last attempt: Error: connect EADDRINUSE
	npm info retry will retry, error on last attempt: Error: connect EADDRINUSE
	npm info retry will retry, error on last attempt: Error: connect EADDRINUSE
	npm info retry will retry, error on last attempt: Error: connect EADDRINUSE
	npm info retry will retry, error on last attempt: Error: connect EADDRINUSE
	npm info retry will retry, error on last attempt: Error: connect EADDRINUSE
	*npm http 200 http://registry.npmjs.org/bower-config*
	npm verb get saving bower-config to d:\dsv\npm-cache\registry.npmjs.org\bower-config\.cache.json
	npm verb addNamed "0.6.1" is a plain semver version for bower-config
	npm verb addRemoteTarball http://registry.npmjs.org/bower-config/-/bower-config-0.6.1.tgz not in flight; adding
	npm verb addRemoteTarball [ 'http://registry.npmjs.org/bower-config/-/bower-config-0.6.1.tgz',
	npm verb addRemoteTarball   '7093155688bef44079bf4cb32d189312c87ded60' ]
	npm info retry fetch attempt 1 at 19:55:09

I believe that the NPM is trying to download all dependencies concurrently but only the first one is fetched and all the others is getting the error EADDRINUSE. Because of the parameter fetch-retries (witch default is 2), after secound round of trying to download all the other dependencies the installation is aborted.

Its look like that npm can´t open more than one connection to http://registry.npmjs.org/

**Comment by othiym23** [comment]
This may sound like an insultingly simple question, but have you tried restarting your machine (or Windows VM) since you started noticing this problem? `EADDRINUSE` with Node on Windows is often an indicator of some kind of underlying resource exhaustion issue. Turning off your firewall is a good idea, because that can also interfere with Node's ability to get to the internet, but sometimes it takes a reboot to get changes like that to apply.

> Its look like that npm can´t open more than one connection to http://registry.npmjs.org/

If this were true, a _lot_ of people would be having problems (most of the ways in which npm is fast rely on it being able to make lots of connections to the registry simultaneously). It's possible that something has changed in Windows 10 related to Node / npm, but at least one member of the CLI team is running on Windows 10, and I don't think she's been having issues.

**Comment by jbfm21** [comment]
Yes, i restarted the machine, turned off the firewall and the anti-virus and restarted again the machine and still doesn´t work. :(

When i increase the fetch-retries config to 50, for exemple, it works, but take a long time (3 hours running the bower installation, and doesn´t finished yet).

I´m trying to understand in which specific condition that EADDRINUSE is throwed when the npm try to execute "http request GET http://registry.npmjs.org/
<package>"

It is possible that npm registry server is blocking my IP ? Thinking that is Denial of Service attack when the NPM is trying to fetch all depenencies concurrently and allowing one connection per time?

**Comment by othiym23** [comment]
> It is possible that npm registry server is blocking my IP ? Thinking that is Denial of Service attack when the NPM is trying to fetch all depenencies concurrently and allowing one connection per time?

When you run an install, your npm process is talking to our content delivery network instead of an actual npm, Inc. server. Do you know if you have trouble accessing CDNs like Fastly from the network where you're running npm? I think your guess that something's up at the network level is right, but it seems more likely to be something in between your computer and the CDN rather than either end itself. Do you use a proxy to connect to the internet from your machine?

**Comment by jbfm21** [comment]
I just did a test right now  and there was no problem in connecting to Azure CDN ou google CDN, Do you have an url to Fastly CDN ?

I dont use a proxy to connect to internet, is a direct connection.

**Comment by jbfm21** [comment]
Hello, only one new informantion. 

I installed node version 0.10.40 (with npm 1.4.28)  and the bower installation work. After that, i tried with node version 0.12.0 and the bower installation didn´t work.

So, i believe that some changes made from one version to another is responsible for the error.

Does anyone know what kind of change may be causing this behavior?

**Comment by sinkingshriek** [comment]
@jbfm21 If upgrading is an option then you might wanna give npm upgrade a try too. npm is already v3+ at the present.

**Comment by jbfm21** [comment]
With v3+ didn´t work too. Only work with old version (1.4.28)

Where i can find the source code of   GetAddrInfoReqWrap.onlookup (dns.js:99:10)? I try to find it but without success.

**Comment by iamstarkov** [comment]
@jbfm21 try to look into dns.js source

**Comment by jbfm21** [comment]
After a lot of investigation, i removed my network driver and reinstalled. Everything works now. Thanks for trying help me.

**Comment by ehsalazar** [comment]
@jbfm21 Glad to hear you're up and running. I'll close this for now but we’ll be happy to reopen if necessary.
