### ISSUE TITLE
Error with npm install

### ISSUE THREAD

**Issue by jcortes0309** [npm/npm#9166]
I'm trying npm install -g generator-webapp; however I'm getting error messages (see below).  I even followed the instructions in the following two threads, but they didn't help me:
* https://github.com/npm/npm/issues/6922
* https://github.com/npm/npm/issues/7884

I followed the instructions in the first thread first since I was getting a WARN locking Error, but doing the nom cache clean didn't help.

Here's the error message I'm getting:

~\ $ npm install -g generator-webapp
npm ERR! Darwin 14.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "generator-webapp"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! path /usr/local/lib/node_modules/generator-webapp
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, rmdir '/usr/local/lib/node_modules/generator-webapp'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, rmdir '/usr/local/lib/node_modules/generator-webapp']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/generator-webapp' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! error rolling back Error: EACCES, rmdir '/usr/local/lib/node_modules/generator-webapp'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EACCES, rmdir '/usr/local/lib/node_modules/generator-webapp']
npm ERR! error rolling back   errno: -13,
npm ERR! error rolling back   code: 'EACCES',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/generator-webapp' }

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/juancortes/npm-debug.log

**Comment by KenanY** [comment]
@jcortes0309 Looks like you do not have permission to write to `/usr/local/`. Have you tried prepending the command with `sudo`?

**Comment by iamstarkov** [comment]
@jcortes0309 yep, @KenanY is right

**Comment by jcortes0309** [comment]
@KenanY @iamstarkov Thanks for the help.  The first thing I tried when I got the error messages was to run it with the sudo command and that didn't help.  I just ran the sudo command again after cleaning the cache and it worked fine.  Must have been some issue with the cache not being cleaned the first time around (I ran the sudo npm cache clean this time).
