### ISSUE TITLE
failed to fetch from registry: https://registry.npmjs.org/ansi-color

### ISSUE THREAD

**Issue by benbruscella** [npm/npm#9168]
Deployments started failing today, seeing this:
```
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.5

npm ERR! failed to fetch from registry: https://registry.npmjs.org/ansi-color
npm ERR!
```

Any ideas?
https://www.npmjs.com/package/ansi-color

**Comment by benbruscella** [comment]
Package that uses it
```
npm install --save brunch
```

**Comment by matthiaskurte** [comment]
Have the same error but with package sass.

npm ERR! Error: failed to fetch from registry: https://registry.npmjs.org/sass
npm ERR!     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:159:18)
npm ERR!     at cb (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:57:9)
npm ERR!     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:137:16)
npm ERR!     at cb (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:166:9)
npm ERR!     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:320:12)
npm ERR!     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:246:65)
npm ERR!     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:236:22)
npm ERR!     at Request.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1142:14)
npm ERR!     at Request.emit (events.js:117:20)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 14.4.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/matthiaskurte/htdocs/prototype
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! not ok code 0

**Comment by j0hnsmith** [comment]
I'm seeing the same for vargs

https://www.npmjs.com/package/vargs
https://registry.npmjs.org/vargs

**Comment by oigewan** [comment]
Commenting here since this probably has the same root cause.

I'm also seeing problems with the vargs package.
```
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! failed to fetch from registry: https://registry.npmjs.org/vargs
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /source/Xero.Reporting.UI/npm-debug.log
```

**Comment by Pmant** [comment]
same with traits:
http://registry.npmjs.org/traits

**Comment by dmorneau** [comment]
Also hitting this. I was able to work around the issue by doing:

`npm install http://registry.npmjs.org/ansi-color/-/ansi-color-0.2.1.tgz  --save`

The page looks broken: https://www.npmjs.com/package/ansi-color

**Comment by gabrielkapiashvili** [comment]
Also failed to fetch from registry: http://registry.npmjs.org/strscan

**Comment by forketyfork** [comment]
Same problem while trying to install `brunch` globally, and @dmorneau's workaround did not help. I installed `ansi-color`, but `brunch` fails to install with the same error.
The metadata in the npmjs.org repository seems to be broken for packages `ansi-color`, `sass`, `traits`, `strscan`, possibly more.

**Comment by forketyfork** [comment]
This helped me: https://github.com/npm/npm/issues/9177#issuecomment-127922092

**Comment by bagbee** [comment]
@dmorneau thanks!

I added to packege.json dependencies:
"ansi-color": "http://registry.npmjs.org/ansi-color/-/ansi-color-0.2.1.tgz"

it helped me.

**Comment by benbruscella** [comment]
@bagbee worked for me too

**Comment by paulmillr** [comment]
@isaacs @iarna @othiym23 Folks, this is an EXTREMELY important issue. One cannot simply depend on NPM if packages vanish from it and break builds of thousands of apps.

**Comment by Yvem** [comment]
+1 deployment of our production app is no longer possible because of this issue. 10hours without resolution already ?

**Comment by bstst** [comment]
Looks like it started working :+1:

**Comment by seldo** [comment]
Hey all: our apologies. As part of routine security tightening-up, we added a requirement that package documents have a `time` field to our front door servers. Really old packages (like 3+ years old) don't have that field so frontdoor started refusing to serve them.

We loosened the restriction this morning. No data was lost, just a temporary bug.

**Comment by Yvem** [comment]
@seldo shouldn't it be reported on http://status.npmjs.org as an incident ?

**Comment by seldo** [comment]
Good call! As far as we can tell very few users were affected (the elevated 404s from packages being unavailable were nothing like enough to register on our monitoring) but I should still put a note in there.

**Comment by josevalim** [comment]
Btw, the package is still not listed on the website: https://www.npmjs.com/package/ansi-color

**Comment by seldo** [comment]
Incident report is up on the status site: http://status.npmjs.org/incidents/t80fpy8qxnwq

@josevalim: the package lacks a README in the package.json, another side-effect of being as old as it is. We are working on correcting that bug, too :-)

**Comment by j0hnsmith** [comment]
Hello!

 

New message, please read <http://esportskart.com/position.php?i>

 

info@whywouldwe.com

**Comment by j0hnsmith** [comment]
Hello!

 

New message, please read <http://serrurier--paris.pro/eyes.php?zp>

 

info@whywouldwe.com

**Comment by j0hnsmith** [comment]
Hello!

 

New message, please read <http://grazyvarius.com/proud.php?s>

 

info@whywouldwe.com

**Comment by j0hnsmith** [comment]
Hello!

 

New message, please read <http://test.sibelayakkabicilik.com.tr/gave.php?3>

 

info@whywouldwe.com

**Comment by jfoclpf** [comment]
Now as I run `npm install --global gulp-cli` I get several similar errors as well (npm ERR! fetch failed) regarding the domain `registry.npmjs.org`

**Comment by legodude17** [comment]
`npm -v`? Update to latest and then open a new issue if it persists.
