### ISSUE TITLE
Getting error on Iconic install

### ISSUE THREAD

**Issue by deepnashi** [npm/npm#9173]
Hi, I am installing iconic but when I run command "npm install -g cordova ionic" then it provides me an error and I am attaching error lightshot link with this. So , please me regarding this.

http://prntscr.com/810pmv this is the link of my error's screenshot.

**Comment by KenanY** [comment]
@deepnashi Have you tried?:

``` bash
$ sudo chown -R $(whoami) "$HOME/.npm"
```

**Comment by deepnashi** [comment]
Dear Sir/Ma'am,
     Thanks for your response. I have tried this command now but got an error. I am attaching error lightshot link with this. So , please me regarding this.

    http://prntscr.com/81ekqv   this is the link of my error's screenshot.

**Comment by KenanY** [comment]
@deepnashi Since you do not appear to have permission to write to `/usr/local/`, you must prefix your `npm install` command with `sudo`.

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.

**Comment by deepnashi** [comment]
@ehsalazar  Hi, I am still having problem regarding installing this platform.

**Comment by ehsalazar** [comment]
@deepnashi thanks for the update. We'll reopen the issue.

**Comment by KenanY** [comment]
@deepnashi Are you still seeing this issue despite my suggestion from August? Is there a new
`npm-debug.log` file you can provide?

**Comment by KenanY** [comment]
Closing again due to no response. Can reopen if necessary.
