### ISSUE TITLE
https://registry.npmjs.org/vargs appears to have vanished

### ISSUE THREAD

**Issue by jollytoad** [npm/npm#9177]
Getting this on npm install:
```
npm ERR! node v0.12.7
npm ERR! npm  v2.13.3
 
npm ERR! failed to fetch from registry: https://registry.npmjs.org/vargs
```
Hit the URL directly and you get nothing.

The dependency chain for this is:
karma-sauce-launcher@0.2.14 -> wd@0.3.12 -> vargs@0.1.0

**Comment by bram-rongen** [comment]
second this

**Comment by stefanbuck** [comment]
Use another registry until npm solves the issue `npm config set registry http://registry.nodejitsu.com/`

Later use `npm config set registry http://registry.npmjs.org` to reset the config

**Comment by paulgambrell** [comment]
Same for sass:

ERR! failed to fetch from registry: https://registry.npmjs.org/sass

**Comment by joekukish** [comment]
Same problem here.

**Comment by XVincentX** [comment]
Same problem with coffeedoc package

**Comment by siancu** [comment]
Had the same issue and switched to the nodejitsu registry like @stefanbuck said. Works now.

**Comment by anthonyalberto** [comment]
switching to the alternate repo works , thanks!

**Comment by cgadam** [comment]
+1 to this. The registry is returning HTTP 200 but a blank response.

**Comment by Yvem** [comment]
+1

**Comment by danyshaanan** [comment]
Do we actually know that this is an npm issue and not an issue with the package itself? My first guess was that the package was unpublished, (which could explain why it is still available from mirrors).
More in https://github.com/admc/wd/issues/400

**Comment by wspittman** [comment]
https://registry.npmjs.org/vargs appears to exist again.
The world is back to normal for me.

**Comment by Yvem** [comment]
pb apparently solved https://github.com/npm/npm/issues/9168#issuecomment-128034802

**Comment by jollytoad** [comment]
Working for me now
