### ISSUE TITLE
npm install script fails in debug mode on Ubuntu

### ISSUE THREAD

**Issue by simonbcn** [npm/npm#9180]
In Ubuntu `/bin/sh` is [Dash shell no Bash](https://wiki.ubuntu.com/DashAsBinSh). The install script fails when debug mode is on:
```
$ npm_debug=1 ./install-npm.sh 
Running in debug mode.
Note that this requires bash or zsh.
+ set -o pipefail
./install-npm.sh: 48: set: Illegal option -o pipefail
```

**Comment by othiym23** [comment]
> Running in debug mode.
> Note that this requires bash or zsh.

Debug mode specifically requires a shell with those options to do its debugging magic. As this is documented in the script output you quoted, I think this is reasonably well documented and as such doesn't rise to the level of being a bug.

**Comment by simonbcn** [comment]
That is the problem. `#!/bin/sh` can be any shell... It's curious that at the beginning of the script there are comments like:
```
# See this helpful document on writing portable shell scripts:
# http://www.gnu.org/s/hello/manual/autoconf/Portable-Shell.html
```
But then they are not applied. 
If this script needs a shell like bash, why not point directly to it with `#!/bin/bash`?

**Comment by othiym23** [comment]
It only needs bash to be run in debug mode, not for ordinary use.
