### ISSUE TITLE
npm install script error in MAKE part

### ISSUE THREAD

**Issue by simonbcn** [npm/npm#9181]
The script is incorrect in this part:

```
...
MAKE=NOMAKE

if [ "x$MAKE" = "x" ]; then
...
```

The `if` is always false:

```
...
+ MAKE=NOMAKE
+ '[' xNOMAKE = x ']'
...
```

The first `MAKE=NOMAKE` (before the check) should be eliminated.

**Comment by othiym23** [comment]
That script has been scrutinized, debugged, and bikeshedded within an inch of its life. I think handling weird edge cases for strange shells and strange versions of shells was basically @isaacs's defining passion for a while. Isaac may have more to say, but my guess is that this chunk of the script is written the way it is on purpose.

**Comment by simonbcn** [comment]
This part of script simplified:
```
x=1
if x=0 then
  echo 'We have a problem...'
else
  echo 'Does anyone is surprised?'
fi
```
I think now is easier to see the problem, no?
I have a working `make` installed but this script doesn't find it:
```
$ which make
/usr/bin/make 

$ ll /usr/bin/make
-rwxr-xr-x 1 root root 167K jun  9  2013 /usr/bin/make*
```

If I execute this part of the script:
```
$ bash /tmp/install.sh 
+ MAKE=NOMAKE
+ '[' xNOMAKE = x ']'
+ make=NOMAKE
+ '[' -x NOMAKE ']'
+ make=NOMAKE
+ echo NOMAKE
NOMAKE
+ echo NOMAKE
NOMAKE
```

If I suppress the first variable initialization it works:
```
$ bash /tmp/install.sh 
+ '[' x = x ']'
++ which gmake
+ make=
+ '[' 1 -eq 0 ']'
++ which make
+ make=/usr/bin/make
+ '[' 0 -eq 0 ']'
+ '[' -x /usr/bin/make ']'
+ exit 0
+ '[' -x /usr/bin/make ']'
+ exit 0
+ echo /usr/bin/make
/usr/bin/make
+ echo

```

`MAKE` is an environment variable of the system, it can be set or not, but if the script crushes that value... :confused:

**Comment by isaacs** [comment]
Yeah, the comment directly above that line is the explanation:

```
# XXX For some reason, make is building all the docs every time.  This
# is an annoying source of bugs. Figure out why this happens.
```

If removing the `MAKE=NOMAKE` bit doesn't cause it to generate docs every time (even when they're already there) then sure, it can be removed.
