### ISSUE TITLE
trim

### ISSUE THREAD

**Issue by keshui** [npm/npm#9190]

**Comment by KenanY** [comment]
@keshui Is there a `npm-debug.log` that you can upload as a [gist](https://gist.github.com/)? I [can't help](https://github.com/npm/npm/wiki/Contributing-Guidelines) if there is no information to go off of....

**Comment by othiym23** [comment]
Closing as empty. If you encounter whatever issue led to you opening this issue again, include the error log or a gist and we can see if we can help you out.
