### ISSUE TITLE
Recursive chmod walks on symlinks

### ISSUE THREAD

**Issue by missingdays** [npm/npm#9193]
Installing package from git repository gives an error EPERM. 
I have some hooks in my .npm/_git-remotes that contain symlinks.
"addModeRecursive" function in https://github.com/npm/npm/blob/master/lib/cache/add-remote-git.js  that changes access permissions recursivly for some reason walks on symlinks too, even though chmod -R doesn't.
For obvious reasons I can't change permissions on the folder that this symlinks lead to(and that is a very bad practice anyway).
I guess you should be checking if given file is symlink and simple ignore it (like chmod -R does).

Error backtraces.
```
npm ERR! Linux 2.6.32-ovz-el-alt134
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.11.14
npm ERR! npm  v2.0.0
npm ERR! path /home/missingdays/.npm/_git-remotes/https-github-com-luckysw-node-qunit-30027e43/hooks/applypatch-msg.sample
npm ERR! code EPERM
npm ERR! errno -1

npm ERR! Error: EPERM, chmod '/home/missingdays/.npm/_git-remotes/https-github-com-luckysw-node-qunit-30027e43/hooks/applypatch-msg.sample'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM, chmod '/home/missingdays/.npm/_git-remotes/https-github-com-luckysw-node-qunit-30027e43/hooks/applypatch-msg.sample']
npm ERR!   stack: 'Error: EPERM, chmod \'/home/missingdays/.npm/_git-remotes/https-github-com-luckysw-node-qunit-30027e43/hooks/applypatch-msg.sample\'\n    at Error (native)',
npm ERR!   errno: -1,
npm ERR!   code: 'EPERM',
npm ERR!   path: '/home/missingdays/.npm/_git-remotes/https-github-com-luckysw-node-qunit-30027e43/hooks/applypatch-msg.sample',
npm ERR!   parent: 'grunt-node-qunit' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
```

**Comment by KenanY** [comment]
@missingdays Can you reproduce this with a stable version of Node.js/io.js and the latest stable release of `npm`?

**Comment by othiym23** [comment]
That's a pretty old version of npm, and newer versions of npm ignore hooks in cached git remotes altogether, so @KenanY's advice is sound. At this point, there's not really a good reason to be running Node 0.11 (which is a testing release series) – either 0.12.7 or io.js 2.4.0 are likely to be more stable and less quirky. If you're still seeing this behavior after upgrading to a stable Node and `npm@latest`, let us know, and we'll reclassify this as a bug.

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.

**Comment by missingdays** [comment]
As I can tell from patch 2.13.5 previews, this issue has been fixed.
I'll upgrade to newest version and try it.
