### ISSUE TITLE
Coding style: Double vs single quotes

### ISSUE THREAD

**Issue by ahstro** [npm/npm#9208]
Reading through and loving the your [style-guidesque docs](https://docs.npmjs.com/misc/coding-style) and I noticed that there was no mention of the ever raging war between double and single quotes. I skimmed through some of your code and found that single quotes seemed to be preferred a majority of the time; if this is the case, shouldn't it be reflected in your style guidelines?

**Comment by KenanY** [comment]
@ahstro Yes, the coding style has changed to that of [`standard`](https://github.com/feross/standard). That documentation can be updated with a pull request :)

**Comment by othiym23** [comment]
`npm@2` has no particular preference with respect to double versus single quotes, but as @KenanY mentioned, `npm@3` is checked against `standard`. The style guide needs to be updated to reflect that fact, but that won't show up in the docs until `npm@3` is `latest` (i.e. moves out of beta). A patch to the docs would be most welcome!

**Comment by aaroncrows** [comment]
I have a patch for this should I do the pull request against master?

**Comment by othiym23** [comment]
Yep! `npm@3` releases are branched from master, so that's the right place to make changes to its documentation!
