### ISSUE TITLE
Local dependencies & npm dedupe in npm 2.x

### ISSUE THREAD

**Issue by timoxley** [npm/npm#9209]
Something happened recently and now `npm dedupe` blows up with the following error when it hits local dependencies, or any other dependencies that are installed that it can't find in the registry while deduping:

```
npm ERR! Cannot read property 'dist-tags' of null
```

The error is caused by `data` being `null` in the call to `next` here (see my annotations):
 
```js
var ranges = data.ranges
    mapToRegistry(name, npm.config, function (er, uri, auth) {
      if (er) return cb(er)

      npm.registry.get(uri, { auth : auth }, next)
    })

    function next (er, data) {  // <= er is a String "404 Not Found", data is null
      var regVersions = er ? [] : Object.keys(data.versions)
      var locMatch = bestMatch(versions, ranges)
      var tag = npm.config.get("tag")
      var distTag = data["dist-tags"] && data["dist-tags"][tag] // <= Blows up here

      var regMatch
      if (distTag && data.versions[distTag] && matches(distTag, ranges)) {
        regMatch = distTag
      } else {
        regMatch = bestMatch(regVersions, ranges)
      }

      cb(null, [[name, has, loc, locMatch, regMatch, locs]])
    }
  }, cb)
```
[dedupe.js#L242-L264](https://github.com/npm/npm/blob/8ce78c29ac4b8e43ebaac117ae293e5ed0d705ad/lib/dedupe.js#L242-L264)

I suggest doing something like this on the first line as a guard against such things:

```js
data = data || {}
```
Tested on npm v2.13.5 and v2.9.0.
Doesn't appear to be an issue for npm v3.2.2.

**Comment by othiym23** [comment]
Good find! Thanks for the detailed issue, Tim!

```javascript
// <= er is a String "404 Not Found", data is null
```

The error being returned as a `String` instead of an `Error` is addressed by npm-registry-client/issues#112 / npm-registry-client/issues#112, and is actually a long-standing bug that was only exposed by some recent changes to the registry (the registry changes are arguably not bugs – basically, there are classes of requests that led to error response codes, like 404, that always used to have a response body, and now don't have a body). 

That patch sounds like a fine fix, and if you wanted to put together a quick patch + test, that would be most appreciated. We'll get to this eventually, but the next couple releases are already pretty much locked in.

**Comment by bcoe** [comment]
@timoxley starting to dig into this issue, but I can't seem to reproduce. Could you provide a minimal example that causes this behavior?

**Comment by narqo** [comment]
@bcoe it seems that all you need is to have a dependency that is not from the npm registry. For example, we use `git://` for our internal packages, that should not go to the public.

**Comment by pornel** [comment]
I've ran into the same problem. Packages that cause this use `git+http://….git#tag` URLs.

**Comment by timoxley** [comment]
@bcoe git clone https://github.com/timoxley/npm2-dedupe-localdeps-issue and run `npm test`

**Comment by bcoe** [comment]
@timoxley does this output look reasonable:

```
Benjamins-MacBook-Pro:npm2-dedupe-localdeps-issue benjamincoe$ npm dedupe
npm WARN unavoidable conflict 8F453069-banana { '/private/tmp/npm2-dedupe-localdeps-issue/node_modules/90B6FB1D-apple/node_modules/8F453069-banana': '1.0.0',
npm WARN unavoidable conflict   '/private/tmp/npm2-dedupe-localdeps-issue/node_modules/B8096B6B-carrot/node_modules/8F453069-banana': '1.0.0' }
npm WARN unavoidable conflict Not de-duplicating
```

**Comment by bcoe** [comment]
@timoxley this is now fixed in production, let me know if you run into any issues.

**Comment by timoxley** [comment]
> does this output look reasonable:

@bcoe Ideally npm could successfully deduplicate when it knows the source is the same, but anything is better than crashing.

>  this is now fixed in production

Whoo

**Comment by narqo** [comment]
@timoxley @bcoe :+1:
