### ISSUE TITLE
cant install phonegap

### ISSUE THREAD

**Issue by eloyfernandes** [npm/npm#9212]
i cant install phone i dont know why :( im using windows 10 
where i can upload the error log?

**Comment by KenanY** [comment]
@eloyfernandes Upload it as a [gist](https://gist.github.com/) please :)

**Comment by eloyfernandes** [comment]
@KenanY https://gist.github.com/eloyfernandes/961e8584ba0f04cbd030

**Comment by KenanY** [comment]
@eloyfernandes Have you tried running `npm cache clean`?

**Comment by eloyfernandes** [comment]
Thanks! it worked @KenanY

**Comment by othiym23** [comment]
Closing as resolved!
