### ISSUE TITLE
Merge 2 of my accounts due to the lack of permissions...

### ISSUE THREAD

**Issue by marcellodesales** [npm/npm#9215]
Hi there

I accidentally used the username from my private npm registry to login to the public npm and published under the username of my company. I'm trying to publish a new version of the a module and I'm getting the error.

```
 npm ERR! You do not have permission to publish 'istanbul-cobertura-badger'. Are you logged in as the correct user? : istanbul-cobertura-badger
```

The reason why is that the module was originally published with this user: 

`mdesales`: I pushed https://www.npmjs.com/package/istanbul-cobertura-badger, `https://www.npmjs.com/~mdesales`

This name is reserved to my account on our private NPM registry... 

For the public account, I've been using the username `marcellodesales`, `https://www.npmjs.com/~marcellodesales`. 

Is it possible to merge all the repos from `mdesales` into the user `marcellodesales`?

thanks
Marcello

**Comment by othiym23** [comment]
Hey, @marcellodesales! This is something that's best handled by writing to support@npmjs.com. This issue tracker is for the npm CLI, and requests to fix things like this up on the registry are best handled by our support team.

If you're blocked on getting `istanbul-cobertura-badger` published under the right account, you can use the [`npm owner`](https://docs.npmjs.com/cli/owner) command to transfer ownership of the package to `marcellodesales`, or you can just wait for the support team to get everything cleared up for you. Sorry for the inconvenience!

**Comment by marcellodesales** [comment]
@othiym23 No worries! Thanks a lot!
