### ISSUE TITLE
npm@1.4.29 that errors on attempts to install scoped packages

### ISSUE THREAD

**Issue by othiym23** [npm/npm#9216]
This would be intended for use in a new release of Node 0.10. The behavior of `npm@1.4.28` caught us by surprise: instead of erroring out, it tries to treat the scoped package name as a GitHub shortcut, which succeeds just often enough to freak out users and convince them that there's some kind of security issue in npm. Instead, as `@scope/package` is supposedly invalid syntax in `npm@1.4.28`, it should show an error urging the user to upgrade to `npm@2`.

**Comment by othiym23** [comment]
Before putting any work into this, it should probably be cross-checked with the Node.js maintainer team to ensure that they'd be up for releasing a new version of 0.10 with `npm@1.4.29` in it.

**Comment by othiym23** [comment]
This is closed by the release of `npm@1.4.29`, which is due out in Node 0.10 LTS any day now.

**Comment by zkat** [comment]
:tada:
