### ISSUE TITLE
Propose a order convention for `package.json` properties.

### ISSUE THREAD

**Issue by reggi** [npm/npm#9219]
I'd love an array of the standard conventional order a `package.json` should be in, or at-least the first couple.

```
var packageOrder = [
  'name',
  'version',
  'description',
  'main',
  'bin',
  'scripts',
  'keywords',
  'homepage',
  'bugs',
  'license',
  'author',
  'contributors',
  'files',
  'man',
  'directories',
  'repository',
  'config',
  'devDependencies',
  'dependencies',
  'peerDependencies',
  'bundledDependencies',
  'optionalDependencies',
  'engines',
  'os',
  'cpu',
  'preferGlobal',
  'private',
  'publishConfig'
]
```

Nobody want's `name`, and `main` at the bottom somewhere, nobody...

**Comment by reggi** [comment]
Here's a simple idea:

```
var _ = require('lodash')

function packageOrder (obj, props) {
  if (!props) props = packageOrder.convention
  var top = _.pick(obj, props)
  var bottom = _.omit(obj, props)
  return _.merge(top, bottom)
}

packageOrder.convention = [
  'name',
  'version',
  'description',
  'main',
  'bin',
  'scripts'
]

module.exports = packageOrder
```

**Comment by dharcourt** [comment]
A reasonable starting point would be the order of the package.json properties in the [package.json documentation](https://docs.npmjs.com/files/package.json):
```
[
    "name",
    "version",
    "description",
    "keywords",
    "homepage",
    "bugs",
    "license",
    "author",
    "contributors",
    "files",
    "main",
    "bin",
    "man",
    "directories",
    "repository",
    "scripts",
    "config",
    "dependencies",
    "devDependencies",
    "peerDependencies",
    "bundledDependencies",
    "optionalDependencies",
    "engines",
    "engineStrict",
    "os",
    "cpu",
    "preferGlobal",
    "private",
    "publishConfig"
]
```
In fact, that documentation could serve as the definition of the standard order... as long as the documentation authors understood that they can't change the order in the documentation without the side effect of changing the order of the standard :smile:.

**Comment by othiym23** [comment]
People have _very strong feelings_ about npm messing with the contents of their `package.json` files. In general, I think it's best to think of those files as npm-managed configuration that should be ignored by human beings, but that's not how many, if not most, developers think of them. npm sorts the contents of some of the fields (most notably the various kinds of dependencies managed by `--save-*`), but when we (inadvertently) changed the sort order of the file as a whole recently, pushback was immediate and very strong. As such, while I agree that for a lot of people, this would be a handy thing for you to have, it's currently an invitation to fruitless bikeshedding. Thanks for putting this together, though!

(That said, this would be a fantastic opportunity for a third-party utility to lint and clean up `package.json`!)

**Comment by reggi** [comment]
@othiym23 Thanks! I'd love a third-party util for cleaning up the package too!

**Comment by reggi** [comment]
@dharcourt Thats the same place I got my list except I floated some to the top that usually appear there. `name`, `main`, `version` seem top prio.

**Comment by sonicdoe** [comment]
I’d also like to see npm define an order convention for `package.json` properties. However, I’m also against npm forcing this convention upon every `package.json` out there.

As @dharcourt pointed out:

> In fact, that documentation could serve as the definition of the standard order

I think this would be a good idea. As it stands, `npm init` and the [package.json documentation](https://docs.npmjs.com/files/package.json) order properties differently. It would be nice to have npm use (but not enforce) one uniform order convention.

By the way, there’s also [clinton](https://github.com/SamVerschueren/clinton) which has [its own order rule](https://github.com/SamVerschueren/clinton/issues/70).

**Comment by reggi** [comment]
[fixpack](https://www.npmjs.com/package/fixpack) does this!

**Comment by imsus** [comment]
Run `npx fixpack` will help you save time.
