### ISSUE TITLE
add `npm install --reverse` (spelling TBD)

### ISSUE THREAD

**Issue by othiym23** [npm/npm#9230]
@lloydwatkin put a tremendous amount of work into #2999, which we have now let languish for several years and isn't really in a mergeable state. At the same time, @iarna has been looking into breaking the code that reads the manually-installed tree for `npm@3` out into a separate module so that `npm init` can use it to write the initial tree. It should be possible to do the same thing later.

It would also be nice if an `npm sync` command noticed that packages had been deleted from `node_modules`, and should be removed from `package.json` as part of running the sync (perhaps controlled by an option).

All of these options should also update `npm-shrinkwrap.json`, if it exists.

**Comment by iarna** [comment]
Related: #8716

**Comment by ljharb** [comment]
Please also include a way to run a command and get a zero or nonzero exit code, without making any changes to the filesystem? CI, linters/tests, and git hooks will thank you!

**Comment by othiym23** [comment]
The CLI team intends to get to this when we do the work necessary to further improve shrinkwrap support, but if somebody wants it sooner, patches are indeed welcome.
