### ISSUE TITLE
registry error parsing json (npm install -g hexo)

### ISSUE THREAD

**Issue by Jiafan** [npm/npm#9232]
### What happened
I'got this error installing hexo.
When executing command "npm install -g hexo" ,I'got error message like below:

```
npm ERR! registry error parsing json
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "hexo"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! Unexpected token d
```

### Environment
* hardware: Macbook 2.2 GHz Intel Core i7;16 GB 1600 MHz DDR3
* software: OS X 10.10.4 ;node-v0.12.7(installed with pkg)

### screenshot
<img width="762" alt="screen shot 2015-08-11 at 9 46 47 am" src="https://cloud.githubusercontent.com/assets/10692668/9188500/6df6051a-400f-11e5-9872-95ce7674e3fa.png">

<img width="762" alt="screen shot 2015-08-11 at 9 46 57 am" src="https://cloud.githubusercontent.com/assets/10692668/9188501/750b09cc-400f-11e5-9338-f9aaa052ed2d.png">

**Comment by sinkingshriek** [comment]
That is weird. This usually means that it's an invalid `JSON` as you can tell from the error but I was able to install it fine. Can you try clearing the cache with `npm cache clean` and try again?

**Comment by Jiafan** [comment]
Thank you very  much.
clearing the cache made no difference.But I had got it done by configing a new registry:
`npm config set registry https://registry.npm.taobao.org`

**Comment by aredridel** [comment]
ah! The transmission from the prior registry was being cut off in the middle. The taobao repository is probably more apt in that case if you're having network problems.

**Comment by ehsalazar** [comment]
It sounds like setting a new registry worked for you. I'll close this for now as we’re trying to clean up some solved issues. We’ll be happy to reopen if necessary.
