### ISSUE TITLE
Installing Cordova Ionic Issue

### ISSUE THREAD

**Issue by anubadshah** [npm/npm#9235]
![untitled-1](https://cloud.githubusercontent.com/assets/13745675/9194309/b413c018-4033-11e5-8504-c6be49121a4a.jpg)

**Comment by snopeks** [comment]
Hi @anubadshah. Based on `EAI_AGAIN` this looks to be a network issue. Are you using a proxy? If so, can you try configuring npm for the proxy and see if that solves the issue?

**Comment by snopeks** [comment]
@anubadshah closing this issue since we haven't heard back from you. Let me know if this is still an issue!
