### ISSUE TITLE
npm Error when install cordova in npm packagist

### ISSUE THREAD

**Issue by quyennvse02884** [npm/npm#9236]
I have installed node-js and set path to the bin folder. using Windows 8.1 pro, npm 1.4.28, node v0.10.39

i am installing cordova, with following command.

"npm install -g cordova" but i'm getting an following error:

![8-11-2015 2-43-09 pm](https://cloud.githubusercontent.com/assets/8041493/9195468/465a025c-404d-11e5-85ed-cd838ab6cced.png)

How to get resolve the problem ? thanks so much.

**Comment by KenanY** [comment]
@quyennvse02884 Are you behind a proxy? From the image, it looks like you have [`proxy`](https://docs.npmjs.com/misc/config#proxy) set to `http://proxy:8080/`... which seems too generic to actually be your proxy (hence the internet connection error that `npm` is throwing).

Maybe try deleting those settings?:

``` sh
$ npm config del proxy
$ npm config del https-proxy
```

**Comment by quyennvse02884** [comment]
@KenanY 
I resolved, 
1) first completely removed all npm, folders (i used IObit Uninstaller to completely cleaned system  from any npm possible files )
2) found npm configfile and removed it
3) removed node.js program

**Comment by ehsalazar** [comment]
It sounds like you got the install to work. I'll close this for now as we’re trying to clean up some solved issues. We’ll be happy to reopen if necessary.
