### ISSUE TITLE
 npm@3.2.2 pack "Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by stefanpenner** [npm/npm#9239]
Hello Friends of NPM,

I believe this is similar to #8138. Some algo within pack may need to be adjusted, as it blows the stack with large module trees.

#### steps to reproduce:

```sh
-> git clone https://github.com/ember-cli/ember-cl
-> cd ember-cli
-> npm i -g npm@3.2.2
-> npm pack
npm ERR! Darwin 14.4.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "pack"
npm ERR! node v2.2.1
npm ERR! npm  v3.2.2

npm ERR! Maximum call stack size exceeded
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 14.4.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "pack"
npm ERR! node v2.2.1
npm ERR! npm  v3.2.2

npm ERR! Maximum call stack size exceeded
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/stefanpenner/src/ember-cli/npm-debug.log
```

*note:
I was going to try master, but noticed the only commit since releasing 3.2.2 has been a changelog edit.*

**Comment by stefanpenner** [comment]
just confirmed same issue (as expected) on node v3

```sh
npm ERR! node v3.0.0
npm ERR! npm  v3.2.2
```

**Comment by iarna** [comment]
This doesn't happen for me with `v3.2.2`, but `v3.3.0` saw a bunch of fixes for (probably) unrelated stack explosion issues. Can you give it a try and see if it helps?

Failing that, give the `safe` branch a try– it shouldn't fix this kind of error, but it might give a better error message. (It also has a bunch of extra logging, just FYI.)

**Comment by stefanpenner** [comment]
@iarna i'll give it a go now.

**Comment by stefanpenner** [comment]
just gave `v3.3.0` a go, and the same issue appears:

```
npm version
{ 'ember-cli': '1.13.8',
  npm: '3.3.0',
  ares: '1.10.1-DEV',
  http_parser: '2.5.0',
  modules: '44',
  node: '2.2.1',
  openssl: '1.0.2a',
  uv: '1.5.0',
  v8: '4.2.77.20',
  zlib: '1.2.8' }
```

resulted in:

```
➜  ember-cli git:(master) npm pack -ddd
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/iojs', '/usr/local/bin/npm', 'pack', '-ddd' ]
npm info using npm@3.3.0
npm info using node@v2.2.1
npm sill cache add args [ '.', null ]
npm verb cache add spec .
npm sill cache add parsed spec { raw: '.',
npm sill cache add   scope: null,
npm sill cache add   name: null,
npm sill cache add   rawSpec: '.',
npm sill cache add   spec: '/Users/stefanpenner/src/ember-cli',
npm sill cache add   type: 'directory' }
npm verb addLocalDirectory /Users/stefanpenner/.npm/ember-cli/1.13.8/package.tgz not in flight; packing
npm info prepublish ember-cli@1.13.8
npm verb tar pack [ '/Users/stefanpenner/.npm/ember-cli/1.13.8/package.tgz',
npm verb tar pack   '/Users/stefanpenner/src/ember-cli' ]
npm verb tarball /Users/stefanpenner/.npm/ember-cli/1.13.8/package.tgz
npm verb folder /Users/stefanpenner/src/ember-cli
npm verb stack RangeError: Maximum call stack size exceeded
npm verb stack     at encodeField (/usr/local/lib/node_modules/npm/node_modules/tar/lib/extended-header-writer.js)
npm verb stack     at /usr/local/lib/node_modules/npm/node_modules/tar/lib/extended-header-writer.js:139:32
npm verb stack     at Array.forEach (native)
npm verb stack     at encodeFields (/usr/local/lib/node_modules/npm/node_modules/tar/lib/extended-header-writer.js:98:23)
npm verb stack     at /usr/local/lib/node_modules/npm/node_modules/tar/lib/extended-header-writer.js:137:32
npm verb stack     at Array.forEach (native)
npm verb stack     at encodeFields (/usr/local/lib/node_modules/npm/node_modules/tar/lib/extended-header-writer.js:98:23)
npm verb stack     at /usr/local/lib/node_modules/npm/node_modules/tar/lib/extended-header-writer.js:137:32
npm verb stack     at Array.forEach (native)
npm verb stack     at encodeFields (/usr/local/lib/node_modules/npm/node_modules/tar/lib/extended-header-writer.js:98:23)
npm verb cwd /Users/stefanpenner/src/ember-cli
npm ERR! Darwin 14.4.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "pack" "-ddd"
npm ERR! node v2.2.1
npm ERR! npm  v3.3.0

npm ERR! Maximum call stack size exceeded
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm verb exit [ 1, true ]
npm verb stack RangeError: Maximum call stack size exceeded
npm verb stack     at encodeField (/usr/local/lib/node_modules/npm/node_modules/tar/lib/extended-header-writer.js)
npm verb stack     at /usr/local/lib/node_modules/npm/node_modules/tar/lib/extended-header-writer.js:139:32
npm verb stack     at Array.forEach (native)
npm verb stack     at encodeFields (/usr/local/lib/node_modules/npm/node_modules/tar/lib/extended-header-writer.js:98:23)
npm verb stack     at /usr/local/lib/node_modules/npm/node_modules/tar/lib/extended-header-writer.js:137:32
npm verb stack     at Array.forEach (native)
npm verb stack     at encodeFields (/usr/local/lib/node_modules/npm/node_modules/tar/lib/extended-header-writer.js:98:23)
npm verb stack     at /usr/local/lib/node_modules/npm/node_modules/tar/lib/extended-header-writer.js:137:32
npm verb stack     at Array.forEach (native)
npm verb stack     at encodeFields (/usr/local/lib/node_modules/npm/node_modules/tar/lib/extended-header-writer.js:98:23)
npm verb cwd /Users/stefanpenner/src/ember-cli
npm ERR! Darwin 14.4.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "pack" "-ddd"
npm ERR! node v2.2.1
npm ERR! npm  v3.3.0

npm ERR! Maximum call stack size exceeded
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/stefanpenner/src/ember-cli/npm-debug.log
```

and the [npm-debug.log](https://gist.github.com/stefanpenner/bd9b11b13ad88d01922d)

–––

Going to checkout the safe branch next.

**Comment by stefanpenner** [comment]
@iarna I seem to be having trouble getting the `safe` branch to install, I am likely just forgotten the appropriate steps, can you point me to the appropriate docs?

**Comment by iarna** [comment]
`npm install -g npm/npm#safe` would be how I would install it– that does have to be done using an existing `npm@3` install.

Alternatively, you can `git clone npm` and checkout the `safe` branch and then just use it directly, eg:

```node /path/to/npm/clone install thingy```

**Comment by iarna** [comment]
So I tried to reproduce this again and following your steps it just does not reproduce for me (instead it happily creates a tarball).  Can you tar up a copy of an `ember-cli` checkout that's failing for you?

**Comment by quarterto** [comment]
I'm seeing this on 3.3.3. Here's my [npm-debug.log](https://gist.github.com/quarterto/92d5aed15ffdf47a3af7) and [package.json](https://github.com/quarterto/browser/blob/6c278bc352445cd7e8c8127709e6cb738b0e86ff/package.json).

**Comment by micahr** [comment]
I can echo this same issue is happening. When I try to publish a module with npm `3.3.4` and have anything in my `node_modules` folder I get this error. If I delete my `node_modules` folder, publish works fine.

**Comment by gregoryfoster** [comment]
+1 for @micahr's workaround, that's an important clue.

**Comment by ile** [comment]
I had this problem with `npm@3.3.6 on Ubuntu. 

It happened (by the logs) when installing the package [once](https://www.npmjs.com/package/once), but I got around that by doing `npm install once` manually and `npm install` after that.

Of course not on ideal solution.

**Comment by othiym23** [comment]
@stefanpenner @iarna made some changes to the publishing code as of `npm@3.3.5` (#9667) that addressed the issue you were seeing, so we're going to close this as resolved. @ile If you encounter this issue again with `npm@latest`, please open a new issue so we can track that separately. Thanks, everybody!

**Comment by jardayn** [comment]
npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--no-bin-links"
npm ERR! node v4.1.1
npm ERR! npm  v3.3.10

 ERR! Maximum call stack size exceeded
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--no-bin-links"
npm ERR! node v4.1.1
npm ERR! npm  v3.3.10
npm ERR!  npm-debug.log.de853319386cae823d97103e4e45e4d6
npm ERR! code ETXTBSY
npm ERR! errno -26
npm ERR! syscall rename

npm ERR! ETXTBSY: text file is busy, rename 'npm-debug.log.de853319386cae823d97103e4e45e4d6' -> 'npm-debug.log'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>



3.3.10 and it's still there it seems.

**Comment by elijahpaul** [comment]
3.4.0
```
npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--no-bin-links"
npm ERR! node v5.0.0
npm ERR! npm  v3.4.0

npm ERR! Maximum call stack size exceeded
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--no-bin-links"
npm ERR! node v5.0.0
npm ERR! npm  v3.4.0
npm ERR! path npm-debug.log.b94eecc7ab58d8720badfb37c5bafcc5
npm ERR! code ETXTBSY
npm ERR! errno -26
npm ERR! syscall rename

npm ERR! ETXTBSY: text file is busy, rename 'npm-debug.log.b94eecc7ab58d8720badfb37c5bafcc5' -> 'npm-debug.log'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by fguillen** [comment]
$ npm install -g ember-cli
    npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in favor of lodash@^4.0.0
    npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0
    npm WARN deprecated lodash-node@3.10.2: This package has been discontinued in favor of lodash@^4.0.0
    npm ERR! Linux 3.2.0-54-virtual
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ember-cli"
    npm ERR! node v5.0.0
    npm ERR! npm  v3.7.1

    npm ERR! Maximum call stack size exceeded
    npm ERR! 
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <https://github.com/npm/npm/issues>

    npm ERR! Please include the following file with any support request:
    npm ERR!     /var/www/reportsdashboardclient.daliaresearch.com/releases/20160208165448/npm-debug.log

**Comment by web-jenezis** [comment]
Hi guys,
I got the same error with node v5.0.0 and npm v3.3.6

Any updates on the issue???

```
npm ERR! Linux 3.13.0-55-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--no-bin-links"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6

npm ERR! Maximum call stack size exceeded
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/project_name/npm-debug.log
```

**Comment by hunter686** [comment]
Same v3.7.1
`vagrant@homestead:~/Code/CRM/alter-solutions-engineering-crm$ sudo npm install --no-bin-links
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/home/npm-global/bin/npm" "install" "--no-bin-links"
npm ERR! node v5.5.0
npm ERR! npm  v3.7.1

npm ERR! Maximum call stack size exceeded
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/Code/CRM/alter-solutions-engineering-crm/npm-debug.log
`

here is my debug log [debug.log](https://gist.github.com/hunter686/a4daca6ee215dd5e3d2d)

**Comment by chaseadamsio** [comment]
We see similar issues in Jenkins CI for 3.6.0.

**Comment by shauvik** [comment]
Issue still present in npm v3.8.3 (latest from homebrew)

```
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node/5.10.1/bin/node" "/usr/local/bin/npm" "install" "--no-bin-links" "--no-progress"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3

npm ERR! Maximum call stack size exceeded
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/shauvik/projects/fs/npm-debug.log
```

**Comment by zhuping** [comment]
thx @micahr solved my problem
