### ISSUE TITLE
Why does npm always reinstall phantomjs?

### ISSUE THREAD

**Issue by wil93** [npm/npm#9242]
I have the version 2.13.3 of npm. The absolute first time I issue the command `npm install` inside my project's folder I can see that many packages are being installed. However, the subsequent times I call the command I *always* get this output:

    (cmsocial)> $ npm install
    
    > phantomjs@1.9.18 install /home/wil93/git/cmsocial/cmsocial/node_modules/phantomjs
    > node install.js
    
    Download already available at /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
    Extracting tar contents (via spawned process)
    Removing /home/wil93/git/cmsocial/cmsocial/node_modules/phantomjs/lib/phantom
    Copying extracted folder /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2-extract-1439322017725/phantomjs-1.9.8-linux-x86_64 -> /home/wil93/git/cmsocial/cmsocial/node_modules/phantomjs/lib/phantom
    Writing location.js file
    Done. Phantomjs binary available at /home/wil93/git/cmsocial/cmsocial/node_modules/phantomjs/lib/phantom/bin/phantomjs

I think that, since phantomjs has been installed, the `npm install` command should do nothing.

**Comment by othiym23** [comment]
Although this is something that happens during the `npm install` process, the bit of the install causing the `phantomjs` tarball to be extracted for every install is actually a script in the `phantomjs` package, not part of npm. If you want this behavior changed, [ask them](https://github.com/Medium/phantomjs/issues).

**Comment by matthiasg** [comment]
@othiym23 i dont quite understand the reasoning here though. do i understand correctly that `npm install` always runs all install scripts even when already run ? which includes compiling too ? is this done to ensure that npm doesnt need to remember whether an install is completed ?
