### ISSUE TITLE
Apache Cordova project with VS2015 Professional, Build fails

### ISSUE THREAD

**Issue by gonadn** [npm/npm#9244]
Hi

When i create new Apache Cordova project in VS2015 Pro, i cant build the project.
I get an error saying that: 
Error	BLD401	Error : BLD00401 : Could not find module 'C:\Users\Bruker-NRX\AppData\Roaming\npm\node_modules\vs-tac\app.js'. Please Go to Tools --> Options --> Tools for Apache Cordova --> Cordova Tools --> Clear Cordova Cache and try building again.	AngularJsGoogleMap		1	Build

This error is described here:
https://social.msdn.microsoft.com/Forums/vstudio/en-US/4f97d8c5-6069-49ee-a065-283741fd483f/unable-to-build-my-first-cordova-app-in-vs-2015?forum=ToolsForApacheCordova

And on MSDN how to configure Apache Cordova Tools:
https://msdn.microsoft.com/library/dn771551%20(v=vs.140).aspx#vstac

After installing npm vs-tac:
npm install -g <path-to-vs-tac>

(C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\ApacheCordovaTools\packages\vs-tac)

And last step i did was to clear the cordova cache....

BUT still iam getting the same error.

Any suggestion?

**Comment by KenanY** [comment]
@gonadn Sorry, this does not look like an issue with `npm` to me. Is there a `npm-debug.log` anywhere that you can upload as a [gist](https://gist.github.com/)? If `npm` is not the tool that is throwing the error, then I am having trouble seeing how `npm` is at fault here.

**Comment by gonadn** [comment]
No NPM is working fine...

**Comment by KenanY** [comment]
@gonadn Hmm, then why open this issue on the issue tracker for `npm`?

**Comment by gonadn** [comment]
The first thing happen when i create Apache Cordova is the error iam getting explained aboce.

Then i install npm by navigating command prompt to my vs-tac folder located in folder(e:\Visual Studio\Programsfiles\Common7\IDE\Extensions\ApacheCordovaTools\Packages\vs-tac\ )

And run "npm -g install"

But i get an error , se pic:
![skjermbilde](https://cloud.githubusercontent.com/assets/3224441/9210480/d630037a-407c-11e5-9f67-696feefe1933.PNG)

Some how on google i find out that this issue is because of missing package.json file in vs-tac folder. 
So i just run npm init
And after that i re-run npm -g install 
![skjermbild2e](https://cloud.githubusercontent.com/assets/3224441/9210538/2d62362c-407d-11e5-8057-9572fe7e42a8.PNG)

And the i clear the cordova cache, restart VS2015, and my computer....But still iam getting the same error....

**Comment by gonadn** [comment]
KenanY sorry, but i think this issue is related to NPM

**Comment by snopeks** [comment]
Hi @gonadn, this doesn't seem to be an issue with `npm`. It looks like there's some issue with how visual studio is accessing `vs-tac`, but that's a question for the visual studio support team. There's no npm debug.log because there is no npm error going on. 

Since it looks like there is nothing more we can do on our end, I'm going to go ahead and close this issue. If you run into any npm errors please let us know, we'll be happy to reopen this issue and take a look at the `npm-debug.log`. Thanks!
