### ISSUE TITLE
Unable to install cordova using npm

### ISSUE THREAD

**Issue by sumitsoman** [npm/npm#9246]
I am unable to install cordova using npm, even after setting ca="" or ca=null.

![error](https://cloud.githubusercontent.com/assets/5772710/9216976/56c1febe-40df-11e5-9beb-adb5d841b400.png)

**Comment by JOELJOSEPHCHALAKUDY** [comment]
i also have the same issue

**Comment by JOELJOSEPHCHALAKUDY** [comment]
I also have some similar issue 
![capture](https://cloud.githubusercontent.com/assets/7545553/9217906/e6947c6e-40ea-11e5-9ad7-ecd98c1fbe64.JPG)

**Comment by shally12** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'cordova' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose install initial load of D:\Program Files\nodejs\node_global\package.json
5 verbose readDependencies loading dependencies from D:\Program Files\nodejs\node_global\package.json
6 silly cache add args [ 'cordova', null ]
7 verbose cache add spec cordova
8 silly cache add parsed spec { raw: 'cordova',
8 silly cache add   scope: null,
8 silly cache add   name: 'cordova',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed cordova@*
10 verbose addNamed "*" is a valid semver range for cordova
11 silly addNameRange { name: 'cordova', range: '*', hasData: false }
12 silly mapToRegistry name cordova
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/cordova
16 verbose addNameRange registry:https://registry.npmjs.org/cordova not in flight; fetching
17 verbose request uri https://registry.npmjs.org/cordova
18 verbose request no auth needed
19 info attempt registry request try #1 at 13:50:58
20 verbose request id b02df8f12bbd6361
21 verbose etag "6LM0QPSRCZHSLS3ZPXM3PYJF3"
22 http request GET https://registry.npmjs.org/cordova
23 http 304 https://registry.npmjs.org/cordova
24 silly get cb [ 304,
24 silly get   { date: 'Fri, 14 Aug 2015 05:50:27 GMT',
24 silly get     via: '1.1 varnish',
24 silly get     'cache-control': 'max-age=60',
24 silly get     etag: '"6LM0QPSRCZHSLS3ZPXM3PYJF3"',
24 silly get     age: '3',
24 silly get     connection: 'keep-alive',
24 silly get     'x-served-by': 'cache-nrt6132-NRT',
24 silly get     'x-cache': 'HIT',
24 silly get     'x-cache-hits': '1',
24 silly get     'x-timer': 'S1439531427.720059,VS0,VE3',
24 silly get     vary: 'Accept' } ]
25 verbose etag https://registry.npmjs.org/cordova from cache
26 verbose get saving cordova to D:\Program Files\nodejs\node_cache\registry.npmjs.org\cordova\.cache.json
27 silly addNameRange number 2 { name: 'cordova', range: '*', hasData: true }
28 silly addNameRange versions [ 'cordova',
28 silly addNameRange   [ '0.0.1',
28 silly addNameRange     '0.0.2',
28 silly addNameRange     '0.0.3',
28 silly addNameRange     '0.0.4',
28 silly addNameRange     '0.0.5',
28 silly addNameRange     '0.0.6',
28 silly addNameRange     '0.0.7',
28 silly addNameRange     '0.0.8',
28 silly addNameRange     '0.0.9',
28 silly addNameRange     '0.1.0',
28 silly addNameRange     '0.1.1',
28 silly addNameRange     '0.1.2',
28 silly addNameRange     '0.1.3',
28 silly addNameRange     '0.1.4',
28 silly addNameRange     '0.1.5',
28 silly addNameRange     '0.1.6',
28 silly addNameRange     '0.1.7',
28 silly addNameRange     '0.1.8',
28 silly addNameRange     '0.1.9',
28 silly addNameRange     '0.1.10',
28 silly addNameRange     '0.1.11',
28 silly addNameRange     '0.1.12',
28 silly addNameRange     '0.1.13',
28 silly addNameRange     '0.1.14',
28 silly addNameRange     '2.2.0',
28 silly addNameRange     '2.3.0',
28 silly addNameRange     '2.3.1',
28 silly addNameRange     '2.3.2',
28 silly addNameRange     '2.3.3',
28 silly addNameRange     '2.3.5',
28 silly addNameRange     '2.3.6',
28 silly addNameRange     '2.4.0',
28 silly addNameRange     '2.4.1',
28 silly addNameRange     '2.4.2',
28 silly addNameRange     '2.4.3',
28 silly addNameRange     '2.4.4',
28 silly addNameRange     '2.4.5',
28 silly addNameRange     '2.4.6',
28 silly addNameRange     '2.4.7',
28 silly addNameRange     '2.4.8',
28 silly addNameRange     '2.4.9',
28 silly addNameRange     '2.4.10',
28 silly addNameRange     '2.5.0',
28 silly addNameRange     '2.5.2',
28 silly addNameRange     '2.5.3',
28 silly addNameRange     '2.5.4',
28 silly addNameRange     '2.5.5',
28 silly addNameRange     '2.6.0',
28 silly addNameRange     '2.6.1',
28 silly addNameRange     '2.6.2',
28 silly addNameRange     '2.7.0-rc.1',
28 silly addNameRange     '2.7.1-rc.1',
28 silly addNameRange     '2.7.2',
28 silly addNameRange     '2.7.3',
28 silly addNameRange     '2.7.4',
28 silly addNameRange     '2.8.0',
28 silly addNameRange     '2.8.1',
28 silly addNameRange     '2.8.2',
28 silly addNameRange     '2.8.3',
28 silly addNameRange     '2.8.4',
28 silly addNameRange     '2.8.5',
28 silly addNameRange     '2.8.6',
28 silly addNameRange     '2.8.7',
28 silly addNameRange     '2.8.8',
28 silly addNameRange     '2.8.9',
28 silly addNameRange     '2.8.10',
28 silly addNameRange     '2.8.11',
28 silly addNameRange     '2.8.12',
28 silly addNameRange     '2.8.13',
28 silly addNameRange     '2.8.14',
28 silly addNameRange     '2.8.15',
28 silly addNameRange     '2.8.16',
28 silly addNameRange     '2.8.17',
28 silly addNameRange     '2.8.18',
28 silly addNameRange     '2.8.19',
28 silly addNameRange     '2.8.20',
28 silly addNameRange     '2.8.21',
28 silly addNameRange     '2.8.22',
28 silly addNameRange     '2.8.23',
28 silly addNameRange     '2.8.24',
28 silly addNameRange     '2.8.25',
28 silly addNameRange     '2.9.0',
28 silly addNameRange     '2.9.1',
28 silly addNameRange     '2.9.2',
28 silly addNameRange     '2.9.3',
28 silly addNameRange     '2.9.4',
28 silly addNameRange     '2.9.5',
28 silly addNameRange     '2.9.6',
28 silly addNameRange     '2.9.7',
28 silly addNameRange     '3.0.0-rc1',
28 silly addNameRange     '3.0.0-rc1-1',
28 silly addNameRange     '3.0.0-rc1-3',
28 silly addNameRange     '3.0.0',
28 silly addNameRange     '3.0.1',
28 silly addNameRange     '3.0.2',
28 silly addNameRange     '3.0.3',
28 silly addNameRange     '3.0.4',
28 silly addNameRange     '3.0.5',
28 silly addNameRange     '3.0.6',
28 silly addNameRange     '3.0.7',
28 silly addNameRange     '3.0.8',
28 silly addNameRange     '3.0.9',
28 silly addNameRange     '3.0.10',
28 silly addNameRange     '3.1.0-0.1.0',
28 silly addNameRange     '3.1.0-0.2.0',
28 silly addNameRange     '3.2.0-rc.1',
28 silly addNameRange     '3.2.0-0.1.0',
28 silly addNameRange     '3.2.0-0.2.0',
28 silly addNameRange     '3.2.0-0.3.0',
28 silly addNameRange     '3.2.0-0.4.0',
28 silly addNameRange     '3.3.0-rc.1',
28 silly addNameRange     '3.3.0-0.1.1',
28 silly addNameRange     '3.3.1-0.1.2',
28 silly addNameRange     '2.9.0-rc1',
28 silly addNameRange     '3.3.1-0.3.0',
28 silly addNameRange     '3.3.1-0.3.1',
28 silly addNameRange     '3.3.1-0.4.1',
28 silly addNameRange     '3.3.1-0.4.2',
28 silly addNameRange     '3.4.0-0.1.0',
28 silly addNameRange     '3.4.0-0.1.1',
28 silly addNameRange     '3.4.0-0.1.2',
28 silly addNameRange     '3.4.0-0.1.3',
28 silly addNameRange     '0.0.0-fake',
28 silly addNameRange     '3.4.1-0.1.0',
28 silly addNameRange     '3.5.0-0.2.0',
28 silly addNameRange     '3.5.0-0.2.1',
28 silly addNameRange     '3.5.0-0.2.2',
28 silly addNameRange     '3.5.0-0.2.3',
28 silly addNameRange     '3.5.0-0.2.4',
28 silly addNameRange     '3.5.0-0.2.6',
28 silly addNameRange     '3.5.0-0.2.7',
28 silly addNameRange     '3.6.0-0.2.8',
28 silly addNameRange     '3.6.0-0.2.9',
28 silly addNameRange     '3.6.1-0.2.10',
28 silly addNameRange     '3.6.3-0.2.11',
28 silly addNameRange     '3.6.3-0.2.12',
28 silly addNameRange     '3.6.3-0.2.13',
28 silly addNameRange     '4.0.0',
28 silly addNameRange     '4.0.1',
28 silly addNameRange     '4.1.0',
28 silly addNameRange     '4.1.1',
28 silly addNameRange     '4.1.2',
28 silly addNameRange     '4.1.3-nightly.2014.10.21',
28 silly addNameRange     '4.2.0',
28 silly addNameRange     '4.3.0',
28 silly addNameRange     '5.0.0',
28 silly addNameRange     '4.3.1',
28 silly addNameRange     '5.1.1',
28 silly addNameRange     '5.2.0' ] ]
29 silly addNamed cordova@5.2.0
30 verbose addNamed "5.2.0" is a plain semver version for cordova
31 silly mapToRegistry name cordova
32 silly mapToRegistry using default registry
33 silly mapToRegistry registry https://registry.npmjs.org/
34 silly mapToRegistry uri https://registry.npmjs.org/cordova
35 verbose addRemoteTarball https://registry.npmjs.org/cordova/-/cordova-5.2.0.tgz not in flight; adding
36 verbose addRemoteTarball [ 'https://registry.npmjs.org/cordova/-/cordova-5.2.0.tgz',
36 verbose addRemoteTarball   '33aded891bfe15c1835e92b4d9dfd456ecf391f2' ]
37 info retry fetch attempt 1 at 13:51:01
38 info attempt registry request try #1 at 13:51:01
39 http fetch GET https://registry.npmjs.org/cordova/-/cordova-5.2.0.tgz
40 http fetch 200 https://registry.npmjs.org/cordova/-/cordova-5.2.0.tgz
41 silly fetchAndShaCheck shasum 33aded891bfe15c1835e92b4d9dfd456ecf391f2
42 verbose stack Error: shasum check failed for C:\Users\sunli\AppData\Local\Temp\npm-2208-41c78ab6\registry.npmjs.org\cordova\-\cordova-5.2.0.tgz
42 verbose stack Expected: 33aded891bfe15c1835e92b4d9dfd456ecf391f2
42 verbose stack Actual:   96be8043c10505bca868bfeb84c241a7476db4ab
42 verbose stack From:     https://registry.npmjs.org/cordova/-/cordova-5.2.0.tgz
42 verbose stack     at D:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:38:8
42 verbose stack     at ReadStream.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:85:7)
42 verbose stack     at ReadStream.emit (events.js:129:20)
42 verbose stack     at _stream_readable.js:908:16
42 verbose stack     at process._tickCallback (node.js:355:11)
43 verbose cwd C:\
44 error Windows_NT 6.1.7601
45 error argv "D:\\Program Files\\nodejs\\\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
46 error node v0.12.7
47 error npm  v2.11.3
48 error shasum check failed for C:\Users\sunli\AppData\Local\Temp\npm-2208-41c78ab6\registry.npmjs.org\cordova\-\cordova-5.2.0.tgz
48 error Expected: 33aded891bfe15c1835e92b4d9dfd456ecf391f2
48 error Actual:   96be8043c10505bca868bfeb84c241a7476db4ab
48 error From:     https://registry.npmjs.org/cordova/-/cordova-5.2.0.tgz
49 error If you need help, you may report this error at:
49 error     <https://github.com/npm/npm/issues>
50 verbose exit [ 1, true ]

**Comment by snopeks** [comment]
Hi @sumitsoman, sorry to hear setting `ca =""` didn't work. Can you try `npm config set strict-ssl false`? 

@JOELJOSEPHCHALAKUDY it looks like you're experiencing a different issue. Try running `npm cache clean` as suggested by the error message, and if you still run into problems please open another issue, we'll be happy to help!

**Comment by snopeks** [comment]
@sumitsoman closing since we haven't heard back from you. If it's still an issue let me know!
