### ISSUE TITLE
Allowing dependency installs from every url is a proxy nightmare

### ISSUE THREAD

**Issue by olingerc** [npm/npm#9248]
My corporate firewall is very restrictive. Every outside urls have to be allowed individually and it takes days for our IT department to react. I managed to get http://registry.npmjs.org allowed and can install most packages. But now and then, I accounter packages that get dependencies from whatever address on the net and my proxy throws a hissy fit. Most of the time it is a https://github... address, but often it is something else.
So my issue is:
Why have a central registry when anybody can just send npm everywhere?? I've lost countless hours trying to get around this by playing with npm cache, or setting up intermediary proxies but every time I solve this for a particularly package, a new package arrives with yet again an obscure address.
Sorry for the rant, but I feel that there is a huge architectural design issue here.

**Comment by othiym23** [comment]
You might want to take a look at setting up either a caching proxy or a private npm instance for your company with some kind of whitelist follower. If you're working in an environment with restricted network access, a tool like [npmE](https://www.npmjs.com/enterprise), [`sinopia`](http://npm.im/sinopia), [`smart-private-npm`](http://npm.im/smart-private-npm), or [`cnpmjs`](http://npm.im/cnpmjs.org) might be able to help you keep things under tighter control. This brings with it a need to patch and republish packages with problematic dependency URLs for use within your company, but if you're operating at the kind of scale where this kind of restriction is necessary, you probably (?) have the resources necessary to deal with this.

In general, the npm ecosystem is too big and varied for us to change the way the dependencies work. I agree that it's hard to make this work well with locked-down corporate networks, but npm was designed to make it easy for developers to share their work, and this includes the flexibility of hosting / depending on packages wherever they happen to be.
