### ISSUE TITLE
Use node version from current process when run node-gyp

### ISSUE THREAD

**Issue by ikokostya** [npm/npm#9253]
I have two node (and npm) versions on my machine:

```
$ /opt/nodejs/0.12/bin/node -v
v0.12.7
$ /opt/nodejs/0.12/bin/npm -v
2.11.3
$ node -v
v0.8.26
$ npm -v
1.4.15
```

When I try install `libxmljs` package using `node 0.12`, `npm` uses global `node 0.8` for `node-gyp`

```
$ /opt/nodejs/0.12/bin/npm i libxmljs --verbose
...
npm info install libxmljs@0.14.2

> libxmljs@0.14.2 install /home/ikokostya/proj/test/node_modules/libxmljs
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp verb cli [ 'node',
gyp verb cli   '/opt/nodejs/0.12/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@2.0.1
gyp info using node@0.8.26 | linux | x64
```
After that `libxmljs` package doesn't work properly https://github.com/polotek/libxmljs/issues/312

I suggest to use same nodejs version.

**Comment by othiym23** [comment]
Reclassifying this as a bug, which will with any luck be closed when #11204 is included in a release (which is going to `npm@next` later today).
