### ISSUE TITLE
Can't install yeoman on ubuntu

### ISSUE THREAD

**Issue by Rookian** [npm/npm#9256]
When I try to install yo, I get the following error:

Error: ENOENT, chmod '/usr/local/lib/node_modules/yo/node_modules/lodash/function/before.js'

**Comment by KenanY** [comment]
@Rookian Please upload the _full_ `npm-debug.log` as a [gist](https://gist.github.com/).

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.
