### ISSUE TITLE
install vs -i

### ISSUE THREAD

**Issue by nickdesaulniers** [npm/npm#9258]
I can run `npm install --save glslify` but not `npm -i --save glslify`.  This inconsistency is unexpected.

**Comment by othiym23** [comment]
Why would `-i` be an alias for `install`?

`npm i --save glsify` works just fine, but the npm commands aren't interchangeable with options anywhere (and at this point can't, because many of the single-letter shortcuts would collide with single-letter options).

**Comment by nickdesaulniers** [comment]
> Why would -i be an alias for install?

oh, idk it just always worked.  Indeed, I'll just drop the `-` in front of `i`.
