### ISSUE TITLE
`npm search` is very slow and needs to much memory

### ISSUE THREAD

**Issue by marcbachmann** [npm/npm#9259]
`npm search` is currently not usable. It uses to much memory during the first index and is pretty slow when executing a query.

I got an out of memory error on node 0.10:
```
$ npm search
npm WARN Building the local index for the first time, please be patient
FATAL ERROR: JS Allocation failed - process out of memory
[1]    13047 abort      npm search
```

I think we can improve the `npm search` command by switching to something else than a json cache.
Maybe leveldb (or a file based index) is a good fit for that, but that's probably out of the scope of the `npm search` command and the npm module. An offline search of all modules might be more complicated in the future because the index will grow.

**Comment by timoxley** [comment]
@marcbachmann duplicate of https://github.com/npm/npm/issues/6016

**Comment by marcbachmann** [comment]
Sorry for the duplicate. I didn't find it by searching in the issues. That title doesn't describe the problem.
Can we create a follow-up ticket that describes the problem in detail?
