### ISSUE TITLE
npm warn invalid config Must be a full url with 'http://'

### ISSUE THREAD

**Issue by kmrrakesh** [npm/npm#9260]
not able to set npm config behind firewall(on windows 7 64 bit machine)

```
npm warn invalid config proxy http://'wipro\kmrrakesh:Accent@2017'@127.0.0.1:8080
npm warn invalid config Must be a full url with 'http://'
```

**Comment by pixsrv** [comment]
@kmrrakesh use escaped chars

**Comment by CrazyFish0564** [comment]
how can I  solve this problem(npm warn invalid config Must be a full url with 'http://')

**Comment by legodude17** [comment]
@CrazyFish0564 and @kmrrakesh make sure to escape all special chars.
