### ISSUE TITLE
issue installing newman

### ISSUE THREAD

**Issue by itsmallman** [npm/npm#9264]
Here is the log

```
C:\Users\PC>npm install -g newman
/


> contextify@0.1.14 install C:\Users\Variable-PC\AppData\Roaming\npm\node_module
s\newman\node_modules\jsdom\node_modules\contextify
> node-gyp rebuild


C:\Users\PC\AppData\Roaming\npm\node_modules\newman\node_modules\jsdom\
node_modules\contextify>if not defined npm_config_node_gyp (node "E:\Node-js\nod
e_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" reb
uild )  else (rebuild)
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: connect ETIMEDOUT
gyp ERR! stack     at exports._errnoException (util.js:746:11)
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1000:1
9)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "E:\\Node-js\\node_modules\\npm\\node_modules\\node-gyp\
\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Variable-PC\AppData\Roaming\npm\node_modules\newman\node_m
odules\jsdom\node_modules\contextify
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "E:\\Node-js\\\\node.exe" "E:\\Node-js\\node_modules\\npm\\bin\\np
m-cli.js" "install" "-g" "newman"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! contextify@0.1.14 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the contextify@0.1.14 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Variable-PC\npm-debug.log
```

Someone knew what it happend?
Please tell me ,thanks very much.

**Comment by KenanY** [comment]
@itsmallman `ETIMEDOUT` errors almost always indicate that the problem lies in your internet connection. Are you behind a proxy or firewall that might be refusing requests?

**Comment by itsmallman** [comment]
@KenanY 21hours ago,maybe I was behind a firewall. Now I am not. I was installed win7 sdk and win8 sdks to resolve this problem today. And I met new problems.This is log:


C:\Users\PC>npm install -g newman
\
> contextify@0.1.14 install C:\Users\Variable-PC\AppData\Roaming\npm\node_module
s\newman\node_modules\jsdom\node_modules\contextify
> node-gyp rebuild
|
C:\Users\PC\AppData\Roaming\npm\node_modules\newman\node_modules\jsdom\
node_modules\contextify>if not defined npm_config_node_gyp (node "E:\Node-js\nod
e_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" reb
uild )  else (rebuild)
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.Cpp.Platform.t
argets(42,5): error MSB8020: The builds tools for Visual Studio 2010 (Platform
Toolset = 'v100') cannot be found. To build using the v100 build tools, either
click the Project menu or right-click the solution, and then select "Update VC+
+ Projects...". Install Visual Studio 2010 to build using the Visual Studio 201
0 build tools. [C:\Users\Variable-PC\AppData\Roaming\npm\node_modules\newman\no
de_modules\jsdom\node_modules\contextify\build\contextify.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (E:\Node-js\node_modules\npm\node_modu
les\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
:12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "E:\\Node-js\\node_modules\\npm\\node_modules\\node-gyp\
\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\PC\AppData\Roaming\npm\node_modules\newman\node_m
odules\jsdom\node_modules\contextify
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "E:\\Node-js\\\\node.exe" "E:\\Node-js\\node_modules\\npm\\bin\\np
m-cli.js" "install" "-g" "newman"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! contextify@0.1.14 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the contextify@0.1.14 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\PC\npm-debug.log

thank you very much !

**Comment by shwoodard** [comment]
Replicable on unix/amd64.

**Comment by DraXus** [comment]
Same problem in Ubuntu 14.04 with nodejs 4.1.0 and npm 2.12.0

**Comment by DraXus** [comment]
I was able to install it in the end. The problem is that `contextify` doesn't work with nodejs 4, so 0.12 is needed: https://github.com/brianmcd/contextify/issues/180

Apart from that I also installed python 2.6.9 as I read in some other threads, but I'm not sure if that also helped: `npm config set python /usr/bin/python2.6`

**Comment by petulla** [comment]
Having this same issue on OSX Yosemite.

**Comment by prakhar-singh** [comment]
> As of Node 0.12, Contextify has been merged into Node, replacing the native vm module. The code has been improved on since then, so if at all possible, you should use a newer Node and the native vm module. Note that newer versions of JSDOM no longer depend on Contextify.

But the newman still uses Contextify. When can we expect a resolution of this issue?
