### ISSUE TITLE
"You cannot publish over the previously published version. Try bumping the version to 1.0.0"

### ISSUE THREAD

**Issue by damassi** [npm/npm#9266]
After publishing a few versions of my module to test `npm install` seamlessness, I've unpublished, via `npm unpublish react-tinymce-mention --force`, from npm (from what I understand this unpublishes ALL versions).  After unpublishing, I've confirmed that the module is no longer available under my username in npmjs.org, but when I try to *republish* it seems to think there are versions there by returning this message:

```
"You cannot publish over the previously published version 0.1.1. Try bumping the version to 1.0.0" : react-tinymce-mention
```

Additionally, after the publish step err'd out, it left me with this strange error placeholder located here: https://www.npmjs.com/package/react-tinymce-mention.  `npm unpublish react-tinymce-mention --force` does not remove this.  

Not sure what to do, and help would be appreciated.  

NPM Version 2.7.4

Thanks!

**Comment by KenanY** [comment]
@damassi You cannot publish over _any_ previously existing versions, whether they be published or unpublished.

**Comment by damassi** [comment]
@KenanY Can you explain why?  If something is unpublished, shouldn't it be deleted from the repository database?  Will I need to republish with a totally incorrect version number?

**Comment by damassi** [comment]
I'm wondering what steps I need to take given this new information

**Comment by ehsalazar** [comment]
@damassi Unfortunately, there is no longer any way to re-use a previously unpublished version of a package in the npm registry. The reason for this is that various systems rely on "name@version" being a unique identifier, and start throwing security warnings if the shasum changes.

While this policy is inconvenient in situations like yours, it also closes a very significant potential security vulnerability if any part of the registry infrastructure is ever compromised, without asking humans to keep track of opaque shasums themselves.

For this reason, we recommend bumping the "patch" version for even the most trivial updates.

**Comment by damassi** [comment]
@ehsalazar - thanks for the explanation; will do.

**Comment by FuzzySockets** [comment]
That makes a lot of sense.  I just made the mistake of thinking I could update a version and ended up having to use the reflog to go back in time :P

**Comment by thatisuday** [comment]
I had the same problem. Then used `v1.1.0-rc.1` instead.

**Comment by medhatdawoud** [comment]
make sure that you've changed the version of your application in the package.json file as well not only the version on git repo

**Comment by tcsiwula** [comment]
+1 for @medhatdawoud. I forgot to update the version number in package.json. Then just run npm publish and it worked fine.
