### ISSUE TITLE
Login from the command line failed

### ISSUE THREAD

**Issue by bitdivine** [npm/npm#9267]
Hello,

npm login is failing.  The npm debug log says that there is an unknown authentication error.  Can someone with access to the server please check whether there is more information there that might help?  Many thanks.

Below is a transcript of the command line output and the npm debug log.

Regards, Bit

    ~/jline$ npm login
    Username: bitdivine
    Password:  <-- Note: The password is definitely correct and still works on npmjs.com.
    Email: (bitdivine69@gmail.com) 
    npm http PUT https://registry.npmjs.org/-/user/org.couchdb.user:bitdivine
    npm http 400 https://registry.npmjs.org/-/user/org.couchdb.user:bitdivine
    npm ERR! Error: Unknown error while authenticating : -/user/org.couchdb.user:bitdivine
    npm ERR!     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:275:14)
    npm ERR!     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:123:22)
    npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
    npm ERR!     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:893:14)
    npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
    npm ERR!     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:844:12)
    npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
    npm ERR!     at _stream_readable.js:920:16
    npm ERR!     at process._tickCallback (node.js:415:13)
    npm ERR! If you need help, you may report this *entire* log,
    npm ERR! including the npm and node versions, at:
    npm ERR!     <http://github.com/isaacs/npm/issues>
    
    npm ERR! System Linux 3.2.0-4-amd64
    npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "login"
    npm ERR! cwd /home/bit/jline
    npm ERR! node -v v0.10.24
    npm ERR! npm -v 1.3.21
    npm ERR! 
    npm ERR! Additional logging details can be found in:
    npm ERR!     /home/bit/jline/npm-debug.log
    npm ERR! not ok code 0

    ~/jline$ cat npm-debug.log | sed 's/^/    /g'
    0 info it worked if it ends with ok
    1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'login' ]
    2 info using npm@1.3.21
    3 info using node@v0.10.24
    4 verbose adduser before first PUT { name: 'bitdivine',
    4 verbose adduser   salt: 'XXXXX',
    4 verbose adduser   password_sha: 'XXXXX',
    4 verbose adduser   email: 'bitdivine69@gmail.com',
    4 verbose adduser   _id: 'org.couchdb.user:bitdivine',
    4 verbose adduser   type: 'user',
    4 verbose adduser   roles: [],
    4 verbose adduser   date: '2015-08-13T18:41:54.188Z' }
    5 verbose url raw /-/user/org.couchdb.user:bitdivine
    6 verbose url resolving [ 'https://registry.npmjs.org/',
    6 verbose url resolving   './-/user/org.couchdb.user:bitdivine' ]
    7 verbose url resolved https://registry.npmjs.org/-/user/org.couchdb.user:bitdivine
    8 info trying registry request attempt 1 at 19:41:54
    9 http PUT https://registry.npmjs.org/-/user/org.couchdb.user:bitdivine
    10 http 400 https://registry.npmjs.org/-/user/org.couchdb.user:bitdivine
    11 verbose adduser back [ [Error: Unknown error while authenticating : -/user/org.couchdb.user:bitdivine],
    11 verbose adduser   { ok: false, error: 'Unknown error while authenticating' },
    11 verbose adduser   '{"ok":false,"error":"Unknown error while authenticating"}' ]
    12 error Error: Unknown error while authenticating : -/user/org.couchdb.user:bitdivine
    12 error     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:275:14)
    12 error     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:123:22)
    12 error     at Request.EventEmitter.emit (events.js:98:17)
    12 error     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:893:14)
    12 error     at Request.EventEmitter.emit (events.js:117:20)
    12 error     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:844:12)
    12 error     at IncomingMessage.EventEmitter.emit (events.js:117:20)
    12 error     at _stream_readable.js:920:16
    12 error     at process._tickCallback (node.js:415:13)
    13 error If you need help, you may report this *entire* log,
    13 error including the npm and node versions, at:
    13 error     <http://github.com/isaacs/npm/issues>
    14 error System Linux 3.2.0-4-amd64
    15 error command "/usr/local/bin/node" "/usr/local/bin/npm" "login"
    16 error cwd /home/bit/jline
    17 error node -v v0.10.24
    18 error npm -v 1.3.21
    19 verbose exit [ 1, true ]

**Comment by bitdivine** [comment]
Solved - you have already fixed it - apologies for the noise:

    sudo npm i -g npm@latest

then npm login as before.

Many thanks.

**Comment by ehsalazar** [comment]
Good to hear. I'll close this for now. We’ll be happy to reopen if necessary.
