### ISSUE TITLE
.npm-init.js runs in the cwd of the init file, not the module you're initializing

### ISSUE THREAD

**Issue by seldo** [npm/npm#9270]
If, as we recommend, your `.npm-init.js` file is in your home directory, things like `__directory` and `__filename` do not actually work as suggested by https://github.com/npm/promzard#usage

We could of course just change promzard's readme but it seems nicer to have the init running in a more intuitive context.

Repro case: `~/.npm-init.js` file of

```
module.exports = {
  "filename": __filename
}
```

produces this package.json when run in `~/projects/npm/emptydir`:

```
{
  "filename": "/Users/seldo/.npm-init.js",
  "name": "",
  "version": ""
}
```

Also of note: `name` and `version` turn up whether or not you prompt for them. Willing to file that as a separate issue or call it expected behaviour and document it, your call.

**Comment by lholmquist** [comment]
@seldo whatever happened to the `name` and `version` issue you noted?  i'm currently going to write some docs for https://github.com/npm/npm/issues/13005, which required me to go a little deeper into the init wizard thingy,  so i could try and take care of that too, if it is still deemed unexpected behaviour
