### ISSUE TITLE
Getting error while npm install in xp

### ISSUE THREAD

**Issue by ktajpuri** [npm/npm#9280]
Hi,
I am trying to use npm install on my7 machine and getting error.
My OS version is windows xp professinal SP 3.
Errors,node and npm versions are attached at images.

Please help.
![nodeerror](https://cloud.githubusercontent.com/assets/10725893/9280787/57892272-42de-11e5-982f-b705cdca15b5.PNG)
![version](https://cloud.githubusercontent.com/assets/10725893/9280788/57a79130-42de-11e5-8d4b-ba8f3a2c87e9.PNG)

**Comment by othiym23** [comment]
This looks like a Node and not an npm issue, which may be a consequence of the fact that newer versions of Node no longer support Windows XP. You might try rolling back to Node 0.10.40 (and then [upgrading to a new version of npm](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows)) and see if that works better for you -- make sure to get the correct (32- vs 64-bit) build.

If that doesn't help, I'm sorry, but there's not a lot more the npm team can do to help you. Even Microsoft has stopped supporting XP at this point.
