### ISSUE TITLE
npm install --save-dev requires admin under Windows 10

### ISSUE THREAD

**Issue by cedon** [npm/npm#9287]
While setting up a new project after upgrading to Windows 10, I noticed that my package.json file was not updating even though I was using --save-dev. The process ran like normal with no errors reported. The file was simply not being updated with the devDependencies.

I tested it using a command prompt with Admin privileges and it worked just like I used to do under a normal command prompt when I was running Windows 7.

A work-around was to use a GitBash shell. Using the NodeJS Command prompt shortcut also worked.

**Comment by cedon** [comment]
I am running npm v2.11.3 which came with my NodeJS install.

**Comment by othiym23** [comment]
Closing as resolved!

The Node team builds the Node installer with the most current stable version of npm available at the time that version was cut, so a newer version of npm won't be included with Node until the next stable version is released. The build team does do some value-added stuff, like ensuring that the npm test suite passes with that build of Node, so switching to using a download+install script would probably be a step backwards in terms of robustness of npm + Node. It _would_ be nice if it were easier to upgrade npm on Windows, though, and this something both the npm and Node teams are working on tweaking.
