### ISSUE TITLE
npm install grunt-ts --save -dev on Windows giving errors

### ISSUE THREAD

**Issue by AndyBrownlie** [npm/npm#9289]
I have been trying without luck over the past couple of days to get this working.

npm has been working for 6 months+ without issues up until now. I haven't changed anything to my dev environment, and all of a sudden its stopped working and producing a number of errors

 (see https://gist.github.com/anonymous/a651543e6ef8b79c909c)

I've tried upgrading to latest node & npm, but this hasn't helped.
I've also cleared the npm-cache and npm-modules dirs as similar issues recommended this but still to no avail.

Any help is greatly appreciated.

**Comment by AndyBrownlie** [comment]
additional info:

I've also noticed that npm has went from lightening fast to dog slow (relatively speaking) since I got these errors. Could this be related to a Windows security patch perhaps?

**Comment by busches** [comment]
Can you provide any more details for this? Can you give the command you're running? Does the latest `npm2` or `npm3` work for you?
@KenanY

**Comment by AndyBrownlie** [comment]
This was so long ago now. I did get past it, and it did seem to rectify itself with an update of npm, but I couldn't tell you what release.  I have not been working with grunt for a few months, so to be honest, I'm not sure how it is just now.
