### ISSUE TITLE
npm install -g phonegap npm, install -g cordova 

### ISSUE THREAD

**Issue by ravi5624** [npm/npm#9293]
not able to install cordova, phonegap .it's giving error

**Comment by KenanY** [comment]
@ravi5624 Is there a `npm-debug.log` you can upload as a [gist](https://gist.github.com/)?

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.

**Comment by ravi5624** [comment]
Hey ,

Thanks for response. Rightnow   i have solved the problem if i need help
next time i will let you know
