### ISSUE TITLE
Latest version of jest-cli is incorrect

### ISSUE THREAD

**Issue by chentsulin** [npm/npm#9294]
`jest-cli 0.5.0` already be released, and I can use `npm install jest-cli@0.5` to successful install it. 

But the latest version of jest-cli which shown on [npm page](https://www.npmjs.com/package/jest-cli) is `0.4.19`, and version installed by `npm install jest-cli` is also `0.4.19`. 

Any ideas here? 

https://github.com/facebook/jest/pull/461

**Comment by KenanY** [comment]
@chentsulin `jest-cli@0.4.19` is what's [tagged](https://docs.npmjs.com/cli/dist-tag) as `latest`. In fact, `0.4.19` was published about 16 minutes _after_ `0.5.0`, hence it is by default tagged as `latest`. This can easily be changed with `npm dist-tag`.

**Comment by chentsulin** [comment]
Thanks for the response. Learn a lesson about `npm dist-tag`. : )
