### ISSUE TITLE
Manual installation of "npm" causes broken links in "[prefix]/share/man"

### ISSUE THREAD

**Issue by the-real-tokai** [npm/npm#9296]
I installed `Node` on `OS X 10.10.5` via `Homebrew` but without the included `npm` (using `brew install node --without-npm --with-openssl`) to avoid all the double path mess this kind of installation would cause. So the next step was to install `npm` additionally. I did this the following way:

```
$ node -v
v0.12.7

$ sudo mkdir /usr/local/node
$ echo 'prefix=/usr/local/node' >~/.npmrc

$ wget https://www.npmjs.com/install.sh
$ chmod +x ./install.sh
$ sudo ./install.sh

$ sudo sh -c 'echo /usr/local/node/bin >/etc/paths.d/npm'
$ sudo sh -c 'echo /usr/local/node/share/man >/etc/manpaths.d/npm'
```

So far all good, no errors during the installation and all path variables are setup properly. (verified with 
`/usr/libexec/path_helper -s` and `man -w`)

But inside `/usr/local/node/share/man` all man files are links to some temporary directory (where the original tar ball was extracted by the `install.sh` script):

```
$ ls -lR /usr/local/node/share/man
...
./man1:
total 416
drwxr-xr-x  54 root  wheel  1836 Aug 16 10:41 .
drwxr-xr-x   6 root  wheel   204 Aug 16 10:41 ..
lrwxr-xr-x   1 root  wheel    52 Aug 16 10:41 npm-README.1 -> /private/tmp/npm.39223/package/man/man1/npm-README.1
lrwxr-xr-x   1 root  wheel    52 Aug 16 10:41 npm-access.1 -> /private/tmp/npm.39223/package/man/man1/npm-access.1
lrwxr-xr-x   1 root  wheel    53 Aug 16 10:41 npm-adduser.1 -> /private/tmp/npm.39223/package/man/man1/npm-adduser.1
lrwxr-xr-x   1 root  wheel    49 Aug 16 10:41 npm-bin.1 -> /private/tmp/npm.39223/package/man/man1/npm-bin.1
lrwxr-xr-x   1 root  wheel    50 Aug 16 10:41 npm-bugs.1 -> /private/tmp/npm.39223/package/man/man1/npm-bugs.1
lrwxr-xr-x   1 root  wheel    51 Aug 16 10:41 npm-build.1 -> /private/tmp/npm.39223/package/man/man1/npm-build.1
...
```

Of course the "npm.39223" directory was gone already, so the links didn't work either. **This is definitely fishy and can't be right.**

I tried deleting the broken links and run a `sudo npm update -g npm` (and a `sudo npm install -g npm`), but this was no help either.

Besides the initial installation problem I'm not sure what the proper procedure would be to update the man files to the latest version anyway. I would have assumed that `sudo npm install -g npm` would do the trick. But I'm rather very new to Node/ npm, so I have no clue how this is supposed to work exactly. :)

**Comment by sparhomenko** [comment]
If that would be of any help to anyone, I used this script to workaround this bug:
```sh
(cd $(dirname $(which node))/$(dirname $(readlink $(which node)))/../share/man && find . \
-type l -ilname "/private/var/*/npm*/package/man/*" \
-exec ln -sf ../../../lib/node_modules/npm/man/{} {} \;)
brew unlink node && brew link node
```
