### ISSUE TITLE
Can't find dns_sd.h on RPi running Node 12.0 & NPM 2.5.1

### ISSUE THREAD

**Issue by AAADiver** [npm/npm#9298]
Hi complete noob but I'm just setting up a new RPi 2. While trying to install another package, it keeps failing when trying to find dns_sd.h. I did try "npm install mdns" and it fails for the same reason. 

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory '/root/node/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
In file included from ../src/dns_sd.cpp:1:0:
../src/mdns.hpp:32:20: fatal error: dns_sd.h: No such file or directory

Thx for any advice,
Allen

**Comment by KenanY** [comment]
@AAADiver Is this happening just for `mdns`? Are you sure you installed the [necessary dependencies](https://github.com/agnat/node_mdns#installation) beforehand?

**Comment by AAADiver** [comment]
Solved: Had to install:
sudo apt-get install build-essential libavahi-compat-libdnssd-dev git
