### ISSUE TITLE
npm not ok when installing bower

### ISSUE THREAD

**Issue by chfakht** [npm/npm#9307]
Hi, i want to install bower , after running "npm install -g bower"  (https://github.com/bower/bower)
i get

```
npm http GET https://registry.npmjs.org/bower

npm ERR! Error: failed to fetch from registry: bower
npm ERR! at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR! at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
npm ERR! at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
npm ERR! at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR! at Request. (/usr/lib/nodejs/request/main.js:212:58)
npm ERR! at Request.emit (events.js:88:20)
npm ERR! at ClientRequest. (/usr/lib/nodejs/request/main.js:412:12)
npm ERR! at ClientRequest.g (events.js:156:14)
npm ERR! at ClientRequest.emit (events.js:67:17)
npm ERR! at HTTPParser.parserOnIncomingClient as onIncoming
npm ERR! You may report this log at:
npm ERR! http://bugs.debian.org/npm
npm ERR! or use
npm ERR! reportbug --attach /home/pi/d3-tip/bower/npm-debug.log npm
npm ERR! 
npm ERR! System Linux 3.18.14-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "bower"
npm ERR! cwd /home/pi/d3-tip/bower
npm ERR! node -v v0.6.19
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: bower
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR! /home/pi/d3-tip/bower/npm-debug.log
npm not ok
```

any hints ?

**Comment by KenanY** [comment]
@chfakht Sorry, Node.js v0.6.19 is over 3 years old at this point and is no longer supported. Please try [upgrading Node.js](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-node) and [upgrading `npm`](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm).

**Comment by chfakht** [comment]
this is weird i have instaleld node-v0.12.7 NOT v0.5.19 .... however i was able to install it by adding sudo
"sudo npm install -g bower"

**Comment by othiym23** [comment]
Closing as resolved! You might want to take a look at your path, @chfakht -- it seems that maybe the version of Node you installed yourself went somewhere other than the version packaged by your OS distribution (hint: check both `/usr/bin/node` and `/usr/local/bin/node`). Either way, I'm glad you were able to get it worked out!

**Comment by chfakht** [comment]
i have /usr/local/bin and /usr/bin/nodejs 
@KenanY  yes you were right when running nodejs --version : v0.6.19 , but  i have download and install node-v0.12.7 from their official site .... maybe  because i'm using raspbian (in raspberry pi) !!!
