### ISSUE TITLE
install/postinstall script not running w/ cli arguments

### ISSUE THREAD

**Issue by th507** [npm/npm#9309]
Environment

io.js: 2.5.0
npm: 2.13.2
OS X

package.json: 

``` json
{
  "scripts": {
    "install": "npm ll"
  }
}
```
1. Run `npm install` yields

```
> @ install /Users/john/foo
> npm ll

@
│ /Users/john/foo
│
└── (empty)
```
1. However, run `npm install q` yields

```
q@1.4.1 node_modules/q
```

Clearly the user script for `install` is ignored.

Same happens for `preinstall`, `postinstall` and `pre/post/-uninstall` script.

When there are package name after the `npm install` command, the user script is then ignored.

Is there any reason why it behave like this?

**Comment by KenanY** [comment]
@th507 `npm --version`?

**Comment by th507** [comment]
Sorry, I forgot to include sys spec:

io.js: 2.5.0
npm: 2.13.2

**Comment by Nargonath** [comment]
@th507 If you have a pre/postinstall hook in your package.json they will be triggered when you install your package i.e. `npm install`. 

`npm install <package>` only triggers the pre/postinstall hook of that particular package not yours.
