### ISSUE TITLE
npm publish --help doesn't document --access

### ISSUE THREAD

**Issue by paulcbetts** [npm/npm#9312]
It'd be cool if `npm publish` doc'd `--access`, I always forget it

```
$ npm publish --help
npm publish <tarball> [--tag <tagname>]
npm publish <folder> [--tag <tagname>]

Publishes '.' if no argument supplied

Sets tag `latest` if no --tag specified

$ npm --version
2.10.1
```

**Comment by othiym23** [comment]
Hey Paul!

```
% npm publish --help
npm publish [<tarball>|<folder>] [--tag <tag>] [--access <public|restricted>]

Publishes '.' if no argument supplied

Sets tag `latest` if no --tag specified

% npm -v
2.14.0
```

We cleaned up the short help a few minor versions ago, so upgrade your npm and this should be taken care of. BTW, this is always kind of a balancing act, as some of the commands can take upwards of 30 different optional parameters, so if you get confused about how a command works, `npm help <command>` is probably the fastest way to get unconfused.

**Comment by paulcbetts** [comment]
@othiym23 :+1:, thanks for the super fast reply!

**Comment by othiym23** [comment]
No prob, you caught me in the middle of a triage pass. ;)
