### ISSUE TITLE
Progress bar broken with color=false

### ISSUE THREAD

**Issue by saper** [npm/npm#9313]
Our new progress bar (#6911) is totally broken with `color=false` in `.npmrc`. It really scared me off when I first tried npm@3

The "carriage return" sequences got removed and we got a 3D progress bar with the progress being logged in the time dimension behind the messages.

 Might be related to #8812

**Comment by iarna** [comment]
This is fixed with the new progress bar as of v3.10.0.

**Comment by saper** [comment]
Thank you!
