### ISSUE TITLE
node-gyp error: EACCES while installing i2c

### ISSUE THREAD

**Issue by pradhanshrijal** [npm/npm#9316]
Debian Wheezy
node: 0.12.7
node-gyp: 2.0.2
npm: 2.11.3

Help!!!!

![eacces error](https://cloud.githubusercontent.com/assets/11836341/9320866/1d551194-4589-11e5-8e4f-6ab02d4d590d.JPG)

**Comment by KenanY** [comment]
@pradhanshrijal 

> node: 0.12.7

Looks like you have two versions of Node.js installed: v0.9.9 and v0.12.7 (see log). I would first try getting rid of the 0.9 one, seeing as how 0.9 was the development branch that became the stable 0.10 over a year ago.

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.
