### ISSUE TITLE
npm install throws error

### ISSUE THREAD

**Issue by siju-irs** [npm/npm#9318]
Hi Team,
I am trying to clone cloud9, when i try npm install under cloud9 directory it throws the below error please help me for the same....!

```
root@dev-VirtualBox:/# cd ~/.cloud9 && npm install
npm WARN package.json cloud9@0.7.0 No license field.
npm WARN excluding symbolic link tests/public/smith.js -> ../../smith.js
npm WARN excluding symbolic link test/assets/symlink-dir/dir/symlink-dir -> ..
npm WARN excluding symbolic link tests/public/smith.js -> ../../smith.js
npm WARN excluding symbolic link test/assets/symlink-dir/dir/symlink-dir -> ..
-
> gnu-tools@0.0.8 postinstall /root/.cloud9/node_modules/jsDAV/node_modules/gnu-tools
> node ./install.js

npm ERR! Linux 3.16.0-30-generic
npm ERR! argv "/root/.nvm/versions/node/v0.12.7/bin/node" "/root/.nvm/versions/node/v0.12.7/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! gnu-tools@0.0.8 postinstall: `node ./install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gnu-tools@0.0.8 postinstall script 'node ./install.js'.
npm ERR! This is most likely a problem with the gnu-tools package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls gnu-tools
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.cloud9/npm-debug.log
```

**Comment by siju-irs** [comment]
i tried to use cloud9 v3 ... https://github.com/c9/core and followed the steps mentioned there. and when i try scripts/install-sdk.sh command it throws the below error.

> pty.js@0.2.7-1 install /root/.c9/node_modules/pty.js
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: spawn ENOENT
gyp ERR! stack     at errnoException (child_process.js:988:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:779:34)
gyp ERR! System Linux 3.16.0-30-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /root/.c9/node_modules/pty.js
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm ERR! Linux 3.16.0-30-generic
npm ERR! argv "/root/.c9/node/bin/node" "/root/.c9/node/bin/npm" "install" "pty.js@0.2.7-1"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.2.7-1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.2.7-1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.c9/npm-debug.log

**Comment by watilde** [comment]
Hmm... this is most likely a problem with the pty.js package like the log said. The following issue would be helpful for you:
https://github.com/c9/core/issues/109
