### ISSUE TITLE
SSL23_GET_SERVER_HELLO:unknown protocol

### ISSUE THREAD

**Issue by t-denis** [npm/npm#9320]
I am trying to build a ASP.NET Web App in Visual Studio 2015 and I'am getting errors during Grunt (or any other package) installation.
I am using Windows 7 and I didn't install NPM manually - it was provided by Visual Studio.
I don't have this issue at home - only at work, maybe our corporate proxy is somehow related to the issue.
And I can`t test workarounds provided for other issues, for example

> npm config set proxy http://proxy_host:port

because I don't know how to run it. Cmd replies that npm is unknown command and I can't find npm.exe on my drives.
There is a log from Visual Studio output window, thanks in advance:

```
npm WARN package.json MovieAngularJSApp@0.0.0 No description
npm WARN package.json MovieAngularJSApp@0.0.0 No repository field.
npm WARN package.json MovieAngularJSApp@0.0.0 No README data
npm http GET https://registry.npmjs.org/grunt
npm http GET https://registry.npmjs.org/grunt-contrib-uglify
npm http GET https://registry.npmjs.org/grunt-contrib-watch
npm http GET https://registry.npmjs.org/grunt-contrib-uglify
npm http GET https://registry.npmjs.org/grunt-contrib-watch
npm http GET https://registry.npmjs.org/grunt
npm http GET https://registry.npmjs.org/grunt-contrib-uglify
npm http GET https://registry.npmjs.org/grunt-contrib-watch
npm http GET https://registry.npmjs.org/grunt
```

====npm command completed with exit code 1====

```
npm ERR! Error: 9116:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:787:
npm ERR! 
npm ERR!     at SlabBuffer.use (tls.js:234:18)
npm ERR!     at CleartextStream.read [as _read] (tls.js:454:29)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:340:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:368:25)
npm ERR!     at doWrite (_stream_writable.js:225:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:215:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:182:11)
npm ERR!     at write (_stream_readable.js:601:24)
npm ERR!     at flow (_stream_readable.js:610:7)
npm ERR!     at Socket.pipeOnReadable (_stream_readable.js:642:5)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\IDE\\Extensions\\Microsoft\\Web Tools\\External\\\\node\\node" "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\IDE\\Extensions\\Microsoft\\Web Tools\\External\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\Dev\Temp\MovieAngularJSApp\src\MovieAngularJSApp
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.9
```

**Comment by othiym23** [comment]
Those are pretty old versions of Node and npm. I'm not sure exactly what the best way to update versions that are bundled with Visual Studio, but there is [a dedicated Windows upgrader](https://github.com/felixrieseberg/npm-windows-upgrade) you might want to try (or maybe see if that VS component has an upgrade?).

Once you've upgraded, you might want to try setting `HTTP_PROXY` or `HTTPS_PROXY` on your system (and then reboot). Newish versions of npm include a version of the `request` HTTP library that pick those settings up from the environment without having to mess with config files. Good luck!

**Comment by t-denis** [comment]
Thank you for your help.
Our proxy requires windows auth. Is there way to provide credentials only when required and not to store them in environment vars?
