### ISSUE TITLE
unable to install mongoose in expressgenerated app.

### ISSUE THREAD

**Issue by sarathmaddala** [npm/npm#9321]
Hi,

I was trying to use express generators and was able to create an app folder structure. But after that, I couldn't install mongoose in this folder structure.

I installed express-installer using below command.

>npm install -g express-generator

Then I used below to generate app.

>express -e todoApp

Then inside todoApp directory, I ran below.
>npm install mongoose --save 

Then the error comes and below is the log file I could get out of it.

Please help me understand what am I doing wrong.

```
0 info it worked if it ends with ok
1 verbose cli [ 'c:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'c:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'mongoose',
1 verbose cli   '--save' ]
2 info using npm@1.3.2
3 info using node@v0.10.13
4 error Error: Invalid name: "todoApp"
4 error     at ensureValidName (c:\Program Files (x86)\nodejs\node_modules\npm\node_modules\read-package-json\node_modules\normalize-package-data\lib\fixer.js:281:15)
4 error     at Object.module.exports.fixNameField (c:\Program Files (x86)\nodejs\node_modules\npm\node_modules\read-package-json\node_modules\normalize-package-data\lib\fixer.js:196:5)
4 error     at c:\Program Files (x86)\nodejs\node_modules\npm\node_modules\read-package-json\node_modules\normalize-package-data\lib\normalize.js:29:38
4 error     at Array.forEach (native)
4 error     at normalize (c:\Program Files (x86)\nodejs\node_modules\npm\node_modules\read-package-json\node_modules\normalize-package-data\lib\normalize.js:28:15)
4 error     at final (c:\Program Files (x86)\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:310:33)
4 error     at then (c:\Program Files (x86)\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:124:33)
4 error     at c:\Program Files (x86)\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:284:48
4 error     at fs.js:207:20
4 error     at Object.oncomplete (fs.js:107:15)
5 error If you need help, you may report this log at:
5 error     <http://github.com/isaacs/npm/issues>
5 error or email it to:
5 error     <npm-@googlegroups.com>
6 error System Windows_NT 6.1.7601
7 error command "c:\\Program Files (x86)\\nodejs\\node.exe" "c:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "mongoose" "--save"
8 error cwd c:\data\angularjs\todoApp
9 error node -v v0.10.13
10 error npm -v 1.3.2
11 verbose exit [ 1, true ]
```

Thank you,
Sarath

**Comment by KenanY** [comment]
@sarathmaddala Couple things:

1. Can't have an uppercase letter in the `"name"` field of your `package.json`
2. `npm@1.3` is very old and no longer supported. Please [upgrade](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows)

**Comment by sarathmaddala** [comment]
hi Thanks Kenyan, I will try to upgrade. For now, I ran "express -e todoapp" and it updated package.json with small letters.

**Comment by othiym23** [comment]
I'm going to close this as resolved, as @KenanY is right – new npm packages can't have names containing uppercase letters. He's also right that that version of npm is unsupported. The fastest way to get a newer npm is just to install the latest stable version of Node (which for now is 0.12.7). Good luck!
