### ISSUE TITLE
Jenkins suddenly freaking out

### ISSUE THREAD

**Issue by Protothor** [npm/npm#9323]
0 info it worked if it ends with ok
1 verbose cli [ '/home/webopt/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_11.13/bin/node',
1 verbose cli   '/home/webopt/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_11.13/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--loglevel',
1 verbose cli   'error' ]
2 info using npm@1.4.9
3 info using node@v0.11.13
4 verbose readDependencies using package.json deps
5 verbose install where, deps [ '/home/webopt/jenkins/jobs/npp-dev3-portal-resource-ux/workspace/src/main/webapp/portal-theme-css',
5 verbose install   [ 'grunt',
5 verbose install     'bootstrap-sass',
5 verbose install     'grunt-bless',
5 verbose install     'grunt-contrib-clean',
5 verbose install     'grunt-contrib-copy',
5 verbose install     'grunt-contrib-csslint',
5 verbose install     'grunt-contrib-cssmin',
5 verbose install     'grunt-sass' ] ]
6 info preinstall portal-theme@0.5.0
7 verbose readDependencies using package.json deps
8 verbose already installed skipping grunt-bless@0.1.1 /home/webopt/jenkins/jobs/npp-dev3-portal-resource-ux/workspace/src/main/webapp/portal-theme-css
9 verbose already installed skipping grunt-contrib-clean@0.6.0 /home/webopt/jenkins/jobs/npp-dev3-portal-resource-ux/workspace/src/main/webapp/portal-theme-css
10 verbose already installed skipping grunt-contrib-copy@0.5.0 /home/webopt/jenkins/jobs/npp-dev3-portal-resource-ux/workspace/src/main/webapp/portal-theme-css
11 verbose already installed skipping grunt-contrib-csslint@0.1.2 /home/webopt/jenkins/jobs/npp-dev3-portal-resource-ux/workspace/src/main/webapp/portal-theme-css
12 verbose already installed skipping grunt-contrib-cssmin@0.11.0 /home/webopt/jenkins/jobs/npp-dev3-portal-resource-ux/workspace/src/main/webapp/portal-theme-css
13 verbose cache add [ 'grunt-sass@~1.0.0', null ]
14 verbose cache add name=undefined spec="grunt-sass@~1.0.0" args=["grunt-sass@~1.0.0",null]
15 verbose parsed url { protocol: null,
15 verbose parsed url   slashes: null,
15 verbose parsed url   auth: null,
15 verbose parsed url   host: null,
15 verbose parsed url   port: null,
15 verbose parsed url   hostname: null,
15 verbose parsed url   hash: null,
15 verbose parsed url   search: null,
15 verbose parsed url   query: null,
15 verbose parsed url   pathname: 'grunt-sass@~1.0.0',
15 verbose parsed url   path: 'grunt-sass@~1.0.0',
15 verbose parsed url   href: 'grunt-sass@~1.0.0' }
16 verbose cache add name="grunt-sass" spec="~1.0.0" args=["grunt-sass","~1.0.0"]
17 verbose parsed url { protocol: null,
17 verbose parsed url   slashes: null,
17 verbose parsed url   auth: null,
17 verbose parsed url   host: null,
17 verbose parsed url   port: null,
17 verbose parsed url   hostname: null,
17 verbose parsed url   hash: null,
17 verbose parsed url   search: null,
17 verbose parsed url   query: null,
17 verbose parsed url   pathname: '~1.0.0',
17 verbose parsed url   path: '~1.0.0',
17 verbose parsed url   href: '~1.0.0' }
18 verbose addNamed [ 'grunt-sass', '~1.0.0' ]
19 verbose addNamed [ null, '>=1.0.0-0 <1.1.0-0' ]
20 verbose already installed skipping grunt@0.4.5 /home/webopt/jenkins/jobs/npp-dev3-portal-resource-ux/workspace/src/main/webapp/portal-theme-css
21 verbose already installed skipping bootstrap-sass@~3.3.5 /home/webopt/jenkins/jobs/npp-dev3-portal-resource-ux/workspace/src/main/webapp/portal-theme-css
22 silly lockFile e16de07a-grunt-sass-1-0-0 grunt-sass@~1.0.0
23 error Error: Attempt to unlock grunt-sass@~1.0.0, which hasn't been locked
23 error     at unlock (/home/webopt/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_11.13/lib/node_modules/npm/lib/cache.js:1434:11)
23 error     at cb (/home/webopt/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_11.13/lib/node_modules/npm/lib/cache.js:675:5)
23 error     at /home/webopt/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_11.13/lib/node_modules/npm/lib/cache.js:684:20
23 error     at /home/webopt/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_11.13/lib/node_modules/npm/lib/cache.js:1412:20
23 error     at afterMkdir (/home/webopt/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_11.13/lib/node_modules/npm/lib/cache.js:1085:14)
23 error     at /home/webopt/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_11.13/lib/node_modules/npm/node_modules/mkdirp/index.js:37:53
23 error     at Object.oncomplete (fs.js:97:15)
24 error If you need help, you may report this *entire* log,
24 error including the npm and node versions, at:
24 error     <http://github.com/npm/npm/issues>
25 error System Linux 2.6.18-398.el5
26 error command "/home/webopt/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_11.13/bin/node" "/home/webopt/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Node_11.13/bin/npm" "install" "--loglevel" "error"
27 error cwd /home/webopt/jenkins/jobs/npp-dev3-portal-resource-ux/workspace/src/main/webapp/portal-theme-css
28 error node -v v0.11.13
29 error npm -v 1.4.9
30 verbose exit [ 1, true ]

We've been using npm to handle all our front end builds on our Jenkins server for much longer than I've been an employee here.

Now, we consistently get these "Attempt to unlock <foo> which hasn't been locked" errors on every build.  It suddenly started Monday morning after months upon months of working properly.  We've tried clearing the global npm cache and starting anew, but to no avail.

Hopefully someone can help.  :smile:

**Comment by othiym23** [comment]
`npm@1.4.9` is well over a year old, and has a bunch of untreated race conditions and other gnarly synchronization bugs. Upgrade to `npm@latest` on your build host and this problem should go away. If you can't do that, either run `npm cache clean` or run `rm -rf "$HOME/.npm"` as the CI user on that host.
