### ISSUE TITLE
Allow ARGS on `login`

### ISSUE THREAD

**Issue by Fluidbyte** [npm/npm#9325]
The `npm login` feature (required for accessing private modules) requires interaction which is only scriptable with something like [expect](http://www.tcl.tk/man/expect5.31/expect.1.html). When using continuous integration or other scripted builds it would be beneficial to have either environment variables or flags (`npm login --user SomeUser --password SomePass`) available for automating authentication.

**Comment by othiym23** [comment]
Take a look at this [blog post](http://blog.getpiggybank.com/npm-private-modules-with-heroku/) for an example of how to pass npm credentials around safely in CI / PaaS environments.

The requirement for using an environment or a scripted login is there to remove a whole category of footguns that can be encountered by processes doing things like passing sensitive credentials on the command line in shared environments. I know it's a pain, but I still think it's a good idea.

**Comment by mitchdenny** [comment]
Hi guys - thanks for sharing this, I've gone down the ```.npmrc``` route for my project and it seems to be working OK. Is my understanding correct that if I change my NPM password that the CI builds will start failing and I'll have to replace the token?

**Comment by jefftucker** [comment]
@othiym23 The blog post you linked no longer exists and I'm having this exact issue and found this thread in response to searching for resolutions.  My CI server (Jenkins) spins up fresh docker containers for absolutely everything and I can pass in a file path to an .npmrc file easily enough (or settings in environment variables) but it would be helpful if somewhere there existed permanent documentation for how to set up an .npmrc file with credentials for publishing a package via CI.

**Comment by samward** [comment]
@jefftucker Try this: https://web.archive.org/web/20151020033842/http://blog.getpiggybank.com/npm-private-modules-with-heroku/
