### ISSUE TITLE
npm access expects package.json to be present

### ISSUE THREAD

**Issue by seldo** [npm/npm#9327]
A command like `npm access ls-packages seldo` does not have anything to do with a package, so npm shouldn't need a package.json to be present, but it's looking for one and throwing an error when it doesn't find it:

https://gist.github.com/seldo/532a75918eca88a6cd4f

Confirmed by @othiym23 and @iarna as a legit bug :-) Workaround is to run the command from any directory containing a package.json.

**Comment by othiym23** [comment]
This one may be fixed by some other changes that @iarna made in `npm@3` (most notably f4a578424b1f9d12f58210c229e7af633d952587 or 4468c92eccd0814b567606897e0792e49640e056), but I'll leave it to her to take a look.

**Comment by othiym23** [comment]
@iarna is going to investigate whether this has already been fixed.

**Comment by iarna** [comment]
This is still happening.

**Comment by iarna** [comment]
This also happens in npm@2, in fact, as far as I can tell it happens with any version of `npm access`.

**Comment by othiym23** [comment]
We landed and shipped a fix for this via 0e8b15e9fbc89e31bd00e573b648846beddfb835 in `npm@2.14.12`, and d7fb92d1c53ba5196ad6dd2101a06792a4c0412b for `npm@3.5.0`.
