### ISSUE TITLE
npm fails to install any package

### ISSUE THREAD

**Issue by pulkitnandan** [npm/npm#9330]
npm install -g yo
npm ERR! addLocal Could not install /home/ubuntu/yo
npm ERR! Linux 3.13.0-48-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "yo"
npm ERR! node v0.12.7
npm ERR! npm  v2.13.5

npm ERR! No version provided in package.json
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/npm-debug.log

NPM Debug Log

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', '-g', 'yo' ]
2 info using npm@2.13.5
3 info using node@v0.12.7
4 verbose install initial load of /usr/local/lib/package.json
5 verbose readDependencies loading dependencies from /usr/local/lib/package.json
6 silly cache add args [ 'yo', null ]
7 verbose cache add spec yo
8 silly cache add parsed spec { raw: 'yo',
8 silly cache add   scope: null,
8 silly cache add   name: null,
8 silly cache add   rawSpec: 'yo',
8 silly cache add   spec: '/home/ubuntu/yo',
8 silly cache add   type: 'directory' }
9 error addLocal Could not install /home/ubuntu/yo
10 verbose stack Error: No version provided in package.json
10 verbose stack     at /usr/local/lib/node_modules/npm/lib/cache/add-local.js:70:17
10 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:345:5
10 verbose stack     at checkBinReferences_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:309:45)
10 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:343:3)
10 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:113:5)
10 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:232:12
10 verbose stack     at evalmachine.<anonymous>:334:14
10 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/graceful-fs/graceful-fs.js:102:5
10 verbose stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
11 verbose cwd /home/ubuntu
12 error Linux 3.13.0-48-generic
13 error argv "node" "/usr/local/bin/npm" "install" "-g" "yo"
14 error node v0.12.7
15 error npm  v2.13.5
16 error No version provided in package.json
17 error If you need help, you may report this error at:
17 error     <https://github.com/npm/npm/issues>
18 verbose exit [ 1, true ]
~

**Comment by iamstarkov** [comment]
can you describe your environment?

**Comment by pulkitnandan** [comment]
Sorry, I couldn't waited more to be stuck on npm install so I reinstalled Os, It works fine now. Yeah environment must have been an issue.
