### ISSUE TITLE
`npm install --save git://github.com/{user}/{plugin}.git` writes local path to package.json on Windows

### ISSUE THREAD

**Issue by tensorproduct** [npm/npm#9331]
I'm encountering a problem where, on Windows, using `npm install --save` to update `package.json` for a dependency from a github repo leads creates a dependency from a local path in AppData.

```
npm install --save git://github.com/jgable/gulp-cache.git
```

creates an entry in `package.json` that looks like:

```
  "dependencies": {
...
    "gulp-cache": "file:..\\..\\AppData\\Local\\Temp\\npm-14068-4106a94c\\git-cache-32d76db21c11\\94354b7c03d09dd86fbe46d189659959ee940860",
...
}
```

Whereas the same operation in Linux creates an entry like:

```
  "dependencies": {
...
    "gulp-cache": "git://github.com/jgable/gulp-cache.git",
...
}
```

The latter is what I would expect in both environments.

This looks like a bug to me. Or is this expected behaviour? I see similar AppData paths appear if I use shrinkwrap in Windows. This makes it difficult to share development of packages between multiple OSes.

**Comment by KenanY** [comment]
@tensorproduct `npm --version`?

**Comment by tensorproduct** [comment]
Aha, upgrading on Windows from 2.5.1 to 2.13.4 (using `npm install -g npm-windows-upgrade`) resolves this problem. Thanks.
