### ISSUE TITLE
Cannot `nmp install -g` from private git repository

### ISSUE THREAD

**Issue by Alber70g** [npm/npm#9332]
So basically the title. Whenever I try to do this, it failes and I get the error shown below.

```npm install -g git+http://<servername>:8080/tfs/RTD/TTS/_git/generator-ngtts```

I can however do the command mentioned below (which said is failed), when running myself from the command line. Anyone has any clue about what's happening here?
```
git -c core.longpaths=true clone --template=C:\Users\<username>\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror http://<servername>:8080/tfs/RTD/TTS/_git/generator-ngtts C:\Users\<username>\AppData\Roaming\npm-cache\_git-remotes\http-<servername>-8080-tfs-RTD-TTS-git-generator-ngtts-42fbf3f9
```

npm-debug.log: https://gist.github.com/Alber70g/882ab977cb31e928a855

```bash
$ npm install -g git+http://<servername>:8080/tfs/RTD/TTS/_git/generator-ngtts
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:751:12)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:110:17)
npm WARN addRemoteGit     at maybeClose (child_process.js:1015:16)
npm WARN addRemoteGit     at Socket.<anonymous> (child_process.js:1183:11)
npm WARN addRemoteGit     at Socket.emit (events.js:107:17)
npm WARN addRemoteGit     at Pipe.close (net.js:485:12)
npm WARN addRemoteGit  git+http://<servername>:8080/tfs/RTD/TTS/_git/generator-ngtts resetting remote C:\Users\<username>\AppData\Roaming\npm-cache\_git-remotes\http-<servername>-8080-tfs-RTD-TTS-git-generator-ngtts-42fbf3f9 because of error: { [Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! git clone --template=C:\Users\<username>\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror http://<servername>:8080/tfs/RTD/TTS/_git/generator-ngtts C:\Users\<username>\AppData\Roaming\npm-cache\_git-remotes\http-<servername>-8080-tfs-RTD-TTS-git-generator-ngtts-42fbf3f9: Cloning into bare repository 'C:\Users\<username>\AppData\Roaming\npm-cache\_git-remotes\http-<servername>-8080-tfs-RTD-TTS-git-generator-ngtts-42fbf3f9'...
npm ERR! git clone --template=C:\Users\<username>\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror http://<servername>:8080/tfs/RTD/TTS/_git/generator-ngtts C:\Users\<username>\AppData\Roaming\npm-cache\_git-remotes\http-<servername>-8080-tfs-RTD-TTS-git-generator-ngtts-42fbf3f9: fatal: Authentication failed for 'http://<servername>:8080/tfs/RTD/TTS/_git/generator-ngtts/'
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "git+http://<servername>:8080/tfs/RTD/TTS/_git/generator-ngtts"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\<username>\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror http://<servername>:8080/tfs/RTD/TTS/_git/generator-ngtts C:\Users\<username>\AppData\Roaming\npm-cache\_git-remotes\http-<servername>-8080-tfs-RTD-TTS-git-generator-ngtts-42fbf3f9
npm ERR! Cloning into bare repository 'C:\Users\<username>\AppData\Roaming\npm-cache\_git-remotes\http-<servername>-8080-tfs-RTD-TTS-git-generator-ngtts-42fbf3f9'...
npm ERR! fatal: Authentication failed for 'http://<servername>:8080/tfs/RTD/TTS/_git/generator-ngtts/'
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files\Git\npm-debug.log
```

**Comment by iamstarkov** [comment]
> -c \<key\>=\<value\>

>    Set a configuration variable in the newly-created repository; this takes effect immediately after the repository is initialized, but before the remote history is fetched or any files checked out. The key is in the same format as expected by git-config(1) (e.g., core.eol=true). If multiple values are given for the same key, each value will be written to the config file. This makes it safe, for example, to add additional fetch refspecs to the origin remote.


 > --template=\<template_directory\>

>    Specify the directory from which templates will be used; (See the "TEMPLATE DIRECTORY" section of git-init(1).)

> --mirror

>    Set up a mirror of the source repository. This implies --bare. Compared to --bare, --mirror not only maps local branches of the source to local branches of the target, it maps all refs (including remote-tracking branches, notes etc.) and sets up a refspec configuration such that all these refs are overwritten by a git remote update in the target repository.

**Comment by othiym23** [comment]
There was some churn in the npm codebase related to our git support between `npm@2.10` and `npm@2.14`. I'm pretty sure it's landed at a happy place now, so can you tell me if [upgrading npm](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) to the latest version addresses this for you?

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some issues. Hopefully upgrading npm work, but if this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.

**Comment by Alber70g** [comment]
Hello, I'm sorry to dig up this old question, but it's still relevant. The problem here is NOT that the command failed in either of the versions. 

The problem is `fatal: Authentication failed for 'http://<servername>:8080/tfs/RTD/TTS/_git/generator-ngtts/'`. I think the problem is that it cannot authenticate with the TFS server, because it's using NTLM. Is there a way to overcome this?

**Comment by chaim1221** [comment]
There was another [issue](https://github.com/npm/npm/issues/7557) related to this, in which @othiym23 suggested installing `cntlm`. I'm not sure I want to recommend this to my whole team, nor support errors with the installation of it, especially when the linked article there uses XP SP3 as their test OS (we're on Windows 10).

This is still an issue on Windows. Should I open a new issue?

We're probably going to end up setting up an npm repository s/a [Sinopia](https://www.npmjs.com/package/sinopia) to deal with this problem, but it would be really nice if Windows npm supported NTLM/Kerberos OOTB instead. :-/

**Comment by othiym23** [comment]
@chaim1221 Opening a new issue isn't likely to do much for you, because how npm interacts with proxies using NTLM / ActiveDirectory / Kerberos auth doesn't have much room for improvement. `cntlm` is necessary because Kerberos ticketing more or less requires natively-linked modules (i.e. modules with a piece written in C++, which get linked against DLLs that implement the fairly complicated Kerberos protocol). npm needs to remain pure JavaScript so that it can install and bootstrap itself in a platform-neutral way, so this particular piece of it kind of has to remain external. I know this is a pain, but tight integration with the operating system is part of how Kerberos guarantees security. Reimplementing that in pure Node (without native dependencies) is somewhere between deeply painful and impossible.

Keep in mind that none of this has anything to do with dependencies hosted on Git. For Git-based dependencies, the CLI calls out to Git commands, and [as far as I can tell](http://stackoverflow.com/questions/5060437/configuring-git-on-windows-to-use-ntlm-proxy-authentication), Git also has the exact same problem, and also requires the use of `cntlm` for proxying.

An alternative to Sinopia is [`npm Enterprise`](https://www.npmjs.com/enterprise), which supports being set up in mirror, read-through, or whitelist mode, and also supports custom auth support, which should make it possible to integrate into a Windows-only network. In mirroring or read-through mode, you would connect to the local npmE instance, and only it would have to be proxied through to the internet, which would simplify things a lot.

**Comment by chaim1221** [comment]
Thank you @othiym23 for the tip. I notice that npmE isn't free software, though, and Sinopia is (so is [reggie](https://github.com/mbrevoort/node-reggie), apparently). There's also the [Microsoft Git credential managager](https://github.com/Microsoft/Git-Credential-Manager-for-Windows) apparently, going to give that a go.
