### ISSUE TITLE
Help please I can't install cordova with npm

### ISSUE THREAD

**Issue by hafedh002** [npm/npm#9334]
this is the error message in cmd:

Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\Hafeedh>npm install -g cordova
npm http GET https://registry.npmjs.org/cordova
npm http 304 https://registry.npmjs.org/cordova
npm http GET https://registry.npmjs.org/cordova-lib/5.2.0
npm http GET https://registry.npmjs.org/q/1.0.1
npm http GET https://registry.npmjs.org/nopt/3.0.1
npm http GET https://registry.npmjs.org/underscore/1.7.0
npm http 304 https://registry.npmjs.org/q/1.0.1
npm http 304 https://registry.npmjs.org/nopt/3.0.1
npm http 304 https://registry.npmjs.org/cordova-lib/5.2.0
npm http 304 https://registry.npmjs.org/underscore/1.7.0
npm http GET https://registry.npmjs.org/abbrev
npm http GET https://registry.npmjs.org/cordova-js/4.1.0
npm http GET https://registry.npmjs.org/bplist-parser/0.0.6
npm http GET https://registry.npmjs.org/cordova-app-hello-world/3.9.0
npm http GET https://registry.npmjs.org/aliasify
npm http GET https://registry.npmjs.org/cordova-serve
npm http GET https://registry.npmjs.org/cordova-registry-mapper
npm http GET https://registry.npmjs.org/dep-graph/1.1.0
npm http GET https://registry.npmjs.org/elementtree/0.1.6
npm http GET https://registry.npmjs.org/glob/4.0.6
npm http GET https://registry.npmjs.org/init-package-json
npm http GET https://registry.npmjs.org/npmconf
npm http GET https://registry.npmjs.org/npm
npm http GET https://registry.npmjs.org/osenv/0.1.0
npm http GET https://registry.npmjs.org/plist/1.1.0
npm http GET https://registry.npmjs.org/request/2.47.0
npm http GET https://registry.npmjs.org/rc/0.5.2
npm http GET https://registry.npmjs.org/unorm/1.3.3
npm http GET https://registry.npmjs.org/properties-parser/0.2.3
npm http GET https://registry.npmjs.org/shelljs/0.3.0
npm http GET https://registry.npmjs.org/semver
npm http GET https://registry.npmjs.org/valid-identifier/0.0.1
npm http GET https://registry.npmjs.org/tar/1.0.2
npm http GET https://registry.npmjs.org/xcode/0.8.0
npm http 304 https://registry.npmjs.org/abbrev
npm http 304 https://registry.npmjs.org/cordova-serve
npm http 304 https://registry.npmjs.org/cordova-registry-mapper
npm http 304 https://registry.npmjs.org/aliasify
npm http 304 https://registry.npmjs.org/bplist-parser/0.0.6
npm http 304 https://registry.npmjs.org/dep-graph/1.1.0
npm ERR! Error: No compatible version found: cordova-serve@'^0.1.2'
npm ERR! Valid install targets:
npm ERR! ["0.1.0","0.1.1","0.1.2"]
npm ERR!     at installTargetsError (C:\Program Files\nodejs\node_modules\npm\li
b\cache.js:719:10)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\lib\cache.js:638:10
npm ERR!     at saved (C:\Program Files\nodejs\node_modules\npm\node_modules\npm
-registry-client\lib\get.js:142:7)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-f
s\polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
npm ERR! cwd C:\Users\Hafeedh
npm ERR! node -v v0.10.15
npm ERR! npm -v 1.3.5
npm http 304 https://registry.npmjs.org/elementtree/0.1.6
npm http 304 https://registry.npmjs.org/init-package-json
npm http 304 https://registry.npmjs.org/npmconf
npm http 304 https://registry.npmjs.org/npm
npm http 304 https://registry.npmjs.org/cordova-js/4.1.0
npm http 304 https://registry.npmjs.org/cordova-app-hello-world/3.9.0
npm http 304 https://registry.npmjs.org/glob/4.0.6
npm http 304 https://registry.npmjs.org/osenv/0.1.0
npm http 304 https://registry.npmjs.org/plist/1.1.0
npm http 304 https://registry.npmjs.org/properties-parser/0.2.3
npm http 304 https://registry.npmjs.org/rc/0.5.2
npm http 304 https://registry.npmjs.org/unorm/1.3.3
npm http 304 https://registry.npmjs.org/request/2.47.0
npm http 304 https://registry.npmjs.org/semver
npm http 304 https://registry.npmjs.org/shelljs/0.3.0
npm http 304 https://registry.npmjs.org/tar/1.0.2
npm http 304 https://registry.npmjs.org/valid-identifier/0.0.1
npm http 304 https://registry.npmjs.org/xcode/0.8.0
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\Hafeedh\npm-debug.log
npm ERR! not ok code 0

C:\Users\Hafeedh>

**Comment by iamstarkov** [comment]
try again. cannot reproduce. considering closing

**Comment by hafedh002** [comment]
I tired but it is the same problem
Is there another way of installation
for example with a zip file cordova

**Comment by iamstarkov** [comment]
can you describe you environment?

**Comment by iamstarkov** [comment]
also you can try help here https://git-wip-us.apache.org/repos/asf?p=cordova-cli.git

**Comment by hafedh002** [comment]
if someone gives me cordova.zip and ionic.zip
please

**Comment by lukeapage** [comment]
@hafedh002 you are using an old version of npm and I suspect the problem is that it does not support the `^` identifier. Upgrade npm or upgrade node.js which will update your npm.

**Comment by hafedh002** [comment]
@lukeapage I chose this version to properly install Ionic cleanly.
ok i install the latest version of node js with npm updated and then cordova Ionic and this is the message in cmd
I ask is that the "Warns" make me bugs in the future.


 Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\Hafeedh>cordova -v
5.2.0

C:\Users\Hafeedh>npm install -g ionic
npm WARN engine cordova-js@4.0.0: wanted: {"node":"~0.10.x"} (current: {"node":"
0.12.7","npm":"2.11.3"})
npm WARN engine npm@1.3.4: wanted: {"node":">=0.6","npm":"1"} (current: {"node":
"0.12.7","npm":"2.11.3"})
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {
"node":"0.12.7","npm":"2.11.3"})
npm WARN installMany normalize-package-data was bundled with npm@1.3.4, but bund
led package wasn't found in unpacked tree
C:\usr\local\ionic -> C:\usr\local\node_modules\ionic\bin\ionic
ionic@1.6.4 C:\usr\local\node_modules\ionic
├── proxy-middleware@0.7.0
├── connect-livereload@0.5.2
├── progress@1.1.7
├── colors@0.6.2
├── open@0.0.5
├── underscore@1.7.0
├── ncp@0.4.2
├── crc@3.2.1
├── q@1.0.1
├── async@0.9.2
├── shelljs@0.2.6
├── semver@4.3.6
├── cross-spawn@0.2.3 (lru-cache@2.6.5)
├── cli-table@0.3.1 (colors@1.0.3)
├── npm@2.1.3
├── finalhandler@0.2.0 (escape-html@1.0.1, debug@2.0.0)
├── connect@3.1.1 (utils-merge@1.0.0, parseurl@1.3.0, debug@1.0.4, finalhandler@
0.1.0)
├── event-stream@3.0.20 (stream-combiner@0.0.4, duplexer@0.1.1, from@0.1.3, paus
e-stream@0.0.11, split@0.2.10, through@2.3.8, map-stream@0.0.6)
├── form-data@0.1.4 (mime@1.2.11, combined-stream@0.0.7)
├── optimist@0.6.0 (wordwrap@0.0.3, minimist@0.0.10)
├── opbeat-ionic@1.1.3 (console-log-level@1.1.0, json-stringify-safe@5.0.1, stac
kman@0.2.3, after-all@2.0.2)
├── serve-static@1.7.1 (utils-merge@1.0.0, escape-html@1.0.1, parseurl@1.3.0, se
nd@0.10.1)
├── tiny-lr-fork@0.0.5 (debug@0.7.4, faye-websocket@0.4.4, qs@0.5.6, noptify@0.0
.3)
├── request@2.51.0 (caseless@0.8.0, aws-sign2@0.5.0, forever-agent@0.5.2, string
stream@0.0.4, oauth-sign@0.5.0, tunnel-agent@0.4.1, json-stringify-safe@5.0.1, q
s@2.3.3, node-uuid@1.4.3, mime-types@1.0.2, combined-stream@0.0.7, http-signatur
e@0.10.1, bl@0.9.4, tough-cookie@2.0.0, form-data@0.2.0, hawk@1.1.1)
├── unzip@0.1.9 (setimmediate@1.0.2, pullstream@0.4.1, readable-stream@1.0.33, m
atch-stream@0.0.2, binary@0.3.0, fstream@0.1.31)
├── prompt@0.2.12 (revalidator@0.1.8, pkginfo@0.3.0, read@1.0.6, winston@0.6.2,
utile@0.2.1)
├── xml2js@0.4.4 (sax@0.6.1, xmlbuilder@2.6.4)
├── vinyl-fs@0.3.7 (graceful-fs@3.0.8, strip-bom@1.0.0, vinyl@0.4.6, mkdirp@0.5.
1, through2@0.6.5, glob-stream@3.1.18, lodash@2.4.2, glob-watcher@0.0.6)
├── cheerio@0.19.0 (entities@1.1.1, lodash@3.10.0, dom-serializer@0.1.0, css-sel
ect@1.0.0, htmlparser2@3.8.3)
├── gulp@3.8.8 (pretty-hrtime@0.2.2, interpret@0.3.10, deprecated@0.0.1, archy@0
.0.2, minimist@1.1.2, tildify@1.1.0, semver@3.0.1, chalk@0.5.1, orchestrator@0.3
.7, liftoff@0.12.1, gulp-util@3.0.6)
└── ionic-app-lib@0.3.8 (vinyl-fs@1.0.0, archiver@0.5.2, ionic-cordova-lib@5.1.7
)

C:\Users\Hafeedh>

**Comment by iamstarkov** [comment]
> I ask is that the "Warns" make me bugs in the future.

what node and npm versions are you using?

**Comment by hafedh002** [comment]
i use the latest version of node and npm

npm -> 2.11.3
node -> 0.12.7

**Comment by iamstarkov** [comment]
> npm WARN engine cordova-js@4.0.0: wanted: {"node":"~0.10.x"} (current: {"node":"
0.12.7","npm":"2.11.3"})
npm WARN engine npm@1.3.4: wanted: {"node":">=0.6","npm":"1"} (current: {"node":
"0.12.7","npm":"2.11.3"})
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {
"node":"0.12.7","npm":"2.11.3"})
npm WARN installMany normalize-package-data was bundled with npm@1.3.4, but bund
led package wasn't found in unpacked tree

latest version of cordova is 5.2.0 and not 4.0, try latest cordova versions


PS. npm is not latest, though

**Comment by lukeapage** [comment]
Yes, it seems cordova specifies a 0.10 version of node.
```
npm WARN engine cordova-js@4.0.0: wanted: {"node":"~0.10.x"} (current: {"node":"
0.12.7","npm":"2.11.3"})
npm WARN engine npm@1.3.4: wanted: {"node":">=0.6","npm":"1"} (current: {"node":
"0.12.7","npm":"2.11.3"})
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {
"node":"0.12.7","npm":"2.11.3"})
```
they have removed that requirement: https://github.com/apache/cordova-js/commit/d5b716cc73fa2f09ac1a1090cefecec5019676ea

either: 
1. ignore the warning, it is very unlikely to go wrong
2. install the latest node 0.10.x version and then upgrade npm with `npm i npm@2 -g` (though search around for help, it isn't straight forward in windows at the moment)

**Comment by hafedh002** [comment]
so i think it's good now i have

C:\Users\Hafeedh>npm -v
2.11.3

C:\Users\Hafeedh>node -v
v0.12.7

C:\Users\Hafeedh>cordova -version
5.2.0

**Comment by iamstarkov** [comment]
if you fine, can you close issue then?

**Comment by hafedh002** [comment]
thinks for all :)
