### ISSUE TITLE
feature request: Default installs of 0.x version packages to not use `^`

### ISSUE THREAD

**Issue by lukeapage** [npm/npm#9336]
Searching for something like this, I found [an informative comment](https://github.com/npm/npm/issues/6768#issuecomment-64726706), written by @othiym23, from which I'll quote..

> semver treats 0.x versions as a sandbox of sorts, where breaking changes can happen at any time.

and

> As the node-semver docs say, for 0.x.y and 0.0.x versions, x is effectively the major version as far as breaking changes are concerned.

Proposal:
 * npm install module where module < 1, inserts the actual version without the `^`
 * npm install module where module >= 1, behaves as it does currently

Motivation:
* a 0.0.x change can be breaking, so effectively "^1.0.0" and "0.0.1" are as safe as each other when the project is following semver
* you want to encourage users to use 1.0.0

(from the same comment)

 > All of these caveats around 0.x are indeed pretty weird, which is why npm init / init-package-json now defaults to 1.0.0 as the initial version of packages, because everything behaves much more sensibly once you're at major version 1 or higher.

* This would help educate users that if they are using a v0 package, it is not considered stable. This in turn should hopefully trickle down to package authors which will then bump to v1 once the API is considered stable.

**Comment by lukeapage** [comment]
@ColinEberhardt this was inspired by your tweet

**Comment by othiym23** [comment]
We tried changing `^` to have these semantics, in `semver@3`, and the results were really inflexible and hostile to people building end-user apps consuming libraries using this syntax. As such, as confusing as pre-1.0.0 versions can be, we're pretty much committed to the current behavior. Thanks for putting this together!

**Comment by lukeapage** [comment]
Thanks for considering it, I understand your position..  Maybe I need to move to start hassling pre-1.0.0 modules that are stable to bump their version.

**Comment by ColinEberhardt** [comment]
Perhaps you need to start a campaign like this one http://24pullrequests.com - but instead focus on getting people to bump versions :-)
