### ISSUE TITLE
npm update -g is still broken?

### ISSUE THREAD

**Issue by ChicagoDev** [npm/npm#9337]
As requested by @iarna I am opening a new issue, because I have reproduced issue [#4099](https://github.com/npm/npm/issues/4099) with npm version 2.11.3

While attempting to globally update my packages with npm, I encountered an error:

    bjg% npm --version                                                                                             ~
    2.11.3

    bjg% npm update -g                                                                                             ~
    npm ERR! Darwin 14.4.0
    npm ERR! argv "node" "/usr/local/bin/npm" "update" "-g"
    npm ERR! node v0.12.7
    npm ERR! npm  v2.11.3
    npm ERR! path /usr/local/lib/node_modules/npm/bin/node-gyp-bin
    npm ERR! code EACCES
    npm ERR! errno -13

    npm ERR! Error: EACCES, rmdir '/usr/local/lib/node_modules/npm/bin/node-gyp-bin'
    npm ERR!     at Error (native)
    npm ERR!  { [Error: EACCES, rmdir '/usr/local/lib/node_modules/npm/bin/node-gyp-bin']
    npm ERR!   errno: -13,
    npm ERR!   code: 'EACCES',
    npm ERR!   path: '/usr/local/lib/node_modules/npm/bin/node-gyp-bin' }
    npm ERR! 
    npm ERR! Please try running this command again as root/Administrator.
    npm ERR! error rolling back Error: EACCES, rmdir '/usr/local/lib/node_modules/npm/bin/node-gyp-bin'
    npm ERR! error rolling back     at Error (native)
    npm ERR! error rolling back  { [Error: EACCES, rmdir '/usr/local/lib/node_modules/npm/bin/node-gyp-bin']
    npm ERR! error rolling back   errno: -13,
    npm ERR! error rolling back   code: 'EACCES',
    npm ERR! error rolling back   path: '/usr/local/lib/node_modules/npm/bin/node-gyp-bin' }

    npm ERR! Please include the following file with any support request:
    npm ERR!     /Users/bjg/npm-debug.log

Subsequently, when I attempted to run `npm update -g`:
    
    bjg% npm update -g                                                                                             ~
    zsh: command not found: npm

I did not attempt to run `npm update -g` with `sudo`, because most of the documentation online warns that using sudo with npm causes lots of issues. However, if someone from NPM can definitively answer that `sudo` is safe to use with `npm update -g` on OS X, or all platforms, I'd like to submit a patch to the official docs [updating-global-packages.md](https://docs.npmjs.com/getting-started/updating-global-packages) if you'd give me the go ahead.

**Comment by ramya4689** [comment]
imnt able to run npm command in my cmd. 
![node_error](https://cloud.githubusercontent.com/assets/13942713/9437772/62ff6cc0-4a76-11e5-8bd3-659cc061cf36.PNG)

**Comment by mateatslc** [comment]
mine :poop:'ed out too on `npm install -g npm@latest` recently

**Comment by othiym23** [comment]
@ChicagoDev 

```
npm ERR! Error: EACCES, rmdir '/usr/local/lib/node_modules/npm/bin/node-gyp-bin'
```

indicates that you need to run `npm update -g` prefixed with `sudo`, or perhaps run `sudo chown $(whoami) -R /usr/local/lib/node_modules/npm`. You have some files owned by root, and that's causing npm to explode when it tries to upgrade itself when run as not-root.

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some issues. Did changing ownership of those files alleviate the `EACCES` errors? If not and this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.

**Comment by mateatslc** [comment]
No need to reopen, as per my recent investigation my problem is really this #5050
