### ISSUE TITLE
Updating to “atom-beautify@0.28.11” failed

### ISSUE THREAD

**Issue by ama4tf** [npm/npm#9341]
Error output

     spawn-sync@1.0.13 postinstall C:\Users\ALEX~1.ABE\AppData\Local\Temp\apm-install-dir-115719-3104-z966dh\node_modules\atom-beautify\node_modules\cross-spawn\node_modules\spawn-sync
     > node postinstall

     Installing native dependencies (this may take up to a minute)

     npm ERR! tar.unpack error reading C:\Users\alex.aberman\.atom\.apm\js-yaml\3.2.7\package.tgz
     npm ERR! Windows_NT 6.1.7601
     npm ERR! argv "C:\\Users\\alex.aberman\\AppData\\Local\\atom\\app-1.0.7\\resources\\app\\apm\\bin\\\\node.exe" "C:\\Users\\alex.aberman\\AppData\\Local\\atom\\app-1.0.7\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\alex.aberman\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\alex.aberman\\.atom\\.apmrc" "install" "C:\\Users\\ALEX~1.ABE\\AppData\\Local\\Temp\\d-115719-3104-ph2qxv\\package.tgz" "--target=0.22.0" "--arch=ia32"
     npm ERR! node v0.10.35
     npm ERR! npm  v2.5.1
     npm ERR! code EBADF
     npm ERR! errno 9

     npm ERR! EBADF, fstat
     npm ERR! 
     npm ERR! If you need help, you may report this error at:
     npm ERR!     <http://github.com/npm/npm/issues>

**Comment by KenanY** [comment]
@ama4tf from https://github.com/npm/npm/issues/7472#issuecomment-76510381:

> EBADF is a bad file descriptor; and this error is coming from `node` without going through a javascript stack trace. So my first suggestion would just be to reboot and try again, on the possibility that there's something weird with your filesystem.

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.
