### ISSUE TITLE
npm search doesn't work

### ISSUE THREAD

**Issue by polkovnikov-ph** [npm/npm#9346]
Local index doesn't build when I run e.g.

	npm search browserify

npm-debug.log
	
	0 info it worked if it ends with ok
	1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
	1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
	1 verbose cli   'search',
	1 verbose cli   'browserify' ]
	2 info using npm@2.0.0
	3 info using node@v0.11.15
	4 verbose node symlink C:\Program Files\nodejs\\node.exe
	5 verbose mapToRegistry name -/all
	6 verbose mapToRegistry uri https://registry.npmjs.org/-/all
	7 info get C:\Users\Не Зоя\AppData\Roaming\npm-cache\registry.npmjs.org\-\all/.cache.json
	8 warn Building the local index for the first time, please be patient
	9 verbose request on initialization, where is /-/all
	10 verbose request after pass 1, where is /-/all
	11 verbose request url raw /-/all
	12 verbose request resolving registry [ 'https://registry.npmjs.org/-/all', './-/all' ]
	13 verbose request after pass 2, where is https://registry.npmjs.org/-/-/all
	14 verbose request no auth needed
	15 info attempt registry request try #1 at 02:08:02
	16 verbose request id 9f2f6c0761858f39
	17 http request GET https://registry.npmjs.org/-/-/all
	18 http 500 https://registry.npmjs.org/-/-/all
	19 verbose stack TypeError: Object.keys called on non-object
	19 verbose stack     at Function.keys (native)
	19 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\get.js:96:12
	19 verbose stack     at f (C:\Program Files\nodejs\node_modules\npm\node_modules\once\once.js:16:25)
	19 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:107:16
	19 verbose stack     at f (C:\Program Files\nodejs\node_modules\npm\node_modules\once\once.js:16:25)
	19 verbose stack     at RegClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:277:12)
	19 verbose stack     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:198:65)
	19 verbose stack     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:236:22)
	19 verbose stack     at Request.emit (events.js:110:17)
	19 verbose stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1142:14)
	20 verbose cwd D:\heroku\erp\tools
	21 error Windows_NT 6.1.7601
	22 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "search" "browserify"
	23 error node v0.11.15
	24 error npm  v2.0.0
	25 error Object.keys called on non-object
	26 error If you need help, you may report this error at:
	26 error     <http://github.com/npm/npm/issues>
	27 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@polkovnikov-ph Does this also occur if you use a stable version of Node.js? How about if you [upgrade `npm`](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows) as well?

**Comment by othiym23** [comment]
Please do try using a current version of Node as well as a newer version of npm – that version of npm is nearly a year old, and there's a lot of flakiness in the TLS code in Node 0.11.

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.
