### ISSUE TITLE
please delete npm-debug.log and forget that idea ever existed

### ISSUE THREAD

**Issue by andrewrk** [npm/npm#9347]
Hello. Upstream maintainer here.

npm-debug.log is worthless. In fact, it's worse than worthless, because users paste it, thinking that it contains something valuable for me to troubleshoot their problem, but it does not contain anything valuable in it, it contains a bunch of bullshit nonsense that does not help at all. All I want is users to paste the goddamn stdio from the actual program, and npm's job is to just put some node modules in the PATH env variable and then get out of the goddamn way.

I can't escape from it, even users who are smart enough to delete or otherwise ignore it make [pull requests](https://github.com/andrewrk/groovebasin/pull/466) to add it to .gitignore. I don't want that shit in .gitignore, because then I wouldn't know when it was on my hard drive, so I could delete it and then scrub the bits clean just to feel better about how deleted it is.

**Comment by othiym23** [comment]
Hi! Thanks for the feedback!

`npm-debug.log` may be useless and an annoyance to you, but it is the single most valuable troubleshooting resource available to the npm CLI team, npm's OSS contributors helping users debug their own issues, and npm, Inc's support team. As such, it's going to stick around, at least in some form. You may want to take a look at #6744, which is on [the npm roadmap](https://github.com/npm/npm/wiki/Roadmap) and waiting for us (or an enterprising outside contributor) to have a few cycles to implement it. That, plus #7611 and #6756, should make it less likely to get in your way.

**Comment by andrewrk** [comment]
thanks. putting it in the cache folder would be a step in the right direction.

**Comment by andrewrk** [comment]
I'll just leave this here: https://github.com/andrewrk/groovebasin/issues/467

**Comment by andrewrk** [comment]
again: https://github.com/andrewrk/groovebasin/issues/474

**Comment by bozdoganCihangir** [comment]
rm -rf npm-debug.log*           it became the first command when i log in to server lol
