### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by shirleymolomo** [npm/npm#9353]
MS BUILD: ERROR MSB3428:could not load the visual c++ component "VCBUILD.exe" to fix this 1) install the .NET framework 2.0 SDK(which i did)

**Comment by KenanY** [comment]
@shirleymolomo There's not a lot of detail in your report so I cannot say for sure what will solve your issue, but it appears as though that error message is _not_ coming from `npm` itself. I would first ensure that you have all of [`node-gyp`'s dependencies](https://github.com/nodejs/node-gyp#installation) if you are going to be building native addons.

If anything, uploading a `npm-debug.log` as a [gist](https://gist.github.com/) can go a long way towards finding a solution for your problem.

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.
