### ISSUE TITLE
browserDependencies

### ISSUE THREAD

**Issue by monolithed** [npm/npm#9354]
> @othiym23 
There is discussion of a new browserDependencies (name not final, almost certain to change, don't hold us to this, etc.) dependency type to to handle dependencies that are guaranteed to be flat and that will error on conflicts, which may or may not install to somewhere other than node_modules, but this is not generally desirable behavior for regular npm dependencies, configurably or otherwise. Regardless of its eventual semantics, it will not be part of the npm@3 release.

There're many different solutions:

[spm](http://spmjs.io/)
[jam](http://jamjs.org/)
[bower](http://bower.io/)
[component](https://github.com/componentjs/component)
[volo](http://volojs.org/)
[broccoli](https://github.com/broccolijs/broccoli)
~~[npm](https://npmjs.org/) with [browserify](http://browserify.org/)~~

All of these solutions are patches for npm. 
And I really don't understand why frontend is ignored by npm for many years...

Is there any plan to support `browserDependencies`?
Thanks.

**Comment by othiym23** [comment]
This is [on the npm road map](https://github.com/npm/npm/wiki/Roadmap#front-end-asset-installer), and is a fairly high-priority project for the team.

**Comment by zkat** [comment]
This is a big thing we really want to do, and it's been on our roadmap for a while. Having a straightforward, usable way of using npm for browser-based dependencies is super important.

Unfortunately, because of other priorities, we don't know when we're going to get to this. As such, I'm going to close this issue, and we'll reopen it in the future when we have a proposal ready for the community to iterate upon.

**Comment by stramel** [comment]
Is there any update on this? It sounds like exactly what I'm wanting

**Comment by honkskillet** [comment]
Updates?

**Comment by legodude17** [comment]
@othiym23 or @zkat will reopen this when the CLI team is ready to work on this. Remember, the CLI team is quite small and has a lot of work to do, as show by the 2,000+ issues open here.

**Comment by whitecolor** [comment]
yarn has a like proposaal https://github.com/yarnpkg/rfcs/issues/13

**Comment by monolithed** [comment]
@whitecolor, not the same issue, here it is https://github.com/npm/npm/issues/13479

**Comment by klihelp** [comment]
+1
