### ISSUE TITLE
error : npm install gulp 

### ISSUE THREAD

**Issue by fuyc3** [npm/npm#9362]
```
E:\hongbao>npm install -g gulp
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\nodejs\\\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-
cli.js" "install" "-g" "gulp"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! syscall getaddrinfo

npm ERR! getaddrinfo EAI_AGAIN
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     E:\hongbao\npm-debug.log
```

why ?  who can tell me .

**Comment by sinkingshriek** [comment]
Hey @fuyc3, the `EAI_AGAIN` error is most likely network error. Either you can keep trying or if you're behind proxy then you'd have to tell npm about your proxy setting. If that doesn't work then can you post the `npm-debug.log` that it generated for you for us to take a good look at it?

**Comment by fuyc3** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\nodejs\\\\node.exe',
1 verbose cli   'D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'gulp' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose config Skipping project config: C:\Users\Administrator/.npmrc. (matches userconfig)
5 verbose install initial load of C:\Users\Administrator\package.json
6 verbose readDependencies loading dependencies from C:\Users\Administrator\package.json
7 silly cache add args [ 'gulp', null ]
8 verbose cache add spec gulp
9 silly cache add parsed spec { raw: 'gulp',
9 silly cache add   scope: null,
9 silly cache add   name: 'gulp',
9 silly cache add   rawSpec: '',
9 silly cache add   spec: '*',
9 silly cache add   type: 'range' }
10 silly addNamed gulp@*
11 verbose addNamed "*" is a valid semver range for gulp
12 silly addNameRange { name: 'gulp', range: '*', hasData: false }
13 silly mapToRegistry name gulp
14 silly mapToRegistry using default registry
15 silly mapToRegistry registry https://registry.npmjs.org/
16 silly mapToRegistry uri https://registry.npmjs.org/gulp
17 verbose addNameRange registry:https://registry.npmjs.org/gulp not in flight; fetching
18 verbose request uri https://registry.npmjs.org/gulp
19 verbose request no auth needed
20 info attempt registry request try #1 at 13:34:18
21 verbose request id ddcdaf432d324170
22 http request GET https://registry.npmjs.org/gulp
23 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN
24 info attempt registry request try #2 at 13:34:29
25 http request GET https://registry.npmjs.org/gulp
26 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN
27 info attempt registry request try #3 at 13:35:29
28 http request GET https://registry.npmjs.org/gulp
29 verbose stack Error: getaddrinfo EAI_AGAIN
29 verbose stack     at Object.exports._errnoException (util.js:746:11)
29 verbose stack     at errnoException (dns.js:49:15)
29 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)
30 verbose cwd C:\Users\Administrator
31 error Windows_NT 6.1.7601
32 error argv "D:\\nodejs\\\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "gulp"
33 error node v0.12.7
34 error npm  v2.11.3
35 error code EAI_AGAIN
36 error errno EAI_AGAIN
37 error syscall getaddrinfo
38 error getaddrinfo EAI_AGAIN
39 error If you need help, you may report this error at:
39 error     <https://github.com/npm/npm/issues>
40 verbose exit [ 1, true ]


above  is the  npm-debug.log

**Comment by tesnep** [comment]
I ran into this same problem and got around it by changing these npm default configurations.

`$ npm config set registry "http://registry.npmjs.org`
`$ npm set strict-ssl false`

**Comment by kellyjandrews** [comment]
@fuyc3 Are you still having this issue, or can this issue be marked closed?
