### ISSUE TITLE
npm install -g cylon failing

### ISSUE THREAD

**Issue by drumwhizz** [npm/npm#9366]
OS: Kubuntu 14.04.3
Nodejs: v0.10.25
Npm: v1.3.10

Trying to install cylonjs I get  the following error. Thinking my VM was corrupted I have done a fresh installation of the OS but still get the following error:

```
sudo npm install -g cylon
npm http GET https://registry.npmjs.org/cyclon
npm http 404 https://registry.npmjs.org/cyclon
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/share/npm/lib/cache.js:687:35)
npm ERR!     at /usr/share/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
```

**Comment by drumwhizz** [comment]
https://gist.github.com/drumwhizz/0ddc0d5b80b3134be598

**Comment by drumwhizz** [comment]
Found the solution here:

http://askubuntu.com/questions/426750/how-can-i-update-my-nodejs-to-the-latest-version

**Comment by KenanY** [comment]
@drumwhizz Yes, `npm@1.3.10` is almost two years old now so upgrading is definitely the best solution here.

**Comment by sinkingshriek** [comment]
Also, somewhat related. `cyclon` package is not available in the registry, however `cyclonejs` is. Not sure if you were going after that one.

**Comment by othiym23** [comment]
Closing as resolved:

1. that npm is very old; if you upgrade you'll have a better npm experience, and
2. `cyclonejs` and `cylon` are npm packages, but `cyclon` is not.

Have a great day, and I hope this helps!
