### ISSUE TITLE
npm private packages

### ISSUE THREAD

**Issue by przemyslawpluta** [npm/npm#9368]
Is there a way to give access to npm private packages to users who do not have npm accounts?

**Comment by othiym23** [comment]
To access private packages, _all_ users with read access to the private package must have a paid npm account. Right now this means that each user must sign up for private packages individually, but coming very soon, npm will be adding support for organization accounts that can sponsor users on teams associated with their organization. If you want to know more, you can [sign up](http://www.npmjs.com/orgs) to be notified when this becomes available.
