### ISSUE TITLE
homepage not listed on npmjs.com

### ISSUE THREAD

**Issue by sagiegurari** [npm/npm#9370]
I updated the package.json to point to the project homepage (I have always had the git location), but still on the npmjs.com there is no link to the project homepage unlike other projects with similar package.json structure.
For example see node-go-require:

https://www.npmjs.com/package/node-go-require
https://github.com/sagiegurari/node-go-require/blob/master/package.json

in package.json I have:
```json
"homepage": "http://github.com/sagiegurari/node-go-require",
  "repository": {
    "type": "git",
    "url": "http://github.com/sagiegurari/node-go-require.git"
  },
```

thanks

**Comment by sagiegurari** [comment]
By the way I'm using npm 2.11.3 when publishing

**Comment by KenanY** [comment]
@sagiegurari I believe this was recently fixed. I can see the link on [the staging server](https://staging.npmjs.com/package/node-go-require).

**Comment by sagiegurari** [comment]
so that means the main npmjs.com website will also be updated soon?

**Comment by KenanY** [comment]
@sagiegurari Yes, in fact it has just been updated and I now see the link on the main site as well.

**Comment by sagiegurari** [comment]
you are right. thanks
