### ISSUE TITLE
npm failed to install package with node.js (chakra).

### ISSUE THREAD

**Issue by NNM11** [npm/npm#9371]
installed Node.js (Chakra) on Windows 10 Enterprise (https://github.com/Microsoft/node), upgraded npm to v3.3.0 with (https://www.npmjs.com/package/npm-windows-upgrade).  

the "npm install -g any-package" will fail and return error "invalid name: node.js (chakra)".

```
205 error Windows_NT 6.3.9600
206 error argv "C:\\Program Files (x86)\\Node.js (chakra)\\\\node.exe" "C:\\Program Files (x86)\\Node.js (chakra)\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "flatten-packages"
207 error node v0.12.6-2
208 error npm  v3.3.0
209 error Invalid name: "Node.js (chakra)"
210 error If you need help, you may report this error at:
210 error     <https://github.com/npm/npm/issues>
```

**Comment by othiym23** [comment]
Assigning to @iarna for investigation and probable closing, because I think we've subsequently fixed the underlying bug.

**Comment by iarna** [comment]
This was doubling fixed:

First, this particular validation error is now a warning and not an error.

Second, we no longer intuit package names when a `package.json` is missing, and as such we won't think your package is named "Node.js (chakra)" and so we wouldn't even warn about this.
