### ISSUE TITLE
Why can't our node_modules tree link into a flat module store?

### ISSUE THREAD

**Issue by joeytwiddle** [npm/npm#9373]
There might be nothing novel here. My apologies if so.

My goal is to save space on disk (and possibly speed up installs) by keeping all known packages in a flat global or local store, with unique folders based on package name and version.

My `node_modules` tree would then have symlinks which point to the modules in my flat store. Aside from the symlinks, it should have identical structure to before.

Whenever a module is needed that we already have installed, we can just make a symlink to the module in the store, and save consuming any extra disk-space.

I actually wrote [a script](https://github.com/joeytwiddle/jsh/blob/master/code/shellscript/node/npm_flatten_modules.sh) to demonstrate the idea by transforming a normal `node_modules` folder.

(It actually does what is was designed to, but it is quite likely to break your `node_modules` folder, possibly because its simplicity does not account for existing flattening #6912. It might do better if that could be disabled.)

(One advantage of a separate store folder is that modules will never be deduped into `node_modules`, so they cannot be accidentally `require()`d without being explicitly installed. This was a concern raised in #6912.)

There are a few issues:

- I know `npm` maintainers have spoken out strongly against a flat structure in the past. So there may be good reasons why it cannot work.

- Is it valid to identify installed modules by `name@version`, or could two installs differ significantly but have the same signature?

- Sometimes `version` is not always available.  Then I use the timestamp of the most recent file in the package.

- Sometimes two installed modules have the same `name` and `version` but they have a different value for `_from`. Perhaps I should just ignore `_from` in this case. (It might also be from #6912.)

- Of course uninstalling modules could become trickier, unless we track the reverse-dependencies for each (`_from`). That should be possible for a project-local store (or just wipe `node_modules` and install fresh). But a global store might lose track of a project that needs certain modules, and think they are orphaned, if that project has been renamed or moved on the filesystem.

Anyway, I still believe that this could be an efficient way to maintain lots of packages without duplicating them. But is there some blocking reason that I haven't thought of? Cheers!

**Comment by XVincentX** [comment]
I think that npm 3.x is already doing this.

**Comment by timoxley** [comment]
> I think that npm 3.x is already doing this.

It isn't, but flat store + symlinks is how [jkroso/packin](https://github.com/jkroso/packin) works.

**Comment by othiym23** [comment]
`npm@3` installs a maximally flat tree (that is, it produces a tree that's flat except when there are semver conflicts within dependencies, and then allows installs to go deeper). It doesn't adopt the single package tree @joeytwiddle asks for. This has been requested many times in the past, and is not a path that npm interested in pursuing itself, as the number of new and sharp edge cases that it creates far more than outweigh any gains to having a single shared dependency tree.

This feature has been requested before, both here and on the Node and io.js issue trackers, and each time the team's position has remained the same: after looking at the tradeoffs, we're convinced that per-application, nested `node_modules` is still a solid design for how packages work in Node and with npm, and aside from tweaks like default deduping, we won't be changing how that aspect of the program works.
