### ISSUE TITLE
Scripts executed from nested directory lose original PWD

### ISSUE THREAD

**Issue by KrekkieD** [npm/npm#9374]
I like how `npm@^2.0.0` allows scripts to be executed from nested directories, but I seem to lose the current working directory.

`package.json` at `/projects/myPackage/package.json`:

``` json
{
  "scripts": {
    "showPwd": "echo $PWD"
  }
}
```

Terminal:

``` bash
# @ /projects/myPackage/lib/nested/directory
$ npm run showPwd

# output: /projects/myPackage <- package.json dir
```

Is there a way to get the original `PWD` (`/projects/myPackage/lib/nested/directory`) in the scripts? I would like this so I can pass it to a different module, or I would like to be able to access the `PWD` from the module itself (i.e. `process.cwd()`).

**Comment by motdotla** [comment]
I would like to see this too. :+1: 

I've tried digging through the available values in `process` but I do not see a way to access the original `PWD`.

Possibly this could be added as an additional env? Something like: `ORIGINAL_PWD`

---

My current workaround is:

```
ORIGINAL_PWD=$PWD npm run showPwd
```

```
{
  "scripts": {
    "showPwd": "echo $ORIGINAL_PWD"
  }
}
```

**Comment by kentcdodds** [comment]
Ping. I also have a use case for this. 'twould be awesome to know where the npm script is being run from when using something like [plop](http://npm.im/plop) to generate files in the `PWD`.

**Comment by lewisf** [comment]
Ping, I also have a use case for this. It'd be nice if I could do something like

```
cd some/folder/with/tests
npm run test -- .
```

and to have that basically evaluate to
```
npm run test -- some/folder/with/tests
```

right now, no matter how far nested i am into npm/package/root/, it would evaluate to

```
npm run test -- npm/package/root/
```

**Comment by ndabAP** [comment]
Does anyone of you got a solution for this already?

**Comment by rbalicki2** [comment]
@ndabAP Having done a `printenv`, I found that the `$INIT_CWD` environment variable points to the folder from which I ran the `npm run` command. This should be much more publicized!

**Comment by ndabAP** [comment]
@rbalicki2, cool, I'll check that later. Thank you!

**Comment by Jakobud** [comment]
Check out the `process.env.PWD` environment variable also. That appears to preserve the directory of the `package.json` that is being used by `npm`, even if you execute in a subdirectory.
