### ISSUE TITLE
Untar error/unknown symlink error installing grunt-contrib-imagemin

### ISSUE THREAD

**Issue by melarish** [npm/npm#9377]
Trying to set up Habitica (http://habitica.wikia.com/wiki/Setting_up_Habitica_Locally) using Vagrant. I got some missing module errors, so trying to reinstall grunt-contrib-imagemin but getting this error:

```
26656 error tar.unpack untar error /home/vagrant/.npm/readable-stream/2.0.2/package.tgz
29674 verbose stack Error: UNKNOWN, symlink '../repeating/cli.js'
29675 verbose cwd /vagrant
29676 error Linux 3.2.0-23-generic
29677 error argv "node" "/usr/bin/npm" "install" "grunt-contrib-imagemin"
29678 error node v0.10.37
29679 error npm  v2.14.1
29680 error path ../repeating/cli.js
29681 error code UNKNOWN
29682 error errno -1
29683 error UNKNOWN, symlink '../repeating/cli.js'
29684 error If you need help, you may report this error at:
29684 error     <https://github.com/npm/npm/issues>
29685 verbose exit [ -1, true ]
```

Whole log file at https://www.dropbox.com/s/9sh6au66wx0jhk3/npm-debug.log.00c2c6e20e915750d2b56ad6949064df?dl=0

I'm pretty sure `readable-stream` is where the missing module (./lib/_stream_transform.js) was supposed to be, so it probably failed the same during the initial install.

I've already done `sudo npm install -g npm@next`

**Comment by KenanY** [comment]
@melarish Is this Vagrant on top of Windows?

**Comment by melarish** [comment]
@KenanY Yes, it's Windows 8.

**Comment by KenanY** [comment]
@melarish Could you try using the `--no-bin-links` argument?

**Comment by melarish** [comment]
Tried that but looks like the same errors. 
npm ERR! tar.unpack untar error /home/vagrant/.npm/readable-stream/2.0.2/package.tgz
npm WARN optional dep failed, continuing imagemin-optipng@4.3.0
npm WARN optional dep failed, continuing imagemin-jpegtran@4.3.0
npm WARN optional dep failed, continuing imagemin-gifsicle@4.2.0
npm ERR! Linux 3.2.0-23-generic
npm ERR! argv "node" "/usr/bin/npm" "install" "grunt-contrib-imagemin" "--no-bin-links"
npm ERR! node v0.10.37
npm ERR! npm  v2.14.1
npm ERR! path /vagrant/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/vinyl-
fs/node_modules/glob-stream/node_modules/unique-stream/node_modules/through2-filter/node_modules/thr
ough2/node_modules/readable-stream/lib/_stream_passthrough.js
npm ERR! code EPERM
npm ERR! errno 50
npm ERR! Error: EPERM, open '/vagrant/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node
_modules/vinyl-fs/node_modules/glob-stream/node_modules/unique-stream/node_modules/through2-filter/n
ode_modules/through2/node_modules/readable-stream/lib/_stream_passthrough.js'
npm ERR!  { [Error: EPERM, open '/vagrant/node_modules/grunt-contrib-imagemin/node_modules/imagemin/
node_modules/vinyl-fs/node_modules/glob-stream/node_modules/unique-stream/node_modules/through2-filt
er/node_modules/through2/node_modules/readable-stream/lib/_stream_passthrough.js']
npm ERR!   errno: 50,
npm ERR!   code: 'EPERM',
npm ERR!   path: '/vagrant/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/vi
nyl-fs/node_modules/glob-stream/node_modules/unique-stream/node_modules/through2-filter/node_modules
/through2/node_modules/readable-stream/lib/_stream_passthrough.js' }

Full log: https://www.dropbox.com/s/lalglczu6wuwwzg/npm-debug.log.2bc7d1d26eac4f5c3373eb5f0c4d4851?dl=0

**Comment by wandl** [comment]
+1 Any progress on this having similar errors Windows 7, Git-Bash, Vagrant, VVV-apache, Ubuntu 14.04 LTS

https://gist.github.com/wandl/bef351f564b257767984

Any help much appreciated!
