### ISSUE TITLE
i cant install gulp and something likes,please help me~

### ISSUE THREAD

**Issue by nanmenxue** [npm/npm#9380]
it says 
```
npm WARN locking Error: EACCES, open '/Users/wai121/.npm/_locks/gulp-709d00e5d169ceb3.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/wai121/.npm/_locks/gulp-709d00e5d169ceb3.lock failed { [Error: EACCES, open '/Users/wai121/.npm/_locks/gulp-709d00e5d169ceb3.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/wai121/.npm/_locks/gulp-709d00e5d169ceb3.lock' }
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "gulp"
npm ERR! node v0.12.0
npm ERR! npm  v2.13.3

npm ERR! Attempt to unlock /usr/local/lib/node_modules/gulp, which hasn't been locked
```

**Comment by KenanY** [comment]
@nanmenxue It looks like you don't have permission to modify `npm`'s cache directory, for whatever reason. Could you try running the following?:

``` sh
$ sudo chown -R $(whoami) "$HOME/.npm"
```

Also, since your current configuration has `npm` putting global modules in `/usr/local`, you will have to prefix your `npm install -g` commands with `sudo` unless you `chown` that directory as well.

**Comment by nanmenxue** [comment]
when i use $ sudo chown -R $(whoami) "$HOME/.npm"
it says -bash: $: command not found

**Comment by nanmenxue** [comment]
what can i do now?my english is poor,thank you firstly.

**Comment by nanmenxue** [comment]
oh i know ,i should prefix sudo.
is it right?but i want to know why

**Comment by KenanY** [comment]
@nanmenxue You should not enter that first dollar sign (`$`). That just indicates that you should run the command that follows it at the command line. So just enter everything afterwards.

**Comment by nanmenxue** [comment]
ok~i have so much thing to learn~thank you again

**Comment by ehsalazar** [comment]
Were you able to get things working once you dropped the `$` from the command? I'll close this for now as we’re trying to clean up some solved issues. We’ll be happy to reopen if necessary.
