### ISSUE TITLE
Error installing npm modules

### ISSUE THREAD

**Issue by myazhbin** [npm/npm#9383]
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', '-g', 'yo' ]
2 info using npm@2.14.0
3 info using node@v0.12.7
4 verbose install initial load of /usr/local/lib/package.json
5 verbose readDependencies loading dependencies from /usr/local/lib/package.json
6 silly cache add args [ 'yo', null ]
7 verbose cache add spec yo
8 silly cache add parsed spec { raw: 'yo',
8 silly cache add   scope: null,
8 silly cache add   name: 'yo',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed yo@*
10 verbose addNamed "*" is a valid semver range for yo
11 silly addNameRange { name: 'yo', range: '*', hasData: false }
12 silly mapToRegistry name yo
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/yo
16 verbose addNameRange registry:https://registry.npmjs.org/yo not in flight; fetching
17 verbose request uri https://registry.npmjs.org/yo
18 verbose request no auth needed
19 info attempt registry request try #1 at 7:43:39 AM
20 verbose request id 9bd61ae20e5cd2c8
21 http request GET https://registry.npmjs.org/yo
22 http 200 https://registry.npmjs.org/yo
23 silly get cb [ 200,
23 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
23 silly get     etag: '"9Q26KKMNJA31XDB9T64FPWQ9L"',
23 silly get     'content-type': 'application/json',
23 silly get     'cache-control': 'max-age=60',
23 silly get     'content-length': '34022',
23 silly get     'accept-ranges': 'bytes',
23 silly get     date: 'Sun, 23 Aug 2015 23:43:40 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     age: '0',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-hkg6822-HKG',
23 silly get     'x-cache': 'MISS',
23 silly get     'x-cache-hits': '0',
23 silly get     'x-timer': 'S1440373420.251777,VS0,VE673',
23 silly get     vary: 'Accept' } ]
24 verbose get saving yo to /Users/maxyazhbin/.npm/registry.npmjs.org/yo/.cache.json
25 silly addNameRange number 2 { name: 'yo', range: '*', hasData: true }
26 silly addNameRange versions [ 'yo',
26 silly addNameRange   [ '1.1.0',
26 silly addNameRange     '1.1.1',
26 silly addNameRange     '1.1.2',
26 silly addNameRange     '1.2.0',
26 silly addNameRange     '1.2.1',
26 silly addNameRange     '1.3.0',
26 silly addNameRange     '1.3.2',
26 silly addNameRange     '1.3.3',
26 silly addNameRange     '1.4.1',
26 silly addNameRange     '1.4.2',
26 silly addNameRange     '1.4.4',
26 silly addNameRange     '1.4.5',
26 silly addNameRange     '1.4.6',
26 silly addNameRange     '1.4.7' ] ]
27 silly addNamed yo@1.4.7
28 verbose addNamed "1.4.7" is a plain semver version for yo
29 silly mapToRegistry name yo
30 silly mapToRegistry using default registry
31 silly mapToRegistry registry https://registry.npmjs.org/
32 silly mapToRegistry uri https://registry.npmjs.org/yo
33 verbose addRemoteTarball https://registry.npmjs.org/yo/-/yo-1.4.7.tgz not in flight; adding
34 verbose addRemoteTarball [ 'https://registry.npmjs.org/yo/-/yo-1.4.7.tgz',
34 verbose addRemoteTarball   '7eecb354f6f4df2dafbc2da53d30f7f7fafcb450' ]
35 info retry fetch attempt 1 at 7:43:41 AM
36 info attempt registry request try #1 at 7:43:41 AM
37 http fetch GET https://registry.npmjs.org/yo/-/yo-1.4.7.tgz
38 http fetch 200 https://registry.npmjs.org/yo/-/yo-1.4.7.tgz
39 silly fetchAndShaCheck shasum 7eecb354f6f4df2dafbc2da53d30f7f7fafcb450
40 verbose addTmpTarball /var/folders/xq/n0_cvd_10nqbnn_jzkfd6ry40000gn/T/npm-1110-669e1840/registry.npmjs.org/yo/-/yo-1.4.7.tgz not in flight; adding
41 verbose addTmpTarball already have metadata; skipping unpack for yo@1.4.7
42 silly cache afterAdd yo@1.4.7
43 verbose afterAdd /Users/maxyazhbin/.npm/yo/1.4.7/package/package.json not in flight; writing
44 verbose afterAdd /Users/maxyazhbin/.npm/yo/1.4.7/package/package.json written
45 silly install resolved [ { name: 'yo',
45 silly install resolved     version: '1.4.7',
45 silly install resolved     description: 'CLI tool for running Yeoman generators',
45 silly install resolved     license: 'BSD-2-Clause',
45 silly install resolved     bin: { yo: 'lib/cli.js' },
45 silly install resolved     author: { name: 'Yeoman' },
45 silly install resolved     repository: { type: 'git', url: 'https://github.com/yeoman/yo' },
45 silly install resolved     engines: { node: '>=0.10.0', npm: '>=2.8.0' },
45 silly install resolved     scripts:
45 silly install resolved      { test: 'jshint . && mocha test/**/*.js',
45 silly install resolved        postinstall: 'yodoctor',
45 silly install resolved        postupdate: 'yodoctor',
45 silly install resolved        prepublish: 'nsp audit-package' },
45 silly install resolved     files: [ 'lib' ],
45 silly install resolved     keywords:
45 silly install resolved      [ 'cli-app',
45 silly install resolved        'cli',
45 silly install resolved        'bin',
45 silly install resolved        'front-end',
45 silly install resolved        'development',
45 silly install resolved        'dev',
45 silly install resolved        'build',
45 silly install resolved        'web',
45 silly install resolved        'tool',
45 silly install resolved        'scaffold',
45 silly install resolved        'stack',
45 silly install resolved        'yeoman',
45 silly install resolved        'generator',
45 silly install resolved        'generate',
45 silly install resolved        'app',
45 silly install resolved        'boilerplate' ],
45 silly install resolved     dependencies:
45 silly install resolved      { 'array-uniq': '^1.0.2',
45 silly install resolved        async: '^1.0.0',
45 silly install resolved        chalk: '^1.0.0',
45 silly install resolved        configstore: '^1.0.0',
45 silly install resolved        'cross-spawn': '^0.4.0',
45 silly install resolved        figures: '^1.3.5',
45 silly install resolved        findup: '^0.1.5',
45 silly install resolved        fullname: '^1.0.0',
45 silly install resolved        got: '^3.2.0',
45 silly install resolved        'humanize-string': '^1.0.0',
45 silly install resolved        inquirer: '^0.8.0',
45 silly install resolved        insight: '^0.6.0',
45 silly install resolved        lodash: '^3.2.0',
45 silly install resolved        meow: '^3.0.0',
45 silly install resolved        'npm-keyword': '^1.1.1',
45 silly install resolved        opn: '^1.0.0',
45 silly install resolved        'package-json': '^1.1.0',
45 silly install resolved        repeating: '^1.1.2',
45 silly install resolved        'root-check': '^1.0.0',
45 silly install resolved        'sort-on': '^1.0.0',
45 silly install resolved        'string-length': '^1.0.0',
45 silly install resolved        titleize: '^1.0.0',
45 silly install resolved        'update-notifier': '^0.5.0',
45 silly install resolved        'user-home': '^1.1.0',
45 silly install resolved        'yeoman-character': '^1.0.0',
45 silly install resolved        'yeoman-doctor': '^1.0.0',
45 silly install resolved        'yeoman-environment': '^1.0.1',
45 silly install resolved        yosay: '^1.0.0' },
45 silly install resolved     devDependencies:
45 silly install resolved      { jshint: '^2.5.11',
45 silly install resolved        mocha: '^2.1.0',
45 silly install resolved        mockery: '^1.4.0',
45 silly install resolved        nock: '^2.0.1',
45 silly install resolved        nsp: '*',
45 silly install resolved        proxyquire: '^1.0.1',
45 silly install resolved        'registry-url': '^3.0.0',
45 silly install resolved        sinon: '^1.12.1' },
45 silly install resolved     preferGlobal: true,
45 silly install resolved     gitHead: '675d647162f1ecd7f290995078cf8ab42756bf9d',
45 silly install resolved     bugs: { url: 'https://github.com/yeoman/yo/issues' },
45 silly install resolved     homepage: 'https://github.com/yeoman/yo',
45 silly install resolved     _id: 'yo@1.4.7',
45 silly install resolved     _shasum: '7eecb354f6f4df2dafbc2da53d30f7f7fafcb450',
45 silly install resolved     _from: 'yo@*',
45 silly install resolved     _npmVersion: '2.10.1',
45 silly install resolved     _nodeVersion: '0.12.4',
45 silly install resolved     _npmUser: { name: 'sindresorhus', email: 'sindresorhus@gmail.com' },
45 silly install resolved     dist:
45 silly install resolved      { shasum: '7eecb354f6f4df2dafbc2da53d30f7f7fafcb450',
45 silly install resolved        tarball: 'http://registry.npmjs.org/yo/-/yo-1.4.7.tgz' },
45 silly install resolved     maintainers: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
45 silly install resolved     directories: {},
45 silly install resolved     _resolved: 'https://registry.npmjs.org/yo/-/yo-1.4.7.tgz' } ]
46 info install yo@1.4.7 into /usr/local/lib
47 info installOne yo@1.4.7
48 verbose installOne of yo to /usr/local/lib not in flight; installing
49 warn locking Error: EACCES, open '/Users/maxyazhbin/.npm/_locks/yo-c80abb7e04f27e35.lock'
49 warn locking     at Error (native)
49 warn locking  /Users/maxyazhbin/.npm/_locks/yo-c80abb7e04f27e35.lock failed { [Error: EACCES, open '/Users/maxyazhbin/.npm/_locks/yo-c80abb7e04f27e35.lock']
49 warn locking   errno: -13,
49 warn locking   code: 'EACCES',
49 warn locking   path: '/Users/maxyazhbin/.npm/_locks/yo-c80abb7e04f27e35.lock' }
50 verbose stack Error: Attempt to unlock /usr/local/lib/node_modules/yo, which hasn't been locked
50 verbose stack     at unlock (/usr/local/lib/node_modules/npm/lib/utils/locker.js:64:11)
50 verbose stack     at cb (/usr/local/lib/node_modules/npm/lib/install.js:1018:5)
50 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:1022:20
50 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/locker.js:39:7
50 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
50 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
50 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:230:16
50 verbose stack     at FSReqWrap.oncomplete (fs.js:95:15)
51 verbose cwd /Users/maxyazhbin
52 error Darwin 14.4.0
53 error argv "node" "/usr/local/bin/npm" "install" "-g" "yo"
54 error node v0.12.7
55 error npm  v2.14.0
56 error Attempt to unlock /usr/local/lib/node_modules/yo, which hasn't been locked
57 error If you need help, you may report this error at:
57 error     <https://github.com/npm/npm/issues>
58 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@myazhbin This looks like a permissions issue to me. Could you try running the following?:

``` sh
sudo chown -R $(whoami) "$HOME/.npm"
```

**Comment by myazhbin** [comment]
I just did, but nothing happened

**Comment by KenanY** [comment]
@myazhbin I just want to clarify: you are still receiving the same error?

**Comment by myazhbin** [comment]
yes. here is the error:

Maxs-MacBook-Air:~ maxyazhbin$ npm install -g yo
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "yo"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.0
npm ERR! path /usr/local/lib/node_modules/yo
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, rmdir '/usr/local/lib/node_modules/yo'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, rmdir '/usr/local/lib/node_modules/yo']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/yo' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
npm ERR! error rolling back Error: EACCES, rmdir '/usr/local/lib/node_modules/yo'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EACCES, rmdir '/usr/local/lib/node_modules/yo']
npm ERR! error rolling back   errno: -13,
npm ERR! error rolling back   code: 'EACCES',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/yo' }

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/maxyazhbin/npm-debug.log



But now I sudo in front of my commands and that allows for the commands to work.

**Comment by KenanY** [comment]
@myazhbin Oh yes, that is a slightly different error. You don't have permission to modify `/usr/local` either (a default on most systems), yet your global modules are being installed into there. So yes, you will need to use `sudo` or `chown` that directory to your own user.

**Comment by myazhbin** [comment]
great, thanks
