### ISSUE TITLE
Exclude .npmrc files by default

### ISSUE THREAD

**Issue by tqc** [npm/npm#9384]
The documentation states that .npmrc files may contain sensitive information and that they have no effect on a published module.

Is there any good reason they should not be included in the list of files ignored regardless of .npmignore settings?

I recently got an email from the npm security bot informing me that I had accidentally published my password. The problem turned out to be a CI server writing a .npmrc file. Since there is not normally a local .npmrc, there was no reason for it to be in .gitignore, and it never showed up on github, which would have been more noticeable. 

Yes, I screwed up the configuration, but it seems like an easy mistake to make impossible.

**Comment by iarna** [comment]
Hey, it's funny that everyone seems to be discovering this at once. We landed this change in `npm@next` last week.

See also this conversation: https://github.com/npm/npm/pull/9376
