### ISSUE TITLE
With npm run script, os.tmpdir() is set to script path

### ISSUE THREAD

**Issue by butaixianran** [npm/npm#9388]
By default, os.tempdir() should be "/tmp" in Linux.
But with npm run script, os.tempdir() is redirected to the directory of script file.

This is an issue? or I missed something in package.json?

Thanks

**Comment by KenanY** [comment]
@butaixianran You mean like this?:

``` json
{
  "scripts": {
    "test": "node -e 'console.log(require(\"os\").tmpdir())'"
  }
}
```

With io.js 3.1.0 and `npm@2.14.0`, I get:

``` sh
$ npm test

> @ test /home/kenan/Code/npm-tmpdir
> node -e 'console.log(require("os").tmpdir())'

/tmp
```

**Comment by butaixianran** [comment]
well, seems I should update my iojs. thanks.

**Comment by ehsalazar** [comment]
We haven't heard back in while, did updating help?. I'll close this for now as we’re trying to clean up some solved issues. We’ll be happy to reopen if necessary.

**Comment by ulybu** [comment]
Hi, 
I ran into that today 
```shell
[root@mp testRepo]# node -v ; npm -v
v5.0.0
3.3.6
[root@mp testRepo]# npm test

> testRepo@1.0.0 test /net/mac/Users/ulybu/CODE/githp/testRepo
> node -e 'console.log(require("os").tmpdir())'

/net/mac/Users/ulybu/CODE/githp/testRepo
[root@mp testRepo]# 
```

**Comment by KenanY** [comment]
@ulybu Unfortunately I still cannot reproduce.

``` sh
$ node -v
v5.1.1

$ npm -v
3.5.2

$ npm t

> @ test /home/kenan/code/npm-9388
> node -e 'console.log(require("os").tmpdir())'

/tmp
```

**Comment by bchenSyd** [comment]
reproduced the same issue on npm `v5.3`;
on `5.6.0` the issue has been fixed
