### ISSUE TITLE
npm cache causes errors when a github dependency's branches change in certain ways.

### ISSUE THREAD

**Issue by trusktr** [npm/npm#9395]
For example, suppose we depend on package `foo` from `git+https://github.com/foo/foo#bar`, depending on the `bar` branch. When we `npm install`, it'll work just fine. Now, suppose the `foo/foo` repo also has a branch called `baz`. `npm install` still works. Now suppose upstream moves the `baz` branch to a branch called `baz/new` and make more branches under the `baz` bamespace, f.e. `baz/impsum`, etc.

Although these branches have nothing to do with the dependency that we are pulling from GitHub (we're depending on the `bar` branch, NPM will throw errors like the following:

```
npm ERR! Command failed: git fetch -a origin
npm ERR! From https://github.com/foo/foo
npm ERR! error: cannot lock ref 'refs/heads/baz/ipsum': 'refs/heads/baz' exists; cannot create 'refs/heads/baz/ipsum'
npm ERR! error: some local refs could not be updated; try running
npm ERR!  'git remote prune origin' to remove any old, conflicting branches
```

NPM will just crash. A quick solution is running `rm -rf ~/.npm` and trying again. NPM would need to detect this case and re-clone the repos or similar (git prune).

**Comment by iarna** [comment]
I think I favor fetching with `-p` (prune) on general principles, although I'm not certain that will solve this issue.

**Comment by othiym23** [comment]
I put this on the [npm roadmap](https://github.com/npm/npm/wiki/Roadmap), so someone on the CLI team should get to this relatively soon. Sorry for the bother!

**Comment by trusktr** [comment]
:+1: :sparkles:

**Comment by admosity** [comment]
This is still broken. I find that the reproduction case is when there is a branch that has a prefix of another branch. For example, with these two branches in the repository it will break a npm install:

`refactor`
`refactor/something-else`
