### ISSUE TITLE
Add command for editing package.json

### ISSUE THREAD

**Issue by iarna** [npm/npm#9397]
The files section of the package.json would be a lot more useful if you could edit it via the command line. I'm thinking something along the lines of git commit staging:

* `npm files add <file>` - Add named file (or files) to the files section of the package.json.
* `npm files rm <file>` - Remove named file (or files) section from the package.json. Warn if a glob entry would match this file.
* `npm files status` - Like `git status`, show which files will be included in a package.

As a bonus, `npm files status` w/o a files section could read `.gitignore` or `.npmignore` and show what would be included.

Possible bonus command:

* `npm files ignore add <file>`
* `npm files ignore rm <file>`

**Comment by othiym23** [comment]
I think an `npm package` command that behaves similarly to `npm config`, but for `package.json`, would be very helpful:

* add validation for particular sections of the file
* make it hookable, a la `init-package-json`, to support custom package.json fields, a la `browser` or `browserify`
* provide a top-level space to add a command like `npm package validate` to run all the `package.json` checks from the top level. 

Having a way to edit the `files` section would be a really useful element of this, for sure.

**Comment by zkat** [comment]
Not gonna work on it this year ourselves, so patches welcome :\
