### ISSUE TITLE
Tag version on package.json

### ISSUE THREAD

**Issue by brunowego** [npm/npm#9402]
The attribute "version" could not automatically come from the git tag? Bower does this and this feature is pretty cool.

**Comment by othiym23** [comment]
I think adding a new top-level parameter to `npm version`, a la `npm version from-git`, could be useful here. This is pretty low-priority, though, so it might need some help from the community.

**Comment by zkat** [comment]
This got merged through #10717 and is out in `npm@next` already. Wee!

**Comment by brunowego** [comment]
Thanks @zkat :+1:
