### ISSUE TITLE
Timing npm scripts

### ISSUE THREAD

**Issue by garygreen** [npm/npm#9415]
Does npm expose some details about tasks being run how long they took? For instance if you did `npm run build` is it possible to get how long 'clean' and 'js' and 'css' took to run? Idea is to output the timings of each task, similar to [time-grunt](https://github.com/sindresorhus/time-grunt/blob/master/index.js)

```json
"scripts": {
    "build": "npm run clean && npm run js && npm run css",
    "clean": "rimraf public/dist",
    "js": "mkdirp public/dist/js && browserify resources/assets/js/site.js -o public/dist/js/app.js",
    "css": "lessc resources/assets/less/site.less public/dist/css/site.css"
}
```

**Comment by zkat** [comment]
This seems great, and would be really useful to add! Patches welcome, but we're closing it for now :)
