### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by vicky15061** [npm/npm#9417]
c:\Users\DELL\angular-phonecat\npm-debug.log..this is the issue while instaling the npm using cmd

**Comment by KenanY** [comment]
@vicky15061 Could you upload the `npm-debug.log` as a [gist](https://gist.github.com/)?

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.
