### ISSUE TITLE
Setting up appointment

### ISSUE THREAD

**Issue by mycra-craig** [npm/npm#9426]
http://mycratherapy.com/office

When I set up an appointment for Klee@miller schools she received an email saying a session had been set up.  However, she never received an email reminder that the session had been set up with a link.

She did receive the link when I sent her an open session invitation and one to ignore start date and open session immediately.

Let me know if this information is specific enough

**Comment by othiym23** [comment]
I think this is probably an issue with your application, and not with npm itself. Depending on which piece of your application is responsible for sending emails to users, you should probably ask for further support there, or possibly on [#Node.js on Freenet IRC](https://nodejs.org/community/). Good luck!
