### ISSUE TITLE
Windows_NT 6.3.9600

### ISSUE THREAD

**Issue by BramDecuypere** [npm/npm#9428]
![2015-08-27 23_22_39-c__windows_system32_cmd exe](https://cloud.githubusercontent.com/assets/7522178/9533466/96643502-4d12-11e5-891d-af100e2b02b8.png)

http://justpaste.it/npm-debug

**Comment by thanhmabo** [comment]
@BramDecuypere , install Angular 2.0?

**Comment by BramDecuypere** [comment]
This is when following the mean.io tutorial. I've tried everything out there.
But nothing really works, so I'm pretty stuck atm.

**Comment by mdrozdo** [comment]
The log looks really similar to the one I posted recently - #9418. Probably a duplicat.  I'm pretty sure I can still easily replicate it.
