### ISSUE TITLE
Npm error

### ISSUE THREAD

**Issue by ghost** [npm/npm#9429]
npm is broken :(

**Comment by othiym23** [comment]
Can you be more specific? An `npm-debug.log` file posted as [a gist](https://gist.github.com/) would be helpful, along with a description of what you were trying to do when npm failed.

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some issues. If you're still having issues, can you please reply and let us know? We’ll be happy to reopen if necessary.
