### ISSUE TITLE
npm install error,what's the error?

### ISSUE THREAD

**Issue by xmlxpath** [npm/npm#9430]
![qq 20150828120933](https://cloud.githubusercontent.com/assets/3400783/9539008/a96699c2-4d7d-11e5-9a17-ba3b0bfccbf4.png)

**Comment by KenanY** [comment]
@xmlxpath The error is an invalid `"name"` field in your `package.json`.

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some issues. Were you able to get your `package.json` set as needed? If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.
