### ISSUE TITLE
Invalid dependency format can result in EMISSINGARG

### ISSUE THREAD

**Issue by jamietre** [npm/npm#9433]
Not a high priority but caused some confusion for a while, e.g.

    "devDependencies": {
      "babel-core": "npm:babel-core@^5.1.13"
    }.

will result in

    > npm install
    npm ERR! Windows_NT 6.1.7601
    npm ERR! argv "node" "...\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
    npm ERR! node v0.12.7
    npm ERR! npm  v3.3.0
    npm ERR! code EMISSINGARG

    npm ERR! typeerror Error: Missing required argument #3
    npm ERR! typeerror     at exports.findRequirement (...\npm\node_modules\npm\lib\install\deps.js:475:3)
    npm ERR! typeerror   .. (etc)

This was a JSPM format dependency that I didn't fix properly. I would expect it to give an error more like how

    "devDependencies": {
      "babel-core": "foobar"
    }.

results in...

    > npm install
    npm ERR! No compatible version found: babel-core@foobar
    npm ERR! Valid install targets:
    npm ERR! ["5.8.23","5.8.22","5.8.21" ...]

**Comment by othiym23** [comment]
Yeah, this error message isn't ideal, but it's also not a bug, per se, so a patch to return a better error message in this case would be appreciated.

**Comment by iarna** [comment]
This was fixed a week or two ago! You should now get this instead:
```
npm ERR! Unsupported URL Type: npm:babel-core@^5.1.13
```
