### ISSUE TITLE
error:0906D06C:PEM routines:PEM_read_bio:no start line

### ISSUE THREAD

**Issue by sreenibellamkonda** [npm/npm#9437]
```
error:0906D06C:PEM routines:PEM_read_bio:no start line
```

**Comment by KenanY** [comment]
@sreenibellamkonda More often than not, SSL errors like that are caused by a proxy configuration error. Could you at least upload the _entire_ `npm-debug.log` as a [gist](https://gist.github.com/)?

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.
