### ISSUE TITLE
question: how to specify additional prefix search path for libraries and header files when doing npm install

### ISSUE THREAD

**Issue by andrewrk** [npm/npm#9438]
I'm trying to run `npm install` in a project source tree.

Typical linux systems have .so files in  /usr/lib/*  or /usr/local/lib/* . On my system I'm doing some dev work so I just want to test a native addon node module that builds against a library that is in ~/local/lib/* (headers in ~/local/include/*). I've been digging around in the documentation for a command line switch or environment variable to add this additional search directory but have not found one. Is there one?

**Comment by othiym23** [comment]
You'd want to look at the [`node-gyp` documentation](https://www.npmjs.com/package/node-gyp) and probably also the [`gyp` documentation](https://chromium.googlesource.com/external/gyp/+/master/docs/UserDocumentation.md). npm just acts as a front end for `node-gyp` when building native dependencies, and you're going to want to put local configuration into `config.gypi`.
