### ISSUE TITLE
Wintersmith install failed

### ISSUE THREAD

**Issue by jamshark70** [npm/npm#9450]
```
$ npm install --save-dev wintersmith
```

... dumps tons of stuff into the console log and tells me to check npm-debug.log. This file is 2.7 MB!

https://gist.github.com/jamshark70/0cda2887cbfdbd470b5b

What's the next step?

node -v == 0.12.7
npm -v == 2.11.3
uname -a == Linux hjh-e431 3.11.0-26-generic #45~precise1-Ubuntu SMP Tue Jul 15 04:02:35 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Thanks.

**Comment by crucialfelix** [comment]
"unexpected end of stream"  - the user is in China and has noted that npm / github is being bandwidth capped.  so the failure is possibly related to that. 

wintersmith installed for me fine in a few seconds.

**Comment by jamshark70** [comment]
Based on crucialfelix's comment, I went ahead and paid an extra $6 US to my VPN service so I can use it for all apps, not just browsers, and... now npm is working.

Suggestion: Establish a mirror that is friendly to the Great Firewall of China (unless you want node.js to be unusable on the mainland).

**Comment by othiym23** [comment]
We'd love to have better support for mainland China, which (as you've seen) has spotty access to our CDN, for non-npm-related reasons. Unfortunately, it's pretty tough to get set up, largely for non-technical reasons. For now, probably the most reliable way to use npm inside Chiba is to use cnpmjs / the Taobao registry mirror.

**Comment by jamshark70** [comment]
Resolved by Astrill's StealthVPN. Thanks.
