### ISSUE TITLE
npm main for a dist solution and a build solution

### ISSUE THREAD

**Issue by blainekasten** [npm/npm#9459]
So I have a question/request/unsure what this is. But, it seems more and more libraries want to take advantage of ES6 features, which requires a build tool like webpack. An issue arises however when a webpack build requires another webpack build. So as library developers wanting to use ES6 is pretty unusable. I'm wondering if there already is a way, or proposing the idea of different `main` targets for the npm package. One for a dist solution (built), and a build solution (not yet built). This way libraries can import the other libraries and build it altogether or just pull in the dist solution if they need it that way.

**Comment by othiym23** [comment]
Until the [ES module loader spec](https://whatwg.github.io/loader/) gets into a finished enough state that browsers start implementing it, it feels premature for npm to pave any cowpaths here, as much as I (and many others) would like to see npm take the lead. I've had conversations with @ericf, @caridy, and @dherman about this (although not for a few months), and where we ended up (for now) is that `main` should point to the JavaScript directly consumable by Node (i.e. something run through Babel or webpack), and some other property should point to the ES2015 (or later) source.

The convention that @ericf has been using is `jsnext:main`, which has the desirable property of being a property that will never collide with anything npm does (we will never use colons in property names within npm), but the undesirable property that you'll need to migrate it to another name when we _do_ come up with an npm-supported mechanism for dealing with this in the future.

To get webpack moving in the direction of a convention here, you'd probably want to write a new loader for it that looks for whatever `weback-example-property-name:main` property you want in `package.json` and then use that when depending across webpack packages. It may also be able to build another layer of infrastructure atop webpack to get it to pay attention to things at the npm package layer.

I _can_ tell you that it's unlikely that npm is going to prescribe the use of a specific tool like Webpack or browserify. I don't know exactly what npm is going to do (you can peruse [npm's road map](https://github.com/npm/npm/wiki/Roadmap#areas-of-focus) to see how fuzzy my thinking is right now), but I do think it's going to probably add a new class of installable assets plus some lifecycle extensions to call out to a tool like webpack. So, time spent building out an infrastructure for webpack to deal with this is unlikely to be wasted when npm grows this capability.

I hope this is an adequat conversation-starter; the others I've tagged into this issue are welcome to offer their thoughts and hopes on what npm should do here, and I've now added this issue onto the road map. This is something I'd like to see npm address in the medium term, but I want to be careful about how we move forward here to avoid causing people to have to change course too many times as we get closer to figuring out how all this is going to work with JavaScript's new module system.

**Comment by blainekasten** [comment]
@othiym23 Really great points. I appreciate all of it. I definitely see this as premature for something of NPM's scale to tackle right now. I also definitely understand that NPM would never prescribe a specific external tool.

All said, I really think you're onto something with the lifecycle extensions. I don't have much to offer into this other than it seems to be a growing issue as ES6 becomes more widely accepted and utilized.

**Comment by othiym23** [comment]
See also the discussion in https://github.com/nodejs/node-eps/pull/3, which is working on getting the newly-drafted WHATWG Loader spec into Node.js. @zkat and I are keeping an eye on that discussion, and other parties interested in figuring out the transition to ES6 modules should do so as well. I'm hopeful that npm will offer some meaningful support for this sometime this year.

**Comment by bmeck** [comment]
@othiym23 on that note, if we do use a file extension to differentiate there won't be a need for separate `main` fields as we can prioritize ES6 in the file extension resolution as higher than CJS

**Comment by jkrems** [comment]
Having a separate main field as an option might still be nice. It allows having the compiled CJS in a separate directory for packages that want to support both (and have more than a single file).

**Comment by bmeck** [comment]
@jkrems I had not thought of that, though symlinks would also work.

**Comment by bmeck** [comment]
ignore that comment, my tarball maker is not how npm does it by default (it strips symlinks)

**Comment by othiym23** [comment]
@bmeck Understood, but I do think there's room for npm to come up with a sensible way to handle packages that ship both ES6 and CJS in the same distribution. It's still not clear to me to me what that would look like, but I believe `"jsnext:main"` didn't arise out of a vacuum, and I'd like to understand the needs that motivated that and see if npm can codify that usage usefully.

**Comment by balupton** [comment]
Is there still a proposal here? Seems it is more a discussion about how to point to a ES2015 compiled version, and how to point to a ESNext version of the same package, for use in bundlers. I tried to raise it over at the ES modules discussion here: https://github.com/nodejs/node-eps/pull/3#issuecomment-184962845

But seems their discussion is more focused on ES vs CJS module compat, rather than specifically bundlers and build tools.

At Bevry, we've been using the guide here https://github.com/bevry/esnextguardian for handling this issue, however it really should be a more thorough discussion that isn't tied to any particular place or team - as the many variances of how to do accomplish this shows it has more or less been vacuums by everyone.

**Comment by balupton** [comment]
I've been working on https://github.com/bevry/base/issues/21#issuecomment-185570359 which is a proposal for such a thing but with multiple editions so: source (for bundlers) + esnext (for future node) + es2015 (for node 4) + es5 (for node 0.10 and IE8)
