### ISSUE TITLE
Update the documentation about "npm start"

### ISSUE THREAD

**Issue by wyattbiker** [npm/npm#9460]
Took me a while to figure out where npm start it finds things. Here is great answer to the question:

https://stackoverflow.com/questions/11716421/difference-between-npm-start-node-app-js-when-starting-app/11716667#11716667

```
From the man page, npm start:

runs a package's "start" script, if one was provided. If no version is specified, then it starts the "active" version.
Admittedly, that description is completely unhelpful, and that's all it says. At least it's more documented than socket.io.

Anyhow, what really happens is that npm looks in your package.json file, and if you have something like

"scripts": { "start": "coffee server.coffee" }
then it will do that. If npm can't find your start script, it defaults to:

node server.js
```

**Comment by othiym23** [comment]
The current description in `npm help start` is terse, like much of npm's documentation, but between the docs for [`npm start`](https://docs.npmjs.com/cli/start), [`npm run-script`](https://docs.npmjs.com/cli/run-script), [`scripts`](https://docs.npmjs.com/misc/scripts), and [`package.json`](https://docs.npmjs.com/files/package.json#scripts), the documentation is pretty comprehensive. There's a constant tension in npm's docs in figuring out the right places to put things, and it's not as easy to navigate from one bit of the documentation to another, but it gets tough when you start trying to maintain the same information in multiple places.
