### ISSUE TITLE
npm err registry error parsing json

### ISSUE THREAD

**Issue by wowbruce** [npm/npm#9462]
install ionic error:  npm err registry error parsing json

**Comment by wowbruce** [comment]
who can help me  .

**Comment by KenanY** [comment]
@wowbruce Is there a `npm-debug.log` that you can upload as a [gist](https://gist.github.com/)?

**Comment by mnamutso** [comment]
I get the same error too when i run > npm install -g karma karma-coverage

https://gist.github.com/mnamutso/bb566b6a7da564806a7d

**Comment by mnamutso** [comment]
Hello,

Does anyone have a work around on this issue?

**Comment by tcpip98** [comment]
I'm facing same error too frequently, but sometimes it succeeded.
And npm requires new updated package.json version every time I'm trying publish. even if my previous publishing was failed with "ERR! registry error parsing json".

npm says,
````
    Please include the following file with any support request:
    D:\git\my-location\npm-debug.log
````
but there is no *.log file.

**Comment by chrislaughlin** [comment]
What version of npm/node do you have installed?
