### ISSUE TITLE
Running npm update replace dependency to file / local module

### ISSUE THREAD

**Issue by pveyes** [npm/npm#9464]
**How to repro**: run `npm update` with `package.json` like below
```json
{
  "dependencies": {
    "something": "file:path/to/something"
  }
}
```

**Current behavior**: Replace `something` dependency in `package.json` with the one found in npm registry (or error if not exists), and generate `package.json` like below
```json
{
  "dependencies": {
    "something": "^2.1.1"
  }
}
```

**Expected behavior**: Update `node_modules/something` with updated code in `path/to/something`, and don't touch `something` dependency in `package.json`

**Comment by KenanY** [comment]
@pveyes `npm --version`?

**Comment by pveyes** [comment]
Ah sorry forgot to include that, just realized I have `npm v2.10.1`. Updated npm and problem solved
