### ISSUE TITLE
npm ERR! agar.io minimap server

### ISSUE THREAD

**Issue by Dominiik** [npm/npm#9466]
Hey,
This is npm debug log:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose config Skipping project config: C:\Users\loncar/.npmrc. (matches userconfig)
5 verbose stack Error: ENOENT, open 'C:\Users\loncar\package.json'
5 verbose stack     at Error (native)
6 verbose cwd C:\Users\loncar
7 error Windows_NT 6.1.7601
8 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
9 error node v0.12.7
10 error npm  v2.11.3
11 error path C:\Users\loncar\package.json
12 error code ENOENT
13 error errno -4058
14 error enoent ENOENT, open 'C:\Users\loncar\package.json'
14 error enoent This is most likely not a problem with npm itself
14 error enoent and is related to npm not being able to find a file.
15 verbose exit [ -4058, true ]

Im trying to create agar.io minimap server with node.js but dont know whats wrong
All i did is type: cd d:\agar\server  to direct to this map
Then type: npm run build
But it brings error

**Comment by KenanY** [comment]
@Dominiik Looks like you did not `cd` into the directory you wanted to. `npm` still says you are in your home directory:

```
6 verbose cwd C:\Users\loncar
```

**Comment by Dominiik** [comment]
@KenanY   I typed cd f:\agar
So how should i cd into that directory? Idk what i'm doing wrong

**Comment by KenanY** [comment]
@Dominiik Could you verify that the directory actually exists? I personally don't know where you have the directory so I can't tell you where to `cd` into.

**Comment by Dominiik** [comment]
@KenanY It works now, anyways thanks for help!
I was still on the c:\users, so i needed to type d:\ than cd d:\agar\server

**Comment by ehsalazar** [comment]
@Dominiik Good to hear. I'll close this for now as we’re trying to clean up some solved issues. We’ll be happy to reopen if necessary.
