### ISSUE TITLE
ionic that installed in my system diappeared 

### ISSUE THREAD

**Issue by abintjohn** [npm/npm#9467]
once i successfully installed ionic but suddenly it disappeared from system and when i input ionic in cmd it shows that 'íonic' is not recognized as an internal or external command,operable program or batch file.

**Comment by KenanY** [comment]
@abintjohn I doubt `npm` would cause such a sudden disappearance unless you explicitly told `npm` to uninstall ionic or you changed your `PATH` in such a way as to make ionic not be part of it anymore. Why don't you just try re-installing it, or checking to see if it is in your global `node_modules/` directory?

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some issues. Were you able to find ionic in your `node_modules/` directory or perhaps re-installing it worked? If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.
