### ISSUE TITLE
npm install --only=development dont work in windows

### ISSUE THREAD

**Issue by feeel1** [npm/npm#9468]
Commands:
npm install --development
npm install --dev
npm install --only=dev
npm install --only=development
npm install --only={development}
npm install --only={dev}
install all packages: development and production.

os: Windows7
npm 2.7.4 and 2.10.1
node 0.12.2 and 0.12.4

**Comment by suenot** [comment]
:+1:  Another problem in windows

**Comment by othiym23** [comment]
The `--only` and `--also` options are only in `npm@3`, and won't be backported to `npm@2` releases, as they're a decent-sized feature and we're cutting everything over to `npm@3`. `npm@3` is a manual upgrade right now, which is admittedly a little tricky on Windows, but it will be entering general release very soon, at which point it will be bundled with some version of Node.
