### ISSUE TITLE
Error while npm publish 

### ISSUE THREAD

**Issue by Anikakp** [npm/npm#9475]

**Comment by Anikakp** [comment]
Tried to login to npm using npm adduser command but getting below error. I am able to login at the parent directory. Any specific reason ?

0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   '/home/ubuntu/.nvm/v0.10.35/bin/npm',
1 verbose cli   '--color=always',
1 verbose cli   'view',
1 verbose cli   '@*****/workshop' ]
2 info using npm@2.14.1
3 info using node@v0.10.35
4 silly mapToRegistry name @*****/workshop
5 silly mapToRegistry scope (from package name) @*****
6 verbose mapToRegistry no registry URL found in name for scope @*****
7 silly mapToRegistry using default registry
8 silly mapToRegistry registry http://localhost:15443/
9 silly mapToRegistry uri http://localhost:15443/@*****%2fworkshop
10 verbose request uri http://localhost:15443/@*****%2fworkshop
11 verbose request no auth needed
12 info attempt registry request try #1 at 23:00:23
13 verbose request id 676d7907d01f00c0
14 http request GET http://localhost:15443/@anikakp%2fworkshop
15 info retry will retry, error on last attempt: Error: connect ECONNREFUSED
16 info attempt registry request try #2 at 23:00:33
17 http request GET http://localhost:15443/@anikakp%2fworkshop
18 info retry will retry, error on last attempt: Error: connect ECONNREFUSED
19 info attempt registry request try #3 at 23:01:33
20 http request GET http://localhost:15443/@anikakp%2fworkshop
21 verbose stack Error: connect ECONNREFUSED
21 verbose stack     at errnoException (net.js:905:11)
21 verbose stack     at Object.afterConnect [as oncomplete] (net.js:896:19)
22 verbose cwd /home/ubuntu/workspace/workshop
23 error Linux 3.14.13-c9
24 error argv "node" "/home/ubuntu/.nvm/v0.10.35/bin/npm" "--color=always" "view" "@anikakp/workshop"
25 error node v0.10.35
26 error npm  v2.14.1
27 error code ECONNREFUSED
28 error errno ECONNREFUSED
29 error syscall connect
30 error Error: connect ECONNREFUSED
30 error     at errnoException (net.js:905:11)
30 error     at Object.afterConnect [as oncomplete] (net.js:896:19)
30 error  { [Error: connect ECONNREFUSED]
30 error   code: 'ECONNREFUSED',
30 error   errno: 'ECONNREFUSED',
30 error   syscall: 'connect' }
31 error If you are behind a proxy, please make sure that the
31 error 'proxy' config is set properly.  See: 'npm help config'
32 verbose exit [ 1, true ]

**Comment by sinkingshriek** [comment]
>verbose request uri http://localhost:15443/@

This should give you a hint on what registry it's trying to connect to. What does it say when you do `npm get registry` ?

**Comment by Anikakp** [comment]
http://localhost:15443/  how do I change it.

**Comment by sinkingshriek** [comment]
`npm config set registry https://registry.npmjs.org/`  
Try the above and see if it works with the original issue.

**Comment by Anikakp** [comment]
I am getting below error on changing registry URL. 

npm ERR! Linux 3.14.13-c9
npm ERR! argv "node" "/home/ubuntu/.nvm/v0.10.35/bin/npm" "login"
npm ERR! node v0.10.35
npm ERR! npm  v2.14.1
npm ERR! code E404

npm ERR! 404 missing : -/user/org.couchdb.user:*****

**Comment by sinkingshriek** [comment]
That's odd. Can you even login with `npm login`?

**Comment by Anikakp** [comment]
npm login also gives the same error. Not able to login.

**Comment by sinkingshriek** [comment]
Hm..this is tricky. From the error it seems like you're trying to hit the resource that doesn't even exist. This might be pretty obvious and stupid thing to ask but have you registered an account on npm? If so, then would you mind posting the log one more time but this time with `silly` loglevel?
`npm login --loglevel=silly`

**Comment by Anikakp** [comment]
Yes, have registered account on npm. I am able to login to npm. 

Here is the log.

npm info it worked if it ends with ok
npm verb cli [ 'node',
npm verb cli   '/home/ubuntu/.nvm/v0.10.35/bin/npm',
npm verb cli   'login',
npm verb cli   '--loglevel=silly' ]
npm info using npm@2.14.1
npm info using node@v0.10.35
Username: anikakp
Password: 
Email: (this IS public) anikakp@gmail.com
npm verb adduser before first PUT { _id: 'org.couchdb.user:anikakp',
npm verb adduser   name: 'anikakp',
npm verb adduser   password: 'XXXXX',
npm verb adduser   email: '*********',
npm verb adduser   type: 'user',
npm verb adduser   roles: [],
npm verb adduser   date: '2015-09-10T18:28:38.541Z' }
npm verb request uri https://registry.npmjs.org/-/user/org.couchdb.user:anikakp
npm verb request new user, so can't send auth
npm info attempt registry request try #1 at 18:28:38
npm verb request id 7973fd9665cf54dd
npm http request PUT https://registry.npmjs.org/-/user/org.couchdb.user:anikakp
npm http 400 https://registry.npmjs.org/-/user/org.couchdb.user:anikakp
npm verb headers { 'content-type': 'application/json',
npm verb headers   'cache-control': 'max-age=60',
npm verb headers   'content-length': '57',
npm verb headers   'accept-ranges': 'bytes',
npm verb headers   date: 'Thu, 10 Sep 2015 18:28:39 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-ord1721-ORD',
npm verb headers   'x-cache': 'MISS',
npm verb headers   'x-cache-hits': '0',
npm verb headers   'x-timer': 'S1441909718.648663,VS0,VE455' }
npm verb request invalidating /home/ubuntu/.npm/registry.npmjs.org/-/user/org.couchdb.user_3Aanikakp on PUT
npm verb adduser back [ { [Error: Unknown error while authenticating : -/user/org.couchdb.user:anikakp] statusCode: 400, code: 'E400' },
npm verb adduser   { ok: false, error: 'Unknown error while authenticating' },
npm verb adduser   '{"ok":false,"error":"Unknown error while authenticating"}' ]
npm verb stack Error: Unknown error while authenticating : -/user/org.couchdb.user:anikakp
npm verb stack     at makeError (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:263:12)
npm verb stack     at CachingRegistryClient.<anonymous> (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:251:14)
npm verb stack     at Request._callback (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:171:14)
npm verb stack     at Request.self.callback (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/npm/node_modules/request/request.js:198:22)
npm verb stack     at Request.emit (events.js:98:17)
npm verb stack     at Request.<anonymous> (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/npm/node_modules/request/request.js:1073:14)
npm verb stack     at Request.emit (events.js:117:20)
npm verb stack     at IncomingMessage.<anonymous> (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/npm/node_modules/request/request.js:1019:12)
npm verb stack     at IncomingMessage.emit (events.js:117:20)
npm verb stack     at _stream_readable.js:944:16
npm verb statusCode 400
npm verb cwd /home/ubuntu/workspace
npm ERR! Linux 3.14.13-c9
npm ERR! argv "node" "/home/ubuntu/.nvm/v0.10.35/bin/npm" "login" "--loglevel=silly"
npm ERR! node v0.10.35
npm ERR! npm  v2.14.1
npm ERR! code E400

npm ERR! Unknown error while authenticating : -/user/org.couchdb.user:anikakp
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/npm-debug.log

**Comment by Anikakp** [comment]
I was able to resolve the issue. Had to change registry URL in .npmrc file and it worked. It was still pointing to localhost in-spite of setting config to npmjs registry. Thanks for your time.

**Comment by ionakathryn** [comment]
I am having the same problem. I checked using 'get registry' and it's http://localhost:15443/

I then checked my .npmrc and this is what it says. How do I solve this? I am also unable to npm login.

Thanks
