### ISSUE TITLE
Custom README path?

### ISSUE THREAD

**Issue by mikemorris** [npm/npm#9481]
I'd like to be able to define a custom README path in `package.json`, as the `README.md` file in the root directory pertains to the core C++ project, while the README for the Node C++ addon lives in a subdirectory.

**Comment by othiym23** [comment]
This would indeed be useful, and to get this functionality landed, changes would be needed to `fstream-npm` (to make sure the correct README gets included in the package) and `read-package-json` and / or `normalize-package-data` (so that the CLI knows where to find the README).

**Comment by othiym23** [comment]
The team needs to get out a new version of `read-package-json` that includes the patch, and then we'll need a small PR including the updated dependency and a tweak to the documentation to reflect that this is now configurable, and then we'll get this in!
