### ISSUE TITLE
NPM Error when trying to repo git. 

### ISSUE THREAD

**Issue by kimberlyliew** [npm/npm#9484]
```
$ npm install
npm WARN package.json proto-watch@1.1.0 No license field.
npm WARN package.json Dependency 'grunt-sass' exists in both dependencies and devDependencies, using 'grunt-sass@^0.18.1' from dependencies
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:751:12)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:110:17)
npm WARN addRemoteGit     at maybeClose (child_process.js:1015:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
npm WARN addRemoteGit  git://github.com/bessdsv/bower-installer.git#temp resetting remote C:\Users\Kimberly Liew\AppData\Roaming\npm-cache\_git-remotes\git-github-com-bessdsv-bower-installer-git-8c0433f6 because of error: { [Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! git clone --template=C:\Users\Kimberly Liew\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/bessdsv/bower-installer.git C:\Users\Kimberly Liew\AppData\Roaming\npm-cache\_git-remotes\git-github-com-bessdsv-bower-installer-git-8c0433f6: Cloning into bare repository 'C:\Users\Kimberly Liew\AppData\Roaming\npm-cache\_git-remotes\git-github-com-bessdsv-bower-install                     er-git-8c0433f6'...
npm ERR! git clone --template=C:\Users\Kimberly Liew\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/bessdsv/bower-installer.git C:\Users\Kimberly Liew\AppData\Roaming\npm-cache\_git-remotes\git-github-com-bessdsv-bower-installer-git-8c0433f6: fatal: unable to connect to github.com:
npm ERR! git clone --template=C:\Users\Kimberly Liew\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/bessdsv/bower-installer.git C:\Users\Kimberly Liew\AppData\Roaming\npm-cache\_git-remotes\git-github-com-bessdsv-bower-installer-git-8c0433f6: github.com[0: 192.30.252.128]: errno=No error
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\Kimberly Liew\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/bessdsv/bower-installer.git C:\Users\Kimberly Liew\AppData\Roaming\npm-cache\_git-remotes\git-github-com-bessdsv-bower-installer-git-8c0433f6
npm ERR! Cloning into bare repository 'C:\Users\Kimberly Liew\AppData\Roaming\npm-cache\_git-remotes\git-github-com-bessdsv-bower-installer-git-8c0433f6'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.128]: errno=No error
npm ERR!
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Kimberly Liew\Desktop\LevelUp\melb_watch_edition_blue\npm-debug.log
```

I've tried changing to https:// not working. 
clearing cache and removed module. Still not working

**Comment by KenanY** [comment]
@kimberlyliew 

```
npm ERR! fatal: unable to connect to github.com:
```

Looks like an internet connection issue with regards to connecting to `github.com`. Are you behind a proxy or firewall that might be blocking `git`'s requests?

**Comment by kimberlyliew** [comment]
I'm using University's WiFi actually. Or is it the firewall on my console?

**Comment by kimberlyliew** [comment]
I managed to use my own wifi connection. Mnaged to connect to github
but there are some dependency errors. 

$ npm install
npm WARN package.json proto-watch@1.1.0 No license field.
npm WARN package.json Dependency 'grunt-sass' exists in both dependencies and devDependencies, using 'grunt-sass@^0.18.1' from dependencies
npm WARN unmet dependency C:\Users\Kimberly Liew\Desktop\LevelUp\melb_watch_edition_blue\node_modules\browserify requires glob@'^4.0.5' but will load
npm WARN unmet dependency C:\Users\Kimberly Liew\Desktop\LevelUp\melb_watch_edition_blue\node_modules\glob,
npm WARN unmet dependency which is version 5.0.14
npm WARN unmet dependency C:\Users\Kimberly Liew\Desktop\LevelUp\melb_watch_edition_blue\node_modules\grunt-prompt requires lodash@'~2.4.1' but will load
npm WARN unmet dependency C:\Users\Kimberly Liew\Desktop\LevelUp\melb_watch_edition_blue\node_modules\lodash,
npm WARN unmet dependency which is version 3.10.1
npm WARN unmet dependency C:\Users\Kimberly Liew\Desktop\LevelUp\melb_watch_edition_blue\node_modules\load-grunt-config requires glob@'~3.2.6' but will load
npm WARN unmet dependency C:\Users\Kimberly Liew\Desktop\LevelUp\melb_watch_edition_blue\node_modules\glob,
npm WARN unmet dependency which is version 5.0.14
npm WARN unmet dependency C:\Users\Kimberly Liew\Desktop\LevelUp\melb_watch_edition_blue\node_modules\glob\node_modules\once\node_modules\wrappy\node_modules\tap\node_modules\glob requires minimatch@'0.3' but will load
npm WARN unmet dependency C:\Users\Kimberly Liew\Desktop\LevelUp\melb_watch_edition_blue\node_modules\minimatch,
npm WARN unmet dependency which is version 2.0.10
npm WARN unmet dependency C:\Users\Kimberly Liew\Desktop\LevelUp\melb_watch_edition_blue\node_modules\minimatch\node_modules\browserify requires glob@'^4.0.5' but will load
npm WARN unmet dependency C:\Users\Kimberly Liew\Desktop\LevelUp\melb_watch_edition_blue\node_modules\glob,
npm WARN unmet dependency which is version 5.0.14
npm WARN unmet dependency C:\Users\Kimberly Liew\Desktop\LevelUp\melb_watch_edition_blue\node_modules\minimatch\node_modules\brace-expansion\node_modules\tape requires glob@'~3.2.9' but will load
npm WARN unmet dependency C:\Users\Kimberly Liew\Desktop\LevelUp\melb_watch_edition_blue\node_modules\glob,
npm WARN unmet dependency which is version 5.0.14
npm WARN unmet dependency C:\Users\Kimberly Liew\Desktop\LevelUp\melb_watch_edition_blue\node_modules\minimatch\node_modules\standard\node_modules\dezalgo\node_modules\asap\node_modules\jshint requires lodash@'3.7.x' but will load
npm WARN unmet dependency C:\Users\Kimberly Liew\Desktop\LevelUp\melb_watch_edition_blue\node_modules\lodash,
npm WARN unmet dependency which is version 3.10.1
npm WARN unmet dependency C:\Users\Kimberly Liew\Desktop\LevelUp\melb_watch_edition_blue\node_modules\minimatch\node_modules\standard\node_modules\dezalgo\node_modules\asap\node_modules\wd requires lodash@'~2.4.1' but will load
npm WARN unmet dependency C:\Users\Kimberly Liew\Desktop\LevelUp\melb_watch_edition_blue\node_modules\lodash,

**Comment by othiym23** [comment]
You might want to remove `node_modules` altogether (if Explorer won't let you because of path length issues, run `npm -g install rimraf` and then `rimraf node_modules` in your project directory) and run `npm install` again -- it seems that npm left things in an inconsistent state during a previous run. You might also want to [upgrade to the latest stable npm](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows), because it has a few new fixes to problems with npm's git support.

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.
