### ISSUE TITLE
gulp issues with l5beauty ...... page 98 of the pdf document ....

### ISSUE THREAD

**Issue by arnoldjp57** [npm/npm#9486]
Hi  ... Having issues with  gulp  .... have tried a few google goodies, but is getting worse now. Can someone tell me how to get past the following error ..... The issue started when I had to run gulp twice .....      gulp copyfiles and then gulp  ...... Got an error that gulp-util was missing ... went downhill from there :-) 

vagrant@homestead:~/Code/odie$ uname -a
Linux homestead 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

vagrant@homestead:~/Code/odie$ sudo npm install gulp
npm WARN engine get-stdin@5.0.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.37","npm":"1.4.28"})
npm ERR! Error: UNKNOWN, symlink '../semver/bin/semver'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.13.0-24-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "gulp"
npm ERR! cwd /home/vagrant/Code/odie
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! path ../semver/bin/semver
npm ERR! code UNKNOWN
npm ERR! errno -1
npm ERR! not ok code 0

**Comment by KenanY** [comment]
@arnoldjp57 Is this Vagrant on top of Windows?

**Comment by arnoldjp57** [comment]
Hi ... yes, on Windows 10 ....  BUT, I have managed to get it working .... I updated the version on npm and went thru all the steps again to do the gulp copyfiles and gulp ... there were lots of missing packages that I had to download and it eventually worked ....
