### ISSUE TITLE
`npm install` should fail (or ask the user if they'd like to init) when there is no package.json present 

### ISSUE THREAD

**Issue by jcollum** [npm/npm#9490]
```
$ versions
npm 2.11.3
node v0.12.7

10:44 ~/work/trx_projects $ pushd ~/temp
~/temp ~/work/trx_projects

10:44 ~/temp $ mkcd stuff

10:44 ~/temp/stuff $ npm install moment
npm WARN package.json trx-mover@0.1.0 No README data
moment@2.10.6 ../node_modules/moment

10:44 ~/temp/stuff $ ll

10:44 ~/temp/stuff $ ls

10:44 ~/temp/stuff $ ll node_modules
ls: node_modules: No such file or directory

10:45 ~/temp/stuff $ ll package.json
ls: package.json: No such file or directory

10:48 ~/temp/stuff $ 
```

Two issues here, one is a feature request, one is a bug (or something). 
1. Feature: NPM should either require a `package.json` file to be present (maybe a suggestion to run `npm init -y`?) or create a node_modules directory. As it is, the install runs but nothing happens, no node_modules is created. Some installs (e.g. AMQP libs) have a lot of node-gyp stuff running during install, so it's a bit of a wait for nothing to happen.  
2. Bug: see above: `npm WARN package.json trx-mover@0.1.0 No README data` -- where the heck is it getting `trx-mover@0.1.0` from? I was in that directory a bit ago but when I ran the npm install I was not in that directory. Is this related to `pushd`? Fixed in NPM 3?

**Comment by othiym23** [comment]
```
moment@2.10.6 ../node_modules/moment
```

...is the answer to both of your questions. If there's no `package.json` in the present directory, npm will recursively crawl up the filesystem looking for a `package.json` file or `node_modules` directory, and will install the package in the first `node_modules` it finds. So, in this example, it's putting moment in the `node_modules` directory in the parent directory from where you are right now, and that's also where it's finding `trx-mover`.

It's true that this can be surprising if you're not aware of it, but it is [documented behavior](https://docs.npmjs.com/files/folders#more-information). I could see prompting to init on `npm install --save` if the software follows the documented algorithm and doesn't find a `node_modules` or `package.json` during its search for prefixes, but that would probably present its own set of surprises. What do you think?

**Comment by jcollum** [comment]
First I want to say that I really appreciate your professionalism regarding the npm github issue tracker.

You're right, I kinda missed the `../node_modules` -- npm was telling me where it was installing but in a subtle way. The existing behavior is both sensible and confusing. 

Confusing because if I'm in a directory that is a subdirectory (or sub-sub) of a dir that has a `node_modules` folder it will install to the folder in the parent directory -- which in this case I didn't realize existed, it wasn't supposed to be there. I had accidentally copied a `package.json` and `node_modules` folder into `~/temp`. 

Sensible because if I'm in a subdir of an actual project and want to install a lib, I shouldn't have to cd to the root of the project to install. 

My general rule when logging is to send a Warning message if I'm making assumptions about what the end user intended. So my preference in this situation would be to log a WARN and say, in effect, "hey, you don't have a node_modules folder in this directory, so I'm gonna go searching..." then "ok I found one and it's at /home/Users/jcollum/temp, I'm using that now"
