### ISSUE TITLE
npm tries to install in the wrong place

### ISSUE THREAD

**Issue by sauergeek** [npm/npm#9491]
I recently built node 0.12.7, and am now trying to install madoko.  However, when I try that install, I get:

> npm install madoko -g
npm ERR! tar.unpack untar error /h/<user>/.npm/madoko/0.9.2-beta/package.tgz
npm ERR! Linux 2.6.32-573.1.1.el6.x86_64
npm ERR! argv "node" "/usr/local/bin/npm" "install" "madoko" "-g"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.2
npm ERR! path /usr/local/lib/node_modules/madoko
npm ERR! code EROFS
npm ERR! errno -30

npm ERR! rofs EROFS, mkdir '/usr/local/lib/node_modules/madoko'
npm ERR! rofs This is most likely not a problem with npm itself
npm ERR! rofs and is related to the file system being read-only.
npm ERR! rofs
npm ERR! rofs Often virtualized file systems, or other file systems
npm ERR! rofs that don't support symlinks, give this error.

npm ERR! Please include the following file with any support request:
npm ERR!     /h/<user>/npm-debug.log

When I built node, I gave it the prefix /usr/local/node-0.12.7, and have installed it there.  /usr/local/node-0.12.7 in a read-write filesystem, and I have write permissions on it.  However, there's also a symlink tree in /usr/local:

> ls -al /usr/local/bin/npm
lrwxrwxrwx. 1 root root 22 Sep  4 14:15 /usr/local/bin/npm -> ../node-0.12.7/bin/npm

That symlink tree is in a different, read-only file system.  (There are ugly automount tricks in play here).

It is trying to install to /usr/local/lib/node_modules/madoko instead of /usr/local/node-0.12.7/lib/node_modules/madoko.  This happens even if I invoke npm in its actual location, /usr/local/node-0.12.7/bin/npm.

Why will it not try the install in /usr/local/node-0.12.7/lib/node_modules/madoko ?

**Comment by sauergeek** [comment]
And, because I see no way to attach the debug log, here it is in all its glory:
---------------------------------------
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', 'madoko', '-g' ]
2 info using npm@2.14.2
3 info using node@v0.12.7
4 verbose node symlink /usr/local/bin/node
5 verbose install initial load of /usr/local/lib/package.json
6 verbose readDependencies loading dependencies from /usr/local/lib/package.json
7 silly cache add args [ 'madoko', null ]
8 verbose cache add spec madoko
9 silly cache add parsed spec { raw: 'madoko',
9 silly cache add   scope: null,
9 silly cache add   name: 'madoko',
9 silly cache add   rawSpec: '',
9 silly cache add   spec: '*',
9 silly cache add   type: 'range' }
10 silly addNamed madoko@*
11 verbose addNamed "*" is a valid semver range for madoko
12 silly addNameRange { name: 'madoko', range: '*', hasData: false }
13 silly mapToRegistry name madoko
14 silly mapToRegistry using default registry
15 silly mapToRegistry registry https://registry.npmjs.org/
16 silly mapToRegistry uri https://registry.npmjs.org/madoko
17 verbose addNameRange registry:https://registry.npmjs.org/madoko not in flight; fetching
18 verbose request uri https://registry.npmjs.org/madoko
19 verbose request no auth needed
20 info attempt registry request try #1 at 14:28:44
21 verbose request id 9ecdf52d27f46738
22 verbose etag "4F8NJQLR6I53YQ4E6NJE16WFB"
23 http request GET https://registry.npmjs.org/madoko
24 http 304 https://registry.npmjs.org/madoko
25 silly get cb [ 304,
25 silly get   { date: 'Fri, 04 Sep 2015 18:28:44 GMT',
25 silly get     via: '1.1 varnish',
25 silly get     'cache-control': 'max-age=60',
25 silly get     etag: '"4F8NJQLR6I53YQ4E6NJE16WFB"',
25 silly get     age: '0',
25 silly get     connection: 'keep-alive',
25 silly get     'x-served-by': 'cache-iad2141-IAD',
25 silly get     'x-cache': 'MISS',
25 silly get     'x-cache-hits': '0',
25 silly get     'x-timer': 'S1441391324.724119,VS0,VE198',
25 silly get     vary: 'Accept' } ]
26 verbose etag https://registry.npmjs.org/madoko from cache
27 verbose get saving madoko to /h/<user>/.npm/registry.npmjs.org/madoko/.cache.json
28 silly addNameRange number 2 { name: 'madoko', range: '*', hasData: true }
29 silly addNameRange versions [ 'madoko',
29 silly addNameRange   [ '0.1.0-alpha',
29 silly addNameRange     '0.1.1-alpha',
29 silly addNameRange     '0.2.0-beta',
29 silly addNameRange     '0.3.0-beta',
29 silly addNameRange     '0.3.1-beta',
29 silly addNameRange     '0.4.0-beta',
29 silly addNameRange     '0.4.2-beta',
29 silly addNameRange     '0.4.4-beta',
29 silly addNameRange     '0.4.6-beta',
29 silly addNameRange     '0.4.8-beta',
29 silly addNameRange     '0.5.0-beta',
29 silly addNameRange     '0.5.2-beta',
29 silly addNameRange     '0.5.4-beta',
29 silly addNameRange     '0.6.1-beta',
29 silly addNameRange     '0.6.2-beta',
29 silly addNameRange     '0.6.3-beta',
29 silly addNameRange     '0.6.5-beta',
29 silly addNameRange     '0.6.7-beta',
29 silly addNameRange     '0.6.9-beta',
29 silly addNameRange     '0.7.3-beta',
29 silly addNameRange     '0.7.5-beta',
29 silly addNameRange     '0.7.7-beta',
29 silly addNameRange     '0.8.0-beta',
29 silly addNameRange     '0.8.2-beta',
29 silly addNameRange     '0.8.4-beta',
29 silly addNameRange     '0.9.0-beta',
29 silly addNameRange     '0.9.0-beta1',
29 silly addNameRange     '0.9.2-beta' ] ]
30 info addNameTag [ 'madoko', 'latest' ]
31 silly mapToRegistry name madoko
32 silly mapToRegistry using default registry
33 silly mapToRegistry registry https://registry.npmjs.org/
34 silly mapToRegistry uri https://registry.npmjs.org/madoko
35 verbose addNameTag registry:https://registry.npmjs.org/madoko already in flight; waiting
36 silly addNameTag next cb for madoko with tag latest
37 silly addNamed madoko@0.9.2-beta
38 verbose addNamed "0.9.2-beta" is a plain semver version for madoko
39 silly cache afterAdd madoko@0.9.2-beta
40 verbose afterAdd /h/<user>/.npm/madoko/0.9.2-beta/package/package.json not in flight; writing
41 verbose afterAdd /h/<user>/.npm/madoko/0.9.2-beta/package/package.json written
42 silly install resolved [ { name: 'madoko',
42 silly install resolved     author: { name: 'Daan Leijen, Microsoft Corp.' },
42 silly install resolved     version: '0.9.2-beta',
42 silly install resolved     homepage: 'http://madoko.codeplex.com',
42 silly install resolved     description: 'Madoko is a fast scholarly Markdown processor written in Koka',
42 silly install resolved     licenses: [ [Object] ],
42 silly install resolved     keywords:
42 silly install resolved      [ 'Madoko',
42 silly install resolved        'Markdown',
42 silly install resolved        'LaTeX',
42 silly install resolved        'Koka',
42 silly install resolved        'Microsoft',
42 silly install resolved        'Scholarly',
42 silly install resolved        'Academic' ],
42 silly install resolved     preferGlobal: true,
42 silly install resolved     main: './lib/madoko.js',
42 silly install resolved     bin: { madoko: './lib/cli.js' },
42 silly install resolved     directories: { lib: './lib', doc: './doc' },
42 silly install resolved     files: [ 'lib', 'styles', 'Jakefile.js', 'readme.md', 'license.txt' ],
42 silly install resolved     engines: { node: '>=0.10.0' },
42 silly install resolved     dependencies: { amdefine: '>=0.0.4', requirejs: '>=2.1', mkdirp: '>=0.3.5' },
42 silly install resolved     devDependencies: { jake: '>=0.7.6' },
42 silly install resolved     repository: { type: 'hg', url: 'https://hg.codeplex.com/madoko' },
42 silly install resolved     _id: 'madoko@0.9.2-beta',
42 silly install resolved     _shasum: 'e3dc97b99ec654a0c0cd63ee64a29dbe0d40f47f',
42 silly install resolved     _from: 'madoko@*',
42 silly install resolved     _npmVersion: '1.4.9',
42 silly install resolved     _npmUser: { name: 'daanl', email: 'daan@microsoft.com' },
42 silly install resolved     maintainers: [ [Object] ],
42 silly install resolved     dist:
42 silly install resolved      { shasum: 'e3dc97b99ec654a0c0cd63ee64a29dbe0d40f47f',
42 silly install resolved        tarball: 'http://registry.npmjs.org/madoko/-/madoko-0.9.2-beta.tgz' },
42 silly install resolved     _resolved: 'https://registry.npmjs.org/madoko/-/madoko-0.9.2-beta.tgz',
42 silly install resolved     readme: 'ERROR: No README data found!' } ]
43 info install madoko@0.9.2-beta into /usr/local/lib
44 info installOne madoko@0.9.2-beta
45 verbose installOne of madoko to /usr/local/lib not in flight; installing
46 verbose lock using /h/<user>/.npm/_locks/madoko-ad38ae671c57ac45.lock for /usr/local/lib/node_modules/madoko
47 silly install write writing madoko 0.9.2-beta to /usr/local/lib/node_modules/madoko
48 verbose unbuild lib/node_modules/madoko
49 silly gentlyRm /usr/local/lib/node_modules/madoko is being purged from base /usr/local
50 verbose gentlyRm don't care about contents; nuking /usr/local/lib/node_modules/madoko
51 verbose tar unpack /h/<user>/.npm/madoko/0.9.2-beta/package.tgz
52 verbose tar unpacking to /usr/local/lib/node_modules/madoko
53 silly gentlyRm /usr/local/lib/node_modules/madoko is being purged
54 verbose gentlyRm don't care about contents; nuking /usr/local/lib/node_modules/madoko
55 silly gunzTarPerm modes [ '700', '600' ]
56 error tar.unpack untar error /h/<user>/.npm/madoko/0.9.2-beta/package.tgz
57 verbose unlock done using /h/<user>/.npm/_locks/madoko-ad38ae671c57ac45.lock for /usr/local/lib/node_modules/madoko
58 verbose fstream_path /usr/local/lib/node_modules/madoko
59 verbose fstream_type Directory
60 verbose fstream_class DirWriter
61 verbose stack Error: EROFS, mkdir '/usr/local/lib/node_modules/madoko'
61 verbose stack     at Error (native)
62 verbose fstream_stack /usr/local/node-0.12.7/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:35:25
62 verbose fstream_stack /usr/local/node-0.12.7/lib/node_modules/npm/node_modules/mkdirp/index.js:47:53
62 verbose fstream_stack FSReqWrap.oncomplete (fs.js:95:15)
63 verbose cwd /h/<user>
64 error Linux 2.6.32-573.1.1.el6.x86_64
65 error argv "node" "/usr/local/bin/npm" "install" "madoko" "-g"
66 error node v0.12.7
67 error npm  v2.14.2
68 error path /usr/local/lib/node_modules/madoko
69 error code EROFS
70 error errno -30
71 error rofs EROFS, mkdir '/usr/local/lib/node_modules/madoko'
71 error rofs This is most likely not a problem with npm itself
71 error rofs and is related to the file system being read-only.
71 error rofs
71 error rofs Often virtualized file systems, or other file systems
71 error rofs that don't support symlinks, give this error.
72 verbose exit [ -30, true ]
73 verbose unbuild lib/node_modules/madoko
74 silly gentlyRm /usr/local/lib/node_modules/madoko is being purged from base /usr/local
75 verbose gentlyRm don't care about contents; nuking /usr/local/lib/node_modules/madoko

**Comment by othiym23** [comment]
> Why will it not try the install in `/usr/local/node-0.12.7/lib/node_modules/madoko`?

Because you haven't told it to yet.

```
$ npm config set prefix /usr/local/node-0.12.7
```

should tell npm to start installing packages to the right place. npm doesn't try to do anything clever or magical when determining its install prefix, nor does it pick up the value set for Node (because there's no necessary correlation between the two). Its default value is `/usr/local`, which is why you're seeing the behavior you're seeing.

If there's more than just you using npm on that box, you might want to run `sudo npm -g config set prefix /usr/local/node-0.12.7`, but that presumes that `/usr/local/etc` is writable.

**Comment by sauergeek** [comment]
/usr/local/etc is on the same read-only file system.  However, the following sequence worked:

> npm config set prefix /usr/local/node-0.12.7
> npm -g set prefix /usr/local/node-0.12.7
...and then adding an extra symlink into the symlink tree:
> ls -al /usr/local/etc/npmrc
lrwxrwxrwx. 1 root root 24 Sep  4 15:26 /usr/local/etc/npmrc -> ../node-0.12.7/etc/npmrc

I then got rid of my own .npmrc and .npm directory, and tried:

> npm -g install madoko

Which now works as expected.

Many thanks!

**Comment by othiym23** [comment]
Great! Closing as resolved!
