### ISSUE TITLE
The 'npm install' command is always no response, I have been waiting for more than 2 hours

### ISSUE THREAD

**Issue by simusco** [npm/npm#9494]
I run 'npm install' command on win7, it's always no response and no any error message for me. I think the npm should print some messages for user that will be better.

node -v v0.12.4
npm -v 2.10.1

there are some flles created by 'npm install' command :C:\Users\Administrator\AppData\Roaming\npm-cache.

```
registry.cnpmjs.org ---folder
registry.cnpmjs.org/sass  --folder
registry.cnpmjs.org/sass/.cache.json  --file
```

```
C:\Users\Administrator>npm install -d -g sass
npm info it worked if it ends with ok
npm info using npm@2.10.1
npm info using node@v0.12.4
npm info attempt registry request try #1 at 08:07:29
npm http request GET http://registry.cnpmjs.org/sass
npm http 200 http://registry.cnpmjs.org/sass
\
```

**Comment by othiym23** [comment]
It looks like you may indeed be experiencing a network hang. Is it possible for you to use a VPN or some other way to get a more direct connection to `registry.cnpmjs.org`? It looks like the CLI is doing what it's supposed to do. I'm sorry interacting with npm registries within China is so difficult. :/

**Comment by ehsalazar** [comment]
@simusco As with the your [other ticket](https://github.com/npm/npm/issues/9488), have you been able to get it worked out with the cnpmjs folks? Please let us know if we can help more on our side. We’ll be happy to reopen if necessary.
