### ISSUE TITLE
can not able to install ubuntu 14.04

### ISSUE THREAD

**Issue by dineshrabara** [npm/npm#9497]
please check npm log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'cordova',
1 verbose cli   'ionic' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 silly cache add args [ 'cordova', null ]
5 verbose cache add spec cordova
6 silly cache add args [ 'ionic', null ]
7 verbose cache add spec ionic
8 silly cache add parsed spec { raw: 'cordova',
8 silly cache add   scope: null,
8 silly cache add   name: 'cordova',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '_',
8 silly cache add   type: 'range' }
9 verbose addNamed cordova@_
10 silly addNamed semver.valid null
11 silly addNamed semver.validRange *
12 silly addNameRange { name: 'cordova', range: '_', hasData: false }
13 silly mapToRegistry name cordova
14 silly mapToRegistry using default registry
15 silly mapToRegistry registry http://192.168.1.195:8080/
16 silly mapToRegistry uri http://192.168.1.195:8080/cordova
17 verbose addNameRange registry:http://192.168.1.195:8080/cordova not in flight; fetching
18 silly cache add parsed spec { raw: 'ionic',
18 silly cache add   scope: null,
18 silly cache add   name: 'ionic',
18 silly cache add   rawSpec: '',
18 silly cache add   spec: '_',
18 silly cache add   type: 'range' }
19 verbose addNamed ionic@*
20 silly addNamed semver.valid null
21 silly addNamed semver.validRange *
22 silly addNameRange { name: 'ionic', range: '*', hasData: false }
23 silly mapToRegistry name ionic
24 silly mapToRegistry using default registry
25 silly mapToRegistry registry http://192.168.1.195:8080/
26 silly mapToRegistry uri http://192.168.1.195:8080/ionic
27 verbose addNameRange registry:http://192.168.1.195:8080/ionic not in flight; fetching
28 verbose request uri http://192.168.1.195:8080/cordova
29 verbose request no auth needed
30 info attempt registry request try #1 at 1:13:02 PM
31 verbose request id 342b447dddbd4ffa
32 http request GET http://192.168.1.195:8080/cordova
33 verbose request uri http://192.168.1.195:8080/ionic
34 verbose request no auth needed
35 info attempt registry request try #1 at 1:13:02 PM
36 http request GET http://192.168.1.195:8080/ionic
37 info retry will retry, error on last attempt: Error: connect EHOSTUNREACH
38 info retry will retry, error on last attempt: Error: connect EHOSTUNREACH
39 info attempt registry request try #2 at 1:13:12 PM
40 http request GET http://192.168.1.195:8080/cordova
41 info attempt registry request try #2 at 1:13:12 PM
42 http request GET http://192.168.1.195:8080/ionic
43 info retry will retry, error on last attempt: Error: connect EHOSTUNREACH
44 info retry will retry, error on last attempt: Error: connect EHOSTUNREACH
45 info attempt registry request try #3 at 1:14:14 PM
46 http request GET http://192.168.1.195:8080/cordova
47 info attempt registry request try #3 at 1:14:14 PM
48 http request GET http://192.168.1.195:8080/ionic
49 verbose stack Error: connect EHOSTUNREACH
49 verbose stack     at exports._errnoException (util.js:746:11)
49 verbose stack     at TCPConnectWrap.afterConnect [as oncomplete](net.js:983:19)
50 verbose cwd /home/dinesh/Desktop
51 error Linux 3.13.0-61-generic
52 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "cordova" "ionic"
53 error node v0.12.0
54 error npm  v2.5.1
55 error code EHOSTUNREACH
56 error errno EHOSTUNREACH
57 error syscall connect
58 error connect EHOSTUNREACH
59 error If you need help, you may report this error at:
59 error     http://github.com/npm/npm/issues
60 verbose exit [ 1, true ]

**Comment by sinkingshriek** [comment]
Give this a try and see if that works:-
`npm install mypackage --reg http://http://registry.npmjs.org/`

**Comment by dineshrabara** [comment]
i just try below both

sudo npm install -g cordova ionic --reg http://registry.npmjs.org/
npm install -g cordova ionic --reg http://registry.npmjs.org/

but does not work


On 6 September 2015 at 00:05, Yojan Shrestha <notifications@github.com>
wrote:

> Give this a try and see if that works:-
> npm install mypackage --reg http://http://registry.npmjs.org/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/npm/npm/issues/9497#issuecomment-137985519>.
>



-- 
Regards,

*Dinesh Rabara*
*software Developer*

**Comment by sinkingshriek** [comment]
Is the error same as before?

**Comment by dineshrabara** [comment]
Yes

**Comment by sinkingshriek** [comment]
Okay, sounds like a network issue on your side. Are you even able to ping `registry.npmjs.org` at all?

**Comment by dineshrabara** [comment]
please check attached screen

On 7 September 2015 at 09:10, Yojan Shrestha <notifications@github.com>
wrote:

> Okay, sounds like a network issue on your side. Are you even able to ping
> registry.npmjs.org at all?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/npm/npm/issues/9497#issuecomment-138171980>.
>



-- 
Regards,

*Dinesh Rabara*
*software Developer*

**Comment by busches** [comment]
@dineshrabara were able to get this resolved? Your last attachment did not come through.
