### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by curlymonkey** [npm/npm#9499]
Having trouble installing node on my mac. any help would be great
<img width="613" alt="screen shot 2015-09-06 at 09 25 39" src="https://cloud.githubusercontent.com/assets/6751493/9703358/4ec1feb4-5479-11e5-9865-ae4d01c48b73.png">

**Comment by sinkingshriek** [comment]
Hi, welcome to npm's issue tracker. This however does not appear to be a npm issue as it says in the error itself. :smiley: 
But to give you a brief oversight of what's happening from the error is that `npm` is trying to look for `package.json` (manifest file for node packages) and it's not finding in your `desktop` dir. 
If you're new to node then [nodeschool.io](http://nodeschool.io/) is a great place to start.

**Comment by KenanY** [comment]
@curlymonkey Are you still seeing this issue?

**Comment by KenanY** [comment]
Closing due to no response.
