### ISSUE TITLE
problem installing underscore

### ISSUE THREAD

**Issue by pinkanpaula** [npm/npm#9500]
Hi,

I'm facing a problem downloading underscore, I used the command 
npm install underscore  and  I got the following errors.

http GET https://registry.npmjs.org/underscore/-/underscore-1.5.0.tgz
55 error fetch failed https://registry.npmjs.org/underscore/-/underscore-1.5.0.tgz
56 silly lockFile 72adf75d--underscore-underscore-1-5-0-tgz https://registry.npmjs.org/underscore/-/underscore-1.5.0.tgz
57 silly lockFile d00c5b0c-underscore-1-5-0 underscore@1.5.0
58 silly lockFile 7629b758-underscore underscore@
59 error Error: SSL Error: CERT_UNTRUSTED
59 error     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/main.js:440:26)
59 error     at ClientRequest.g (events.js:185:14)
59 error     at ClientRequest.EventEmitter.emit (events.js:88:17)
59 error     at HTTPParser.parserOnIncomingClient (http.js:1455:7)
59 error     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:111:23)
59 error     at CleartextStream.socketOnData (http.js:1366:20)
59 error     at CleartextStream.CryptoStream._push (tls.js:492:27)
59 error     at SecurePair.cycle (tls.js:846:20)
59 error     at EncryptedStream.CryptoStream.write (tls.js:227:13)
59 error     at Socket.ondata (stream.js:38:26)

Any advice will be really appreciated!

Thanks & regards,

Paula

**Comment by thefourtheye** [comment]
It works fine for me. What is the npm version you are using? You might want to try with the latest available for your platform.

**Comment by KenanY** [comment]
@pinkanpaula Are you still seeing this issue?

**Comment by KenanY** [comment]
Closing due to no response.
