### ISSUE TITLE
Installing Zurb foundation-apps 

### ISSUE THREAD

**Issue by paulyorde** [npm/npm#9504]
When Creating a new app with Zurb foundation-apps, I get this:
Downloading the Foundation for Apps template...
Done downloading!

Installing dependencies...

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:559:26)

C:\Users\Owner\Documents>npm start
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! path C:\Users\Owner\Documents\package.json
npm ERR! code ENOENT
npm ERR! errno -4058

npm ERR! enoent ENOENT, open 'C:\Users\Owner\Documents\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
```
# 

Here is the npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose stack Error: ENOENT, open 'C:\Users\Owner\Documents\package.json'
4 verbose stack     at Error (native)
5 verbose cwd C:\Users\Owner\Documents
6 error Windows_NT 6.3.9600
7 error argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
8 error node v0.12.7
9 error npm  v2.11.3
10 error path C:\Users\Owner\Documents\package.json
11 error code ENOENT
12 error errno -4058
13 error enoent ENOENT, open 'C:\Users\Owner\Documents\package.json'
13 error enoent This is most likely not a problem with npm itself
13 error enoent and is related to npm not being able to find a file.
14 verbose exit [ -4058, true ]
```

**Comment by sinkingshriek** [comment]
QQ: Are you able to install any other npm packages at all? It looks like it failed to install dependencies for your zurb application and the subsequent errors are the result of that.

**Comment by paulyorde** [comment]
Yes, I am able, now, to install other packages. I guess it wasn't before, so I updated NPM, and now it does. Still, I am getting the same errors when I try to install foundation.

**Comment by paulyorde** [comment]
This is the error I'm getting when installing zurb, and I'm wondering if it's a permissions error?

npm WARN deprecated exec@0.1.4: deprecated in favor of builtin child_process.execFile
C:\Users\Owner\AppData\Roaming\npm\gulp -> C:\Users\Owner\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "foundation-cli" "bower" "gulp"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "foundation-cli" "bower" "gulp"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

**Comment by sinkingshriek** [comment]
It definitely doesn't look like a permission issue if you can install other packages globally too and I haven't seen much of a permission issue with Windows users.  
Are you behind firewall or a proxy?

**Comment by paulyorde** [comment]
Yes, I think so. I am using webroot security. I looked at the proxy settings and that doesn't seem to be an issue. Though, when I did this on the mac, I did have the same error, and that as far as I know shouldn't be behind a firewall?

**Comment by sinkingshriek** [comment]
It depends. If you're behind a corporate firewall then it doesn't matter which machine you use but if it's your home connection then you'd have to make sure none of the anti-virus are blocking the connection.

**Comment by johnweland** [comment]
I am getting the same error 

"npm WARN deprecated exec@0.1.4: deprecated in favor of builtin child_process.execFile"

**Comment by KenanY** [comment]
@johnweland Looks like a warning, not an error. You can run `npm ls exec` to see what modules are still using that deprecated `exec` module. Also your issue is not really the same as the errors that @paulyorde is seeing (although, yes, that line does appear in their log, but it's not the cause of the general issues they are having).

**Comment by idpokute** [comment]
@johnweland  I have exactly same problem. 
@KenanaY after I run npm ls exec, it shows npm ERR! code1

**Comment by olefredrik** [comment]
+1

**Comment by johnweland** [comment]
yeah had multiple tabs open and replied to the wrong thread. my bad.

**Comment by xtianF** [comment]
I am getting the same error, anything on this?... help
