### ISSUE TITLE
Installing NodeCG getting error on two different Mac's and a Window's OS

### ISSUE THREAD

**Issue by Baker** [npm/npm#9507]
Last login: Sat Sep  5 21:17:38 on ttys001
Macbook-Pro:nodecg admin$ cd ..
Macbook-Pro:com~apple~CloudDocs admin$ npm install  nodecg
 
> ws@0.6.5 install /Users/admin/Library/Mobile Documents/com~apple~CloudDocs/node_modules/nodecg/node_modules/obs-remote/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
 
> fsevents@0.3.8 install /Users/admin/Library/Mobile Documents/com~apple~CloudDocs/node_modules/nodecg/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
 
> utf-8-validate@1.1.0 install /Users/admin/Library/Mobile Documents/com~apple~CloudDocs/node_modules/nodecg/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
 
> bufferutil@1.1.0 install /Users/admin/Library/Mobile Documents/com~apple~CloudDocs/node_modules/nodecg/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
 
> utf-8-validate@1.1.0 install /Users/admin/Library/Mobile Documents/com~apple~CloudDocs/node_modules/nodecg/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
 
> bufferutil@1.1.0 install /Users/admin/Library/Mobile Documents/com~apple~CloudDocs/node_modules/nodecg/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "nodecg"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall read

npm ERR! network read ETIMEDOUT
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "nodecg"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2

npm ERR! Cannot read property 'emit' of null
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by KenanY** [comment]
@Baker Are you still seeing this issue?

**Comment by KenanY** [comment]
Closing due to no response.
