### ISSUE TITLE
cannot install npm packages on ubuntu

### ISSUE THREAD

**Issue by jaspi-lalbuat** [npm/npm#9511]
npm ERR! Linux 3.13.0-24-generic
npm ERR! argv "node" "/usr/bin/npm" "install" "express" "--save"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.2
npm ERR! path ../mime/cli.js
npm ERR! code EPROTO
npm ERR! errno -71

npm ERR! EPROTO, symlink '../mime/cli.js'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 3.13.0-24-generic
npm ERR! argv "node" "/usr/bin/npm" "install" "express" "--save"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.2
npm ERR! path npm-debug.log.9b0ad88e430181af9e9909119fb1473b
npm ERR! code ETXTBSY
npm ERR! errno -26

npm ERR! ETXTBSY, rename 'npm-debug.log.9b0ad88e430181af9e9909119fb1473b'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /vagrant/vagrant-mean/npm-debug.log

can somebody help?

**Comment by KenanY** [comment]
@jaspi-lalbuat Is this Vagrant on top of Windows?

**Comment by jaspi-lalbuat** [comment]
@KenanY yes it is

**Comment by KenanY** [comment]
@jaspi-lalbuat Have you tried running that command with the `--no-bin-links` flag?

**Comment by bobmshannon** [comment]
Having the same issues here with a Windows 10 host (ETXTBSY). No success with running vagrant as admin and using `npm --no-bin-links install`.

**Comment by KenanY** [comment]
Closing as abandoned. This issue would almost surely be fixed by disabling `bin-links`; if this is not the case then I can reopen.
