### ISSUE TITLE
Windows EACCES error on nodejs\node_modules

### ISSUE THREAD

**Issue by Kachilero** [npm/npm#9513]
```
C:\Program Files (x86)\nodejs\node_modules
npm ERR! code EACCES
```
I have been having this issue for a couple of months and can find no solution.
ANY time that I try to run `npm install -g` I get this error. I have tried a multitude of different possible solutions, but none work. Some of the things that I have tried are:
* Running `cmd` as administrator
* Using `gitshell`
* Using `runas /user:<localmachinename>\<AdministratorAccountName> "npm install -g"` (as well as with my user name)
* I've update npm to 3.2.0 using [npm-windows-upgrade](https://github.com/felixrieseberg/npm-windows-upgrade)
* Running CCleaner on the registry, didn't help

None of these solve the issue. I have been all over [stackoverflow](http://stackoverflow.com/), Googled every term that I could think of and looked through the open and closed issues on here to no avail. I can install packages locally - without the `-g` tag - but there are certain node packages that I would like to have available globally.

I have created a gist of the npm debug log [here](https://gist.github.com/Kachilero/bd91d85a90bbaea60ec9#file-npm-debug-log). WARNING: it is 20,000+ lines long

Windows Version: Windows 10 Home (upgraded from windows 7)
npm version: 3.2.0
node version: 0.12.1

Any help on this issue would be appreciated, even if this issue is deemed to not be one with npm itself.
Thank you in advance.

**Comment by Kachilero** [comment]
## UPDATE: 
I figured out how to fix this problem, so I'm putting it here for any other people that encounter this problem.

**What seemed to have be the problem**: Node and NPM at the version that I was running them CANNOT update inside of a Windows 10 (and probably 7) environment from the command line. They don't have the permission.

**SOLUTION**: Go to [nodejs.org](https://nodejs.org/en/) and download the windows installer. This will delete the old version, then install all new version (@ 4.0.0) of node and NPM (@ 2.14.2). After this, I was able to save modules globally.

**Comment by KenanY** [comment]
Closing as resolved then.
