### ISSUE TITLE
Problem with deploying on metro up

### ISSUE THREAD

**Issue by ggndpsingh** [npm/npm#9514]
This is the error I am getting.

Started TaskList: Deploy app 'qpinion' (linux)
[128.199.124.103] - Uploading bundle
[128.199.124.103] - Uploading bundle: SUCCESS
[128.199.124.103] - Setting up Environment Variables
[128.199.124.103] - Setting up Environment Variables: SUCCESS
[128.199.124.103] - Invoking deployment process
[128.199.124.103] x Invoking deployment process: FAILED
	
	-----------------------------------STDERR-----------------------------------
	yp -v v2.0.2
	gyp ERR! not ok 
	npm WARN package.json meteor-dev-bundle@0.0.0 No description
	npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
	npm WARN package.json meteor-dev-bundle@0.0.0 No README data
	npm WARN package.json meteor-dev-bundle@0.0.0 No license field.
	child_process: customFds option is deprecated, use stdio instead.
	../src/coroutine.cc: In function ‘void* find_thread_id_key(void*)’:
	../src/coroutine.cc:90:3: warning: ‘thread_id’ may be used uninitialized in this function [-Wmaybe-uninitialized]
	   if (tls == thread_id) {
	   ^
	js-bson: Failed to load c++ bson extension, using pure JS version
	  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
	                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
	Latest deployment failed! Reverted back to the previous version.
	-----------------------------------STDOUT-----------------------------------
	yles
	
	escape-string-regexp@1.0.3 node_modules/escape-string-regexp
	
	chalk@0.5.1 node_modules/chalk
	
	has-ansi@0.1.0 node_modules/has-ansi
	
	strip-ansi@0.3.0 node_modules/strip-ansi
	
	supports-color@0.2.0 node_modules/supports-color
	
	eachline@2.3.3 node_modules/eachline
	
	type-of@2.0.1 node_modules/type-of
	
	amdefine@1.0.0 node_modules/amdefine
	
	asap@2.0.3 node_modules/asap
	
	meteor-promise@0.4.6 node_modules/meteor-promise
	
	underscore@1.5.2 node_modules/underscore
	
	promise@7.0.4 node_modules/promise
	
	source-map-support@0.3.2 node_modules/source-map-support
	
	semver@4.1.0 node_modules/semver
	
	source-map@0.1.32 node_modules/source-map
	
	fibers@1.0.5 node_modules/fibers
	Waiting for MongoDB to initialize. (5 minutes)
	{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
	connected
	qpinion stop/waiting
	qpinion start/running, process 12165
	Waiting for 15 seconds while app is booting up
	Checking is app booted or not?
	qpinion stop/waiting
	qpinion start/running, process 12261
	----------------------------------------------------------------------------

I have tried updating and re-installing npm and node. I do not know what else I can do to fix these problems as I'm fairly new to this. 
I checked the log with mup logs -n 400 and this is what I get from that, quite a few times:

Error: Could not load the bindings file. Tried:
 → /opt/qpinion/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/bcrypt_lib.node
 → /opt/qpinion/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/Debug/bcrypt_lib.node
 → /opt/qpinion/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/Release/bcrypt_lib.node
 → /opt/qpinion/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/out/Debug/bcrypt_lib.node
 → /opt/qpinion/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/Debug/bcrypt_lib.node
 → /opt/qpinion/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/out/Release/bcrypt_lib.node
 → /opt/qpinion/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/Release/bcrypt_lib.node
 → /opt/qpinion/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/default/bcrypt_lib.node
 → /opt/qpinion/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/compiled/0.12.7/linux/x64/bcrypt_lib.node
    at bindings (/opt/qpinion/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:84:13)
    at Object.<anonymous> (/opt/qpinion/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.Npm.require (/opt/qpinion/app/programs/server/boot.js:162:18)
    at packages/npm-bcrypt/packages/npm-bcrypt.js:9:1
error: Forever detected script exited with code: 1
error: Script restart attempt #1
/opt/qpinion/app/programs/server/node_modules/fibers/future.js:245

Any help be great. It was working fine until yesterday. I don't think I've changed anything other than work on my App.

Thanks

**Comment by Dev1an** [comment]
I am having the exact same problem. It worked perfectly last month and now it stopped working.
The following workaround works for me:
- Go to /opt/`myApp`/tmp/bundle.tar.gz
- cd into server/program and run `npm install`
- replace the app folder with tmp/bundle

**Comment by KenanY** [comment]
@ggndpsingh Is this still an issue for you?

**Comment by KenanY** [comment]
Closing as abandoned.
