### ISSUE TITLE
Unable to install appium using npm command in the Yosemeti OS Mac machine

### ISSUE THREAD

**Issue by kiransweng** [npm/npm#9515]
Hi Team,

I have applied the command "npm install -g appium" to install appium from the command line. Responded below error , could anyone assist me in this one.

terminal message:CSCINDAF026517:~ admin$ npm install -g appium
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "appium"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! path /usr/local/lib/node_modules/appium
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, rmdir '/usr/local/lib/node_modules/appium'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, rmdir '/usr/local/lib/node_modules/appium']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/appium' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! error rolling back Error: EACCES, rmdir '/usr/local/lib/node_modules/appium'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EACCES, rmdir '/usr/local/lib/node_modules/appium']
npm ERR! error rolling back   errno: -13,
npm ERR! error rolling back   code: 'EACCES',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/appium' }

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/admin/npm-debug.log
CSCINDAF026517:~ admin$ sudo npm install -g appium
Password:
|
^CCSCINDAF026517:~ admin$ sudo npm install -g appium
npm ERR! tar.unpack untar error /tmp/npm-9586-f0babfdd/registry.npmjs.org/es6-promise/-/es6-promise-2.3.0.tgz
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "appium"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! unexpected eof
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/admin/npm-debug.log

Regards,
Kiran

**Comment by sinkingshriek** [comment]
Related #9503

**Comment by kiransweng** [comment]
This has been resolved by changing the permissions of \usr\local folder. specified links helped me to resolve this.

Team, Thanks for your support.

Regards,
Kiran Edupuganti

**Comment by Prav0314** [comment]
Hi, can you please let me know the solution on how you have resolved the issue. I am facing the same issue and got stuck ...

Please help

-Praveen
