### ISSUE TITLE
Error in Build/Install in Intel XDK_Iot_edition using Galileo gen 2

### ISSUE THREAD

**Issue by Lohith94** [npm/npm#9521]
hey,
I'm new to the Galileo forum. I’m doing a project on the board, but i thought I'll start off first with uploading the blinking on-board led.I've followed all steps given in the main.js file and the readme file. I’ve also included the repository suggested and tried opkg update, which was largely successful apart from the lone error.
* opkg_conf_parse_file: Duplicate src declaration (mraa-upm http://iotdk.intel.com/repos/1.1/intelgalactic). Skipping.

I was able to connect the board through manual connection. These errors show up when I try to Install/Build.

npm ERR! syscall getaddrinfo                                                                                                                                
npm ERR! code ESRCH                                                                                                                                         
npm ERR! errno ESRCH                                                                                                                                        
npm ERR!                                                                                                                                                    
npm ERR! Additional logging details can be found in:                                                                                                        
npm ERR!     /home/root/.node_app_slot/npm-debug.log                                                                                                        
npm ERR! not ok code 0                                                                                                                                      
|================================================================                                                                                           
|    NPM INSTALL COMPLETE![ 1 ]   [ 1 ]                                                                                                                     
|================================================================  
has anyone faced the same error? Is there a workaround? or am i doing something wrong?

**Comment by KenanY** [comment]
@Lohith94 Are you still facing this issue?

**Comment by KenanY** [comment]
Closing due to no response.
