### ISSUE TITLE
npm fails after installing Node 4.0

### ISSUE THREAD

**Issue by smatsri** [npm/npm#9526]
keep getting:
`process.getuid is not a function`

**Comment by KenanY** [comment]
@smatsri `npm --version`? Operating system? Could you upload a resulting `npm-debug.log` as a [gist](https://gist.github.com/)?

**Comment by smatsri** [comment]
node v4.0.0 
npm  v2.12.0

windows 

[gist](https://gist.github.com/smatsri/11a4b4350c0638c0e7bb)

**Comment by othiym23** [comment]
`npm@2.12.0` is [busted on Windows](https://github.com/npm/npm/releases/tag/v2.12.1). If you completely uninstall Node and npm, or just reinstall Node using the Windows installer and use the version of npm bundled with it, this problem will go away. Good luck!

**Comment by smatsri** [comment]
thanks
