### ISSUE TITLE
Error in installing uglifyjs2

### ISSUE THREAD

**Issue by l3ardia** [npm/npm#9529]
I am installing uglifyjs2 but I get the following error:

186 error argv "/nginx/usr/local/bin/node" "/nginx/usr/local/bin/npm" "link" "."
187 error node v0.12.7
188 error npm  v2.11.3
189 error code EAI_AGAIN
190 error errno EAI_AGAIN
191 error syscall getaddrinfo
192 error getaddrinfo EAI_AGAIN
193 error If you need help, you may report this error at:
193 error     <https://github.com/npm/npm/issues>
194 verbose exit [ 1, true ]

**Comment by Seebomega** [comment]
I've same error for all my npm commands :+1: 

18 verbose request no auth needed
19 info attempt registry request try #1 at 12:57:23
20 verbose request id 67b48ae0f9a8f537
21 http request GET https://registry.npmjs.org/npm
22 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN
23 info attempt registry request try #2 at 12:57:53
24 http request GET https://registry.npmjs.org/npm
25 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN
26 info attempt registry request try #3 at 12:59:13
27 http request GET https://registry.npmjs.org/npm
28 verbose stack Error: getaddrinfo EAI_AGAIN
28 verbose stack     at Object.exports._errnoException (util.js:746:11)
28 verbose stack     at errnoException (dns.js:49:15)
28 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)
29 verbose cwd /home/serveur/serveur
30 error Linux 3.14.32-xxxx-grs-ipv6-64
31 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "npm" "-g"
32 error node v0.12.5
33 error npm  v2.11.2
34 error code EAI_AGAIN
35 error errno EAI_AGAIN
36 error syscall getaddrinfo
37 error getaddrinfo EAI_AGAIN
38 error If you need help, you may report this error at:
38 error     <https://github.com/npm/npm/issues>
39 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@l3ardia Are you still seeing this issue?

**Comment by KenanY** [comment]
Closing due to no response.
