### ISSUE TITLE
npm install -gq minit@latest   出现问题

### ISSUE THREAD

**Issue by JunningCui** [npm/npm#9532]
```
C:\Windows\system32>npm install -gq minit@latest
npm ERR! Error: connect ETIMEDOUT
npm ERR!     at errnoException (net.js:878:11)
npm ERR!     at Object.afterConnect [as oncomplete] (net.js:869:19)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "D:\\node\\nodejs\\\\node.exe" "D:\\node\\nodejs\\node_modules
\npm\\bin\\npm-cli.js" "install" "-gq" "minit@latest"
npm ERR! cwd C:\Windows\system32
npm ERR! node -v v0.10.2
npm ERR! npm -v 1.2.15
npm ERR! syscall connect
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Windows\system32\npm-debug.log
npm ERR! not ok code 0
```

**Comment by KenanY** [comment]
@JunningCui `npm@1.2` is very old and no longer supported. You should first of all [upgrade Node.js](https://github.com/npm/npm/wiki/Troubleshooting#updating-node-on-windows) and [upgrade `npm`](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows). Second of all, the error you are receiving is indicative of a network connection issue. Perhaps you are behind a proxy or firewall?

**Comment by JunningCui** [comment]
ok.thank you .I have update node and npm,and success,but there is some others,eg:


C:\Program Files\nodejs>npm install -g mop
npm http GET http://registry.npmjs.org/mop
npm http 304 http://registry.npmjs.org/mop
npm http GET http://registry.npmjs.org/montage
npm http GET http://registry.npmjs.org/mr
npm http GET http://registry.npmjs.org/collections
npm http GET http://registry.npmjs.org/q/1.0.0
npm http GET http://registry.npmjs.org/url2
npm http GET http://registry.npmjs.org/semver
npm http GET http://registry.npmjs.org/optimist
npm http GET http://registry.npmjs.org/uglify-js
npm http GET http://registry.npmjs.org/csso
npm http GET http://registry.npmjs.org/html-minifier
npm http GET http://registry.npmjs.org/q-io
npm http GET http://registry.npmjs.org/minidom
npm http 304 http://registry.npmjs.org/q/1.0.0
npm http 304 http://registry.npmjs.org/mr
npm http 304 http://registry.npmjs.org/collections
npm http 304 http://registry.npmjs.org/montage
npm http 304 http://registry.npmjs.org/url2
npm http 304 http://registry.npmjs.org/csso
npm http 304 http://registry.npmjs.org/semver
npm http 304 http://registry.npmjs.org/html-minifier
npm http 304 http://registry.npmjs.org/uglify-js
npm http 304 http://registry.npmjs.org/optimist
npm http 304 http://registry.npmjs.org/minidom
npm http 304 http://registry.npmjs.org/q-io
npm http GET http://registry.npmjs.org/url/0.10.2
npm http GET http://registry.npmjs.org/wordwrap
npm http GET http://registry.npmjs.org/q/0.9.7
npm http GET http://registry.npmjs.org/q
npm http GET http://registry.npmjs.org/qs
npm http GET http://registry.npmjs.org/mime
npm http GET http://registry.npmjs.org/mimeparse
npm ERR! error rolling back Error: ENOTEMPTY, rmdir 'C:\Program Files\nodejs\nod
e_global\node_modules\mop\node_modules\minidom'
npm ERR! error rolling back  mop@0.15.1 { [Error: ENOTEMPTY, rmdir 'C:\Program F
iles\nodejs\node_global\node_modules\mop\node_modules\minidom']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: 'C:\\Program Files\\nodejs\\node_global\\nod
e_modules\\mop\\node_modules\\minidom' }
npm ERR! Error: No compatible version found: url2@'^0.0.0'
npm ERR! Valid install targets:
npm ERR! ["0.0.0","1.0.0","1.0.1","1.0.2","1.0.3","2.0.0","1.0.4"]
npm ERR!     at installTargetsError (C:\Program Files\nodejs\node_modules\npm\li
b\cache.js:685:10)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\lib\cache.js:607:10
npm ERR!     at RegClient.get_ (C:\Program Files\nodejs\node_modules\npm\node_mo
dules\npm-registry-client\lib\get.js:101:14)
npm ERR!     at RegClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\
node_modules\npm-registry-client\lib\get.js:37:12)
npm ERR!     at fs.js:266:14
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "mop"
npm ERR! cwd C:\Program Files\nodejs
npm ERR! node -v v0.10.2
npm ERR! npm -v 1.2.15
npm ERR! Error: ENOENT, lstat 'C:\Program Files\nodejs\node_global\node_modules\
mop\node_modules\collections\CHANGES.md'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "mop"
npm ERR! cwd C:\Program Files\nodejs
npm ERR! node -v v0.10.2
npm ERR! npm -v 1.2.15
npm ERR! path C:\Program Files\nodejs\node_global\node_modules\mop\node_modules\
collections\CHANGES.md
npm ERR! fstream_path C:\Program Files\nodejs\node_global\node_modules\mop\node_
modules\collections\CHANGES.md
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack C:\Program Files\nodejs\node_modules\npm\node_modules\fst
ream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat 'C:\Program Files\nodejs\node_global\node_modules\
mop\node_modules\csso\lib\util.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "mop"
npm ERR! cwd C:\Program Files\nodejs
npm ERR! node -v v0.10.2
npm ERR! npm -v 1.2.15
npm ERR! path C:\Program Files\nodejs\node_global\node_modules\mop\node_modules\
csso\lib\util.js
npm ERR! fstream_path C:\Program Files\nodejs\node_global\node_modules\mop\node_
modules\csso\lib\util.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack C:\Program Files\nodejs\node_modules\npm\node_modules\fst
ream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat 'C:\Program Files\nodejs\node_global\node_modules\
mop\node_modules\uglify-js\test\compress\loops.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "mop"
npm ERR! cwd C:\Program Files\nodejs
npm ERR! node -v v0.10.2
npm ERR! npm -v 1.2.15
npm ERR! path C:\Program Files\nodejs\node_global\node_modules\mop\node_modules\
uglify-js\test\compress\loops.js
npm ERR! fstream_path C:\Program Files\nodejs\node_global\node_modules\mop\node_
modules\uglify-js\test\compress\loops.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack C:\Program Files\nodejs\node_modules\npm\node_modules\fst
ream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat 'C:\Program Files\nodejs\node_global\node_modules\
mop\node_modules\minidom\bundle.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "mop"
npm ERR! cwd C:\Program Files\nodejs
npm ERR! node -v v0.10.2
npm ERR! npm -v 1.2.15
npm ERR! path C:\Program Files\nodejs\node_global\node_modules\mop\node_modules\
minidom\bundle.js
npm ERR! fstream_path C:\Program Files\nodejs\node_global\node_modules\mop\node_
modules\minidom\bundle.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack C:\Program Files\nodejs\node_modules\npm\node_modules\fst
ream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http 304 http://registry.npmjs.org/q/0.9.7
npm http 304 http://registry.npmjs.org/url/0.10.2
npm http GET http://registry.npmjs.org/punycode/1.3.2
npm http 304 http://registry.npmjs.org/wordwrap
npm WARN package.json wordwrap@0.0.3 No README.md file found!
npm http 304 http://registry.npmjs.org/qs
npm http 304 http://registry.npmjs.org/q
npm http 304 http://registry.npmjs.org/mime
npm http 304 http://registry.npmjs.org/mimeparse
npm http 304 http://registry.npmjs.org/punycode/1.3.2
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Program Files\nodejs\npm-debug.log
npm ERR! not ok code 0

**Comment by KenanY** [comment]
@JunningCui The new log indicates no change in your Node.js and `npm` versions:

```
npm ERR! node -v v0.10.2
npm ERR! npm -v 1.2.15
```

Be sure to follow the Windows-specific instructions I linked to previously. If all else fails, you could always try uninstalling then re-installing.

**Comment by KenanY** [comment]
@JunningCui Are you still seeing this issue after updating to `npm@2` or `npm@3`?

**Comment by KenanY** [comment]
Closing as abandoned.
