### ISSUE TITLE
Error: Attempt to unlock twit, which hasn't been locked

### ISSUE THREAD

**Issue by kallol169856** [npm/npm#9533]
I am using version 0.10.35 . Please help.
The log file says :-  
0 info it worked if it ends with ok
1 verbose cli [ 'd:\\NodeJS\\\\node.exe',
1 verbose cli   'd:\\NodeJS\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'twit' ]
2 info using npm@1.4.28
3 info using node@v0.10.35
4 verbose node symlink d:\NodeJS\\node.exe
5 verbose cache add [ 'twit', null ]
6 verbose cache add name=undefined spec="twit" args=["twit",null]
7 verbose parsed url { protocol: null,
7 verbose parsed url   slashes: null,
7 verbose parsed url   auth: null,
7 verbose parsed url   host: null,
7 verbose parsed url   port: null,
7 verbose parsed url   hostname: null,
7 verbose parsed url   hash: null,
7 verbose parsed url   search: null,
7 verbose parsed url   query: null,
7 verbose parsed url   pathname: 'twit',
7 verbose parsed url   path: 'twit',
7 verbose parsed url   href: 'twit' }
8 silly lockFile 2fa2c8f5-twit twit
9 error Error: Attempt to unlock twit, which hasn't been locked
9 error     at unlock (d:\NodeJS\node_modules\npm\lib\utils\locker.js:44:11)
9 error     at cb (d:\NodeJS\node_modules\npm\lib\cache\add-local.js:30:5)
9 error     at d:\NodeJS\node_modules\npm\lib\cache\add-local.js:47:20
9 error     at d:\NodeJS\node_modules\npm\lib\utils\locker.js:22:20
9 error     at d:\NodeJS\node_modules\npm\node_modules\inflight\inflight.js:22:7
9 error     at Array.forEach (native)
9 error     at res (d:\NodeJS\node_modules\npm\node_modules\inflight\inflight.js:21:9)
9 error     at f (d:\NodeJS\node_modules\npm\node_modules\once\once.js:16:25)
9 error     at d:\NodeJS\node_modules\npm\node_modules\mkdirp\index.js:46:53
9 error     at Object.oncomplete (fs.js:108:15)
10 error If you need help, you may report this *entire* log,
10 error including the npm and node versions, at:
10 error     <http://github.com/npm/npm/issues>
11 error System Windows_NT 6.1.7601
12 error command "d:\\NodeJS\\\\node.exe" "d:\\NodeJS\\node_modules\\npm\\bin\\npm-cli.js" "install" "twit"
13 error cwd D:\Kallol\US Retail BFS01\BTG North America\Channel Planning\Client MVC  Hybrid Quick Starter Kit\code\backbone\09092015\backbonetwitterapplication\server
14 error node -v v0.10.35
15 error npm -v 1.4.28
16 verbose exit [ 1, true ]

**Comment by smikes** [comment]
Is this still a problem for you?

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4. Can you try updating your npm installation?

To update npm on Windows, you can use this command-line tool from Microsoft: https://github.com/felixrieseberg/npm-windows-upgrade
or follow the manual instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

Thanks!

**Comment by KenanY** [comment]
Closing as abandoned. Can reopen if this is still an issue with `npm@>=2`.
