### ISSUE TITLE
bootstrap npm install error 

### ISSUE THREAD

**Issue by jesseyu** [npm/npm#9539]
log:

➜  bootstrap-3.3.5  npm install
npm WARN locking Error: EACCES, open '/Users/geekyu/.npm/_locks/grunt-contrib-copy-a26d25002349a3a4.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/geekyu/.npm/_locks/grunt-contrib-copy-a26d25002349a3a4.lock failed { [Error: EACCES, open '/Users/geekyu/.npm/_locks/grunt-contrib-copy-a26d25002349a3a4.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/geekyu/.npm/_locks/grunt-contrib-copy-a26d25002349a3a4.lock' }
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! Attempt to unlock /Users/geekyu/Downloads/bootstrap-3.3.5/node_modules/grunt-contrib-copy, which hasn't been locked
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/geekyu/.npm/_locks/grunt-contrib-cssmin-abc7c9452852cc0e.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/geekyu/.npm/_locks/grunt-contrib-cssmin-abc7c9452852cc0e.lock failed { [Error: EACCES, open '/Users/geekyu/.npm/_locks/grunt-contrib-cssmin-abc7c9452852cc0e.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/geekyu/.npm/_locks/grunt-contrib-cssmin-abc7c9452852cc0e.lock' }
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! Attempt to unlock /Users/geekyu/Downloads/bootstrap-3.3.5/node_modules/grunt-contrib-cssmin, which hasn't been locked
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/geekyu/.npm/_locks/npm-shrinkwrap-20dbbe7ea06db6f1.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/geekyu/.npm/_locks/npm-shrinkwrap-20dbbe7ea06db6f1.lock failed { [Error: EACCES, open '/Users/geekyu/.npm/_locks/npm-shrinkwrap-20dbbe7ea06db6f1.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/geekyu/.npm/_locks/npm-shrinkwrap-20dbbe7ea06db6f1.lock' }
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! Attempt to unlock /Users/geekyu/Downloads/bootstrap-3.3.5/node_modules/npm-shrinkwrap, which hasn't been locked
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/geekyu/.npm/_locks/grunt-saucelabs-54fd73da4f906678.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/geekyu/.npm/_locks/grunt-saucelabs-54fd73da4f906678.lock failed { [Error: EACCES, open '/Users/geekyu/.npm/_locks/grunt-saucelabs-54fd73da4f906678.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/geekyu/.npm/_locks/grunt-saucelabs-54fd73da4f906678.lock' }
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! Attempt to unlock /Users/geekyu/Downloads/bootstrap-3.3.5/node_modules/grunt-saucelabs, which hasn't been locked
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/geekyu/.npm/_locks/grunt-contrib-concat-a952176b93b06f43.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/geekyu/.npm/_locks/grunt-contrib-concat-a952176b93b06f43.lock failed { [Error: EACCES, open '/Users/geekyu/.npm/_locks/grunt-contrib-concat-a952176b93b06f43.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/geekyu/.npm/_locks/grunt-contrib-concat-a952176b93b06f43.lock' }
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! Attempt to unlock /Users/geekyu/Downloads/bootstrap-3.3.5/node_modules/grunt-contrib-concat, which hasn't been locked
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/geekyu/.npm/_locks/grunt-fedad255828c189c.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/geekyu/.npm/_locks/grunt-fedad255828c189c.lock failed { [Error: EACCES, open '/Users/geekyu/.npm/_locks/grunt-fedad255828c189c.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/geekyu/.npm/_locks/grunt-fedad255828c189c.lock' }
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! Attempt to unlock /Users/geekyu/Downloads/bootstrap-3.3.5/node_modules/grunt, which hasn't been locked
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/geekyu/.npm/_locks/grunt-contrib-connect-113c2b4a8ca79030.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/geekyu/.npm/_locks/grunt-contrib-connect-113c2b4a8ca79030.lock failed { [Error: EACCES, open '/Users/geekyu/.npm/_locks/grunt-contrib-connect-113c2b4a8ca79030.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/geekyu/.npm/_locks/grunt-contrib-connect-113c2b4a8ca79030.lock' }
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! Attempt to unlock /Users/geekyu/Downloads/bootstrap-3.3.5/node_modules/grunt-contrib-connect, which hasn't been locked
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/geekyu/.npm/_locks/grunt-contrib-csslint-22a8dceac94cfd17.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/geekyu/.npm/_locks/grunt-contrib-csslint-22a8dceac94cfd17.lock failed { [Error: EACCES, open '/Users/geekyu/.npm/_locks/grunt-contrib-csslint-22a8dceac94cfd17.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/geekyu/.npm/_locks/grunt-contrib-csslint-22a8dceac94cfd17.lock' }
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! Attempt to unlock /Users/geekyu/Downloads/bootstrap-3.3.5/node_modules/grunt-contrib-csslint, which hasn't been locked
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/geekyu/.npm/_locks/grunt-contrib-jade-01115b4fe4f3320e.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/geekyu/.npm/_locks/grunt-contrib-jade-01115b4fe4f3320e.lock failed { [Error: EACCES, open '/Users/geekyu/.npm/_locks/grunt-contrib-jade-01115b4fe4f3320e.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/geekyu/.npm/_locks/grunt-contrib-jade-01115b4fe4f3320e.lock' }
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! Attempt to unlock /Users/geekyu/Downloads/bootstrap-3.3.5/node_modules/grunt-contrib-jade, which hasn't been locked
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/geekyu/.npm/_locks/grunt-contrib-clean-a78c9c9bd996310e.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/geekyu/.npm/_locks/grunt-contrib-clean-a78c9c9bd996310e.lock failed { [Error: EACCES, open '/Users/geekyu/.npm/_locks/grunt-contrib-clean-a78c9c9bd996310e.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/geekyu/.npm/_locks/grunt-contrib-clean-a78c9c9bd996310e.lock' }
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! Attempt to unlock /Users/geekyu/Downloads/bootstrap-3.3.5/node_modules/grunt-contrib-clean, which hasn't been locked
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/geekyu/.npm/_locks/grunt-contrib-jshint-1e664f9e7fef66a9.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/geekyu/.npm/_locks/grunt-contrib-jshint-1e664f9e7fef66a9.lock failed { [Error: EACCES, open '/Users/geekyu/.npm/_locks/grunt-contrib-jshint-1e664f9e7fef66a9.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/geekyu/.npm/_locks/grunt-contrib-jshint-1e664f9e7fef66a9.lock' }
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! Attempt to unlock /Users/geekyu/Downloads/bootstrap-3.3.5/node_modules/grunt-contrib-jshint, which hasn't been locked
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/geekyu/.npm/_locks/grunt-html-63ed9129b9d861ae.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/geekyu/.npm/_locks/grunt-html-63ed9129b9d861ae.lock failed { [Error: EACCES, open '/Users/geekyu/.npm/_locks/grunt-html-63ed9129b9d861ae.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/geekyu/.npm/_locks/grunt-html-63ed9129b9d861ae.lock' }
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! Attempt to unlock /Users/geekyu/Downloads/bootstrap-3.3.5/node_modules/grunt-html, which hasn't been locked
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/geekyu/.npm/_locks/grunt-contrib-qunit-e01ac35a9a57170a.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/geekyu/.npm/_locks/grunt-contrib-qunit-e01ac35a9a57170a.lock failed { [Error: EACCES, open '/Users/geekyu/.npm/_locks/grunt-contrib-qunit-e01ac35a9a57170a.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/geekyu/.npm/_locks/grunt-contrib-qunit-e01ac35a9a57170a.lock' }
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! Attempt to unlock /Users/geekyu/Downloads/bootstrap-3.3.5/node_modules/grunt-contrib-qunit, which hasn't been locked
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/geekyu/.npm/_locks/grunt-contrib-watch-9f072cf89dcf2706.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/geekyu/.npm/_locks/grunt-contrib-watch-9f072cf89dcf2706.lock failed { [Error: EACCES, open '/Users/geekyu/.npm/_locks/grunt-contrib-watch-9f072cf89dcf2706.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/geekyu/.npm/_locks/grunt-contrib-watch-9f072cf89dcf2706.lock' }
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! Attempt to unlock /Users/geekyu/Downloads/bootstrap-3.3.5/node_modules/grunt-contrib-watch, which hasn't been locked
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/geekyu/.npm/_locks/grunt-contrib-htmlmin-b0f3a7109347d2c4.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/geekyu/.npm/_locks/grunt-contrib-htmlmin-b0f3a7109347d2c4.lock failed { [Error: EACCES, open '/Users/geekyu/.npm/_locks/grunt-contrib-htmlmin-b0f3a7109347d2c4.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/geekyu/.npm/_locks/grunt-contrib-htmlmin-b0f3a7109347d2c4.lock' }
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! Attempt to unlock /Users/geekyu/Downloads/bootstrap-3.3.5/node_modules/grunt-contrib-htmlmin, which hasn't been locked
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/geekyu/.npm/_locks/grunt-jekyll-fa11d87f423129e7.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/geekyu/.npm/_locks/grunt-jekyll-fa11d87f423129e7.lock failed { [Error: EACCES, open '/Users/geekyu/.npm/_locks/grunt-jekyll-fa11d87f423129e7.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/geekyu/.npm/_locks/grunt-jekyll-fa11d87f423129e7.lock' }
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! Attempt to unlock /Users/geekyu/Downloads/bootstrap-3.3.5/node_modules/grunt-jekyll, which hasn't been locked
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/geekyu/.npm/_locks/grunt-jscs-e329fa5c7cda5616.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/geekyu/.npm/_locks/grunt-jscs-e329fa5c7cda5616.lock failed { [Error: EACCES, open '/Users/geekyu/.npm/_locks/grunt-jscs-e329fa5c7cda5616.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/geekyu/.npm/_locks/grunt-jscs-e329fa5c7cda5616.lock' }
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! Attempt to unlock /Users/geekyu/Downloads/bootstrap-3.3.5/node_modules/grunt-jscs, which hasn't been locked
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/geekyu/.npm/_locks/time-grunt-ffe06064f2c673d9.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/geekyu/.npm/_locks/time-grunt-ffe06064f2c673d9.lock failed { [Error: EACCES, open '/Users/geekyu/.npm/_locks/time-grunt-ffe06064f2c673d9.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/geekyu/.npm/_locks/time-grunt-ffe06064f2c673d9.lock' }
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! Attempt to unlock /Users/geekyu/Downloads/bootstrap-3.3.5/node_modules/time-grunt, which hasn't been locked
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/geekyu/.npm/_locks/grunt-contrib-compress-d76addefa545bba1.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/geekyu/.npm/_locks/grunt-contrib-compress-d76addefa545bba1.lock failed { [Error: EACCES, open '/Users/geekyu/.npm/_locks/grunt-contrib-compress-d76addefa545bba1.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/geekyu/.npm/_locks/grunt-contrib-compress-d76addefa545bba1.lock' }
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! Attempt to unlock /Users/geekyu/Downloads/bootstrap-3.3.5/node_modules/grunt-contrib-compress, which hasn't been locked
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/geekyu/.npm/_locks/grunt-exec-7bd3e98d449b90bb.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/geekyu/.npm/_locks/grunt-exec-7bd3e98d449b90bb.lock failed { [Error: EACCES, open '/Users/geekyu/.npm/_locks/grunt-exec-7bd3e98d449b90bb.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/geekyu/.npm/_locks/grunt-exec-7bd3e98d449b90bb.lock' }
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! Attempt to unlock /Users/geekyu/Downloads/bootstrap-3.3.5/node_modules/grunt-exec, which hasn't been locked
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/geekyu/.npm/_locks/grunt-autoprefixer-0f84f49e8d848ed5.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/geekyu/.npm/_locks/grunt-autoprefixer-0f84f49e8d848ed5.lock failed { [Error: EACCES, open '/Users/geekyu/.npm/_locks/grunt-autoprefixer-0f84f49e8d848ed5.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/geekyu/.npm/_locks/grunt-autoprefixer-0f84f49e8d848ed5.lock' }
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! Attempt to unlock /Users/geekyu/Downloads/bootstrap-3.3.5/node_modules/grunt-autoprefixer, which hasn't been locked
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/geekyu/.npm/_locks/grunt-contrib-less-481b088b2c74adfb.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/geekyu/.npm/_locks/grunt-contrib-less-481b088b2c74adfb.lock failed { [Error: EACCES, open '/Users/geekyu/.npm/_locks/grunt-contrib-less-481b088b2c74adfb.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/geekyu/.npm/_locks/grunt-contrib-less-481b088b2c74adfb.lock' }
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! Attempt to unlock /Users/geekyu/Downloads/bootstrap-3.3.5/node_modules/grunt-contrib-less, which hasn't been locked
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/geekyu/.npm/_locks/load-grunt-tasks-3fcbf2c966605709.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/geekyu/.npm/_locks/load-grunt-tasks-3fcbf2c966605709.lock failed { [Error: EACCES, open '/Users/geekyu/.npm/_locks/load-grunt-tasks-3fcbf2c966605709.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/geekyu/.npm/_locks/load-grunt-tasks-3fcbf2c966605709.lock' }
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! Attempt to unlock /Users/geekyu/Downloads/bootstrap-3.3.5/node_modules/load-grunt-tasks, which hasn't been locked
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/geekyu/.npm/_locks/grunt-csscomb-ce546db07c2e307c.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/geekyu/.npm/_locks/grunt-csscomb-ce546db07c2e307c.lock failed { [Error: EACCES, open '/Users/geekyu/.npm/_locks/grunt-csscomb-ce546db07c2e307c.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/geekyu/.npm/_locks/grunt-csscomb-ce546db07c2e307c.lock' }
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! Attempt to unlock /Users/geekyu/Downloads/bootstrap-3.3.5/node_modules/grunt-csscomb, which hasn't been locked
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/geekyu/.npm/_locks/grunt-contrib-uglify-a158c02acd11013f.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/geekyu/.npm/_locks/grunt-contrib-uglify-a158c02acd11013f.lock failed { [Error: EACCES, open '/Users/geekyu/.npm/_locks/grunt-contrib-uglify-a158c02acd11013f.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/geekyu/.npm/_locks/grunt-contrib-uglify-a158c02acd11013f.lock' }
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! Attempt to unlock /Users/geekyu/Downloads/bootstrap-3.3.5/node_modules/grunt-contrib-uglify, which hasn't been locked
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/geekyu/.npm/_locks/btoa-f3d4f8564d4824c3.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/geekyu/.npm/_locks/btoa-f3d4f8564d4824c3.lock failed { [Error: EACCES, open '/Users/geekyu/.npm/_locks/btoa-f3d4f8564d4824c3.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/geekyu/.npm/_locks/btoa-f3d4f8564d4824c3.lock' }
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! Attempt to unlock /Users/geekyu/Downloads/bootstrap-3.3.5/node_modules/btoa, which hasn't been locked
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/geekyu/.npm/_locks/markdown-it-fdc655f9520166f0.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/geekyu/.npm/_locks/markdown-it-fdc655f9520166f0.lock failed { [Error: EACCES, open '/Users/geekyu/.npm/_locks/markdown-it-fdc655f9520166f0.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/geekyu/.npm/_locks/markdown-it-fdc655f9520166f0.lock' }
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! Attempt to unlock /Users/geekyu/Downloads/bootstrap-3.3.5/node_modules/markdown-it, which hasn't been locked
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/geekyu/.npm/_locks/glob-d76b8f4baa04b49a.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/geekyu/.npm/_locks/glob-d76b8f4baa04b49a.lock failed { [Error: EACCES, open '/Users/geekyu/.npm/_locks/glob-d76b8f4baa04b49a.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/geekyu/.npm/_locks/glob-d76b8f4baa04b49a.lock' }
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! Attempt to unlock /Users/geekyu/Downloads/bootstrap-3.3.5/node_modules/glob, which hasn't been locked
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/geekyu/.npm/_locks/grunt-sed-9163aec2278e6e65.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/geekyu/.npm/_locks/grunt-sed-9163aec2278e6e65.lock failed { [Error: EACCES, open '/Users/geekyu/.npm/_locks/grunt-sed-9163aec2278e6e65.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/geekyu/.npm/_locks/grunt-sed-9163aec2278e6e65.lock' }
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! Attempt to unlock /Users/geekyu/Downloads/bootstrap-3.3.5/node_modules/grunt-sed, which hasn't been locked
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/geekyu/Downloads/bootstrap-3.3.5/npm-debug.log

**Comment by KenanY** [comment]
@jesseyu I would first try running

``` sh
sudo chown -R $(whoami) "$HOME/.npm"
```

**Comment by KenanY** [comment]
@jesseyu It has been several months now with no response from you... are you still seeing this issue after following my suggestion?

**Comment by KenanY** [comment]
Closing as abandoned and not an issue with `npm`.

**Comment by jesseyu** [comment]
@KenanY  thank you , I've solved it
