### ISSUE TITLE
Ubuntu: appium installation error

### ISSUE THREAD

**Issue by toralMevada** [npm/npm#9540]
Hi,

I installed node using brew. When I tried to install appium, faced this error.

toral@toral:~$ npm install -g appium
npm ERR! tar.unpack untar error /tmp/npm-20547-fc36a401/registry.npmjs.org/date-utils/-/date-utils-1.2.17.tgz
npm ERR! tar.unpack untar error /tmp/npm-20547-fc36a401/registry.npmjs.org/appium-instruments/-/appium-instruments-2.0.5.tgz
npm ERR! tar.unpack untar error /tmp/npm-20547-fc36a401/registry.npmjs.org/appium-uiauto/-/appium-uiauto-1.10.8.tgz
npm ERR! Linux 3.5.0-23-generic
npm ERR! argv "node" "/home/toral/.linuxbrew/bin/npm" "install" "-g" "appium"
npm ERR! node v0.12.7
npm ERR! npm v2.12.1

npm ERR! unexpected eof
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR! https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR! /home/toral/npm-debug.log
toral@toral:~$

**Comment by garthk** [comment]
@toralMevada this might be nodejs/new.nodejs.org#124; try upgrading `npm` to `2.13.2`?

**Comment by toralMevada** [comment]
@garthk.

After upgrading npm to latest, it shows as 2.12.1 when version is checked. Any suggestion?  

'
toral@toral:~$ npm install npm -g
/home/toral/.npm-packages/bin/npm -> /home/toral/.npm-packages/lib/node_modules/npm/bin/npm-cli.js
npm@2.14.2 /home/toral/.npm-packages/lib/node_modules/npm
toral@toral:~$ npm -v
2.12.1
'

**Comment by toralMevada** [comment]
Followed https://gist.github.com/DanHerbert/9520689 to upgrade npm to latest i.e. 2.14.2.

But appium installation still gives error:
'
toral@toral:~$ npm install -g appium
npm ERR! tar.unpack untar error /tmp/npm-10150-cd74dcc6/registry.npmjs.org/appium-instruments/-/appium-instruments-2.0.5.tgz
npm ERR! tar.unpack untar error /tmp/npm-10150-cd74dcc6/registry.npmjs.org/appium-uiauto/-/appium-uiauto-1.10.8.tgz
npm ERR! Linux 3.5.0-23-generic
npm ERR! argv "node" "/home/toral/.node/bin/npm" "install" "-g" "appium"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.2

npm ERR! unexpected eof
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/toral/npm-debug.log
'

**Comment by toralMevada** [comment]
And what does this "tar.unpack untar error" mean?

**Comment by garthk** [comment]
@toralMevada if you look at the `.tgz` file my bet is it'll be HTML from the NPM home page or blog due to the CDN error. Blow away `~/.npm/appium-instruments` and try again.

**Comment by toralMevada** [comment]
Thanks @garthk.

Even after deleting ~/.npm/appium-instruments, it is giving same error.

**Comment by KenanY** [comment]
@toralMevada Are you still seeing this issue? :(

**Comment by KenanY** [comment]
Closing as abandoned.
