### ISSUE TITLE
npm error using visual studio 2015

### ISSUE THREAD

**Issue by simox-dev** [npm/npm#9542]
Hi! 
I'm using visual studio and I made a multiplatform application. Sometime when I open visual studio appear this error

====Executing command 'npm install'====

npm ERR! install Couldn't read dependencies
npm ERR! Error: Invalid name: "Pasta Vegan"
npm ERR!     at ensureValidName (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\npm\node_modules\normalize-package-data\lib\fixer.js:300:15)
npm ERR!     at Object.module.exports.fixNameField (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\npm\node_modules\normalize-package-data\lib\fixer.js:204:5)
npm ERR!     at C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\npm\node_modules\normalize-package-data\lib\normalize.js:30:38
npm ERR!     at Array.forEach (native)
npm ERR!     at normalize (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\npm\node_modules\normalize-package-data\lib\normalize.js:29:15)
npm ERR!     at final (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\npm\node_modules\read-package-json\read-json.js:342:33)
npm ERR!     at then (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\npm\node_modules\read-package-json\read-json.js:126:33)
npm ERR!     at C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\npm\node_modules\read-package-json\read-json.js:316:48
npm ERR!     at fs.js:207:20
npm ERR!     at OpenReq.Req.done (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\npm\node_modules\graceful-fs\graceful-fs.js:144:5)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\IDE\\Extensions\\Microsoft\\Web Tools\\External\\\\node\\node" "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\IDE\\Extensions\\Microsoft\\Web Tools\\External\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\Users\Simone\Desktop\PastaVegan
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.9
npm

====npm command completed with exit code 1====

What is?

**Comment by KenanY** [comment]
@simox-dev 

```
npm ERR! Error: Invalid name: "Pasta Vegan"
```

Spaces and capital letters are not allowed in packages names.

**Comment by KenanY** [comment]
Closing as resolved. If you are still having this issue with `npm@2` or `npm@3` feel free to open a new issue.
