### ISSUE TITLE
cross-compiling idiom

### ISSUE THREAD

**Issue by nicks** [npm/npm#9545]
I maintain an NPM package with some platform-specific code. Users have requested support for cross-compiling for other platforms.

Is there an agreed-upon idiom for expressing "install these NPM packages to be run on target architecture X"? I saw some vague references on the internet to npm_config_arch and npm_config_platform, but nothing in the official NPM docs.

To be clear, I'm not asking for NPM to implement anything. I'm asking if there's a standard that package maintainers can implement. Obviously, every package could implement support for their own environment variable MY_PACKAGE_TARGET_ARCH but this would become unwieldy for end-users of lots of packages.

Thanks!

**Comment by smikes** [comment]
Sort of.. there's `node-pre-gyp` which you can use to prebuild packages for different architectures and store them in a defined location. - see https://www.npmjs.com/package/node-pre-gyp

Does that address your question?

**Comment by nicks** [comment]
The question i'm asking is one layer up. 

If i'm using node-gyp, and I want the user invoking `npm install` to be able to specify the value of `--target_arch` in my package, is there a convention for doing that? or does every package invent their own convention?

**Comment by smikes** [comment]
I don't think there's a convention for that.

I think people generally advise that the consumer of your package should run `npm install` on the target architecture.

In the situations where that's not possible (eg, bundling for later deployment onto devices or networkless deployments...) people do, as you suspect, have to roll their own.

**Comment by nicks** [comment]
ok, thanks!
