### ISSUE TITLE
npm ERR! Error: getaddrinfo ESRCH

### ISSUE THREAD

**Issue by aman-IoT** [npm/npm#9547]
```
root@galileo:~# npm install iotkit-agent
npm ERR! Error: getaddrinfo ESRCH
npm ERR!     at errnoException (dns.js:37:11)
npm ERR!     at Object.onanswer [as oncomplete] (dns.js:124:16)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.8.7-yocto-standard
npm ERR! command "node" "/usr/bin/npm" "install" "iotkit-agent"
npm ERR! cwd /home/root
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! syscall getaddrinfo
npm ERR! code ESRCH
npm ERR! errno ESRCH
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/root/npm-debug.log
npm ERR! not ok code 0
```

I am getting this error when i try to install iotkit-agent , I have boot SD card with the latest bz2 image file. 
Yesterday I install the older version and sensed some data it was working fine then for actuation purpose I updated image with "npm update -g iotkit-agent" and actuation was also perfect.

But today when tried to connect it by TEST command it showed some error and afterward I formatted SD card and install latest version of Image where I am getting this issue.

Please sort this out it will be very helpfull

Thank You

**Comment by aman-IoT** [comment]
![error1](https://cloud.githubusercontent.com/assets/14223353/9798956/f33b922e-5821-11e5-9019-015131ac2e7c.PNG)

**Comment by aman-IoT** [comment]
Sombody Provide some help please...

**Comment by ehsalazar** [comment]
@aman-IoT The version on npm you're running is outdated. Could you give [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) a try?

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.
