### ISSUE TITLE
4.0.0 fails to build on Debian, succeeds on Windows

### ISSUE THREAD

**Issue by altsheets** [npm/npm#9554]
I spent many many hours with this. In the end, I actually found a solution - downgrading:
https://www.reddit.com/r/node/comments/3kgxym/ram_build_install_on_windows_and_run_start_on/cuxqc8c

The whole time I had thought ... it is a memory issue. I even thought if I perhaps have to build cross-platform, somehow:  https://www.reddit.com/r/node/comments/3kgxym/ram_build_install_on_windows_and_run_start_on/

Then I was already thinking into the right direction, seemingly
https://www.reddit.com/r/node/comments/3kh9nb/do_older_versions_of_nodejs_use_less_ram_for/

and finally, I threw away my 4.0.0 - and that solved it.

Test case is there. 

Builds perfectly on Windows, fails -without(*) an error message- on Debian.

---

(*) 
“But the plans were on display…”
“On display? I eventually had to go down to the cellar to find them.”
“That’s the display department.”
“With a flashlight.”
“Ah, well, the lights had probably gone.”
“So had the stairs.”
“But look, you found the notice, didn’t you?”
“Yes,” said Arthur, “yes I did. It was on display in the bottom of a locked filing cabinet stuck in a disused lavatory with a sign on the door saying ‘Beware of the Leopard.”

― Douglas Adams, The Hitchhiker's Guide to the Galaxy

**Comment by altsheets** [comment]
but ... thanks a LOT for node.js, and npm!
Seems to be a powerful piece of software!

**Comment by altsheets** [comment]
https://github.com/nodejs/node/issues/2798

**Comment by saper** [comment]
Judging from https://www.reddit.com/r/node/comments/3kgxym/ram_build_install_on_windows_and_run_start_on/cuxc18e this is related to https://github.com/socketio/socket.io/issues/2228 ?

**Comment by ChALkeR** [comment]
What's the exact issue, again? There are problems building something in a low memory enviroment? Why does the title say about Debian vs Windows if the problem is about 0.5 GiB vs 8 GiB?
_What_ are you building? Node.js? Installing npm? Installing some packages with npm?

**Comment by ChALkeR** [comment]
If `npm install` in some project fails for you because of low memory, try installing your deps manually with `npm install {dep}` for each `{dep}` in your dependencies.

**Comment by saper** [comment]
@altsheets can you publish the `builderror.log` somewhere? like gist.github.com?

**Comment by altsheets** [comment]
@saper 

I killed that machine, and started new. So I don't have that file anymore. But I posted this extract on reddit:

	tail /root/AEEE/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/builderror.log  
	gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/AEEE/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/.node-gyp/4.0.0"  
	...  
	gyp WARN EACCES attempting to reinstall using temporary dev dir "/root/AEEE/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/.node-gyp"     
	FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory    
	Aborted 

Perhaps that helps you?

It was in 

    /node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/builderror.log

You can try it out yourself:

    git clone https://github.com/etherparty/explorer  
    cd explorer  
    npm install

**Comment by altsheets** [comment]
@ChALkeR

Later, the same also happened again on a larger machine with *2GB RAM* and 4GB swap.

And on that initial small droplet (512MB and s.th. like 2GB swap), while I was building ... I was closely watching "top" - and there was always swap memory left.

**Comment by altsheets** [comment]
but perhaps yes - perhaps all this was only me. It was my 2nd day with node.js
And I am an experienced coder, but not a Linux admin.

This experience however, has taught me so much! Learning more every day.

All was good *when I left 4.0.0 for an older nodejs*. The same project built in seconds, and running smooth.

Thanks to everyone!

**Comment by saper** [comment]
On Sat, 12 Sep 2015, altsheets wrote:

> @saper 
> 
> I killed that machine, and started new. So I don't have that file anymore. But I posted this extract on reddit:
> 
> 	tail /root/AEEE/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/builderror.log  
> 	gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/AEEE/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/.node-gyp/4.0.0"  
> 	...  
> 	gyp WARN EACCES attempting to reinstall using temporary dev dir "/root/AEEE/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/.node-gyp"     
> 	FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory    
> 	Aborted 

Can you check if your node is not compiled in the debug configuration?

Just run "node" and ask for "process.config", it should say 'Release' in "default_configuration"

Ethereum Explorer seems to install fine on my machine.

**Comment by altsheets** [comment]
Not ethereum, it is this lightweight block explorer

    git clone https://github.com/etherparty/explorer  
    cd explorer  
    npm install

**Comment by saper** [comment]
> Not ethereum, it is this lightweight block explorer
> 
>     git clone https://github.com/etherparty/explorer  
>     cd explorer  
>     npm install 

From package.json:

  "name": "EthereumExplorer",
  "private": false,
  "version": "0.1.0",
  "description": "A lightweight ethereum block explorer",
  "repository": "https://github.com/etherparty/explorer",

**Comment by altsheets** [comment]
> Ethereum *Explorer* ...

Oh, I had overlooked the 2nd word - sorry.

> Ethereum Explorer seems to install fine on my machine.

Good. Happy to hear that. 

Then I must have had on both machines I tried it on ... somehow a wrongly configured nodejs.

>  check if your node is not compiled 

Yes, perhaps. Dunno. 

One day in the future, I might touch nodejs v4 again.

For now, the app is running perfectly with v0.10.40. Happy!

**Comment by altsheets** [comment]
As a side effect of all this, I wrote a [complete manual how to install this thingy on a new empty droplet](https://github.com/altsheets/explorer/blob/master/how-to/debian-ubuntu.sh).

**Comment by altsheets** [comment]
Many many thanks to everyone who helped. 

Enjoy whatever you do!
