### ISSUE TITLE
missing script start

### ISSUE THREAD

**Issue by desa0068** [npm/npm#9555]
argv "/Applications/nodejs-0.12.7-0/nodejs/bin/.node.bin" "/Applications/nodejs-0.12.7-0/nodejs/bin/npm" "start"
 missing script start

**Comment by KenanY** [comment]
@desa0068 Do you have a [`"start"` script](https://docs.npmjs.com/misc/scripts) defined in your [`package.json`](https://docs.npmjs.com/files/package.json)? If not, `npm` will have no idea what you want it to do when you run [`npm start`](https://docs.npmjs.com/cli/start).

Could you tell me what you are _expecting_ to happen when you run `npm start`? This way, I can perhaps help guide you in the right direction.

**Comment by desa0068** [comment]
No I just did not change my directory which contained the project I wanted to start so that may be th reason that it did not start but now it is running thank you.
