### ISSUE TITLE
`npm -g ls` is very slow, even when constrained to depth 0

### ISSUE THREAD

**Issue by mzgol** [npm/npm#9556]
Compare:
```
$ npm --version
2.13.3
$ npm -g install bower caniuse-cmd david grunt-cli http-server iron-node jspm nodemon node-gyp npm-bump recursive-blame trash yo 
$ time npm -g ls --depth=0
...
npm -g ls --depth=0  0.57s user 0.09s system 97% cpu 0.675 total
$ time npm -g ls
...
npm -g ls  3.79s user 0.83s system 118% cpu 3.905 total
```
to:
```
$ npm --version
3.3.2
$ npm -g install bower caniuse-cmd david grunt-cli http-server iron-node jspm nodemon node-gyp npm-bump recursive-blame trash yo 
$ time npm -g ls --depth=0
...
npm -g ls --depth=0  16.49s user 0.74s system 103% cpu 16.614 total
$ time npm -g ls
...
npm -g ls  17.48s user 0.85s system 103% cpu 17.726 total
```

**Comment by 75lb** [comment]
on 3.3.3, `npm ls -g` is unusable for me.. maxes out the CPU for 20-30 seconds before i terminate it..

**Comment by yamalight** [comment]
same here with npm@3.3.3, node v4.1.0 on latest stable mac os.
time to execute `npm --depth=0 ls` ranges from 6s to 10s, CPU load is always above 100%. 
pretty much unusable now.
was no issue like this on 2.x, please fix.

**Comment by MethodGrab** [comment]
+1 for this. With 40 global modules installed, time taken increases from <1s to almost 20mins!
I'm on a Macbook Pro with OS X 10.10.4.

```
$ node -v
v0.12.7

$ npm -v
2.13.0

$ time npm ls -g --depth=0
npm ls -g --depth=0  0.68s user 0.10s system 105% cpu 0.742 total
```



```
$ node -v
v4.1.0

$ npm -v
3.3.3

$ time npm ls -g --depth=0
npm ls -g --depth=0  1044.00s user 8.21s system 99% cpu 17:39.36 total
```

**Comment by iarna** [comment]
Hi all, this is a duplicate #8826, so I'm closing as such.

But you'll all be happy to hear that I made a HUGE performance improvement earlier this week, so this week's release should being npm@3 performance into much closer alignment w/ npm@2.

**Comment by jstejada** [comment]
:+1:
