### ISSUE TITLE
Can't install packages (registry error parsing json + checksum errors)

### ISSUE THREAD

**Issue by zeezali** [npm/npm#9560]
Hi, I've been having some major trouble installing packages for the last day or so. Actually, in some cases I haven't been able to install packages at all (when running `npm install` or `npm update`).

My current setup:
npm version: 2.13.2
iojs version: 2.5.0

Here are examples of some errors I keep seeing while trying to install packages:

**Invalid Checksum:**
    
    npm ERR! registry error parsing json
    npm ERR! Darwin 14.5.0
    npm ERR! argv "/Users/Zee/.nvm/versions/io.js/v2.5.0/bin/iojs" "/Users/Zee/.nvm/versions/io.js/v2.5.0/bin/npm" "install"
    npm ERR! node v2.5.0
    npm ERR! npm  v2.13.2

    npm ERR! shasum check failed for /var/folders/yg/bz8zpb3n7p778blpqjrd54hc0000gn/T/npm-99355-5be3067f/registry.npmjs.org/modernizr/-/modernizr-3.0.0.tgz
    npm ERR! Expected: c8f2db9ebcf97e68244b767269e54140dfaec5db
    npm ERR! Actual:   da39a3ee5e6b4b0d3255bfef95601890afd80709
    npm ERR! From:     https://registry.npmjs.org/modernizr/-/modernizr-3.0.0.tgz
    npm ERR! 
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <https://github.com/npm/npm/issues>

**Registry error parsing JSON:**

    npm ERR! registry error parsing json
    npm ERR! Darwin 14.5.0
    npm ERR! argv "/Users/Zee/.nvm/versions/io.js/v2.5.0/bin/iojs" "/Users/Zee/.nvm/versions/io.js/v2.5.0/bin/npm" "install"
    npm ERR! node v2.5.0
    npm ERR! npm  v2.13.2

    npm ERR! failed to fetch from registry: https://registry.npmjs.org/gulp
    npm ERR! 
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <https://github.com/npm/npm/issues>

There were also times where the JSON error would state `unexpected end of input`, while showing a minified version of a module's `package.json` file.

Things I've tried for far without any luck:

* Installed the latest stable version of npm – `sudo npm install npm -g`
* Removed Node completely from my machine and reinstalled it
* Removed nvm completely and reinstalled it
* Ran `npm cache clean` everytime an error took place
* Downgraded to **node** `v0.12.4` to see whether anything changes
* Downgraded to `iojs-v2.3.0` (from 2.5.0)
* Restarted my machine....
* Tried installing packages on a different machine

After lots of trying I ended up **downgrading to npm@1.4.28 and was then able to install packages without any issues** (except some warnings about packages that expected higher versions of npm).

Looking at the [Troubleshooting Wiki](https://github.com/npm/npm/wiki/Troubleshooting), I'm wondering whether it's just a temporary glitch in the registry or something specific to my environment?

**Comment by levibuzolic** [comment]
I'm having similar issues here. Tried a few different `node` and `npm` versions. Eventually once I get enough good packages into my cache, I can get through an install -- but it's nearly impossible to do a `npm install` with a handfull of fresh packages and have it work first time.

**Comment by zeezali** [comment]
Checked again this afternoon and was still having the same issues. Wasn't able to install packages and kept seeing a lot of `npm ERR! registry error parsing json`.

I started going through some of the other open issues and came across https://github.com/npm/npm/issues/9559#issuecomment-139808471.

I can confirm that changing the registry URL to the Chinese mirror (`npm set registry http://r.cnpmjs.org/`) has also worked for me. I'm able to install packages again!

As far as issues with the official registry (`https://registry.npmjs.org/`) are concerned, I'm wondering whether it's something to do with location?? I'm in Sydney, Australia if that helps.

**Comment by koresar** [comment]
The proper workaround is here: https://github.com/npm/npm/issues/9574#issuecomment-139940172

**Comment by zeezali** [comment]
@koresar - Thanks!

Reverted back to `https://registry.npmjs.org` this morning. Everything seems to be back to normal!

I think it's safe to close this since it was just a temporary registry glitch. More info can be found here (under "Past incidents"): http://status.npmjs.org/

**Comment by mrseanryan** [comment]
in case it helps anyone

I had similar error

> npm ERR! registry error parsing json

I believe it covers many different scenarios ...

on reading the npm debug log file (npm-debug.log) - 
in my case, it was an authentication issue:

> 872 verbose headers   'x-tfs-serviceerror': 'TF400813%3a+Resource+not+available+for+anonymous+access.+Client+authentication+required

so I had to update my VSTS token (I'm using a npm feed on VSTS)

so in my case reading the log file helped a lot :)
