### ISSUE TITLE
Unable to install iron-meteor package

### ISSUE THREAD

**Issue by sreeraghuparuchuri** [npm/npm#9561]
After installing NPM, i am trying to install iron-meteor package and I was facing EACCESS issue. I followed the steps mentioned in the npm website to make changes and tested by installing jshint and it worked.

However, when I try to install iron-meteor package I am facing the below issue.

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "iron-meteor"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.3

npm ERR! version not found: fibers@1.0.6
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sreeraghuparuchuri/npm-debug.log

**Comment by KenanY** [comment]
@sreeraghuparuchuri This is an issue with `iron-meteor`. There is no such version of `fibers` in the registry, hence the error. Please see https://github.com/iron-meteor/iron-cli/issues/207.

**Comment by sreeraghuparuchuri** [comment]
@KenanY 
Hi,

So I tried installing the latest version of fibres and this is what I get...

Srees-MacBook-Air:~ sreeraghuparuchuri$ npm install "fibers"
-
> fibers@1.0.7 install /Users/sreeraghuparuchuri/node_modules/fibers
> node build.js || nodejs build.js

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: node-v4.0.0.tar.gz local checksum f0f68e9a0cdadcf5070c9ce26ed8212305309b6ad533728a137648a76444a4f9 not match remote e110e5a066f3a6fe565ede7dd66f3727384b9b5c5fbf46f8db723d726e2f5900
gyp ERR! stack     at deref (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:307:20)
gyp ERR! stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:348:13)
gyp ERR! stack     at emitNone (events.js:72:20)
gyp ERR! stack     at IncomingMessage.emit (events.js:166:7)
gyp ERR! stack     at endReadableNT (_stream_readable.js:893:12)
gyp ERR! stack     at doNTCallback2 (node.js:429:9)
gyp ERR! stack     at process._tickCallback (node.js:343:17)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /Users/sreeraghuparuchuri/node_modules/fibers
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
Build failed
sh: nodejs: command not found
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "fibers"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! fibers@1.0.7 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the fibers@1.0.7 install script 'node build.js || nodejs build.js'.
npm ERR! This is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js || nodejs build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sreeraghuparuchuri/orderApp/npm-debug.log

**Comment by sreeraghuparuchuri** [comment]
@KenanY : Hi,

So I tried installing the latest version of fibers and this is what i get

fibers@1.0.7 install /Users/sreeraghuparuchuri/node_modules/fibers
node build.js || nodejs build.js

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: node-v4.0.0.tar.gz local checksum f0f68e9a0cdadcf5070c9ce26ed8212305309b6ad533728a137648a76444a4f9 not match remote e110e5a066f3a6fe565ede7dd66f3727384b9b5c5fbf46f8db723d726e2f5900
gyp ERR! stack     at deref (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:307:20)
gyp ERR! stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:348:13)
gyp ERR! stack     at emitNone (events.js:72:20)
gyp ERR! stack     at IncomingMessage.emit (events.js:166:7)
gyp ERR! stack     at endReadableNT (_stream_readable.js:893:12)
gyp ERR! stack     at doNTCallback2 (node.js:429:9)
gyp ERR! stack     at process._tickCallback (node.js:343:17)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /Users/sreeraghuparuchuri/node_modules/fibers
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
Build failed
sh: nodejs: command not found
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "fibers"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! fibers@1.0.7 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the fibers@1.0.7 install script 'node build.js || nodejs build.js'.
npm ERR! This is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js || nodejs build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls fibers

**Comment by sreeraghuparuchuri** [comment]
Fixed here https://github.com/iron-meteor/iron-cli/issues/207
