### ISSUE TITLE
Optional Dependency install should probably be silent (or at least, less scary)

### ISSUE THREAD

**Issue by isaacs** [npm/npm#9567]
People get kind of freaked out when a big compilation thingie dumps a bunch of red stuff to the screen.  Even if, at the end, it "worked", this sends the message that things are broken somehow.

Idea: if a dependency is optional, buffer up the output from the build scripts, and log it all at `loglevel=silly` or some such.  Maybe output a warning line that says something like `optional dependency fooblz failed to build, continuing without it` (pending language bikeshedding).

References:
- https://github.com/websockets/ws/issues/577
- https://twitter.com/denormalize/status/642853007818801153

Another idea might be to just log the failures at `silly` or `info` rather than `warn` or `error`, but then the build output would still be dumped out, which might itself have a bunch of scary failures.

Definitely the failure output should not be _lost_ entirely, and needs to end up in the `npm-debug.log` file.  But it looks way too much like something alarming right now.

Doesn't seem important enough to put in 2.x rather than just moving forward somewhere in 3.x, but I'm happy to be outvoted on that by the cli team if y'all feel differently about it.

**Comment by aredridel** [comment]
Such a good idea.

**Comment by othiym23** [comment]
Pretty sure this is a dupe, but I won't know for sure until I check next week.

**Comment by feross** [comment]
Yes, +1000. This is much needed.

cc @maxogden @mafintosh

**Comment by johanneswuerbach** [comment]
This would definitely help us at testem / ember-cli

//cc @stefanpenner

**Comment by stefanpenner** [comment]
older & related issue: https://github.com/npm/npm/issues/7892

**Comment by othiym23** [comment]
This is related to #10491. That one puts the stdout and stderr of script output in `npm-debug.log`, this one only shows the output for commands where said output is relevant. We intend to add both within the next year, but as always, if people want to send us patches, we'd love to work with you to get them landed.

**Comment by stefanpenner** [comment]
Just an update, we ended up forking all the socket.io libs and created -pure variants. Not ideal, but no longer depending on any native deps has been a big ergonomic win.

It makes me wonder if optional deps should be just that, optional.  Just a thought, maybe not great either.

**Comment by feross** [comment]
ws no longer has a native dependency.

**Comment by stefanpenner** [comment]
Awesome, we will then have to give it a whirl. If memory serves their where several other issues, coupled with many months of inaction. But getting off out forks would be best

**Comment by johanneswuerbach** [comment]
I already did this (updated `ws` and moved back to upstream), but that isn't really solving the issue of that thread.

Optional dependency failures should be handled more quietly instead of suggesting to the user that `npm install` failed. When you are used to the npm output it might be clear, but I know a lot of other devs who thought something was broken, but it was only an optional native dependency failure.

**Comment by stefanpenner** [comment]
@johanneswuerbach  oh awesome, and yes you are correct. I was merely mentioning all this to shed some light on the symptoms/effort resulting from the current state.

**Comment by stereokai** [comment]
What about this issue?

It is very annoying and in fact, unacceptable, that our build fails because `node-gyp` can't find Pyhton 2 *for compiling an **optional** dependency*.

**Comment by Munter** [comment]
Follow up because I ran into this problem myself yesterday: The output for failed optional dependency installations is much better from npm@5.6.0, so try `npm install -g npm@latest` and give it a go again
