### ISSUE TITLE
npm ERR! Windows_NT 6.1.7601

### ISSUE THREAD

**Issue by suthanrag** [npm/npm#9572]
I am getting the following error at the end of the app generation.However, I could see the App Running but with an awkward UI, missing a lot of front end stuff. Please advice. Kindly request for npm debug file, If required. Thanks in advance.

```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2

npm ERR! shasum check failed for C:\Windows\TEMP\npm-2204-8c22c412\registry.npmjs.org\cdnjs-cdn-data\-\cdnjs-cdn-data-0.1.2.tgz
npm ERR! Expected: 865d34ba4e48dd1b73fd668e24a61a5adf9b8b21
npm ERR! Actual:   c1350dbeaf4893c2bf6b3a86501ba667496c3afc
npm ERR! From:     https://registry.npmjs.org/cdnjs-cdn-data/-/cdnjs-cdn-data-0.1.2.tgz
```

**Comment by KenanY** [comment]
@suthanrag Have you tried `npm cache clear`?

**Comment by suthanrag** [comment]
@Kenan : Yup Ken. I did. I actually had different issues, before that, I jus resolved those with npm cache clear and a couple of other steps. But at this point I am left with no options.

**Comment by ronglen** [comment]
npm ERR! Expected: 865d34ba4e48dd1b73fd668e24a61a5adf9b8b21
npm ERR! Actual:   a7af13481abac78daf0a3df40b47d89cf3b36004
npm ERR! From:     https://registry.npmjs.org/cdnjs-cdn-data/-/cdnjs-cdn-data-0.1.2.tgz

also have the issue now

**Comment by suthanrag** [comment]
Hi Kenan,

Yup. I did. The issue got resolved. Thanks

Thanks & Regards,

Raghu

**Comment by KenanY** [comment]
Closing as resolved.
