### ISSUE TITLE
Opening www.npmjs.com results with 503

### ISSUE THREAD

**Issue by koresar** [npm/npm#9575]
Sydney mirror is down. Please, update your status page accrodingly http://status.npmjs.org/

![screen shot 2015-09-14 at 9 50 18 am](https://cloud.githubusercontent.com/assets/1622575/9839757/10bab5d6-5ac6-11e5-8343-48c6f9235cf1.png)

**Comment by KenanY** [comment]
@koresar This repo is for issues with the `npm` CLI. Issues with the website should be opened over [here](https://github.com/npm/newww).

**Comment by koresar** [comment]
Thanks!

**Comment by koresar** [comment]
Created a new one here: https://github.com/npm/newww/issues/1322
I strongly believe these two are related: https://github.com/npm/npm/issues/9574
