### ISSUE TITLE
Drag and drop to install package.

### ISSUE THREAD

**Issue by coderextreme** [npm/npm#9576]
Can I drag and drop a package from a web page to a package.json to install a node module in a local folder?

**Comment by KenanY** [comment]
@coderextreme That sounds like it would be incredibly difficult to do for little practical reward. In fact, I believe a feature like this would have to be implemented by your web browser, no?

**Comment by coderextreme** [comment]
You could have a special protocol for a URL, say npm:// .   Then you would have to get into the desktop and figure out what happens when you drop that link onto package.json.  I would think that similar things would have been done, like clicking on a link in android brings up the app store.

I don’t really know how difficult it is until I research it some more.  Copy paste may be easier than drag and drop.

John

**Comment by othiym23** [comment]
This isn't something that npm itself is going to do. It sounds like a fascinating hack / browser extension / something else for somebody who was looking for a fun hacking project, though! Good luck to whomever takes that on!
