### ISSUE TITLE
[docs:scripts] Reference to node-waf

### ISSUE THREAD

**Issue by ronkorving** [npm/npm#9583]
This *has* to be some overlooked legacy, right? See: https://docs.npmjs.com/misc/scripts

ref: https://github.com/npm/newww/issues/1323
cc @aredridel

**Comment by aredridel** [comment]
Sure is. node-waf went out with the arrival of node 0.8; the current default involves some shenanigans around node-gyp instead. #9584 looks right to me, anyway!
