### ISSUE TITLE
Separate credentials for each different scopes backed by same registry

### ISSUE THREAD

**Issue by mhofman** [npm/npm#9587]
Let's suppose I have packages on 2 different scopes (or some scoped and some un-scoped packages) that are backed by the same registry.

I would like to use different credentials to access each scope.

From what I understand this is not possible today, even though the documentation doesn't make that clear:
- The [code responsible](https://github.com/npm/npm/blob/b50be6aff34a739ca43de65f546e743d1a9975b9/lib/utils/map-to-registry.js#L48) for auth credentials lookup only considers the registry URL, not the scope if any.
- The [documentation](https://docs.npmjs.com/cli/adduser) seem to imply username and password are associated with the scope, not the registry: `If specified, the user and login credentials given will be associated with the specified scope`

The way I see it you should be able to define a set of credentials for a specific registry, and override them in a specific scope.

**Comment by othiym23** [comment]
This is something that would require some fairly significant changes to both the CLI and the registry and its ACL, so before we go any further into discussing how this might work, let me first ask: what problem would this solve for you?

**Comment by mhofman** [comment]
We're considering using NPM Private Modules for hosting some internal packages but the user management seem a bit limited right now, especially if developers already have an npm user. One option I was thinking of was to provision an organizational account for developers to perform operations on the organization's private modules, but this registry / scope credential overlap would prevent developers from keeping their npm user if any.

**Comment by othiym23** [comment]
It sounds like you want [npm organizations and teams](https://docs.npmjs.com/getting-started/working-with-orgs)! It's in the very early stages of beta rollout right now, but that's where this is likely to be added, and it works with the npm and the registry we have right now. As such, I'm going to close this out. Check that out and request access to the beta, if you're interested. Thanks for providing a detailed answer!

**Comment by mhofman** [comment]
Thanks, just requested access. I can't find any info on orgs besides that command line usage you linked. Is there any more info anywhere?

Btw, I would say the issue is still somewhat valid, the documentation is not clear on what credentials are linked to.

**Comment by othiym23** [comment]
The interface is mostly via the CLI for now, although we'll be rolling the management features out to the web site as we get them ready.

> I would say the issue is still somewhat valid, the documentation is not clear on what credentials are linked to.

A PR that takes a stab at getting the docs to where you feel they're useful is something that would be gratefully accepted, and would probably get merged fairly quickly. They look pretty clear to me, but I know how everything's implemented, so I may not be the best person to be writing them (if that makes sense).
