### ISSUE TITLE
Error "Callback called more than once"

### ISSUE THREAD

**Issue by saharj** [npm/npm#9588]
After cloning [angular.io repository](https://github.com/angular/angular.io), when you try to do the "npm install" you get the following error message:
"Callback called more than once."
Here is my console output: 
```
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "install"
npm ERR! node v2.3.1
npm ERR! npm  v2.11.3

npm ERR! Callback called more than once.
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sahar/Documents/angulario/angular.io/npm-debug.log
```
Here's the [log](https://gist.github.com/saharj/7090903989e125ce062a).

**Comment by saharj** [comment]
I upgraded to the latest npm and node from node.js, and then tried to install. It prompted several errors during the installation, but it said the installation was successful at the end.

Here is my log: https://gist.githubusercontent.com/saharj/ebb5ecff595691509993/raw/728bc7b775ba5947129b140bd07870b7b49216a8/output.log

**Comment by ehsalazar** [comment]
@saharj It appears upgrading worked and the install was successful, less a few warning. Were you able to utilize the module? If so, I'll close out this issue.

**Comment by ehsalazar** [comment]
If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.

**Comment by saharj** [comment]
I don't know! I had this problem more than a month ago, and I'm not using it anymore.
