### ISSUE TITLE
npm --verbose is not outputting to stdout

### ISSUE THREAD

**Issue by saharj** [npm/npm#9589]
```
npm install --verbose > output.log
```
This command doesn't work, but it works without `--verbose`.
npm version: 2.14.2

**Comment by KenanY** [comment]
@saharj Works for me (`npm@2.14.4`):

``` sh
$ npm install --verbose > output.log
$ cat output.log 
concat-stream@1.5.0 node_modules/concat-stream
├── inherits@2.0.1
├── typedarray@0.0.6
└── readable-stream@2.0.2 (isarray@0.0.1, process-nextick-args@1.0.3, util-deprecate@1.0.1, string_decoder@0.10.31, core-util-is@1.0.1)
```

**Comment by saharj** [comment]
I don't know where to get `npm@2.14.4`. The command didn't work on `npm@2.14.3` either.
Also, I'm using fish.

**Comment by KenanY** [comment]
@saharj (I'm using bash if it matters)

``` sh
$ npm --version
2.14.3
$ npm install --verbose > output.log
$ cat output.log 
concat-stream@1.5.0 node_modules/concat-stream
├── inherits@2.0.1
├── typedarray@0.0.6
└── readable-stream@2.0.2 (isarray@0.0.1, process-nextick-args@1.0.3, util-deprecate@1.0.1, string_decoder@0.10.31, core-util-is@1.0.1)
```

**Comment by ehsalazar** [comment]
Based on the other [issue](https://github.com/npm/npm/issues/9588) you submitted, I sounds like you were able to upgrade. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.

**Comment by saharj** [comment]
I am not using this now, so I don't know if the issue still exists or it's fixed.
