### ISSUE TITLE
Install dev dependencies without running prepublish

### ISSUE THREAD

**Issue by gagern** [npm/npm#9590]
I'd like some functionality to install resp. upgrade to the latest version of all `dependencies` and `devDependencies` of the current project, without running the prepublish script of the current project, and without recursively installing `devDependencies`. Preferrably via some flag to `npm update` which chooses the union of `dependencies` and `devDependencies` at the top level, but doesn't get applied recursively.

Use case: I'm developing an application which mainly relies on `make` to organize its build. The `Makefile` is also responsible for setting up the build environment. It even downloads node if that isn't present, so it makes sense to also install dependencies from the `Makefile`. On the other hand, it makes sense to use a `package.json` to note the required versions of all `dependencies` and `devDependencies`. And if you have a `package.json`, people might expect the `prepublish` script to build the project, i.e. call `make` at some point. This, however can lead to an infinite loop: Make detects that the dependencies haven't been installed yet, and calls `npm install` to get them before touching some stamp file. However, the `npm install` call runs make, recursing infinitely. Using `npm update` instead of `npm install` works nicely for non-dev `dependencies`, but for `devDependencies` it's effect is recursive, installing way more packages than would actually be needed.

**Comment by othiym23** [comment]
I see the use case, but this is marginal enough that I don't think it's worth adding support for it to npm proper. There are ways to use npm and make together that don't conflict with each other, and this situation would be brittle even were we to add the functionality you're describing. Fundamentally, making `Makefile`s and npm interdependent like this is fragile.

However, I do have a workaround for you if you're using `npm@3`, thanks to some recent contributions from @bengl:

```
npm install --only=prod
npm install --only=dev --ignore-scripts
```

You could try putting one or both of these commands in the Makefile, and I believe it will give you the behavior you need.
