### ISSUE TITLE
can't install two older packages from their tar.gz with npm

### ISSUE THREAD

**Issue by Ir1sh** [npm/npm#9592]
I am trying to move all our dependencies from bower to npm.  My npm version is 2.14.3 I have been able to do this for all bar two packages parselyjs and ng-currency.  The former has newer versions on npm but I need a version that is not on there 1.2.2.  The latter has nothing registered with npm.  the github repos are https://github.com/guillaumepotier/Parsley.js and https://github.com/aguirrel/ng-currency

I have tried to install them with the cli and in different projects to this one and always get the same error.

I have tried the following syntax in my package.json to no avail even though this syntax is working fine with other repos

```
"dependencies": {
    "parsley": "https://github.com/guillaumepotier/Parsley.js/archive/1.2.2.tar.gz",
    "ng-currency": "https://github.com/aguirrel/ng-currency/archive/v0.7.10.tar.gz"
}
```

```
"dependencies": {
    "parsley": "git://github.com/guillaumepotier/Parsley.js.git#1.2.2",
    "ng-currency": "git://github.com/aguirrel/ng-currency/archive/v0.7.10.tar.gz"
}
```

The error looks like this

```
npm WARN package.json blah@0.0.0 No README data
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.26
npm ERR! npm  v2.14.0
npm ERR! path /var/folders/12/x0kkr1fd4w157d_j37b28kf00000gn/T/npm-3514-30dafc7d/unpack-41b7fb162ef4/package.json
npm ERR! code ENOENT
npm ERR! errno 34

npm ERR! enoent ENOENT, open '/var/folders/12/x0kkr1fd4w157d_j37b28kf00000gn/T/npm-3514-30dafc7d/unpack-41b7fb162ef4/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Mark/workspace/blah/npm-debug.log
```

I can provide npm-debug.log if necessary, any advice is greatly appreciated, thanks

**Comment by KenanY** [comment]
@Ir1sh

  - `guillaumepotier/Parsley.js#1.2.2` does not have a `package.json`
  - `aguirrel/ng-currency#0.7.10` does not have a `package.json`

**Comment by Ir1sh** [comment]
ah that makes sense, is it possible to force npm to install them anyway?

**Comment by KenanY** [comment]
@Ir1sh Erm, no. You wouldn't even be able to `require` them if you wanted to:

``` sh
$ wget -qO- https://github.com/guillaumepotier/Parsley.js/archive/1.2.2.tar.gz | tar xz -C node_modules/
$ mv node_modules/Parsley.js-1.2.2 node_modules/parsley
$ node
> require('parsley')
Error: Cannot find module 'parsley'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at repl:1:1
    at REPLServer.defaultEval (repl.js:164:27)
    at bound (domain.js:250:14)
    at REPLServer.runBound [as eval] (domain.js:263:12)
    at REPLServer.<anonymous> (repl.js:392:12)
    at emitOne (events.js:82:20)
>
```

If you just want them downloaded I would use `wget`. A `package.json` is a strict expectation of both `npm` and the `node` module loading system.

**Comment by Ir1sh** [comment]
thanks I dont need to be able to require them these will be used in the browser I just need them downloaded so thanks I will try that

**Comment by othiym23** [comment]
Closing as the spiritual equivalent of a `WONTFIX`. npm only installs packages. and `package.json` is what makes a tarball a package.
