### ISSUE TITLE
npm ls shows too many packages (npm@3)

### ISSUE THREAD

**Issue by mzgol** [npm/npm#9593]
```
$ node --version
v4.0.0
$ npm --version
3.3.2
$ ls -1 .nvm/versions/node/v4.0.0/lib/node_modules/
bower
caniuse-cmd
david
grunt-cli
http-server
iron-node
jspm
mime-types
node-gyp
nodemon
npm
npm-bump
recursive-blame
request
trash
yo
$ npm -g ls --depth=0
/Users/mgol/.nvm/versions/node/v4.0.0/lib
├── async@1.4.2
├── bower@1.5.2
├── caniuse-cmd@1.1.1
├── chalk@1.1.1
├── david@6.2.0
├── form-data@1.0.0-rc3
├── grunt-cli@0.1.13
├── http-server@0.8.0
├── iron-node@1.5.32
├── is-my-json-valid@2.12.2
├── jspm@0.16.2
├── mime-types@2.1.5
├── node-gyp@3.0.2
├── nodemon@1.5.0
├── npm@3.3.2
├── npm-bump@0.0.13
├── recursive-blame@0.2.1
├── request@2.61.0
├── trash@2.0.0
└── yo@1.4.8
```

Packages `async`, `chalk`, `form-data` & `is-my-json-valid` shouldn't appear in the top level of the `npm ls` tree.

**Comment by othiym23** [comment]
It looks like you installed some of your global packages with a version of npm 3 that predates the one that silos each global package into its own directory. Does this recur if you nuke your global packages and try reinstalling all of the packages that should be in the top-level listing?

**Comment by mzgol** [comment]
Removing all global packages & installing them again helped. Not sure if you want to do anything about it then. :)

**Comment by othiym23** [comment]
Because there's not a good general way to clean up packages that were installed globally with early versions of the `npm@3` beta, we're just going to go ahead and close this. Thanks for reporting it and following up with your results!
