### ISSUE TITLE
NPM downloading nothing but empty files.

### ISSUE THREAD

**Issue by CoreyDotCom** [npm/npm#9601]
Can't npm install, all files downloaded are 0 length:

npm ERR! tar.unpack error reading /tmp/npm-27303-084f3f74/registry.npmjs.org/glob/-/glob-3.2.3.tgz
npm ERR! tar.unpack error reading /tmp/npm-27303-084f3f74/registry.npmjs.org/glob/-/glob-3.2.3.tgz
npm ERR! tar.unpack error reading /tmp/npm-27303-084f3f74/registry.npmjs.org/xtend/-/xtend-4.0.0.tgz
npm ERR! tar.unpack error reading /tmp/npm-27303-084f3f74/registry.npmjs.org/kind-of/-/kind-of-2.0.0.tgz
npm ERR! tar.unpack error reading /tmp/npm-27303-084f3f74/registry.npmjs.org/xtend/-/xtend-4.0.0.tgz

**Comment by CoreyDotCom** [comment]
Seems to work fine with https://registry.nodejitsu.com, but not the default registry http://registry.npmjs.org.

**Comment by lxe** [comment]
I'm experiencing this as well. Looks like something is awry, even though http://status.npmjs.org/ is showing all green.

**Comment by CoreyDotCom** [comment]
Yep and now I'm experiencing it from the mirrors as well.

**Comment by KenanY** [comment]
https://github.com/npm/npm/issues/9600 was opened even earlier than this one :smirk:

**Comment by CoreyDotCom** [comment]
So does the npm core team regularly monitor these issues? Odd that - http://status.npmjs.org/ is still happy.

**Comment by cgadam** [comment]
+1 having issues while downloading several modules. 
All related to 0 bytes tarball.
The registry status still green.

**Comment by seldo** [comment]
We apologize. A canary server rolled out earlier had a bug and we have rolled it back. Follow here for updated: https://npmjs.statuspage.io/incidents/pyw00fmpjzrh

**Comment by CoreyDotCom** [comment]
Still happening but assume we just need to wait til the fix propagates?

**Comment by seldo** [comment]
Leaving this open while @mmalecki completes cache invalidations, yes.

**Comment by seldo** [comment]
@CoreyDotCom to your earlier question: we monitor like crazy, but unfortunately the bug was serving empty tarballs as HTTP 200 -- so none of our usual monitoring caught it. We're currently deciding how we can better detect this type of mistake.

**Comment by CoreyDotCom** [comment]
Thanks!, about how many minutes/hours for the registries to all be back in working order? Just curious.

**Comment by seldo** [comment]
I just updated the status incident, but ~15 minutes.

**Comment by seldo** [comment]
Resolved.
