### ISSUE TITLE
Error while installing live-server

### ISSUE THREAD

**Issue by rbakersmith** [npm/npm#9603]
I'm getting the following error while trying to install live-server:

```
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "live-server"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4

npm ERR! shasum check failed for C:\Users\Ryan\AppData\Local\Temp\npm-7108-5a1c5507\registry.npmjs.org\event-stream\-\event-stream-3.3.1.tgz
npm ERR! Expected: b8cf6c00119181e688f335363daa7915ce890bdb
npm ERR! Actual:   da39a3ee5e6b4b0d3255bfef95601890afd80709
npm ERR! From:     https://registry.npmjs.org/event-stream/-/event-stream-3.3.1.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\code\aurelia-typescript-lean-dev\npm-debug.log
```

Running `npm cache clear` didn't help either.
<hr>
Updated node to 4.0.0 and npm to 2.14.3 and still getting error.

**Comment by TeffenEllis** [comment]
Also facing similar issues with checksum failures.

**Comment by pliashkou** [comment]
Confirm, please fix ASAP

**Comment by tommaitland** [comment]
Also facing these issues - any ideas? I've run `npm cache clear` and updated npm.

```
npm ERR! Darwin 14.3.0
npm ERR! argv "/usr/local/Cellar/node/0.10.28/bin/node" "/usr/local/bin/npm" "install" "mailgun-js"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2

npm ERR! shasum check failed for /var/folders/jz/r3fqnxns1wjb_dbxmspbjyfw0000gn/T/npm-18317-1d4ce368/registry.npmjs.org/https-proxy-agent/-/https-proxy-agent-0.3.6.tgz
npm ERR! Expected: 713fa38e5d353f50eb14a342febe29033ed1619b
npm ERR! Actual:   da39a3ee5e6b4b0d3255bfef95601890afd80709
npm ERR! From:     https://registry.npmjs.org/https-proxy-agent/-/https-proxy-agent-0.3.6.tgz
```

**Comment by FeodorFitsner** [comment]
I can confirm that. Node.js projects on AppVeyor are failing with the same error.

**Comment by kamilbrk** [comment]
Same thing, our AppVeyor support ticket with examples:
http://help.appveyor.com/discussions/problems/3050

(thanks @FeodorFitsner!)

**Comment by FeodorFitsner** [comment]
I'm getting the same error while trying to install gulp on my local dev machine:

```
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "gulp"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2

npm ERR! shasum check failed for C:\Users\Feodor\AppData\Local\Temp\npm-16124-86574ef4\registry.npmjs.org\dateformat\-\dateformat-1.0.11.tgz
npm ERR! Expected: f27cbee7a012bbfb82ea051562d3977f6093dbb1
npm ERR! Actual:   da39a3ee5e6b4b0d3255bfef95601890afd80709
npm ERR! From:     https://registry.npmjs.org/dateformat/-/dateformat-1.0.11.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Projects\2\npm-debug.log
```

**Comment by o5** [comment]
+1 for fix pls :)

**Comment by andyday** [comment]
I'm getting the same error on AppVeyor.

```
npm install -g gulp
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\iojs\\iojs.exe" "C:\\Program Files (x86)\\iojs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "gulp"
npm ERR! node v2.5.0
npm ERR! npm  v2.13.2
 
npm ERR! shasum check failed for C:\Users\appveyor\AppData\Local\Temp\1\npm-1624-a1cc1d1a\registry.npmjs.org\dateformat\-\dateformat-1.0.11.tgz
npm ERR! Expected: f27cbee7a012bbfb82ea051562d3977f6093dbb1
npm ERR! Actual:   da39a3ee5e6b4b0d3255bfef95601890afd80709
npm ERR! From:     https://registry.npmjs.org/dateformat/-/dateformat-1.0.11.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
 
npm ERR! Please include the following file with any support request:
npm ERR!     C:\projects\cloud\npm-debug.log
```

**Comment by malonecj** [comment]
me too 
```
Build started
git config --global core.autocrlf input
git clone -q --branch=master git@github.com:adazzle/AdazzleUI.git C:\projects\adazzleui
git checkout -qf e1d35f56d4018647f38dd63431c2f25ac352d9f0
Restoring build cache
Skip restoring "C:\Users\appveyor\AppData\Roaming\npm\node_modules" as one of the dependencies (package.json) changed
Skip restoring "C:\Users\appveyor\AppData\Roaming\npm-cache" as one of the dependencies (package.json) changed
Skip restoring "node_modules" as one of the dependencies (package.json) changed
Running Install scripts
Install-Product node 0
npm -g install npm@2.11.3
C:\Users\appveyor\AppData\Roaming\npm\npm -> C:\Users\appveyor\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
npm@2.11.3 C:\Users\appveyor\AppData\Roaming\npm\node_modules\npm
set PATH=%APPDATA%\npm;%PATH%
npm install -g gulp
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "node" "C:\\Users\\appveyor\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "gulp"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
 
npm ERR! shasum check failed for C:\Users\appveyor\AppData\Local\Temp\1\npm-2488-53ce4372\registry.npmjs.org\lodash._reevaluate\-\lodash._reevaluate-3.0.0.tgz
npm ERR! Expected: 58bc74c40664953ae0b124d806996daca431e2ed
npm ERR! Actual:   da39a3ee5e6b4b0d3255bfef95601890afd80709
npm ERR! From:     https://registry.npmjs.org/lodash._reevaluate/-/lodash._reevaluate-3.0.0.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
 
npm ERR! Please include the following file with any support request
```

**Comment by aredridel** [comment]
@o5: you probably want to get current versions of things, though this is probably a network problem in addition.

**Comment by lxe** [comment]
I'm seeing 0-length tarballs getting served consistently for 'https://registry.npmjs.org/lodash._reevaluate/-/lodash._reevaluate-3.0.0.tgz'

**Comment by dantepsychedelico** [comment]
me too

```
root@43e4b3fcee45:/# npm install -g mean-cli
/
> mean-cli@0.10.14 preinstall /usr/local/lib/node_modules/mean-cli
> node ./scripts/preinstall

npm WARN deprecated json-file-plus@2.0.0: Before v3.0.0, errors in fs.writeFile would not be propagated
npm ERR! Linux 3.16.0-30-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "mean-cli"
npm ERR! node v0.10.38
npm ERR! npm  v2.10.0

npm ERR! shasum check failed for /tmp/npm-7-ef7c751c/registry.npmjs.org/lodash/-/lodash-2.4.2.tgz
npm ERR! Expected: fadd834b9683073da179b3eae6d9c0d15053f73e
npm ERR! Actual:   da39a3ee5e6b4b0d3255bfef95601890afd80709
npm ERR! From:     https://registry.npmjs.org/lodash/-/lodash-2.4.2.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
```

**Comment by yerfinojul** [comment]
+1

**Comment by oliverjanik** [comment]
Me too:

```
C:\Users\Oliver\dev\webpack-test>npm install -g clone
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\Oliver\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "clone"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.3

npm ERR! shasum check failed for C:\Users\Oliver\AppData\Local\Temp\npm-14936-8decd9b9\registry.npmjs.org\clone\-\clone-1.0.2.tgz
npm ERR! Expected: 260b7a99ebb1edfe247538175f783243cb19d149
npm ERR! Actual:   da39a3ee5e6b4b0d3255bfef95601890afd80709
npm ERR! From:     http://registry.npmjs.org/clone/-/clone-1.0.2.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Oliver\dev\webpack-test\npm-debug.log
```

**Comment by SunnyTam** [comment]
+1
```
node v4.0.0
npm ERR! npm  v2.14.2

npm ERR! shasum check failed for /var/folders/qy/v3tkshr524v0gg0qbrr___gh0000gn/T/npm-7018-8c0e9ff4/registry.npmjs.org/through2/-/through2-0.6.5.tgz
npm ERR! Expected: 41ab9c67b29d57209071410e1d7a7a968cd3ad48
npm ERR! Actual:   da39a3ee5e6b4b0d3255bfef95601890afd80709
npm ERR! From:     https://registry.npmjs.org/through2/-/through2-0.6.5.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by mmalecki** [comment]
Hey folks, sorry about this issue. The problem was caused by a bug in code we rolled out to our canary server today morning, and which our automated checks haven't caught. We just rolled back the deploy and are working on invalidating our caches.

Here's an incident on our status page: https://npmjs.statuspage.io/incidents/pyw00fmpjzrh

**Comment by mohan08p** [comment]
Same while creating docker image of node:0.10.38 in which while installing dependencies, npm

Here is the stack-trace of the error,                                                                                                 
npm ERR! package.json ENOENT, open '/home/scrapebook/tutorial/app/package.json'                    
npm ERR! package.json This is most likely not a problem with npm itself.                           
npm ERR! package.json npm can't find a package.json file in your current directory.                
                                                                                                   
npm ERR! Please include the following file with any support request:                               
npm ERR!     /home/scrapebook/tutorial/app/npm-debug.log                                           
The command '/bin/sh -c npm install' returned a non-zero code: 34

**Comment by seldo** [comment]
Hi @mohan08p, I don't believe this is the same error. Can you please open a different issue with your full npm-debug.log?

**Comment by PremkumarAgrawal** [comment]
Mee too Getting same error

C:\Users\premkumar.agrawal>npm install ionic cordova -g
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm a
nd is now out of date with respect to npm
npm ERR! fetch failed https://registry.npmjs.org/browserify-transform-tools/-/br
owserify-transform-tools-1.5.3.tgz
npm WARN retry will retry, error on last attempt: Error: socket hang up
npm ERR! Windows_NT 6.1.7600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "ionic" "cordova" "-g"
npm ERR! node v5.8.0
npm ERR! npm  v3.7.3
npm ERR! code ENETUNREACH
npm ERR! errno ENETUNREACH
npm ERR! syscall connect

npm ERR! connect ENETUNREACH 103.245.222.162:443
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\premkumar.agrawal\npm-debug.log

**Comment by PremkumarAgrawal** [comment]
C:\Users\premkumar.agrawal>npm install -g ionic
C:\Users\premkumar.agrawal\AppData\Roaming\npm\ionic -> C:\Users\premkumar.agraw
al\AppData\Roaming\npm\node_modules\ionic\bin\ionic

> node-sass@3.4.2 install C:\Users\premkumar.agrawal\AppData\Roaming\npm\node_mo
dules\ionic\node_modules\node-sass
> node scripts/install.js

Binary downloaded and installed at C:\Users\premkumar.agrawal\AppData\Roaming\np
m\node_modules\ionic\node_modules\node-sass\vendor\win32-ia32-47\binding.node

> spawn-sync@1.0.15 postinstall C:\Users\premkumar.agrawal\AppData\Roaming\npm\n
ode_modules\ionic\node_modules\spawn-sync
> node postinstall


> node-sass@3.4.2 postinstall C:\Users\premkumar.agrawal\AppData\Roaming\npm\nod
e_modules\ionic\node_modules\node-sass
> node scripts/build.js

` C:\Users\premkumar.agrawal\AppData\Roaming\npm\node_modules\ionic\node_modules
\node-sass\vendor\win32-ia32-47\binding.node ` exists.
 testing binary.
Binary is fine; exiting.
C:\Users\premkumar.agrawal\AppData\Roaming\npm
`-- ionic@1.7.14
  +-- cli-table@0.3.1
  | `-- colors@1.0.3
  +-- connect@3.1.1
  | `-- utils-merge@1.0.0
  +-- expand-tilde@1.2.0
  | `-- user-home@1.1.1
  +-- gulp@3.8.8
  | +-- gulp-util@3.0.7
  | | +-- dateformat@1.0.12
  | | +-- fancy-log@1.1.0
  | | +-- through2@2.0.0
  | | | `-- readable-stream@2.0.5
  | | |   `-- util-deprecate@1.0.2
  | | `-- vinyl@0.5.3
  | +-- liftoff@0.12.1
  | | `-- findup-sync@0.1.3
  | |   `-- lodash@2.4.2
  | `-- orchestrator@0.3.7
  |   `-- end-of-stream@0.1.5
  |     `-- once@1.3.3
  |       `-- wrappy@1.0.1
  +-- ionic-app-lib@0.7.0
  | +-- archiver@0.5.2
  | | +-- lazystream@0.1.0
  | | | `-- readable-stream@1.0.33
  | | +-- lodash@2.4.2
  | | +-- readable-stream@1.0.33
  | | `-- zip-stream@0.1.4
  | |   `-- readable-stream@1.0.33
  | +-- cross-spawn@2.0.0
  | | +-- cross-spawn-async@2.1.8
  | | | +-- lru-cache@4.0.0
  | | | | `-- yallist@2.0.0
  | | | `-- which@1.2.4
  | | `-- spawn-sync@1.0.15
  | |   `-- concat-stream@1.5.1
  | |     `-- readable-stream@2.0.5
  | +-- ionic-cordova-lib@5.1.10
  | | +-- cordova-js@4.0.0
  | | | +-- browserify@10.1.3
  | | | | +-- assert@1.3.0
  | | | | +-- browser-pack@4.0.4
  | | | | | `-- through2@0.5.1
  | | | | |   `-- readable-stream@1.0.33
  | | | | +-- deps-sort@1.3.9
  | | | | | `-- through2@1.1.1
  | | | | +-- glob@4.5.3
  | | | | +-- insert-module-globals@6.6.3
  | | | | | `-- through2@1.1.1
  | | | | +-- labeled-stream-splicer@1.0.2
  | | | | | `-- stream-splicer@1.3.2
  | | | | |   `-- through2@1.1.1
  | | | | +-- module-deps@3.9.1
  | | | | | +-- stream-combiner2@1.0.2
  | | | | | | `-- through2@0.5.1
  | | | | | |   `-- readable-stream@1.0.33
  | | | | | `-- through2@1.1.1
  | | | | +-- through2@1.1.1
  | | | | +-- url@0.10.3
  | | | | | `-- punycode@1.3.2
  | | | | +-- util@0.10.3
  | | | | `-- vm-browserify@0.0.4
  | | | `-- uglify-js@2.6.1
  | | |   `-- async@0.2.10
  | | +-- glob@4.0.6
  | | | `-- graceful-fs@3.0.8
  | | +-- init-package-json@1.9.3
  | | | +-- glob@6.0.4
  | | | +-- read-package-json@2.0.3
  | | | | `-- glob@6.0.4
  | | | +-- validate-npm-package-license@3.0.1
  | | | `-- validate-npm-package-name@2.2.2
  | | +-- npm@2.14.17
  | | | +-- cmd-shim@2.0.1
  | | | | `-- graceful-fs@3.0.8
  | | | +-- glob@5.0.15
  | | | +-- inflight@1.0.4
  | | | +-- node-gyp@3.2.1
  | | | | `-- glob@4.5.3
  | | | +-- normalize-package-data@2.3.5
  | | | +-- npm-registry-client@7.0.9
  | | | | `-- concat-stream@1.5.1
  | | | |   `-- readable-stream@2.0.4
  | | | |     `-- util-deprecate@1.0.2
  | | | +-- once@1.3.3
  | | | +-- request@2.67.0
  | | | | +-- bl@1.0.0
  | | | | | `-- readable-stream@2.0.4
  | | | | |   `-- util-deprecate@1.0.2
  | | | | +-- har-validator@2.0.3
  | | | | | `-- is-my-json-valid@2.12.3
  | | | | |   `-- xtend@4.0.1
  | | | | `-- http-signature@1.1.0
  | | | |   `-- jsprim@1.2.2
  | | | |     `-- verror@1.3.6
  | | | +-- validate-npm-package-license@3.0.1
  | | | +-- validate-npm-package-name@2.2.2
  | | | `-- wrappy@1.0.1
  | | +-- npmconf@2.1.2
  | | +-- plist@1.1.0
  | | | `-- xmldom@0.1.22
  | | +-- through2@0.6.3
  | | | `-- readable-stream@1.0.33
  | | `-- valid-identifier@0.0.1
  | +-- node-sass@3.4.2
  | | +-- cross-spawn@2.1.5
  | | +-- glob@5.0.15
  | | | `-- inflight@1.0.4
  | | +-- meow@3.7.0
  | | | +-- normalize-package-data@2.3.5
  | | | `-- read-pkg-up@1.0.1
  | | |   `-- read-pkg@1.1.0
  | | +-- node-gyp@3.2.1
  | | +-- request@2.69.0
  | | | +-- bl@1.0.1
  | | | | `-- readable-stream@2.0.5
  | | | +-- har-validator@2.0.6
  | | | | `-- is-my-json-valid@2.12.4
  | | | `-- http-signature@1.1.1
  | | |   `-- jsprim@1.2.2
  | | |     `-- verror@1.3.6
  | | `-- sass-graph@2.1.0
  | |   +-- glob@6.0.4
  | |   `-- yargs@3.10.0
  | |     +-- camelcase@1.2.1
  | |     +-- cliui@2.1.0
  | |     `-- window-size@0.1.0
  | +-- opbeat-ionic@1.1.3
  | | +-- after-all@2.0.2
  | | `-- stackman@0.2.3
  | +-- unzip2@0.2.5
  | | +-- fstream@0.1.31
  | | | `-- graceful-fs@3.0.8
  | | `-- readable-stream@1.0.33
  | +-- vinyl-fs@1.0.0
  | | +-- duplexify@3.4.2
  | | | +-- end-of-stream@1.0.0
  | | | `-- readable-stream@2.0.5
  | | +-- glob-stream@4.1.1
  | | | +-- glob@4.5.3
  | | | `-- unique-stream@2.2.0
  | | |   `-- through2-filter@2.0.0
  | | +-- graceful-fs@3.0.8
  | | +-- merge-stream@0.1.8
  | | | `-- through2@0.6.5
  | | |   `-- readable-stream@1.0.33
  | | +-- strip-bom@1.0.0
  | | +-- through2@0.6.5
  | | | `-- readable-stream@1.0.33
  | | `-- vinyl@0.4.6
  | |   `-- clone@0.2.0
  | `-- winston@1.1.2
  |   +-- async@1.0.0
  |   `-- colors@1.0.3
  +-- npm@2.1.3
  | +-- npm-registry-client@3.2.2
  | | `-- npmlog@2.0.3
  | |   `-- are-we-there-yet@1.1.2
  | |     `-- readable-stream@2.0.6
  | `-- wrappy@1.0.1
  +-- optimist@0.6.0
  | `-- wordwrap@0.0.2
  +-- prompt@0.2.12
  | `-- utile@0.2.1
  |   `-- async@0.2.10
  +-- request@2.51.0
  | `-- bl@0.9.5
  |   `-- readable-stream@1.0.33
  +-- serve-static@1.7.1
  +-- unzip@0.1.9
  | +-- fstream@0.1.31
  | | `-- graceful-fs@3.0.8
  | +-- match-stream@0.0.2
  | | `-- readable-stream@1.0.33
  | +-- pullstream@0.4.1
  | | +-- readable-stream@1.0.33
  | | `-- slice-stream@1.0.0
  | |   `-- readable-stream@1.0.33
  | `-- readable-stream@1.0.33
  +-- vinyl-fs@0.3.7
  | +-- glob-stream@3.1.18
  | | +-- glob@4.5.3
  | | `-- through2@0.6.5
  | |   `-- readable-stream@1.0.33
  | +-- graceful-fs@3.0.8
  | +-- lodash@2.4.2
  | +-- strip-bom@1.0.0
  | +-- through2@0.6.5
  | | +-- readable-stream@1.0.33
  | | `-- xtend@4.0.1
  | `-- vinyl@0.4.6
  |   `-- clone@0.2.0
  `-- xml2js@0.4.4
    +-- sax@0.6.1
    `-- xmlbuilder@2.2.1


C:\Users\premkumar.agrawal>ionic -v
1.7.14

**Comment by PremkumarAgrawal** [comment]
Download Node.js, git and Apache ant

->Install Node.js, Git
->Set Path variables for
	Nodejs\bin
	Git\bin
	apache ant\bin
	AndroidSDK\platform tools
	AndroidSDK\tools
-> install updated npm
	>npm install npm@latest
-> install cordova
	>npm install -g cordova
->install ionic
	>npm install -g ionic

**Comment by zhipengyue** [comment]
check your project folder'name and the name in the package.json.make sure ,the name is not like 'gulp', 'webpack' and ather npm package name;
