### ISSUE TITLE
NPM error for gulp and elixir

### ISSUE THREAD

**Issue by yespbs** [npm/npm#9604]
I am having issues installing gulp and laravel-elixir, I switched my global install path after several failed attempts but still no luck ( was following this https://docs.npmjs.com/getting-started/fixing-npm-permissions option 2)

Global install works but local install fail, from a package.json or cli

npm install gulp --save-dev
npm install laravel-elixir

previously it was ok with Meverick, I also upgraded node and npm, using Yosmite now

node v4.0.0
npm  2.14.2 

Any help or clue appreciated

npm-debug.log

https://gist.githubusercontent.com/yespbs/40ab18286a3ce904ba7c/raw/4161bbcfa18b470a1c491a24f90f558ebf17beb2/npm-debug.log

**Comment by rajnetgen** [comment]
#9601 this is an active issue

**Comment by seldo** [comment]
We apologize. A canary server rolled out earlier had a bug and we have rolled it back. Follow here for updates: https://npmjs.statuspage.io/incidents/pyw00fmpjzrh
