### ISSUE TITLE
empty tar balls from fastly

### ISSUE THREAD

**Issue by JoshRagem** [npm/npm#9606]
getting shasum failures same as https://github.com/npm/npm/issues/6451

we tried three locations and only the one that hits a.sni.fastly.net at 23.235.47.162 get empties.

There are at least two packages affected:

* server 4.2.0
* pgpass 0.0.3

**Comment by KenanY** [comment]
Sounds like https://github.com/npm/npm/issues/9601.

**Comment by CoreyDotCom** [comment]
Yep, man down! Someone update npm status website please. :)

**Comment by CoreyDotCom** [comment]
Also affects 199.27.79.162.

**Comment by seldo** [comment]
We apologize. A canary server rolled out earlier had a bug and we have rolled it back. Follow here for updated: https://npmjs.statuspage.io/incidents/pyw00fmpjzrh

**Comment by JoshRagem** [comment]
this is still happening:

```
npm ERR! Error: shasum check failed for /tmp/npm-1-dLRwTqWD/registry.npmjs.org/semver/-/semver-4.2.0.tgz
npm ERR! Expected: a571fd4adbe974fe32bd9cb4c5e249606f498423
npm ERR! Actual:   da39a3ee5e6b4b0d3255bfef95601890afd80709
npm ERR! From:     https://registry.npmjs.org/semver/-/semver-4.2.0.tgz
```

**Comment by JoshRagem** [comment]
fixed now. thanks!
