### ISSUE TITLE
I can't install flux from npm?

### ISSUE THREAD

**Issue by sqxieshuai** [npm/npm#9607]
i want to install https://www.npmjs.com/package/flux, but i got something wrong.

---

$ npm install flux
npm ERR! Darwin 14.4.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "install" "flux"
npm ERR! node v2.4.0
npm ERR! npm  v2.13.0

npm ERR! shasum check failed for /var/folders/d2/ndw3lnhx7plgvmyn34xlwb_w0000gn/T/npm-19984-208480a6/registry.npmjs.org/fbjs/-/fbjs-0.1.0-alpha.7.tgz
npm ERR! Expected: ad4308b8f232fb3c73603349ea725d1e9c39323c
npm ERR! Actual:   da39a3ee5e6b4b0d3255bfef95601890afd80709
npm ERR! From:     https://registry.npmjs.org/fbjs/-/fbjs-0.1.0-alpha.7.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

----

the npm debug log is:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/iojs', '/usr/local/bin/npm', 'install', 'flux' ]
2 info using npm@2.13.0
3 info using node@v2.4.0
4 verbose install initial load of /Users/xrush/personal/eelknow/eelknow-fe/package.json
5 warn package.json eelknow-fe@0.0.1 No repository field.
6 warn package.json eelknow-fe@0.0.1 No README data
7 warn package.json eelknow-fe@0.0.1 No license field.
8 verbose installManyTop reading scoped package data from /Users/xrush/personal/eelknow/eelknow-fe/node_modules/babel-core/package.json
9 verbose installManyTop reading scoped package data from /Users/xrush/personal/eelknow/eelknow-fe/node_modules/babel-loader/package.json
10 verbose installManyTop reading scoped package data from /Users/xrush/personal/eelknow/eelknow-fe/node_modules/css-loader/package.json
11 verbose installManyTop reading scoped package data from /Users/xrush/personal/eelknow/eelknow-fe/node_modules/exports-loader/package.json
12 verbose installManyTop reading scoped package data from /Users/xrush/personal/eelknow/eelknow-fe/node_modules/expose-loader/package.json
13 verbose installManyTop reading scoped package data from /Users/xrush/personal/eelknow/eelknow-fe/node_modules/express/package.json
14 verbose installManyTop reading scoped package data from /Users/xrush/personal/eelknow/eelknow-fe/node_modules/extract-text-webpack-plugin/package.json
15 verbose installManyTop reading scoped package data from /Users/xrush/personal/eelknow/eelknow-fe/node_modules/file-loader/package.json
16 verbose installManyTop reading scoped package data from /Users/xrush/personal/eelknow/eelknow-fe/node_modules/html-webpack-plugin/package.json
17 verbose installManyTop reading scoped package data from /Users/xrush/personal/eelknow/eelknow-fe/node_modules/image-webpack-loader/package.json
18 verbose installManyTop reading scoped package data from /Users/xrush/personal/eelknow/eelknow-fe/node_modules/imagemin/package.json
19 verbose installManyTop reading scoped package data from /Users/xrush/personal/eelknow/eelknow-fe/node_modules/imports-loader/package.json
20 verbose installManyTop reading scoped package data from /Users/xrush/personal/eelknow/eelknow-fe/node_modules/less/package.json
21 verbose installManyTop reading scoped package data from /Users/xrush/personal/eelknow/eelknow-fe/node_modules/less-loader/package.json
22 verbose installManyTop reading scoped package data from /Users/xrush/personal/eelknow/eelknow-fe/node_modules/node-jsx/package.json
23 verbose installManyTop reading scoped package data from /Users/xrush/personal/eelknow/eelknow-fe/node_modules/node-less/package.json
24 verbose installManyTop reading scoped package data from /Users/xrush/personal/eelknow/eelknow-fe/node_modules/purecss/package.json
25 verbose installManyTop reading scoped package data from /Users/xrush/personal/eelknow/eelknow-fe/node_modules/react/package.json
26 verbose installManyTop reading scoped package data from /Users/xrush/personal/eelknow/eelknow-fe/node_modules/react-hot-loader/package.json
27 verbose installManyTop reading scoped package data from /Users/xrush/personal/eelknow/eelknow-fe/node_modules/react-router/package.json
28 verbose installManyTop reading scoped package data from /Users/xrush/personal/eelknow/eelknow-fe/node_modules/react-router-proxy-loader/package.json
29 verbose installManyTop reading scoped package data from /Users/xrush/personal/eelknow/eelknow-fe/node_modules/style-loader/package.json
30 verbose installManyTop reading scoped package data from /Users/xrush/personal/eelknow/eelknow-fe/node_modules/superagent/package.json
31 verbose installManyTop reading scoped package data from /Users/xrush/personal/eelknow/eelknow-fe/node_modules/url-loader/package.json
32 verbose installManyTop reading scoped package data from /Users/xrush/personal/eelknow/eelknow-fe/node_modules/webpack/package.json
33 verbose installManyTop reading scoped package data from /Users/xrush/personal/eelknow/eelknow-fe/node_modules/webpack-dev-server/package.json
34 info package.json image-webpack-loader@1.6.1 No license field.
35 info package.json less-loader@2.2.0 No license field.
36 info package.json node-jsx@0.13.3 license should be a valid SPDX license expression
37 info package.json purecss@0.6.0 license should be a valid SPDX license expression
38 info package.json expose-loader@0.7.0 No license field.
39 info package.json exports-loader@0.6.2 No license field.
40 verbose readDependencies loading dependencies from /Users/xrush/personal/eelknow/eelknow-fe/package.json
41 silly cache add args [ 'flux', null ]
42 verbose cache add spec flux
43 silly cache add parsed spec { raw: 'flux',
43 silly cache add   scope: null,
43 silly cache add   name: 'flux',
43 silly cache add   rawSpec: '',
43 silly cache add   spec: '*',
43 silly cache add   type: 'range' }
44 silly addNamed flux@*
45 verbose addNamed "*" is a valid semver range for flux
46 silly addNameRange { name: 'flux', range: '*', hasData: false }
47 silly mapToRegistry name flux
48 silly mapToRegistry using default registry
49 silly mapToRegistry registry https://registry.npmjs.org/
50 silly mapToRegistry uri https://registry.npmjs.org/flux
51 verbose addNameRange registry:https://registry.npmjs.org/flux not in flight; fetching
52 verbose request uri https://registry.npmjs.org/flux
53 verbose request no auth needed
54 info attempt registry request try #1 at 22:20:31
55 verbose request id 577cfeca5b333a5e
56 verbose etag "5Z32LTIJKL3G6LPQT00AXK8GP"
57 http request GET https://registry.npmjs.org/flux
58 http 304 https://registry.npmjs.org/flux
59 silly get cb [ 304,
59 silly get   { date: 'Wed, 16 Sep 2015 14:19:48 GMT',
59 silly get     via: '1.1 varnish',
59 silly get     'cache-control': 'max-age=60',
59 silly get     etag: '"5Z32LTIJKL3G6LPQT00AXK8GP"',
59 silly get     age: '0',
59 silly get     connection: 'keep-alive',
59 silly get     'x-served-by': 'cache-hkg6820-HKG',
59 silly get     'x-cache': 'HIT',
59 silly get     'x-cache-hits': '1',
59 silly get     'x-timer': 'S1442413188.703250,VS0,VE233',
59 silly get     vary: 'Accept' } ]
60 verbose etag https://registry.npmjs.org/flux from cache
61 verbose get saving flux to /Users/xrush/.npm/registry.npmjs.org/flux/.cache.json
62 silly addNameRange number 2 { name: 'flux', range: '*', hasData: true }
63 silly addNameRange versions [ 'flux',
63 silly addNameRange   [ '1.0.0',
63 silly addNameRange     '1.0.1',
63 silly addNameRange     '1.0.2',
63 silly addNameRange     '2.0.0',
63 silly addNameRange     '2.0.1',
63 silly addNameRange     '2.0.3',
63 silly addNameRange     '2.1.0',
63 silly addNameRange     '2.1.1' ] ]
64 silly addNamed flux@2.1.1
65 verbose addNamed "2.1.1" is a plain semver version for flux
66 silly cache afterAdd flux@2.1.1
67 verbose afterAdd /Users/xrush/.npm/flux/2.1.1/package/package.json not in flight; writing
68 verbose afterAdd /Users/xrush/.npm/flux/2.1.1/package/package.json written
69 silly install resolved [ { name: 'flux',
69 silly install resolved     version: '2.1.1',
69 silly install resolved     description: 'An application architecture based on a unidirectional data flow',
69 silly install resolved     keywords: [ 'flux', 'react', 'facebook', 'dispatcher' ],
69 silly install resolved     homepage: 'http://facebook.github.io/flux/',
69 silly install resolved     bugs: { url: 'https://github.com/facebook/flux/issues' },
69 silly install resolved     files:
69 silly install resolved      [ 'LICENSE',
69 silly install resolved        'PATENTS',
69 silly install resolved        'README.md',
69 silly install resolved        'flow',
69 silly install resolved        'index.js',
69 silly install resolved        'lib',
69 silly install resolved        'utils.js',
69 silly install resolved        'dist' ],
69 silly install resolved     main: 'index.js',
69 silly install resolved     scripts:
69 silly install resolved      { build: 'gulp build',
69 silly install resolved        prepublish: 'gulp publish',
69 silly install resolved        test: 'NODE_ENV=test jest' },
69 silly install resolved     repository: { type: 'git', url: 'git+https://github.com/facebook/flux.git' },
69 silly install resolved     author: { name: 'Facebook' },
69 silly install resolved     contributors: [ [Object], [Object], [Object], [Object] ],
69 silly install resolved     license: 'BSD-3-Clause',
69 silly install resolved     devDependencies:
69 silly install resolved      { babel: '^5.4.7',
69 silly install resolved        'babel-core': '^5.8.22',
69 silly install resolved        'babel-loader': '^5.3.2',
69 silly install resolved        del: '^1.2.0',
69 silly install resolved        gulp: '^3.9.0',
69 silly install resolved        'gulp-babel': '^5.1.0',
69 silly install resolved        'gulp-flatten': '^0.1.1',
69 silly install resolved        'gulp-util': '^3.0.6',
69 silly install resolved        'jest-cli': '^0.4.18',
69 silly install resolved        'object-assign': '^3.0.0',
69 silly install resolved        'run-sequence': '^1.1.0',
69 silly install resolved        'vinyl-source-stream': '^1.0.0',
69 silly install resolved        webpack: '^1.11.0',
69 silly install resolved        'webpack-stream': '^2.1.0' },
69 silly install resolved     dependencies:
69 silly install resolved      { fbemitter: '^2.0.0',
69 silly install resolved        fbjs: '0.1.0-alpha.7',
69 silly install resolved        immutable: '^3.7.4' },
69 silly install resolved     jest:
69 silly install resolved      { modulePathIgnorePatterns: [Object],
69 silly install resolved        persistModuleRegistryBetweenSpecs: true,
69 silly install resolved        preprocessorIgnorePatterns: [Object],
69 silly install resolved        rootDir: '',
69 silly install resolved        scriptPreprocessor: 'scripts/jest/preprocessor.js',
69 silly install resolved        setupEnvScriptFile: 'scripts/jest/environment.js',
69 silly install resolved        testPathDirs: [Object],
69 silly install resolved        unmockedModulePathPatterns: [Object] },
69 silly install resolved     gitHead: 'ad204fdf5d2a852ef1d7fec323c4d93aad4ce247',
69 silly install resolved     _id: 'flux@2.1.1',
69 silly install resolved     _shasum: '2c6ac652d4337488968489c6586f3aff26a38ea4',
69 silly install resolved     _from: 'flux@*',
69 silly install resolved     _npmVersion: '2.12.1',
69 silly install resolved     _nodeVersion: '0.12.7',
69 silly install resolved     _npmUser: { name: 'kyldvs', email: 'kyldvs@gmail.com' },
69 silly install resolved     dist:
69 silly install resolved      { shasum: '2c6ac652d4337488968489c6586f3aff26a38ea4',
69 silly install resolved        tarball: 'http://registry.npmjs.org/flux/-/flux-2.1.1.tgz' },
69 silly install resolved     maintainers: [ [Object], [Object], [Object] ],
69 silly install resolved     directories: {},
69 silly install resolved     _resolved: 'https://registry.npmjs.org/flux/-/flux-2.1.1.tgz',
69 silly install resolved     readme: 'ERROR: No README data found!' } ]
70 info install flux@2.1.1 into /Users/xrush/personal/eelknow/eelknow-fe
71 info installOne flux@2.1.1
72 verbose installOne of flux to /Users/xrush/personal/eelknow/eelknow-fe not in flight; installing
73 verbose lock using /Users/xrush/.npm/_locks/flux-5c1f9c195c5a272f.lock for /Users/xrush/personal/eelknow/eelknow-fe/node_modules/flux
74 silly install write writing flux 2.1.1 to /Users/xrush/personal/eelknow/eelknow-fe/node_modules/flux
75 verbose unbuild node_modules/flux
76 silly gentlyRm /Users/xrush/personal/eelknow/eelknow-fe/node_modules/flux is being purged from base /Users/xrush/personal/eelknow/eelknow-fe
77 verbose gentlyRm don't care about contents; nuking /Users/xrush/personal/eelknow/eelknow-fe/node_modules/flux
78 verbose tar unpack /Users/xrush/.npm/flux/2.1.1/package.tgz
79 verbose tar unpacking to /Users/xrush/personal/eelknow/eelknow-fe/node_modules/flux
80 silly gentlyRm /Users/xrush/personal/eelknow/eelknow-fe/node_modules/flux is being purged
81 verbose gentlyRm don't care about contents; nuking /Users/xrush/personal/eelknow/eelknow-fe/node_modules/flux
82 silly gunzTarPerm modes [ '755', '644' ]
83 silly gunzTarPerm extractEntry package.json
84 silly gunzTarPerm extractEntry README.md
85 silly gunzTarPerm extractEntry LICENSE
86 silly gunzTarPerm extractEntry index.js
87 silly gunzTarPerm extractEntry utils.js
88 silly gunzTarPerm extractEntry dist/Flux.js
89 silly gunzTarPerm extractEntry dist/Flux.min.js
90 silly gunzTarPerm extractEntry flow/include/Dispatcher.js
91 silly gunzTarPerm extractEntry flow/include/FluxContainer.js
92 silly gunzTarPerm extractEntry flow/include/FluxMapStore.js
93 silly gunzTarPerm extractEntry flow/include/FluxMixinLegacy.js
94 silly gunzTarPerm extractEntry flow/include/FluxReduceStore.js
95 silly gunzTarPerm extractEntry flow/include/FluxStore.js
96 silly gunzTarPerm extractEntry flow/include/FluxStoreGroup.js
97 silly gunzTarPerm extractEntry flow/include/abstractMethod.js
98 silly gunzTarPerm extractEntry flow/lib/dev.js
99 silly gunzTarPerm extractEntry lib/Dispatcher.js
100 silly gunzTarPerm extractEntry lib/FluxContainer.js
101 silly gunzTarPerm extractEntry lib/FluxMapStore.js
102 silly gunzTarPerm extractEntry lib/FluxMixinLegacy.js
103 silly gunzTarPerm extractEntry lib/FluxReduceStore.js
104 silly gunzTarPerm extractEntry lib/FluxStore.js
105 silly gunzTarPerm extractEntry lib/FluxStoreGroup.js
106 silly gunzTarPerm extractEntry lib/abstractMethod.js
107 silly gunzTarPerm extractEntry PATENTS
108 verbose write writing to /Users/xrush/personal/eelknow/eelknow-fe/node_modules/flux/package.json
109 info preinstall flux@2.1.1
110 verbose readDependencies loading dependencies from /Users/xrush/personal/eelknow/eelknow-fe/node_modules/flux/package.json
111 silly prepareForInstallMany adding fbemitter@^2.0.0 from flux dependencies
112 silly prepareForInstallMany adding fbjs@0.1.0-alpha.7 from flux dependencies
113 silly prepareForInstallMany adding immutable@^3.7.4 from flux dependencies
114 verbose readDependencies loading dependencies from /Users/xrush/personal/eelknow/eelknow-fe/node_modules/flux/package.json
115 silly cache add args [ 'immutable@^3.7.4', null ]
116 verbose cache add spec immutable@^3.7.4
117 silly cache add parsed spec { raw: 'immutable@^3.7.4',
117 silly cache add   scope: null,
117 silly cache add   name: 'immutable',
117 silly cache add   rawSpec: '^3.7.4',
117 silly cache add   spec: '>=3.7.4 <4.0.0',
117 silly cache add   type: 'range' }
118 silly addNamed immutable@>=3.7.4 <4.0.0
119 verbose addNamed ">=3.7.4 <4.0.0" is a valid semver range for immutable
120 silly addNameRange { name: 'immutable', range: '>=3.7.4 <4.0.0', hasData: false }
121 silly mapToRegistry name immutable
122 silly mapToRegistry using default registry
123 silly mapToRegistry registry https://registry.npmjs.org/
124 silly mapToRegistry uri https://registry.npmjs.org/immutable
125 verbose addNameRange registry:https://registry.npmjs.org/immutable not in flight; fetching
126 silly cache add args [ 'fbemitter@^2.0.0', null ]
127 verbose cache add spec fbemitter@^2.0.0
128 silly cache add parsed spec { raw: 'fbemitter@^2.0.0',
128 silly cache add   scope: null,
128 silly cache add   name: 'fbemitter',
128 silly cache add   rawSpec: '^2.0.0',
128 silly cache add   spec: '>=2.0.0 <3.0.0',
128 silly cache add   type: 'range' }
129 silly addNamed fbemitter@>=2.0.0 <3.0.0
130 verbose addNamed ">=2.0.0 <3.0.0" is a valid semver range for fbemitter
131 silly addNameRange { name: 'fbemitter', range: '>=2.0.0 <3.0.0', hasData: false }
132 silly mapToRegistry name fbemitter
133 silly mapToRegistry using default registry
134 silly mapToRegistry registry https://registry.npmjs.org/
135 silly mapToRegistry uri https://registry.npmjs.org/fbemitter
136 verbose addNameRange registry:https://registry.npmjs.org/fbemitter not in flight; fetching
137 silly cache add args [ 'fbjs@0.1.0-alpha.7', null ]
138 verbose cache add spec fbjs@0.1.0-alpha.7
139 silly cache add parsed spec { raw: 'fbjs@0.1.0-alpha.7',
139 silly cache add   scope: null,
139 silly cache add   name: 'fbjs',
139 silly cache add   rawSpec: '0.1.0-alpha.7',
139 silly cache add   spec: '0.1.0-alpha.7',
139 silly cache add   type: 'version' }
140 silly addNamed fbjs@0.1.0-alpha.7
141 verbose addNamed "0.1.0-alpha.7" is a plain semver version for fbjs
142 silly mapToRegistry name fbjs
143 silly mapToRegistry using default registry
144 silly mapToRegistry registry https://registry.npmjs.org/
145 silly mapToRegistry uri https://registry.npmjs.org/fbjs
146 verbose addNameVersion registry:https://registry.npmjs.org/fbjs not in flight; fetching
147 verbose request uri https://registry.npmjs.org/fbemitter
148 verbose request no auth needed
149 info attempt registry request try #1 at 22:20:33
150 verbose etag "BCAQEMDRO0KEXXQO9SZ4ASFB6"
151 http request GET https://registry.npmjs.org/fbemitter
152 verbose request uri https://registry.npmjs.org/fbjs
153 verbose request no auth needed
154 info attempt registry request try #1 at 22:20:33
155 verbose etag "4QEV3EE79UQ5J97U7RI6YQ48D"
156 http request GET https://registry.npmjs.org/fbjs
157 verbose request uri https://registry.npmjs.org/immutable
158 verbose request no auth needed
159 info attempt registry request try #1 at 22:20:33
160 verbose etag "9YWRWIKHDFUMHE7GQYUITHK6A"
161 http request GET https://registry.npmjs.org/immutable
162 http 304 https://registry.npmjs.org/immutable
163 silly get cb [ 304,
163 silly get   { date: 'Wed, 16 Sep 2015 14:19:50 GMT',
163 silly get     via: '1.1 varnish',
163 silly get     'cache-control': 'max-age=60',
163 silly get     etag: '"9YWRWIKHDFUMHE7GQYUITHK6A"',
163 silly get     age: '0',
163 silly get     connection: 'keep-alive',
163 silly get     'x-served-by': 'cache-hkg6821-HKG',
163 silly get     'x-cache': 'HIT',
163 silly get     'x-cache-hits': '1',
163 silly get     'x-timer': 'S1442413190.165353,VS0,VE750',
163 silly get     vary: 'Accept' } ]
164 verbose etag https://registry.npmjs.org/immutable from cache
165 verbose get saving immutable to /Users/xrush/.npm/registry.npmjs.org/immutable/.cache.json
166 http 304 https://registry.npmjs.org/fbemitter
167 silly get cb [ 304,
167 silly get   { date: 'Wed, 16 Sep 2015 14:19:50 GMT',
167 silly get     via: '1.1 varnish',
167 silly get     'cache-control': 'max-age=60',
167 silly get     etag: '"BCAQEMDRO0KEXXQO9SZ4ASFB6"',
167 silly get     age: '0',
167 silly get     connection: 'keep-alive',
167 silly get     'x-served-by': 'cache-hkg6823-HKG',
167 silly get     'x-cache': 'HIT',
167 silly get     'x-cache-hits': '1',
167 silly get     'x-timer': 'S1442413190.148631,VS0,VE774',
167 silly get     vary: 'Accept' } ]
168 verbose etag https://registry.npmjs.org/fbemitter from cache
169 verbose get saving fbemitter to /Users/xrush/.npm/registry.npmjs.org/fbemitter/.cache.json
170 silly addNameRange number 2 { name: 'fbemitter', range: '>=2.0.0 <3.0.0', hasData: true }
171 silly addNameRange versions [ 'fbemitter', [ '2.0.0' ] ]
172 silly addNamed fbemitter@2.0.0
173 verbose addNamed "2.0.0" is a plain semver version for fbemitter
174 silly addNameRange number 2 { name: 'immutable', range: '>=3.7.4 <4.0.0', hasData: true }
175 silly addNameRange versions [ 'immutable',
175 silly addNameRange   [ '0.8.0-SNAPSHOT',
175 silly addNameRange     '0.8.0',
175 silly addNameRange     '0.9.0',
175 silly addNameRange     '0.9.1',
175 silly addNameRange     '0.9.2',
175 silly addNameRange     '1.0.0',
175 silly addNameRange     '1.1.0',
175 silly addNameRange     '1.2.0',
175 silly addNameRange     '1.3.0',
175 silly addNameRange     '1.4.0',
175 silly addNameRange     '1.5.0',
175 silly addNameRange     '1.4.1',
175 silly addNameRange     '2.0.0',
175 silly addNameRange     '2.0.1',
175 silly addNameRange     '2.0.2',
175 silly addNameRange     '2.0.3',
175 silly addNameRange     '2.0.4',
175 silly addNameRange     '2.0.5',
175 silly addNameRange     '2.0.6',
175 silly addNameRange     '2.0.7',
175 silly addNameRange     '2.0.8',
175 silly addNameRange     '2.0.9',
175 silly addNameRange     '2.0.10',
175 silly addNameRange     '2.0.11',
175 silly addNameRange     '2.0.12',
175 silly addNameRange     '2.0.13',
175 silly addNameRange     '2.0.14',
175 silly addNameRange     '2.0.15',
175 silly addNameRange     '2.0.16',
175 silly addNameRange     '2.0.17',
175 silly addNameRange     '2.1.0',
175 silly addNameRange     '2.2.1',
175 silly addNameRange     '2.2.2',
175 silly addNameRange     '2.2.3',
175 silly addNameRange     '2.3.0',
175 silly addNameRange     '2.3.1',
175 silly addNameRange     '2.3.2',
175 silly addNameRange     '2.5.0',
175 silly addNameRange     '2.5.1',
175 silly addNameRange     '2.6.0',
175 silly addNameRange     '2.6.1',
175 silly addNameRange     '2.6.2',
175 silly addNameRange     '3.0.0',
175 silly addNameRange     '3.0.1',
175 silly addNameRange     '3.0.2',
175 silly addNameRange     '3.0.3',
175 silly addNameRange     '3.1.0',
175 silly addNameRange     '3.2.0',
175 silly addNameRange     '3.2.1',
175 silly addNameRange     '3.3.0',
175 silly addNameRange     '3.4.0',
175 silly addNameRange     '3.4.1',
175 silly addNameRange     '3.5.0',
175 silly addNameRange     '3.6.0',
175 silly addNameRange     '3.6.1',
175 silly addNameRange     '3.6.2',
175 silly addNameRange     '3.6.3',
175 silly addNameRange     '3.6.4',
175 silly addNameRange     '3.7.0',
175 silly addNameRange     '3.7.1',
175 silly addNameRange     '3.7.2',
175 silly addNameRange     '3.7.3',
175 silly addNameRange     '3.7.4',
175 silly addNameRange     '3.7.5' ] ]
176 silly addNamed immutable@3.7.5
177 verbose addNamed "3.7.5" is a plain semver version for immutable
178 silly cache afterAdd fbemitter@2.0.0
179 verbose afterAdd /Users/xrush/.npm/fbemitter/2.0.0/package/package.json not in flight; writing
180 silly cache afterAdd immutable@3.7.5
181 verbose afterAdd /Users/xrush/.npm/immutable/3.7.5/package/package.json not in flight; writing
182 http 304 https://registry.npmjs.org/fbjs
183 silly get cb [ 304,
183 silly get   { date: 'Wed, 16 Sep 2015 14:19:50 GMT',
183 silly get     via: '1.1 varnish',
183 silly get     'cache-control': 'max-age=60',
183 silly get     etag: '"4QEV3EE79UQ5J97U7RI6YQ48D"',
183 silly get     age: '0',
183 silly get     connection: 'keep-alive',
183 silly get     'x-served-by': 'cache-hkg6822-HKG',
183 silly get     'x-cache': 'HIT',
183 silly get     'x-cache-hits': '1',
183 silly get     'x-timer': 'S1442413190.170145,VS0,VE796',
183 silly get     vary: 'Accept' } ]
184 verbose etag https://registry.npmjs.org/fbjs from cache
185 verbose get saving fbjs to /Users/xrush/.npm/registry.npmjs.org/fbjs/.cache.json
186 verbose afterAdd /Users/xrush/.npm/fbemitter/2.0.0/package/package.json written
187 verbose afterAdd /Users/xrush/.npm/immutable/3.7.5/package/package.json written
188 silly mapToRegistry name fbjs
189 silly mapToRegistry using default registry
190 silly mapToRegistry registry https://registry.npmjs.org/
191 silly mapToRegistry uri https://registry.npmjs.org/fbjs
192 verbose addRemoteTarball https://registry.npmjs.org/fbjs/-/fbjs-0.1.0-alpha.7.tgz not in flight; adding
193 verbose addRemoteTarball [ 'https://registry.npmjs.org/fbjs/-/fbjs-0.1.0-alpha.7.tgz',
193 verbose addRemoteTarball   'ad4308b8f232fb3c73603349ea725d1e9c39323c' ]
194 info retry fetch attempt 1 at 22:20:35
195 info attempt registry request try #1 at 22:20:35
196 http fetch GET https://registry.npmjs.org/fbjs/-/fbjs-0.1.0-alpha.7.tgz
197 http fetch 200 https://registry.npmjs.org/fbjs/-/fbjs-0.1.0-alpha.7.tgz
198 silly fetchAndShaCheck shasum ad4308b8f232fb3c73603349ea725d1e9c39323c
199 verbose about to build /Users/xrush/personal/eelknow/eelknow-fe/node_modules/flux
200 verbose unlock done using /Users/xrush/.npm/_locks/flux-5c1f9c195c5a272f.lock for /Users/xrush/personal/eelknow/eelknow-fe/node_modules/flux
201 verbose stack Error: shasum check failed for /var/folders/d2/ndw3lnhx7plgvmyn34xlwb_w0000gn/T/npm-19984-208480a6/registry.npmjs.org/fbjs/-/fbjs-0.1.0-alpha.7.tgz
201 verbose stack Expected: ad4308b8f232fb3c73603349ea725d1e9c39323c
201 verbose stack Actual:   da39a3ee5e6b4b0d3255bfef95601890afd80709
201 verbose stack From:     https://registry.npmjs.org/fbjs/-/fbjs-0.1.0-alpha.7.tgz
201 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/sha/index.js:38:8
201 verbose stack     at ReadStream.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/sha/index.js:85:7)
201 verbose stack     at emitNone (events.js:72:20)
201 verbose stack     at ReadStream.emit (events.js:166:7)
201 verbose stack     at endReadableNT (_stream_readable.js:889:12)
201 verbose stack     at doNTCallback2 (node.js:430:9)
201 verbose stack     at process._tickCallback (node.js:344:17)
202 verbose cwd /Users/xrush/personal/eelknow/eelknow-fe
203 error Darwin 14.4.0
204 error argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "install" "flux"
205 error node v2.4.0
206 error npm  v2.13.0
207 error shasum check failed for /var/folders/d2/ndw3lnhx7plgvmyn34xlwb_w0000gn/T/npm-19984-208480a6/registry.npmjs.org/fbjs/-/fbjs-0.1.0-alpha.7.tgz
207 error Expected: ad4308b8f232fb3c73603349ea725d1e9c39323c
207 error Actual:   da39a3ee5e6b4b0d3255bfef95601890afd80709
207 error From:     https://registry.npmjs.org/fbjs/-/fbjs-0.1.0-alpha.7.tgz
208 error If you need help, you may report this error at:
208 error     <https://github.com/npm/npm/issues>
209 verbose exit [ 1, true ]
210 verbose unbuild node_modules/flux
211 info preuninstall flux@2.1.1
212 info uninstall flux@2.1.1
213 verbose unbuild rmStuff flux@2.1.1 from /Users/xrush/personal/eelknow/eelknow-fe/node_modules
214 info postuninstall flux@2.1.1
215 silly gentlyRm /Users/xrush/personal/eelknow/eelknow-fe/node_modules/flux is being purged from base /Users/xrush/personal/eelknow/eelknow-fe
216 verbose gentlyRm don't care about contents; nuking /Users/xrush/personal/eelknow/eelknow-fe/node_modules/flux
217 silly vacuum-fs purging /Users/xrush/personal/eelknow/eelknow-fe/node_modules/flux
218 silly vacuum-fs quitting because other entries in /Users/xrush/personal/eelknow/eelknow-fe/node_modules

**Comment by KenanY** [comment]
@sqxieshuai Have you tried running `npm cache clean`?

**Comment by CoreyDotCom** [comment]
Believe this is also #9601 - I'm getting same errors and the file that fails the shasum is 0-length

**Comment by KenanY** [comment]
@CoreyDotCom I agree :)

**Comment by seldo** [comment]
We apologize. A canary server rolled out earlier had a bug and we have rolled it back. Follow here for updated: https://npmjs.statuspage.io/incidents/pyw00fmpjzrh
