### ISSUE TITLE
Can not execute the command:$npm install hexo-cli -g

### ISSUE THREAD

**Issue by xiaoliuzi** [npm/npm#9608]
$ npm install hexo-cli -g
    npm WARN optional dep failed, continuing fsevents@0.3.8
    npm ERR! Windows_NT 6.3.9600
    npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program      Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "hexo-cli" "-g"
    npm ERR! node v4.0.0
    npm ERR! npm  v2.14.2

    npm ERR! shasum check failed for C:\Users\John\AppData\Local\Temp\npm-4504-            7766cd51\registry.npmjs.org\core-util-is\-\core-util-is-1.0.1.tgz
    npm ERR! Expected: 6b07085aef9a3ccac6ee53bf9d3df0c1521a5538
    npm ERR! Actual:   da39a3ee5e6b4b0d3255bfef95601890afd80709
    npm ERR! From:     https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.1.tgz
    npm ERR!
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <https://github.com/npm/npm/issues>

    npm ERR! Please include the following file with any support request:
    npm ERR!     C:\Users\John\npm-debug.log

I have the same problems on Windows.  I have try this method:

https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows

but, it doesn't work.  

I can ping registry.npmjs.org successfully.

**Comment by KenanY** [comment]
@xiaoliuzi Have you tried `npm cache clean`?

**Comment by KenanY** [comment]
@xiaoliuzi Actually, `da39a3ee5e6b4b0d3255bfef95601890afd80709` is the shasum of a 0-length file. I believe you are running into https://github.com/npm/npm/issues/9601.

**Comment by xiaoliuzi** [comment]
@KenanY I have tried npm cache clean, and reinstalled node.js, but still failed.

    $ npm cache clean

    John@tsingpeng MINGW64 ~
    $ npm install -g hexo
    npm ERR! Windows_NT 6.3.9600
    npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "hexo"
    npm ERR! node v4.0.0
    npm ERR! npm  v2.14.2

    npm ERR! shasum check failed for C:\Users\John\AppData\Local\Temp\npm-11424-35ff4e09\registry.npmjs.org\swig\-\swig-1.4.2.tgz
    npm ERR! Expected: 4085ca0453369104b5d483e2841b39b7ae1aaba5
    npm ERR! Actual:   da39a3ee5e6b4b0d3255bfef95601890afd80709
    npm ERR! From:     https://registry.npmjs.org/swig/-/swig-1.4.2.tgz
    npm ERR!
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <https://github.com/npm/npm/issues>

    npm ERR! Please include the following file with any support request:
    npm ERR!     C:\Users\John\npm-debug.log


Please help me, thank you.

**Comment by KenanY** [comment]
@xiaoliuzi Like I said, this is probably a duplicate a bunch of other tickets right now since the registry is serving 0-length tarballs at the moment.

**Comment by xiaoliuzi** [comment]
@KenanY But I have met this problem for 6 hours.

**Comment by seldo** [comment]
We apologize. A canary server rolled out earlier had a bug and we have rolled it back. Follow here for updated: https://npmjs.statuspage.io/incidents/pyw00fmpjzrh

**Comment by xiaoliuzi** [comment]
@seldo That is all right. I really do not mean to blame. My English is not very good, I just can not understand this reply:
>Like I said, this is probably a duplicate a bunch of other tickets right now since the registry is serving 0-length tarballs at the moment.

**Comment by KenanY** [comment]
@xiaoliuzi That's my fault then, sorry (I authored the reply). I would not worry about it anymore.

**Comment by xiaoliuzi** [comment]
I still can not solve this issue. So I should wait for some time, then to check it ?

I download [node.js](https://nodejs.org/en/), which have npm in it.

If you can please check node.js by the way. Maybe it should be update too.

**Comment by xiaoliuzi** [comment]
@KenanY @seldo 
I have fix it to reinstall node.js with the version Node.js v0.12.7. 

Thank you very much.
