### ISSUE TITLE
error installing cordova and ionic on windows 8.1

### ISSUE THREAD

**Issue by rajnetgen** [npm/npm#9609]
Installed fresh copy of nodejs.
getting same error again and again.
have tried cleaning cache and then install. no solution so far

C:\Windows\System32>
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Windows\system32>npm -v
2.14.2

C:\Windows\system32>node -v
v4.0.0

C:\Windows\system32>npm cache clean
C:\Windows\system32>npm install cordova
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {
"node":"4.0.0","npm":"2.14.2"})
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "cordova"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2

npm ERR! shasum check failed for C:\Users\Design\AppData\Local\Temp\npm-4420-b0a
0dc33\registry.npmjs.org\ini\-\ini-1.3.4.tgz
npm ERR! Expected: 0537cb79daf59b59a1a517dff706c86ec039162e
npm ERR! Actual:   da39a3ee5e6b4b0d3255bfef95601890afd80709
npm ERR! From:     https://registry.npmjs.org/ini/-/ini-1.3.4.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\system32\npm-debug.log

C:\Windows\system32>

**Comment by KenanY** [comment]
@rajnetgen `da39a3ee5e6b4b0d3255bfef95601890afd80709` is the shasum of a 0-length file. If `npm cache clean` does not help, this might be a registry issue (https://github.com/npm/npm/issues/9601).

**Comment by seldo** [comment]
We apologize. A canary server rolled out earlier had a bug and we have rolled it back. Follow here for updated: https://npmjs.statuspage.io/incidents/pyw00fmpjzrh
