### ISSUE TITLE
cordova and ionic problem

### ISSUE THREAD

**Issue by usmannaveed** [npm/npm#9613]
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {
"node":"4.0.0","npm":"2.14.2"})
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x8
6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2

npm ERR! shasum check failed for C:\My-Temp\npm-2480-ea8f61fc\registry.npmjs.org
\ini\-\ini-1.3.4.tgz
npm ERR! Expected: 0537cb79daf59b59a1a517dff706c86ec039162e
npm ERR! Actual:   da39a3ee5e6b4b0d3255bfef95601890afd80709
npm ERR! From:     https://registry.npmjs.org/ini/-/ini-1.3.4.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\USMAN.NAVEED\npm-debug.log

I am getting this error and for ionic from last 7 hours and i have tried every thing

Please help me

**Comment by rajnetgen** [comment]
#9601 this seems to be an active issue with the registry

**Comment by seldo** [comment]
We apologize. A canary server rolled out earlier had a bug and we have rolled it back. Follow here for updates: https://npmjs.statuspage.io/incidents/pyw00fmpjzrh
