### ISSUE TITLE
shasum check failed for bytes-2.1.0.tgz

### ISSUE THREAD

**Issue by rh0dium** [npm/npm#9614]
npm ERR! Error: shasum check failed for /tmp/npm-1915-aD58zsvN/registry.npmjs.org/bytes/-/bytes-2.1.0.tgz
npm ERR! Expected: ac93c410e2ffc9cc7cf4b464b38289067f5e47b4
npm ERR! Actual:   da39a3ee5e6b4b0d3255bfef95601890afd80709
npm ERR! From:     https://registry.npmjs.org/bytes/-/bytes-2.1.0.tgz
npm ERR!     at /usr/lib/node_modules/npm/node_modules/sha/index.js:38:8
npm ERR!     at ReadStream.<anonymous> (/usr/lib/node_modules/npm/node_modules/sha/index.js:85:7)
npm ERR!     at ReadStream.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:944:16
npm ERR!     at process._tickCallback (node.js:448:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.2.0-48-virtual
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/ubuntu/pivotalenergy/apps/messaging/server
npm ERR! node -v v0.10.39
npm ERR! npm -v 1.4.28
npm ERR! not ok code 0

**Comment by rohandaxini** [comment]
I am also facing similar error

> npm install
npm WARN package.json react-app-boilerplate@2.2.2 No repository field.
npm WARN package.json react-app-boilerplate@2.2.2 No README data
npm WARN deprecated react-tools@0.12.2: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.3

npm ERR! shasum check failed for /var/folders/83/_wy36kbn163bl_4_fzs4f23c0000gp/T/npm-92599-edee72ea/registry.npmjs.org/findup-sync/-/findup-sync-0.2.1.tgz
npm ERR! Expected: e0a90a450075c49466ee513732057514b81e878c
npm ERR! Actual:   da39a3ee5e6b4b0d3255bfef95601890afd80709
npm ERR! From:     https://registry.npmjs.org/findup-sync/-/findup-sync-0.2.1.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /my_folder/npm-debug.log

**Comment by Fonger** [comment]
+1 

$ sudo npm install nodemon -g                                             1 ↵

> fsevents@0.3.8 install /usr/local/lib/node_modules/nodemon/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
./Release/.deps/Release/obj.target/fse/fsevents.o.d.raw { dev: 16777220,
  mode: 33188,
  nlink: 1,
  uid: -2,
  gid: 20,
  rdev: 0,
  blksize: 4096,
  ino: 9464694,
  size: 1370,
  blocks: 8,
  atime: Wed Sep 16 2015 23:25:18 GMT+0800 (CST),
  mtime: Wed Sep 16 2015 23:25:18 GMT+0800 (CST),
  ctime: Wed Sep 16 2015 23:25:18 GMT+0800 (CST),
  birthtime: Wed Sep 16 2015 23:25:18 GMT+0800 (CST) }
  SOLINK_MODULE(target) Release/fse.node
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "nodemon" "-g"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2

npm ERR! shasum check failed for /tmp/npm-69065-5d9181fb/registry.npmjs.org/lodash._createassigner/-/lodash._createassigner-3.1.1.tgz
npm ERR! Expected: 838a5bae2fdaca63ac22dee8e19fa4e6d6970b11
npm ERR! Actual:   da39a3ee5e6b4b0d3255bfef95601890afd80709
npm ERR! From:     https://registry.npmjs.org/lodash._createassigner/-/lodash._createassigner-3.1.1.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jerry/Dreamology-Backend/npm-debug.log

**Comment by tomoguisuru** [comment]
I'm having a similar issue but with different packages. I've tried `npm cache clean`, installing npm 3, installing npm at the latest stable rev, and completely removing the tmp folders. Nothing seems to be working though.

The strange thing is that if I rerun `npm install` different packages come back with errors.

Here is the latest:

```
npm WARN deprecated pangyp@2.3.2: use node-gyp@3+, it does all the things
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.6
npm ERR! npm  v2.14.3

npm ERR! shasum check failed for /var/folders/w8/3fz9xvdd5fz7p2tft5t0bcs40000gn/T/npm-12729-a26c7696/registry.npmjs.org/bytes/-/bytes-2.1.0.tgz
npm ERR! Expected: ac93c410e2ffc9cc7cf4b464b38289067f5e47b4
npm ERR! Actual:   da39a3ee5e6b4b0d3255bfef95601890afd80709
npm ERR! From:     https://registry.npmjs.org/bytes/-/bytes-2.1.0.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/brandondrake/src/EV/ember-deployment/npm-debug.log
```

**Comment by hisune** [comment]
+10086

`npm install geoip-lite`

`
npm ERR! Linux 2.6.32-358.6.2.el6.x86_64
npm ERR! argv "node" "/usr/local/node/bin/npm" "install" "geoip-lite"
npm ERR! node v0.10.36
npm ERR! npm v2.14.3

npm ERR! shasum check failed for /tmp/npm-8116-ad9e27de/registry.npmjs.org/pullstream/-/pullstream-0.0.4.tgz
npm ERR! Expected: 41d83c446d290e2f2eb9b681d3f3b56fee88a0af
npm ERR! Actual: da39a3ee5e6b4b0d3255bfef95601890afd80709
npm ERR! From: https://registry.npmjs.org/pullstream/-/pullstream-0.0.4.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR! https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR! /data/click/npm-debug.log
`

**Comment by seldo** [comment]
We apologize. A canary server rolled out earlier had a bug and we have rolled it back. Follow here for updates: https://npmjs.statuspage.io/incidents/pyw00fmpjzrh

**Comment by rohandaxini** [comment]
thanks for the updates @seldo By when it will start working again as I am still facing same error.

**Comment by rohandaxini** [comment]
I read on that link you sent `We rolled the deployment back at 14:29 UTC and are working on invalidating caches affected by this outage.`

**Comment by seldo** [comment]
Resolved now!

**Comment by rohandaxini** [comment]
Thanks @seldo its working now :+1:

**Comment by rh0dium** [comment]
Thanks!!  Working.
