### ISSUE TITLE
Cannot install Bower on Yosemite

### ISSUE THREAD

**Issue by javirocha** [npm/npm#9615]
I have node, npm & git on my mac, but I can't install Bower since it throws an error, even if I run the command as su.

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "bower"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2

npm ERR! shasum check failed for /tmp/npm-822-d8486ea8/registry.npmjs.org/p-throttler/-/p-throttler-0.1.1.tgz
npm ERR! Expected: 15246409d225d3eefca85c50de710a83a78cca6a
npm ERR! Actual:   da39a3ee5e6b4b0d3255bfef95601890afd80709
npm ERR! From:     https://registry.npmjs.org/p-throttler/-/p-throttler-0.1.1.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Javier/npm-debug.log

**Comment by seldo** [comment]
We apologize. A canary server rolled out earlier had a bug and we have rolled it back. Follow here for updates: https://npmjs.statuspage.io/incidents/pyw00fmpjzrh
