### ISSUE TITLE
npm pack won't pack a symlink

### ISSUE THREAD

**Issue by aredridel** [npm/npm#9622]
I've a package with two files, one symlinked to the other. After packing, the symlink is gone in the resulting tarball.

**Comment by othiym23** [comment]
This is by design (I think, @isaacs can correct me if my thinking is faulty here). Not all platforms support symbolic links, and there are a host of security issues we can avoid if we avoid packing symlinks altogether. @isaacs should links within a package be preserved by the packing process?
