### ISSUE TITLE
OS X - Docker Machine - symlink issue

### ISSUE THREAD

**Issue by alancasagrande** [npm/npm#9624]
(Not sure if it's a npm issue, sorry if it isn't)

Running `npm install` inside a Docker Container using Docker Machine on OS X is failing for me, apparently due to bin links:

```
$ npm install node-sass

npm WARN deprecated pangyp@2.3.2: use node-gyp@3+, it does all the things
npm ERR! Linux 4.0.9-boot2docker
npm ERR! argv "node" "/usr/local/bin/npm" "install" "node-sass"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! path ../mkdirp/bin/cmd.js
npm ERR! code EPROTO
npm ERR! errno -71

npm ERR! EPROTO, symlink '../mkdirp/bin/cmd.js'
```

However this works perfectly:

```
$ npm install node-sass --no-bin-links

$ ln -s /usr/local/lib/node_modules/node-sass/bin/node-sass node_modules/.bin

$ node_modules/.bin/node-sass

Provide a Sass file to render

  Example
    node-sass --output-style compressed foobar.scss foobar.css
    cat foobar.scss | node-sass --output-style compressed > foobar.css
```

Setting this didn't help:

```
VBoxManage setextradata default VBoxInternal2/SharedFoldersEnableSymlinksCreate/SHARE_NAME 1
```

Any ideas? What npm is running under the hood?

**Comment by mstade** [comment]
Not that it's much help; but I just ran into the exact same situation, and can verify all you've written as correct.

**Comment by mstade** [comment]
FWIW, doing an `npm install` outside of the container seems to work, so the problem aren't so much the symlinks as it is the symlink creation. Also worth mentioning is that docker-machine sets SharedFoldersEnableSymlinksCreate for the Users share correctly by itself, so no such configuration should be necessary. I verified this just now with a fresh machine.

**Comment by rschutt** [comment]
Are you running VirtualBox 5.0.4?  Looks like there's a symlink bug in 5.0.4:  https://www.virtualbox.org/ticket/14563

**Comment by alancasagrande** [comment]
Installed the 5.0.5 build linked on the ticket and now it's working again. Thanks! I'm closing as it's not a npm issue.

**Comment by mstade** [comment]
Can confirm @alancasagrande's comment – everything's working fine now. Thank you very much @rschutt for the pointer in the right direction!

**Comment by Pushplaybang** [comment]
this also sorted this out for me.

**Comment by neurosnap** [comment]
I'm having the same issue on Windows 8.1, the 5.0.5 build linked above is for OS X only, I guess I'll downgrade virtualbox for now, does anyone know of a working version to install?

**Comment by rdsubhas** [comment]
Just another thing to watch out for: Make sure Virtualbox Extension Pack is installed (some people miss this and it produces the same symlink error outlined above)

**Comment by Pushplaybang** [comment]
thanks for the tip, I don't remember seeing anything about the extension pack, is it bundled in the virtualbox installer ?

**Comment by rdsubhas** [comment]
Not sure whether its bundled in Docker Toolbox, can you check `VirtualBox > Preferences > Extensions`?

<img width="767" alt="screen shot 2015-10-24 at 8 44 23 pm" src="https://cloud.githubusercontent.com/assets/1570745/10711143/12f8b6ce-7a90-11e5-9b0c-7565dac1918c.png">

**Comment by Pushplaybang** [comment]
Having installed virtualbox directly, it doesn't seem to be there by default.

**Comment by rdsubhas** [comment]
Yep, most likely reason for the symlink issue. Can you try installing the Extension Pack separately from https://www.virtualbox.org/wiki/Downloads - it should resolve the symlink error.

FYI https://medium.com/@rdsubhas/docker-for-development-common-problems-and-solutions-95b25cae41eb#.k3zqz8cgd
