### ISSUE TITLE
ERR! network getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by haiyanhu** [npm/npm#9630]
I get the following error:
node:v4.0.0
npm:v2.14.2

```
$ sudo npm install -g supervisor --registry http://registry.npmjs.org/
[sudo] password for HHY
npm ERR! Linux 3.10.0-123.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/bin/npm" "install" "-g" "supervisor" "--registry" "http://registry.npmjs.org/"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! syscall getaddrinfo

npm ERR! network getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:80
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     /home/huhaiyan/node-v4.0.0-linux-x64/npm-debug.log
```

**Comment by KenanY** [comment]
@haiyanhu I'll ask the same question the error message does: are you behind a proxy or a firewall that could be messing with your connection to the registry?

**Comment by haiyanhu** [comment]
@KenanY  yes.npm config  as below:
$ npm config list
; cli configs
user-agent = "npm/2.14.2 node/v4.0.0 linux x64"

; userconfig /home/huhaiyan/.npmrc
http_proxy = "http://172.17.2.37:3128"
https- = "proxy"
https-proxy = "http://172.17.2.37:3128/"
proxy = "http://172.17.2.37:3128/"
registry = "http://registry.npmjs.org/"

; node bin location = /usr/local/bin/node
; cwd = /home/huhaiyan/node-v4.0.0-linux-x64
; HOME = /home/huhaiyan
; 'npm config ls -l' to show all defaults.

**Comment by xushvai** [comment]
`npm config set registry http://registry.npmjs.org/`

**Comment by lhkhhy** [comment]
By switch the env. has been resolved this issue, it may be my netword has problem 
closes #9630

**Comment by ZapevalovAnton** [comment]
Thanks @xushvai. It is work!

**Comment by azanli** [comment]
Thanks @xushvai. This solution should've been present in the other 10 similar forum issues!

**Comment by telalwar** [comment]
npm config delete proxy worked for me.  I was not behind a corporate proxy so that doesn't apply to me.
