### ISSUE TITLE
Error while executing the dependency with npm install

### ISSUE THREAD

**Issue by Sridhararshanapally** [npm/npm#9635]
We are getting the "Error: Command failed: git clone" error while running npm install.

```
1197 error Error: Command failed: git clone --mirror git@git.assembla.com:caready.ui-framework.git c:\Users\sarshanapally\AppData\Roaming\npm-cache\_git-remotes\git-git-assembla-com-caready-ui-framework-git-e324541a
1197 error Cloning into bare repository 'c:\Users\sarshanapally\AppData\Roaming\npm-cache\_git-remotes\git-git-assembla-com-caready-ui-framework-git-e324541a'...
1197 error Host key verification failed.
1197 error fatal: Could not read from remote repository.
1197 error
1197 error Please make sure you have the correct access rights
1197 error and the repository exists.
1197 error
1197 error     at ChildProcess.exithandler (child_process.js:728:12)
1197 error     at ChildProcess.EventEmitter.emit (events.js:107:17)
1197 error     at maybeClose (child_process.js:991:16)
1197 error     at Process.ChildProcess._handle.onexit (child_process.js:1058:5)
1198 error If you need help, you may report this *entire* log,
1198 error including the npm and node versions, at:
```

Environment : Windows 7, git version 2.5.2, npm 1.4.3

Please find the log for details.
package.json
```
"devDependencies": {
   ...
  "caready.ui-framework": "git+ssh://git@git.assembla.com:caready.ui-framework.git#master",
  ....
}
```

**Comment by Sridhararshanapally** [comment]
![npm debug](https://cloud.githubusercontent.com/assets/7143236/9937847/796b948a-5d30-11e5-98cc-b58b2e449003.png)

**Comment by ehsalazar** [comment]
@Sridhararshanapally The version of npm you're using is outdate. Could you give [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) a try? You may want to also [update node](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-node).

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.
