### ISSUE TITLE
Installing npm from older npm missing dependencies: Error: Cannot find module 'are-we-there-yet'

### ISSUE THREAD

**Issue by jdufresne** [npm/npm#9644]
I'm using the system npm provided by Fedora to install a local, newer version of npm before using newer npm to install my project's dependencies. Ideally it would go:

```
$ npm install npm
$ node_modules/.bin/npm install
```

 However, the newly install npm fails with every execution. It throws the error: "Cannot find module 'are-we-there-yet'"

```
[jon@localhost ~]$ npm --version
1.3.6
[jon@localhost ~]$ npm cache clean
[jon@localhost ~]$ rm -rf node_modules
[jon@localhost ~]$ npm install npm
npm http GET https://registry.npmjs.org/npm
npm http 200 https://registry.npmjs.org/npm
npm http GET https://registry.npmjs.org/npm/-/npm-3.3.3.tgz
npm http 200 https://registry.npmjs.org/npm/-/npm-3.3.3.tgz
npm@3.3.3 node_modules/npm
[jon@localhost ~]$ node_modules/.bin/npm --version

module.js:340
    throw err;
          ^
Error: Cannot find module 'are-we-there-yet'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/jon/node_modules/npm/node_modules/npmlog/log.js:2:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by othiym23** [comment]
That version of npm is so old it can't reliably upgrade all the way to `npm@3`. I agree that the behavior isn't ideal, but there's not a lot we can do about it now, as 1.3 barely works with the current registry architecture and is full of race conditions (and is no longer supported by the CLI team, for these and many other reasons). You should be able to install `npm@1.4.28` or `npm@2.14.4` and use that to bootstrap to `npm@latest`.With luck, there will be newer npm packages from distro vendors soon. Good luck!

**Comment by dynnamitt** [comment]
Nice weekend to you!!!

**Comment by jdufresne** [comment]
Thanks @othiym23 I followed up with an downstream bug. <https://bugzilla.redhat.com/show_bug.cgi?id=1264440>

**Comment by Gert25** [comment]
This was useless
