### ISSUE TITLE
Error in running command npm install request

### ISSUE THREAD

**Issue by VishalGulati** [npm/npm#9648]
Getting an error that "getting an error that you are behind a proxy or have bad network setting"

**Comment by sinkingshriek** [comment]
I think the error is pretty descriptive enough. 
If you're behind a firewall then you'd need to let `npm` know about it.

##### For proxy servers:- 
`npm config set proxy=<your_proxy_server:port>`
`npm config set https-proxy=<your_proxy_server:port>`

##### For bad network:-
`ping registry.npmjs.org // if this successfully returns with no packet loss then you should be good as well`

Also, make sure your anti-virus/firewall isn't blocking the connection.

**Comment by VishalGulati** [comment]
tried all this but no luck!
