### ISSUE TITLE
3.x being tagged as latest

### ISSUE THREAD

**Issue by pascalduez** [npm/npm#9649]
I guess there's an issue in tagging, and it's not what's been stated in the Changelog.

Actually: `npm i npm@latest -g` installs `3.3.3` while it should install `2.14.4`

```
$ npm dist-tag ls npm
latest-2: 2.14.4
latest: 3.3.3
next-2: 2.14.5
next: 3.3.4
```

**Comment by othiym23** [comment]
See the [head of CHANGELOG.md](https://github.com/npm/npm/blob/master/CHANGELOG.md) and the [release notes for the latest release](https://github.com/npm/npm/releases/tag/v3.3.3). See also these tweets:

- https://twitter.com/ReBeccaOrg/status/644653063932788736
- https://twitter.com/ReBeccaOrg/status/644653508906487808
- https://twitter.com/othiym23/status/644653554548871169
- https://twitter.com/othiym23/status/644666660348006402

It's `npm@3` time!

**Comment by pascalduez** [comment]
Dang, sorry. 
 For some obscure reasons I was referring to the first 3.0 release notes...
