### ISSUE TITLE
npm publish - Fails with error code 500

### ISSUE THREAD

**Issue by prabhash1785** [npm/npm#9654]
I am trying to publish a public module to npm. I checked for module name on https://registry.npmjs.org/ and this module name does not exist yet so the name is available.

I also looked at all my .npmrc configuration and all the information seems to be correct.

Before doing publish, I did npm login a few times but I keep seeing this error:

```
npm ERR! publish Failed PUT 500
npm ERR! Error: unexpected status code: 404 : mock-up
npm ERR!     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:308:14)
npm ERR!     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:246:65)
npm ERR!     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:236:22)
npm ERR!     at Request.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1142:14)
npm ERR!     at Request.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1096:12)
npm ERR!     at IncomingMessage.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:943:16
npm ERR!     at process._tickCallback (node.js:419:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 13.4.0
npm ERR! command "node" "/usr/local/bin/npm" "publish"
npm ERR! cwd /Users/prrathore/MyGitRepo/mockserver
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/prrathore/MyGitRepo/mockserver/npm-debug.log
npm ERR! not ok code 0
```

Can someone please help?

**Comment by KenanY** [comment]
@prabhash1785 Does this also occur if you [upgrade](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) to the latest stable release of `npm`?

**Comment by prabhash1785** [comment]
I haven't upgraded to the latest npm version. But this is what I have on my machines:
Node.js v0.10.32
NPM 1.4.28

Is this a problem with the version I am using? I am able to publish to our Enterprise NPM version without any problems.

**Comment by prabhash1785** [comment]
I was able to publish my module. I had a .npmrc file in my project. Once I deleted this project specific .npmrc, I was able to publish.

Even though it worked, I am not able to understand why was it failing because of project level .npmrc? As per npm documentation, I read that project level .npmrc is not considered while publishing the module?

**Comment by ehsalazar** [comment]
@prabhash1785 npm@1 is quite old. We're currently at v3.3.9. [Updating](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) will cure a multiple of issues. It sounds like you were able to get the package published none the less. I'll close this for now. We’ll be happy to reopen if necessary.
