### ISSUE TITLE
npm JS API has a breaking change between 3.2 and 3.3

### ISSUE THREAD

**Issue by ljharb** [npm/npm#9656]
See https://travis-ci.org/ljharb/npm-deprecations/builds/81028280 vs https://travis-ci.org/ljharb/npm-deprecations/builds/81028867 - the only change is bumping `npm` from `3.2.x` to `3.3.x` - and the tests on travis are failing. Note, they pass for me just fine on my Mac with 3.3.x, so I'm not 100% sure what's going on.

**Comment by KenanY** [comment]
Test failed once for me (Linux) but now it passes. I thought it might be a cache thing but even clearing cache (just `npm cache clear forms` at the moment) is not helping :/

**Comment by othiym23** [comment]
I don't consider the internal API to be part of the versioned interface of the CLI; when asked, we tell people that it's guaranteed for no particular purpose and unsupported. It wasn't intended for use outside the npm code base and we very much want to replace it with something better. This is why the API documentation was removed – it being there led to a misleading impression of the API's stability.

So I don't think a change to the API is breaking or a bug unless it changes the behavior of the CLI when run from the command line. I'm interested in finding out what changed here, but until and unless we can establish that npm's overall behavior has changed in an incompatible way, I'm not going to mark this as a bug.

**Comment by ljharb** [comment]
That's fair. I discussed it in irc and I must have just missed the official deprecation notice awhile back.

I'd love to see it fixed, and I'm super curious what broke, but I'll also look for ways to migrate off of this usage.

**Comment by KenanY** [comment]
`git bisect`ing while running the tests on Travis tells me that https://github.com/npm/npm/commit/b50105fcb2ef2c96df0521a4fe7bfd4ee39a8702 is the first bad commit (as innocent as it might look).

**Comment by othiym23** [comment]
@ljharb: `child_process.spawn` is your friend. ;)

@KenanY it's unclear to me why the changes to `chownr` would cause this issue, but if your poking around finds that this is actually a semantic change in npm's behavior, please let us know, because this may have uncovered a(n actual) bug.

**Comment by othiym23** [comment]
I'm going to close this out now. We'll be happy to fix whatever we broke if it turns out to be easy to land without breaking anything else, but in general, the npm API is what it is (which is mostly something in need of continual improvement).
