### ISSUE TITLE
npm 3, peer dependency and deduping

### ISSUE THREAD

**Issue by targos** [npm/npm#9663]
I'm going to try and explain a problem that I have with a project after updating to npm@3 (v3.3.3).
I setup a test repository to reproduce the issue: https://github.com/targos/npm-peer-deps

So here is the situation:
Among my devDependencies I have **eslint** and **browserify**.
Eslint depends on **estraverse-fb**, which has **estraverse** as a peerDependency. Eslint has estraverse in its dependencies (version ^4.1.0).
Browserify does not directly depend on estraverse but has it somewhere in its dependency tree (version ^1.9.1).
Eslint does not direcly require estraverse. It requires estraverse-fb, which then requires estraverse.

When I install with npm@3, I get the following directory structure:
- node_modules
  - eslint
    - node_modules/estraverse@4.1.0
  - estraverse@1.9.3
  - estraverse-fb

So when eslint requires estraverse-fb, estraverse-fb ends up requiring estraverse@1.9.3. This is not the version that eslint expects and has in its dependencies.
The consequence of all this is that the eslint command crashes in my project because I use ES2015 features that are not supported by estraverse@1.9.3.

**Comment by othiym23** [comment]
This is awkward and irritating and I'm sorry you got caught on this. There are two fixes for this issue:

1. file an issue on `estraverse-fb`. I'm not really sure why they thought it was a good idea to `peerDepend` on `estraverse`, but in the `npm@3` world, they should _also_ have either a `dependency` or `devDependency` to ensure that it's available to `estraverse-fb`.
2. add a direct `devDependency` or `dependency` on `estraverse@^4.1.0` to your `package.json`. That way, the version of `estraverse` at the top level will keep `estraverse-fb` from exploding, and `browserify` will get its own copy of `estraverse@1.9.1`, and everybody _should_ be happy. If not, that's definitely a bug.

**Comment by othiym23** [comment]
After talking this through with @iarna, we've decided that a relatively small change to the install algorithm would smooth this particular rough edge:

>  iarna [14:43]
> I think it's plausible we can make it do a right thing there, and install `estraverse-fb` under `eslint` so that its `peerDependency` is met. (Making it know to flip where versions of eslint goes, I'm less sure about.) Because when the resolver is deciding where to put `estraverse-fb` it walks up the tree until it either finds a place that's not acceptable (in which case it backups up to the previous level) or hits the top (and uses that) – hitting a layer in the tree where any of its `peerDependencies` match could plausibly mark that is the highest point it can go, and it could stop there.
> 
> othiym23 [14:47] 
> Yeah, that's what I was thinking as well: have a stage of the tree realization process being prioritizing `peerDependency` versions (that are already scheduled to be installed, natch) over others, so that `browserify` gets its old busted `estraverse` but `estraverse-fb` ends up with what it needs at the right level automatically (i.e. treating `peerDependency` even more like a constraint).
> 
> iarna [14:50]
> It matches the current model. That's how we treat bin conflicts now too.

**Comment by targos** [comment]
Thank you for your answer and fast support :smiley: 

For now I went for fix#2 and added `estraverse` in my `devDependencies`.

**Comment by damonmcminn** [comment]
I've also been experiencing the same issue, so thanks @othiym23 planning a fix.

**Comment by mzgol** [comment]
@targos Is there any reason why `estraverse-fb` cannot depend on `estraverse` instead of `peerDepend`ing?

**Comment by targos** [comment]
I don't know... Maybe @rreverser can explain ?

**Comment by RReverser** [comment]
@mzgol With npm@3 it can I guess. Estraverse-FB usually has to inject into pre-installed Estraverse, and earlier peerDependency was the only way to guarantee that Estraverse-FB won't install own inner version of Estraverse inside of it's folder instead of injecting into pre-installed one.

**Comment by mzgol** [comment]
> Estraverse-FB usually has to inject into pre-installed Estraverse

But according to the initial report ESLint doesn't directly require `estraverse` but only `estraverse-fb` so why can't ESLint stop depending on `estraverse` and `estraverse-fb` start depending on `estraverse`? Only one copy would be used then as well.

**Comment by RReverser** [comment]
@mzgol Well, ESLint is not the only consumer. But anyway, with flattened dir structure that came in npm@3 I guess it shouldn't be a problem at all. Just too bad that npm@2 is still the default that comes pre-installed with Node, somewhat afraid to break other dependents.

**Comment by RReverser** [comment]
> So when eslint requires estraverse-fb, estraverse-fb ends up requiring estraverse@1.9.3. 

In fact, this is weird - estraverse-fb depends on `estraverse@*` and not specific version range.

**Comment by mzgol** [comment]
> @mzgol Well, ESLint is not the only consumer.

Ah, OK, I didn't know that matters.

> Just too bad that npm@2 is still the default that comes pre-installed with Node

Yup, and only Node>=5 will get npm@3 by default; Node 4 will be supported until 2018-04-01 so this will not be a disappearing problem any time soon.

**Comment by RReverser** [comment]
> so this will not be a disappearing problem any time soon

Hmm. Can't it get newer npm as part of it's support? (like, in minor release)

**Comment by mzgol** [comment]
That's more a question to the npm team, but I doubt such a drastic change would be introduced to v4 when it's in the LTS phase and it's getting there the day Node 5 is getting released.

**Comment by othiym23** [comment]
It's not up to the npm team to decide what goes into Node LTS releases; that policy is set by the Node.js LTS working group. They've (mostly) decided that the flattened install in `npm@3` is too big a change to include in Node 4 before it goes LTS, so unless the WG changes its collective mind, Node 4 LTS will always ship with `npm@2`. The CLI team will probably continue to encourage all users to update to `npm@latest`, because we believe it to be the most stable and usable version of npm overall (especially once @iarna's upcoming performance work lands), but in a break from the past, we will be supporting `npm@2` well into next year in order to ensure that Node LTS users have a supported version of npm.

**Comment by othiym23** [comment]
That said, I would look long and hard at how `estraverse-fb` is designed to be used, because my general advice is that people using `peerDependencies` to enforce a singleton pattern – especially for this kind of in-place monkeypatching – are generally following an antipattern. It seems to me that either applying itself to an `estraverse` instance / function after it's been required, or using what comes out of `estraverse-fb` directly would work with both npm 2 and 3 without worrying about requiring there to be only one `estraverse` in the install tree.

**Comment by RReverser** [comment]
>  It seems to me that either applying itself to an estraverse instance / function after it's been required

This is also available starting from some version of estraverse that supported pluggable rules. Right now both modes can work.
