### ISSUE TITLE
Error when Installing Yeoman

### ISSUE THREAD

**Issue by 1vision** [npm/npm#9673]
I keep getting this error when I try to install Yeoman on Linux 3.13.0-63-generic:

 Attempt to unlock /home/stephanie/.node/lib/node_modules/yo, which hasn't been locked

I have tried updating everything but it's still giving me this error and will not load.

**Comment by othiym23** [comment]
What do you get when you run `npm -v`? It's possible you may have a version of npm old enough that a simple [npm upgrade](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) may fix things for you. (If you're running on Ubuntu and using their default versions of `nodejs` and `npm`, you may need to also installl the package `nodejs-legacy` for the upgraded version of npm to work properly.)

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.
