### ISSUE TITLE
npm 3.3.4: after linking a module, i can't remove it

### ISSUE THREAD

**Issue by 75lb** [npm/npm#9680]
when i'm working on a new module i often link to it from an existing app:
```
$ npm ln ../../wordwrapjs/
```

later, after publishing wordwrapjs, i want to remove the link and install it properly.. but i can't remove it.. 
```
$ npm rm wordwrapjs
npm ERR! gentlyRm containing path /Users/lloyd/Documents/75lb/gists/link/node_modules/wordwrapjs isn't under npm's control
npm WARN install:wordwrapjs Refusing to delete: /Users/lloyd/Documents/75lb/gists/link/node_modules/.bin/wordwrapjs not in /Users/lloyd/Documents/75lb/gists/link/node_modules/wordwrapjs
- wordwrapjs@0.2.0 node_modules/wordwrapjs
```

i end up trashing `node_modules` entirely and starting again..

**Comment by azat-co** [comment]
same for me

**Comment by digital-synapse** [comment]
yeah. just found this happens on windows as well.

```
npm ERR! gentlyRm containing path C:\Program Files\nodejs\node_modules\webef-cli isn't under npm's control
npm WARN install:webef-cli Refusing to delete: C:\Program Files\nodejs\webef.cmd not in C:\Program Files\nodejs\node_mod
ules\webef-cli
- webef-cli@0.1.0 node_modules\webef-cli
```

**Comment by bowenliang123** [comment]
i got the same problem.

**Comment by johnjelinek** [comment]
:+1: :crying_cat_face:

**Comment by feross** [comment]
Same issue.

**Comment by artemsvirskyi** [comment]
+

**Comment by azat-co** [comment]
i'm unfollowing this ;-)

**Comment by evernaut** [comment]
I believe I have the same issue, but only when I run npm uninstall programmatically (or spawn npm-cli.js) ... it works fine when run it from the command line.

**Comment by ericgrosse** [comment]
I had this issue when trying `npm install -g yo`. It turns out my npm version was way out of date (3.3.6 compared to latest of 3.7.3) and updating npm did the trick. For windows users, the easiest way to update npm is by doing:

`npm install -g npm-windows-upgrade`
`npm-windows-upgrade`

**Comment by jeremyckahn** [comment]
Upgrading to 3.8.3 fixed the issue for me.  It seems that this is no longer an issue in recent npm versions.  Should this issue be closed?

**Comment by hassankhan** [comment]
I just got the same issue

**Comment by zkat** [comment]
I'm seeing multiple people claiming that this got fixed for them after updating to the latest npm. @75lb does this still happen for you on `npm@latest`?

**Comment by 75lb** [comment]
Hi @zkat  - this issue has been fixed for a number of months, now.. i'm unable to reproduce it in 3.10.5.. Closing, thanks 👍
