### ISSUE TITLE
npm 3.3.3: remove bar for short-running commands?

### ISSUE THREAD

**Issue by indexzero** [npm/npm#9683]
From what I've gleaned the progress bar is pretty awesome for `npm install` and `npm outdated`, but not as useful for the following commands:

```
npm owner
npm view
```

Local commands appear to have it removed, e.g.:

```
npm config
npm ls
npm test
```

... so I guess it's just a network request thing? What are your thoughts on removing it for commands where the network requests are all or nothing?

**Comment by iarna** [comment]
I generally agree– I think we shouldn't be showing progress bars for commands that complete quickly. That said, having used npm on really, really bad networks, having some indication that it's doing something is really nice.

I think my preferred solution would be to only show the progress bar (and thus the spinner) if the command has taken more than some amount of time.

However, this isn't on the roadmap for the coming year, and so the core team is unlikely to get to it. We're not keeping open feature requests that we don't expect to get to in the next year, so I'm going to close this. We would accept a PR to this effect though.
