### ISSUE TITLE
How to install node npm for nodejs on ubuntu

### ISSUE THREAD

**Issue by neelabhsingh** [npm/npm#9687]
On my ubuntu system **nodejs verison is v0.10.25 and nop version is 1.3.10**. But when I tried to install mochajs for testing I am getting following error

    user@ubuntu:~/mochatest$ sudo npm install -g mocha
    npm ERR! Error: Cannot find module 'fstream'
    npm ERR!     at Function.Module._resolveFilename (module.js:338:15)
    npm ERR!     at Function.Module._load (module.js:280:25)
    npm ERR!     at Module.require (module.js:364:17)
    npm ERR!     at require (module.js:380:17)
    npm ERR!     at Object.<anonymous> (/usr/lib/nodejs/tar/lib/entry.js:14:15)
    npm ERR!     at Module._compile (module.js:456:26)
    npm ERR!     at Object.Module._extensions..js (module.js:474:10)
    npm ERR!     at Module.load (module.js:356:32)
    npm ERR!     at Function.Module._load (module.js:312:12)
    npm ERR!     at Module.require (module.js:364:17)
    npm ERR! If you need help, you may report this log at:
    npm ERR!     <http://github.com/isaacs/npm/issues>
    npm ERR! or email it to:
    npm ERR!     <npm-@googlegroups.com>
    
    npm ERR! System Linux 3.13.0-36-generic
    npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "mocha"
    npm ERR! cwd /home/mochatest
    npm ERR! node -v v0.10.25
    npm ERR! npm -v 1.3.10
    npm ERR! code MODULE_NOT_FOUND
    npm ERR! 
    npm ERR! Additional logging details can be found in:
    npm ERR!     /home/mochatest/npm-debug.log
    npm ERR! not ok code 0

**Comment by KenanY** [comment]
@neelabhsingh Does this also occur if you [upgrade Node.js](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-node) and/or [upgrade `npm`](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) to their respective latest stable releases?

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.
