### ISSUE TITLE
Unable to install wordpos

### ISSUE THREAD

**Issue by saurabhkhemuka** [npm/npm#9688]
![screenshot from 2015-09-21 13 40 32](https://cloud.githubusercontent.com/assets/14541121/9987546/75b2396e-6066-11e5-8695-823051228a0e.png)

It says that no compatible version of natural found, but this version of natural is one of the valid targets 

![screenshot from 2015-09-21 13 39 42](https://cloud.githubusercontent.com/assets/14541121/9987545/75a07396-6066-11e5-862c-72659ce14541.png)

If this information is not enough, please ask for the necessary
I'm quite new at this, what should be done??

**Comment by KenanY** [comment]
@saurabhkhemuka `npm@1.3.10` is very old. Please try [updating](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm).

**Comment by saurabhkhemuka** [comment]
Got it. Thank you
