### ISSUE TITLE
`wanted` vs `latest`

### ISSUE THREAD

**Issue by Zearin** [npm/npm#9690]
Not sure what to make of this, but here’s what just happened:

``` bash
$ npm -g outdated
Package  Current  Wanted  Latest  Location
npm        3.3.3   3.3.4   3.3.3  lib
xlyrics    0.9.0   0.9.0   0.6.0  lib

$ npm -g install npm@latest
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
/usr/local/lib
└── npm@3.3.3 
```

So, npm “wants” `3.3.4`, but the latest is `3.3.3`.  Hmmm…

(Running on OS X with Node v4.1.0.)

**Comment by Zearin** [comment]
(I forgot to mention that) The same results also occurred with `npm -g up npm`.

**Comment by remcohaszing** [comment]
This issue affects me too. I'm confused by the `support` label. This looks like a bug to me. 

It appears on Ubuntu and OS X using Node 0.12 and Node 4.1.x.

**Comment by sholladay** [comment]
I encountered this today and thought it was strange, too. Here is my output.

````sh
$ npm outdated -g
Package                Current  Wanted         Latest  Location
generator-node-webkit    1.0.3   1.0.4  2.0.0-alpha.3  
npm                      3.3.6   3.3.8          3.3.6  
````

In my case, the fact that there is a difference between `npm` and `generator-node-webkit` in whether or not Wanted is higher than Latest makes it particularly confusing. The npm row makes it look like Wanted is just finding the highest version in `dist-tags`, but the `generator-node-webkit` row makes it look like it doesn't care about that at all.

**Comment by Zearin** [comment]
(Checking in on this, <time>2015-10-29</time>.)

Still having issues with this.  Here’s the latest output (and version info):

```bash
$ npm -g outdated
Package     Current  Wanted  Latest  Location
browserify   11.2.0  11.2.0  12.0.1   
$ npm -g up browserify
$ npm -g outdated
Package     Current  Wanted  Latest  Location
browserify   11.2.0  11.2.0  12.0.1  
$ node --version
v4.2.1
$ npm --version
3.3.9
```

**Comment by thealjey** [comment]
@Zearin this is an npm2 issue, just run (the duplication is intentional):
```
npm i npm@latest -g
npm i npm@latest -g
```
to resolve the above mentioned "problem"

**Comment by Zearin** [comment]
> @Zearin this is an npm2 issue

But…my npm said it was v3.3.9 (?)

> just run (the duplication is intentional):

I just did.  No luck. The same behavior persists.  :(

Does this help?

```
$ npm -g config ls | sed -e 's/«my $HOME»/~/g'
; cli configs
global = true
user-agent = "npm/3.3.9 node/v4.2.1 darwin x64"

; environment configs
cache = "~/Library/Caches/npm"
loglevel = "warn"
userconfig = "~/.config/npm/.npmrc"
userignorefile = "~/.config/npm/.npmignore"

; userconfig ~/.config/npm/.npmrc
cache = "~/Library/Caches/npm"
https-proxy = null
loglevel = "warn"
python = "/usr/local/bin/python2"

; builtin config undefined
prefix = "/usr/local"

; node bin location = /usr/local/Cellar/node/4.2.1/bin/node
; cwd = /usr/local/lib
; HOME = ~
; "npm config ls -l" to show all defaults.
```

**Comment by Zearin** [comment]
> This issue affects me too. I'm confused by the support label. This looks like a bug to me.

:+1:

**Comment by ilikebits** [comment]
:+1: It seems to me that NPM's `wanted` actually means "matched by `*` using `semvar`" whereas "latest" means "last package version published". For example, installing `elm` and running `npm outdated` shows the "wanted" version (which is actually old) to be `2.0.0` but the "latest" version to (correctly) be `0.16.0`.
