### ISSUE TITLE
ENEEDAUTH error when publishing modules

### ISSUE THREAD

**Issue by bnvk** [npm/npm#9694]
Just this morning NPM won't let me publish modules. I re-ran the `npm login` command and double checked my credentials with logging into the website. I even deleted my `.npmrc` and re-ran login which seemed to complete just fine, however I keep getting the same issue:

```
196 silly publish   readmeFilename: 'README.md',
196 silly publish   _id: 'twiddler@0.2.1',
196 silly publish   dist: { shasum: 'fe9908b4c084decd7c06fa889e786c4f2eaec8fe' },
196 silly publish   _from: '.' }
197 error need auth auth and email required for publishing
197 error need auth You need to authorize this machine using `npm adduser`
198 error System Linux 3.18.17-6.pvops.qubes.x86_64
199 error command "node" "/usr/bin/npm" "publish"
200 error cwd /home/user/Twiddler
201 error node -v v0.10.36
202 error npm -v 1.3.6
203 error code ENEEDAUTH
204 verbose exit [ 1, true ]
```

I'm running Fedora 21

**Comment by KenanY** [comment]
@bnvk You can no longer publish with `npm@1.3.6`. It is way to old to understand the new registry architexture. Try [updating](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) first.

**Comment by bnvk** [comment]
@KenanY thanks for the suggestion. I ran the command in the link you mentioned `npm install -g npm@latest` and now I getting the following error:

```
[user@dev ~]$ npm -v

module.js:340
    throw err;
          ^
Error: Cannot find module 'are-we-there-yet'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/npmlog/log.js:2:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by KenanY** [comment]
@bnvk Hmm, looks broken now. Probably because it would have been wiser for me to say that you should update to `npm@1.4.28` first before going straight to `npm@3`, since I don't think `npm@1.3` can quite handle installing `npm@3`.

Maybe try fixing everything with a reinstall?:

```
curl -L https://www.npmjs.org/install.sh | sh
```

**Comment by othiym23** [comment]
@brnvk You're going to need to reinstall Node so you get a clean version of npm again, and then run `npm install -g npm@2 && npm install -g npm@latest` -- right now it's not possible to upgrade directly from `npm@1.3.6` to `npm@3` (we're working on that).

Otherwise closing this as resolved. Get to a newer version of npm, log in again, and this problem will go away.

**Comment by bnvk** [comment]
@KenanY @othiym23 I did indeed to have to remove and reinstall node and npm, but seems to be working now! Thanks for the help :+1: :smile:
