### ISSUE TITLE
 npm v3.3.3: npm can no longer self-update

### ISSUE THREAD

**Issue by CKarper** [npm/npm#9695]
npm won't update to v3.3.4. This is the output I get:
```
d:\>npm i npm -g
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ckarper.DEV\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "npm" "-g"
npm ERR! node v4.0.0
npm ERR! npm  v3.3.3
npm ERR! code ENOSELF

npm ERR! Refusing to install npm as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     d:\npm-debug.log
```

I've linked the [npm-debug.log here](https://gist.github.com/CKarper/dd27c1fb40ba068849c6).

**Comment by othiym23** [comment]
Marking as a big bug because we don't want to leave npm in a state where it can't update itself for very long. This is one for @iarna's attention.

**Comment by iarna** [comment]
Hey you all, this landed in 3.3.5! You can work around it in the time being by passing `-f` to install, to tell npm to ignore the "error" that it found. (eg `npm i npm -g -f`)

**Comment by gdibble** [comment]
@iarna good tip, thanks :+1:

**Comment by JessicaR** [comment]
Thanks @iarna - really saved me some time!

**Comment by Sogl** [comment]
@iarna Many thanks! 
It works on Windows too.

**Comment by jorrit** [comment]
I guess this issue can be closed.

**Comment by colorgap** [comment]
@iarna -f worked. Thanks

**Comment by charlescarrari** [comment]
@iarna Thanks! :)

**Comment by ShepelE** [comment]
@iarna Thanks from me too! :)
this works also for  
sudo npm install express --save - npm WARN install Refusing to install express as a dependency of itself

**Comment by annliz** [comment]
@iarna thanks a lot ! it did the trick !

**Comment by kayGweb** [comment]
@larna This was a awesome tip thanks!!!!!!

**Comment by xgqfrms-GitHub** [comment]
npm i npm -g -f

# --force

**Comment by xgqfrms-GitHub** [comment]
**https://github.com/npm/npm/issues/14433**

# Error  
![npm install -g npm error](https://cloud.githubusercontent.com/assets/18028768/19745995/ebe12578-9c06-11e6-9068-db3e3f79ce9c.png)

# OK  
![npm i npm -g -f super power](https://cloud.githubusercontent.com/assets/18028768/19746013/014bfde8-9c07-11e6-952a-7f3ef166060a.png)

**Comment by husain1303** [comment]
@iarna thanks
