### ISSUE TITLE
Issue excuting npm commands npm ERR, npm colourModule.js

### ISSUE THREAD

**Issue by shashidharkj** [npm/npm#9697]
I have been trying to execute a sample javascript program.
I have installed npm 2.6.1.

While executing I am getting below error.
Could anyone please help me to sort this issue out. I tried clearing cache and then run the commands  but same error.

E:\JScript\node>npm colorModule.js

Usage: npm <command>

where <command> is one of:
    access, add-user, adduser, apihelp, author, bin, bugs, c,
    cache, completion, config, ddp, dedupe, deprecate, dist-tag,
    dist-tags, docs, edit, explore, faq, find, find-dupes, get,
    help, help-search, home, i, info, init, install, issues, la,
    link, list, ll, ln, login, logout, ls, outdated, owner,
    pack, prefix, prune, publish, r, rb, rebuild, remove, repo,
    restart, rm, root, run-script, s, se, search, set, show,
    shrinkwrap, star, stars, start, stop, t, tag, test, tst, un,
    uninstall, unlink, unpublish, unstar, up, update, v,
    verison, version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm faq          commonly asked questions
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    C:\Users\Shashidhar\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@2.6.1 E:\JScript\node\node_modules\npm

**Comment by CKarper** [comment]
You didn't give npm a command.

https://docs.npmjs.com/getting-started/installing-npm-packages-locally

**Comment by shashidharkj** [comment]
I have provided already but anyways here you go.
npm ERR
npm ColorModule.js

Note: I executed "npm install color". It worked and I can see color package created under node_modules.
E:\JScript\node>npm -v
2.6.1

E:\JScript\node>npm install colors
colors@1.1.2 node_modules\colors

I created colorModule.js javascript. To verify installed color package.

E:\JScript\node>npm cache clean

E:\JScript\node>npm colorModule.js

Usage: npm <command>

where <command> is one of:
    access, add-user, adduser, apihelp, author, bin, bugs, c,
    cache, completion, config, ddp, dedupe, deprecate, dist-tag,
    dist-tags, docs, edit, explore, faq, find, find-dupes, get,
    help, help-search, home, i, info, init, install, issues, la,
    link, list, ll, ln, login, logout, ls, outdated, owner,
    pack, prefix, prune, publish, r, rb, rebuild, remove, repo,
    restart, rm, root, run-script, s, se, search, set, show,
    shrinkwrap, star, stars, start, stop, t, tag, test, tst, un,
    uninstall, unlink, unpublish, unstar, up, update, v,
    verison, version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm faq          commonly asked questions
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    C:\Users\Shashidhar\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@2.6.1 E:\JScript\node\node_modules\npm

**Comment by CKarper** [comment]
Seriously, you're not getting it.

The syntax is ```npm <command> <packageName>```

```npm colorModule.js``` is giving colorModule.js as the command, which I'm sure is not what you mean.    Are you trying to run the colorModule.js?    You should try ```node colorModule.js```.

Maybe try [StackOverflow](http://stackoverflow.com/) in the future for general node.js support, rather than the issue list for npm.

I will not reply again in this thread.

**Comment by shashidharkj** [comment]
Ohh ..! Sorry to raise this as an issue..! Its node command I need to issue to run js wherein I was using npm...!
