### ISSUE TITLE
npm@3.3.4: "Invalid Version: 1.0.5beta"

### ISSUE THREAD

**Issue by indexzero** [npm/npm#9701]
This is a very strange bug. Lets start with the relevant parts of the `npm-debug.log`:

```
2643 verbose etag http://$REDACTED/handlebars from cache
2644 verbose get saving handlebars to /$REDACTED/.npm/$REDACTED/handlebars/.cache.json
2645 verbose stack TypeError: Invalid Version: 1.0.5beta
2645 verbose stack     at new SemVer (/$REDACTED/lib/node_modules/npm/node_modules/semver/semver.js:293:11)
2645 verbose stack     at SemVer.compare (/$REDACTED/lib/node_modules/npm/node_modules/semver/semver.js:346:13)
2645 verbose stack     at compare (/$REDACTED/lib/node_modules/npm/node_modules/semver/semver.js:570:31)
2645 verbose stack     at rcompare (/$REDACTED/lib/node_modules/npm/node_modules/semver/semver.js:580:10)
2645 verbose stack     at Array.sort (native)
2645 verbose stack     at pickVersionFromRegistryDocument (/$REDACTED/lib/node_modules/npm/lib/fetch-package-metadata.js:111:48)
2645 verbose stack     at /$REDACTED/lib/node_modules/npm/node_modules/iferr/index.js:13:50
2645 verbose stack     at /$REDACTED/lib/node_modules/npm/lib/utils/pulse-till-done.js:19:8
2645 verbose stack     at saved (/$REDACTED/lib/node_modules/npm/lib/cache/caching-client.js:168:7)
2645 verbose stack     at /$REDACTED/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:210:7
```

The really strange part of this is that version of `handlebars` is not being installed explicitly. I rolled back to `npm@2.14.5` and the install worked. At which point I ran:

```
my-redacted-thing@0.0.0 /path/to/my-redacted-thing
└─┬ istanbul@0.3.20
  └── handlebars@3.0.0 
``` 

If I had to guess my gut is that since the cache holds a document which represents all versions (not just the version requested – in this case `3.0.0`) then if there is logic somewhere that iterates over those versions and does a `semver.valid` naively ... :boom: ... this bug.

**Comment by indexzero** [comment]
_UPDATE:_ I did indeed narrow this down to being unable to install `handlebars` at all:

```
$ npm i handlebars@3.0.0
npm http request GET http://172.19.112.179:4873/handlebars
npm http 200 http://172.19.112.179:4873/handlebars
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/Users/crobbins/.local/bin/npm" "i" "handlebars@3.0.0"
npm ERR! node v0.12.7
npm ERR! npm  v3.3.3

npm ERR! Invalid Version: 1.0.5beta
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /$REDACTED/npm-debug.log
```

**Comment by indexzero** [comment]
@bengl helped me isolate this to those users running against an endpoint that is not `registry.npmjs.org`. This works:

```
$ npm i handlebars --reg=https://registry.npmjs.org
```

**Comment by indexzero** [comment]
Further spelunking has revealed that this is the expected behavior.

1. `npm` will now correct `semver` strings on publish (e.g. `1.6.5beta2` becomes `1.6.5-beta2`)
2. Old packages have been sanitized to reflect this (or are dynamically sanitized, see below)
3. Thus the `npm` CLI can make these strong assumptions about the contents of versions (i.e. that they are valid semver)

##### Closing remark on public registry

There may be dynamic sanitization being performed by the public npm registry, but I only have anecdotal evidence to support this. I fetched the raw JSON for handlebars for the public reg and our mirror. 

```
curl https://registry.npmjs.org/handlebars > handlebars.json
curl https://$OUR_MIRROR/handlebars > handlebars2.json
```

Then inspected the keys of the versions:

``` js
var h = require('./handlebars');
var h2 = require('./handlebars2');

Object.keys(h.versions)
/*
[ '1.0.6',
  '1.0.6-2',
  '1.0.7',
  '1.0.8',
  '1.0.9',
  '1.0.10',
  '1.0.11',
  '1.0.12',
  '1.1.0',
  '1.1.1',
  '1.1.2',
  '1.2.0',
  '1.2.1',
  '1.3.0',
  '2.0.0-alpha.1',
  '2.0.0-alpha.2',
  '2.0.0-alpha.3',
  '2.0.0-alpha.4',
  '2.0.0-beta.1',
  '2.0.0',
  '3.0.0',
  '3.0.1',
  '3.0.2',
  '3.0.3',
  '4.0.0',
  '4.0.1',
  '4.0.2',
  '1.0.2-beta',
  '1.0.4-beta',
  '1.0.5-beta' ]
*/

Object.keys(h2.versions);
/* 
[ '1.0.6',
  '1.0.6-2',
  '1.0.7',
  '1.0.8',
  '1.0.9',
  '1.0.10',
  '1.0.11',
  '1.0.12',
  '1.1.0',
  '1.1.1',
  '1.1.2',
  '1.2.0',
  '1.2.1',
  '1.3.0',
  '2.0.0-alpha.1',
  '2.0.0-alpha.2',
  '2.0.0-alpha.3',
  '2.0.0-alpha.4',
  '1.0.2-beta',
  '1.0.4-beta',
  '1.0.5-beta',
  '2.0.0-beta.1',
  '2.0.0',
  '3.0.0',
  '1.0.2beta',
  '1.0.4beta',
  '1.0.5beta',
  '3.0.1',
  '3.0.2',
  '3.0.3',
  '4.0.0',
  '4.0.1',
  '4.0.2' ]
*/
```

The ordering of keys in the public versions suggests they are dynamically rewritten _since they are at the end of the object and not in their previous location in the list._ Maybe someone will confirm, but otherwise I think mirror maintainers may need to be aware of.

**Comment by bengl** [comment]
For those running [`registry-static`](https://github.com/davglass/registry-static) and running into this: if you make sure to be on the most recent version of `registry-static` and sync the offending package, you should be good to go (after clearing caches, etc.).

**Comment by indexzero** [comment]
For those running `sinopia`, you can simply remove the package:

```
rm -rf ./path/to/storage/handlebars
```

It will resync the next time you install it.

**Comment by bengl** [comment]
Looks like this is the same as #9657

**Comment by geekytime** [comment]
> For those running sinopia, you can simply remove the package:
> rm -rf ./path/to/storage/handlebars
> It will resync the next time you install it.

Sinopia also supports unpublish. For example:

```
npm unpublish handlebars --force
```

This is helpful for those who don't have easy access to their Sinopia instance. I had about 5 offending dependencies when I tried to install eslint.

**Comment by justjake** [comment]
Here's a gist of a script that I wrote to list the bad packages on our Sinopia server at Airbnb: https://gist.github.com/justjake/f1ceeeaf30fee9fe23a4
