### ISSUE TITLE
npm 3.3.3: Maximum call stack exceeded on "npm publish"

### ISSUE THREAD

**Issue by indexzero** [npm/npm#9704]
Seen this on multiple modules I've tried to publish today since upgrading to `npm@3.3.3`. Here is a log from [`http-server`](https://github.com/indexzero/http-server): https://gist.github.com/indexzero/d60271242962159c51ab

I can work around this every time by doing:

```
rm -rf node_modules
npm publish
```

**Comment by othiym23** [comment]
Closing as duplicate of #9224.
