### ISSUE TITLE
npm start outputs missing script: start

### ISSUE THREAD

**Issue by theleancoder** [npm/npm#9706]
This is the package.json file.

```
{
  "name": "flapper-news",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "start": "node ./bin/www"
  },
  "dependencies": {
    "body-parser": "~1.13.2",
    "cookie-parser": "~1.3.5",
    "debug": "~2.2.0",
    "ejs": "~2.3.3",
    "express": "~4.13.1",
    "morgan": "~1.6.1",
    "serve-favicon": "~2.3.0"
  }
}
```

**Comment by theleancoder** [comment]
```
#!/usr/bin/env node

/**
 * Module dependencies.
 */

var app = require('../app');
var debug = require('debug')('flapper-news:server');
var http = require('http');

/**
 * Get port from environment and store in Express.
 */

var port = normalizePort(process.env.PORT || '3000');
app.set('port', port);

/**
 * Create HTTP server.
 */

var server = http.createServer(app);

/**
 * Listen on provided port, on all network interfaces.
 */

server.listen(port);
server.on('error', onError);
server.on('listening', onListening);

/**
 * Normalize a port into a number, string, or false.
 */

function normalizePort(val) {
  var port = parseInt(val, 10);

  if (isNaN(port)) {
    // named pipe
    return val;
  }

  if (port >= 0) {
    // port number
    return port;
  }

  return false;
}

/**
 * Event listener for HTTP server "error" event.
 */

function onError(error) {
  if (error.syscall !== 'listen') {
    throw error;
  }

  var bind = typeof port === 'string'
    ? 'Pipe ' + port
    : 'Port ' + port;

  // handle specific listen errors with friendly messages
  switch (error.code) {
    case 'EACCES':
      console.error(bind + ' requires elevated privileges');
      process.exit(1);
      break;
    case 'EADDRINUSE':
      console.error(bind + ' is already in use');
      process.exit(1);
      break;
    default:
      throw error;
  }
}

/**
 * Event listener for HTTP server "listening" event.
 */

function onListening() {
  var addr = server.address();
  var bind = typeof addr === 'string'
    ? 'pipe ' + addr
    : 'port ' + addr.port;
  debug('Listening on ' + bind);
}
```

**Comment by theleancoder** [comment]
This is the debug.log file.
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.3.4
3 info using node@v4.1.0
4 verbose config Skipping project config: C:\Users\ankit/.npmrc. (matches userconfig)
5 verbose stack Error: missing script: start
5 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:148:19)
5 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:58:5
5 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:345:5
5 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:309:45)
5 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:343:3)
5 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:113:5)
5 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:300:12
5 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:76:16
5 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
6 verbose cwd C:\Users\ankit
7 error Windows_NT 10.0.10240
8 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
9 error node v4.1.0
10 error npm  v3.3.4
11 error missing script: start
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@theleancoder 

```
6 verbose cwd C:\Users\ankit
```

Are you sure you are in the right directory? `npm` says you are in your home directory.

**Comment by theleancoder** [comment]
I was in a wrong directory. My bad. Thanks for your response.

**Comment by codingWhenever** [comment]
but what is right path? @KenanY

**Comment by KenanY** [comment]
@codingWhenever Any path with a `package.json` that defines a `"start"` script.

**Comment by ehsalazar** [comment]
@theleancoder It sounds like you got things figured out. I'll close this for now as we’re trying to clean up some solved issues. We’ll be happy to reopen if necessary.

**Comment by ravnan** [comment]
Hi guys,

i am new to node.js i am getting the error missing script. But, my package.json has the script syntax
following is the package.json file.

{
    "name": "rtc-over-ortc",
    "version": "0.0.0",
    "private": true,
    "main": "server.js",
    "dependencies": {
        "express": "~3.1.0"
    },
    "scripts": {
        "start": "node server.js"
    }
}

when i hit the command npm start i get the missing script error. Unable to figure out what is the error. Any help would be appreciated.

Thanks in advance.

**Comment by KenanY** [comment]
@ravnan Is there a `npm-debug.log` file you can upload to [gist.github.com](https://gist.github.com/)?

**Comment by imyejin** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

dufma555@naver.com 님께 보내신 메일 <Re: [npm] npm start outputs missing script: start (#9706)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by nick3499** [comment]
After uninstalling `start` then reinstalling using the string `npm i -S start` the command `npm start` gave me an error message. 
```
npm ERR! missing script: start
```
`package.json` contained script:
```
    "scripts": {
        "test": "budo index.js --live"
    },
```
`budo index.js --live` runs from command line
`start` module is in my `node_modules` directory

[npm-debug.txt](https://github.com/npm/npm/files/46682/npm-debug.txt)

**Comment by KenanY** [comment]
@nick3499 You do not have a `"start"` script defined in your `package.json` hence `npm` has no idea what you want to be done when you execute `npm start`. Why do you think the `start` package plays any role here? Have you read the documentation on [`npm start`](https://docs.npmjs.com/cli/start)?

**Comment by srirafa** [comment]
"test": "make test",
"start": "node index.js"

**Comment by srirafa** [comment]
Hi Kenan Y.Please help me

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'protractor' ]
2 info using npm@3.6.0
3 info using node@v5.6.0
4 verbose stack Error: missing script: protractor
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:147:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:57:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:345:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:309:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:343:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:113:5)
4 verbose stack     at ReadFileContext.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:284:20)
4 verbose stack     at ReadFileContext.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:76:16)
4 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:324:13)
5 verbose cwd E:\Sri\SDK6.16\CI_SDK_Win_x64\CI_AFW\CI_apps\html\Test
6 error Windows_NT 6.3.9600
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "protractor"
8 error node v5.6.0
9 error npm  v3.6.0
10 error missing script: protractor
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by srirafa** [comment]
I couldn't run npm.

**Comment by srirafa** [comment]
Attaching package.json. {
  "name": "package",
  "version": "1.0.0",
  "description": "rt",
  "main": "karma.conf.js",
  "scripts": {
    
	"test": "make test",
"start": "node index.js"
  },
  "repository": {
    "type": "git",
    "url": "rr"
  },
  "keywords": [
    "rr"
  ],
  "author": "rr",
  "license": "ISC",
  "devDependencies": {
    "jshint": "^2.9.2",
    "protractor": "^3.3.0"
  }
}


Whats the issue

**Comment by KenanY** [comment]
@srirafa You're missing a `"protractor"` script:

```
4 verbose stack Error: missing script: protractor
```

**Comment by srirafa** [comment]
Hi,


I've added the script.Now M getting different error.Please advise!


{
  "name": "package",
  "version": "1.0.0",
  "description": "rt",
  "main": "karma.conf.js",
  "scripts": {

 "test": "karma start test/karma.conf.js",
    "update-webdriver": "webdriver-manager update",
    "protractor": "protractor test/protractor.conf.js",
    "test-single-run": "karma start test/karma.conf.js",
  },
  "repository": {
    "type": "git",
    "url": "rr",
  },
  "keywords": [
    "rr"
  ],
  "author": "rr",
  "license": "ISC",
  "devDependencies": {
    "jshint": "^2.9.2",
    "protractor": "^3.3.0"
  }
}





Thanks and Regards,

Sriram

________________________________

**Comment by srirafa** [comment]
Hi,

Please ignore previous mail. This is the error I'm getting now.


0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'protractor' ]
2 info using npm@3.6.0
3 info using node@v5.6.0
4 verbose run-script [ 'preprotractor', 'protractor', 'postprotractor' ]
5 info lifecycle package@1.0.0~preprotractor: package@1.0.0
6 silly lifecycle package@1.0.0~preprotractor: no script for preprotractor, continuing
7 info lifecycle package@1.0.0~protractor: package@1.0.0
8 verbose lifecycle package@1.0.0~protractor: unsafe-perm in lifecycle true
9 verbose lifecycle package@1.0.0~protractor: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;E:\Sri\SDK6.16\CI_SDK_Win_x64\CI_AFW\CI_apps\html\Test\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\nodejs\
10 verbose lifecycle package@1.0.0~protractor: CWD: E:\Sri\SDK6.16\CI_SDK_Win_x64\CI_AFW\CI_apps\html\Test
11 silly lifecycle package@1.0.0~protractor: Args: [ '/d /s /c', 'protractor test/protractor.conf.js' ]
12 silly lifecycle package@1.0.0~protractor: Returned: code: 1  signal: null
13 info lifecycle package@1.0.0~protractor: Failed to exec protractor script
14 verbose stack Error: package@1.0.0 protractor: `protractor test/protractor.conf.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:827:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid package@1.0.0
16 verbose cwd E:\Sri\SDK6.16\CI_SDK_Win_x64\CI_AFW\CI_apps\html\Test
17 error Windows_NT 6.3.9600
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "protractor"
19 error node v5.6.0
20 error npm  v3.6.0
21 error code ELIFECYCLE
22 error package@1.0.0 protractor: `protractor test/protractor.conf.js`
22 error Exit status 1
23 error Failed at the package@1.0.0 protractor script 'protractor test/protractor.conf.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the package package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     protractor test/protractor.conf.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs package
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls package
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]




Thanks and Regards,

Sriram

________________________________

**Comment by srirafa** [comment]
Hi,

This is the error M getting now.

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'protractor' ]
2 info using npm@3.6.0
3 info using node@v5.6.0
4 verbose run-script [ 'preprotractor', 'protractor', 'postprotractor' ]
5 info lifecycle package@1.0.0~preprotractor: package@1.0.0
6 silly lifecycle package@1.0.0~preprotractor: no script for preprotractor, continuing
7 info lifecycle package@1.0.0~protractor: package@1.0.0
8 verbose lifecycle package@1.0.0~protractor: unsafe-perm in lifecycle true
9 verbose lifecycle package@1.0.0~protractor: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;E:\Sri\SDK6.16\CI_SDK_Win_x64\CI_AFW\CI_apps\html\Test\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\nodejs\
10 verbose lifecycle package@1.0.0~protractor: CWD: E:\Sri\SDK6.16\CI_SDK_Win_x64\CI_AFW\CI_apps\html\Test
11 silly lifecycle package@1.0.0~protractor: Args: [ '/d /s /c', 'protractor test/protractor.conf.js' ]
12 silly lifecycle package@1.0.0~protractor: Returned: code: 1  signal: null
13 info lifecycle package@1.0.0~protractor: Failed to exec protractor script
14 verbose stack Error: package@1.0.0 protractor: `protractor test/protractor.conf.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:827:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid package@1.0.0
16 verbose cwd E:\Sri\SDK6.16\CI_SDK_Win_x64\CI_AFW\CI_apps\html\Test
17 error Windows_NT 6.3.9600
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "protractor"
19 error node v5.6.0
20 error npm  v3.6.0
21 error code ELIFECYCLE
22 error package@1.0.0 protractor: `protractor test/protractor.conf.js`
22 error Exit status 1
23 error Failed at the package@1.0.0 protractor script 'protractor test/protractor.conf.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the package package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     protractor test/protractor.conf.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs package
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls package
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by srirafa** [comment]
Is there any problem with npm 3.6.0 & protractor 3.3.0? because this are the npm &protractor versions installed in my machine.


Thanks and Regards,

Sriram

________________________________

**Comment by hassanabas** [comment]
facing same issue.
`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.9
3 info using node@v6.9.2
4 verbose stack Error: missing script: start
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:320:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:354:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
4 verbose stack     at ReadFileContext.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:295:20)
4 verbose stack     at ReadFileContext.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16)
4 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:365:13)
5 verbose cwd C:\node
6 error Windows_NT 6.3.9600
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
8 error node v6.9.2
9 error npm  v3.10.9
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

`

**Comment by RemeAjayi** [comment]
Hello, here is my npm debug file, my app was working last week but its not anymore when i try to start it, please any help would be greatly appreciated.


0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'devstart' ]
2 info using npm@2.15.9
3 info using node@v4.6.0
4 verbose stack Error: missing script: devstart
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:142:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:58:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:320:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:354:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
4 verbose stack     at ReadFileContext.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:295:20)
4 verbose stack     at ReadFileContext.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16)
4 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)
5 verbose cwd C:\Users\Olohireme\WebstormProjects\obsessions-master
6 error Windows_NT 6.3.9600
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "devstart"
8 error node v4.6.0
9 error npm  v2.15.9
10 error missing script: devstart
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by sa6a8-github** [comment]
hey @KenanY please help me with this.missing script error. thank u.

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'migrate' ]
2 info using npm@5.8.0
3 info using node@v9.10.1
4 verbose stack Error: missing script: migrate
4 verbose stack     at run (/usr/lib/node_modules/npm/lib/run-script.js:151:19)
4 verbose stack     at /usr/lib/node_modules/npm/lib/run-script.js:61:5
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:115:5
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:418:5
4 verbose stack     at checkBinReferences_ (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:373:45)
4 verbose stack     at final (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:416:3)
4 verbose stack     at then (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:160:5)
4 verbose stack     at ReadFileContext.<anonymous> (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:332:20)
4 verbose stack     at ReadFileContext.callback (/usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16)
4 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:441:13)
5 verbose cwd /home/sarath/NodeProject/RestProject/current
6 verbose Linux 3.16.0-30-generic
7 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "migrate"
8 verbose node v9.10.1
9 verbose npm  v5.8.0
10 error missing script: migrate
11 verbose exit [ 1, true ]

**Comment by kenany** [comment]
@sa6a8-github Please open a new ticket.
