### ISSUE TITLE
failed to execute command of npm install -g cordova on windows platform

### ISSUE THREAD

**Issue by wubinbaoyi** [npm/npm#9710]

**Comment by KenanY** [comment]
@wubinbaoyi Not enough information to go on. Is there a `npm-debug.log` you can upload as a [gist](https://gist.github.com/)?

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.
