### ISSUE TITLE
npm@3.3.3: don't use absolute path for local folder dependencies

### ISSUE THREAD

**Issue by necolas** [npm/npm#9717]
npm 3 is writing an absolute path to the `package.json` when installing a local folder. i expected (and i believe this is the default behaviour with npm 2) the path to be the same relative path used in the install command.

```
npm install --save ../folder
```

expected (npm@2):

```
{
  "dependencies": {
    "local-package": "file:../folder"
  }
}
```

actual:

```
{
  "dependencies": {
    "local-package": "file:/<absolute-path>/folder"
  }
}
```

**Comment by azu** [comment]
Same problem.

I do following step with npm 3. 

```
npm i -S ../
vim pacakge.json
# manually rewrite path "file:.."
```

I don't want to do this :(

**Comment by schickling** [comment]
This was working in NPM2 :(

**Comment by gabrielfs7** [comment]
Hi!! Are there any news about this issue? Thanks

**Comment by briandipalma** [comment]
There is also the added issue of cross platform development where the paths aren't portable between Windows/Unixes. This is still an issue in npm 4.1.2.

**Comment by mysticatea** [comment]
I have encountered the same problem.

I have to rewrite the absolute path to relative paths manually because absolute paths cause installation problems to team members. It's inconvenient.

**Comment by legodude17** [comment]
This will be fixed in `npm@5` (currently in beta), I think.

**Comment by briandipalma** [comment]
Can confirm it's fixed in npm 5.

**Comment by iarna** [comment]
Fixed in npm@5 \o/

**Comment by Mairu** [comment]
Now it is not possible to use absolute paths anymore even when wanted :(
