### ISSUE TITLE
npm@3, flattened dependencies, and non-deterministic dependency locations

### ISSUE THREAD

**Issue by jesstelford** [npm/npm#9718]
I'm creating a package which wraps the `eslint` binary to add extra functionality. (Think how github's [`hub`](https://github.com/github/hub) tool wraps `git`).

In npm@2, this worked with a `process.spawn` like so:

```javascript
var argv = process.argv.slice(2);
// ...
child = process.spawn(
  path.join(__dirname, 'node_modules', '.bin', 'eslint'),
  argv,
  { cwd: process.cwd() }
);
```

However, in npm@3 the path `node_modules/.bin/eslint` is no longer deterministic.

----

Where this module's deps would previously (npm@2) be put into a deterministic location like so:

```
node_modules/this-module/node_modules/eslint
```

And if something else depended upon `eslint`, we'd end up with another deterministic location:

```
node_modules/this-module/node_modules/eslint
node_modules/something-else/node_modules/eslint
```

But now (npm@3), depending on the flattening algorithm, and other dependency's versions, etc, we could end up with different path structures:

```
node_modules/this-module
node_modules/something-else
node_modules/eslint
```

Is there a way for me to programmatically get the path to a dependency so I can use its binary file?

**Comment by bengl** [comment]
I've been using things like `require.resolve('.bin/eslint')` with some success.

**Comment by jesstelford** [comment]
@bengl Awesome, that's working great so far!

What about when there are multiple versions?

```
node_modules/this-module/node_modules/eslint@1.2.3
node_modules/something-else
node_modules/eslint@1.1.0
```

Which version does it pick?

**Comment by bengl** [comment]
As I understand, it's whichever one it finds first via the [module resolution algorithm](https://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders).

**Comment by ehsalazar** [comment]
@jesstelford It sounds like your on the right path now. I'll close this for now as we’re trying to clean up some solved issues. We’ll be happy to reopen if necessary.

**Comment by jesstelford** [comment]
Here's some background info on non-determinism: ["npm3 Non-determinism"](https://docs.npmjs.com/how-npm-works/npm3-nondet)
