### ISSUE TITLE
--literally flag.

### ISSUE THREAD

**Issue by dominictarr** [npm/npm#9721]
when a command is invoked with the --literally flag enabled (may also be configured in your local npm configuration) then all commands will be taken literally and performed exactly as you asked them, without npm trying to guess what you meant or do you any special favors.

for example, `npm install --literally` would install dependencies, but not run the prepublish script.

**Comment by dominictarr** [comment]
this would resolve the long standing issues
 
https://github.com/npm/npm/issues/3059
https://github.com/npm/npm/issues/9590
etc

**Comment by danmactough** [comment]
I `npm install --ignore-scripts` does what you want, here.

**Comment by dominictarr** [comment]
I don't want to ignore all scripts, just ignore the scripts that i didn't literally ask for. so literally should still run preinstall postinstall etc

**Comment by danmactough** [comment]
Fair point

**Comment by sindresorhus** [comment]
:+1: Alternative name: `--fix-all-the-things`.

**Comment by dominictarr** [comment]
--literally would also make npm use only `.npmignore` and not look in `.gitignore`
