### ISSUE TITLE
Errors installing npm

### ISSUE THREAD

**Issue by fmoraless** [npm/npm#9724]
I've som errors during install npm
This is part of my terminal, thanks

Frantic@fmorales MINGW64 /c/xampp/htdocs/platzilaravel (master)
$ npm install
npm WARN optional dep failed, continuing fsevents@0.3.8
npm WARN optional dep failed, continuing fsevents@0.3.8

> spawn-sync@1.0.13 postinstall C:\xampp\htdocs\platzilaravel\node_modules\larav                                                                                                                el-elixir\node_modules\gulp-sass\node_modules\node-sass\node_modules\cross-spawn                                                                                                                \node_modules\spawn-sync
> node postinstall

> node-sass@3.3.3 install C:\xampp\htdocs\platzilaravel\node_modules\laravel-eli                                                                                                                xir\node_modules\gulp-sass\node_modules\node-sass
> node scripts/install.js

Binary downloaded and installed at C:\xampp\htdocs\platzilaravel\node_modules\la                                                                                                                ravel-elixir\node_modules\gulp-sass\node_modules\node-sass\vendor\win32-ia32-14\                                                                                                                binding.node

> node-sass@3.3.3 postinstall C:\xampp\htdocs\platzilaravel\node_modules\laravel                                                                                                                -elixir\node_modules\gulp-sass\node_modules\node-sass
> node scripts/build.js

` C:\xampp\htdocs\platzilaravel\node_modules\laravel-elixir\node_modules\gulp-sa                                                                                                                ss\node_modules\node-sass\vendor\win32-ia32-14\binding.node ` exists.
 testing binary.
Binary is fine; exiting.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x8                                                                                                                6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! shasum check failed for C:\Users\Frantic\AppData\Local\Temp\npm-24120-0                                                                                                                6b2e6bf\registry.npmjs.org\node-notifier\-\node-notifier-4.3.1.tgz
npm ERR! Expected: 94a3e35c388938b4d9fa196fed6b36e9ab671119
npm ERR! Actual:   dfba055745144b2c2e69884e442605e719f65706
npm ERR! From:     https://registry.npmjs.org/node-notifier/-/node-notifier-4.3.                                                                                                                1.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\xampp\htdocs\platzilaravel\npm-debug.log

**Comment by KenanY** [comment]
@fmoraless Does `npm cache clean` help?

**Comment by snopeks** [comment]
hi @fmoraless were you able to resolve the issue? We haven't heard back and we're trying to clean up some issues. If this is still a problem, can you please reply and let us know? We'll be happy to reopen if necessary.
