### ISSUE TITLE
npm@3: npm shrinkwrap includes devDependencies by default

### ISSUE THREAD

**Issue by vvo** [npm/npm#9727]
Hi, it seems `npm shrinkwrap` in npm3 includes devDependencies by default, is this the correct behavior?

package.json
```json
{
  "name": "shrinkwrap3",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "babel": "^5.8.23"
  },
  "dependencies": {
    "lodash": "^3.10.1"
  }
}
```

```sh
npm install

npm shrinkwrap
# npm WARN shrinkwrap Excluding devDependency: babel { lodash: '^3.10.1' }
#wrote npm-shrinkwrap.json

cat npm-shrinkwrap.json
#{
#  "name": "shrinkwrap3",
#  "version": "1.0.0",
#  "dependencies": {
#    "alter": {
#      "version": "0.2.0",
#      "from": "alter@>=0.2.0 <0.3.0",
#      "resolved": "https://registry.npmjs.org/alter/-/alter-0.2.0.tgz"
#    },
#    "amdefine": {
#      "version": "1.0.0",
#      "from": "amdefine@>=0.0.4",
#      "resolved": "https://registry.npmjs.org/amdefine/-/amdefine-1.0.0.tgz"
#    },
#    "ansi-green": {
#      "version": "0.1.1",
#      "from": "ansi-green@>=0.1.1 <0.2.0",
#      "resolved": "https://registry.npmjs.org/ansi-green/-/ansi-green-0.1.1.tgz"
#    },
#    "ansi-regex": {
#      "version": "2.0.0",
#      "from": "ansi-regex@>=2.0.0 <3.0.0",
#      "resolved": "https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.0.0.tgz"
#    },
#    "ansi-styles": {
#      "version": "2.1.0",
#      "from": "ansi-styles@>=2.1.0 <3.0.0",
#      "resolved": "https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.1.0.tgz"
#    },
#    "ansi-wrap": {
#      "version": "0.1.0",
#      "from": "ansi-wrap@0.1.0",
#      "resolved": "https://registry.npmjs.org/ansi-wrap/-/ansi-wrap-0.1.0.tgz"
#    },
#    "anymatch": {
#      "version": "1.3.0",
#      "from": "anymatch@>=1.1.0 <2.0.0",
#      "resolved": "https://registry.npmjs.org/anymatch/-/anymatch-1.3.0.tgz"
#    },
#    "arr-diff": {
#      "version": "1.1.0",
#      "from": "arr-diff@>=1.0.1 <2.0.0",
#      "resolved": "https://registry.npmjs.org/arr-diff/-/arr-diff-1.1.0.tgz"
#    },
#    "arr-flatten": {
#      "version": "1.0.1",
#      "from": "arr-flatten@>=1.0.1 <2.0.0",
#      "resolved": "https://registry.npmjs.org/arr-flatten/-/arr-flatten-1.0.1.tgz"
#    },
#    "array-slice": {
#      "version": "0.2.3",
#      "from": "array-slice@>=0.2.3 <0.3.0",
#      "resolved": "https://registry.npmjs.org/array-slice/-/array-slice-0.2.3.tgz"
#    },
#    "array-unique": {
#      "version": "0.2.1",
#      "from": "array-unique@>=0.2.1 <0.3.0",
#      "resolved": "https://registry.npmjs.org/array-unique/-/array-unique-0.2.1.tgz"
#    },
#    "arrify": {
#      "version": "1.0.0",
#      "from": "arrify@>=1.0.0 <2.0.0",
#      "resolved": "https://registry.npmjs.org/arrify/-/arrify-1.0.0.tgz"
#    }
# and on and on and on
# ^^^ "BAD"?
```

It seems to say "excluding dev.." while then it reads the node_modules and shrinkwrap all that it's inside.

```sh
rm -rf node_modules
npm install --production
npm shrinkwrap
cat npm-shrinkwrap.json
# {
#   "name": "shrinkwrap3",
#   "version": "1.0.0",
#   "dependencies": {
#     "lodash": {
#       "version": "3.10.1",
#       "from": "lodash@>=3.10.1 <4.0.0",
#       "resolved": "https://registry.npmjs.org/lodash/-/lodash-3.10.1.tgz"
#     }
#   }
# }
# ^^^ GOOD
```

Any hint?

**Comment by terinjokes** [comment]
I'm attempting to work on a patch to resolve this.

**Comment by terinjokes** [comment]
I have a commit on my fork that seems to resolve the shrinkwrap issue, but I haven't (yet) explicitly tested all the edges.

**Comment by vvo** [comment]
Awesome, I was not confident in submiting a fix, you tried! let's see what the npm team think

**Comment by terinjokes** [comment]
@vvo not submitted as a PR yet, because I want to add some tests around it :) Do let me if it does or doesn't work for you though.

**Comment by Maxwell2022** [comment]
+1 waiting for this fix

**Comment by egoist** [comment]
Any news there? I just cannot resist that `npmshrink.json` is over 100kb... 😶

**Comment by vincentwoo** [comment]
This seems like a pretty critical issue for doing reliable production deploys with npm.

**Comment by martynchamberlin** [comment]
This is a serious pain point for us. Packages that are dependencies of a `devDependencies` package get included in `npm-shrinkwrap.json`. Combined with [this bug](https://www.bountysource.com/issues/974580-npm-install-production-should-ignore-devdependencies-in-the-shrinkwrap-file): 

> Currently `npm install --production` blindly uses the shrinkwrap file and installs everything listed in it. 

the end result is that when we deploy, we're installing packages that are dependencies of `devDependencies`. 

Would love to see this bug fixed...

**Comment by valscion** [comment]
I think this might have been fixed by https://github.com/npm/npm/pull/10073 but this issue just didn't get closed, due to there being a bit of back-and-forth with the original PR https://github.com/npm/npm/pull/10265 that was closed in favor of #10073

I assume there are quite a few duplicates of this same issue. Can I help vet these together somehow?

**Comment by vvo** [comment]
if the reproduction sample I gave in the description now leads to the correct shrinkwrap behavior then this can be closed, @valscion you can try it, let me know

**Comment by valscion** [comment]
@vvo I was not able to reproduce. See my steps from the commit log of https://github.com/valscion/npm-9727-repro

**Comment by vvo** [comment]
Nice, thanks!

**Comment by iarna** [comment]
Oh nice, good catch! =)
