### ISSUE TITLE
Problem installing lessc Compiler

### ISSUE THREAD

**Issue by chrisrandy** [npm/npm#9728]
Hi, 

every time I try to install a lessc compiler with the command "npm install less -g" I get the following error...
If somebody could help me would be nice!

Here ist the Error-Log: 

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'less',
1 verbose cli   '-g' ]
2 info using npm@2.14.4
3 info using node@v4.1.1
4 verbose install initial load of C:\Users\Administrator\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\Administrator\AppData\Roaming\npm\package.json
6 silly cache add args [ 'less', null ]
7 verbose cache add spec less
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'less',
8 silly cache add   scope: null,
8 silly cache add   name: 'less',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed less@*
10 verbose addNamed "*" is a valid semver range for less
11 silly addNameRange { name: 'less', range: '*', hasData: false }
12 silly mapToRegistry name less
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/less
16 verbose addNameRange registry:https://registry.npmjs.org/less not in flight; fetching
17 verbose request uri https://registry.npmjs.org/less
18 verbose request no auth needed
19 info attempt registry request try #1 at 10:55:26
20 verbose request id a1505770c52ac1ac
21 http request GET https://registry.npmjs.org/less
22 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
23 info attempt registry request try #2 at 10:55:46
24 http request GET https://registry.npmjs.org/less
25 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
26 info attempt registry request try #3 at 10:56:56
27 http request GET https://registry.npmjs.org/less
28 verbose stack Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
28 verbose stack     at Object.exports._errnoException (util.js:837:11)
28 verbose stack     at errnoException (dns.js:30:15)
28 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
29 verbose cwd C:\Users\Administrator
30 error Windows_NT 6.1.7601
31 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "less" "-g"
32 error node v4.1.1
33 error npm  v2.14.4
34 error code EAI_AGAIN
35 error errno EAI_AGAIN

**Comment by abacon** [comment]
This looks like it is probably a duplicate #7348, and is the result of a transient network issue. @chrisrandy, are you still experiencing the problem?

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some issues. This does appear to be similar to #7348. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.
