### ISSUE TITLE
npm@1/node@8: TypeError: Cannot read property 'latest' of undefined

### ISSUE THREAD

**Issue by robcolburn** [npm/npm#9734]
Should anyone else encounter this error.

```
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/Users/robertcolburn/.nvm/v0.8.28/lib/node_modules/npm/lib/cache.js:690:35)
npm ERR!     at /Users/robertcolburn/.nvm/v0.8.28/lib/node_modules/npm/lib/cache.js:678:5
npm ERR!     at saved (/Users/robertcolburn/.nvm/v0.8.28/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:302:15)
```

Check your log for any HTTP 401's from npm.  For me, I needed to disable my `~/.npmrc` which had my npm publishing token, as per ( https://github.com/npm/npm/issues/2778 ).  If work on npm@1 continues at all, it would be nice to have a relevant error message, rather what looks like a code error.  C'est la vie

**Comment by ehsalazar** [comment]
@robcolburn Thanks for submitting this issue. I'd suggest moving to `npm@3` or `npm@2`. Work on `npm@1` is limited as it's now deprecated.
