### ISSUE TITLE
Try to install Ternjs on Atom Error

### ISSUE THREAD

**Issue by Freestyler100** [npm/npm#9736]
Try to install https://atom.io/packages/atom-ternjs

Needed are Nodejs and Git: installed and set to path

But error occurred:

Installing “atom-ternjs@0.7.2” failed.Hide output…

npm WARN addRemoteGit Error: Command failed: 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:658:15)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:98:17)
npm WARN addRemoteGit     at maybeClose (child_process.js:766:16)
npm WARN addRemoteGit     at Socket.<anonymous> (child_process.js:979:11)
npm WARN addRemoteGit     at Socket.emit (events.js:95:17)
npm WARN addRemoteGit     at Pipe.close (net.js:466:12)
npm WARN addRemoteGit  git+https://github.com/angelozerr/tern-lint.git resetting remote C:\Users\Niklas.atom.apm_git-remotes\https-github-com-angelozerr-tern-lint-git-0f1c926e because of error: { [Error: Command failed: ] killed: false, code: 1, signal: null }
npm WARN addRemoteGit Error: Command failed: 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:658:15)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:98:17)
npm WARN addRemoteGit     at maybeClose (child_process.js:766:16)
npm WARN addRemoteGit     at Socket.<anonymous> (child_process.js:979:11)
npm WARN addRemoteGit     at Socket.emit (events.js:95:17)
npm WARN addRemoteGit     at Pipe.close (net.js:466:12)
npm WARN addRemoteGit  git+https://github.com/marijnh/tern.git resetting remote C:\Users\Niklas.atom.apm_git-remotes\https-github-com-marijnh-tern-git-6d289200 because of error: { [Error: Command failed: ] killed: false, code: 1, signal: null }
npm ERR! git clone --template=C:\Users\Niklas.atom.apm_git-remotes_templates --mirror https://github.com/angelozerr/tern-lint.git C:\Users\Niklas.atom.apm_git-remotes\https-github-com-angelozerr-tern-lint-git-0f1c926e: Cloning into bare repository 'C:\Users\Niklas.atom.apm_git-remotes\https-github-com-angelozerr-tern-lint-git-0f1c926e'...
npm ERR! git clone --template=C:\Users\Niklas.atom.apm_git-remotes_templates --mirror https://github.com/angelozerr/tern-lint.git C:\Users\Niklas.atom.apm_git-remotes\https-github-com-angelozerr-tern-lint-git-0f1c926e: fatal: Unable to find remote helper for 'https'
npm ERR! git clone --template=C:\Users\Niklas.atom.apm_git-remotes_templates --mirror https://github.com/marijnh/tern.git C:\Users\Niklas.atom.apm_git-remotes\https-github-com-marijnh-tern-git-6d289200: Cloning into bare repository 'C:\Users\Niklas.atom.apm_git-remotes\https-github-com-marijnh-tern-git-6d289200'...
npm ERR! git clone --template=C:\Users\Niklas.atom.apm_git-remotes_templates --mirror https://github.com/marijnh/tern.git C:\Users\Niklas.atom.apm_git-remotes\https-github-com-marijnh-tern-git-6d289200: fatal: Unable to find remote helper for 'https'
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\Users\Niklas\AppData\Local\atom\app-1.0.11\resources\app\apm\bin\node.exe" "C:\Users\Niklas\AppData\Local\atom\app-1.0.11\resources\app\apm\node_modules\npm\bin\npm-cli.js" "--globalconfig" "C:\Users\Niklas\.atom\.apm\.apmrc" "--userconfig" "C:\Users\Niklas\.atom\.apmrc" "install" "C:\Users\Niklas\AppData\Local\Temp\d-115823-9504-bu2r2d\package.tgz" "--target=0.22.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 128

npm ERR! Command failed: Cloning into bare repository 'C:\Users\Niklas.atom.apm_git-remotes\https-github-com-angelozerr-tern-lint-git-0f1c926e'...
npm ERR! fatal: Unable to find remote helper for 'https'
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

Please help :)

**Comment by mhart** [comment]
You might be running into this issue: https://github.com/npm/npm/issues/13353
