### ISSUE TITLE
Npm can't update local packages

### ISSUE THREAD

**Issue by Vietworm** [npm/npm#9737]
I update new version the packages on my project but I can't get any changes to code before. I did run npm update in the same directory as your package.json file. But not working, I'm using windows 8.1 and npm v2.13.3
I hope, have someone support my issue.

Thanks & Best regards, 

![npm](https://cloud.githubusercontent.com/assets/7351351/10049570/50b71fca-6242-11e5-8632-b5b9330514e9.png)

**Comment by KenanY** [comment]
@Vietworm Did you update the SemVer ranges in your `package.json`?

**Comment by Vietworm** [comment]
@KenanY, that is idea. But i think `npm update` will automatically do it.
I use `npm install <package>@<version> --save` to upgrade packages version. It work, but i don't like this.

**Comment by KenanY** [comment]
@Vietworm Yeah, `npm update` won't install versions not accepted by what you defined in your `package.json`.
