### ISSUE TITLE
npm-shrinkwrap silently prevents a package from package.json dependencies from installing

### ISSUE THREAD

**Issue by d4goxn** [npm/npm#9738]
I am trying to lock the buffer module to an older version, to work around [buffer #79](https://github.com/feross/buffer/issues/79) (upgrading to node 4.1.1 had no effect). In order to do that, I have created the following npm-shrinkwrap.json:

    {
      "dependencies": {
        "buffer": {
          "version": "3.0.3",
          "from": "buffer@3.0.3",
          "resolved": "https://registry.npmjs.org/buffer/-/buffer-3.0.3.tgz"
        }
      }
    }

However, this prevents `npm install` from installing one of the dependencies from package.json (Joi):

    {
      "dependencies": {
        "babel-runtime": "^5.8.24",
        "joi": "^6.7.1"
      },
      "devDependencies": {
        "babel": "^5.8.20",
        "babel-loader": "^5.3.2"
      }
    }

There are no errors during npm install, but node_modules/joi is missing, and the other modules  are present. If I manually `npm install joi`, it actually is installed.  

This was not an issue when I had a full shrinkwrap file generated by `npm shrinkwrap`, but I do not want to lock the versions of all of my dependencies, just this one package that is causing problems.

How are we supposed to shrinkwrap just one package?

**Comment by KenanY** [comment]
@d4goxn Can't you just put `buffer@3.0.3` in your `package.json`?

``` json
{
  "dependencies": {
    "babel-runtime": "^5.8.24",
    "buffer": "3.0.3",
    "joi": "^6.7.1"
  },
  "devDependencies": {
    "babel": "^5.8.20",
    "babel-loader": "^5.3.2"
  }
}
```

**Comment by d4goxn** [comment]
Setting a hard version in package.json should have worked, but for me, I was still getting buffer 3.5.0 as a dependency of webpack -> node-libs-browser. In the end, I had to resort to forking node-libs-browser and setting the Buffer version there.

I'll keep my repro of the "package doesn't install or throw an error" issue in a branch in case anyone else who hits it wants to compare repros. For now though, since I am no longer troubleshooting this issue, I am closing it.

**Comment by KenanY** [comment]
@d4goxn Oh, you wanted to lock down the `buffer` version of a specific module... hmm yeah usually I just fork.
