### ISSUE TITLE
Make package changelogs easier to find by supporting them in package.json

### ISSUE THREAD

**Issue by JedWatson** [npm/npm#9740]
When you're trying to figure out what's changed in a package, there's almost no consistency about where to look. Options include:
- `CHANGELOG.md` (or variants) in the code / repo
- GitHub Releases page
- Commit History
- Project Website / Blogs
- TryItAndSeeWhatBreaks

It can be a real time sink, and [despite some efforts](http://keepachangelog.com) if no standard has emerged by now I doubt one will.

npm seems uniquely positioned to be able to solve this problem in an unopinionated way :)

Supporting a `changelog` property in `package.json` would give the community a standard way to point to wherever the changelog is, however the authors choose to publish it.

It would open up opportunities for tools like `npm outdated` and [npm-check-updates](https://www.npmjs.com/package/npm-check-updates) to link to the info you need right from the command line.

And since npmjs.com has become the nicest place to find package docs (you can open a package's read & links without knowing where the repo or homepage is), it would be great to include a link to the project changelog with the other handy links (repo / homepage / open issues, etc).

**Comment by donaldpipowitch** [comment]
Sounds good. +1

**Comment by schmod** [comment]
This would be a good improvement.
