### ISSUE TITLE
onesignal-cordova-plugin-pgb-compat not defaulting to latest

### ISSUE THREAD

**Issue by jkasten2** [npm/npm#9745]
I am the plugin owner of the npmjs package `onesignal-cordova-plugin-pgb-compat` and it's stuck in a state where install commands do not default to `@latest`.

Here is the output I get without and with `@latest`
###### npm install:
`None:`
```cmd
npm install onesignal-cordova-plugin-pgb-compat
└── onesignal-cordova-plugin-pgb-compat@1.7.6
```
`@lastest`
```cmd
npm install onesignal-cordova-plugin-pgb-compat@latest
└── onesignal-cordova-plugin-pgb-compat@1.9.4-pgb-compat
```
<br>
###### cordova plugin add:
*(new project) config.xml is default.*
`None:`
```cmd
cordova plugin -verbose add onesignal-cordova-plugin-pgb-compat
no version specified, retrieving version from config.xml
Calling plugman.fetch on plugin "onesignal-cordova-plugin-pgb-compat"
Fetching plugin "onesignal-cordova-plugin-pgb-compat" via npm
Copying plugin "C:\Users\Josh\AppData\Roaming\npm-cache\onesignal-cordova-plugin-pgb-compat\1.7.6\package" =>
 "C:\OneSignal-Compat-Test\plugins\com.onesignal.plugins.onesignalpgbcompat"
```
```cmd
cordova plugin -verbose add onesignal-cordova-plugin-pgb-compat@latest
Calling plugman.fetch on plugin "onesignal-cordova-plugin-pgb-compat@latest"
Fetching plugin "onesignal-cordova-plugin-pgb-compat@latest" via npm
Copying plugin "C:\Users\Josh\AppData\Roaming\npm-cache\onesignal-cordova-plugin-pgb-compat\1.9.4-pgb-compat\package" =>
 "C:\OneSignal-Compat-Test\plugins\onesignal-cordova-plugin-pgb-compat"
```

Running npm dist-tag list shows the correct version:
```cmd
npm dist-tag list onesignal-cordova-plugin-pgb-compat
latest: 1.9.4-pgb-compat
```
As well as https://www.npmjs.com/package/onesignal-cordova-plugin-pgb-compat is reporting 1.9.4-pgb-compat as the latest.

I tried pushing a few new updates with `npm publish` but it didn't fix my issue. My other plugin `onesignal-cordova-plugin` works fine and when an update is pushed install commands use the latest without having to include `@latest`.

Any idea why leaving `@latest` off commands isn't using the latest and is stuck on my old 1.7.6 version?

I already tried updating to the latest npm, node, cordova. node v4.1.1, npm at 3.3.3, and cordova 5.3.1. I also tried running `npm cache clean` before these commands.

Thanks.

**Comment by KenanY** [comment]
@jkasten2 I believe this is because `npm@>2` does not install pre-release versions like `1.9.4-pgb-compat` unless you explicitly ask for one.

**Comment by jkasten2** [comment]
@KenanY Thanks for the information! Didn't realize anything with a dash '-' after the version was being considered as pre-release by npm. I was trying to use it for clarity but the different repo name is probably clear enough.

The reason there is 2 branches of the plugin is to work around the whole ANT dependency issue. Its still a big headache for PhoneGap Build(PGB) and any plugins that haven't been updated to use gradle references to "Google Play services" and the "Android Support Library".

Thanks.
