### ISSUE TITLE
npm start issue on windows

### ISSUE THREAD

**Issue by vivekdhiman** [npm/npm#9746]
Hi npm start giving me the error message, i just installed the node.js.

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose stack Error: ENOENT, open 'C:\Users\vivekdhiman\Desktop\package.json'
5 verbose stack     at Error (native)
6 verbose cwd C:\Users\vivekdhiman\Desktop
7 error Windows_NT 6.1.7601
8 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
9 error node v0.12.0
10 error npm  v2.5.1
11 error path C:\Users\vivekdhiman\Desktop\package.json
12 error code ENOENT
13 error errno -4058
14 error enoent ENOENT, open 'C:\Users\vivekdhiman\Desktop\package.json'
14 error enoent This is most likely not a problem with npm itself
14 error enoent and is related to npm not being able to find a file.
15 verbose exit [ -4058, true ]

**Comment by KenanY** [comment]
@vivekdhiman Does `C:\Users\vivekdhiman\Desktop\package.json` exist?

**Comment by vivekdhiman** [comment]
Yes, Issue got resolved.
