### ISSUE TITLE
Feature request: non-interactive npm login/deployment keys

### ISSUE THREAD

**Issue by adamkdean** [npm/npm#9747]
We have recently signed up for private npm modules. We need to use these in our containers, which means logging in within our Dockerfiles. Unfortunately, npm login requires an interactive shell and quite frankly I think this stinks.

I'd very much like to be able to login by providing the details on the command line, for example:

```
npm login -u $NPM_USER -p $NPM_PASS -e $NPM_EMAIL
```

or maybe using an API key?

```
npm login -u $NPM_USER -a $API_KEY
```

The fact that I'm now going to have to generate the auth token and inject a pre-baked .npmrc file means that I'm duplicating functionality which may change in the future (as it did recently). 

Can we get a more intuitive CLI for npm please, something that feels like it belongs in 2015?

If this isn't something you think aligns with npm, can you say provide why not?

**Comment by adamkdean** [comment]
For anyone who finds this who needs a solution, I put together a quick docker image which can authenticate on the command line.

    docker run \
        -e NPM_USER=$NPM_USER \
        -e NPM_PASS=$NPM_PASS \
        -e NPM_EMAIL=$NPM_EMAIL \
        bravissimolabs/generate-npm-authtoken \
        > ~/.npmrc

https://github.com/bravissimolabs/docker-generate-npm-authtoken

**Comment by FrankZZ** [comment]
+1

**Comment by RolfKoenders** [comment]
+1

**Comment by Jackyjjc** [comment]
+1

**Comment by tkambler** [comment]
Or you could just call the following shell script:

```
#!/usr/bin/env bash

USERNAME=$1
PASSWORD=$2
EMAIL=$3

/usr/bin/expect <<EOF
set timeout 10
spawn npm login
match_max 100000

expect "Username"
send "$USERNAME\r"

expect "Password"
send "$PASSWORD\r"

expect "Email"
send "$EMAIL\r"

expect {
   timeout      exit 1
   expect eof
}
EOF
```

```
$ login-npm {user} {pass} {email}
```

---

- Requires `expect` - `$ apt-get install -y expect`

**Comment by adamkdean** [comment]
@tkambler aye, that will work fine when you're running in a script. Unfortunately it won't work inside a Dockerfile, that's why I had to create the above Docker image (though I no longer maintain it).

It would be a lot easier though if npm simply supported `npm login -u $NPM_USER -p $NPM_PASS -e $NPM_EMAIL` :shrug:

**Comment by tkambler** [comment]
@adamkdean I'm using it in a Dockerfile.

```
COPY ./login-npm /tmp/login-npm
RUN chmod +x /tmp/login-npm
RUN /tmp/login-npm {username} {password} {email}
```

I agree, native non-interactive login would be ideal.

**Comment by adamkdean** [comment]
Seems a little bit dirty though because you'd also have to use `RUN apt-get install -y expect` on that same image, which personally just feels wrong. Perhaps a better solution would be to put the script + expect into a base image. Thanks for the script though, definitely more lightweight than my approach, though I'm guessing they're quite similar under the hood, I guess it's a question of how you wish to apply it.

But alas, native non-interactive login _would_ be ideal.

cc @isaacs *ahem*

**Comment by noahehall** [comment]
I was able to create a user separately and export the auth token as an environ var following these instructions

http://blog.npmjs.org/post/118393368555/deploying-with-npm-private-modules

**Comment by jrharshath** [comment]
Can auth tokens expire after a fixed period of time? (say, 10 minutes, or 1 day)? In case someone "npm login"s but forgets to "npm logout"?

**Comment by adamkdean** [comment]
@jrharshath they don't expire but they aren't guaranteed to not expire

**Comment by adamkdean** [comment]
@noahehall yes, because if the auth token gets revoked, it could break your pipeline

**Comment by jononu** [comment]
This should be re-opened.

**Comment by eschwartz** [comment]
Yes, please re-open this issue.

> I was able to create a user separately and export the auth token as an environ var following these instructions

I saw that this is the method recommended by npm.

Here's why I'm concerned about this:
- There is no way for me to associate a token with application running the CI build. Which means I cannot safely delete old tokens, without worrying about breaking existing pipelines.
- If I want to change my npm password, it will wipe all existing tokens. Without knowing which token is associated with which CI user, this is a very scary thing to do.

Alternatively, if we could associate a CI user with every build (eg, with a `name` or `description` field), all this would be less of a headache.

**Comment by adamkdean** [comment]
I haven't used private npm packages since 2015/16, but it's amazing that this is still an issue. It should be such a simple thing to achieve, and yet it's completely ignored. Ridiculous.

**Comment by eschwartz** [comment]
Looks like you can do this by curling the API

```
curl -u [USERNAME]:[PASSWORD] https://registry.npmjs.org/-/npm/v1/tokens \
  -X POST -H 'content-type: application/json' \
  -d '{"password":"[PASSWORD]", "readonly": "true"}'
```
