### ISSUE TITLE
sometimes can't install some modules with npm@3 

### ISSUE THREAD

**Issue by TsumiNa** [npm/npm#9750]
I'm in japan, from this week, I can't use npm to install some modules at night. such as `typescript`, `react`, `materialize-css`, `browser-sync` etc. At day time it's worked. Here is a sample of install `materialize-css`.

![speed](https://cloud.githubusercontent.com/assets/6410921/10082895/f02700f8-6336-11e5-8874-2fd57ad76d57.png)

![node](https://cloud.githubusercontent.com/assets/6410921/10082981/4f1b628e-6337-11e5-9d37-8ac48cea07d0.png)

![npm](https://cloud.githubusercontent.com/assets/6410921/10082993/5ae034fa-6337-11e5-99e1-141ceb4e595d.png)

there is the gist
https://gist.github.com/TsumiNa/cdd6c5c2b244a69ee805#file-install_output-txt

**Comment by TsumiNa** [comment]
![browser-sync](https://cloud.githubusercontent.com/assets/6410921/10083250/94ad7bc4-6338-11e5-8d7d-a7531319097c.png)

this is install `browser-sync`. there is the log in `--verbose`.
https://gist.github.com/TsumiNa/a1c01ad379750d93304e#file-browers-sync-text

**Comment by ehsalazar** [comment]
@TsumiNa Have you given `npm cache clean` a try?

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.
