### ISSUE TITLE
other files are excluded when adding the `files` array.

### ISSUE THREAD

**Issue by andineck** [npm/npm#9753]
I wanted to add  build files to the npm package which are ignored in (.gitigngore).
In the docs i found the `files` array you can put into the package.json.

So I added it:

```javascript
"files": [
    "public/build"
  ]
```

What's great is, the public/build directory and all it's files are now added,
BUT: all the other files are now excluded in the npm package except for the `main` file.

That is really confusing. You want to add something, and everything else get's left out.

Did I miss something or is this a bug?

npm version 3.3.4

**Comment by KenanY** [comment]
@andineck `"files"` is a whitelist. Anything that's not on the list won't be packed up into the final package.

**Comment by andineck** [comment]
@KenanY thx, for your response.

That wasn't clear to me when I read the docs, and I was surprised by this behaviour. I assumed, it's the opposite of the `.npmignore` file.

I do it now in the `.npmignore` file with an inclusion 

    !public/build

(wasn't aware you can actually include things in the npm package with `.npmignore` that would be excluded because of the `.gitignore`)
