### ISSUE TITLE
Issue Updating Node Global Modules

### ISSUE THREAD

**Issue by icn2you** [npm/npm#9754]
Upon attempting to execute an update of Node's global packages (`npm update -g`) this morning, I received the following error:

```js
npm WARN install:async ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/bower/node_modules/form-data/node_modules/async' -> '/usr/local/lib/node_modules/bower/node_modules/form-data/node_modules/async'
async@0.9.2 node_modules/bower/node_modules/form-data/node_modules/async -> node_modules/bower/node_modules/form-data/node_modules/async
form-data@0.2.0 node_modules/bower/node_modules/request/node_modules/form-data -> node_modules/bower/node_modules/form-data
- /usr/local/lib/node_modules/bower/node_modules/form-data node_modules/bower/node_modules/form-data
/usr/local/lib
└── (empty)

npm ERR! code 1
```

I've had Node running on my machine—a MBP (mid-2009) with OS X 10.9.5—for months with no issues. I run the same update command routinely four to five times per week (*i.e.*, near daily) and have not experienced a single error until today.

From what I can deduce, the error seems to be related to the`bower`module. (Am I correct in concluding this is a`bower`dependency issue?) After poking around a bit on Google, I tried clearing the cache (`npm cache clean`), which had no effect on the error. I then attempted to reinstall`bower`(`npm install -g bower`), but that produced a similar error message, ostensibly related to another dependency:

```js
npm WARN install:mime-types ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/bower/node_modules/form-data/node_modules/mime-types' -> '/usr/local/lib/node_modules/bower/node_modules/form-data/node_modules/mime-types'
mime-types@2.0.14 node_modules/bower/node_modules/form-data/node_modules/mime-types -> node_modules/bower/node_modules/form-data/node_modules/mime-types
form-data@0.2.0 node_modules/bower/node_modules/request/node_modules/form-data -> node_modules/bower/node_modules/form-data
- /usr/local/lib/node_modules/bower/node_modules/form-data node_modules/bower/node_modules/form-data
/usr/local/lib
└── (empty)
```

I'm a novice web developer, so I don't yet know the intricacies of Node. Please assist.

**Comment by KenanY** [comment]
@icn2you `npm --version`?

**Comment by AJIh** [comment]
+1. 
MBP(mid-2015) with OSX 10.10.5.
npm version: 3.3.5

**Comment by icn2you** [comment]
@KenanY An essential piece of info I unintentionally omitted—so sorry: npm 3.3.5. Looks like @AJIh and I have the same version but varying hardware and OS specs.

**Comment by ActionScripted** [comment]
Had the same issue here. It seems to be a bower problem and less an overall npm problem. Was able to get things working by uninstalling and reinstall bower:

`npm uninstall -g bower`
`npm install -g bower`

**Comment by icn2you** [comment]
Worked like a charm, @ActionScripted. Thank you for the heads-up. Guess I should open an issue with the`bower`dev team?

**Comment by rd13** [comment]
@ActionScripted thanks, worked for me.

**Comment by bkapo** [comment]
@ActionScripted,  worked for me.
Thank you!

**Comment by dansod** [comment]
@ActionScripted, worked for med too, thanks!

**Comment by fabrulana** [comment]
Sweet it works, thanks!

**Comment by dmontenegro** [comment]
@ActionScripted thank you! Works for me too.

**Comment by EvanCarroll** [comment]
How annoying. Is it not possible to have upstream `bower` fix this?

**Comment by marhalpert** [comment]
@ActionScripted THANKS! Worked

**Comment by sebloix** [comment]
@ActionScripted thanks for this, worked for me too!

**Comment by jfrye0717** [comment]
Did not work for me.

**Comment by joostaafjes** [comment]
+1
OSX 10.11.2
npm 3.3.12 and node 5.4.0

Gave me a headache, @ActionScripted: thx.

**Comment by stihlsicher** [comment]
@ActionScripted great thanks! saved my day! 
OSX 10.9.5
npm 3.3.12
node 5.5.0
