### ISSUE TITLE
(3.3.5) Progress bar seems to be broken on Windows CMD

### ISSUE THREAD

**Issue by laggingreflex** [npm/npm#9755]
I'm on npm@3.3.5 and this is what `npm install xxx` outputs to console on Windows CMD console:

[![](http://i.imgur.com/zNY8ppY.png)](http://i.imgur.com/zNY8ppY.png)

Text ([full](http://pastebin.com/iDvy4jDD)) :

```
▄ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
▐ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadIdealTree → cloneCurr ▄ ╢███████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadRequestedDeps → addNa ▌ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadRequestedDeps → reque ▀ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadRequestedDeps → netwo ▄ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadRequestedDeps → netwo ▌ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadRequestedDeps → netwo ▀ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:fsevents → networ ▀ ╢████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:fsevents → 304    ▐ ╢████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:fsevents → instal ▌ ╢████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm WARN install Couldn't install optional dependency: Unsupported
loadDep:fsevents          ▌ ╢████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:minimatch         ▀ ╢████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:once              ▀ ╢██████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadExtraneous            ▀ ╢██████████████████████████░░░░░░░░░░░░░░░░░░░░░░░╟
```

It seems to be not being able to clear-line and instead goes to next line to print the "progess"..

Searched and saw some similar issues being discussed in #8812 & #8761 but I'm guessing this Windows issue is different than those?

**Comment by Stanzilla** [comment]
Mine looks like that, both in cmd and ConEmu 

![cmder_2015-09-26_23-25-40](https://cloud.githubusercontent.com/assets/75278/10119944/4873ba1a-64a6-11e5-9d0b-86d2fc7aa5a7.png)

**Comment by web20opensource** [comment]
![image](https://cloud.githubusercontent.com/assets/2625752/10376305/d4d8b2f6-6dc2-11e5-914d-2b356d18bb76.png)

**Comment by Stanzilla** [comment]
@iarna any idea what could cause this?

**Comment by iarna** [comment]
You are somehow not using a unicode font? Or there's some way that I was unware of to disable unicode support in cmd?

**Comment by Stanzilla** [comment]
No you can't really disable it and I tried a few different fonts and all of them had that problem, Lucida Console, Consolas...etc.

**Comment by Stanzilla** [comment]
@iarna Weeeelll, that certainly looks like a lot of fun http://stackoverflow.com/questions/388490/unicode-characters-in-windows-command-line-how/388500#388500

**Comment by web20opensource** [comment]
Thanks @Stanzilla

**Comment by Stanzilla** [comment]
It works in PuTTY though, I haven't managed to get it working in either cmd or ConEmu.

**Comment by laggingreflex** [comment]
Apart from unicode characters not rendering (presumably rendering "a"s for █ blocks, which actually isn't the case with me as posted originally), what about the issue of them appearing in multiple lines like that? I assume they're supposed to be re-rendered in the same line showing the progress, but instead are getting printed on new lines?

Or could these two issues actually be related? Like some new line character not being rendered kind of issue?

**Comment by lizimeow** [comment]
i met the same situation with you。

Do you have to settle this matter now？QAQ

**Comment by lizimeow** [comment]
i met the same situation with you..
Do you settle this matter now？QAQ

**Comment by Stanzilla** [comment]
Sort of, you have to use PUTTY if you want it to look right.

**Comment by yongtw123** [comment]
A similar issue https://github.com/npm/npm/issues/10648 refers to here https://github.com/iarna/gauge/issues/5 as the cause. It's about the code page.

**Comment by Stanzilla** [comment]
You can change the codepage all you want on Windows, it doesn't fix this. Mine is actually set to Unicode on the screenshots.

**Comment by yongtw123** [comment]
@Stanzilla Have you tried this? http://stackoverflow.com/a/388500 It works for me but I suspect there could be ramifications.

**Comment by Stanzilla** [comment]
@yongtw123 yep, didn't fix it for me. did it for you?

**Comment by alphatan** [comment]
This problem also confused me. 

        npm@3.3.12
        win7

It's hard to use UTF-8 as a default coding page.

If it's not possible to change back to the v2 style progress bar officially, is it possible to give us a hint how to do it ourself ?

Thanks.

**Comment by Stanzilla** [comment]
Oh boy https://twitter.com/shanselman/status/695738082209853440/photo/1

**Comment by alphatan** [comment]
The difficult part happens in changing all the system characters to the new old.

e.g. Orginally using Chinese, then chaning to UTF-8 will result in all file names in Chinese will be messed up.

Alternatively, if it can show progress percentage instead of progress bar, or just a switch to turn it off, it will be very helpful.

Thanks.

**Comment by lovanwubing** [comment]
A simple solution is to upgrade node js to latest version 6.6.0. It works for me on windows 10.

**Comment by rempatterson** [comment]
I desparately want to to unsubscribe. How can I do it? I think you are reaching me at my email alias of 'patterson@computer.org', although it is possible you are writing me directly at 'bill.patterson1@comcast.net. Ether way, I am not prepared for the volume of email that I am getting. 

Thank you. 

----- Original Message -----

**Comment by laggingreflex** [comment]
@lovanwubing node latest is 6.1, no? I have that (and also I'm on Win10) but issue still persists. Did you mean nightly builds? But even in [nighly builds](https://nodejs.org/download/nightly/) I don't see a v6.6

Also I like to point out that the issues detailed in this thread are actually two different ones. The first one (with which I started the thread) was that the progress isn't displayed in a single line, but every change in animation (the rotator, the bar) displays in a new line. 

The second issue, as pointed out by @Stanzilla and others is the font issue. I personally don't have this issue. But others seem to have both. 

Are these two related?

---

@rempatterson visit this page and try the unsubscribe button on the right --->

**Comment by daddie888** [comment]
I got both problems after upgrading to Ruby MRI 2.3.0 on W7. Was only with MRI, not jRuby and only in Conemu, CMD was fine. Got rid of the problem by unchecking the Settings/Features/Inject ConEmuHk checkbox. Hope it helps. The combination Ruby-ConEmu rocks..
