### ISSUE TITLE
elm-reactor has problems after install

### ISSUE THREAD

**Issue by iamwilhelm** [npm/npm#9757]
This is what I see after I install. I'm using node 0.12.7, npm 3.3.4, 

```
 > npm install elm

> elm@2.0.0 postinstall /Users/iamwil/projects/experimental/silhouette/node_modules/elm
> node lib/install.js

  ✔ elm pre-build test passed successfully
  ✔ elm-make pre-build test passed successfully
  ✔ elm-package pre-build test passed successfully
  ✖ The `/Users/iamwil/projects/experimental/silhouette/node_modules/elm/vendor/elm-reactor` binary doesn't seem to work correctly
  ✖ elm-reactor pre-build test failed
  ✔ elm-repl pre-build test passed successfully
```
I get the message that the elm-reactor pre-build has failed. how can I debug what went wrong?

**Comment by KenanY** [comment]
@iamwilhelm Maybe the `elm-reactor` developers would be of greater help?

**Comment by snopeks** [comment]
Hi @iamwilhelm, since this isn't an npm-related issue I'm going to go ahead and close it. Please reach out to the `elm` folks, they'll be of more help in debugging why the `elm-reactor` pre-build failed. Thank you!
