### ISSUE TITLE
objc[16648] too many errors

### ISSUE THREAD

**Issue by lordlycastle** [npm/npm#9758]
When I go `npm install -g webtorrent`, the following line is output many times. I don't know how to fix this.
```
objc[16648]: Class  is implemented in both /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/Frameworks/DevToolsCore.framework/Versions/A/DevToolsCore and /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/Frameworks/DevToolsCore.framework/Versions/A/DevToolsCore. One of the two will be used. Which one is undefined.
```
[Full output](https://truck.it/p/sBvmSJU0lZ)

I also noticed that `npm outdated -g --depth=0` doesn't work. I know my bower package is outdated, but it doesn't show up in the command; only npm is listed in the command (though it is updated to current version)

**Comment by KenanY** [comment]
@lordlycastle Are you still seeing this issue?

**Comment by lordlycastle** [comment]
Nope 👍
