### ISSUE TITLE
npm owner rm xyz lodash.startcase error

### ISSUE THREAD

**Issue by jdalton** [npm/npm#9760]
I was doing maintenance on package owners and ran into an issue with the `lodash.startcase` package.

```bash
npm owner rm kitcambridge lodash.startcase
npm ERR! owner mutate Failed to update package metadata
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "owner" "rm" "kitcambridge" "lodash.startcase"
npm ERR! node v4.1.0
npm ERR! npm  v2.14.5
npm ERR! code E500

npm ERR! "name and _id should match" : lodash.startcase
```

**Comment by jdalton** [comment]
it also happens with `lodash.startswith`, something with the `start` bit maybe?

**Comment by jdalton** [comment]
This also happens with `lodash._charsstartindex` and `lodash.padstart`.

**Comment by jdalton** [comment]
and `lodash.trimstart`.

**Comment by jdalton** [comment]
It looks like the error is in the response to attempting `npm.registry.request()`.
```js
{ [Error: "name and _id should match" : lodash.trimstart] pkgid: 'lodash.trimstart', statusCode: 500, code: 'E500' }
{ success: false, error: '"name and _id should match"' }
```

**Comment by soldair** [comment]
traced this down to the presence of "star" actually so i have a good idea where to look =)

**Comment by jdalton** [comment]
This is the coolest bug ever! :star:

**Comment by soldair** [comment]
I have a fix deployed to stage and it's tested but ill deploy Monday because .. Friday.

The command works now as long as the module name is *not* part of the command line arguments.
there was some dubious sniffing the in http referer for star|unstar that was not anchored to the start of the  string. The cli sends the command line arguments in the http referrer for logging.

**Comment by soldair** [comment]
so you can cd to a module with package.json name value of "lodash.startcase"
, then run `npm owner rm username` and as long as the username does not also contain star it will work lol

**Comment by jdalton** [comment]
> so you can cd to a module with package.json name value of "lodash.startcase"
, then run npm owner rm username and as long as the username does not also contain star it will work lol

That's only needed until Monday though, correct?

**Comment by soldair** [comment]
Yeah. Only till the fix is deployed

**Comment by jdalton** [comment]
:sunglasses:

**Comment by ljharb** [comment]
@soldair that workaround does not allow me to deprecate tho, correct?

**Comment by soldair** [comment]
Im not sure how deprecate populates the default arguments. If you are in the module you may be able to specify only the version number you want to deprecate. otherwise outa luck till monday.

**Comment by ljharb** [comment]
thanks, i tried ti - seems i'll be waiting til monday. appreciate the fix, and thanks @jdalton for helping narrow it down!

**Comment by soldair** [comment]
this should be working now. i deployed the fix yesterday morning. please test and let me know =)

**Comment by jdalton** [comment]
Yep it works for me.

**Comment by ljharb** [comment]
Hooray, thanks! `deprecations string.prototype.padleft` is showing my message that contains "start" now :-D
