### ISSUE TITLE
devEngines

### ISSUE THREAD

**Issue by justinbmeyer** [npm/npm#9765]
A few of my projects require a certain version of NPM to do development work.  For example, they use `preversion`, `version`, and `postversion` scripts.  I'd like to let people know they need to upgrade npm, but only if they are doing development work.  I don't want them to update if they are simply using the project.

Would you consider adding a `devEngines` config that would warn only when a package is being used in a development context?

Thanks!

**Comment by nrempel** [comment]
I'd like to see this functionality too!

In the meantime, you can set it up manually by following the lead of https://github.com/facebook/react.

Steps:

- Add devEngines to your package.json [(example)](https://github.com/facebook/react/blob/master/package.json)
- Install this package: https://www.npmjs.com/package/fbjs-scripts
- Add a postinstall hook to check dev dependencies [(example)](https://github.com/facebook/react/blob/master/package.json)

**Comment by danny-andrews** [comment]
Alternatively, you can just use existing tools for this: nvm + .nvmrc.
