### ISSUE TITLE
Mocha blues...

### ISSUE THREAD

**Issue by Russann** [npm/npm#9767]
I cannot seem to run localhost:8000 from my residence on this quiz for school. Here is my response inviting me to contact this url:

sh: mocha: command not found
npm ERR! Test failed.  See above for more details.
Russann-Johnsons-2014-MacBook-Pro:quiz2 russanntomlinson$ atom .
Russann-Johnsons-2014-MacBook-Pro:quiz2 russanntomlinson$ 
Russann-Johnsons-2014-MacBook-Pro:quiz2 russanntomlinson$ npm start
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! missing script: start
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/russanntomlinson/Desktop/quiz2/npm-debug.log
Russann-Johnsons-2014-MacBook-Pro:quiz2 russanntomlinson$

**Comment by KenanY** [comment]
@Russann Are you still seeing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
