### ISSUE TITLE
Can't install steroids - shasum check failed

### ISSUE THREAD

**Issue by danicamozo** [npm/npm#9770]
C:\Users\Danica>npm install steroids -g
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "steroids" "-g"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! shasum check failed for C:\Users\Danica\AppData\Local\Temp\npm-6832-7a1
63d81\registry.npmjs.org\steroids\-\steroids-4.1.19.tgz
npm ERR! Expected: 8fa96779487f481154640482e7d798af63a0386c
npm ERR! Actual:   542f896e53f81f26dfe10ba1708bb31321ba10c0
npm ERR! From:     http://registry.npmjs.org/steroids/-/steroids-4.1.19.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Danica\npm-debug.log

C:\Users\Danica>npm install steroids -g
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "steroids" "-g"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! shasum check failed for C:\Users\Danica\AppData\Local\Temp\npm-4876-3ca
2faaf\registry.npmjs.org\steroids\-\steroids-4.1.19.tgz
npm ERR! Expected: 8fa96779487f481154640482e7d798af63a0386c
npm ERR! Actual:   0efc79861657312f8e5fdc72f0b98c650433420a
npm ERR! From:     http://registry.npmjs.org/steroids/-/steroids-4.1.19.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by KenanY** [comment]
@danicamozo Have you tried running `npm cache clean`?
