### ISSUE TITLE
npm install issue

### ISSUE THREAD

**Issue by RenaudGagne** [npm/npm#9774]
This is what I have in my npm-debug.log

I have node, ruby and gulp installed with the latest updates. What's missing?

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@2.14.4
3 info using node@v4.1.1
4 verbose readDependencies loading dependencies from C:\SteamTrainGit\WebApp\Platform1\package.json
5 error install Couldn't read dependencies
6 verbose stack Error: ENOENT: no such file or directory, open 'C:\SteamTrainGit\WebApp\Platform1\package.json'
6 verbose stack     at Error (native)
7 verbose cwd C:\SteamTrainGit\WebApp\Platform1
8 error Windows_NT 6.1.7601
9 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
10 error node v4.1.1
11 error npm  v2.14.4
12 error path C:\SteamTrainGit\WebApp\Platform1\package.json
13 error code ENOPACKAGEJSON
14 error errno -4058
15 error syscall open
16 error package.json ENOENT: no such file or directory, open 'C:\SteamTrainGit\WebApp\Platform1\package.json'
16 error package.json This is most likely not a problem with npm itself.
16 error package.json npm can't find a package.json file in your current directory.
17 verbose exit [ -4058, true ]
```

**Comment by KenanY** [comment]
@RenaudGagne Does `C:\SteamTrainGit\WebApp\Platform1\package.json` exist?

**Comment by RenaudGagne** [comment]
it shouldn't since I am executing npm install within C:\SteamTrainGit\WebApp\Platform1\web-starter-kit\
package.json is in there.

**Comment by MasterPCUK** [comment]
Hi there,

I have issue with npm install as well.
Running virtualbox and vagrant with ubuntu 14.04(laravel/homestead) and latest npm and node.

I am trying to install following dependecies, but npm throws errors:

```
"devDependencies": {
        "gulp": "^3.8.8"
    },
    "dependencies": {
        "laravel-elixir": "^3.0.0",
        "bootstrap-sass": "^3.0.0"
    }
```

Here is console output:

```
npm WARN optional dep failed, continuing request@2.64.0
npm ERR! Linux 3.13.0-24-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! path ../user-home/cli.js
npm ERR! code EPROTO
npm ERR! errno -71
npm ERR! syscall symlink

npm ERR! EPROTO: protocol error, symlink '../user-home/cli.js' -> '/users/janisberzins/Development/server1/code/masterpc/node_modules/gulp/node_modules/v8flags/node_modules/.bin/user-home'
npm ERR! 
```

Here is my npm-debug.log: 
https://drive.google.com/file/d/0B2P4i22GbLNINWpmbXEtX3F2cUk/view?usp=sharing


I have tried rm -rf node-modules, clearing tmp, reboting server, reinstaling vagrant, but nothing has helped.

Any advice would be appreciated!

**Comment by KenanY** [comment]
@RenaudGagne The log says that this is the directory you are in:

```
7 verbose cwd C:\SteamTrainGit\WebApp\Platform1
```

@MasterPCUK Your issue looks unrelated, but I am glad that you discovered the fix! "Permanent solution" would be to use the flag you found or use a system that supports symlinks.

**Comment by RenaudGagne** [comment]
Oh right, I gave you the wrong .log file
Here is what happens when I am in the right folder:
https://www.dropbox.com/s/o48vx2yrlq5jda8/npm-debug.log?dl=0

**Comment by masterpowers** [comment]
I got this error can someone help me up
```
npm WARN install Couldn't install optional dependency: Unsupported
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Andrew Galang\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--no-bin-links"
npm ERR! node v4.1.2
npm ERR! npm  v3.3.5

npm ERR! Maximum call stack size exceeded
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Andrew Galang\Code\rfnbeta\npm-debug.log
```

**Comment by Pedramrn** [comment]
It's an old issue, mostly happens when using npm in virtualbox or vmware.

look this [askubuntu question] (http://askubuntu.com/questions/269727/npm-errors-when-installing-packages-on-windows-share#)

**Comment by Parthjhaveri** [comment]
I un-installed NPM globally, but when I try to re-install it on the command line by typing `npm install -g npm`, I get this weird error saying:

`-bash: /usr/local/bin/npm: No such file or directory`

Any idea why?  The reason I un-installed NPM was because when I was trying to do npm install, it would kill the installation instantly on the terminal.

Thanks!
