### ISSUE TITLE
Yo Jhipster

### ISSUE THREAD

**Issue by khanvani** [npm/npm#9775]
browser-sync@2.9.6 node_modules\browser-sync
├── async-each-series@0.1.1
├── emitter-steward@1.0.0
├── ucfirst@0.0.1
├── longest@1.0.1
├── opn@2.0.1
├── dev-ip@1.0.1
├── ua-parser-js@0.7.9
├── immutable@3.7.5
├── pad-left@1.0.2 (repeat-string@1.5.2)
├── browser-sync-client@2.3.1 (fresh@0.3.0, etag@1.7.0)
├── query-string@2.4.1 (strict-uri-encode@1.0.2)
├── serve-static@1.10.0 (escape-html@1.0.2, parseurl@1.3.0, send@0.13.0)
├── connect@3.4.0 (utils-merge@1.0.0, parseurl@1.3.0, debug@2.2.0, finalhandler@
0.4.0)
├── resp-modifier@5.0.2 (debug@2.2.0, minimatch@2.0.10)
├── meow@3.3.0 (object-assign@3.0.0, minimist@1.2.0, camelcase-keys@1.0.0, inden
t-string@1.2.2)
├── portscanner@1.0.0 (async@0.1.15)
├── serve-index@1.7.2 (escape-html@1.0.2, parseurl@1.3.0, batch@0.5.2, http-erro
rs@1.3.1, debug@2.2.0, accepts@1.2.13, mime-types@2.1.7)
├── easy-extender@2.3.1 (lodash@2.4.2)
├── eazy-logger@2.1.2 (opt-merger@1.1.0, tfunk@3.0.1)
├── chokidar@1.1.0 (arrify@1.0.0, path-is-absolute@1.0.0, is-glob@2.0.0, async-e
ach@0.1.6, glob-parent@2.0.0, is-binary-path@1.0.1, readdirp@2.0.0)
├── anymatch@1.3.0 (arrify@1.0.0, micromatch@2.2.0)
├── foxy@11.1.3 (cookie@0.1.5, resp-modifier@4.0.4, http-proxy@1.11.2, lodash.me
rge@3.3.2)
├── lodash@3.10.1
├── localtunnel@1.7.0 (debug@0.7.4, openurl@1.1.0, request@2.11.4, yargs@3.15.0)

├── socket.io@1.3.7 (has-binary-data@0.1.3, debug@2.1.0, socket.io-parser@2.2.4,
 socket.io-adapter@0.3.1, engine.io@1.5.4, socket.io-client@1.3.7)
└── browser-sync-ui@0.5.16 (connect-history-api-fallback@0.0.5, stream-throttle@
0.1.3, weinre@2.0.0-pre-I0Z7U9OV)
? May bower anonymously report usage statistics to improve the tool over time? b
ower ENOGIT        git is not installed or not in the PATH
'grunt' is not recognized as an internal or external command,
operable program or batch file.
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn grunt ENOENT
    at notFoundError (C:\Users\rahulk\AppData\Roaming\npm\node_modules\generator
-jhipster\node_modules\yeoman-generator\node_modules\cross-spawn\node_modules\cr
oss-spawn-async\lib\enoent.js:8:11)
    at verifyENOENT (C:\Users\rahulk\AppData\Roaming\npm\node_modules\generator-
jhipster\node_modules\yeoman-generator\node_modules\cross-spawn\node_modules\cro
ss-spawn-async\lib\enoent.js:43:16)
    at ChildProcess.cp.emit (C:\Users\rahulk\AppData\Roaming\npm\node_modules\ge
nerator-jhipster\node_modules\yeoman-generator\node_modules\cross-spawn\node_mod
ules\cross-spawn-async\lib\enoent.js:30:19)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)

**Comment by KenanY** [comment]
@khanvani The stack trace indicates that this error was not thrown by `npm`.

**Comment by jdubois** [comment]
Have a look at the [JHipster installation documentation](http://jhipster.github.io/installation.html) point 7, you need to install Grunt.

**Comment by eddiemonge** [comment]
You also need to install git and make it available to your path. @khanvani or if this is fixed by now please close this ticket

**Comment by jdubois** [comment]
Installing Git is our point 3 in the [JHipster installation documentation](http://jhipster.github.io/installation.html) I was already pointing to in my previous comment.

If you don't want to follow or read the documentation, we provide a Virtual Machine with everything already set up [here](https://github.com/jhipster/jhipster-devbox)

**Comment by khanvani** [comment]
Done Thanks :)
