### ISSUE TITLE
NPM Restore Packages problem.

### ISSUE THREAD

**Issue by Iamguy84** [npm/npm#9776]
Hi Folks,

I am having problem with Restore Packages for NPM.

I follow this tutorial: 
http://docs.asp.net/en/latest/client-side/using-gulp.html

I am getting this error message when restoring packages:

====Executing command 'npm install'====

npm http GET https://registry.npmjs.org/gulp
npm http GET https://registry.npmjs.org/gulp
npm http GET https://registry.npmjs.org/gulp
npm ERR! network tunneling socket could not be established, cause=Parse Error
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\IDE\\Extensions\\Microsoft\\Web Tools\\External\\\\node\\node" "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\IDE\\Extensions\\Microsoft\\Web Tools\\External\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd D:\*********\SAMPLE_TEST\WebApplication4\src\WebApplication4
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.9
npm ERR! code ECONNRESET
npm

====npm command completed with exit code 1====

I am using behind a proxy. Lets say My proxy is abc.net and port# is 8080 (Sorry! cannot show you my real proxy ;) )
so I changed proxy config:
H:\>npm config edit

proxy=http://abc.net:8080/
https-proxy=http://abc.net:8080/
strict-ssl=false

I run restore package again and same error message.
Any Idea?
Thanks

**Comment by KenanY** [comment]
@Iamguy84 Is this still an issue for you?

**Comment by Iamguy84** [comment]
No
