### ISSUE TITLE
Error: Appium Setup android-Window

### ISSUE THREAD

**Issue by quangdt** [npm/npm#9777]
Hello everyone,
Please help me. I have problem with appium: setup for android-windows when start the server use appium with commands such as:
--> npm install g appium # to install the appium -> npm install 
--> npm install wd # get appium client
Result:
![4](https://cloud.githubusercontent.com/assets/9360498/10131321/9c5438c2-65f9-11e5-8487-88e49e137dcf.png)

Please help me! Thank everyone more much!﻿

**Comment by KenanY** [comment]
@quangdt Try:

```
npm install -g appium
npm install wd
```

That is, don't actually type the `#` comments.

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some issues. Hopefully the recommendation from @KenanY helped. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.
