### ISSUE TITLE
"*install" script clarification

### ISSUE THREAD

**Issue by mmwtsn** [npm/npm#9781]
After cloning a repository with a package.json file I noticed that running `npm install` triggered the "preinstall" script. Both "install" and "postinstall" are triggered as well. Is that the expected behavior?

According to [the scripts documentation](https://docs.npmjs.com/misc/scripts):

>  preinstall: Run BEFORE the package is installed
> install, postinstall: Run AFTER the package is installed.

Based on that I assumed those scripts were run only when the package itself was installed, e.g.:

``` shell
$ git clone git@github.com:npm/npm.git
$ cd npm
$ npm install           # npm's install-related scripts are not run
$ npm install my-module # my-module's install-related scripts are run
```

**Comment by mamapitufo** [comment]
This behavior confused me as well. I was expecting those scripts to be run only when the package was installed, but not when its dependencies were installed.

**Comment by Nargonath** [comment]
@mmwtsn If you have a pre/postinstall hook in your package.json they will be triggered when you install your package i.e. `npm install`. `npm install <package>` only triggers the pre/postinstall hook of that particular package not yours.
