### ISSUE TITLE
npm install strongloop issue 

### ISSUE THREAD

**Issue by ghatwala** [npm/npm#9783]
Hi All,

I am getting errors while using npm to install strongloop . 
$ npm install -g strongloop 

My nodejs version
test@pts00449-vm28:~$ nodejs -v
v0.10.25
test@pts00449-vm28:~$ python --version
Python 2.7.9
test@pts00449-vm28:~$ g++ --version
g++ (Ubuntu 4.9.2-10ubuntu13) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Please kindly see the below log inside "npm-debug.log"

/*************************/
106765 error Error: ENOENT, lstat '/usr/local/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/yeoman-generator/node_modules/html-wiring/node_modules/cheerio/node_modules/htmlparser2/node_modules/entities/maps/legacy.json'
106766 error If you need help, you may report this *entire* log,
106766 error including the npm and node versions, at:
106766 error     <http://github.com/npm/npm/issues>
106767 error System Linux 3.19.0-15-generic
106768 error command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "strongloop"
106769 error cwd /home/test
106770 error node -v v0.10.25
106771 error npm -v 1.4.21
106772 error path /usr/local/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/yeoman-generator/node_modules/html-wiring/node_modules/cheerio/node_modules/htmlparser2/node_modules/entities/maps/legacy.json
106773 error fstream_path /usr/local/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/yeoman-generator/node_modules/html-wiring/node_modules/cheerio/node_modules/htmlparser2/node_modules/entities/maps/legacy.json
106774 error fstream_type File
106775 error fstream_class FileWriter
106776 error code ENOENT
106777 error errno 34
106778 error fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
106778 error fstream_stack Object.oncomplete (evalmachine.<anonymous>:107:15)
106779 verbose exit [ 34, true ]

/**************************/
Regards,
Amit

**Comment by KenanY** [comment]
@ghatwala Does this also occur if you [upgrade `npm`](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm)?

**Comment by ghatwala** [comment]
Hi @KenanY :

I got this working after i upgraded nodejs from source as per url : http://linoxide.com/ubuntu-how-to/setup-node-js-ubuntu-15-04-different-methods/

I took " node-v4.1.1.tar.gz  " file , Next i installed strongloop using "npm install " command and it could see the "strongloop" login page at an externally mapped port.

Regards,
Amit
