### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by pingpong1109** [npm/npm#9784]
I am getting this following error:

npm http GET https://registry.npmjs.org/daemonize2/0.4.2
npm http GET https://registry.npmjs.org/engine.io
npm http GET https://registry.npmjs.org/es6-promise
npm http GET https://registry.npmjs.org/eventemitter2/0.4.14
npm http GET https://registry.npmjs.org/iconv-lite/0.4.4
npm http GET https://registry.npmjs.org/ipaddr.js/0.1.3
npm http GET https://registry.npmjs.org/lodash/2.4.1
npm http GET https://registry.npmjs.org/negotiator/0.4.3
npm http GET https://registry.npmjs.org/node-static/0.7.4
npm http GET https://registry.npmjs.org/po2json/0.3.0
npm http GET https://registry.npmjs.org/socksjs/0.4.4
npm http GET https://registry.npmjs.org/spdy/1.19.1
npm http GET https://registry.npmjs.org/uglify-js/2.4.12
npm http GET https://registry.npmjs.org/winston

npm ERR! Error: failed to fetch from registry: iconv-lite/0.4.4
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
npm ERR!     at ClientRequest.g (events.js:156:14)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1256:7)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /root/KiwiIRC/npm-debug.log npm
npm ERR!
npm ERR! System Linux 3.12.26-rpi-aufs
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /root/KiwiIRC
npm ERR! node -v v0.6.19
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: iconv-lite/0.4.4
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/KiwiIRC/npm-debug.log
npm not ok

**Comment by KenanY** [comment]
@pingpong1109 Does this also occur if you upgrade [Node.js](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-node) and [`npm`](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm)? Node.js v0.6 is so old at this point that it would be a miracle for anything to still work on it. Furthermore, `npm@1.1.4` is just as old, and has not been supported for what could be considered **years** now due to the fact that `npm` has gone through maybe over a hundred releases since then.

**Comment by pingpong1109** [comment]
I did apt-get update && apt-get upgrade and they appear to be on the latest version

**Comment by KenanY** [comment]
@pingpong1109 You might want to use [NodeSource's distribution](https://github.com/nodesource/distributions) if Debian's is lagging behind the latest stable release.

**Comment by ehsalazar** [comment]
Have you been able to update? If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.
