### ISSUE TITLE
latest version of npm works really slow

### ISSUE THREAD

**Issue by prog666** [npm/npm#9785]
i try to do `npm update checkbox-radio-styler` and it just stuck, there's no deps and not so much weight.

**Comment by KenanY** [comment]
@prog666 Just slow, or literally stuck for an indefinite amount of time (title and description conflict on this)?

**Comment by prog666** [comment]
it stuck for about 2 minutes when install, and I could not wait until update unstucked.
sometimes after `npm install` it already installed the module, I can use it, but terminal is still busy.

**Comment by prog666** [comment]
the title says that it all got worse than previous versions

**Comment by iarna** [comment]
Hi all, this is a duplicate #8826, so I'm closing as such.

But you'll all be happy to hear that I made a HUGE performance improvement earlier this week, so this week's release should being npm@3 performance into much closer alignment w/ npm@2.
