### ISSUE TITLE
npm install -g bower error

### ISSUE THREAD

**Issue by JoyNAGInc** [npm/npm#9787]
Installation error please see error log content below:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'bower' ]
2 info using npm@2.11.2
3 info using node@v0.12.5
4 verbose install initial load of C:\Users\Joy\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\Joy\AppData\Roaming\npm\package.json
6 silly cache add args [ 'bower', null ]
7 verbose cache add spec bower
8 silly cache add parsed spec { raw: 'bower',
8 silly cache add   scope: null,
8 silly cache add   name: 'bower',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed bower@*
10 verbose addNamed "*" is a valid semver range for bower
11 silly addNameRange { name: 'bower', range: '*', hasData: false }
12 silly mapToRegistry name bower
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/bower
16 verbose addNameRange registry:https://registry.npmjs.org/bower not in flight; fetching
17 verbose request uri https://registry.npmjs.org/bower
18 verbose request no auth needed
19 info attempt registry request try #1 at 4:17:14 PM
20 verbose request id 2ea3b74cef448b55
21 verbose etag "F5DZ09SKDJ5DLFDPVBOP8TZTX"
22 http request GET https://registry.npmjs.org/bower
23 http 200 https://registry.npmjs.org/bower
24 silly get cb [ 200,
24 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
24 silly get     etag: '"9T83GPBORE2SESGCV41JXJ5PU"',
24 silly get     'content-type': 'application/json',
24 silly get     'cache-control': 'max-age=60',
24 silly get     'content-length': '122887',
24 silly get     'accept-ranges': 'bytes',
24 silly get     date: 'Tue, 29 Sep 2015 23:17:17 GMT',
24 silly get     via: '1.1 varnish',
24 silly get     age: '35',
24 silly get     connection: 'keep-alive',
24 silly get     'x-served-by': 'cache-ord1731-ORD',
24 silly get     'x-cache': 'HIT',
24 silly get     'x-cache-hits': '1',
24 silly get     'x-timer': 'S1443568637.022733,VS0,VE1',
24 silly get     vary: 'Accept' } ]
25 verbose get saving bower to C:\Users\Joy\AppData\Roaming\npm-cache\registry.npmjs.org\bower\.cache.json
26 silly addNameRange number 2 { name: 'bower', range: '*', hasData: true }
27 silly addNameRange versions [ 'bower',
27 silly addNameRange   [ '0.1.0',
27 silly addNameRange     '0.1.2',
27 silly addNameRange     '0.1.3',
27 silly addNameRange     '0.2.0',
27 silly addNameRange     '0.3.0',
27 silly addNameRange     '0.3.1',
27 silly addNameRange     '0.3.2',
27 silly addNameRange     '0.4.0',
27 silly addNameRange     '0.5.0',
27 silly addNameRange     '0.5.1',
27 silly addNameRange     '0.6.0',
27 silly addNameRange     '0.6.1',
27 silly addNameRange     '0.6.2',
27 silly addNameRange     '0.6.3',
27 silly addNameRange     '0.6.4',
27 silly addNameRange     '0.6.5',
27 silly addNameRange     '0.6.6',
27 silly addNameRange     '0.6.7',
27 silly addNameRange     '0.6.8',
27 silly addNameRange     '0.7.0',
27 silly addNameRange     '0.7.1',
27 silly addNameRange     '0.8.0',
27 silly addNameRange     '0.8.1',
27 silly addNameRange     '0.8.2',
27 silly addNameRange     '0.8.3',
27 silly addNameRange     '0.8.4',
27 silly addNameRange     '0.8.5',
27 silly addNameRange     '0.8.6',
27 silly addNameRange     '0.9.0',
27 silly addNameRange     '0.9.1',
27 silly addNameRange     '0.9.2',
27 silly addNameRange     '0.10.0',
27 silly addNameRange     '1.0.0',
27 silly addNameRange     '1.0.1',
27 silly addNameRange     '1.0.2',
27 silly addNameRange     '1.0.3',
27 silly addNameRange     '1.1.0',
27 silly addNameRange     '1.1.1',
27 silly addNameRange     '1.1.2',
27 silly addNameRange     '1.2.0',
27 silly addNameRange     '1.2.1',
27 silly addNameRange     '1.2.2',
27 silly addNameRange     '1.2.3',
27 silly addNameRange     '1.2.4',
27 silly addNameRange     '1.2.5',
27 silly addNameRange     '1.2.6',
27 silly addNameRange     '1.2.7',
27 silly addNameRange     '1.2.8',
27 silly addNameRange     '1.3.0',
27 silly addNameRange     '1.3.1',
27 silly addNameRange     '1.3.2',
27 silly addNameRange     '1.3.3',
27 silly addNameRange     '1.3.4',
27 silly addNameRange     '1.3.5',
27 silly addNameRange     '1.3.6',
27 silly addNameRange     '1.3.7',
27 silly addNameRange     '1.3.8',
27 silly addNameRange     '1.3.9',
27 silly addNameRange     '1.3.10',
27 silly addNameRange     '1.3.11',
27 silly addNameRange     '1.3.12',
27 silly addNameRange     '1.4.0',
27 silly addNameRange     '1.4.1',
27 silly addNameRange     '1.5.0',
27 silly addNameRange     '1.5.1',
27 silly addNameRange     '1.5.2',
27 silly addNameRange     '1.5.3' ] ]
28 silly addNamed bower@1.5.3
29 verbose addNamed "1.5.3" is a plain semver version for bower
30 silly mapToRegistry name bower
31 silly mapToRegistry using default registry
32 silly mapToRegistry registry https://registry.npmjs.org/
33 silly mapToRegistry uri https://registry.npmjs.org/bower
34 verbose addRemoteTarball https://registry.npmjs.org/bower/-/bower-1.5.3.tgz not in flight; adding
35 verbose addRemoteTarball [ 'https://registry.npmjs.org/bower/-/bower-1.5.3.tgz',
35 verbose addRemoteTarball   'ee5d7952e114e30b18795e20e9fefcc5b4cf963d' ]
36 info retry fetch attempt 1 at 4:17:15 PM
37 info attempt registry request try #1 at 4:17:15 PM
38 http fetch GET https://registry.npmjs.org/bower/-/bower-1.5.3.tgz
39 http fetch 200 https://registry.npmjs.org/bower/-/bower-1.5.3.tgz
40 silly fetchAndShaCheck shasum ee5d7952e114e30b18795e20e9fefcc5b4cf963d
41 verbose addTmpTarball C:\Users\Joy\AppData\Local\Temp\npm-9836-f9d29430\registry.npmjs.org\bower\-\bower-1.5.3.tgz not in flight; adding
42 verbose addTmpTarball already have metadata; skipping unpack for bower@1.5.3
43 silly cache afterAdd bower@1.5.3
44 verbose afterAdd C:\Users\Joy\AppData\Roaming\npm-cache\bower\1.5.3\package\package.json not in flight; writing
45 verbose afterAdd C:\Users\Joy\AppData\Roaming\npm-cache\bower\1.5.3\package\package.json written
46 silly install resolved [ { name: 'bower',
46 silly install resolved     version: '1.5.3',
46 silly install resolved     description: 'The browser package manager',
46 silly install resolved     author: { name: 'Twitter' },
46 silly install resolved     license: 'MIT',
46 silly install resolved     repository: { type: 'git', url: 'https://github.com/bower/bower' },
46 silly install resolved     main: 'lib',
46 silly install resolved     homepage: 'http://bower.io',
46 silly install resolved     engines: { node: '>=0.10.0' },
46 silly install resolved     dependencies:
46 silly install resolved      { abbrev: '^1.0.5',
46 silly install resolved        archy: '1.0.0',
46 silly install resolved        'bower-config': '^0.6.1',
46 silly install resolved        'bower-endpoint-parser': '^0.2.2',
46 silly install resolved        'bower-json': '^0.4.0',
46 silly install resolved        'bower-logger': '^0.2.2',
46 silly install resolved        'bower-registry-client': '^0.3.0',
46 silly install resolved        cardinal: '0.4.4',
46 silly install resolved        chalk: '^1.0.0',
46 silly install resolved        chmodr: '0.1.0',
46 silly install resolved        configstore: '^0.3.2',
46 silly install resolved        'decompress-zip': '^0.1.0',
46 silly install resolved        fstream: '^1.0.3',
46 silly install resolved        'fstream-ignore': '^1.0.2',
46 silly install resolved        github: '^0.2.3',
46 silly install resolved        glob: '^4.3.2',
46 silly install resolved        'graceful-fs': '^3.0.5',
46 silly install resolved        handlebars: '^2.0.0',
46 silly install resolved        inquirer: '0.8.0',
46 silly install resolved        insight: '^0.7.0',
46 silly install resolved        'is-root': '^1.0.0',
46 silly install resolved        junk: '^1.0.0',
46 silly install resolved        lockfile: '^1.0.0',
46 silly install resolved        'lru-cache': '^2.5.0',
46 silly install resolved        'md5-hex': '^1.0.2',
46 silly install resolved        mkdirp: '0.5.0',
46 silly install resolved        mout: '^0.11.0',
46 silly install resolved        nopt: '^3.0.1',
46 silly install resolved        opn: '^1.0.1',
46 silly install resolved        'p-throttler': '0.1.1',
46 silly install resolved        promptly: '0.2.0',
46 silly install resolved        q: '^1.1.2',
46 silly install resolved        request: '2.53.0',
46 silly install resolved        'request-progress': '0.3.1',
46 silly install resolved        retry: '0.6.1',
46 silly install resolved        rimraf: '^2.2.8',
46 silly install resolved        semver: '^2.3.0',
46 silly install resolved        'shell-quote': '^1.4.2',
46 silly install resolved        'stringify-object': '^1.0.0',
46 silly install resolved        'tar-fs': '^1.4.1',
46 silly install resolved        tmp: '0.0.24',
46 silly install resolved        'update-notifier': '^0.3.0',
46 silly install resolved        'user-home': '^1.1.0',
46 silly install resolved        which: '^1.0.8' },
46 silly install resolved     devDependencies:
46 silly install resolved      { chai: '^1.10.0',
46 silly install resolved        coveralls: '^2.11.2',
46 silly install resolved        'expect.js': '^0.3.1',
46 silly install resolved        grunt: '^0.4.5',
46 silly install resolved        'grunt-cli': '^0.1.13',
46 silly install resolved        'grunt-contrib-jshint': '^0.10.0',
46 silly install resolved        'grunt-contrib-watch': '^0.6.1',
46 silly install resolved        'grunt-exec': '^0.4.6',
46 silly install resolved        'grunt-simple-mocha': '^0.4.0',
46 silly install resolved        istanbul: '^0.3.5',
46 silly install resolved        'load-grunt-tasks': '^2.0.0',
46 silly install resolved        mocha: '^2.1.0',
46 silly install resolved        multiline: '^1.0.2',
46 silly install resolved        nock: '^0.56.0',
46 silly install resolved        'node-uuid': '^1.4.2',
46 silly install resolved        proxyquire: '^1.3.0',
46 silly install resolved        'spawn-sync': '^1.0.5' },
46 silly install resolved     scripts: { test: 'grunt test' },
46 silly install resolved     bin: { bower: 'bin/bower' },
46 silly install resolved     files: [ 'bin', 'lib', 'templates' ],
46 silly install resolved     gitHead: '66310523d16a1f342f3da2aa49ea90d927fe7d46',
46 silly install resolved     bugs: { url: 'https://github.com/bower/bower/issues' },
46 silly install resolved     _id: 'bower@1.5.3',
46 silly install resolved     _shasum: 'ee5d7952e114e30b18795e20e9fefcc5b4cf963d',
46 silly install resolved     _from: 'bower@*',
46 silly install resolved     _npmVersion: '1.4.28',
46 silly install resolved     _npmUser: { name: 'sheerun', email: 'sheerun@sher.pl' },
46 silly install resolved     maintainers: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
46 silly install resolved     dist:
46 silly install resolved      { shasum: 'ee5d7952e114e30b18795e20e9fefcc5b4cf963d',
46 silly install resolved        tarball: 'http://registry.npmjs.org/bower/-/bower-1.5.3.tgz' },
46 silly install resolved     directories: {},
46 silly install resolved     _resolved: 'https://registry.npmjs.org/bower/-/bower-1.5.3.tgz' } ]
47 info install bower@1.5.3 into C:\Users\Joy\AppData\Roaming\npm
48 info installOne bower@1.5.3
49 verbose installOne of bower to C:\Users\Joy\AppData\Roaming\npm not in flight; installing
50 verbose lock using C:\Users\Joy\AppData\Roaming\npm-cache\_locks\bower-9c52060c23c191dd.lock for C:\Users\Joy\AppData\Roaming\npm\node_modules\bower
51 silly install write writing bower 1.5.3 to C:\Users\Joy\AppData\Roaming\npm\node_modules\bower
52 verbose unbuild node_modules\bower
53 info preuninstall bower@1.4.1
54 info uninstall bower@1.4.1
55 verbose unbuild rmStuff bower@1.4.1 from C:\Users\Joy\AppData\Roaming\npm\node_modules
56 silly gentlyRm C:\Users\Joy\AppData\Roaming\npm\bower.cmd is being gently removed
57 silly gentlyRm verifying C:\Users\Joy\AppData\Roaming\npm is an npm working directory
58 silly gentlyRm containing path C:\Users\Joy\AppData\Roaming\npm is under npm's control, in C:\Users\Joy\AppData\Roaming\npm
59 silly gentlyRm deletion target C:\Users\Joy\AppData\Roaming\npm\bower.cmd is under C:\Users\Joy\AppData\Roaming\npm
60 verbose gentlyRm vacuuming from C:\Users\Joy\AppData\Roaming\npm\bower.cmd up to C:\Users\Joy\AppData\Roaming\npm
61 silly vacuum-fs removing C:\Users\Joy\AppData\Roaming\npm\bower.cmd
62 silly vacuum-fs finished vacuuming up to C:\Users\Joy\AppData\Roaming\npm
63 silly gentlyRm C:\Users\Joy\AppData\Roaming\npm\bower is being gently removed
64 silly gentlyRm verifying C:\Users\Joy\AppData\Roaming\npm is an npm working directory
65 silly gentlyRm containing path C:\Users\Joy\AppData\Roaming\npm is under npm's control, in C:\Users\Joy\AppData\Roaming\npm
66 silly gentlyRm deletion target C:\Users\Joy\AppData\Roaming\npm\bower is under C:\Users\Joy\AppData\Roaming\npm
67 verbose gentlyRm vacuuming from C:\Users\Joy\AppData\Roaming\npm\bower up to C:\Users\Joy\AppData\Roaming\npm
68 silly vacuum-fs removing C:\Users\Joy\AppData\Roaming\npm\bower
69 silly vacuum-fs finished vacuuming up to C:\Users\Joy\AppData\Roaming\npm
70 info postuninstall bower@1.4.1
71 silly gentlyRm C:\Users\Joy\AppData\Roaming\npm\node_modules\bower is being purged from base C:\Users\Joy\AppData\Roaming\npm
72 verbose gentlyRm don't care about contents; nuking C:\Users\Joy\AppData\Roaming\npm\node_modules\bower
73 silly vacuum-fs purging C:\Users\Joy\AppData\Roaming\npm\node_modules\bower
74 verbose unlock done using C:\Users\Joy\AppData\Roaming\npm-cache\_locks\bower-9c52060c23c191dd.lock for C:\Users\Joy\AppData\Roaming\npm\node_modules\bower
75 verbose stack Error: EIO, unlink 'C:\Users\Joy\AppData\Roaming\npm\node_modules\bower\node_modules\decompress-zip\node_modules\touch\node_modules\nopt\LICENSE'
75 verbose stack     at Error (native)
76 verbose cwd C:\Users\Joy\MobileApps
77 error Windows_NT 6.1.7601
78 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "bower"
79 error node v0.12.5
80 error npm  v2.11.2
81 error path C:\Users\Joy\AppData\Roaming\npm\node_modules\bower\node_modules\decompress-zip\node_modules\touch\node_modules\nopt\LICENSE
82 error code EIO
83 error errno -4070
84 error EIO, unlink 'C:\Users\Joy\AppData\Roaming\npm\node_modules\bower\node_modules\decompress-zip\node_modules\touch\node_modules\nopt\LICENSE'
85 error If you need help, you may report this error at:
85 error     <https://github.com/npm/npm/issues>
86 verbose exit [ -4070, true ]
87 verbose unbuild node_modules\bower
88 silly gentlyRm C:\Users\Joy\AppData\Roaming\npm\node_modules\bower is being purged from base C:\Users\Joy\AppData\Roaming\npm
89 verbose gentlyRm don't care about contents; nuking C:\Users\Joy\AppData\Roaming\npm\node_modules\bower
90 silly vacuum-fs purging C:\Users\Joy\AppData\Roaming\npm\node_modules\bower
91 error error rolling back Error: EIO, unlink 'C:\Users\Joy\AppData\Roaming\npm\node_modules\bower\node_modules\decompress-zip\node_modules\touch\node_modules\nopt\LICENSE'
91 error error rolling back     at Error (native)
91 error error rolling back  { [Error: EIO, unlink 'C:\Users\Joy\AppData\Roaming\npm\node_modules\bower\node_modules\decompress-zip\node_modules\touch\node_modules\nopt\LICENSE']
91 error error rolling back   errno: -4070,
91 error error rolling back   code: 'EIO',
91 error error rolling back   path: 'C:\\Users\\Joy\\AppData\\Roaming\\npm\\node_modules\\bower\\node_modules\\decompress-zip\\node_modules\\touch\\node_modules\\nopt\\LICENSE' }

Thanks! any help will be appreciated.

**Comment by KenanY** [comment]
@JoyNAGInc From previous issues where I have seen `EIO`:

> `EIO` is a low-level Node / libuv / libc error indicating that something is seriously wrong with the running OS's disk I/O. If you can, try restarting the instance and see if the problem persists. This error is not raised by `npm` itself, so if that doesn't fix it, take a look at your Node installation.

**Comment by JoyNAGInc** [comment]
Thanks Kenan,

 I will give it a try.

On Tue, Sep 29, 2015 at 9:37 PM, Kenan Yildirim <notifications@github.com>
wrote:

> @JoyNAGInc <https://github.com/JoyNAGInc> From previous issues where I
> have seen EIO:
>
> EIO is a low-level Node / libuv / libc error indicating that something is
> seriously wrong with the running OS's disk I/O. If you can, try restarting
> the instance and see if the problem persists. This error is not raised by
> npm itself, so if that doesn't fix it, take a look at your Node
> installation.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/npm/npm/issues/9787#issuecomment-144279733>.
>



-- 
*Joy O. Ogbanje*

NAG, Inc
Phone: (213) 625-7636   Cell: (213) 718-8303
355 South Grand Avenue, Suite 2450, Los Angeles, California 90071

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.

**Comment by JoyNAGInc** [comment]
I tried what Kenan, suggested but it didn't work so I went a different
route. Thanks though!


On Wed, Nov 4, 2015 at 4:17 PM, Ernie Salazar <notifications@github.com>
wrote:

> Closed #9787 <https://github.com/npm/npm/issues/9787>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/npm/npm/issues/9787#event-455173111>.
>



-- 
*Joy O. Ogbanje*

NAG, Inc
Phone: (213) 625-7636   Cell: (213) 718-8303
355 South Grand Avenue, Suite 2450, Los Angeles, California 90071
