### ISSUE TITLE
window xp install nodejs 4.1.1 appear some things error,how to solve it

### ISSUE THREAD

**Issue by fyatao** [npm/npm#9788]
npm ERR! addLocal Could not install C:\Documents and Settings\Adminis
npm ERR! Windows_NT 5.1.2600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program File
node_modules\\npm\\bin\\npm-cli.js" "install" "?"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! path C:\Documents and Settings\Administrator\?
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'C:\Documents
gs\Administrator\?'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Documents and Settings\Administrator\npm-debug.log

**Comment by KenanY** [comment]
@fyatao Why are you running

```
npm install ?
```

that is, telling `npm` to install simply the question mark? What behavior are you expecting to happen?

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.
