### ISSUE TITLE
Installing Shout-irc error

### ISSUE THREAD

**Issue by pingpong1109** [npm/npm#9789]
This error seems more like a npm issue because it does it for other modules as well.

sudo npm install -g shout                                   npm http GET https://registry.npmjs.org/bcrypt-nodejs/0.0.3
npm http GET https://registry.npmjs.org/cheerio
npm http GET https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/event-stream
npm http GET https://registry.npmjs.org/express
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/moment
npm http GET https://registry.npmjs.org/read
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/slate-irc
npm http GET https://registry.npmjs.org/socket.io
npm http 304 https://registry.npmjs.org/express
npm http 304 https://registry.npmjs.org/commander
npm http 304 https://registry.npmjs.org/event-stream
npm http 304 https://registry.npmjs.org/bcrypt-nodejs/0.0.3
npm http 304 https://registry.npmjs.org/cheerio
npm http 304 https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/moment
npm ERR! Error: No compatible version found: express@'^4.9.5'
npm ERR! Valid install targets:
npm ERR! ["0.14.0","0.14.1","1.0.0","1.0.1","1.0.2","1.0.3","1.0.4","1.0.5","1.0.6","1.0.7","1.0.8","2.0.0","2.1.0","2.1.1","2.2.0","2.2.1","2.2.2","2.3.0","2.3.1","2.3.2","2.3.3","2.3.4","2.3.5","2.3.6","2.3.7","2.3.8","2.3.9","2.3.10","2.3.11","2.3.12","2.4.0","2.4.1","2.4.2","2.4.3","2.4.4","2.4.5","2.4.6","2.4.7","2.5.0","2.5.1","2.5.2","2.5.3","2.5.4","2.5.5","2.5.6","2.5.7","2.5.8","2.5.9","2.5.10","2.5.11","3.0.0","3.0.1","3.0.2","3.0.3","3.0.4","3.0.5","3.0.6","3.1.0","3.1.1","3.1.2","3.2.0","3.2.1","3.2.2","3.2.3","3.2.4","3.2.5","3.2.6","3.3.0","3.3.1","3.3.2","3.3.3","3.3.4","3.3.5","3.3.6","1.0.0-beta","1.0.0-beta2","1.0.0-rc","1.0.0-rc2","1.0.0-rc3","1.0.0-rc4","2.0.0-beta","2.0.0-beta2","2.0.0-beta3","2.0.0-rc","2.0.0-rc2","2.0.0-rc3","3.0.0-alpha1","3.0.0-alpha2","3.0.0-alpha3","3.0.0-alpha4","3.0.0-alpha5","3.0.0-beta1","3.0.0-beta2","3.0.0-beta3","3.0.0-beta4","3.0.0-beta6","3.0.0-beta7","3.0.0-rc1","3.0.0-rc2","3.0.0-rc3","3.0.0-rc4","3.0.0-rc5","3.3.7","3.3.8","3.4.0","3.4.1","3.4.2","3.4.3","3.4.4","3.4.5","3.4.6","3.4.7","3.4.8","4.0.0-rc1","4.0.0-rc2","3.5.0","4.0.0-rc3","4.0.0-rc4","3.5.1","4.0.0","3.5.2","4.1.0","4.1.1","3.5.3","4.1.2","3.6.0","4.2.0","3.7.0","3.8.0","4.3.0","4.3.1","3.8.1","4.3.2","3.9.0","4.4.0","4.4.1","3.10.0","3.10.1","3.10.2","3.10.3","3.10.4","4.4.2","3.10.5","4.4.3","3.11.0","4.4.4","3.12.0","3.12.1","4.4.5","3.13.0","4.5.0","4.5.1","3.14.0","4.6.0","4.6.1","3.15.0","4.7.0","3.15.1","4.7.1","3.15.2","4.7.2","4.7.3","3.15.3","4.7.4","3.16.0","4.8.0","3.16.1","4.8.1","3.16.2","4.8.2","3.16.3","3.16.4","4.8.3","3.16.5","3.16.6","4.8.4","3.16.7","4.8.5","3.16.8","4.8.6","3.16.9","4.8.7","3.16.10","4.8.8","3.17.0","3.17.1","4.9.0","3.17.2","4.9.1","4.9.2","3.17.3","4.9.3","3.17.4","4.9.4","3.17.5","4.9.5","3.17.6","3.17.7","4.9.6","4.9.7","3.17.8","4.9.8","3.18.0","3.18.1","4.10.0","3.18.2","4.10.1","5.0.0-alpha.1","3.18.3","4.10.2","3.18.4","4.10.3","4.10.4","4.10.5","3.18.5","3.18.6","4.10.6","4.10.7","3.19.0","4.10.8","4.11.0","3.19.1","4.11.1","3.19.2","4.11.2","3.20.0","4.12.0","3.20.1","4.12.1","4.12.2","3.20.2","4.12.3","3.20.3","4.12.4","3.21.0","4.13.0","3.21.1","4.13.1","5.0.0-alpha.2","3.21.2","4.13.2","4.13.3"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:679:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:594:10
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:297:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.12.26-rpi-aufs
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "shout"
npm ERR! cwd /root
npm ERR! node -v v0.8.21
npm ERR! npm -v 1.2.11
npm http 304 https://registry.npmjs.org/slate-irc
npm http 304 https://registry.npmjs.org/read
npm http 304 https://registry.npmjs.org/request
npm http 304 https://registry.npmjs.org/socket.io
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm ERR! not ok code 0

**Comment by KenanY** [comment]
@pingpong1109 `npm@1.2` does not recognize the `^` semver operator you see here:

```
npm ERR! Error: No compatible version found: express@'^4.9.5'
```

hence it fails to find a valid version to install. The solution is to [upgrade `npm`](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) (I know I already told you this in https://github.com/npm/npm/issues/9784, but really this would solve your issue).

**Comment by pingpong1109** [comment]
I do this follow command npm install -g npm@latest and I get this error


npm http GET https://registry.npmjs.org/npm
npm http 304 https://registry.npmjs.org/npm
npm http GET https://registry.npmjs.org/npm/-/npm-3.3.4.tgz
npm http 200 https://registry.npmjs.org/npm/-/npm-3.3.4.tgz
npm ERR! tar pack Error reading /root/tmp/npm-22017/1443654404337-0.06953159254044294/package
npm ERR! TypeError: Cannot call method 'filter' of undefined
npm ERR!     at Packer.IgnoreReader.addIgnoreRules (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/ignore.js:148:13)
npm ERR!     at Packer.IgnoreReader.addIgnoreFile (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/ignore.js:133:10)
npm ERR!     at fs.readFile (fs.js:176:14)
npm ERR!     at Object.oncomplete (fs.js:297:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.12.26-rpi-aufs
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "npm@latest"
npm ERR! cwd /root
npm ERR! node -v v0.8.21
npm ERR! npm -v 1.2.11
npm ERR! type non_object_property_call
npm ERR! addLocalDirectory Could not pack "/root/tmp/npm-22017/1443654404337-0.06953159254044294/package" to "/root/.npm/npm/3.3.4/package.tgz"
npm ERR! SyntaxError: Unexpected end of input
npm ERR!     at Object.parse (native)
npm ERR!     at Packer.readRules (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/fstream-npm.js:189:33)
npm ERR!     at Packer.IgnoreReader.addIgnoreFile (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/ignore.js:132:22)
npm ERR!     at fs.readFile (fs.js:176:14)
npm ERR!     at Object.oncomplete (fs.js:297:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.12.26-rpi-aufs
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "npm@latest"
npm ERR! cwd /root
npm ERR! node -v v0.8.21
npm ERR! npm -v 1.2.11
npm ERR! file /root/tmp/npm-22017/1443654404337-0.06953159254044294/package/node_modules/read-package-tree/test/fixtures/bad/package.json
npm ERR! path /root/tmp/npm-22017/1443654404337-0.06953159254044294/package/node_modules/read-package-tree/test/fixtures/bad
npm ERR! type unexpected_eos
npm ERR! fstream_path /root/tmp/npm-22017/1443654404337-0.06953159254044294/package/node_modules/read-package-tree/test/fixtures/bad
npm ERR! fstream_type Directory
npm ERR! fstream_class Packer
npm ERR! fstream_stack Packer.readRules (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/fstream-npm.js:192:10)
npm ERR! fstream_stack Packer.IgnoreReader.addIgnoreFile (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/ignore.js:132:22)
npm ERR! fstream_stack fs.readFile (fs.js:176:14)
npm ERR! fstream_stack Object.oncomplete (fs.js:297:15)
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm ERR! not ok code 0

**Comment by KenanY** [comment]
@pingpong1109 Oh, I don't think `npm@1.2` is capable of upgrading all the way to `npm@3`. If:

``` sh
npm install -g npm@1.4
```

does not work then I would suggest upgrading Node.js instead since it bundles `npm`.

**Comment by pingpong1109** [comment]
Ok that worked. Thank you.

**Comment by ehsalazar** [comment]
It sounds like you were successful in upgrading. I'll close this for now as we’re trying to clean up some solved issues. We’ll be happy to reopen if necessary.
