### ISSUE TITLE
Often getting shasum check failed

### ISSUE THREAD

**Issue by cristim** [npm/npm#9791]
I keep getting these errors pretty much almost on a daily basis.
```
npm ERR! Linux 3.14.48-33.39.amzn1.x86_64
npm ERR! argv "/opt/nodejs/bin/node" "/opt/nodejs/bin/npm" "update"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! shasum check failed for /tmp/npm-121-7ec609c3/registry.npmjs.org/selenium-server/-/selenium-server-2.47.1.tgz
npm ERR! Expected: 624eeb1a38df2c57eff1f3620ede4a3cad2ed349
npm ERR! Actual:   906f5612ff4a2f90fbaac992a2b5fd99196ad6d2
npm ERR! From:     https://registry.npmjs.org/selenium-server/-/selenium-server-2.47.1.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
```

I can provide more debugging information upon demand.

The issues are happening on different AWS instances(recycled nightly to a fresh state) running in US-East-1.

**Comment by teleological** [comment]
Check to see if npm is actually downloading a valid tarball. Kaspersky thinks a file in the Selenium jar (hudsucker.exe) is infected by a virus (see https://code.google.com/p/selenium/issues/detail?id=789) so you may be getting an error page and not a tarball if you're using a proxy that uses kasperky.

**Comment by ehsalazar** [comment]
@cristim Is this still an issue for you? What happens if you give `npm cache clean` a try?

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.

**Comment by teleological** [comment]
@ehsalazar I can confirm this still happens. However, the problem seems specific to eugeneware/selenium-server
```
$ npm install selenium-server
npm http GET http://registry.npmjs.org/selenium-server
npm http 200 http://registry.npmjs.org/selenium-server
npm http GET http://registry.npmjs.org/selenium-server/-/selenium-server-2.48.3.tgz
npm http 200 http://registry.npmjs.org/selenium-server/-/selenium-server-2.48.3.tgz
npm ERR! Error: shasum check failed for /var/folders/4c/tqywkh7j7z79smwwwfxqd61hjl_zvk/T/npm-49616-Zs7SfSMy/1449874862626-0.5279354385565966/tmp.tgz
npm ERR! Expected: 965b700d5a419028537eb937aee94d93832a31dc
npm ERR! Actual:   c97c128d311b83740a6528372b9e32a8fb53f070
```
