### ISSUE TITLE
parser.generated.js

### ISSUE THREAD

**Issue by samox1n** [npm/npm#9792]
Hi

node 0.10.25
npm 3.3.4

Cannot find module parser.generated.js

npm update, npm remove not working

**Comment by KenanY** [comment]
@samox1n Is `npm` throwing this error? Is there a `npm-debug.log` that you can upload as a [gist](https://gist.github.com/)? If not, then I am uncertain as to whether or not this is an issue with `npm` (and I am not sure then how I can help).

**Comment by samox1n** [comment]
https://gist.github.com/samox1n/ecde76f475df87ee30c9

**Comment by samox1n** [comment]
https://gist.github.com/samox1n/ecde76f475df87ee30c9
