### ISSUE TITLE
Can't npm install package --save, npm ERR

### ISSUE THREAD

**Issue by VipedL** [npm/npm#9793]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'sails-mongo',
1 verbose cli   '--save' ]
2 info using npm@3.3.4
3 info using node@v4.0.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData sails-mongo
8 silly fetchNamedPackageData sails-mongo
9 silly mapToRegistry name sails-mongo
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/sails-mongo
13 verbose request uri https://registry.npmjs.org/sails-mongo
14 verbose request no auth needed
15 info attempt registry request try #1 at 2:40:23 PM
16 verbose request id 438b42a8c26f9702
17 verbose etag "V29MO3US2OXWI4LGSUHKRG8N"
18 http request GET https://registry.npmjs.org/sails-mongo
19 http 304 https://registry.npmjs.org/sails-mongo
20 verbose headers { date: 'Wed, 30 Sep 2015 11:40:24 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   'cache-control': 'max-age=60',
20 verbose headers   etag: '"V29MO3US2OXWI4LGSUHKRG8N"',
20 verbose headers   age: '0',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-fra1225-FRA',
20 verbose headers   'x-cache': 'HIT',
20 verbose headers   'x-cache-hits': '1',
20 verbose headers   'x-timer': 'S1443613224.068981,VS0,VE377',
20 verbose headers   vary: 'Accept' }
21 silly get cb [ 304,
21 silly get   { date: 'Wed, 30 Sep 2015 11:40:24 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     'cache-control': 'max-age=60',
21 silly get     etag: '"V29MO3US2OXWI4LGSUHKRG8N"',
21 silly get     age: '0',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-fra1225-FRA',
21 silly get     'x-cache': 'HIT',
21 silly get     'x-cache-hits': '1',
21 silly get     'x-timer': 'S1443613224.068981,VS0,VE377',
21 silly get     vary: 'Accept' } ]
22 verbose etag https://registry.npmjs.org/sails-mongo from cache
23 verbose get saving sails-mongo to /home/ville/.npm/registry.npmjs.org/sails-mongo/.cache.json
24 silly install normalizeTree
25 verbose stack TypeError: Cannot set property 'fs-extra' of undefined
25 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/deps.js:94:36
25 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/dezalgo/dezalgo.js:17:12
25 verbose stack     at RawTask.call (/usr/local/lib/node_modules/npm/node_modules/asap/asap.js:40:19)
25 verbose stack     at flush (/usr/local/lib/node_modules/npm/node_modules/asap/raw.js:50:29)
25 verbose stack     at doNTCallback0 (node.js:407:9)
25 verbose stack     at process._tickCallback (node.js:336:13)
26 verbose cwd /home/ville/Programming/nodejs/activityOverlord2
27 error Linux 3.16.0-38-generic
28 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "sails-mongo" "--save"
29 error node v4.0.0
30 error npm  v3.3.4
31 error Cannot set property 'fs-extra' of undefined
32 error If you need help, you may report this error at:
32 error     <https://github.com/npm/npm/issues>
33 verbose exit [ 1, true ]

**Comment by daniel79** [comment]
Having the same issue on El Capitan

**Comment by daniel79** [comment]
npm clean cache
rm -rf node_modules

worked for me

**Comment by niallobrien** [comment]
Thanks @daniel79, that worked for me too.

**Comment by KenanY** [comment]
@VipedL Are you still experiencing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
