### ISSUE TITLE
npm install -g strongloop  failed

### ISSUE THREAD

**Issue by miukki** [npm/npm#9794]
please help recognize to me reason. 
why its failed: 

npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "strongloop"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1

npm ERR! shasum check failed for /var/folders/sh/bttln6pd6nv82v9g6l9dvv140000gn/T/npm-35465-629a7551/registry.npmjs.org/strong-arc/-/strong-arc-1.8.1.tgz
npm ERR! Expected: a089abc0e76b8810d7b8e09e701e1137bafd1e79
npm ERR! Actual:   459157e4d097ae8e171663b55a10d00bb210809f
npm ERR! From:     https://registry.npmjs.org/strong-arc/-/strong-arc-1.8.1.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/miukki/Sites/magazine-app/npm-debug.log

**Comment by miukki** [comment]
upload file form doesnt work.

**Comment by KenanY** [comment]
@miukki Have you tried running `npm cache clean`?

**Comment by miukki** [comment]
i got it it is about checksum.. broken tgz file
