### ISSUE TITLE
npm install grunt-contrib-copy --save-dev

### ISSUE THREAD

**Issue by ginere** [npm/npm#9795]
npm install grunt-contrib-copy --save-dev

npm ERR! Darwin 13.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "grunt-contrib-copy" "--save-dev"
npm ERR! node v4.1.1
npm ERR! npm  v3.3.5

npm ERR! Cannot read property 'localeCompare' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ventura/projects/video2/installation-root/data/git/video2-skins/black/npm-debug.log
[~/projects/black]$ npm install grunt-contrib-copy --save-dev
npm ERR! Darwin 13.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "grunt-contrib-copy" "--save-dev"
npm ERR! node v4.1.1
npm ERR! npm  v3.3.5

npm ERR! Cannot read property 'localeCompare' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ventura/projects/video2/installation-root/data/git/video2-skins/black/npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'grunt-contrib-copy',
1 verbose cli   '--save-dev' ]
2 info using npm@3.3.5
3 info using node@v4.1.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData grunt-contrib-copy
8 silly fetchNamedPackageData grunt-contrib-copy
9 silly mapToRegistry name grunt-contrib-copy
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/grunt-contrib-copy
13 verbose request uri https://registry.npmjs.org/grunt-contrib-copy
14 verbose request no auth needed
15 info attempt registry request try #1 at 3:50:40 PM
16 verbose request id 7572c024976d1ef7
17 verbose etag "DC5L3LOIQGIW96KNDTUMX15M5"
18 http request GET https://registry.npmjs.org/grunt-contrib-copy
19 http 304 https://registry.npmjs.org/grunt-contrib-copy
20 verbose headers { date: 'Wed, 30 Sep 2015 13:50:41 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   'cache-control': 'max-age=60',
20 verbose headers   etag: '"DC5L3LOIQGIW96KNDTUMX15M5"',
20 verbose headers   age: '11',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-ams4135-AMS',
20 verbose headers   'x-cache': 'HIT',
20 verbose headers   'x-cache-hits': '1',
20 verbose headers   'x-timer': 'S1443621041.176700,VS0,VE0',
20 verbose headers   vary: 'Accept' }
21 silly get cb [ 304,
21 silly get   { date: 'Wed, 30 Sep 2015 13:50:41 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     'cache-control': 'max-age=60',
21 silly get     etag: '"DC5L3LOIQGIW96KNDTUMX15M5"',
21 silly get     age: '11',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-ams4135-AMS',
21 silly get     'x-cache': 'HIT',
21 silly get     'x-cache-hits': '1',
21 silly get     'x-timer': 'S1443621041.176700,VS0,VE0',
21 silly get     vary: 'Accept' } ]
22 verbose etag https://registry.npmjs.org/grunt-contrib-copy from cache
23 verbose get saving grunt-contrib-copy to /Users/ventura/.npm/registry.npmjs.org/grunt-contrib-copy/.cache.json
24 silly install normalizeTree
25 silly loadCurrentTree Finishing
26 silly loadIdealTree Starting
27 silly install loadIdealTree
28 silly cloneCurrentTree Starting
29 silly install cloneCurrentTreeToIdealTree
30 silly cloneCurrentTree Finishing
31 silly loadShrinkwrap Starting
32 silly install loadShrinkwrap
33 silly loadShrinkwrap Finishing
34 silly loadAllDepsIntoIdealTree Starting
35 silly install loadAllDepsIntoIdealTree
36 silly resolveWithNewModule grunt-contrib-copy@0.8.1 checking installable status
37 silly cache add args [ 'grunt-contrib-copy', null ]
38 verbose cache add spec grunt-contrib-copy
39 silly cache add parsed spec Result {
39 silly cache add   raw: 'grunt-contrib-copy',
39 silly cache add   scope: null,
39 silly cache add   name: 'grunt-contrib-copy',
39 silly cache add   rawSpec: '',
39 silly cache add   spec: '*',
39 silly cache add   type: 'range' }
40 silly addNamed grunt-contrib-copy@*
41 verbose addNamed "*" is a valid semver range for grunt-contrib-copy
42 silly addNameRange { name: 'grunt-contrib-copy', range: '*', hasData: false }
43 silly mapToRegistry name grunt-contrib-copy
44 silly mapToRegistry using default registry
45 silly mapToRegistry registry https://registry.npmjs.org/
46 silly mapToRegistry uri https://registry.npmjs.org/grunt-contrib-copy
47 verbose addNameRange registry:https://registry.npmjs.org/grunt-contrib-copy not in flight; fetching
48 verbose get https://registry.npmjs.org/grunt-contrib-copy not expired, no request
49 silly addNameRange number 2 { name: 'grunt-contrib-copy', range: '*', hasData: true }
50 silly addNameRange versions [ 'grunt-contrib-copy',
50 silly addNameRange   [ '0.2.0',
50 silly addNameRange     '0.2.1',
50 silly addNameRange     '0.2.2',
50 silly addNameRange     '0.2.3',
50 silly addNameRange     '0.2.4',
50 silly addNameRange     '0.3.0',
50 silly addNameRange     '0.3.1',
50 silly addNameRange     '0.3.2',
50 silly addNameRange     '0.4.0',
50 silly addNameRange     '0.4.1',
50 silly addNameRange     '0.5.0',
50 silly addNameRange     '0.6.0',
50 silly addNameRange     '0.7.0',
50 silly addNameRange     '0.8.0',
50 silly addNameRange     '0.8.1',
50 silly addNameRange     '0.4.0-rc7' ] ]
51 silly addNamed grunt-contrib-copy@0.8.1
52 verbose addNamed "0.8.1" is a plain semver version for grunt-contrib-copy
53 silly cache afterAdd grunt-contrib-copy@0.8.1
54 verbose afterAdd /Users/ventura/.npm/grunt-contrib-copy/0.8.1/package/package.json not in flight; writing
55 verbose afterAdd /Users/ventura/.npm/grunt-contrib-copy/0.8.1/package/package.json written
56 silly fetchNamedPackageData file-sync-cmp
57 silly mapToRegistry name file-sync-cmp
58 silly mapToRegistry using default registry
59 silly mapToRegistry registry https://registry.npmjs.org/
60 silly mapToRegistry uri https://registry.npmjs.org/file-sync-cmp
61 verbose request uri https://registry.npmjs.org/file-sync-cmp
62 verbose request no auth needed
63 info attempt registry request try #1 at 3:50:46 PM
64 verbose etag "7NWSRDSAW0M781QIEMX5NYY63"
65 http request GET https://registry.npmjs.org/file-sync-cmp
66 http 304 https://registry.npmjs.org/file-sync-cmp
67 verbose headers { date: 'Wed, 30 Sep 2015 13:50:47 GMT',
67 verbose headers   via: '1.1 varnish',
67 verbose headers   'cache-control': 'max-age=60',
67 verbose headers   etag: '"7NWSRDSAW0M781QIEMX5NYY63"',
67 verbose headers   age: '29',
67 verbose headers   connection: 'keep-alive',
67 verbose headers   'x-served-by': 'cache-ams4123-AMS',
67 verbose headers   'x-cache': 'HIT',
67 verbose headers   'x-cache-hits': '2',
67 verbose headers   'x-timer': 'S1443621047.233028,VS0,VE0',
67 verbose headers   vary: 'Accept' }
68 silly get cb [ 304,
68 silly get   { date: 'Wed, 30 Sep 2015 13:50:47 GMT',
68 silly get     via: '1.1 varnish',
68 silly get     'cache-control': 'max-age=60',
68 silly get     etag: '"7NWSRDSAW0M781QIEMX5NYY63"',
68 silly get     age: '29',
68 silly get     connection: 'keep-alive',
68 silly get     'x-served-by': 'cache-ams4123-AMS',
68 silly get     'x-cache': 'HIT',
68 silly get     'x-cache-hits': '2',
68 silly get     'x-timer': 'S1443621047.233028,VS0,VE0',
68 silly get     vary: 'Accept' } ]
69 verbose etag https://registry.npmjs.org/file-sync-cmp from cache
70 verbose get saving file-sync-cmp to /Users/ventura/.npm/registry.npmjs.org/file-sync-cmp/.cache.json
71 silly resolveWithNewModule file-sync-cmp@0.1.1 checking installable status
72 silly cache add args [ 'file-sync-cmp@^0.1.0', null ]
73 verbose cache add spec file-sync-cmp@^0.1.0
74 silly cache add parsed spec Result {
74 silly cache add   raw: 'file-sync-cmp@^0.1.0',
74 silly cache add   scope: null,
74 silly cache add   name: 'file-sync-cmp',
74 silly cache add   rawSpec: '^0.1.0',
74 silly cache add   spec: '>=0.1.0 <0.2.0',
74 silly cache add   type: 'range' }
75 silly addNamed file-sync-cmp@>=0.1.0 <0.2.0
76 verbose addNamed ">=0.1.0 <0.2.0" is a valid semver range for file-sync-cmp
77 silly addNameRange { name: 'file-sync-cmp',
77 silly addNameRange   range: '>=0.1.0 <0.2.0',
77 silly addNameRange   hasData: false }
78 silly mapToRegistry name file-sync-cmp
79 silly mapToRegistry using default registry
80 silly mapToRegistry registry https://registry.npmjs.org/
81 silly mapToRegistry uri https://registry.npmjs.org/file-sync-cmp
82 verbose addNameRange registry:https://registry.npmjs.org/file-sync-cmp not in flight; fetching
83 verbose get https://registry.npmjs.org/file-sync-cmp not expired, no request
84 silly addNameRange number 2 { name: 'file-sync-cmp', range: '>=0.1.0 <0.2.0', hasData: true }
85 silly addNameRange versions [ 'file-sync-cmp', [ '0.1.0', '0.1.1' ] ]
86 silly addNamed file-sync-cmp@0.1.1
87 verbose addNamed "0.1.1" is a plain semver version for file-sync-cmp
88 silly cache afterAdd file-sync-cmp@0.1.1
89 verbose afterAdd /Users/ventura/.npm/file-sync-cmp/0.1.1/package/package.json not in flight; writing
90 verbose afterAdd /Users/ventura/.npm/file-sync-cmp/0.1.1/package/package.json written
91 verbose stack TypeError: Cannot read property 'localeCompare' of undefined
91 verbose stack     at installOrder (/usr/local/lib/node_modules/npm/lib/install/deps.js:241:32)
91 verbose stack     at Array.sort (native)
91 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/deps.js:240:27
91 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
91 verbose stack     at resolveWithExistingModule (/usr/local/lib/node_modules/npm/lib/install/deps.js:377:3)
91 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/deps.js:347:5
91 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
91 verbose stack     at Array.forEach (native)
91 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
91 verbose stack     at Array.forEach (native)
92 verbose cwd /Users/ventura/projects/video2/installation-root/data/git/video2-skins/black
93 error Darwin 13.3.0
94 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "grunt-contrib-copy" "--save-dev"
95 error node v4.1.1
96 error npm  v3.3.5
97 error Cannot read property 'localeCompare' of undefined
98 error If you need help, you may report this error at:
98 error     <https://github.com/npm/npm/issues>
99 verbose exit [ 1, true ]

**Comment by ravishivt** [comment]
See https://github.com/npm/npm/issues/9766

**Comment by iarna** [comment]
Closing as a duplicate (fix is in the process of landing!)
