### ISSUE TITLE
npm install chai --dev --save (invalid syntax) gets npm into a invalid state

### ISSUE THREAD

**Issue by infinitflow** [npm/npm#9797]
This is not valid syntax. I made this mistake as a newbie to npm but it could happen to others too. The proper syntax is --save-dev.

The node_modules folder went from around 30MB to over 4GB and the npm process was taking almost all the CPU.

**Comment by KenanY** [comment]
@infinitflow Right, if you use the `--dev` flag (even by accident), you are going to have a bad time :)

The flag was deprecated in https://github.com/npm/npm/pull/9024. What change are you requesting here?

**Comment by infinitflow** [comment]
Would it be possible to prevent the bad syntax and show a message like "did you man to use --save-dev flag instead?" 

That way the machine won't go into what seems an infinite loop taking almost all processing power and disk space until users quit npm.

Thanks
