### ISSUE TITLE
npm install nightwatch -g - Errors

### ISSUE THREAD

**Issue by Dimu4** [npm/npm#9800]
Just installed latest node and npm, when i'm trying to install nightwatch getting errors:

npm ERR! tar.unpack untar error /Users/dkostiu/.npm/nightwatch/0.8.3/package.tgz
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "nightwatch" "-g"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! path /usr/local/lib/node_modules/nightwatch
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir

npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/nightwatch'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/nightwatch']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules/nightwatch',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/nightwatch',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:35:25',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:47:53',
npm ERR!      'FSReqWrap.oncomplete (fs.js:82:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dkostiu/npm-debug.log
L-SB8W3DCFD5-M:~ dkostiu$ npm cache clean
L-SB8W3DCFD5-M:~ dkostiu$ npm install nightwatch -g
npm ERR! tar.unpack untar error /Users/dkostiu/.npm/nightwatch/0.8.3/package.tgz
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "nightwatch" "-g"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! path /usr/local/lib/node_modules/nightwatch
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir

npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/nightwatch'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/nightwatch']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules/nightwatch',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/nightwatch',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:35:25',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:47:53',
npm ERR!      'FSReqWrap.oncomplete (fs.js:82:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dkostiu/npm-debug.log
L-SB8W3DCFD5-M:~ dkostiu$ clear

L-SB8W3DCFD5-M:~ dkostiu$ npm config set ca=""
L-SB8W3DCFD5-M:~ dkostiu$ npm config set registry=http://registry.npmjs.org
L-SB8W3DCFD5-M:~ dkostiu$ npm install nightwatch -g
npm ERR! tar.unpack untar error /Users/dkostiu/.npm/nightwatch/0.8.3/package.tgz
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "nightwatch" "-g"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! path /usr/local/lib/node_modules/nightwatch
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir

npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/nightwatch'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/nightwatch']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules/nightwatch',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/nightwatch',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:35:25',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:47:53',
npm ERR!      'FSReqWrap.oncomplete (fs.js:82:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dkostiu/npm-debug.log

**Comment by Dimu4** [comment]
Issue resolved when i ran it as administrator.

**Comment by KenanY** [comment]
@Dimu4 Yeah, since you don't seem to have permission to write to `/usr/local/`. you will need to use `sudo` (or you can follow [this guide](https://docs.npmjs.com/getting-started/fixing-npm-permissions) to have your global modules install into a directory your user owns).

**Comment by ehsalazar** [comment]
Good to hear. I'll close this for now as we’re trying to clean up some solved issues. We’ll be happy to reopen if necessary.

**Comment by prasetyo531** [comment]
hello guys, need helh

 i have run npm install [-g] nightwatch as administrator but still error, which is code typed sudo npm install [-g] nightwatch

npm ERR! addLocal Could not install /usr/local/bin/[-g]
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/Cellar/node/7.7.3/bin/node" "/usr/local/bin/npm" "install" "[-g]" "nightwatch"
npm ERR! node v7.7.3
npm ERR! npm  v4.1.2
npm ERR! path /usr/local/bin/[-g]
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/usr/local/bin/[-g]'
npm ERR! enoent ENOENT: no such file or directory, open '/usr/local/bin/[-g]'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/bin/npm-debug.log

**Comment by KenanY** [comment]
@prasetyo531 Remove the `[` and `]` from your command.
