### ISSUE TITLE
npm install failing with errors

### ISSUE THREAD

**Issue by pvasi** [npm/npm#9801]
I see this in the npm-debug.log file 

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install' ]
2 info using npm@1.2.0
3 info using node@v0.8.17
4 verbose read json /Users/p0vasir/package.json
5 error install Couldn't read dependencies
6 error Error: ENOENT, open '/Users/p0vasir/package.json'
7 error If you need help, you may report this log at:
7 error     <http://github.com/isaacs/npm/issues>
7 error or email it to:
7 error     <npm-@googlegroups.com>
8 error System Darwin 12.6.0
9 error command "node" "/usr/local/bin/npm" "install"
10 error cwd /Users/p0vasir
11 error node -v v0.8.17
12 error npm -v 1.2.0
13 error path /Users/p0vasir/package.json
14 error code ENOENT
15 error errno 34
16 verbose exit [ 34, true ]

**Comment by KenanY** [comment]
@pvasi Does `/Users/p0vasir/package.json` exist?

(I should also implore you to [upgrade `npm`](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm))

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.
