### ISSUE TITLE
can you have custom prerelease tags and does npm / semver support them?

### ISSUE THREAD

**Issue by bojand** [npm/npm#9802]
For example lets say I have my own package `foobar`, and I've published versions `1.0.0-pre.0` and `1.0.0-blue.0`. In a `package.json` I have:

```
"dependencies": {
  "foobar": "~1.0.0-blue.0"
},
```

when I `npm i` `foobar@1.0.0-pre.0` gets pulled down. I expected `foobar@1.0.0-blue.0` to be installed. `^1.0.0-blue.0` exhibits same behavior. Is this type of thing supported?

Thanks.

**Comment by KenanY** [comment]
@bojand I believe this is because `1.0.0-pre.0` is considered to be greater than `1.0.0-blue.0`:

``` javascript
const semver = require('semver');

semver.maxSatisfying(['1.0.0-blue.0', '1.0.0-pre.0'], '~1.0.0-blue.0');
// => '1.0.0-pre.0'
```
