### ISSUE TITLE
 npm install -g express-generator error on windows 7 

### ISSUE THREAD

**Issue by muhabalwan** [npm/npm#9806]
I am new to node.js npm and all of its related stuff.
I am following up some tutorials and in one of them it was mentioned t install express-generator.
now when I enter this command  npm install -g express-generator
the following shows: 
__

$ npm install -g express-generator
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files (x86)\nodejs\node.exe" "C:\Program Files (x86)\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "express-generator"
npm ERR! node v4.1.1
npm ERR! npm  v3.3.4

npm ERR! Invalid name: ".node"
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files\Git\npm-debug.log

---

I thought it their might be problems with writing permissions on C:\ Drive 
So my user has full authority on C:\Program Files (x86)\nodejs\node.exe" "C:\Program Files (x86)\nodejs\  using the  iCacls command 
but that did not help ...
Does anyone have any recommendation or advice
![capture](https://cloud.githubusercontent.com/assets/5458873/10215464/eec9707a-6821-11e5-819b-e3c72abaf41e.PNG)
 on how to fix this issue here

**Comment by lsirpa** [comment]
check this manual :) and see how to solve the problem
https://drive.google.com/file/d/0B4-v0059mrAwQTU1dUpQR2hLcEE/view?usp=sharing

**Comment by muhabalwan** [comment]
this would work if I can install on my pass but as it seems I can not instal express-generator at all

**Comment by smartmouse** [comment]
You mentioned that you are using windows 7, are you using a Cygwin environment or a native command prompt?
Do you have the required prereq

**Comment by muhabalwan** [comment]
no, actually I am using native command prompt

On Sun, Oct 4, 2015 at 4:30 AM, smartmouse <notifications@github.com> wrote:

> You mentioned that you are using windows 7, are you using a Cygwin
> environment or a native command prompt?
> Do you have the required prereq
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/npm/npm/issues/9806#issuecomment-145311136>.
>



-- 

*Muhab Alwan.*
*Mob: +49 152 236 325 17*
*Email: alwanmuhab@gmail.com <alwanmuhab@gmail.com>*
*Skype: muhaboo1.*
*LinkedIn: **https://de.linkedin.com/pub/muhab-alwan/30/a12/25
<https://de.linkedin.com/pub/muhab-alwan/30/a12/25>9*

**Comment by smartmouse** [comment]
How did you set up your node environment?
Did you install using their xx.msi?
When you install , did you specify add to PATH?
How come your npm version is 3.x?
The default one that comes with node 4.1.1 should be npm  2.14.4
That may be problematic.
I always use the default one to save myself trouble,s

**Comment by Ingosmar89219** [comment]
hey friends what can i do for this? when im trying to install express in a project of polymer show this error in cmd windows 8
C:\Users\osmarvirux\Documents\messenger>npm install express
express@4.14.0 ..\..\node_modules\express
├── escape-html@1.0.3
├── array-flatten@1.1.1
├── content-type@1.0.2
├── encodeurl@1.0.1
├── merge-descriptors@1.0.1
├── etag@1.7.0
├── methods@1.1.2
├── cookie@0.3.1
├── path-to-regexp@0.1.7
├── cookie-signature@1.0.6
├── utils-merge@1.0.0
├── range-parser@1.2.0
├── vary@1.1.0
├── serve-static@1.11.1
├── content-disposition@0.5.1
├── parseurl@1.3.1
├── fresh@0.3.0
├── depd@1.1.0
├── qs@6.2.0
├── on-finished@2.3.0 (ee-first@1.1.1)
├── finalhandler@0.5.0 (unpipe@1.0.0, statuses@1.3.0)
├── debug@2.2.0 (ms@0.7.1)
├── proxy-addr@1.1.2 (forwarded@0.1.0, ipaddr.js@1.1.1)
├── accepts@1.3.3 (negotiator@0.6.1, mime-types@2.1.12)
├── type-is@1.6.13 (media-typer@0.3.0, mime-types@2.1.12)
└── send@0.14.1 (destroy@1.0.4, statuses@1.3.0, ms@0.7.1, mime@1.3.4, http-error
s@1.5.0)
