### ISSUE TITLE
Error installing grunt and grunt-contrib-clean

### ISSUE THREAD

**Issue by hellboy81** [npm/npm#9808]
npm i grunt@~0.4.1

npm ERR! Linux 3.13.0-63-generic
npm ERR! argv "node" "/usr/local/bin/npm" "i" "grunt@~0.4.1"
npm ERR! node v0.10.30
npm ERR! npm  v3.3.4

npm ERR! Invalid Version: 0.4.0rc8

``` sh
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'i', 'grunt@~0.4.1' ]
2 info using npm@3.3.4
3 info using node@v0.10.30
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData grunt@~0.4.1
8 silly fetchNamedPackageData grunt
9 silly mapToRegistry name grunt
10 silly mapToRegistry using default registry
...
23 verbose get saving grunt to /home/local/.../.npm/.../grunt/.cache.json
24 verbose stack TypeError: Invalid Version: 0.4.0rc8
24 verbose stack     at new SemVer (/usr/local/lib/node_modules/npm/node_modules/semver/semver.js:293:11)
24 verbose stack     at compare (/usr/local/lib/node_modules/npm/node_modules/semver/semver.js:570:10)
24 verbose stack     at rcompare (/usr/local/lib/node_modules/npm/node_modules/semver/semver.js:580:10)
24 verbose stack     at Array.sort (native)
24 verbose stack     at pickVersionFromRegistryDocument (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:111:48)
24 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/iferr/index.js:13:50
24 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/pulse-till-done.js:19:8
24 verbose stack     at saved (/usr/local/lib/node_modules/npm/lib/cache/caching-client.js:168:7)
24 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:210:7
24 verbose stack     at Object.oncomplete (fs.js:107:15)
26 error Linux 3.13.0-63-generic
27 error argv "node" "/usr/local/bin/npm" "i" "grunt@~0.4.1"
28 error node v0.10.30
29 error npm  v3.3.4
30 error Invalid Version: 0.4.0rc8
31 error If you need help, you may report this error at:
31 error     <https://github.com/npm/npm/issues>
32 verbose exit [ 1, true ]
```

 Missing. You might want to install these.
 ◯ grunt-contrib-clean missing                  Registry error Invalid Version: 0.4.0rc6
 ◯ grunt missing                                Registry error Invalid Version: 0.4.0rc8

grunt 
   ?? NPM ERR!  Registry error Invalid Version: 0.4.0rc8

runt-contrib-clean 
  ??  NPM ERR!  Registry error Invalid Version: 0.4.0rc6

**Comment by benurb** [comment]
You might want to clean your local npm cache using `npm cache clean`. If you're using a private npm registry you maybe have to clean its cache, too.

**Comment by bobfields** [comment]
Cache clean doesn't help. It appears to be a semver problem in that it doesn't recognize that as a valid version. Here's a snippet from npm-debug.log:
315 verbose stack TypeError: Invalid Version: 0.4.0rc8
315 verbose stack     at new SemVer (C:\Users\RJF3\AppData\Roaming\npm\node_modules\npm\node_modules\semver\semver.js:293:11)
315 verbose stack     at compare (C:\Users\RJF3\AppData\Roaming\npm\node_modules\npm\node_modules\semver\semver.js:570:10)
315 verbose stack     at rcompare (C:\Users\RJF3\AppData\Roaming\npm\node_modules\npm\node_modules\semver\semver.js:580:10)
315 verbose stack     at Array.sort (native)
315 verbose stack     at pickVersionFromRegistryDocument (C:\Users\RJF3\AppData\Roaming\npm\node_modules\npm\lib\fetch-package-metadata.js:111:48)
315 verbose stack     at C:\Users\RJF3\AppData\Roaming\npm\node_modules\npm\node_modules\iferr\index.js:13:50
315 verbose stack     at C:\Users\RJF3\AppData\Roaming\npm\node_modules\npm\lib\utils\pulse-till-done.js:19:8
315 verbose stack     at saved (C:\Users\RJF3\AppData\Roaming\npm\node_modules\npm\lib\cache\caching-client.js:168:7)
315 verbose stack     at C:\Users\RJF3\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:210:7
315 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
316 verbose cwd D:\Programs\Github\WDPR-UI\generator-wdpr-angular
317 error Windows_NT 6.1.7601
318 error argv "C:\\Programs\\nodejs\\node.exe" 
319 error node v4.1.2
320 error npm  v3.3.5
321 error Invalid Version: 0.4.0rc8

**Comment by benurb** [comment]
According to the SemVer spec `0.4.0rc8` isn't a valid version. Are you using npmjs.org or some other registry?

**Comment by bobfields** [comment]
Looks like an issue with our internal repository (sinopia) which proxies npmjs.org. I was confused because the error was on an external artifact (chalk) with no internally published versions. When I switched npm registry to https://registry.npmjs.org/ everything downloaded OK (though *extremely* slowly compared to npm v2). The internal repository 'npm info chalk versions' shows the same info as npmjs.org, so I need to investigate where the extraneous versions are coming from.

Another snippet:
```
718 silly resolveWithNewModule chalk@1.0.0 checking installable status
719 silly cache add args [ 'chalk@~1.0.0', null ]
720 verbose cache add spec chalk@~1.0.0
721 silly cache add parsed spec Result {
721 silly cache add   raw: 'chalk@~1.0.0',
721 silly cache add   scope: null,
721 silly cache add   name: 'chalk',
721 silly cache add   rawSpec: '~1.0.0',
721 silly cache add   spec: '>=1.0.0 <1.1.0',
721 silly cache add   type: 'range' }
722 silly addNamed chalk@>=1.0.0 <1.1.0
723 verbose addNamed ">=1.0.0 <1.1.0" is a valid semver range for chalk
724 silly addNameRange { name: 'chalk', range: '>=1.0.0 <1.1.0', hasData: false }
725 silly mapToRegistry name chalk
726 silly mapToRegistry using default registry
727 silly mapToRegistry registry http://npm.cloud.corp.dig.com/
728 silly mapToRegistry uri http://npm.cloud.corp.dig.com/chalk
729 verbose addNameRange registry:http://npm.cloud.corp.dig.com/chalk not in flight; fetching
730 verbose stack TypeError: Invalid Version: 0.4.0rc8
730 verbose stack     at new SemVer (C:\Users\RJF3\AppData\Roaming\npm\node_modules\npm\node_modules\semver\semver.js:293:11)
730 verbose stack     at compare (C:\Users\RJF3\AppData\Roaming\npm\node_modules\npm\node_modules\semver\semver.js:570:10)
730 verbose stack     at rcompare (C:\Users\RJF3\AppData\Roaming\npm\node_modules\npm\node_modules\semver\semver.js:580:10)
730 verbose stack     at Array.sort (native)
730 verbose stack     at pickVersionFromRegistryDocument (C:\Users\RJF3\AppData\Roaming\npm\node_modules\npm\lib\fetch-package-metadata.js:111:48)
730 verbose stack     at C:\Users\RJF3\AppData\Roaming\npm\node_modules\npm\node_modules\iferr\index.js:13:50
730 verbose stack     at C:\Users\RJF3\AppData\Roaming\npm\node_modules\npm\lib\utils\pulse-till-done.js:19:8
730 verbose stack     at saved (C:\Users\RJF3\AppData\Roaming\npm\node_modules\npm\lib\cache\caching-client.js:168:7)
730 verbose stack     at C:\Users\RJF3\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:210:7
730 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
```

I'll have to look into fetchPackageMetadata and caching-client.js to see why it retrieves those extra invalid versions. The cache was cleared before invocation.

What's interesting is that this works fine with npm v2.14, same project, same sinopia installation, same version of semver: ~5.0.3.

**Comment by KenanY** [comment]
Previously: https://github.com/npm/npm/issues/9657, https://github.com/npm/npm/issues/9701

**Comment by bobfields** [comment]
Thanks so much. I'll have our sinopia guy clean these up. FYI the offending artifact/versions:
grunt-contrib-clean 0.4.0rc6
grunt 0.4.0rc8
grunt-contrib-copy 0.4.0rc7
grunt-contrib-watch 0.2.0rc7
grunt-contrib-concat 0.1.2rc6
grunt-contrib-connect 0.1.1rc6
grunt-contrib-jshint 0.1.1rc6
grunt-contrib-less 0.5.0rc7

One suggestion, to make this type of troubleshooting easier - it is very difficult to line up the artifact/version list with the error message in the logs, because of the asynch nature of the function calls. The error message only says 'Invalid Version' and does not say the artifact name. If you could add in npm/lib/fetch-package-metadata.js line 111 (before it errors out on Object.keys.sort):
```
    function pickVersionFromRegistryDocument (pkg) {
      if (!regCache[url]) regCache[url] = pkg
      log.silly(dep.name || dep.rawSpec, " versions=", JSON.stringify(Object.keys(pkg.versions)));
      var versions = Object.keys(pkg.versions).sort(semver.rcompare)

**Comment by bobfields** [comment]
And... advice for those cleaning up sinopia: npm unpublish does not work, but npm unpublish --force works. It returns a 404 error (no such file available) but gets rid of the bad version anyway, which can be verified with 'npm info <artifact> versions'. Other artifacts I had to clean up: handlebars, shelljs.

**Comment by benurb** [comment]
Like I wrote in my first post: if you're using a private registry get rid of its cache, too. Imho it's easier than a lot of `npm unpublish` calls :smile:
But of course it's up to you to decide.

**Comment by markstos** [comment]
I think this issue can be closed. From the history, the root cause had to do with an external sinopia repo, not npm.
