### ISSUE TITLE
publish fails unless I delete `node_modules` folder

### ISSUE THREAD

**Issue by blainekasten** [npm/npm#9810]
Whenever I run `npm publish` in my package, I get a 

`Maximum call stack size exceeded` error.

If I delete the `node_modules` folder it then works.

`npm -v 3.3.4`
`node -v 4.0.0`

**Comment by othiym23** [comment]
Closing as duplicate of #9224 (you're not alone!). Follow that one for updates. Since it's marked `big-bug`, it's something the CLI team definitely intends to address.
