### ISSUE TITLE
Package cleanup?

### ISSUE THREAD

**Issue by tolmasky** [npm/npm#9813]
I noticed that facebook-search (https://github.com/dangeross/node-facebook-search ) package lists its dependencies as ["underscore"], yet when I npm install the dependencies are correct as { "underscore": "" }. Is there a standard procedure for cleaning things like this in the package, or code that does this? Took a look in the repo but couldn't find where its happening.

**Comment by KenanY** [comment]
@tolmasky I think this is it: https://github.com/npm/normalize-package-data/blob/0aa15b23116f2dfd086f1ed6bf213cbb7e7490dd/lib/fixer.js#L376-L402

**Comment by tolmasky** [comment]
Yes, thank you!
