### ISSUE TITLE
npm install runs node-gyp if any .gyp file is present

### ISSUE THREAD

**Issue by dherman** [npm/npm#9816]
The documented behavior of `npm install` is that it runs node-gyp if there is a `binding.gyp` file (the docs actually say `bindings.gyp` but I think that's a typo). But if there's _any_ .gyp file in the project directory, it attempts to run `node-gyp rebuild`, even if none of them is called `binding.gyp`. This then fails since `binding.gyp` doesn't exist.

Steps to reproduce:
1. Create an empty project.
2. Create a file called `bogus.gyp` in the project root.
3. Run `npm install`.

Expected behavior: successful `npm install` without attempting to run `node-gyp`.

Observed behavior `npm install` attempts to run `node-gyp`, which fails because it cannot find `binding.gyp`.

**Edit**: I tested this with io.js 3.0.0.

**Comment by othiym23** [comment]
See also #9820. It might be a little while until we have time to tackle this (there's a lot going on now that `npm@3` is in wider use), but if you wanted to take a stab at fixing this, we'd be able to land a patch much more quickly.

Thanks for the clear report!
