### ISSUE TITLE
Node installer - version of npm

### ISSUE THREAD

**Issue by GuiToniello** [npm/npm#9824]
Hello everybody's npm,

Yesterday (01.10.2015) I installed the latest version of [node js](https://nodejs.org/en/) 4.1.1 on windows, and the version of npm that was installed was the 2.14.x. But the version that is as release is already 3.3.4.

I had to use the command:   ``> npm npm install -g`` to update.

No errors, but I believe (as a suggestion) would be interesting node install the latest version of npm, especially in the windows, which had that problem very long paths, thus ensures better use of npm.

Thank you.

**Comment by GuiToniello** [comment]
Issues:  https://github.com/npm/npm/issues/3697 https://github.com/npm/npm/issues/7768

**Comment by GuiToniello** [comment]
#7768

**Comment by KenanY** [comment]
@GuiToniello I believe `npm@3` will be bundled with Node.js v5.

**Comment by othiym23** [comment]
Hi, @GuiToniello! While this isn't readily apparent, the CLI team (i.e. the people who maintain the `npm` tool and manage this issue tracker) don't choose the version of npm bundled with the Node installer. That's handled by the Node collaborator team, and ultimately the Node build working group. As @KenanY indicated, Node 5, which will be released (most likely) before the end of the year, will bundle the `npm@3` release series. As Node 4 is going into LTS (long-term support) very soon, the Node LTS team has decided that switching major versions of npm within that release series is unduly risky. If you would like to see that changed, the Node LTS working group is the team to lobby.

**Comment by GuiToniello** [comment]
@KenanY  well, thanks for your support ! ;)
