### ISSUE TITLE
npm ERR! Windows_NT 6.1.7600

### ISSUE THREAD

**Issue by justVilla** [npm/npm#9829]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'grunt-cli' ]
2 info using npm@2.14.4
3 info using node@v4.1.1
4 verbose install initial load of C:\Users\SufiiiYaN\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\SufiiiYaN\AppData\Roaming\npm\package.json
6 silly cache add args [ 'grunt-cli', null ]
7 verbose cache add spec grunt-cli
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'grunt-cli',
8 silly cache add   scope: null,
8 silly cache add   name: 'grunt-cli',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed grunt-cli@*
10 verbose addNamed "*" is a valid semver range for grunt-cli
11 silly addNameRange { name: 'grunt-cli', range: '*', hasData: false }
12 silly mapToRegistry name grunt-cli
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/grunt-cli
16 verbose addNameRange registry:https://registry.npmjs.org/grunt-cli not in flight; fetching
17 verbose request uri https://registry.npmjs.org/grunt-cli
18 verbose request no auth needed
19 info attempt registry request try #1 at 1:14:38 AM
20 verbose request id aa28c716e7b4c53e
21 verbose etag "7S8Q4C4WTTVGZDZP1G302BPLI"
22 http request GET https://registry.npmjs.org/grunt-cli
23 verbose stack Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
23 verbose stack     at Error (native)
23 verbose stack     at Object.createSecureContext (_tls_common.js:87:19)
23 verbose stack     at Object.exports.connect (_tls_wrap.js:955:21)
23 verbose stack     at Agent.createConnection (https.js:73:22)
23 verbose stack     at Agent.createSocket (_http_agent.js:174:16)
23 verbose stack     at Agent.addRequest (_http_agent.js:143:23)
23 verbose stack     at new ClientRequest (_http_client.js:133:16)
23 verbose stack     at Object.exports.request (http.js:31:10)
23 verbose stack     at Object.exports.request (https.js:163:15)
23 verbose stack     at Request.start (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:803:30)
24 verbose cwd D:\Projects\myApp
25 error Windows_NT 6.1.7600
26 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "grunt-cli"
27 error node v4.1.1
28 error npm  v2.14.4
29 error error:0906D06C:PEM routines:PEM_read_bio:no start line
30 error If you need help, you may report this error at:
30 error     <https://github.com/npm/npm/issues>
31 verbose exit [ 1, true ]
```

**Comment by othiym23** [comment]
It looks like you might need to configure npm to use a proxy to connect to the registry. Take a look at the [section in the troubleshooting guide](https://github.com/npm/npm/wiki/Troubleshooting#ssl-error) about dealing with SSL errors, which includes links to proxy documentation.

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.

**Comment by andreshg112** [comment]
I'm having the same issue:
`4272 verbose stack Error: EPERM: operation not permitted, rename 'C:\Projects\Node.js\gulp-primeros-pasos\node_modules\globule' -> 'C:\Projects\Node.js\gulp-primeros-pasos\node_modules\.globule.DELETE'
4272 verbose stack     at moveAway (C:\Users\Yo\AppData\Roaming\npm\node_modules\npm\lib\install\action\finalize.js:38:5)
4272 verbose stack     at destStatted (C:\Users\Yo\AppData\Roaming\npm\node_modules\npm\lib\install\action\finalize.js:27:7)
4272 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
4272 verbose stack
4272 verbose stack Error: EPERM: operation not permitted, rename 'C:\Projects\Node.js\gulp-primeros-pasos\node_modules\globule' -> 'C:\Projects\Node.js\gulp-primeros-pasos\node_modules\.globule.DELETE'
4272 verbose stack     at Error (native)
4273 verbose cwd C:\Projects\Node.js\gulp-primeros-pasos
4274 error Windows_NT 6.1.7600
4275 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Yo\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "gulp"
4276 error node v5.8.0
4277 error npm  v3.8.2
4278 error path C:\Projects\Node.js\gulp-primeros-pasos\node_modules\globule
4279 error code EPERM
4280 error errno -4048
4281 error syscall rename
4282 error Error: EPERM: operation not permitted, rename 'C:\Projects\Node.js\gulp-primeros-pasos\node_modules\globule' -> 'C:\Projects\Node.js\gulp-primeros-pasos\node_modules\.globule.DELETE'
4282 error     at moveAway (C:\Users\Yo\AppData\Roaming\npm\node_modules\npm\lib\install\action\finalize.js:38:5)
4282 error     at destStatted (C:\Users\Yo\AppData\Roaming\npm\node_modules\npm\lib\install\action\finalize.js:27:7)
4282 error     at FSReqWrap.oncomplete (fs.js:82:15)
4282 error
4282 error Error: EPERM: operation not permitted, rename 'C:\Projects\Node.js\gulp-primeros-pasos\node_modules\globule' -> 'C:\Projects\Node.js\gulp-primeros-pasos\node_modules\.globule.DELETE'
4282 error     at Error (native)
4282 error  { [Error: EPERM: operation not permitted, rename 'C:\Projects\Node.js\gulp-primeros-pasos\node_modules\globule' -> 'C:\Projects\Node.js\gulp-primeros-pasos\node_modules\.globule.DELETE'] parent: 'gulp-primeros-pasos' }
4283 error Please try running this command again as root/Administrator.
4284 verbose exit [ -4048, true ]`

**Comment by komalbadge** [comment]
I am having this issue long time and not getting anything what to doo.... can anyone help me out there @sufiiiyan @othiym23 @ehsalazar @andreshg112 @alexkwolfe
