### ISSUE TITLE
issue with npm install

### ISSUE THREAD

**Issue by yarsunny** [npm/npm#9834]
```
npm ERR! tar.unpack untar error /var/folders/vs/r5pkpbgj1xbbrbl0fjn7v6yh0000gn/T/npm-3072-4ce337d6/registry.npmjs.org/node-sass/-/node-sass-3.2.0.tgz
npm ERR! tar.unpack untar error /var/folders/vs/r5pkpbgj1xbbrbl0fjn7v6yh0000gn/T/npm-3072-4ce337d6/registry.npmjs.org/node-sass/-/node-sass-3.2.0.tgz
npm ERR! tar.unpack untar error /var/folders/vs/r5pkpbgj1xbbrbl0fjn7v6yh0000gn/T/npm-3072-4ce337d6/registry.npmjs.org/moment/-/moment-2.10.6.tgz
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/4.1.1/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.1.1
npm ERR! npm  v3.3.4

npm ERR! unexpected eof
```

**Comment by rsa408** [comment]
npm ERR! tar.unpack untar error C:\Users\Green-pc\AppData\Local\Temp\npm-6332-d9754471\registry.npmjs.org\request\-\request-2.65.0.tgz
npm ERR! tar.unpack untar error C:\Users\Green-pc\AppData\Local\Temp\npm-6332-d9754471\registry.npmjs.org\npm\-\npm-2.1.3.tgz
npm ERR! tar.unpack untar error C:\Users\Green-pc\AppData\Local\Temp\npm-6332-d9754471\registry.npmjs.org\npm\-\npm-2.1.3.tgz
npm ERR! tar.unpack untar error C:\Users\Green-pc\AppData\Local\Temp\npm-6332-d9754471\registry.npmjs.org\source-map\-\source-map-0.3.0.tgz
npm ERR! tar.unpack untar error C:\Users\Green-pc\AppData\Local\Temp\npm-6332-d9754471\registry.npmjs.org\source-map\-\source-map-0.3.0.tgz
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs2\\node.exe" "C:\\Users\\Green-pc\\AppD
ata\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic"
npm ERR! node v4.1.1
npm ERR! npm  v3.3.6

npm ERR! unexpected eof
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\mob\npm-debug.log
