### ISSUE TITLE
npm fetch failure

### ISSUE THREAD

**Issue by msmith2199** [npm/npm#9837]
I keep trying to install cordova and ionic and as far as i know others will fail as well.

This is what I see. enter image description here

I tried disabling the proxy and setting the registry.
![wjzcx](https://cloud.githubusercontent.com/assets/13982203/10263674/890b4674-69c4-11e5-9ded-1a02d7f7d214.png)

**Comment by Stephn-R** [comment]
Do you have any other applications running on your machine while running the npm install?

**Comment by msmith2199** [comment]
No I do not

**Comment by msmith2199** [comment]
IT only does it on one computer of mine, my laptop is the only one with this issue

**Comment by smartmouse** [comment]
Is your laptop using WIFI to connect to internet? Any firewall? You are not using any private registry?

**Comment by msmith2199** [comment]
I have tried wifi and direct, firewall on and off and no private registry as far as I know

**Comment by msmith2199** [comment]
Could it be a path variable not setup correctly?
When I do npm install -g cordova it shows up in
C:\Users\Mason-Laptop\AppData\Roaming\npm\node_modules\cordova

but I cant use it.

**Comment by smartmouse** [comment]
Oh, please check if c:\User\Mason-Laptop\AppData\Roaming\npm is in your path
echo %PATH%
I have similar  setup in my path

C:\Users\IBM_ADMIN\AppData\Roaming\npm;C:\Program Files\nodejs\;....

**Comment by msmith2199** [comment]
I checked my path and they are all in there, does the order of which they are in my path matter?

**Comment by msmith2199** [comment]
Even tried using an older version still no go, makes no sense

**Comment by smartmouse** [comment]
ok, check your path length, windows has limit to path length, or move around the setting to the front.

**Comment by smartmouse** [comment]
we got similar issue in our jenkin server, the files are not picked up even it it is there, then it is to do with the path limitation.
