### ISSUE TITLE
npm err tar.unpack (windows)

### ISSUE THREAD

**Issue by mbaljeetsingh** [npm/npm#9838]
![2015-10-03_22-49-32](https://cloud.githubusercontent.com/assets/872762/10264124/1f18d832-6a21-11e5-86b3-c08e51639ef2.png)
Does anybody know how to fix it?, Currently i am using the latest npm version 2.14.4, i tried reinstalling the previous version. Nothing worked.

**Comment by jlmitch5** [comment]
getting something similar on NPM 2.5.1, Node 1.2.0 (OSX)

```
114563 verbose stack Error: read ECONNRESET
114563 verbose stack     at exports._errnoException (util.js:734:11)
114563 verbose stack     at TCP.onread (net.js:531:26)
114564 verbose cwd /Users/jmitchell/tower_fork
114565 error Darwin 15.0.0
114566 error argv "node" "/usr/local/bin/npm" "install"
114567 error node v1.2.0
114568 error npm  v2.5.1
114569 error code ECONNRESET
114570 error errno ECONNRESET
114571 error syscall read
114572 error network read ECONNRESET
114572 error network This is most likely not a problem with npm itself
114572 error network and is related to network connectivity.
114572 error network In most cases you are behind a proxy or have bad network settings.
114572 error network
114572 error network If you are behind a proxy, please make sure that the
114572 error network 'proxy' config is set properly.  See: 'npm help config'
114573 verbose exit [ 1, true ]
```

**Comment by ehsalazar** [comment]
You may need to configure npm to use a proxy to connect to the registry. Take a look at the section in the [troubleshooting guide](https://github.com/npm/npm/wiki/Troubleshooting#ssl-error) about dealing with SSL errors. It includes links to proxy documentation.

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.

**Comment by mbaljeetsingh** [comment]
@ehsalazar i resolved the issue, Thanks.
