### ISSUE TITLE
Node.exe - npm ls

### ISSUE THREAD

**Issue by darkmorpher** [npm/npm#9839]
Question:

Does `npm ls` needs to be run from the same directory where node.exe+npm is located for `npm list` command to work?

**Comment by KenanY** [comment]
@darkmorpher If the path to the `npm` binary is in your `PATH` environment variable, then you can run `npm` from anywhere :)

**Comment by darkmorpher** [comment]
It is. But `npm ls` will return *empty* unless I run the command from where npm is located.
Ex:
`C:\Users\Me>npm ls npm
└── (empty)`

`C:\Users\BK-201\Documents\node>npm ls npm
└── npm@3.3.6`

Which seemed odd to me. Is this a intended behavior?

**Comment by KenanY** [comment]
@darkmorpher `npm ls` displays the modules installed in the `node_modules/` directory of the project you are currently in. If there is no `node_modules/` in your current directory, `npm ls` will display `(empty)`. If you want to be able to see your globally installed modules (like `npm`), you can run `npm ls` with the `--global` flag (shorthand: `-g`).

**Comment by darkmorpher** [comment]
Thanks
