### ISSUE TITLE
How to change node_modules path in windows ?

### ISSUE THREAD

**Issue by JFSolorzano** [npm/npm#9840]
I've change form OS X to Windows recently, but i can't specify the node_modules path of my current project, what i did on OS X was:

`export NODE_PATH='server'/node_modules`

But if i run that in cmd it doesn't work.

How could i do that in windows?
Also how could i tell my project to change the node_modules path permanently (with that way i had to run that command every time i opened the project) ?

**Comment by smartmouse** [comment]
How did you install node on your windows? Using the msi? 
When you install, you can specify to add it to your path.

c:\Program Files\node.js is where I installed my node
and it is in my path
echo %PATH%

For my window 7 environment, I use the Node.js command prompt, the path is automatically set up.
NPM is under c:\Users\IBM_ADMIN\AppData\Roaming\npm
any npm install -g xxx is installed
under c:\Users|IBM_ADMIN\AppData\Roaming\npm\node_modules

To set system wide environment variables in windows:
You can set system wide environment variables  - Control Panel->System & Security->System- click on Environment variables.

echo %PATH% to check your current path settings.
You can google information for windows path settings.

**Comment by othiym23** [comment]
@JFSolorzano you'll need to set that variable in your Windows environment, which is [pretty different from Windows](http://www.computerhope.com/issues/ch000549.htm). If you don't mind, could you let me know why you're using `NODE_PATH` instead of allowing each application to have its own dependencies? I'm always curious when I see people using that feature.

**Comment by JFSolorzano** [comment]
I don't find any other way to change the default location of the node_modules folder @othiym23

**Comment by busches** [comment]
@JFSolorzano did you get this error resolved so the issue can be closed?
