### ISSUE TITLE
npm install deps at top level

### ISSUE THREAD

**Issue by apps4u** [npm/npm#9844]
HI Ive just udated my mac to os x 10.11 , Im running NPM -v 3.5.5 and node -v 4 
I had a project that Ive not worked on fro two months it had two package as below.
now in my node_modules folder I had just two package but I was getting a error running gulp so I ran a npm update and Now I have over 705 package in my node_modules folder so It looks like the deps are not being nested with each packages node_modules folder.
```json
{
  "private": true,
  "devDependencies": {
    "gulp": "^3.8.8",
    "laravel-elixir": "*"
  }
}
```

**Comment by KenanY** [comment]
@apps4u Are you sure you are not just experiencing one of the defining features of `npm@3`?:

> Your dependencies will now be installed _maximally_ flat. Insofar as is possible, all of your dependencies, and their dependencies, and THEIR dependencies will be installed in your project's `node_modules` folder with no nesting. You'll only see modules nested underneath one another when two (or more) modules have conflicting dependencies.

https://github.com/npm/npm/releases/tag/v3.0.0

**Comment by apps4u** [comment]
thanks I thought thats what was happening I thought I might I changed a setting as Ii know windows users have asked for this for a while now..
