### ISSUE TITLE
npm not recognised - > npm.cmd works

### ISSUE THREAD

**Issue by PreethiBabu87** [npm/npm#9845]
Hi

I tried installing nodejs in windows 8 machine. The node got installed successfully.
But when i type in npm in the command line. It shows the below error:

npm is not recognised as internal or external command.
I have also set the PATh variable to "C:\Program Files\nodejs" where the nodejs is installed.

But it works when i type in npm.cmd. It shows the help options of npm.
How can i use npm instead of npm.cmd?
Installed : node-v0.12.6-x64.msi
Kindly help.

Regards
Preethi

**Comment by rdquintas** [comment]
Hi, was wondering if I could help here.
Is this still an open issue ?
Never had issues with nodejs on windows 8 machine myself.
