### ISSUE TITLE
Npm Grunt Error Ubuntu 14.04 with latest versions

### ISSUE THREAD

**Issue by sandinosaso** [npm/npm#9849]
3000 info preuninstall grunt-contrib-clean@0.6.0
3001 silly lockFile c9ffd2e6-lodash-2-4-2 lodash@2.4.2
3002 silly lockFile c9ffd2e6-lodash-2-4-2 lodash@2.4.2
3003 silly lockFile 257f9ab3-lodash-2-4-1 lodash@~2.4.1
3004 silly lockFile 257f9ab3-lodash-2-4-1 lodash@~2.4.1
3005 info uninstall grunt-contrib-clean@0.6.0
3006 verbose true,/var/www/ccc/lh/node_modules,/var/www/ccc/lh/node_modules
unbuild grunt-contrib-clean@0.6.0
3007 info postuninstall grunt-contrib-clean@0.6.0
3008 silly gunzTarPerm extractEntry test/scenarios/force
push/remote/hooks/commit-msg.sample
3009 silly gunzTarPerm extractEntry test/scenarios/force
push/remote/hooks/post-update.sample
3010 silly gunzTarPerm extractEntry test/scenarios/force
push/remote/hooks/pre-applypatch.sample
3011 silly gunzTarPerm extractEntry test/scenarios/force
push/remote/hooks/pre-commit.sample
3012 error Error: UNKNOWN, symlink '../rimraf/bin.js'
3013 error If you need help, you may report this log at:
3013 error     <http://github.com/isaacs/npm/issues>
3013 error or email it to:
3013 error     <npm-@googlegroups.com>
3014 error System Linux 3.13.0-32-generic
3015 error command "/usr/bin/nodejs" "/usr/bin/npm" "install"
3016 error cwd /var/www/ccc/lh
3017 error node -v v0.10.25
3018 error npm -v 1.3.10
3019 error path ../rimraf/bin.js
3020 error code UNKNOWN
3021 error errno -1
3022 verbose exit [ -1, true ]

**Comment by KenanY** [comment]
@sandinosaso Does this also occur if you [upgrade to the latest stable release of `npm](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm)? Also do you know if your system support symlinks? If not, you will need to run `npm install` with the [`--no-bin-links`](https://docs.npmjs.com/misc/config#bin-links) flag.

**Comment by sandinosaso** [comment]
It also happens when I upgrade to the latest version, when I do npm i -g npm it install another version of npm but problem persist. My system is Ubuntu 14.04 so it supports symlinks

**Comment by sandinosaso** [comment]
I close this issue because I solved it running a 
rm -fR node_modules
npm cache clean

Thanks.
