### ISSUE TITLE
Getting Error while running container using 'docker-compose up'

### ISSUE THREAD

**Issue by akshath4u** [npm/npm#9851]
![docker-compose-errorr](https://cloud.githubusercontent.com/assets/9428527/10301543/0635af96-6c21-11e5-9155-7dd964ae4cdc.png)

Please any one know the reason for this error?

**Comment by KenanY** [comment]
@akshath4u Looks like https://github.com/npm/npm/issues/9766.

**Comment by KenanY** [comment]
I'm gonna close this since I am very much certain that this is fixed as of `npm@3.3.7`, but if I'm wrong I can easily reopen. Just let me know @akshath4u.
