### ISSUE TITLE
messy info for npm install command

### ISSUE THREAD

**Issue by dejour** [npm/npm#9854]
when i run npm install command,my console show this.(windows,latest version of node and npm)

![image](https://cloud.githubusercontent.com/assets/7224044/10307563/865add40-6c62-11e5-950c-706ad90418da.png)

**Comment by iarna** [comment]
Which terminal are you using? cmd?

**Comment by dejour** [comment]
my terminal is cmd ,and i use windows 7

**Comment by dejour** [comment]
it is same in powershell.is it about my system font setting?

**Comment by iarna** [comment]
So... as far as I knew, you couldn't change the font in cmd or powershell? Certainly if you did that would have an impact!

It might be a locale thing too?

**Comment by gillesdemey** [comment]
@dejour were you able to find out what was causing this? If this is indeed the default behaviour on Win7 then it needs to be looked at.

**Comment by dejour** [comment]
i can't find the reason 😅
