### ISSUE TITLE
npm can't use in windows7

### ISSUE THREAD

**Issue by tianzhen** [npm/npm#9858]
I want to use npm in my windows7 system. I download node-v4.1.2-x64.msi and install into D:\nodejs.After that , I make two environment variable, the one is Path= D:\nodejs , the second is NODE_PATH=D:\nodejs\node_modules. Then I cd to D:\nodejs , input "node -v" , the output is "v4.1.2", it seems to be ok , but when i input " npm -v" , there's no result , it looks like the process is suspend, then i test "npm config get prefix" , it's the same to 'npm -v', it's so strange.
anyone can help , so thankful.

**Comment by krnlde** [comment]
Usually you don't need to set the env-variables. What's your reason to set them?

**Comment by tianzhen** [comment]
Thanks to Krnlde, I've solved the problem , just deleted the npmrc file in the user home directory.
