### ISSUE TITLE
npm install error (timeout)

### ISSUE THREAD

**Issue by Tomson124** [npm/npm#9862]
Today I tried to install the dev dependencies for bootstrap 4 in my local homestead enviroment but after doing `npm install` I get the following error:

```
npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-ddd"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect

npm ERR! network connect ETIMEDOUT 185.31.17.162:80
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm verb exit [ 1, true ]
npm verb stack Error: ETXTBSY: text file is busy, rename 'npm-debug.log.0419050ce79e906bc902572d57489e1e' -> 'npm-debug.log'
npm verb stack     at Error (native)
npm verb cwd /home/vagrant/Code/bootstrap-4-dev
npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-ddd"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! path npm-debug.log.0419050ce79e906bc902572d57489e1e
npm ERR! code ETXTBSY
npm ERR! errno -26
npm ERR! syscall rename

npm ERR! ETXTBSY: text file is busy, rename 'npm-debug.log.0419050ce79e906bc902572d57489e1e' -> 'npm-debug.log'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm verb exit [ -26, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/Code/bootstrap-4-dev/npm-debug.log
```

Debug log: http://pastebin.com/4tPvx96Z

I tried setting the registry to: http://registry.npmjs.org/ but I didn't work.
I also tried `curl`ing the registry but http:// and https:// work both fine with `curl`.

Then I tried `npm install` on my host machine (Windows 7 Pro 64bit) but it didn't worked their either, turning of the firewall didn't solved the problem.

If it helps in any way, I'm from Germany so I think the IP it calls isn't quite right....

**Comment by neverfox** [comment]
Oh no, it's not just me. The Fastly CDNs are timing out. This would happen when I have a huge deadline.

**Comment by neverfox** [comment]
Interestingly, the npm status page says all systems are operational.

**Comment by loremipson** [comment]
+1

Started timing out on me out of no where tonight. Was weirded out when I saw the status page though..

**Comment by Tomson124** [comment]
Maybe I should mention that it worked about a week ago ando now I always get this timeouts, but only if I do a `npm install`. Global installs worked fine so far...

**Comment by Tomson124** [comment]
Maybe I should mention that it worked about a week ago ando now I always get this timeouts, but only if I do a `npm install`. Global installs worked fine so far...

**Comment by Tomson124** [comment]
It's so strange I just tried `npm install less` and it worked just fine after that I tried `npm install` in the bootstrap directory and I'm getting the ETIMED error again...

**Comment by Tomson124** [comment]
Just tried it on my linux machine (no vm) and there everthing works fine... I think my windows pc is messed up :/

**Comment by Tomson124** [comment]
Any news ?

**Comment by hyzhak** [comment]
got ETIMEOUT as well. Is there any way to increase wait time to prevent timeout?

**Comment by LoveAndHappiness** [comment]
+1

**Comment by neverfox** [comment]
Seven days? More like a year and seven months.
