### ISSUE TITLE
express installation failure

### ISSUE THREAD

**Issue by kumarwbm** [npm/npm#9864]
I am get the following error whenever i try to install express.js using node.

i am using the following command 
npm install express-generator -g

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "express-generator" "-g"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code EPROTO
npm ERR! errno EPROTO
npm ERR! syscall write

npm ERR! write EPROTO
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "express-generator" "-g"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! path c:\Program Files\nodejs\npm-debug.log.5b139398d76b693e051c96f0a2af
9c23
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall open

npm ERR! Error: EPERM: operation not permitted, open 'c:\Program Files\nodejs\np
m-debug.log.5b139398d76b693e051c96f0a2af9c23'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, open 'c:\Program Files\nodej
s\npm-debug.log.5b139398d76b693e051c96f0a2af9c23']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'open',
npm ERR!   path: 'c:\\Program Files\\nodejs\\npm-debug.log.5b139398d76b693e051c9
6f0a2af9c23' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Program Files\nodejs\npm-debug.log

**Comment by CristianWorkGit** [comment]
I mean if only want to install express.js this is the command :"npm install express --save" .
The "--save" tag is to add the depedency only on the project where you are, if you want global use the tag "-g"

**Comment by smartmouse** [comment]
why are you having permission issues?
When you install your node 4.1.1, did you use sudo or not?
looks like there is some issues laying down the files when install globallu.

Try just create a folder say c:\test
and then install without the global flag
Do npm install express-generator  
See if you have the same error or not.

**Comment by KenanY** [comment]
@kumarwbm Is this still an issue for you?

**Comment by KenanY** [comment]
Closing as abandoned.
