### ISSUE TITLE
How to crack this? Do not include modules which aren't supported by the current OS to the shrinkwrap.json

### ISSUE THREAD

**Issue by binarykitchen** [npm/npm#9865]
This fails

```
$ npm shrinkwrap --dev

npm ERR! Linux 3.19.0-30-generic
npm ERR! argv "/usr/bin/iojs" "/usr/bin/npm" "shrinkwrap" "--dev"
npm ERR! node v2.5.0
npm ERR! npm  v3.3.5

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! missing: fsevents@^1.0.0, required by chokidar@1.2.0
```

I can `npm install` fine, but not build a shrinkwrap.json. I know you recently solved the `EBADPLATFORM` issue for npm installs but what about the shrinkwrap file? I guess this is a difficult one to crack, especially when I share that shrinkwrap.json to other developers who aren't on Linux but on Mac OS.

**Comment by tonyhb** [comment]
+1 can we allow multi-arch shrinkwraps such as fsevents?

**Comment by hatched** [comment]
I also ran into then when trying to upgrade to npm 3. Works as expected with 2.14.11 though.

```
npm ERR! Linux 3.13.0-68-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "shrinkwrap" "--dev"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! missing: fsevents@^1.0.0, required by chokidar@1.2.0
npm ERR! missing: fsevents@^1.0.0, required by chokidar@1.2.0
```

**Comment by turadg** [comment]
Specifying `fsevents` under `optionalDependencies` of `package.json` worked for me. Thanks to @lxe in https://github.com/npm/npm/issues/2679#issuecomment-150084700

**Comment by busches** [comment]
@binarykitchen @tonyhb @hatched did @turadg's solution work for you?

**Comment by hatched** [comment]
@busches we ended up using another approach and so removed the dependency.
