### ISSUE TITLE
Deprecate and drop `_password` and `_auth` support in `.npmrc`

### ISSUE THREAD

**Issue by ChALkeR** [npm/npm#9866]
Seriously, storing user password in cleartext (_base64 counts as cleartext_) is a no-go. That is really bad and that makes consequences of any leak (due to _bugs_, malware, or users publishing their own dotfiles) much worse.
1. If only a token is stored — nothing else is affected (_yes, users re-use their passwords a lot, duh_).
2. A token could be simply revoked — that doesn't make users to lose their access and doesn't force them to use password restore.

Atm, `npm` already uses `_authToken` by default, but it still silently supports `_password` and `_auth` afaik. But there are still an immense amount of password-based `.npmrc` files in the wild, and those are used, and those leak sometimes.

So, the proposal is:
1. Soft-deprecate `_password` and `_auth` by printing a warning to the console if those entries exist in the currently used `.npmrc` — in a minor version (i.e. 3.4.0).
2. Remove `_password` and `_auth` support, fail with an error if those are present in the currently used `.npmrc` — in a major version (i.e. 4.0.0).
3. Remove the check and the error in some future major version (i.e. 6.0.0).

Please, think twice about this before rejecting.

**Comment by focusaurus** [comment]
Here's a link to a github search showing how many developers check their .npmrc into git and publish to github: https://github.com/search?utf8=%E2%9C%93&q=filename:.npmrc+_auth&type=Code&ref=searchresults

**Comment by ChALkeR** [comment]
@focusaurus While the point itself is pretty valid (and was one of the reasons why I opened this issue), imo publising a direct link to not yet revoked users' credentials in a public issue is not a very nice thing to do.

**Comment by ChALkeR** [comment]
Ref: https://github.com/npm/npm/issues/4905#issuecomment-56631955
