### ISSUE TITLE
unable to update npm modules globally with `npm update -g`

### ISSUE THREAD

**Issue by shaunstanislaus** [npm/npm#9869]
``` bash
npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/shaunstanislaus/homebrew/Cellar/node/4.1.2/bin/node" "/usr/local/bin/npm" "update" "-g"
npm ERR! node v4.1.2
npm ERR! npm  v3.3.5

npm ERR! 'undefined' == 'string'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/shaunstanislaus/npm-debug.log

```

**Comment by lerouxvn** [comment]
I had the same problem. Did a npm update -g for every package installed under /usr/lib/node_modules/... Problem fixed after running 'npm update -g flightplan'

**Comment by shaunstanislaus** [comment]
your solution doesn't work @lerouxvn

**Comment by blitzd** [comment]
I had this same problem with Node v5.0.0 and npm v3.3.6, downgrading to npm 3.3.4 enabled me to get past it and I was then able to run an update -g. 

npm@3.3.6 was also failing to install node-inspector, and it worked afterwards.

**Comment by Oikio** [comment]
Same issue here, node v0.12.7, npm v3.3.6. Thanks to @blitzd, downgrading to v3.3.4 helped. But at first npm tried to install npm-debug.log package, removing log file from global node_modules helped.
