### ISSUE TITLE
Problem on npm install (Windows)

### ISSUE THREAD

**Issue by hitmands** [npm/npm#9871]
Hi, when I try to exec `npm install` the cli responds with a `Error: Command failed: git -c core.longpaths=true config --get remote.origin.url`

**Comment by KenanY** [comment]
@hitmands Is there a `npm-debug.log` that you can upload as a [gist](https://gist.github.com/)?

**Comment by hitmands** [comment]
@KenanY https://gist.github.com/hitmands/f3d6be19f4f5d1fc99de

**Comment by KenanY** [comment]
@hitmands Looks like an issue with your internet connection:

```
1382 verbose stack fatal: unable to connect to github.com:
1382 verbose stack github.com[0: 192.30.252.128]: errno=No error
```

Maybe a proxy or firewall is messing with requests to the `git://` protocol or `github.com`?

**Comment by hitmands** [comment]
I've many repositories on github and all of them (except this) work well!
By the way, yes there is a company-proxy and I switched from the git protocol to https via `url.https://.insteadof=git://`

I don't understand why only this repo has problems!

**Comment by KenanY** [comment]
@hitmands Is this still an issue you are having?

**Comment by hitmands** [comment]
that's was fixed. Sorry.
Can be closed
