### ISSUE TITLE
npm install -g appium is not working

### ISSUE THREAD

**Issue by sheetal0123** [npm/npm#9872]
Hi,

i tries to install appium and followed steps from 
http://ubuntubegin.blogspot.in/2015/07/how-to-setup-appium-in-ubuntu.html

but on following step i am getting error:
npm install -g appium

Error:
npm ERR! tar.unpack untar error /tmp/npm-12525-ec762ef2/registry.npmjs.org/appium-instruments/-/appium-instruments-2.0.6.tgz
npm ERR! tar.unpack untar error /tmp/npm-12525-ec762ef2/registry.npmjs.org/appium-adb/-/appium-adb-1.7.5.tgz
npm ERR! Linux 3.13.0-63-generic
npm ERR! argv "/home/xebia/.linuxbrew/Cellar/node/4.1.1/bin/node" "/home/xebia/.linuxbrew/bin/npm" "install" "-g" "appium"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4

npm ERR! unexpected eof
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/xxx/npm-debug.log

**Comment by KenanY** [comment]
@sheetal0123 Are you still seeing this issue?

**Comment by sheetalsingh** [comment]
Hi,
Last year i tried to setup appium on ubuntu but not able to setup properly if i remembered correctly.
Now i am using mac and appium is working fine on this.

**Comment by KenanY** [comment]
@sheetalsingh Thanks for following up.
