### ISSUE TITLE
npm ERR! Maximum call stack size exceeded

### ISSUE THREAD

**Issue by masterpowers** [npm/npm#9875]
npm WARN install Couldn't install optional dependency: Unsupported
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Andrew Galang\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--no-bin-links"
npm ERR! node v4.1.2
npm ERR! npm  v3.3.5

npm ERR! Maximum call stack size exceeded
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Andrew Galang\Code\rfnbeta\npm-debug.log

**Comment by masterpowers** [comment]
this is my packages.json
```
{
  "dependencies": {
    "gulp-concat": "^2.6.0",
    "gulp-concat-sourcemap": "^1.3.1",
    "gulp-filter": "^1.0.2",
    "gulp-if": "^1.2.5",
    "gulp-jshint": "^1.9.0",
    "gulp-minify-css": "^0.3.11",
    "gulp-ng-annotate": "^1",
    "gulp-notify": "^2.0.0",
    "gulp-sourcemaps": "^1",
    "gulp-uglify": "^1",
    "jshint-stylish": "^2",
    "laravel-elixir": "^3.0.0",
    "laravel-elixir-livereload": "^1.1.1",
    "main-bower-files": "^2.1.0"
  },
  "devDependencies": {
    "gulp": "^3.9.0"
  }
}
```

**Comment by masterpowers** [comment]
i run the command npm install --no-bin-links
on my local machine in windows

**Comment by masterpowers** [comment]
running only npm install fix the problem :)

**Comment by masterpowers** [comment]
to wrap things up what i do
i just updated to the latest node and npm
fix the windows issue of long path name
then npm install

**Comment by KenanY** [comment]
@masterpowers Is this still an issue for you?

**Comment by KenanY** [comment]
Closing as abandoned.
