### ISSUE TITLE
I am not able to install bower 

### ISSUE THREAD

**Issue by MahaSannasi** [npm/npm#9876]
When I execute the " npm install -g bower "

Getting the below errors .

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files (x86)\nodejs\\node.exe" "C:\Program Files (
x86)\nodejs\node_modules\npm\bin\npm-cli.js" "install" "bower"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code SELF_SIGNED_CERT_IN_CHAIN

npm ERR! self signed certificate in certificate chain
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\mahals\npm-debug.log

Please help me on this

**Comment by fxf601244325** [comment]
I also encountered the same problem.

FXFMac:~ zxc$ npm install -g bower

npm WARN locking Error: EACCES, open '/Users/zxc/.npm/_locks/bower-e8debc5417026b57.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/zxc/.npm/_locks/bower-e8debc5417026b57.lock failed { [Error: EACCES, open '/Users/zxc/.npm/_locks/bower-e8debc5417026b57.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/zxc/.npm/_locks/bower-e8debc5417026b57.lock' }
npm ERR! Darwin 15.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "bower"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! Attempt to unlock /usr/local/lib/node_modules/bower, which hasn't been locked
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/zxc/npm-debug.log

**Comment by KenanY** [comment]
@fxf601244325 Your issue looks different. Your have `npm` configured to install global modules to `/usr/local`, but you don't have permission to write to that directory. Hence, you will need to use `sudo` when you want to install global modules. It also looks like the permissions of `npm`'s cache directory might be messed up, so you can try running:

```
sudo chown -R $(whoami) "$HOME/.npm"
```

Please open a new issue next time. @MahaSannasi's issue is regarding SSL certificates whilst yours regards directory permissions.

**Comment by vasco3** [comment]
> I'm not able to install bower

Congratulations

**Comment by KenanY** [comment]
@MahaSannasi Are you still experiencing this issue?
