### ISSUE TITLE
error when installing ionic fram work 

### ISSUE THREAD

**Issue by abode97** [npm/npm#9878]
when I write   npm install -g cordova ionic I have alot of error that I cant screen showt them .... I want the solution for this problem and all nessesary program to download for install the inoic fram work ... and thanks for help ^_^

**Comment by KenanY** [comment]
@abode97 Could you upload the resulting `npm-debug.log` as a [gist](https://gist.github.com/)?

**Comment by abode97** [comment]
sorry for my lateness but this the first time I post a question here .. I can upload the result here cause I dont know to copy from cmd .. but I have I screen shoute of them .. could we contact in facebook tp solve this problem ? my Account is https://www.facebook.com/abode.aho thank you very much I I am waiting for you

**Comment by KenanY** [comment]
@abode97 Sorry but I would prefer if we use this ticket as the medium of communication or over on IRC (`freenode`, `#npm`), but I would still need to see your `npm-debug.log` in order to have any clue as to what error you are experiencing.

**Comment by abode97** [comment]
![555](https://cloud.githubusercontent.com/assets/15010503/10444907/23755bbc-7174-11e5-9f80-b5609deb0991.png)
![5556](https://cloud.githubusercontent.com/assets/15010503/10444908/23831e50-7174-11e5-9799-f675dcdd6624.png)
![46466](https://cloud.githubusercontent.com/assets/15010503/10444909/238df212-7174-11e5-96c4-d512b74b4750.png)
![55567](https://cloud.githubusercontent.com/assets/15010503/10444910/23a25fc2-7174-11e5-8b42-9eab82bb1ea4.png)
![efer](https://cloud.githubusercontent.com/assets/15010503/10444913/2412773a-7174-11e5-9296-c86b035f490f.png)
![ferfege](https://cloud.githubusercontent.com/assets/15010503/10444914/24194e70-7174-11e5-8e6e-1f30362f6e12.png)
![trhhrth](https://cloud.githubusercontent.com/assets/15010503/10444911/23c7c80c-7174-11e5-9b85-eace5d077b14.png)
![tyjhh](https://cloud.githubusercontent.com/assets/15010503/10444912/23d5ab8e-7174-11e5-92c1-fde9369c0a47.png)

**Comment by abode97** [comment]
this is the result of npm-debug.log thank you for helping and I would to clear this problem
