### ISSUE TITLE
npm install moment error

### ISSUE THREAD

**Issue by bhushangoel** [npm/npm#9881]
I'm trying to install moment v2.10.0
and getting the following error

npm ERR! Error: version not found: 2.10.0 : moment/2.10.0
npm ERR!     at RegClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:272:14)
npm ERR!     at Request.self.callback (/usr/lib/nodejs/request/index.js:148:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/index.js:896:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/lib/nodejs/request/index.js:847:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)

**Comment by KenanY** [comment]
@bhushangoel Such a version does not exist:

``` bash
$ npm info moment versions
[ '1.0.0',
  '1.0.1',
  '1.1.0',
  '1.1.1',
  '1.2.0',
  '1.3.0',
  '1.4.0',
  '1.5.0',
  '1.5.1',
  '1.6.0',
  '1.6.1',
  '1.6.2',
  '1.7.0',
  '1.7.1',
  '1.7.2',
  '2.0.0',
  '2.1.0',
  '2.2.1',
  '2.3.0',
  '2.3.1',
  '2.4.0',
  '2.5.0',
  '2.5.1',
  '2.6.0',
  '2.7.0',
  '2.8.1',
  '2.8.2',
  '2.8.3',
  '2.8.4',
  '2.9.0',
  '2.10.2',
  '2.10.3',
  '2.10.5',
  '2.10.6' ]
```

**Comment by KenanY** [comment]
@bhushangoel ping? :)

**Comment by KenanY** [comment]
Closing as resolved; this is expected `npm` behavior. It cannot install things which do not exist.
