### ISSUE TITLE
Error when trying to init a react-native project

### ISSUE THREAD

**Issue by rongj** [npm/npm#9882]
$ react-native init MyProject
This will walk you through creating a new React Native project in c:\Users\Admin
istrator\desktop\MyProject
Installing react-native package from npm...

npm ERR! git fetch -a origin (git://github.com/facebook/react.git) fatal: Unable
 to create 'f:/nodejs/node-cache/_git-remotes/git-github-com-facebook-react-git-
baa2986b/refs/pull/529/head.lock': File exists.
npm ERR! git fetch -a origin (git://github.com/facebook/react.git)
npm ERR! git fetch -a origin (git://github.com/facebook/react.git) If no other g
it process is currently running, this probably means a
npm ERR! git fetch -a origin (git://github.com/facebook/react.git) git process c
rashed in this repository earlier. Make sure no other git
npm ERR! git fetch -a origin (git://github.com/facebook/react.git) process is ru
nning and remove the file manually to continue.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "f:\\nodejs\\node.exe" "f:\\nodejs\\node_modules\\npm\\bin\\npm-cl
i.js" "install" "--save" "react-native"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.4
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true fetch -a origin
npm ERR! fatal: Unable to create 'f:/nodejs/node-cache/_git-remotes/git-github-c
om-facebook-react-git-baa2986b/refs/pull/529/head.lock': File exists.
npm ERR!
npm ERR! If no other git process is currently running, this probably means a
npm ERR! git process crashed in this repository earlier. Make sure no other git
npm ERR! process is running and remove the file manually to continue.
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Users\Administrator\desktop\MyProject\npm-debug.log

`npm install --save react-native` failed

**Comment by carl1990** [comment]
I have this problem too

the error info is:

npm ERR! git clone --template=/Users/carlwei/.npm/_git-remotes/_templates --mirror git://github.com/facebook/react.git /Users/carlwei/.npm/_git-remotes/git-github-com-facebook-react-git-baa2986b: Cloning into bare repository '/Users/carlwei/.npm/_git-remotes/git-github-com-facebook-react-git-baa2986b'...
npm ERR! git clone --template=/Users/carlwei/.npm/_git-remotes/_templates --mirror git://github.com/facebook/react.git /Users/carlwei/.npm/_git-remotes/git-github-com-facebook-react-git-baa2986b: fatal: unable to open /Users/carlwei/.npm/_git-remotes/git-github-com-facebook-react-git-baa2986b/objects/pack/tmp_pack_u5XyIb: No such file or directory
npm ERR! git clone --template=/Users/carlwei/.npm/_git-remotes/_templates --mirror git://github.com/facebook/react.git /Users/carlwei/.npm/_git-remotes/git-github-com-facebook-react-git-baa2986b: fatal: index-pack failed
npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/carlwei/.nvm/versions/node/v4.1.2/bin/node" "/Users/carlwei/.nvm/versions/node/v4.1.2/bin/npm" "install"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.4
npm ERR! code 128

npm ERR! Command failed: git clone --template=/Users/carlwei/.npm/_git-remotes/_templates --mirror git://github.com/facebook/react.git /Users/carlwei/.npm/_git-remotes/git-github-com-facebook-react-git-baa2986b
npm ERR! Cloning into bare repository '/Users/carlwei/.npm/_git-remotes/git-github-com-facebook-react-git-baa2986b'...
npm ERR! fatal: unable to open /Users/carlwei/.npm/_git-remotes/git-github-com-facebook-react-git-baa2986b/objects/pack/tmp_pack_u5XyIb: No such file or directory
npm ERR! fatal: index-pack failed
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/carlwei/Desktop/ZhiHuDaily-React-Native/npm-debug.log

**Comment by jozerozero** [comment]
I also have this problem
I:\react>react-native init MyProjecy
This will walk you through creating a new React Native project in I:\react\MyPro
jecy
Installing react-native package from npm...

npm ERR! git clone --template=C:\Users\梓健\AppData\Roaming\npm-cache\_git-remot
es\_templates --mirror git://github.com/facebook/react.git C:\Users\梓健\AppData
\Roaming\npm-cache\_git-remotes\git-github-com-facebook-react-git-baa2986b: unde
fined
npm ERR! git clone --template=C:\Users\梓健\AppData\Roaming\npm-cache\_git-remot
es\_templates --mirror git://github.com/facebook/react.git C:\Users\梓健\AppData
\Roaming\npm-cache\_git-remotes\git-github-com-facebook-react-git-baa2986b: unde
fined
npm ERR! fetch failed https://registry.npmjs.org/worker-farm/-/worker-farm-1.3.1
.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 199.2
7.79.162:443
npm ERR! fetch failed https://registry.npmjs.org/ws/-/ws-0.8.0.tgz
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 199.2
7.79.162:443
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "react-native"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ENOGIT

npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! Please include the following file with any support request:
npm ERR!     I:\react\MyProjecy\npm-debug.log

`npm install --save react-native` failed

I:\react>

**Comment by tarakpurohit** [comment]
I am having the same issue... 


```javascript 

npm install --save react-native
npm ERR! git clone --template=/Users/tarak/.npm/_git-remotes/_templates --mirror git://github.com/facebook/react.git /Users/tarak/.npm/_git-remotes/git-github-com-facebook-react-git-baa2986b: Cloning into bare repository '/Users/tarak/.npm/_git-remotes/git-github-com-facebook-react-git-baa2986b'...
npm ERR! git clone --template=/Users/tarak/.npm/_git-remotes/_templates --mirror git://github.com/facebook/react.git /Users/tarak/.npm/_git-remotes/git-github-com-facebook-react-git-baa2986b: fatal: unable to connect to github.com:
npm ERR! git clone --template=/Users/tarak/.npm/_git-remotes/_templates --mirror git://github.com/facebook/react.git /Users/tarak/.npm/_git-remotes/git-github-com-facebook-react-git-baa2986b: github.com[0: 192.30.252.129]: errno=Operation timed out
npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/tarak/.nvm/versions/node/v4.2.1/bin/node" "/Users/tarak/.nvm/versions/node/v4.2.1/bin/npm" "install" "--save" "react-native"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code 128

npm ERR! Command failed: git clone --template=/Users/tarak/.npm/_git-remotes/_templates --mirror git://github.com/facebook/react.git /Users/tarak/.npm/_git-remotes/git-github-com-facebook-react-git-baa2986b
npm ERR! Cloning into bare repository '/Users/tarak/.npm/_git-remotes/git-github-com-facebook-react-git-baa2986b'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.129]: errno=Operation timed out
npm ERR!
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tarak/Documents/ReactNative/npm-debug.log

```

**Comment by courtsimas** [comment]
+1 same for me.

**Comment by KenanY** [comment]
- @rongj Is getting a "File exists." from `git`
  - @carl1990 Is getting a "index-pack failed" error from `git`
  - @jozerozero does not have `git` installed (please read the error message)
  - @tarakpurohit Is having a connection timeout issue with regards to connecting to `github.com` (so this is an internet connection issue).

Each user here is experiencing a different issue than the rest yet everyone has commented as if they have @rongj's issue....

@courtsimas Same as who? (it's very ambiguous because of what I've said above)

**Comment by courtsimas** [comment]
I've just realized I had a mkdir issue, and it was solved with `sudo chown -R $USER:$GROUP ~/.npm` so apologies.

**Comment by rongj** [comment]
thanks,I have solved!

**Comment by KenanY** [comment]
Closing as resolved. Several different issues were reported in this one thread, [as I outlined above](https://github.com/npm/npm/issues/9882#issuecomment-154132987), so if any of you are still experiencing any issues with `npm` feel free to open a _new_ issue.
