### ISSUE TITLE
npm install failed with shasum error

### ISSUE THREAD

**Issue by khoanguyen123** [npm/npm#9893]
npm install failed with shasum error. Can't attach log file for some reason. Below is the hopefully relevant info:

'''
242154 verbose cwd c:\Users\g701533\workspace\rmui
242155 error Windows_NT 6.1.7601
242156 error argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
242157 error node v0.12.5
242158 error npm  v2.11.2
242159 error shasum check failed for C:\Users\g701533\AppData\Local\Temp\npm-19012-b18f811c\registry.npmjs.org\browser-sync-ui\-\browser-sync-ui-0.5.16.tgz
242159 error Expected: e08b5fb1d5c7587e996f815c4c5e7e4c2532f2e8
242159 error Actual:   1e9bed8e49a9ce2d0af923ff8380b0015c353eef
242159 error From:     https://registry.npmjs.org/browser-sync-ui/-/browser-sync-ui-0.5.16.tgz
242160 error If you need help, you may report this error at:
242160 error     <https://github.com/npm/npm/issues>
242161 verbose exit [ 1, true ]
'''

**Comment by KenanY** [comment]
@khoanguyen123 Have you tried running `npm cache clean`?

**Comment by khoanguyen123** [comment]
No. But I tried again, and it worked.

**Comment by ehsalazar** [comment]
@khoanguyen123 Good to hear. I'll close this for now. We’ll be happy to reopen if necessary.
