### ISSUE TITLE
node_modules/history always ends up in the NPM tarball

### ISSUE THREAD

**Issue by taion** [npm/npm#9894]
For some bizarre reason, `node_modules/history` seems to always get pulled into the NPM tarball when publishing a package that has the `history` package installed as a dependency. For a sampling, check e.g.:

- http://registry.npmjs.org/react-router/-/react-router-1.0.0-rc1.tgz
- http://registry.npmjs.org/react-bootstrap/-/react-bootstrap-0.27.0.tgz
- http://registry.npmjs.org/react-router-bootstrap/-/react-router-bootstrap-0.19.0.tgz

This happens when publishing with both npm2 and npm3. This hasn't directly caused issues for me, but apparently it causes problems for my users who use `npm shrinkwrap`, which chokes on the extraneous `node_modules/history` present under the package installed from NPM.

**Comment by Aweary** [comment]
If its just the `history` package maybe it's due to: [utils/tar.js#L73](https://github.com/npm/npm/blob/ff47bc138e877835f1c0f419fea5f5672110678a/lib/utils/tar.js#L73)

**Comment by taion** [comment]
That's pretty funny.

As far as I can tell it's just the `history` package. I don't have anything that depends on any packages named `changelog` or whatever, but that snippet does look pretty suspicious.

**Comment by KenanY** [comment]
I was about to say that the regex isn't in `npm@2` but then I found it in a dependency: https://github.com/npm/fstream-npm/blob/v1.0.5/fstream-npm.js#L102

**Comment by Aweary** [comment]
Should be able to confirm by checking a tarball that depends on the `changelog` or `changes` packages on npm

**Comment by KenanY** [comment]
(I'm using `npm` at 50ce116)

``` bash
$ git clone https://github.com/rackt/react-router.git
$ cd react-router/
$ npm install
$ npm pack
$ tar -ztf react-router-1.0.0-rc1.tgz | grep history
package/node_modules/history/package.json
...
```

Apply:

``` diff
diff --git a/lib/utils/tar.js b/lib/utils/tar.js
index 5b20160..03222e1 100644
--- a/lib/utils/tar.js
+++ b/lib/utils/tar.js
@@ -70,7 +70,7 @@ BundledPacker.prototype.applyIgnores = function (entry, partial, entryObj) {
   if (entry.match(/^(license|licence)(\.[^\.]*)?$/i)) return true
 
   // changelogs should never be ignored.
-  if (entry.match(/^(changes|changelog|history)(\.[^\.]*)?$/i)) return true
+  if (entry.match(/^(changes|changelog)(\.[^\.]*)?$/i)) return true
 
   // special rules.  see below.
   if (entry === 'node_modules' && this.packageRoot) return true
```

Then:

```
$ npm pack
$ tar -ztf react-router-1.0.0-rc1.tgz | grep history
(no matches)
```

Probably not the proper fix but I'm convinced that it is the cause of the issue :)

**Comment by Aweary** [comment]
It should probably just check whether the entry is currently contained within `node_modules`

**Comment by mjackson** [comment]
I did some more of my own analysis [here](https://github.com/rackt/react-router/issues/2195#issuecomment-146620769), but it basically just confirms what @KenanY already said.

This problem is particularly painful for us in the react-router package because we share some deps with the history package. In particular, we have a dev dependency on qs which means it is installed under `node_modules`. Then later, when users install react-router without dev dependencies they are missing qs.

I can work around this manually by clearing out my `node_modules` directory before I `npm pack`, but that's a nasty problem that is bound to resurface someday.

**Comment by timdorr** [comment]
> `if (entry.match(/^(changes|changelog|history)(\.[^\.]*)?$/i)) return true`

![](http://i.giphy.com/E2USislQIlsfm.gif)

So, this will also affect the [changelog](https://www.npmjs.com/package/changelog), [changes](https://www.npmjs.com/package/changes), and [license](https://www.npmjs.com/package/license) packages as well. 

Hard coding strikes again!

**Comment by taion** [comment]
To be fair, hardly anybody uses any of those :stuck_out_tongue:

**Comment by mjackson** [comment]
Ah, looks like this is a dup of https://github.com/npm/npm/issues/9642

**Comment by taion** [comment]
Oops, my bad. Closing this, then.
