### ISSUE TITLE
Error while installing phonegap through npm

### ISSUE THREAD

**Issue by nuthan63** [npm/npm#9895]
hey every one this is wat the error am getting while installing phonegap thro npm
please help me

cli.js" "install" "-g" "phonegap"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\nodejs\\node.exe" "C:\nodejs\node_modules\npm\bin\npm-
cli.js" "install" "-g" "phonegap"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\nodejs\\node.exe" "C:\nodejs\node_modules\npm\bin\npm-
cli.js" "install" "-g" "phonegap"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\nodejs\\node.exe" "C:\nodejs\node_modules\npm\bin\npm-
cli.js" "install" "-g" "phonegap"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\nodejs\\node.exe" "C:\nodejs\node_modules\npm\bin\npm-
cli.js" "install" "-g" "phonegap"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\nodejs\\node.exe" "C:\nodejs\node_modules\npm\bin\npm-
cli.js" "install" "-g" "phonegap"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\nodejs\\node.exe" "C:\nodejs\node_modules\npm\bin\npm-
cli.js" "install" "-g" "phonegap"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\nodejs\\node.exe" "C:\nodejs\node_modules\npm\bin\npm-
cli.js" "install" "-g" "phonegap"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\nodejs\\node.exe" "C:\nodejs\node_modules\npm\bin\npm-
cli.js" "install" "-g" "phonegap"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\nodejs\\node.exe" "C:\nodejs\node_modules\npm\bin\npm-
cli.js" "install" "-g" "phonegap"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\nodejs\\node.exe" "C:\nodejs\node_modules\npm\bin\npm-
cli.js" "install" "-g" "phonegap"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\nodejs\\node.exe" "C:\nodejs\node_modules\npm\bin\npm-
cli.js" "install" "-g" "phonegap"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\nodejs\\node.exe" "C:\nodejs\node_modules\npm\bin\npm-
cli.js" "install" "-g" "phonegap"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\nodejs\\node.exe" "C:\nodejs\node_modules\npm\bin\npm-
cli.js" "install" "-g" "phonegap"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\nodejs\\node.exe" "C:\nodejs\node_modules\npm\bin\npm-
cli.js" "install" "-g" "phonegap"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\nodejs\\node.exe" "C:\nodejs\node_modules\npm\bin\npm-
cli.js" "install" "-g" "phonegap"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

> ws@0.4.31 install C:\Users\Nuthan\AppData\Roaming\npm\node_modules\phonegap\no
> de_modules\connect-phonegap\node_modules\socket.io\node_modules\socket.io-client
> \node_modules\engine.io-client\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

C:\Users\Nuthan\AppData\Roaming\npm\node_modules\phonegap\node_modules\connect-p
honegap\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine
.io-client\node_modules\ws>if not defined npm_config_node_gyp (node "C:\nodejs\n
ode_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" r
ebuild )  else (node  rebuild )
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\nodejs\\node.exe" "C:\nodejs\node_modules\npm\bin\npm-
cli.js" "install" "-g" "phonegap"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! path C:\Users\Nuthan\AppData\Roaming\npm\phonegap
npm ERR! code EISDIR
npm ERR! errno -4068

npm ERR! EISDIR, open 'C:\Users\Nuthan\AppData\Roaming\npm\phonegap'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Nuthan\npm-debug.log

C:\Users\Nuthan>

**Comment by cmrose** [comment]
Hi Nuthan  - I'm no expert but you might want to start with installing ionic instead.  It's the latest iteration of phonegap.   http://ionicframework.com/getting-started/   

You may experience the problems I had but check this post and thread: https://github.com/npm/npm/issues/7862#issuecomment-146077003

**Comment by hawk4031** [comment]
@cmrose Ionic and Phonegap are both built on top of Cordova, but they are not the same framework.

**Comment by cmrose** [comment]
@hawk  Thanks for the correction - as I said I'm no expert :)
