### ISSUE TITLE
execute  npm install -g phonegap@3.5.0-0.21.14

### ISSUE THREAD

**Issue by XinMa1** [npm/npm#9897]
execute  npm install -g phonegap@3.5.0-0.21.14
then  

![install phonegap](https://cloud.githubusercontent.com/assets/12506038/10360834/8db0d7fa-6dd6-11e5-84a4-fa5c3b0cd00a.JPG)

**Comment by KenanY** [comment]
@XinMa1 Node.js v0.6 is no longer supported. Please try [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-node) Node.js.
