### ISSUE TITLE
npm ERR! fetch failed http://registry.cnpmjs.org/esprima-fb/download/esprima-fb-3001.1.0-dev-harmony-fb.tgz

### ISSUE THREAD

**Issue by GoldenForest** [npm/npm#9898]
npm ERR! fetch failed http://registry.cnpmjs.org/esprima-fb/download/esprima-fb-3001.1.0-dev-harmony-fb.tgz

**Comment by KenanY** [comment]
@GoldenForest Is there a `npm-debug.log` file you can upload as a [gist](https://gist.github.com/)? Does this issue also occur if you use the default registry?

**Comment by KenanY** [comment]
@GoldenForest Are you still having this issue? If so, could you provide the `npm-debug.log`?

**Comment by KenanY** [comment]
Closing as abandoned.
