### ISSUE TITLE
Offline package installing or solution for ntml auth

### ISSUE THREAD

**Issue by pedritin** [npm/npm#9900]
I'm getting <b><i>Cache Access Denied</i></b> from my proxy when I'm trying to fetch packages from http://registry.npmjs.com. I spoke with my domain admins and they say I can't do that because of domain policies. I don't know what to do cause I'm a beginner and also I'm cuban and there's a lot of things that my company's proxy doesn't allow me to do. Please help!!

**Comment by KenanY** [comment]
@pedritin Is this still an issue for you?

**Comment by KenanY** [comment]
Closing as abandoned.

**Comment by pedritin** [comment]
Sorry, I didn't realized about your question, maybe I didn't checked notifications, sorry again and yes, it stills is asn issue.

**Comment by KenanY** [comment]
@pedritin Thanks, reopening.

**Comment by pedritin** [comment]
So, nobody seems to know about this.

**Comment by KenanY** [comment]
I feel like this is more the fault of your proxy and not of `npm`. If you have any ideas of changes that could be made to `npm` that would resolve this, we're all ears, but until then I'm not sure what more could be done here.
