### ISSUE TITLE
 EPROTO: protocol error, symlink '../user-home/cli.js'

### ISSUE THREAD

**Issue by Braun20021991** [npm/npm#9901]
Hi guys!
Whout wrong with my local install.

vagrant@homestead:~/Code/lara$ npm install bower
npm WARN optional dep failed, continuing uglify-js@2.3.6
npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "bower"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! path ../user-home/cli.js
npm ERR! code EPROTO
npm ERR! errno -71
npm ERR! syscall symlink

npm ERR! EPROTO: protocol error, symlink '../user-home/cli.js' -> '/home/vagrant/Code/lara/node_modules/bower/node_modules/.bin/user-home'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "bower"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! path npm-debug.log.6ad97a0d642b8fa94d90ad2a5f4e3e9c
npm ERR! code ETXTBSY
npm ERR! errno -26
npm ERR! syscall rename

npm ERR! ETXTBSY: text file is busy, rename 'npm-debug.log.6ad97a0d642b8fa94d90ad2a5f4e3e9c' -> 'npm-debug.log'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/Code/lara/npm-debug.log

**Comment by KenanY** [comment]
@Braun2002 Is this Vagrant on top of Windows? You cannot use symlinks then. Try using the
[`--no-bin-links`](https://docs.npmjs.com/misc/config#bin-links) flag.

**Comment by wolfius** [comment]
I'm also having this problem right now, Vagrant running on OSX

npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! path ../user-home/cli.js
npm ERR! code EPROTO
npm ERR! errno -71
npm ERR! syscall symlink

npm ERR! EPROTO: protocol error, symlink '../user-home/cli.js' -> '/home/vagrant/Sites/laravel/node_modules/gulp/node_modules/v8flags/node_modules/.bin/user-home'

**Comment by KenanY** [comment]
@wolfius Did you try my suggestion to @Braun2002?

**Comment by wolfius** [comment]
@KenanY my bad! that did it. I was ignoring the flag even though it was in the laravel elixir documentation because its supposed to be for VMs running on Windows machines, but well, worked on OSX too. Thanks!

**Comment by flitbit** [comment]
Confirming; on Mac OS X, using docker-machine/boot2docker, the same issue occurs inside a docker container when`npm install` is executed within a directory that is mounted as a volume from the host. Likewise, adding the `--no-bin-links` flag to the command eliminates the error: `npm install --no-bin-links`.

**Comment by simonewebdesign** [comment]
@KenanY @flitbit `npm install --no-bin-links` worked for us too (we use docker-machine). Thanks!

**Comment by Rykka** [comment]
works

**Comment by matthewp** [comment]
Is there a better solution? bin symlinks is an important feature.

**Comment by aantipov** [comment]
For non-windows users: it seems like the real problem was with creation of symlinks containing `../`and this problem is fixed in latest versions of virtualbox https://www.virtualbox.org/ticket/14563

But in my case I was the only one of our team who experienced the problem and I think this was because I had Vritualbox installed via `brew cask`.

So I removed Virtualbox installed through `brew cask` and then downloaded and installed the latest version from the official site and that solved the problem for me (OS X El Capitan 10.11.1).

**Comment by mandersondesign** [comment]
Thanks @aantipov! That was incredibly helpful.

**Comment by surajpadhy** [comment]
@KenanY, Thanks worked for me +1:

**Comment by tianaorrego** [comment]
Thanks, works for me too!

**Comment by atanl** [comment]
@KenanY you save my life.

**Comment by vazh** [comment]
is there any way to make `npm install` with `--no-bin-links` by default.
so that i dont have to write `--no-bin-links` everytime i use `npm install`

**Comment by KenanY** [comment]
@vazh How about:

``` bash
$ npm config set bin-links false
```

**Comment by vazh** [comment]
@KenanY thanks, it works. much appreciated.

**Comment by KenanY** [comment]
Closing as resolved.

**Comment by Dmitrev** [comment]
@wolfius and everyone who was interested in a better solution without using `--no-bin-links`

By default on Windows only the System user can create symlinks, so in order to use this in a VM you would have to use `vagrant up` inside an administrator command prompt.

Source: http://serverfault.com/a/477159

**Comment by Azovsky** [comment]
@KenanY, @Dmitrev, yes, just need to run the Wndows CLI as administrator and symlinks will working fine.
Thanks!

**Comment by jehy** [comment]
If you don't want to run virtualbox as administrator, you can allow creating symbolic links for all users:

1. Open the Local Group Policy Editor (gpedit.msc)
2. Edit the Create symbolic links policy at:

Computer configuration → Windows Settings → Security Settings → Local Policies → User Rights Assignment → Create symbolic links
