### ISSUE TITLE
npm install logging???

### ISSUE THREAD

**Issue by gravidThoughts** [npm/npm#9904]
I am making the change to npm 3. I have a package.json with an extensive collection of node modules. 

Running `npm install` in node.js command prompt on windows box is producing a ton of errors taht fall out of the console buffer, even at maximum size.

I cannot find a npm-debug.log being produced anywhere.

Is there not a simple mechanism for piping the output of `npm install` to a file?

**Comment by KenanY** [comment]
@gravidThoughts 

> Is there not a simple mechanism for piping the output of `npm install` to a file?

I don't know about Windows, but on Unix I can do:

``` sh
npm install 2> file.log
```

**Comment by gravidThoughts** [comment]
nvm I am embarrassed I asked this lol. Just got all caught up in the fact that an `npm-debug.log` file was not being produced.

Windows supports the same as unix `npm install>install.log`
