### ISSUE TITLE
UNABLE_TO_GET_ISSUER_CERT_LOCALLY

### ISSUE THREAD

**Issue by fredramsey** [npm/npm#9906]
Here's the log (see further down for a log from Visual Studio 2015):

0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'gulp',
1 verbose cli   '-g' ]
2 info using npm@2.14.4
3 info using node@v4.1.2
4 verbose install initial load of C:\Users\ramsey_f\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\ramsey_f\AppData\Roaming\npm\package.json
6 silly cache add args [ 'gulp', null ]
7 verbose cache add spec gulp
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'gulp',
8 silly cache add   scope: null,
8 silly cache add   name: 'gulp',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '_',
8 silly cache add   type: 'range' }
9 silly addNamed gulp@_
10 verbose addNamed "_" is a valid semver range for gulp
11 silly addNameRange { name: 'gulp', range: '_', hasData: false }
12 silly mapToRegistry name gulp
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/gulp
16 verbose addNameRange registry:https://registry.npmjs.org/gulp not in flight; fetching
17 verbose request uri https://registry.npmjs.org/gulp
18 verbose request no auth needed
19 info attempt registry request try #1 at 2:04:12 PM
20 verbose request id 4bdb874fb127c3d6
21 http request GET https://registry.npmjs.org/gulp
22 info retry will retry, error on last attempt: Error: unable to get local issuer certificate
23 info attempt registry request try #2 at 2:04:22 PM
24 http request GET https://registry.npmjs.org/gulp
25 info retry will retry, error on last attempt: Error: unable to get local issuer certificate
26 info attempt registry request try #3 at 2:05:22 PM
27 http request GET https://registry.npmjs.org/gulp
28 verbose stack Error: unable to get local issuer certificate
28 verbose stack     at Error (native)
28 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:1000:38)
28 verbose stack     at emitNone (events.js:67:13)
28 verbose stack     at TLSSocket.emit (events.js:166:7)
28 verbose stack     at TLSSocket._finishInit (_tls_wrap.js:567:8)
29 verbose cwd Y:\
30 error Windows_NT 6.1.7601
31 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "gulp" "-g"
32 error node v4.1.2
33 error npm  v2.14.4
34 error code UNABLE_TO_GET_ISSUER_CERT_LOCALLY
35 error unable to get local issuer certificate
36 error If you need help, you may report this error at:
36 error     https://github.com/npm/npm/issues
37 verbose exit [ 1, true ]
Visual Studio 2015:

====Executing command 'npm install'====

npm http GET https://registry.npmjs.org/gulp
npm http GET https://registry.npmjs.org/gulp-config
npm http GET https://registry.npmjs.org/gulp-bower
npm http GET https://registry.npmjs.org/gulp-less
npm http GET https://registry.npmjs.org/gulp-plumber
npm http GET https://registry.npmjs.org/gulp-plumber
npm http GET https://registry.npmjs.org/gulp-config
npm http GET https://registry.npmjs.org/gulp
npm http GET https://registry.npmjs.org/gulp-bower
npm http GET https://registry.npmjs.org/gulp-less
npm http GET https://registry.npmjs.org/gulp-plumber
npm http GET https://registry.npmjs.org/gulp-config
npm http GET https://registry.npmjs.org/gulp
npm http GET https://registry.npmjs.org/gulp-bower
npm http GET https://registry.npmjs.org/gulp-less
npm ERR! Error: CERT_UNTRUSTED
npm ERR!     at SecurePair.<anonymous> (tls.js:1367:32)
npm ERR!     at SecurePair.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:979:10)
npm ERR!     at CleartextStream.read [as _read](tls.js:471:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:340:10)
npm ERR!     at EncryptedStream.write [as _write](tls.js:368:25)
npm ERR!     at doWrite (_stream_writable.js:225:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:215:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:182:11)
npm ERR!     at write (_stream_readable.js:601:24)
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/npm/npm/issues
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\\node\node" "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\npm\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! cwd D:\Development\Cass.Web\Cass.Web.VendorSetup\Dev\Cass.Web.VendorSetup
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.9
npm

====npm command completed with exit code 1====

**Comment by neocotic** [comment]
I've also been seeing this since upgrading to node 4.x.

**Comment by Marco-ST** [comment]
me too

**Comment by Marco-ST** [comment]
by using nmp install --registry http://registry.npmjs.org/, it fixed the problem for me
The workaround is to use http instead of https
