### ISSUE TITLE
npm install works on npm@2, fails on npm@3

### ISSUE THREAD

**Issue by seantimm** [npm/npm#9907]
I'm getting the following error when doing a clean npm install with npm@3:

-------------------------------------------
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/Cellar/node/4.1.2/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.1.2
npm ERR! npm  v3.3.6
npm ERR! path /Users/sean/Projects/ui.assets/node_modules/babel-core/node_modules/json5/b
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/sean/Projects/ui.assets/node_modules/babel-core/node_modules/json5/b'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
-------------------------------------------

I don't know if it's expected, but it seems strange that the path is getting clipped (i.e. json5/b).

Here's the npm-debug.log in full: https://gist.githubusercontent.com/seantimm/3221437d01b8ab3eaa2f/raw/75a8089c400aa8d55498388fcfd85824f9bb64cf/npm-debug.log

**Comment by seantimm** [comment]
Also, if I do an npm shrinkwrap on my npm@2 box and then do an npm install with the shrinkwrap in place on my npm@3 box, it installs fine.

**Comment by boneskull** [comment]
I am also having this issue with `@next`

**Comment by seantimm** [comment]
This is still happening in 3.3.9.

**Comment by tboyce** [comment]
Seeing the same thing here, with various packages. Also a clean install.

**Comment by seantimm** [comment]
It turns out this is an issue with ProGet (my npm private server).  If I point directly to the npm server, it works fine.

**Comment by boneskull** [comment]
@seantimm please reopen this; it affects other not using your private server

**Comment by seantimm** [comment]
If you have specific details with a problem that fails against the public server, you should open a new ticket with details that will help them solve your problem.  None of the info I linked will help them since the debug info I provided works fine against the public repo.

**Comment by seantimm** [comment]
@boneskull Oddly enough, npm@3.33.11 resolved this issue for me, so maybe it was an npm issue after all?  Seems weird it would work with the official and not with a private, but I'm just glad to have it finally working!

**Comment by tboyce** [comment]
I am also using ProGet.

**Comment by tboyce** [comment]
The issue is also resolved here with npm@3.3.11
