### ISSUE TITLE
update ionic error

### ISSUE THREAD

**Issue by wangjing0716** [npm/npm#9913]
node v0.12.7
npm 2.11.3
cordova 5.3.1
when I update ionic from 1.6.4 to 1.6.5 with the cmd (npm install -g ionic),it is error
tar.unpack ^^^^^
then I input : npm cache clean
the error is the same

**Comment by faiq** [comment]
Hey- can you please post the logs from error that you're getting so we could help you better? 
Also you should try updating npm by doing `sudo npm install -g npm` it's possible that just updating your npm and trying to install ionic might work!

**Comment by wangjing0716** [comment]
sorry,I don't find the logs where is in C:/users/me/npm-debug.log,and it cannot upload the printscreen or photo about the error.
the error is tar.unpack untar C:\Users ……

**Comment by faiq** [comment]
hey, can you try run the command `npm install -g ionic` with an administrator command prompt? 

the problem could be that npm needs extra permissions to write stuff globally

**Comment by wangjing0716** [comment]
yes,I have tried run the command npm install -g ionic with an administrator command prompt
but it run more than 1 hour.I still wait it

**Comment by wangjing0716** [comment]
the problem is still exist, I hava uninstall ionic,and clean the cache ,then install ionic with signed version 1.6.4，(by the way ,ionic update to 1.7.0,)error is still tar.unpack untar……I‘m breakdown

**Comment by snopeks** [comment]
Hello @wangjing0716, is this still an issue? Do you need ionic version `1.6.5` specifically or are you trying to get the most recent update? 
If you need `1.6.5` specifically, can you try running `npm install -g ionic@1.6.5` and let me know what the results are?

If this isn't the issue, it would be really helpful if you can screenshot your error and drag/drop the screenshot into your github comment.

**Comment by wangjing0716** [comment]
Thank you,I have installed ionic using the sentence npm install -g ionic@1.6.5,but it is still wrong.Fortunately,I installed ionic successfully a few days ago,just npm install -g ionic,and its version is  1.7.7.I think install ionic is a matter of luck.

**Comment by snopeks** [comment]
@wangjing0716 I am glad to hear you were able to install ionic! I'm going to close this as resolved now. If you have issues with future installs you can always email support@npmjs.com, we'll be here to help.
