### ISSUE TITLE
Feature Request: Subcommand `npm scripts` to list package scripts for current project

### ISSUE THREAD

**Issue by halhenke** [npm/npm#9914]
For the lazy (me) 
Basically equivalent to:

```
npm info . scripts
```

which, while perfectly usable, was not something i knew you could do until checking into this. A fact that I will also submit to the court under the "laziness" appeal....
 
Related to #8030 I suppose.

**Comment by othiym23** [comment]
Have you tried `npm run` (with no extra arguments)?

**Comment by halhenke** [comment]
...I had not. 

![](http://i.giphy.com/Z6f7vzq3iP6Mw.gif)

Problem solved - thanks!

**Comment by othiym23** [comment]
:tada: You're welcome!
