### ISSUE TITLE
npm install <folder> fails if preinstall-script has npm uninstall <folder> with npm@3.3.6

### ISSUE THREAD

**Issue by hacker112** [npm/npm#9916]
Problem in version: 3.3.6
Worked fine in version: 2.11.3

When working with servers that should not have direct access to the git-repos we use git-submodules sync them to the servers and use local folders to install them as npm packages. (through  "npm install --save path/to/submodule" )

Since installing local submodules is only done once and we need to make sure that the package is refreshed each time "npm install" is run. We added preinstall script like this:

``` json
  "scripts": {
    "preinstall": "npm uninstall path/to/submodule"
  }
```

This works fine npm 2 where it uninstalls the package and then reinstalls it. 
In npm 3 it fails to install the package at all when the preinstall script is there.

**Comment by nadavsinai** [comment]
I am suffering from this too, we used symlinks to simplify require pathes - with a helper module  called [slinker](https://www.npmjs.com/package/slinker) the thing is that with shrinkwrap npm will remove any module not found in the npm-shrinkwrap.json  recursively  - destroying the target of the symlinks
we used to use the preinstall script to remove the symlinks and postinstall to add them
npm 3.3.6 runs preinstall too late - after the clearning of the node_modules.
