### ISSUE TITLE
Facing error while using npm start

### ISSUE THREAD

**Issue by RohitLuthra19** [npm/npm#9918]
C:\Program Files\nodejs>npm start
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files\nodejs\npm-debug.log

**Comment by KenanY** [comment]
@RohitLuthra19 Do you have a `"start"` script defined in your `package.json`?

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.

**Comment by RohitLuthra19** [comment]
My all issues are resolved now these all are due to proxy authentication problem.....Thanks for your response
