### ISSUE TITLE
Can I have npm install packages to different custom directories?

### ISSUE THREAD

**Issue by SetTrend** [npm/npm#9921]
AFAIK, *npm* always seems to install JavaScript libraries, like AngularJS or jQuery, into the same root directory. I may change that root directory but I don't seem to be able to provide an additional path for each of the packages.

I want to manually choose a dedicated target (sub) directory for each of the packages when installing them so they won't conflict with other NuGet packages.

How can I do this?

I imagine something similar to:

```javascript
{
  dependencies:
  {
    "jquery":  { "^2.1.0", "jQuery/v2" }
  , "angular": { "^1.5.0", "ng" }
  }
}
```

... resulting in ...

```
./Scripts/jQuery/v2/jquery-2.1.0.min.js
./Scripts/ng/angular-1.5.0.min.js
```

**Comment by othiym23** [comment]
I believe this is similar to the behavior described on the [npm road map](https://github.com/npm/npm/wiki/Roadmap-area-of-focus%3A-browser-dependencies) as the "front-end asset installer". It may not work exactly as you describe here, but the desired functionality is the same. As this is something we're already tracking on the road map, I'm going to close this feature request, but this is definitely something we want to tackle within the next 6-18 months.
