### ISSUE TITLE
sha checksum failed for mongoose-4.1.10.tgz

### ISSUE THREAD

**Issue by bhavyakamboj** [npm/npm#9930]
Below is the log
bhavya@bhavya-Lenovo-IdeaPad-Y500:~/Desktop/test-app$ npm install mongoose --save
npm WARN package.json http-server@ No description
npm WARN package.json http-server@ No repository field.
npm WARN package.json http-server@ No README data
^Cbhavya@bhavya-Lenovo-IdeaPad-Y500:~/Desktop/test-app$ npm install mongoose --save
npm WARN package.json http-server@ No description
npm WARN package.json http-server@ No repository field.
npm WARN package.json http-server@ No README data
npm ERR! Error: shasum check failed for /tmp/npm-4794-ua-lAnY+/registry.npmjs.org/mongoose/-/mongoose-4.1.10.tgz
npm ERR! Expected: af2404730de04422828d65b34fc89bea0e8f9cd0
npm ERR! Actual:   dd893803be6f6fbe6ce3be93e83f2c884779bca1
npm ERR! From:     https://registry.npmjs.org/mongoose/-/mongoose-4.1.10.tgz
npm ERR!     at /usr/lib/nodejs/sha/index.js:38:8
npm ERR!     at ReadStream.<anonymous> (/usr/lib/nodejs/sha/index.js:85:7)
npm ERR!     at ReadStream.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>
npm ERR! System Linux 3.19.0-28-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "mongoose" "--save"
npm ERR! cwd /home/bhavya/Desktop/test-app
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/bhavya/Desktop/test-app/npm-debug.log
npm ERR! not ok code 0

**Comment by KenanY** [comment]
@bhavyakamboj Have you tried running `npm cache clean`? Does this also occur if you [update](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) to the latest stable release of `npm`?

**Comment by snopeks** [comment]
hello @bhavyakamboj, we haven’t heard back and we’re trying to clean up some issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.
