### ISSUE TITLE
Not able to install npm

### ISSUE THREAD

**Issue by naturalfreak** [npm/npm#9933]
npm install -g npm
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\test\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "npm"
npm ERR! node v4.1.2
npm ERR! npm  v3.3.4
npm ERR! code ENOSELF

npm ERR! Refusing to install npm as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\test\npm-debug.log

**Comment by scottaddie** [comment]
I'm seeing this message this morning as well. The only difference is I'm running Node v4.2.0. Trying to upgrade to NPM v3.3.6.

**Comment by KenanY** [comment]
@naturalfreak Sorry for the late response. Are you still facing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.

**Comment by scottaddie** [comment]
@KenanY Thank you for following up. I no longer see this problem.
