### ISSUE TITLE
node_modules folder is messed up

### ISSUE THREAD

**Issue by paulca55** [npm/npm#9934]
I think this problem has only appeared since updating Node.js (4.1.2) and npm (3.3.7) on WIndows but now any package I install doesn't go into its own specific folder within the node_modules folder, but instead all the contents of each package are all mixed up in one place.

Please see the attached photo of how it looked before and how it looks now. Any help will be greatly appreciated.

Before
![before](https://cloud.githubusercontent.com/assets/7057526/10411235/6019f07a-6f56-11e5-8b1d-0c1480e1f975.JPG)

After
![after](https://cloud.githubusercontent.com/assets/7057526/10411237/6959dc54-6f56-11e5-9542-4c469596f03f.JPG)

**Comment by KenanY** [comment]
@paulca55 Are you sure that you are not just experiencing one of the defining new features of `npm@3`?:

> Your dependencies will now be installed _maximally flat_. Insofar as is possible, all of your dependencies, and their dependencies, and THEIR dependencies will be installed in your project's `node_modules` folder with no nesting. You'll only see modules nested underneath one another when two (or more) modules have conflicting dependencies.

https://github.com/npm/npm/releases/tag/v3.0.0

**Comment by paulca55** [comment]
Thanks KenanY that does appear to be the case. I'm still very new to this so please forgive me, I should of read all of the release notes. This is actually really good news as I previously had a lot of problems with long paths in Windows. Thanks again.
