### ISSUE TITLE
Nested npm run scripts

### ISSUE THREAD

**Issue by cbas** [npm/npm#9935]
What are the thoughts on adding support to nest scripts?

Rough idea:
```json
{ "scripts": {
  "test": {
    "tdd": { "js": "mocha --watch" },
    "lint": { "js": "standard", "css": "postcss", "html": "htmllint frontend" },
    "audit": "node-license-validator --deep"
  },
  "dev": "npm run test.tdd & http-server",
  "start": "npm run audit && forever"
} }
```

This would avoid the repetition in property names that I see in many [substack-esque, pseudo-nested packages](http://substack.net/task_automation_with_npm_run).

I am not yet familiar with the `npm run` implementation but happy to take a look and do a PR if this idea is not deemed too terrible. :stuck_out_tongue_winking_eye:

**Comment by faiq** [comment]
I'm a heavy user of npm scripts, and I don't really see myself using this feature. I usually just combine things together the pseudo nested way and its worked just fine.

Also from an implementation standpoint, adding this kind of complexity seems pretty hard.

**Comment by ehsalazar** [comment]
@cbas Thanks for submitting the idea. It looks you received a response via #9970. I'll close this issue out as you'd closed the other as well.

**Comment by cbas** [comment]
@ehsalazar :+1: Thanks!
