### ISSUE TITLE
Unable to install Yeoman

### ISSUE THREAD

**Issue by KelCard** [npm/npm#9938]
Hi all. I am unaable to install Yeoman. Here are the errors.

> spawn-sync@1.0.13 postinstall /usr/local/lib/node_modules/yo/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"v0.10.25","npm":"1.3.10"})
npm WARN engine boom@2.9.0: wanted: {"node":">=0.10.40"} (current: {"node":"v0.10.25","npm":"1.3.10"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"v0.10.25","npm":"1.3.10"})
npm http GET https://registry.npmjs.org/generate-function
npm http GET https://registry.npmjs.org/jsonpointer/2.0.0
npm http GET https://registry.npmjs.org/generate-object-property
npm ERR! Error: ENOENT, open '/usr/local/lib/node_modules/yo/node_modules/lodash/internal/composeArgs.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.16.0-38-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "yo"
npm ERR! cwd /home/kelly
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/yo/node_modules/lodash/internal/composeArgs.js
npm ERR! code ENOENT
npm ERR! errno 34
npm http 304 https://registry.npmjs.org/jsonpointer/2.0.0
npm http 304 https://registry.npmjs.org/generate-object-property
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/yo/node_modules/insight/node_modules/inquirer/node_modules/rx/dist/rx.time.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.16.0-38-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "yo"
npm ERR! cwd /home/kelly
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/yo/node_modules/insight/node_modules/inquirer/node_modules/rx/dist/rx.time.js
npm ERR! fstream_path /usr/local/lib/node_modules/yo/node_modules/insight/node_modules/inquirer/node_modules/rx/dist/rx.time.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/yo/node_modules/insight/node_modules/request/node_modules/har-validator/node_modules/bluebird/js/main'
npm ERR! error rolling back  yo@1.4.8 { [Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/yo/node_modules/insight/node_modules/request/node_modules/har-validator/node_modules/bluebird/js/main']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/yo/node_modules/insight/node_modules/request/node_modules/har-validator/node_modules/bluebird/js/main' }
npm ERR! weird error 1
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/yo/node_modules/insight/node_modules/request/node_modules/http-signature/node_modules/ctype/man/man3ctype/ctio.3ctype'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.16.0-38-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "yo"
npm ERR! cwd /home/kelly
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/yo/node_modules/insight/node_modules/request/node_modules/http-signature/node_modules/ctype/man/man3ctype/ctio.3ctype
npm ERR! fstream_path /usr/local/lib/node_modules/yo/node_modules/insight/node_modules/request/node_modules/http-signature/node_modules/ctype/man/man3ctype/ctio.3ctype
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/yo/node_modules/insight/node_modules/request/node_modules/hawk/node_modules/sntp/lib/index.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.16.0-38-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "yo"
npm ERR! cwd /home/kelly
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/yo/node_modules/insight/node_modules/request/node_modules/hawk/node_modules/sntp/lib/index.js
npm ERR! fstream_path /usr/local/lib/node_modules/yo/node_modules/insight/node_modules/request/node_modules/hawk/node_modules/sntp/lib/index.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/grouped-queue/node_modules/lodash/dist/lodash.min.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.16.0-38-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "yo"
npm ERR! cwd /home/kelly
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/grouped-queue/node_modules/lodash/dist/lodash.min.js
npm ERR! fstream_path /usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/grouped-queue/node_modules/lodash/dist/lodash.min.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/yo/node_modules/insight/node_modules/request/node_modules/hawk/node_modules/boom/images/boom.png'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.16.0-38-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "yo"
npm ERR! cwd /home/kelly
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/yo/node_modules/insight/node_modules/request/node_modules/hawk/node_modules/boom/images/boom.png
npm ERR! fstream_path /usr/local/lib/node_modules/yo/node_modules/insight/node_modules/request/node_modules/hawk/node_modules/boom/images/boom.png
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/yo/node_modules/insight/node_modules/request/node_modules/hawk/node_modules/hoek/images/hoek.png'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.16.0-38-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "yo"
npm ERR! cwd /home/kelly
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/yo/node_modules/insight/node_modules/request/node_modules/hawk/node_modules/hoek/images/hoek.png
npm ERR! fstream_path /usr/local/lib/node_modules/yo/node_modules/insight/node_modules/request/node_modules/hawk/node_modules/hoek/images/hoek.png
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http 304 https://registry.npmjs.org/generate-function
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/yo/node_modules/package-json/node_modules/got/node_modules/read-all-stream/node_modules/readable-stream/doc/stream.markdown'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.16.0-38-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "yo"
npm ERR! cwd /home/kelly
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/yo/node_modules/package-json/node_modules/got/node_modules/read-all-stream/node_modules/readable-stream/doc/stream.markdown
npm ERR! fstream_path /usr/local/lib/node_modules/yo/node_modules/package-json/node_modules/got/node_modules/read-all-stream/node_modules/readable-stream/doc/stream.markdown
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http GET https://registry.npmjs.org/is-property
npm ERR! Error: ENOENT, lstat '/home/kelly/tmp/npm-8502-2973ulkU/1444503239732-0.5106878282967955/package/docs/twig.html'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.16.0-38-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "yo"
npm ERR! cwd /home/kelly
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/kelly/tmp/npm-8502-2973ulkU/1444503239732-0.5106878282967955/package/docs/twig.html
npm ERR! fstream_path /home/kelly/tmp/npm-8502-2973ulkU/1444503239732-0.5106878282967955/package/docs/twig.html
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http 304 https://registry.npmjs.org/is-property
npm http GET https://registry.npmjs.org/isarray/0.0.1
npm http GET https://registry.npmjs.org/core-util-is
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/process-nextick-args
npm http GET https://registry.npmjs.org/string_decoder
npm http GET https://registry.npmjs.org/util-deprecate
npm http 304 https://registry.npmjs.org/string_decoder
npm http 304 https://registry.npmjs.org/core-util-is
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/process-nextick-args
npm http 304 https://registry.npmjs.org/isarray/0.0.1
npm http 304 https://registry.npmjs.org/util-deprecate
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/kelly/npm-debug.log
npm ERR! not ok code 0

**Comment by KenanY** [comment]
@KelCard Please try [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm). `npm@1.3` is no longer supported.

**Comment by KelCard** [comment]
Thank you
