### ISSUE TITLE
Some dependecies of dependencies are not installed in version 3.3.6

### ISSUE THREAD

**Issue by volkanunsal** [npm/npm#9939]
There are two specific packages that are not getting their dependencies installed:

```
karma-chrome-launcher
karma-babel-preprocessor
```

Not sure if this is a problem on their part or something wrong with npm....

**Comment by KenanY** [comment]
@volkanunsal So, to clarify, running `npm install karma-chrome-launcher` will install that package but not its dependencies? What version of `npm` and Node.js are you running? What operating system?

**Comment by KenanY** [comment]
@volkanunsal I cannot reproduce this with Node.js v4.1.2 and `npm@3.3.7` on Linux:

``` sh
$ npm install karma-chrome-launcher
$ npm ls
/home/kenan/Code/npm-9939
└─┬ karma-chrome-launcher@0.2.1
  ├─┬ fs-access@1.0.0
  │ └── null-check@1.0.0
  └─┬ which@1.2.0
    └─┬ is-absolute@0.1.7
      └── is-relative@0.1.3

$ rm -rf node_modules/

$ npm install karma-babel-preprocessor
$ npm ls --depth 1
/home/kenan/Code/npm-9939
└─┬ karma-babel-preprocessor@5.2.2
  └── babel-core@5.8.25
```

**Comment by volkanunsal** [comment]
@KenanY It's working now. I installed packages that raised peer dependency warnings, and other packages that preferred global, and s on, and after a few hours it's finally working now. Not sure what the problem was originally, but I might just close this because it's working for now.
