### ISSUE TITLE
npm view local project information

### ISSUE THREAD

**Issue by mstade** [npm/npm#9942]
Using `npm view` it's trivial to find out information about a package _in the registry_, however there seems to be no matching utility for viewing information about a package locally. Working on a project, it's sometimes necessary (in shell scripts for instance) to get information about a package, and it seems as though currently the only recourse you have is to parse package.json yourself.

So consider this a feature request: either change the behavior of `npm view` to print information about a locally installed package, in case `<name>` is a path (perhaps requiring paths to start with `./`, `../` or `/`) or by some other means add the ability to view details about a locally installed packages.

If there is such a way (that doesn't involve installing additional packages or esoteric non-DRY scripting) I'd love to know!

**Comment by busches** [comment]
@othiym23 Is this a feature the `npm` team would like added to `npm`?

**Comment by mstade** [comment]
FWIW, I implemented the functionality I need in a little CLI: https://github.com/mstade/npm-inspect

The docs are magical, I know, sorry about that. The usage is essentially `npm-inspect <property>` where `<property>` is something like `version` or for deeper access use dot-notation, e.g. `author.name`. The output should be shell safe, so each line can be exported as a shell variable, e.g. `eval $(npm-inspect devDependencies)` would set variables for each dev dependency in the package.json. It's been very useful to me, and I use it constantly, but maybe this is an edge case.
