### ISSUE TITLE
ETIMEDOUT in Windows 10 with latest node.js stable (64bit)

### ISSUE THREAD

**Issue by ditikos** [npm/npm#9943]
I am trying to install the following modules:

- bower
- npm-windows-upgrade

Both from the .org repository and the .eu (I live in Greece).

I am getting ETIMEDOUT:

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "i" "-g" "bower"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.4
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect

npm ERR! network connect ETIMEDOUT 144.76.114.210:80
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:

Which is not correct, because I am also running a virtual machine (virtualbox briged nat) and a macbook pro in the same network and they have installed bower (the most important) correctly. Any other modules are installed without hassle like grunt or passport or everything else on ALL machines.

I've upgraded my git, cleaned npm cache, reinstalled node.js nothing work.

**Comment by smartmouse** [comment]
On your macbook pro and vm that worked, if you do npm get config proxy, does it show NULL?
Is it same as the windows that fails?

**Comment by ditikos** [comment]
Yes in every occasion. I have no proxies. I am using a home router, upnp enabled, no firewall setup on windows (disabled it myself yesterday to see if that was the culprit). All my computers are getting ips from the same dhcp pool 192.168.1.x (10 to 13).

One difference -- in linux (LUBUNTU) I have the 0.10.40 branch yet (the one stocked with the current lubuntu), while in everything else is the 4.1.2 nodejs with the appropriate npm (listed above in the error).

**Comment by ditikos** [comment]
An update. After yesterday's release of Bower, npm installed it fast and properly. Which makes me believe that the problem was not on my network afterall but on bower.
