### ISSUE TITLE
error while sudo npm install -g meanio@latest --registry https://registry.npmjs.org/

### ISSUE THREAD

**Issue by venkatesh1453** [npm/npm#9944]
> meanio@0.8.82 postinstall /usr/local/lib/node_modules/meanio
> cd ./lib/core_modules/server && npm install && cd ../../..

npm ERR! addLocal Could not install .
npm ERR! Error: No version provided
npm ERR!     at needVersion (/usr/local/lib/node_modules/npm/lib/cache.js:1446:40)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:1253:10
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:51:40
npm ERR!     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:349:17)
npm ERR!     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:126:33)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:316:48
npm ERR!     at fs.js:207:20
npm ERR!     at OpenReq.Req.done (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:144:5)
npm ERR!     at OpenReq.done (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:64:22)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 14.4.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /usr/local/lib/node_modules/meanio/lib/core_modules/server
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/local/lib/node_modules/meanio/lib/core_modules/server/npm-debug.log
npm ERR! not ok code 0
npm ERR! meanio@0.8.82 postinstall: `cd ./lib/core_modules/server && npm install && cd ../../..`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the meanio@0.8.82 postinstall script.
npm ERR! This is most likely a problem with the meanio package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd ./lib/core_modules/server && npm install && cd ../../..
npm ERR! You can get their info via:
npm ERR!     npm owner ls meanio
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 14.4.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "meanio@latest" "--registry" "https://registry.npmjs.org/"
npm ERR! cwd /Users/venkatesha.p/dp/mean-on-openshift
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/venkatesha.p/dp/mean-on-openshift/npm-debug.log
npm ERR! not ok code 0

+++++++++++++++++++++++++++++++++++++++
npm -v
1.4.9
++++++++++++++++++++++++++++++++++++++++
node -v
v0.10.28

**Comment by KenanY** [comment]
@venkatesh1453 Does this also occur if you [upgrade](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) to the latest stable release of `npm`?

**Comment by snopeks** [comment]
Hello @venkatesh1453 We haven’t heard back and we’re trying to clean up some issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.
