### ISSUE TITLE
Feature: Implement require("@parent/myfile") to get parent module

### ISSUE THREAD

**Issue by Alphapage** [npm/npm#9945]
Hello,

It is very difficult to get the parent of a module.
As we don't need to know the parent's name, I think it would be interesting to have a syntax like this:
```
import * from "@parent/test";
var test = require("@parent/shared");
```
This would be a great and easy to use feature for plugins.

Hope (@parent, #parent,@@parent... wathever you want) could be implemented in the near future.

**Comment by KenanY** [comment]
@Alphapage So, you are asking to change the behavior of `require()`? You should open this at the Node.js repo then, this is `npm` the package manager which does not implement `require()`. Do note however that the [modules API](https://nodejs.org/api/modules.html) is locked.
