### ISSUE TITLE
Error: EPERM: operation not permitted, ftruncate

### ISSUE THREAD

**Issue by RamuSamudrala** [npm/npm#9946]
"calling gulp build ******************"
     [exec] fs.js:750
     [exec]   return binding.ftruncate(fd, len);
     [exec]                  ^
     [exec] Error: EPERM: operation not permitted, ftruncate
     [exec]     at Error (native)
     [exec]     at Object.fs.ftruncateSync (fs.js:750:18)
     [exec]     at Object.setSiteAbbr (C:\Urban\Bit_bucket_Anthro\anthroweb\gulp\site-config.js:36:16)
     [exec]     at Object.<anonymous> (C:\Urban\Bit_bucket_Anthro\anthroweb\gulp\tasks\proxy.js:16:23)
     [exec]     at Module._compile (module.js:434:26)
     [exec]     at Object.Module._extensions..js (module.js:452:10)
     [exec]     at Module.load (module.js:355:32)
     [exec]     at Function.Module._load (module.js:310:12)
     [exec]     at Module.require (module.js:365:17)
     [exec]     at require (module.js:384:17)

**Comment by KenanY** [comment]
@RamuSamudrala This error message is not coming from `npm`. My guess is that you do not have permission to modify the file that you are trying to modify. I would open this issue with the module that you are having trouble with.

**Comment by snopeks** [comment]
Hello @RamuSamudrala, we haven’t heard back and we’re trying to clean up some issues. If you are running into npm errors, can you please reply and let us know? We’ll be happy to reopen if necessary.
