### ISSUE TITLE
node-gyp is not recognized as an internal or external command

### ISSUE THREAD

**Issue by panuhorsmalahti** [npm/npm#9947]
I started getting this error after updating from npm 3.3.5 to 3.3.7.

```
node-gyp is not recognized as an internal or external command
```

I'm using Windows 7 with node 4.1.1 and node 4.1.2. The error happened with both node versions.

**Comment by tsing80** [comment]
similiar problem occur when  try "npm install coffeelint", got an error "cake is not recognized as an internal or external command"

work fine on npm 3.3.6, but not on npm 3.3.7

**Comment by KenanY** [comment]
@panuhorsmalahti Is this still an issue for you?

**Comment by KenanY** [comment]
Closing as abandoned.
