### ISSUE TITLE
Fix "node command not found"

### ISSUE THREAD

**Issue by ForbesLindesay** [npm/npm#9949]
One common error people seem to get in lifecycle hooks looks like:

```
sh: node: command not found
```

Could we detect this and either:
1. Automatically fix it by using the version of node that npm is run under for all lifecycle hooks
2. or print an error telling people what the problem is and how to fix it, rather than directing them to message the package maintainers.

**Comment by Stephn-R** [comment]
Are you manually installing npm separate from nodejs?

**Comment by ForbesLindesay** [comment]
I'm not, and I don't have this error, but I get an e-mail about once every couple of weeks from someone who can't install [spawn-sync](https://www.npmjs.com/package/spawn-sync) because of this error.  My guess would be that it's caused by them installing `node` under a different name, e.g. some package managers install it as `nodejs`.

**Comment by palanichocku** [comment]
Hi, I get this error when I run: npm install. Tried updating the PATH variable of where the node executable is with no luck. The 'node' is executable by all. I am running CentOS 6.7.
sh: node: command not found
npm ERR! Linux 2.6.32-504.16.2.el6.x86_64
npm ERR! argv "/user/.nvm/versions/node/v5.8.0/bin/node" "/user/.nvm/versions/node/v5.8.0/bin/npm" "install"
npm ERR! node v5.8.0
npm ERR! npm  v3.7.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! node-sass@3.4.2 install: `node scripts/install.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the node-sass@3.4.2 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

Any pointers/help to fix this will be appreciated...Thank you.
