### ISSUE TITLE
why can't publish modules?

### ISSUE THREAD

**Issue by huboshu0819** [npm/npm#9956]
![image](https://cloud.githubusercontent.com/assets/10299842/10450065/4ff795aa-71ca-11e5-84ab-4c51136861c4.png)

**Comment by yaodongwei** [comment]
I finded this problem an hour ago

**Comment by yaodongwei** [comment]
I have tried this way to resolve it：

npm config set registry http://registry.npmjs.org  //reset your config
npm adduser

**Comment by KenanY** [comment]
@huboshu0819 Is this still an issue for you?

**Comment by KenanY** [comment]
Closing as abandoned.
