### ISSUE TITLE
Tried installing grunt with cmd npm install grunt and got the following msg

### ISSUE THREAD

**Issue by githubjack** [npm/npm#9960]
Attempt to unlock /usr/local/bin/node_modules/grunt, which hasn't been locked

**Comment by KenanY** [comment]
@githubjack Could you please upload the _full_ `npm-debug.log` as a [gist](https://gist.github.com/) rather than simply pasting a single line?

**Comment by githubjack** [comment]
Hi Kenan
Please find attached the npm.debug.log


Cheers.

**Comment by KenanY** [comment]
@githubjack GitHub does not allow you to attach documents when you are replying via email. Please just use gist.github.com as I suggested.

**Comment by KenanY** [comment]
@githubjack Thanks. Looks like a permissions issue. Could you try running the following:

``` sh
sudo chown -R $(whoami) "$HOME/.npm"
```

**Comment by githubjack** [comment]
Hi Kenan
From which directory e.g usr or usr/local or usr/local/bin

**Comment by KenanY** [comment]
@githubjack You should be able to run that command from any directory.

**Comment by githubjack** [comment]
OK I tried that and got this returned.

--------------------------------------------------

ld-yalap:bin jack$ npm install grunt

grunt@0.4.5 node_modules/grunt

├── eventemitter2@0.4.14

├── dateformat@1.0.2-1.2.3

├── which@1.0.9

├── getobject@0.1.0

├── async@0.1.22

├── colors@0.6.2

├── lodash@0.9.2

├── rimraf@2.2.8

├── hooker@0.2.3

├── grunt-legacy-util@0.2.0

├── exit@0.1.2

├── coffee-script@1.3.3

├── iconv-lite@0.2.11

├── nopt@1.0.10 (abbrev@1.0.7)

├── underscore.string@2.2.1

├── minimatch@0.2.14 (sigmund@1.0.1, lru-cache@2.7.0)

├── glob@3.1.21 (inherits@1.0.2, graceful-fs@1.2.3)

├── grunt-legacy-log@0.1.2 (grunt-legacy-log-utils@0.1.1, lodash@2.4.2,
underscore.string@2.3.3)

├── findup-sync@0.1.3 (lodash@2.4.2, glob@3.2.11)

└── js-yaml@2.0.5 (esprima@1.0.4, argparse@0.1.16)

-----------------------------------------------------------------------------

So I guess I have grunt installed.

**Comment by KenanY** [comment]
@githubjack Yup, I do not see an error there! :)

**Comment by snopeks** [comment]
hello @githubjack Since it looks like this error is resolved, I'm going to close this issue :)

**Comment by githubjack** [comment]
Thank you
