### ISSUE TITLE
I see the old npm vesion in Git Bash

### ISSUE THREAD

**Issue by stefano2** [npm/npm#9962]
I have Windows 7, and have upgraded npm to version 2.14.4 to 3.3.6
If I check the version in Windows Command Prompt I see the correct one.
But if I check it in Git Bash it give me the old version 2.14.4

Can be conseguence of a bad upgrade process?

I followed the instructions in
https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows
**but with a difference:** after editing PATH as explained in Option 1, I didn't find the folder npm in %appdata%\npm\node_modules\

So before doing the second step I installed npm with `npm install -g npm@latest` and then the npm folder appeared. So I copied the npmrc file there, as described in the second step, but I had to overwrite the existing npmrc.

Finally, I restarted Windows.

**Comment by jakub-g** [comment]
Run this in git bash
`which npm`

And this in cmd
`where npm`

What is the output?

**Comment by stefano2** [comment]
in Git Bash:
`/c/Program Files/nodejs/npm`

in cmd:
```
C:\Program Files\nodejs\npm
C:\Program Files\nodejs\npm.cmd
D:\Users\stefo\AppData\Roaming\npm\npm
D:\Users\stefo\AppData\Roaming\npm\npm.cmd
```
it's right that I still have the old npm in C?

**Comment by jakub-g** [comment]
When you install nodejs, it ships with npm. Nodejs by default goes to C:\program files\.
Then to upgrade npm you issued `npm install -g npm`, and the npm installed the new version of itself in `D:\Users\...` (npm installed npm as a global module, in folder chosen as described in http://stackoverflow.com/a/27298237/245966)

Now, it seems that both those folders are in `PATH`, but git bash and cmd have a slightly different way of enumeration of those `PATH` items (not sure what the exact issue is but I've seen this behavior already).

To fix the issue you either delete `npm` and `npm.cmd` from `c:\program files\nodejs`, or add `D:\Users\stefo\AppData\Roaming\npm` somwhere at the beginning of the `PATH`

**Comment by stefano2** [comment]
Fixed, thanks.

In `PATH`, I replaced `%appdata%\npm` with `D:\Users\stefo\AppData\Roaming\npm`

Now both Git Bash and Cmd give me the same path list:

```
D:\Users\stefo\AppData\Roaming\npm\npm
D:\Users\stefo\AppData\Roaming\npm\npm.cmd
C:\Program Files\nodejs\npm
C:\Program Files\nodejs\npm.cmd
```
