### ISSUE TITLE
with latest node 4.2.1 and npm 3.3.8, I still encounter crash from youtube

### ISSUE THREAD

**Issue by leandroong** [npm/npm#9963]
Crash is intermittent. normally crash while playing youtube, during maximize screen and minimize screen. Error resulted with firefox screen whitens, nothing displayed, sound is still playing.
BTW, i'm using dispatch-proxy, utilizing both 2.4Ghz and 5Ghz connections on my router.

**Comment by KenanY** [comment]
@leandroong Could you expand on how this is an issue with `npm`?

**Comment by leandroong** [comment]
After re-examination, the problem turn out to be the latest firefox 64 bit version, switching to firefox 32bit with same latest version works without any issue. You may close this issue.

**Comment by othiym23** [comment]
Closing as not an issue with npm itself. Thanks for the assist, @KenanY!
