### ISSUE TITLE
Node 4.2.1 installs npm with a invalid package.json for at least one dependency.

### ISSUE THREAD

**Issue by waynebloss** [npm/npm#9965]
Every installation of Node v4.2.1 that I've looked at contains invalid JSON in the file `$node-root$/lib/node_modules/npm/node_modules/graceful-fs/package.json`. The contents of that file are shown below. You can see that the `version` and `repository` fields are repeated in the root object.

I have tried installing v4.2.1 with and without using `nvm` on multiple operating systems (Ubuntu 14, Windows 10, OS X Yosemite) and it is the same each time.

**UPDATE:** Here is the full list of duplicated root keys:

- engines
- gitHead
- bugs
- homepage
- _id
- _shasum
- _from
- _npmVersion
- _nodeVersion
- _npmUser
- dist
- repository
- version

*Contents of `graceful-fs/package.json` that gets installed with npm*:
```json
{
  "_args": [
    [
      "graceful-fs@latest",
      "/Users/isaacs/dev/npm/npm"
    ]
  ],
  "_from": "graceful-fs@latest",
  "_id": "graceful-fs@4.1.2",
  "_inCache": true,
  "_location": "/graceful-fs",
  "_nodeVersion": "2.2.1",
  "_npmUser": {
    "email": "isaacs@npmjs.com",
    "name": "isaacs"
  },
  "_npmVersion": "3.0.0",
  "_phantomChildren": {},
  "_requested": {
    "name": "graceful-fs",
    "raw": "graceful-fs@latest",
    "rawSpec": "latest",
    "scope": null,
    "spec": "latest",
    "type": "tag"
  },
  "_requiredBy": [
    "/"
  ],
  "_shasum": "fe2239b7574972e67e41f808823f9bfa4a991e37",
  "_shrinkwrap": null,
  "_spec": "graceful-fs@latest",
  "_where": "/Users/isaacs/dev/npm/npm",
  "bugs": {
    "url": "https://github.com/isaacs/node-graceful-fs/issues"
  },
  "dependencies": {},
  "description": "A drop-in replacement for fs, making various improvements.",
  "version": "3.0.8",
  "repository": {
    "type": "git",
    "url": "git://github.com/isaacs/node-graceful-fs.git"
  },
  "main": "graceful-fs.js",
  "engines": {
    "node": ">=0.4.0"
  },
  "directories": {
    "test": "test"
  },
  "dist": {
    "shasum": "fe2239b7574972e67e41f808823f9bfa4a991e37",
    "tarball": "http://registry.npmjs.org/graceful-fs/-/graceful-fs-4.1.2.tgz"
  },
  "engines": {
    "node": ">=0.4.0"
  },
  "files": [
    "fs.js",
    "graceful-fs.js",
    "legacy-streams.js",
    "polyfills.js"
  ],
  "gitHead": "c286080071b6be9aa9ba108b0bb9b44ff122926d",
  "homepage": "https://github.com/isaacs/node-graceful-fs#readme",
  "keywords": [
    "fs",
    "module",
    "reading",
    "retry",
    "retries",
    "queue",
    "error",
    "errors",
    "handling",
    "EMFILE",
    "EAGAIN",
    "EINVAL",
    "EPERM",
    "EACCESS"
  ],
  "license": "ISC",
  "devDependencies": {
    "mkdirp": "^0.5.0",
    "rimraf": "^2.2.8",
    "tap": "^1.2.0"
  },
  "gitHead": "45c57aa5e323c35a985a525de6f0c9a6ef59e1f8",
  "bugs": {
    "url": "https://github.com/isaacs/node-graceful-fs/issues"
  },
  "homepage": "https://github.com/isaacs/node-graceful-fs#readme",
  "_id": "graceful-fs@3.0.8",
  "_shasum": "ce813e725fa82f7e6147d51c9a5ca68270551c22",
  "_from": "graceful-fs@>=3.0.8 <3.1.0",
  "_npmVersion": "2.10.1",
  "_nodeVersion": "2.0.1",
  "_npmUser": {
    "name": "isaacs",
    "email": "isaacs@npmjs.com"
  },
  "dist": {
    "shasum": "ce813e725fa82f7e6147d51c9a5ca68270551c22",
    "tarball": "http://registry.npmjs.org/graceful-fs/-/graceful-fs-3.0.8.tgz"
  },
  "maintainers": [
    {
      "name": "isaacs",
      "email": "i@izs.me"
    }
  ],
  "name": "graceful-fs",
  "optionalDependencies": {},
  "repository": {
    "type": "git",
    "url": "git+https://github.com/isaacs/node-graceful-fs.git"
  },
  "scripts": {
    "test": "node test.js | tap -"
  },
  "version": "4.1.2"
}
```

I'm not actually sure if duplicate keys makes the JSON invalid because I didn't finish reading the [conversation here](https://esdiscuss.org/topic/json-duplicate-keys) to find out the conclusion. However, it's breaking one of the tools that I use which basically rummages through all of the globally installed packages and apparently their dependencies. Also, I'm not sure if this belongs here or with [nodejs/node](https://github.com/nodejs/node) but I will certainly be glad to post it over there if anyone asks. Thanks.

**Comment by waynebloss** [comment]
Also, I (being naive about how `npm` is built/installed) thought it was weird that when I do `npm install graceful-fs`, my local `node_modules/graceful-fs` folder does not contain the same `package.json` file contents as shown above. Instead, it contains the following valid JSON:

```json
{
  "name": "graceful-fs",
  "description": "A drop-in replacement for fs, making various improvements.",
  "version": "4.1.2",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/isaacs/node-graceful-fs.git"
  },
  "main": "graceful-fs.js",
  "engines": {
    "node": ">=0.4.0"
  },
  "directories": {
    "test": "test"
  },
  "scripts": {
    "test": "node test.js | tap -"
  },
  "keywords": [
    "fs",
    "module",
    "reading",
    "retry",
    "retries",
    "queue",
    "error",
    "errors",
    "handling",
    "EMFILE",
    "EAGAIN",
    "EINVAL",
    "EPERM",
    "EACCESS"
  ],
  "license": "ISC",
  "devDependencies": {
    "mkdirp": "^0.5.0",
    "rimraf": "^2.2.8",
    "tap": "^1.2.0"
  },
  "files": [
    "fs.js",
    "graceful-fs.js",
    "legacy-streams.js",
    "polyfills.js"
  ],
  "gitHead": "c286080071b6be9aa9ba108b0bb9b44ff122926d",
  "bugs": {
    "url": "https://github.com/isaacs/node-graceful-fs/issues"
  },
  "homepage": "https://github.com/isaacs/node-graceful-fs#readme",
  "_id": "graceful-fs@4.1.2",
  "_shasum": "fe2239b7574972e67e41f808823f9bfa4a991e37",
  "_from": "graceful-fs@*",
  "_npmVersion": "3.0.0",
  "_nodeVersion": "2.2.1",
  "_npmUser": {
    "name": "isaacs",
    "email": "isaacs@npmjs.com"
  },
  "dist": {
    "shasum": "fe2239b7574972e67e41f808823f9bfa4a991e37",
    "tarball": "http://registry.npmjs.org/graceful-fs/-/graceful-fs-4.1.2.tgz"
  },
  "maintainers": [
    {
      "name": "isaacs",
      "email": "i@izs.me"
    }
  ],
  "_resolved": "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.1.2.tgz"
}
```

**Comment by iarna** [comment]
Looks like a bad merge in 022691a introduced this

**Comment by iarna** [comment]
You didn't get the same, bad graceful-fs package.json because npm includes a copy of it in its distribution (npm bundles all of its modules, so that you don't need npm to install npm), and it's npm's copy that's broken, not the version on the registry.

**Comment by iarna** [comment]
(And you got the right place! We'll fix it here and push it over to the node folks as part of our usual release process.)

**Comment by waynebloss** [comment]
@iarna Thanks for explaining all the details! I wasn't thinking hard enough about that one :smile:

**Comment by waynebloss** [comment]
Oh, also I wanted to warn you that those may not be the only duplicate keys - just the ones I detected visually. I'm busy now trying to find a good way to validate JSON that also detects duplicate keys.

**Comment by waynebloss** [comment]
I updated the issue with the full list of duplicate keys. Here's the code I used to find them, although it's python so probably not much use. I just entered it into the REPL

```python
import json
json.dupes = ''
s = '{"json": "with dupe keys", "json": "no linebreaks"}'
def json_checker(seq):
	d = {}
	for key, value in seq:
		if key in d:
			json.dupes += ',' + key
		else:
			d[key]=value
	return d
json.loads(s, object_pairs_hook=json_checker)
```

**Comment by othiym23** [comment]
Fixing this is waiting on a new `npm@2` release, because it's basically fixing up an error with the packaging rather than a bug in the code itself.

**Comment by cjmackenzie40** [comment]
Is there a workaround I can use? I'm a beginner "Getting Started" with Ionic and I've fallen at the first hurdle because of this. http://stackoverflow.com/questions/33342983/error-reading-package-graceful-fs-package-json

**Comment by waynebloss** [comment]
@cjmackenzie40 Just open the file at %AppData%\npm\node_modules\npm\node_modules\graceful-fs\package.json and remove all of the duplicate keys that I listed.

**Comment by boyney123** [comment]
I'm having the same issues. All my packages on my AWS instance have this kind of format. 

Didn't really think that was a valid package.json file format?

Having similar issues with newrelic module.

**Comment by iarna** [comment]
Oooh, so a fix for this finally went out, you can find it in 2.14.11!
