### ISSUE TITLE
npm v3 / multi-stage install does not install child dependencies within parent folders

### ISSUE THREAD

**Issue by ericsoco** [npm/npm#9967]
`npm@3` installs all child dependencies in their own folders directly within `node_modules` instead of nesting within their parent folders. This is a change from previous versions of npm. I guess if we can still `npm uninstall` successfully it doesn't really matter, but it surprised me to see this.

This is probably intended and documented somewhere, but I've been having trouble finding that documentation. Please feel free to close this if you can provide more information. Thanks!

**Comment by othiym23** [comment]
This is one of `npm@3`'s banner features, and is discussed in the [`npm@3.0.0` release notes](https://github.com/npm/npm/blob/master/CHANGELOG.md#flat-flat-flat), which, being attached to a beta release, maybe not everybody saw. You might also want to listen to [the episode of JavaScript Jabber](https://devchat.tv/js-jabber/174-jsj-npm-3-with-rebecca-turner-and-forrest-norvell) where we go over the whys and wherefores of `npm@3`, as that goes into the motivation for the change quite a bit more. Short answer: Windows. Longer answer: potentially major disk space savings. And yes, `npm uninstall <parentdep>` will clean up any dangling dependencies.

**Comment by ericsoco** [comment]
Thanks for the links! Cheers on the release. Good stuff.
