### ISSUE TITLE
npm install fails due to phantomjs and "node install.js" 

### ISSUE THREAD

**Issue by sindhu732** [npm/npm#9969]
>C:\Users\Dell\mriob>npm install
>npm WARN package.json mean@0.5.5 No license field.
>/
> phantomjs@1.9.18 install C:\Users\Dell\mriob\node_modules\phantomjs
> node install.js

>Looks like an `npm install -g` on windows; unable to check for already installed version.
>Download already available at C:\Users\Dell\AppData\Local\Temp\phantomjs\phantom
>js-1.9.8-windows.zip
>Extracting zip contents
>Error extracting zip
>Phantom installation failed Invalid or unsupported zip format. No END header found undefined

>npm ERR! Windows_NT 6.1.7601
>npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
>npm ERR! node v4.2.1
>npm ERR! npm  v2.14.7
>npm ERR! code ELIFECYCLE
>npm ERR! phantomjs@1.9.18 install: `node install.js`
>npm ERR! Exit status 1
>npm ERR!
>npm ERR! Failed at the phantomjs@1.9.18 install script 'node install.js'.
>npm ERR! This is most likely a problem with the phantomjs package,
>npm ERR! not with npm itself.
>npm ERR! Tell the author that this fails on your system:
>npm ERR!     node install.js
>npm ERR! You can get their info via:
>npm ERR!     npm owner ls phantomjs
>npm ERR! There is likely additional logging output above.

>npm ERR! Please include the following file with any support request:
>npm ERR!     C:\Users\Dell\mriob\npm-debug.log

I tried installing phantomjs using "npm install -g phantomjs". This happens perfectly. But, when I run "npm install" inside the MEAN stack folder "mriob", I get this error.

I tried deleting the phantomjs zip file in temp and then ran "npm install". Same error.

**Comment by laylaaitlaaraj** [comment]
Hi,

Am encountering the same issue, did you find any solution?

**Comment by sindhu732** [comment]
Try letting "npm install" run completely..

**Comment by LukeSkyw** [comment]
Hi Sindhu,
What do you mean by "run completely" ? If you do that it fails on `node install.js` indeed.

**Comment by sindhu732** [comment]
Hey,
I meant even if you see the errors..dont press ctrl+C and stop the
execution. It might repair itself if you let it continue executing.

Make sure you installed gulp, etc as mentioned in mean.io installation page

**Comment by joeldeval** [comment]
any solution?

**Comment by sindhu732** [comment]
Install phantom using "npm install phantom --save" then do npm install again

**Comment by mendirattanishant** [comment]
@sindhu732  Did that work for you??

**Comment by sindhu732** [comment]
Yes. It has worked multiple times.

**Comment by sarabs3** [comment]
I have faced the same issue on windows 8. Is there any solution for this ?

**Comment by sindhu732** [comment]
Check if you have Visual Studio installed. Then run npm install and dont
interrupt it.

**Comment by naoyeye** [comment]
`npm install phantom --save`

**Comment by bellangerq** [comment]
`npm install phantom --save` worked for me!

**Comment by KenanY** [comment]
Closing as resolved.
