### ISSUE TITLE
Doesn’t exit

### ISSUE THREAD

**Issue by tomekwi** [npm/npm#9971]
Hi,

we’re struggling with a peculiar problem since a couple of days. On our dev machines `npm install --verbose` works alright – but on our CI server it hangs after `npm verb exit [ 0, true ]`:

```sh
$ node --version
v4.2.1

$ npm --version
2.14.7

$ npm install --verbose
# Loads and loads of output.
# A correct dependency tree.
npm verb exit [ 0, true ]
```

`npm info ok` never comes – and the command never exits. It just hangs forever.

Let me know what info you need in addition to the above.

(CC: @chripo)

**Comment by tomekwi** [comment]
The issue happens on multiple projects. They’re all closed-source – but I can post part of the `package.json` files if you need them.

**Comment by tomekwi** [comment]
This happens on our open-source projects as well. For example, this fails to exit (a project with multiple dependencies, some of them nested):

```sh
git clone git@github.com:studio-b12/tape-css \
&& cd tape-css \
&& git checkout 01d53067cfc3472734a3c9aa96810d0070799fca \
&& npm install npm@3.3.6 \
&& node_modules/.bin/npm install --verbose --production \
&& echo 'OK!'
# …
# npm verb exit [ 0, true ]
# (Hangs forever.)
```

These both work though (first project without dependencies, the other one with one simple shallow dependency):

```sh
git clone git@github.com:studio-b12/array-from \
&& cd array-from \
&& git checkout 3919ca3956b1bf35eebfda28039a87717d85f435 \
&& npm install npm@3.3.6 \
&& node_modules/.bin/npm install --verbose --production \
&& echo 'OK!'
# …
# npm verb exit [ 0, true ]
# npm info ok
# OK!
```

```sh
git clone git@github.com:tomekwi/virtual-dom-lite \
&& cd virtual-dom-lite \
&& git checkout 1f70eac9a73ea89f75f963a10d60b1fb63a82324 \
&& npm install npm@3.3.6 \
&& node_modules/.bin/npm install --verbose --production \
&& echo 'OK!'
# …
# npm verb exit [ 0, true ]
# npm info ok
# OK!
```

We can’t reproduce the error outside the CI server. Do you know where it might lie?

**Comment by chripo** [comment]
node is compiled from source (gentoo)
CFLAGS="-march=native -O2 -fno-reorder-blocks -fno-reorder-functions -pipe -w"
LDFLAGS="-Wl,-O1,--as-needed"
those issues occur for nodejs 4.1.1 and 4.2.1 too.

**Comment by othiym23** [comment]
@tomekwi What kernel, distribution, and containerization versions are you using? Until the CLI team can reproduce this, we're not going to be able to offer any insight (I tried your test cases, and they all exited without issue for me).

**Comment by tomekwi** [comment]
@othiym23 thanks for your response!

I have to pass your question on to @chripo – he administers the CI server.

**Comment by tomekwi** [comment]
We’ve found out that the error is caused by wrong compiler flags in Gentoo repositories. @chripo has passed the issue further.

Thanks again. Cheers!

**Comment by chripo** [comment]
the issues occur with libuv-1.7.0

**Comment by wouterds** [comment]
I have the same issue on Mac OS X El Capitan with Node v4.1.1 and npm 2.14.4.

**Comment by g13013** [comment]
Have this issue with these conditions
 - Windows 
 - ruby's `Open3` via rake task
 - `loglevel` other than `error`

if I use loglevel=error everything works great

node `v4.2.3`
npm `2.14.7`
