### ISSUE TITLE
Curious question, dispatch-proxy not displaying correct version

### ISSUE THREAD

**Issue by leandroong** [npm/npm#9972]
dispatch-proxy site: https://github.com/Morhaus/dispatch-proxy
It is stated that package.json version is 0.1.3. When I check version, using syntax "dispatch -V", it shows 0.1.2 only. Is this an npm issue ?

**Comment by KenanY** [comment]
@leandroong Maybe you have `0.1.2` installed?

**Comment by leandroong** [comment]
during installation, "npm install -g dispatch-proxy", I saw version 0.1.3 being installed. Only issue "dispatch -V" not displaying correct version, I think ...

**Comment by leandroong** [comment]
i even tried installing it using "npm install -g dispatch-proxy@0.1.3", same result

**Comment by KenanY** [comment]
@leandroong Oh, this is `dispatch-proxy`'s fault:

https://github.com/Morhaus/dispatch-proxy/blob/7259ae27228fc82e7931e8a6dc84bcb5fcbb6ad5/src/index.coffee#L27

**Comment by leandroong** [comment]
ok, thanks.
