### ISSUE TITLE
can not update npm to 3.x version

### ISSUE THREAD

**Issue by littlee** [npm/npm#9973]
my current version of npm is 2.14.3 on window 7 x64

npm install -g npm failed

**Comment by fundon** [comment]
`nam i npm@next -g`

**Comment by KenanY** [comment]
@littlee Not enough information to give a definitive answer. Is there an `npm-debug.log` that you can upload as a [gist](https://gist.github.com/)?

**Comment by eppsilon** [comment]
You might try using [npm-windows-upgrade](https://www.npmjs.com/package/npm-windows-upgrade).

**Comment by littlee** [comment]
npm i npm@next -g works

**Comment by KenanY** [comment]
@littlee `latest` does not equal `next`. https://docs.npmjs.com/cli/dist-tag

**Comment by KenanY** [comment]
This seems resolved to me. Let me know if it isn't and I'll gladly reopen.
