### ISSUE TITLE
Having issues installing Braintree

### ISSUE THREAD

**Issue by mstrdlo** [npm/npm#9975]
I've updated my latest version of node.js and trying to install braintree and getting the following errors.

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   'braintree-web' ]
2 info using npm@2.14.7
3 info using node@v4.2.1
4 verbose install initial load of D:\Visual Studio\Visual Studio 2013\Projects\ZR\Braintree\package.json
5 verbose readDependencies loading dependencies from D:\Visual Studio\Visual Studio 2013\Projects\ZR\Braintree\package.json
6 silly cache add args [ 'braintree-web', null ]
7 verbose cache add spec braintree-web
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'braintree-web',
8 silly cache add   scope: null,
8 silly cache add   name: 'braintree-web',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed braintree-web@*
10 verbose addNamed "*" is a valid semver range for braintree-web
11 silly addNameRange { name: 'braintree-web', range: '*', hasData: false }
12 silly mapToRegistry name braintree-web
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/braintree-web
16 verbose addNameRange registry:https://registry.npmjs.org/braintree-web not in flight; fetching
17 verbose request uri https://registry.npmjs.org/braintree-web
18 verbose request no auth needed
19 info attempt registry request try #1 at 3:26:26 PM
20 verbose request id f9226657f8dc20bb
21 http request GET https://registry.npmjs.org/braintree-web
22 info retry will retry, error on last attempt: Error: write EPROTO
23 info attempt registry request try #2 at 3:26:37 PM
24 http request GET https://registry.npmjs.org/braintree-web
25 info retry will retry, error on last attempt: Error: write EPROTO
26 info attempt registry request try #3 at 3:27:37 PM
27 http request GET https://registry.npmjs.org/braintree-web
28 verbose stack Error: write EPROTO
28 verbose stack     at Object.exports._errnoException (util.js:874:11)
28 verbose stack     at exports._exceptionWithHostPort (util.js:897:20)
28 verbose stack     at WriteWrap.afterWrite (net.js:763:14)
29 verbose cwd D:\Visual Studio\Visual Studio 2013\Projects\ZR\Braintree
30 error Windows_NT 6.1.7601
31 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "braintree-web"
32 error node v4.2.1
33 error npm  v2.14.7
34 error code EPROTO
35 error errno EPROTO
36 error syscall write
37 error write EPROTO
38 error If you need help, you may report this error at:
38 error     <https://github.com/npm/npm/issues>
39 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@mstrdlo Are you still experiencing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
