### ISSUE TITLE
Error: connect ECONNREFUSED 185.31.18.162:443

### ISSUE THREAD

**Issue by khusamov** [npm/npm#9977]
khusamov@cardinal:~/workspace (master) $ npm publish
npm ERR! publish Failed PUT undefined
npm ERR! Linux 3.14.13-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v4.1.2/bin/node" "/home/ubuntu/.nvm/versions/node/v4.1.2/bin/npm" "publish"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.4
npm ERR! code ECONNREFUSED
npm ERR! errno ECONNREFUSED
npm ERR! syscall connect

npm ERR! Error: connect ECONNREFUSED 185.31.18.162:443
npm ERR!     at Object.exports._errnoException (util.js:849:11)
npm ERR!     at exports._exceptionWithHostPort (util.js:872:20)
npm ERR!     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1060:14)
npm ERR!  { [Error: connect ECONNREFUSED 185.31.18.162:443]
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   syscall: 'connect',
npm ERR!   address: '185.31.18.162',
npm ERR!   port: 443 }
npm ERR! 
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly.  See: 'npm help config'

Content of file npm-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ '/home/ubuntu/.nvm/versions/node/v4.1.2/bin/node',
1 verbose cli   '/home/ubuntu/.nvm/versions/node/v4.1.2/bin/npm',
1 verbose cli   'publish' ]
2 info using npm@2.14.4
3 info using node@v4.1.2
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec Result {
7 silly cache add   raw: '.',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: '/home/ubuntu/workspace',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory /home/ubuntu/.npm/cardinalkeeper/0.0.4/package.tgz not in flight; packing
9 verbose tar pack [ '/home/ubuntu/.npm/cardinalkeeper/0.0.4/package.tgz',
9 verbose tar pack   '/home/ubuntu/workspace' ]
10 verbose tarball /home/ubuntu/.npm/cardinalkeeper/0.0.4/package.tgz
11 verbose folder /home/ubuntu/workspace
12 info prepublish cardinalkeeper@0.0.4
13 verbose addLocalTarball adding from inside cache /home/ubuntu/.npm/cardinalkeeper/0.0.4/package.tgz
14 silly cache afterAdd cardinalkeeper@0.0.4
15 verbose afterAdd /home/ubuntu/.npm/cardinalkeeper/0.0.4/package/package.json not in flight; writing
16 verbose afterAdd /home/ubuntu/.npm/cardinalkeeper/0.0.4/package/package.json written
17 silly publish { description: 'Cardinal Keeper 2015',
17 silly publish   author: { name: 'Khusamov Sukhrob', email: 'khusamov@yandex.ru' },
17 silly publish   name: 'cardinalkeeper',
17 silly publish   version: '0.0.4',
17 silly publish   main: 'cardinalkeeper.js',
17 silly publish   repository:
17 silly publish    { type: 'git',
17 silly publish      url: 'git+https://bitbucket.org/khusamov/cardinal.git' },
17 silly publish   engines: { node: '~4.1.2' },
17 silly publish   dependencies:
17 silly publish    { 'jsymfony-autoload': '~0.0.1',
17 silly publish      'pg-monitor': '~0.3.2',
17 silly publish      'pg-promise': '~1.10.6',
17 silly publish      express: '~4.13.3',
17 silly publish      'express-resource': '~1.0.0',
17 silly publish      'body-parser': '~1.14.0',
17 silly publish      ini: '~1.3.4',
17 silly publish      'multi-ini': '~0.5.2',
17 silly publish      pretty: '~1.0.0' },
17 silly publish   bugs:
17 silly publish    { url: 'https://bitbucket.org/khusamov/cardinal/issues',
17 silly publish      email: 'khusamov@yandex.ru' },
17 silly publish   readme: '<removed>',
17 silly publish   readmeFilename: 'README.md',
17 silly publish   gitHead: '0f9a274042a8e54981a4ad51a29d64d5d0bc9d04',
17 silly publish   homepage: 'https://bitbucket.org/khusamov/cardinal#readme',
17 silly publish   _id: 'cardinalkeeper@0.0.4',
17 silly publish   scripts: {},
17 silly publish   _shasum: '39816b88cbebd47bd58a221ad9359575ef10e2f7',
17 silly publish   _from: '.' }
18 verbose getPublishConfig undefined
19 silly mapToRegistry name cardinalkeeper
20 silly mapToRegistry using default registry
21 silly mapToRegistry registry https://registry.npmjs.org/
22 silly mapToRegistry uri https://registry.npmjs.org/cardinalkeeper
23 verbose publish registryBase https://registry.npmjs.org/
24 silly publish uploading /home/ubuntu/.npm/cardinalkeeper/0.0.4/package.tgz
25 verbose request uri https://registry.npmjs.org/cardinalkeeper
26 verbose request sending authorization for write operation
27 info attempt registry request try #1 at 8:42:34 PM
28 verbose request using bearer token for auth
29 verbose request id 662bebcfa545701c
30 http request PUT https://registry.npmjs.org/cardinalkeeper
31 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 23.235.43.162:443
32 info attempt registry request try #2 at 8:42:45 PM
33 verbose request using bearer token for auth
34 http request PUT https://registry.npmjs.org/cardinalkeeper
35 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 185.31.18.162:443
36 info attempt registry request try #3 at 8:43:46 PM
37 verbose request using bearer token for auth
38 http request PUT https://registry.npmjs.org/cardinalkeeper
39 verbose request invalidating /home/ubuntu/.npm/registry.npmjs.org/cardinalkeeper on PUT
40 error publish Failed PUT undefined
41 verbose stack Error: connect ECONNREFUSED 185.31.18.162:443
41 verbose stack     at Object.exports._errnoException (util.js:849:11)
41 verbose stack     at exports._exceptionWithHostPort (util.js:872:20)
41 verbose stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1060:14)
42 verbose cwd /home/ubuntu/workspace
43 error Linux 3.14.13-c9
44 error argv "/home/ubuntu/.nvm/versions/node/v4.1.2/bin/node" "/home/ubuntu/.nvm/versions/node/v4.1.2/bin/npm" "publish"
45 error node v4.1.2
46 error npm  v2.14.4
47 error code ECONNREFUSED
48 error errno ECONNREFUSED
49 error syscall connect
50 error Error: connect ECONNREFUSED 185.31.18.162:443
50 error     at Object.exports._errnoException (util.js:849:11)
50 error     at exports._exceptionWithHostPort (util.js:872:20)
50 error     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1060:14)
50 error  { [Error: connect ECONNREFUSED 185.31.18.162:443]
50 error   code: 'ECONNREFUSED',
50 error   errno: 'ECONNREFUSED',
50 error   syscall: 'connect',
50 error   address: '185.31.18.162',
50 error   port: 443 }
51 error If you are behind a proxy, please make sure that the
51 error 'proxy' config is set properly.  See: 'npm help config'
52 verbose exit [ 1, true ]

**Comment by Makadas** [comment]
did you solve this problem? I am stuck with the same error

**Comment by khusamov** [comment]
Did not solve. The next day, the problem disappeared by itself.

**Comment by KenanY** [comment]
Closing since the issue seems to have been resolved.

**Comment by RajaNataraja** [comment]
I too having the same problem, may i know how to resolve this.

**Comment by ionakathryn** [comment]
Yes I am going thru FCC backend certification and getting the same error message. How do I solve it? I try to add dist-tags and it takes a long time, then this message appears.

**Comment by Vishal-vash** [comment]
Check your system proxy and set the same as:

npm config set proxy http://127.0.0.1:3128
npm config set https-proxy http://127.0.0.1:3128

This might solve the problem

**Comment by 23garimajain** [comment]
I am facing same issue.

npm config set proxy http://127.0.0.1:3128
npm config set https-proxy http://127.0.0.1:3128

Tried this one but didn't get resolve. 

Please let me know if some one got Solution for this. 
I am facing this issue when Setting up visual Studio 2015 update 3 for node.js.  I have added package.jason, Src,bs-config.jason from quick start file into my Angular 2 Solution. After that while restore package from Package.jason.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ECONNREFUSED
npm ERR! errno ECONNREFUSED
npm ERR! syscall connect
npm ERR! Error: connect ECONNREFUSED 151.101.24.162:443
npm ERR!     at Object.exports._errnoException (util.js:1018:11)
npm ERR!     at exports._exceptionWithHostPort (util.js:1041:20)
npm ERR!     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
npm ERR!  { Error: connect ECONNREFUSED 151.101.24.162:443
npm ERR!     at Object.exports._errnoException (util.js:1018:11)
npm ERR!     at exports._exceptionWithHostPort (util.js:1041:20)
npm ERR!     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   syscall: 'connect',
npm ERR!   address: '151.101.24.162',
npm ERR!   port: 443,
npm ERR!   parent: 'angular-quickstart' }
npm ERR! 
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Please include the following file with any support request:
npm ERR!     c:\users\e3010064\documents\visual studio 2015\Projects\Angular2Demo\Angular2Demo\npm-debug.log

====npm command completed with exit code 1====

**Comment by Vishal-vash** [comment]
Check your network proxy. If you are using some proxy then replace IP above with that like 

npm config set proxy http://your proxy IP + Port
npm config set https-proxy http://your proxy IP + Port

You can see proxy Internet Options > Connection > LAN settings.

**Comment by 23garimajain** [comment]
I have checked my proxy settings through CMD and get below output 
1. npm config get proxy 
null

2. npm config get https-proxy
null

And from  internet Option > connection LAN settings 
Use a proxy server for your LAN  this checkbox is disabled.

**Comment by Vishal-vash** [comment]
If you are behind some corporate proxy can you please try steps given in https://github.com/npm/npm/issues/9401

npm config set registry http://registry.npmjs.org/ 

must resolve the issue.

**Comment by ramakrishnankv** [comment]
Anti virus scan protection could be one of the reason. I had this issue on my windows and able to solve this by disabling the virus scan protection.
