### ISSUE TITLE
sudo npm install webpack -g not working 

### ISSUE THREAD

**Issue by ashishpersistent** [npm/npm#9986]
t@v-pt-0959 /]# sudo npm install webpack -g
npm ERR! fetch failed http://registry.npmjs.org/webpack/-/webpack-1.12.2.tgz
npm ERR! Error: 403 Forbidden
npm ERR!     at WriteStream.<anonymous> (/usr/lib/node_modules/npm/lib/utils/fetch.js:58:12)
npm ERR!     at WriteStream.emit (events.js:117:20)
npm ERR!     at evalmachine.<anonymous>:1610:14
npm ERR!     at /usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:102:5
npm ERR!     at Object.oncomplete (evalmachine.<anonymous>:108:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 2.6.32-431.el6.x86_64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "webpack" "-g"
npm ERR! cwd /
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /npm-debug.log
npm ERR! not ok code 0

**Comment by skh** [comment]
That 403 error seems to have been a transient problem, the file is accessible now and installation works fine.

**Comment by KenanY** [comment]
@ashishpersistent Are you still seeing this issue?

**Comment by ashishpersistent** [comment]
No¡ now its working fine  for me
