### ISSUE TITLE
Npm connection and download problems

### ISSUE THREAD

**Issue by Smirne** [npm/npm#9987]
I have some problems with npm install. 
I receive a lot of ETIMEDOUT and ECONNRESET error. 

Sometimes node get stuck on downloading files. 
It might be due to some network problem on my enviroment, but everything else seems to be working fine. 
Is there any option to set on download and connection timeout?
```
npm info lifecycle phantomjs@1.9.18~install: phantomjs@1.9.18

> phantomjs@1.9.18 install /data/jenkins/jobs/npm-prove/node_modules/phantomjs
> node install.js

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2
Saving to /data/jenkins/jobs/npm-prove/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
Receiving...
  [=---------------------------------------] 3% 0.0s

```

**Comment by KenanY** [comment]
@Smirne Are you still experiencing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.

**Comment by Smirne** [comment]
Not in the last few months!

Michele Giacobazzi
-----------------------------
