### ISSUE TITLE
Error: Cannot find module 'npmlog'

### ISSUE THREAD

**Issue by NikosEfthias** [npm/npm#9990]
After installing node 4.1.2 precompiled node works only if i write absolute path in my case /usr/bin/node and npm gives the error on the title and quits

**Comment by KenanY** [comment]
@NikosEfthias Maybe try repairing `npm` by re-installing it through the install script?:

``` sh
curl -L https://www.npmjs.org/install.sh | sh
```

**Comment by NikosEfthias** [comment]
it doesnt work either i tried .
if i compile source code all works but precompiled packages doesnt work
![screenshot from 2015-10-15 19 17 42](https://cloud.githubusercontent.com/assets/9097437/10520145/733ebab8-7371-11e5-9bdb-685762eb5b21.png)
