### ISSUE TITLE
Flattened node_modules

### ISSUE THREAD

**Issue by aray12** [npm/npm#9994]
So I upgraded to the latest version of npm and noticed that when I run install my node_modules contains all dependencies, including my dependencies' dependencies flattened. Is this intended behavior? I thought one of the advantages of was that you have the same dependency but a different version and it would still function properly...?

Sorry if this isn't the write place to ask this. Apparently I don't have enough reputation on SO to comment on an answer...

**Comment by KenanY** [comment]
@aray12 Yes, that is one of the new features introduced in `npm@3`:

https://github.com/npm/npm/releases/tag/v3.0.0

> Your dependencies will now be installed _maximally flat_. Insofar as is possible, all of your dependencies, and their dependencies, and THEIR dependencies will be installed in your project's `node_modules` folder with no nesting. You'll only see modules nested underneath one another when two (or more) modules have conflicting dependencies.

**Comment by aray12** [comment]
@KenanY  Thanks for the response. That is an interesting optimzation
