### ISSUE TITLE
Run node api ( server hapi run with rejoice -c and json file ) with nodemon issue

### ISSUE THREAD

**Issue by kraczo** [npm/npm#9995]
Hi everybody I d'like to run api with rejoice and package.json with nodemon ( automatically restart the server api)
At the nodemon i found something like that

"If you have a package.json file for your app, you can omit the main script entirely and nodemon will read the package.json for the main property and use that value as the app" 

but that doesn't work for me, i tried to run api at my rejoice directory with 
"nodemon rejoice -c jsonfile.json and it return error below :

basedir=`dirname "$0"`
        ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

any ideas ?

**Comment by KenanY** [comment]
@kraczo I do not see how this is an issue with `npm`. I recommend you open a issue on `nodemon`'s issue tracker rather than here.

**Comment by kraczo** [comment]
Yes, you right, I already done that. 

THANKS
