### ISSUE TITLE
error @ npm install grunt-cli-g in skylinkjs

### ISSUE THREAD

**Issue by prathameshjoshi** [npm/npm#9996]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'install', 'grunt-cli-g' ]
2 info using npm@1.3.10
3 info using node@v0.10.25
4 verbose readDependencies using package.json deps
5 verbose cache add [ 'grunt-cli-g', null ]
6 verbose cache add name=undefined spec="grunt-cli-g" args=["grunt-cli-g",null]
7 verbose parsed url { protocol: null,
7 verbose parsed url   slashes: null,
7 verbose parsed url   auth: null,
7 verbose parsed url   host: null,
7 verbose parsed url   port: null,
7 verbose parsed url   hostname: null,
7 verbose parsed url   hash: null,
7 verbose parsed url   search: null,
7 verbose parsed url   query: null,
7 verbose parsed url   pathname: 'grunt-cli-g',
7 verbose parsed url   path: 'grunt-cli-g',
7 verbose parsed url   href: 'grunt-cli-g' }
8 silly lockFile ababe170-grunt-cli-g grunt-cli-g
9 verbose lock grunt-cli-g /home/prathamesh/.npm/ababe170-grunt-cli-g.lock
10 silly lockFile ababe170-grunt-cli-g grunt-cli-g
11 silly lockFile ababe170-grunt-cli-g grunt-cli-g
12 verbose addNamed [ 'grunt-cli-g', '' ]
13 verbose addNamed [ null, '*' ]
14 silly lockFile 3bb8618c-grunt-cli-g grunt-cli-g@
15 verbose lock grunt-cli-g@ /home/prathamesh/.npm/3bb8618c-grunt-cli-g.lock
16 silly addNameRange { name: 'grunt-cli-g', range: '*', hasData: false }
17 verbose url raw grunt-cli-g
18 verbose url resolving [ 'https://registry.npmjs.org/', './grunt-cli-g' ]
19 verbose url resolved https://registry.npmjs.org/grunt-cli-g
20 info trying registry request attempt 1 at 13:44:36
21 http GET https://registry.npmjs.org/grunt-cli-g
22 http 404 https://registry.npmjs.org/grunt-cli-g
23 silly registry.get cb [ 404,
23 silly registry.get   { 'content-type': 'application/json',
23 silly registry.get     'cache-control': 'max-age=0',
23 silly registry.get     'content-length': '2',
23 silly registry.get     'accept-ranges': 'bytes',
23 silly registry.get     date: 'Fri, 16 Oct 2015 08:14:37 GMT',
23 silly registry.get     via: '1.1 varnish',
23 silly registry.get     age: '0',
23 silly registry.get     connection: 'keep-alive',
23 silly registry.get     'x-served-by': 'cache-sin6927-SIN',
23 silly registry.get     'x-cache': 'MISS',
23 silly registry.get     'x-cache-hits': '0',
23 silly registry.get     'x-timer': 'S1444983277.414196,VS0,VE266' } ]
24 silly addNameRange number 2 { name: 'grunt-cli-g', range: '*', hasData: true }
25 silly addNameRange versions [ undefined, [] ]
26 error TypeError: Cannot read property 'latest' of undefined
26 error     at next (/usr/share/npm/lib/cache.js:687:35)
26 error     at /usr/share/npm/lib/cache.js:675:5
26 error     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
26 error     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
26 error     at Object.oncomplete (fs.js:107:15)
27 error If you need help, you may report this log at:
27 error     <http://github.com/isaacs/npm/issues>
27 error or email it to:
27 error     <npm-@googlegroups.com>
28 error System Linux 3.13.0-65-generic
29 error command "/usr/bin/nodejs" "/usr/bin/npm" "install" "grunt-cli-g"
30 error cwd /home/prathamesh/Software/SkyLink/skylinkjs
31 error node -v v0.10.25
32 error npm -v 1.3.10
33 error type non_object_property_load
34 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@prathameshjoshi `npm@1.3` is no longer supported. Please [upgrade `npm`](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) and [update Node.js](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-node) to versions that aren't over a year old.

**Comment by KenanY** [comment]
Closing since this version of `npm` has not been supported for a long time now. If you are still seeing this issue with `npm@2` or `npm@3`, feel free to open a new issue.
