### ISSUE TITLE
npm ERR! Linux 3.13.0-55-generic

### ISSUE THREAD

**Issue by 1303110335** [npm/npm#9998]
make: Leaving directory `/vagrant/www/nodejs/imoc/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build'
npm ERR! Linux 3.13.0-55-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "express" "jade" "moment" "mongoose"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! path ../uglify-js/bin/uglifyjs
npm ERR! code EPROTO
npm ERR! errno -71
npm ERR! syscall symlink

npm ERR! EPROTO: protocol error, symlink '../uglify-js/bin/uglifyjs' -> '/vagrant/www/nodejs/imoc/node_modules/jade/node_modules/.bin/uglifyjs'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 3.13.0-55-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "express" "jade" "moment" "mongoose"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! path npm-debug.log.96f14be3c55549e3cd52c4449920b0b5
npm ERR! code ETXTBSY
npm ERR! errno -26
npm ERR! syscall rename

npm ERR! ETXTBSY: text file is busy, rename 'npm-debug.log.96f14be3c55549e3cd52c4449920b0b5' -> 'npm-debug.log'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /vagrant/www/nodejs/imoc/npm-debug.log

**Comment by KenanY** [comment]
@1303110335 Is this Vagrant on top of Windows?

Have you tried running the command with the [`--no-bin-links`](https://docs.npmjs.com/misc/config#bin-links) flag?

**Comment by 1303110335** [comment]
it works , thanks !
