### ISSUE TITLE
[npm3] Install with a symlinked module results in lots of warnings (for no reason)

### ISSUE THREAD

**Issue by stefanr** [npm/npm#9999]
During a `npm install` all modules in `node_modules` will be analyzed to build up the ideal dependency tree ... as far as I understand ...

But this doesn't make any sense for modules that are symlinked. This is also realized by `npm` and results in a bunch of warn messages: 

```
npm WARN skippingAction Module is inside a symlinked module: not running add ...
```

So why analyzing this modules anyway? Wouldn't it make sense to filter these out in an earlier install step. Because besides being unnecessary it also takes a lot of time, depending on the size of the module of course.

**Comment by i-e-b** [comment]
This seems to result in the situation where you have module `A` which depends on `B` and `C`, and `C` also depends on `B`, with de-duplication you would expect
```
A
    B
    C
```
but if `C` is put in place by `npm link` then you get
```
A
    C
        B
```
which is non-functional.
Possibly related to https://github.com/npm/npm/issues/9689

**Comment by stefanr** [comment]
Actually I expect npm to ignore anything inside the symlinked folder because it isn't allowed to touch anything inside anyways. So the case is more like this:

I have a symlinked module called `S` and two modules called `A` and `B` which also depend on `S`. `S` is already present in `node_modules` as a symlinked folder. S if `A` and `B` are installed and the version of `S` matches the version needed by `A` and `B` it will not be installed. And since `S` is symlinked it shouldn't be inspected for de-duplication.

**Comment by tellnes** [comment]
+1 what @stefanr said. If a module is symlinked in the `node_modules`, I expect npm not to touch anything inside it.

**Comment by stevage** [comment]
This is pretty infuriating. Since upgrading to npm3, I'm now getting hundreds of lines of spam when doing any npm operation:

```
npm WARN skippingAction Module is inside a symlinked module: not running remove adm-zip@0.4.7 node_modules/terriajs/node_modules/adm-zip
npm WARN skippingAction Module is inside a symlinked module: not running remove after@0.8.1 node_modules/terriajs/node_modules/after
npm WARN skippingAction Module is inside a symlinked module: not running remove ansi-regex@2.0.0 node_modules/terriajs/node_modules/ansi-regex
...
```

The module in question (`terriajs`) was `npm link`ed the standard way - I don't think I'm doing anything that is not standard.

**Comment by jdrydn** [comment]
+1 to what @stefanr and @tellnes said - it makes building submodules a real pain and made the migration from 0.12 to 4.0 unnecessarily difficult :cry:

**Comment by philosoralphter** [comment]
+1 spam.  annoying.  not very informative.

**Comment by b-smets** [comment]
+1. Hope this gets fixed soon.

**Comment by michaeljosephrosenthal** [comment]
I wrapped npm in a filter function to avoid this problem:
```bash
function npms { #`s` for symlink
    npm $@ --color=always 2>&1 | grep -vE 'Module is inside a symlinked module'
}
```
Another helpful utility:
```bash
function npm-ls-linked-deps {
    ls -l node_modules | \
        grep ^l | \
        awk '{print $9}' | \
        sed 's/@//g';
}
```
